### ISSUE TITLE
YCbCr format confusion

### ISSUE THREAD

**Issue by Tcll** [python-pillow/Pillow#1002]
so I'm trying to figure out how to convert this format to [R,G,B], and I'm finding alot of various conversions and things and I'm extremely confused on this one...

for one, PIL's format is apparently borked:
http://stackoverflow.com/questions/7041172/pils-colour-space-conversion-ycbcr-rgb
^ the dude switches to YUV

for two, I have no idea which YCbCr format is used in pillow:
http://www.equasys.de/colorconversion.html

I think I may just skip support on this format until there's better documentation available >_>
(I understand it returns 3 values, but of what ranges)

**Comment by Shoeboxam** [comment]
This issue appears to have been resolved, but was never closed.

**Comment by aclark4life** [comment]
Thanks @Shoeboxam
