### ISSUE TITLE
IOError: cannot identify image file (StringIO and BytesIO)

### ISSUE THREAD

**Issue by Tcll** [python-pillow/Pillow#1006]
https://drive.google.com/file/d/0B1T13qYbnHNKd3JrWGRaU3BzNVk/view?usp=sharing

if this works for you, google may have converted it, and I'll have to upload it somewhere else

```
IOError: cannot identify image file <open file 'test.png', mode 'r' at 0x009A1020>
```

EDIT:
nope, it's even doing this with the test png I used earlier...
anyone know what's causing this??

EDIT2: figured it out, it's IMPORTANT to use binary modes.
with the file test, I was in a confused panic, so I forgot there...
so now I'm figuring out how to get StringIO to work here, which should fix the original issue ;)

EDIT3:
I'm about to flip a table:

```
IOError: cannot identify image file <StringIO.StringIO instance at 0x05213A58>
IOError: cannot identify image file <_io.BytesIO object at 0x054D2E70>
```

http://stackoverflow.com/questions/25116/binary-buffer-in-python

only one last thing I can think of here... and that's my string function >_<

```
return __f[__c].tostring() # __f[__c] = array( 'B', [] )
```

^ I can write the imported PNG file data (__f[__c]) to a new PNG file with no problems (everything is the same)
in fact, that's exactly what that test.png upload is (first post), a binary copy from my system:

```
f = open('test.png','wb'); f.write( string(0) ); f.close()
```

string(0) >>> __f[__c].tostring()
I don't understand why StringIO and BytesIO cause PIL to cough when that works perfectly

**Comment by beyondlex** [comment]
I got this problem when using selenium together with ImagePipeline, because every request (includes downloading the images) will get through the middleware which is using the selenium in it's process_request() method , so when trying to download an image, the selenium will open the browser with an url like 'http://site.com/hello.jpg', then we got a response like:
```html
<html><body><img src="http://site.com/hello.jpg"/></body></html>
```
Obviously, this response can not be identified as an image by Pillow. 
My solution is passing an object (like `{"from": "spider"}` ) from spider to the middleware, and in the process_request method of middleware:
```
if request is from spider: use selenium
else:  return // when downloading images, selenium should be skipped.
```
hope this helps.

**Comment by MarynaLongnickel** [comment]
Hello, Tcll. I'm getting the same error :< ... Any chance you could help me out?

```
app = Flask(__name__)


def get_model():
    global model, graph
    model = load_model('model.h5')
    print(' * Model loaded!')
    graph = tf.Graph()


def preprocess_image(image, target_size):
    if image.mode != 'RGB':
        image = image.convert('RGB')
    image = image.resize(target_size)
    image = img_to_array(image)
    image = np.expand_dims(image, axis=0)

    return image


print(' * Loading model...')
get_model()


@app.route('/predict', methods=["POST"])
def predict():
    message = request.get_json(force=True)
    encoded = message['image']
    decoded = base64.b64decode(encoded)
    with graph.as_default():
        image = Image.open(io.BytesIO(decoded))
        preprocessed_image = preprocess_image(image, target_size(50, 50))
        prediction = model.predict(preprocessed_image).tolist()

        response = {
            'prediction': {
                'food': prediction[0][0],
                'notfood': prediction[0][1]
            }
        }
    return jsonify(response)
```

**Comment by Tcll** [comment]
sorry I'm late to this...

all I can say is, check your relative installation of pillow
if you're importing from the egg/whl without extracting it, make sure you provide the full path to the egg/whl in `sys.path.append( fullpath )`
once the full path is added, the egg/whl can be imported from, and should identify other modules.
(note that the full path includes the egg/whl file itself)

if you installed the egg/whl through pip or some other installation utility, you may be better off creating a new issue for your case ;)
