### ISSUE TITLE
Image fails to save when folder does not exist.

### ISSUE THREAD

**Issue by Ep0chalypse** [python-pillow/Pillow#1036]
Hey! I just noticed that if I use ImageOps to generate a thumbnail, then go to save the thumbnail and the folder doesnt exist(I'm currently saving image/thumbnail to folders in year/month/day/). I easily fixed it in my own code using os.makedirs() before trying to save. 

I'm not sure if this is intended or not, but it would be nice to have a option to tell save() "if folder does not exist create, then save image"

My relevant bits of code:

``` python
if not os.path.exists(save_path):
            os.makedirs(save_path)
imagefit = ImageOps.fit(img, (175, 131), Image.ANTIALIAS)
imagefit.save(save_path+ save_name, 'JPEG', quality=30)
```

**Comment by nscozzaro** [comment]
It would be convenient to have an option to automatically create the directory. `create_dir = True`
