### ISSUE TITLE
PIL fails to roundtrip some TIFF images

### ISSUE THREAD

**Issue by anntzer** [python-pillow/Pillow#1039]
For some TIFF images, a simple `Image.open(path).save(path)` fails with the following:
```
_TIFFVSetField: /path/to/test.tiff: Bad value 2 for "ExtraSamples" tag.
Traceback (most recent call last):
  <elided traceback>
  File "/usr/lib/python3.4/site-packages/PIL/Image.py", line 1685, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python3.4/site-packages/PIL/TiffImagePlugin.py", line 1185, in _save
    e = Image._getencoder(im.mode, 'libtiff', a, im.encoderconfig)
  File "/usr/lib/python3.4/site-packages/PIL/Image.py", line 430, in _getencoder
    return encoder(mode, *args + extra)
RuntimeError: Error setting from dictionary
```

The image was created using Qt's `QImageWriter` (from a `QImage.Format_RBG32` image), but it is not clear how to reproduce the issue as a simple blank image created in the same way does not trigger the same issue.

**Comment by radarhere** [comment]
Is this resolved now?

**Comment by radarhere** [comment]
Testing, I find that it works in both Python 3.0.x and master. I'll close this, and anyone can request a re-open if they feel otherwise.

**Comment by wiredfool** [comment]
Pillow, I think.  

But anyway, this is part of the massive IFD overhaul, so it should be settled.

**Comment by anntzer** [comment]
Yup, I forgot what this was exactly but from my earlier descriptions this must have been fixed by the IFD rewrite.
