### ISSUE TITLE
Pillow is unable to process JPEG images

### ISSUE THREAD

**Issue by zhguokai** [python-pillow/Pillow#1057]
An error occurred when I use Pillow processing of JPEG images,, the following error message

`Traceback (most recent call last):
  File "/data/AppCode/05CodeNet/pytorando/application/test/tecdemo/imgWrit.py", line 6, in <module>
    draw = ImageDraw.Draw(img)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 299, in Draw
    return ImageDraw(im, mode)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageDraw.py", line 63, in __init__
    im.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 247, in load
    raise_ioerror(e)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
IOError: broken data stream when reading image file
`

My code is:

``` python



      # -*- coding: utf-8 -*-

     from PIL import Image,ImageDraw,ImageFont

     font = ImageFont.truetype('../simsun.ttc',88)
     img = Image.open("../result.jpg")
     draw = ImageDraw.Draw(img)
     draw.text((200,100),u'你好,世界!',(23,55,99),font = font)
     draw.text((260,140),unicode('你好','utf-8'),(678,123,234),font = font)
     img.save("jpeg.jpg",'JPEG')


```

it can correctly read the jpg image,but cant draw image,When I use PIL(imaging-1.7.1),it work correctly,

who can tell me why? and how to Solve it,thanks very munch

**Comment by iamgroot42** [comment]
For those who still can't resolve the problem, try upgrading your Pillow ( `pip install Pillow --upgrade`). I had the same problem as above which was not fixed by any of the discussed workarounds.

**Comment by arpanmodi** [comment]
Thanks @iamgroot42 , it helps!
