### ISSUE TITLE
Run OS X tests more regularly

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#1065]
Hi @wiredfool and @matthew-brett,

I just realised the [python-wheels repo](https://github.com/python-pillow/pillow-wheels), which [builds on OS X, also runs all the unit tests](https://travis-ci.org/python-pillow/pillow-wheels). Great!

I'd like to look into having tests run for OS X for commits to the main repo. That way we can be sure everything works (well, tests pass) on OS X as we go along and don't get any surprises on release day.

Two options:

1. Add OS X to the main repo builds
2. Trigger python-wheel repo builds from the main repo

I don't think (1) is possible right now as the repo must be whitelisted for OS X, and [Travis are at capacity and aren't accepting new requests for now](http://blog.travis-ci.com/2014-05-13-multi-os-feature-available/). Also, as OS X doesn't support Python out of the box, I expect it'll be difficult to mix Linux/Python with OS X/Objective-C.

So that leaves (2).

Things to do:

* [x] Trigger a python-wheels build from the main repo. Travis doesn't yet support dependent releases (e.g. python-wheels declaring it is dependent on Pillow) (see https://github.com/travis-ci/travis-ci/issues/249), but the [travis-build-children script](https://github.com/ajdm/travis-build-children) will allow Pillow to trigger a python-wheels build, which is just fine. PRs are more complex and aren't a priority: pillow-wheels would need to know from Pillow the PR's repo. Instead just building Pillow/master will do, so the trigger script only needs to be called for those Pillow builds. (If triggering is problematic, there are some solutions for daily/weekly builds.)

* [x] Have python-wheels build the latest Pillow version and not a specified release. Am I correct that we'd just need to uncomment `global: LATEST_TAG=1`? Then when making a proper release, recomment it when setting the release commit hash?

* [x] Restrict the deploy to releases. How? Travis support [conditional releases](http://docs.travis-ci.com/user/deployment/#Conditional-Releases-with-on%3A), for example, only for tags or env variables, but how can this be linked to the main repo? We could tag the python-wheels repo at the same time as the main repo for creating releases. Or, following on from the previous point, perhaps it could check `LATEST_TAG` is not set.

Thoughts? Anything I've missed? Does this sound feasible?

**Comment by wiredfool** [comment]
What about having a couple of branches in the Pillow-wheels repo -- one for release and one for nightlies, each with the appropriate settings for releasing or whatever. Then we could force a travis build on the appropriate branch either nightly or on releases, depending. 

Any work that we do can be done on master, then merged out into the working branches.

**Comment by matthew-brett** [comment]
If you turn off LATEST_TAG the repo builds the current commit of the Pillow submodule, but of course it would be easy to check out the latest master as part of the build step.

**Comment by hugovk** [comment]
Thanks both, here's a pair of PRs for this:

https://github.com/python-pillow/pillow-wheels/pull/9
https://github.com/python-pillow/Pillow/pull/1067

**Comment by hugovk** [comment]
OK, this seems to be working now.
