### ISSUE TITLE
Imagegrab from command line not working.

### ISSUE THREAD

**Issue by jrknox1977** [python-pillow/Pillow#1073]
I am running python 2.7.9 and have PIL 1.1.7 installed:

My issue is that I get this error when I try to use ImageGrab from the command line:

C:\pycode>python quickGrab.py
Traceback (most recent call last):
  File "quickGrab.py", line 1, in <module>
    from PIL import ImageGrab
  File "C:\python27\lib\site-packages\PIL\ImageGrab.py", line 31, in <module>
    grabber = Image.core.grabscreen
  File "C:\python27\lib\site-packages\PIL\Image.py", line 37, in __getattr__
    raise ImportError("The _imaging C module is not installed")
ImportError: The _imaging C module is not installed

Here is the code:

from PIL import ImageGrab
import os
import time

def screenGrab():
	box = ()
	
	# this line creates a variable to hold the screenshot
	im = ImageGrab.grab()

	# This command will save the screenshot into a time-stamped png file
	# FYI - getcwd() is get Current Working Directory
	im.save(os.getcwd() + '\\full_snap__' + str(int(time.time())) + '.png', 'PNG')

def main():
	screenGrab()

if __name__ == '__main__':
	main()

I have also tried just import ImageGrab this als odid not work.

Thanks!

**Comment by aclark4life** [comment]
Have you tried with Pillow?

**Comment by jrknox1977** [comment]
Thanks!

I installed Pillow and the same code worked as is! Awesome! 

 I am sorry I did not even realize that Pillow was actually different from PIL
(And I am still a little confused, I am assuming that pillow overwrites the old PIL's "guts" but uses the same commands/functions?)

Anyway, thanks for not just flaming me for asking an uninformed question! :)

**Comment by hugovk** [comment]
Pillow is a fork, or continuation, of the PIL project. So Pillow started off with the same code as PIL, and has added to it and fixed it.
