### ISSUE TITLE
ImageTk

### ISSUE THREAD

**Issue by bobl** [python-pillow/Pillow#1080]
An apparently trivial invocation of PIL.ImageTk.PhotoImage() is segfaulting Python (2.7.6). Given the following test program, which is in a file "``image_tk_bug_using_pillow.py``":

    import Tkinter

    import PIL
    print "PIL attributes:"
    print "       VERSION:", PIL.VERSION
    print "PILLOW_VERSION:", PIL.PILLOW_VERSION
    print "      __file__:", PIL.__file__
    print
    print "PIL.Image attributes:"
    import PIL.Image
    print "      __file__:", PIL.Image.__file__
    print "       VERSION:", PIL.Image.VERSION
    print "PILLOW_VERSION:", PIL.Image.PILLOW_VERSION
    print
    import PIL.ImageTk
    print "PIL.ImageTk attributes:"
    print "      __file__:", PIL.ImageTk.__file__
    print
    import numpy as np

    a = np.array(((0.0, 0.1),
                  (0.2, 0.3)))
    print a.shape

    root = Tkinter.Tk() # so that "PIL.ImageTk()" won't say it's "too early"
    pilImage = PIL.Image.fromarray(a)
    print(pilImage)
    photoImage = PIL.ImageTk.PhotoImage(pilImage)

Its invocation on an x64_64 Xubuntu 14.04 LTS system is:

    $ python image_tk_bug_using_pillow.py
    PIL attributes:
           VERSION: 1.1.7
    PILLOW_VERSION: 2.3.0
          __file__: /home/bobl/src/pillow/pillow-2.3.0/PIL/__init__.pyc

    PIL.Image attributes:
          __file__: /home/bobl/src/pillow/pillow-2.3.0/PIL/Image.pyc
           VERSION: 1.1.7
    PILLOW_VERSION: 2.3.0

    PIL.ImageTk attributes:
          __file__: /home/bobl/src/pillow/pillow-2.3.0/PIL/ImageTk.pyc

    (2, 2)
    <PIL.Image.Image image mode=F size=2x2 at 0x7F48BE270CF8>
    Segmentation fault (core dumped)

Having downloaded Pillow (2.3.0) from source and compiled it, gdb allows me to find the segfaulting line:

    $ gdb /usr/bin/python
    GNU gdb (Ubuntu 7.7.1-0ubuntu5~14.04.2) 7.7.1
    Copyright (C) 2014 Free Software Foundation, Inc.
    License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
    This is free software: you are free to change and redistribute it.
    There is NO WARRANTY, to the extent permitted by law.  Type "show copying"
    and "show warranty" for details.
    This GDB was configured as "x86_64-linux-gnu".
    Type "show configuration" for configuration details.
    For bug reporting instructions, please see:
    <http://www.gnu.org/software/gdb/bugs/>.
    Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.
    For help, type "help".
    Type "apropos word" to search for commands related to "word"...
    Reading symbols from /usr/bin/python...Reading symbols from /usr/lib/debug//usr/bin/python2.7...done.
    done.
    (gdb) r image_tk_bug_using_pillow.py
    Starting program: /usr/bin/python image_tk_bug_using_pillow.py
    [Thread debugging using libthread_db enabled]
    Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
    [New Thread 0x7ffff3c45700 (LWP 4141)]
    PIL attributes:
           VERSION: 1.1.7
    PILLOW_VERSION: 2.3.0
          __file__: /home/bobl/src/pillow/pillow-2.3.0/PIL/__init__.pyc

    PIL.Image attributes:
          __file__: /home/bobl/src/pillow/pillow-2.3.0/PIL/Image.pyc
           VERSION: 1.1.7
    PILLOW_VERSION: 2.3.0

    PIL.ImageTk attributes:
          __file__: /home/bobl/src/pillow/pillow-2.3.0/PIL/ImageTk.pyc

    (2, 2)
    <PIL.Image.Image image mode=F size=2x2 at 0x7FFFF62E2CF8>

    Program received signal SIGSEGV, Segmentation fault.
    0x00007ffff5b49db1 in Tk_PhotoPutBlock () from /usr/lib/x86_64-linux-gnu/libtk8.6.so
    (gdb) up
    #1  0x00007fffeef5fdae in PyImagingPhotoPut (clientdata=<optimized out>, interp=<optimized out>, argc=<optimized out>, argv=<optimized out>) at Tk/tkImaging.c:201
    201	    Tk_PhotoPutBlock(photo, &block, 0, 0, block.width, block.height,
    (gdb) p block
    $1 = {pixelPtr = 0xbbe400 "", width = 2, height = 2, pitch = 2, pixelSize = 1, offset = {0, 0, 0, 32767}}
    (gdb) list
    196	        /* Copy opaque block to photo image, and leave the rest to TK */
    197	        Tk_PhotoPutBlock(photo, &block, 0, 0, block.width, block.height);
    198	
    199	#else /* Tk 8.4 and newer */
    200	#if TK < 85 /* Tk 8.4 */
    201	    Tk_PhotoPutBlock(photo, &block, 0, 0, block.width, block.height,
    202	                     TK_PHOTO_COMPOSITE_SET);
    203	    if (strcmp(im->mode, "RGBA") == 0)
    204	        /* Tk workaround: we need apply ToggleComplexAlphaIfNeeded */
    205	        /* (fixed in Tk 8.5a3) */

This is as far as I've been able to take things. There's something funny about the Tk_PhotoPutBlock() call. Also, if I read the comments correctly, this is supposed to be invoked for Tk 8.4, but I've got Tk 8.6 installed.

"``image_tk_bug_using_pillow.py``" is a much cut-down version of code that continues to run correctly on my 32-bit Xubuntu 14.04 laptops, but which fails in the same way on the 64-bit version on my desktop.

Any ideas what's going on?

**Comment by wiredfool** [comment]
I've poked at it a bit in 14.04 -- I can't reproduce it in 2.3.0 or current master:  (this is the -dbg version, standard version is similar)
```
PIL attributes:
       VERSION: 1.1.7
PILLOW_VERSION: 2.7.0
      __file__: /home/erics/vpy27-dbg/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg/PIL/__init__.pyc

PIL.Image attributes:
      __file__: /home/erics/vpy27-dbg/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg/PIL/Image.pyc
       VERSION: 1.1.7
PILLOW_VERSION: 2.7.0

PIL.ImageTk attributes:
      __file__: /home/erics/vpy27-dbg/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg/PIL/ImageTk.pyc

(2, 2)
<PIL.Image.Image image mode=F size=2x2 at 0x7F05FD9D6BA0>
[83497 refs]
```

**Comment by bobl** [comment]
Interesting. What version of libtk do you have installed? (Mine is 8.6 from 
/usr/lib/x86_64-linux-gnu/libtk8.6.so.)

Thanks.

     - Bob Lewis

**Comment by wiredfool** [comment]
Looks like I've got 8.5 and 8.6:
```
ii  libpython3.3-tk:amd64               3.3.6-2+trusty1                  amd64        Tkinter - Writing Tk applications with Python (version 3.3)
ii  libpython3.3-tk-dbg:amd64           3.3.6-2+trusty1                  amd64        Tkinter - Writing Tk applications with Python (version 3.3 debug extension)
ii  libtk8.5:amd64                      8.5.15-2ubuntu3                  amd64        Tk toolkit for Tcl and X11 v8.5 - run-time files
ii  libtk8.6:amd64                      8.6.1-3ubuntu2                   amd64        Tk toolkit for Tcl and X11 v8.6 - run-time files
ii  pypy-tk                             2.4.0+dfsg-1~ppa2+trusty         amd64        Tkinter module for PyPy (an alternative Python interpreter)
ii  python-tk                           2.7.5-1ubuntu1                   amd64        Tkinter - Writing Tk applications with Python
ii  python-tk-dbg                       2.7.5-1ubuntu1                   amd64        Tkinter - Writing Tk applications with Python (debug extension)
ii  tk                                  8.6.0+6ubuntu3                   amd64        Toolkit for Tcl and X11 (default version) - windowing shell
ii  tk-dev:amd64                        8.6.0+6ubuntu3                   amd64        Toolkit for Tcl and X11 (default version) - development files
ii  tk8.5                               8.5.15-2ubuntu3                  amd64        Tk toolkit for Tcl and X11, v8.5 - windowing shell
ii  tk8.5-dev:amd64                     8.5.15-2ubuntu3                  amd64        Tk toolkit for Tcl and X11, v8.5 - development files
ii  tk8.6                               8.6.1-3ubuntu2                   amd64        Tk toolkit for Tcl and X11 v8.6 - windowing shell
ii  tk8.6-dev:amd64                     8.6.1-3ubuntu2                   amd64        Tk toolkit for Tcl and X11 v8.6 - development files
```

**Comment by wiredfool** [comment]
After removing tk8.5:
```
PIL attributes:
       VERSION: 1.1.7
PILLOW_VERSION: 2.7.0
      __file__: /home/erics/vpy27sys/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg/PIL/__init__.pyc

PIL.Image attributes:
      __file__: /home/erics/vpy27sys/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg/PIL/Image.pyc
       VERSION: 1.1.7
PILLOW_VERSION: 2.7.0

PIL.ImageTk attributes:
      __file__: /home/erics/vpy27sys/local/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-linux-x86_64.egg/PIL/ImageTk.pyc

(2, 2)
<PIL.Image.Image image mode=F size=2x2 at 0x7F1FE9411C20>
(vpy27sys)erics@builder-1404-x64:~/tk$ dpkg -l |grep tk
ii  libpython3.3-tk:amd64               3.3.6-2+trusty1                  amd64        Tkinter - Writing Tk applications with Python (version 3.3)
ii  libpython3.3-tk-dbg:amd64           3.3.6-2+trusty1                  amd64        Tkinter - Writing Tk applications with Python (version 3.3 debug extension)
ii  libtk8.5:amd64                      8.5.15-2ubuntu3                  amd64        Tk toolkit for Tcl and X11 v8.5 - run-time files
ii  libtk8.6:amd64                      8.6.1-3ubuntu2                   amd64        Tk toolkit for Tcl and X11 v8.6 - run-time files
ii  pypy-tk                             2.4.0+dfsg-1~ppa2+trusty         amd64        Tkinter module for PyPy (an alternative Python interpreter)
ii  python-tk                           2.7.5-1ubuntu1                   amd64        Tkinter - Writing Tk applications with Python
ii  python-tk-dbg                       2.7.5-1ubuntu1                   amd64        Tkinter - Writing Tk applications with Python (debug extension)
ii  tk                                  8.6.0+6ubuntu3                   amd64        Toolkit for Tcl and X11 (default version) - windowing shell
ii  tk-dev:amd64                        8.6.0+6ubuntu3                   amd64        Toolkit for Tcl and X11 (default version) - development files
rc  tk8.5                               8.5.15-2ubuntu3                  amd64        Tk toolkit for Tcl and X11, v8.5 - windowing shell
ii  tk8.6                               8.6.1-3ubuntu2                   amd64        Tk toolkit for Tcl and X11 v8.6 - windowing shell
ii  tk8.6-dev:amd64                     8.6.1-3ubuntu2                   amd64        Tk toolkit for Tcl and X11 v8.6 - development files
```

**Comment by aclark4life** [comment]
Assuming fixed or non-issue
