### ISSUE TITLE
Ability to set duration in gifmaker script

### ISSUE THREAD

**Issue by cancan101** [python-pillow/Pillow#1084]
Add ability to set `duration` in the [gifmaker](https://github.com/python-pillow/Pillow/blob/54173d2c67bc8ed8953b56e67d4719676f43a073/Scripts/gifmaker.py) script.

From http://pillow.readthedocs.org/en/latest/handbook/image-file-formats.html#gif:
>**duration**
Time between frames in an animation (in milliseconds).

**Comment by cancan101** [comment]
Depends on #1085

**Comment by aclark4life** [comment]
Still an issue?
