### ISSUE TITLE
Consider implementing _repr_png_ for the Image object

### ISSUE THREAD

**Issue by payne92** [python-pillow/Pillow#1090]
Given the popularity of IPython, consider implementing a `_repr_png_()` method for the Image object, which just returns the object in PNG form.  If this method exists on an object, the IPython notebook will display the rich image representation in-line.

See: http://nbviewer.ipython.org/github/adrn/ipython/blob/1.x/examples/notebooks/Part%205%20-%20Rich%20Display%20System.ipynb

This can be done without dependency on or reference to IPython.

**Comment by wiredfool** [comment]
I've got a branch with that method in it now, (https://github.com/wiredfool/Pillow/tree/repr_png) but it does not seem to trigger iPython's display hooks. Can you give a step by step to test it, or determine what else needs to be added to make it work?

**Comment by payne92** [comment]
The method is _repr_png_() -- your implementation is missing the trailing underscore in the name.

To test in an IPytyon web notebook:

    from PIL import Image
    im = Image.new("RGB", (512, 512), "blue")
    im

IPython will attempt to render the last value.  When it finds _repr_png_(), it will render it.

**Comment by hugovk** [comment]
The problem was GitHub interpreted the underscores as italic markup. I've edited to put backticks ` to make sure it's in code markup!

**Comment by payne92** [comment]
Ah, my bad -- sorry about that.  I should have checked the preview more carefully.

**Comment by wiredfool** [comment]
Ah, much better. Works now.

**Comment by hugovk** [comment]
Implemented #1091, thanks.
