### ISSUE TITLE
Spelling error in comments of IcoImagePlugin.py  should be Flag not "Flage"

### ISSUE THREAD

**Issue by horkana** [python-pillow/Pillow#1092]
There is a comment near the end of the file
https://github.com/python-pillow/Pillow/blob/master/PIL/IcoImagePlugin.py  
 # Flage the ImageFile.Parser so that it 

Was confused at first and was wondering if "Flage" had some special meaning I wasn't aware of but thinking about it more it seemed like a spelling mistake. 
When I realised the code had been written by a German and the German word for flag is "Flagge" it became immediately clear it was definitely nothing more than a spelling mistake. 

Please fix the spelling mistake.

**Comment by wiredfool** [comment]
Thanks, fixed.

**Comment by horkana** [comment]
Thank you.
