### ISSUE TITLE
Can't install on Mac 10.10.1

### ISSUE THREAD

**Issue by computersarecool** [python-pillow/Pillow#1094]
Trying `pip3 install Pillow` returns:

	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found

	#       include <X11/Xlib.h>

	^

	In file included from _imagingtk.c:19:

	/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.10.sdk/usr/include/tk.h:78:11: fatal error: 'X11/Xlib.h' file not found

 	#       include <X11/Xlib.h>

	^

	1 error generated.

	1 error generated.

	Building using 4 processes

	/usr/bin/clang -bundle -undefined dynamic_lookup -arch i386 -arch x86_64 -g build/temp.macosx-10.6-x86_64-3.4/_imagingtk.o build/temp.macosx-10.6-x86_64-3.4/Tk/tkImaging.o -L/Library/Frameworks/Python.framework/Versions/3.4/lib -L/usr/local/lib -L/usr/X11/lib -L/usr/lib -o build/lib.macosx-10.6-x86_64-3.4/PIL/_imagingtk.so -framework Tcl -framework Tk

	clang: error: no such file or directory: 'build/temp.macosx-10.6-x86_64-3.4/_imagingtk.o'

	clang: error: no such file or directory: 'build/temp.macosx-10.6-x86_64-3.4/Tk/tkImaging.o'

	error: command '/usr/bin/clang' failed with exit status 1

Trying `easy_install-3.4 Pillow` returns:

	#       include <X11/Xlib.h>
	                ^
	#       include <X11/Xlib.h>
                ^
	1 error generated.
	1 error generated.
	clang: error: no such file or directory: 'build/temp.macosx-10.6-x86_64-3.4/_imagingtk.o'
	clang: error: no such file or directory: 'build/temp.macosx-10.6-x86_64-3.4/Tk/tkImaging.o'
	error: Setup script exited with error: command '/usr/bin/clang' failed with exit status 1

I get the same messages when I specify a version such as `pip3 install Pillow==2.7.0`

Any help would be appreciated.

**Comment by wiredfool** [comment]
What python are you using?  (System/homebrew/python.org?)

**Comment by computersarecool** [comment]
On my computer I have `Python 2.7.6` and `Python 3.4`.   I am using a Mac with `10.10.1`.  Additionally, I have tried `pip 1.5.6` and `pip 3.4`.  I am using `brew 0.9.5`

**Comment by computersarecool** [comment]
The solution was using `pip3.4 install Pillow`
