### ISSUE TITLE
Filter not applied to PNG by resize() or thumbnail()

### ISSUE THREAD

**Issue by venzen** [python-pillow/Pillow#1097]
I have Pillow 2.7.0 installed via Git master on Ubuntu 14.04. According to PIL SETUP SUMMARY all dependencies are met. When running ./test-installed.py an error "Not enough memory to handle tile data" is reported but the result is "OK (SKIP=24)"

I am able to resize JPEGs to satisfaction but when I apply resize() or thumbnail() to a PNG the result is pixelated. Whichever filter is passed there is no antialiasing or convolution evident. e.g.:

```img.thumbnail((764,500), Image.LANCZOS)```

![foo](https://cloud.githubusercontent.com/assets/6916056/6016160/2cb8b366-abb0-11e4-973b-4640352231fa.png)

**Comment by homm** [comment]
This is not because of PNG, this is because this image in 8bit palette format. Just convert to RGBA before resizing to fix this:

```python
img.convert('RGBA').thumbnail((764,500), Image.LANCZOS)
```
