### ISSUE TITLE
ICO image created does not work on XP

### ISSUE THREAD

**Issue by arsenik** [python-pillow/Pillow#1102]
I created an .ico image from a PNG or JPG. ICO is recognized by Windows Vista and later version of Windows. 
Somehow XP does not recognize this .ico image as an icon.

**Comment by wiredfool** [comment]
Does it work if you create it from a BMP, or other `P` mode image?

**Comment by arsenik** [comment]
Did not work either from BMP. 
Sample code 

    from PIL import Image
    original = Image.open('favicon.ico')
    original.save('newfavicon.ico')

**Comment by cgohlke** [comment]
Icons images are stored in PNG format, which XP can not read.
https://github.com/python-pillow/Pillow/blob/master/PIL/IcoImagePlugin.py#L66

**Comment by arsenik** [comment]
thank you @cgohlke
