### ISSUE TITLE
Travis is failing on pypy2.5.0

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1103]
Looks like something in the new dictionary implementation is failing on travis: 

```
======================================================================
FAIL: TestFileTiff.test___str__
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/python-pillow/Pillow/Tests/test_file_tiff.py", line 181, in test___str__
    '{256: (55,), 257: (43,), 258: (8, 8, 8, 8), 259: (1,), '
AssertionError: '{259: (1,), 284: (1,), 262: (2,), 256: (55,), 257: (43,), 258: (8, 8, 8, 8), 338: (1,), 282: ((720000, 10000),), 283: ((720000, 10000),), 296: (2,), 273: (8,), 277: (4,), 279: (9460,)}' != '{256: (55,), 257: (43,), 258: (8, 8, 8, 8), 259: (1,), 262: (2,), 296: (2,), 273: (8,), 338: (1,), 277: (4,), 279: (9460,), 282: ((720000, 10000),), 283: ((720000, 10000),), 284: (1,)}'
```

Looks like a dictionary ordering issue to me.  I think that this is a test issue, not a bug in Pillow.

**Comment by hugovk** [comment]
Travis updated a bunch of Python versions this week, maybe PyPy was one of them.

**Comment by hugovk** [comment]
http://docs.travis-ci.com/user/build-environment-updates/2015-02-03/#Python-VM

Python 2.7.8 → 2.7.9, 
3.4.0 → 3.4.2 
PyPy 2.3.1 → 2.5.0 
PyPy3 2.3.1 → 2.5.0

Try rebuilding a previously passing build, see if it now fails.

**Comment by wiredfool** [comment]
Yeah, pypy 2.5.0 was released this week, and one of the things that they mentioned that changed was a new implementation of dictionaries, which are now ordered by default, and therefore faster and smaller. I'm guessing that our test is a little specific and needs to not be dependent on tat implementation detail.
