### ISSUE TITLE
Clipping on 16 bit grayscale tiff conversion to JPEG

### ISSUE THREAD

**Issue by dbrunton** [python-pillow/Pillow#1108]
convert() (and consequently pilconvert.py) seems to clip 16 bit grayscale tiffs when they convert to jpeg. This seems to persist no matter what order of conversions is applied. The two attached images were made with pilconvert.py -g and -r. Unfortunately GitHub won't let me upload a Tiff, but I'm happy to send the original via email if that would help.
![test3-g](https://cloud.githubusercontent.com/assets/57850/6133977/e585a3c4-b12b-11e4-94f7-0eb6835ad4cb.jpg)
![test3-r](https://cloud.githubusercontent.com/assets/57850/6133976/e584f744-b12b-11e4-856e-936984c00cfb.jpg)

**Comment by wiredfool** [comment]
I think conversions of 16bit->8bit tend to be done by clipping everything above 255. It might work better to use the ImageMath module to map the 16bit values to 0-255, and then convert to L mode. 

(a linear map would be easy, but other mappings might perserve more information)

**Comment by dbrunton** [comment]
Huh, I've never encountered that behavior before. The four other toolkits we use (IrfanView, libtiff, Aware, and GraphicsMagic) all manage this conversion in a way that results in a more-or-less recognizable facsimile of the original.

We wound up, as a temporary hack, simply shelling out to tiff2rgba prior to saving as a jpeg, (e.g. check_call(["tiff2rgba", file, file])).

**Comment by aclark4life** [comment]
Anything more to say on this issue? Is this a bug?

**Comment by hugovk** [comment]
Closing this as there's been no updates in 4 years.
