### ISSUE TITLE
Limiting of PNG text chunk size to 64k causes side-effects

### ISSUE THREAD

**Issue by euangoddard** [python-pillow/Pillow#1111]
After upgrading PIL from version 2.6.2 to 2.7.0 we found that we get lots of `ValueError`s being raised by `PngImagePlugin`. The change which causes this was introduced in 0b75526ffe41a4697231beb8b5740617c98f290b. This seems like a sensible precaution, but I think that when multiple processes are using `zlib` simultaneously, this cause the error to occur. (We run a Django app inside gunicorn with 20 worker processes per web server). We found this occurs only when our site is being spidered by bots and therefore performing multiple loading of PNG files into memory.

Can you think of any way of remedying this other than by increasing `MAX_TEXT_CHUNK` back to `ImageFile.SAFEBLOCK` (previously used)?

**Comment by wiredfool** [comment]
Previously (2.6.1), the text decompression was unbounded. An incoming chunk was limited to `ImageFile.SAFEBLOCK`, which was 1M (1024*1024 bytes), and it could decompress to anything, limited by roughly 1000x incoming size, or 1G.  2.6.2 and 2.7 have the same patch for limiting the decompression _results_ of a text field to 1M, (Controlled by `PngImagePlugin.MAX_TEXT_CHUNK`, which is set equal to `ImageFile.SAFEBLOCK`) and the sum of all text fields for an image to 64M. (there's an error in the commit comments, that should be 64M, not 64K)

There shouldn't be any concurrency issues like you're seeing. The individual checks are all against a single text entry, and the overall text memory usage is limited on a per PngStream basis, which should be per image and not shared. Are you getting the ValueError from line 248 or from 85? Are you setting `ImageFile.SAFEBLOCK` or  `PngImagePlugin.MAX_TEXT_CHUNK` in your code? Do all of these images work on their own, if run in a single thread?

**Comment by euangoddard** [comment]
Apologies for the stated version. It was an upgrade from 2.6.0 to 2.7.0 which caused us the issue.

I completely agree with the decision to limit the size to mitigate DOS attacks here so am keen to see a way to use this.

The error was coming from line 85 which is what led me to speculate about it being something to do with zlib.

As soon as we got the errors, I loaded the files in ipython using the same invocation as the application code. I tried for several images and never saw the same problem. Some of the images which causes the issues were quite small (~150x150px) and others were larger (>1k x 1k px).

From reading the comments in the code, the only way to alter those constants would be to do so just before PngImagePlugin was invoked, right? Would this not disable the DOS protection also?

**Comment by wiredfool** [comment]
It shouldn't be behaving the way you've described, so there's got to be a reason somewhere. The decompression there should be a pure function with no thread interactions. 

Is gunicorn 20 separate python processes, each with a single thread?  Is there any thread level parallelisim, or evented async stuff going on in the process where zlib is used?

I'd like to get this reproduced in something that doesn't require a massive software stack. If you start a large number of threads for image operations, does that trigger the bug?  Can you share a few of the images that are causing trouble?

**Comment by euangoddard** [comment]
There should not be any thread interactions as we run gunicorn with a single master process with 20 child single-threaded sync workers. We don't use any of the evented options for gunicorn workers.

I will try to create a much more simple implementation of the setup we have with some images that are not client-sensitive within the next day or two.

**Comment by euangoddard** [comment]
I have created a simple app with the same setup as we have, but I cannot reproduce the issue even with 100k requests and high concurrency. Therefore I think the issue is not caused by multiprocessing or threading (I tested the latter as well). I will perform some further investigation to see if anything else is being done to alter the `PngImagePlugin` or `zlib` by other code.

**Comment by aclark4life** [comment]
Any progress?

**Comment by euangoddard** [comment]
I'm afraid not. Even with my entire team spidering a version of our production application, we could not reproduce the issue. This may just be a volume issue or the machine might have a slightly different set of libraries to our production environment.

If no one else has experienced this issue it would seem to be a very edge case as I'd imagine that Pillow 2.7.0 is being used in many high-volume production environments at present.

**Comment by aclark4life** [comment]
OK closing please reopen if anything changes. Thanks
