### ISSUE TITLE
Pillow and Cython

### ISSUE THREAD

**Issue by joekilner** [python-pillow/Pillow#1112]
Is there an easy way to access the buffers of an Image using Cython?

(for more information here is me asking the same question of the Cython community:  https://groups.google.com/forum/#!topic/cython-users/Dc1ft5W6KM4)

Basically it seems that Cython has nice syntax for interacting with things that support the buffer protocol, and there are hints that Pillow "supports" the buffer protocol, but I haven't found out exactly what that means (I suspect it means that you can create Pillow Images *from* things that support the buffer protocol).

At the end of the day I just want a simple way to write fast code that does stuff accessing pixels, I'm not  particularly bothered how that is achieved. I already have an implementation that uses Numpy and weave to do the job, but I am looking for something that is simpler to redistribute, which is why a Cython version is appealing.

**Comment by wiredfool** [comment]
From a quick look at the code, it's pretty clear that Pillow doesn't support exporting the core image object as a buffer object. It may be possible to it the other way, by creating a buffer object, then sharing that to Pillow with Image.frombuffer. This will work with some image types. I believe that you'd still retain write access to the image memory, so it would probably do what you need it to do.  

(Now why we have PIL style buffer access in python and no apparent buffer access in a PIL fork. Well, that's a mystery. Beyond what I have in source control history.)

The other thing you could look at is the PyAccess module. It does cffi based access to the data structure for all supported image types. It is quite fast, especially in PyPy.

**Comment by joekilner** [comment]
From all the hints and comments I can find on the web it does look a bit like a job half done. I'll have another look at the PyAccess module and if that doesn't work I'll see if I can't finish of what others seem to have started...

**Comment by joekilner** [comment]
Thanks for your help. There appears to be some discussion on the Cython thread that might lead to something - people discussing wrapping an ImagingMemoryInstance pointer in a MemoryView.

In the meantime I just copied what PyAccess does in my Cython code. Works like a charm. Thanks!

**Comment by devinus** [comment]
@joekilner What exactly did you do? I'm trying to do something similar to this, but it's no bueno:

```cython
    tmp = image.convert('YCbCr').tobytes()
    cdef bytes py_bytes = tmp
    cdef char* c_string = py_bytes
```

**Comment by joekilner** [comment]
I did this, basically copying the data structure access from the PyAccess module

    in_image.load()
    ptr_val = dict(in_image.im.unsafe_ptrs)['image8']
    cdef unsigned char** in_val = (<unsigned char**>ptr_val)

    output = Image.new("L", image_size, 0)
    output.load()
    ptr_val = dict(output.im.unsafe_ptrs)['image8']
    cdef unsigned char** out_val = (<unsigned char**>ptr_val)

If your image mode is anything other than "L" you will need to access a different unsafe pointer and cast it to the appropriate type...

**Comment by aclark4life** [comment]
Resolved?

**Comment by joekilner** [comment]
Kind of. The answer to the question is "no" and I've found a workaround.

Now if someone wants to take that on and turn the "no" into a "yes" by writing the appropriate buffer access wrappers, that is another matter!

**Comment by aclark4life** [comment]
Thanks
