### ISSUE TITLE
Add support of RW2 files

### ISSUE THREAD

**Issue by koutoftimer** [python-pillow/Pillow#1118]
Here is ipython output

    In [3]: im = Image.open('panasonic_gm1_sample1.rw2')
    ---------------------------------------------------------------------------
    IOError                                   Traceback (most recent call last)
    <ipython-input-3-e157c42cfa3f> in <module>()
    ----> 1 im = Image.open('panasonic_gm1_sample1.rw2')

    /venv/lib/python2.7/site-packages/PIL/Image.pyc in open(fp, mode)
       2272 
       2273     raise IOError("cannot identify image file %r"
    -> 2274                   % (filename if filename else fp))
       2275 
       2276 

    IOError: cannot identify image file 'panasonic_gm1_sample1.rw2'

Library version

    $ pip freeze | grep Pillow
    Pillow==2.7.0

**Comment by wiredfool** [comment]
We don't currently support raw files from any other camera manufacturer. There have been a couple mentions for supporting reading raw files in general through a library dependency, but that has not been contributed.
