### ISSUE TITLE
Release 2.8.0 on April 1, 2015

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1124]
No joke

**Comment by aclark4life** [comment]
@hugovk @wiredfool Anything special that needs to happen before 2.8.0? As far as I can tell, it's shaping up to be an uneventful release (i.e. the best kind).

**Comment by hugovk** [comment]
Nothing special, just the usual review of the pulls and issues.

**Comment by aclark4life** [comment]
@hugovk cool thanks. @wiredfool you handling the release again?

**Comment by wiredfool** [comment]
I'm going to have to stand back on this one and the next. I'll do what I can, but I can't promise much.

**Comment by aclark4life** [comment]
@wiredfool No problem, glad I asked :smile:

**Comment by aclark4life** [comment]
OK I just finished triaging issues:

- Add comments
- Add labels
- Closed finished

Next we should mark anything that could potentially go in 2.8.0 and get it done, else whatever is in master now will become 2.8.0.

**Comment by aclark4life** [comment]
I would love to get #1122, #1125, #1131 in before 2.8.0 goes out sometime today CC: @wiredfool @hugovk @homm.

**Comment by hugovk** [comment]
I've merged #1131. See https://github.com/python-pillow/Pillow/pull/1131#issuecomment-88444301

**Comment by homm** [comment]
Sorry, I don't think we can merge #1122 as is. I just started code review and there are some questions.

**Comment by aclark4life** [comment]
@homm No problem, just checking. Thanks

**Comment by aclark4life** [comment]
@cgohlke Ping re: Windows binaries. Thanks

**Comment by cgohlke** [comment]
Here you go: http://www.lfd.uci.edu/~gohlke/download/Pillow-2.8.0.win-dist.zip

**Comment by aclark4life** [comment]
Thanks @cgohlke. @hugovk do you know how to operate ``pillow-wheels`` to build OS X wheels? Also, I can't remember how we've built Linux wheels in the past.

**Comment by wiredfool** [comment]
I can push an osx build. Basically, you have to git pull/checkout the pillow dependency to what you want to build, then commit and push the ref in the pillow-wheels repo. I'll do it and document.

**Comment by wiredfool** [comment]
```
erics@builder-1204-x64:~/pillow-wheels$ cd pillow-wheels-upstream/
erics@builder-1204-x64:~/pillow-wheels-upstream$ git fetch --all
Fetching origin
remote: Counting objects: 15, done.
remote: Compressing objects: 100% (5/5), done.
remote: Total 15 (delta 4), reused 1 (delta 1), pack-reused 9
Unpacking objects: 100% (15/15), done.
From github.com:python-pillow/pillow-wheels
   783aeea..71f8c6a  master     -> origin/master
 * [new branch]      latest     -> origin/latest
 * [new branch]      refs/pull/10/head -> pr/10
 * [new branch]      refs/pull/11/head -> pr/11
 * [new branch]      refs/pull/9/head -> pr/9
erics@builder-1204-x64:~/pillow-wheels-upstream$ cd Pillow/
erics@builder-1204-x64:~/pillow-wheels-upstream/Pillow$ git fetch --all
Fetching origin
remote: Counting objects: 669, done.
remote: Compressing objects: 100% (159/159), done.
remote: Total 669 (delta 304), reused 213 (delta 213), pack-reused 297
Receiving objects: 100% (669/669), 1.46 MiB | 715 KiB/s, done.
Resolving deltas: 100% (394/394), done.
From https://github.com/python-pillow/Pillow
 * [new branch]      2.8.x      -> origin/2.8.x
   0f05eb2..d754598  master     -> origin/master
 * [new tag]         2.8.0      -> 2.8.0
erics@builder-1204-x64:~/pillow-wheels-upstream/Pillow$ git checkout 2.8.0
Previous HEAD position was 9f0ec3b... Revert "Workaround Pypy regression"
HEAD is now at d754598... Update CHANGES [ci skip]
erics@builder-1204-x64:~/pillow-wheels-upstream/Pillow$ cd ..
erics@builder-1204-x64:~/pillow-wheels-upstream$ ls
archives  Pillow  pillow.patch  README.rst  run_install.sh  terryfy
erics@builder-1204-x64:~/pillow-wheels-upstream$ git status
# On branch master
# Your branch is behind 'origin/master' by 2 commits, and can be fast-forwarded.
#
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
#	modified:   Pillow (new commits)
#
no changes added to commit (use "git add" and/or "git commit -a")
erics@builder-1204-x64:~/pillow-wheels-upstream$ git commit -m "Pillow -> 2.8.0" Pillow
[master 719f772] Pillow -> 2.8.0
 1 file changed, 1 insertion(+), 1 deletion(-)
```

**Comment by aclark4life** [comment]
Nice, thanks @wiredfool

**Comment by aclark4life** [comment]
@wiredfool Did you push? I don't see anything in the Rackspace container http://cdf58691c5cf45771290-6a3b6a0f5f6ab91aadc447b2a897dd9a.r50.cf2.rackcdn.com/

**Comment by wiredfool** [comment]
no, I edited and said I'd wait till 2.8.1, unless you'd rather I pushed now.

**Comment by aclark4life** [comment]
Go ahead and push, thanks. I can do 2.8.1 hopefully, now that process is documented. Do we still need to handle Linux wheels?

**Comment by wiredfool** [comment]
Pushed osx wheels. I don't remember on linux wheels. I don't think we've been doing linux binaries though.

**Comment by wiredfool** [comment]
bah, travis-ci has removed their contrast for april fools.

**Comment by aclark4life** [comment]
Uploaded, thanks

**Comment by hugovk** [comment]
Reminder: document the wheels process in https://github.com/python-pillow/Pillow/blob/master/RELEASING.md

**Comment by aclark4life** [comment]
Reopening for 2.8.1 discussion. So all I need to do is merge Hugo's PR #1165 and release 2.8.1? Thanks for the awesome debugging @wiredfool and @hugovk

**Comment by hugovk** [comment]
Whichever PR is merged, it'll need to go into both master and 2.8.x, and then the release made from 2.8.x (to avoid feature creep).

I followed this `git bisect` guide: https://robots.thoughtbot.com/git-bisect

**Comment by aclark4life** [comment]
Right. I plan to merge PR to master then merge those changes into 2.8.x branch then release. Do we need to decide between undoing the bisected "bad" commit vs. catching struct error? If so, then I am +1 for the latter I think.

**Comment by hugovk** [comment]
Yes, merge just one of https://github.com/python-pillow/Pillow/pull/1165 or https://github.com/python-pillow/Pillow/pull/1164 and reject the other. I'm +1 on the catch.

**Comment by aclark4life** [comment]
@cgohlke Can I trouble you for https://pypi.python.org/pypi/Pillow/2.8.1 binaries? Sorry for the extra work, and please let us know if this process ever becomes annoying. There are probably additional steps we can take to ensure binaries are only cut once per quarter e.g. release candidates.

**Comment by cgohlke** [comment]
Here you go: http://www.lfd.uci.edu/~gohlke/download/Pillow-2.8.1.win-dist.zip

**Comment by aclark4life** [comment]
Great, thanks @cgohlke
