### ISSUE TITLE
transform on I;16

### ISSUE THREAD

**Issue by carlosdcastillo** [python-pillow/Pillow#1127]
I'm loading a 16 bit image available here: https://www.dropbox.com/s/z0gylmagvibpqbm/image.tif?dl=0

And I'm trying to apply a simple perspective transform and I'm getting a black image.

I tried with the same but 8bit image: https://www.dropbox.com/s/0z9ds3ul6x5oghk/image.png?dl=0

and it worked as expected.

Attached is the the code to reproduce:

    from PIL import Image
    im = Image.open('image.tif')
    (w,h) = im.size
    coeffs = [  6.76536993e-01,  -2.20372868e-01,   1.31540009e+02,  -6.78693273e-03,
           3.71504111e-01,   1.12171563e+02,  -8.13846306e-07,  -5.86155180e-04]
    im = im.transform((w,2*h),Image.PERSPECTIVE, coeffs, Image.BICUBIC)
    im.save('imageout.tif')

    im = Image.open('image.png')
    (w,h) = im.size  
    coeffs = [  6.76536993e-01,  -2.20372868e-01,   1.31540009e+02,  -6.78693273e-03,
           3.71504111e-01,   1.12171563e+02,  -8.13846306e-07,  -5.86155180e-04]
    im = im.transform((w,2*h),Image.PERSPECTIVE, coeffs, Image.BICUBIC)
    im.save('imageout.png')

**Comment by wiredfool** [comment]
There are a couple of possible issues:

-  `I;16` isn't fully supported, you may need to convert to an `I` mode. 
- There may be issues in the save or display of the `I;16` image, you may want to check image.tobytes to see if it's returning what you think it should be prior to saving. 
- A quick test was showing something other than a black image for me. It didn't look right, but it wasn't blank.

**Comment by carlosdcastillo** [comment]
Thanks!

That trick of converting to I, transforming and then converting back to I;16 really works. That is the solution to my problem.
