### ISSUE TITLE
fromarray fails on PyPy

### ISSUE THREAD

**Issue by daver1691** [python-pillow/Pillow#1129]
Pillow seems to mostly work on PyPy, the Python JIT compiler, but I find that `fromarray` does not work. Not sure if this is a PyPy, numpy or Pillow issue.

Tested on the recently released PyPy 2.5.0 (stable), numpy 1.9.0 and Pillow 2.7.0. This code snippet works OK on CPython, and pops up a window of randomly coloured pixels, but fails on PyPy.

```python
import numpy as np
from PIL import Image
arr = np.uint8(255 * np.random.rand(300,400,3))
img = Image.fromarray(arr, mode="RGB")
img.show()
```
```
$ pypy test-array-pil.py
Traceback (most recent call last):
  File "app_main.py", line 75, in run_toplevel
  File "test-array-pil.py", line 5, in <module>
    img = Image.fromarray(arr, mode="RGB")
  File "/opt/pypy/site-packages/PIL/Image.py", line 2174, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/opt/pypy/site-packages/PIL/Image.py", line 2124, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)
  File "/opt/pypy/site-packages/PIL/Image.py", line 2050, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/opt/pypy/site-packages/PIL/Image.py", line 721, in frombytes
    s = d.decode(data)
TypeError: must be string or read-only buffer, not ndarray
```

**Comment by wiredfool** [comment]
Have you tried Numpypy?  http://morepypy.blogspot.com/2015/02/numpypy-status-january-2015.html

**Comment by daver1691** [comment]
From that, I think that numpypy is another name for the version of numpy for pypy which I installed following the instructions on the pypy download page http://pypy.org/download.html with the command
`pip install git+https://bitbucket.org/pypy/numpy.git`

**Comment by wiredfool** [comment]
Digging a little and I'm seeing that an ndarray on 2.7 implements `tobytes` where the pypy version doesn't, as installed by the pip command. That would be what Pillow is calling to read the bytes-like-object in frombytes.

**Comment by daver1691** [comment]
Thanks. But being an end-user rather than a developer, I had to Google that, and I've no idea what I'm doing.  The following works on CPython and Pypy...
```python
from PIL import Image
import numpy as np
byt = Image.new("RGB",(400,300),"red").tobytes()
img = Image.frombytes('RGB',(400,300), byt)
img.show()
```

**Comment by wiredfool** [comment]
Sorry, to unpack:

`Image.fromarray` attempts to share that backing buffer of the ndarray, and can do that for certain modes (mainly ones that are densely packed, e.g. L, I, or RGBA). RGB is not one of those modes, since there's spare space in there for an Alpha channel. 

If it can't share the backing buffer, it passes the ndarray to `Image.frombytes`, which requires that the passed in object support the `tobytes` method so that it can retrieve the data. 

For some reason, numpy on pypy is not providing that method. It may work with one of the mapped modes, but I'd caution you that it's not a tested configuration. (We test on pypy, but we don't build numpy for pypy to test the fromarray portion). It would probably be worth raising this wiht the numpy/pypy people if you really need this combination to work.

**Comment by daver1691** [comment]
Sorry, I still don't get it. As I said in the previous post, numpy1.9 for PyPy _does_ seem to me to have the tobytes method on ndarrays. This works:
    byt = np.uint8(255 * np.random.rand(300,400,3)).tobytes()
Sorry if I'm misunderstanding what you're saying and I'm happy to ask the numpy/pypy people, but what precisely are you saying is missing?

**Comment by wiredfool** [comment]
I wasn't seeing nparray.tobytes in the version from source on pypy, but I was seeing it on the system numpy on ubuntu12.04, which I think is 1.6. 

I think what's happening (without source diving, since right now I'm away from dev machine) is that there's some meta magic on tobytes in 1.9 which wasn't there earlier. I'll try to trace exactly where the problem is in the C layer.

**Comment by wiredfool** [comment]
Works with current versions

**Comment by sn6uv** [comment]
I'm seeing this again on numpy-1.11.1, PyPy 5.4.1 and Pillow 3.3.1:
```
  File "/home/angus/Mathics/mathics/builtin/image.py", line 2158, in atom_to_boxes
    pillow = PIL.Image.fromarray(pixels, pixels_format)
  File "/home/angus/venv/venv_pypy/site-packages/PIL/Image.py", line 2189, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/home/angus/venv/venv_pypy/site-packages/PIL/Image.py", line 2134, in frombuffer
    core.map_buffer(data, size, decoder_name, None, 0, args)
TypeError: PyPy does not yet implement the new buffer interface
```

**Comment by hugovk** [comment]
@sn6uv A similar "PyPy does not yet implement the new buffer interface" error occurs on Travis CI when upgrading PyPy from 5.3.1 to 5.4.1:
```
TestFileIcns.test_jp2_icon ... ERROR
======================================================================
ERROR: TestFileIcns.test_jp2_icon
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/travis/build/hugovk/Pillow/Tests/test_file_icns.py", line 82, in test_jp2_icon
    im2.load()
  File "/home/travis/build/hugovk/Pillow/PIL/IcnsImagePlugin.py", line 287, in load
    im = self.icns.getimage(self.best_size)
  File "/home/travis/build/hugovk/Pillow/PIL/IcnsImagePlugin.py", line 235, in getimage
    channels = self.dataforsize(size)
  File "/home/travis/build/hugovk/Pillow/PIL/IcnsImagePlugin.py", line 227, in dataforsize
    dct.update(reader(self.fobj, desc, size))
  File "/home/travis/build/hugovk/Pillow/PIL/IcnsImagePlugin.py", line 89, in read_32
    "L", pixel_size, b"".join(data), "raw", "L", 0, 1
  File "/home/travis/build/hugovk/Pillow/PIL/Image.py", line 2141, in frombuffer
    core.map_buffer(data, size, decoder_name, None, 0, args)
TypeError: PyPy does not yet implement the new buffer interface
```
https://travis-ci.org/hugovk/Pillow/builds/164390550

Which sounds like a PyPy error rather than Pillow.
