### ISSUE TITLE
Transparency/alpha mask and pasting?

### ISSUE THREAD

**Issue by darkfeline** [python-pillow/Pillow#1133]
Given one opaque image A and a semi-transparent image B, if I paste B onto A, I would expect the result C to be opaque, but it seems like I'm getting a C that is semi-transparent, like B's mask is overwriting A's mask rather than just determining the pixels that get pasted onto A.

I'll try to whip up a demonstrative example later.

**Comment by homm** [comment]
You need [`PIL.Image.alpha_composite`](http://pillow.readthedocs.org/en/latest/reference/Image.html#PIL.Image.alpha_composite).

**Comment by darkfeline** [comment]
Thanks, I see how paste works now.  Maybe a note should be added for clarification to paste()'s documentation with a "see also alpha_composite"?

**Comment by aclark4life** [comment]
Sure can you send a pull request?

**Comment by darkfeline** [comment]
I have tracked down the paste implementation to [libImaging/Paste.c](https://github.com/python-pillow/Pillow/blob/master/libImaging/Paste.c), but I can't tell what it's doing with the mask.

Through empirical tests I think I figured out what it's doing.  If the current image does not have an alpha channel, then the mask determines how much of each image to use for the result.  If the current image does have an alpha channel, then intermediate mask values (only intermediate values, not 0 or 255) will set the alpha channel of the result.

I've made a patch that clarifies things:
https://github.com/darkfeline/Pillow/commit/bb01e845ea4ccdd84acedaa82818d17034c212d0

Is there any preferred way of making pull requests?

**Comment by aclark4life** [comment]
@darkfeline Great! Dev guidelines here: https://github.com/python-pillow/Pillow/blob/master/CONTRIBUTING.md

**Comment by radarhere** [comment]
Is this issue resolved now that the PR has been merged?

**Comment by hugovk** [comment]
Closing, we can re-open if needed.
