### ISSUE TITLE
Installation hangs under PyPy (solved)

### ISSUE THREAD

**Issue by vmarkovtsev** [python-pillow/Pillow#1135]
`pip install Pillow` / `pypy setup.py install` may hang forever. I managed to solve the problem and found out what it was, so others can reference this issue. 

This is because `tkinter` package is lazily compiled with pypy's cffi at the moment of the first usage and distutils uses multiple processes during the compilation on Pillow natives (on my machine, 4, though it has 32 cores); pip launches 8). So `import Tkinter` in each process triggers cffi machinery and they interfere with compiling the same files in parallel and deadlock each other. The solution to the problem is executing `import Tkinter` *before* installing Pillow.

I guess this is not a problem with Pillow, but with pypy's cffi, so closing this at once.

**Comment by vmarkovtsev** [comment]
See https://bitbucket.org/pypy/pypy/issue/1999/cffi-must-use-file-locks

**Comment by arigo** [comment]
Fwiw, tkinter should be precompiled during a normal PyPy installation, so that particular problem is showing an issue with your installation.  But I see the problem in general.

**Comment by fusionbeam** [comment]
I've run into the same issue.
I've build pypy from sources, packaged it with package.py
pip install pillow hangs indefinitely due to this deadlock it seems.

I also tried an import Tkinter in a python console before the pip install.
Initially it complained about tk headers. 
After an apt-get install tk-dev I get this error:

```
(env)nms@nmssandbox:~/nms/env$ python
Python 2.7.9 (9c4588d731b7fe0b08669bd732c2b676cb0a8233, Apr 14 2015, 10:29:42)
[PyPy 2.5.1 with GCC 4.8.2] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> import Tkinter
/opt/pypy/lib_pypy/_tkinter/__pycache__/_cffi__ge45aff47x9fa68891.c: In function ‘_cffi_check_struct_Tcl_Obj’:
/opt/pypy/lib_pypy/_tkinter/__pycache__/_cffi__ge45aff47x9fa68891.c:380:26: warning: initialization from incompatible pointer type [enabled by default]
   { Tcl_ObjType * *tmp = &p->typePtr; (void)tmp; }
                          ^
/opt/pypy/lib_pypy/_tkinter/__pycache__/_cffi__ge45aff47x9fa68891.c: In function ‘_cffi_check_struct_Tcl_ObjType’:
/opt/pypy/lib_pypy/_tkinter/__pycache__/_cffi__ge45aff47x9fa68891.c:408:19: warning: initialization from incompatible pointer type [enabled by default]
   { char * *tmp = &p->name; (void)tmp; }
```
Any thoughts?

**Comment by arigo** [comment]
Hi,

On 20 April 2015 at 17:42, fusionbeam <notifications@github.com> wrote:

> Any thoughts?
>

This is not an error, just warnings given by the C compiler.  Ignore them
(they should only show up once).


Armin

**Comment by Storyyeller** [comment]
I ran into this issue as well, but was able to solve it by setting `MAX_CONCURRENCY=1` as suggested [here](https://github.com/python-pillow/Pillow/issues/1385).

I wish Pypy would work out of the box though

`
Python 2.7.13 (84a2f3e6a7f8, Oct 03 2017, 18:46:00)
[PyPy 5.9.0 with GCC 4.2.1 Compatible Apple LLVM 5.1 (clang-503.0.40)] on darwin
`

**Comment by arigo** [comment]
Storyyeller: this is an old issue describing a problem that should not exist any more nowadays.  If playing with MAX_CONCURRENCY helps you it's a very different problem.  In this case please report it to pypy's own issue tracker with some details about what you're doing, which is surely different.
