### ISSUE TITLE
PNG image shows up corrupt

### ISSUE THREAD

**Issue by cool-RR** [python-pillow/Pillow#1136]
I'm trying to load PNG images using Pillow 2.7.0 and they come up corrupt.

Example session with images here: http://stackoverflow.com/questions/29107694/opening-png-with-pil-pillow

**Comment by wiredfool** [comment]
It looks like the show() isn't getting the alpha information from the image. Show uses BMP on windows, and our BMP writer doesn't do alpha.

**Comment by cool-RR** [comment]
I've seen the image get corrupted not only in `.show()` but also when I did
`image.paste` of it into another image. It was corrupted in exactly the
same way visually.

**Comment by cool-RR** [comment]
Solved, not a bug: http://stackoverflow.com/a/29108827/76701
