### ISSUE TITLE
bug during converting between pillow and numpy?

### ISSUE THREAD

**Issue by retsyo** [python-pillow/Pillow#1140]
I am using anacond Python 2.7.6 |Anaconda 1.9.2 (32-bit)| (default, Nov 11 2013, 10:50:31) on windows 7 64 bits. Pillow and numpy are all updated on March 20, 2015 with 'conda update xx' (pillow-2.7.0-py27_0.tar.bz2, numpy-1.9.2-py27_p0.tar)

I want to do image processing with PIL and numpy(yes, I know there is 'scipy.misc.imread'), but the result always fails to meet the mathmatical answer. So I traced and coin the following simple code. The key problem lies in 'imgData2=numpy.array(img, dtype="uint8").**reshape(img.size)**' which is so-said over many webpages, but I found only 'imgData2=numpy.array(img, dtype="uint8").**reshape(img.size[::-1])**' is true. So I just come to find whether this is a bug in conversion between PIL and numpy, or something I made wrong. Thanks

```python
#coding=utf-8
import os, sys
import numpy
from pylab import *

import PIL.Image as Image

def printImageData(img):
    wid, hi=img.size
    for y in range(hi):
        for x in range(wid):
            print img.getpixel((x, y)),
        print
    print

#we create a picture, whose width is 3, and high is 2
wid, hi=3, 2
img=Image.new('L', (wid, hi), 255)
img.putpixel((0,0),0)
img.putpixel((0,1),0)
img.putpixel((2,0),0)

printImageData(img)
img.save('test.png')


#there are 2 problems:
#1. if we do not transpose, then img2 is 2 pixels in width, and 3 pixels in high, which is different from original img
#2. even we use transposition, img2 has different pixels value than original img
imgData2=numpy.array(img, dtype="uint8").reshape(img.size)#.T

img2=Image.fromarray(imgData2, mode='L')
printImageData(img2)
img2.save('img2.png')

#this is the right way
imgData3=numpy.array(img, dtype="uint8").reshape(img.size[::-1])
img3=Image.fromarray(imgData3, mode='L')
printImageData(img3)

subplot(1,3,1)
imshow(img, cmap='gray', interpolation='nearest' )
title('original pic')

subplot(1,3,2)
imshow(img2, cmap='gray', interpolation='nearest' )
title('pic 2. the wrong one')

subplot(1,3,3)
imshow(img3, cmap='gray', interpolation='nearest' )
title('pic 3, the right one')

fig=gcf()
fig.tight_layout()

show()
```

**Comment by radarhere** [comment]
Testing OS X with Pillow 2.7.x and bumpy 1.9.2, if I remove the `.reshape(img.size)`, I am unable to replicate the problem. Perhaps someone else will have more luck.

With regards to what you're experiencing after you use `reshape`, there's an example about halfway down http://docs.scipy.org/doc/numpy/reference/generated/numpy.reshape.html that shows that for a 2D shape, numpy does expect the arguments the other way around. When Googling this, I couldn't find sites that used `img.size` explicitly, but instead found examples of manually specifying the dimensions. So yes, using `[::-1]` would have the desired effect, but is perhaps confusing. You might be interested in the recently added Pillow feature that allows you to refer to `img.width` and `img.height`, as I think that `.reshape(img.height, img.width)` is probably the clearest way of writing the code.
