### ISSUE TITLE
Image.load() does not close file pointer

### ISSUE THREAD

**Issue by arve0** [python-pillow/Pillow#1144]
I'm doing this:

``` python
from PIL import Image
img = Image.open(path)
fp = img.fp
img.load()
fp.closed # False
```

Expected file pointer to be closed.

System:
- Windows 7 64bit
- Python 3.4.1
- Pillow 2.7.0 (installed via conda)

**Comment by aclark4life** [comment]
It's not False, the attribute is missing:

```
>>> img = Image.open("/Users/alexclark/Downloads/bob 15.jpg")
>>> img.fp.closed
False
>>> img.load()
<PixelAccess object at 0x10664c110>
>>> img.fp.closed
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'NoneType' object has no attribute 'closed'

```

I agree this is wonky.

**Comment by arve0** [comment]
Yes, the file pointer is deleted from img object, but if you copy the reference, you can still see that its there and open.

**Comment by aclark4life** [comment]
Ah! OK marked as bug, thanks.

**Comment by radarhere** [comment]
I can replicate this on OS X, so it's not just Windows.

I wrote a patch so that the file pointer would close, but I then found that the seek method in GifImagePlugin uses the file pointer after calling load()

**Comment by QuLogic** [comment]
Same as #835?

**Comment by arve0** [comment]
@QuLogic Seems plausible. Herre is the updated line nr: https://github.com/python-pillow/Pillow/blob/6a85d5184c5556a35dfbf5c0d3ed3d0903781193/PIL/ImageFile.py#L246

**Comment by hugovk** [comment]
The code in the first comment now passes:
```python
from PIL import Image
img = Image.open(path)
fp = img.fp
img.load()
fp.closed # was False in original report, but is now True
```

System:
- macOS Sierra
- Python 3.6.0
- Pillow 2.7.13
