### ISSUE TITLE
Image.open( <svg file> )

### ISSUE THREAD

**Issue by michalwerner** [python-pillow/Pillow#1146]
Is it possible to open .svg files with Pillow?

**Comment by homm** [comment]
Full list of supported formats: http://pillow.readthedocs.org/en/latest/handbook/image-file-formats.html

**Comment by aclark4life** [comment]
Wow nice list but no SVG, sorry! No.

**Comment by KS-HTK** [comment]
Word of Caution:
List is not complete as `.emf` (enhanced metafile) can be opened but is not included on the list.

**Comment by radarhere** [comment]
Fair enough. I've created #6338 to add it to the list.

**Comment by nulano** [comment]
You can see the full list by running `python -m PIL`. Comparing this with the docs, I see that SUN is also missing. I did not check whether each format is in the correct category.

**Comment by radarhere** [comment]
XPM is present - https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#xpm

**Comment by nulano** [comment]
Huh, I checked XPM multiple times and I was sure it was not there a minute ago... 😕

**Comment by radarhere** [comment]
I've updated #6338 to add SUN as well.
