### ISSUE TITLE
Support for HTTP response objects as file-like pointers for Image.open()

### ISSUE THREAD

**Issue by mfitzp** [python-pillow/Pillow#1148]
Opening this in response to this [report on matplotlib](https://github.com/matplotlib/matplotlib/issues/4252). Attempting to open remote image files (passing the `urlopen` object) fails as the object does not support `.seek`. 

There is example code on [this StackOverflow post](http://stackoverflow.com/questions/12020657/how-do-i-open-an-image-from-the-internet-in-pil) for how to wrap the opened object into a file-like object supporting `.seek` using `io.BytesIO` (replacement for `StringIO`).

    from PIL import Image
    import urllib2 as urllib
    import io

    fd = urllib.urlopen("http://a/b/c")
    image_file = io.BytesIO(fd.read())
    im = Image.open(image_file)

The relevant bit of PIL code can be inserted as follows in `Image.imread` (line `2242`) immediately before the prefix load:

    if isPath(fp):
        filename = fp
        fp = builtins.open(fp, "rb")
    else:
        filename = ""

    try:
        fp.seek(0)
    except (AttributeError, io.UnsupportedOperation):
        fp = io.BytesIO(fp.read())

    prefix = fp.read(16)

The general approach that works is checking for `AttributeError` during `.seek(0)` and on failure attempting to wrap the object into a `io.Bytes` object. This will fail if it is not a buffer and we can exit as normal. Using this we can then request files via urls, using both `urllib` or `requests` as follows:

    Image.open(urllib2.urlopen(url))
    Image.open(requests.get(url, stream=True).raw)

It would be nice if `requests.get(url).content` worked, but that is a raw bytes object with no `.read()` so would require an alternative handling.

Is this something that would be considered for inclusion in the PIL library? I am happy to put together a PR if it looks reasonable. This depends on the `io` module as is which adds a 2.6 requirement, but the earlier StringIO is equivalent (there is a wrapper available in `six.BytesIO`).

**Comment by aclark4life** [comment]
I don't see why not. If you send the PR soon it could go in 2.8.0

**Comment by mfitzp** [comment]
Great! I've submitted a PR for consideration. This uses `io.BytesIO` as that [is supported from Python 2.6+](https://docs.python.org/2/library/io.html) according to the docs.
