### ISSUE TITLE
Testsuite failures on SuperH architecture

### ISSUE THREAD

**Issue by glaubitz** [python-pillow/Pillow#1154]
Hello!

Pillow currently fails to build from source on the buildds for the sh4 (Renesas SuperH) port of Debian. The testsuite crashes at some point with a traceback starting in the file /usr/lib/python2.7/dist-packages/nose/plugins/multiprocess.py.

I am not really an expert in Python but I would assume this issue arises since Pillow makes wrong assumptions about the underlying architecture. But please have a look at it yourself, I am attaching a the full build log [1]. I am also happy to provide further details if necessary and I would be happy to test any patches.

Cheers,
Adrian

> [1] https://people.debian.org/~glaubitz/pillow_2.6.1-1_sh4-20150304-0321

**Comment by aclark4life** [comment]
Thanks. How about 2.7.0? Looks like the multiprocessing test failed. Maybe you can disable that one.

**Comment by glaubitz** [comment]
Alright, that was actually my guess :). I will ask the maintainer in Debian to disable that particular test on sh4. I am a Debian Developer myself but I don't maintain Pillow.

Could you give me a quick hint how to disable it so I can come up with a patch right away? Otherwise I am sure that Matthias Klose (maintainer of Pillow in Debian) will be able to do that as well.

Thanks!
Adrian

**Comment by aclark4life** [comment]
If these are nose tests, then pass 0 to --processes to disable multiprocessing:
```
  --processes=NUM       Spread test run among this many processes. Set a
                        number equal to the number of processors or cores in
                        your machine for best results. Pass a negative number
                        to have the number of processes automatically set to
                        the number of cores. Passing 0 means to disable
                        parallel testing. Default is 0 unless NOSE_PROCESSES
                        is set. [NOSE_PROCESSES]
```
