### ISSUE TITLE
inconsistent data when reading jpeg file

### ISSUE THREAD

**Issue by matthias-k** [python-pillow/Pillow#1156]
Hi,

when reading jpeg files with pillow, I get inconsistend results for two python installations on my machine. Take for example [this image](https://kalliope.matthias-k.org/~matthias/tmp/i05june05_static_street_boston_p1010764.jpeg):

On my ubuntu 14.04s native python2.7 (numpy, pillow 2.7.0 installed from pip), I get

    >>> np.array(PIL.Image.open('i05june05_static_street_boston_p1010764.jpeg'))

    array([[[ 84, 129, 135],
        [ 84, 128, 131],
        [ 72, 110, 111],
        ..., 
        [ 21,  36,  39],
        [ 35,  57,  55],
        [ 74,  99,  96]],

       [[ 84, 129, 135],
        [ 84, 128, 131],
        [ 72, 111, 110],
        ..., 
        [ 27,  42,  45],
        [ 38,  60,  58],
        [ 78, 103, 100]],

       [[ 81, 129, 133],
        [ 82, 127, 130],
        [ 70, 110, 109],
        ..., 
        [ 32,  47,  50],
        [ 35,  57,  55],
        [ 78, 103, 100]],

       ..., 
       [[139, 141, 140],
        [134, 136, 135],
        [129, 131, 130],
        ..., 
        [250, 245, 255],
        [253, 248, 255],
        [255, 250, 255]],

       [[132, 134, 133],
        [129, 131, 130],
        [127, 129, 128],
        ..., 
        [183, 174, 201],
        [184, 175, 204],
        [184, 175, 202]],

       [[129, 131, 130],
        [130, 132, 131],
        [131, 133, 132],
        ..., 
        [177, 168, 199],
        [179, 170, 201],
        [180, 171, 202]]], dtype=uint8)

When using an anaconda installation of python 2.7 on the same machine with numpy and pillow 2.7.0 installed with conda, however, the result looks like this:

    >>> np.array(PIL.Image.open('i05june05_static_street_boston_p1010764.jpeg'))
    array([[[ 84, 128, 137],
        [ 84, 127, 133],
        [ 72, 110, 111],
        ..., 
        [ 21,  36,  39],
        [ 35,  57,  55],
        [ 73,  99,  96]],

       [[ 84, 128, 137],
        [ 84, 127, 133],
        [ 71, 111, 110],
        ..., 
        [ 27,  42,  45],
        [ 38,  60,  58],
        [ 77, 103, 100]],

       [[ 81, 128, 134],
        [ 82, 127, 132],
        [ 70, 110, 109],
        ..., 
        [ 32,  47,  50],
        [ 35,  56,  57],
        [ 77, 103, 100]],

       ..., 
       [[139, 141, 140],
        [134, 136, 135],
        [129, 131, 130],
        ..., 
        [250, 245, 255],
        [253, 248, 255],
        [255, 250, 255]],

       [[132, 134, 133],
        [129, 131, 130],
        [127, 129, 128],
        ..., 
        [183, 174, 203],
        [184, 175, 204],
        [184, 175, 204]],

       [[129, 131, 130],
        [130, 132, 131],
        [131, 133, 132],
        ..., 
        [177, 167, 201],
        [179, 169, 203],
        [180, 170, 204]]], dtype=uint8)

Notice for example the differences in the first line of output or the last line of output, where differences of as much as 2 occur.

I am aware that anaconda comes with it's own version of libjpeg, but shouldn't jpeg decoding be consistent? Any help would be highly appreciated, as for my application I need reliable jpeg decoding.

Best,
  Matthias

**Comment by homm** [comment]
I have some thoughts what this can be related to draft mode of libjpeg.
 
Could you check is result of this code execution under anaconda is equal to result of the execution under native python installation:

```python
i = PIL.Image.open('i05june05_static_street_boston_p1010764.jpeg')
i.load()
np.array(i)
```

Also, please check following code under anaconda:

```python
i = PIL.Image.open('i05june05_static_street_boston_p1010764.jpeg')
i.decoderconfig = (1, 1)
i.load()
np.array(i)
```

> anaconda comes with it's own version of libjpeg, but shouldn't jpeg decoding be consistent?

I don't really know is decoding of different versions of libjpeg should be consistent, but I suppose what the decoding of different jpeg decoders may not match pixel-to-pixel.

**Comment by matthias-k** [comment]
Thanks for the quick answer. When executing

    i = PIL.Image.open('i05june05_static_street_boston_p1010764.jpeg')
    i.load()
    np.array(i)

the results are as above, i.e. different for andaconda vs the native installation. For your second code fragment, however

    i = PIL.Image.open('i05june05_static_street_boston_p1010764.jpeg')
    i.decoderconfig = (1, 1)
    i.load()
    np.array(i)

the results are the same under both python versions (but different to both results produced by native python and anaconda without the decoderconfig). What does this mean?

Best,
  Matthias

**Comment by homm** [comment]
> What does this mean?

At least this means what it's not the draft mode in anaconda by default.

Could you check exact version number of libjpeg-turbo distributed with anaconda? The version with Ubuntu 14.04 should be 1.3.0.

**Comment by matthias-k** [comment]
I am not sure how to check this. In my native python installation, pillow's _imaging.so links to /usr/lib/x86_64-linux-gnu/libjpeg.so.8 which links to libjpeg.so.8.0.2. In anaconda, the used libjpeg links to a libjpeg.so.8.4.0 in anacondas library directory. How can I check the libjeg-turbo version?

**Comment by homm** [comment]
The truth is I also doesn't know ) I've checked the libjpeg-turbo package versions in aptitude, what obviously will not work for anaconda. It is also possible what anaconda uses vanilla libjpeg, not libjpeg-turbo.

**Comment by matthias-k** [comment]
The [anaconda package list](http://docs.continuum.io/anaconda/pkg-docs.html) states the version of jpeg as "8d", whatever that may be. I send them message asking for more details.
