### ISSUE TITLE
Flags --disable-tcl and --disable-tk ignored

### ISSUE THREAD

**Issue by jakirkham** [python-pillow/Pillow#1168]
The flags --disable-tcl --disable-tk appear to be ignored. As it attempts to link against Tkinter even when it is expressly forbidden. I should add that I am using Mac OS 10.9 with Python 2.7.9.

**Comment by aclark4life** [comment]
@jakirkham Appear to be ignored, or are actually ignored? You may want to paste your build output or give some more detail; I'm not sure we've heard this one before.

**Comment by jakirkham** [comment]
@aclark4life, sorry I should have provided more details. They can now be found in the follow gist ( https://gist.github.com/jakirkham/e0ba675cc00fdb8e46b5 ). I guess I say appears to be ignored as I could always be doing something wrong. There are a few lines, which lead me to believe it is building Tcl/Tk support anyways.

    building 'PIL._imagingtk' extension

    gcc -bundle -undefined dynamic_lookup -Wl,-rpath,/xopt_ilastik/local/lib -L/xopt_ilastik/local/lib build/temp.macosx-10.9-x86_64-2.7/_imagingtk.o build/temp.macosx-10.9-x86_64-2.7/Tk/tkImaging.o -L/xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib -L/opt/X11/lib -L/usr/local/lib -L/usr/lib -o build/lib.macosx-10.9-x86_64-2.7/PIL/_imagingtk.so -framework Tcl -framework Tk

    copying build/lib.macosx-10.9-x86_64-2.7/PIL/_imagingtk.so -> build/bdist.macosx-10.9-x86_64/egg/PIL

Finally, I see the following on the library.

    $ otool -L /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-macosx-10.9-x86_64.egg/PIL/_imagingtk.so 
    /xopt_ilastik/local/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/Pillow-2.7.0-py2.7-macosx-10.9-x86_64.egg/PIL/_imagingtk.so:
        /System/Library/Frameworks/Tcl.framework/Versions/8.5/Tcl (compatibility version 8.5.0, current version 8.5.9)
        /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk (compatibility version 8.5.0, current version 8.5.9)
        /usr/lib/libSystem.B.dylib (compatibility version 1.0.0, current version 1197.1.1)

**Comment by radarhere** [comment]
So, the reason for this is that in setup.py -
`if sys.platform == "darwin": # include Tcl/Tk frameworks and _imagingtk`
`elif feature.tcl and feature.tk: # include _imagingtk`

In other words, on OS X, ignore the disable-tcl and disable-tk flags.

It's been this way since PIL. If there's consensus that it should be changed, then it's a fairly simple one.

**Comment by hugovk** [comment]
Sounds like a sensible change.

**Comment by jakirkham** [comment]
@radarhere, sounds fine. Not sure what others think...

**Comment by aclark4life** [comment]
+1

**Comment by jakirkham** [comment]
So, I'm using 3.2.0 and while this is somewhat addressed, this problem still exists.

At this point, I might be content to just build with Tcl/Tk if that is easier, but instead pick which Tcl/Tk to use. Namely, I don't want to use the system version.

**Comment by wiredfool** [comment]
Does this solve your issue: https://github.com/python-pillow/Pillow/pull/1883 ?

**Comment by jakirkham** [comment]
Nope, turns out I need to put `build_ext` and `install` in the same call and then everything is fine. Sorry for the noise.

**Comment by jakirkham** [comment]
Though for skip frameworks and building with normal libs. Yes, that looks promising. Let me take it for a spin.

**Comment by jakirkham** [comment]
Yep, that patch works perfectly. Thanks @wiredfool. 👍
