### ISSUE TITLE
IOError: decoder zip not available

### ISSUE THREAD

**Issue by xgvargas** [python-pillow/Pillow#1171]
First I have to say thanks for this great library!

I've made upgrade to 2.8.1 and started having this error (in a code that used to work before with 2.6.2):

IOError: decoder zip not available

Then I downgrade to 2.8.0 and its working again.... I just want to let you know something is missing into your newest package.

**Comment by xgvargas** [comment]
Ignore me!!!

After my previous test I installed again 2.8.1 just to be sure and now it's is working fine. No ideia about what I did wrong first time....

My mistake serves to enforce what I've said about your library being great :)

**Comment by aclark4life** [comment]
@xgvargas Heh, no problem. Thanks for using Pillow! :smile:
