### ISSUE TITLE
Release 2.9.0 on July 1, 2015

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1174]

**Comment by wiredfool** [comment]
Turning off notifications because IRL. Summon me if you need me.

**Comment by aclark4life** [comment]
Roger that, thanks @wiredfool

**Comment by radarhere** [comment]
One week left. Are there any pull requests or issues that people would like to see completed for this release?

**Comment by aclark4life** [comment]
@radarhere Good question. @wiredfool are you on the release tip for 2.9.0 or am I?

**Comment by wiredfool** [comment]
IRL is getting crunch time again, despite what it's looked like the last couple of weeks. So I'd like it if you'd be release manager.

The only pr I'm hoping to get into is the exif/tiff one. My gut on that is to run it in legacy mode with a deprecation warning for a release or two before flipping to the new api. But I need to test it against old in the wild code.

**Comment by aclark4life** [comment]
@wiredfool No prob! Will do

**Comment by radarhere** [comment]
Maybe someone is just still getting around to looking at it, but I'd be keen for #1282 to be merged before release, just because otherwise, it means that the `n_frames` method is being released for the first time with an off-by-one bug in GifImagePlugin.

**Comment by aclark4life** [comment]
Commence 24 hour clock! On expiration, we ask @cgohlke for binaries

**Comment by cgohlke** [comment]
Windows binaries are at <http://www.lfd.uci.edu/~gohlke/download/Pillow-2.9.0.win-dist.zip>

**Comment by aclark4life** [comment]
Thank you @cgohlke

**Comment by hugovk** [comment]
Not strictly about 2.9.0, but if you're watching this repo, it'd be good to also watch the https://github.com/python-pillow/pillow-wheels/ repo so we don't forget about PRs like this:
https://github.com/python-pillow/pillow-wheels/pull/12

Thanks!
