### ISSUE TITLE
ImportError: The _imagingft C module is not installed

### ISSUE THREAD

**Issue by xuehao** [python-pillow/Pillow#1178]
Platform: Ubuntu 14.04 x86_64
```
Traceback (most recent call last):
  File "a.py", line 6, in <module>
    font = ImageFont.truetype("1.ttf", 72)
  File "/usr/local/lib/python3.4/dist-packages/PIL/ImageFont.py", line 262, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python3.4/dist-packages/PIL/ImageFont.py", line 142, in __init__
    self.font = core.getfont(font, size, index, encoding)
  File "/usr/local/lib/python3.4/dist-packages/PIL/ImageFont.py", line 44, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```
Error in the Ubuntu's default Python 3.4.0
But It Runs OK in the `venv` Python 3.4.0

**Comment by aclark4life** [comment]
Thanks. Are you sure this is a Pillow bug?

**Comment by xuehao** [comment]
I test in Ubuntu venv and Windows 7, No Problem.
So it means Ubuntu has something wrong.
I don't know why. Maybe you know the mechanism of Pillow, so could you tell me the reason?

**Comment by hugovk** [comment]
Pillow is tested against Python 3.4 (and 6 other Python versions) on 12.04 LTS on Travis CI, so that at least works.

Have you installed everything? See http://pillow.readthedocs.org/installation.html#linux-installation

**Comment by xuehao** [comment]
@hugovk I installed all the packages.
The wrong code is just
```
im.save('test', "JPEG")
```
It occurs `OSError: encoder jpeg not available`

When I change code to
```
im.save('test', "PNG")
```
It works OK in Ubuntu's default environment.

So I think maybe `libjpeg` has something wrong in my Ubuntu. Maybe it's due to x64 platform?

**Comment by aclark4life** [comment]
Do you have libjpeg-dev installed?

**Comment by aclark4life** [comment]
:beers:
