### ISSUE TITLE
Pillow should have a "proper" website

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1180]
Now that [Pillow has a logo](https://github.com/python-pillow/Pillow/issues/575), we may consider building a "proper" website. Nothing elaborate, just a single page design to replace the current GitHub Pages themed site: http://python-pillow.github.io/.

This issue exists to encourage someone to build a new Pillow website :+1:

**Comment by hugovk** [comment]
And here's the repo to send PRs to:

https://github.com/python-pillow/python-pillow.github.io

**Comment by jleclanche** [comment]
There's something there, you can close this?

**Comment by radarhere** [comment]
The site at http://python-pillow.github.io/ is the same site that was there when this issue was opened.

**Comment by jleclanche** [comment]
It looks fine, honestly.

**Comment by aclark4life** [comment]
Yeah, definitely not a priority; will close for now. We can reopen whenever the possible "replace current Pillow website" project begins.
