### ISSUE TITLE
Determine supported features at run time

### ISSUE THREAD

**Issue by mgedmin** [python-pillow/Pillow#1182]
Sometimes I wish I could check which of the optional features of Pillow were enabled during install time, when I no longer have the terminal with the build output open.  I'd like to be able to open a Python prompt and do something like:

```
>>> from PIL import supported_features
>>> 'ZLIB' in supported_features
True
>>> from PIL import all_features
>>> all_features - supported_features
set(['OPENJPEG'])
```

A set of strings is just an idea; I'm sure you could come up with a better API.

This may become more pressing with the release of pip 6.1.0, which [hides the output of the build script](https://github.com/pypa/pip/pull/2487).

**Comment by aclark4life** [comment]
+1, can you send a PR?

**Comment by mgedmin** [comment]
I could, if I had any idea how to test for the presence of a feature at runtime!  Can you provide any hints?

**Comment by aclark4life** [comment]
@mgedmin Hah, sure. Let's ask @wiredfool or @hugovk or @homm. Thanks

**Comment by benoit-pierre** [comment]
This is what I currently use to build a dictionary mapping `{ format name: (mime types, extensions) }` of supported image formats:

```python
def get_supported_formats():
    # Make sure all supported formats are registered.
    Image.init()
    # Not all PIL formats register a mime type,
    # fill in the blanks ourselves.
    supported_formats = {
        'BMP': (('image/bmp', 'image/x-bmp', 'image/x-MS-bmp'), []),
        'ICO': (['image/x-icon', 'image/x-ico', 'image/x-win-bitmap'], []),
        'PCX': (['image/x-pcx'], []),
        'PPM': (['image/x-portable-pixmap'], []),
        'TGA': (['image/x-tga'], []),
    }
    for name, mime in Image.MIME.items():
        mime_types, extensions = supported_formats.get(name, ([], []))
        supported_formats[name] = mime_types + [mime], extensions
    for ext, name in Image.EXTENSION.items():
        assert '.' == ext[0]
        mime_types, extensions = supported_formats.get(name, ([], []))
        supported_formats[name] = mime_types, extensions + [ext[1:]]
    # Remove formats with no mime type or extension.
    for name in supported_formats.keys():
        mime_types, extensions = supported_formats[name]
        if not mime_types or not extensions:
            del supported_formats[name]
    return supported_formats
```

Use case: build file filters for an open dialog.

Note: you can also check Image.OPEN.

**Comment by wiredfool** [comment]
Look at `selftest.py` for runtime feature detection.

**Comment by mgedmin** [comment]
I'm half-tempted to make setup.py write a _features.py [somewhere around here](https://github.com/python-pillow/Pillow/blob/888414f91e9f9b2910b8ed32f68c4c9210d6190d/setup.py#L623).

**Comment by aclark4life** [comment]
If it's easy you can submit a PR for debate. Creating a Python file during installation raises some concerns, but I'm not sure how legitimate they are. My biggest concern is probably "is this the 'right' way to provide this feature"?

**Comment by hugovk** [comment]
Required libraries can be installed or removed at any time after Pillow installation, so it's safer to abstract away and re-use the existing selftest.py functionality, rather than rely on a possibly out-of-date settings file.

**Comment by hugovk** [comment]
Implemented in https://github.com/python-pillow/Pillow/pull/1233
