### ISSUE TITLE
Improve Image.convert() documentation

### ISSUE THREAD

**Issue by d-schmidt** [python-pillow/Pillow#1186]
Trying to find a bug I noticed in the case of RGBA->P convert() it uses quantize() and ignores almost all parameters.
![s_7_rgb_p_quantize](https://cloud.githubusercontent.com/assets/3226483/7106501/25a7c486-e143-11e4-8d6d-7fbbf2eaf2ce.png) rgb.quantize(256)
![s_7_rgb_p_defaultweb_floyd](https://cloud.githubusercontent.com/assets/3226483/7106500/25a73b2e-e143-11e4-959e-da335332daf0.png) rgb.convert("P")
![s_7_rgb_p_adapt_nodither](https://cloud.githubusercontent.com/assets/3226483/7106502/25a9504e-e143-11e4-86a3-f11089c1964a.png)  rgb.convert("P", dither = Image.NONE, palette = Image.ADAPTIVE)
![s_7_rgb_p_adapt_floyd](https://cloud.githubusercontent.com/assets/3226483/7106503/25ac62c0-e143-11e4-8a3c-072c4f8cd500.png) rgb.convert("P", palette = Image.ADAPTIVE)
![s_7_rgba_p](https://cloud.githubusercontent.com/assets/3226483/7106498/2599fd56-e143-11e4-8b02-fb8f219da742.png) rgb.convert("RGBA").convert("P")
![s_7_rgb](https://cloud.githubusercontent.com/assets/3226483/7106499/259a2448-e143-11e4-8e04-6a4f19347a46.png) rgb

**Comment by radarhere** [comment]
I have created PR #3386 to resolve this.
