### ISSUE TITLE
Keep user-specified order of "sizes" when saving to .ico file

### ISSUE THREAD

**Issue by karimbahgat** [python-pillow/Pillow#1189]
I recently discovered that IcoImagePlugin.py when saving .ico files automatically changes and sorts the order of the user-specified "sizes" argument (the multiple resolutions of the .ico image). This sorting can cause problems for some consumers of the .ico file, and as far as I can tell there is no particular reason or benefit for sorting them. So I suggest leaving it up to the user which order they want to save the images in, leaving the specified list of sizes exactly as provided. Doing so is as easy as just deleting the line that does the sorting, roughly line 56. 

The issue came up when trying to make a distributable exe file with an icon using py2exe. Py2exe documentation states that for the exe icon to work the images added to the .ico file must be from largest to smallest dimension sizes. This is the opposite order of how Pillow orders them, so the resulting exe file appeared without an icon. Not sure what other use-cases care about the order of .ico resolution images, but py2exe is a fairly popular way of packaging and distributing Python programs, and it would be nice to be able to automate the exe icon creation via Pillow.

Since it is such an easy fix, is it better for you guys (the main devs, if you agree with the change) to fix this yourself, or do you prefer I fork Pillow and create a push request?

**Comment by aclark4life** [comment]
Fork and push! Thanks

**Comment by karimbahgat** [comment]
I made a pull request at #1193. Sorry for cluttering, I just didn't know how to add the pull request to this existing issue (this is the first time I've done a pull request).

**Comment by hugovk** [comment]
You've done the right thing: PRs and issues are different things. It's good to mention the issue number in the PR, but you've mentioned the PR in this issue, so it's cross-referenced them anyway.

**Comment by hugovk** [comment]
Sorting was added with save support by @exherb last year:
https://github.com/python-pillow/Pillow/commit/b38c8e0df21a0c7c616e34f124a44b312e9db56a

@exherb, Any strong reason to retain this sorting?

**Comment by exherb** [comment]
@hugovk Because in my first commit I was using thumbnail, and the image size became smaller. But after added code "tmp = im.copy()", the Sorting is actually can be removed safely.

@karimbahgat thanks

**Comment by hugovk** [comment]
@exherb Thanks!

**Comment by radarhere** [comment]
It looks like this issue can be closed?

**Comment by hugovk** [comment]
Closed.
