### ISSUE TITLE
discern if an image is animated / total number of frames

### ISSUE THREAD

**Issue by jvanasco** [python-pillow/Pillow#1190]
Right now it seems that the only way to tell if an image is animated is to use `seek()`

    def is_animated(im):
        try:
            im.seek(1)
            return True
        except EOFError:
            return False

And the only way to get the number of frames is to iterate over the frames until an EOFError is raised, or use an ImageSequence.Iterator -- both of which require a rewind via `seek(0)`.

It would be nice if images had a property (or two), which could automate this within PIL:

I'd like to suggest `Image.is_animated` and `Image.total_frames`

The reason why I suggest the two, is that `is_animated` is a trivial operation -- some formats declare that the image is animated early on, but the worst-case-scenario would only require scanning for a second frame.  I'm unfamiliar with the Pillow internals, and I don't know if iterating over all the `total_frames` would be a fast operation or not. 

It's not difficult to get this information in Python scripts, but this information seems much better suited as Image properties.

**Comment by homm** [comment]
You can check is image animated gif at least by `'loop' in image.info`. But you certainly right, should be more convenient way.

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/1261 added `n_frames()`. Would you still like an `is_animated()`?

**Comment by jvanasco** [comment]
I thought `is_animated` would be useful, because you only have to seek until a second frame is found and can then stop reading.  If you're dealing with one of those movie-like gifs that are hundreds of frames, that could be potentially much easier on the resources – though the way n_frames is implemented and Pillow manages files might make an optimization like that unnecessary.

**Comment by radarhere** [comment]
As an example, this likely applies to other formats - for PSD files, what is being counted by `n_frames` is not actually frames, but layers. I'm comfortable enough stretching the definition of 'frame' to include layers in that instance, but I'm not sure about calling a PSD file with multiple layers 'animated'.

I can see three options -
1 - Agree to stretch the definition of 'animated' to include multi-layer files.
2 - Change the name of `is_animated` to something more generic.
3 - Only add `is_animated` to some formats.

Thoughts?

**Comment by hugovk** [comment]
Also something to consider before `n_frames` is released for the first time on 1st July:

Is `n_frames` the right name?

**Comment by radarhere** [comment]
I can't think of a general name to describe both layers and frames, beyond something like 'segments' or 'parts'.

Once #1282 is merged, I'll open a PR for `is_animated` so that the code can at least be reviewed while we're still debating this.
