### ISSUE TITLE
Replace PIL.Image.DEBUG checks by logging at DEBUG level?

### ISSUE THREAD

**Issue by anntzer** [python-pillow/Pillow#1191]
All's basically in the title.  I don't have a strong argument except that it looks nicer, imo.

**Comment by homm** [comment]
+1 Pillow should use standard logging.

**Comment by aclark4life** [comment]
Anyone want to estimate LOE required?

**Comment by anntzer** [comment]
#1207 already covers most of what's needed.

**Comment by aclark4life** [comment]
Can you fix up the PR? I'll merge this right after 2.9.0
![screenshot 2015-06-29 07 31 06](https://cloud.githubusercontent.com/assets/72164/8407053/e3f10482-1e30-11e5-94ef-4961b46b14aa.png)

**Comment by radarhere** [comment]
Since the PR has been merged, this issue is complete.
