### ISSUE TITLE
Unified access to number of frames

### ISSUE THREAD

**Issue by anntzer** [python-pillow/Pillow#1192]
It would be nice if there was a unique attribute (e.g., `n_frames`) that indicated the number of frames for all multiframe image formats.  A quick look at the ImagePlugins that redefine `seek` show that many already have such an attribute, under different names.  For others (e.g. TIFF), it would have to be computed separately.

**Comment by homm** [comment]
Duplicate of #1190

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/1261 added `n_frames()`.
