### ISSUE TITLE
Problems adding plugin for image files to pil library in pillow

### ISSUE THREAD

**Issue by antonio19812** [python-pillow/Pillow#1194]
This is my problem: I have created 3 plugin file for an image extension file that is not present in the Pillow library. Then I added the 3 plugin to the pillow library package on my laptop and this works fine in windows, I can read  the file with this specific extension,l can display the image and I can get the value of each pixels.
What I do after including the plugins in the PIllow library is to import from pillow the plugin to the reader routine, so that the extension can be recognized and the file decoded
Then I had to move to Linux because I need it for my project,l have installed Pillow for my python 2.7 version with pydev in Eclipse and I did the same things I had done for windows to include the plugins in the Pillow library, but this time when I try to read the image file I obtain this message:

cannot identify image file, 

What could i do? it seems as if the Image class of Pillow can not use the plugin for the file, but in windows I have no problems

**Comment by aclark4life** [comment]
Install the development libraries then reinstall Pillow, or use OS vendor packages: http://pillow.readthedocs.org/installation.html#linux-installation

**Comment by antonio19812** [comment]
is that the reason?? Because however if at the beginning of a script i write for example:
import PIL

then digiting PIL.  ,after the dot it  automatically opens a window menu (typical of eclipse and pydev)containing all the modules of the pillow library, included the ones I have added manually .

**Comment by hugovk** [comment]
> Pillow >= 1.0 no longer supports “import Image”. Please use “from PIL import Image” instead.

https://pillow.readthedocs.org/installation.html#installation

**Comment by wiredfool** [comment]
There was a change a year or so back where we no longer automatically import anything with an ImagePlugin.py filename and require that the plugin writer import and register. Depending on versions that might be it.

**Comment by antonio19812** [comment]
well I have discovered that one of the 3 plugins I have created and added do the library is working, the problem is with the other two plugins. The difference among the 3 is not the extension, but the parameter of the decoder class

**Comment by antonio19812** [comment]
As I said, one of my 3 plugins worked properly, and it is the one for little images, of 128*128 pixels.
The other 2 plugins are for images tha can be 512*512 or  256*512 and I decided to make a debug. The three scripts while running had the same behaviour while going into Image.py until we get in the line of :
_decompression_bomb_check(im.size)

after that the two last script for reading my image return the error, while for the first plugin no problem.

**Comment by aclark4life** [comment]
Is this still an issue? If so, what exactly is the issue?

**Comment by wiredfool** [comment]
Closing, reopen if you have additional details.
