### ISSUE TITLE
Compiling on Windows with putdata() patch.

### ISSUE THREAD

**Issue by VOTProductions** [python-pillow/Pillow#1200]
Can someone please compile the latest git on Windows with https://github.com/python-pillow/Pillow/pull/1196/commits and link me the build, or least provide some instructions at least? I've been trying for days, but due to inaccurate and out of date instructions I haven't succeeded.

Thanks, VOT.

**Comment by aclark4life** [comment]
@VOTProductions Can you explain more about what you are asking for? I.e. is this a Pillow request?
 
```
"compile the latest git on Windows"
```

does not sound like something we typically handle here.

**Comment by hugovk** [comment]
@aclark4life VOT is asking for Windows binaries of the latest Pillow master with that PR applied.

@VOTProductions Unfortunately I don't have a Windows setup for compiling binaries.

**Comment by aclark4life** [comment]
@VOTProductions @hugovk Right. I'm not sure that is something we can easily provide, nor would I  expect the Pillow Project to be providing builds "on demand". However if we had something equivalent to [pillow-wheels](https://github.com/python-pillow/pillow-wheels) for Windows then it would be easy.

**Comment by VOTProductions** [comment]
No problem, it's just that compiling on Windows is difficult due to all the dependencies and lack of instructions, and I thought someone here could be able to help.

When I tried compiling myself I ended up with no support for any external library (eg no Tkinter or libjpeg) for some reason.

**Comment by wiredfool** [comment]
I would love to get a jenkins-ci server going for the windows testing and builds, but I was having problems getting a handful of the options build properly when I was working on it. We've got the resources on Rackspace, but time and expertise is the issue.

**Comment by aclark4life** [comment]
@wiredfool What resources do we have from Rackspace? I can't remember.

**Comment by wiredfool** [comment]
@aclark4life Pretty much anything in their cloud, up to some large $$/month.  More than enough to run CI and buildbots and dev machines on platforms we don't have locally. (tho, not bigendian. they don't have any of them)

**Comment by aclark4life** [comment]
@wiredfool Right! Thanks. I forgot all about this but I do have access. I'll see what I can whip up.

**Comment by wiredfool** [comment]
There's some tooling here: https://github.com/wiredfool/Pillow/tree/winbuild/winbuild   IIRC, there were a couple of things that weren't building, but the majority would build across the 5 pythons, in 32 and 64 bit versions.

**Comment by aclark4life** [comment]
Thanks. You want me to move that somewhere more appropriate?

**Comment by wiredfool** [comment]
It's a WIP. Build on it if it helps. If it does, then it would be good to move to a more prominent location.

**Comment by aclark4life** [comment]
Release in 3 days
