### ISSUE TITLE
pip install fails on win 8.1 + cygwin

### ISSUE THREAD

**Issue by w-** [python-pillow/Pillow#1201]
Hi,

I learned from https://github.com/python-pillow/Pillow/issues/560 that cygwin is not a supported platform. I'm wondering if that has changed now? (that issue is from 2014)

When I install on cygwin using pip i get errors like

    gcc -fno-strict-aliasing -ggdb -O2 -pipe -Wimplicit-function-declaration -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.x86_64/build=/usr/src/debug/python-2.7.8-1 -fdebug-prefix-map=/usr/src/ports/python/python-2.7.8-1.x86_64/src/Python-2.7.8=/usr/src/debug/python-2.7.8-1 -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -DHAVE_LIBZ -I/usr/include/freetype2 -I/tmp/pip-build-AceIfG/Pillow/libImaging -I/c/Users/guy/Envs/hippo_dev/include -I/usr/include -I/usr/include/python2.7 -c libImaging/ConvertYCbCr.c -o build/temp.cygwin-1.7.35-x86_64-2.7/libImaging/ConvertYCbCr.o
    In file included from /c/Users/guy/Envs/hippo_dev/include/Python.h:58:0,
                     from outline.c:20:
    /c/Users/guy/Envs/hippo_dev/include/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
     #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      ^
    In file included from /c/Users/guy/Envs/hippo_dev/include/Python.h:58:0,
                     from libImaging/ImPlatform.h:10,
                     from libImaging/Imaging.h:14,
                     from libImaging/ConvertYCbCr.c:15:
    /c/Users/guy/Envs/hippo_dev/include/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
     #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      ^
    In file included from /c/Users/guy/Envs/hippo_dev/include/Python.h:58:0,
                     from libImaging/ImPlatform.h:10,
                     from libImaging/Imaging.h:14,
                     from libImaging/Bands.c:19:
    /c/Users/guy/Envs/hippo_dev/include/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
     #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      ^
    In file included from /c/Users/guy/Envs/hippo_dev/include/Python.h:58:0,
                     from _imaging.c:76:
    /c/Users/guy/Envs/hippo_dev/include/pyport.h:886:2: error: #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
     #error "LONG_BIT definition appears wrong for platform (bad gcc/glibc config?)."
      ^

- Is there something I can try to resolve this build error?
- Is there an alternative to Pillow/PIL I can use?

I just need Pillow / PIL so that I can do some django development. I need it for the ImageField class of Models.

Thanks

**Comment by aclark4life** [comment]
How about using some of the native Windows packages? https://pypi.python.org/pypi/Pillow/2.8.1#downloads

**Comment by w-** [comment]
Thanks for the suggestion.
I'm pretty new to cygwin. when i install packages via pip in a cygwin terminal and they are compiled, is it actually compiling them for windows?

How might i go about using pip to install one of these dependencies (or how would i manually install this package in a virtual environment)? 
I've never done this before and not sure what i would search for.

Thanks

**Comment by aclark4life** [comment]
Re compiling: no, Cygwin is a separate computing environment that runs on top of Windows if I understand correctly; so binaries produced for Cygwin do not run without it.

Not sure what you mean by "virtual environment" but if you want to install native packages then install Python for Windows first then run easy_install or pip to install Pillow.

**Comment by w-** [comment]
just as a quick update, i attempted to install the relevant whl files
i used cp27 versions of both the win32 and win64 packages and got incorrect platform errors.

i also tried to install via the windows exe, but am not able to customize the installation directory. So i let it install to C:\Python27\libs\site-packages\
then i copied it over to my vitualenv directory.

As could be expected i ran into this issue when trying to load the library in cygwin shell:

    from PIL import Image
    ...
    ImportError: cannot import name _imaging

If i try using the windows version (by opening a command prompt and running interactive interpreter from there) it works as expected.
https://github.com/python-pillow/Pillow/issues/848

**Comment by w-** [comment]
Hmm for reference, I was originally using 64-bit cygwin.

I just tried the 32-bit version and it installed no problem.

I'd like to help document the issue for other people who might run into this but not sure what kind of information may be helpful here.

**Comment by aclark4life** [comment]
This ticket is very helpful, for starters. Are you saying we can possibly declare 32-bit Cygwin as "supported" ? Come to think of it, I could probably test this myself. Thanks for the info

**Comment by w-** [comment]
haha, might be a bit away from "supported" 
I've only successfully installed and verified no issue loading 

    from PIL import Image

in python interactive shell.

Let me know anything i can do to help. 
Thanks for maintaining Pillow and being so responsive.
