### ISSUE TITLE
Installing pillow on Centos 7

### ISSUE THREAD

**Issue by hanleyhansen** [python-pillow/Pillow#1220]
Is Centos 7 supported? It's not in the list of supported platforms but that might just be an oversight. 

I have been having issues getting it to work however.

**Comment by aclark4life** [comment]
Did it work?

**Comment by hanleyhansen** [comment]
It did work. There was a separate problem with my virualenv causing a conflict.

**Comment by aclark4life** [comment]
Cool! I'll make a note then, thanks.
