### ISSUE TITLE
Invalid transparency value where `png` tRNS contains only null byte(s)

### ISSUE THREAD

**Issue by juztin** [python-pillow/Pillow#1238]
Currently dealing with some `png` files that have null byte(s) set for the tRNS. This is causing the transparency info to be set to a `null` value as well. Downstream projects (we're using `reportlab`) rely on this being an integer.  
*(using `ImageMagick`, `Pillow`, and `ReportLab` to do conversions from `pdf` to `png` and back)*

Here's where our exception is being raised *(`utils.py` of reportlab)*:
```python
# line 891
transparency = self._image.info["transparency"] * 3
...
# line 903
return [ord(c) for c in palette[transparency:transparency+3]]
```

Since the `transparency` value is null byte(s) the above results in a `cannot concatenate 'str' and 'int' objects`  

The value is being set to null byte(s) here *(`PngImagePlugin.py` of `Pillow`)*:

```python
# Line 349
if _simple_palette.match(s): 
...
# Line 353
else:
    self.im_info["transparency"] = s
```

**Comment by hugovk** [comment]
Fixed in #1239.
