### ISSUE TITLE
Python 3.4 crashes when opening an image with Pillow and tkinter

### ISSUE THREAD

**Issue by SGB88** [python-pillow/Pillow#1241]
have no idea why but even for the simplest of scripts python crashes and I get the following message:
"ActivePython 3.4 quit unexpectedly." I'm running it on a Mac, OSX 10.7.5.

The code I'm running to test it is:

    from tkinter import * 
    from PIL import Image, ImageTk 

    root = Tk()

    image = Image.open("/Users/Name/Desktop/image.png")
    photo = ImageTk.PhotoImage(image)
    image_label = Label(root, width = 400, height = 400, image = photo)

    root.mainloop()

I think it's a problem with tkinter rather than PIL because the following code works fine:

    from PIL import Image, ImageTk 

    image = Image.open("/Users/Name/Desktop/image.png")
    image.show()

Any guesses at why this could be?

**Comment by dossan** [comment]
I have also the same problem. According to `pip3`, my version of `Pillow` is `2.8.1`, but if I `import PIL` from the `IDLE` and I check the version with:

~~~python
>>> import PIL
>>> PIL.VERSION
'1.1.7'
>>> 
~~~p

So, it seems it is a compatibility/importing problem or something similar.

If I run the script above through the terminal, I get:

    objc[19995]: Class TKApplication is implemented in both /Library/Frameworks/Tk.framework/Versions/8.5/Tk and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
    objc[19995]: Class TKMenu is implemented in both /Library/Frameworks/Tk.framework/Versions/8.5/Tk and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
    objc[19995]: Class TKContentView is implemented in both /Library/Frameworks/Tk.framework/Versions/8.5/Tk and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
    objc[19995]: Class TKWindow is implemented in both /Library/Frameworks/Tk.framework/Versions/8.5/Tk and /System/Library/Frameworks/Tk.framework/Versions/8.5/Tk. One of the two will be used. Which one is undefined.
    Segmentation fault: 11

Which seems to indicate that I have to versions of the `Tk` framework and there's a conflict.

**Comment by radarhere** [comment]
@SGB88 Perhaps this is obvious, perhaps not, but your first script is missing the
`root.mainloop()`
line at the end. This is a necessary part of Tkinter scripts, as it engages Tkinter's runtime. Without it, your Tkinter app dies when the script stops executing. The second script runs fine because you're not creating any Tkinter windows, you're merely passing on the Image instance to another program. Using MacPorts Python 3.4 on OS X 10.10.3 I find no other problems.

@dossan helping with regards to PIL VERSION at least, I can say that this is happens for everyone, and is exactly as expected and intended. The PIL version is 1.1.17, and the Pillow version is 2.8.1.

**Comment by SGB88** [comment]
Hi radarhere, sorry that was just a typo. It still crashes with root.mainloop() included.

**Comment by SGB88** [comment]
@dossan have you had any success in resolving your Python crashing issue? Do you think importing tkinter with Pillow is the problem? I'm going to try and install Qt for my GUI instead and see how I go.

**Comment by radarhere** [comment]
Hi @SGB88. I found your post on StackOverflow - http://stackoverflow.com/questions/30436924/python-3-4-crashes-when-opening-an-image-with-pil-in-tkinter

I've been using PIL (and now Pillow) with Tkinter for years, so I assure you that it is possible to get them working, and I hope that you find a solution in the end.

In StackOverflow, you include the error log, and the crash appears to happen at Tk_GetImageMasterData. That then lead me to this -
https://mail.python.org/pipermail//tkinter-discuss/2012-April/003131.html

That seems similar to what is being discussed. The way that I read the next answer is that PIL may have linked against a different Tkinter to the rest of Python -
https://mail.python.org/pipermail//tkinter-discuss/2012-April/003132.html

I've had similar problems in the past, and I know that it can be fiddly to get working. Hopefully that clue can point you in the right direction. Again, if possible, I recommend MacPorts. It manages so much of this work internally that it saves a lot of effort.

**Comment by SGB88** [comment]
Hi radarhere, thanks for your post. I'm very new to all of this and to be frank, it's quite overwhelming. I actually use MacPorts, (I think) but then I saw a post somewhere saying you should use Homebrew, so I installed that, then installed Pillow via Homebrew. I suspect now, since reading your post, that's the problem. Everything else was installed using MacPorts and then I installed Pillow with Homebrew. Problem is, as you pointed out, it's very fiddly to work the problem out. I'm thinking now I should probably uninstall Homebrew and find a way to install Pillow through MacPorts. sudo pip install Pillow?

**Comment by radarhere** [comment]
Homebrew may work wonderfully as well for all I know. MacPorts is simply the only OS X package manager that I've tried.

The MacPorts command for Python 3.4 Pillow would be
`sudo port install py34-Pillow`

`pip install Pillow` - maybe you'll need sudo, I don't know - will install Pillow with pip, but note that pip is something different again - http://en.wikipedia.org/wiki/Pip_%28package_manager%29 - it's a Python package manager, whereas MacPorts/Homebrew can install a variety of things.

**Comment by aclark4life** [comment]
Happy ending :beers:

**Comment by Oni-Shadow** [comment]
Hi !
I append to have the exact same problem on windows. I could not fix it since I did not find the System/Library/Frameworks/Tk.Framework folder, can you help me please, I am quite new to python (and git) :)
Many Thanks,
O_S

**Comment by SGB88** [comment]
Hi O_S, if you're on Windows you won't find this path as it only exists on Mac OS X.

**Comment by Oni-Shadow** [comment]
Thanks you for your answer, it is very frustrating, my code worked under Linux, but crashes under windows when writing :
photo = ImageTk.PhotoImage(image)
Any idea of what could fix it?

**Comment by radarhere** [comment]
Are you getting any output when it crashes?

**Comment by Oni-Shadow** [comment]
sorry for the late reply
well
#1st try
path = 'D:\home\Documents\Academique\Stages\OU_MS_Thesis\code\Pictures\ou_50.png'
image = Im.open(path)
photo = ImageTk.PhotoImage(file=image)
#
# error message
#
PS D:\home\Documents\Academique\Stages\OU_MS_Thesis\code> python Wgui.py
Traceback (most recent call last):
  File "Wgui.py", line 73, in <module>
    MainWindow(fenetre)
  File "Wgui.py", line 42, in __init__
    s.browseFile()
  File "Wgui.py", line 50, in browseFile
    photo = ImageTk.PhotoImage(file=image)
  File "C:\Users\Oni\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\ImageTk.py", line 84, in __init__
    image = Image.open(kw["file"])
  File "C:\Users\Oni\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\Image.py", line 2256, in open
    prefix = fp.read(16)
  File "C:\Users\Oni\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\Image.py", line 626, in __getattr__
    raise AttributeError(name)
AttributeError: read
Exception ignored in: <bound method PhotoImage.__del__ of <PIL.ImageTk.PhotoImage object at 0x00000051F453F160>>
Traceback (most recent call last):
  File "C:\Users\Oni\AppData\Local\Programs\Python\Python35\lib\site-packages\PIL\ImageTk.py", line 118, in __del__
    name = self.__photo.name
AttributeError: 'PhotoImage' object has no attribute '_PhotoImage__photo'
PS D:\home\Documents\Academique\Stages\OU_MS_Thesis\code>
 
#2md try : (withought the file=)
path = 'D:\home\Documents\Academique\Stages\OU_MS_Thesis\code\Pictures\ou_50.png'
image = Im.open(path)
photo = ImageTk.PhotoImage(image)
 
#
# Python crashes
#
