### ISSUE TITLE
Trying to seek in multipage TIFF

### ISSUE THREAD

**Issue by jakirkham** [python-pillow/Pillow#1244]
For simplicity, we try seeking to the beginning (where we already are). However, this error can be found for other locations, as well. Whether or not the mode is specified, this still fails.

```
>>> from PIL import Image
>>> im = Image.open("./ITPT044_S001_F01_002.tif", mode='r')
>>> im.seek(0)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-17-864e01ab7a06> in <module>()
----> 1 im.seek(0)

/home/kirkhamj/miniconda/envs/nanshenv/lib/python2.7/site-packages/PIL/TiffImagePlugin.pyc in seek(self, frame)
    646         # different size/mode.
    647         Image._decompression_bomb_check(self.size)
--> 648         self.im = Image.core.new(self.mode, self.size)
    649 
    650     def tell(self):

ValueError: unrecognized mode
>>> im.mode
'I;16S'
```

**Comment by hugovk** [comment]
I can't reproduce it with any of those from the test suite.

It works with multipage.tiff and multipage-lastframe.tif from https://github.com/python-pillow/Pillow/tree/master/Tests/images (Python 2.7, OS X):

```python
>>> from PIL import Image
>>> im = Image.open("multipage.tiff", mode="r")
>>> im.seek(0)
>>> im.mode
'P'
>>> 
>>> im = Image.open("multipage-lastframe.tif", mode="r")
>>> im.seek(0)
>>> im.mode
'P'
```

And it works for all the \*.tif\* files in the same directory:

```python
>>> filenames = ["10ct_32bit_128.tiff", "16bit.cropped.tif", "hopper_g4.tif", "lab.tif", "pport_g4.tif", "12bit.cropped.tif", "16bit.deflate.tif", "hopper_g4_500.tif", "multipage-lastframe.tif", "tiff_adobe_deflate.tif", "12in16bit.tif", "g4-fillorder-test.tif", "hopper_gray_4bpp.tif", "multipage.tiff", "total-pages-zero.tif", "16bit.MM.cropped.tif", "hopper.Lab.tif", "lab-green.tif", "pil136.tiff", "16bit.MM.deflate.tif", "hopper.tif", "lab-red.tif", "pil168.tif"]
>>> for filename in filenames:
...   im = Image.open(filename, mode="r")
...   im.seek(0)
...   print(im.mode, filename)
... 
('F', '10ct_32bit_128.tiff')
('I;16', '16bit.cropped.tif')
('1', 'hopper_g4.tif')
('LAB', 'lab.tif')
('1', 'pport_g4.tif')
('I;16', '12bit.cropped.tif')
('I;16', '16bit.deflate.tif')
('1', 'hopper_g4_500.tif')
('P', 'multipage-lastframe.tif')
('RGB', 'tiff_adobe_deflate.tif')
('I;16', '12in16bit.tif')
('1', 'g4-fillorder-test.tif')
('L', 'hopper_gray_4bpp.tif')
('P', 'multipage.tiff')
('1', 'total-pages-zero.tif')
('I;16B', '16bit.MM.cropped.tif')
('LAB', 'hopper.Lab.tif')
('LAB', 'lab-green.tif')
('RGBA', 'pil136.tiff')
('I;16B', '16bit.MM.deflate.tif')
('RGB', 'hopper.tif')
('LAB', 'lab-red.tif')
('RGB', 'pil168.tif')
>>> 
```

Please can you share your test file? Ideally a smallish file we can include in the test suite.

**Comment by aclark4life** [comment]
Please reopen when you provide image

**Comment by jakirkham** [comment]
Understood, unfortunately, the image is proprietary and so I cannot provide it.

**Comment by jakirkham** [comment]
@aclark4life, I have a reproducing image that is not proprietary and I would like to share with you. I found it on stackoverflow ( http://stackoverflow.com/questions/7247371/python-and-16-bit-tiff ). So, am guessing it is ok to share.

I stuck the image in my Dropbox in case the old one gets deleted. It can be found here ( https://www.dropbox.com/s/nunyt75db1mc6ve/pinei_2002300_1525_modis_ch02.tif?dl=0 ).

To reproduce, simply do the following.

    >>> from PIL import Image
    >>> im = Image.open("pinei_2002300_1525_modis_ch02.tif", mode='r')
    >>> im.seek(0)
    ---------------------------------------------------------------------------
    ValueError                                Traceback (most recent call last)
    <ipython-input-17-864e01ab7a06> in <module>()
    ----> 1 im.seek(0)
    
    /home/kirkhamj/miniconda/envs/nanshenv/lib/python2.7/site-packages/PIL/TiffImagePlugin.pyc in seek(self, frame)
        646         # different size/mode.
        647         Image._decompression_bomb_check(self.size)
    --> 648         self.im = Image.core.new(self.mode, self.size)
        649 
        650     def tell(self):
    
    ValueError: unrecognized mode
    >>> im.mode
    'I;16S'

Unfortunately, I am unable to reopen the issue as it does not give me the button to do so.

**Comment by hugovk** [comment]
Re-opened.

**Comment by jakirkham** [comment]
Thanks @hugovk.

**Comment by radarhere** [comment]
Hi. So, the problem is not actually the `seek` operation. It's just that the image isn't loaded by simply opening it, Pillow waits to load it until it needs to, which is being triggered by `seek`.

I've found the portion of code that fails to recognise the I;16S mode - and it lists 1;16, I;16L, I;16B and I;16N. I presume that I;16S was simply forgotten in that list, rather than being excluded for any particular reason.

So I've created a PR to fix the issue.

**Comment by jakirkham** [comment]
Ok, interesting and that was all that was necessary to support the TIFF in question?

**Comment by radarhere** [comment]
Working with the image that you linked to from StackOverflow, it seemed to be fixed after that, and to my mind this explains everything that's been happening. You're welcome to try and build from the branch of my PR, that should fix your problem.

Also, it would be great if you had an image that we were able to include as a test image under the Pillow license so that we could prevent this re-emerging in the future. I understand if you don't, I've been creating to create a I;16S image myself, and not experiencing any success.

**Comment by amitani** [comment]
I came across the same issue and made a tiff file causing the same issue. If necessary you can include this in the project under the Pillow license. 
https://drive.google.com/file/d/0B27UMoGK5FQxSUdtb00teGliLU0/view

For your information, the file was created using Tiff library in Matlab, which uses LibTiff. 

```
clear tagstruct

tagstruct.BitsPerSample=16;
tagstruct.SampleFormat=Tiff.SampleFormat.Int;
tagstruct.Photometric=Tiff.Photometric.MinIsBlack;
tagstruct.Compression=Tiff.Compression.None;
tagstruct.SamplesPerPixel=1;
tagstruct.PlanarConfiguration=Tiff.PlanarConfiguration.Chunky;
tagstruct.ImageLength=10;
tagstruct.ImageWidth=10;

tf=Tiff('test.tif','w');

tf.setTag(tagstruct);
tf.write(2^15*int16(eye(10)));
tf.writeDirectory;

tf.close();
```

**Comment by radarhere** [comment]
Thanks very much for the image!

**Comment by jakirkham** [comment]
> Also, it would be great if you had an image that we were able to include as a test image under the Pillow license so that we could prevent this re-emerging in the future. I understand if you don't, I've been creating to create a I;16S image myself, and not experiencing any success.

Maybe if something is published. :)

However, I think @amitani's MATLAB constructed image is probably similar enough to what I'm seeing. I may take a closer look.

**Comment by jakirkham** [comment]
Have since retested and this appears to be fixed in the latest Pillow. I'm guessing this was fixed by PR ( https://github.com/python-pillow/Pillow/pull/2748 ), correct? Feel free to close.

**Comment by wiredfool** [comment]
Yep, thanks.
