### ISSUE TITLE
Cannot instal pillow in python3.4 using pip on armhf ubuntu

### ISSUE THREAD

**Issue by pritstift** [python-pillow/Pillow#1251]
I tried to install the Pillow package for python 3.4 by executing
```sudo python3 -m pip install Pillow ```

Got ``` error: command 'arm-linux-gnueabihf-gcc' failed with exit status 1 ```. Maybe it's an problem of ```arm-linux-gnueabihf-gcc```. However, i had no problems installing the django package for example (but i do not no, whether it uses the gcc compiler)

Here goes the command line output 

https://gist.github.com/pritstift/9a9fdbad2f099f73e5ff#file-gistfile1-txt

Any idea?

**Comment by hugovk** [comment]
Did you install the prerequisites? See https://pillow.readthedocs.org/installation.html#linux-installation

**Comment by pritstift** [comment]
Well. Shame on me for not reading the docs carefully. It solved the issue. Thanks

**Comment by hugovk** [comment]
:+1:
