### ISSUE TITLE
Regression in how certain small sized ellipses are filled

### ISSUE THREAD

**Issue by follower** [python-pillow/Pillow#1252]
There has been a regression in how certain small sized ellipses are filled sometime between 2.3.0 and 2.6.1 and it is still present in 2.8.1.

The result is that the entire area is not filled--the bottom "edge" of the shape has a "bite" out of it.

Here is a magnified view of a comparison between versions--note the bottom of the green ellipse fill is incomplete in more recent versions:

![pillow-ellipse-issues-2 3 0-vs-2 6 1-vs-2 8 1](https://cloud.githubusercontent.com/assets/189962/7975968/15c74330-0a32-11e5-9da0-ae4075a715cb.png)

This was first noticed when some code that drew a small white on black ellipse was moved from Pillow 2.3.0 to Pillow 2.7.0, I then replicated the results as far back as 2.6.1 and as far forward as 2.8.1.

It does not happen at all sizes, e.g. when `size` in the test script is at (I think) 51 pixels the issue is not apparent.

The change in behaviour is very noticeable at small sizes on low resolution displays. 

(It should be noted that the original fill implementation has a bug in it--the "fill" is drawn outside the "outline" in certain places--which is no longer present in the current implementation but IMO this was less of an issue than the missing fill.)

Here are the details of where the test cases were run:

```
$ uname -a
Linux vagrant-ubuntu-trusty-64 3.13.0-46-generic #79-Ubuntu SMP Tue Mar 10 20:06:50 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux
```

```
$ python --version
Python 2.7.6
```

The test script:

```
import Image, ImageDraw
size=50

for outline_colour in [ (0,0,255), None]:
    i=Image.new("RGB",(size,size),(255,0,0))
    id_=ImageDraw.Draw(i)
    id_.ellipse(((0,0),(size-1,size)), outline=outline_colour, fill=(0,255,0))
    i.save("ellipse-%s-%soutline.png" % (Image.PILLOW_VERSION,
                                       ("no-" if not outline_colour else "")))
```

Here are the individual files output by the test script:
![ellipse-2 3 0-no-outline](https://cloud.githubusercontent.com/assets/189962/7975943/c79ced68-0a31-11e5-9ba9-be5a674aedeb.png) ![ellipse-2 3 0-outline](https://cloud.githubusercontent.com/assets/189962/7975944/c79dc3d2-0a31-11e5-8ae2-4898676f224d.png) ![ellipse-2 6 1-no-outline](https://cloud.githubusercontent.com/assets/189962/7975942/c79ca060-0a31-11e5-905c-bd2292fce101.png) ![ellipse-2 6 1-outline](https://cloud.githubusercontent.com/assets/189962/7975946/c7abdb34-0a31-11e5-8dde-6dd6127fad2b.png) ![ellipse-2 8 1-no-outline](https://cloud.githubusercontent.com/assets/189962/7975945/c7aa4706-0a31-11e5-96d7-04f95f7f6438.png) ![ellipse-2 8 1-outline](https://cloud.githubusercontent.com/assets/189962/7975947/c7ac0e56-0a31-11e5-9eb2-cabe4e054d43.png)

**Comment by follower** [comment]
Looks like it might be related to: ["Rewrite of the polygon_generic function"](https://github.com/python-pillow/Pillow/commit/cd332fc38a2320207153b73d5fecedee135adb8b)?

**Comment by hugovk** [comment]
I've not checked in detail, but that sounds the likely cause. See also the related open issue https://github.com/python-pillow/Pillow/issues/367 which still has things to be resolved, but it's not been touched in a while.

**Comment by radarhere** [comment]
Testing before and after, I agree that it's related to 'Rewrite of the polygon_generic function'.

I've created a pull request that fixes the issue.

**Comment by radarhere** [comment]
This issue can be closed now that the PR has been merged.
