### ISSUE TITLE
missing proper GIF headers when writing animated GIF

### ISSUE THREAD

**Issue by phoet** [python-pillow/Pillow#1253]
i was trying to use the [gifmaker](https://github.com/python-pillow/Pillow/blob/master/Scripts/gifmaker.py) code to spike [animated-gif support for pilbox](https://github.com/agschwender/pilbox/pull/43) but i got stuck with the GIF not looping.

as far as i can tell (which is not much) it's missing the proper headers (loop and duration) to function properly. i experimented with various things including images2gif but it seems i'm lacking some gif skills there... 

is there a proper way to create animated, looping gifs with pillow?

**Comment by hugovk** [comment]
I've just merged in @radarhere's PR for this: https://github.com/python-pillow/Pillow/pull/1172 

The next release is at the end of this month.

(See also  #1084 and #1085.)

(I've used Gifsicle before to make animated gifs. http://www.lcdf.org/gifsicle/ )

**Comment by phoet** [comment]
:+1: thx!
