### ISSUE TITLE
Add BPG support

### ISSUE THREAD

**Issue by gtors** [python-pillow/Pillow#1257]
https://en.wikipedia.org/wiki/Better_Portable_Graphics

**Comment by hugovk** [comment]
@gtors Pull requests are welcome. 

Have a look at https://pillow.readthedocs.org/handbook/writing-your-own-file-decoder.html and PIL/*ImagePlugin.py to get an idea what to do.

**Comment by Lucas-C** [comment]
Correct link to the Pillow doc: http://pillow.readthedocs.io/en/stable/handbook/writing-your-own-file-decoder.html

BPG spec: https://bellard.org/bpg/bpg_spec.txt

I'd love to spend some time on this, but won't have the time needed for now

**Comment by radarhere** [comment]
It looks like BPG was abandoned after releasing v0.9.8 in April 2018, and [never reached any browsers](https://caniuse.com/?search=bpg).

Is there still interest in this format?

**Comment by radarhere** [comment]
Closing. Let us know if there is still interest.
