### ISSUE TITLE
Plone 5.0b2 Unified Installer fails on OSX 10.10.3 with "JPEG support is not available"

### ISSUE THREAD

**Issue by pfraterdeus** [python-pillow/Pillow#1268]
I've tried a number of fixes suggested on sourceforge and elsewhere, but can't get this install to work on Yosemite.

 ./zeocluster/bin/python --version
Python 2.7.6

I think this is the correct Pillow dist?
> ls -l  buildout-cache/downloads/dist/
total 12240
...
-rw-r--r--  1 plone_buildout  plone_group   7.2M May 23 14:20 Pillow-2.7.0.zip
...

> ls -l  buildout-cache/eggs/
...
drwxr-xr-x   4 plone_buildout  plone_group   136B Jun  8 10:08 Pillow-2.7.0-py2.7-macosx-10.10-intel.egg/

| ~/Downloads/Plone-5.0b2-UnifiedInstaller-r1 @ nealta-geala (peterf) 
| => sudo ./install.sh zeo

Testing /usr/bin/python2.7 for Zope/Plone requirements....
/usr/bin/python2.7 looks OK. We will use it.
Root install method chosen. Will install for use by users:
  ZEO & Client Daemons:      plone_daemon
  Code Resources & buildout: plone_buildout
Detailed installation log being written to /Users/peterf/Downloads/Plone-5.0b2-UnifiedInstaller-r1/install.log
Installing Plone 5.0b2 at /Applications/Plone

Using dscl to create users and groups
....
....

Creating Python virtual environment.
New python executable in /Applications/Plone/zeocluster/bin/python
Installing setuptools, pip, wheel...done.
Installing zc.buildout in virtual environment.
/Applications/Plone/zeocluster/lib/python2.7/site-packages/pip/_vendor/requests/packages/urllib3/util/ssl_.py:90: InsecurePlatformWarning: A true SSLContext object is not available. This prevents urllib3 from configuring SSL appropriately and may cause certain SSL connections to fail. For more information, see https://urllib3.readthedocs.org/en/latest/security.html#insecureplatformwarning.
  InsecurePlatformWarning
You are using pip version 7.0.1, however version 7.0.3 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
Found existing buildout cache at /Applications/Plone/buildout-cache\; skipping step.
Setting /Applications/Plone ownership to plone_buildout:plone_group
Copying buildout skeleton
Building Zope/Plone; this takes a while...
Failed: JPEG support is not available.

Try preinstalling up-to-date libjpeg development libraries, then run
the installer again.
Buildout failed. Unable to continue

Installation has failed.
See the detailed installation log at /Users/peterf/Downloads/Plone-5.0b2-UnifiedInstaller-r1/install.log
to determine the cause.

less /Users/peterf/Downloads/Plone-5.0b2-UnifiedInstaller-r1/install.log

...
...# Make sure anything we've created in var is r/w by our group
find /Applications/Plone/zeocluster/var -type d -exec chmod 770 {} \; 2> /dev/null
find /Applications/Plone/zeocluster/var -type f -exec chmod 660 {} \; 2> /dev/null
find /Applications/Plone/zeocluster/var -type d -exec chmod 770 {} \; 2> /dev/null
find /Applications/Plone/zeocluster/var -type f -exec chmod 660 {} \; 2> /dev/null
chmod 754 /Applications/Plone/zeocluster/bin/*'
Unused options for setpermissions: 'update-command'.
Traceback (most recent call last):
  File "/Applications/Plone/zeocluster/bin/zopepy", line 267, in <module>
    exec(_val)
  File "<string>", line 1, in <module>
ImportError: dlopen(/Applications/Plone/buildout-cache/eggs/Pillow-2.7.0-py2.7-macosx-10.10-intel.egg/PIL/_imaging.so, 2): Symbol not found: _jpeg_resync_to_restart
  Referenced from: /Applications/Plone/buildout-cache/eggs/Pillow-2.7.0-py2.7-macosx-10.10-intel.egg/PIL/_imaging.so
  Expected in: flat namespace
 in /Applications/Plone/buildout-cache/eggs/Pillow-2.7.0-py2.7-macosx-10.10-intel.egg/PIL/_imaging.so

-----

**Comment by hugovk** [comment]
Have you installed all the prerequisites?

https://pillow.readthedocs.org/installation.html#os-x-installation

**Comment by aclark4life** [comment]
Please reopen if this is still an issue. Thanks
