### ISSUE TITLE
TIFF incorrect colours

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#1270]
In case anyone wants to investigate this, I've found a TIFF that Pillow reads with the incorrect colours.

The linked image is black text on white writing. Pillow views it as green writing on a pink background.

To reproduce, just open the image and show it.

http://www.nightprogrammer.org/wp-uploads/2013/02/multipage_tiff_example.tif

**Comment by wiredfool** [comment]
Looks like from the format key, we're interpreting this as an RGB image, but there's a tag (#530, YCbCrSubSampling) which seems to indicate that it's in YCbCr mode.

I'd have to dig deeper to see if there are any other indications that the data isn't in RGB mode.

**Comment by hugovk** [comment]
Fixed in https://github.com/python-pillow/Pillow/pull/2899.
