### ISSUE TITLE
PIL is 20!

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#1276]
On Monday 15th June 2015, the Python Imaging Library (PIL), from which Pillow is a fork, turns 20 years old!

From the [Image-SIG mailing list](https://mail.python.org/pipermail/image-sig/2005-June/003377.html) in June 2005:

> just fyi:

> $ cd pil
$ grep 1995-06 */*.c
libImaging/Convert.c: * 1995-06-15 fl   created
libImaging/Except.c: * 1995-06-15 fl   Created
libImaging/Geometry.c: * 1995-06-15 fl  Created
libImaging/Histo.c: * 1995-06-15 fl   Created.
libImaging/Storage.c: * 1995-06-15 fl   Created

> thanks to everyone who's used PIL for cool stuff for the last decade,
and everyone who's contributed cool stuff to PIL !

> cheers /F 

And checking again today:

```bash
[hugo:~/github/Pillow] master(3)+* ± grep 1995-06 */*.c
libImaging/Convert.c: * 1995-06-15 fl   created
libImaging/Except.c: * 1995-06-15 fl   Created
libImaging/Geometry.c: * 1995-06-15 fl  Created
libImaging/Histo.c: * 1995-06-15 fl   Created.
libImaging/Storage.c: * 1995-06-15 fl   Created
```

Thanks to original author Fredrik Lundh, and all the other contributors and users over the decades!

**Comment by radarhere** [comment]
Congratulations to all users and contributors! And here's to many more years of helping Python to work with images.

**Comment by aclark4life** [comment]
Awesome! :beers:
