### ISSUE TITLE
Image width/height should be accessible via named attributes

### ISSUE THREAD

**Issue by alexwlchan** [python-pillow/Pillow#1279]
Whenever I have to get the width/height of an image, it’s mildly annoying to have to use numeric indices:

```python
from PIL import Image

im = Image.open('colourful.jpeg')

width  = im.size[0]
height = im.size[1]
```

I think it would be nicer to have named attributes; i.e.

```python
width  = im.size.width
height = im.size.height
```

which would it clear exactly which attributes, and save me looking up the order every time.

Since `size` is just a regular 2-tuple, I’d suggest changing it to a namedtuple with the appropriate attribute names. I haven’t tried it yet, but it looks like this approach would be a minimal change and shouldn’t break much (any?) of the rest of the codebase.

I’m happy to have the first crack at implementing this, but before I start, I just wanted to check whether this would be sensible and/or useful. Any thoughts?

**Comment by hugovk** [comment]
No objections from me about the idea.

Or how about something a bit simpler like this?

```python
width  = im.width
height = im.height
```

Or:

```python
width  = im.width()
height = im.height()
```

**Comment by alexwlchan** [comment]
@hugovk I already implement your second approach using a monkey-patch in my PIL programs, as so:

    from PIL import Image

    def height(self): return self.size[1]
    def width(self):  return self.size[0]

    Image.Image.height = height
    Image.Image.width = width

Your first approach seems slightly better to me – if they’re attributes, somebody can set the width/height using the named parameters as well.

I’ll have a play with this over the weekend and see how far I can get with that approach.

**Comment by karstenw** [comment]
Since width and height are usually used together:

width, height = im.size

**Comment by radarhere** [comment]
I'm all for making the width and height values more accessible, but I wouldn't have thought that end users should be setting the size directly. There are methods for cropping or resizing the image.

**Comment by hugovk** [comment]
> I'm all for making the width and height values more accessible, but I wouldn't have thought that end users should be setting the size directly. There are methods for cropping or resizing the image.

Agreed.

**Comment by radarhere** [comment]
How did you go with your attempt over the weekend @alexwlchan? If just you're still getting around to it, no worries, but if you like, I'm happy to have a go.

**Comment by alexwlchan** [comment]
@radarhere Sorry, I dropped the ball on this. I've been fairly busy and haven't had time to look at it yet. Feel free to have a go.

**Comment by radarhere** [comment]
No worries. I've created the PR.

**Comment by hugovk** [comment]
#1304 merged.

**Comment by hugovk** [comment]
Oh, we should document this too!

**Comment by radarhere** [comment]
Fair enough! PR created.
