### ISSUE TITLE
Image Thumbnail

### ISSUE THREAD

**Issue by abdulMuneerM** [python-pillow/Pillow#1292]
Getting the following error when calling 'im.thumbnail()' after Image.open() in 2.8.2,
'not all arguments converted during string formatting'

**Comment by radarhere** [comment]
Are you getting this error on a specific image, or any image? If it's a specific image, uploading the file so that we can replicate the error would be very helpful.

**Comment by abdulMuneerM** [comment]
I was trying to upload the following image and it worked when switched the
version to 2.8.1.

On Sat, Jun 20, 2015 at 1:05 PM, Andrew Murray <notifications@github.com>
wrote:

> Are you getting this error on a specific image, or any image? If it's a
> specific image, uploading the file so that we can replicate the error would
> be very helpful.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-pillow/Pillow/issues/1292#issuecomment-113721055>
> .
>



-- 
*Regards,*
*Abdul Muneer M | *(+91) - 9961545350 *|* (+971) - 528094209

**Comment by radarhere** [comment]
I'm unable to replicate the error in 2.8.2 using the image you provided.

Perhaps someone else will have better luck than me, but looking at [the commit](https://github.com/python-pillow/Pillow/commit/733dda7b4e0739aa97027b53af64c165b7ba685d) of the core changes in 2.8.2, I'm having trouble seeing how that error could be generated. Are you sure that you didn't change any other part of your configuration when switching between 2.8.2 and 2.8.1?

**Comment by abdulMuneerM** [comment]
I didn't change any other part of configuration when switching from 2.8.2
to 2.8.1.

Let me try once again.

On Mon, Jun 22, 2015 at 10:50 AM, Andrew Murray <notifications@github.com>
wrote:

> I'm unable to replicate the error in 2.8.2 using the image you provided.
>
> Perhaps someone else will have better luck than me, but looking at the
> commit
> <https://github.com/python-pillow/Pillow/commit/733dda7b4e0739aa97027b53af64c165b7ba685d>
> of the core changes in 2.8.2, I'm having trouble seeing how that error
> could be generated. Are you sure that you didn't change any other part of
> your configuration when switching between 2.8.2 and 2.8.1?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-pillow/Pillow/issues/1292#issuecomment-114008827>
> .
>



-- 
*Regards,*
*Abdul Muneer M | *(+91) - 9961545350 *|* (+971) - 528094209

**Comment by hugovk** [comment]
Also unable to reproduce with Pillow 2.8.1 or 2.8.2 with Python 2.7.9 on Windws 7:


```
M:\stufftodelete>pip freeze | grep illow
Pillow==2.8.1

E:\stufftodelete>wget https://cloud.githubusercontent.com/assets/6244895/8266470/7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg
--10:10:41--  https://cloud.githubusercontent.com/assets/6244895/8266470/7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg
           => `7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg'
Resolving cloud.githubusercontent.com... done.
Connecting to cloud.githubusercontent.com[185.31.17.133]:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 343,040 [image/jpeg]

100%[====================================>] 343,040        1.75M/s    ETA 00:00

10:10:42 (1.75 MB/s) - `7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg' saved [343040/343040]


E:\stufftodelete>mv 7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg img.jpg

E:\stufftodelete>identify img.jpg
img.jpg JPEG 999x662 999x662+0+0 8-bit sRGB 343KB 0.000u 0:00.034

E:\stufftodelete>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> im = Image.open("img.jpg")
>>> im.thumbnail((100, 100))
>>> im.show()
>>> exit()

E:\stufftodelete>pip install -U pillow
Collecting pillow
  Downloading Pillow-2.8.2-cp27-none-win_amd64.whl (1.3MB)
    100% |################################| 1.3MB 375kB/s
Installing collected packages: pillow
  Found existing installation: Pillow 2.8.1
    Uninstalling Pillow-2.8.1:
      Successfully uninstalled Pillow-2.8.1
Successfully installed pillow-2.8.2

E:\stufftodelete>pip freeze | grep illow
Pillow==2.8.2

E:\stufftodelete>python
Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> im = Image.open("img.jpg")
>>> im.show()
>>> im.thumbnail((100, 100))
>>> im.show()
>>>exit()
```

**Comment by abdulMuneerM** [comment]
Please find the output using different version of Pillow.

pip list
config (0.3.9)
MySQL-python (1.2.5)
Pillow (2.8.1)

>>> from PIL import Image
>>> im = Image.open("/home/muneer/Documents/2.jpg")
>>> im.thumbnail((64,64))
>>> im.save("/home/muneer/Documents/2_thump","jpeg")

pip list
config (0.3.9)
MySQL-python (1.2.5)
Pillow (2.8.2)

>>> from PIL import Image
>>> im = Image.open("/home/muneer/Documents/2.jpg")
>>> im.thumbnail((64,64))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File
"/home/muneer/works/whatsapp-api/venv/local/lib/python2.7/site-packages/PIL/Image.py",
line 1804, in thumbnail
    im = self.resize(size, resample)
  File
"/home/muneer/works/whatsapp-api/venv/local/lib/python2.7/site-packages/PIL/Image.py",
line 1547, in resize
    self.load()
  File
"/home/muneer/works/whatsapp-api/venv/local/lib/python2.7/site-packages/PIL/ImageFile.py",
line 203, in load
    d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
  File
"/home/muneer/works/whatsapp-api/venv/local/lib/python2.7/site-packages/PIL/Image.py",
line 419, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder jpeg not available



On Mon, Jun 22, 2015 at 12:46 PM, Hugo van Kemenade <
notifications@github.com> wrote:

> Also unable to reproduce with Pillow 2.8.1 or 2.8.2 with Python 2.7.9 on
> Windws 7:
>
> M:\stufftodelete>pip freeze | grep illow
> Pillow==2.8.1
>
> E:\stufftodelete>wget https://cloud.githubusercontent.com/assets/6244895/8266470/7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg
> --10:10:41--  https://cloud.githubusercontent.com/assets/6244895/8266470/7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg
>            => `7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg'
> Resolving cloud.githubusercontent.com... done.
> Connecting to cloud.githubusercontent.com[185.31.17.133]:443... connected.
> HTTP request sent, awaiting response... 200 OK
> Length: 343,040 [image/jpeg]
>
> 100%[====================================>] 343,040        1.75M/s    ETA 00:00
>
> 10:10:42 (1.75 MB/s) - `7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg' saved [343040/343040]
>
>
> E:\stufftodelete>mv 7d7dfa96-174d-11e5-87f6-002f5d3c3f1d.jpg img.jpg
>
> E:\stufftodelete>identify img.jpg
> img.jpg JPEG 999x662 999x662+0+0 8-bit sRGB 343KB 0.000u 0:00.034
>
> E:\stufftodelete>python
> Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from PIL import Image
> >>> im = Image.open("img.jpg")
> >>> im.thumbnail((100, 100))
> >>> im.show()
> >>> exit()
>
> E:\stufftodelete>pip install -U pillow
> Collecting pillow
>   Downloading Pillow-2.8.2-cp27-none-win_amd64.whl (1.3MB)
>     100% |################################| 1.3MB 375kB/s
> Installing collected packages: pillow
>   Found existing installation: Pillow 2.8.1
>     Uninstalling Pillow-2.8.1:
>       Successfully uninstalled Pillow-2.8.1
> Successfully installed pillow-2.8.2
>
> E:\stufftodelete>pip freeze | grep illow
> Pillow==2.8.2
>
> E:\stufftodelete>python
> Python 2.7.9 (default, Dec 10 2014, 12:28:03) [MSC v.1500 64 bit (AMD64)] on win32
> Type "help", "copyright", "credits" or "license" for more information.
> >>> from PIL import Image
> >>> im = Image.open("img.jpg")
> >>> im.show()
> >>> im.thumbnail((100, 100))
> >>> im.show()
> >>>exit()
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-pillow/Pillow/issues/1292#issuecomment-114025791>
> .
>



-- 
*Regards,*
*Abdul Muneer M | *(+91) - 9961545350 *|* (+971) - 528094209

**Comment by radarhere** [comment]
That's not the error you were reporting originally though?

**Comment by abdulMuneerM** [comment]
That was the error i got when i try to send image using yowsup.

On Tue, Jun 23, 2015 at 11:46 AM, Andrew Murray <notifications@github.com>
wrote:

> That's not the error you were reporting originally though?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-pillow/Pillow/issues/1292#issuecomment-114374832>
> .
>



-- 
*Regards,*
*Abdul Muneer M | *(+91) - 9961545350 *|* (+971) - 528094209

**Comment by hugovk** [comment]
@abdulMuneerM It looks like you're missing dependencies. Have you installed them? What operating system are you using? 

Please check the instructions here https://pillow.readthedocs.org/installation.html
