### ISSUE TITLE
Problem installing Python Imaging Library

### ISSUE THREAD

**Issue by plsm** [python-pillow/Pillow#1300]
I'm installing plone version 4.1.4 which requires pillow version 1.7.6.  The installation fails with an error message.  The install log has the following line:

```
_imagingft.c:73:31: fatal error: freetype/fterrors.h: Arquivo ou diretório não encontrado
 #include <freetype/fterrors.h>
```

 My system is debian/wheezy.  I have version 2.5.2-3 of libfreetype6-dev package.  In this package the include files are in directory:

/usr/include/freetype2/fterrors.h

**Comment by radarhere** [comment]
Hi. Just as a note to others - the error message translates to 'File or directory not found'.

**Comment by wiredfool** [comment]
Pillow 1.7.x isn't supported anymore, we've had about 10 releases since then. I think the core issue is a freetype versioning issue, you're providing freetype2/*.h, it's looking for freetype/*.h. (that change may have been at the 2.1/2.2 era, but I don't recall exactly)
