### ISSUE TITLE
Image.split returns the wrong band for blue

### ISSUE THREAD

**Issue by SuperDoxin** [python-pillow/Pillow#1310]
using image.split like this:

    inimg=Image.open("test.png").convert("RGB")

    r,g,b=inimg.split()

    r.convert("RGB").save("r.png")
    g.convert("RGB").save("g.png")
    b.convert("RGB").save("b.png")

you get an unexpected and wrong result. the blue band is exactly the same as the red band.

![derp2](https://cloud.githubusercontent.com/assets/377239/8394058/a13425ce-1d28-11e5-8533-586d3d232e3c.png)

**Comment by radarhere** [comment]
I took a screenshot of part of that image, and it worked fine for me. Would you be able to attach the actual image that you're using? Thanks.

**Comment by SuperDoxin** [comment]
taking a screenshot should work entirely fine, I just made a quick image in gimp. in any case I've attached it here as well.
![test](https://cloud.githubusercontent.com/assets/377239/8398020/dcf5caf0-1de0-11e5-8b98-de29facfce7c.png)

**Comment by aclark4life** [comment]
Can't reproduce, but why are the split files not RGB?

![screenshot 2015-06-28 17 19 34](https://cloud.githubusercontent.com/assets/72164/8398376/eb477cd8-1db9-11e5-87da-7c62f531ce88.png)

**Comment by hugovk** [comment]
Also can't reproduce.

Without looking at the code, I'm guessing it's monochrome to represent Booleans of whether each pixel  contains any R, G or B.

So r.png has white for the red and white sections because the colours red and white contain red, and black for blue and green because they contain no red.
