### ISSUE TITLE
Add packaging tests to Travis CI

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1313]
Can we add tests similar to ``release-test`` target of ``Makefile`` to Travis? I shouldn't be the only one who fixes ``MANIFEST.in`` :smile: Something like

```
release-test:
	$(MAKE) install-req
	python setup.py develop
	python selftest.py
	nosetests Tests/test_*.py
	python setup.py install
	python test-installed.py
	check-manifest
	pyroma .
```

Actually, maybe only ``check-manifest``

**Comment by hugovk** [comment]
See PR #1314 to run `check-manifest`.
