### ISSUE TITLE
Make Pillow Code Citable via DOI

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#1322]
Pillow and PIL have been referenced in academic papers, for example:

https://scholar.google.com/scholar?q=%22Pillow%22+Python&btnG=&hl=en&as_sdt=0%2C5

It might be useful to make Pillow citable via Digital Object Identifiers. Here's how: https://guides.github.com/activities/citable-code/

It's done automatically via webhooks when releases are made.

Should we do this starting in time for 2.9.0?

cc @aclark4life

**Comment by aclark4life** [comment]
Nice! Let's do this in ``master`` immediately after 2.9.0 is released. So 3.0.0 will have "real" logging (#1207) and cite-ability…

**Comment by radarhere** [comment]
This looks fairly straightforward, and I would imagine it's something that any member of the core team has enough privileges to do. Shall I go ahead with it now? Or someone else can.

**Comment by aclark4life** [comment]
Please! Thanks

**Comment by radarhere** [comment]
Ah, sorry, just tried, and looks like I was too keen - it's only listing my personal repositories. Guess I don't have sufficient privileges to do this after all.

**Comment by hugovk** [comment]
I also don't have sufficient privileges.

**Comment by aclark4life** [comment]
Done! Now we need to make a release I guess.

![screenshot 2015-08-24 10 23 26](https://cloud.githubusercontent.com/assets/72164/9442503/4270e7e4-4a4a-11e5-82e9-8373362a8b37.png)

**Comment by radarhere** [comment]
Sweet, thanks.

**Comment by wiredfool** [comment]
@hugovk -- is this done for 3.0.0?

**Comment by aclark4life** [comment]
Yup

**Comment by wiredfool** [comment]
Ok, thanks.

**Comment by hugovk** [comment]
Did it work?

I don't find anything here: https://zenodo.org/search?ln=en&p=pillow&action_search=

@aclark4life What does it say for Pillow here? https://zenodo.org/account/settings/github/

Anything under "Recent Deliveries" when clicking under the hook here? https://github.com/python-pillow/Pillow/settings/hooks

**Comment by aclark4life** [comment]
Looks like I had to "draft a release" in the GitHub UI to make this work.

**Comment by hugovk** [comment]
:+1:
