### ISSUE TITLE
Add radarhere to Pillow Core Team

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1332]
@radarhere Any interest in joining the Pillow team? You've been very active lately and it would be great to have you on the team officially. Minimal responsibilities may include:

- Keep developing and improving Pillow in accordance with your current interests
- Be a "life long" (or foreseeable future-long) protector and promoter of Pillow (e.g. keep bad code out, good code in. Post Pillow propaganda on social media.)
- Give your permission to be listed as a member of the team

**Comment by wiredfool** [comment]
+1

**Comment by aclark4life** [comment]
Thanks @wiredfool. I should also add: be subjected to a vote of ``+1/-1`` by current team members CC: @hugovk @homm

**Comment by hugovk** [comment]
+1 and thanks for all the recent work!

**Comment by radarhere** [comment]
Hi. If everyone is on board with the idea, then yes, I'd be glad to join the Pillow team. It's been great to have Pillow continue the work of PIL, and I'm happy to keep giving back to it accordingly.

Thanks to those of you who have been a part of it so far!

**Comment by aclark4life** [comment]
Great! Welcome @radarhere to the team. :cake:
