### ISSUE TITLE
WebP conversion in Raspberry Pi don't get quality nor transparency

### ISSUE THREAD

**Issue by analca3** [python-pillow/Pillow#1335]
Hi! I'm developing [LaTeX2IMGbot](https://github.com/analca3/LaTeX2IMGbot) and I have a problem with Pillow. In my Raspberry Pi with RaspBMC the output is not the same that the output I get in my laptop with Archlinux. 

I'm doing test with this piece of code:

```python
#!/usr/bin/env python3 
import os
from PIL import Image

def img2webp(rutaImagen):
    file, ext = os.path.splitext(rutaImagen)
    im = Image.open(rutaImagen).convert("RGBA")
    im.save(file + ".webp", "WEBP")

img2webp(someFilename)
```

Left side is Rasbperry Pi and right is Archlinux.

![Comparison 1](http://i.imgur.com/JSBDUTo.png)

Here left - Arch and right - RaspBMC
![Comparison 2](http://i.imgur.com/xXGnA4A.png)

Rasbperry Pi don't maintain the quality and loses transparency (with white background can't appreciate).

I have installed pillow AFTER libwepb-dev in Raspberry Pi (how it must be done) but I can't understand this.

Anybody can help me? Thanks!

**Comment by radarhere** [comment]
So you've provided images to compare the outputs, which is helpful, thanks for that - would you be able to provide the original images that you're passing into the method?

**Comment by analca3** [comment]
These are the originals

![1](http://i.imgur.com/s08qiMb.png)
![2](http://i.imgur.com/gJYxJtO.png)

These are the pillow packages installed in both systems

```bash
pi@raspbmc:~/webp$ pip-3.2 freeze
Pillow==2.9.0
```
```
[antonio@Antonio-Arch ~]$ pacman -Qs pillow
local/python-pillow 2.8.2-1
    Python Imaging Library (PIL) fork. Python3 version.
local/python2-pillow 2.8.2-1
    Python Imaging Library (PIL) fork. Python2 version.
```
Thank you!

**Comment by wiredfool** [comment]
There's a version of webp that doesn't do transparency correctly, and I believe raspian was shipping it as of last year. 

Look at this test: https://github.com/python-pillow/Pillow/blob/master/Tests/test_file_webp_alpha.py#L20  and you should be able to tell if that feature is off for that reason.

**Comment by analca3** [comment]
In Arch

```bash

```

**Comment by wiredfool** [comment]
I'm not sure about a package -- there may be an unstable/dev branch of raspbian, or you could pull the source package and do a new upstream release build, or build it from source. IIRC, webp isn't tricky to build.

**Comment by analca3** [comment]
I've uninstall libwebp2 and libwebp-dev from repos, compile libwebp from [source](https://developers.google.com/speed/webp/docs/compiling#building), reinstall pillow, and the result from the test is the same... ¡but the output is perfect! libwebp in my Raspberry Pi is working like a charm.

Thank you guy!
