### ISSUE TITLE
Incorrect background color on generating thumbnail when mode is RGBA

### ISSUE THREAD

**Issue by meddulla** [python-pillow/Pillow#1345]
In the test case here https://gist.github.com/meddulla/02e032b8a2b49fac1a70, when we generate a thumbnail from the example image (at https://cld.pt/dl/download/beb8b78f-5267-4931-8e46-eeb801ff6e1a/pillow-issue/out.png) the generated image has a black background when it should have a white background. In version 2.1 this didn't happen and it can be traced to the commit 10214bc6c4e17b3e023d26878e8ba02111844fcb which basically adds 

<pre>
+        if self.mode == 'RGBA':
+            return self.convert('RGBa').transform(size, method, data, resample, fill).convert('RGBA')
+
</pre>

to the resize method in PIL/Image.py. If no conversion is done then it works in the latest version. But I'm not sure if simply removing the convert/reconvert is the correct fix..

**Comment by wiredfool** [comment]
The convert to premultiplied alpha is important for some images, so removing the conversion isn't the right fix. 

It looks like this image doesn't convert to premultiplied alpha well, or at least, doesn't convert back well.

**Comment by meddulla** [comment]
That image was generated from a pdf using ghostscript. I noticed that if we change the device from pngalpha to png16m then the conversion works. It seems that it has something to do with the alpha setting.

Here's the command we're using:

<pre>
gs -dFirstPage=1 -dLastPage=1 -q -dSAFER -dBATCH -dNOPAUSE -dNOPROMPT -dMaxBitmap=500000000 -dAlignToPixels=0 -dGridFitTT=2 -sDEVICE=pngalpha -dTextAlphaBits=4 -dGraphicsAlphaBits=4 -r131.361579304 -sOutputFile=/home/sofiabcardita/out.jpg latex-short.pdf
</pre>

The source pdf is at https://cld.pt/dl/download/beb8b78f-5267-4931-8e46-eeb801ff6e1a/pillow-issue/latex-short.pdf?download=true.

**Comment by wiredfool** [comment]
In the original, the background color is ((white), transparent), round tripping through premultiplied alpha, we get ((black), transparent).

This is one case where there's a lot of information loss, as a the color value of a fully transparent pixel in premultiplied alpha is totally lost. 

I'm not sure why fully transparent pixels are displayed differently, as imagemagick is showing the listed background color as white for both images.

**Comment by homm** [comment]
Actually, the bug is that Pillow allows to save `RGBA` image as JPEG and automatically discards alpha channel. By the way, Pillow doesn't allow the same with `LA` mode.

```python
In [8]: Image.open('../i/grayscale-alpha.png').resize((200, 200), Image.BICUBIC).save('../i/grayscale-alpha.jpg')
IOError: cannot write mode LA as JPEG

In [9]: Image.open('../i/color-alpha.png').resize((200, 200), Image.BICUBIC).save('../i/color-alpha.jpg')
```

@meddulla You need to convert the image to RGB before saving JPEG.

If you want to leave original pixels color (which can still be black under "transparency"), you may discard alpha channel by `i = i.convert('RGB')' before resizing.

If you want always get JPEG with some solid colors, you need to paste it over solid background. Like this:

```python
if image.mode in ('RGBA', 'LA'):
    background = Image.new(image.mode[:-1], image.size, fill_color)
    background.paste(image, image.split()[-1])
    image = background
```
