### ISSUE TITLE
landscape.io

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#1351]
https://landscape.io/github/python-pillow/Pillow/ - reports that the repository is no longer being checked by Landscape.

https://landscape.io/github/python-pillow/Pillow/334 - seems to be the last time that the master branch was checked, on the 6th of July.

I assume this isn't intentional.

**Comment by hugovk** [comment]
It's not intentional, looks like something changed on their side. Anyway, I signed in, clicked the thing for it to start checking and it's importing it now.

https://landscape.io/repository/72557/status

**Comment by radarhere** [comment]
Thanks!

**Comment by radarhere** [comment]
Okay, landscape has finished importing, and all is back to normal. Thanks again for looking into that.

**Comment by radarhere** [comment]
Maybe I'm missing something, but I've noticed that landscape is playing up again. This time, it was last successfully checked on 11 August. The repositories are fully synced. This time, the latest checks are stuck 'waiting'.

If there's a simple setting that I'm not seeing, please let me know. Thanks.

**Comment by hugovk** [comment]
I just logged in to Landscape.io and it suddenly started checking python-pillow/Pillow. 

I don't see any setting that's missing. Seems like a bug on their side.Their issue tracker is here: https://github.com/landscapeio/landscape-issues/

**Comment by radarhere** [comment]
Okay. I still see it as 'waiting', but fair enough, thanks.

**Comment by hugovk** [comment]
Still says waiting for me too.

**Comment by aclark4life** [comment]
Looks like their Heroku app is down, do we want to remove this badge for 3.0.0 maybe?

**Comment by radarhere** [comment]
For the sake of this issue, I'll note here that the commit to remove the landscape badge has been reverted, presumably because landscape.io is back up again.

**Comment by aclark4life** [comment]
Thanks, yeah these badges are driving me crazy. I can't seem to get consistent performance for any but the coverage badge. And by consistent performance, I mean:
- Badges consistently load & display properly within a few seconds in development & production (i.e. local, GitHub, PyPi, RTD, etc.)
I reverted because I think the problem went away and I want to re-think the whole approach to badges.

**Comment by radarhere** [comment]
I'm going to try closing this again, as landscape seems to be working. I think the problems we've experienced are nothing to do with the Pillow repository, and so there's nothing to be done here.

If the problem arises again, the issue can be re-opened.
