### ISSUE TITLE
'OutStream' object has no attribute 'readable'

### ISSUE THREAD

**Issue by ImmanuelSamuel** [python-pillow/Pillow#1364]
```
im = Image.open("fix.ppm")
ps = PSDraw.PSDraw()

box = (1*72, 2*72, 7*72, 10*72) # in points
ps.begin_document("hello")
ps.image(box, im, 75)
ps.rectangle(box)

ps.setfont("Ariel",500)
ps.text((500,500),'hello')
ps.end_document()
```

gives following error at ps.image(box, im, 75)
'OutStream' object has no attribute 'readable'

**Comment by radarhere** [comment]
I'm unable to replicate the problem. Would you be able to post the full error trace?

**Comment by zhiyu-jiang** [comment]
```
from PIL import Image
from PIL import PSDraw
​
im = Image.open("images\IMG_3114.JPG")
title = "girl"
print(im.size)
box = (1*72, 2*72, 7*72, 10*72) # in points
​
ps = PSDraw.PSDraw() # default is sys.stdout
ps.begin_document(title)
​
# draw the image (75 dpi)
ps.image(box, im, 75)
ps.rectangle(box)
​
# draw centered title
ps.setfont("HelveticaNarrow-Bold", 36)
w, h, b = ps.textsize(title)
ps.text((4*72-w/2, 1*72-h), title)
​
ps.end_document()
```











(128, 124)
%!PS-Adobe-3.0
save
/showpage { } def
%%EndComments
%%BeginDocument
/S { show } bind def
/P { moveto show } bind def
/M { moveto } bind def
/X { 0 rmoveto } bind def
/Y { 0 exch rmoveto } bind def
/E {    findfont
        dup maxlength dict begin
        {
                1 index /FID ne { def } { pop pop } ifelse
        } forall
        /Encoding exch def
        dup /FontName exch def
        currentdict end definefont pop
} bind def
/F {    findfont exch scalefont dup setfont
        [ exch /setfont cvx ] cvx bind def
} bind def
/Vm { moveto } bind def
/Va { newpath arcn stroke } bind def
/Vl { moveto lineto stroke } bind def
/Vc { newpath 0 360 arc closepath } bind def
/Vr {   exch dup 0 rlineto
        exch dup neg 0 exch rlineto
        exch neg 0 rlineto
        0 exch rlineto
        100 div setgray fill 0 setgray } bind def
/Tm matrix def
/Ve {   Tm currentmatrix pop
        translate scale newpath 0 0 .5 0 360 arc closepath
        Tm setmatrix
} bind def
/Vf { currentgray exch setgray fill setgray } bind def
%%EndProlog
gsave
226.560000 372.480000 translate
0.960000 0.960000 scale




---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-4-0d51a4f6d4f5> in <module>()
     11 
     12 # draw the image (75 dpi)
---> 13 ps.image(box, im, 75)
     14 ps.rectangle(box)
     15 

D:\Program Files (x86)\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\PIL\PSDraw.py in image(self, box, im, dpi)
    139             sy = y / im.size[1]
    140             self._fp_write("%f %f scale\n" % (sx, sy))
--> 141         EpsImagePlugin._save(im, self.fp, None, 0)
    142         self._fp_write("\ngrestore\n")
    143 

D:\Program Files (x86)\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\PIL\EpsImagePlugin.py in _save(im, fp, filename, eps)
    379     fp = NoCloseStream(fp)
    380     if sys.version_info[0] > 2:
--> 381         fp = io.TextIOWrapper(fp, encoding='latin-1')
    382 
    383     if eps:

D:\Program Files (x86)\WinPython-64bit-3.4.3.5\python-3.4.3.amd64\lib\site-packages\PIL\EpsImagePlugin.py in __getattr__(self, name)
    371 
    372         def __getattr__(self, name):
--> 373             return getattr(self.fp, name)
    374 
    375         def close(self):

AttributeError: 'OutStream' object has no attribute 'readable'

**Comment by radarhere** [comment]
Hi. Thanks for that. It shows a clearer picture of what's happening and why.

However, unless I'm missing something, OutStream is not a part of standard Python, and it's not a part of Pillow. Would you be able to determine where it is originating from?
