### ISSUE TITLE
pillow2.9, ImportError("The _imagingft C module is not installed") (whereas pillow 2.8 does not)

### ISSUE THREAD

**Issue by eggeek** [python-pillow/Pillow#1375]
##	execute flowing code
    fontpath='Arial.ttf'
    font = ImageFont.truetype(fontpath, 19)
    

## trace back
    /home/ubuntu/.virtualenvs/zsz/local/lib/python2.7/site-packages/PIL/ImageFont.pyc in truetype(font, size, index, encoding, filename)
        258
        259     try:
    --> 260         return FreeTypeFont(font, size, index, encoding)
        261     except IOError:
        262         ttf_filename = os.path.basename(font)

    /home/ubuntu/.virtualenvs/zsz/local/lib/python2.7/site-packages/PIL/ImageFont.pyc in __init__(self, font, size, index, encoding, file)
        138
        139         if isPath(font):
    --> 140             self.font = core.getfont(font, size, index, encoding)
        141         else:
        142             self.font_bytes = font.read()

    /home/ubuntu/.virtualenvs/zsz/local/lib/python2.7/site-packages/PIL/ImageFont.pyc in __getattr__(self, id)
         40     # module placeholder
         41     def __getattr__(self, id):
    ---> 42         raise ImportError("The _imagingft C module is not installed")
         43
         44 try:

    ImportError: The _imagingft C module is not installed

## in version 2.8
execute

	sudo apt-get install libfreetype6-dev
	pip uninstall pillow
	pip install pillow==2.8.2
	
can fix this problem, however, install pillow 2.9 does not work.

## *.so after install pillow

	# install pillow 2.9
	_imagingmath.so
	_imagingmorph.so
	_imaging.so	
	
	# install pillow 2.8.2
	_imagingmath.so
	_imagingmorph.so
	_imaging.so
	_imagingft.so
it's seems like pillow 2.9 miss the file '_imagingft.so'

**Comment by wiredfool** [comment]
Did you try to install libfreetype-dev package before installing pillow 2.9?

**Comment by wiredfool** [comment]
Also, see #1275
