### ISSUE TITLE
Crash converting GIF with transparency to RGB

### ISSUE THREAD

**Issue by JPLeBreton** [python-pillow/Pillow#1377]
Repro code here:

https://gist.github.com/JPLeBreton/88d475eb1c388ba3ab83

Explanation of crash is in comments.  Suggested fix: Image.py should detect if this kind of conversion is being attempted, and set the "transparency" image info key to zero (or remove it) before setting pixels to avoid the crash, given that the transparent bit will have no relevance in the resulting Image.

**Comment by radarhere** [comment]
For those interested, the simplest code required to reproduce is -

    from PIL import Image
    Image.open('grad2.gif').convert('RGB').quantize().convert('RGB')

where grad2.gif is http://vectorpoem.com/images/grad2.gif

**Comment by radarhere** [comment]
The problem seems to be that transparency is set to `(83, 138, 38)` at https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L892

**Comment by radarhere** [comment]
Okay, I've figured out a fix! If you're interested, have a look at the PR I've created.

Is `grad2.gif` an image that we can use under Pillow's license, adding it to the test image suite?

**Comment by radarhere** [comment]
Actually, never mind - I managed to create a test using one of the existing test suite images.
