### ISSUE TITLE
IOError: decoder jpeg not available

### ISSUE THREAD

**Issue by SebastienPi** [python-pillow/Pillow#1386]
Hi!

I have got this issue when I tried to use Pillow with thumbor:
> 015-08-21 18:33:41 thumbor:ERROR Could not save as improved image, consider to increase ImageFile.MAXBLOCK
> Traceback (most recent call last):
>   File "/usr/lib/python2.6/site-packages/thumbor/engines/pil.py", line 157, in read
>     self.image.save(img_buffer, FORMATS[ext], **options)
>   File "/usr/lib64/python2.6/site-packages/PIL/Image.py", line 1671, in save
>     self.load()
>   File "/usr/lib64/python2.6/site-packages/PIL/ImageFile.py", line 203, in load
>     d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
>   File "/usr/lib64/python2.6/site-packages/PIL/Image.py", line 420, in _getdecoder
>     raise IOError("decoder %s not available" % decoder_name)
> IOError: decoder jpeg not available
> 2015-08-21 18:33:41 tornado.application:ERROR Future exception was never retrieved: Traceback (most recent call last):
>   File "/usr/lib/python2.6/site-packages/tornado/gen.py", line 876, in run
>     yielded = self.gen.throw(*exc_info)
>   File "/usr/lib/python2.6/site-packages/thumbor/handlers/__init__.py", line 86, in get_image
>     self.context.request.image_url
>   File "/usr/lib/python2.6/site-packages/tornado/gen.py", line 870, in run
>     value = future.result()
>   File "/usr/lib/python2.6/site-packages/tornado/concurrent.py", line 215, in result
>     raise_exc_info(self._exc_info)
>   File "/usr/lib/python2.6/site-packages/tornado/gen.py", line 879, in run
>     yielded = self.gen.send(value)
>   File "/usr/lib/python2.6/site-packages/thumbor/handlers/__init__.py", line 396, in _fetch
>     buffer = self.context.request.engine.read(extension)
>   File "/usr/lib/python2.6/site-packages/thumbor/engines/pil.py", line 160, in read
>     self.image.save(img_buffer, FORMATS[ext])
>   File "/usr/lib64/python2.6/site-packages/PIL/Image.py", line 1671, in save
>     self.load()
>   File "/usr/lib64/python2.6/site-packages/PIL/ImageFile.py", line 203, in load
>     d = Image._getdecoder(self.mode, d, a, self.decoderconfig)
>   File "/usr/lib64/python2.6/site-packages/PIL/Image.py", line 420, in _getdecoder
>     raise IOError("decoder %s not available" % decoder_name)
> IOError: decoder jpeg not available

Self test says:
> # python selftest.py                   
> --------------------------------------------------------------------
> Pillow 2.9.0 TEST SUMMARY 
> --------------------------------------------------------------------
> Python modules loaded from /usr/lib64/python2.6/site-packages/PIL
> Binary modules loaded from /usr/lib64/python2.6/site-packages/PIL
> --------------------------------------------------------------------
> --- PIL CORE support ok
> *** TKINTER support not installed
> *** FREETYPE2 support not installed
> *** LITTLECMS2 support not installed
> *** WEBP support not installed
> *** JPEG support not installed
> *** OPENJPEG (JPEG2000) support not installed
> *** ZLIB (PNG/ZIP) support not installed
> *** LIBTIFF support not installed

Howover:
> # yum info libjpeg-turbo-devel
> Installed Packages
> Name        : libjpeg-turbo-devel
> Arch        : x86_64
> Version     : 1.2.1
> Release     : 3.el6_5
> Size        : 314 k
> Repo        : installed
> From repo   : centos6-channel
> Summary     : Headers for the libjpeg-turbo library
> URL         : http://sourceforge.net/projects/libjpeg-turbo
> License     : wxWidgets
> Description : This package contains header files necessary for developing programs which
>             : will manipulate JPEG files using the libjpeg-turbo library.

And I added a link to /usr/lib (read that when I googled the issue):
> Added ln -s
> # ls -l /usr/lib/libjpeg.so 
> lrwxrwxrwx 1 root root 21 Aug 21 15:18 /usr/lib/libjpeg.so -> /usr/lib64/libjpeg.so
> # ls -l  /usr/lib64/libjpeg.so*
> lrwxrwxrwx 1 root root     17 Aug 21 14:50 /usr/lib64/libjpeg.so -> libjpeg.so.62.0.0
> lrwxrwxrwx 1 root root     17 Aug 21 14:19 /usr/lib64/libjpeg.so.62 -> libjpeg.so.62.0.0
> -rwxr-xr-x 1 root root 262896 Dec 10  2013 /usr/lib64/libjpeg.so.62.0.0

Pillow was installed by pip. So it should be fine…

I noticed something weird:
> ls -d /usr/lib*/python2.6/site-packages/*thumbor
> /usr/lib/python2.6/site-packages/libthumbor  /usr/lib/python2.6/site-packages/thumbor
> ls -d /usr/lib*/python2.6/site-packages/*Pillow*
> /usr/lib64/python2.6/site-packages/Pillow-2.9.0.dist-info
> ls -d /usr/lib*/python2.6/site-packages/*PIL*
> /usr/lib64/python2.6/site-packages/PIL
I have got tow folders for Python in “/usr/lib” and “/usr/lib64”. Is it possible that there some king of mess with that?

Versions:
Pillow 2.9
libjpeg-turbo 1.2.1
Python 2.6.9
OS Red Hat 5.6

Thanks.

**Comment by wiredfool** [comment]
Your pillow isn't built against any libraries -- either they couldn't be found at compile time or they weren't inapstalled at the time.  Try rebuilding pillow, and save a log if it doesn't report that the JPEG support is enabled.

**Comment by SebastienPi** [comment]
Here are the logs: http://pastebin.com/Eh7nbwpm && http://pastebin.com/YrHBAcYd

**Comment by wiredfool** [comment]
In the tail end of the first paste in, it says that it's installing from a cached pip build, so you're not getting it rebuilt with any newly installed libraries.  You're going to need to clear the cache and rebuild it fresh.

**Comment by SebastienPi** [comment]
Thanks. It works with --no-cache-dir
