### ISSUE TITLE
How do I resample images using Pillow?

### ISSUE THREAD

**Issue by ferozed** [python-pillow/Pillow#1395]
I want to resample an existing image to reduce it's file size without affecting quality. I want to use Chroma subsampling, as detailed in https://en.wikipedia.org/wiki/Chroma_subsampling

Is it possible to do this out of the box, in Pillow?

**Comment by radarhere** [comment]
https://pillow.readthedocs.org/PIL.html#subsampling

**Comment by radarhere** [comment]
I'm going to close this issue. I think that the documentation link I provided is a clear answer. If there's anything else, just comment again.
