### ISSUE TITLE
Three "images" that cause PIL.Image.open() to hang

### ISSUE THREAD

**Issue by d33tah** [python-pillow/Pillow#1399]
Hello,

Here's what I found with my early afl-fuzz fuzzing:

```
(virtualenv)[1/6][14:45:24][~/workspace/Pillow/pillow-virtualenv/o/hangs]$ for file in *; do hexdump -C $file; done
00000000  50 36                                             |P6|
00000002
00000000  50 35                                             |P5|
00000002
00000000  50 79 50                                          |PyP|
00000003
```

**Comment by radarhere** [comment]
Hi. Thanks for reporting, but unfortunately I don't quite follow. Would you be able to post some Python code that reproduces the problem?

**Comment by d33tah** [comment]
```
f = open('out.jpg', 'w')
f.write('P6')
f.close()
import PIL.Image
PIL.Image.open('out.jpg')
```

Same applies for P5 and PyP.

**Comment by radarhere** [comment]
Okay. These files are detected as PPM format, and the code goes into an infinite loop when the EOF is reached prematurely.

I've created a PR to fix this.

**Comment by d33tah** [comment]
Just for the reference, link to your PR: https://github.com/python-pillow/Pillow/pull/1401
