### ISSUE TITLE
Question about image verification

### ISSUE THREAD

**Issue by AcidWeb** [python-pillow/Pillow#1408]
Is
```
img = Image.open(path)
img.verify()
img = Image.open(path)
img.load()
```
is enough to check if PNG/JPEG file is not corrupted and can be safely mangled ( :-) ) by Pillow?
Or above snippet still can pass some files that will fail later during various transformation.

**Comment by wiredfool** [comment]
Verify only checks the chunk checksums in png files, and is a no-op elsewhere.

Load will read (some of) the pixel data, and at that point, you know that the image should be ok.

The exception is if you have a multiframe image, such as an animated GIF or multipage TIFF, then the data is only read on successive seeks. 

Until the all the data is read, there's still a chance that something will go wrong.

**Comment by AcidWeb** [comment]
OK. Thank you.
