### ISSUE TITLE
3.0.0 on Oct 1

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1411]
It's that time again. 

I'm hoping to tear through a bunch of the backlog of PRs for review in the next [time period] leaving something left for stabilizing everything before we actually release a big 0.0. (and the subsequent .0.1 and .0.2 releases. )

I'm also going to try to do a bit of triage and add some priorities for those things that aren't wholly baked yet.

**Comment by aclark4life** [comment]
3.0.0!!!

**Comment by wiredfool** [comment]
Wonder what pyroma would think of 3.0.0!!!1!! as a version number.

**Comment by aclark4life** [comment]
Hah or 3.0.0 :fireworks:

**Comment by radarhere** [comment]
Okay, about ten days left now, so I'll ask it - are there any pull requests or issues that people would specifically like to see completed for this release?

**Comment by aclark4life** [comment]
Also who's doing this one? Please let me know if it's me. :smile:

**Comment by wiredfool** [comment]
I'll manage this one

**Comment by wiredfool** [comment]
Here's my triage of things. 

Looking at the PRs that are tagged 3.0.0: 

* #1431 should land, but not in its current form. 
* #1398, #1393, #1246 are minimally invasive, and should land with a bit of docs or tests. In #1246 and #1393, I'd like to see tests that test the correctness of the implementation, not just that they run and return data without crashing. 
* #1343 will land, I need one more pass through it. 
* #1388, I'm not entirely sure that we're implementing the right option, but I'd like to see it land in one form or another. 
* #1122, I'm not sure I really want to potentially destabilize just before release. I think I might put that in a post 3.0.0 merge window. Open to discussion on that one though. 

Issues:

* #1412 would require **discussion**, and probably a not terribly involved implementation. 
* #1432 I'd like to include, if there's time. 
* #1411 is kind of a given. 
* I think #1355 has been fixed. 
* #1129 has not been touched in a while.
* #1087 is also a given at this point.  
* We can probably drop #947. 
* I don't see #733 getting in

**Comment by wiredfool** [comment]
I've written some tests for #1393 and #1246.

#1393 apparently was never run prior to the PR, since it died at the sanity check level. I fixed that, but couldn't get the results to match a couple of samples from wikipedia, so I'm going to put it on hold until someone else wants to look at it. 

#1246 generally behaves ok, but there are some strange edge cases for flat colors that might indicate further bugs.

**Comment by aclark4life** [comment]
Are release notes still a thing? http://pillow.readthedocs.org/releasenotes/index.html

**Comment by wiredfool** [comment]
They should be. I've been meaning to add the Tiff Exif changes, since they're potentially breaking. Also the deprecations that were just merged.

**Comment by wiredfool** [comment]
What is viewdoc?  It's in the release-test target but it's not pip installable.

**Comment by aclark4life** [comment]
jarn.viewdoc

**Comment by wiredfool** [comment]
Is that really a useful test for prerelease?  What am I supposed to be seeing?

**Comment by aclark4life** [comment]
No idea if it's useful to you, but I use it a lot to "compile" the README. However, it's definitely not useful for Travis (if that's what you mean) because it does the equivalent of:

```
	rst2html.py README.rst > readme.html; open readme.html
```

i.e. for local viewing only

**Comment by wiredfool** [comment]
I'm wondering in the context of the release checklist. Is the compilation or the README.rst required for the release?

**Comment by aclark4life** [comment]
Only inasmuch as you care about how the release looks on PyPI.

**Comment by wiredfool** [comment]
Ok. Running the release now.

**Comment by aclark4life** [comment]
Great! Good luck & thanks :+1:

**Comment by wiredfool** [comment]
Ok, Branched, tagged and uploaded. Took a bit of beating on the .pypirc file to make it work. 

@cgohlke -- We're ready for windows binaries.

**Comment by aclark4life** [comment]
Nice work! :cake:

**Comment by wiredfool** [comment]
Thanks. I've added python 3.5 to the pillow-wheels build in a branch. We'll see if it works.

**Comment by wiredfool** [comment]
So, I hate to ask this question, but should the name of the osx wheel get even stupider now that 10.11 is released? Cause we could fit a few more versions in `Pillow-3.0.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl`

**Comment by wiredfool** [comment]
So, the python 3.5 build failed in bdist_wheel.  https://travis-ci.org/python-pillow/pillow-wheels/jobs/83200641

**Comment by timgraham** [comment]
Try updating to the latest version of wheel to resolve that issue.

**Comment by wiredfool** [comment]
It downloaded and installed wheel 0.26.0, which looks like the most recent on pypi: 

```
Collecting wheel
  Downloading wheel-0.26.0-py2.py3-none-any.whl (63kB)
    100% |████████████████████████████████| 65kB 1.1MB/s 
Installing collected packages: pip, wheel
```

**Comment by timgraham** [comment]
Okay, not sure then. I saw a similar error and that resolved it for me (https://bitbucket.org/pypa/wheel/issues/146/wheel-building-fails-on-cpython-350b3).

**Comment by wiredfool** [comment]
Thanks for the try. We'll get there. 

@aclark4life Can you upload windows binaries if we get them in the next 8 hours or so?  I'm about done for the night.

**Comment by cgohlke** [comment]
Windows binaries are at <http://www.lfd.uci.edu/~gohlke/download/Pillow-3.0.0.win-dist.zip>

**Comment by aclark4life** [comment]
Sure will do, thanks @cgohlke

**Comment by aclark4life** [comment]
Binaries are up & that's a wrap folks, thanks!

**Comment by radarhere** [comment]
Anyone mind if I close the milestone for this release?

**Comment by aclark4life** [comment]
Please do, thanks

**Comment by radarhere** [comment]
Okay, done.
