### ISSUE TITLE
ImageFont cannot support AppleColorEmoji.ttf on MAC

### ISSUE THREAD

**Issue by palanceli** [python-pillow/Pillow#1422]
I want to  convert emoji to a png on MAC, but I failed to create font. My code is below:

```python
font = PIL.ImageFont.truetype('/System/Library/Fonts/Apple Color Emoji.ttf', 16, encoding='unic')
```

I got error below:
```
  File "test.py", line 37, in TestEmoji

    font = PIL.ImageFont.truetype('/System/Library/Fonts/Apple Color Emoji.ttf', 16, encoding='unic')

  File "/Library/Python/2.7/site-packages/PIL/ImageFont.py", line 290, in truetype

    return FreeTypeFont(fontpath, size, index, encoding)

  File "/Library/Python/2.7/site-packages/PIL/ImageFont.py", line 140, in __init__

    self.font = core.getfont(font, size, index, encoding)

IOError: invalid pixel size
```

**Comment by radarhere** [comment]
Testing, I found that the following sizes work - 20, 32, 40, 48, 64, 96, 160

**Comment by radarhere** [comment]
I think that the font only supports those sizes, and so this error is valid. If you disagree, please say so. If you think the error should be a different one, please say so, and the issue can be re-opened.

For the moment however, I think there is nothing to do here, and this can be closed.

**Comment by freeIsa** [comment]
Just found the same issue.

> Testing, I found that the following sizes work - 20, 32, 40, 48, 64, 96, 160

Just to be clear, is there any way to make it work with "arbitrary" sizes?

**Comment by nulano** [comment]
The FreeType library, which Pillow uses to handle fonts, doesn't allow scaling of bitmap fonts. The only option is to render at a supported size and scale the output yourself.

**Comment by NightMachinary** [comment]
The emojis are rendered black and white. Is this intended? It also can't render any normal text ...

**Comment by NightMachinary** [comment]
The color support can be fixed with https://github.com/python-pillow/Pillow/pull/4955 .

**Comment by jdhao** [comment]
For anyone interested, you may need to loop through different font sizes to find the correct size to use for the color font.

I tried the apple color emoji provided [here](https://github.com/samuelngs/apple-emoji-linux/releases). It seems that only 137 is the valid size. The following works:

```
unicode_font = ImageFont.truetype(r"E:\AppleColorEmoji.ttf", 137)
```

**Comment by luisadrianpuga** [comment]
> 96

thank you

**Comment by braveltd** [comment]
> For anyone interested, you may need to loop through different font sizes to find the correct size to use for the color font.
> 
> I tried the apple color emoji provided [here](https://github.com/samuelngs/apple-emoji-linux/releases). It seems that only 137 is the valid size. The following works:
> 
> ```python
> unicode_font = ImageFont.truetype(r"E:\AppleColorEmoji.ttf", 137)
> ```

same for me, only works on 137 size
