### ISSUE TITLE
Wheel does not work on Debian Jessie (8.x)

### ISSUE THREAD

**Issue by docapotamus** [python-pillow/Pillow#1448]
I have an issue on Debian Jessie where installing from the wheel does not work.

- If I install from the wheel my tests fail when processing various images.
- If I install the build dependencies first with `python build-dep python-pil` install the wheel it still does not work.
- If I install the dependencies and the `pip install Pillow --no-use-wheel` all the tests pass fine.

Is this to be expected? I am have to install all my requirements with `--no-use-wheel` on deployment just so Pillow gets build correctly. This does not happen on OS X. I presume it is the nature of wheels being pre-build just wondering if there is a work around.

I have searched around but to no avail. Not sure if everyone has moved to Jessie just yet.

Thanks in advance for any information.

**Comment by wiredfool** [comment]
We don't distribute wheels for linux, only for OSX and Windows.  What wheel are you using?

**Comment by docapotamus** [comment]
@wiredfool it has taken your comment for me to see the issue.

On all the boxes I am developing on I have installed Pillow before the dependencies. Without following the way `pip` has changed over the last while it is creating and caching a wheel in to `~/.cache/pip/wheels`. Even after uninstalling Pillow, installing the dependencies it was still using this wheel.

I never used `-v` in `pil` to see what was happening so it looked like it was just installing Pillow from a wheel.

Thanks for your help.

**Comment by wiredfool** [comment]
Ah, I see.  We've run into that before, and I think that there's a note in the docs about it.  There's also a patch in 3.0 that should prevent people from accidentally installing without and of the dependencies installed.

**Comment by docapotamus** [comment]
That will be amazing. It's the first time I've run into this. I'm glad I have though as I often neglect `pip` and simply install from requirements.
