### ISSUE TITLE
Python 3.5/3.6/3.7 on Appveyor

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1455]
We should be testing on Python 3.5 on Appveyor. This is going to take adding the new compiler info into the config.py structures and testing it on Visual Studio 2015.

**Comment by wiredfool** [comment]
Also, we should save n days of nightlies or merges to master,

**Comment by radarhere** [comment]
Maybe this was already the case when you created the issue, but Python 3.5.0 is now up on AppVeyor.

**Comment by wiredfool** [comment]
Yes, the real issue is getting all the settings right for a build using VS2015.

**Comment by aclark4life** [comment]
Seems like @cgohlke made a comment about AppVeyor recently, not sure if this is related.

**Comment by wiredfool** [comment]
Really, this time. I want this to work.

**Comment by hugovk** [comment]
VS 2015 can be used for Python 3.5-3.7:


Python version	Visual Studio
Python 2.7	VS 2008 and VS 2010
Python 3.4	VS 2010
Python 3.5 and 3.6	VS 2015
Python 3.7 (master)	VS 2015 or VS 2017

http://pythondev.readthedocs.io/windows.html

**Comment by hugovk** [comment]
Brilliant, thanks and https://github.com/python-pillow/Pillow/pull/3399 merged!

The second bit can be done with "artifacts":

https://www.appveyor.com/docs/packaging-artifacts/

https://ci.appveyor.com/project/python-pillow/pillow/settings/artifacts

They're kept for 6 months, which should be plenty. They can be copied to external storage like S3, which might be useful later, but for now AppVeyor's own storage should suffice.

Which files and folders should be included?

**Comment by hugovk** [comment]
Hang on, we already have artifacts enabled!

Added in https://github.com/python-pillow/Pillow/pull/1818 and https://github.com/python-pillow/Pillow/pull/1927:

https://github.com/python-pillow/Pillow/blob/07645bd82878a12af70b00698805f650c2548c60/.appveyor.yml#L94-L120

Here's a `Pillow-5.4.0.dev0-py3.7-win32.egg` and `Pillow-5.4.0.dev0-cp37-cp37m-win32.whl` from a recent build:

https://ci.appveyor.com/project/python-pillow/pillow/build/job/i8yyorldevfyotcr/artifacts
