### ISSUE TITLE
TypeError in ImageFile.py?

### ISSUE THREAD

**Issue by 2grep** [python-pillow/Pillow#1463]
These are lines excerpted from Google's deepdream.ipynb notebook:
```
from io import StringIO
import PIL.Image

def showarray(a, fmt='jpeg'):
    a = np.uint8(np.clip(a, 0, 255))
    f = StringIO()
    PIL.Image.fromarray(a).save(f, fmt)
    display(Image(data=f.getvalue()))

img = np.float32(PIL.Image.open('sky1024px.jpg'))
showarray(img)
```
and this is what I get back
```
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-20-1b0ac20ca6d1> in <module>()
      1 img = np.float32(PIL.Image.open('sky1024px.jpg'))
----> 2 showarray(img)

<ipython-input-7-87a628791553> in showarray(a, fmt)
     21     a = np.uint8(np.clip(a, 0, 255))
     22     f = StringIO()
---> 23     PIL.Image.fromarray(a).save(f, fmt)
     24     display(Image(data=f.getvalue()))

~/anaconda/lib/python2.7/site-packages/PIL/Image.pyc in save(self, fp, format, **params)
   1701 
   1702         try:
-> 1703             save_handler(self, fp, filename)
   1704         finally:
   1705             # do what we can to clean up

~/anaconda/lib/python2.7/site-packages/PIL/JpegImagePlugin.pyc in _save(im, fp, filename)
    695     bufsize = max(ImageFile.MAXBLOCK, bufsize, len(info.get("exif", b"")) + 5)
    696 
--> 697     ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
    698 
    699 

~/anaconda/lib/python2.7/site-packages/PIL/ImageFile.py in _save(im, fp, tile, bufsize)
    481             while True:
    482                 l, s, d = e.encode(bufsize)
--> 483                 fp.write(d)
    484                 if s:
    485                     break

TypeError: unicode argument expected, got 'str'
ipdb> type(d)
<type 'str'>
```

I'm just a biology nerd trying to learn some ML, so I have to admit, I'm a little hesitant on which way to go with this. While `d` is a `str`, it looks like it's really a whole bunch of things and I haven't figured out how PIL actually works all the way down. Is this the fingerprint of a rookie mistake or is this a real issue? Thoughts?

**Comment by wiredfool** [comment]
I've checked back to Pillow 2.3.0, and I don't see this ever having worked. (and I can't easily check back from there without uninstalling some dependencies). So at least it's nothing new.

**Comment by 2grep** [comment]
By "this", do you mean passing a `StringIO` object into `Image.fromarray(a).save`, or something else? It did work when I imported `StringIO` from `cStringIO` instead of importing it from `io`. Would love to hear your thoughts on why that might be. Working through with some pdb traces but I'm sure you know more about this than pdb can ever teach me.

**Comment by wiredfool** [comment]
'This' being essentially that excerpt from google's notebook. I haven't gone farther than determining that it's not due to the release we made last week.

**Comment by kmike** [comment]
I think it makes zero sense to support io.StringIO in Pillow. io.StringIO is for unicode data, Pillow should output bytes. Error message can be better, but the behaviour looks correct. It looks like a bug in the notebook.

In Python 3 it should be io.BytesIO; in Python 2 it should be either io.BytesIO or [c]StringIO.StringIO.

**Comment by wiredfool** [comment]
Ah. I totally missed the io.StringIO vs StringIO.StringIO. Too close to the 'everything's burning' part of the release process, I guess. 

@kmike has it, io.StringIO objects aren't going to work. It's either StringIO.Stringio or io.BytesIO.
