### ISSUE TITLE
AppVeyor URL Change Please

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1468]
Can whoever has access to AppVeyor (@wiredfool?) please change the URL from:
- https://ci.appveyor.com/project/Pythonpillow/pillow
To:
- https://ci.appveyor.com/project/python-pillow/Pillow

Or add me to the project so I can do it? Thank you!

**Comment by wiredfool** [comment]
Will do when I get back to keyboard.

**Comment by wiredfool** [comment]
I've changed the username to python-pillow, and added the pillow team as administrators there. Use this power for good. 

I think these options are new, or I would have added them originally. 

ping @homm, @hugovk, @radarhere

**Comment by aclark4life** [comment]
Thanks! Looks good
