### ISSUE TITLE
Not possible to install Pillow with TKINTER support in Ubuntu 14.04.3 LTS

### ISSUE THREAD

**Issue by gonvaled** [python-pillow/Pillow#1473]
This is my situation:

My system is (pretty standard):
```
» lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty
```

I have installed the required libraries:
```
sudo apt-get install python-tk tk8.5-dev tcl8.5-dev tk8.5 tcl8.5
```

New virtualenv:

```
» virtualenv venv
» . venv/bin/activate
» python --version
Python 2.7.6
» which python
.../venv/bin/python
» ls venv/lib/python2.7/lib-dynload/_tkinter.so 
venv/lib/python2.7/lib-dynload/_tkinter.so
```

Version 3.0.0 of Pillow:

```
» git checkout 3.0.0
» make clean
...
» make
...
```

But tkinter support is just not there:
```
» python selftest.py
--------------------------------------------------------------------
Pillow 3.0.0 TEST SUMMARY 
--------------------------------------------------------------------
Python modules loaded from xxx/Pillow/PIL
Binary modules loaded from xxx/Pillow/PIL
--------------------------------------------------------------------
--- PIL CORE support ok
*** TKINTER support not installed
--- FREETYPE2 support ok
*** LITTLECMS2 support not installed
*** WEBP support not installed
--- JPEG support ok
*** OPENJPEG (JPEG2000) support not installed
--- ZLIB (PNG/ZIP) support ok
--- LIBTIFF support ok
--------------------------------------------------------------------
Running selftest:
--- 57 tests passed.
```

What else can I check? Is there a workaround?

**Comment by hugovk** [comment]
Travis CI also uses Ubuntu 12.04 LTS and has Tkinter support:
https://travis-ci.org/python-pillow/Pillow/jobs/83681587#L1757

The Travis setup doesn't use `make`, so perhaps there's a problem with the makefile

Try something like this:
```
python setup.py clean
python setup.py build_ext --inplace
```

https://github.com/python-pillow/Pillow/blob/master/.travis.yml#L44-L45

**Comment by wiredfool** [comment]
Travis uses 12.04, he's wondering about 14.04.

**Comment by gonvaled** [comment]
I think I have detect the problem: the _tkinter shared object shipped with ubuntu has version 8.6, and I was installing tk8.5-dev. Installing tk8.6-dev seems to solve the problem.

**Comment by wiredfool** [comment]
I'm not sure how to find that info, but you're welcome to submit a PR if you can figure it out.

**Comment by wiredfool** [comment]
So, apparently we're reporting this in the setup summary, but not the selftest thingy. Shows how much I'm paying attention. 

```
$ pip install pillow
[tons of stuff deleted]
    --------------------------------------------------------------------
    PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 3.0.0
    platform     linux2 2.7.6 (default, Jun 22 2015, 18:00:18)
                 [GCC 4.8.2]
    --------------------------------------------------------------------
    *** TKINTER support not available
    (Tcl/Tk 8.6 libraries needed)
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    --- LIBTIFF support available
    --- FREETYPE2 support available
    --- LITTLECMS2 support available
    *** WEBP support not available
    *** WEBPMUX support not available
    --------------------------------------------------------------------
```

**Comment by gfairchild** [comment]
I'm running Debian 8.2, and I can't get Tkinter or OpenJPEG working, despite having both `tk8.6-dev` (which includes `tcl8.6-dev`) and `libopenjpeg-dev`.

In a [blog post I just wrote about installing Pillow's requirements](http://www.gfairchild.com/2015/10/08/installing-the-requirements-for-pillow-3-on-debian/), I suspect I can't get OpenJPEG working because the version that comes with Debian is too old. That's reasonable. But I don't understand why Tkinter support isn't working.

**Comment by wiredfool** [comment]
The installation docs http://pillow.readthedocs.org/en/3.0.x/installation.html don't have Debian specifically called out, but it's likely a similar set to Ubuntu 14.04:  
```
sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk```
```

OpenJpeg in the Debian packages is too old, and I don't think they have any desire to update it. There's a script in the `depends` directory that we use to install it on travis (as we have for webp, since iirc, that one's pretty old in the debian repos as well).

**Comment by gfairchild** [comment]
Ah, ok, `python-tk` looks like it might be the package I'm missing. I've installed all the others. I'll see about trying that when I'm back in the office next week. Thanks!

**Comment by wiredfool** [comment]
I'm working on a little something for this in my depends branch: https://github.com/wiredfool/Pillow/tree/depends

**Comment by gfairchild** [comment]
Those changes to the docs look great. Thanks @wiredfool!
