### ISSUE TITLE
Can't get GPS information in exif - Ver.3.0.0

### ISSUE THREAD

**Issue by hMatoba** [python-pillow/Pillow#1477]
I executed below scirpt with pillow 2.9.0:

    from PIL import Image
    i = Image.open(r"tests\images\01.jpg")
    e = i._getexif()
    for key in sorted(e):
        print(str(key) + ": " + str(e[key]))

I got below:

```
258: (24, 24, 24)
271: Make
272: XXX-XXX
282: (4294967295, 1)
296: 65535
305: PIL
514: 4294967295
33434: (4294967295, 1)
34665: 185
34853: {0: b'\x00\x00\x00\x01', 2: (4294967295, 1), 5: 1, 30: 65535, 29: '1999:99:99 99:99:99'}
34856: b'\xaa\xaa\xaa\xaa\xaa\xaa'
34867: 4294967295
36867: 2099:09:29 10:10:10
41994: 65535
42034: ((1, 1), (1, 1), (1, 1), (1, 1))
42035: LensMake
```

With 3.0.0, I got below:

```
258: (24, 24, 24)
271: Make
272: XXX-XXX
282: 4294967295.0
296: 65535
305: PIL
514: 4294967295
33434: (4294967295.0,)
34665: 185
34853: (366,)
34856: (b'\xaa\xaa\xaa\xaa\xaa\xaa',)
34867: (4294967295,)
36867: ('2099:09:29 10:10:10',)
37380: (-0.9999999995343387,)
41994: (65535,)
42034: (1.0, 1.0, 1.0, 1.0)
42035: ('LensMake',)
50715: (1.0, 1.0, 1.0)
```

"34853" is a pointer to the GPS information IFD. Ver.2.9.0, it can get GPS informations as dict type.
Ver.3.0.0, it is a int value in tuple(pointer value?).
I looked for about this issue in CHANGES and couldn't find any information.

![01](https://cloud.githubusercontent.com/assets/4497270/10332838/f720c3f6-6d1a-11e5-99f7-25fc31c2133d.jpg) <- JPEG image I used this example.

**Comment by hugovk** [comment]
Looks like a bug, probably similar to https://github.com/python-pillow/Pillow/pull/1465

**Comment by hugovk** [comment]
@hMatoba Please may we include that JPEG in our test suite, under the Pillow MIT-like licence?

**Comment by hMatoba** [comment]
Okay.

**Comment by hugovk** [comment]
Test and possible fix in this branch: https://github.com/hugovk/Pillow/tree/1477_exif_jpeg

`test_exif_gps` passes with Pillow 2.9.0 and fails as expected with 3.0.0. But it also fails with the fix because the returned dict is slightly different.

```python
    def test_exif_gps(self):
        # Arrange
        im = Image.open('Tests/images/exif_gps.jpg')
        gps_index = 34853
        expected_exif_gps = {
            0: '\x00\x00\x00\x01',
            2: (4294967295L, 1),
            5: '\x01',
            30: 65535,
            29: u'1999:99:99 99:99:99'}

        # Act
        exif = im._getexif()

        # Assert
        self.assertEqual(exif[gps_index], expected_exif_gps)
```

In 2.9.0 `exif[gps_index]` is the dict in `expected_exif_gps`, but for the fix it's:
```python
        {
            0: (0, 0, 0, 1),
            2: (4294967295.0,),
            5: (1,),
            30: (65535,),
            29: (u'1999:99:99 99:99:99',),}
```

For reference, the image's GPS data from Irfanview:
```
GPS information: - 
GPSVersionID - 0.0.0.1
GPSLatitude - -1  0.85  1.00 (-0.985556)
GPSAltitudeRef - Sea level
GPSDateStamp - 1999:99:99 99:99:99
```

Any ideas?

**Comment by wiredfool** [comment]
Ok, I think this may be a v1/v2 thing. There's going to be more to fix it, but you're on the right track.

**Comment by hugovk** [comment]
I think I've found the problem: type should be long instead of byte.
```python
    34853: ('GPSInfoIFD', 4, 1),
```

**Comment by wiredfool** [comment]
Where are we on this one?

**Comment by hugovk** [comment]
No further than above.

**Comment by wiredfool** [comment]
Ok, I think this might be the last thing in the queue for 3.0.1.  I'll take a look when I can.

**Comment by Erotemic** [comment]
I'm getting a similar error as well. 

on this image: http://images.summitpost.org/original/769474.JPG

I get the exifdict, and the GPS tag returns a tuple with an integer in it. Whereas in old versions of PIL I get a dictionary with information. 

pil_img = Image.open('769474.JPG')
exif_dict = pil_img._getexif()
EXIF_TAG_TO_TAGID = {val: key for (key, val) in six.iteritems(TAGS)}
GPSINFO_CODE = EXIF_TAG_TO_TAGID['GPSInfo']
gps_info = exif_dict[GPSINFO_CODE]

In 2.6.1 I get 
{0: '\x02\x03\x00\x00',
 1: u'N',
 2: ((41, 1), (53, 1), (23487, 1000)),
 3: u'E',
 4: ((12, 1), (29, 1), (10362, 1000)),
 5: '\x00',
 6: (56819, 1000),
 7: ((15, 1), (7, 1), (33998, 1000)),
 9: u'A',
 10: u'3',
 11: (13552, 10000),
 12: u'K',
 13: (955, 1000),
 14: u'T',
 15: (34442, 100),
 16: u'M',
 17: (4775, 100),
 18: u'WGS-84',
 29: u'2011:12:31',
 30: 0}

And in 3.0.0 I get 
(13254,)

**Comment by pauloxnet** [comment]
I had to downgrade to Pillow 2.9.0 because this bug.

I hope it will be fixed soon on Pillow 3.0.1

**Comment by wiredfool** [comment]
@hugovk & others -- Here's something that passes the tests on both 2.9.0 and this branch:  https://github.com/wiredfool/Pillow/tree/1477_exif_jpeg

This is backing it out to v1 results. We should probably check some of the other exif info to see if we're getting what we think we should be getting.

**Comment by hugovk** [comment]
Fixed in https://github.com/python-pillow/Pillow/pull/1619.

**Comment by wiredfool** [comment]
For everyone who's interested in the exif handling in Pillow, Please test the new 3.1.0-rc1 release soon and give feedback.
