### ISSUE TITLE
Not able to install Pillow on my virtualenv running python3.4-devel

### ISSUE THREAD

**Issue by d3prof3t** [python-pillow/Pillow#1481]
Just have a look at this:

https://gist.github.com/d3prof3t/656b1bf7a9de0750a98d

**Comment by radarhere** [comment]
Hi. This seems to be a duplicate of #1457. To quote one of the replies from over there -

Do you have libjpeg installed? See https://pillow.readthedocs.org/en/3.0.0/installation.html#linux-installation for instructions.

If not, and if you don't want libjpeg, use the --disable-jpeg build flag. More: https://pillow.readthedocs.org/en/3.0.0/installation.html#build-options

**Comment by d3prof3t** [comment]
Thanks, it workded!.
