### ISSUE TITLE
3.0.1

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#1484]
There have been commits on the 3.0.x branch since the 3.0.0 branch, so I presume this indicates a plan to release 3.0.1. I don't believe it's been discussed directly anywhere else, so I thought I'd start an issue.

What needs to be resolved before it can be released?

**Comment by wiredfool** [comment]
Regressions mostly.

I think I've tagged most of them, but there's still the gps exif one to get working.  I don't think I've cherry picked the iccprofile one either. 

I'm also thinking that a better error for missing libjpeg might be in order as well.

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/issues?utf8=%E2%9C%93&q=milestone%3A3.0.1

**Comment by wiredfool** [comment]
I've cherry-picked the iccprofile fix.

**Comment by radarhere** [comment]
@hugovk thanks for pointing out the milestone. I had noticed it previously, but clearly forgot about it when creating this issue.

**Comment by jaddison** [comment]
Can I recommend including #1497?

**Comment by radarhere** [comment]
Just asking - is there some point at which 3.0.1 is abandoned and instead incorporated into 3.1?

**Comment by wiredfool** [comment]
I'm not sure. 3.0.1 has never felt finished, as there's been regressions that aren't confirmed fixed yet, and I wanted to get it done in one shot. However, I'd really like to get them nailed before 3.1, as I'd hate to have two kinda broken releases on top of each other. 

I've been pretty slammed at work this past month and a half, so I haven't been able to push things forward or review like I'd like to.

**Comment by radarhere** [comment]
Any further thoughts?

**Comment by wiredfool** [comment]
Not gonna happen. We move on, with a bigger digit. Or at least a leftward one.

**Comment by radarhere** [comment]
Anyone mind if I delete the 3.0.1 milestone?
