### ISSUE TITLE
Wrong version number 2.6.1 in docs titles

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#1494]
The built docs have the wrong version number in the title. For example:

https://pillow.readthedocs.org/en/3.0.x/ 
`<title>Pillow &mdash; Pillow (PIL Fork) 2.6.1 documentation</title>`

https://pillow.readthedocs.org/en/3.0.x/installation.html
`<title>Installation &mdash; Pillow (PIL Fork) 2.6.1 documentation</title>` 

---

The default is defined <a href="https://github.com/python-pillow/Pillow/blob/3.0.x/docs/conf.py#L126-L128">here</a>:

```python
# The name for this set of Sphinx documents.  If None, it defaults to
# "<project> v<release> documentation".
#html_title = None
```

[Where](https://github.com/python-pillow/Pillow/blob/3.0.x/docs/conf.py#L62):
```python
release = PIL.PILLOW_VERSION
```

But [this looks correct](https://github.com/python-pillow/Pillow/blob/3.0.x/PIL/__init__.py#L15):
```python
PILLOW_VERSION = '3.0.0'  # Pillow
```

And I don't see any `2.6.1` text in the repo.

**Comment by wiredfool** [comment]
It's got to be something at RTD, since building the docs locally shows 3.1.0.dev

**Comment by jwilk** [comment]
I guess the problem is that conf.py doesn't ensure that the PIL it imports is actually the version you're building documentation for.
So if PIL 2.6.1 was installed on the RTD builder, that number would end up in the documentation.

**Comment by radarhere** [comment]
Well, if you look at the Sphinx and readthedocs issues I've created in relation to this, they both believe that it's the other's responsibility.

However, in the Sphinx issue, they mentioned that they "clicked Build version: 3.1.x on ReadTheDocs", and now the version number is correct in the titles once more. So the immediate issue is fixed at least.

**Comment by hugovk** [comment]
Thanks for chasing up!

Closing.
