### ISSUE TITLE
_imagingtiff is gone?

### ISSUE THREAD

**Issue by msarahan** [python-pillow/Pillow#1498]
I'm building Pillow on Windows, and old tests check for import of _imagingtiff.  I found that this particular bit isn't being built, and ultimately traced it back to _imagingtiff.c no longer existing.  When was this change made?  Is tiff no longer supported?  Can the stuff aobut _imagingtiff.c be removed from setup.py?

**Comment by wiredfool** [comment]
Tiff is still there, but support has changed quite a bit from the PIL days.  I'm not aware of the _imagingtiff.c file, I don't really remember it from the old package, and I don't see it in the initial import here.

If you can use the prebuilt packages, I'd highly recommend going with them, as building on windows is kind of a pain, especially getting all the dependencies working.

**Comment by hugovk** [comment]
`git log -- _imagingtiff.c` (and `git log -1 -- _imagingtiff.c` should show when it was deleted, but I don't get anything when I run it.

I also don't see the file in any of the PIL 1.1.1 to 1.1.7 releases: https://github.com/hugovk/PIL/commits/master

**Comment by msarahan** [comment]
Thanks, both of you.  I build packages for Continuum Analytics' Anaconda distribution.  We'd like to maintain the ability to build from source, rather than depend on someone else to build binaries for us.

I guess this is long vestigial code.  I'll see about a PR to clean up setup.py.

**Comment by hugovk** [comment]
@msarahan I've made a PR here: #1499.

**Comment by wiredfool** [comment]
Fwiw, our testing Windows builds are run by the appveyor.yml  file, using the scripts in winbuild.  They should give you a starting point.

**Comment by wiredfool** [comment]
Just realized that you're building Anaconda, not building _on_ it. 

This is good, I'd like to have as many independent builds as possible, especially since it's such a pain on Windows and the current bus factor is pretty low.

**Comment by msarahan** [comment]
Great, I'll be happy to participate.  Please ping me if you run across issues I might be able to help with.
