### ISSUE TITLE
Issue with Pillow 2.9 and Pillow 3.0 

### ISSUE THREAD

**Issue by sa35t** [python-pillow/Pillow#1502]
I am facing issue with pillow 2.9 and pillow 3.0 while working with following code which meant for converting **webp** image to **jpg** image

Here is my code 

```python
from PIL import Image
im = Image.open("2_webp_a.webp").convert("RGB")
im.save("test.jpg","jpeg")
```
File: https://www.gstatic.com/webp/gallery3/2_webp_a.webp

After executing above code I am getting following error
```python
Traceback (most recent call last):
  File "webptopng.py", line 3, in <module>
    im = Image.open("unnamed.webp").convert("RGB")
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 2330, in open
    % (filename if filename else fp))
IOError: cannot identify image file '2_webp_a.webp'
```
> Tried with pillow 2.9 and pillow 3.0 

Please help me to resolve this issue

**Comment by wiredfool** [comment]
Most likely explanation is that you don't have the webp dependencies installed. 

try:

``` 
from PIL import features
print (features.check_module('webp'))
```

**Comment by sa35t** [comment]
I am getting `True` for above command

**Comment by wiredfool** [comment]
Ok, that's good anyway. 
The error trace that you're showing mentions `unnamed.webp` where your example is `2_webp_a.webp`.

Are you sure that `unnamed.webp` is a valid webp file?

**Comment by sa35t** [comment]
yes `unnamed.webp` is a valid webp file

**Comment by hugovk** [comment]
That code and image work for me on Windows 7 (Python 2.7, Pillow 3.0.0), and `features.check_module('webp') == True`, and it also opens ok in Chrome.

**Comment by sa35t** [comment]
I am on Ubuntu 12.04

**Comment by wiredfool** [comment]
You may need a newer webp. The system packages with 12.04 are really old, and have known issues with transparent images. There may be other images that they have trouble with as well.

**Comment by sa35t** [comment]
Currently I have these two library related to webp
`ii  libwebp-dev                                                 0.1.3-2.1ubuntu1                        Lossy compression of digital photographic images.
ii  libwebp2                                                    0.1.3-2.1ubuntu1                        Lossy compression of digital photographic images`

which version do you suggest to install ?

**Comment by wiredfool** [comment]
Try installing from source, you're going to want the 0.4.3 version.    You may need to reinstall pillow afterwards, making sure that you're not installing from the pip cache.  See the install docs for the details.  http://pillow.readthedocs.org/en/latest/installation.html

**Comment by sa35t** [comment]
Thanks @wiredfool, Issue has been resolve now. I have install libwebp-0.4.3 from source and install pillow again using pip. 
 
Now it is working fine. Thanks for your assistance

**Comment by MustafayevMohammed** [comment]
print (features.check_module('webp')) gives False for me. I am on Alpine Linux

**Comment by aclark4life** [comment]
> print (features.check_module('webp')) gives False for me. I am on Alpine Linux @wiredfool

Hmmm, install webp-dev on Alpine and run it again?
