### ISSUE TITLE
IOError: broken data stream when reading image file

### ISSUE THREAD

**Issue by Yucie** [python-pillow/Pillow#1510]
I can open and convert attach image file with other image software. However, i cannot convert this image file due to IOError: broken data stream when reading image file. Can someone solve this problem?

Thank you

![tesbb](https://cloud.githubusercontent.com/assets/12384865/10756039/6383e25a-7cdc-11e5-82e3-72016a4396b3.jpg)

**Comment by radarhere** [comment]
Hi. That is the error that typically describes truncated images. If you enable `LOAD_TRUNCATED_IMAGES`, the image can load.

    from PIL import Image, ImageFile
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    Image.open('image.jpg').load()

However, when I try and use beyond that, it is black. Who knows however, this may be sufficient to resolve your situation.

**Comment by Yucie** [comment]
Dear radarhere:
I have not any problem about open this image with PILLOW. When i want to change the format, resize ... etc, the  warning message " IOError: broken data stream when reading image file " will occur. I have not any idea to solve it. I hope someone can solve this problem, Thank you very much

**Comment by radarhere** [comment]
When Pillow opens an image, it lazy loads the data. Resizing or converting the format will force the data to load. In my example, I have explicitly run the load operation in my example.

If you find that including `ImageFile.LOAD_TRUNCATED_IMAGES = True` has no effect on the situation, feel free to say, but if you haven't tried it, I recommend doing so.

Also, if you're able to include a sample snippet of code to demonstrate the problem that you're experiencing, that could be helpful.

**Comment by Yucie** [comment]
orginal_image = Image.open(image file) <- No error
bmpinfo = orginal_image.size 
print bmpinfo <- Show the image size correctly
test = orginal_image.crop((0,0,0,0)) <- IOError: broken data stream when reading image file

**Comment by radarhere** [comment]
Okay. This code should run without an error -

    from PIL import Image, ImageFile
    ImageFile.LOAD_TRUNCATED_IMAGES = True
    orginal_image = Image.open('test.jpg')
    bmpinfo = orginal_image.size 
    test = orginal_image.crop((0,0,0,0))

From my tests, at that point you will find that the image is black. Now, at that point, I don't know how to resolve the problem. Perhaps someone else will have a suggestion.

To be helpful though, if you're just interested in making this particular image work, I recommend using other image editing software to resave it, possibly converting it between formats. This is a malformed image, and Pillow isn't reading it correctly. If you resave it in a different format however, it should stop being malformed.

**Comment by Yucie** [comment]
Thank you for your reply. Although i using other software to convert format from jpg to bmp and using PILLOW to reload it, the whole process will become slow due to using third part software. I hope someone can help me.

**Comment by hugovk** [comment]
Imagemagick is good at batch converting things.

One at a time:

`convert input.jpg output.png`

Lots at a time:

`mogrify -format ong *.jpg`

**Comment by Yucie** [comment]
Dear hugovk:
I know imagemagick is good convertor for the image. However, i cant package it to one exe file to distrub software to the other. Moreover, if i use imagemagick to convert image, the user still need to install imagmagick also. Therefore , i finding a best solution for this case. Thank you.

**Comment by Yucie** [comment]
Finally, i found the reason why PILLOW cannot convert and data error occur in this case. The reason is Pillow using FFD9 to identify the end of the image. However, this image using FF66 this value to become end. Therefore, Pillow cannot found the end of the file and occur error.

**Comment by radarhere** [comment]
Yes, this is the error that `LOAD_TRUNCATED_IMAGES` avoids. However, the problem then becomes that Pillow can't interpret the visual data that does still exist within the file.

**Comment by Yucie** [comment]
Since Pillow only process the specific maker in this file. "https://github.com/python-pillow/Pillow/blob/master/PIL/JpegImagePlugin.py". I solve maker problem with check the file binary data with FFXX is the specific maker in that file. If not, change to FF00.

**Comment by stuartspotlight** [comment]
I am having this issue in PIL 5.1.0 when loading a JPEG2000 from a byte stream which I've extracted from a pdf, has any resolution been found?
