### ISSUE TITLE
Text not getting normalized in PIL imaging library

### ISSUE THREAD

**Issue by cliveverghese** [python-pillow/Pillow#1516]
u'\u0d2a\u0d4b\u0d1f\u0d4b' is getting printed in the NFKD format instead of the NFKC. on the canvas

**Comment by radarhere** [comment]
Would it be possible to get the output image vs what you were expecting? And possibly a few lines that you used to generate the image?

**Comment by wiredfool** [comment]
I think we've run across this before, but I can't find the one where I actually responded with an analysis. It may be the same as this: #597.

IIRC, Freetype needs another library to do normalization of unicode, and we've never added support for it.

**Comment by radarhere** [comment]
From my search, is Harfbuzz the additional library you are referring to?

**Comment by wiredfool** [comment]
Yep, pretty sure that was it.

**Comment by wiredfool** [comment]
Closing this, I'd certainly consider a PR implementing harfbuzz support.
