### ISSUE TITLE
Iterate over pixel tuples using Image.point

### ISSUE THREAD

**Issue by JuanPotato** [python-pillow/Pillow#1517]
You can iterate over an image and get the pixels in different ways, one of which is Image.point. I would like to know if there is any method that, like point, is efficient and allows me to input a function but rather having single integers being given through the function, gives a tuple representing the pixel. I know about using Pixel Access Objects, but I would like a more efficient approach.

**Comment by wiredfool** [comment]
If you can express your function as a linear transformation of the RGB values of the point in matrix form, you should try Image.convert. 

This is a good overview: http://engineering.khanacademy.org/posts/making-thumbnails-fast.htm

**Comment by JuanPotato** [comment]
@wiredfool Thank you for that link, unfortunately my function does not seem to be able to be represented as a linear transformation. Do you have any other ideas? Why can't there be a point for rgb value at once?
