### ISSUE TITLE
missing 'version' key-value in Image.__array_interface__

### ISSUE THREAD

**Issue by mattip** [python-pillow/Pillow#1518]
According to http://docs.scipy.org/doc/numpy/reference/arrays.interface.html#python-side , ``__array_interface__`` has 3 required items: ``version``, ``shape`` and ``typestr``. ``Image.__array_interface__`` is missing the version key-value. A pull request with tests will be submitted soon

**Comment by radarhere** [comment]
Closing, as the PR has been merged.
