### ISSUE TITLE
createfontdatachunk.py is marked as executable but does not start with shebang

### ISSUE THREAD

**Issue by 65HQqp5QTq8QwA3f** [python-pillow/Pillow#1521]
Pillow/Scripts/createfontdatachunk.py is marked as executable but does not start with shebang.  See https://lintian.debian.org/tags/executable-not-elf-or-script.html

**Comment by hugovk** [comment]
PR for this: https://github.com/python-pillow/Pillow/pull/1522

**Comment by radarhere** [comment]
Just curious - when you say that it's marked as an executable, do you simply that it includes `if __name__ == "__main__":`?

**Comment by hugovk** [comment]
The file has executable bit set, so can be run as a standalone program:

```bash
$ ls -l Scripts/
total 56
-rw-r--r-- 1 hugovk 197121   555 Jun  9 15:15 createfontdatachunk.py
-rw-r--r-- 1 hugovk 197121   351 Sep 30 16:21 diffcover-install.sh
-rw-r--r-- 1 hugovk 197121   105 Sep  8  2014 diffcover-run.sh
-rwxr-xr-x 1 hugovk 197121  1569 May  4  2015 enhancer.py*
-rwxr-xr-x 1 hugovk 197121  2553 Jun  9 15:15 explode.py*
-rwxr-xr-x 1 hugovk 197121   675 Jun 30 15:20 gifmaker.py*
-rwxr-xr-x 1 hugovk 197121  2115 Oct 21 13:43 painter.py*
-rwxr-xr-x 1 hugovk 197121  2460 May  4  2015 pilconvert.py*
-rwxr-xr-x 1 hugovk 197121 16031 Jun  9 15:15 pildriver.py*
-rwxr-xr-x 1 hugovk 197121  2770 Aug 31 17:28 pilfile.py*
-rwxr-xr-x 1 hugovk 197121  1087 Aug 31 17:28 pilfont.py*
-rwxr-xr-x 1 hugovk 197121  2493 May  4  2015 pilprint.py*
-rwxr-xr-x 1 hugovk 197121  2278 Aug 31 17:28 player.py*
-rw-r--r-- 1 hugovk 197121  2215 Oct 21 13:43 README.rst
-rwxr-xr-x 1 hugovk 197121  1871 May  4  2015 thresholder.py*
-rwxr-xr-x 1 hugovk 197121  1024 May  4  2015 viewer.py*
```

Compare:
```bash
$ ls -l PIL/Image.py
-rw-r--r-- 1 hugovk 197121 83753 Oct 21 13:43 PIL/Image.py
```

So you can do `scripts/createfontdatachunk.py` as well as `python scripts/createfontdatachunk.py`, but the former might not work properly without the correct shebang.

**Comment by radarhere** [comment]
Okay, thanks for explaining. Those aren't the permission levels I see on my system, but I'm on board with the change anyway.

**Comment by hugovk** [comment]
They're UNIXy things that are maintained in Git. You don't usually see them in Windows with cmd.exe/`dir` etc. but you can with something like MINGW (my previous pastes are from MINGW) or with `ls` from UnxUtils (which I find handy to have for cmd.exe).
