### ISSUE TITLE
Getting TypeError when saving TIFF file

### ISSUE THREAD

**Issue by chimezie** [python-pillow/Pillow#1524]
The full traceback is at the bottom.  This seems to occur only when the typ variable has a value of 1, in which case self._write_dispatch[typ] becomes <function ImageFileDirectory_v2._register_basic.<locals>.<lambda> at 0x7f5b650e59d8>.

```
Traceback (most recent call last):
  File "/home/dev/workspace/video-generation/video_process.py", line 425, in generate_video
    self.mp4 = encode_video(self.listing, photos, str(music))
  File "/home/dev/workspace/video-generation/generation/encode.py", line 287, in encode_video
    with_address.save(str(filename))
  File "/home/dev/athena-venv/lib/python3.4/site-packages/PIL/Image.py", line 1665, in save
    save_handler(self, fp, filename)
  File "/home/dev/athena-venv/lib/python3.4/site-packages/PIL/TiffImagePlugin.py", line 1320, in _save
    offset = ifd.save(fp)
  File "/home/dev/athena-venv/lib/python3.4/site-packages/PIL/TiffImagePlugin.py", line 608, in save
    if len(data) <= 4:
TypeError: object of type 'int' has no len()
```

**Comment by radarhere** [comment]
Thanks for reporting the problem. I don't suppose you'd be able to provide an image to demonstrate the problem? It would make debugging the issue easier.

**Comment by wiredfool** [comment]
It's the metadata that's failing, so it's related to the big IFD rewrite that happened. I'd really need to see the image metadata to trace through why it's happening though.

**Comment by caspervdw** [comment]
I got exactly the same issue using matplotlib imsave. Matplotlib (at least, version 1.5) uses the PIL tiff writer.
See traceback and short discussion at https://github.com/soft-matter/trackpy/pull/308.

**Comment by caspervdw** [comment]
I had some more time to look at this problem. This code reproduces the problem with matplotlib 1.5 and Pillow 3.0.0:

    import matplotlib.pyplot as plt
    fig = plt.figure()
    fig.savefig('temp.tif')

It seems to have something to do with tag 338, it is defined in `TAGS_V2` to have type `1`, which results in the exception.

**Comment by ttback** [comment]
Had this exact same error last week. I had to roll back to Pillow 2.9.0 and everything works again.

**Comment by Nexuapex** [comment]
This seems to appear on any RGBA image. It's trying to write the "ExtraSamples" tag, which only appears for RGBA and RGBX images.

**Comment by Nexuapex** [comment]
As far as I can tell, write_byte does not handle being passed an int instead of a string, and the ExtraSamples tag is incorrectly typed as a byte instead of a short.

**Comment by wiredfool** [comment]
Confirmed in the spec: http://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf

**Comment by radarhere** [comment]
With the PR merged, this can be closed, yes?

**Comment by wiredfool** [comment]
I don't think so, extra samples is not directly implicated in the original error, which was never tracked down.
