### ISSUE TITLE
Doc update for high resolution monitors

### ISSUE THREAD

**Issue by zlorb** [python-pillow/Pillow#1528]
ImageGrab.grab: Screenshots are incorrectly cropped on high-DPI displays. Windows returns display geometry data scaled for the DPI, while the actual screenshots are unscaled. Workaround: Right-click on python.exe, Properties, Compatibility tab, check 'Disable display scaling on high DPI settings'. Repeat for pythonw.exe.

Thanks to: https://github.com/ludios/Desktopmagic

**Comment by radarhere** [comment]
Hi. Thanks for pointing this out. However, this sounds like a bug to me, rather than something for a documentation change, and if it's possible to fix it, I think that would be good.

Also, I don't think that including a paragraph from the README of another project is best practice.

**Comment by aclark4life** [comment]
Indeed, this makes no sense to me. @zlorb Please clarify if you still care. Thanks
