### ISSUE TITLE
insert sparse image data

### ISSUE THREAD

**Issue by nschloe** [python-pillow/Pillow#1538]
I have sparse image data, i.e., a list of pixel positions and RGB values
```python
sparse = [
        [(0, 0), (255, 255,0)],
        [(0, 1), (255, 255,100)],
        # ...
        [(12, 10), (27, 0, 0)],
        ]
```
To construct an image from that data, I do
```python
im = Image.new('RGB', (100, 100), (0, 0, 0))
for item in sparse:
    X, value = item
    im.putpixel(X, value)
```
Unfortunately, this takes a lot of time since the loop is executed in Python. I cannot use `putdata()` either since this would require constructing dense data which is prohibitive for memory consumption.

Is there another way for setting pixel data in bulk?

**Comment by hugovk** [comment]
Note: http://stackoverflow.com/questions/33713221/create-png-image-from-sparse-data

**Comment by wiredfool** [comment]
@hugovk That's essentially the same question and answer. 

First of all, there's no way to do sparse images, so you're going to be using  4 bytes * pixels of storage for the main image storage (for RGB, single band images will be 1byte/pixel). There are ways that this can be memory mapped but off the top of my head, I don't remember the details of when that works. 

There's no sparse matrix representation of data in pillow. The closest would be something in numpy, but to get the data into an image form, we'd wind up needing the data in the full non-sparse form. 

It _may_ be possible to make the matrix in numpy and have it shared via the memmapped array buffer interface, but details of that would come from reading the code.
