### ISSUE TITLE
Sphinx errors on Travis CI

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#1541]
It's not causing builds to fail, but `pushd docs; make html; make linkcheck; popd` results in errors in the log:

https://travis-ci.org/python-pillow/Pillow/jobs/91335318#L2493

    0.72s$ pushd docs; make html; make linkcheck; popd
    ~/build/python-pillow/Pillow/docs ~/build/python-pillow/Pillow
    sphinx-build -b html -d _build/doctrees   . _build/html
    Running Sphinx v1.3.1
    making output directory...
    Exception occurred:
      File "conf.py", line 59, in <module>
        import PIL
    ImportError: No module named PIL
    The full traceback has been saved in /tmp/sphinx-err-awRHdU.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    make: *** [html] Error 1
    sphinx-build -b linkcheck -d _build/doctrees   . _build/linkcheck
    Running Sphinx v1.3.1
    making output directory...
    Exception occurred:
      File "conf.py", line 59, in <module>
        import PIL
    ImportError: No module named PIL
    The full traceback has been saved in /tmp/sphinx-err-7PDKSC.log, if you want to report the issue to the developers.
    Please also report this if it was a user error, so that a better error message can be provided next time.
    A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
    make: *** [linkcheck] Error 1
    ~/build/python-pillow/Pillow

cc @aclark4life

**Comment by aclark4life** [comment]
Does it happen local for anyone?

**Comment by wiredfool** [comment]
I think what's happening here is that Travis is doing an inplace build, so, from the root of the Pillow directory you can import PIL and have it work. We then cd into the docs directory and try to import PIL, and since we aren't in the package root, it fails. 

The best case would probably be to install into a virtualenv and build against that. Alternately, we could monkey around with the import path for sphinx to get it to recognize where Pillow is.

**Comment by aclark4life** [comment]
We could also move the documentation out of Pillow, if anyone is in to that idea... that would make it "clean" (but also create more work in the process, which I probably don't mind if there is interest in doing it that way.)

**Comment by wiredfool** [comment]
I'd like to keep the docs in the same repo for management and pr purposes. If we get new features from someone, I'd like to keep it as easy as possible to add documentation as well.

**Comment by aclark4life** [comment]
Cool, fine with me.

**Comment by radarhere** [comment]
From my understanding, this has been resolved by #1655
