### ISSUE TITLE
_getexif format change

### ISSUE THREAD

**Issue by willmcgugan** [python-pillow/Pillow#1542]
Thanks for your work on Pillow. It is invaluable.

The format of the exif data as returned from _getexif has change in 3.0.0. It used to return fractions as a list of two values, i.e. [1, 640] for a shutter speed, now it returns such values as a tuple of 1 float value. 

I'd recommend keeping is as a list of two values, because a photographer would expect to see 1/640 and not 0.0015625.

If the format has to change, would it be possible for '_getexif' to return the same format as pre 3.0.0 and expose the new format as 'getexif'? For the sake of backwards compatibility.  I know _getexif was never a blessed method. I can't even find it in the docs, but people have been using it as far back as 2010 and its going to break a lot of code.

**Comment by wiredfool** [comment]
See #1531, #1492, #1497 for current work on getexif and rationals.
