### ISSUE TITLE
Malformed spider file makes open() raise OverflowError

### ISSUE THREAD

**Issue by MrShark** [python-pillow/Pillow#1543]
While fuzzing imagesfiles I found a file that causes `Image.open(infile).load()` to give the following stack trace:

```
Traceback (most recent call last):
  File "./test2.py", line 6, in <module>
    Image.open(infile).load()
  File "/install/local/lib/python2.7/site-packages/PIL/Image.py", line 2280, in open
    im = _open_core(fp, filename, prefix)
  File "/install/local/lib/python2.7/site-packages/PIL/Image.py", line 2266, in _open_core
    im = factory(fp, filename)
  File "/install/local/lib/python2.7/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/install/lib/python2.7/site-packages/PIL/SpiderImagePlugin.py", line 108, in _open
    hdrlen = isSpiderHeader(t)
  File "/install/lib/python2.7/site-packages/PIL/SpiderImagePlugin.py", line 66, in isSpiderHeader
    if not isInt(h[i]):
  File "/install/lib/python2.7/site-packages/PIL/SpiderImagePlugin.py", line 46, in isInt
    i = int(f)
OverflowError: cannot convert float infinity to integer
```
The image file is uploaded here: [spider_img.txt](https://github.com/python-pillow/Pillow/files/36721/spider_img.txt)

The following patch fixes the problem and changes it into an IOError

```patch
--- a/PIL/SpiderImagePlugin.py
+++ b/PIL/SpiderImagePlugin.py
@@ -50,6 +50,8 @@ def isInt(f):
             return 0
     except ValueError:
         return 0
+    except OverflowError:
+        return 0
 
 iforms = [1, 3, -11, -12, -21, -22]
```

**Comment by radarhere** [comment]
Thanks for finding this. I've created a PR with your change.

I presume that since the image file is one you've generated randomly, it is able to be distributed as a test image under Pillow's license, and that you're happy for this to be done?

**Comment by MrShark** [comment]
Its OK, It's generated by [afl](http://lcamtuf.coredump.cx/afl/) so they might have some residual copyright but I decline mine.

**Comment by radarhere** [comment]
afi is distributed under Apache License version 2 - http://lcamtuf.coredump.cx/afl/README.txt. I don't believe that open source licenses in any way cover works created using the software, only the software itself.

**Comment by wiredfool** [comment]
For copyright to be an issue, the work in question has to be created by a human. The products from afl are generated by an automated computer process, so aren't covered under that.
