### ISSUE TITLE
Does Pillow make use of GPU instances (CUDA) 

### ISSUE THREAD

**Issue by ferozed** [python-pillow/Pillow#1546]
Does Pillow utilize GPU instructions when running on GPU enabled machines?

**Comment by wiredfool** [comment]
No, there's no support for CUDA. Pull requests are appreciated.

**Comment by aclark4life** [comment]
Some folks from NVIDIA have expressed an interest in adding CUDA support, please watch for future discussions here and elsewhere.

They referenced [this library](https://github.com/CVCUDA/CV-CUDA) they built with ByteDance which has an implementation of Pillow's resize for CUDA, added by popular demand.

Initial discussions will be about:

- What does CUDA support in Pillow look like? We know the implementation will be significantly scoped and there are likely no "small pieces" (although the recently added #8329 may help).
- Should it go in Pillow or in another library e.g. pillow-cuda. A separate library could facilitate something like `pip install pillow[cuda]`.
- Assuming this feature is developed outside of Pillow and sent via PRs, how will the Pillow team maintain it? We don't want to add any significant maintenance burden for the core team to have to absorb.

Similar to #1888, I am excited about the possibility of expanding Pillow's core features in ways that are both popular (in demand) and maintainable (in scope).

**Comment by wiredfool** [comment]
There is a bit in the arrow spec about device memory, so it's possible that it's one way to leverage getting the data onto the GPU. PyArrow has CUDA/Numba integration: https://arrow.apache.org/docs/python/integration/cuda.html . On the other hand, if there's an arrow->GPU->arrow program that does image manipulation, we can support that now.

**Comment by wiredfool** [comment]
Also, FWIW, If we did anything on MacOS, it would probably have to be Metal, and that doesn't look insurmountable. Ref:
* https://github.com/noppoMan/python-metal-benchmark
* https://github.com/Al0den/metalgpu

**Comment by wiredfool** [comment]
This might be related: https://thenewstack.io/nvidia-finally-adds-native-python-support-to-cuda/
