### ISSUE TITLE
zlib requested, but not found - aborting

### ISSUE THREAD

**Issue by skyflyer** [python-pillow/Pillow#1551]
Trying to install Pillow on OS X El Capitan (10.11.1). I do have zlib installed on the system (using `brew install lzlib`).

The error I get:
```--enable-zlib requested but zlib not found, aborting.```. I tried installing via wheel for OS X 10.10, but I get this error instead:
```
pip install ~/Downloads/Pillow-3.0.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl 
Pillow-3.0.0-cp27-none-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl is not a supported wheel on this platform.
```

I can install the older version (2.6.1), though it is also missing a ZLIB and OPENJPEG support:
```
    --- TKINTER support available
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support
    *** ZLIB (PNG/ZIP) support not 
    --- LIBTIFF support available
    --- FREETYPE2 support available
    --- LITTLECMS2 support availabl
    --- WEBP support available
    --- WEBPMUX support available
```

I'm not sure how to tell build script that I have zlib on my system. I also tried exporting the `CPPFLAGS`:
```
export LDFLAGS=-L/usr/local/opt/zlib/lib
export CPPFLAGS=-I/usr/local/opt/zlib/include
```

**Comment by skyflyer** [comment]
Ah, it is usually after an hour of searching, that one decides to file a bug report. Then, you try somehting else, and it gets resolved quickly... sorry for polluting the issues here. I've managed to resolve my issue with reinstalling some Xcode related stuff using `xcode-select --install`. I got a hint from [Homebrew issues](https://github.com/Homebrew/homebrew-python/issues/234).

**Comment by tdsmith** [comment]
This may be related to https://bugs.python.org/issue25136.
