### ISSUE TITLE
ImageQt missing import

### ISSUE THREAD

**Issue by ericfrederich** [python-pillow/Pillow#1557]
The fromqimage function requires PIL.Image been imported.

The following will fail from the command line:

```
$ python -c "from PIL import ImageQt; from PyQt4.QtGui import QImage; qim = QImage(32, 32, QImage.Format_ARGB32); im = ImageQt.fromqimage(qim)"
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "PIL/ImageQt.py", line 72, in fromqimage
    return PIL.Image.open(b)
AttributeError: 'module' object has no attribute 'Image'
```

**Comment by radarhere** [comment]
Thanks for picking this up. I've created an alternative PR to fix this - not because there's anything wrong with yours, but just to be more consistent with the rest of the codebase.

**Comment by radarhere** [comment]
PR has been merged, so this issue should be resolved.
