### ISSUE TITLE
Inconsistent behavior when converting  RGB and HSV images to a numpy array 

### ISSUE THREAD

**Issue by cartisan** [python-pillow/Pillow#1559]
The behavior of RGB and HSV Images is different when converting into a numpy array.

```python
>>> from PIL import Image
>>> from numpy import array
>>> img = Image.open("\usr\bin\pic.jpg")
>>> arr = array(img)
>>> arr.shape
(800, 715, 3)
>>> img_hsv = img.convert("HSV")
>>> arr_hsv = array(img_hsv)
>>> arr.shape
()
```

In fact with the HSV Image what I get is not even a proper array but apparently just some container. I can't iterate on it, for instance. I assume this is something for you and not the numpy guys, please correct me if that's wrong!

Python is 2.7, Pillow is 2.9.0.

**Comment by radarhere** [comment]
From my inspection, the problem is that HSV is not part of this list - https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L240

**Comment by wiredfool** [comment]
Yep, it needs an entry there. Should be a one line fix + a test.
