### ISSUE TITLE
TIFF tags removed when using libtiff

### ISSUE THREAD

**Issue by rbonestell** [python-pillow/Pillow#1561]
My specific utilization of Pillow requires that I generate a TIFF image with  G4 compression and provide at least the following tags; 256, 257, 259, 262, 273, 274, 278, 279, 282, and 283.

The following line in TiffImagePlugin.py specifies a list of tags to exclude from the file when using libtiff:
https://github.com/python-pillow/Pillow/blob/master/PIL/TiffImagePlugin.py#L1281

I cannot find any justification for this other than the comment on line 1280, "ICC Profile crashes."
Is it impossible to create a TIFF file using G4 compression with Pillow that contains the ROWSPERSTRIP (278) TIFF tag?

**Comment by rbonestell** [comment]
I took the liberty of removing "ROWSPERSTRIP" from the blocklist collection on my local environment and it appears to behave as expected, error free. Any additional information would be greatly appreciated.

**Comment by wiredfool** [comment]
IIRC, libtiff was supposed to be adding those tags based on how the library was doing the encoding. 

ICCprofile was crashing, probably due to some questionable handling of the attributes.
