### ISSUE TITLE
Majority/Mode resampling method

### ISSUE THREAD

**Issue by jkazemifard** [python-pillow/Pillow#1562]
Hi everyone,
Just to say that a "majority" resampling method could be interesting. For example to use with "land use / land cover" images (or other type of classification).
The majority resampling (or mode resampling) should select the value which appears most often of all the sampled points.
If anyone wants to develop this, I'm sure it will make some people happy. Well, at least me ;)

**Comment by hugovk** [comment]
Thanks, I'll close this as there's been no movement in 3 years. PRs still welcome!
