### ISSUE TITLE
Broken link to installation documentation on pypi page

### ISSUE THREAD

**Issue by pitchforks** [python-pillow/Pillow#1569]
https://pypi.python.org/pypi/Pillow/3.0.0

"Installation" link that points to https://pillow.readthedocs.org/installation.html seems broken, there's nothing on that location

**Comment by hugovk** [comment]
The same applies to the Handbook link:
https://pillow.readthedocs.org/handbook/index.html

https://pillow.readthedocs.org/ redirects to https://pillow.readthedocs.org/en/3.0.x/.

There are working links at:
https://pillow.readthedocs.org/en/3.0.x/installation.html
https://pillow.readthedocs.org/en/3.0.x/handbook/index.html

But there's also `latest`:
https://pillow.readthedocs.org/en/latest/
https://pillow.readthedocs.org/en/latest/installation.html
https://pillow.readthedocs.org/en/latest/handbook/index.html

And `latest` is more up-to-date than `3.0.x`.

Should PyPI's 3.0.0 page point to `3.0.x` or `latest`?

**Comment by radarhere** [comment]
My opinion is that it should point to `3.0.x` - otherwise, it's conceivable that a user looking for 3.0.0 details could become confused reading about unreleased changes in `latest`.

**Comment by radarhere** [comment]
See also https://github.com/python-pillow/Pillow/commit/88dbf0682087749898e84c2df55e364e7a6fe422#commitcomment-13559359

**Comment by wiredfool** [comment]
The general history was --

* We were using unprefixed, but that tracks master, which led to the general documentation being ahead of the released code. 
* We switched to versions, where we have 3.0.x and latest, which 404'd the unprefixed docs. 

I think this is actually a RTD bug/feature -- the deep unprefixed links should redirect somewhere, and they don't.
