### ISSUE TITLE
Review TiffTags.py

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1595]
We've had a couple of bug reports for types in TiffTags.py that were incorrect and causing issues since the types were added in 3.0.0. 

We should probably go through the spec (https://partners.adobe.com/public/developer/en/tiff/TIFF6.pdf) and make sure that all of the defined tags are listed with the correct type and length in our spec. Unfortunately, it's not in the tiff headers anywhere, just in one massive case statement in the library.

**Comment by hugovk** [comment]
The [table](https://github.com/python-pillow/Pillow/blob/master/PIL/TiffTags.py#L33-L163) would be more readable and checkable if constants were used for the types instead of an integer. Something like:

`254: ("NewSubfileType", LONG, 1),`

instead of:

`254: ("NewSubfileType", 4, 1),`

**Comment by radarhere** [comment]
Here's something confusing. On page 86 of the document, it lists ReferenceBlackWhite as RATIONAL and N=6. So I presume that TiffTags listing of LONG was incorrect. However, on the page 118, it lists it as LONG and 2*SamplesPerPixel?

Looking elsewhere, http://www.exiv2.org/tags-xmp-tiff.html lists it as RATIONAL. http://www.media.mit.edu/pia/Research/deepview/exif.html lists it as RATIONAL and 6.

Perhaps this is minor, but I thought I'd mention it.

**Comment by wiredfool** [comment]
Libtiff is writing it as a list of 6 floats, which would be rational. 

```
	case TIFFTAG_REFERENCEBLACKWHITE:
		/* XXX should check for null range */
		_TIFFsetFloatArray(&td->td_refblackwhite, va_arg(ap, float*), 6);
		break;
```

Rational it is. 

Constants are good, but don't tread on each other's toes.  And separate commits, so any changes due to fixing things are obvious.

**Comment by JRoush** [comment]
FYI, I've identified two tag enums that need correcting:
    296: ("ResolutionUnit", SHORT, 2, {"none": 1, "inch": 2, "cm": 3}),
    317: ("Predictor", SHORT, 1, {"none": 1, "Horizontal Differencing": 2}),

**Comment by wiredfool** [comment]
Thanks, added.
