### ISSUE TITLE
Pillow's Image open cause core dumped and aborting of python for some webp images

### ISSUE THREAD

**Issue by bagherbal** [python-pillow/Pillow#1603]
Hi. I have some png images. In the code I first convert them to webp then I try to make thumbnail from webp image, but for some images trying to open webp image cause core dumped and termination of python.

For converting images to webp I use this code:

    original_image = Image.open(path).convert("RGBA")
    webp_image = Image.new("RGBA", orig.size)
    webp_image.paste(original_image, mask=0)
    webp_image.save(webp_path, "WEBP", quality=100)

then when I run following code:

    from PIL import Image
    Image.open(webp_path)

I get this error:

    python: vp8l.c:619: GetHtreeGroupForPos: Assertion `meta_index < hdr->num_htree_groups_' failed.

    Aborted (core dumped)

I tried all combination of Pillow=2.9.0/3.0.0 and libwebp-dev==0.4.0/0.4.4 but with no success. The host OS that get this error is Ubuntu 14.04 trusty and version of python I'm using is 2.7.

What can I do about this error? I should report this bug in libwebp-dev package?

[sample.webp.zip](https://github.com/python-pillow/Pillow/files/66794/sample.webp.zip)

**Comment by wiredfool** [comment]
I think it might be a bug with the 14.04 webp packages. 

Using Pillow 3.0.0, I've tried this on 12.04 with libwebp build from source (0.4.0) and it works.  14.04 fails when built against the libwebp packages, but succeeds when run against  libwebp build from source. (in this case, 0.4.3, as it's what's scripted with Pillow 3.0.0).

So, It looks like an ubuntu issue.

**Comment by Mohanson** [comment]
I also met this problem, I will try build from source, thanks @wiredfool
