### ISSUE TITLE
ImageStat.Stat.extrema reports 0,255 on 16 bit grey image

### ISSUE THREAD

**Issue by markstock** [python-pillow/Pillow#1606]
Using python-pillow-2.6.2-2.fc21.x86_64 on 16-bit grey png images, I've noticed that ImageStat.Stat.extrema reports incorrect information.

```python
>>> from PIL import Image
>>> im = Image.open("myimg16b.png")
>>> im.mode
'I'
>>> from PIL import ImageStat
>>> ImageStat.Stat(im).extrema
[(0, 255)]
```

But

```
$ pngtopam myimg16b.png | pamsumm -max -brief
63490
```

Is this fixed in newer releases?
Sample image is here: [myimg16b.png](http://markjstock.org/transfer/myimg16b.png)

**Comment by radarhere** [comment]
No, testing with the latest version, I get the same result.

**Comment by wiredfool** [comment]
There is an `Image.getextrema` function, which returns the per-band extrema for the image. 

This function is used by the histogram function for non 8-bit modes to return extrema to define the bins used in the histogram. 

ImageStat.extrema relies on the image histogram function, and simply returns the low and high bins used. This is correct for 8 bit per channel images, but fails for anything else. 

So, ultimately, the Image.getextrema is a much more efficient and correct function to use.

**Comment by wiredfool** [comment]
* [ ] Document the format limitations of `ImageStat`
* [ ] Document the much more efficient `Image.getextrema` function
* [ ] Alternately, pop a warning or clear no data on `I` or `F` images
