### ISSUE TITLE
Setting DPI doesn't seem to work?

### ISSUE THREAD

**Issue by v-python** [python-pillow/Pillow#1612]
I write a tiff file using

```python
print('DPI:', paper.dpi )
thepage.save( ttif,
              dpi=( paper.dpi, paper.dpi ),
              compression='group4')
```

DPI: 500  is printed.  However, when I run tiffdump on the result, I get XResolution and YResolution set to 0, see below.

```
d:\my\gnuwin32\bin>tiffdump d:\temp\makebook-margins\temporary-x.tif
d:\temp\makebook-margins\temporary-x.tif:
Magic: 0x4949 <little-endian> Version: 0x2a
Directory 0: offset 17720 (0x4538) next 0 (0)
ImageWidth (256) SHORT (3) 1<2559>
ImageLength (257) SHORT (3) 1<3936>
BitsPerSample (258) SHORT (3) 1<1>
Compression (259) SHORT (3) 1<4>
Photometric (262) SHORT (3) 1<1>
StripOffsets (273) LONG (4) 1<8>
StripByteCounts (279) LONG (4) 1<17711>
XResolution (282) RATIONAL (5) 1<0>
YResolution (283) RATIONAL (5) 1<0>
PlanarConfig (284) SHORT (3) 1<1>
ResolutionUnit (296) SHORT (3) 1<2>
```

I open the file in IrfanView, and use its capabilities to set the DPI to 500 in each direction, now tiffdump has:
```
XResolution (282) RATIONAL (5) 1<500>
YResolution (283) RATIONAL (5) 1<500>
...
ResolutionUnit (296) SHORT (3) 1<2>
```
(of course other things change, and the resulting file is actually slightly smaller).

Am I specifying the DPI incorrectly? It seems sad that Pillow would write out the Resolution IFD entries, and not fill them in with the correct value, if I'm specifying them correctly. The documentation is a bit vague on how to do that...

**Comment by v-python** [comment]
Oh, Python 3.5, Pillow 3.0.0, Win 10.

**Comment by wiredfool** [comment]
There have been a lot of changes in this code for the 3.0 release, and more upcoming.  (Including a IFDRational class to encapsulate rational values)

That said, I think if you pass in a float, that should propagate through to xresolution and yresolution. It's not clear what you're passing in in this case.

**Comment by v-python** [comment]
paper.dpi is an integer 500. I guess that wasn't so clear, although I did say it was 500.  So I was passing a tuple of two integer 500s, because passing one gave me a fault trying to access a 2nd element.  I'll try a float.... tried, worked. Strange that integer wouldn't work, too.

**Comment by wiredfool** [comment]
Libtiff is a lot more picky about what gets passed in for metadata than the Pillow encoder (and anytime compression is used, it's going to go through libtiff)

**Comment by wiredfool** [comment]
Also, the docs should be more correct once the IFDRational goes in.
