### ISSUE TITLE
Release Pillow 3.2.0 on April 1, 2016

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1634]

**Comment by wiredfool** [comment]
I've done a pass through the PRs and dealt with anything that looks straightforward and ready to roll. There are a few that look like they're easy to merge with more tests or documentation, and then there are a bunch that are less straight forward.

**Comment by aclark4life** [comment]
Thanks @wiredfool. @python-pillow/pillow-team Let's try to update labels so we can figure out what to do for ``3.2.0``. For example, I only see 3 tickets labeled "Needs Review":

- https://github.com/python-pillow/Pillow/pulls?q=is%3Apr+is%3Aopen+label%3A%22Needs+Review%22

While there are 6 that need Documentation review:

- https://github.com/python-pillow/Pillow/labels/Needs%20Documentation

(In a related story, I may rename these labels to include dashes e.g. ``needs-review`` instead of "Needs Review"!)

**Comment by wiredfool** [comment]
Ok, I've merged what's clearly safe, I'm drawing a line here. If we're going to destabilize it, it's going to be  after the release.

**Comment by wiredfool** [comment]
Ok, tagged and sdists uploaded to Pypi. 

@cgohlke  -- We'd appreciate it if you could do 3.2.0 binaries.   There's also a 3.1.2 release, which we're going to leave as a source only release (I think) as it gives distros an easy way to cherry pick the security content in this release.

**Comment by wiredfool** [comment]
OSX wheels are up.

**Comment by cgohlke** [comment]
[Here you go](http://www.lfd.uci.edu/~gohlke/download/Pillow-3.2.0.win-dist.zip).

**Comment by wiredfool** [comment]
Thank you @cgohlke.

**Comment by aclark4life** [comment]
Thanks all :cake:

**Comment by aclark4life** [comment]
For posterity

<img width="1440" alt="screenshot 2016-04-01 17 57 18" src="https://cloud.githubusercontent.com/assets/72164/14221225/46d3fcb2-f833-11e5-81a6-0d6614ce3385.png">
