### ISSUE TITLE
ARGB pixel format support

### ISSUE THREAD

**Issue by jleclanche** [python-pillow/Pillow#1635]
Could ARGB mode be added to Pillow somehow? Right now an ARGB image has to be converted to RGBA manually before being passed off to pil which is quite a bit slower and kind of a pain.

**Comment by wiredfool** [comment]
There are a bunch of unpackers in various permutations of rgb and a, including ARGB. It doesn't appear that there's a packer, but that would be trivial to add. 

Those can be used with the raw decoder as listed here: http://pillow.readthedocs.org/en/3.0.x/handbook/writing-your-own-file-decoder.html#the-raw-decoder

**Comment by jleclanche** [comment]
I don't see ARGB documented on that page. Is it supposed to be documented anywhere?

**Comment by wiredfool** [comment]
That's how to use the rawmode, ARGB is one that is available.  The full list is in Unpack.c, https://github.com/python-pillow/Pillow/blob/master/libImaging/Unpack.c#L1102 .

**Comment by wiredfool** [comment]
And, generally what's done is you do what you need to do to your pixels in whatever format you have, and then chain back to the raw decoder with that block of pixels and let it untwiddle them into the preferred native format.

**Comment by jleclanche** [comment]
Great, thanks.
