### ISSUE TITLE
Drop support for Python 3.2?

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#1637]
It was suggested [here](https://github.com/python-pillow/Pillow/issues/1563#issuecomment-168641684) to drop support for Python 3.2:

> I'm kind of willing to let Python 3.2 go, It's 5 years old with three newer more compatible successors. I'd say drop it and if there are major complaints we can revisit.

Anyone for or against this?

**Comment by hugovk** [comment]
Here's some stats for Python 3.2.

The last release Pillow 3.0.0 was downloaded from PyPI 1,047,167 times of which 83% was the zipped source. Excluding source, Python 3.2 accounts for 2% of the packages downloaded:

![image](https://cloud.githubusercontent.com/assets/1324225/12089054/6c3a3bc2-b2e9-11e5-97c7-9ed134e8a765.png)

![image](https://cloud.githubusercontent.com/assets/1324225/12089066/7c13c20c-b2e9-11e5-9094-0d8fa4889182.png)

This [2014](http://www.randalolson.com/2015/01/30/python-usage-survey-2014/) [survey](https://docs.google.com/forms/d/1DqxkNi4GvyTCu54usSdE1DjW29zw1tc52iMeH3z4heg/viewanalytics) said 2.8% of 6,746 respondents regularly use Python 3.2:
![image](https://cloud.githubusercontent.com/assets/1324225/12089281/d5c8c692-b2eb-11e5-8999-e9277f8604eb.png)

This [2015 survey](https://astrofrog.github.io/blog/2015/05/09/2015-survey-results/) said <1% of 786 respondents use Python 3.2 as their *primary* installation:
![image](https://cloud.githubusercontent.com/assets/1324225/12089282/dbc81f0c-b2eb-11e5-906b-a5e652fb5b23.png)

**Comment by wiredfool** [comment]
To be clear, I was referring to Windows 3.2 builds, not overall Pillow compatibility with 3.2. Pillow still works with 3.2, and I'm not aware of anything that we're chomping at the bit to add if we dropped 3.2. (Though, not being able to use u'' strings in tests has tripped me up. )

**Comment by hugovk** [comment]
Fair enough.

Windows packages account for 3,211/3,771 of the Python 3.2 packages for Pillow 3.0.0.

**Comment by wiredfool** [comment]
My guess is that we're going to trip up more ci systems than actual users.
