### ISSUE TITLE
Error installing in Debian / Jessie

### ISSUE THREAD

**Issue by maheshkronecker** [python-pillow/Pillow#1639]
Hello. I don't know whether the following error is due to Pillow or something else. I don't understand the message and any help to understand/resolve the issue would be appreciated. The full log is attached. Thanks!

In Debian/Jessie:
```
pip install Pillow
...
*/usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/4.9/../../../x86_64-linux-gnu/crti.o: réadressage inconnu (0x2a) dans la section « .init » (=unknown relocation in section .init)*
    /usr/bin/ld: édition de lien finale en échec: Mauvaise valeur (=failure in final link edition: wrong value)
[log.txt](https://github.com/python-pillow/Pillow/files/77197/log.txt)

    collect2: error: ld returned 1 exit status
    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1
    
    ----------------------------------------
Command "/usr/bin/python3 -c "import setuptools, tokenize;__file__='/tmp/pip-build-r6ds66us/Pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-tdlsmagx-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-build-r6ds66us/Pillow
```

**Comment by wiredfool** [comment]
Do you have the python3-dev package installed?

**Comment by maheshkronecker** [comment]
Yes I do. sudo apt-get install python3-dev tells me I already have the most recent version installed.

**Comment by maheshkronecker** [comment]
Further to the above, I have found a recent Debian gcc bug description:
https://www.mail-archive.com/debian-bugs-dist%40lists.debian.org/msg1380015.html
which I can replicate on my system. So it seems that the issue is a Debian problem. I still don't understand how to fix it, though. 
Thank you!

**Comment by wiredfool** [comment]
That bug report appears to be from Sid. Sid breaks things. Always has, since that's where they find a lot of the bugs that don't hit stable. Jessie is on libc6 2.19-18+deb8u1, which is from before the break.

**Comment by maheshkronecker** [comment]
Thank you. However note that I am on Jessie, not sid, with only stable sources and  
Package: libc6 
Source: glibc
Version: 2.19-18+deb8u1
I can still reproduce the bug described at https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=808205#5 for sid, but on Jessie. I don't know what is going on; I might report this to Debian maintainers if I don't find anything I might have done wrongly. Best, Mahesh

**Comment by wiredfool** [comment]
I've just checked in a fully updated Debian Jessie / 8.2 vm and I'm not seeing that issue.

**Comment by maheshkronecker** [comment]
Indeed. It took me time to realize that I had sid/stretch sources on my system (libc 6 2.21) which really should only have stable packages. My sincere apologies for not working this out myself before posting a comment here. Downgrading back to stable solved all issues.
