### ISSUE TITLE
Provide additional keyword args for ImageDraw.text(...) method for multiline text

### ISSUE THREAD

**Issue by troygrosfield** [python-pillow/Pillow#1645]
The check for ``if self._multiline_check(text):`` inside of the ``ImageDraw.text(...)`` method [1] is great, but if True, it goes to the next line ``return self.multiline_text(xy, text, fill, font, anchor)`` and doesn't allow the user to pass important keyword args to the ``multiline_text(...)`` function like **align** and **spacing**.  Instead, why not do something like:

```py
def text(self, xy, text, fill=None, font=None, anchor=None, **kwargs):
    """:param kwargs: additional args to pass to multiline_text if the text is multiline"""
    if self._multiline_check(text):
        return self.multiline_text(xy, text, fill, font, anchor, **kwargs)
```

Then I can call the ``.text(...)`` function with those additional params:

```py
draw = ImageDraw.Draw(myImage)
draw.text((0,0), 'hello world', align='left', spacing=5)
```

This would be a passive change to the current ``.text(...)`` method call.

[1] https://github.com/python-pillow/Pillow/blob/master/PIL/ImageDraw.py#L245

**Comment by radarhere** [comment]
Thanks for the suggestion. I've created a PR to make this change, adding in `args` as well as `kwargs`.

**Comment by troygrosfield** [comment]
Awesome!  Thanks @radarhere! :+1:
