### ISSUE TITLE
ImageSequence.Iterator name is misleading

### ISSUE THREAD

**Issue by u55** [python-pillow/Pillow#1648]
Hi Pillow developers,

I found this error message to be rather hilarious:
```
TypeError: 'Iterator' object is not an iterator
```
which was produced by this code:
```python
from PIL import Image, ImageSequence

with Image.open('multipage.tiff', mode='r') as tif:
    i = ImageSequence.Iterator(tif)
    next(i)
```

It seems that `ImageSequence.Iterator` does not define an `__iter__()` method, which means that it is a sequence type but not an iterator type. In my opinion, this is misleading and I suggest that a proper `__iter__()` method should be added to the class definition.

Thanks.

**Comment by radarhere** [comment]
Fair enough. I've created a PR.
