### ISSUE TITLE
Open file handles after processing a multipage tiff

### ISSUE THREAD

**Issue by sekrause** [python-pillow/Pillow#1651]
When processing *some* TIFF files with multiple pages Pillow keeps some open files handles around so that the file can neither be moved nor deleted anymore on Windows. The following script shows the error (tested here with 64-bit Python 3.4.3 on Windows). The file handle leak does *not* happen with the `multipage.tiff` test file from Pillow's repository. However, the example file [g4-multi.tiff.gz](https://github.com/python-pillow/Pillow/files/500686/g4-multi.tiff.gz) can reproduce this problem. The main difference between the two files is that my file uses the G4 compression codec.

```python
import os
import shutil
import tempfile
from PIL import Image

TESTFILE = r'g4-multi.tiff'

def create_tempfile():
    with open(TESTFILE, 'rb') as f, tempfile.NamedTemporaryFile('wb', delete=False) as t:
        shutil.copyfileobj(f, t)
        return t.name

def process(filename):
    with open(filename, 'rb') as f:
        im = Image.open(f)
        count = im.n_frames
        im.close()
    print('File is closed: %s' % f.closed) # True
    return count

def main():
    tmp = create_tempfile()
    count = process(tmp)
    print('Number of pages: %d' % count) # 3
    os.remove(tmp) # Windows PermissionError here!

main()
```

**Comment by radarhere** [comment]
I am unable to reproduce on OS X 10.11 with Pillow 3.1.0 and multiple Python versions.

You may be interested in #1144

**Comment by sekrause** [comment]
You won't be able to reproduce this on OS X (or any Unix system) because there it's always allowed to delete files that are still open somewhere. So `os.remove(tmp)` will never fail on OS X even if you also have leaked file handlers, but on Windows it's not possible to delete open files.

**Comment by radarhere** [comment]
Ah, didn't realise that it was only Windows. Thanks for clarifying.

**Comment by hugovk** [comment]
Also reproducible on Windows with a simpler `process()`:
```python
def process(filename):
    im = Image.open(filename)
    count = im.n_frames
    im.close()
    return count
```

**Comment by jbarlow83** [comment]
Problem also occurs on OS X.
I did an explicit `del im` after im.close().

**Comment by seehuhn** [comment]
The following issue may have the same root cause: http://stackoverflow.com/questions/38541735/pillownumpyunittest-gives-a-resourcewarning-does-this-indicate-a-leak/38542329 .  There, when I try to close a TIFF `Image` object after use, the `.fp` member already has been set to `None` and thus the `Image.close()` method fails to close the file descriptor.  Maybe the line `self.fp = None` in `TiffImageFile._load_libtiff()` is to blame?  Not sure ...

**Comment by sekrause** [comment]
I think I found the cause of the issue. The file descriptor of the image is duplicated here and stored in `fp`: https://github.com/python-pillow/Pillow/blob/d3d29ab2e31b3c647f5355482c2e7e4c552dc055/PIL/TiffImagePlugin.py#L1200

`fp` is then only used once in [line 1236](https://github.com/python-pillow/Pillow/blob/d3d29ab2e31b3c647f5355482c2e7e4c552dc055/PIL/TiffImagePlugin.py#L1236), but never closed. That is the reason why you can't delete the file on Windows.

When I simply add an `if fp: os.close(fp)` after [line 1236](https://github.com/python-pillow/Pillow/blob/d3d29ab2e31b3c647f5355482c2e7e4c552dc055/PIL/TiffImagePlugin.py#L1236) the error goes away. Not sure if it is the right fix, though.

**Comment by sekrause** [comment]
So here is the actual problem in `TiffImageFile`:

- The file descriptor [is duplicated](https://github.com/python-pillow/Pillow/blob/d3d29ab2e31b3c647f5355482c2e7e4c552dc055/PIL/TiffImagePlugin.py#L1200) each time `TiffImageFile._setup()` is called.
- `TiffImageFile._setup()` is called [every time](https://github.com/python-pillow/Pillow/blob/d3d29ab2e31b3c647f5355482c2e7e4c552dc055/PIL/TiffImagePlugin.py#L981) you call `TiffImageFile._seek()`. That happens 4 times in the 3-page long multipage tiff above: Once when the file is opened and three times from n_frames. So we end up with four additional file descriptors that prevent the file from being deleted on Windows.
- libtiff closes the file descriptor passed to it in `TiffImageFile._load_libtiff()` when [decoder.decode()](https://github.com/python-pillow/Pillow/blob/d3d29ab2e31b3c647f5355482c2e7e4c552dc055/PIL/TiffImagePlugin.py#L1066) is called. That's why os.dup() is actually used. But even when `im.load()` is called and libtiff closes the `fd` passed to it, we still remain with 3 out of 4 created file descriptors still open.

Now I'm not sure if I understand the code correctly, but wouldn't it make more sense to only duplicate the file descriptor when it's actually passed to libtiff (in `_load_libtiff()`) instead of every time `_setup()` is called? I've created the following patch which does just that and it fixes the bug for me, but someone with more insight to Pillow should probably take a look at it and see if it causes any problems elsewhere: https://gist.github.com/sekrause/584aa2845c9a55c1f668a476999b77a4
