### ISSUE TITLE
Define security procedures

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#1658]
Add information to documentation about how to properly disclose sensitive vulnerability information to Pillow team.

**Comment by aclark4life** [comment]
For lack of better options, the vulnerability disclosure procedure is currently: **Send email to aclark@aclark.net** and I will CC relevant parties.

**Comment by wiredfool** [comment]
If your org/employer is a distributor of Pillow and would like to get advance notification of security related bugs, please let us know the preferred contact method. So far I've got security@(debian|ubuntu), Redhat's bugzilla with the security check box at the bottom, and Atlassian.

**Comment by hugovk** [comment]
Something like https://github.com/python-pillow/Pillow/pull/1712?

**Comment by aclark4life** [comment]
In #1712 we discussed registration of the `python-pillow.org` domain. That domain is now registered and we'll discuss initial setup in #1713 . (Additionally, a preliminary security procedure was added to the docs, thanks @hugovk !)
