### ISSUE TITLE
read and write tiffs with doubles

### ISSUE THREAD

**Issue by microe** [python-pillow/Pillow#1659]
I have come across tiffs with pixels of type double. It would be nice if pillow supported that.

**Comment by wiredfool** [comment]
There's some historical support in pillow for 64 bit floating point image formats, but only for single band images. I'm not aware of it ever being actually enabled or of what use it might be. 

(See `libImaging/Unpack.c`, or search for FLOAT64 in the c layer)

**Comment by microe** [comment]
If one were to put in 64-bit floating point support, how would one do that? I notice that the OPEN_INFO and SAVE_INFO dictionaries are a good place to start. If I do that, any idea what else I have to do? I put in these lines into OPEN_INFO:
```
    (II, 0, (3,), 1, (64,), ()): ("F;64", "F;64F"),
    (MM, 0, (3,), 1, (64,), ()): ("F;64", "F;64BF"),
    (II, 1, (3,), 1, (64,), ()): ("F;64", "F;64F"),
    (MM, 1, (3,), 1, (64,), ()): ("F;64", "F;64BF"),
```

And that gets me a little bit of the way:
```
In [1]: from PIL import Image

In [2]: img = Image.open('tiffdouble.tif')

In [3]: img.mode
Out[3]: 'F;64'
```

Now, when I try to do things, it isn't what I expect:
```
In [8]: np.asarray(img)
Out[8]: array(<PIL.TiffImagePlugin.TiffImageFile image mode=F;64 size=192x192 at 0x7F6D181B0750>, dtype=object)
In [10]: np.asarray(img, dtype=np.float64)
---------------------------------------------------------------------------
TypeError                                 Traceback (most recent call last)
<ipython-input-10-dd76324344e0> in <module>()
----> 1 np.asarray(img, dtype=np.float64)

/work/ehovland/pillow-hacking/local/lib/python2.7/site-packages/numpy/core/numeric.pyc in asarray(a, dtype, order)
    529 
    530     """
--> 531     return array(a, dtype, copy=False, order=order)
    532 
    533 

TypeError: float() argument must be a string or a number
```

Any advice is appreciated. I am willing to hack this in, but I am still pretty lost.

**Comment by wiredfool** [comment]
There's currently no support for storing anything more than 32bits/pixel. If you look in Unpack.c, the ifdef'd out items for FLOAT64 store the items in FLOAT32 storage. 

At the very least, there would need to be changes to Pack.c, Unpack.c, and Storage.c, as well as the format definitions for to and from numpy. I'm not clear what would have to happen on the Tiff side of things, but it would require the storage stuff done first. 

Also, note that Image.open() doesn't actually load the bytes, just the file header. So while putting in the bits of OPEN_INFO and SAVE_INFO recognized the files, it didn't actually try to load anything at that point.

**Comment by microe** [comment]
Wow, you aren't kidding!
```
ehovland@mage:Pillow$git diff --stat
 PIL/TiffImagePlugin.py |  7 +++++++
 Tests/make_hash.py     |  2 +-
 libImaging/Access.c    | 75 ++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++-
 libImaging/Imaging.h   |  4 +++-
 libImaging/Pack.c      | 22 ++++++++++++++++++++++
 libImaging/Storage.c   |  7 +++++++
 libImaging/Unpack.c    |  4 ----
 7 files changed, 114 insertions(+), 7 deletions(-)
```

**Comment by cschreib-ibex** [comment]
This is an old issue, but:
> I'm not aware of it ever being actually enabled or of what use it might be.

Matlab's default floating point type is double, and TIFF is a common export format. Having 64bit TIFF supported would be really useful for this reason.
