### ISSUE TITLE
PEP440: Version Name

### ISSUE THREAD

**Issue by ax3l** [python-pillow/Pillow#1661]
With `easy_install ` and python 2.7 and setuptools 14.0 I get the install warning:
```
PEP440Warning: 'Pillow-3.1.0 (rc1)' is being parsed as a legacy, non PEP 440, version.
You may find odd behavior and sort order. In particular it will be sorted as less than 0.0.
It is recommend to migrate to PEP 440 compatible versions.
```

Ref: https://www.python.org/dev/peps/pep-0440/

**Comment by wiredfool** [comment]
I'm not seeing that now. 

At any rate, the rc1 release was a release candidate for the 3.1.0 release, which is now out. It is ok if sorts at the bottom.

**Comment by ax3l** [comment]
surprising, if I use `pip 7.1.2` it also selects the `3.1.0` version and not the release candidate for me.
