### ISSUE TITLE
Converting Image Profile to sRGB

### ISSUE THREAD

**Issue by mikebarkmin** [python-pillow/Pillow#1662]
Hi,

when i am converting a Image with an embedded "Adobe RGB (1998)" profile to sRGB, i only receive an fully transparent image. On the other Hand, when i am converting an image with an embedded "Linear Color Space" profile, everything works as expected. I don't know why some profiles convert to only transparent pictures. It would be great, if we could work out this issue.

Source Code:

``` python
import PIL.Image
import PIL.ImageCms
import tempfile

img = PIL.Image.open('input.png')
icc = tempfile.mkstemp(suffix='.icc')[1]
with open(icc, 'w') as f:
    f.write(img.info.get('icc_profile'))
srgb = PIL.ImageCms.createProfile('sRGB')
img = PIL.ImageCms.profileToProfile(img, icc, srgb)
img.save('output.png')
```

Tested Python Versions:
- 2.7.10

Tested Pillow Versions:
- 3.0.0
- 3.1.0

Tested LittleCms Versions:
- 2.7

Source and Sample Image:
[source.zip](https://github.com/python-pillow/Pillow/files/92095/source.zip)

**Comment by radarhere** [comment]
You say 'some profiles'. Does this mean that you've found this with other profiles as well?

**Comment by FlorianLudwig** [comment]
@radarhere yes, attached is an image with a different profile which also results in an all-transparent image.

![input](https://cloud.githubusercontent.com/assets/432263/14180623/1d96aee6-f764-11e5-9252-038d2249d0d6.png)

Any idea how to debug this?

**Comment by radarhere** [comment]
I don't think I'm going to be the one to solve this, I'm just trying to get the conversation going for someone who might. However, from my investigation so far, Pillow uses lcms2 to convert the image profile, so I presume that Pillow is just interfacing with it incorrectly. If someone could demonstrate the correct lcms2 command, it would be a start.

Would either of the images included here be able to be included as test images, under Pillow's license?

**Comment by aclark4life** [comment]
@mikebarkmin Is this still an issue?
