### ISSUE TITLE
RFC - allow setting of a RGB color on P images

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1664]
The current implementation of putpixel requires that the color passed in for P mode images be an integer. 

It would be a useful and reasonable to accept an RGB(A) color, look it up in the palette (or allocate an entry if possible) and then pass that integer into the core putpixel method.

**Comment by radarhere** [comment]
I've created PR #3519 to allow setting a RGB color on a P image. Adding in alpha can be a second task.
