### ISSUE TITLE
Identifying a file with magic at byte 128

### ISSUE THREAD

**Issue by jleclanche** [python-pillow/Pillow#1681]
I am writing a plugin for a format that has its magic at the 128th byte. How can I have the validate function take more than the first 16 bytes?

**Comment by wiredfool** [comment]
I believe what's done in other decoders is to not pass an accept function, or simply return true. Then, in the _open function, when you have the file pointer, do whatever reads are necessary to get to the magic bytes.  If it's not the file type you're looking for, then raise an exception and it will be caught in Imagefile, and the next decoder will be tried. 

There are performance issues with this approach.

**Comment by jleclanche** [comment]
Would it be reasonable to pass more than 16 bytes? Or to somehow make it configurable (maybe through a magic variable)?

**Comment by wiredfool** [comment]
It might make sense to increase the limit, though it would take an audit of the existing code. I'd be -1 on a magic variable.

**Comment by jleclanche** [comment]
@wiredfool are you willing to keep this open as a request to increase to 144 bytes?

**Comment by wiredfool** [comment]
I'm not rejecting it, I'm just closing it as a question that has been answered. 

There's at least one other plugin that requires 2k+4bytes for the magic number.
