### ISSUE TITLE
Color Changed after Image.convert ?

### ISSUE THREAD

**Issue by zhanglc** [python-pillow/Pillow#1684]
```python
im = Image.open('before.jpg').convert('RGBA')
im.save('after.jpg','jpeg',quality=100)
```
before.jpg main color is (190,31,29) ,but after the code execute ,the main color is (186,0,1).

hmmm....is there anything wrong in my code ? or it's bug?

**Comment by zhanglc** [comment]
may be the color change after open 
``` python
im = Image.open('before.jpg')
im.save('after.jpg','jpeg',quality=100)
```

**Comment by lilydjwg** [comment]
Nothing is wrong. It's a feature from the lossful JPEG format. Open, save, compare, you'll see loss, for any JPEG that hasn't been saved enough times. (new format of JPEG may do losslessly, I'm not sure.)
