### ISSUE TITLE
Wrong libjpeg version:  IOError: encoder error -2 when writing image file

### ISSUE THREAD

**Issue by miohtama** [python-pillow/Pillow#169]
I came across this peculiar case of libjpeg versions:

```
from PIL import Image ; im = Image.open("test.png") ; im.save("test2.jpg") ; im.save("test2.png")
Wrong JPEG library version: library is 62, caller expects 80
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "/srv/plone/python/python-2.7/lib/python2.7/site-packages/Pillow-1.7.8-py2.7-linux-x86_64.egg/PIL/Image.py", line 1437, in save
    save_handler(self, fp, filename)
  File "/srv/plone/python/python-2.7/lib/python2.7/site-packages/Pillow-1.7.8-py2.7-linux-x86_64.egg/PIL/JpegImagePlugin.py", line 471, in _save
    ImageFile._save(im, fp, [("jpeg", (0,0)+im.size, 0, rawmode)])
  File "/srv/plone/python/python-2.7/lib/python2.7/site-packages/Pillow-1.7.8-py2.7-linux-x86_64.egg/PIL/ImageFile.py", line 502, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

This situation can e.g. happen if
- You have libjpeg8 installed on your Ubuntu Linux box
- You then try to install Pillow using some recipes (buildout.python) which does static libjpeg compiliation

The tricky part here is that
- You detect the error in run-time
- _IOError: encoder error -2 when writing image file_ is the visible sympton
- ...but apparently there is another error message going stdout (stderr?) which is actually meaningful: Wrong JPEG library version: library is 62, caller expects 80

If you are running any server-side software (web application) you will miss this stdout message and this issue becomes ridiculous difficult to debug.

I am not sure how the issue should be solved. The best solution would be change the exception message to reflect the actual situation more clearly, though this case can be rare.

Update: Also there is another gotcha: This error can transform itself to the following (even if it's saving, not reading):

```
   IOError: broken data stream when reading image file
```

... which is even more misleading

**Comment by David-Grob** [comment]
I was having a similar issue and wanted to share my solution here to help someone in the future. The only thing that worked for me was forcing pip to build pillow from source after installing the dev version of the needed libraries (my code was editing a jpg and adding a label using a custom font). This was on a ARM based embedded device running Ubuntu Linux using Python 3.7.3 in a docker container.

`apt-get install -y libjpeg-dev libfreetype6-dev
pip3 install pillow --global-option="build_ext" --global-option="--enable-jpeg" --global-option="--enable-freetype" `

**Comment by jackmahoney** [comment]
I'm also having same issues on python 3.6.8 and Ubuntu 18.04 - don't have a fix yet.

`Wrong JPEG library version: library is 80, caller expects 90`

**Comment by aclark4life** [comment]
@jackmahoney Well we're all in quarantine so may as well try to "fix it". I assume you aren't using Buildout, but you have multiple jpegs installed … did you install a wheel or compile source?

**Comment by radarhere** [comment]
Closing due to lack of response.
