### ISSUE TITLE
Pasting image with a 2-tuple doesn't behave as expected/documented in docstring.

### ISSUE THREAD

**Issue by rbonestell** [python-pillow/Pillow#1691]
The docstring on `Image.paste` indicates that if a 2-tuple value is provided for `box` then it will interpret that value as the upper-left corner (https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1278), however the code following the docstring treats it as a lower-left corner and is commented describing such behavior (https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1298, https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1308).

**Comment by radarhere** [comment]
The way that I read it, `box = box + (box[0]+size[0], box[1]+size[1])` treats the 2-tuple value as a upper-left corner, adding `size` values to generate lower-right third and fourth values for the tuple. So it's the comment at 1298 that is wrong.

Feel free to correct my understanding.

**Comment by rbonestell** [comment]
The resulting second point has a higher Y value than the first point by a value of `size[1]` which I interpret to mean that it will be higher than the previous point. To make the next point lower, wouldn't it be `box = box + (box[0]+size[0], box[1]-size[1])`?
