### ISSUE TITLE
Extract frames from animated gif, every frame is not correct except the first frame when I save it to png file

### ISSUE THREAD

**Issue by fengjianque** [python-pillow/Pillow#1692]
I want to extract frames from an animated gif image, and save every frame into png format, but i found the png is not correct in some area except the first frame.

```python
   im = Image.open('earth.gif')
   try:
        while True:
            new_frame = im.convert('RGBA')
            new_frame.save('foo%02d.png' % im.tell(), 'PNG')
            im.seek(im.tell()+1)
    except EOFError:
        pass
```

This is origin image  
earth.gif
![earth](https://cloud.githubusercontent.com/assets/1113985/12680212/78cfae22-c6e3-11e5-893b-5ade3b10408d.gif)

This is the second frame which i use my program got.
![foo01](https://cloud.githubusercontent.com/assets/1113985/12680343/4b238c04-c6e4-11e5-9ef5-4af0e19af226.png)

And the second frame shoud be(correct one):
![image](https://cloud.githubusercontent.com/assets/1113985/12680567/888ab832-c6e5-11e5-86e0-9aaa7dc6d6f9.png)

the different area(red mark) between them:
![diff](https://cloud.githubusercontent.com/assets/1113985/12680935/2b160984-c6e7-11e5-825c-08d0bfcf231e.png)

other frames has the same problem, is it a bug in GifImagePlugin.py?  
Tell me what i should do ?

**Comment by radarhere** [comment]
While I can't say for certain, I suspect that this is related to #1525

**Comment by radarhere** [comment]
Is the animated GIF that you have provided one that could be used as a test image and subsequently released under Pillow's license?

**Comment by fengjianque** [comment]
> While I can't say for certain, I suspect that this is related to #1525

I use the patch you provided in #1525, it does't work。And it throws exception:
```
palette_bytes = im.im.getpalette("RGB")[:palette_byte_number]
ValueError: image has no palette
```

**Comment by fengjianque** [comment]
The above GIF i used for testing is downloaded from:
[https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Rotating_earth_%28large%29.gif/200px-Rotating_earth_%28large%29.gif](https://upload.wikimedia.org/wikipedia/commons/thumb/2/2c/Rotating_earth_%28large%29.gif/200px-Rotating_earth_%28large%29.gif)

**Comment by radarhere** [comment]
Thanks for the link. The licensing for that file can be found at https://commons.wikimedia.org/wiki/File:Rotating_earth_(large).gif#Licensing

**Comment by RiTu1337** [comment]
Try my answer to a similar issue here: http://stackoverflow.com/questions/35613716/imagemagick-pillow-generate-malformed-gif-frames/35615319#35615319

**Comment by radarhere** [comment]
I've created PR #5857 to resolve this.

![second](https://user-images.githubusercontent.com/3112309/143823879-ed87735f-7baf-4771-a651-e3d550ac386d.png)
