### ISSUE TITLE
IOError("cannot identify image file") being raised when using io.BytesIO with pillow

### ISSUE THREAD

**Issue by Space-Cat** [python-pillow/Pillow#1707]
I have one instance of io.BytesIO, which I'll call MyBytes, and two instances of PIL.Image, which I'll call MyImage, and MyImage2. After I call MyBytes.write() and then call MyImage.open(MyBytes) an IOError("cannot identify image file") error is raised.
If I call MyImage.save(MyBytes, "JPEG") and then call MyImage2.open(MyBytes), the same error is rasied. 

In both cases the the only solution I could find was to call MyBytes.seek(0) right beforehand.

I believe that PIL.Image.save(fp) and PIL.Image.open(fp) should always call fp.seek(0) as a default behavior to prevent this problem. IOError("cannot identify image file") was a very misleading error message.

**Comment by radarhere** [comment]
I can see that you've made your case for seeking to zero before opening. Unless I'm missing something though, I can't see an argument for changing the seek behaviour surrounding saving. Would you be able to elaborate on that?

**Comment by Space-Cat** [comment]
If I do:
`img.save(newImgBytes, "JPEG", quality=JpgQuality)
data=newImgBytes.read()`
Then data contains nothing.

But if I do 
`img.save(newImgBytes, "JPEG", quality=JpgQuality)
newImgBytes.seek(0)
data=newImgBytes.read()`
Data contains the entire image and my script works perfectly
