### ISSUE TITLE
3.1.1.tar.gz link broken on pipy

### ISSUE THREAD

**Issue by catskul** [python-pillow/Pillow#1716]
https://pypi.python.org/packages/source/P/Pillow/Pillow-3.1.1.tar.gz#md5=d382a86c4b9b1c8de684bd00dad43bb8

Hangs until timeout. Preventing builds on CI server.

**Comment by hugovk** [comment]
3.1.1 is being released now but PyPI is being difficult.

I recommend either trying again later or installing 3.1.0 in the meantime.

**Comment by hugovk** [comment]
@wiredfool Please could you check this link?

**Comment by wiredfool** [comment]
That hash appears to be correct, when compared to what I built and uploaded. It's downloading for me now, but pypi has been giving a bunch of 500 errors when uploading today.

**Comment by catskul** [comment]
Working for me now to. Closing.
