### ISSUE TITLE
GIF decoder can't handle zero-length extension blocks

### ISSUE THREAD

**Issue by benrg** [python-pillow/Pillow#1718]
To reproduce:

``` python
>>> import io, PIL.Image
>>> PIL.Image.open(io.BytesIO(bytes.fromhex('47 49 46 38 39 61 01 00 01 00 80 00 00 FF FF FF 00 00 00 21 FE 00 2C 00 00 00 00 01 00 01 00 00 02 02 44 01 00 3B')))
```

**Comment by radarhere** [comment]
I assume that this image is able to be redistributed as a image in the test suite under Pillow's license?

**Comment by radarhere** [comment]
Just to post information here, an EOFError is being raised at https://github.com/python-pillow/Pillow/blob/master/PIL/GifImagePlugin.py#L266

**Comment by radarhere** [comment]
I have created PR #3479
