### ISSUE TITLE
Trojan in Pillow-2.9.0.win-amd64-py2.7.exe 

### ISSUE THREAD

**Issue by zveer** [python-pillow/Pillow#1721]
When I'm trying to download Pillow-2.9.0.win-amd64-py2.7.exe (or any other *.exe files) windows security blocks it with error (Trojan inside reason) 
![image](https://cloud.githubusercontent.com/assets/14909087/12890085/bb3601ea-ce8a-11e5-977a-6fadbc67f7cb.png)
Is there any explanation?

**Comment by hugovk** [comment]
@zveer Where are you downloading from?

**Comment by hugovk** [comment]
I checked [Pillow-2.9.0.win-amd64-py2.7.exe](https://pypi.python.org/packages/2.7/P/Pillow/Pillow-2.9.0.win-amd64-py2.7.exe#md5=69d0f72b660154a6947875e45af6814f) from https://pypi.python.org/pypi/Pillow/2.9.0 on a couple of online scanners and it came out clean from both. 

The first checked against 54 scanners:

 * https://www.virustotal.com/en/file/ec163b7277c1c9ec6365c839c85c46cb01d1bb66137231ec5b97b34bb794b486/analysis/1454963651/

And the second 43 scanners:

 * https://www.metascan-online.com/#!/results/file/1d2b835390494236b0558134349d8aa9/regular

**Comment by zveer** [comment]
Everything is ok now, seems it was a tamporary failure. I tried to download
the library from this page:
https://pypi.python.org/pypi/Pillow/3.1.1
[image: Inline images 1]

On 8 February 2016 at 23:30, Hugo <notifications@github.com> wrote:

> I checked Pillow-2.9.0.win-amd64-py2.7.exe
> <https://pypi.python.org/packages/2.7/P/Pillow/Pillow-2.9.0.win-amd64-py2.7.exe#md5=69d0f72b660154a6947875e45af6814f>
> from https://pypi.python.org/pypi/Pillow/2.9.0 on a couple of online
> scanners and it came out clean from both.
>
> The first checked against 54 scanners:
>
>    -
>    https://www.virustotal.com/en/file/ec163b7277c1c9ec6365c839c85c46cb01d1bb66137231ec5b97b34bb794b486/analysis/1454963651/
>
> And the second 43 scanners:
>
>    -
>    https://www.metascan-online.com/#!/results/file/1d2b835390494236b0558134349d8aa9/regular
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/python-pillow/Pillow/issues/1721#issuecomment-181558881>
> .
>



-- 
с ув. Максим
