### ISSUE TITLE
Question about Integer overflow in Resample.c

### ISSUE THREAD

**Issue by apoleon** [python-pillow/Pillow#1737]
Hello, I am currently preparing a security update of pillow and python-imaging for Debian's oldstable and stable versions. An integer overflow in Resample.c was fixed by https://github.com/python-pillow/Pillow/commit/41fae6d9e2da741d2c5464775c7f1a609ea03798 but it seems that older versions like 1.1.7 or 2.6.1 are not affected because they don't use this code. For these versions the code is in Antialias.c. Can anyone confirm or disconfirm that this assumption is correct?

**Comment by wiredfool** [comment]
That code was added in Pillow 2.7, so anything prior to that would not be vulnerable.

**Comment by apoleon** [comment]
Am 20.02.2016 um 16:32 schrieb wiredfool:
> That code was added in Pillow 2.7, so anything prior to that would not
> be vulnerable.

Thank you for the clarification
