### ISSUE TITLE
Animated GIF frames rendered incorrectly

### ISSUE THREAD

**Issue by czablocki** [python-pillow/Pillow#1742]
The attached animated .gif (bad.gif) is rendered incorrectly by PIL, with a lot of artifacts and noise in its frames (eg: bad_frame_2.gif). The same file plays correctly in web browsers and image viewers on Windows and Linux.

After uploading and re-downloading bad.gif from imgur.com, I got good.gif, which displays correctly in everything. 

good.gif is slightly different in size and has slightly different color tables, but the part I'd expect to be important (transparency index and corresponding palette entry) is the same.

The only remarkable things about bad.gif that I noticed is the transparency index (0) maps to white (255,255,255) and it has NoDispose (1) as its dispose_method

Here's the test script:

```python
from PIL import Image

image = Image.open("good.gif")
#image = Image.open("bad.gif")

#actually 18 frames long
for x in range(0, 2):
    image.seek(x)
    image.show()
```

bad.gif
![bad](https://cloud.githubusercontent.com/assets/2029052/13278670/07b81e74-da87-11e5-991c-5ab9bf41515e.gif)
![bad_frame_2](https://cloud.githubusercontent.com/assets/2029052/13278669/07b825d6-da87-11e5-9406-6360771e6af1.gif)

good.gif
![good](https://cloud.githubusercontent.com/assets/2029052/13278668/07b4f06e-da87-11e5-909c-b6ce38e4470a.gif)
![good_frame_2](https://cloud.githubusercontent.com/assets/2029052/13278667/07b4e31c-da87-11e5-81e5-a2d87ebcb857.gif)

**Comment by radarhere** [comment]
@Fiona1729 I'm not quite certain what you're saying. If you'd like us to investigate, please provide a self-contained example.

**Comment by radarhere** [comment]
I've created PR #5857 to resolve this.

![1](https://user-images.githubusercontent.com/3112309/143823518-41a440e0-cb29-440a-a5e8-a7a7efb14b00.png)
