### ISSUE TITLE
Import order causes changes in behaviour

### ISSUE THREAD

**Issue by birgander2** [python-pillow/Pillow#1743]
I encounter a rather strange behaviour / bug. When importing first a certain package developed here in-house before importing pillow, things are obviously going wrong.
```
>>> import mypackage
>>> from PIL import Image
>>> img = Image.open("something.jpg")
>>> img.show()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/Image.py", line 1718, in show
    _show(self, title=title, command=command)
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/Image.py", line 2466, in _show
    _showxv(image, **options)
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/Image.py", line 2471, in _showxv
    ImageShow.show(image, title, **options)
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/ImageShow.py", line 51, in show
    if viewer.show(image, title=title, **options):
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/ImageShow.py", line 77, in show
    return self.show_image(image, **options)
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/ImageShow.py", line 96, in show_image
    return self.show_file(self.save_image(image), **options)
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/ImageShow.py", line 92, in save_image
    return image._dump(format=self.get_format(image))
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/Image.py", line 576, in _dump
    self.load()
  File "/opt/anaconda/lib/python3.5/site-packages/PIL/ImageFile.py", line 218, in load
    "(%d bytes not processed)" % len(b))
OSError: image file is truncated (228787 bytes not processed)
```
When I do not import my package, everything is fine:
```
>>> from PIL import Image
>>> img = Image.open("something.jpg")
>>> img.show()
```
Another bizarre but probably related effect happens when using scipy (scipy uses pillow, right?):
```
>>> import mypackage
>>> from scipy.misc import imread
>>> imread("something.jpg")
array(<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=1075x840 at 0x7F0CFBDDA198>, dtype=object)
```
while not importing first my own package first gives the correct result:
```
>>> from scipy.misc import imread  
>>> imread("something.jpg")      
array([[[255, 255, 255],
        [255, 255, 255],
        [254, 254, 254],
        ..., 
        [255, 255, 255],
```
I'm not sure if this is a bug in PIL or if I'm doing something wrong in my package. However, I'm certainly not tweaking around with pillow and scipy in there, just using it. Any ideas? I am using pillow 3.1.0 on python 3.5.1 64 bit (anaconda 2.5.0) / linux.

**Comment by wiredfool** [comment]
1) It's in the `Image.load()`, that's called from `Image.show()`, so we can cut a bunch out of the stack that way. 

2)
If you try:
```
from PIL import Image
import mypackage
img = Image.open("something.jpg")
img.load()
```
Does it work?  If so, does your package work?

I'd suspect that somewhere in your package you're loading a local module that's shadowing a python builtin that we're using, and then when we try to import it, we get your version. Or possibly it's monkeypatching something.

**Comment by birgander2** [comment]
This was a good hint and indeed the workaround you proposed seems to work. However, I would like to resolve since I's suspect that something is still not ok in the background. By commenting out some imports I was able to track down the source. It is not my own code, but an import of the gdal package. A simple:
```
from osgeo import gdal
from scipy.misc import imread
imread("something.jpg")
````
triggers the error. Unluckily, I need gdal in my project. So it seems the error is on their side, not yours - sorry for bothering and thanks for the quick help!

**Comment by hugovk** [comment]
@birgander2 You can use pylint to find reused builtins. For example:

```
pip install -U pylint
pylint PIL --disable=all --enable=W0141
```

Watch out for false positives for `map` and `filter`.
