### ISSUE TITLE
crop does not sanity check for integers

### ISSUE THREAD

**Issue by lambdafu** [python-pillow/Pillow#1744]
Hi,
with Pillow 3.1.1:
```
>>> Image.new("RGB", (10, 10)).crop((0.3, 0.3, 4.6, 4.6)).size
(4.3, 4.3)
```

This then throws "integer argument expected, got float" when one tries to call convert() on the image or use the size in new().  Either crop should round/truncate or throw the error immediately.

**Comment by hugovk** [comment]
I think rounding to the nearest integer makes most sense, this is what ImageMagick does.

I've created PR #1745.
