### ISSUE TITLE
doc difference rotate vs transpose

### ISSUE THREAD

**Issue by lambdafu** [python-pillow/Pillow#1746]
The docs state: "There’s no difference in performance or result between transpose(ROTATE) and corresponding rotate() operations."

That's not correct.  Rotate preserves the image geometry (leading to clipping), while transpose transforms it along with the pixel data:

```
>>> Image.open("0001.jpg").size
(2490, 3487)
>>> Image.open("0001.jpg").rotate(90).size
(2490, 3487)
>>> Image.open("0001.jpg").transpose(Image.ROTATE_90).size
(3487, 2490)
```

**Comment by radarhere** [comment]
Thanks for pointing that out. How do you feel about #1751 instead?
