### ISSUE TITLE
Image.verify raises struct.error (instead of IndexError) on Pillow > 2.7.0

### ISSUE THREAD

**Issue by melinath** [python-pillow/Pillow#1755]
```
Traceback (most recent call last):
  File "daguerre/tests/unit/test_adjustments.py", line 329, in test_adjust__broken
    self.assertRaises(IndexError, image.verify)
  File "unittest/case.py", line 475, in assertRaises
    callableObj(*args, **kwargs)
  File "PIL/PngImagePlugin.py", line 544, in verify
    self.png.verify()
  File "PIL/PngImagePlugin.py", line 163, in verify
    self.crc(cid, ImageFile._safe_read(self.fp, length))
  File "PIL/PngImagePlugin.py", line 142, in crc
    crc2 = i16(self.fp.read(2)), i16(self.fp.read(2))
  File "PIL/_binary.py", line 53, in i16be
    return unpack(">H", c[o:o+2])[0]
error: unpack requires a string argument of length 2
```

Similar to #1163 in form, but maybe not in cause.

**Comment by melinath** [comment]
Here's the image I'm trying to verify:

![broken](https://cloud.githubusercontent.com/assets/299979/13469525/961aa10c-e05c-11e5-8e0a-333175820e04.png)

**Comment by melinath** [comment]
Verified that this test (for IndexError) works on 2.3.0, the last version I was testing with. I'll check a few more versions to try to narrow it down.

**Comment by melinath** [comment]
2.9.0: Broken
2.8.2: Broken
2.7.0: Works

**Comment by wiredfool** [comment]
The underlying implementation of the binary functions changed to `struct.unpack` at about 2.7 and every time that we throw a `struct.error` it's because of that change.

**Comment by hugovk** [comment]
That change was in PR #1121, which was released in 2.8.0.

**Comment by radarhere** [comment]
Given that you've created a PR in another project to act on this, are you right for this issue to be closed?

**Comment by melinath** [comment]
I mean... I need to support both in any case, so I don't care. The question is more what you feel is a more appropriate error as far as I'm concerned. :-) I'm guessing struct.error might make more sense? But OTOH I personally wouldn't have known that was a struct.error if you hadn't told me, which makes the error message pretty opaque.

But yeah, I personally don't need anything from you on this.

**Comment by wiredfool** [comment]
We've treated this as an error for opening files, it makes sense to do it for verify. (though, verify is a very inconsistently supported function, currently it's only available for pngs)
