### ISSUE TITLE
Pillow should implement __copy__ and __deepcopy__

### ISSUE THREAD

**Issue by temp56817906847** [python-pillow/Pillow#1769]
The load() function fails after Python copy under some circumstances, e.g. after crop and Python copy:

    import copy
    import PIL.Image

    pilIm = PIL.Image.new('RGBA', (100, 100))
    pilImCopy = copy.copy(pilIm)
    pilImCopy.load()  # fine

    cropped = pilIm.crop((80,80, 90,90))
    croppedCopy = copy.copy(cropped)  # same with deepcopy
    croppedCopy.load()  # AttributeError: _ImageCrop__crop
  
results in:

    Traceback (most recent call last):
      File "pillow_test_bug.py", line 10, in <module>
        croppedCopy.load()  # AttributeError: _ImageCrop__crop
      File "C:\Python27\lib\site-packages\PIL\Image.py", line 1963, in load
        if self.__crop:
      File "C:\Python27\lib\site-packages\PIL\Image.py", line 628, in __getattr__
        raise AttributeError(name)
    AttributeError: _ImageCrop__crop

  
Fix might be as easy as adding these lines to the Image class right below the copy function:

    __copy__ = copy
    __deepcopy__ = copy

**Comment by radarhere** [comment]
Thanks for the suggestion. I've created a PR to add the __copy__ method.

I suspect that properly implementing __deepcopy__ would be less trivial, as you would have to ensure that all objects used by the different plugins were copied. If you'd like to look into it, you're welcome to create a PR for review.

**Comment by temp56817906847** [comment]
Great! I see, `__deepcopy__` may be more difficult. But this is very useful, thanks!

**Comment by radarhere** [comment]
The PR has now been merged. Unless you would like to hold out hope for deepcopy, this issue can now be closed.

**Comment by temp56817906847** [comment]
Thanks!
