### ISSUE TITLE
get different image from same numpy.array

### ISSUE THREAD

**Issue by yiyuezhuo** [python-pillow/Pillow#1771]
I use Pillow to transform my image to 0,1 matrix to feed theano. But I found some confusing behavior as code below.

    Image.fromarray(X_train[0][0],'1')
    Out[69]: 
![image](https://cloud.githubusercontent.com/assets/12798270/13778896/3cf31ab8-eaf3-11e5-9f1a-fd25bb9b713d.png)

    Image.fromarray(X_train[0][0].astype('float32')>0.5,'1')
    Out[70]: 
![image](https://cloud.githubusercontent.com/assets/12798270/13778909/4dc2497c-eaf3-11e5-88ae-1a72b1da334a.png)

but that's equal anyway.

    np.all(X_train[0][0]==(X_train[0][0].astype('float32')>0.5))
    Out[71]: True

**Comment by wiredfool** [comment]
I think this is the same as #350, as (numbers) > 0.5 is a boolean, and booleans don't convert to a mode '1' array.
