### ISSUE TITLE
Pull Image Segmentation in ImageOps

### ISSUE THREAD

**Issue by mayukh18** [python-pillow/Pillow#1777]
Will it be a good idea to contribute a segmentation method in ImageOps? My code works best on grayscale or each layer of color and is implementation of fuzzy c-means clustering. It can work on a total RGB or CMYK image too, but with some color inaccuracies if we choose very few color clusters or segments.

**Comment by wiredfool** [comment]
I think that segmentation might be more appropriate for a higher level toolkit like scipy or opencv. We don't really have anything that's related to computer vision, other than the low level tools to deal with image formats.

**Comment by rcarmo** [comment]
I'd like to see the ability to segment by color. Right now it's pretty hard to build masks...
