### ISSUE TITLE
Cannot save thumbnail'd medium-large TIFFs

### ISSUE THREAD

**Issue by Twangist** [python-pillow/Pillow#1797]
### What did you do?

Load a 3.5 MB TIFF by filename, call .thumbnail((100, 100)) on the image, then call the image's .save() method, with a new filename.
### What did you expect to happen?

I expected that the image would be saved :)
### What actually happened?

"TypeError: write_byte() takes 2 positional arguments but 21581 were given"
However, this works as expected with a smaller TIF (1.2 MB) -- thumbnail is saved, no error.
### What versions of Pillow and Python are you using?

Python 3.4.2, Pillow 3.2.0, but the error also exists (with a slightly different exception message), in Pillow 2.9.x.

Straight-line code with no dependencies that illustrates the issue:

``` python
from PIL import Image

# Open a smaller (1.2 MB) TIF and make it a "thumbnail":
image = Image.open("small.tif")
image.thumbnail((100, 100))
# Save it:
image.save("small--100x100-thumbnail.tif")
# That worked.

# - - - - - - - - - - - - - - - - - - - - - - - -
# Now try with a medium-large (3.5 MB) tif.
# Open it:
image = Image.open("medium.tif")

# First, resize it to 100x100 (ignoring niceties about preserving aspect ratio)
# and save, two ways -- both work:
image_resized = image.resize((100,100), resample=Image.BICUBIC)
image_resized.save("medium--100x100-resized-bicubic.tif")

image_resized = image.resize((100,100), resample=Image.LANCZOS)
image_resized.save("medium--100x100-resized-lanczos.tif")
# That went well.

# Now try thumbnailing and saving:
image.thumbnail((100, 100))
# Try to save it -- blow up:
image.save("medium--100x100-thumbnail.tif")
```

**\* P.S.**\* I tried to attach two sample TIFs, but regrettably github says:

> Unfortunately, we don’t support that file type. Try again with a PNG, GIF, JPG, DOCX, PPTX, XLSX, TXT, PDF, or ZIP. 

Of course that's a silly suggestion.

**Comment by hugovk** [comment]
You can zip the image or just add another extension to fool GitHub.

**Comment by Twangist** [comment]
Thanks, I will (lol/doh, it's early)

**Comment by Twangist** [comment]
[small-and-medium-tifs.zip](https://github.com/python-pillow/Pillow/files/201292/small-and-medium-tifs.zip)
The two example TIFs used by the code, in a zip file.

**Comment by radarhere** [comment]
The simplest code to reproduce the problem is

    from PIL import Image
    Image.open("medium.tif").save("medium2.tif")
It is failing on the `XMP` and `PhotoshopInfo` tags.

So as an immediate fix, I can offer

    from PIL import Image
    im = Image.open("medium.tif")
    del im.ifd[700]
    del im.ifd[34377]
    im.save("medium2.tif")

**Comment by Twangist** [comment]
Thanks for the workaround.

**Comment by wiredfool** [comment]
Right, tiff metadata.

**Comment by radarhere** [comment]
The simplest example from my earlier comment no longer produces an error. Testing, I find that https://github.com/python-pillow/Pillow/pull/2719 resolves the issue.
