### ISSUE TITLE
3.3.0 Release July 1, 2016

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1800]
Tracking issue.

**Comment by radarhere** [comment]
So, any remaining priorities for this release?

**Comment by wiredfool** [comment]
There's been a lot of C level changes in this iteration.

I really want to land the malloc check: pr #1781

#1934 is something that I think should land, but I'd like someone else to look at it and agree to the approach. 

Something of the palette issue (#1593) should land, I think I'm leaning to the bytearray approach, but comments either way would be useful. 

If I have time, I'd like to sweep though all of the numpy/fromarray issues and consolidate/resolve them. The ICC profile stuff is in that category too.

**Comment by homm** [comment]
From my PR's I want to see in next release at least #1909 and #1970. Anything else is less important. Also, I want #1910 to be addressed, but I don't have a fix.

**Comment by wiredfool** [comment]
I think we've hit all that. 

@homm, what are your thoughts on bugfixes in #1986 and #1991?

The only other one that I'm considering at this point is #1846, which is just waiting on documentation. It's low risk, as it just adds behavior that was previously broken. 

Apart from that, freeze except for docs.

**Comment by aclark4life** [comment]
Thanks all for working on this release, let me know if you need anything! <3

**Comment by wiredfool** [comment]
Release is tagged and source uploaded.

**Comment by wiredfool** [comment]
@cgohlke Would appreciate windows binaries when you can.

**Comment by wiredfool** [comment]
So, postmortem of sorts for this release. This feels like a big release, especially in terms of landing things in C land. Personally, I'm time constrained on reviews especially, so there are still a lot of PRs left.

As I see it, PRs fall into ~~several~~ categories;
- Clearly no. 
- Eh, Suspicious without further input
- Those needing tests or documentation
- Those that are clearly 0 effect, and are for style.
- Those that are possibly 0 effect, but take a close reading to make sure.
- Bug fixes with tests
- Small extensions of the api
- Significant, but low risk.
- Significant, high risk
- Those that resemble flies from a distance

I think we've gotten most of the big ones into this release. There's a host in the needing more or possibly 0 effect categories.

**Comment by cgohlke** [comment]
Here you go: http://www.lfd.uci.edu/~gohlke/download/Pillow-3.3.0.win-dist.zip
The wheels require pip >= 8.
Maybe it's time to deprecate egg and exe binaries?

**Comment by aclark4life** [comment]
@cgohlke Probably time, though I'd hate to do that …

**Comment by wiredfool** [comment]
There are a lot of files. I'm not clear on how many people would likely be impacted.

**Comment by wiredfool** [comment]
49 binaries, 2 source packages.

**Comment by hugovk** [comment]
Pillow 3.2.0 download stats from PyPI using [Vanity](https://github.com/aclark4life/vanity) (assuming https://github.com/aclark4life/vanity/issues/22 is fixed) show of 64,717 total downloads: 
 * 359 egg 
 * 467 exe
 * 6,947 whl
 * 54,608 zip
 * 2,336 tar.gz

In case there's some caching of stats; for 3.1.0 (inc. rc1), out of 452,851 total downloads there's a similar share:
 * 6,827 egg
 * 5,753 exe
 * 62,823 whl
 * 19,768 zip
 * 357,680 tar.gz

```bash
$ vanity pillow -p 3.2.0.*egg
    Pillow-3.2.0-py3.5-win32.egg    2016-04-01           35
Pillow-3.2.0-py3.5-win-amd64.egg    2016-04-01           22
    Pillow-3.2.0-py3.4-win32.egg    2016-04-01           44
Pillow-3.2.0-py3.4-win-amd64.egg    2016-04-01           17
    Pillow-3.2.0-py3.3-win32.egg    2016-04-01           13
Pillow-3.2.0-py3.3-win-amd64.egg    2016-04-01            9
    Pillow-3.2.0-py3.2-win32.egg    2016-04-01            9
Pillow-3.2.0-py3.2-win-amd64.egg    2016-04-01            9
    Pillow-3.2.0-py2.7-win32.egg    2016-04-01          134
Pillow-3.2.0-py2.7-win-amd64.egg    2016-04-01           44
    Pillow-3.2.0-py2.6-win32.egg    2016-04-01           12
Pillow-3.2.0-py2.6-win-amd64.egg    2016-04-01           11
-----------------------------------------------------------
Pillow has been downloaded 359 times!
```
```bash
$ vanity pillow -p 3.2.0.*exe
    Pillow-3.2.0.win32-py3.5.exe    2016-04-01           51
    Pillow-3.2.0.win32-py3.4.exe    2016-04-01           54
    Pillow-3.2.0.win32-py3.3.exe    2016-04-01            9
    Pillow-3.2.0.win32-py3.2.exe    2016-04-01           11
    Pillow-3.2.0.win32-py2.7.exe    2016-04-01           37
    Pillow-3.2.0.win32-py2.6.exe    2016-04-01            9
Pillow-3.2.0.win-amd64-py3.5.exe    2016-04-01          111
Pillow-3.2.0.win-amd64-py3.4.exe    2016-04-01           81
Pillow-3.2.0.win-amd64-py3.3.exe    2016-04-01           14
Pillow-3.2.0.win-amd64-py3.2.exe    2016-04-01            9
Pillow-3.2.0.win-amd64-py2.7.exe    2016-04-01           67
Pillow-3.2.0.win-amd64-py2.6.exe    2016-04-01           14
-----------------------------------------------------------
Pillow has been downloaded 467 times!
```
```bash
$ vanity pillow -p 3.2.0.*whl
                                                                                     Pillow-3.2.0-cp35-none-win_amd64.whl    2016-04-01          471
                                                                                         Pillow-3.2.0-cp35-none-win32.whl    2016-04-01          566
Pillow-3.2.0-cp35-cp35m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl    2016-04-01          753
                                                                                     Pillow-3.2.0-cp34-none-win_amd64.whl    2016-04-01          246
                                                                                         Pillow-3.2.0-cp34-none-win32.whl    2016-04-01          232
Pillow-3.2.0-cp34-cp34m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl    2016-04-01          159
                                                                                     Pillow-3.2.0-cp33-none-win_amd64.whl    2016-04-01           13
                                                                                         Pillow-3.2.0-cp33-none-win32.whl    2016-04-01           36
Pillow-3.2.0-cp33-cp33m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl    2016-04-01           12
                                                                                     Pillow-3.2.0-cp32-none-win_amd64.whl    2016-04-01            8
                                                                                         Pillow-3.2.0-cp32-none-win32.whl    2016-04-01           10
                                                                                     Pillow-3.2.0-cp27-none-win_amd64.whl    2016-04-01          773
                                                                                         Pillow-3.2.0-cp27-none-win32.whl    2016-04-01        1,308
Pillow-3.2.0-cp27-cp27m-macosx_10_6_intel.macosx_10_9_intel.macosx_10_9_x86_64.macosx_10_10_intel.macosx_10_10_x86_64.whl    2016-04-01        2,201
                                                                                     Pillow-3.2.0-cp26-none-win_amd64.whl    2016-04-01          102
                                                                                         Pillow-3.2.0-cp26-none-win32.whl    2016-04-01           57
----------------------------------------------------------------------------------------------------------------------------------------------------
Pillow has been downloaded 6,947 times!
```
```bash
$ vanity pillow -p 3.2.0.*zip
Pillow-3.2.0.zip    2016-04-01       54,608
-------------------------------------------
Pillow has been downloaded 54,608 times!
```
```bash
$ vanity pillow -p 3.2.0.*tar.gz
Pillow-3.2.0.tar.gz    2016-04-01        2,336
----------------------------------------------
Pillow has been downloaded 2,336 times!
```

**Comment by wiredfool** [comment]
The difference between the 3.1 and 3.2 stats is somewhat unbelievable.

**Comment by aclark4life** [comment]
I think stats are still considered broken until warehouse https://github.com/aclark4life/vanity/issues/22

**Comment by wiredfool** [comment]
Thanks everyone!  We'll be planning on doing this all again in 3 months...
