### ISSUE TITLE
New long running branch: tests-for-open-bugs

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1801]
We've got a lot of bugs. Shame if some of them got squashed. 

I've started a long running branch in the main pillow repo, with the intention of collecting test failures for bugs that have been reported in the issues. I'm hoping that we'll build up a collection of tests that fail, which should do 2 things:
- Give use a good handle on what's not working, in a way that we can see numerically and not just ignore because it's on the second or third page of the issues list
- Reproduce a bug and provide a clear sign when it's complete. 
- Potentially give people a clear thing to work on. Take a failing test, pass it around, one less failing test on the wall. 

Send PRs to this branch with a test and a # link to the reporting issue. I'll periodically merge from master to bring things up to date.

**Comment by hugovk** [comment]
PR https://github.com/wiredfool/Pillow/pull/4 has failing tests for https://github.com/python-pillow/Pillow/issues/835.

**Comment by wiredfool** [comment]
(edited to clarify that the branch is in the main pillow repo)

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/1802 has failing tests for #835.

**Comment by aclark4life** [comment]
The ``Infrastructure`` label strikes again! :smile:

**Comment by aclark4life** [comment]
At some point, this policy should make it to our developer documentation then this issue can be closed.

**Comment by radarhere** [comment]
I don't think this caught on. #835 and #1462 were the only issues to have failing tests added, and those have both been resolved.

**Comment by wiredfool** [comment]
No, I’d say not.

**Comment by radarhere** [comment]
Do you mind if I delete the branch and close this?

**Comment by wiredfool** [comment]
No, it was an idea at the time, but as you said, it didn’t really work out.
