### ISSUE TITLE
Missing EPS mode: "cannot identify image file"

### ISSUE THREAD

**Issue by bmgraff** [python-pillow/Pillow#1816]
### What did you do?
Open an EPS file.

### What did you expect to happen?
To get an ImageFile object.

### What actually happened?
IOError: cannot identify image file ...

### What versions of Pillow and Python are you using?
Python 2.7.10
Pillow 3.1.1

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
from PIL import Image

i = Image.open('Little_Chief_Mountain_GNP1.eps')

```
[Little_Chief_Mountain_GNP1.eps.zip](https://github.com/python-pillow/Pillow/files/210533/Little_Chief_Mountain_GNP1.eps.zip)

It appears that EPS files are not supported upload types, so you'll have to unzip this one.

The problem is that there is an unsupported EPS image mode. Referencing the information at http://computer-programming-forum.com/36-postscript/08d33c9e914c1c55.htm, EPS files have a mode 4 that is CMYK. Therefore, line 204 of EpsImagePlugin.py looks like this:
```
    mode_map = {1: "L", 2: "LAB", 3: "RGB"}
```
but should look like this:
```
    mode_map = {1: "L", 2: "LAB", 3: "RGB", 4: "CMYK"}
```

**Comment by radarhere** [comment]
Is the image that you've included one that could be incorporated into the Pillow test suite, and released under it's license?

**Comment by bmgraff** [comment]
Yes. The original image is from wikimedia, with an alteration-allowed license. I turned it into an EPS with appropriate attributes (mode).

**Comment by radarhere** [comment]
Never mind, I managed to convert one of the existing test images.

Thanks for reporting this. I've created a PR to make the change.

**Comment by pawelmhm** [comment]
I just stumbled on this issue and #1826 seems to fix my problem

**Comment by radarhere** [comment]
To note it here in this issue, PR #1826 has been superseded by PR #1846.

**Comment by wiredfool** [comment]
Fix has been merged
