### ISSUE TITLE
installation error in pillow in virtualenv in ubuntu 14.04

### ISSUE THREAD

**Issue by kartikdanidhariya** [python-pillow/Pillow#1827]
Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

i create one virtual env in ubuntu 14.04 and my python version 2.7.9
when i try ti install pillow using pip install pillow
so it return following error

"error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

----------------------------------------
Cleaning up...
Command /home/vrs/isma_108_second/bin/python -c "import setuptools, tokenize;__file__='/home/vrs/isma_108_second/build/pillow/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-4dHL8k-record/install-record.txt --single-version-externally-managed --compile --install-headers /home/vrs/isma_108_second/include/site/python2.7 failed with error code 1 in /home/vrs/isma_108_second/build/pillow
Traceback (most recent call last):
  File "/home/vrs/isma_108_second/bin/pip", line 11, in <module>
    sys.exit(main())
  File "/home/vrs/isma_108_second/local/lib/python2.7/site-packages/pip/__init__.py", line 185, in main
    return command.main(cmd_args)
  File "/home/vrs/isma_108_second/local/lib/python2.7/site-packages/pip/basecommand.py", line 161, in main
    text = '\n'.join(complete_log)
UnicodeDecodeError: 'ascii' codec can't decode byte 0xe2 in position 66: ordinal not in range(128)
"

i try with install dependency
"sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev tcl8.6-dev tk8.6-dev python-tk
"

but still get same error 

after i tried with 
sudo apt-get install python-dev

so it change the version of python from 2.7.4 to 2.7.9 but still error is same in virtual env

i also try with "easy_install pillow"

but still give same error

**Comment by wiredfool** [comment]
It looks like something in the log is not ascii, but that was triggered by some other error. Unfortunately, that error isn't showing up in the trace above. 

Could you download the source package from pypi, untar, and run `python setup.py install` from within the directory? That will push out much more useful logging.

**Comment by kartikdanidhariya** [comment]
out of virtualenv it install successfully issue occurs only in virtualenv

**Comment by kartikdanidhariya** [comment]
i tried with pypi untar and python setup.py install but still give error log in 



x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/decode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/encode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/map.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/display.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/outline.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/path.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Access.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/AlphaComposite.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Resample.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Bands.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/BitDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Blend.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Chops.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Convert.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/ConvertYCbCr.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Copy.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Crc32.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Crop.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Dib.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Draw.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Effects.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/EpsEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/File.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Fill.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Filter.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/FliDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Geometry.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/GetBBox.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/GifDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/GifEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/HexDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Histo.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/JpegDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/JpegEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/LzwDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Matrix.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/ModeFilter.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/MspDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Negative.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Offset.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Pack.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/PackDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Palette.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Paste.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Quant.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantOctree.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantHash.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/QuantHeap.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/PcdDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/PcxDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/PcxEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Point.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/RankFilter.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/RawDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/RawEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Storage.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/SunRleDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/TgaRleDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Unpack.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/UnpackYCC.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/UnsharpMask.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/XbmDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/XbmEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/ZipDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/ZipEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/TiffDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Incremental.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Jpeg2KDecode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/Jpeg2KEncode.o: No such file or directory
x86_64-linux-gnu-gcc: error: build/temp.linux-x86_64-2.7/libImaging/BoxBlur.o: No such file or directory
x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-fstack-protector-strong’
x86_64-linux-gnu-gcc: error: unrecognized command line option ‘-fstack-protector-strong’
error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by wiredfool** [comment]
That's still missing a bunch from the top of the run.  It should work in a virtual environment as that is how most of the development happens, so it's likely that somethings wrong with the setup in your specific virtual environment.  Try running the install command from a fresh virtual environment.

**Comment by kartikdanidhariya** [comment]
i tried that already five times in my local machine but still same issue

**Comment by wiredfool** [comment]
Your logs should start with this:
```
python setup.py install
running install
running bdist_egg
running egg_info
...
```
and contain a few lines like this: 
````
running build_ext
building 'PIL._imaging' extension
creating build/temp.linux-x86_64-2.7/libImaging
gcc -pthread -fno-strict-aliasing -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fPIC -DHAVE_LIBJPEG -DHAVE_OPENJPEG -DHAVE_LIBZ 
-DHAVE_LIBTIFF -I/usr/include/freetype2 -I/usr/local/include/openjpeg-2.0 -I/home/erics/Pillow/libImaging -I/home/erics/vpy27/include
 -I/usr/include/tcl8.5 -I/usr/local/include -I/usr/include -I/usr/include/python2.7 -I/usr/include/x86_64-linux-gnu -c _imaging.c -o 
build/temp.linux-x86_64-2.7/_imaging.o
```

What you've posted is the output from a later stage, where something has already failed. 

Since none of the .o files are available, I wonder if it's a permissions issue on the build directory.

**Comment by abidibo** [comment]
@kartikdanidhariya I had the same issues, in my case I was running out of memory! Increasing the RAM fixed it.
