### ISSUE TITLE
Pillow failed to install with pip on Debian Jessie

### ISSUE THREAD

**Issue by Pastafarianist** [python-pillow/Pillow#1835]
### What did you do?

Tried to install `mitmproxy` via `pip install --user mitmproxy` on Debian Jessie ARM.

### What actually happened?

Pillow was one of the dependencies and failed to install. Please see the complete `pip.log` at https://gist.github.com/Pastafarianist/20c4efb7a98ecb3ffabb5a0f1dfb85b5 . Note that Github has truncated it, but there is a link to the full file.

### What versions of Pillow and Python are you using?

Python 2.7.9, Pillow is the latest in Debian Jessie repository.

**Comment by wiredfool** [comment]
```
    ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting
```

You need to install the dependencies: http://pillow.readthedocs.org/en/3.2.x/installation.html#building-on-linux

See also https://github.com/python-pillow/Pillow/blob/master/depends/debian_8.2.sh
