### ISSUE TITLE
Transparency is lost when loading PNG with transparent black color

### ISSUE THREAD

**Issue by olt** [python-pillow/Pillow#1838]
I noticed a regression from #1239 

### Expected behavior

``info['transparency']`` in PIL stores either the palette index of the full transparent color, or the opacity values for all palette entries. 
So it's 255 if all pixels with the value 255 are transparent, but it's a byte string if the palette values can have their own opacity.

Here is a paletted PNG with full alpha support (created with pngquant):

![fade-rgba-fs8](https://cloud.githubusercontent.com/assets/235174/14610420/2c0faed6-058e-11e6-8598-ea174b32b660.png)

You can see that ``info['transparency']`` contains a byte string, even after #1239:

``print(repr(Image.open('fade-rgba-fs8.png').info['transparency']))``

This byte string is important. Otherwise PIL is not able to keep the full alpha channel when saving PNGs.
See here how the byte string is used in the _save method:
https://github.com/python-pillow/Pillow/blob/master/PIL/PngImagePlugin.py#L720..L724

### Triggering the bug

The "fix" from #1239 removes the transparency information when the byte string only contains nulls. But this string is still valid. It means that all palette entries are full transparent.

You can create an image like that with:
``
Image.new("RGBA", (100, 100), (0, 0, 0, 0)).convert('P').save('transp.png')
``

You can see how Pillow with #1239 removes the transparency by open and saving the image with:
``
Image.open('transp.png').save('/tmp/bug.png')
``

### Solution

I suggest to revert the change. 
According to #1238, reportlab does not handle `transparency` with byte strings and #1239 tries to fix this by letting Pillow not return a byte string in this single case. But it only fixes it this specific case (all bytes null). The image above is one example where reportlab should still raise an exception. @juztin can you confirm this?

I can create a pull request with the revert together with a few new tests for the expected ``transparency`` behavior.

**Comment by olt** [comment]
The pull request reverts the change from #1239, but it also improves the transparency handling so that the simple test case from #1239 still passes.

I've extended the tests to cover the current (expected) behavior, there is a [failing test](https://github.com/python-pillow/Pillow/pull/1840/commits/0f8d66bc96dcd7ecfcdce54c1a2558d8b6ed63e5#diff-3902a6361d7f1ba3cca3ccaa3f8091f6R260) for this issue and I've updated the documentation to match the actual implementation from ``_save`` and ``_load``.

Please let me know if you have questions or if there are any further changes required. Thanks!

**Comment by radarhere** [comment]
Resolved by #1882
