### ISSUE TITLE
Pillow manipulated/saved images are not recognized by google vision APIs

### ISSUE THREAD

**Issue by mahrous78** [python-pillow/Pillow#1857]
Hey,

I am trying to build an application using google cloud vision APIs to do some OCR on images,
when manipulating  the image by pillow before sending it, all images are not recognized,
even when just open and save the image by pillow without any modifications.
 in contrary the images manipulated by opencv  are working without problems.

what is the problem and what is  information needed to trace this issue ?

**Comment by radarhere** [comment]
The most helpful thing would be to either upload a problem image, or provide a link to it, so that then others can test it and reproduce the problem.

If you're doing anything beyond `Image.open` and `Image.save`, then pasting your code would be great. You could also copy and paste the error that you're receiving, just so that others know when they are experiencing the same error as you.

**Comment by mahrous78** [comment]
I am not doing anything beyond open and save
raw image: https://storage.googleapis.com/smartcards/50.jpg
after open and save with pillow: https://storage.googleapis.com/smartcards/50_after.jpg
also I have noted the size of the images reduced too much after saving by pillow !!!!!!!!!

**Comment by radarhere** [comment]
I am able to open and save the image without any errors. Would you be able to copy and paste the error you're receiving? Also, your operating system and Python version would be useful. If you're not using the latest Pillow, then your Pillow version would also be good -
```
import PIL
PIL.PILLOW_VERSION
```

**Comment by mahrous78** [comment]
the  issue is not in saving the image but it is that google apis  able to read the raw image and can not read  processed image.
probably it is an APIs problem not pillow
PIL.PILLOW_VERSION: 3.0.0

**Comment by radarhere** [comment]
Ah, apologies for misunderstanding. Hope that you come to a solution.

**Comment by mahrous78** [comment]
Thank you for your time, I have tried bigger images and it works fine with the APIs.
