### ISSUE TITLE
Gif image size problem

### ISSUE THREAD

**Issue by Lucuz91** [python-pillow/Pillow#1858]
##I have a strange problem. 
Simply open a GIF and safely without further changes. 
The saved image size becomes much bigger , more than double than the original.

I used Python 2.7.11 and Pillow 3.2

```python
from PIL import Image
import os

image = Image.open("randomlogo.gif")
print (image.info)
print (os.stat("randomlogo.gif").st_size)

image.save("out.gif")
image2 = Image.open("out.gif")
print(image2.info)
print(os.stat("out.gif").st_size)

 {'duration': 0, 'background': 0, 'transparency': 255, 'version': 'GIF89a'}
29069

{'duration': 0, 'background': 0, 'transparency': 213, 'version': 'GIF89a'}
66438

**Comment by radarhere** [comment]
Have a look at #617

**Comment by radarhere** [comment]
Since you've reacted positively to the presence of the other issue, are you happy for this issue to be closed as a duplicate?
