### ISSUE TITLE
Manylinux wheel recipe

### ISSUE THREAD

**Issue by matthew-brett** [python-pillow/Pillow#1859]
I've been working on making a recipe for building [manylinux](https://www.python.org/dev/peps/pep-0513/) wheels for Pillow.

As y'all may have seen, Manylinux is a specification and a matching docker image that allows us to build binary wheels for Linux that we expect to run on almost any Linux system (see the spec above).

As of pip version 8.1, pip will install wheels with the `manylinux1` tag.  There are manylinux wheels for numpy, scipy and cython already uploaded to pypi.

I made a recipe for building manylinux wheels for Pillow - here : https://github.com/matthew-brett/manylinux-builds/blob/master/build_pillows.sh

Does that recipe look right?  It passes all tests on a simple test run I did for Python 2.7 and Pillow 3.2.

I just uploaded the built wheels to a testing server at https://nipy.bic.berkeley.edu/manylinux

Y'all can test with:

```
# Get latest pip
python -m pip install --upgrade pip
pip install -f https://nipy.bic.berkeley.edu/manylinux pillow
```

**Comment by radarhere** [comment]
Curious, how did you arrive at that list of Pillow versions? It skips a few, and I'm just wondering why.

**Comment by matthew-brett** [comment]
No very serious reason - I was just trying to replicate the versions for the wheels already built and used for travis-ci Ubuntu 12.04 installs over at http://travis-wheels.scikit-image.org/  .  It would be easy to add all the versions available on pypi.

**Comment by matthew-brett** [comment]
I put up logs of running the tests on all the built wheels as installed onto a Debian sid machine.

Test script: http://nipy.bic.berkeley.edu/manylinux/tests/test_pillow.py
Logs:

http://nipy.bic.berkeley.edu/manylinux/tests/27_pillow.log
http://nipy.bic.berkeley.edu/manylinux/tests/34_pillow.log
http://nipy.bic.berkeley.edu/manylinux/tests/35_pillow.log

**Comment by AbdealiJK** [comment]
I was wondering if this is planned to be implemented soon ? Or if an ETA could be provided ?

**Comment by matthew-brett** [comment]
We have a recipe up as a pull-request here : https://github.com/python-pillow/pillow-wheels/pull/36

That repo does build good 64-bit wheels, but there are some test errors for 32-bit wheels.

Honestly, if it were me, I would upload the built 64-bit wheels for 2.6.0, and meanwhile get the 32-bit test failures sorted out.  It would really help to have Pillow wheels available - it's pretty hard to build right from source.

**Comment by AbdealiJK** [comment]
I agree. Also, 32bit systems are becoming hard to find, so it'd be a smaller set who don't benefit from the wheel (yet). 

Also, correct me if I'm wrong here ... The build at [140092012#L1289](https://travis-ci.org/python-pillow/pillow-wheels/jobs/140092012#L1289) shows that the test fails because 1 floating point number is different than expected at the 17th decimal digit. Could this be because of inaccuracies by the 32bit ?

The table at https://en.wikipedia.org/wiki/Floating_point#Internal_representation says that double precision floating point numbers (floats with 8 byte) have a typical "Number of decimal digits" as 15.9. So, if an internal 32bit C library tried processing it, it may truncate and handle it differently.

Maybe that test needs to be modified for 32bit systems because they have less accuracy ?

**Comment by hugovk** [comment]
Pillow 3.3.0 is due out on 1st July and I agree it'd be good to include those 64-bit wheels which build.

If the 32-bit wheels aren't fixable in time, how about temporarily allowing those to fail (using [`allow_failures` in .travis.yml](https://docs.travis-ci.com/user/customizing-the-build/#Rows-that-are-Allowed-to-Fail)) or removing them so we can merge the PR, and send a later one with working 32-bit wheels?

**Comment by matthew-brett** [comment]
Would you consider merging with the 32-bit failures - given these are new
failures exposed by the new builds?   ​

**Comment by wiredfool** [comment]
Yeah, I don't think that the 32 bit failures are actual bugs, they're just overprecise tests. They should be fixed by backing off the precision when comparing floats, though that might be a pain because they're embedded in tuples and we're comparing the tuples for equality.

**Comment by AbdealiJK** [comment]
I've created the PR https://github.com/python-pillow/Pillow/pull/1990 to reduce the precision of the tuples by rounding it down to 10 digits.

**Comment by hugovk** [comment]
The python-pillow/wheels PR is now merged. Thanks!

**Comment by hugovk** [comment]
I just noticed that if you still have old pip (e.g. Travis CI with container-based infrastructure has Python 2.7.9 and pip 6.0.7) then `pip install pillow` results in a slow build from source.

For example:
pip 6.0.7: 13.43s https://travis-ci.org/hugovk/test/jobs/166222684#L136
pip 8.1.2: 2.03s https://travis-ci.org/hugovk/test/jobs/166223245#L147

(The non-container-based Travis comes with Python 2.7.12 and pip 8.1.2 and takes 1.83s https://travis-ci.org/hugovk/test/jobs/166222125#L119.)

So it's probably good practice to include `pip install -U pip` at the start of all Travis CI runs.
