### ISSUE TITLE
Mmap is partially tested?

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1873]
https://coveralls.io/builds/5952533/source?filename=PIL%2FImageFile.py#L158

There are two mmap implementations, one of them is core, one is python. (I think). It doesn't appear that the core version is tested, at least on linux. 
- Is this dead code?
- Can it be tested, and if not, can it be deleted?

Looking at map.c: https://coveralls.io/builds/5952533/source?filename=map.c  It appears that we're only mapping a buffer, not a file.

**Comment by radarhere** [comment]
This looks like it is now tested - https://codecov.io/gh/python-pillow/Pillow/src/4407cb65079a7d1150277e3b9a144996f56357c9/src/PIL/ImageFile.py#L175
