### ISSUE TITLE
ImageTk

### ISSUE THREAD

**Issue by Pymann** [python-pillow/Pillow#1874]
I used the command ImageTk.PhotoImage(...) to create a simple tkinter compatible picture object

To Receive a tkinter compatible PhotoImage

He spits out an error, saying: "RuntimeError: Too early to create image"

Python 3.3.5 and Pilow 3.1.0

**Solution:** It is possible to create a tkinter photo object in a tkinter class, Only.

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
from PIL import Image, ImageFont, ImageDraw, ImageTk
from tkinter import Tk, Canvas, NW

template_2 = Image.open("Template_Being_Wappen.gif")

print(template_2.format, template_2.size, template_2.mode)

tk_photo = ImageTk.PhotoImage(template_2)


```

**Comment by radarhere** [comment]
Hi. It is Tkinter, and not Pillow, that directly generates the error. You must start Tk before attempting to communicate with it.

If you add the line `root = Tk()` before `tk_photo = ImageTk.PhotoImage(template_2)`, the error will disappear.

**Comment by Pymann** [comment]
Yeah i realized that, it is also possible to create the object in a class,
I wrote that.

2016-05-02 9:58 GMT+02:00 Andrew Murray <notifications@github.com>:
