### ISSUE TITLE
Documentation tutorial roll image not working as described

### ISSUE THREAD

**Issue by StephenHesperus** [python-pillow/Pillow#1876]
I'm following the tutorial on http://pillow.readthedocs.io/en/3.2.x/handbook/tutorial.html#rolling-an-image.
According to the description, function `roll(image, delta)` should roll the image sideways by distance of `delta`. 
But when I use the function in my script, the result image is not what it should be.
#### The code from the tutorial:
```python
def roll(image, delta):
    "Roll an image sideways"

    xsize, ysize = image.size

    delta = delta % xsize
    if delta == 0: return image

    part1 = image.crop((0, 0, delta, ysize))
    part2 = image.crop((delta, 0, xsize, ysize))
    image.paste(part2, (0, 0, xsize-delta, ysize))
    image.paste(part1, (xsize-delta, 0, xsize, ysize))

    return image
```

#### Test image: call function `roll(image, delta)` with `delta = image.size[0] // 3`

original | ![poeny1](https://cloud.githubusercontent.com/assets/4600585/14947067/8fd47880-105f-11e6-995e-4743a0ad2865.jpg)
----------|----------------
from the tutorial | ![poeny1 sideways not ok](https://cloud.githubusercontent.com/assets/4600585/14947087/b065e80e-105f-11e6-9b5e-e27a9d4675ed.jpg)

After I read the reference section, I figured out that `image.crop` is a lazy operation, to really make the crop happen, a call to `cropped_region.load()` is needed.

#### This is the __modified__ version of `roll()` function:

```python
def roll(image, delta):
    "Roll an image sideways"

    xsize, ysize = image.size

    delta = delta % xsize
    if delta == 0: return image

    part1 = image.crop((0, 0, delta, ysize))
    part2 = image.crop((delta, 0, xsize, ysize))
    part1.load()
    part2.load()
    image.paste(part2, (0, 0, xsize-delta, ysize))
    image.paste(part1, (xsize-delta, 0, xsize, ysize))

    return image
```

#### Test image: call function `roll(image, delta)` with `delta = image.size[0] // 3`

original | ![poeny1](https://cloud.githubusercontent.com/assets/4600585/14947067/8fd47880-105f-11e6-995e-4743a0ad2865.jpg)
----------|-------
modified `roll()` function | ![poeny1 sideways](https://cloud.githubusercontent.com/assets/4600585/14947130/7c41416c-1060-11e6-86de-126f2a5aedc2.jpg)

I'm using _Python_ 3.5 in a virtualenv created by virtualenvwrapper. _Pillow_ is the latest version: 3.2.x.

**Comment by radarhere** [comment]
Thanks for finding that. I've created a PR to updated the documentation.
