### ISSUE TITLE
Image auto rotate / auto orient

### ISSUE THREAD

**Issue by Starefossen** [python-pillow/Pillow#1884]
Does Pillow have support for ImageMagick's [`-auto-orient`](http://www.imagemagick.org/script/command-line-options.php#auto-orient) option?

**Comment by wiredfool** [comment]
No, it doesn't.

**Comment by Starefossen** [comment]
Thank you for the answer. Would support for that feature be merged if I made a pull request?

**Comment by wiredfool** [comment]
It depends. The feature sounds useful, but the interface for option flags on opening is somewhat undeveloped.
