### ISSUE TITLE
[patch] test_extended_information assumes existence of the icc profiles

### ISSUE THREAD

**Issue by doko42** [python-pillow/Pillow#1887]
test_extended_information assumes existence of the icc profiles, and should be guarded if these files don't exist (some Linux distros don't ship these for license reasons).

--- pillow-3.2.0.orig/Tests/test_imagecms.py
+++ pillow-3.2.0/Tests/test_imagecms.py
@@ -256,6 +256,7 @@ class TestImageCms(PillowTestCase):
                          ImageCms.getProfileDescription(p2))
 
     def test_extended_information(self):
+        self.skip_missing()
         o = ImageCms.getOpenProfile(SRGB)
         p = o.profile

**Comment by wiredfool** [comment]
If you've got a broken install of lcms, I'd expect broken tests.

**Comment by doko42** [comment]
wrong, nothing is broken. it's the icc profiles in pillow which we can't ship. And the other tests in test_imagecms.py already honor this.

**Comment by wiredfool** [comment]
So what exactly aren't you shipping?

**Comment by wiredfool** [comment]
(and your patch is garbled. it interacts badly with markdown)

**Comment by wiredfool** [comment]
Ah, ok, I see it now.
