### ISSUE TITLE
Maybe not an issue but a need for support

### ISSUE THREAD

**Issue by ytrezq** [python-pillow/Pillow#1895]
Hello, gif similarly to png with itxt or ztxt can contains arbitrary plain text metadata *(comment extension)*.

However, looking at the source code and the documentation of Pillow, I wasn’t able to find any relevant function for reading or writing them.

**Comment by radarhere** [comment]
Hi. This does look like a feature request, that Pillow add support for the comment extension to the GIF format. Which sounds like a reasonable idea.

Quick question, what is 'exim'?

**Comment by radarhere** [comment]
Okay, I've created a PR to add support for the GIF comment extension.

**Comment by ytrezq** [comment]
> Hi. This does look like a feature request, that Pillow add support for the comment extension to the GIF format. Which sounds like a reasonable idea.

I don’t know, maybe Pillow already support it.

**Comment by radarhere** [comment]
No, Pillow does not currently support GIF comments. I've created a pull request to add the functionality. All things going well, it will be a part of the 3.3.0 release on July 1.
