### ISSUE TITLE
ImageTk int overflow error

### ISSUE THREAD

**Issue by vlachoudis** [python-pillow/Pillow#1902]
I am running on a 32bit Fedora-23 virtual machine via virtualbox, version 3.0.0-4
When I try to convert an image to tkimage I get an overflow error
since the tk.interpaddr() returns a 64bit address which cannot be converted to int.

The same code in 64bit Fedora-23 save version works ok.

```
File "/usr/local/flair/lib/ZoomImage.py", line 162, in zoomImage
    self.tkimage = ImageTk.PhotoImage(self.photo)
  File "/usr/lib/python2.7/site-packages/PIL/ImageTk.py", line 115, in __init__
    self.paste(image)
  File "/usr/lib/python2.7/site-packages/PIL/ImageTk.py", line 182, in paste
    _imagingtk.tkinit(tk.interpaddr(), 1)
OverflowError: Python int too large to convert to C long
```

```
>>> from Tkinter import *
>>> tk=Tk()
>>> tk.interpaddr()
2161299816L
```

**Comment by wiredfool** [comment]
It's not actually a 64 bit address, but it is in the upper 2gb of a 32 bit address. Which is too big to fit into a Py_ssize_t on 32 bit, which is limited to 2^31. 

The value is actually a PyInt_FromLong, from _tkinter.c:
```
static PyObject *
Tkapp_InterpAddr(PyObject *self, PyObject *args)
{

    if (!PyArg_ParseTuple(args, ":interpaddr"))
        return NULL;

    return PyInt_FromLong((long)Tkapp_Interp(self));
}
```

Which is interpreted as a an int->Py_ssize_t in _imagingtk.c 
```
static PyObject*
_tkinit(PyObject* self, PyObject* args)
{
    Tcl_Interp* interp;

    Py_ssize_t arg;
    int is_interp;
    if (!PyArg_ParseTuple(args, "ni", &arg, &is_interp))
        return NULL;

    if (is_interp)
        interp = (Tcl_Interp*) arg;
    else {
        TkappObject* app;
	/* Do it the hard way.  This will break if the TkappObject
	   layout changes */
        app = (TkappObject*) arg;
        interp = app->interp;
    }
```

Given the evidence here, I don't think that it's actually possible to reliably (in all cases, with all corners of 32/64 signed/unsigned silliness) pass a pointer through as an interpreted int. It can be passed as a PyInt, and then it needs to be interpreted as something like:


```
    void *arg;
    PyObject *int_obj;
    if (!PyArg_ParseTuple(args, "Oi", &arg, &is_interp))
        return NULL;

    if (PyInt_Check(O)) {
        if (sizeof(arg) == 4) {

**Comment by wiredfool** [comment]
from the debian bug report: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=847812

https://github.com/matplotlib/matplotlib/commit/a91559b82cf23ee407cd57580653015fc7dc35f0

**Comment by vlachoudis** [comment]
I had a similar issue in one program of mine, and I solve it by changing the ParseTuple as
```
	unsigned long interpaddr;
...
	if (!PyArg_ParseTuple(args, "Osk", &geometry, &winname, &interpaddr)) return -1;
        Tcl_Interp *interp = (Tcl_Interp*)interpaddr;
```
and it works nicely in both 32bit and 64bit environments.

**Comment by wiredfool** [comment]
I don't think that is valid in a 64 bit environment because a pointer doesn't fit into an unsigned long.
