### ISSUE TITLE
Stroke color for font

### ISSUE THREAD

**Issue by controversial** [python-pillow/Pillow#1907]
Is there a way in `ImageDraw` or `ImageFont` to draw text with a border color? If not, there probably should be. [It can be faked](http://stackoverflow.com/a/8050556/4414003) but it'd be nice if this functionality was built-in.

**Comment by radarhere** [comment]
The only solutions that I'm aware of are the workaround already suggested, or finding a font file that has a shadow built in.

**Comment by HinTak** [comment]
https://github.com/rougier/freetype-py have 4 examples on this.

**Comment by radarhere** [comment]
Closing as a duplicate of #2209. I know this issue was first, but that one has more detail.

**Comment by radarhere** [comment]
I've created PR #3978 to resolve this.
