### ISSUE TITLE
ImageDraw Ellipse: Asymmetric Circle for all even diameters

### ISSUE THREAD

**Issue by cgramesp** [python-pillow/Pillow#1913]
### What did you do?

used ImageDraw Ellipse with two equal diameters to draw a circle.
### What did you expect to happen?

round, symmetric circle
### What actually happened?

round and symmetric circles for all odd diameters but unsymmetric artifacts for all even diameters
### What versions of Pillow and Python are you using?

Pillow 3.2.0, Python 3
<img width="211" alt="bildschirmfoto 2016-05-16 um 13 56 04" src="https://cloud.githubusercontent.com/assets/15788821/15290691/83679b88-1b7a-11e6-937b-286f313ab739.png">

``` python
from PIL import Image, ImageDraw

img = Image.new('1', (8, 8), "white")
draw = ImageDraw.Draw(img)

draw.ellipse((1, 1, 6, 6), fill = 'black', outline ='black')

img.show()
```

**Comment by aclark4life** [comment]
@python-pillow/pillow-team FYI Christoph Gramespacher has inquired via email about the status of this issue … maybe someone feels like fixing this for 3.4.0 :smile:

**Comment by radarhere** [comment]
@aclark4life you can e-mail Christoph if you like?

**Comment by aclark4life** [comment]
@radarhere Great, will do thanks

**Comment by aclark4life** [comment]
<img width="1680" alt="screenshot 2018-07-02 10 13 58" src="https://user-images.githubusercontent.com/72164/42169052-b02c7128-7de0-11e8-9d68-e8db54c89a81.png">
