### ISSUE TITLE
ValueError: jpeg is required unless explicitly disabled using --disable-jpeg, aborting  - however,

### ISSUE THREAD

**Issue by JonasT** [python-pillow/Pillow#1922]
### What did you do?
I ran the following commands in a docker file (basically think of all those commands executed on a freshly installed headless Fedora 23 system), with the aim of installing pillow among other things:
```
FROM fedora:23

RUN dnf upgrade -y
RUN dnf install -y pypy-devel wget
RUN cd /tmp && wget https://bootstrap.pypa.io/get-pip.py
RUN cd /tmp && pypy ./get-pip.py
RUN dnf install -y cairo-devel freetype-devel libpng-devel
RUN dnf install -y libffi-devel git
RUN dnf install -y redhat-rpm-config gcc gcc-c++ gcc-gfortran libffi
RUN /usr/lib64/pypy-4.0.1/bin/pip install --upgrade pip
RUN /usr/lib64/pypy-4.0.1/bin/pip install cairocffi
RUN git clone https://bitbucket.org/pypy/numpy.git /numpy/
RUN cd /numpy/ && git checkout pypy-4.0.1
RUN cd /numpy; pypy setup.py install
RUN dnf install -y postgresql-libs postgresql-devel
RUN /usr/lib64/pypy-4.0.1/bin/pip install psycopg2cffi-compat
RUN dnf install -y openjpeg-devel libtiff-devel turbojpeg-devel zlib-devel lcms2-devel
RUN /usr/lib64/pypy-4.0.1/bin/pip install pillow
```

### What did you expect to happen?
pillow is either successfully installed, or at least doesn't complain about missing libjpeg files

### What actually happened?
pillow complains about missing libjpeg files

### What versions of Pillow and Python are you using?
Pillow-3.2.0 and pypy-4.0.1 (for Python 2.x)

See commands above for reproduction.

**Comment by wiredfool** [comment]
1) There is a tested script for the dependencies for Fedora 23, in `depends/fedora_23.sh`. It works with Pillow 3.2.0. 
2) Have you checked that you're installing the libraries and headers?  This error means that Pillow can't find the dependencies, and it's looking for the header file and the library in many of the usual locations.

**Comment by wiredfool** [comment]
Specifically, the package you're looking for is `libjpeg-turbo-devel`, not `turbojpeg-devel`.

**Comment by JonasT** [comment]
Oops that was indeed my problem, thanks :-)
