### ISSUE TITLE
Use run-time loading of Tcl / Tk?

### ISSUE THREAD

**Issue by matthew-brett** [python-pillow/Pillow#1928]
Over at Matplotlib, we switched to detecting Tcl / Tk at run time, using the symbols loaded by Python Tkinter - https://github.com/matplotlib/matplotlib/pull/6442 .

This has the advantage that Matplotlib is always using the same Tcl / Tk lib as Python, avoiding run-time crashes when Matplotlib is compiled with a different version of Tcl / Tk (package upgrades, building wheels on another system).   We also abstracted out the very small part of the Tcl / Tk headers that we needed to compile, meaning that we can compile against Tcl / Tk without an installation of Tcl / Tk at build time.

For matplotlib, we tested this as working on Linux, OSX and Windows (see comments on that PR).  Do you think this would also work for Pillow?  At a superficial look, you're using very similar parts of Tcl / Tk...

**Comment by wiredfool** [comment]
That sounds good.  Does it add a dependency on anything else, like cffi?

**Comment by matthew-brett** [comment]
No new dependencies, it's all C code, using standard libraries on Unix and Windows.

**Comment by matthew-brett** [comment]
I'm happy to give it a shot with a PR if you think you'd use it.

**Comment by wiredfool** [comment]
I think it's worth a shot. It's a pain point with some platforms, and if we get the same results without the funkiness of finding the right libraries, that's a win for me.

**Comment by matthew-brett** [comment]
PR at https://github.com/python-pillow/Pillow/pull/1932
