### ISSUE TITLE
Enable fuzzing

### ISSUE THREAD

**Issue by orf** [python-pillow/Pillow#1929]
Hey, after the ImageTragick vulnerabilities I became interested in running `afl-fuzz` on Pillow to potentially find any issues with the decoders in `libImaging`.

I ran into a little trouble though, as far as I can tell the Pillow decoders are pretty tied to the Python runtime. `afl-fuzz` works by executing a given program with a file path, which the program should then attempt to process, but I couldn't manage to get a simple C program that could do this without using Python objects.

So my question is this: Is it possible to use the library from a simple C program to just run a given file through an encoder without the overhead and complexity of creating cPython objects? Really I just want to be able to construct an `Imaging` and `ImagingCodecState` with the correct values as fast as possible and pass them to the correct decode functions, but as far as I can see the `Imaging` object is irreversibly tied to Python.

If some sample code could be given or some hints as to the correct way to do this then I can run Pillow on a powerful fuzzing box I own for a while. Looking at the code I think it is the perfect code for`afl-fuzz` and I would bet some money on it finding some issues somewhere in the codebase. I think this would be a great idea for the project, and might be worth some refactoring if it is not possible currently.

**Comment by wiredfool** [comment]
I've tried using afl, (and afl-clang) through the python stack, but was never able to get it to run fast enough to be useful. I've got an execv version, and this one:
```
#include "Python.h"

int main(int argc, char *argv[])
{
    Py_InitializeEx(0);
    PySys_SetArgvEx(argc, argv, 0);
#ifdef __AFL_HAVE_MANUAL_CONTROL
    __AFL_INIT();
#endif
    FILE *f = fopen("test.pyc", "rb");
    if(PyRun_AnyFileEx(f, "test.pyc" ,1 ) == -1) {
        printf("fail");
    }

    Py_Finalize();
    return 0;
}

/* Compile with:
   export CC=/home/erics/build/afl-2.07b/afl-gcc
   $CC `python-config --includes` -o test test.c `python-config --libs`  
   
   $CC `python-config --includes` -o test test.c /usr/local/lib/libpython2.7.a -lpthread -ldl -lutil -lm
   

*/
```

Where test.py was 
```
#!/usr/bin/env python
import sys
from PIL import Image
im = Image.open(sys.argv[1])
im.load()
exit(0)
```

There's also fuzzpy, but I didn't get far with that one either (https://bitbucket.org/ebadf/fuzzpy)

As for not using the python stack at all, that's going to be difficult. Most/all of the decoders do a bunch of setup work in python before handing off to C code. Additionally, (almost) all of the decoders rely on the python code to shovel the data to them. I don't see a way to deal with that without writing a ton of scaffolding code.

**Comment by orf** [comment]
Yeah, running it through the whole python stack like that is never going to be fast enough :(

I think it's more than possible though. If we take the simple `PyImaging_ZipDecoderNew` function:

```C
PyObject*
PyImaging_ZipDecoderNew(PyObject* self, PyObject* args)
{
    ImagingDecoderObject* decoder;

    char* mode;
    char* rawmode;
    int interlaced = 0;
    if (!PyArg_ParseTuple(args, "ss|i", &mode, &rawmode, &interlaced))
        return NULL;

    decoder = PyImaging_DecoderNew(sizeof(ZIPSTATE));
    if (decoder == NULL)
        return NULL;

    if (get_unpacker(decoder, mode, rawmode) < 0)
        return NULL;

    decoder->decode = ImagingZipDecode;

    ((ZIPSTATE*)decoder->state.context)->interlaced = interlaced;

    return (PyObject*) decoder;
}
```

The Python C api isn't that slow, it's hitting the pure python layer that absolutely destroys performance. The only python bits it needs is to parse the `mode`, `rawmode` and `interlaced` stuff. The `self` argument is never used. So perhaps we could strip the function down to something like this:

```C
PyObject*
PyImaging_ZipDecoderNewFuzz()
{
    ImagingDecoderObject* decoder;
    // Set these as default values?
    char* mode;
    char* rawmode;
    int interlaced = 0;
    decoder = PyImaging_DecoderNew(sizeof(ZIPSTATE));
    get_unpacker(decoder, mode, rawmode)
    decoder->decode = ImagingZipDecode;
    ((ZIPSTATE*)decoder->state.context)->interlaced = interlaced;
    return (PyObject*) decoder;
}
```
But then I'm unsure of how to take the `PyObject` we've got and feed it some data from a file.

**Comment by wiredfool** [comment]
Ok, so one way that you'd get to the zip decoder is to load a .png file. 

Mode and rawmode are set in python from reading the PNG chunks. https://github.com/python-pillow/Pillow/blob/a0602fb68c62ccf3825b7cd074751153772cef70/PIL/PngImagePlugin.py#L326 .That python code also grabs the position of the data chunk in the file and the size of the image.

Mode and the image size are used to make the c-layer image object, allocate the memory, and initialize the size fields. Mode, rawmode, and the size of the image are also used to get the data out of the decoder into the image memory using the shuffle function. If those values aren't correct, then the shuffle function will overwrite memory. 
 
To get data into the decoder, you'd repeatedly call decoder->decode with the image object, the state, and a hunk of data, (The decoder in this case is ImagingZipDecode from ZipDecode.c). This is essentially the code from the inner loop of ImageFile.load.

**Comment by orf** [comment]
Hold on a second:

> Mode and rawmode are set in python from reading the PNG chunks. 
> Mode, rawmode, and the size of the image are also used to get the data out of the decoder into the image memory using the shuffle function. If those values aren't correct, then the shuffle function will overwrite memory. 

What do you mean by 'overwrite memory'? Isn't that a big issue if all the inputs are user controlled?

I think I might be able to get something working with minimal overhead.

**Comment by wiredfool** [comment]
They've got to be consistent between the image as allocated and the shuffler/unpacker. If you get the wrong shuffler/unpacker for the image mode combination, then you've got the chance of writing a 32bpp image into space for an 8bpp.
