### ISSUE TITLE
IOError: decoder libtiff not available

### ISSUE THREAD

**Issue by arag0rn2k3** [python-pillow/Pillow#1930]
can't convert tif files on ubuntu 14.04 :( libtiff is installed, pillow and ubuntu are up-todate:

ii  libtiff5:amd64                      4.0.3-7ubuntu0.4                     amd64        Tag Image File Format (TIFF) library
ii  libtiff5-dev:amd64                  4.0.3-7ubuntu0.4                     amd64        Tag Image File Format library (TIFF), development files
ii  libtiffxx5:amd64                    4.0.3-7ubuntu0.4                     amd64        Tag Image File Format (TIFF) library -- C++ interface

sudo pip install pillow --no-cache-dir
Requirement already up-to-date: pillow in /usr/local/lib/python3.4/dist-packages

Any ideas?

**Comment by homm** [comment]
if you got `Requirement already up-to-date` then the package is not rebuild. Try the following:

```
$ pip install pillow --upgrade --force-reinstall --no-cache-dir
```

**Comment by arag0rn2k3** [comment]
Hi Alexander, I have reinstalled pillow - but the problem isn't fixed :/  >> IOError: decoder libtiff not available

~$ sudo pip install pillow --upgrade --force-reinstall --no-cache-dir
[sudo] password for dse:
Collecting pillow
  Downloading Pillow-3.2.0.zip (10.5MB)
    100% |████████████████████████████████| 10.5MB 10.7MB/s
Installing collected packages: pillow
  Found existing installation: Pillow 3.2.0
    Uninstalling Pillow-3.2.0:
      Successfully uninstalled Pillow-3.2.0
  Running setup.py install for pillow ... done
Successfully installed pillow-3.2.0

**Comment by arag0rn2k3** [comment]
PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 3.2.0
    platform     linux 3.4.3 (default, Oct 14 2015, 20:28:29)
                 [GCC 4.8.4]
    --------------------------------------------------------------------
    *** TKINTER support not available
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    --- LIBTIFF support available
    *** FREETYPE2 support not available
    *** LITTLECMS2 support not available
    *** WEBP support not available
    *** WEBPMUX support not available
    --------------------------------------------------------------------

**Comment by arag0rn2k3** [comment]
IOError: decoder libtiff not available

Traceback (most recent call last):
  PL/Python function "save_objectdata_tif50", line 9, in <module>
    pil_img = Image.open(infile).convert('RGB')
  PL/Python function "save_objectdata_tif50", line 841, in convert
  PL/Python function "save_objectdata_tif50", line 1014, in _load_libtiff
  PL/Python function "save_objectdata_tif50", line 415, in _getdecoder
PL/Python-Funktion „save_objectdata_tif50“
SQL-Anweisung „SELECT save_objectdata_tif50(v_id::int,$2)“

**Comment by wiredfool** [comment]
Does it work outside of postgres?   Have you restarted postgres after re-installing pillow?

**Comment by arag0rn2k3** [comment]
yes I did server and postgres restarts. I will test it outside of postgres asap (I'm not the python guru)

**Comment by arag0rn2k3** [comment]
some problem outside postgres :(
:~$ vi test.py
_______________________________
from PIL import Image
import glob, os

size = 128, 128

for infile in glob.glob("*.tif"):
    file, ext = os.path.splitext(infile)
    im = Image.open(infile)
    im.thumbnail(size, Image.ANTIALIAS)
    im.save(file + ".thumbnail", "JPEG")
_________________________________

:~$ ls
FaxMail_688917292.tif openresty-1.9.7.4  openresty-1.9.7.4.tar.gz  test  test2  test.py  www
_______________________________
:~$ python test.py
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    im.thumbnail(size, Image.ANTIALIAS)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1786, in thumbnail
    im = self.resize(size, resample)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1526, in resize
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/TiffImagePlugin.py", line 1015, in _load_libtiff
    self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 416, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder libtiff not available

**Comment by wiredfool** [comment]
Your setup summary is from python 3.4: 

```
PIL SETUP SUMMARY
--------------------------------------------------------------------
version Pillow 3.2.0
platform linux 3.4.3 (default, Oct 14 2015, 20:28:29)
```

But your traceback here is python 2.7:
```
File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 416, in _getdecoder
```

**Comment by arag0rn2k3** [comment]
problem solved...

sudo easy_install-2.7 pip

sudo pip install pillow --upgrade --force-reinstall

PIL SETUP SUMMARY
    --------------------------------------------------------------------
    version      Pillow 3.2.0
    platform     linux2 2.7.6 (default, Jun 22 2015, 17:58:13)
                 [GCC 4.8.2]
    --------------------------------------------------------------------
    *** TKINTER support not available
    (Tcl/Tk 8.6 libraries needed)
    --- JPEG support available
    *** OPENJPEG (JPEG2000) support not available
    --- ZLIB (PNG/ZIP) support available
    --- LIBTIFF support available
    *** FREETYPE2 support not available
    *** LITTLECMS2 support not available
    *** WEBP support not available
    *** WEBPMUX support not available
    --------------------------------------------------------------------
    To add a missing option, make sure you have the required
    library, and set the corresponding ROOT variable in the
    setup.py script.

    To check the build, run the selftest.py script.

**Comment by flowl** [comment]
I have this problem right now with Pillow 5.0 and the "solution" does not help.
What do I actually have to do? I don't have a `selftest.py`, I am using Docker with `python:3.6.8-slim-jessie`.

**Comment by radarhere** [comment]
If https://pillow.readthedocs.io/en/stable/installation.html#building-on-linux does not help, please consider creating a new issue with the command that you're running and the output.

**Comment by flowl** [comment]
For me this is a bug in `pip`, it doesn't install the most current version even if you freshly install it and specify in `requirements.txt`. Apt, npm, composer all behave better than pip.
