### ISSUE TITLE
Turn off coveralls posts

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#1943]
@hugovk Can we turn off the coveralls spam in PRs?  It's pretty useless in most cases.

**Comment by hugovk** [comment]
Yes, but I don't have permission for this repo. Here's the settings on my own repo. 

![image](https://cloud.githubusercontent.com/assets/1324225/15895687/4716a4f8-2d95-11e6-9c7d-8103f0c6567b.png)

Let's turn LEAVE COMMENTS? off but keep USE STATUS API? turned on.

https://coveralls.io/github/python-pillow/Pillow

**Comment by wiredfool** [comment]
Ah, ok. Apparently I had permission, if I looked hard enough.
