### ISSUE TITLE
Fails to find zlib in alpine

### ISSUE THREAD

**Issue by mmoya** [python-pillow/Pillow#1944]
### What did you do?

    $ docker run -it --rm alpine:3.3 /bin/sh
    # apk --no-cache add py-pip gcc musl-dev libjpeg-turbo-dev python-dev zlib-dev
    # pip install Pillow==3.2.0

you can run everything in one row with:

    $ docker run -it --rm alpine:3.3 /bin/sh -c 'apk --no-cache add py-pip gcc musl-dev libjpeg-turbo-dev python-dev zlib-dev && pip install Pillow==3.2.0'

it also happens with alpine:3.4 image.

### What did you expect to happen?

Pillow to be installed.

### What actually happened?

Pillow failed to install because it can't find _zlib_. The following files are present in the filesystem:

    # apk -q info -L zlib zlib-dev
    lib/libz.so.1.2.8
    lib/libz.so.1

    lib/libz.a
    lib/libz.so
    usr/lib/pkgconfig/zlib.pc
    usr/include/zlib.h
    usr/include/zconf.h

### What versions of Pillow and Python are you using?

[Python 2.7.11][1], Pillow 3.2.0.

 [1]: http://pkgs.alpinelinux.org/package/v3.3/main/x86_64/python

**Comment by wiredfool** [comment]
Should be fixed on master as of pr #1937

**Comment by wiredfool** [comment]
Closing this -- if master doesn't fix it, feel free to post again

**Comment by mmoya** [comment]
@wiredfool I couldn't find any release schedule in Pillow website. Is there any expected release date including #1937 other than _where it's ready_?

Thanks.

**Comment by wiredfool** [comment]
Aiming for today, 2016-07-01

**Comment by radarhere** [comment]
@mmoya for the release schedule more generally, see https://github.com/python-pillow/Pillow/blob/master/RELEASING.md
