### ISSUE TITLE
Can't save JPEG2000 to a BytesIO object

### ISSUE THREAD

**Issue by CSNE** [python-pillow/Pillow#1945]
### What did you do?
I tried to save a JPEG2000 image into a BytesIO object. 

### What did you expect to happen?
It should have saved the image file into the BytesIO object.

### What actually happened?
The script fails("python.exe has stopped working"). 

### What versions of Pillow and Python are you using?
Python 3.3.4 (32-bit) and Pillow 3.2.0
I also tried using Python 3.5.1, but the script still fails.

```
from PIL import Image
from io import BytesIO

#Any image will reproduce the bug.
img=Image.open(r"some-image.png")

print("Saving ordinary JPEG to a BytesIO object. This works fine.")
bio=BytesIO()
img.save(bio,"JPEG")

print("Saving JPEG2000 to a file. This also works fine.")
img.save(r"some-other-image.jpf","JPEG2000")

print("Saving JPEG2000 to a BytesIO object. This fails.")
bio2=BytesIO()
img.save(bio2,"JPEG2000")
```

**Comment by radarhere** [comment]
When testing, I managed to trigger -

    Traceback (most recent call last):
      File "PIL/ImageFile.py", line 460, in _save
        fh = fp.fileno()
    io.UnsupportedOperation: fileno

Hopefully, this is the same as the error that you're experiencing. I've created a PR to fix this. If you're able to try that PR and see if it fixes your problem, that would be helpful.

**Comment by wiredfool** [comment]
Is this Windows?  And is it a crash or a exception?

**Comment by CSNE** [comment]
I'm using Windows 8.1.
When I run the script, no traceback is printed in the console, but a Windows dialog pops up saying "python.exe has stopped working.". So I guess it's a crash.
![capture12](https://cloud.githubusercontent.com/assets/14859382/15984436/950c4038-3005-11e6-89a5-0afb9e71a3f4.PNG)

**Comment by wiredfool** [comment]
That's a crash, and it's odd. Our roundtrip tests for J2k use bytesio, so that should be the most well tested configuration. On the other hand, we don't have that configuration in ci, so it's possible something is wrong.

**Comment by CSNE** [comment]
Update: Just tried running the script on two of my friend's computers(one Windows 7 w/ Python 3.5 and one Windows 8.1 w/ Python 3.5). They don't crash.
Perhaps it was just my machine.

**Comment by wiredfool** [comment]
It does seem that way. You could have some corruption in the pillow or the python install which might be fixed by reinstalling.

**Comment by CSNE** [comment]
Reinstalling doesn't help, might be something wrong in the system.
Anyways, thanks!
