### ISSUE TITLE
Different file size when calling save

### ISSUE THREAD

**Issue by Selol** [python-pillow/Pillow#1953]
### What did you do?
use PIL to check and save image
### What did you expect to happen?
should save the original image when calling im.save (at least the new file size and original file size should be the same)
### What actually happened?
they are different
### What versions of Pillow and Python are you using?
Pillow==2.9.0, Python 2.7.6
Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```python
bogon:Downloads licong$ ll 1.png 
-rw-r--r--@ 1 licong  staff  5678 12  4  2015 1.png
bogon:Downloads licong$ python
Python 2.7.6 (v2.7.6:3a1db0d2747e, Nov 10 2013, 00:42:54) 
[GCC 4.2.1 (Apple Inc. build 5666) (dot 3)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> im = Image.open('./1.png')
>>> im.save('./1_NEW.png')
>>> ^D
bogon:Downloads licong$ ll ./1_NEW.png
-rw-r--r--  1 licong  staff  5652  6 14 16:10 ./1_NEW.png
```

**Comment by wiredfool** [comment]
That's going to happen. There are multiple (correct) encodings of PNG images that are designed to facilitate the zlib compression.
