### ISSUE TITLE
Expose registered file extensions

### ISSUE THREAD

**Issue by lggomez** [python-pillow/Pillow#1955]
Is there any way of getting the file extensions supported by the library?
Usually it's a good practice to expose the supported types or extensions, specially in libraries that handle files, so the consumer can have a way to obtain or check its target extensions based on the ones provided by the library

I'm not very familiar with Pillow's code but this method in Image.py should do the trick:

``` python
def registered_extensions():
    """
    Returns a dictionary containing all file extensions belonging
    to registered plugins
    """
    if not bool(EXTENSION):
        init()
    return EXTENSION
```

Anyway, it's just a suggestion so you shall take it with a grain of salt. Keep up the good work on this fork

**Comment by radarhere** [comment]
From my understanding, `preinit()` should not be necessary when immediately followed by `init()`. It's just a version of `init()` that aims to be faster by only covering the most popular formats.

**Comment by lggomez** [comment]
Indeed, after checking I see that using init() will be enough, I corrected it

Do you consider this a worthy addition? If so I can make the pull request

**Comment by radarhere** [comment]
Potentially, yes. I won't be the one to ultimately merge it, but you should certainly feel free to create a PR as a way of moving this forward.

**Comment by radarhere** [comment]
This has been done in #2343.
