### ISSUE TITLE
Reading JPEG with 2 layers failed

### ISSUE THREAD

**Issue by AbdealiJK** [python-pillow/Pillow#1960]
### What did you do?
I was trying to read the file https://commons.wikimedia.org/wiki/File:JoeSimpson2012.JPG .

I am scikit-image with Pillow as backend. This was initially raised at https://github.com/scikit-image/scikit-image/issues/2154 you can see the analysis by stefanv there. He said that the 2 layers are extracted from the JPEG by Pillow. The second layer seems to be a thumbnail of the first.

### What did you expect to happen?
Other files are read fine using skimage+Pillow, I expected this file to be read correctly too.

### What actually happened?
It seems that when `.getdata()` is called (internally in scikit-image), an `IOError` is raised.

### What versions of Pillow and Python are you using?
Pillow v3.2.0
Python v2.7.11 :: Continuum Analytics
pip v8.1.2
conda v4.0.7
Ubuntu 14.04

Here is a sample code which can reproduce the error:
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import (division, absolute_import, unicode_literals,
                        print_function)

import os
from shutil import copyfileobj

try:
    from urllib2 import urlopen
except ImportError:
    from urllib.request import urlopen

from PIL import Image

def download(url, filename, overwrite=False):
    if not os.path.exists(filename) or overwrite:
        response = urlopen(url)
        with open(filename, 'wb') as out_file:
            copyfileobj(response, out_file)

download('https://upload.wikimedia.org/wikipedia/commons/e/ea/JoeSimpson2012.JPG',
         'JoeSimpson2012.JPG')

image = Image.open('JoeSimpson2012.JPG')
image.seek(1)
image.getdata()
```

The output:
```
Traceback (most recent call last):
  File "test.py", line 28, in <module>
    image.getdata()
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/PIL/Image.py", line 1151, in getdata
    self.load()
  File "/home/ajk/miniconda/envs/py27/lib/python2.7/site-packages/PIL/ImageFile.py", line 218, in load
    "(%d bytes not processed)" % len(b))
IOError: image file is truncated (0 bytes not processed)
```

**Comment by radarhere** [comment]
If, as the error suggests, the file is indeed truncated, there here is the way to handle that. The following code should not throw an error -

```python
from PIL import Image
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
image = Image.open('JoeSimpson2012.JPG')
image.seek(1)
image.getdata()
```

**Comment by AbdealiJK** [comment]
This does indeed work.
So, is this a fault with the image ? is the image corrupted ?

**Comment by radarhere** [comment]
A fault with the image, yes. To my mind, to say that an image is truncated means that it ends prematurely.

**Comment by AbdealiJK** [comment]
Hm, alright. Closing this then :+1:
