### ISSUE TITLE
Test failures for Linux 32-bit

### ISSUE THREAD

**Issue by matthew-brett** [python-pillow/Pillow#1973]
I've built a test grid that builds Pillow 3.2.0 wheels for manylinux1, and tests them : 

* https://travis-ci.org/matthew-brett/pillow-wheels/builds/139079195
* https://github.com/matthew-brett/pillow-wheels/tree/refactor-to-multibuild

In particular, I'm testing the 32-bit builds on 32-bit docker images.  The 32-bit builds are all failing with a single test failure:

https://travis-ci.org/matthew-brett/pillow-wheels/jobs/139079199#L1113

```
======================================================================
FAIL: TestImageCms.test_extended_information
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/io/Pillow/Tests/test_imagecms.py", line 262, in test_extended_information
    self.assertEqual(p.attributes, 4294967296)
AssertionError: -4587544 != 4294967296L
```

Any ideas what might be going on?

**Comment by hugovk** [comment]
The test: https://github.com/python-pillow/Pillow/blob/master/Tests/test_imagecms.py#L263
It's new code only added in the last release: PR https://github.com/python-pillow/Pillow/pull/1756

Ping @lambdafu

**Comment by wiredfool** [comment]
That certainly looks like integer overflow to me.

**Comment by wiredfool** [comment]
It's a bug here: https://github.com/python-pillow/Pillow/blob/master/_imagingcms.c#L990

**Comment by lambdafu** [comment]
Drats.  The purpose here is to convert the 64bit number (which will be an unsigned long long in 32-bit GNU/Linux systems) to a python integer without loss.  I can research the relevant interfaces in Python, although I suspect that people who are already familiar with it can do it from the top of their hat.

**Comment by lambdafu** [comment]
We should use PyLong_FromUnsignedLongLong.

**Comment by wiredfool** [comment]
Testing the fix in #1975, I'm also getting precision errors with: p.blue_colorant, p.chromatic_adaption, p.green_primary, p.media_black_point, p.media_white_point and p.media_white_point_temperature. 

These are pretty much all small differences in the least significant digit: e.g.:

```
======================================================================
FAIL: TestImageCms.test_extended_information
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/ubuntu/Pillow/Tests/test_imagecms.py", line 290, in test_extended_information
    self.assertEqual(p.media_white_point, ((0.964202880859375, 1.0, 0.8249053955078125), (0.3457029219802284, 0.3585375327567059, 1.0)))
AssertionError: Tuples differ: ((0.964202880859375, 1.0, 0.82... != ((0.964202880859375, 1.0, 0.82...

First differing element 1:
(0.34570292198022834, 0.3585375327567059, 1.0)
(0.3457029219802284, 0.3585375327567059, 1.0)

  ((0.964202880859375, 1.0, 0.8249053955078125),
-  (0.34570292198022834, 0.3585375327567059, 1.0))
?                    -

+  (0.3457029219802284, 0.3585375327567059, 1.0))

----------------------------------------------------------------------
Ran 19 tests in 0.431s
```

**Comment by wiredfool** [comment]
I'm also getting a pretty consistent hang in test_j2k_overflow.

**Comment by matthew-brett** [comment]
Interesting - I had to disable openjpg on OSX because the tests were
hanging at `TestFileIcns.test_jp2_icon` :

https://s3.amazonaws.com/archive.travis-ci.org/jobs/139079205/log.txt
​

**Comment by wiredfool** [comment]
That's something of a known issue, and there's a pr for it, but it's kind of a big change: https://github.com/python-pillow/Pillow/pull/1934
