### ISSUE TITLE
Can't install Pillow to virtualenv

### ISSUE THREAD

**Issue by aayn** [python-pillow/Pillow#1999]
I can't seem to install Pillow on my virtualenv. `pip install Pillow` doesn't work and gives bunch of warnings and errors.

Here's the log:
[error_log.txt](https://github.com/python-pillow/Pillow/files/341974/error_log.txt)

I'm using python3.4 on Fedora 23.
I should point out that it installs fine on to my system. This issue is specific to installing it to a virtualenv.

**Comment by wiredfool** [comment]
It's not finding the compiler: `/usr/lib/rpm/redhat/redhat-hardened-cc1`.  I think that's the `redhat-rpm-config` mentioned in the install docs.

**Comment by aayn** [comment]
Oh yeah. A simple `dnf install redhat-rpm-config` fixes this. Thanks :+1:
