### ISSUE TITLE
ValueError when getting tiff tags

### ISSUE THREAD

**Issue by impact27** [python-pillow/Pillow#2006]
### What did you do?

I tried to extract metadata from a .tif file
### What did you expect to happen?

get the metadata
### What actually happened?

ValueError: too many values to unpack (expected 1)
### What versions of Pillow and Python are you using?

pillow 3.3.0
python 3.5

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
from PIL import Image
img = Image.open("myfil.tif")
dict(img.tag)
```

**Comment by wiredfool** [comment]
What's the image that causes this?

**Comment by impact27** [comment]
[img_000001856_Default_000.tif.zip](https://github.com/python-pillow/Pillow/files/343854/img_000001856_Default_000.tif.zip)

**Comment by impact27** [comment]
I figured out why it was doing it: the tag 50838 (MetaData count) has a count of 2 and TiffTags.py expect 1. (I think this is because the first 12 bytes are utf8 and the rest are utf16)

**Comment by wiredfool** [comment]
Yeah. That appears to be it.  And as far as I can tell, there's no spec for MetaDataByteCounts, but looking at the ImageJ source, (https://github.com/imagej/imagej1/blob/ce491f23ca56a342576ee13455de60bf018b1015/ij/io/TiffEncoder.java#L309) there's definitely an arbitrary number of items in that field, not a single. I think that the tiffTags entry should be changed to `   50838: ("ImageJMetaDataByteCounts", LONG, 0),`.

**Comment by impact27** [comment]
Yes but on line 553:
https://github.com/python-pillow/Pillow/blob/master/PIL/TiffImagePlugin.py#L553
if len(values) >1 and info.length ==1, it will cause a problem, wouldn't it make sense to also check that en(values) ==1? To avoid similar issues?

**Comment by cgohlke** [comment]
FWIW, [tifffile.py](http://www.lfd.uci.edu/~gohlke/code/tifffile.py.html) can parse ImageJ metadata:
```Python
>>> import tifffile
>>> tf = tifffile.TiffFile("img_000001856_Default_000.tif")
>>> print(tf.pages[0].imagej_tags.info)
{
  "Core-Focus": "",
  "Core-Shutter": "",
  "QCamera-TriggerType": "Freerun",
  "Channel": "Default",
  "Core-Initialize": "1",
  "UUID": "6e16cb7e-b556-4dd4-9c90-6a503854801a",
  "Core-Camera": "QCamera",
  "Core-TimeoutMs": "5000",
  "Core-SLM": "",
  "FrameIndex": 1856,
  "QCamera-OffsetMax": "1023",
  "ElapsedTime-ms": 944743.549987793,
  "QCamera-CameraName": "Rolera EMC2",
  "Frame": 1856,
  "Core-ChannelGroup": "",
  "PositionIndex": 0,
  "Width": 1004,
  "QCamera-ExposureMin": "0.2000",
  "WaitInterval": 500,
  "ROI": "0-0-1004-1002",
  "PositionName": null,
  "QCamera-Camera": "37718 Rolera EMC2 S/N Q37718",
  "Camera": "QCamera",
  "PixelSizeUm": 0,
  "Height": 1002,
  "QCamera-OffsetMin": "0",
  "Core-ImageProcessor": "",
  "QCamera-Cooler": "On",
  "Summary": {
    "Slices": 1,
    "InitialPositionList": null,
    "Interval_ms": 500,
    "UUID": "b3c81756-52e2-4db9-9fdd-1abc1ad29c02",
    "UserName": "LegoScope",
    "Depth": 2,
    "PixelType": "GRAY16",
    "Time": "2016-06-24 11:13:55 +0100",
    "Date": "2016-06-24",
    "z-step_um": 0,
    "MetadataVersion": 10,
    "PositionIndex": 0,
    "SlicesFirst": false,
    "ChContrastMin": [0],
    "Width": 1004,
    "PixelAspect": 1,
    "MicroManagerVersion": "1.4.18",
    "ROI": [
      0,
      0,
      1004,
      1002
    ],
    "ChNames": ["Default"],
    "IJType": 1,
    "GridRow": 0,
    "Comment": "",
    "Height": 1002,
    "GridColumn": 0,
    "Prefix": "e1105qt5b_170S2tf_6mgac2t80_0to5V_800ulhr_2",
    "PixelSize_um": 0,
    "Frames": 7200,
    "BitDepth": 14,
    "KeepShutterOpenChannels": false,
    "Source": "Micro-Manager",
    "Channels": 1,
    "ComputerName": "B62-LegoScope",
    "CustomIntervals_ms": [],
    "KeepShutterOpenSlices": false,
    "ChColors": [-1],
    "TimeFirst": false,
    "ChContrastMax": [65536],
    "Positions": 1,
    "Directory": "C:\\Users\\LegoScope\\Desktop\\Therese\\160623e1105q"
  },
  "QCamera-Exposure": "500.00",
  "Source": "QCamera",
  "SlicePosition": null,
  "QCamera-CameraID": "Serial number Q37718",
  "Exposure-ms": 500,
  "QCamera-TransposeCorrection": "0",
  "QCamera-Offset": "0",
  "Core-AutoShutter": "1",
  "QCamera-CCDTemperatureMin": "-50",
  "QCamera-TransposeXY": "0",
  "Binning": "1",
  "NextFrame": null,
  "Core-XYStage": "",
  "AxisPositions": null,
  "PixelType": "GRAY16",
  "Time": "2016-06-24 11:29:26 +0100",
  "QCamera-EMGainMin": "0",
  "QCamera-Binning": "1",
  "ImageNumber": "1856",
  "QCamera-Easy EM Enabled": "Yes",
  "QCamera-EMGainMax": "4095",
  "QCamera-CCDTemperatureMax": "0",
  "QCamera-TransposeMirrorY": "0",
  "Core-AutoFocus": "",
  "YPositionUm": null,
  "QCamera-CCDTemperature": "-50",
  "XPositionUm": null,
  "QCamera-Description": "QCam 2.0.13",
  "QCamera-ReadoutTime": "10.0 MHz",
  "QCamera-TransposeMirrorX": "0",
  "BitDepth": 14,
  "Slice": 0,
  "QCamera-Easy EM Gain": "0",
  "QCamera-PixelType": "14bit",
  "FileName": "img_000001856_Default_000.tif",
  "Core-Galvo": "",
  "Position": "Default",
  "QCamera-ExposureMax": "1073741.8750",
  "QCamera-Name": "QCamera",
  "CameraChannelIndex": 0,
  "ChannelIndex": 0,
  "SliceIndex": 0,
  "ZPositionUm": null
}
```

**Comment by wiredfool** [comment]
There's more issues in the metadata handling generally related to the difference between fields in the file being internally correct and fields being correct with respect to the spec, and what that means for the rest of the code. Specifically, there are some metadata fields where the spec is important, and some where it's advisory.

**Comment by impact27** [comment]
Yes but the code will produce an error anyway if len(values) >1 and info.length ==1. So why not try to avoid that? If the file can be open even with a few mistakes in the header why not do it?
