### ISSUE TITLE
Loading pillow into an Anaconda Navigator environment

### ISSUE THREAD

**Issue by Dipugee** [python-pillow/Pillow#2025]
### What did you do?

1. Created an environment called “ImagProc”
2. Installed packages such as numpy, pillow and  others in that
3. Using Jupyter I created a notebook called "imageprocessing ”
4. Then I created a code cell to import and check the contents of pillow

### What did you expect to happen?

Get a listing of pillow's contents to verify that it  is loaded in the environment

### What actually happened?

ImportError: No module named 'pillow'

### What versions of Pillow and Python are you using?
pillow version 3.3.0 with Python 3.5 under Anaconda's Navigator running on Mac OS 10.11.5
Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```python
import pillow
help (pillow)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e7e06395ca9f> in <module>()
----> 1 import pillow
      2 help (pillow)

 ```
'

Comment:
BTW, “pillow” (version 3.3.0) does  show up with a  check in the box when I look at the   “ImagProc” environment page in Navigator under Installed packages. I did the same thing for both numpy and Scipy and was able to get the contents listing.

**Comment by radarhere** [comment]
Hi. While I haven't looked into your problem in detail, I imagine this advice will help -

Pillow is imported using `import PIL` not `import pillow`.

Individual classes, such as `Image` are usually imported using `from PIL import Image`.

**Comment by Dipugee** [comment]
Thanks Andrew. I will continue to dig deeper.

Best.

Dipu


Dipankar Ganguly
Consultant: Strategy/Technology/Commercialization
Bothell, WA
Cell: 408-203-8814
email: dipugee@gmail.com
http://www.linkedin.com/in/dipugee
