### ISSUE TITLE
Issues with Pillow on Navigator

### ISSUE THREAD

**Issue by Dipugee** [python-pillow/Pillow#2029]
### What did you do?
 I come from a Matlab background and used their Image and Signal Processing toolboxes a lot. I am now trying to learn to do similar things with  Python.   This is what I have done so far…

I am using Anaconda’s Navigator on my MacBook Pro running OS 10.11.5 with the Python version set to 3.5. 

1. Created an environment called “ImagProc”
2. Installed packages such as numpy, pillow and  others in that environment
3. Using Jupyter I created a notebook called "imageprocessing ”
4. Then I created a code cell to import and check the contents of pillow

### What actually happened?

```
import pillow
help (pillow)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e7e06395ca9f> in <module>()

import pillow
help (pillow)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e7e06395ca9f> in <module>()
----> 1 import pillow
      2 help (pillow)

ImportError: No module named 'pillow'
```

### What versions of Pillow and Python are you using?

Pillow: 3.3.0. Python: 3.5 under Mac OS 10.11.5

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
import pillow
help (pillow)
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-2-e7e06395ca9f> in <module>()
----> 1 import pillow
      2 help (pillow)

ImportError: No module named 'pillow'

code goes here
```

BTW, “pillow” (version 3.3.0) does  show up with a  check in the box when I look at the   “ImagProc” environment page in Navigator under Installed packages. I did the same thing for both numpy and Scipy and was able to get the contents listing.

Dipu

**Comment by homm** [comment]
So, what did you expect to happen? :)

You can start learning from [tutorial](https://pillow.readthedocs.io/en/3.3.x/handbook/tutorial.html).

**Comment by Dipugee** [comment]
I expected to see a listing of Pillow's contents  to ensure that Pillow was installed; similar to listings I got for numpy.

**Comment by homm** [comment]
Just look at the the tutorial.

**Comment by Dipugee** [comment]
Ok. Thanks.
