### ISSUE TITLE
"Edit on GitHub" link doesn't lead to master

### ISSUE THREAD

**Issue by techtonik** [python-pillow/Pillow#2030]
### What did you do?
1. Open https://pillow.readthedocs.io/
2. Click Edit on GitHub

### What did you expect to happen?
Expected to edit doc sources in master
https://github.com/python-pillow/Pillow/blob/master/docs/index.rst

### What actually happened?
https://github.com/python-pillow/Pillow/blob/3.3.x/docs/index.rst
https://github.com/python-pillow/Pillow/pull/2026#issuecomment-232921417

**Comment by wiredfool** [comment]
The public docs are against the last release, as that covers exactly what we have in the release.  All PRs need to go to master, we may back port/cherry pick if necessary. 

However, RTD doesn't know what our workflow is.
