### ISSUE TITLE
Could truncated file exception be more descriptive?

### ISSUE THREAD

**Issue by AlexHill** [python-pillow/Pillow#2038]
I don't know much about image file formats. When an image file is found to be truncated, do we know what proportion of the image we successfully decoded, or just that there should have been more?

If it's the former, could that information be included in the exception? I ask because I process images from a lot of sources, and a couple of those sources produce damaged JPEGs that nonetheless display fine. I guess all the data is there, but they're improperly terminated.

Other truncated actually have significant missing image data. It would be good to be able to differentiate between the two by knowing how much of the image wasn't processed.

Currently you get `OSError: image file is truncated (<n> bytes not processed)`, but that seems to be the size of the leftover chunk that had been read but not yet decoded, rather than anything to do with the size of the file/image.

**Comment by wiredfool** [comment]
You may be interested in the ImageFile.LOAD_TRUNCATED_IMAGES flag. It may do what you want.
