### ISSUE TITLE
FYI I disabled third party application access for python-pillow organization

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#2040]
@python-pillow/pillow-team Please let me know if you experience any adverse effects from this ``python-pillow`` organization change I just made (hopefully not!):

<img width="790" alt="screenshot 2016-07-27 16 01 10" src="https://cloud.githubusercontent.com/assets/72164/17190341/84136f72-5413-11e6-84c4-eb07d546330f.png">

**Comment by hugovk** [comment]
Looks like that's disabled all our CI checks, the latest one doesn't have a green tick or red cross:

![image](https://cloud.githubusercontent.com/assets/1324225/17202991/5f72f06a-54a5-11e6-955b-ef20f0ef723c.png)

Compare https://github.com/python-pillow/Pillow/pull/2035 and https://github.com/python-pillow/Pillow/pull/2041, the former has AppVeyor, Travis and Coveralls checks:

![image](https://cloud.githubusercontent.com/assets/1324225/17203018/9478c8de-54a5-11e6-9a8b-4b6a25a9757e.png)

The new one doesn't:

![image](https://cloud.githubusercontent.com/assets/1324225/17203038/b326a0ee-54a5-11e6-9953-6f1aeb98857b.png)

**Comment by hugovk** [comment]
I've requested access for Travis CI to python-pillow. It said the owners should get an email about it.

I can't see how to request access for AppVeyor or Coveralls.

**Comment by wiredfool** [comment]
I've approved travis.

**Comment by wiredfool** [comment]
And I've restarted travis and appveyor for the last pr, That might reconnect them. If not, IDK.

**Comment by aclark4life** [comment]
Thanks folks, I'll keep an eye on it too. Hopefully the approvals will smooth things out, and I feel better knowing how the third party access mechanism works.

**Comment by wiredfool** [comment]
I've tried dropping and readding github permissions for Appveyor, but it seems to be doing it on my account even though I'm logged in through the python-pillow org.

**Comment by aclark4life** [comment]
Travis, IRC & RTD are services whereas AppVeyor are "just" webhooks… I'll look into it further. We also need to fix RTD & IRC presumably.

![screenshot 2016-07-28 05 37 16](https://cloud.githubusercontent.com/assets/72164/17208200/8676959c-5485-11e6-9e35-0cc2fd652b99.png)

**Comment by wiredfool** [comment]
I think appveyor requires service permission to report back the results.

**Comment by aclark4life** [comment]
OK I think I clicked through and enabled AppVeyor, though I have no idea how to verify AppVeyor is working (other than using #2045, which doesn't seem to show me anything AppVeyor related.)

![screenshot 2016-07-28 14 27 54](https://cloud.githubusercontent.com/assets/72164/17224642/d296ea22-54cf-11e6-82a7-bb1706373d3b.png)

**Comment by wiredfool** [comment]
I got about 10 notifications of it, don't know if it's my mail or github...

**Comment by hugovk** [comment]
We have Travis CI but are still missing AppVeyor and Coveralls on the most recent PR: https://github.com/python-pillow/Pillow/pull/2047

**Comment by aclark4life** [comment]
OK I'll work on it today and fix, else revert to less security.

**Comment by aclark4life** [comment]
Some progress here, I think:

![screenshot 2016-08-01 16 50 11](https://cloud.githubusercontent.com/assets/72164/17308462/21795fea-5808-11e6-9602-28a70245cbcf.png)

**Comment by aclark4life** [comment]
Not sure what's going on with Coveralls. Seems to be doing something:

![screenshot 2016-08-01 17 00 56](https://cloud.githubusercontent.com/assets/72164/17308765/96971352-5809-11e6-8203-e2bddff280d5.png)

**Comment by wiredfool** [comment]
So the webhooks are working, but reporting back looks broken.

**Comment by aclark4life** [comment]
Right, OK I give up. I reverted, please let me know if this does not fix everything. According to this document, it should: https://help.github.com/articles/about-third-party-application-restrictions/.

﻿
![screenshot 2016-08-03 07 04 42](https://cloud.githubusercontent.com/assets/72164/17363481/b01086c0-5948-11e6-9b25-3eec2335ddf9.png)

**Comment by hugovk** [comment]
Travis CI, AppVeyor and Coveralls are back in action: https://github.com/python-pillow/Pillow/pull/2050

Thanks!

**Comment by aclark4life** [comment]
Great, thanks! Sorry for the exercise in futility.
