### ISSUE TITLE
outdated documentation

### ISSUE THREAD

**Issue by PramodBisht** [python-pillow/Pillow#2051]
In PILLOW 2.2.2, I found few part of code have outdated documentation, I understand it don't have any functional impact on pillow, I would like to update it. Can I send PR for that?

Thanks

**Comment by radarhere** [comment]
You're welcome to send PRs to update documentation. It's an important part of the library.

I would encourage you to create the PR against the master branch, rather than updating the 2.2.x branch, which was moved on from several years ago.
