### ISSUE TITLE
JPEG2000 files do not return pixel access object on calling the load() function

### ISSUE THREAD

**Issue by Ghost---Shadow** [python-pillow/Pillow#2059]
### What did you do?
I tried to load pixels of a j2k file but got None instead of the pixel access object.
Same for other jpeg 2000 file extensions like jpk. 
Since `j2k.show()` shows the image perfectly, the problem is only in the load function. 

### What did you expect to happen?
I expected it to return the pixel access object like it does for other file types.
### What actually happened?
the load() function returned None
### What versions of Pillow and Python are you using?
Python 3.4.3 (v3.4.3:9b73f1c3e601, Feb 24 2015, 22:43:06) [MSC v.1600 32 bit (Intel)] on win32
Pillow 3.3.0
```
j2k = Image.open('./MyImage.j2k')
pix = j2k.load()
assert pix is not None #Assertion fails
```

**Comment by wiredfool** [comment]
Right, we're missing a return.
