### ISSUE TITLE
Coveralls doesn't show the difference

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#2060]
Coveralls used to show the difference. For example:

```
coverage/coveralls — Coverage increased (+0.02%) to 77.967%
```

Now it shows only current value:

```
coverage/coveralls — First build on master at 78.15%
```

**Comment by hugovk** [comment]
That was happening before but they fixed something: https://github.com/lemurheavy/coveralls-public/issues/610. Want to notify them?

**Comment by homm** [comment]
I also suppose this can be related to latest changes in https://github.com/python-pillow/Pillow/issues/2040

**Comment by hugovk** [comment]
Perhaps, although the first build after that was restored looked fine: "Coverage remained the same" https://github.com/python-pillow/Pillow/pull/2050

**Comment by aclark4life** [comment]
Ahhh! I love when I have a chance to use my `Infrastructure` label :smile:

**Comment by hugovk** [comment]
Seems to be working now, see for example this recent PR: https://github.com/python-pillow/Pillow/pull/2333

The text is truncated, but it says:

>              — Coverage increased (+0.005%) to 79.455%
        
So let's close this.
