### ISSUE TITLE
Match webp default quality to cwebp

### ISSUE THREAD

**Issue by pdknsk** [python-pillow/Pillow#2062]
The default quality in `PIL` is set to `80`, apparently inspired by the last sentence in `cwebp` output.

```
$ cwebp
Usage:

   cwebp [options] -q quality input.png -o output.webp

where quality is between 0 (poor) to 100 (very good).
Typical value is around 80.
```

The [actual default quality](https://chromium.googlesource.com/webm/libwebp/+/master/src/webp/encode.h#169) is `75`.

```
// Note that the default values are lossless=0 and quality=75.
```

**Comment by radarhere** [comment]
I started to put together the PR for this, and then discovered that, unsurprisingly, lowering the quality means that the tests need to account for greater differences.

That's not a problem, except that `test_write_rgba` has a different threshold for older versions of WebP. Is anyone willing and able to test an old version of WebP with this new quality setting to see what the threshold ought to be?

**Comment by pdknsk** [comment]
FYI: ​the latest matching _old_ version is [0.3.0](https://chromium.googlesource.com/webm/libwebp/+/0.3.0/src/webp/decode.h#23).

**Comment by aclark4life** [comment]
@pdknsk Are you willing and able to test an old version of WebP with this new quality setting to see what the threshold ought to be?

**Comment by wiredfool** [comment]
Enhancement?

**Comment by aclark4life** [comment]
@wiredfool **Shrug** How about ``Bug``? :smile:

**Comment by wiredfool** [comment]
How about Won't Fix? 

1) It hasn't been shown to cause problems. 
2) It's a minor change in output, probably unnoticed by anyone unless they're really looking for it, except that it breaks the tests
3) If they really want quality=75, it's just an option away.
