### ISSUE TITLE
jpeg sampling factor is wrong

### ISSUE THREAD

**Issue by pdknsk** [python-pillow/Pillow#2063]
`2x2` is `4:2:0`, [not `4:1:1`](https://github.com/python-pillow/Pillow/blob/master/libImaging/JpegEncode.c#L197). This is wrong in many places, most importantly [here](https://github.com/python-pillow/Pillow/blob/master/PIL/JpegImagePlugin.py#L615).

Documented [here](https://github.com/libjpeg-turbo/libjpeg-turbo/blob/master/turbojpeg.h#L106-L107), and elsewhere.

May I also suggest to add the `NxN` representation to the docs, which is easier to comprehend.

**Comment by homm** [comment]
I don't understand how `h_samp_factor` and `v_samp_factor` maps to subsampling numbers and which exactly subsampling value is used in [this place](https://github.com/python-pillow/Pillow/blob/master/libImaging/JpegEncode.c#L197).

According to this picture, `4:2:0` looks more useful than `4:1:1` for me:

<img width="1008" alt="screen shot 2016-08-15 at 13 40 01" src="https://cloud.githubusercontent.com/assets/128982/17663657/6aedb4c8-62ee-11e6-8266-61173482531c.png">

**Comment by aclark4life** [comment]
@pdknsk Any response to @homm's comments? Do you still consider this a bug?

**Comment by pdknsk** [comment]
Yes, it's still a bug. You could simply fix it by replacing `4:1:1` with `4:2:0` throughout.
> I don't understand how h_samp_factor and v_samp_factor maps to subsampling numbers

It's explained by the _libjpeg-turbo_ maintainer [here](https://github.com/libjpeg-turbo/libjpeg-turbo/issues/86#issuecomment-226995244).

> and which exactly subsampling value is used in [this place](https://github.com/python-pillow/Pillow/blob/master/libImaging/JpegEncode.c#L197).

It's `4:2:0`.
