### ISSUE TITLE
unintuitive save properties

### ISSUE THREAD

**Issue by pdknsk** [python-pillow/Pillow#2064]
> **progressive**
> If present, indicates that this image should be stored as a progressive JPEG file.

It is not completely obvious that ```progressive = False``` evaluates to it being set. I guess it's difficult to change this whilst keeping backwards compatibility. (I doubt someone passes ```progressive = False``` with the intention to enable it.)

**Comment by pdknsk** [comment]
Sorry for re-opening, but I should've made clearer that I used ```progressive``` only as an example. Other parameters are also affected. In particular `optimize` for both **JPEG** and **PNG**, and `lossless` for **WebP**.

**Comment by pdknsk** [comment]
(Oh, I can't actually re-open.)

**Comment by radarhere** [comment]
Looking at the code, that shouldn't be the case for lossless for WebP. Are you able to provide code to demonstrate that?

**Comment by pdknsk** [comment]
You're right, it's only a documentation bug.
> **lossless**
> If present, instructs the WEBP writer to use lossless compression.

**Comment by wiredfool** [comment]
This should be addressed now.
