### ISSUE TITLE
Multiline text is not centered correctly

### ISSUE THREAD

**Issue by deepakazad** [python-pillow/Pillow#2067]
I tried to write a center align text in an image. However, it is not centered. 

I use Python 3.5 and Pillow 3.3.0

Code to reproduce 

``` python
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw 
img = Image.open("sample.jpg")
draw = ImageDraw.Draw(img)
font = ImageFont.load_default().font

width,height= draw.textsize("Sample Text", font=font)
#draw.text((100-width/2, 100),"Sample Text",(255,255,255),font=font)
draw.multiline_text((100, 100),"Sample Text",(255,255,255),font=font, align='center')
img.save('sample-out.jpg')
```

`draw.multiline_text()` does not center align the text. If I calculate the width as shown and then call `draw.text()` (the commented line), the text is aligned perfectly.

**Comment by deepakazad** [comment]
The problematic code is in ImageDraw.multiline_text

elif align == "center":
                left += (max_width - widths[idx]) / 2.0

should be changed to

elif align == "center":
                left += (- widths[idx]) / 2.0

I don't think max_width is relevant for center alignment.

**Comment by radarhere** [comment]
Hi. If you look at -

http://pillow.readthedocs.io/en/3.3.x/reference/ImageDraw.html?highlight=multiline_text#PIL.ImageDraw.PIL.ImageDraw.Draw.multiline_text

you will see that the `xy` argument is the top left corner of the text.

'center' for `multiline_text` is meant to center the text within the box of all of the text that is written - this is why the maximum width is used, and why `xy` is the top left corner. `xy` is not the center if the 'center' alignment is used, it keeps being the top left.

So your code is writing the text 'Sample Text', using (100,100) as the top left co-ordinates. It does not appear to be centered because there is no wider line for it to be centered relative to.

**Comment by deepakazad** [comment]
Oops, fair point. Also, thanks for the fast response.

Though I would argue that the `multiline_text` API would be simpler to use if `x` has different meaning depending on the `align` parameter. If you are trying to center the text you would logically think where is the box centered rather than where does the box start, hence `x` should be the center of the box in which text is written. Similarly, if you are trying to right align the text `x` would be the right of the box. 

Since `x` is left of the box, I had to compute the text width myself and align it properly. Hence defeating the purpose of the API a little bit.

Having said that, the API does work as described in the docs. Feel free to close this if you think best.

**Comment by quantumpotato** [comment]
@deepakazad how did you calculate the size of the text? I tried using 

```
 tw, th = d.textsize(rank, font=f2)
  d.text(((W-tw)/2,(H-th)/2), rank, fill=b)
   ```
   
   but it only draws a very small font even though my f2 font is bigger when I draw normally.

**Comment by quantumpotato** [comment]
Oh, I got the size working but how did you calculate multiline? It feels like I need to tell the textsize function not to exceed the image boundary

**Comment by radarhere** [comment]
> Oh, I got the size working

I presume you realised you need to pass the font to `d.text` as well - https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text

> how did you calculate multiline? It feels like I need to tell the textsize function not to exceed the image boundary

You might be interested in #5669, where there is an example of reducing font size until multiline text fits within a box, or #6201, where they talk about starting a new line once text reaches the end of a line.

**Comment by nulano** [comment]
> Oh, I got the size working but how did you calculate multiline.

I'm not entirely sure what you are asking, but you might be interested in knowing that there is a new way to center text using [anchors](https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html#text-anchors), which should be both more convenient and more accurate, e.g.:

```python
d.text((W/2, H/2), text, fill="red", font=font, anchor="mm")
```
