### ISSUE TITLE
Multithreading with pixel data

### ISSUE THREAD

**Issue by sindney** [python-pillow/Pillow#2080]
PixelAccess is not multithreadable, so i tried getdata() and modify the pixel data.
But there's no api for setdata(), and fromarrray, frombuffer requires extra handling, 
Is it possible to add a setdata() api
or make PixelAccess multithreadable.
Thanks

**Comment by wiredfool** [comment]
Look at Image.putdata

**Comment by sindney** [comment]
LOL, i should have read the entir document, thx alot !
