### ISSUE TITLE
No way to read Parallax tag from stereo MPO files

### ISSUE THREAD

**Issue by DarkStarSword** [python-pillow/Pillow#2081]
Stereo MPO files (such as those produced with the Fujifilm Finepix W3 camera) store the parallax value in a tag in the EXIF information of the _second_ image in the MPO file, but it appears that Pillow can only read the EXIF information from the first image at present.

The tag can be manually read via exiftool as follows:

``` bash
$ exiftool DSCF3195.MPO -mpimage2 -b > DSCF3195-r.jpg
$ exiftool  DSCF3195-r.jpg -Parallax
Parallax                        : 5.625
```

I have several sample MPO files available:
http://valen.darkstarsword.net/photos/stereo/misc/originals/

I would like to make use of this tag in my Stereo Cropping Tool ( https://github.com/DarkStarSword/StereoCropper ) to start with the correct parallax value.

**Comment by radarhere** [comment]
@wiredfool why did you label this as TIFF? MPO is JPEG based, yes?

**Comment by DustinJSilk** [comment]
I can't seem to get the image size of the second frame. Did you ever figure this out?

I'm trying to split mpo files but can't crop the second frame without knowing its size. And doing a seek then save just saves the second frame at the size of the first frame

**Comment by DarkStarSword** [comment]
I haven't looked into it further... it only represents a relatively small enhancement for my tool since my tool is designed to allow the user to very rapidly adjust the parallax and crop on a stereo photo, so not having the parallax pre-set only equates to maybe a second or two of inconvenience per photo... Still, it would be nice to have.

**Comment by DarkStarSword** [comment]
BTW - this is unrelated to Pillow, but I have a shell script that can convert .mpo files into various other formats (including .jps) and correctly accounts for the parallax tag:
https://github.com/DarkStarSword/3d-fixes/blob/master/photo-gallery/orig2all.sh

**Comment by radarhere** [comment]
Are there any images that could be included as part of the test suite, under Pillow's license?

**Comment by radarhere** [comment]
I have created PR #3576 to resolve this.

A problem here is that the parallax data is stored in the MakerNote tag - this is specific to the manufacturer. So in the PR, I have added reading of the Fujifilm format that you provide here, and the Nintendo format that is already in our test suite. If there are any other formats that you would like supported, please let us know.

**Comment by DarkStarSword** [comment]
> Are there any images that could be included as part of the test suite, under Pillow's license?
Feel free to take your pick from any of these - they're all my own work and I'm more than happy for them to be used under Pillow's license:
http://valen.darkstarsword.net/photos/stereo/misc/originals/

**Comment by radarhere** [comment]
Thanks very much! I've added one of the images to the PR.

**Comment by hugovk** [comment]
Thanks for the image!

However, it's nearly 10 MB, and our current source zip (including most test images) is 16 MB.

Would it be possible to create one which is, say, less than a megabyte?

If not, shall we leave it out of this repo (and the source zip) and put it in https://github.com/python-pillow/pillow-depends/tree/master/test_images instead, and pull it in just for testing?

**Comment by radarhere** [comment]
Just for the record - while a natural image is obviously better, another option would be to switch back to original 117kb file from my original commits in the PR. I copied one of the existing test images and then manually hexedited in the parallax data.

**Comment by radarhere** [comment]
For the sake of clarity I'll note here that with the impending release of Pillow 6.0.0, you will now be able to read parallax data like so -

```python
# Nintendo
im = Image.open("Tests/images/sugarshack.mpo")
exif = im.getexif()
exif.get_ifd(0x927c)[0x1101]["Parallax"]  # -44.798187255859375

# Fujifilm
im = Image.open("Tests/images/fujifilm.mpo")
im.seek(1)
exif = im.getexif()
exif.get_ifd(0x927c)[0xb211]  # -3.125
```

`0x927c` being the MakerNote tag - https://www.exiv2.org/makernote.html
