### ISSUE TITLE
3.3.1 Release for 2016-08-18

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2082]
I've cherry picked the 2 patches for regressions in 3.3.0 that had the 3.3.1 release milestone and done the version bump in the 3.3.x branch. 

It's dated for tomorrow, I'm planning on tagging and doing binaries then, unless objections.

@cgohlke @homm?

**Comment by cgohlke** [comment]
OK

**Comment by wiredfool** [comment]
Tagged.    (the date in the title should have been 2016-08-18.. off by one errors are hard.)

**Comment by cgohlke** [comment]
Here you go <http://www.lfd.uci.edu/~gohlke/download/Pillow-3.3.1.win-dist.zip>

**Comment by wiredfool** [comment]
Thanks @cgohlke

**Comment by radarhere** [comment]
Just noting that I've now closed the milestone for this.
