### ISSUE TITLE
3.3.1 Broken on Windows

### ISSUE THREAD

**Issue by corylutton** [python-pillow/Pillow#2085]
### What did you do?
I just attempted to update Report lab that has Pillow as a requirement.  It failed so I tried to update just Pillow by itself.

### What did you expect to happen?
Expected update success

### What actually happened?
    >pip install Pillow -U
    ........
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

    ----------------------------------------
    Rolling back uninstall of pillow

### What versions of Pillow and Python are you using?
Pillow 3.3.1, Python 3.4.4 (32bit) on Windows 7

**Comment by wiredfool** [comment]
Binaries aren't upload yet, they will be shortly

**Comment by corylutton** [comment]
Oh, makes sense, I'm sure that will resolve it.  Looks like just a timing issue on my end.

**Comment by wiredfool** [comment]
binaries are up now.
