### ISSUE TITLE
Create an animated GIF from scratch

### ISSUE THREAD

**Issue by wodim** [python-pillow/Pillow#2098]
Can Pillow create animated GIFs from scratch at all? Like, having a series of 10 images of the same size, can I turn them into frames and save them as an animated GIF?

**Comment by olanguyenvan** [comment]
Yes you can, check this package https://gist.github.com/jonschoning/7216290 .

**Comment by wodim** [comment]
No offence, but you are practically writing the GIF by hand byte by byte. I could do that as well, but I'd rather have an abstraction over the format of GIF files, that's why I'm using an imaging library.

**Comment by radarhere** [comment]
Hi. There isn't a simple way to do that at the moment. I'd be interesting in putting together a PR, if anyone can think of a good API to use.

To solve your immediate problem, I have copied and modified GifImagePlugin's save method to put together an example script for creating an animated GIF. This could be better, but hopefully you will find it helpful.

	from PIL import Image, ImageFile, ImageChops
	from PIL.GifImagePlugin import _imaging_gif, RAWMODE, _convert_mode, getheader, getdata, get_interlace, _get_local_header

	def save_sequence(ims, filename):
		im = ims[0]
		fp = open(filename, 'wb')
	
		if hasattr(im, 'encoderinfo'):
			im.encoderinfo.update(im.info)
		if _imaging_gif:
			# call external driver
			try:
				_imaging_gif.save(im, fp, filename)
				return
			except IOError:
				pass  # write uncompressed file

		if im.mode in RAWMODE:
			im_out = im.copy()
		else:
			im_out = _convert_mode(im, True)

		# header
		if hasattr(im, 'encoderinfo'):
			try:
				palette = im.encoderinfo["palette"]
			except KeyError:
				palette = None
				im.encoderinfo["optimize"] = im.encoderinfo.get("optimize", True)
		else:
			palette = None
			im.encoderinfo = {}

		save_all = True
		if save_all:
			previous = None

			first_frame = None
			for im_frame in ims:
				im_frame = _convert_mode(im_frame)

				# To specify duration, add the time in milliseconds to getdata(),
				# e.g. getdata(im_frame, duration=1000)
				if not previous:
					# global header
					first_frame = getheader(im_frame, palette, im.encoderinfo)[0]
					first_frame += getdata(im_frame, (0, 0), **im.encoderinfo)
				else:
					if first_frame:
						for s in first_frame:
							fp.write(s)
						first_frame = None

					# delta frame
					delta = ImageChops.subtract_modulo(im_frame, previous.copy())
					bbox = delta.getbbox()

					if bbox:
						# compress difference
						for s in getdata(im_frame.crop(bbox),
										 bbox[:2], **im.encoderinfo):
							fp.write(s)
					else:
						# FIXME: what should we do in this case?
						pass
				previous = im_frame
			if first_frame:
				save_all = False
		if not save_all:
			header = getheader(im_out, palette, im.encoderinfo)[0]
			for s in header:
				fp.write(s)

			flags = 0

			if get_interlace(im):
				flags = flags | 64

			# local image header
			_get_local_header(fp, im, (0, 0), flags)

			im_out.encoderconfig = (8, get_interlace(im))
			ImageFile._save(im_out, fp, [("gif", (0, 0)+im.size, 0,
										  RAWMODE[im_out.mode])])

			fp.write(b"\0")  # end of image data

		fp.write(b";")  # end of file

		if hasattr(fp, "flush"):
			fp.flush()

	ims = [Image.new('RGB', (100, 100), hex) for hex in ['#f00', '#0f0','#0ff','#ff0','#000','#fff','#f0f']]
	save_sequence(ims, 'test.gif')

**Comment by wodim** [comment]
You could take a look at Wand, which is another binding to ImageMagick. Here's an example of what creating a GIF looks like there (although the implementation is buggy so I've had to abandon that library):

https://github.com/dahlia/wand/issues/300#issue-166542295

I'd be very thankful if you could make that PR, I'm very interested in this feature.

**Comment by radarhere** [comment]
Okay, I've created a PR. Please provide any feedback you might have.
