### ISSUE TITLE
Can't recognize font in the pyspark context

### ISSUE THREAD

**Issue by twmht** [python-pillow/Pillow#2099]
Hi,

I am using pyspark with PIL

but whenever I load the font with 

```python
 font = ImageFont.truetype(font_path, 50)
```

It always throws the exception 
```python
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 239, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFont.py", line 128, in __init__
    self.font = core.getfont(font, size, index, encoding)
IOError: unknown file format
```

My PIL version is 1.1.7, and os version is ubuntu 14.04.

pyspark runs in JVM, I am not sure if this is the problem.

the font can be loaded when running without pyspark, so the format is fine.

any advice?

thank you.

**Comment by hugovk** [comment]
What do you have in `font_path`?

**Comment by twmht** [comment]
Hi @hugovk , `font_path` is something like `path/to/myfont.ttf`

**Comment by hugovk** [comment]
And what font are you trying to load? Does it work with other fonts?

**Comment by twmht** [comment]
oops... this is due to some of bugs in my scripts. It's not related to pyspark and PIL.
