### ISSUE TITLE
Is there a way to reverse a GIF?

### ISSUE THREAD

**Issue by rj93** [python-pillow/Pillow#2104]
I am looking for a way to be able to reverse the sequence of an animated GIF and save it as a new `.gif` file. Is there a way to do this using this library?

**Comment by radarhere** [comment]
Hi. There is not a simple way at the moment. However, I'm currently working on a similar feature for #2098.

How would you feel about this as a suggested API?

    from PIL import Image
    im = Image.open('original.gif')
    frames = im.get_frames()
    frames.reverse()
    frames[0].save('reversed.gif', save_all=True, append_images=frames[1:])

**Comment by rj93** [comment]
I'd be greatful if you could implement that while you're working on the other feature

**Comment by radarhere** [comment]
I've realised that `get_frames` doesn't strictly need to be added, as the code is simple enough without it. So if you wanted to, you could test the changes in #2098 with the following code, just to be sure that the changes from that PR will solve your situation.

    from PIL import Image, ImageSequence
    im = Image.open('original.gif')
    frames = [frame.copy() for frame in ImageSequence.Iterator(im)]
    frames.reverse()
    frames[0].save('reversed.gif', save_all=True, append_images=frames[1:])

**Comment by hugovk** [comment]
Closing; PR https://github.com/python-pillow/Pillow/pull/2103 is merged.
