### ISSUE TITLE
Image.Open() doesn't open png file of 16 bit depth correctly 

### ISSUE THREAD

**Issue by zxpatric** [python-pillow/Pillow#2107]
### What did you do?

open two png files and show them in matplotlib. One is 8 bit depth png and the other is 16 bit 

### What did you expect to happen?

show the mario and another image correctly 

small-super-mario.png is available at https://drive.google.com/open?id=0B185R70hbZHkTzZoY1puUi14LUU

LeftSnap20.png is available at https://drive.google.com/open?id=0B185R70hbZHkcjQ5LXgtWTI1STQ

### What actually happened?

mario is showing correctly but not the second one LeftSnap20.png

### What versions of Pillow and Python are you using?

Python 3.4.0 (v3.4.0:04f714765c13, Mar 16 2014, 19:25:23) [MSC v.1600 64 bit (AM
D64)] on win32
Pillow-3.3.1

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```python
import matplotlib.pyplot as plt
from PIL import Image
outDir=r'./'
img1=Image.open(outDir+'small-super-mario.png')
img2=Image.open(outDir+'LeftSnap20.png')
plt.imshow(img1)
plt.show()
plt.imshow(img2)
plt.show()
```

small-super-mario.png is available at https://drive.google.com/open?id=0B185R70hbZHkTzZoY1puUi14LUU

LeftSnap20.png is available at https://drive.google.com/open?id=0B185R70hbZHkcjQ5LXgtWTI1STQ

**Comment by wiredfool** [comment]
Pillow does not currently support multi channel images with > 8 bits per channel.

**Comment by zxpatric** [comment]
LeftSnap20.png  is not a multi channel image. It is a single channel png with 16 bits. Also not supported?

available at https://drive.google.com/open?id=0B185R70hbZHkcjQ5LXgtWTI1STQ

**Comment by homm** [comment]
Is this the problem related to `Image.open()` or rather `matplotlib`? Could you show the example without `matplotlib` or change the topic. As I see, Pillow at least does open and save this file.

**Comment by wiredfool** [comment]
```
from PIL import Image
im = Image.open('LeftSnap20.png')
im.load()
print im.size
print im.mode
print im.getextrema()
```
yields:
```(3376, 2704)
I
(0, 65535)
```

So it appears to work without matplotlib. Using im.show() on it gives about what I'd expect from the default conversion of 16bit I -> 8 bit L mode, namely clipping anywhere the value is over 255.

**Comment by zxpatric** [comment]
hmm. seems that matplotlib imshow has some trouble to show PIL.PngImagePlugin.PngImageFile object of 16 bit depth. Possibly oversees the img.mode.

I did the raw data manipulation and it shows fine. Not sure if there is a way to get the needed ndarray dtype out of img.mode directly though.

nda=np.ndarray((img.size[1],img.size[0]),buffer=bs,dtype=int) 
plt.imshow(nda, cmap='Greys_r')
plt.show()

**Comment by wiredfool** [comment]
I'm not entirely sure, but I think you should be looking at a uint16 mode instead of an int mode for the ndarray.
