### ISSUE TITLE
ImportError: cannot import name Image

### ISSUE THREAD

**Issue by silbertmonaphia** [python-pillow/Pillow#2108]
### What did you do?
pip install 'Pillow==3.3.1'
from PIL import Image
### What actually happened?
ImportError: cannot import name Image
### What versions of Pillow and Python are you using?
Pillow==3.3.1
Python==2.7.12+

 I use Kali Rolling and virtualenv

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies.

```
#! /usr/bin/env python
# encoding:utf-8
from PIL import Image

im=Image.open('/home/smona/py_spiders/ceair/loginStatus/captcha/TrainedData/0.jpg')
im.show()

```

**Comment by silbertmonaphia** [comment]
![image](https://cloud.githubusercontent.com/assets/17708548/18498773/ab9d9b8e-7a6b-11e6-9d00-53d8fda78e8d.png)

But  I can import Image in  interactive mode

**Comment by silbertmonaphia** [comment]
My fault.....I name my python script 'PIL.py':D

**Comment by trinitybest** [comment]
Unbelievable.. I made the same mistake...

**Comment by wzheng92** [comment]
Unbelievable.. I made the same mistake TOO...

**Comment by abishek21** [comment]
i have python2.7.14 what version of pillow should i install?

**Comment by hugovk** [comment]
@abishek2 Install the latest: Pillow 5.0.0.

**Comment by abishek21** [comment]
i tried it says import error:cannot import name image
please help mee am stuck with this for 3hrss

**Comment by hugovk** [comment]
@abishek21 Please open a new issue and give full details of the error.
