### ISSUE TITLE
Can't install in Windows python 2.7.9

### ISSUE THREAD

**Issue by chibill** [python-pillow/Pillow#2109]
### What did you do?
I ran pip install Pillow
### What did you expect to happen?
Pillow to be installed
### What actually happened?
Pip crashed with the error that zlib is required. 
### What versions of Pillow and Python are you using?
I don't have Pillow so not sure exactly. Python 2.7.9 on Windows 10

**Comment by chibill** [comment]
The pip log file from the attempted install.
https://gist.github.com/chibill/9bd71d9f1e8ba116f556b499af725e06

**Comment by wiredfool** [comment]
Your pip is attempting to compile pillow without the required dependencies.   Pip should be installing a binary, but it's not. It's possible that you need to update your version of pip (or python).

**Comment by hugovk** [comment]
Works with Windows 7:
```
C:\>python --version
Python 2.7.11

C:\>pip --version
pip 8.1.2 from c:\python27\lib\site-packages (python 2.7)

C:\>pip install -U pillow
Collecting pillow
  Downloading Pillow-3.3.1-cp27-cp27m-win_amd64.whl (1.4MB)
    100% |################################| 1.4MB 799kB/s
Installing collected packages: pillow
  Found existing installation: Pillow 3.3.0
    Uninstalling Pillow-3.3.0:
      Successfully uninstalled Pillow-3.3.0
Successfully installed pillow-3.3.1
```

**Comment by chibill** [comment]
Okay it seemed to be pip.  Apparently I was way out of date on it. (which is odd)
