### ISSUE TITLE
Test suite fails with freetype 2.7

### ISSUE THREAD

**Issue by DimStar77** [python-pillow/Pillow#2116]
Freetype 2.7 has been released

PIL's test suite seems to fail in this situation (could potentially also be freetype's fault)

```
[   59s] FAIL: TestImageFont.test_multiline_spacing
[   59s] ----------------------------------------------------------------------
[   59s] Traceback (most recent call last):
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/test_imagefont.py", line 230, in test_multiline_spacing
[   59s]     self.assert_image_similar(im, target_img, .5)
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/helper.py", line 100, in assert_image_similar
[   59s]     ave_diff, epsilon))
[   59s] AssertionError:  average pixel value difference 6.1854 > epsilon 0.5000
[   59s] -------------------- >> begin captured logging << --------------------
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 2783
[   59s] --------------------- >> end captured logging << ---------------------
[   59s] 
[   59s] ======================================================================
[   59s] FAIL: TestImageFont.test_render_multiline
[   59s] ----------------------------------------------------------------------
[   59s] Traceback (most recent call last):
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/test_imagefont.py", line 147, in test_render_multiline
[   59s]     self.assert_image_similar(im, target_img, .5)
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/helper.py", line 100, in assert_image_similar
[   59s]     ave_diff, epsilon))
[   59s] AssertionError:  average pixel value difference 6.1854 > epsilon 0.5000
[   59s] -------------------- >> begin captured logging << --------------------
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 2786
[   59s] --------------------- >> end captured logging << ---------------------
[   59s] 
[   59s] ======================================================================
[   59s] FAIL: TestImageFont.test_render_multiline_text
[   59s] ----------------------------------------------------------------------
[   59s] Traceback (most recent call last):
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/test_imagefont.py", line 161, in test_render_multiline_text
[   59s]     self.assert_image_similar(im, target_img, .5)
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/helper.py", line 100, in assert_image_similar
[   59s]     ave_diff, epsilon))
[   59s] AssertionError:  average pixel value difference 6.1854 > epsilon 0.5000
[   59s] -------------------- >> begin captured logging << --------------------
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 2786
[   59s] --------------------- >> end captured logging << ---------------------
[   59s] 
[   59s] ======================================================================
[   59s] FAIL: TestImageFont.test_textsize_equal
[   59s] ----------------------------------------------------------------------
[   59s] Traceback (most recent call last):
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/test_imagefont.py", line 128, in test_textsize_equal
[   59s]     self.assert_image_similar(im, target_img, .5)
[   59s]   File "/home/abuild/rpmbuild/BUILD/Pillow-3.3.1/Tests/helper.py", line 100, in assert_image_similar
[   59s]     ave_diff, epsilon))
[   59s] AssertionError:  average pixel value difference 2.4736 > epsilon 0.5000
[   59s] -------------------- >> begin captured logging << --------------------
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IHDR 16 13
[   59s] PIL.PngImagePlugin: DEBUG: STREAM IDAT 41 1463
[   59s] --------------------- >> end captured logging << ---------------------

```

**Comment by hugovk** [comment]
I've not looked into the details, but we've been regularly tracking and updating freetype and this is the first to cause failures.

**Comment by radarhere** [comment]
I can confirm that it's not specific to your environment. Here's a link to Travis CI failing with the update - https://travis-ci.org/python-pillow/pillow-wheels/builds/159823682

**Comment by wiredfool** [comment]
That's likely to be a subtle font spacing issue, not an overall failure. I know we've had this issue before on these tests with a patch for freetype.

**Comment by badshah400** [comment]
This patch:
https://github.com/python-pillow/Pillow/compare/master...badshah400:master
gets things building, but please let me know if these epsilon values seem to high and if there might be some real problem here, when freetype 2.7 is used.

**Comment by badshah400** [comment]
In case master changes, I meant just this commit:
https://github.com/badshah400/Pillow/commit/00503ec6703c15f72808bcfa76f820f8ea617096

**Comment by hugovk** [comment]
I've updated to FreeType 2.7 and get the same errors. Here's how the newly-generated `im` look (macOS Sierra, Python 2.7.12, Pillow master badbff1b99a939c05b3651db7e4aea11181e5bd7) compared to the pre-generated `target_img` from the test suite.

Test | im  | target_img
--- | --- | ---
test_multiline_spacing | ![test_multiline_spacing-im](https://cloud.githubusercontent.com/assets/1324225/21098303/3e003f40-c071-11e6-8395-2ba6e8adb33d.png) | ![test_multiline_spacing-target_img](https://cloud.githubusercontent.com/assets/1324225/21098304/40e6dc32-c071-11e6-963c-44bdea98db82.png)
test_render_multiline_text | ![test_render_multiline_text-im](https://cloud.githubusercontent.com/assets/1324225/21098224/daf5e4a4-c070-11e6-8243-1c28b97eaf96.png) | ![test_render_multiline_text-target_img](https://cloud.githubusercontent.com/assets/1324225/21098232/e10af046-c070-11e6-8f55-1ec149ccd588.png)
test_render_multiline | ![test_render_multiline-im](https://cloud.githubusercontent.com/assets/1324225/21098241/ea548464-c070-11e6-9929-505e04702c79.png) | ![test_render_multiline-target_img](https://cloud.githubusercontent.com/assets/1324225/21098244/f25482ea-c070-11e6-8a31-59b302897cbf.png)
test_render_multiline_text - center | ![test_render_multiline_text_center-im](https://cloud.githubusercontent.com/assets/1324225/21100562/6e927c70-c07d-11e6-9ed2-e405441172e1.png) | ![test_render_multiline_text_center-target](https://cloud.githubusercontent.com/assets/1324225/21100572/7fb40276-c07d-11e6-99b8-54afb491bd64.png)
test_render_multiline_text - right | ![test_render_multiline_text_right-im](https://cloud.githubusercontent.com/assets/1324225/21100581/9010f21e-c07d-11e6-84f7-ad60d899b48b.png) | ![test_render_multiline_text_right-target](https://cloud.githubusercontent.com/assets/1324225/21100585/9207ac66-c07d-11e6-8dc9-81a56611ec2a.png)
test_textsize_equal | ![test_textsize_equal-im](https://cloud.githubusercontent.com/assets/1324225/21097909/8bd81ffa-c06f-11e6-8ddf-588a500d0103.png) | ![test_textsize_equal-target_img](https://cloud.githubusercontent.com/assets/1324225/21097924/96832a76-c06f-11e6-836d-c03ea4045bf1.png)

If anything, the old versions look a bit better, but here's a PR: https://github.com/python-pillow/Pillow/pull/2286.
