### ISSUE TITLE
Error: Cannot use ImageField because Pillow is not installed.

### ISSUE THREAD

**Issue by petitchamp** [python-pillow/Pillow#2124]
### What did you do?
I made a clone of my django project and created a new virtualenv with 
`python -m venv waterenv`
`python -m pip install -r requirement.txt`

Then I ran `manage.py migrate` to create my localdb 

### What did you expect to happen?
No error should apprears

### What actually happened?
I got following error 
```
_article.Article.photo: (fields.E210) Cannot use ImageField because Pillow is not installed.
        HINT: Get Pillow at https://pypi.python.org/pypi/Pillow or run command "pip install Pillow"._
```
But when I execute `from PIL import Image` in python console , everything is ok 
Then I tried the same thing, i.e. `manage.py syncdb` in Pycharm with the same virtualenv, MAGIC!
No error occured . 
It seems this error is only linked with windows console.

### What versions of Pillow and Python are you using?
Win7 64bit
Python 3.5.1 64bit
Pillow 3.3.1

**Comment by wiredfool** [comment]
You've got your virtualenvs confused -- It's not a pillow bug.
