### ISSUE TITLE
Include Pillow-SIMD in Pillow

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#2148]
@homm Just noticed https://pypi.python.org/pypi/Pillow-SIMD/3.3.2.post0 and wanted to explore the reasons why we don't include this in Pillow here.

**Comment by homm** [comment]
The reasons described here: https://github.com/uploadcare/pillow-simd#why-do-not-contribute-simd-to-the-original-pillow
and here: https://github.com/uploadcare/pillow-simd/issues/8

In short: we can't include this as is because it will break a lot of users. And there is no easy way to turn on this only for some users.

**Comment by aclark4life** [comment]
@homm I understand that part. I'm just saying, you could probably move the project here but continue to do separate package releases, if you are interested in doing so. Otherwise, no worries.

**Comment by homm** [comment]
By "moving here" you are referring to the transfer the repo to the "python-pillow" organization?

**Comment by aclark4life** [comment]
Right, assuming you require a separate repo. Ideally you could just do SIMD stuff in a branch, or something. But yeah you are welcome to move the repo here if you like.

**Comment by homm** [comment]
Ok, thanks for the proposition. At the moment I want to have for Pillow-SIMD at least separate readme (which will not be so elegant in a branch) and issues (less important).

There is a small announcement: I currently work on SIMD 3.4.0 release as well as Pillow-perf tools and page: http://homm.github.io/pillow-perf/ (just a beginning)

Maybe when I'm done, we could move current SIMD readme to a documentation page.

**Comment by aclark4life** [comment]
@homm Did this happen? I see https://github.com/python-pillow/pillow-perf …

**Comment by hugovk** [comment]
I'll close this issue.

I see https://github.com/python-pillow/pillow-perf is now in this org.

Just ping and re-open if you'd like to transfer https://github.com/uploadcare/pillow-simd over. 👍
