### ISSUE TITLE
Version 3.4.1 and 3.3.3

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2150]
### What did you do?

Messed up. Didn't run enough of the test matrix. 

### What did you expect to happen?

A clean release. Tests passing, birds chirping, happiness, gaiety. 

### What actually happened?

Bugs. Test failures. Earthquakes. Doom.  DOOOOOM.

* The check for overflow in map.c should check against ~~SSIZE_MAX~~ PY_SSIZE_T_MAX, not SIZE_MAX. 
* The tests in Image.py should let a 2 element list through in addition to a 2 element tuple. (3.4.0 only)

### What versions of Pillow and Python are you using?

3.3.2, 3.4.0

cc: @cgohlke @homm @aclark4life @hugovk @radarhere

**Comment by homm** [comment]
By the way, 3.3.2 isn't affected by wrong argument types. Maybe we should hide 3.4.0 from PyPI right now.

**Comment by aclark4life** [comment]
Done (hid 3.4.0 on PyPI)

**Comment by wiredfool** [comment]
ok, waiting on wheel build for the full test matrix there, and then I'll cherry pick and merge things all around.

**Comment by wiredfool** [comment]
Merges done, 3.3.3 looks good on all fronts, 3.4.1 is building well on appveyor and travis, waiting on the wheel build.

**Comment by wiredfool** [comment]
Sources are tagged & uploaded, Wheel builds have stalled on the OSX builds. There's some issue unrelated to today's changes. 

@cgohlke If you could do your thing with the windows binaries...

**Comment by homm** [comment]
Please hide Pillow 3.3.2 from PyPI

**Comment by homm** [comment]
Or not, because there is no binaries. Sorry

**Comment by cgohlke** [comment]
Here you go <http://www.lfd.uci.edu/~gohlke/download/Pillow-3.4.1.win-dist.zip>

**Comment by wiredfool** [comment]
Thanks @cgohlke .

**Comment by wiredfool** [comment]
Ok, windows and linux binaries are up, OSX is failing with `multibuild/common_utils.sh: line 45: shell_session_update: command not found` .

**Comment by wiredfool** [comment]
Travis issues sorted out with the OSX builds, they changed their default image between the test 3.3.3 run and the 3.4.1 run. Binaries are all up now. 

No one better be finding cause for 3.4.2 tomorrow.

**Comment by hugovk** [comment]
That's two config things that hit during release: https://github.com/python-pillow/Pillow/pull/2143 and https://github.com/python-pillow/pillow-wheels/issues/45.

Thanks for doing the four releases!
