### ISSUE TITLE
Add 32 bit linux to the Travis test matrix

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2152]
We should add at least a canary 32 bit build to the travis test matrix to prevent errors from slipping through.

**Comment by hugovk** [comment]
Travis CI have no plans to add 32-bit environments: https://github.com/travis-ci/travis-ci/issues/986#issuecomment-124141683.

There's a possible workaround here: https://github.com/travis-ci/travis-ci/issues/5770#issuecomment-197771661.

However, the macOS pillow-wheels builds already include some i686 builds, added in PR https://github.com/python-pillow/pillow-wheels/pull/36:

> Refactoring using multibuild submodule to run and test builds of manylinux1 wheels.
> Builds and tests on 64- and 32-bit.

And they failed on the "3.4.0 build" commit:
https://travis-ci.org/python-pillow/pillow-wheels/builds/164671267

Is that sufficient?

Note those macOS builds are only triggered on master for non-PRs: 
https://github.com/python-pillow/Pillow/blob/master/.travis.yml#L89-L104.

**Comment by wiredfool** [comment]
I know that we're getting x86 builds there, since that's what alerted me to the breakage. I'd just like to see the breakage prior to merging, rather than at the wheel building stage, since right now the pillow wheels aren't building except when they're manually triggered by a change to the pillow-wheels repo. But by that point, we were tagged and source uploaded on two different releases.
