### ISSUE TITLE
TrueType texts in different versions of Python are different

### ISSUE THREAD

**Issue by andreymal** [python-pillow/Pillow#2153]
```python
#!/usr/bin/env python
# -*- coding: utf-8 -*-

from __future__ import unicode_literals

import platform

import PIL
from PIL import Image, ImageFont, ImageDraw

impl = '{} {} - Pillow {}'.format(
    platform.python_implementation(), platform.python_version(),
    PIL.PILLOW_VERSION,
)

f1 = ImageFont.truetype('PTC75F.ttf', 20)
f2 = ImageFont.truetype('PTAstraSerif-Regular.ttf', 12)

im = Image.new('RGBA', (220, 100), (0, 0, 0, 255))
draw = ImageDraw.Draw(im)
draw.text((0, 0), 'Точки над ё!©®™¹²³', font=f1)
draw.text((0, 24), 'Test text', font=f2)
draw.text((200 - f2.getsize(impl)[0], 80), impl, font=f2)
im.save('result {}.png'.format(impl))
```

- [PTC75F.ttf](http://www.paratype.ru/uni/public/PTSansOFL.zip) (389684 bytes, md5: 126f7a51661907bcf946cd1d4b3fec79)
- [PTAstraSerif-Regular.ttf](http://www.paratype.ru/uni/public/PTAstraSerif.zip) (141212 bytes, md5: 5bf075dd75e33f7da15a4e081a50b673)

I ran this script (Arch Linux 64bit, extra/freetype2 2.7-2 installed) in four versions of python (including PyPy 5.4.1) and got different results (pay attention to "ё"):

![Точки над ё двигаются](https://i.imgur.com/KAy0npm.gif)

This is not critical (`font.getsize()` remains the same), but I want the same result pixel-to-pixel everywhere :)

Or it may be not Pillow bug/feature and I should update some third-party library?

**Comment by wiredfool** [comment]
I've run this on Ubuntu 12.04 (which is what travis is running), on 2.7, 3.4, pypy5.4.1, and 3.5, using freetype 2.4.8, and I'm not seeing any differences between the images (with the exception of the text tags at the bottom). 

![result cpython 2 7 3 - pillow 3 4 0 dev0](https://cloud.githubusercontent.com/assets/19792/19232776/8c4ff100-8ed9-11e6-86f9-eda5ee8f6741.png)
![result cpython 3 4 3 - pillow 3 4 0 dev0](https://cloud.githubusercontent.com/assets/19792/19232774/8c4eac82-8ed9-11e6-95ef-ddc020f1ea5a.png)
![result cpython 3 5 2 - pillow 3 5 0 dev0](https://cloud.githubusercontent.com/assets/19792/19232775/8c4fa0f6-8ed9-11e6-8464-345026e109a5.png)
![result pypy 2 7 10 - pillow 3 5 0 dev0](https://cloud.githubusercontent.com/assets/19792/19232777/8c53ab1a-8ed9-11e6-9027-c5ef347a267d.png)

**Comment by andreymal** [comment]
Hm.
Looks like fixed in 3.4.2
- I upgraded to 3.4.2 and can't reproduce it
- I downgraded to 3.4.1 and can reproduce it again
- I upgraded to 3.4.2 again and can't reproduce it again

You can reproduce it with Ubuntu 12.04, Pillow 3.4.1 and freetype upgraded to 2.7:
![](https://cdn.everypony.ru/storage/01/42/24/2016/10/22/a3abd3dc8d.gif)
![](https://cdn.everypony.ru/storage/01/42/24/2016/10/22/f7d27e24b6.gif)
Anyway, looks like fixed in 3.4.2, maybe issue can be closed

**Comment by wiredfool** [comment]
There is really nothing different in 3.4.2 that should affect this, since there's no resampling going on in this test, and that was the only change.

**Comment by andreymal** [comment]
I assume it may be related to a package building for PyPI (depends on freetype headers on developer machine? Someone updated freetype between 3.4.1 and 3.4.2? :)

**Comment by wiredfool** [comment]
He manylinux packages could explain it, when I tested, I was building from the source tree.  If you're getting a different version of freetype in manylinux wheels, that would certainly be sufficient to explain the differences, as there are pixel level changes in letter spacing.

**Comment by andreymal** [comment]
Now PyPI has manylinux packages for 3.4.2 ~~and it not looks like fixed now :D~~

Result are different for pillow compiled with freetype<=2.6 (like manylinux packages) and freetype>=2.7 (like my arch linux).

You can reproduce this on Travis CI with Ubuntu 12.04 after upgrading freetype to 2.7.

![](http://i.imgur.com/VNACaYC.gif)

@wiredfool just for information purposes (I just will always use --no-binary now)
