### ISSUE TITLE
3.4.2

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2167]
We're going to have a 3.4.2 release soon, tentatively Tuesday the 18th.

There's one patch for it so far, the fix for #2161, the regression in Image.thumbnail

I've pushed what is likely the final form into the 3.4.x branch for CI and other interested parties to review.

**Comment by wiredfool** [comment]
Thanks.

**Comment by wiredfool** [comment]
And out it goes... pinging @cgohlke

**Comment by hugovk** [comment]
Wheels builds failing with:
`ImportError: libjpeg.so.9: cannot open shared object file: No such file or directory`
https://travis-ci.org/python-pillow/pillow-wheels/builds/168719093

**Comment by cgohlke** [comment]
Here you go <http://www.lfd.uci.edu/~gohlke/download/Pillow-3.4.2.win-dist.zip>

You may want to remove the pypy wheels.

**Comment by wiredfool** [comment]
Thanks @cgohlke .  I'll test the pypy one, and upload if it's good enough. 

Windows builds are uploaded, Macos are _still_ going, and linux builds are broken.

**Comment by wiredfool** [comment]
Macos.  Still building. 

@aclark4life If you want to grab fhe OSX builds and upload them when they finish, go ahead. Otherwise I'll get them in the morning GMT.

```
wget -m -A 'Pillow-3.4.2-*'  'http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/'
```

**Comment by hugovk** [comment]
OS X builds are done.
https://travis-ci.org/python-pillow/pillow-wheels/builds/168719093

**Comment by wiredfool** [comment]
Ok, OSX builds are up.

**Comment by andyneff** [comment]
Are the manylinux1 wheels on the way?

**Comment by hugovk** [comment]
@andyneff At some point, yes, once https://github.com/python-pillow/pillow-wheels/issues/47 is fixed.

**Comment by hugovk** [comment]
https://github.com/python-pillow/pillow-wheels/issues/47 is fixed and Linux builds are passing: https://travis-ci.org/python-pillow/pillow-wheels/builds/168719093

**Comment by wiredfool** [comment]
Ok, manylinux wheels are uploaded.
