### ISSUE TITLE
Transfer pillow-perf to Pillow organization

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#2169]
I want to transfer my project to Pillow organization:

https://github.com/homm/pillow-perf

pillow-perf is set of scripts and docs designed to explain Pillow performance. It consists of three parts:

* `/testsuite/` — set of performance tests with rich CLI for different operations. Works against Pillow and other image libraries with python interface.
* `/auto/` — shell script which helps automate running testsuite against different Pillow versions at once.
* `/docs/` — [public page](http://homm.github.io/pillow-perf/) with benchmark results for different systems, detailed information about tests and applied optimizations.

The work is still in progress. A lot of texts, some readme, more tests and more platforms are required. But at that point, I want to continue the working on this project as on an official Pillow page.

**Comment by wiredfool** [comment]
Sounds good to me.

**Comment by hugovk** [comment]
Here's how to do it:

https://help.github.com/articles/transferring-a-repository-owned-by-your-personal-account/#transferring-to-an-organization

**Comment by homm** [comment]
> It'd be good to add a licence.

Any thoughts?

**Comment by homm** [comment]
Also, I'd like to hear @aclark4life here

**Comment by aclark4life** [comment]
@homm I think we like MIT, but I would check with @wiredfool to be sure.

**Comment by wiredfool** [comment]
As long as you have a valid, well recognized licence, I'm good with it. It's your work, you get to choose.

**Comment by homm** [comment]
> It'd be good to add a licence.

@hugovk Done. It under MIT

@wiredfool Can I transfer to you and then you'll transfer to python-pillow org?

<img width="469" alt="screen shot 2016-10-22 at 21 41 33" src="https://cloud.githubusercontent.com/assets/128982/19621715/7b5cf23c-98a0-11e6-95cd-facb1d37cbff.png">

**Comment by aclark4life** [comment]
@homm Can you initiate a transfer? If so, we can accept… I think that's how it's supposed to work.

**Comment by homm** [comment]
@aclark4life Done!

**Comment by aclark4life** [comment]
And done! https://github.com/python-pillow/pillow-perf

**Comment by wiredfool** [comment]
Great. I see my work here is done ;)
