### ISSUE TITLE
Creating GIF from JPEGs results in tiny file

### ISSUE THREAD

**Issue by FutureSharks** [python-pillow/Pillow#2174]
I want to create a GIF from a series of JPEG files. I've read the documentation and many examples but my output file is always 4328 bytes.

What am I doing wrong here?

```python
>>> from PIL import Image
>>> jpeg_files = ['%s-%s.jpg' % ('/some/path/image', i) for i in range(10)]
>>> ims = [Image.open(i) for i in jpeg_files]
>>> ims
[<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB6483238>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648C350>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648C468>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648C788>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648C918>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648CA80>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648CBE8>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648CD50>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB648CEB8>, <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x600 at 0xB6491058>]
>>> im=Image.new('RGB', size=(800,600))
>>> im.save('/some/path/pi.gif', append_images=ims, save_all=True, loop=True, duration=200)
```

**Comment by wiredfool** [comment]
Are you using a 3.4.x version of Pillow?

**Comment by FutureSharks** [comment]
Ah sorry, I had the OS package version installed, it was old. I installed via pip and now it works fine.

For anyone else who finds this, `loop` should be set to 0 to infinitely loop. Also in my example you end up with the first frame blank black. Not sure how I could delete a frame before appending during save, perhaps open the first jpeg and append the others.

Thanks wiredfool

**Comment by wiredfool** [comment]
Glad to hear that it was that easy to fix. 

Saving the first frame and appending the others should work, as what's happening now is that you're creating a black frame with the `Image.new` call, and then appending the others.
