### ISSUE TITLE
Should ICO really be classified as a “read-only” file format?

### ISSUE THREAD

**Issue by alexwlchan** [python-pillow/Pillow#2179]
I’m reading the docs for 3.5.0dev0, and there’s a [list of supported image file formats](http://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html).

On this list, there are two sections: “fully supported formats” and “read-only formats”. ICO is listed as read-only, but this is what it says under ICO:

> ### ICO

> ICO is used to store icons on Windows. The largest available icon is read.

> The `save()` method supports the following options:

> * `sizes`: A list of sizes including in this ico file; these are a 2-tuple, (width, height); Default to [(16, 16), (24, 24), (32, 32), (48, 48), (64, 64), (128, 128), (255, 255)]. Any size is bigger then the original size or 255 will be ignored.

How can a read-only file format have a `save()` method? Is this just in the wrong section, or have I misunderstood something?

**Comment by wiredfool** [comment]
Yeah, it looks like the save was added without moving it out of the read-only section of the docs.
