### ISSUE TITLE
Documentation recommends aggdraw yet Pillow broke compatibility with aggdraw

### ISSUE THREAD

**Issue by peterrb** [python-pillow/Pillow#2190]
### What did you do?
Current Documentation for the ImageDraw module says for more advanced drawing, see the aggdraw module, with a link directly to effbot's aggdraw site.
However, aggdraw is not compatible with PIL (starting from whenever Image.fromstring was removed).

Users might feel frustrated at the advice to install something that the maintainers broke compatibility with.

### What did you expect to happen?
Aggdraw should work despite its dependency on old and unpleasant functions which the maintainers of Pillow would rather remove. Aggdraw is an old but nonetheless extremely useful library even today, a truth borne out in the fact that the documentation for the ImageDraw module which still recommends it. 
I believe that for a library which is intended to serve as a drop in replacement for PIL, breaking compatibility with commonly used tools or libraries should be treated as a bug.
When these kind of bugs affect a library where development has stagnated or ceased altogether, as is the case with aggdraw, it effectively locks users out of functionality they used to have, unless they are exceptional enough to be able to modify and compile their own extensions from source.
 However trivial it may be to fix aggdraw (some have cloned it and done so themselves to workaround exactly this problem), this is far beyond the reach of many PIL users who would follow the common advice of "just use pip and install aggdraw" and then find themselves stymied.

### What actually happened?
Calling aggdraw.Draw(image) will result in either a NotImplemented exception or a base exception (depending on the Pillow version).

### What versions of Pillow and Python are you using?
Python 2.7, Pillow 3.2.0 through to Pillow 3.4.2
```python
from PIL import Image
import aggdraw
img = Image.new("RGBA",(10,10))
drawing_context = aggdraw.Draw(img)
# User sees "NotImplementedError: tostring() has been removed. Please call tobytes() instead." and thinks "how nice of them to remove that :("
```

**Comment by pinobatch** [comment]
I see a 10-month-old commit in <https://github.com/jakul/aggdraw> that fixes this issue.

**Comment by wiredfool** [comment]
Is there a clear master aggdraw repo that's maintained for current pythons/Pillow/Security Bugs?  I'm seeing at least https://github.com/scottopell/aggdraw-64bits and https://github.com/jakul/aggdraw .

**Comment by hugovk** [comment]
See also https://pypi.python.org/pypi/PyAgg/0.2.0 == https://github.com/karimbahgat/PyAgg

**Comment by aclark4life** [comment]
Ehhh so what should we do here? Is this a documentation change (or are we waiting to update AggDraw)?

**Comment by wiredfool** [comment]
Probably clear the aggdraw recommendation and possibly link to a maintained version.

**Comment by hugovk** [comment]
> I see a 10-month-old commit in <https://github.com/jakul/aggdraw> that fixes this issue.

That now lives at https://github.com/pytroll/aggdraw where it is being maintained; see https://github.com/pytroll/aggdraw/issues/11.
