### ISSUE TITLE
Draw rotated ellipse

### ISSUE THREAD

**Issue by mrlzla** [python-pillow/Pillow#2204]
I wanted to draw a rotated ellipse, but I was confused that there is no way to do this.

**Comment by radarhere** [comment]
Would you be content with an explanation of how to draw an ellipse, rotate the image, and then paste it on top of another image?

**Comment by mrlzla** [comment]
http://stackoverflow.com/questions/40442931/how-to-rotate-ellipse-in-pilpillow
I have a solution but there is a problem. In the cycle I create something like gradient.And it doesn't work.
If I do somethink like this(without rotating ellipse), it works:
`
draw = ImageDraw.Draw(im, 'RGBA')# first im has 'RGB' format
for l in range(b, -1, -1):
    color = (red, green, blue, int(alpha/(b)))
    draw.ellipse((x0-l*2, y0-l, x0+l*2, y0+l), fill=color)
return im
`

**Comment by radarhere** [comment]
I'm missing some variables from both the Stackoverflow code and your code snippet, and once I modify it to get it working, it seems to work for me. To be helpful, I'll show a simple version here -

    from PIL import Image, ImageDraw

    overlay = Image.new('RGBA', (200, 100))
    draw = ImageDraw.Draw(overlay)
    draw.ellipse((0, 0, 200, 100), '#0f0')

    im = Image.new('RGB',(500,500),'#f00')
    rotated = overlay.rotate(45, expand=True)
    im.paste(rotated, (0, 0), rotated)
    im.save('test.png')

**Comment by radarhere** [comment]
@mrlzla was this situation ever resolved for you?
