### ISSUE TITLE
Image.paste box=None doesn't work as documented

### ISSUE THREAD

**Issue by tisdall** [python-pillow/Pillow#2207]
The docs say that box having a value of `None` is "same as (0, 0)".  But [the code clearly shows](https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1311) that it's actually equal to (0, 0, self.size[0], self.size[1]).

The difference is an exception occurs if the image being pasted in (the one in the first argument) is not the same size as the destination image.  If instead you pass `box=(0, 0)`, you don't get an exception when the pasted image is a different size as it's just pasted at the top left regardless of it's size.

```
img = Image.new(
    mode='RGBA',
    size=(100, 100),
    color=(255,255,255,0)
)

small_img = Image.new(
    mode='RGBA',
    size=(50, 50),
    color=(255,255,255,0)
)

img.paste(small_img, box=(0,0))  #  this works fine
img.paste(small_img)  # this throws an exception
```

It looks like it's safe to just change:
```
    if box is None:
        # cover all of self
        box = (0, 0) + self.size
```
into:
```
    if box is None:
        box = (0, 0)
```

**Comment by radarhere** [comment]
Thanks for reporting this. I've created a PR with your suggested change.

**Comment by tisdall** [comment]
^_^  Thank you.  I didn't think such a simple PR would be accepted so I stuck with filing an issue.  Shouldn't the failing example I gave be included in a test somewhere? (maybe somewhere in [test_image_paste.py](https://github.com/python-pillow/Pillow/blob/master/Tests/test_image_paste.py)?)

**Comment by radarhere** [comment]
Yep, you're right about the test code. I've now added it. Thanks.
