### ISSUE TITLE
JPEG format image not getting compressed

### ISSUE THREAD

**Issue by zealfire** [python-pillow/Pillow#2238]
### What did you do?
```python
from PIL import Image
img = Image.open('/../../Desktop/jpg_test.jpg')
img.save('/../../Desktop/new_jpg.jpg', format='JPEG', optimize=True, quality=70)
```
### What did you expect to happen?
Size of newly formed image(new_jpg.jpg) should get reduced.
### What actually happened?
instead it increased to ~13.6kB.
Size of original image ~11.8kB

### Below attached is original image:
![jpg_test](https://cloud.githubusercontent.com/assets/5805013/20465329/6fa1539c-af80-11e6-96ee-922a741b9991.jpg)

**Comment by wiredfool** [comment]
Is it smaller if you set quality to 60? Larger at 80?

**Comment by zealfire** [comment]
@wiredfool 
for quality set at 60 it is still more than expected(~12.7kB)
and for quality set at 80 it increases again to ~14.9kB

**Comment by hugovk** [comment]
Confirmed output files are bigger than the original (created with Adobe Photoshop CC 2014 (Windows)), but output file size does change as expected when changing quality:
```
$ python
Python 2.7.12 (default, Sep 28 2016, 18:41:32) 
[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.38)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> img = Image.open("jpg_test.jpg")
>>> img.save("70.jpg", format='JPEG', optimize=True, quality=70)
>>> img.save("80.jpg", format='JPEG', optimize=True, quality=80)
>>> img.save("60.jpg", format='JPEG', optimize=True, quality=60)
>>> exit()

$ ll *.jpg
-rw-r--r--  1 hugo          wheel   12651 21 Nov 09:20 60.jpg
-rw-r--r--  1 hugo          wheel   13550 21 Nov 09:19 70.jpg
-rw-r--r--  1 hugo          wheel   14878 21 Nov 09:19 80.jpg
-rw-r--r--  1 hugo          wheel   11774 20 Nov 20:51 jpg_test.jpg
```

**Comment by wiredfool** [comment]
I think that this is working as intended. The quality levels are consistent with one encoder and one file, it just appears that photoshop generates a smaller file for a given quality than whatever libjpeg is linked.

**Comment by chichengfengye** [comment]
Hello wiredfool, I have the save problem , can you tell me how you solved it？
thanks！
