### ISSUE TITLE
LANCZOS/ANTIALIAS filter not available for degree rotation?

### ISSUE THREAD

**Issue by jaddison** [python-pillow/Pillow#2247]
### What did you do?

Tried to `im.rotate(45, resample=Image.LANCZOS, expand=True)`.

### What did you expect to happen?

Rotate the specified degrees, expanding the image as necessary to contain the resulting image and resampled using LANCZOS.

### What actually happened?

An exception was thrown because only certain resampling methods are permitted - and LANCZOS is not one of them. See https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L1912

### What versions of Pillow and Python are you using?

Python 3.5.2
Pillow 3.4.2

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

1. Load an image into `im`.
2. Try:
```python
im.rotate(45, resample=Image.LANCZOS, expand=True)
```

**Comment by hugovk** [comment]
That's right, Lanczos is only for resize() and thumbnail() at the moment:

> Calculate the output pixel value using a high-quality Lanczos filter (a truncated sinc) on all pixels that may contribute to the output value. This filter can only be used with the resize() and thumbnail() methods.

https://pillow.readthedocs.io/en/3.4.x/handbook/concepts.html?highlight=lanczos#filters

**Comment by jaddison** [comment]
I just assumed that it was an oversight that it wasn't included for the rotate operation. 

You're saying it literally can't be added in and made to work at all by the nature of the algorithm? If so, I'll close this issue.

**Comment by hugovk** [comment]
Have a look at https://github.com/python-pillow/Pillow/issues/636#issuecomment-229931103:

> Currently, transformations use fast but very inaccurate filters based on fixed number of source samples (like resizing with `BICUBIC` and `BILINEAR` in Pillow prior `2.7.0`). `LANCZOS` (former `ANTIALIAS`) doesn't have any advantages over `BICUBIC` with such approach.

**Comment by jaddison** [comment]
OK, I'll close as nothing can be done. Thank you!
