### ISSUE TITLE
Permission to add stubs for Pillow to Typeshed?

### ISSUE THREAD

**Issue by rowillia** [python-pillow/Pillow#2250]
Howdy

I'd like to add stubs for Pillow to https://github.com/python/typeshed, a repository used to store PEP 484 type signatures for the python stdlib and popular third party libraries. As per PEP 484, permission is required from the library owner before merging type signatures into typeshed - https://www.python.org/dev/peps/pep-0484/#the-typeshed-repo. Would you mind if I contributed those stubs?  I would be happy to continue maintaining them.

**Comment by wiredfool** [comment]
I don't have any objections, but I'm not clear on the obligations that it would entail. Though essentially, I believe that the license grants you to the right to make this derivative work (type annotations) and release it under the existing license.

**Comment by radarhere** [comment]
typeshed's Pillow stubs have been [removed](https://github.com/python/typeshed/pull/12732), since Pillow now has it's own type hints.
