### ISSUE TITLE
Image of size zero is not getting initialized.

### ISSUE THREAD

**Issue by rakeshvar** [python-pillow/Pillow#2259]
I want an image with zero size. I have a lot of use for it.

```py
>>> from PIL import Image as im
>>> import numpy as np
>>> im.fromarray(np.empty((0, 0), dtype=np.uint8))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2187, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2114, in frombuffer
    _check_size(size)
  File "/usr/local/lib/python3.4/dist-packages/PIL/Image.py", line 2001, in _check_size
    raise ValueError("Width and Height must be > 0")
ValueError: Width and Height must be > 0
```

This was working previously. But after this [commit](https://github.com/python-pillow/Pillow/commit/445451c0b9347b50e0f603db33f196e207de470d), in the latest version (i.e. 3.4.2) it is throwing an error.

As @manthey points out in the commit, one can create a zero sized image by cropping an existing one. So this too should be allowed. 

Thanks.

**Comment by hugovk** [comment]
@manthey's [commit](https://github.com/python-pillow/Pillow/commit/445451c0b9347b50e0f603db33f196e207de470d) comment:

> Prior to this change, you could create a
new image with a zero size. Now, you
can't, but you can still crop an image to
end up with an image of zero size. Is
there a reason it is allowed based on
some operations but not in a new image? It seems it should either be
allow in both instances or neither.

@rakeshvar's commit comment:

> I strongly agree with @manthey. This
check should not even be there. What is
wrong with an image of size 0x0?

The commit is part of PR https://github.com/python-pillow/Pillow/pull/2146, which are fixes for https://github.com/python-pillow/Pillow/issues/2105, "Multiple memory corruption
vulnerabilities".

**Comment by wiredfool** [comment]
I'm not clear where a 0x0 image is useful. Can you explain the usecase?

**Comment by rakeshvar** [comment]
The same way the number [zero](https://en.wikipedia.org/wiki/Identity_element) is useful in mathematics. It acts as an additive identity, and is key to defining a [Group](https://en.wikipedia.org/wiki/Group_(mathematics)) in the image space. This helps if you are stitching images together - which has obvious uses. Also like @manthey mentioned, when you crop (subtract) an image from itself, it results in the zero image. Hence denying a zero is not mathematically consistent, and will result in bugs.

**Comment by manthey** [comment]
I have two code paths that handle certain image operations.  One has a crop step that can result in a 0 x 0 image.  The other has a condition where if a certain condition is not met, I have no image data, but I have a band specification.  Both these paths then can optionally create a larger image that has the same color bands as this image.  Originally I had an output step where these paths come together and was creating a 0 x 0 image in the second condition to indicate that there would be no image data.  This was handier than passing a special value, as the image maintains the color band information for the later step.

**Comment by homm** [comment]
What if you want to resize zero image to real size. Which color should it be? The infinity color?

> This helps if you are stitching images together

Could you elaborate this?

> Prior to this change, you could create a new image with a zero size. Now, you can't, but you can still crop an image to end up with an image of zero size.

This is bug, in my opinion.

**Comment by hugovk** [comment]
> What if you want to resize zero image to real size. Which color should it be? The infinity color?

The default colour, black. https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L2009

**Comment by ChillarAnand** [comment]
Doesn't seem to work on latest version

```
→ cat pillow_exp.py 
from PIL import Image
import numpy as np

Image.fromarray(np.empty((0, 0), dtype=np.uint8))

→ python pillow_exp.py 
[1]    1498 floating point exception (core dumped)  python pillow_exp.py
```

**Comment by hugovk** [comment]
I can reproduce with Pillow 4.0.0 and master and get `Floating point exception: 8`

Problem is in map.c:

```
Crashed Thread:        0  Dispatch queue: com.apple.main-thread

Exception Type:        EXC_ARITHMETIC (SIGFPE)
Exception Codes:       EXC_I386_DIV (divide by zero)
Exception Note:        EXC_CORPSE_NOTIFY

Termination Signal:    Floating point exception: 8
Termination Reason:    Namespace SIGNAL, Code 0x8
Terminating Process:   exc handler [0]

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   _imaging.so                   	0x000000010aa0880f PyImaging_MapBuffer + 287 (map.c:345)
1   org.python.python             	0x000000010a63c23d PyEval_EvalFrameEx + 27113
2   org.python.python             	0x000000010a63565e PyEval_EvalCodeEx + 1617
3   org.python.python             	0x000000010a63feee fast_function + 117
4   org.python.python             	0x000000010a63c159 PyEval_EvalFrameEx + 26885
5   org.python.python             	0x000000010a63565e PyEval_EvalCodeEx + 1617
6   org.python.python             	0x000000010a63feee fast_function + 117
7   org.python.python             	0x000000010a63c159 PyEval_EvalFrameEx + 26885
8   org.python.python             	0x000000010a63565e PyEval_EvalCodeEx + 1617
9   org.python.python             	0x000000010a635007 PyEval_EvalCode + 48
10  org.python.python             	0x000000010a658a8c run_mod + 53
11  org.python.python             	0x000000010a658b2f PyRun_FileExFlags + 133
12  org.python.python             	0x000000010a658680 PyRun_SimpleFileExFlags + 702
13  org.python.python             	0x000000010a669e1e Py_Main + 3094
14  libdyld.dylib                 	0x00007fffcbc4d255 start + 1

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x000000007fffffff  rbx: 0x000000010a7f925c  rcx: 0x0000000000000000  rdx: 0x0000000000000000
  rdi: 0x000000010a7f925e  rsi: 0x0000000000000000  rbp: 0x00007fff556505a0  rsp: 0x00007fff556504c0
   r8: 0x0000000000000000   r9: 0x00007fff55650480  r10: 0x000000010aa3f2cb  r11: 0x0000000000000029
  r12: 0x000000010a8e5120  r13: 0x00007fd935406660  r14: 0x000000010a9c14d0  r15: 0x00007fd935496748
  rip: 0x000000010aa0880f  rfl: 0x0000000000010246  cr2: 0x000000010aa086f0
  ```
