### ISSUE TITLE
The _imaging C module is not installed

### ISSUE THREAD

**Issue by frankgould** [python-pillow/Pillow#2260]
I have searched and tried everything I could find online to fix this problem but it continues to occur when executing the following code in my Android apk. I build the apk using buildozer and the compile is successful and runs until it hits the line below.

img.rotate(270).save(filename, pix_type)

I have copied all the _imaging .c files into my app's PIL folder, they compile into .so files, and they all reside in the Android .../files/app/PIL folder on a tablet. Previously, I uninstalled Pillow, installed libjpeg-dev, freetype-dev, and libpng-dev, and then resinstalled Pillow.

My compiler runs on Oracle VirtualBox Ubuntu linux mint and when testing python interpreter in the terminal window, the same code that fails on Android, works in the interpreter.

I don't know what to do next and would appreciate any assistance or direction for me to investigate. I spent a day trying all online suggestions but have yet to find a solution. Please let me know if there is any additional information I can provide. Below is the full Traceback, if helpful.

I/python  (14984): [INFO   ] [Base        ] Leaving application in progress...
I/python  (14984):  Traceback (most recent call last):
I/python  (14984):    File "main.py", line 3070, in <module>
I/python  (14984):      SlideShow().run()
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/lib/python2.7/site-packages/kivy/app.py", line 828, in run
I/python  (14984):      runTouchApp()
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/lib/python2.7/site-packages/kivy/base.py", line 487, in runTouchApp
I/python  (14984):      EventLoop.window.mainloop()
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 637, in mainloop
I/python  (14984):      self._mainloop()
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/lib/python2.7/site-packages/kivy/core/window/window_sdl2.py", line 390, in _mainloop
I/python  (14984):      EventLoop.idle()
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/lib/python2.7/site-packages/kivy/base.py", line 327, in idle
I/python  (14984):      Clock.tick()
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/lib/python2.7/site-packages/kivy/clock.py", line 581, in tick
I/python  (14984):      self._process_events()
I/python  (14984):    File "kivy/_clock.pyx", line 368, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7731)
I/python  (14984):    File "kivy/_clock.pyx", line 398, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7608)
I/python  (14984):    File "kivy/_clock.pyx", line 396, in kivy._clock.CyClockBase._process_events (kivy/_clock.c:7529)
I/python  (14984):    File "kivy/_clock.pyx", line 168, in kivy._clock.ClockEvent.tick (kivy/_clock.c:3521)
I/python  (14984):    File "main.py", line 1835, in startup
I/python  (14984):      self.sync_pix(True)
I/python  (14984):    File "main.py", line 2511, in sync_pix
I/python  (14984):      if sync_server_pix(init_sync, gd_client):
I/python  (14984):    File "main.py", line 918, in sync_server_pix
I/python  (14984):      fix_rotation(vp_frame.local_pix + pname, pix_type)    # Fix file rotation issues from exif data.
I/python  (14984):    File "main.py", line 913, in fix_rotation
I/python  (14984):      img.rotate(270).save(filename, pix_type)
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/PIL/Image.py", line 1621, in rotate
I/python  (14984):      return self.transform((w, h), AFFINE, matrix, resample)
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/PIL/Image.py", line 1866, in transform
I/python  (14984):      im = new(self.mode, size, None)
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/PIL/Image.py", line 2025, in new
I/python  (14984):      return Image()._new(core.new(mode, size))
I/python  (14984):    File "/data/data/com.masterpics.slideshow/files/app/PIL/Image.py", line 45, in __getattr__
I/python  (14984):      raise ImportError("The _imaging C module is not installed")
I/python  (14984):  ImportError: The _imaging C module is not installed
I/python  (14984): Python for android ended.

**Comment by wiredfool** [comment]
The only report that we've ever had of Pillow on android is https://github.com/python-pillow/Pillow/issues/1957 . You're trying something that's unsupported at the very least. 

If I had to guess, you've got an architecture mismatch between your build platform and where you're running it. You're going to need to either cross compile for android or build on android.

**Comment by frankgould** [comment]
I've been working with some people on kivy.org and there appears to be a PIL recipe in python-for-android. Kivy.org's inclement replied "There was a PR for pillow, I can't remember what happened there, maybe it was never merged." So, I don't know what to do to move this forward that way. The alternative is to manipulate the texture array in Kivy which is a lot more work than just using a library function to rotate by degrees while saving (which I've coded and tested).

I also read #1957 you recommended and the LFLAGS setting resulted in the same run time error. I'm guessing there's something in the recipe that will compile the library once I understand what needs to change to make it work or ask someone to fix it.

Any suggestions will be greatly appreciated.

**Comment by wiredfool** [comment]
Unless you're using a lot of Pillow's functionality, I'd say that using a rotational transform in kivy is probably less effort than packaging Pillow for a platform where we've had 1 known successful attempt ever to run on. And even then.

**Comment by frankgould** [comment]
I can attest that PIL/Pillow does run on Android because my code is now executing the rotate function successfully. So, you can now say you've had 2 known successful attempts. Yes, there is a kivy way to solve this with a simple array algorithm but I don't want to be manipulating image pixels just to rotate an image. That was the solution the devs suggested on kivy.org IRC. Besides, I'm now sure that in the future I have the image library available for additional features in my app.

To close this ticket as resolved, below is the section I updated in buildozer.spec with pil and pillow in the requirements to fix the apk from crashing when receiving a rotated image, defined in EXIF metadata. This crash also caused Android to dump memory and system data in the logcat.

# (list) Application requirements
# comma seperated e.g. requirements = sqlite3,kivy
requirements = kivy,openssl,pyopenssl,hostpython2,pil,pillow

**Comment by wiredfool** [comment]
I'm glad you got it working.
