### ISSUE TITLE
Is there a `read` interface to read from Image object?

### ISSUE THREAD

**Issue by RobGThai** [python-pillow/Pillow#2287]
I'm trying to upload Image object onto [Swift](http://docs.openstack.org/developer/swift/) storage.
Swift support reading from two sources, `read` enabled object or path as string.

Image object seems to be reading data into it using `read` method. Is there a way to read out in the same fashion? 

Under the hood, Swift is reading content from object like this: 

```
    def __next__(self):
        chunk = self.content.read(self.chunk_size)
        if not chunk:
            raise StopIteration

        try:
            self.md5sum.update(chunk)
        except TypeError:
            self.md5sum.update(chunk.encode())

        return chunk
```

Is this possible with Pillow?

**Comment by wiredfool** [comment]
There is no interface like that directly from an Image object. The image object is an internal memory representation of an image, so it's not really a storage format. There is an array interface for acting on the pixels for scipy/numpy, but that's not likely to be useful. 

The best way would be to save the Image into a io.BytesIO object, in whatever image format you require (png/jpeg/etc), then pass that to Swift.

**Comment by homm** [comment]
> I'm trying to upload Image object onto Swift storage.

Are you really trying to upload python Image object (like something Pickling) or an Image file? Anyway, you need first to serialize the Image object to appropriate format (either pickle or PNG/JPEG), then upload it.

```python
import io
from PIL import Image

im = Image.new('RGB', (200, 200))
buffer = io.BytesIO()
im.save(buffer, format='PNG')
buffer.seek(0)
```

**Comment by RobGThai** [comment]
@homm Thanks, I didn't realise I can use `save` to write to the buffer. I actually ended up using that.
