### ISSUE TITLE
Move #pillow IRC channel to #pil

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#2297]
(Just want to keep a record of this task, as well as introduce the ``Infrastructure`` label for issues related to Pillow community infrastructure e.g. servers, policies, etc.)

I've been meaning to tackle this for a few years now, and just decided this year is the year. I want to automatically redirect users from #pillow on Freenode to #pil, following these steps:

- https://wiki.ubuntu.com/IRC/MovingChannels

I thought that I could just mirror the channels, but I'm not seeing an easy way to do that now. I'm also not sure which is better, assuming such an option exists. Our IRC traffic is low, so it probably doesn't matter either way.

**Comment by jleclanche** [comment]
You can do this by setting the channel to `+f #pil` and making sure to set `MLOCK +f #pil` as well (so that that doesn't expire after a few months).

**Comment by aclark4life** [comment]
@jleclanche OK so I'm actually going to try to do that soon!

**Comment by radarhere** [comment]
https://en.wikipedia.org/wiki/Freenode
> On 14 June 2021, Freenode administrators launched a new network under the freenode name based on InspIRCd and Anope IRC services, intended to replace the previous network. Unlike previous migrations, none of the data from the old network, such as user and channel registration, was migrated over to the new network.

If I search at https://webchat.freenode.net/, I can't find #pil or #pillow.

So I think we no longer need to worry about moving the channel... the question is now whether people feel the need for a Freenode channel, or if we should just stick with gitter?

**Comment by hugovk** [comment]
Other Python projects have been moving to https://libera.chat/ but I don't use either.

**Comment by aclark4life** [comment]
I would like to use Libera but don't yet … anyway yeah this one is no longer applicable, thanks.
