### ISSUE TITLE
Python+C coverage missing, not sent to Coveralls

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#2299]
The last coverage report on Coveralls is from a week ago, 13 December 2016, when PR #2234 was merged: https://coveralls.io/repos/19620/builds

The next merge after PR #2234 was @jdufresne's PR #2199, a few minutes later the same day, which also contained a change to .travis.yml, adding `pip install -e .`:

https://github.com/python-pillow/Pillow/pull/2199/files#diff-354f30a63fb0907d4ad57269548329e3R45

---

Here's a diff of the Py2.7 builds from the #2234 and #2199 merges:
https://www.diffchecker.com/GPJlMb1Y

There's a difference around line 3838 (looking at the line numbers on the left) when running `$ lcov --capture --directory . -b . --output-file coverage.info`:
```
Scanning . for .gcda files ...
Found 1 data files in .
Processing _webp.gcda
Finished .info-file creation
```
->
```
Scanning . for .gcda files ...
geninfo: ERROR: no .gcda files found in .!
```

Note that local Python coverage reports worked, but not the stuff to combine the C and Python reports and send to Coveralls.

---

Replacing `pip install -e .` with `pip install olefile` fixes the build, and sends reasonable-looking coverage numbers to Coveralls.

I've sent a PR for this (#2300), but is it the correct thing to do? Can/should we fix whatever `pip install -e .` did wrong?

---

`pip install -e .` did this:

```
$ travis_retry pip install -e .
Obtaining file:///home/travis/build/python-pillow/Pillow
Requirement already satisfied (use --upgrade to upgrade): olefile in /home/travis/virtualenv/python2.7.12/lib/python2.7/site-packages (from Pillow==3.5.0.dev0)
Installing collected packages: Pillow
  Running setup.py develop for Pillow
Successfully installed Pillow-3.5.0.dev0
```

Perhaps `python setup.py develop` is the problem?

**Comment by wiredfool** [comment]
LGTM
