### ISSUE TITLE
Cannot read sequences in GIF

### ISSUE THREAD

**Issue by Xdynix** [python-pillow/Pillow#2301]
### What did you do?
Firstly I generate a GIF file with three frames.
```python
from PIL import Image, ImageDraw

size = (15, 15)
im1 = Image.new(mode='RGB', size=size)
im2 = Image.new(mode='RGB', size=size)
im3 = Image.new(mode='RGB', size=size)

d1 = ImageDraw.ImageDraw(im1)
d2 = ImageDraw.ImageDraw(im2)
d3 = ImageDraw.ImageDraw(im3)

d1.rectangle([0, 0, 5, 5], fill=(255, 0, 0))
d2.rectangle([5, 5, 10, 10], fill=(0, 255, 0))
d3.rectangle([10, 10, 15, 15], fill=(0, 0, 255))

im1.save('im1.jpg')
im2.save('im2.jpg')
im3.save('im3.jpg')

# Following http://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving-sequences
im1.save('im.gif', save_all=True, append_images=[im2, im3])
```

Then I tried to read sequences in it.

```python
# Following http://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#reading-sequences
im4 = Image.open('im.gif')
try:
    print(im4.tell())
    im4.seek(im4.tell() + 1)
except EOFError:
    pass
```

### What did you expect to happen?
The script should print 0, 1, 2, since there are only three frames.

### What actually happened?
The script only print 0.
I also tried this on some other GIF downloaded from Internet, they also cannot be read correctly.
(And each frame of `im.gif` is red. But this palette issue have being reported before.)

### What versions of Pillow and Python are you using?

Pillow (3.4.2)
Python (3.5.1)

**Comment by radarhere** [comment]
You do not have a loop in your code. The script runs once and then is done.

I have changed your code to what I believe you were aiming for. Running it over the outputted image from the first section, it prints 0, 1 and 2.

    from PIL import Image
    im4 = Image.open('im.gif')
    while True:
        try:
            print(im4.tell())
            im4.seek(im4.tell() + 1)
        except EOFError:
            break

**Comment by Xdynix** [comment]
What a stupid mistake I've made...
I'm sorry to be such a bother.

**Comment by radarhere** [comment]
No worries!
