### ISSUE TITLE
Package name should match module name

### ISSUE THREAD

**Issue by nlw0** [python-pillow/Pillow#2303]
Now here is a great feature request PIL users have had since the beginning of eras. Can't we figure out a way to maintain compatibility with `import PIL` programs, but also allow us to `import Pillow`? Let us be nicer to our dumb IDEs and users who always get confused with the naming, let's make a module with the same name of the package, please... Are there any major technical barriers to that?

**Comment by aclark4life** [comment]
Short answer: no, not easily or elegantly. Or, yes: there are major technical barriers to that. Also I think we have a ticket on this somewhere … sorry!
