### ISSUE TITLE
Unhelpful error if libwebp is not installed

### ISSUE THREAD

**Issue by khazhyk** [python-pillow/Pillow#2309]
### What did you do?
Tried to open a webp file.
### What did you expect to happen?
The webp file opened, or PIL would notify me that it was compiled without webp support.
### What actually happened?
Got generic 'OSError: cannot identify image file'
### What versions of Pillow and Python are you using?
Python 3.5, Pillow 3.4.2

Judging by https://github.com/python-pillow/Pillow/issues/1930 a more specific error doesn't seem unreasonable, and could speed up troubleshooting for others in the future.

**Comment by aclark4life** [comment]
@khazhyk Can you send a pull request with the changes you want? Also what platform did you install on? I know that if you compile Pillow you'll see webp missing… but maybe you installed a pre-built wheel.

**Comment by khazhyk** [comment]
I had installed (not from wheel) a while ago and just so happened to recently to start using webp.

From what I understand by the code, a plugin will fail to import (and register) if the native extension isn't compiled (and logs to debug), which means by the time we reach open() we can't distinguish between something that matches no plugins and something that would match a plugin if it's native portion had been compiled. It seems like that could be changed to allow for that, although I don't fully understand PIL's design or rationale for what implications that would have.

**Comment by radarhere** [comment]
I've created a PR as a possible solution to this.

**Comment by hugovk** [comment]
Fixed by https://github.com/python-pillow/Pillow/pull/3169.
