### ISSUE TITLE
saving animated gif drops frames

### ISSUE THREAD

**Issue by gboeing** [python-pillow/Pillow#2314]
### What did you do?

Saved a set of 100 png files as an animated gif then opened the gif

### What did you expect to happen?

I expected the gif to have 100 frames, same as the number of png files

### What actually happened?

The gif has only 70 frames

### What versions of Pillow and Python are you using?

pillow 3.4.2, python 3.5.2

### Demo

There are 100 png files in the folder `save_folder`, named 000.png through 099.png. The first 16 images are identical to one another, and the final 16 images are identical to one another. The other 68 images are all different from each other. In other words, the animation would show the first image for 16 frames, then run through the middle 68 frames before coming to the concluding image which it shows for 16 frames. But when I save the gif, it is missing 15 of the first 16 images and 15 of the final 16 images. Thus there is no "pause" at the beginning or end of the animation.

```python
images = [Image.open(image) for image in glob.glob('{}/*.png'.format(save_folder))]
len(images)
```
returns: 100

```python
gif = images[0]
gif.save(fp=gif_filepath, format='gif', save_all=True, append_images=images[1:])
Image.open(gif_filepath).n_frames
```
returns: 70

**Comment by radarhere** [comment]
As a partial answer, you could workaround this problem using #2298

**Comment by gboeing** [comment]
@radarhere thanks yes that serves as a workaround. But any idea why it drops (seemingly depulicates?) frames?

**Comment by radarhere** [comment]
For my sake, here is a complete script to reproduce the problem. It results in 100 / 65, rather than 100 / 70, but the principle is the same.

    from PIL import Image
    import os, glob

    frames = [0]*16 + list(range(1,68)) + [68]*16

    save_folder = os.path.expanduser('~/Desktop/images')
    for i, r in enumerate(frames):
	    im = Image.new('RGB',(100,100),(r*4,0,0))
	    im.save(os.path.join(save_folder, str(i).zfill(3)+'.png'))

    images = [Image.open(image) for image in glob.glob('{}/*.png'.format(save_folder))]
    print(len(images))

    gif_filepath = os.path.join(save_folder, 'output.gif')
    gif = images[0]
    gif.save(fp=gif_filepath, format='gif', save_all=True, append_images=images[1:])
    print(Image.open(gif_filepath).n_frames)

When running this script, it hits 'FIXME: what should we do in this case?' - https://github.com/python-pillow/Pillow/blob/master/PIL/GifImagePlugin.py#L391 - the same number of times as the number of missing frames.

**Comment by wiredfool** [comment]
I can think of three options for the fixme -- either bump the duration on the previous frame, write a null frame of 0x0 pixels, or write a frame of 1x1.  

Bumping the duration would be the smallest file, but it would be the hardest to pull off since by the time we need to bump the duration, we've already written it to the file. 

I'm not sure if a 0x0 box frame would work for other decoders. I'm sure it's been done before though -- if only in a fuzzer. A 1x1 is probably the most compatible (at a wild guess).

**Comment by radarhere** [comment]
I've created a PR for the @wiredfool suggestion of extending the duration of the previous frame.

**Comment by Rawing** [comment]
I'm not sure if this is the same issue, but this also happens when there are no identical frames. For example, this code will output 1 instead of 2:
```
f1= Image.new("RGB", (1,1), "white")
f2= Image.new("RGB", (1,1), "black")

p= 'test.gif'
f1.save(p, 'GIF', save_all=True, append_images=[f2])

i= Image.open(p)
print(i.n_frames)
```

**Comment by radarhere** [comment]
Thanks for finding this bug.

`im` is an object, so it is passed in by reference. So even though the method doesn't used it, the modification to it still takes effect elsewhere.

I've created a PR to fix this. However, as an immediate workaround, if you change your code to `f1.save(p, 'GIF', save_all=True, optimize=False, append_images=[f2])`, you should find that it works.

**Comment by Rawing** [comment]
Setting `optimize=False` doesn't always work. It works with the white and black gif, but with different colors it doesn't:
```
f1= Image.new("RGB", (1,1), '#240000')
f2= Image.new('RGB', (1,1), '#481010')

p= 'test.gif'
f1.save(p, 'GIF', save_all=True, append_images=[f2], optimize=False)

i= Image.open(p)
print(i.n_frames, '/', 2) # outputs 1 / 2
```
Seems like there's a whole bunch of reasons why frames are being dropped. (Would it be better to open new issues for these?)

**Comment by radarhere** [comment]
Believe it or not, this is still about the colours being the same.

    from PIL import Image

    f1 = Image.new("RGB", (1,1), '#240000')
    f2 = Image.new('RGB', (1,1), '#481010')

    # As a sanity check, you can see that the colours are different
    print(f1.getpixel((0, 0)))  # (36, 0, 0)
    print(f2.getpixel((0, 0)))  # (72, 16, 16)

    # However, when saving, GifImagePlugin converts RGB frames to P mode
    # which is when the colours become the same
    print(f1.convert('P').getpixel((0, 0)))  # 11
    print(f2.convert('P').getpixel((0, 0)))  # 11

    # Likely related, changing the dimensions from (1,1) to (100,100)
    # You can see that the converted image is no longer a solid colour
    Image.new("RGB", (100,100), '#240000').convert('P').show()

So you may want to open a new issue for that.

**Comment by wiredfool** [comment]
Closing with #2375
