### ISSUE TITLE
Python 3.6 wheels

### ISSUE THREAD

**Issue by mgedmin** [python-pillow/Pillow#2318]
### What did you do?

`pip install Pillow` on a Windows machine with Python 3.6

### What did you expect to happen?

get Pillow

### What actually happened?

`ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting`, which is a bit misleading TBH since the Windows machine in question doesn't even have a C compiler on it.

### What versions of Pillow and Python are you using?

Pillow 3.4.2
Python 3.6.0

**Comment by tommyzat** [comment]
Same issue

**Comment by wiredfool** [comment]
We don't have 3.6 wheels yet, likely at the release in a few days.

Furthermore, that error is different in master/next release.

**Comment by mgedmin** [comment]
This issue was me trying ineptly to sqeeze "please would you upload Python 3.6 wheels to PyPI" into your issue template.  I'm glad to hear you've plans for that in the near future!

**Comment by aclark4life** [comment]
Hmmm. Whenever a new Python is released, I'm assuming there's nothing _practical_ or easy we can do for folks in this situation but tell them to wait for the next quarterly Pillow release. Unless we want to consider proactively "backfilling" the wheel supply…

**Comment by hugovk** [comment]
Unofficial Windows binaries for Python 3.7 are already available at http://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow

**Comment by aclark4life** [comment]
Well, those unofficial binaries are presumably available to be official if we ask @cgohlke.

**Comment by cgohlke** [comment]
Feel free to upload my Pillow‑3.4.2‑cp36 wheels to PyPI or wait two days for Pillow 4.0.
