### ISSUE TITLE
Setup.py: if dependency (zlib, jpeg..) not found, print locations where script has looked

### ISSUE THREAD

**Issue by grizzlyfred** [python-pillow/Pillow#2334]
DID:
Tried to install pillow into a docker image for aarch64 (arm64) on my odroid-c2 running hardkernel's stock ubuntu with the following docker file as follows (as a "feasability test" to get some more odroids and have them do something for me in a docker swarm...):

```
from aarch64/python:2.7 #use the "best effort" container for arm64

#Tried specifcally installing zlib1g-dev, but that seems to be there,
#so no effect so commented out
#RUN apt-get update
#RUN apt-get install -y zlib1g-dev

#didn't help
#ENV LIBRARY_PATH=/lib:/usr/lib:/usr/include

#Works so commented
#RUN pip install pyyaml
#RUN pip install psutil

#neither works
RUN  CPATH=/usr/include /bin/sh -c "pip install pillow"
RUN pip install pillow

```

Expected:
Pillow 4.0.0 would install into the docker image

Happened:
zlib not found:

```
The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     http://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-build-7vQrKP/pillow/setup.py", line 791, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
```
`

Version:
4.0.0 with python 2.7

Possible solution:
**Right at the start of setup.py, there is a hardcoded DEBUG=False. If I could pass a parameter to the setup.py such as --debug and that would be honored, I would maybe know, where the zlib.so zlib.a and zlib.h files have been looked for and I could symlink them there.**
I wouldn't mind manually wgetting pillow source, patching the setup.py and invoking that manually if it helps.
Even better would be to have a pre-built aarch64-wheel so I might have to learn how to create one.

**As an alternative, if zlib is not found, the setup.py should print where it has been looking.** So that one can try symlinking the files.

Strangely enough, somehow it seems to have been looking in multiarch-path and I did some symlinking but to no avail - this is on the host machine:

```
sudo find -name zlib* 2>/dev/null
./lib/modules/3.14.79-98/kernel/crypto/zlib.ko
./usr/lib/python3.5/encodings/zlib_codec.py
./usr/lib/python3.5/encodings/__pycache__/zlib_codec.cpython-35.pyc
./usr/lib/python2.7/encodings/zlib_codec.pyc
./usr/lib/python2.7/encodings/zlib_codec.py
./usr/lib/aarch64-linux-gnu/imlib2/loaders/zlib.so
./usr/lib/aarch64-linux-gnu/pkgconfig/zlib.pc
./usr/lib/aarch64-linux-gnu/zlib.h
./usr/lib/zlib.h
./usr/share/doc/zlib1g
./usr/share/doc/zlib1g-dev
./usr/share/doc/zlib1g-dev/examples/zlib_how.html
./usr/share/man/man3/zlib.3.gz
./usr/share/man/man1/zlib-flate.1.gz
./usr/share/mime/application/zlib.xml
./usr/include/zlib.h
./usr/bin/zlib-flate
```

I have not yet figured out how to "list" the file contents of the container during build so as to find out whether the aarch64/pyhton2.7 - container contains zlib.
On amd64 (but manjaro) no problem at all.
Maybe ubuntu again is just too old - maybe I shoul try to get to run archlinux on this odroid?

**Comment by wiredfool** [comment]
I think the command line you're looking for is 

`python setup.py build_ext --debug`

**Comment by grizzlyfred** [comment]
Well, better late then never. Running arch on the odroids since the summer, here all works as expected.
