### ISSUE TITLE
Olefile installation failure

### ISSUE THREAD

**Issue by invenis-paris** [python-pillow/Pillow#2335]
When installing pillow (4.0.0) in a Python3 venv with the command:
`python setup.py develop`
in a project which depends on pillow

I get: 

> Searching for olefile
> Reading https://pypi.python.org/simple/olefile/
> Downloading https://pypi.python.org/packages/61/f4/7b52981ee0c3c2521c504fa318466136be8d47bc720ef1eff2aa2f193730/olefile-0.43.tar.gz#md5=f570df81ebfab51aaa538af39fef6fd3
> Best match: olefile 0.43
> Processing olefile-0.43.tar.gz
> Writing /tmp/easy_install-6nz_cbcx/olefile-0.43/setup.cfg
> Running olefile-0.43/setup.py -q bdist_egg --dist-dir /tmp/easy_install-6nz_cbcx/olefile-0.43/egg-dist-tmp-ap58il3z
>   File "build/bdist.linux-x86_64/egg/olefile/olefile2.py", line 225
>     raise ValueError, 'Need to fix a bug with 32 bit arrays, please contact author...'
>                     ^
> SyntaxError: invalid syntax

**Comment by wiredfool** [comment]
What version of python are you running?

**Comment by invenis-paris** [comment]
Python 3.4.4

**Comment by wiredfool** [comment]
Despite the error, it does appear to work on my 3.4 installation. 

From the olefile2 header: https://bitbucket.org/decalage/olefileio_pl/src/3073963b640935134ed0da34906fea8e506460be/olefile/olefile2.py?at=default&fileviewer=file-view-default

> IMPORTANT NOTE: olefile2 is an old version of olefile meant to be used
as fallback for Python 2.5 and older. For Python 2.6, 2.7 and 3.x, please use
olefile which is more up-to-date. The improvements in olefile might
not always be backported to olefile2.

**Comment by invenis-paris** [comment]
Another test: when i create a new venv in which I just `pip install pillow` , it works.
So the problem is related to another dependencies.

**Comment by invenis-paris** [comment]
Maybe it will be easier with the full process (sorry):
$` python setup.py develop`

> /usr/lib/python3.5/distutils/dist.py:261: UserWarning: Unknown distribution option: 'tests_requires'
>   warnings.warn(msg)
> running develop
> running egg_info
> writing dependency_links to project_server.egg-info/dependency_links.txt
> writing top-level names to project_server.egg-info/top_level.txt
> writing requirements to project_server.egg-info/requires.txt
> writing entry points to project_server.egg-info/entry_points.txt
> writing project_server.egg-info/PKG-INFO
> reading manifest file 'project_server.egg-info/SOURCES.txt'
> reading manifest template 'MANIFEST.in'
> writing manifest file 'project_server.egg-info/SOURCES.txt'
> running build_ext
> Creating /home/benjamin/.virtualenvs/pillowenv3/lib/python3.5/site-packages/project-server.egg-link (link to .)
> project-server 1.1.0 is already the active version in easy-install.pth
> Installing project_server-celery script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing project_server-manage script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing project_server-gunicorn script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installed /home/benjamin/archeo/projectserver
> Processing dependencies for project-server==1.1.0
> Searching for Pillow>=2.9.0
> Reading https://pypi.python.org/simple/Pillow/
> Downloading https://pypi.python.org/packages/8d/80/eca7a2d1a3c2dafb960f32f844d570de988e609f5fd17de92e1cf6a01b0a/Pillow-4.0.0.tar.gz#md5=d5af224b0fa2c66dacc9814785fef9e7
> Best match: Pillow 4.0.0
> Processing Pillow-4.0.0.tar.gz
> Writing /tmp/easy_install-1h30lxd9/Pillow-4.0.0/setup.cfg
> Running Pillow-4.0.0/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1h30lxd9/Pillow-4.0.0/egg-dist-tmp-folvyphm
> warning: no files found matching '*.sh'
> no previously-included directories found matching 'docs/_static'
> warning: no previously-included files found matching '.coveragerc'
> warning: no previously-included files found matching '.editorconfig'
> warning: no previously-included files found matching '.landscape.yaml'
> warning: no previously-included files found matching 'appveyor.yml'
> warning: no previously-included files found matching 'build_children.sh'
> warning: no previously-included files found matching 'tox.ini'
> warning: no previously-included files matching '.git*' found anywhere in distribution
> warning: no previously-included files matching '*.pyc' found anywhere in distribution
> warning: no previously-included files matching '*.so' found anywhere in distribution
> Building using 4 processes
> Building using 4 processes
> Building using 4 processes
> Building using 4 processes
> Building using 4 processes
>
> PIL SETUP SUMMARY
> version      Pillow 4.0.0
> platform     linux 3.5.2 (default, Nov 17 2016, 17:05:23)
> [GCC 5.4.0 20160609]
>
>  JPEG support available
> OPENJPEG (JPEG2000) support not available
>  ZLIB (PNG/ZIP) support available
>  LIBIMAGEQUANT support not available
>  LIBTIFF support not available
>  FREETYPE2 support available
>  LITTLECMS2 support not available
>  WEBP support not available
>  WEBPMUX support not available
>
> To add a missing option, make sure you have the required
> library and headers.
> See https://pillow.readthedocs.io/en/latest/installation.html#building-from-source
> 
> To check the build, run the selftest.py script.
> 
> Moving Pillow-4.0.0-py3.5-linux-x86_64.egg to /home/benjamin/.virtualenvs/pillowenv3/lib/python3.5/site-packages
> Adding Pillow 4.0.0 to easy-install.pth file
> Installing explode.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing thresholder.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing pilfile.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing pildriver.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing player.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing createfontdatachunk.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing pilfont.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing painter.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing gifmaker.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing pilconvert.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing enhancer.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing viewer.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> Installing pilprint.py script to /home/benjamin/.virtualenvs/pillowenv3/bin
> 
> Installed /home/benjamin/.virtualenvs/pillowenv3/lib/python3.5/site-packages/Pillow-4.0.0-py3.5-linux-x86_64.egg
> Searching for olefile
> Reading https://pypi.python.org/simple/olefile/
> Downloading https://pypi.python.org/packages/61/f4/7b52981ee0c3c2521c504fa318466136be8d47bc720ef1eff2aa2f193730/olefile-0.43.tar.gz#md5=f570df81ebfab51aaa538af39fef6fd3
> Best match: olefile 0.43
> Processing olefile-0.43.tar.gz
> Writing /tmp/easy_install-1tlpkj95/olefile-0.43/setup.cfg
> Running olefile-0.43/setup.py -q bdist_egg --dist-dir /tmp/easy_install-1tlpkj95/olefile-0.43/egg-dist-tmp-b4i44taa
>   File "build/bdist.linux-x86_64/egg/olefile/olefile2.py", line 225
>     raise ValueError, 'Need to fix a bug with 32 bit arrays, please contact author...'
>                     ^
> SyntaxError: invalid syntax

**Comment by wiredfool** [comment]
If you preinstall olefile, it should work well enough for pillow to install, even though there are parts that aren't working with python 3.x. 

cc @decalage2 Is there a way to prevent olefile2 from parsing on install, or exiting on py3?

**Comment by invenis-paris** [comment]
@wiredfool thanks but this part is in an script I cannot modify easily so i will temporary force pillow version to be <4.0.0

**Comment by hugovk** [comment]
Note there's a pending PR in olefile to drop olefile2 completely, as that is only meant for Python <= 2.5: https://github.com/decalage2/olefile/pull/42

So it shouldn't even be going into olefile2 for Python 3. 

@invenis-paris You could see what exception you're getting from this part (maybe just remove the `try:` and the whole `except:` part, and unindent):

https://github.com/decalage2/olefile/blob/master/olefile/__init__.py#L25-L29

**Comment by decalage2** [comment]
I confirm olefile2 will be removed shortly. It will solve the issue. (once I publish the new version on PyPI)

About the bug, I fixed it in setup.py a while ago by forcing setup not to pre-compile the modules, but only when running "setup.py install" (not develop).

See [setup.py line 244](https://github.com/decalage2/olefile/blob/master/setup.py#L244):

```python
    # when running 'setup.py install', disable the compilation of all python
    # modules, because olefile2.py triggers a syntax error with Python 3.
    # For this, add the option --no-compile to the command-line:
    if 'install' in sys.argv:
        sys.argv.append('--no-compile')
```

=> it is possible to fix it temporarily by testing both install and develop.

**Comment by wiredfool** [comment]
Thanks @decalage2. That does explain why we didn't hit the error in testing.

**Comment by radarhere** [comment]
olefile2 has been removed now, with the release of olefile 0.44. So this problem should now be resolved.
