### ISSUE TITLE
invalid address or address of corrupt block passed to dlfree

### ISSUE THREAD

**Issue by frankgould** [python-pillow/Pillow#2338]
I have been successfully resizing images using pillow except when the image size is unusual, like in a panorama shot.  For instance, when the original image resolution is (1600, 900) and the resize call is to (1366, 767), there's no problem.  But using the same call for an original image at (4572, 900) resized to (1366, 269), it generates "invalid address or address of corrupt block (#) passed to dlfree" error in logcat and crashes the app.  What am I doing wrong?

Below is mycode:
```python
    print 'Original image width: ' + str(tmp_img.size[0]) + ', height: ' + str(tmp_img.size[1]) + ', and aspect ratio: ' + str(aspect_ratio)
    if aspect_ratio < 1:    # Handle picture landscape orientation
        picture_lowest = int(mp_frame.picture_widest * aspect_ratio)
        logger.info('fix_rotate_size: aspect_ratio < 1, aspect_ratio=' + str(aspect_ratio) + ', [picture_widest, picture_lowest]=' + str([mp_frame.picture_widest, picture_lowest]))
        mp_img = tmp_img.resize((mp_frame.picture_widest,picture_lowest), Image.NEAREST)
```
Here is my logcat for the code above when panorama image processed:
I/python  ( 2296): Original image width: 4572, height: 900, and aspect ratio: 0.197
I/python  ( 2296): [INFO   ] [fix_rotate_size] aspect_ratio < 1, aspect_ratio=0.197, [picture_widest, picture_lowest]=[1366, 269]
F/libc    ( 2296): invalid address or address of corrupt block 0x6eba3800 passed to dlfree
F/libc    ( 2296): Fatal signal 11 (SIGSEGV) at 0xdeadbaad (code=1), thread 2312 (SDLThread)

**Comment by wiredfool** [comment]
I'm not seeing it here with a quick test. 

What platform are you on, what versions of Pillow and Python are you running, and can you post the image?

**Comment by frankgould** [comment]
I should have provided more in my original post. Thanks for your response.

**Versions:**
Android 4.4.2
I/python  ( 2700): [INFO   ] [Kivy        ] v1.9.2-dev0
I/python  ( 2700): [INFO   ] [Python      ] v2.7.2 (default, Dec  3 2016, 11:42:45) 
VERSION = '1.1.7'  # PIL version
PILLOW_VERSION = '3.4.2'  # Pillow
![canopy stitch](https://cloud.githubusercontent.com/assets/11017534/21679117/3435ed3c-d310-11e6-9170-d42f8e8a8da0.jpg)

**Comment by wiredfool** [comment]
Unfortunately, Android is not a supported platform. While Pillow may work there, (and we've had a couple reports of success) we don't have the ability to build, test or debug on it.

**Comment by wiredfool** [comment]
This doesn't trigger any errors here, so it's likely a platform difference with memory management. To track it down is going to require being able to build pillow binaries for your platform and an ability to debug the C layer. 

The first thing I'd do is get it down to a small test script, similar to:
```
from PIL import Image
im = Image.open('issue_2338.jpg')
im2 = im.resize((1366,269), Image.NEAREST)
```

Run that under gdb (or whatever android's debugger is), get a stack trace of the failure. More than likely you're going to want to get (at least) debug symbols or a non-optimized build so that the stack trace makes some sense compared to the C code. 

From there, it's going to be a matter of figuring out why there's a bad pointer getting passed to free.
