### ISSUE TITLE
ImageFont incompatible with harfbuzz 1.4.1

### ISSUE THREAD

**Issue by markubiak** [python-pillow/Pillow#2346]
### What did you do?
Update harfbuzz to 1.4.1

### What did you expect to happen?
Nothing

### What actually happened?
I got a  
```
Traceback (most recent call last):
  File "/usr/bin/wallpaper-reddit", line 11, in <module>
    load_entry_point('wallpaper-reddit==3.0.2', 'console_scripts', 'wallpaper-reddit')()
  File "/usr/lib/python3.6/site-packages/wpreddit/main.py", line 40, in run
    download.download_image(valid_url, title)
  File "/usr/lib/python3.6/site-packages/wpreddit/download.py", line 23, in download_image
    img = set_image_title(img, title)
  File "/usr/lib/python3.6/site-packages/wpreddit/download.py", line 38, in set_image_title
    font = ImageFont.truetype(config.walldir + '/fonts/Cantarell-Regular.otf', size=config.titlesize)
  File "/usr/lib/python3.6/site-packages/PIL/ImageFont.py", line 238, in truetype
    return FreeTypeFont(font, size, index, encoding)
  File "/usr/lib/python3.6/site-packages/PIL/ImageFont.py", line 127, in __init__
    self.font = core.getfont(font, size, index, encoding)
  File "/usr/lib/python3.6/site-packages/PIL/ImageFont.py", line 37, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
ImportError: The _imagingft C module is not installed
```
whenever I tried to use the ImageFont module.  Further inspection  resulted in this error:  
``ImportError: /usr/lib/libharfbuzz.so.0: undefined symbol: FT_Get_Var_Blend_Coordinates``
Downgrading harfbuzz to 1.3.4 temporarily solves the issue.  

### What versions of Pillow and Python are you using?
Python 3.6, Pillow 4.0.0

Seems pretty straight forward, Pillow was using a function in harfbuzz that got moved/removed/renamed in the upgrade to 1.4.1.

**Comment by aclark4life** [comment]
@markubiak What is harfbuzz?

**Comment by markubiak** [comment]
https://github.com/behdad/harfbuzz

It's described as an "OpenType text shaping engine".  It seems to be linked by ImageFont.

**Comment by wiredfool** [comment]
We don't use/link it yet, except for a pending pr for drawing complex text.

**Comment by khaledhosny** [comment]
Might be the same issues as https://github.com/baedert/corebird/issues/663 (and several other similar reports from people using the unofficial FreeType infinality patches on Arch Linux).

**Comment by markubiak** [comment]
I was actually using the unofficial infinality patches on Arch.  I uninstalled them and the issue was resolved, so I am closing the issue.  Apologies for the erroneous bug report, and congrats on the release of 4.0 (which has otherwise been working perfectly so far by the way).
