### ISSUE TITLE
Secret teams public?

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#2350]
I'm not sure why our teams are secret, but just wanted to verify no one cares if I make them all public? I assume individuals can still maintain their privacy if they want.

<img width="1000" alt="screenshot 2017-01-10 10 06 32" src="https://cloud.githubusercontent.com/assets/72164/21811199/d32ebf76-d71c-11e6-8c14-e8dedc59b72f.png">
<img width="1023" alt="screenshot 2017-01-10 10 07 56" src="https://cloud.githubusercontent.com/assets/72164/21811200/d32f88f2-d71c-11e6-976a-8a54b3f1c0a4.png">

**Comment by wiredfool** [comment]
I'm pretty sure that everyone listed is pretty obvious from their contributions in the repos. 

(and, umm, not to mention this issue)

**Comment by aclark4life** [comment]
Cool, done!
