### ISSUE TITLE
GimpGradientFile.py License Info?

### ISSUE THREAD

**Issue by Alex-Vaduva** [python-pillow/Pillow#2353]
In GimpGradientFile.py it is stated that:
"# Stuff to translate curve segments to palette values (derived from
"# the corresponding code in GIMP, written by Federico Mena Quintero.
"# See the GIMP distribution for more information.)

Can you give more info about this statement? The code from GIMP what license did it have?
Thanks.

**Comment by wiredfool** [comment]
It's part of the original import from PIL, and from the changelog, it appears to date to 1997:
https://github.com/python-pillow/Pillow/blob/9a640e3157150e35f17354517e8c6304fc428060/PIL/GimpGradientFile.py

It's archaeology past this point.

**Comment by wiredfool** [comment]
'You' in this case is Fredrik, 20 years ago.  I don't know if this is a copy, translation, or reimplementation based on the functionality of the code from GIMP, or if there was any discussion between Fredrik and Federico at the time. 

Is Federico Mena Quintero complaining about this?

**Comment by Alex-Vaduva** [comment]
Well no...not from my knowledge but here is the problem, or at least how I see it:
because the code that was written by Federico is licensed under GPL and because the file GimpGradientFile.py doesn't mention that the code was taken from GPL that doesn't mean that GPL is not valid. On the contrary. Therefore your code has a violation from a legal point of view.
Therefore at any point Federico can come and complain. I just want to respect all the licenses which apply on a code and I don't want any problems in the future.
If instead Federico and Fredrik have a agreement, then it should be listed. Or maybe only Fredrik is allowed to use the code from Federico and the rest of us no. As you can see there can be many scenario.

So to resume can you discuss with Fredrik to see what he discussed with Federico in 1997 or if they even discussed at all?

**Comment by wiredfool** [comment]
> So to resume can you discuss with Fredrik to see what he discussed with Federico in 1997 or if they even discussed at all?

Effectively, no. We haven't heard from him in ~ 5 years. Pillow is picking up essentially abandoned code. 

I understand the GPL and your concerns. 

IFF the code was copied from GIMP, then there could be an issue, and whoever held the copyright in 1997 could raise the issue of a copyright violation. IF the PIL code was implemented using the algorithms from the code as documentation, then it's not a license or copyright violation. It's a reverse engineered implementation. 

It appears from poking around that the release and file in question is from gimp-0.99.31, app/gradient.c, and the calculations are essentially straight from that file. 

```
def linear(middle, pos):
    if pos <= middle:
        if middle < EPSILON:
            return 0.0
        else:
            return 0.5 * pos / middle
    else:
        pos = pos - middle
        middle = 1.0 - middle
        if middle < EPSILON:
            return 1.0
        else:
            return 0.5 + 0.5 * pos / middle


def curved(middle, pos):
    return pos ** (log(0.5) / log(max(middle, EPSILON)))


def sine(middle, pos):
    return (sin((-pi / 2.0) + pi * linear(middle, pos)) + 1.0) / 2.0


def sphere_increasing(middle, pos):
    return sqrt(1.0 - (linear(middle, pos) - 1.0) ** 2)


def sphere_decreasing(middle, pos):
    return 1.0 - sqrt(1.0 - linear(middle, pos) ** 2)
```

vs:
```
static double
calc_linear_factor(double middle, double pos)
{
	if (pos <= middle) {
		if (middle < EPSILON)
			return 0.0;
		else
			return 0.5 * pos / middle;
	} else {
		pos -= middle;
		middle = 1.0 - middle;

		if (middle < EPSILON)
			return 1.0;
		else
			return 0.5 + 0.5 * pos / middle;
	} /* else */
} /* calc_linear_factor */


/*****/

static double
calc_curved_factor(double middle, double pos)
{
	if (middle < EPSILON)
		middle = EPSILON;

	return pow(pos, log(0.5) / log(middle));
} /* calc_curved_factor */


/*****/

static double
calc_sine_factor(double middle, double pos)
{
	pos = calc_linear_factor(middle, pos);

	return (sin((-M_PI / 2.0) + M_PI * pos) + 1.0) / 2.0;
} /* calc_sine_factor */


/*****/

static double
calc_sphere_increasing_factor(double middle, double pos)
{
	pos = calc_linear_factor(middle, pos) - 1.0;

	return sqrt(1.0 - pos * pos); /* Works for convex increasing and concave decreasing */
} /* calc_sphere_increasing_factor */


/*****/

static double
calc_sphere_decreasing_factor(double middle, double pos)
{
	pos = calc_linear_factor(middle, pos);

	return 1.0 - sqrt(1.0 - pos * pos); /* Works for convex decreasing and concave increasing */
} /* calc_sphere_decreasing_factor */
```

If there's really a problem, I'd just drop the file, because the PIL license and GPL are not really compatible. 

pinging @federicomena on twitter about this.

**Comment by federicomenaquintero** [comment]
I have no problem with that code being translated to Python.  Go for it!

**Comment by wiredfool** [comment]
@federicomenaquintero 

To be absolutely clear -- This has been in PIL under the PIL license, which is not the GPL for the past 20 years. (It's more MIT like).  Is that de facto relicensing ok?

**Comment by federicomenaquintero** [comment]
Yes, it's OK.

**Comment by wiredfool** [comment]
Thank you.
