### ISSUE TITLE
Prevent hanging file pointers for Image

### ISSUE THREAD

**Issue by condemil** [python-pillow/Pillow#2361]
### What did you do?
Opened image (using with statement) and get pixel values out of it

### What did you expect to happen?
File pointer of opened image will be closed

### What actually happened?
File pointer of opened image is not closed

### What versions of Pillow and Python are you using?
Pillow 4.0.0
Python 3.5.2

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

```python
import warnings
from PIL import Image

warnings.simplefilter('default')

with Image.open('test.png') as image:
    image.getdata()
```

```
/tmp/test.py
/Users/user/envs/tryouts/lib/python3.5/site-packages/PIL/Image.py:1153: ResourceWarning: unclosed file <_io.BufferedReader name='test.png'>
  self.load()

Process finished with exit code 0
```

**Comment by condemil** [comment]
Related to #2019

**Comment by hugovk** [comment]
This was fixed by https://github.com/python-pillow/Pillow/pull/2032 (in https://github.com/python-pillow/Pillow/pull/2330).

The test code gives no warning for me with Python 2.7.13 and 3.6.0 on macOS Sierra:
```python
import warnings
from PIL import Image

warnings.simplefilter('default')

with Image.open('test.png') as image:
    image.getdata()
```
