### ISSUE TITLE
TIFFFillStrip: Read error at scanline 

### ISSUE THREAD

**Issue by GISkschultz** [python-pillow/Pillow#2364]
I have this code

```python
from PIL import Image, ImageFile

import os
size = 3300, 5100
tag =""
directory = "C:\\\\Users\\kschultz\\Desktop\\streets\\"
error = 0
countError =0
for dirname, dirnames, filenames in os.walk(directory):
  print(dirname)
  for file in os.listdir(dirname):
    if file.endswith(('.tif', '.TIF')) or file.endswith(('.TIFF', '.tiff')) :
        if os.path.isfile(os.path.splitext(os.path.join(dirname, file))[0] + ".jpg"):
            print "A jpeg file already exists for %s" % file
        else:
            outfile = os.path.splitext(os.path.join(dirname, file))[0] + ".jpg"
            try:
                ImageFile.LOAD_TRUNCATED_IMAGES = True
                im = Image.open(os.path.join(dirname, file))
                print "Generating jpeg for %s" % file
                print(im.size)
                im.thumbnail(size)
                im.save(outfile, "JPEG", quality=75)
            except Exception, IOError:
                print IOError


```
It is suppose to scan a directory and convert all TIFF images to jpeg

It does this for the majority but occasionally I get back an error like these

> TIFFFillStrip: Read error at scanline 4294967295; got 1999675 bytes, expected 2289636.

> TIFFFillStrip: Read error at scanline 4294967295; got 510923 bytes, expected 510924.

> TIFFFillStrip: Read error at scanline 4294967295; got 478037 bytes, expected 478038.

Which results in the image failing to be converted to jpeg.

I'm using python 2.7.12 and I couldnt find the PIL version but I installed it with the command line
 pip install pil 

so I'm assuming its the latest version?

**Comment by hugovk** [comment]
You can check what version you have with "pip freeze".

You shouldn't use PIL, which is really old, but Pillow instead.

First, make sure you have the prerequisites for your OS, see http://pillow.readthedocs.io/en/4.0.x/installation.html

Then:

pip uninstall pil
pip install pillow

And then try your code again.

**Comment by GISkschultz** [comment]
I just did this and I'm still getting the same error, pillow is running at version 4.0

**Comment by wiredfool** [comment]
That sounds like an error from libtiff, so it's highly unlikely that it's from PIL vs Pillow. It sounds like libtiff is complaining about a corrupt image.  (that's scanline 0xFFFFFFFF, which is a known suspicious value).

**Comment by GISkschultz** [comment]
Is there anyway to bypass this? So I can convert the tiff image to jpeg.  I checked the images that are in question and all can be opened.

**Comment by wiredfool** [comment]
Post an image and I'll take a look.
