### ISSUE TITLE
empty transparent image saved as black

### ISSUE THREAD

**Issue by 3lixy** [python-pillow/Pillow#2366]
I am trying to make a fully transparent image using Pillow in Python
```python
img2 = PILImage.new('RGBA', (1920, 1080), (0,0,0,0))
img2.save('test.png')
```
The above code generates test.png a black image not a fully transparent image:

The above code was created referencing: https://pillow.readthedocs.io/en/4.0.x/reference/Image.html#constructing-images

> PIL.Image.new(mode, size, color=0)
> 
> color – What color to use for the image. Default is black. If given, this should be a single integer or floating point value for single-band modes, and a tuple for multi-band modes (one value per band). When creating RGB images, you can also use color strings as supported by the ImageColor module. If the color is None, the image is not initialised.

https://pillow.readthedocs.io/en/4.0.x/handbook/concepts.html#concept-modes

> `RGBA` (4x8-bit pixels, true color with transparency mask)

System info:
```bash
$ pip2.7 freeze | grep -i pillow
Pillow==4.0.0

$ python2.7 -V
Python 2.7.9

$ apt list --installed | grep -i imagemagick    
imagemagick/stable,now 8:6.8.9.9-5+deb8u6 amd64 [installed]
imagemagick-6.q16/stable,now 8:6.8.9.9-5+deb8u6 amd64 [installed,automatic]
imagemagick-common/stable,now 8:6.8.

$ convert --version
Version: ImageMagick 6.8.9-9 Q16 x86_64 2016-11-26 http://www.imagemagick.org

$ uname -a
Linux revo-vpn-74 3.16.0-4-amd64 #1 SMP Debian 3.16.36-1+deb8u2 (2016-10-19) x86_64 GNU/Linux

$ cat /etc/*release
PRETTY_NAME="Debian GNU/Linux 8 (jessie)"
NAME="Debian GNU/Linux"
VERSION_ID="8"
VERSION="8 (jessie)"
ID=debian
HOME_URL="http://www.debian.org/"
SUPPORT_URL="http://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"
```

**Comment by hugovk** [comment]
It's working for me (macOS Sierra / Python 2.7.13 / Pillow 4.0.0) (note the import and `Image.new` instead of `PILImage.new`):
```python
from PIL import Image
img2 = Image.new('RGBA', (1920, 1080), (0,0,0,0))
img2.save('test.png')
```
---
![test](https://cloud.githubusercontent.com/assets/1324225/22125266/b5061d10-de9b-11e6-910e-c071363b50b5.png)
---

Here's one without transparency:
```python
img3 = Image.new('RGB', (1920, 1080), (0,0,0))
img3.save("test3.png")
```
---
![test3](https://cloud.githubusercontent.com/assets/1324225/22125318/df4341fc-de9b-11e6-9252-cd20b35f6f5d.png)
---

**Comment by 3lixy** [comment]
I am using the below to import. my class is not helpfully named Image. I will probably change it later.

```
from PIL import Image as PILImage
from PIL import ImageDraw as PILImageDraw
from PIL import ImageFont as PILImageFont

log = logging.getLogger(__name__)

class Image(object):

    img2 = PILImage.new('RGBA', (1920, 1080), (0,0,0,0))
    img2.save('test.png')
```
You think it is an environment issue?

If I put text or alpha_composite with img2 the transparent is as expected. Its only when I make a fully transparent image that is is saved as black. I don't actually need it at the moment. It just thew me as that was my first test to see if transparency would work if I created a new image within pillow and not start from a fully transparent png.

**Comment by hugovk** [comment]
Please can you create a new script in /tmp with just this, and run it from there?
```python
from PIL import Image

img2 = Image.new('RGBA', (1920, 1080), (0,0,0,0))
img2.save('test.png')

img3 = Image.new('RGB', (1920, 1080), (0,0,0))
img3.save("test3.png")

**Comment by 3lixy** [comment]
Yup that works as expected.

test.png > fully transparrent
test3.png > fully black

Has to be something I am doing in the code.

**Comment by Tjorriemorrie** [comment]
FYI: On my mac when using `img.show()` it is shown as black in Preview, but the saved img is transparent when opened afterwards in Preview. Is it missing meta with `show()`?

**Comment by wiredfool** [comment]
Show uses PPM, which is a quick, simple format that is guaranteed to exist, but doesn't support transparency.

**Comment by ThatOneCalculator** [comment]
> Please can you create a new script in /tmp with just this, and run it from there?
> 
> ```python
> from PIL import Image
> 
> img2 = Image.new('RGBA', (1920, 1080), (0,0,0,0))
> img2.save('test.png')
> 
> img3 = Image.new('RGB', (1920, 1080), (0,0,0))
> img3.save("test3.png")
> ```

Not sure if this has come back but I've repeated the steps for test.png and it still shows up as black. Arch Linux, Python 3.8.
