### ISSUE TITLE
Pillow and Numpy, getting pixel values

### ISSUE THREAD

**Issue by adammenges** [python-pillow/Pillow#2370]
For some reason

```python
im_data = np.array(im.getdata()).reshape(im.size[0], im.size[1], 3)
p1 = im.getpixel((i, j))
p2 = im_data[i, j]
```

p1 and p2 are the same rgb values most of the time, except when they're not. Any idea why?

**Comment by wiredfool** [comment]
Do you have an example?

**Comment by adammenges** [comment]
Ah, `im.getdata()` wasn't giving me what I thought it was. 

```python
im_data = np.array(im.getdata()).reshape(im.size[1], im.size[0], 3)
p1 = im.getpixel((i, j))
p2 = im_data[j, i]
```

Now p1 and p2 are always the same. Maybe some more information in the docs could be helpful. How can I contribute?

**Comment by hugovk** [comment]
The source of the docs at https://pillow.readthedocs.io/en/ can be found under https://github.com/python-pillow/Pillow/tree/master/docs.

Some general contributing info: https://github.com/python-pillow/Pillow/blob/master/.github/CONTRIBUTING.md

**Comment by adammenges** [comment]
Thanks
