### ISSUE TITLE
Release Pillow 4.1.0 on April 1, 2017

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2373]
This is the release thread for 4.1.0, scheduled for 2017-04-01. 

I'd like to have a couple of goals for this release. 

1) I'd like to cover all of the image formats that we supposedly support with tests for correctness of loaded (/saved) images, or have a loud warning that this is untested code, either in code or docs. There have been three cases in the last few months where I've opened the hood on a file format or a feature and found it nearly untested and/or broken. (Sun RLE was broken, SGI raster files only tested that we rejected unsupported compression, and ImageTk has never had tests where we loaded the tk interpreter.)  I'd like to not need the "Hasn't worked in 20 years" tag anymore. 

 - [x] BufrStubImagePlugin: https://github.com/python-pillow/Pillow/pull/2441
 - [x] ContainerIO: https://github.com/python-pillow/Pillow/pull/2443
 - [x] FitsStubImagePlugin: https://github.com/python-pillow/Pillow/pull/2430
 - [ ] GdImagePlugin: https://github.com/python-pillow/Pillow/pull/1817
 - [x] GribStubImagePlugin: https://github.com/python-pillow/Pillow/pull/2440
 - [x] Hdf5StubImagePlugin: https://github.com/python-pillow/Pillow/pull/2431
 - [x] MspImagePlugin: #1938 (#2384)
 - [x] PixarImagePlugin: #2428 
 - [x] PsdImagePlugin: https://github.com/python-pillow/Pillow/pull/2427
 - [x] XVThumbImagePlugin: https://github.com/python-pillow/Pillow/pull/2442
 - [ ] FPXImagePlugin
 - [ ] BitDecode.c
 - [ ] McIdasImagePlugin.py
 - [ ] MicImagePlugin.py
 - [ ] IptcImagePlugin.py (load is never tested)

2) Finish several longstanding issues -- File Closing, Palette, and Tiff Metadata handling come to mind. 

 - [x] File closing #2330
 - [ ] Palette
 - [ ] Tiff metadata

3) Refactor the mess that is GifImagePlugin. 

 - [x] GifImagePlugin

**Comment by wiredfool** [comment]
For point 1, just from the review of #2425:
 - BufrStubImagePlugin
 - ContainerIO
 - FitsStubImagePlugin
 - GribStubImagePlugin
 - Hdf5StubImagePlugin
 - PixarImagePlugin
 - PsdImagePlugin
 - XVThumbImagePlugin

**Comment by hugovk** [comment]
For point 1, from #1817:
 * [ ] GdiImagePlugin

(I've also turned the previous comment's bullets into checkboxes.)

**Comment by wiredfool** [comment]
Release notes for #2374

**Comment by radarhere** [comment]
Would anyone like to merge PRs in pillow-wheels before the release?

**Comment by hugovk** [comment]
@radarhere Done!

**Comment by radarhere** [comment]
@hugovk thanks!

**Comment by wiredfool** [comment]
[ ] Blocking issue, at least to determine if it's right or not: https://github.com/python-pillow/Pillow/commit/977f3192349282ae1a7108102415a7ad1baaa305#commitcomment-21546844

I propose we slip the release till Monday:
1) I don't have enough time today
2) April Fools is a bad day to release software.
3) Avoiding weekends.

**Comment by wiredfool** [comment]
I've triaged, there are 2 prs that are almost there, just needing to pass windows tests, and one that I think has probably been fixed with an unrelated change. 

Other than that, nothing big, anything small had better not break anything.

**Comment by hugovk** [comment]
Re: https://github.com/python-pillow/Pillow/commit/977f3192349282ae1a7108102415a7ad1baaa305#commitcomment-21546844

Confirmed in [code](https://github.com/python-pillow/Pillow/search?l=Python&q=dpi&type=&utf8=%E2%9C%93) and [docs](https://pillow.readthedocs.io/en/4.0.x/handbook/image-file-formats.html?highlight=dpi#jpeg):

> The `open()` method may set the following info properties if available:
> ...
> **dpi**
> A tuple representing the reported pixel density in pixels per inch, if the file is a jfif file and the units are in inches.

I'll make a new PR.

**Comment by aclark4life** [comment]
@wiredfool Since you are doing all (or most of) the work, Monday is fine with me :smile: though I'll reiterate in general, I don't like to change the release schedule if we can help it. Also for whatever it's worth, "no time" is certainly a valid cause to delay, but "April fool's & weekends" is not IMO; I'm fairly happy with the quarterly release schedule, despite one of the quarters beginning with April 1.

**Comment by wiredfool** [comment]
I've merged the three PRs that were aimed at this release.  Running out of time here, and I've just buried all the CI machines. 

I've got a 4.1.0 release, it's in the 4.1.x branch. 
* CI is running on it, in it's potentially releasable state
* The wheel CI is running on it, and may be released if everything is green. 

The release is _not_ tagged, so if there's something that would be a x.x.1, there's still time to get it in while it's still a .0.  

If we're good, I'll tag and release at some point tomorrow when it's morning in @cgohlke's timezone.

To Go:
* [ ] tag && push tag
* [ ] pull 4.1.x into master
* [ ] upload source - .tar.gz
* [ ] upload osx/linux wheels
* [ ] upload win binaries

**Comment by hugovk** [comment]
Few little release note things: PR https://github.com/python-pillow/Pillow/pull/2474

**Comment by wiredfool** [comment]
Manylinux wheels for x64 appear to be broken due to rpm repo urls not being available. It was working as recently as 9 days ago, when Hugo pushed some changes.

**Comment by wiredfool** [comment]
Wheel issue explained here: https://github.com/pypa/manylinux/issues/100

**Comment by wiredfool** [comment]
Ok, Tagged and released.  Manylinux wheels will be delayed until the centos thing is worked out. 

pinging @cgohlke

**Comment by cgohlke** [comment]
Here you go http://www.lfd.uci.edu/~gohlke/download/Pillow-4.1.0.win-dist.zip#md5=53069f4e0a0fe3dfce3ead9a04458933

**Comment by wiredfool** [comment]
Thanks @cgohlke

**Comment by cgohlke** [comment]
Re pypy wheel: I had to remove `install_requires` from setup.py to build the pypy wheel due to a bug somewhere in pypy/setuptools/wheel. So `olefile` needs to be installed separately for now on pypy. Also, `TestEmbeddable` should be disabled when running on pypy.
