### ISSUE TITLE
set random seed

### ISSUE THREAD

**Issue by edgarriba** [python-pillow/Pillow#2390]
hi! is it possible to set the random seed?
I've noticed that after calling resize method I got different results.

**Comment by hugovk** [comment]
### What did you do?

### What did you expect to happen?

### What actually happened?

### What versions of Pillow and Python are you using?

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```
