### ISSUE TITLE
Pillow 3.4.2 is not available as a pre-compiled Python 3.6 version for Windows

### ISSUE THREAD

**Issue by aleksihakli** [python-pillow/Pillow#2391]
### What did you do?

Tried to install Pillow 3.4.2 from old project requirements after upgrading Python to Win32 3.6.0

### What did you expect to happen?

A smooth installation.

### What actually happened?

Compilation from source and failure to install due to missing requirements.

### What versions of Pillow and Python are you using?

    $ python --version
    Python 3.6.0
    $ cat requirements.txt|grep pillow
    Pillow==3.4.2             # via django-versatileimagefield

**Comment by hugovk** [comment]
Python 3.6.0 was released December 2016.

Pillow 3.4.2 was released in October 2016, and didn't include Python 3.6 wheels/binaries. 

Building from source is a pain on Windows, can you use Pillow 4.0.0 (January 2017) instead? It's the next release after 3.4.2 and has Pillow 3.6.0 wheels for Windows.

**Comment by aleksihakli** [comment]
@hugovk With the component we use Pillow 4.0.0 works beautifully:

https://github.com/respondcreate/django-versatileimagefield/pull/86

Releasing older version binaries is of course up to you, but the wheels would make it considerably easier for people with limited capacity for building the custom binaries to work with Python 3.6.0 and Pillow 3.4.2 combo.

We have some ongoing reasearch in another FOSS project on compiling Python binaries in a free-to.-use Windows CI service for different projects. I'll ping you back if we have the time to make some project templates that have different stock Microsoft VCC compiled and Windows redistributable binaries - I think those could really help in producing these wheels as well :) I know the pain included.

**Comment by wiredfool** [comment]
If you're going to do the validation work to upgrade Python versions, I think it's reasonable to do the validation work to upgrade to Pillow 4.0.0 as well.
