### ISSUE TITLE
Png interlaced output

### ISSUE THREAD

**Issue by Lucuz91** [python-pillow/Pillow#2393]
Hello guys,
I See That Pillow supports PNG interlaced in input but not on input output. Is there a way to create a PNG interlaced with Pillow?
GIMP and Photoshop have this option and is very useful for web, the picture is render first, and with a good quality without downloading it Entirely.

![interlaced](https://cloud.githubusercontent.com/assets/18615313/22650923/6a70a560-ec81-11e6-97f4-beb3dca737a8.PNG)

This is a example of web improve with jpeg https://www.youtube.com/watch?v=TOc15-2apY0.

Convert a PNG to JPEG is not accepted because JPEG does not support transparency, useful in different cases.

Is there any solution?

**Comment by wiredfool** [comment]
No, saving interlaced PNGs is not implemented. 

PRs would be accepted.
