### ISSUE TITLE
Creating a multiframe image object

### ISSUE THREAD

**Issue by blochl** [python-pillow/Pillow#2401]
Hi!

* I know that the ```save_all=True``` option saves all the frames of the image object for supported formats.
* I know that opening a multiframe image of a supported format creates a multiframe image object.

But how to create a new multiframe image object? Say from a 3D Numpy array? ```Image.fromarray``` accepts only 2D arrays...

Thanks!
Leonid.

**Comment by radarhere** [comment]
You can create a series of single frame images, and then combine them using `append_images` - https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/3.4.0.rst#append-images-to-gif

**Comment by blochl** [comment]
Hi, thanks for your answer. But it does not seem to work.
Code example:
```python
import numpy as np
from PIL import Image
a = np.random.rand(100,100,100)
a = ((a - a.min())/(a.max() - a.min()) * 255).astype(np.uint8)
imlist = []
for m in a:
    imlist.append(Image.fromarray(m))

imlist[0].save("test.tif", save_all=True, compression="tiff_deflate",
               append_images=imlist[1:])
```
Expected results: a 100-frame tiff.
Actual results: 1-frame tiff.

**Comment by radarhere** [comment]
`append_images` is currently available only for GIF. Changing that, your example works for me.

**Comment by blochl** [comment]
But is there currently a way to save multiframe tiffs (tiff image stacks) in Pillow?

**Comment by radarhere** [comment]
You may not like this answer.

    import numpy as np
    from PIL import Image
    a = np.random.rand(100,100,100)
    a = ((a - a.min())/(a.max() - a.min()) * 255).astype(np.uint8)
    imlist = []
    for m in a:
        imlist.append(Image.fromarray(m))

    # By saving it as a GIF and then opening it and saving it as a TIFF
    imlist[0].save("test.gif", save_all=True, append_images=imlist[1:])
    Image.open("test.gif").save("test.tif", save_all=True)
    print(Image.open("test.tif").n_frames) #  100

    # To improve this somewhat, it can be done using BytesIO
    import io
    output = io.BytesIO()
    imlist[0].save(output, format="GIF", save_all=True, append_images=imlist[1:])
    Image.open(output).save("test.tif", save_all=True)
    print(Image.open("test.tif").n_frames) #  100

**Comment by martmists** [comment]
Same result happens here, even though I'm trying to save to a .gif
when I print a list of frames to console:
<img src="https://light-theme-hurts.my-ey.es/234b48.png">
```python
print(frames)  # shown above
frames[0].save("file.gif", save_all=True, append_images=frames)
```
Output however, is a single frame gif

**Comment by radarhere** [comment]
@martmists this doesn't output 100 for you?

    import numpy as np
    from PIL import Image
    a = np.random.rand(100,100,100)
    a = ((a - a.min())/(a.max() - a.min()) * 255).astype(np.uint8)
    imlist = []
    for m in a:
        imlist.append(Image.fromarray(m))

    imlist[0].save("test.gif", save_all=True, append_images=imlist[1:])
    print(Image.open("test.gif").n_frames)

**Comment by martmists** [comment]
<img src="https://light-theme-hurts.my-ey.es/b018cd.png">

**Comment by radarhere** [comment]
@martmists what version of Pillow are you using?

    import PIL
    print(PIL.__version__)

**Comment by martmists** [comment]
```py
>>> import PIL
>>> PIL.__version__
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: module 'PIL' has no attribute '__version__'
```Quite the unusual error

**Comment by martmists** [comment]
According to pip it's 3.3.1

**Comment by radarhere** [comment]
Thanks. This makes sense, as `append_images` was added in Pillow 3.4. So I recommend that you upgrade.

**Comment by martmists** [comment]
Updating seems to have fixed it 👌

**Comment by blochl** [comment]
Made a pull request that will allow to export directly to tiffs: #2404
I realize that it might be quick and dirty (with copying the ```encoder{info,config}``` stuff) but that is what I could come up with in the short time I had. Still I think it's better than _via_ a GIF... :)
Will be glad to hear fixes/suggestions.
