### ISSUE TITLE
ICO Conversion saved at lowest size (16x16) creating pixel artifacts

### ISSUE THREAD

**Issue by vantler** [python-pillow/Pillow#2405]
### What did you do?

Made some png to ico conversion.

### What did you expect to happen?

The ico size should've been the same as the original png image. 

### What actually happened?

Original png image: http://i.imgur.com/Sfdhm9C.png
![image](https://cloud.githubusercontent.com/assets/1324225/23015528/e20ce2e8-f43b-11e6-841e-344ef32389b0.png)
Converted icons were saved at 16x16: http://i.imgur.com/CYUqAfg.png
![image](https://cloud.githubusercontent.com/assets/1324225/23015513/cbef672e-f43b-11e6-961d-75474cde5485.png)
Creating black pixel artifacts: http://i.imgur.com/QBt3Bjf.png
![image](https://cloud.githubusercontent.com/assets/1324225/23015524/d99c5df0-f43b-11e6-835f-3cbe4761a926.png)

### What versions of Pillow and Python are you using?

Pillow version 4.0.0
Python version 3.5.2

```python
from PIL import Image
 
png = Image.open('D:\\Downloads\\Canary_2.png')
png.save('D:\\Downloads\\Canary_2.ico')
ico = Image.open('D:\\Downloads\\Canary_2.ico')
 
print(ico.info['sizes'])
```

**Comment by hugovk** [comment]
With macOS Sierra, Python 2.7.13 and Pillow 4.0.0 I get these sizes:

`set([(64, 64), (16, 16), (256, 256), (24, 24), (32, 32), (128, 128), (48, 48)])`

ImageMagick gives:
```bash
$ identify Canary_2.ico
Canary_2.ico[0] PNG 16x16 16x16+0+0 8-bit sRGB 40.2KB 0.010u 0:00.000
Canary_2.ico[1] PNG 24x24 24x24+0+0 8-bit sRGB 40.2KB 0.010u 0:00.009
Canary_2.ico[2] PNG 32x32 32x32+0+0 8-bit sRGB 40.2KB 0.010u 0:00.009
Canary_2.ico[3] PNG 48x48 48x48+0+0 8-bit sRGB 40.2KB 0.010u 0:00.009
Canary_2.ico[4] PNG 64x64 64x64+0+0 8-bit sRGB 40.2KB 0.010u 0:00.009
Canary_2.ico[5] PNG 128x128 128x128+0+0 8-bit sRGB 40.2KB 0.010u 0:00.009
Canary_2.ico[6] PNG 256x256 256x256+0+0 8-bit sRGB 40.2KB 0.010u 0:00.009
```

Here's the output image I get, which when opened in Preview shows the seven sizes without any obvious artefacts: [2405.zip](https://github.com/python-pillow/Pillow/files/779592/2405.zip)

What sizes do you get? Please can you upload the output image?

**Comment by hugovk** [comment]
I get the same results with Windows 7, Python 2.7.11 and Pillow 4.0.0: the output files are identical.

But Windows file properties show the same 16x16 and artefacts in the preview:

![image](https://cloud.githubusercontent.com/assets/1324225/23015599/1f1d6f90-f43c-11e6-871a-9d0b7ef4350f.png)

**Comment by vantler** [comment]
My output file: 
[Canary_2.zip](https://github.com/python-pillow/Pillow/files/779773/Canary_2.zip)

On icofx: http://i.imgur.com/ii8dzgm.png

I forgot to note that the artefacts are only visible on preview but the embedded images itself are fine.

**Comment by hugovk** [comment]
So, revisiting this, it looks like Windows has decided to show a low-resolution image there, and it's a bit rubbish at resizing it without artefacts.

Your best bet is creating icons that don't have small sizes in them, and you can tell Pillow what sizes you do want.

So for example, the smallest that looked fine in properties is 128x128:

```python
from PIL import Image

png = Image.open('Canary_2.png')
png.save('Canary_2.ico', sizes=[(256, 256), (128, 128)])
ico = Image.open('Canary_2.ico')

print(ico.info['sizes'])
```

Gives this (showing 128x128 under Details):
```
set([(256, 256), (128, 128)])
```
![image](https://cloud.githubusercontent.com/assets/1324225/24926823/92418d14-1f05-11e7-9d3b-b24e44671e33.png)

**Comment by hugovk** [comment]
Hope that suggestion works for you. Closing this, can re-open if necessary.
