### ISSUE TITLE
PSF Grant 2

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#2407]
### What did you do?

Asked PSF to pay for python-pillow.org

### What did you expect to happen?

PSF to pay for python-pillow.org

### What actually happened?

PSF offered to take over python-pillow.org

### More Information

Similar to #61, with [grant proposal 2](https://github.com/python-pillow/grant-proposal2), I've asked the PSF to pay for the next 8 years of domain renewals for ``python-pillow.org``. Not surprisingly, in response they offered to take over the domain. While I definitely appreciate their offer, I'm not quite ready to give up the domain and since I've just renewed it, I'm going to take some time to think about it and track thoughts/opinions here.

**Comment by radarhere** [comment]
I'll note that according to WHOIS, the domain is currently registered until the 4th of February 2018. So that may have anyone reading this to understand the time frame involved.
