### ISSUE TITLE
Add repo topics/tags

### ISSUE THREAD

**Issue by Metallicow** [python-pillow/Pillow#2408]
Please add topics(what github calls them)/tags(what I call them).
https://github.com/blog/2309-introducing-topics

python, pil, pillow, cross-platform

...etc... and any others that would seem appropriate there.

**Comment by aclark4life** [comment]
Done, feel free to suggest more as you think of them, thanks.

<img width="593" alt="screenshot 2017-02-18 15 43 55" src="https://cloud.githubusercontent.com/assets/72164/23096758/1e9be6c6-f5f1-11e6-94b2-19cebb0d8004.png">
