### ISSUE TITLE
Questions about license

### ISSUE THREAD

**Issue by Ya2s** [python-pillow/Pillow#2416]
Hello,

I read the license but I have always a doubt :

Have I to mentione the authors name in my website (using Pillow) ?
Have I to mentione something else ?

Thank you !

**Comment by wiredfool** [comment]
If you are distributing Pillow in some other software, you must include the copyright notice and license. For example, mentioning in the about box and shipping the license alongside the code. 

If you are using Pillow on a website, there are no obligations, though any mention is nice.
