### ISSUE TITLE
Converting from RGB to 'P' mode and back

### ISSUE THREAD

**Issue by rdevon** [python-pillow/Pillow#2418]
This is a general question that I have not been able to find an answer to, neither in the documentation, community discussion, etc.

I have RGB images in the form of an array. I need to convert these to an 8-bit representation. Later down the pipe, I get another 8-bit representation of a completely different set of images. I need to convert this *back* to RGB representation, but unfortunately, I'm having difficulty recovering the color palette for the original set of images. 

Here is the RGB to 8-bit conversion
```
# Given: arr: a 3 x 64 x 64 array of RGB values
img = Image.fromarray(arr.transpose(1, 2, 0))
img = img.convert('P')

# Now I get my 8-bit representation
arr2 = np.array(img)
#Now suppose I want to construct a new image
img2 = Image.fromarray(arr2)
# and convert to RGB
img2 = img2.convert('RGB')
```

And of course, this creates a greyscale image. What is the best way to convert back to RGB color? I've tried a variety of things, such as using `img.getpalette()` and using that as an argument to `img2.convert`, but no luck.

**Comment by wiredfool** [comment]
You need to call something like img2.setpalette(img.getpalette()) to copy the palette from the original image to the second one, prior to converting to RGB. 

Palette images are essentially an 8-bit gray image with attached palette. Converting them to a numpy array removes the palette, so all you have are the indexes. You need to add that back in.

**Comment by rdevon** [comment]
Actually it's `img2.putpalette(img.getpalette())`, but yes that works. Thanks!

**Comment by wiredfool** [comment]
Sorry, was doing it from memory, but I'm glad it helped.
