### ISSUE TITLE
Converting one image with another image's 16 color palette

### ISSUE THREAD

**Issue by rdevon** [python-pillow/Pillow#2421]
What I'd like to do is take one image and convert it with another image's 16 color palette. It appears that the only convert method uses the kmart `palette=Image.ADAPTIVE`. I would like to do something like this:

```python
# Given: arr and arr2 of RGB color data
img = Image.fromarray(arr)
img = img.convert('P', palette=Image.ADAPTIVE, colors=16)

img2 = Image.fromarray(arr2)
img2 = img2.convert('P', palette=img.getpalette(), colors=16)
```

Alas, `img2` has 256 colors.

**Comment by wiredfool** [comment]
Look at `Image.quantize`: http://pillow.readthedocs.io/en/4.0.x/reference/Image.html#PIL.Image.Image.quantize

It should do exactly what you want.
