### ISSUE TITLE
Support for Saving 12-Bit JPEG

### ISSUE THREAD

**Issue by cancan101** [python-pillow/Pillow#2423]
### What did you do?
Try to sve 12 bit JPEG.

### What did you expect to happen?
File saved with 12 bit JPEG.

### What actually happened?
```
/Users/alex/.virtualenvs/work/lib/python2.7/site-packages/PIL/JpegImagePlugin.pyc in _save(im, fp, filename)
    590         rawmode = RAWMODE[im.mode]
    591     except KeyError:
--> 592         raise IOError("cannot write mode %s as JPEG" % im.mode)
    593
    594     if im.mode == 'RGBA':

IOError: cannot write mode I;16 as JPEG
```
### What versions of Pillow and Python are you using?
`4.0.0`

```python
Image.fromarray(np.ones((10,10), np.uint16)).save('/Users/alex/Desktop/test.jpeg')
```

Related: https://github.com/python-pillow/Pillow/issues/414

Some work on libjpeg: https://trac.osgeo.org/gdal/wiki/TIFF12BitJPEG

**Comment by wiredfool** [comment]
There's no support in Pillow, and from the link it doesn't appear that the underlying support in libjpeg or libtiff is widespread or common.
