### ISSUE TITLE
Font loaded from a different folder.

### ISSUE THREAD

**Issue by cprogrammer1994** [python-pillow/Pillow#2435]
### What did you do?

Using `ImageFont.truetype(...)` with random prefix in filename (incorrect path).
Probably the **OpenSans-Regular.ttf** is installed in my Fonts (I am using windows)

### What did you expect to happen?

Expected to get an error.
Will my **installed font** override the font with **filename** if it exists?

### What actually happened?

I got the font loaded without, but the file was not there.

### What versions of Pillow and Python are you using?

- Python 3.6 32bit
- Windows 10 64bit
- Pillow 4.0.0

```python
from PIL import ImageFont
import os

# This will print File does not exists.
if not os.path.exists('../../DataFiles/OpenSans-Regular.ttf'):
	print('File does not exists.')

# These all work fine
font0 = ImageFont.truetype('../../DataFiles/OpenSans-Regular.ttf', 120)
font1 = ImageFont.truetype('../this/folder/does/not/exists/OpenSans-Regular.ttf', 120)
font2 = ImageFont.truetype('potato://////OpenSans-Regular.ttf', 120)
font3 = ImageFont.truetype('random-prefix-just-works-fine/OpenSans-Regular.ttf', 120)
```

**Comment by cprogrammer1994** [comment]
Checked: _Will my **installed font** override the font with **filename** if it exists?_
Answer: **NO**

**Comment by hugovk** [comment]
This is the "correct" behaviour.

https://github.com/python-pillow/Pillow/blob/58b5c9187db8bb1c0cf49a35d8996a2179ac2e4c/PIL/ImageFont.py#L237-L278

`ImageFont.truetype` first looks for the font in the given directory. If not found, it chops off the path and looks for the filename in a number of system paths.

It's documented as:
> **font** – A truetype font file. Under Windows, if the file is not found in this filename, the loader also looks in Windows `fonts/` directory.

https://pillow.readthedocs.io/en/4.0.x/reference/ImageFont.html#PIL.ImageFont.truetype
