### ISSUE TITLE
Enable DPI Scaling Awareness

### ISSUE THREAD

**Issue by yabbas** [python-pillow/Pillow#2438]
### What did you do?
Tried to grab a screenshot with pyautogui.  This passes control over to Pillow's imagegrab.

### What did you expect to happen?
A screenshot of the entire screen.

### What actually happened?
The top left corner of the screen (1/4) was saved.

### What versions of Pillow and Python are you using?
Python 3.6, Pillow 4.00

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

```python
PIL.ImageGrab.grab(bbox=None)
<PIL.Image.Image image mode=RGB size=1600x900 at 0x132A0D5F898>
# screen resolution is actually 3200x1800
```

Fix - making the App DPI Aware:
https://github.com/asweigart/pyautogui/issues/33#issuecomment-236981496

**Comment by davePlug** [comment]
This is still an issue...and now is becoming more pressing with even more 4k monitors around

**Comment by radarhere** [comment]
#4000 has now been merged, using an awareness context of DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE.
