### ISSUE TITLE
Image load not returning when multiple requests are made at once

### ISSUE THREAD

**Issue by tangfucius** [python-pillow/Pillow#2444]
### What did you do?
My apache server serves some large jpgs (~20M) using PIL. Whenever there is more than one request for the images at the same time, only one image would be fetched. I went through my code and saw that im.load() doesn't return for all the other requests (even though they belong to different processes/wsgi).

### What versions of Pillow and Python are you using?
Pillow: 4.0.0, Python 2.7

Each process/wsgi makes the following call:
```python
im = Image.open(src_fp)
try:
    im.load()
    logger.debug("Loaded: "+src_fp)
except:
    logger.debug("Needed to reload: "+src_fp)
```
But I never saw anything in my logs (except the request that completed), so I concluded that im.load() must have hung. Possibly some race condition?

**Comment by wiredfool** [comment]
What's the environment? What is the software stack around Pillow?  What threading model is it using?

Can you share the images?

**Comment by tangfucius** [comment]
It is running under Ubuntu 14.04. The image server is [Loris](https://github.com/loris-imageserver/loris/blob/development/loris/transforms.py#L43) - not knowledgeable about the threading model, don't think there is one - I see that it has spawned multiple processes though, so I guess there are no shared threads?

The image loads fine if there is only one request.

**Comment by wiredfool** [comment]
It looks like loris is using werkzeug, which looks like it uses one of three different concurrency methods, which doesn't really narrow anything down.  Race conditions or deadlocks are tricky things, and generally sensitive to the exact conditions, and there's not enough here for me to go on. 

If it's deadlocked, it should be possible to use gdb to get a backtrace of what's blocked. You many need a debug version of python/pillow to make that useful. (python-dbg package in ubuntu, then compile pillow for it).  It may also depend on the storage for the images. 

Try to narrow it down to a reproducible case that doesn't involve a huge stack of other software.

**Comment by tangfucius** [comment]
I installed python-dbg, but would you mind telling me how I compile pillow for it? Can't find it in the docs.

**Comment by wiredfool** [comment]
You're going to need to download the pillow sources. Make a virtualenv using python-dbg as the python interpreter. (-p flag). Install the dependencies for pillow on your machine, which are listed in the install docs, or you can look in the pillow source at depends/ubuntu-14.04.sh. You might not need all of them, depending on what you're doing with pillow. 

Source your new virtualenv, then from the Pillow directory run `python setup.py install`.  That will install pillow into the virtualenv.  Then, install all your other webapp stuff into it, and run there. 

Once you get a hang, run `gdb -p [processid]` of your python process, and `bt` to get a backtrace. You may have multiple processes to check, or there may be multiple threads to get a trace from. The command `py-bt` should get a python level stack trace as well.
