### ISSUE TITLE
img.transpose does not accept None as argument value.

### ISSUE THREAD

**Issue by Po-Hsuan-Huang** [python-pillow/Pillow#2446]
When I was using Image module of Pillow, I tried to feed transpose() with elements in a dictionary.  The elements are the commands to flip or rotate the image, but sometimes I want to take null action. However, the transpose function does not allow null arguments, i.e., the image is always flipped, or rotated. 

How do I let image stay unchanged in this case ? I don't want to use condition because it looks bad. Is it a good idea to add None as a valid argument value for transpose() function ?

**Comment by radarhere** [comment]
If it helps, here are some alternative ways that you could write your code, given the current state of Pillow -

- You could pass in None and catch the TypeError
- You could pass in an integer not 0-5 for a tranpose operation that does not currently exist and catch the ValueError
- If you don't want to use if-else, then you could use dictionary comprehension
- You could create a method and call that instead, with the method containing the if-else, or dictionary comprehension

**Comment by homm** [comment]
>  I don't want to use condition because it looks bad.

Explicit is better than implicit.
