### ISSUE TITLE
Support for Guetzli

### ISSUE THREAD

**Issue by harrislapiroff** [python-pillow/Pillow#2452]
Looks like [Google announced](https://research.googleblog.com/2017/03/announcing-guetzli-new-open-source-jpeg.html) a JPEG encoder this month that is slower than libjpeg but produces smaller and potentially less artifacty files. Is it possible to set up Pillow to use either libjpeg or guetzli?

**Comment by wiredfool** [comment]
Guetzli appears to be implemented as a command line tool, not a library. To use it, one would write a .png file and call the tool, providing an output and options. 

There doesn't appear to be any good reason to incorporate that into Pillow rather than a standalone Guetzli tool.

**Comment by harrislapiroff** [comment]
Ah, that makes sense.
