### ISSUE TITLE
Different font rendering in Alpine/Ubuntu

### ISSUE THREAD

**Issue by misisnik** [python-pillow/Pillow#2454]
### What did you do?
I want to put truetype font into the pucture in Alpine linux and this picture save or get bits values (load()).
This module I using in my user interface graphic display.

### What did you expect to happen?
Render text correctly due to font and font size

### What actually happened?
Actually in Ubuntu everything works fine:
Ubuntu example: [http://i.imgur.com/e9TuHJl.jpg](http://i.imgur.com/e9TuHJl.jpg)
![image](https://cloud.githubusercontent.com/assets/1324225/24204878/7d64563a-0f22-11e7-8c4f-7d3ead9e77cb.png)

but in Alpine text is rendering wrong:
Alpine example: [http://i.imgur.com/uKfA1wX.jpg](http://i.imgur.com/uKfA1wX.jpg)
![image](https://cloud.githubusercontent.com/assets/1324225/24204891/83659954-0f22-11e7-9f7e-2fac0a517a96.png)

### What versions of Pillow and Python are you using?
Version of Python is 3.5 (Ubuntu and Alpine are same)
Version of Pillow is 4.0.0 (Ubuntu and Alpine are same)

```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

image = Image.new('1', (192, 64))
draw = ImageDraw.Draw(image)

font = ImageFont.truetype('fnt/arial.ttf', 10)
draw.text((0,0), 'Hello world!', font=font, fill = 1)

font = ImageFont.truetype('fnt/arial.ttf', 15)
draw.text((0,15), 'Hello world!', font=font, fill = 1)

font = ImageFont.truetype('fnt/arial.ttf', 20)
draw.text((0,40), 'Hello world!', font=font, fill = 1)

image.save('test', 'JPEG')
```

**Comment by wiredfool** [comment]
The explanation is likely either:
1) You're using slightly different fonts (possibly one of them is pulling from a shared system font directory)
2) You're using different versions of freetype. There are distros that ship patches for freetype that affect the kerning.

**Comment by misisnik** [comment]
1. Font file is alwais same (I have been loading it from fnt/  (if I delete the font  pillow will give me error that font does not exist)

2. Freetype version
Ubuntu: libfreetype6-dev_2.6.1-0.1ubuntu2.1_amd64.deb
Alpine: freetype-2.7-r0 description: TrueType font rendering library

**Comment by misisnik** [comment]
I ve tried to install Alpine with Pillow on Docker like here (https://github.com/python-pillow/docker-images/blob/master/alpine/Dockerfile)

Result is still  the same :(. 
Python3.5.2, freetype 2.7, font file is in program  directory (i am 100% sure that is loaded)

**Comment by misisnik** [comment]
Finally when I have compiled older version (**2.4.1 from https://github.com/LuaDist/freetype**), output is fine (image from ubuntu = image from Alpine)
