### ISSUE TITLE
Travis CI: enable auto-cancellation?

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#2463]
Would this be useful?

> If you are only interested in building the most recent commit on each branch you can use this new feature to automatically cancel older builds in the queue that are _not yet running_.

https://docs.travis-ci.com/user/customizing-the-build/#Building-only-the-latest-commit
https://blog.travis-ci.com/2017-03-22-introducing-auto-cancellation

**Comment by radarhere** [comment]
Perhaps. I'm not strongly opinionated either way. If I'm concerned enough with a Travis run to want it done faster, i'm probably also concerned enough to not worry about manually cancelling builds.

**Comment by aclark4life** [comment]
@hugovk I'd say if it's easy to set, we should. Maybe it helps them to conserve resources, and if it becomes annoying we can turn it off.

**Comment by hugovk** [comment]
No need to do this, Travis have enabled it by default to help free up resources for everyone.

More info: 
* https://blog.travis-ci.com/2017-09-21-default-auto-cancellation
* https://blog.travis-ci.com/2017-09-22-macos-update
