### ISSUE TITLE
BytesWarning when attempting to resize and save a GIF

### ISSUE THREAD

**Issue by tbarrella** [python-pillow/Pillow#2476]
### What did you do?
Tried to resize and save an image in Python 3

### What did you expect to happen?
Resized image is saved to a `BytesIO()` object

### What actually happened?
```
...
File ".../PIL/Image.py", line 1698, in save
    save_handler(self, fp, filename)
  File ".../PIL/GifImagePlugin.py", line 389, in _save
    header = getheader(im_out, palette, im.encoderinfo)[0]
  File ".../PIL/GifImagePlugin.py", line 699, in getheader
    if im.info.get("version") == "89a":
BytesWarning: Comparison between bytes and string
```

### What versions of Pillow and Python are you using?
Pillow 3.4.2, Python 3.6.1

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

```python
from PIL import Image
from io import BytesIO
raw = ...  # response from urllib.request.Request
img = Image.open(BytesIO(raw))
fmt = img.format  # 'GIF'
to = BytesIO()
img.resize((10, 10), Image.ANTIALIAS).save(to, fmt, {})
```

**Comment by JelleZijlstra** [comment]
To clarify, this Python 3 with the `-bb` option turned on.

**Comment by tbarrella** [comment]
Closing because it appears this has since been fixed in more recent versions of Pillow; the corresponding line in 4.1.0 is
`if im.info.get("version") == b"89a":`
