### ISSUE TITLE
Images no more read with Pillow 4.1.0

### ISSUE THREAD

**Issue by saimn** [python-pillow/Pillow#2481]
### What did you do?

Opened images, get their size etc. For a number of images it now fails with Pillow 4.1 (https://travis-ci.org/saimn/sigal/jobs/220063296 for instance).

### What actually happened?

An exception: `OSError: cannot identify image file`

### What versions of Pillow and Python are you using?

Please include code that reproduces the issue and whenever possible, an image that demonstrates the issue. The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, django, or buildout, try to replicate the issue just using Pillow. 

With this image: https://github.com/saimn/sigal/blob/master/tests/sample/pictures/dir2/exo20101028-b-full.jpg

With Pillow 4.0:
```
In [1]: import PIL

In [2]: PIL.PILLOW_VERSION
Out[2]: '4.0.0'

In [3]: from PIL import Image

In [4]: Image.open('tests/sample/pictures/dir2/exo20101028-b-full.jpg')
Out[4]: <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=800x651 at 0x7FC7A081A320>

In [5]: Image.open('tests/sample/pictures/dir2/exo20101028-b-full.jpg').size
Out[5]: (800, 651)
```

With Pillow 4.1:
```
In [1]: import PIL

In [2]: PIL.PILLOW_VERSION
Out[2]: '4.1.0'

In [3]: from PIL import Image

In [4]: Image.open('tests/sample/pictures/dir2/exo20101028-b-full.jpg')
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-4-8014aa965ecb> in <module>()
----> 1 Image.open('tests/sample/pictures/dir2/exo20101028-b-full.jpg')

/home/simon/miniconda3/envs/sigal/lib/python3.6/site-packages/PIL/Image.py in open(fp, mode)
   2450         fp.close()
   2451     raise IOError("cannot identify image file %r"
-> 2452                   % (filename if filename else fp))
   2453 
   2454 #

OSError: cannot identify image file 'tests/sample/pictures/dir2/exo20101028-b-full.jpg'
```

**Comment by hugovk** [comment]
A quick go with [git bisect](https://robots.thoughtbot.com/git-bisect) points at 07a96209597c5e8dfe785c757d7051ce67a980fb:
```
07a96209597c5e8dfe785c757d7051ce67a980fb is the first bad commit
commit 07a96209597c5e8dfe785c757d7051ce67a980fb
Author: Hugo
Date:   Tue Mar 14 11:49:10 2017 +0200

    If DPI isn't in JPEG header, fetch from EXIF

:040000 040000 391c8f192170883a508880f4b39be3eb3aecb29b 3aa7b78dd462a731025d6f9f7688eda92e4cdcbf M	PIL
```

I'll take a closer look later.

**Comment by hugovk** [comment]
Looks like index error here: https://github.com/python-pillow/Pillow/pull/2472/files#diff-42c79834cd0653b67739d44923e685acR126

`x_resolution` == 72, and not a tuple.

**Comment by hugovk** [comment]
For an image like Tests/images/photoshop-200dpi.jpg used by `python Tests/test_file_jpeg.py TestFileJpeg.test_dpi_from_exif`, `x_resolution == (2000000, 10000)`.

For another, it is `(72, 1)`.

Anyway, I have a fix. 

@saimn Would it be okay to include the image in the test suite under the PIL licence, to guard against regressions?

**Comment by saimn** [comment]
@hugovk - I thought it came from wikipedia, but I cannot find it there and it seems actually to be [copyrighted](http://www.lauriehatch.com/GalleryMain.asp?GalleryID=134714&AKey=6Q457TBG) (so I will also remove it from my tests).
But there are failures with other images in my tests, for instance [here](https://travis-ci.org/saimn/sigal/jobs/220063296#L2212) with [this image](https://github.com/saimn/sigal/blob/master/tests/sample/pictures/dir1/test2/21.jpg), which is mine, so no problem to include this one (if the error has the same origin but I guess so).

**Comment by hugovk** [comment]
@saimn Thank you! I've created a PR to fix this: https://github.com/python-pillow/Pillow/pull/2484

**Comment by saimn** [comment]
@hugovk - Thanks for the quick fix !
