### ISSUE TITLE
WebPImagePlugin.py decodes webp in open() 

### ISSUE THREAD

**Issue by christophegithubtts** [python-pillow/Pillow#2483]
### What did you do?
Calling Image.open() on a webp file

### What did you expect to happen?
The call should be quick

### What actually happened?
open() for a webp image actually decodes the webp into rgb !
So open() for a webp image is much slower than open() for a png for instance 

The implementation in WebPImagePlugin.py is not efficient at all. 
open should call WebPGetInfo or WebPGetFeatures but not WebPDecode !

### What versions of Pillow and Python are you using?
Latest pillow (4.1) and python 2.7

**Comment by hugovk** [comment]
PRs welcome.

Have a look at:
* https://pillow.readthedocs.io/en/latest/handbook/writing-your-own-file-decoder.html
* https://github.com/python-pillow/Pillow/blob/master/PIL/WebPImagePlugin.py
* https://github.com/python-pillow/Pillow/blob/master/_webp.c

**Comment by wiredfool** [comment]
There is actually a pr languishing that totally rewrites webp support.

**Comment by hugovk** [comment]
* https://github.com/python-pillow/Pillow/pull/1122: "Add WebP decoder"
* https://github.com/python-pillow/Pillow/pull/1263: "Added WebP advanced options."

**Comment by christophegithubtts** [comment]
wiredfool : do you mean pr #1122 has some problems and will not be checked in ?

**Comment by wiredfool** [comment]
No. I mean that there is a PR, and that it appeared to be a ground up rewrite which may or may not have the same issues as the current version of the webp plugin.  IIRC, there was discussion around that PR, and then it went nowhere because it's a huge code drop that replaced existing functionality without ever discussing the differences between it and the current code.

**Comment by radarhere** [comment]
#2761 being merged in on 6 Nov 2017 meant that WebPDecode is no longer called for newer versions of libwebp. Testing, if I force the legacy mode to be used, it is 424% of the time of PNG open. Testing the normal version of WebP open, I get 188% of the time of PNG open.

Is that speed up sufficient for this issue to be closed?

**Comment by christophegithubtts** [comment]
That's better for sure
I guess the following line 
self._decoder = _webp.WebPAnimDecoder(self.fp.read()) 
is responsible for 88% additional time compared to png ? 

I let you close the ticket

**Comment by radarhere** [comment]
No, `self._decoder = _webp.WebPAnimDecoder(self.fp.read())` is only responsible for about 13% of the additional time compared to PNG.
