### ISSUE TITLE
Is it possible to use Pillow on Win64?

### ISSUE THREAD

**Issue by pineapplemachine** [python-pillow/Pillow#2489]
I'm trying to use any version of Pillow on Windows 7 x64 with 64-bit Python 2.7.9.

I tried installing with `pip install pillow` and I received the error "The headers or library files could not be found for zlib, a required dependency when compiling Pillow from source." I installed zlib from [here](http://gnuwin32.sourceforge.net/packages/zlib.htm). I tried adding the installed directory containing `zlib1.dll` to PATH, and I tried adding the directory containing `zlib.h` to PATH, but I still receive the same error when trying to install Pillow.

I tried installing with the wheels hosted [here](http://www.lfd.uci.edu/~gohlke/pythonlibs/#pil) and for all the ones I tried I received errors such as `Pillow-4.1.0-cp27-cp27m-win_amd64.whl is not a supported wheel on this platform.`

**Comment by wiredfool** [comment]
I suspect that given you're on an old python, you probably need to update your version of pip to handle the wheels.

**Comment by pineapplemachine** [comment]
I updated pip and the wheel installed fine. I had no idea that could be an issue, thank you for suggesting it!
