### ISSUE TITLE
HTTPS GitHub Pillow site listing

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#2490]
At the top of https://github.com/python-pillow/Pillow is -

'The friendly PIL fork (Python Imaging Library) http://python-pillow.org'

After #2403, https://github.com/python-pillow/Pillow/blob/master/setup.py lists the URL as 'https://python-pillow.org', rather than 'http://python-pillow.org'. Should the website at the top of the GitHub project also be changed to HTTPS?

**Comment by aclark4life** [comment]
Thanks, done.

**Comment by radarhere** [comment]
Thanks
