### ISSUE TITLE
4.1.1 Release Issue

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2492]
So, 4.1.0 has settled for a bit, and I think that a 4.1.1 release is appropriate for the Exif/Dpi (#2484) issue and the Python 3.6.0/1 (#2479) issue. 

I've had a look at https://bugs.python.org/issue29943 again, and I'm not sure where the resolution of this is going to fall, but I'm leaning to some sort of workaround on our end, either a friendly notification or undefining the symbol. (Though, the undefining solution is going to live on far past the eventual resolution in Python)

As a sort of delayed post-mortem for the 4.1.0 release, it's becoming clear that no one installing our code is really prepared to do the compilation. Binaries are the thing, and we'd save support issues by pushing the new release to pypi all in one shot, rather than as source, then two or three different sets of binaries. 

So, if @cgohlke is ok with it, I'd like to change the release procedure to:
 * Prepare release, bump versions and such. 
 * Run the osx/linux wheels
 * Tag & notify @cgohlke for windows binaries
 * Upload sdist, mac, linux, and windows wheels in one shot. 

I don't know if @cgohlke is pulling from pypi, or git checkout or zips or what -- so that's the uncertainty in this plan.

**Comment by aclark4life** [comment]
+1, I'm fairly certain @cgohlke can grab the source from GitHub to build binaries but you're right we should confirm that.

**Comment by cgohlke** [comment]
A tag on GitHub is OK.

**Comment by wiredfool** [comment]
k, tagged 4.1.1 and pushed on pillow wheels.

**Comment by cgohlke** [comment]
[Here you go](http://www.lfd.uci.edu/~gohlke/download/Pillow-4.1.1.win-dist.zip).

**Comment by wiredfool** [comment]
Many thanks @cgohlke

**Comment by wiredfool** [comment]
And they're up.
