### ISSUE TITLE
strange behaviour with image mode "L" and "1" 

### ISSUE THREAD

**Issue by AugustH** [python-pillow/Pillow#2494]
### What did you do?
```python
from PIL import ImageDraw, Image, ImageFont

for mode in "RGB", "L", "1":
    img = Image.new(mode, (300, 100), (255, 255, 255))
    draw = ImageDraw.Draw(img)
    font = ImageFont.truetype("times", 48)
    draw.text((10, 10), "Some Text", (0, 0, 0), font)
    draw.line(((0, 100), (300, 0)), (0, 0, 0))
    img.save(mode + ".png")
    img.convert('L').save(mode + "-L.png")
    img.convert('1').save(mode + "-1.png")
```

### What did you expect to happen?

get identical pictures independent of the mode -- or an error/exception if i am doing something wrong

### What actually happened?

only the "RGB" and "RGB" converted to "L" or "1" images contain the image, the "L" and "1" mode images are blank

### What versions of Pillow and Python are you using?

Pillow 3.1.2 with Python 2.7.12 and Python 3.5.2 (Linux Mint 18.1)

**Comment by hugovk** [comment]
@AugustH Please can you retest with the latest Pillow 4.1.0?

`img = Image.new(mode, (300, 100), (255, 255, 255))` with `mode == "L"` or `"1"` now gives a `TypeError`.

**Comment by AugustH** [comment]
yes - indeed. 

Traceback (most recent call last):
  File "bug.py", line 5, in <module>
    img = Image.new(mode, (300, 100), (255, 255, 255))
  File "...python3.5/site-packages/PIL/Image.py", line 2162, in new
    return Image()._new(core.fill(mode, size, color))
TypeError: function takes exactly 1 argument (3 given)
