### ISSUE TITLE
No VERSION.py file

### ISSUE THREAD

**Issue by Ashargin** [python-pillow/Pillow#2495]
I am sorry, i believe this is not the way what github should be used : i have trouble running pillow and i would need some help.
I installed pillow 4.1.0 using pip.
"from PIL import Image" returns "ImportError: cannot import name 'VERSION'" because there is, indeed, no VERSION.py file in the PIL folder.
Is there something i'm doing wrong?
Thanks in advance and sorry for the wrong use of this platform, i know it is used to suggest improvements and not ask questions. I could not find any answer on stackoverflow.

**Comment by radarhere** [comment]
I don't personally object to others asking questions here. This is the home of Pillow, and if you need help in adopting Pillow, then why would we want to help?

Congratulations on apparently solving your problem.

**Comment by Ashargin** [comment]
Uninstalling it and reinstalling it solved it. I have no idea what was not working correctly.

**Comment by wiredfool** [comment]
I suspect that the Python portion of Pillow was importing an early PIL core, which doesn't have a version attribute.  We added the version attribute to prevent mismatches of that sort.
