### ISSUE TITLE
Invalid colors in TIF format

### ISSUE THREAD

**Issue by AlexLazov** [python-pillow/Pillow#2503]
Some TIFF images are displayed incorrectly.
I'm using the latest version Pillow.

![dd03](https://cloud.githubusercontent.com/assets/26875658/25739924/54979196-31ae-11e7-81c3-caee6e65bb8b.jpg)

Images TIF:
https://yadi.sk/d/SpI9WGU-3Hh6KQ

**Comment by wiredfool** [comment]
This looks something like a color space issue, almost as if we're interpreting YCrCb (the default jpeg space) as RGB (which is what the image is tagged as).  I'm not seeing any place where we're obviously going wrong, so ... more digging required.

**Comment by AlexLazov** [comment]
I already understood this. If you open using the library, everything is correctly displayed (READ_LIBTIFF = True). By the way, the problem was discussed before.

**Comment by wiredfool** [comment]
I'm not seeing the previous discussion in github's search.

**Comment by AlexLazov** [comment]
We can solve the problem like this.
In the condition "_if READ_LIBTIFF or self._compression in ["tiff_ccitt", "group3", ..._" add "_jpeg_". Then everything will work.
File TiffImagePlugin.py, line 1194.

``if READ_LIBTIFF or self._compression in ["tiff_ccitt", "group3",
                                                     "group4", "tiff_jpeg",
                                                     "tiff_adobe_deflate",
                                                     "tiff_thunderscan",
                                                     "tiff_deflate",
                                                     "tiff_sgilog",
                                                     "tiff_sgilog24",
                                                     "tiff_raw_16","jpeg"]:``

**Comment by hugovk** [comment]
Fixed in https://github.com/python-pillow/Pillow/pull/2899.
