### ISSUE TITLE
PIL/Image.py has a bug

### ISSUE THREAD

**Issue by elfayoumi** [python-pillow/Pillow#2505]
### What did you do?
```python
from sklearn.datasets import load_sample_image
china = load_sample_image("china.jpg")
```
### What did you expect to happen?
load the image
### What actually happened?
exception
### What versions of Pillow and Python are you using?
python 3.6, and Pillow 4.1.1

Please change the code in Image.py to:
```python
    # If the _imaging C module is not present, Pillow will not load.
    # Note that other modules should not refer to _imaging directly;
    # import Image and use the Image.core variable instead.
    # Also note that Image.core is not a publicly documented interface,
    # and should be considered private and subject to change.
    from . import _imaging as core
    if core.PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
        raise ImportError("The _imaging extension was built for another "
                          "version of Pillow or PIL")
```

```python
from sklearn.datasets import load_sample_image
from PIL import Image
#import Image
china = load_sample_image("china.jpg")
flower = load_sample_image("flower.jpg")
image = china[150:220, 130:250]
height, width, channels = image.shape
image_grayscale = image.mean(axis=2).astype(np.float32)
images = image_grayscale.reshape(1, height, width, 1)
```

**Comment by wiredfool** [comment]
I think you have an issue with the install of pillow, your core version doesn't match the python version, which can happen when upgrading from PIL to Pillow. 

Uninstall all of the PIL and Pillow versions you have, and reinstall Pillow.

**Comment by JoeHEZHAO** [comment]
I have the same issue, python 3.6 with pillow 4.1.1, in python3.6/site-distributes/PIL, I do not find _imaging anywhere. Already reinstall Pillow but get no luck. Any suggestions ?

**Comment by wiredfool** [comment]
Make sure that you're using the python that you think you're using, e.g. pip corresponds to the correct python. Remove all versions of PIL and Pillow.  Then install, and post a log in a new issue.  Make sure that you include platform information.

**Comment by jaketalyor32325** [comment]
win 10, python 3.6.5, pillow 5.2.0
the following runs fine for me. I have a fresh pillow install.

	from sklearn.datasets import load_sample_image

	# Load sample images
	china = load_sample_image("china.jpg")
	flower = load_sample_image("flower.jpg")
