### ISSUE TITLE
Support for explicitly setting ICO sub-images

### ISSUE THREAD

**Issue by pdknsk** [python-pillow/Pillow#2513]
Currently *Pillow* automatically saves additional _ICO_ resolutions when set with `sizes`. This is often not desired, as better (not automatically resized) sub-images can be made manually.

I suggest option `images` that takes a dictionary with size as _keys_, and `Image.Image` as _values_. Or perhaps just a list of `Image.Image`, with the corresponding size taking from each.

**Comment by wiredfool** [comment]
I'd be open to adding that functionality. I'd like to make sure that the interface makes sense when compared to other similar cases of adding multi-frame images.

**Comment by aclark4life** [comment]
Using the Assignees field loosely here… because you expressed an interest. :smile:

**Comment by radarhere** [comment]
Resolved by #3005
