### ISSUE TITLE
Getting invalid syntax on setup.py line 134.

### ISSUE THREAD

**Issue by aallaire** [python-pillow/Pillow#2519]
### What did you do?
pip install on centos 6 host running python 2.6, per Pillow-4.1.1.tar.gz

### What did you expect to happen?
the installation to succeed without syntax errors, and not having expressions like {"jpeg", "zlib"}. If its meant as a dictionary it needs a colon rather than a comma. If its meant as a tuple or list it needs paranthesis or square brackets rather than curly brackets.

### What actually happened?
Got a syntax error

### What versions of Pillow and Python are you using?
Pillow 4.1.1 and python 2.6

**Comment by aclark4life** [comment]
@aallaire Could it be due to dropping support for Python 2.6 as of Pillow 4? http://pillow.readthedocs.io/en/4.1.x/releasenotes/4.0.0.html

**Comment by aallaire** [comment]
I would be surprised if that worked on any 2.X python

**Comment by aallaire** [comment]
Ah I stand corrected, in 2.7 it makes it a set.
