### ISSUE TITLE
PNG image save does not keep DPI header info read or changed, float or int

### ISSUE THREAD

**Issue by shawndream** [python-pillow/Pillow#2524]
Opening a png file shows it has img.info dictionary with a 'dpi' value as (int, int)

But saving that img and then opening the new file results in an empty info dictionary with no dpi value.

I have tried updating the 'dpi' value with (int, int), (float, float), [int, int], [float, float] and setting it in the save command with:

```python
img.save(filenew, dpi=(300, 300))
```

(and the float and list variants of that).

### What did you expect to happen?
I expected the info dictionary with dpi to be included.

### What actually happened?
blank info when saved file is loaded.
```python
{ }
```

### What versions of Pillow and Python are you using?
```bash
C:\>pip install image
Collecting image
  Downloading image-1.5.5.tar.gz
Collecting pillow (from image)
  Downloading Pillow-4.1.1-cp36-cp36m-win_amd64.whl (1.5MB)
    100% |████████████████████████████████| 1.5MB 727kB/s
```

Python 3.6.1 (v3.6.1:69c0db5, Mar 21 2017, 18:41:36) [MSC v.1900 64 bit (AMD64)] on win32

To reproduce try:

```python
from PIL import Image
fileorig = r'c:/test/origimg.png'
filenew = r'c:/test/newimg.png'
img = Image.open(fileorig)
img.info
img.save(filenew)
nimg = Image.open(filenew)
nimg.info
```

**Comment by shawndream** [comment]
FYI - apparently this is a longstanding issue:
http://blog.client9.com/2007/08/28/python-pil-and-png-metadata-take-2.html

I have found the code here from a decade ago to still function (for text header info):

from PIL import PngImagePlugin
info = PngImagePlugin.PngInfo()
info.add_text("foo", "bar")
img.save(filenew, "png", pnginfo=info)
nimg = Image.open(filenew)
nimg.info

Trying to figure out a workaround for the dpi setting that would be understood by PIL on read (and our other apps).

But, dropping everything by default definitely seems a bug.

**Comment by radarhere** [comment]
Hi. You say that you've tried `dpi=`. So the following code doesn't work for you? It works for me.

    from PIL import Image
    im = Image.open('Pillow/Tests/images/hopper.png')
    print(im.info)  # {'dpi': (96, 96), 'gamma': 0.45455}

    out = 'out.png'
    im.save(out, dpi=im.info['dpi'])
    im = Image.open(out)
    print(im.info)  # {'dpi': (96, 96)}

**Comment by hugovk** [comment]
That code also works for me on macOS with Pillow 4.1.1 and hopper.png from this codebase.

Python 2.7:
```python
{'dpi': (96, 96), 'gamma': 0.45455}
{'dpi': (96, 96)}
```

Python 3.6:
```python
{'gamma': 0.45455, 'dpi': (96, 96)}
{'dpi': (96, 96)}
```

**Comment by shawndream** [comment]
Thank you Radar and Hugo, you are correct, and setting dpi= DOES work... mostly.

My initial tests discovering that the info is not included by default got confused with later testing using the built in PNG viewer on windows server (Paint).

Paint can read the dpi on my source file, but not the dpi on any PIL saved file (it defaults to displaying 96dpi, same as it shows when you don't specify a dpi in PIL, leaving no DPI).

im.save(out, dpi=(300, 300))  # file dpi setting visible to irfanview, gimp, and PIL (but not Paint)

This miscommunication between paint and PIL is probably escaping notice because the hopper test image really is 96 dpi, but as Paint is the odd man out, that's a bug for someone else to care about (hopefully MS).
