### ISSUE TITLE
 The Landscape Hiatus – Checking paused for open source projects for a few months.

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#2532]
Landscape is currently paused for open source projects - https://landscape.io/hiatus.

This issue is just to let people know, in case they would like to remove the badge until it returns.

**Comment by aclark4life** [comment]
Interesting, thanks.

**Comment by radarhere** [comment]
I contacted landscape.io, asking about their status, and the fact that the page at the URL I posted above has not updated. I received the response -

> The service is not in hiatus - I had that in place while moving servers a while back. Though the page is still visible it should not be linked from anywhere - can you tell me where you found the link? There must be some code somewhere that didn’t get updated or is using the old setting!
> 
> Everything should be Running Fine™

However, https://landscape.io/github/python-pillow/Pillow is not automatically running for each new commit.

**Comment by hugovk** [comment]
It ran for the last commit:
https://landscape.io/github/python-pillow/Pillow/564
https://github.com/python-pillow/Pillow/commit/a795b40b056cbbd4f69f73f0e4afb2867576df7f

**Comment by radarhere** [comment]
Yeah. That was me clicking the Refresh button.
