### ISSUE TITLE
Pillow doesn't support transparent BMPs created by GIMP

### ISSUE THREAD

**Issue by RustyBludgeon** [python-pillow/Pillow#2534]
Traceback (most recent call last):
```
  File "/home/m/Desktop/test.py", line 4, in <module>
    img = Image.open('img1.bmp')
  File "/home/m/.local/lib/python3.5/site-packages/PIL/Image.py", line 2439, in open
    im = _open_core(fp, filename, prefix)
  File "/home/m/.local/lib/python3.5/site-packages/PIL/Image.py", line 2429, in _open_core
    im = factory(fp, filename)
  File "/home/m/.local/lib/python3.5/site-packages/PIL/ImageFile.py", line 100, in __init__
    self._open()
  File "/home/m/.local/lib/python3.5/site-packages/PIL/BmpImagePlugin.py", line 202, in _open
    self._bitmap(offset=offset)
  File "/home/m/.local/lib/python3.5/site-packages/PIL/BmpImagePlugin.py", line 155, in _bitmap
    raise IOError("Unsupported BMP bitfields layout")
OSError: Unsupported BMP bitfields layout
```
File data scanned by Pillow:
```
{'direction': -1, 'compression': 3, 'g_mask': 16711680, 'rgb_mask': (4278190080, 16711680, 65280), 'b_mask': 65280, 'y_flip': 
False, 'a_mask': 255, 'bits': 32, 'width': 1, 'palette_padding': 4, 'header_size': 124, 'data_size': 4, 'rgba_mask': (4278190080, 
16711680, 65280, 255), 'colors': 4294967296, 'planes': 1, 'pixels_per_meter': (2835, 2835), 'height': 1, 'r_mask': 4278190080}
```
I think the issue is that GIMP produces BMPs with bitfield layout of 0xff000000, 0xff0000, 0xff00, 0xff, and the closest Pillow supports is 0xff0000, 0xff00, 0xff, 0xff000000 (BGRA).

Python: 3.5.3; Pillow: 4.1.1.
[img1.zip](https://github.com/python-pillow/Pillow/files/1007895/img1.zip)

**Comment by cprogrammer1994** [comment]
I just checked the file with a hex editor:

![image](https://cloud.githubusercontent.com/assets/11232402/26159328/a0b3de3a-3b1e-11e7-896c-60e9c3f3d916.png)

The format seems ok according to [BMP_file_format](https://en.wikipedia.org/wiki/BMP_file_format).
The image is a 1x1 pixel image with 32bits / pixel the data starts at `8A` and it is 4 bytes long (no additional padding)

The value at `1E` `[03 00]` means `BI_BITFIELDS` and it is possible it should be `BI_RGB` (a dummy 0 value) but not sure.

**Comment by RustyBludgeon** [comment]
The image is supposed to contain a single transparent pixel (0, 0, 0, 0). So is it GIMP (2.8) at fault here? Just to make sure I made it again, the output and results are identical (except that instead of RGBA now it says RGBs, but it still fails with the same error. Should I submit this to the GIMP team?

**Comment by cprogrammer1994** [comment]
I am not sure about the value. I was able to point out a minimal change that allows me to load the image.
It is possible that the value is correct and such a compression method is not supported by PIL.
If you create a larger image and you change the value at `1E` then load it with a standard image viewer (or with GIMP) and the image shows up correctly could mean that the compression method is not specified correctly when the image was saved. The data is redundant and this field may be ignored at all by other viewers. Wait for an expert from PIL to answer.

> PS: It is possible that this field is ignored by image viewers and editors however PIL is sensitive on that.

**Comment by hugovk** [comment]
Pillow doesn't currently support this type of BMP.

img1.bmp is a 32-bit BMP with compression 3, or bitfields encoding.

> [Compression](http://www.fileformat.info/format/bmp/egff.htm) indicates the type of encoding method used to compress the bitmap data. 0 indicates that the data is uncompressed; 1 indicates that the 8-bit RLE algorithm was used; 2 indicates that the 4-bit RLE algorithm was used; and **3 indicates that bitfields encoding was used**. If the bitmap contains 16 or 32 bits per pixel, then only a Compression value of 3 is supported and the RedMask, GreenMask, and BlueMask fields will be present following the header in place of a color palette. If Compression is a value other than 3, then the file is identical to a Windows 3.x BMP file.

Pillow is falling over [here](https://github.com/python-pillow/Pillow/blob/master/PIL/BmpImagePlugin.py#L147-L154):
```python
if file_info['bits'] in SUPPORTED:
    if file_info['bits'] == 32 and file_info['rgba_mask'] in SUPPORTED[file_info['bits']]:
        raw_mode = MASK_MODES[(file_info['bits'], file_info['rgba_mask'])]
        self.mode = "RGBA" if raw_mode in ("BGRA",) else self.mode
    elif file_info['bits'] in (24, 16) and file_info['rgb_mask'] in SUPPORTED[file_info['bits']]:
        raw_mode = MASK_MODES[(file_info['bits'], file_info['rgb_mask'])]
    else:
        raise IOError("Unsupported BMP bitfields layout")
```

img1.bmp has `file_info['rgba_mask'] ` of `(0xff000000, 0xff0000, 0xff00, 0xff)` which isn't found in `SUPPORTED`:
```python
32: [(0xff0000, 0xff00, 0xff, 0x0), (0xff0000, 0xff00, 0xff, 0xff000000), (0x0, 0x0, 0x0, 0x0), (0xff000000, 0xff0000, 0xff00, 0x0)],
```

---

A quick test adding `(0xff000000, 0xff0000, 0xff00, 0xff)` to `SUPPORTED` and `(32, (0xff000000, 0xff0000, 0xff00, 0xff)): "BGRA",` to `MASK_MODES` allows the image to be opened, but I've not checked if the image is opened correctly.
