### ISSUE TITLE
Read and write some gifs wrong, with "artifacts". "optimize" doesn't work

### ISSUE THREAD

**Issue by pl7ofit** [python-pillow/Pillow#2543]
### What did you do?
I read each frame of the gif, and then write them to a file.
### What did you expect to happen?
That everything will work without a headache =)
### What actually happened?
Some gif files wrote with artifacts and "optimize" doesn't work
pic2.gif
![Gif №2](https://2.downloader.disk.yandex.ru/disk/677207113ada27dc0fab71259e44cd3725ac6a3d927ef9eb8b773b8a703191ec/5927db88/qHKJXPm8T_Yg-00ZS7B2R9Eu3HgL8ZXiUw_6PMyOiWJCwBbj8eNaE-jssUUjmwPMIquycemV-27eQO8rbj38Og%3D%3D?uid=0&filename=bad_gif2.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=303799&hid=428e605b9b7d14be21ca971df4ebcc88&media_type=image&tknv=v2&etag=4132b128b991c576c279690aee59b53a)

pic6.gif
![Gif №6](https://3.downloader.disk.yandex.ru/disk/f9c5f6387dbbea3b5b7aaa03b87a551d66a2bb261df4d6163488f7289ac18bfe/5927dbd3/qHKJXPm8T_Yg-00ZS7B2R8uWSZVMg0cbzY78lUo11U6XuGiIpKe-cJ6Chmf9L325huqtkVWjwa8ujGdihECkEw%3D%3D?uid=0&filename=bad_gif6.png&disposition=inline&hash=&limit=0&content_type=image%2Fpng&fsize=360587&hid=9afda8ba56aac0ee090c8f0817c9c795&media_type=image&tknv=v2&etag=1dcedbbd1460e6187aacfc56c0adc17f)

I think compare successful and unsuccessful gifs will be right. Therefore I downloaded the gifs archive
["Bad" and "good" gifs tar archive](https://yadi.sk/d/msIkj1bN3JXrkR)

### What versions of Pillow and Python are you using?
Pillow-4.1.1-cp35-cp35m-manylinux1_x86_64.whl
Python 3.5.2
Ubuntu 16.04.2 amd64
```python
from PIL import Image, ImageChops, ImageSequence

f = Image.open('file.gif')
frames = []
framesIterator = ImageSequence.Iterator(f)
for frame in [ frame.copy() for frame in framesIterator ]: frames.append(frame)
frame.save('out.gif', save_all=True, optimize=True, append_images=frames)
```

**Comment by wiredfool** [comment]
There's definitely something odd with these images in the palette ~or dispose options~, as imagemagick isn't displaying them properly either. Different, but not proper.

Also, as an aside, optimize trims the palette size if there are unused items and the palette can be reduced to the next lower power of 2. There's a max of ~760 bytes per palette that could be saved (if there's a pathologically bad encoding of a b/w image). It's not going to do much of anything for these images.

**Comment by petrasovaa** [comment]
I have very similar problem (probably the same), it degrades the quality of the images, it adds noise. See for example:
https://trac.osgeo.org/grass/raw-attachment/ticket/3367/noisy.gif

**Comment by wiredfool** [comment]
The noise is likely dither, which is used to make palette images more perceptually correct in color at the expense of noise. Pillow's quantize doesn't have a very sophisticated method of determining if dither is needed, it's either on or off depending on the parameter passed in to `Image.quantize`.

**Comment by petrasovaa** [comment]
Thanks for responding, that's what I needed, thank you!

**Comment by radarhere** [comment]
I've created PR #5857 to fix the original problem here, resolving this.
