### ISSUE TITLE
Can tobytes/frombytes handle different alignments?

### ISSUE THREAD

**Issue by cprogrammer1994** [python-pillow/Pillow#2547]
I was reading the docs and I am wondering if I can use Pillow to read images and convert them to raw data with a custom byte alignment (1, 2, 4, or 8).

Currently I use the following snippets to load textures:

```py
from PIL import Image
img = Image.open(filename).convert('RGB')
ctx.texture(img.size, 3, img.tobytes(), alignment=1)
```

I already made `alignment=1` the default value in my module. ([change alignmet in favor to use Pillow easily](https://github.com/cprogrammer1994/ModernGL/commit/74629595abe3d44f32658b304f9ab3e1df9123a4))
However I would like to load images from other sources as well. In OpenGL the default alignment is `4`.
The real problem is with the padding added to the end of the rows.

This is how a 2x2 pixel texture should look like when it is given to OpenGL without changing the pixel pack alignment:

```
        0 1 2 3 4 5 6 7

0x00:   r g b r g b 0 0
0x08:   r g b r g b 0 0
```

How can I achieve such a result using `Image.tobytes()`?

I would rather change back the default alignment to `4` as it should be and mention in the [example](https://github.com/cprogrammer1994/ModernGL/blob/master/examples/GLWindow/04_textures.py) how can one use `Image.tobytes()` to get the pixel data in the proper format.

**Comment by wiredfool** [comment]
The raw encoder can take a stride, which is the row length in bytes. So:

```
Python 2.7.12 (default, Nov 19 2016, 06:48:10) 
[GCC 5.4.0 20160609] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> im = Image.new('RGB',(2,2), 'white')
>>> im.tobytes()
'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
>>> im.tobytes('raw', 'RGB', 8)
'\xff\xff\xff\xff\xff\xff\x00\x00\xff\xff\xff\xff\xff\xff\x00\x00'
```

Similarly, the raw decoder takes a stride. 
```
>>> im2 = Image.new('RGB', (2,2))
# without the stride
>>> im2.frombytes(im.tobytes('raw', 'RGB', 8))
>>> im2.tobytes()
'\xff\xff\xff\xff\xff\xff\x00\x00\xff\xff\xff\xff'
# with stride
>>> im2.frombytes(im.tobytes('raw', 'RGB', 8), 'raw', 'RGB', 8)
>>> im2.tobytes()
'\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff\xff'
```

**Comment by cprogrammer1994** [comment]
Thank you!
