### ISSUE TITLE
missing -dBATCH in ghostscript invocation in PIL/EpsImagePlugin.py

### ISSUE THREAD

**Issue by HinTak** [python-pillow/Pillow#2559]
Just noticed that you are missing a `-dBATCH` in ghostscript invocation in PIL/EpsImagePlugin.py , from looking at 
https://github.com/python-pillow/Pillow/issues/2545

Without it, ghostscript finishes processing the input arguments and ends in the interactive prompt, and expects more input. This is likely not what you want. It had not caused problems so far since ghostscript gets out of interactive mode anyway on encountering control-d.

BTW, https://github.com/python-pillow/Pillow/issues/2545 is _not_ a ghostscript bug. It is a FreeBSD mispackaging. Building ghostscript from git works correctly.

**Comment by aclark4life** [comment]
@HinTak So you'd like it added? Can you send a PR?

**Comment by HinTak** [comment]
Merely pointing out a problem. Up to the Pillow developers to do anythng about it.

**Comment by aclark4life** [comment]
Roger that, thanks.
