### ISSUE TITLE
`from PIL import Image` crashes Anaconda2/Python2.7 (only embedded in Visual Studio)

### ISSUE THREAD

**Issue by kungfooman** [python-pillow/Pillow#2562]
Hey all,

currently I'm writing a C++ application, which shall use Python 2.7 as scripting engine, but I struggle with a crash in ntdll.dll, when executing `from PIL import Image` (I can import other stuff just fine):

`Exception thrown at 0x00007FFDBF979D2A (ntdll.dll) in opsys.exe: 0xC0000008: An invalid handle was specified.`

![](https://i.gyazo.com/9cafa0bea3f5e6b94ff34c6ff8ee5d2b.png)

`PIL.PILLOW_VERSION` is `4.0.0`

Does anybody has an idea what could cause this crash or how to analyse the source?

**Comment by wiredfool** [comment]
It almost looks like *args is not valid when you break. Are you sure that func and args are good values at that point?

**Comment by kungfooman** [comment]
Yea, pretty sure of that, I can also just continue the process after the exception. Nonetheless, I made two screenshots with more variables, first one:

Just executing `import PIL`, which works fine, hence I set a breakpoint to see the values:

![](https://i.gyazo.com/905c348847ee76c2eae46206b5ec568c.png)

And `from PIL import Image`, forced into debugger via exception:

![](https://i.gyazo.com/e551a3085c3f28ecadadec6c4617ef8f.png)

To me the values looks pretty much the same, some differences, but thats probably the nature of the Python interpreter.

It would probably be a great help to have Python 2.7 Debug libraries for Visual Studio, but I couldn't find any and I have no clue how to built Python 2.7 via Visual Studio from scratch yet. :S

**Comment by kungfooman** [comment]
Ok, I just realized that - after resuming the program after the exception - that Python had a very clear error message. It was mentioning "import FixTk", so I looked `C:\Anaconda2\Lib\lib-tk\FixTk.py` up and executed it chunkwise in my REPL to figure out the problem. Currently tracked the crash down to this function:

```
    def convert_path(s):
        assert isinstance(s, str)   # sys.prefix contains only bytes
        udir = s.decode("mbcs")
        hdir = ctypes.windll.kernel32.\
            CreateFileW(udir, 0x80, # FILE_READ_ATTRIBUTES
                        1,          # FILE_SHARE_READ
                        None, 3,    # OPEN_EXISTING
                        0x02000000, # FILE_FLAG_BACKUP_SEMANTICS
                        None)
        if hdir == -1:
            # Cannot open directory, give up
            return s
        buf = ctypes.create_unicode_buffer(u"", 32768)
        res = ctypes.windll.kernel32.\
            GetFinalPathNameByHandleW(hdir, buf, len(buf),
                                      0) # VOLUME_NAME_DOS
        ctypes.windll.kernel32.CloseHandle(hdir)
        if res == 0:
            # Conversion failed (e.g. network location)
            return s
        s = buf[:res].encode("mbcs")
        # Ignore leading \\?\
        if s.startswith("\\\\?\\"):
            s = s[4:]
        if s.startswith("UNC"):
            s = "\\" + s[3:]
        return s
```


Gonna try to understand what's going on, why it happens and how to fix etc.

**Comment by wiredfool** [comment]
Right, so what's going on with TK is that we're now dynamically loading it at runtime, so that we don't need it installed at compile time. This was a change at 3.3.x. 

#2296 is possibly something of interest as well, as it relates to a crash when embedding the interpreter on windows.

**Comment by wiredfool** [comment]
The .pdbs are downloadable and not hard to find for windows python, I think they're on python.org in the downloads directory. Anaconda though, I don't know. And it's been a long time since I've managed a debug build of Pillow on windows.

**Comment by kungfooman** [comment]
Ok, thanks for your input. :)

Currently I "fixed" it, by simply not calling `CloseHandle`, since that function leads to the exception. I can execute `from PIL import Image` just fine now.

I've run the function statements side by side (embedded / python27.exe), to understand where the difference comes from:

```
import ctypes
s = "c:\\anaconda2\\"
udir = s.decode("mbcs")
hdir = ctypes.windll.kernel32.CreateFileW(udir, 0x80, 1, None, 3, 0x02000000, None)
buf = ctypes.create_unicode_buffer(u"", 32768)
res = ctypes.windll.kernel32.GetFinalPathNameByHandleW(hdir, buf, len(buf), 0)
```

For python27.exe:

```
>>> res
16
>>> buf.value
u'\\\\?\\C:\\Anaconda2'
```

And `hdir` is in the range around 360 - 390.

For Python embedded:

```
>>> res
0
>>> buf.value
u''
```

And `hdir` is in the range around 11000 and 15000.

MSDN about `GetFinalPathNameByHandle`: `If the function fails for any other reason, the return value is zero. To get extended error information, call GetLastError.`

So I did:

```
res = ctypes.windll.kernel32.GetFinalPathNameByHandleW(hdir, buf, len(buf), 0)
ctypes.GetLastError()
```

Returns `6`, which is `ERROR_INVALID_HANDLE`.

So I wondered about a way to check the sanity of a handle, found this:

```
import win32api
print win32api.GetHandleInformation(hdir), ctypes.GetLastError()
```

But it returns `0, 0`, which is `ERROR_SUCCESS`.

So yea, I have no clue why the Win32-API messes this up. Easiest solution is to just not closing the handle.

**Comment by aclark4life** [comment]
Marking as invalid and closing because it's been worked around, but adding documentation and library linking labels because it's a good read.
