### ISSUE TITLE
4 channel JPEG in ImageNet LSVRC 2012 validation data set?

### ISSUE THREAD

**Issue by 983** [python-pillow/Pillow#2564]
### What did you do?

```python
from PIL import Image
print("This image has %d channels."%Image.open("image.jpg").layers)
```

image.jpg:

![image](https://cloud.githubusercontent.com/assets/11274194/26694688/91b6dcca-4708-11e7-8a87-814c95e393b5.jpg)

### What did you expect to happen?

`This image has 3 channels.`

### What actually happened?

`This image has 4 channels.`

### What versions of Pillow and Python are you using?

Pillow 4.1.1, Python 2.7.6
and
Pillow 3.1.1, Python 3.5.2

### Miscellaneous information:

This bug was first found in `scipy.misc.imread` which uses pillow:

```python
import scipy.misc
print("Image shape is:", scipy.misc.imread("image.jpg").shape)
```

`Image shape is: (461, 614, 4)`

The image is from the ImageNet LSVRC 2012 validation data set where it is named ILSVRC2012_val_00019877.JPEG and can be downloaded from http://academictorrents.com/details/5d6d0df7ed81efd49ca99ea4737e0ae5e3a5f2e5

It is a 3 channel JPEG file with 32 bits per channel and can be opened correctly in Windows Photo Viewer, Firefox, Chrome and GIMP.

The `rdjpgcom` tool seems to have the same bug. This information might help to track down where the bug is in Pillow.

` rdjpgcom -verbose image.jpg`

Output:

`JPEG image is 614w * 461h, 4 color components, 8 bits per sample`
`JPEG process: Baseline`

**Comment by kkopachev** [comment]
Looks like it's CMYK image.

**Comment by 983** [comment]
Oh, sorry, I didn't know such a thing existed. Never mind then!

**Comment by sjsrini** [comment]
****
