### ISSUE TITLE
Can't identify TIF with mode=CMYK

### ISSUE THREAD

**Issue by talebbits** [python-pillow/Pillow#257]
```
File "/src/pilkit/pilkit/utils.py", line 21, in open_image
   return Image.open(target)
File "/lib/python2.7/site-packages/PIL/Image.py", line 2020, in open
    raise IOError("cannot identify image file")
IOError: cannot identify image file
```

**Comment by languitar** [comment]
I was just hit by the same issue. Would the fix in https://github.com/neerajthakur11/Pillow/commit/922994431ba4ce8d4153c05275b3ddc3f27c03b0 be enough to get support for this format?

**Comment by radarhere** [comment]
It wouldn't offer any alpha functionality for the CMYKA image.
