### ISSUE TITLE
Encoder error (jpeg) when save image with embed color profile

### ISSUE THREAD

**Issue by Lucuz91** [python-pillow/Pillow#2575]
Hi all,
I try to simply resize one image with Pillow 4.1.1 and the save function return an error.

The image is in this link 
https://drive.google.com/file/d/0BxZoHLj1LrNecTYzMEpUV29NWEE/view?usp=sharing

This is the code i use
```python
from PIL import Image

img = Image.open('path/to/image')
img.thumbnail((200, 200))
img.save("path/to/save", format="JPEG", quality=90, progressive=True, icc_profile=img.info.get('icc_profile'))
```

And this is the error returned
```
Suspension not allowed here
Traceback (most recent call last):
  File "path/my/script.py", line 5, in <module>
    img.save("path/to/save", format="JPEG", quality=90, progressive=True, icc_profile=img.info.get('icc_profile'))
  File "C:\Python27\lib\site-packages\PIL\Image.py", line 1728, in save
    save_handler(self, fp, filename)
  File "C:\Python27\lib\site-packages\PIL\JpegImagePlugin.py", line 734, in _save
    ImageFile._save(im, fp, [("jpeg", (0, 0)+im.size, 0, rawmode)], bufsize)
  File "C:\Python27\lib\site-packages\PIL\ImageFile.py", line 495, in _save
    raise IOError("encoder error %d when writing image file" % s)
IOError: encoder error -2 when writing image file
```

This error don't appear with resize (500, 500) or quality 20.

This error is very similar to one I had already met [here](https://github.com/python-pillow/Pillow/issues/2272), is the same error or something new?

**Comment by wiredfool** [comment]
Same issue. Looks like the jpeg encoder returns the icc_profile in the same buffer as the image data. So, bump up ImageFile.MAXBLOCK, don't save as progressive, or don't include the icc profile. 

<aside>
I'm really not clear on the advantage to a progressive jpg when the ICC profile is 4x the size of the image data. If you're trying to optimize for load time, the ICC profile is killing you. 

(ICC profile is 60k, saved image data is 15k)
</aside>

**Comment by Lucuz91** [comment]
I solved (as recommended) by increasing ImageFile.MAXBLOCK.
I used this value to be safe:

`ImageFile.MAXBLOCK = max(ImageFile.MAXBLOCK, (4 * image.size [0] * image.size [1]) + len(image.info.get('icc_profile')) + 10) if icc_profile else ImageFile.MAXBLOCK`


Unfortunately I have to include the ICC profile at the moment, otherwise the pictures are in wrong colors.
I'm working to convert the image and use it without ICC, but with the right colors

**Comment by aclark4life** [comment]
Documented workaround 🤙
