### ISSUE TITLE
PIL freezes PC and causes blue screen when saving large gif

### ISSUE THREAD

**Issue by martmists** [python-pillow/Pillow#2591]
### What did you do?
I made PIL save a gif of 760 frames

### What did you expect to happen?
I expected it to take a while and save the gif

### What actually happened?
My computer froze. On Linux it occasionally got a SIGKILL, and on Windows it caused a BSoD

### What versions of Pillow and Python are you using?
Python 3.6.1, Pillow 4.1.1

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
# Not tested if this causes the freeze as well, as I have 64 rectangles drawn over each image as well which may contribute to the issue
from PIL import Image

imgs = []
for _ in range (760):
    imgs.append(Image.new("RGBA", (10000, 7000), (0, 0, 0, 0)))
imgs[0].save("test.gif", save_all=True, append_images=imgs[1:])
```

**Comment by martmists** [comment]
I have noticed the CPU usage fluctuates between 20 and 100%, whereas it takes up 70 to 100% of Memory

Memory: 4GB
CPU: Intel i7-3537U 3.1GHz

**Comment by cprogrammer1994** [comment]
I doubt you can cause a **blue screen** programatically without having a serious HW issue or windows bug.

**Comment by cprogrammer1994** [comment]
Run a memcheck and paste the result

**Comment by cprogrammer1994** [comment]
```python
data = bytearray()
while True:
    data += b'Hello' * 100
```

What happens when you run out of ram running the snippet above?

**Comment by martmists** [comment]
That code immediately makes my CPU spike, but memory usage climbs really slow. Will report back in about 5 hours

**Comment by cprogrammer1994** [comment]
```
ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

===  Python36-64\python huge-gif.py ===
Traceback (most recent call last):
  File "huge-gif.py", line 5, in <module>
    imgs.append(Image.new("RGBA", (10000, 7000), (0, 0, 0, 0)))
  File "p:\Python36-64\lib\site-packages\PIL\Image.py", line 2162, in new
    return Image()._new(core.fill(mode, size, color))
MemoryError

Execution time: 21.081 s
```

I was running at least 4 VMs so I will retest with 16GB ram free as well.

**Comment by cprogrammer1994** [comment]
I get `MemoryError` but no **BSOD**.

```
ptime 1.0 for Win32, Freeware - http://www.pc-tools.net/
Copyright(C) 2002, Jem Berkes <jberkes@pc-tools.net>

===  Python36-64\python huge-gif.py ===
Traceback (most recent call last):
  File "huge-gif.py", line 5, in <module>
    imgs.append(Image.new("RGBA", (10000, 7000), (0, 0, 0, 0)))
  File "p:\Python36-64\lib\site-packages\PIL\Image.py", line 2162, in new
    return Image()._new(core.fill(mode, size, color))
MemoryError

Execution time: 58.338 s
```

![screenshot_4](https://user-images.githubusercontent.com/11232402/27507955-b0bde1ba-58db-11e7-82b2-9f9baa33b897.png)

**Comment by martmists** [comment]
For me the Images do get added, but the process of saving takes forever and hangs

**Comment by martmists** [comment]
I managed to work around the issue by using mode `1` instead of `RGBA`, and only use b/w patterns.

**Comment by wiredfool** [comment]
I'm not surprised that you'd get errors attempting to put 760 x 280Mb images in a list. You're asking for roughly 200Gig of memory, before attempting to save.
