### ISSUE TITLE
Jpeg Image distorting right after Image.open

### ISSUE THREAD

**Issue by vinicius-ronconi** [python-pillow/Pillow#2594]
### What did you do?
I opened an Jpeg image and it has slightly different colors than the original one.

### What did you expect to happen?
The image displayed should have the same colors, contrast and all other characteristics of the original image.

### What actually happened?
The image displayed by show (or saved into a new file) is slightly different than then original file. Looks like some color are not as vivid as the original one. I don't know if the image is loosing contrast or something like that, but the fact is that it is possible to see some differences. My customer first noticed it and it also happens in my machine.

### What versions of Pillow and Python are you using?
Tried first with Pillow 4.0.0 and then with 4.1.1
Python 2.7.10 (default, Feb 7 2017, 00:08:15) \n[GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.34)]
Mac OS Sierra 10.12.5 (16F73)

I saved this image to my local disk:
![gipsy1](https://user-images.githubusercontent.com/17026616/27535927-23f6ef92-5a43-11e7-9420-b1eaffb76e15.jpg)
Then, I ran this code:
```
from PIL import Image
img = Image.open('gipsy1.jpg')
img.show()

```

**Comment by wiredfool** [comment]
This is a color managed JPEG in the Display P3 space. IIRC, this is only supported on new Apple products and some other high end displays. 

`Img.show` on the other hand is completely unmanaged color, and uses the default 0-255/channel to output as a BMP*, which is then interpreted in a platform/viewer dependent way. 

If you save the image with the proper ICC profile and use a color managed viewer, it should be correct. It is also possible that you will need to use the ImageCMS module for color profile management and conversion, depending on what you're doing and how correct you wish to be. 



[*] Master branch is now using PNG, but it doesn't make a difference here.

**Comment by vinicius-ronconi** [comment]
Thanks for that, @wiredfool !
I'm saving it to sRGB and got a better result.
