### ISSUE TITLE
Image.putdata() broken?

### ISSUE THREAD

**Issue by derVedro** [python-pillow/Pillow#2600]
### What did you do?
try to make some b/w pixel based stuff with numpy arrays and to put results in the same image.

```python
import numpy as np
from PIL import Image

img = Image.open(someimage).convert('1', dither=Image.NONE)
a_img = np.asarray(img) * 255
b_img = abs(a_img - 255)  
img.putdata(b_img)
c_img = np.asarray(img) * 255
```

### What did you expect to happen?
`c_img` has same values as `b_img`

### What actually happened?
`c_img` differs from `b_img` and from `a_img`

### What versions of Pillow and Python are you using?
Pillow: 3.1.2 and 4.1.1
Python: 3.5.2

**Comment by wiredfool** [comment]
b_img is a 2d ndarray, not a flat sequence. 

```
(vpy27-dbg)erics@builder-1204-x64:~/test$ python
Python 2.7.3 (default, Feb 27 2014, 19:39:25) 
[GCC 4.6.3] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> import numpy as np
>>> a = np.ndarray((10,10))
>>> a.shape
(10, 10)
>>> len(a)
10
```

Putdata is taking the first len(b_img) items, calling PyInt_AsLong on each one (these are type ndarray)  (which ... I'm not sure what it's actually doing, but it's returning -1).

Putdata really needs a 1d sequence of values, not a multidimensional ndarray. The general accepted way of getting the data from numpy would be Image.fromarray.

**Comment by derVedro** [comment]
Okay, truly my fault. It's working if I `flatten()` the array.

ps: Image.fromarray would create a new Image. This is not what I wanted.

**Comment by cprogrammer1994** [comment]
is it possible to update the entire image from a buffer without creating a new image?

**Comment by derVedro** [comment]
Yes, of course. Why not?

**Comment by cprogrammer1994** [comment]
Is there an example?

**Comment by derVedro** [comment]
just like the first example

```python
import numpy as np
from PIL import Image

img = Image.open(someimage).convert('1', dither=Image.NONE)
a_img = np.asarray(img) * 255
# do some stuff with buffer
a_img = abs(a_img - 255)  
img.putdata(a_img.flatten())

```
