### ISSUE TITLE
4.2.1 Release 

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2611]
So far, there's the one build issue with Pypy on Windows. 

I'm not aware of any other minor release worthy issues that have come up.

**Comment by wiredfool** [comment]
Version bump done, pushed to pillow-wheels. Waiting on CI and builds.

**Comment by wiredfool** [comment]
And tagged. Ping  @cgohlke

**Comment by cgohlke** [comment]
Here you go <http://www.lfd.uci.edu/~gohlke/download/Pillow-4.2.1.win-dist.zip>

**Comment by wiredfool** [comment]
@cgohlke Thank you very much!

We're released.
