### ISSUE TITLE
Cannot load EPS

### ISSUE THREAD

**Issue by kaplun** [python-pillow/Pillow#2615]
### What did you do?
```python
from PIL import Image
i = Image.open("d15-120f10.eps")
i.load()
```

### What did you expect to happen?
The image to be correctly loaded and become usable.

### What actually happened?
```python
---------------------------------------------------------------------------
IOError                                   Traceback (most recent call last)
<ipython-input-3-f1a02b4a3b30> in <module>()
----> 1 i.load()

/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PIL/EpsImagePlugin.pyc in load(self, scale)
    331         if not self.tile:
    332             return
--> 333         self.im = Ghostscript(self.tile, self.size, self.fp, scale)
    334         self.mode = self.im.mode
    335         self.size = self.im.size

/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PIL/EpsImagePlugin.pyc in Ghostscript(tile, size, fp, scale)
    141         with open(os.devnull, 'w+b') as devnull:
    142             subprocess.check_call(command, stdin=devnull, stdout=devnull)
--> 143         im = Image.open(outfile)
    144         im.load()
    145     finally:

/home/skaplun/.virtualenvs/labs3/local/lib/python2.7/site-packages/PIL/Image.pyc in open(fp, mode)
   2517         fp.close()
   2518     raise IOError("cannot identify image file %r"
-> 2519                   % (filename if filename else fp))
   2520 
   2521 #

IOError: cannot identify image file '/tmp/tmpwifcPN'
```

### What versions of Pillow and Python are you using?
* Pillow==4.2.1
* Python 2.7.12+
* gs-9.19

The command that gets executed behind the scene is:
```
$ gs -q -g553x475 -r72.000000x72.000000 -dBATCH -dNOPAUSE -sDEVICE=ppmraw -sOutputFile=/tmp/tmpwifcPN -c '0 0 translate' -f d15-120f10.eps
```

which simply does not produce any output.

I am running this on Ubuntu 17.04 but the same error happen on CentOS7

Here attached an example .eps
[d15-120f10.zip](https://github.com/python-pillow/Pillow/files/1131135/d15-120f10.zip)

**Comment by wiredfool** [comment]
I'm not able to get ghostscript to produce any output with this file, nor any debugging data. I'm not familiar enough with postscript to debug the file, but I think this is more likely to be a ghostscript issue than a pillow one.

**Comment by kaplun** [comment]
OK. I filed a bug report in Ghostscript too: https://bugs.ghostscript.com/show_bug.cgi?id=698272

**Comment by kaplun** [comment]
Ken Sharp from Ghostscript replied back:
> EPS files are meant to be included in other PostScript programs by an application, they are not intended to be used on their own.

> As such, EPS files are not permitted to use the 'showpage' operator which transfers the rendered image to the output file. Since your file (correctly) doesn't include a showpage, the rendered output is never written.

> If you append a 'showpage' to your EPS file, or in any other way execute showpage after the EPS is interpreted, then the content will be rendered.

I confirm indeed that, if I run:
```
$ echo "showpage" >> d15-120f10.eps
$ gs -q -g553x475 -r72.000000x72.000000 -dBATCH -dNOPAUSE -sDEVICE=ppmraw -sOutputFile=/tmp/tmpwifcPN -c '0 0 translate' -f d15-120f10.eps
```

The output file is correctly populated. So, looks like Pillow should rather send the input file in pipeline to Ghostscript and append this last line.
