### ISSUE TITLE
Add big endian for  mode L;4

### ISSUE THREAD

**Issue by Eldinen** [python-pillow/Pillow#2622]
I am creating an image with the code:

img = Image.frombuffer('L', (256, 256), bitmap, "raw", 'L;4', 0, -1)

I am getting almost the right file
![foo](https://user-images.githubusercontent.com/27001443/28209629-9bbb166c-6893-11e7-94aa-1bae76668895.png)

This happens because the image is in Big Endian and I dont know how set this parameter to the image.frombuffer, its using little endian now.

**Comment by wiredfool** [comment]
I'm not sure if big-endian is really the correct term here, as that's normally on a bytes basis. This seems to be on a nibble basis.

There are 2 flags that can be used, Inverse (`I`) and reversed (`R`). e.g. `L;4R`, `L;4I`, or `L;4RI`.  The actual bit wrangling is done here: https://github.com/python-pillow/Pillow/blob/master/libImaging/Unpack.c#L286

Reversed may be what you want, as it reverses the order of the bits.  I don't think inverse is correct, as that reads white as 0 rather than 255.

**Comment by Eldinen** [comment]
You are right, its not the correct term.
Thanks for those options! I will try them as soon as possible!

**Comment by Eldinen** [comment]
I tried with all and L;4R looks better but I can not read the text properly still.

I attached the texture raw and the palette raw too.
[texture.zip](https://github.com/python-pillow/Pillow/files/1169314/texture.zip)

could you take a look please?

**Comment by wiredfool** [comment]
It certainly does appear that it's a nibble-swapped image. I'm ... unclear as to why the generating program would do this. (It's essentially swapping even and odd columns in the image)

This is the resulting file from an unpacker written to swap the nibbles. 

![tmp](https://user-images.githubusercontent.com/19792/29415732-dad0dc6e-835b-11e7-9a00-215ab3e2f942.png)

```
diff --git a/libImaging/Unpack.c b/libImaging/Unpack.c
index dfc8a4d..dfa3a73 100644
--- a/libImaging/Unpack.c
+++ b/libImaging/Unpack.c
@@ -298,6 +298,22 @@ unpackL4R(UINT8* out, const UINT8* in, int pixels)
 }
 
 static void
+unpackL4N(UINT8* out, const UINT8* in, int pixels)
+{
+    /* nibbles (nibble order reversed, white is non-zero) */
+    while (pixels > 0) {
+        UINT8 byte = *in++;
+        byte = (( byte >> 4) & 0x0FU ) | (( byte << 4 ) & 0xF0U );
+        switch (pixels) {
+        default:    *out++ = ((byte >> 4) & 0x0FU) * 0x11U; byte <<= 4;
+        case 1:     *out++ = ((byte >> 4) & 0x0FU) * 0x11U;
+        }
+        pixels -= 2;
+    }
+}
+
+
+static void
 unpackL4IR(UINT8* out, const UINT8* in, int pixels)
 {
     /* nibbles (bit order reversed, white is zero) */
@@ -1179,6 +1195,7 @@ static struct {
     {"L",       "L;4I",         4,      unpackL4I},
     {"L",       "L;4R",         4,      unpackL4R},
     {"L",       "L;4IR",        4,      unpackL4IR},
+    {"L",       "L;4N",        4,       unpackL4N},
 
     {"L",       "L",            8,      copy1},
     {"L",       "L;I",          8,      unpackLI},
```

Note that while this appears to work, I'm not happy with the naming of the mode, or even clear that there are enough files out there in this format that it's worth including.

**Comment by Eldinen** [comment]
I have added the code to unpack.c and installed PI again but if I use L;4N, I get the error unknown raw mode.

Could you tell me how update the code?

**Comment by wiredfool** [comment]
Try building this branch: https://github.com/wiredfool/Pillow/tree/issue_2622

Let me know if that doesn't work.

**Comment by Eldinen** [comment]
I havent been able to build it, could you help me?

**Comment by wiredfool** [comment]
You're missing libraries and headers for zlib and jpeg. The solution is platform dependent, but is documented here: http://pillow.readthedocs.io/en/4.2.x/installation.html#building-from-source and in the depends directory for unixlike platforms. Windows is a harder problem, but you may be able to grab an artifact from one of these builds: https://ci.appveyor.com/project/wiredfool/pillow/build/152

**Comment by Eldinen** [comment]
Yes I am seing is a harder problem.

By the way, how can I revert the process? I mean, once I have the BMP or PNG, how can I revert to raw mode again? As the image was in the beginning.

**Comment by wiredfool** [comment]
There's no support for it, but it would take a packer similar to the unpacker in the patch. Alternatively, it's not hard to swap even/odd rows in numpy and use the `L;4` packer

**Comment by Eldinen** [comment]
could you help me in the way to do it? to create a raw image coding it in L;4N

**Comment by wiredfool** [comment]
Ok, take a look at the latest commit on my branch.
```
from PIL import Image

with open('texture.bin', 'rb') as f:
    raw = f.read()
im = Image.frombuffer('L', (256, 256), raw, "raw", 'L;4N', 0, -1)
im.show()
saved = im.tobytes('raw','L;4N', 0,-1)
print(saved == raw)
```

**Comment by Eldinen** [comment]
oh perfect!
I am gonna try it!
The only problem is, could you compile and send me please?
I cannot compile in windows, I have that zlib problem :(

**Comment by wiredfool** [comment]
Sorry, I didn't manage to push that commit, and I'm away from that computer till monday. I'll push it when I get back.

**Comment by Eldinen** [comment]
Dont worry, have a nice weekend!

**Comment by wiredfool** [comment]
Check out one of these builds: https://ci.appveyor.com/project/wiredfool/pillow/build/157

**Comment by Eldinen** [comment]
How can I check out it from that url?

**Comment by hugovk** [comment]
Click a build that's closest to your Python, then the Artifacts tab, then download and pip install one of the build files.

**Comment by Eldinen** [comment]
pip install https://ci.appveyor.com/project/wiredfool/pillow/build/157 does not work, Cannot unpack file

**Comment by hugovk** [comment]
Works for me (Windows 7, Python 2.7).

From https://ci.appveyor.com/project/wiredfool/pillow/build/157/job/g0lc46fmkpr5fk1w/artifacts I downloaded Pillow-4.3.0.dev0-cp27-cp27m-win_amd64.whl and then:  
```
C:\stufftodelete\Downloads>pip install Pillow-4.3.0.dev0-cp27-cp27m-win_amd64.whl
Processing c:\stufftodelete\downloads\pillow-4.3.0.dev0-cp27-cp27m-win_amd64.whl
Requirement already satisfied: olefile in c:\python27\lib\site-packages (from Pillow==4.3.0.dev0)
Installing collected packages: Pillow
Successfully installed Pillow-4.3.0.dev0

C:\stufftodelete\Downloads>python
Python 2.7.11 (v2.7.11:6d1b6a68f775, Dec  5 2015, 20:40:30) [MSC v.1500 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.PILLOW_VERSION
'4.3.0.dev0'
>>>
>>> with open('texture.bin', 'rb') as f:
...   raw = f.read()
...
>>> im = Image.frombuffer('L', (256, 256), raw, "raw", 'L;4N', 0, -1)
>>> im.show()
>>> saved = im.tobytes('raw','L;4N', 0,-1)
>>> print(saved == raw)
True
```

![image](https://user-images.githubusercontent.com/1324225/29976138-b384b512-8f41-11e7-9d69-69b4586fc806.png)

**Comment by Eldinen** [comment]
I receive this error: it is not a supported wheel on this platform
