### ISSUE TITLE
It looks like the GIL isn't released

### ISSUE THREAD

**Issue by jimfulton** [python-pillow/Pillow#2635]
Some of us were looking at ways to process images concurrently: https://github.com/ConcurrentPython/Parallel_Image_Processing

We assumed that PIL would release the GIL while doing image processing and that threads would be beneficial. However while running under threads, the test script (threaded.py) used more CPUs, but it didn't use much more than one CPU cumulatively and didn't run much faster than processing images sequentially (linear.py).  Using multiprocessing, however, all of the CPUs (testing on an 8-cpu ec2 instance) were used and the test completed much faster, as expected.

Looking at the C sources, I don't see any calls to Py_BEGIN_ALLOW_THREADS, so I'm guessing that the GIL isn't released. This seems to be a lost opportunity.  But I'm probably missing something.

This was with Python 3.6.1 built from source on ubuntu 16.04 and Pillow 4.2.1.

**Comment by wiredfool** [comment]
Look at ImagingSectionEnter/Leave in _imaging.c:
```
void ImagingSectionEnter(ImagingSectionCookie* cookie)
{
#ifdef WITH_THREADING
    *cookie = (PyThreadState *) PyEval_SaveThread();
#endif
}

void ImagingSectionLeave(ImagingSectionCookie* cookie)
{
#ifdef WITH_THREADING
    PyEval_RestoreThread((PyThreadState*) *cookie);
#endif
}
```

It appears that this is equivalent, but using an older API rather than the macro. 

There are likely additional locations where this could be done, but it does appear that there are operations where this happens.

**Comment by jimfulton** [comment]
Ah cool. I should have looked for the macro expansion.

Hm.

**Comment by homm** [comment]
@jimfulton added multithreading for `filter` operations in #2670

**Comment by jimfulton** [comment]
Thanks!

**Comment by homm** [comment]
@jimfulton Maybe you'll be interested in [my plans to significantly speed up](https://github.com/python-pillow/Pillow/issues/2664#issuecomment-321817729) filters in next release, especially in [Pillow-SIMD](https://github.com/uploadcare/pillow-simd).

**Comment by jimfulton** [comment]
Thanks again.
