### ISSUE TITLE
Open image with original size

### ISSUE THREAD

**Issue by FuriousRococo** [python-pillow/Pillow#2651]
When I use PIL.Image.open() function to load a image, it will automatically rotate the image by 90 degrees anticlockwise if the actual width of image is smaller than the height. So far, I can use the rotate function to rotate it back to the original picture. But the same situation happens in the ImageTK too. How can I change the size of the ImageTK file?  I use Pillow-4.1.1 and py3.6.

```python
def load(self):
  image = Image.open(self.openPath)
  self.photoImage = ImageTk.PhotoImage(image) 
  self.imageLabel.configure(image = self.photoImage)
```

![1](https://user-images.githubusercontent.com/24865413/28992799-cf8f1a3c-79d8-11e7-8800-b58d4321c8a2.png)

**Comment by radarhere** [comment]
Hi. Here's a Python 3 example script that I used to test what you've described, and I wasn't able to find a problem.

```
from PIL import Image, ImageTk
import tkinter

# Create an image to test with, where the width is smaller than the height
Image.new('RGB', (100, 200), '#000').save('test.png')

# Load and display the image using tkinter
root = tkinter.Tk()
image = Image.open('test.png')
photoImage = ImageTk.PhotoImage(image)
imageLabel = tkinter.Label(root, image=photoImage)
imageLabel.pack()
root.mainloop()
```

Are you able to provide an image that you're experiencing this problem with?

**Comment by hugovk** [comment]
Maybe the image contains EXIF saying to rotate the image to portrait, and image viewers are applying that rotation.

**Comment by FuriousRococo** [comment]
@radarhere @hugovk The image was down below.
![0](https://user-images.githubusercontent.com/24865413/29000380-21874a86-7a9b-11e7-8f59-326b2566bcc7.jpg)
I've actually used Windows Photo Editor to process the image, so the image actually lost EXIF info.
And I've done a interesting experiment using numpy and pillow.
```python
image = Image.open(self.openPath)
print(image.size, np.array(image).shape)
self.photoImage = ImageTk.PhotoImage(self.image)
self.imageLabel.configure(image = self.photoImage)            
```
The result is like this.
![temp](https://user-images.githubusercontent.com/24865413/29000412-3a26b6ca-7a9c-11e7-9368-a013e208f265.png)
I just don't know what's going on, so confusing.

**Comment by hugovk** [comment]
I'm on my phone now, but I can see that image still contains rotation data. Here's (not necessarily in this order)  the image shown in email, in this issue in Chrome, the single image in Chrome, in the phone's image viewer, and it also shows it has rotation data. 

![smartselectimage_2017-08-06-08-37-59](https://user-images.githubusercontent.com/1324225/29000899-e08bab20-7a82-11e7-9270-9bd2c9b686f7.png)
![smartselectimage_2017-08-06-08-38-55](https://user-images.githubusercontent.com/1324225/29000901-e08efd98-7a82-11e7-8d11-7829948d84dd.png)
![smartselectimage_2017-08-06-08-36-35](https://user-images.githubusercontent.com/1324225/29000900-e08e8d4a-7a82-11e7-91b4-25844fbac4af.png)
![29000380-21874a86-7a9b-11e7-8f59-326b2566bcc7](https://user-images.githubusercontent.com/1324225/29000903-e08f38bc-7a82-11e7-97a0-9d9f798f436e.jpg)
![smartselectimage_2017-08-06-08-37-38](https://user-images.githubusercontent.com/1324225/29000902-e08f2110-7a82-11e7-9948-6540c01b9a35.png)

**Comment by radarhere** [comment]
Have a look at https://stackoverflow.com/questions/4228530/pil-thumbnail-is-rotating-my-image/6218425#6218425

If you're interested in why numpy is showing those numbers - https://github.com/python-pillow/Pillow/issues/2619#issuecomment-315519657

**Comment by FuriousRococo** [comment]
@radarhere @hugovk  Thx for u help, I've solved this problem.

**Comment by hugovk** [comment]
You're welcome!
