### ISSUE TITLE
Error drawing an image. [Huge Text file]

### ISSUE THREAD

**Issue by francescovallone** [python-pillow/Pillow#2666]
I was trying to create an Image from an ASCII file with a huge text.
I set the font as a true type font.

When I try to convert the text in image it returns an error.

I'm using Python 3.5.2 and Pillow 4.2.1

Code:
```python
from PIL import ImageDraw, ImageFont, Image

f = open("ascii.txt", 'r')
text = f.read() #text is a string

img = Image.new('RGB', (9000, 12000), (33, 33, 33))
d = ImageDraw.Draw(img)
font = ImageFont.truetype("roboto.ttf", 10) # roboto.ttf is in the folder
d.multiline_text((0, 0), text, fill=(255,255,255), font=font)

img.save("image.png")
```

Error:
![screenshot from 2017-08-09 12 52 27](https://user-images.githubusercontent.com/15020233/29118289-a2dc5578-7d01-11e7-8e58-6d571a4f333d.png)

**Comment by radarhere** [comment]
Are you able to provide a link to the file? Or, if you believe that size is the only factor, let us know how large the file is?

**Comment by francescovallone** [comment]
[ascii.txt](https://github.com/python-pillow/Pillow/files/1214674/ascii.txt)
This is the file

**Comment by wiredfool** [comment]
This may be a dup of #2614.

**Comment by DarkPhilosophy** [comment]
Error is with bigger and empty string 
"ABCDEFGHIJKLMNOPRSTUXYZDADADWADAWEWAWA" 
and "" both will return NULL without seeding an error

**Comment by francescovallone** [comment]
how can I solve?

**Comment by wiredfool** [comment]
Please check #2706. The issue is (apparently) unrelated to large strings, it's the same issue as #2614, but on render, not on sizing.
