### ISSUE TITLE
installation

### ISSUE THREAD

**Issue by jodyweiss** [python-pillow/Pillow#2673]
### What did you do?
tried to install pillow
### What did you expect to happen?
install
### What actually happened?
said i didnt have python 3.6, and just installed 3.6.2
### What versions of Pillow and Python are you using?
latest

**Comment by radarhere** [comment]
Hi. Would you be able to copy and paste the error message that you are receiving?

**Comment by hugovk** [comment]
How did you insure? On what operating system?

**Comment by jodyweiss** [comment]
python 3.6 required, which was not fond in the registry.  thanks.

**Comment by hugovk** [comment]
Closing this due to lack of information to investigate. 

If you can paste the error message we can reopen. Thanks.
