### ISSUE TITLE
`spacing` argument is invalid when drawing single-line text

### ISSUE THREAD

**Issue by ksze** [python-pillow/Pillow#2685]
### What did you do?
```python
from PIL import Image, ImageDraw, ImageFont
img = Image.new(mode=u'L', size=(512, 200), color=255)
draw = ImageDraw.Draw(img)
font = ImageFont.truetype(u'NotoSansCJKsc-Regular.otf', size=48)
draw.text(xy=(0, 0), text=u'foobar', fill=0, font=font, spacing=4)
```
### What did you expect to happen?
Text drawing succeeds. I expect any argument that does not apply to single-line text to be silently and automatically ignored. This is especially handy when the text is not a hard-coded literal - i.e. user-supplied or generated programmatically.
### What actually happened?
The `spacing` kwarg is invalid when the text is single-line:
```
File "/home/ksze/berryconda3/envs/foo/lib/python3.6/site-packages/PIL/ImageDraw.py", line 217, in text
    mask, offset = font.getmask2(text, self.fontmode, *args, **kwargs)
TypeError: getmask2() got an unexpected keyword argument 'spacing'
```
### What versions of Pillow and Python are you using?
Pillow 4.2.1
Python 3.6.2

**Comment by hugovk** [comment]
@ksze Please could you retest with latest master? This should have been fixed by https://github.com/python-pillow/Pillow/pull/2641.
