### ISSUE TITLE
Default font with provided font size?

### ISSUE THREAD

**Issue by yuanxu-li** [python-pillow/Pillow#2695]
There are at least two ways to get a font, either loading from default or reading from a file, such as:

```python
from PIL import ImageFont
default_font = ImageFont.load_default()
provided_font = ImageFont.truetype("sans-serif.ttf", 16)
```

I am wondering if there is any way that I can use the default font with a given font size, such as:
```python
from PIL import ImageFont
default_font = ImageFont.load_default(size=16)
```

to save myself the trouble of providing a font file while being able to change the font size.

**Comment by wiredfool** [comment]
No, the default font is a bitmapped font with no alternate sizes.

**Comment by paalbra** [comment]
There is still no workaround or anything for this?

It would be nice if Pillow provided a default font that "just works" and you were able to set a font size for it.

**Comment by kylekyle** [comment]
Right now PIllow doesn't ship with a font that can be resized. You probably already have a library that ships with one, so you could just load that. For example:

```python
import os
import cv2

font_path = os.path.join(cv2.__path__[0],'qt','fonts','DejaVuSans.ttf')
font = ImageFont.load(font_path, size=128)
```

**Comment by radarhere** [comment]
For those seeking a default font that can change sizes, #6622 has been created as a request for that.
