### ISSUE TITLE
Error to install imaging extension (error: command 'clang' failed with exit status 1)

### ISSUE THREAD

**Issue by erojasr** [python-pillow/Pillow#27]
My error to install 

Pillow-master rojasmora$ sudo python setup.py install

and

Imaging-1.1.7 rojasmora$ sudo python setup.py install

display the same error

--- using frameworks at /System/Library/Frameworks
building '_imaging' extension
creating build/temp.macosx-10.8-intel-2.7
creating build/temp.macosx-10.8-intel-2.7/libImaging
clang -fno-strict-aliasing -fno-common -dynamic -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch i386 -arch x86_64 -pipe -IlibImaging -I/System/Library/Frameworks/Python.framework/Versions/2.7/include -I/usr/local/include -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c _imaging.c -o build/temp.macosx-10.8-intel-2.7/_imaging.o
unable to execute clang: No such file or directory
error: command 'clang' failed with exit status 1

**Comment by vepurisriram** [comment]
Thanks inklesspen. Your suggestion helped me too :)

**Comment by reentec** [comment]
thx!! It worked flawlessly after installing the CLI Tools
