### ISSUE TITLE
P->RGBA->resize(LANCZOS)->P messes up transparency

### ISSUE THREAD

**Issue by kkopachev** [python-pillow/Pillow#2702]
### What did you do?
Given original image ![test.png](https://user-images.githubusercontent.com/25781945/27951758-500e2398-6349-11e7-8c68-b9cd5e39e166.png)
and following steps:

```python
from PIL import Image
im = Image.open('test.png')
im.mode # 'P'
im = im.convert('RGBA')
im = im.resize((320,240), Image.LANCZOS)
im = im.convert('P')
im.save('broken.png')
```
### What did you expect to happen?
![good](https://user-images.githubusercontent.com/2279051/29907685-b6a50a60-8dd1-11e7-87ff-bb972966fa82.png)

### What actually happened?
![bad](https://user-images.githubusercontent.com/2279051/29907638-62cec516-8dd1-11e7-9c81-8936a902d570.png)

### What versions of Pillow and Python are you using?
Python 2.7.13 / Pillow 4.2.1

However, if I slightly change the script and save RGBA image after convertion and resize to a file and then reopen that file, quantize it to palette, then it's all good:
```python
from PIL import Image
im = Image.open('test.png')
im = im.convert('RGBA')
im = im.resize((320,240), Image.LANCZOS)
im.save('intermidiary.png')
intermidiary = Image.open('intermidiary.png')
intermidiary.mode # 'RGBA'
intermidiary = intermidiary.convert('P')
intermidiary.save('good.png')
```

**Comment by wiredfool** [comment]
Reproduced here. Bug is that the palette is still hanging around in the RGBA image:
```
(vpy27) erics@builder-16:~/test$ python -m pdb issue_2702.py
> /home/erics/test/issue_2702.py(1)<module>()
-> from PIL import Image
(Pdb) n
n
> /home/erics/test/issue_2702.py(2)<module>()
-> im = Image.open('issue_2702.png')
(Pdb) n
> /home/erics/test/issue_2702.py(3)<module>()
-> print im.mode # 'P'
(Pdb) n
P
> /home/erics/test/issue_2702.py(4)<module>()
-> im = im.convert('RGBA')
(Pdb) n
> /home/erics/test/issue_2702.py(5)<module>()
-> im = im.resize((320,240), Image.LANCZOS)
(Pdb) n
> /home/erics/test/issue_2702.py(6)<module>()
-> im.show()
[good image]
(Pdb) im
<PIL.Image.Image image mode=RGBA size=320x240 at 0x7F16BC7EAED0>
(Pdb) im.palette
<PIL.ImagePalette.ImagePalette object at 0x7f16bc7f7450>
(Pdb) im.palette = None
(Pdb) im.show()
[good image]
```

Workaround Code:
```
from PIL import Image
im = Image.open('issue_2702.png')
print im.mode # 'P'
im = im.convert('RGBA')
im.palette = None
im = im.resize((320,240), Image.LANCZOS)
im = im.convert('P')
im.save('issue_2702.out.png')
```

**Comment by onassar** [comment]
This fixes the issue for this image:
![](https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld75639646)

But the issue remains for this PNG:
![](https://s3-us-west-2.amazonaws.com/app.local.getstencil.com/upld6878b91f)

Resizing results in something like this:
![](https://d32q3izcmhqbti.cloudfront.net/772x0/upld6878b91f)

**Comment by kkopachev** [comment]
That's a different issue with another library.

**Comment by onassar** [comment]
How do you mean @kkopachev?
I'm using Thumbor and this is happening. Does it not happen in PIL natively?

**Comment by kkopachev** [comment]
PIL is fine, it's issue in thumbor. I'll create PR there shortly.

**Comment by onassar** [comment]
Okay thanks. I'll work up a series of examples that are causing issues and post it there to ensure everything is captured.

**Comment by rogerchom** [comment]
Hey @kkopachev, have you created a PR to fix this yet? I saw https://github.com/thumbor/thumbor/pull/989, but this addresses something different.

**Comment by kkopachev** [comment]
@rogerchom https://github.com/thumbor/thumbor/pull/988

**Comment by rogerchom** [comment]
@kkopachev Thanks!
