### ISSUE TITLE
Second frame of animated GIF gets mangled when run through Pillow

### ISSUE THREAD

**Issue by alexwlchan** [python-pillow/Pillow#2711]
If I open an image and then immediately re-save, I expect that the new image will be the same (or at least, visually similar).

I’m doing this with the attached animated GIF, and what actually happens is the second frame gets utterly mangled by the conversion.

### What versions of Pillow and Python are you using?

```console
$ python --version
Python 3.6.1

$ pip freeze
olefile==0.44
Pillow==4.2.1

$ convert --version
Version: ImageMagick 7.0.6-4 Q16 x86_64 2017-08-17 http://www.imagemagick.org
Copyright: © 1999-2017 ImageMagick Studio LLC
License: http://www.imagemagick.org/script/license.php
Features: Cipher DPC HDRI Modules
Delegates (built-in): bzlib freetype jng jp2 jpeg lcms ltdl lzma png tiff xml zlib
```

Python 3.6.1, Pillow 4.2.1 and olefile 0.44 on macOS 10.12.4.

### Reproducible example

```python
from PIL import Image

im = Image.open('tamagotchi-death-us.gif')
im.save('tamagotchi-death-us__edited.gif', save_all=True)
```

![tamagotchi-death-us](https://user-images.githubusercontent.com/301220/29978114-c0cce9b0-8f37-11e7-99bd-809f2ddab2b9.gif)

![tamagotchi-death-us__edited](https://user-images.githubusercontent.com/301220/29978120-c399a246-8f37-11e7-946b-055e8f824023.gif)

### Notes

* I’m neither an expert on GIF nor Pillow’s support for it; I could believe this is user error (although I’d hope it could degrade more gracefully!). e.g. when I forgot to include `save_all=True`, I just got a static image.

* ImageMagick converts the image fine:

    ```console
    $ convert tamagotchi-death-us.gif tamagotchi-death-us__im.gif
    ```

* If I load the two images back into Pillow, and inspect them, I see two differences:

    ```pycon
    >>> x = Image.open('tamagotchi-death-us.gif')
    >>> y = Image.open('tamagotchi-death-us__edit.gif')

    >>> x.tile
    [('gif', (0, 0, 129, 65), 885, (7, False))]
    >>> y.tile
    [('gif', (0, 0, 129, 65), 855, (8, False))]

    >>> x.info['extension']
    (b'ImageMagick', 814)
    >>> y.info['extension']
    (b'NETSCAPE2.0', 839)
    ```

    I don’t know enough about GIF to know what these two fields mean – but could their differences be significant?

* At a guess, it looks like the second frame has some “transparent” pixels that are meant to fall through to the first frame (because it hasn’t changed).

That’s about the limit of my debugging abilities (and time this evening!), but happy to dig further if somebody gives me some pointers.

**Comment by wiredfool** [comment]
Does it display correctly when you seek theough the frames?

**Comment by radarhere** [comment]
I'm able to replicate. No, it doesn't display correctly during seek.

It's an issue with `disposal_method`. I would imagine that the disposal method is simply incorrectly set on the image, but then what logic are other programs using to decide to go ahead and replace with previous contents anyway?

**Comment by wiredfool** [comment]
Yep, the disposal_method is set to undefined. 

```
(vpy27)Erics-MacBook-Air:tests erics$ identify -verbose issue_2711.gif  | grep Dispose
  Dispose: Undefined
  Dispose: Undefined
```

The possible values of the disposal method are:
```
            iv) Disposal Method - Indicates the way in which the graphic is to
            be treated after being displayed.

            Values :    0 -   No disposal specified. The decoder is
                              not required to take any action.
                        1 -   Do not dispose. The graphic is to be left
                              in place.
                        2 -   Restore to background color. The area used by the
                              graphic must be restored to the background color.
                        3 -   Restore to previous. The decoder is required to
                              restore the area overwritten by the graphic with
                              what was there prior to rendering the graphic.
                     4-7 -    To be defined.

```
(from https://www.w3.org/Graphics/GIF/spec-gif89a.txt)

So, It's an out of spec image that's potentially salvageable with heuristics.

**Comment by wiredfool** [comment]
Closing -- I think we're handling this correctly according to the spec. I'm willing to look at PRs that would creatively interpret the spec to more correctly render this one -- but there's the possibility of breaking other images so it would have tho be done carefully.
