### ISSUE TITLE
Image loading by file name memory leak is not properly fixed

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#2716]
`__del__` doesn't work, because in the most cases `self.fp` is [None after initial loading](https://github.com/python-pillow/Pillow/blob/master/PIL/ImageFile.py#L249) and actual fp pointer is stored in `self.__fp`

**Comment by radarhere** [comment]
I have created PR #3261 to try and address this.

**Comment by radarhere** [comment]
@homm is this now fixed on master?

**Comment by aclark4life** [comment]
@hugovk @radarhere If you still think this can go in and no objection from @wiredfool or @homm I'd probably just merge it. (I see the PR was merged.)

**Comment by hugovk** [comment]
The PR is merged, closing this issue let's re-open or create a new issue needed.
