### ISSUE TITLE
Image.open raise UnicodeDecodeError if locale setting modified

### ISSUE THREAD

**Issue by rsaint** [python-pillow/Pillow#272]
``` python
import locale
from PIL import Image

locale.setlocale(locale.LC_ALL, "polish")
im = Image.open('test.jpg')

Traceback (most recent call last):
  File "E:\DOWNLOADS\jpegtran\test.py", line 6, in <module>
    im = Image.open('test.jpg')
  File "G:\Python27\lib\site-packages\PIL\Image.py", line 1982, in open
    preinit()
  File "G:\Python27\lib\site-packages\PIL\Image.py", line 300, in preinit
    from PIL import PpmImagePlugin
  File "G:\Python27\lib\site-packages\PIL\PpmImagePlugin.py", line 27, in <module>
    b_whitespace = string.whitespace.encode()
UnicodeDecodeError: 'ascii' codec can't decode byte 0xa0 in position 6: ordinal
not in range(128)
```

**Comment by markmiscavage** [comment]
I appear to still be getting this error. I'm only seeing this currently on SmartOS base-64 17.3.0. 

PIL/PpmImagePlugin.py line 33 is failing with `UnicodeDecodeError: 'utf8' codec can't decode byte 0xa0 in position 6: invalid start byte`,  but the try/except is just skipping that error to fail with the same error seen above. 

b_whitespace = string.whitespace.strip() seems to fix the problem for me. 

I can submit a pull request if this seems like a good solution.

**Comment by hugovk** [comment]
@markmiscavage A PR would be a good starting point and though we don't test SmartOS it will check it doesn't break existing ones on the CIs.

**Comment by markmiscavage** [comment]
Pull request created. 
#2820
