### ISSUE TITLE
Issue with Pillow >= 4.2.0 - IOError cannot write mode RGBA as JPEG

### ISSUE THREAD

**Issue by kouros17** [python-pillow/Pillow#2724]
Using **nautilus-image-tools** (on my manjaro) I can't convert png images to jpeg with **python2-pillow** 4.2 and above. I get:
```
IOError: cannot write mode RGBA as JPEG
```

I had to downgrade to 4.1.1-1 to work.

**Comment by hugovk** [comment]
Please could you check some images in https://github.com/python-pillow/Pillow/tree/master/Tests/images, like hopper.png, and let us know if that causes the problem? If not, can you attach the problematic image? And a (small) sample code would be helpful.

**Comment by wiredfool** [comment]
It's deprecated. Jpegs can't represent transparency.

**Comment by kouros17** [comment]
The image hopper.png converted without issues.
I have issues with the screenshots of my gnome-shell though.
For example when I try to convert the screenshot.png I get this:

![aaaaaa](https://user-images.githubusercontent.com/27904795/30244298-31951310-95c4-11e7-9ae1-4fee591e581d.gif)

The image is this:
![screenshot](https://user-images.githubusercontent.com/27904795/30244323-63a6ac4c-95c4-11e7-85dd-b581cad3ed1f.png)

**Comment by wiredfool** [comment]
You need to flatten/remove the alpha channel, one way or another before saving as a JPEG. 

See https://github.com/python-pillow/Pillow/issues/2609#issuecomment-313922483 and https://github.com/python-pillow/Pillow/blob/4.2.1/docs/releasenotes/4.2.0.rst#removed-deprecated-items
