### ISSUE TITLE
Image.alpha_composite does not behave as claimed by the docs

### ISSUE THREAD

**Issue by Rawing** [python-pillow/Pillow#2727]
According to the [documentation](http://pillow.readthedocs.io/en/4.2.x/reference/Image.html?highlight=alpha_composite#PIL.Image.alpha_composite), `Image.alpha_composite` returns a new image. In reality, it returns `None` and modifies the input image:

```
>>> from PIL import Image
>>> i1 = Image.new('RGBA', (1,1))
>>> i1.tobytes()
b'\x00\x00\x00\x00'
>>> i2 = Image.new('RGBA', (1,1), 'red')
>>> i2.tobytes()
b'\xff\x00\x00\xff'
>>> i1.alpha_composite(i2) # returns None
>>> i1.tobytes() # i1 was modified
b'\xff\x00\x00\xff'
```

I'm using python 3.6.2 and Pillow version 4.2.1.

**Comment by Rawing** [comment]
Welp, I just found the difference between the Image *module* and the Image *class*. In my defense, searching the docs for "alpha_composite" doesn't find the Image class's alpha_composite function.

**Comment by wiredfool** [comment]
The class method was added in 4.2.0, so the hits you'd get for it depend on which exact version of the docs you're hitting.
