### ISSUE TITLE
Strange gif background color

### ISSUE THREAD

**Issue by retsyo** [python-pillow/Pillow#2734]
I am using PILLOW 4.2.1-py36_0 which is updated by conda from `Python 3.6.0 |Anaconda custom (64-bit)| (default, Dec 23 2016, 11:57:41) [MSC v.1900 64 bit (AMD64)] on win32`

I found sometimes the produced gif has strange background. 
1. I only find this with `Stcaiyun.ttf`
2. Even for `Stcaiyun.ttf`, sometimes the gif is ok
3. The `framexx.png` is ok

```python
import random
from PIL import Image, ImageDraw, ImageFont

frames = []
for frame in range(10):
    img = Image.new(size=(320, 200), mode='RGB', color='white')
    
    drw = ImageDraw.Draw(img)
    text = '% 2i' % frame
    font = ImageFont.truetype(r'd:\WINDOWS\Fonts\STCAIYUN.TTF', 80)
    #~ font = ImageFont.truetype(r'd:\WINDOWS\Fonts\Stfangso.ttf', 80)
    #~ font = ImageFont.truetype(r'd:\WINDOWS\Fonts\times.TTF', 80)
    #~ font = ImageFont.truetype(r'3Dkirieji.ttf', 80)
    x, y=random.randint(60,250), random.randint(20,100)
    color = random.choice(['red', 'green', 'blue', (0, 127, 127)])
    drw.text((x, y), text, font=font, fill=color)
    img.save('frame%02i.png' % frame)
    frames.append(img)
    
frames[0].save('out.gif', save_all=True, append_images=frames[1:], duration=300, loop=True, optimize=True)
```

I am sorry I cannot upload STCAIYUN.TTF since it is some huge

[out.zip](https://github.com/python-pillow/Pillow/files/1298110/out.zip)

**Comment by retsyo** [comment]
it seems that `optimize=False` produces right gif

**Comment by radarhere** [comment]
Installing Pillow 4.2.1 from source, I'm unable to replicate.
