### ISSUE TITLE
player?

### ISSUE THREAD

**Issue by seghier** [python-pillow/Pillow#2736]
hello 
how i can use the player script ? and how i can add input and ouput folder

**Comment by wiredfool** [comment]
`player.py` does not appear to have any output. 

The help docs are: `python player.py imagefile(s)`, so something like `python player.py inputdir/*` should play the whole directory.

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/tree/master/Scripts#playerpy says:

> # player.py
>
> A simple image sequence player. You can use either a sequence format like FLI/FLC, GIF, or ARG, or give a number of images which are interpreted as frames in a sequence. All frames must have the same size.

The files under scripts aren't tested or maintained, and may be broken. I just tried player.py on an animated gif (and again with two frames saved as images) and it showed the image in a window but didn't animate it.

**Comment by seghier** [comment]
in your documentaion something about open image sequence but nothing how and if we can view it or not
and the player use tkinter and i am use pyqt4

**Comment by hugovk** [comment]
Closing this as these scripts now live in their own repo at https://github.com/python-pillow/pillow-scripts.

Issues and PRs welcome over there.
