### ISSUE TITLE
Error installing without jpeg support

### ISSUE THREAD

**Issue by expectocode** [python-pillow/Pillow#2751]
### What did you do?
pip install Pillow --glabal-option="build_ext" --global-option="--disable-jpeg"
### What did you expect to happen?
Successful install without jpeg support
### What actually happened?
error: option --disable-jpeg not recognized
### What versions of Pillow and Python are you using?
python3 in a venv, pillow was 4.2.1
Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.
I don't have code for this, it's one line of shell

![screenshot_2017-09-21_00-17-32](https://user-images.githubusercontent.com/15344581/30672104-effe7272-9e59-11e7-9025-55ad068fe662.png)

**Comment by wiredfool** [comment]
You may have to install olefile first, without extra options.

**Comment by aclark4life** [comment]
@wiredfool Is this a bug or won't fix?

**Comment by expectocode** [comment]
Just noticed a typo in my original post - glabal instead of global. Could be related.
