### ISSUE TITLE
Cannot use lambda function for size in Image.new()

### ISSUE THREAD

**Issue by trobertsca** [python-pillow/Pillow#2762]
### What did you do?
    Called Image.new() with a lambda function that returns a Tuple as the argument.
### What did you expect to happen?
    For Image.new() to evaluate the lambda function as if it were a Tuple.
### What actually happened?
    An exception was thrown while Pillow was validating the argument.
### What versions of Pillow and Python are you using?
    Python 3.6.2 Windows x64 and Pillow 4.2.1

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```
from PIL import Image, ImageDraw, ImageFont


dpi = 300
# _nominal measurements are measured in inches and represent the 100% baseline for the UPC-A standard dimensions.
# This size can be reduced to 80% or increased to 200% as needed per the specification.
_nominal_width = 1.469
_nominal_height = 1.02

# Image arguments: 1 is black and white, 1 bit per pixel. We'll start with this and adjust as necessary.
# The lambda function automatically sizes the barcode at 100% magnification per the set dpi.
# (255, 255, 255) is a tuple representing the color white in RBG to fill the new image with.
im = Image.new(1, lambda x=dpi: (_nominal_width * x, _nominal_height * x), (255, 255, 255, 255))
fnt = ImageFont.truetype('Pillow/Tests/fonts/FreeMono.ttf')
d = ImageDraw.Draw(im)
d.text((10, 10), "Test", font=fnt, fill=(255, 255, 255, 255))
im.save('test.png')
```
![pycharm pillow traceback](https://user-images.githubusercontent.com/25038538/30924586-12deec22-a364-11e7-8626-2090102a5d4c.PNG)

**Comment by trobertsca** [comment]
I'm currently working on a fix that would have _check_size evaluate the argument if it is a function, as a somewhat new Python programmer delving into the internals of a large project like this is really interesting.

**Comment by wiredfool** [comment]
What are you trying to achieve by using a lambda rather an a tuple?

**Comment by trobertsca** [comment]
For a clean coding style, I prefer to use lambdas in place of assigning a variable with a simple expression and then passing the variable to a callable. It also seems intuitive that there is no difference between a tuple and an anonymous function that returns a tuple. 

Again, I'm fairly new so if this isn't a very Pythonic way of doing things then I suppose it's not really an issue.

**Comment by wiredfool** [comment]
There's a big difference -- a tuple is an immutable sequence of values, and an anonymous function is not.  Aside from that, there's no point in encapsulating the value in a potentially expensive closure, only to immediately undo that to get the value when nothing other than potential not-in-thread side effects could happen between the calling site and when it's evaluated. 

And furthermore, randomly executing arguments because they're not the type you expect is just asking for bad things to happen from a security point of view.

**Comment by trobertsca** [comment]
That last point is a really good point that I had not considered, thank you. I made the mistake of overlooking the large security risk. I'll go ahead and close the issue.
