### ISSUE TITLE
Image.quantize() doesn't accept a palette

### ISSUE THREAD

**Issue by lxkurko** [python-pillow/Pillow#2770]
Image.quantize() has an option for palette which is used for quantization. However it does not accept a list given by Image.getpalette(), and ImagePalette.ImagePalette (as suggested by documentation) doesn't work either. The reason is apparently that quantize() tries to invoke load() method which does not exist for either of these types.

I did experiments by giving it an Image object (image in palette mode) but it didn't work either.

Also, the documentation sometimes talks about "ImagingPalette" which is apparently a wrong name, such object doesn't apparently exist in the library.

I'm using Pillow 4.0.0(-4) and Python 3.5.3 on Debian 9 "Stretch", x86-64.

**Comment by kkopachev** [comment]
It expects image with palette. Documentation [was fixed here](https://github.com/python-pillow/Pillow/pull/2703)
