### ISSUE TITLE
Quantize should update palette

### ISSUE THREAD

**Issue by kkopachev** [python-pillow/Pillow#2797]
### What did you do?
```python 
# t.png - png image with transparency.
im = Image.open('t.png')
print (im.info['transparency'])
# '\x00\x0f#Af\x99\xce\xfc\xfd\xc1\xdd\x86\xfdk\x94>^#\xcd\xc6\xe2\xb8\xda\xb0\x8c\xaba'
im_rgba = im.convert()
im_p = im_rgba.quantize()
new_im_rgba = im_p.convert()
print (new_im_rgba.mode)
```
### What did you expect to happen?
'RGBA'
### What actually happened?
'RGB'
### What versions of Pillow and Python are you using?
latest master

I noticed [there is code to handle](https://github.com/python-pillow/Pillow/pull/537/files#diff-3fef5f960d5bd8bdfb9c6fadcf96af22R737) that in `convert` for RGB -> P conversion. Looks like it was used for RGBA->P conversion as well, but then RGBA->P got [handled by call to quantize directly](https://github.com/python-pillow/Pillow/pull/573).

**Comment by aclark4life** [comment]
@wiredfool should Quantize update palette? :smile:

**Comment by radarhere** [comment]
I've created PR #3721 to resolve this.
