### ISSUE TITLE
Include Piexif as dependency

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#2800]
I've tried to implement [autorotate functionality](https://github.com/uploadcare/pillow-simd/blob/autorotate/PIL/Image.py#L2200).

My idea was: as we change the orientation of the image pixels, we **should** change or exclude orientation tag from EXIF. Otherwise subsequent calls to `.autorotate()` will rotate image again and again. Moreover, image rotated with `.autorotate()` and then saved with the same EXIF will report wrong orientation.

As Pillow doesn't have EXIF writer (am I wrong?), only EXIF reader, I have two options:

1. Implement lightweight fail-tolerance EXIF editor, which will search for the desired tag and will change only one value from actual orientation to "1", which means "no rotation required". (I already have [Operation tag finder](https://github.com/uploadcare/uploadcare-widget/blob/cbe156faf7485e9035c6625626b541bc04735d6e/app/assets/javascripts/uploadcare/utils/image-processor.coffee#L300) implemented in JS).

2. Use external EXIF writer (and possible reader), like [Piexif](https://pypi.python.org/pypi/piexif) as external dependency for Pillow and regenerate the whole EXIF bytes from modified dict.

Also, I'd like to aks @hMatoba, What do you feel about using Piexif as one of Pillow's dependency?

**Comment by hMatoba** [comment]
Very honored. I started Piexif for Pillow.
https://github.com/python-pillow/Pillow/issues/520

**Comment by homm** [comment]
@hMatoba Thanks for the link to #520, haven't seen this before.

**Comment by hMatoba** [comment]
I think that there isn't a good exif library for Pillow other than Piexif.

- Pure Python and no dependency
- Python ver. 2.7, 3.3, 3.4, 3.5, 3.6

```
from PIL import Image
import piexif
im = Image.open(filename)
exif_dict = piexif.load(im.info["exif"])  // Piexif can load exif from property of 'Image'
exif_bytes = piexif.dump(exif_dict) // Piexif can get exif as bytes
im.save(new_file, "jpeg", exif=exif_bytes)
```

**Comment by homm** [comment]
@wiredfool Any thoughts?

**Comment by wiredfool** [comment]
Tentatively +1, but I'd like to look closer at the apis.

**Comment by radarhere** [comment]
@homm just to let you know, we do now have autorotate functionality - https://pillow.readthedocs.io/en/stable/releasenotes/6.0.0.html#added-imageops-exif-transpose

**Comment by radarhere** [comment]
We seem to have gone with Option 1, so I'm leaning towards closing this. Thoughts from anyone else?
