### ISSUE TITLE
Exception when converting GIF to RGB and saving

### ISSUE THREAD

**Issue by tisdall** [python-pillow/Pillow#2803]
I've reduced the issue down to 2 lines of code:
```python
from PIL import Image
Image.open('plus.gif').convert('RGB').save('plus_thumb.gif', format='GIF')
```
The image with the issue:
![plus](https://user-images.githubusercontent.com/4029388/31668314-e0926098-b31f-11e7-9615-cce39c4113b2.gif)

The exception I get:
```console
# python test5.py 
/usr/local/lib/python2.7/site-packages/PIL/Image.py:967: UserWarning: Couldn't allocate palette entry for transparency
  "for transparency")
Traceback (most recent call last):
  File "test5.py", line 8, in <module>
    Image.open('plus.gif').convert('RGB').save('plus_thumb.gif', format='GIF')
  File "/usr/local/lib/python2.7/site-packages/PIL/Image.py", line 1928, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 465, in _save
    _write_single_frame(im, fp, palette)
  File "/usr/local/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 383, in _write_single_frame
    _write_local_header(fp, im, (0, 0), flags)
  File "/usr/local/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 490, in _write_local_header
    transparency = int(transparency)
TypeError: int() argument must be a string or a number, not 'tuple'
```

This is with Pillow 4.3.0 and Python 2.7.7

**Comment by hugovk** [comment]
Running with Python 3 it prints a warning (aside: whose text we should fix a bit):
```
/Users/hugo/github/Pillow/PIL/Image.py:967: UserWarning: Couldn't allocate palette entry for transparency
  "for transparency")
Traceback (most recent call last):
  File "2803.py", line 2, in <module>
    Image.open('plus.gif').convert('RGB').save('plus_thumb.gif', format='GIF')
  File "/Users/hugo/github/Pillow/PIL/Image.py", line 1928, in save
    save_handler(self, fp, filename)
  File "/Users/hugo/github/Pillow/PIL/GifImagePlugin.py", line 465, in _save
    _write_single_frame(im, fp, palette)
  File "/Users/hugo/github/Pillow/PIL/GifImagePlugin.py", line 383, in _write_single_frame
    _write_local_header(fp, im, (0, 0), flags)
  File "/Users/hugo/github/Pillow/PIL/GifImagePlugin.py", line 490, in _write_local_header
    transparency = int(transparency)
TypeError: int() argument must be a string, a bytes-like object or a number, not 'tuple'
```

Adding some prints:

```python
from PIL import Image
im = Image.open('plus.gif')

print()
print(im)
print(im.info)
print()

im = im.convert('RGB')

print()
print(im)
print(im.info)
print()

im.save('plus_thumb.gif', format='GIF')
```

Shows the transparency tuple:
```
<PIL.GifImagePlugin.GifImageFile image mode=P size=559x600 at 0x10EAFD358>
{'version': b'GIF89a', 'background': 0, 'comment': b'G44', 'transparency': 255, 'duration': 0}


<PIL.Image.Image image mode=RGB size=559x600 at 0x10EAFD320>
{'version': b'GIF89a', 'background': 0, 'comment': b'G44', 'transparency': (85, 0, 0), 'duration': 0}
```

**Comment by tisdall** [comment]
[Right above the warning code](https://github.com/python-pillow/Pillow/blob/master/PIL/Image.py#L965) is the following:  `del(new.info['transparency'])`

Why is that not fixing the issue?  Does the warning cause the image with the deleted transparency to not be returned and the used later?

**Comment by aclark4life** [comment]
@hugovk Is this a bug?

**Comment by kkopachev** [comment]
is this the same? https://github.com/python-pillow/Pillow/pull/2704

**Comment by radarhere** [comment]
I have created PR #3187 to address this, which has the effect of correctly applying `del(new.info['transparency'])`.

**Comment by radarhere** [comment]
With #3187 merged, the TypeError is now fixed. The image is now output as in [the earlier comment by @hugovk](https://github.com/python-pillow/Pillow/issues/2803#issuecomment-337244989). If the UserWarning 'Couldn't allocate palette entry for transparency' is accepted behaviour, then this issue is resolved.

**Comment by radarhere** [comment]
There's a fundamental problem with this situation. Outside of the plus symbol, color index is 255, the transparency. Inside of the plus symbol, the color index is 0.

Both of those entries are (0, 0, 0) in the palette though. So once you convert to RGB, they become the same, and we're not able to get the original image back again. This is a limitation of converting P to RGB.

So I think the correct output of this code should an empty plus symbol.

**Comment by radarhere** [comment]
#5552 resolves this.
![plus_thumb](https://user-images.githubusercontent.com/3112309/123639732-d44b5200-d863-11eb-89c1-93ab590f7bd4.gif)
