### ISSUE TITLE
Error while saving multiple JPEGs as a multi-page PDF

### ISSUE THREAD

**Issue by ixio** [python-pillow/Pillow#2804]
### What did you do?

I wanted to make a PDF out of multiple JPEG images, I loaded the JPEGs and try to save the first one as a PDF with the other images appended.

### What did you expect to happen?

I expected a multi-page PDF, each page being one of my input images.

### What actually happened?

I got the following error:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "[...]/lib/python3.5/site-packages/PIL/Image.py", line 1933, in save
    save_handler(self, fp, filename)
  File "[...]/lib/python3.5/site-packages/PIL/PdfImagePlugin.py", line 60, in _save_all
    _save(im, fp, filename, save_all=True)
  File "[...]/lib/python3.5/site-packages/PIL/PdfImagePlugin.py", line 187, in _save
    Image.SAVE["JPEG"](im, op, filename)
  File "[...]/lib/python3.5/site-packages/PIL/JpegImagePlugin.py", line 609, in _save
    info = im.encoderinfo
AttributeError: 'JpegImageFile' object has no attribute 'encoderinfo'
```

### What versions of Pillow and Python are you using?

Pillow 4.3.0 on Python 3.5

### How to reproduce this and more

I had the problem with JPEGs of mine but even with two very simple JPEGs generated with imagemagick I get the errors. What's interesting is if I try to make a TIFF first I can then make a PDF.

```python
# The bug should be on any two random JPEGs, I generated the following to test:
# > convert -size 100x100 xc:#990000 a.jpeg
# > convert -size 100x100 xc:#009900 b.jpeg

from PIL import Image

Image.open('a.jpeg').save('test.pdf', save_all=True, append_images=[Image.open('b.jpeg')])
# AttributeError: 'JpegImageFile' object has no attribute 'encoderinfo'

a = Image.open('a.jpeg')
b = Image.open('b.jpeg')
a.save('test.pdf', save_all=True, append_images=[b]) # ERROR 
a.save('test.gif', save_all=True, append_images=[b]) # SUCCESS
a.save('test.pdf', save_all=True, append_images=[b]) # ERROR
a.save('test.tiff', save_all=True, append_images=[b]) # SUCCESS
a.save('test.pdf', save_all=True, append_images=[b]) # SUCCESS
```

Test JPEGs you can use:

![b](https://user-images.githubusercontent.com/5647930/31671519-6cae8b30-b35a-11e7-8335-e069187cb071.jpeg)
![a](https://user-images.githubusercontent.com/5647930/31671521-6cdb21a4-b35a-11e7-8ef0-998d4f6bd8f4.jpeg)

**Comment by CrazyJannis44** [comment]
I've got sucha bug too... I want to make a hypermark pdf to an image pdf. That's my code:

`
import shutil
from pathlib import Path
from sys import argv

from PIL import Image
from pdf2image import convert_from_path

pages = convert_from_path(argv[1], 500)
temp_path = Path(str(Path(argv[0]).parent.absolute()) + "/temp/")
if temp_path.exists():
    try:
        shutil.rmtree(temp_path)
    except OSError as e:
        print("Error beim löschen des alten temp ordners")
        exit()

images: Image = []
for i in range(1, len(pages)):
    images.append(pages[i].convert("RGB"))

out = str(Path(argv[1]).absolute()) + ".pnged.pdf"
with open(out, 'w+b') as out_file:
    pages[0].convert("RGB").save(out_file, save_all=True, append=images)
try:
    shutil.rmtree(temp_path)
except OSError as e:
    print("Error beim löschen des temp ordners")
`

**Comment by radarhere** [comment]
The previous comment has been turned into a new issue - #5409
