### ISSUE TITLE
Nose is deprecated

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#2812]
http://nose.readthedocs.io/en/latest/index.html

Nose is deprecated, and it has a couple of failure modes that are kind of annoying. We should look at possible replacements that handle our needs:

* Parallel execution
* coverage
* unittest2 based

**Comment by hugovk** [comment]
A couple of candidates, [nose2](https://github.com/nose-devs/nose2) and [pytest](https://github.com/pytest-dev/pytest).

| thing | nose2 | pytest |
| --- | --- | --- |
| parallel execution | [yes](https://nose2.readthedocs.io/en/latest/plugins/mp.html) | [yes](https://docs.pytest.org/en/3.0.0/xdist.html) |
| coverage | [yes](https://nose2.readthedocs.io/en/latest/plugins/coverage.html) | [yes](https://pytest-cov.readthedocs.io/en/latest/readme.html) |
| unittest2 based | [yes](https://docs.pytest.org/en/latest/faq.html#how-does-pytest-relate-to-nose-and-unittest) | [yes](https://docs.pytest.org/en/latest/faq.html#how-does-pytest-relate-to-nose-and-unittest) |
| monthly pip installs | 49,942 | 1,878,740 |
| GH stars | 401 |  1,822 |
| GH forks | 94 | 484 |

By "unittest2 based", I assume you mean it can find and run tests written using the `unittest` module for Python 2.7 and later (unittest2 being the backport for 2.6 and earlier).

Our tests are all written in plain unittest, nose is only used as the runner, so it should be easy enough to switch to either.

**Comment by wiredfool** [comment]
Unittest based implying that we can just use the existing tests without porting.

**Comment by hugovk** [comment]
Fixed by https://github.com/python-pillow/Pillow/pull/2911.
