### ISSUE TITLE
Allow use of generators when saving GIF with append_images

### ISSUE THREAD

**Issue by skywodd** [python-pillow/Pillow#2828]
### What did you do?

I was trying to save a GIF using ``save_all=True`` and ``append_images=frames``, with ``frames`` being a generator function, not a list.

### What did you expect to happen?

I expected the frames to be saved in the GIF file.

### What actually happened?

I got bitten by Pillow with the following exception:

```
Traceback (most recent call last):
  File "C:\Users\Fabien\Desktop\gif_resize_pillow.py", line 24, in <module>
    om.save("out.gif", save_all=True, append_images=frames)
  File "C:\Python36\lib\site-packages\PIL\Image.py", line 1893, in save
    save_handler(self, fp, filename)
  File "C:\Python36\lib\site-packages\PIL\GifImagePlugin.py", line 451, in _save_all
    _save(im, fp, filename, save_all=True)
  File "C:\Python36\lib\site-packages\PIL\GifImagePlugin.py", line 463, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "C:\Python36\lib\site-packages\PIL\GifImagePlugin.py", line 396, in _write_multiple_frames
    for imSequence in [im]+im.encoderinfo.get("append_images", []):
TypeError: can only concatenate list (not "generator") to list
```

Problem come from [this line](https://github.com/python-pillow/Pillow/blob/master/PIL/GifImagePlugin.py#L398) in ``GifImagePlugin.py``, in the function ``_write_multiple_frames``:

``for imSequence in [im]+im.encoderinfo.get("append_images", []):``

Instead of using list concatenation, it should use ``itertools.chain``:

``for imSequence in itertools.chain([im], im.encoderinfo.get("append_images", [])):``

This allow the use of generator functions, but also tuples with ``append_images``.

### What versions of Pillow and Python are you using?

Pillow (4.3.0)

Example script triggering the bug:

```python
from PIL import Image, ImageSequence

size = 320, 240
im = Image.open("in.gif")
frames = ImageSequence.Iterator(im)

def thumbnails(frames):
    for frame in frames:
        thumbnail = frame.copy()
        thumbnail.thumbnail(size, Image.ANTIALIAS)
        yield thumbnail

frames = thumbnails(frames)

om = next(frames) # Handle first frame separately
om.info = im.info # Copy sequence info
om.save("out.gif", save_all=True, append_images=frames) # Boom!
```

**Comment by radarhere** [comment]
Thanks for your clear explanation of the issue. I've created PR #2829 to ensure support for append_images generators for all formats that use it.
