### ISSUE TITLE
Getting clipped text when drawing

### ISSUE THREAD

**Issue by stefko18** [python-pillow/Pillow#2834]
### What did you do?
I am drawing text on a image that I created.

### What did you expect to happen?
Expectation was to see the text written on the image.

### What actually happened?
Text is clipped at the top. Sometimes just one pixel, sometimes far more. 

### What versions of Pillow and Python are you using?
Python 2.7.6, Image.VERSION returned 1.1.7

```python
import Image, ImageDraw, ImageFont
#grid is a const of px to define the size of a cell
w = grid*(obj_len+2)
h = grid*(obj_len+2)

im = Image.new("RGB", (w, h), bck_col)
draw = ImageDraw.Draw(im)

fntText = ImageFont.truetype(FREESANS, size)

x = row*grid
y = col*grid
offset = #a number to place the text in the corners

if do_draw:
    draw.text((x+offset,y), a_or_s, font=fntText, fill=clr)
    draw.text((x+1,y+offset), deg, font=fntText, fill=clr)

```

Resulting problematic area (observe the S in the image below or the 0°37' value):

![8vtkk](https://user-images.githubusercontent.com/24191063/32419168-23c14c0c-c276-11e7-8271-c6ae123091da.png)

**Comment by hugovk** [comment]
What `Image.PILLOW_VERSION` version?

**Comment by stefko18** [comment]
It says 2.3.0

**Comment by hugovk** [comment]
Pillow [2.3.0](https://github.com/python-pillow/Pillow/releases/tag/2.3.0) is quite old, nearly four years old, please can you upgrade first and retest?

```
python -m pip install -U pip setuptools wheel

pip install -U pillow
```

**Comment by stefko18** [comment]
Upgraded to 4.3.0 and the issue persists.

**Comment by hugovk** [comment]
Please could you update your example code to a minimal, self-contained (as far as possible) runnable example? I see at something like 13 undefined variables. This might help: https://stackoverflow.com/help/mcve

**Comment by stefko18** [comment]
I have tried but strangely it draw the text alright. not that it would prove something. The drawing program is quite complicated and goes above 1000 lines, uses tens of variables and does circles, lines, pasting, resizing, arranging and rearranging ... I included something of each (with reduced complexity) and drawed two pictures at the same time: one example and one real, the example was ok, the real thing was clipped. 

I don't get it .. do you have at least a clue what this could be? It makes all my drawing effort useless.

**Comment by hugovk** [comment]
That does help and does prove (or at least suggest) something: there's a bug in your code and not Pillow. I don't think all your drawing effort is useless, you've managed to get the example code working!

It sounds like your code is quite complex, or at least long, and let's build on the success of the small example. Reuse it. Turn it into a function and use that for the drawing. Then we know at least one small part works. If the end result is wrong, then perhaps its inputs are wrong. So turn other bits of code into small functions, that way you can check them so you know they do one thing only, and do it well.

Have a read of [this](https://ericlippert.com/2014/03/05/how-to-debug-small-programs/) and follow the advice.

**Comment by stefko18** [comment]
Thanks, that's a very constructive way of looking at it. You right, there is a way forward. Just by the way, it's not a single function, it's a structure of multiple classes and does reuse all the time. Just saying I am not a profi, but not a beginer either. 

I leave this open for some time, might need advice once I pinpoint the bug.

**Comment by stefko18** [comment]
Well, I finally managed to reproduce the behaviour. Before I was making the mistake to try only bigger font sizes, even I mostly use font size of 9px. So, I retried today with 9px and it's there. I slowsly cut out other drawing components like elipses, lines, colors, background, arranging and rearanging to find out that the problem it's just that with small font sizes the tops get clipped. 

See attached example drawing (see what should be "TTTTTTTSSSSSSSS"). Below self-contained drawing code example. You need a outpath and a font file to run it.

![example](https://user-images.githubusercontent.com/24191063/32487197-430827be-c3a9-11e7-9796-8144beae2138.png)

    def draw_example():
        #OUT_PATH = 'your path'
        #FREESANS = path to font file #'/FreeSans.ttf'
        size = 9
        fntText = ImageFont.truetype(FREESANS, size)
        #background is light cyan just to diff from github background, works with anything
        im = Image.new("RGB", (150, 50), (224,255,255)) 
        draw = ImageDraw.Draw(im)
        
        x = 5
        y = 20
        
        draw.text((x,y), "TTTTTTTSSSSSSSS", font=fntText, fill="black")
            
        del draw
        im.save(OUT_PATH+"example.png", "PNG")

**Comment by wiredfool** [comment]
I can't replicate this on OSX or Ubuntu 16.04, with freetype 2.8.1,  and 2.6.1 respectively. These are screen shots at 4x enlargement:
OSX:
![screen shot 2017-11-07 at 9 04 43 pm](https://user-images.githubusercontent.com/19792/32517770-52fe0034-c3ff-11e7-9a9a-97d40183a7a8.png)

Ubuntu:
![screen shot 2017-11-07 at 9 03 05 pm](https://user-images.githubusercontent.com/19792/32517706-1f8e7a26-c3ff-11e7-8ef2-8690b5d1d2ff.png)

**Comment by hugovk** [comment]
I could reproduce it on macOS at size 9 with a downloaded FreeSans.ttf, but not at other sizes and not with another ttf from the test suite.

A quick workaround would be just to use another font or size, or draw everything twice as big but then resize down at the very end.

**Comment by wiredfool** [comment]
It's possible that the metrics on the downloaded font are incorrect. I'm using FreeSans.ttf from ubuntu 16.04, since that's what I have hanging around. 

[FreeSans.ttf.gz](https://github.com/python-pillow/Pillow/files/1451738/FreeSans.ttf.gz)

**Comment by hugovk** [comment]
I think I grabbed this one https://github.com/opensourcedesign/fonts/blob/master/gnu-freefont_freesans/FreeSans.ttf

**Comment by wiredfool** [comment]
Yep, that font is different, and shows the problem. 

For the one I had, the metrics are: Height 11, Ascent 9, Descent 2. For the one you posted, Height 13, Ascent 9, Descent 3.

**Comment by stefko18** [comment]
Before I turned here I had this issue with several freely available fonts. 

Also I think that the issue exists at other sizes as well, but it's not so visible and it's also harder to tell if the top pixel is missing from a 18px font size or not. 

Below is 18px zoomed to 800%, look at the "S" bottom and top difference - shouldn't there by the four horizontal smoothing pixels on top as well? Don't know, but might be clipped as well. I wouldn't notice it at 18px if I wouldn't see it happening at 9px.

![example](https://user-images.githubusercontent.com/24191063/32536131-3c3bb3a6-c45d-11e7-8372-ef6a8d37dcce.PNG)

**Comment by stefko18** [comment]
So, I solved this by using another font. But just to let you know I have tried around 20 free fonts and just 3 didn't have this issue at 9px. 

Of those three two have been also decently readable at 9px. So, anybody else looking for a workaround to this, try Chivo or Libre Baskerville.
