### ISSUE TITLE
Polyline joints are ugly

### ISSUE THREAD

**Issue by nawagers** [python-pillow/Pillow#2840]
When drawing a Polyline using PIL.ImageDraw.Draw.line(xy, fill=None, width=0), the segment joints are two rectangles that join together in the center of their widths. This leaves an ugly gap. To make it look pretty it could either extend the rectangle sides until they meet, or draw a radiused joint. Extending the sides could lead to very long extensions on highly acute angles, but a radiused joint works well in every case I can think of.

I suggest changing the function to:

`PIL.ImageDraw.Draw.line(xy, fill=None, width=0, radiused=False)`

and then for each point in xy[1:-2] draw an ellipse centered at the point and whose width and height are the same as the line width. Here is a snippet of how I did it externally

```
draw.line(plot,'black', Weight)
for joint in plot[1:-2]:
    draw.ellipse((joint[0]-Weight/2,joint[1]-Weight/2,
                  joint[0]+Weight/2,joint[1]+Weight/2),'black')
```

**Comment by wiredfool** [comment]
Feel free to send a PR for this.

**Comment by nawagers** [comment]
Will do. I need to get a proper dev environment (I'm running Windows) and add some unittests, then I'll submit a PR.

**Comment by hugovk** [comment]
Please see PR https://github.com/python-pillow/Pillow/pull/3250.
