### ISSUE TITLE
pep257 and pep8 updates wanted?

### ISSUE THREAD

**Issue by nawagers** [python-pillow/Pillow#2845]
I'm willing to spend time writing up some of the docstrings and figured I could do any pep8 formatting while I'm at it. Is this something that the project leaders would like? What other documentation aspects are in most need?

**Comment by wiredfool** [comment]
We've had quite a lot of PRs for Pep8, most of what's left is because hard Pep8 formatting is uglier than relaxing the rules. 

As for docstrings, we've got quite a lot of them being pulled out for the documentation. Are there any in particular that you feel need improvement?

**Comment by nawagers** [comment]
I've mostly been using Image, ImageDraw, and ImageFont. I've found that some functions don't have any docstrings in master or 4.3.x branches. I don't know where readthedocs is pulling from, but it seems inconsistent with the code. Running 'pydocstyle' on them flags lots of errors. In "Contributing.md" there is no mention of a style such as Google's Docstring style: [https://google.github.io/styleguide/pyguide.html?showone=Comments#Comments](url).

**Comment by hugovk** [comment]
Read the Docs pulls from https://github.com/python-pillow/Pillow/tree/master/docs

Do we want to choose some pep8 rules to exclude, or conversely choose some rules to include (or modify), and enforce them on the CI with pycodestyle?

**Comment by hugovk** [comment]
If so, looking at the current ones in the codebase, I'd suggest these could be ignored:

```
8       E122 continuation line missing indentation or outdented
7       E127 continuation line over-indented for visual indent
161     E128 continuation line under-indented for visual indent
6       E131 continuation line unaligned for hanging indent
23      E402 module level import not at top of file
271     E501 line too long (87 > 79 characters)
```

(With possibly changing `E501 line too long (87 > 79 characters)` to a bigger upper limit)

And keep these:
```
2       E101 indentation contains mixed spaces and tabs
1       E129 visually indented line with same indent as next logical line
8       E201 whitespace after '('
1       E203 whitespace before ','
3       E222 multiple spaces after operator
7       E225 missing whitespace around operator
2       E228 missing whitespace around modulo operator
1188    E231 missing whitespace after ','
12      E261 at least two spaces before inline comment
3       E262 inline comment should start with '# '
52      E265 block comment should start with '# '
24      E302 expected 2 blank lines, found 1
9       E303 too many blank lines (2)
89      E305 expected 2 blank lines after class or function definition, found 1
2       E502 the backslash is redundant between brackets
2       E701 multiple statements on one line (colon)
1       E703 statement ends with a semicolon
1       E711 comparison to None should be 'if cond is None:'
35      E722 do not use bare except'
11      E741 ambiguous variable name 'l'
1       W191 indentation contains tabs
4       W291 trailing whitespace
30      W293 blank line contains whitespace
1       W391 blank line at end of file
```

**Comment by aclark4life** [comment]
@nawagers @wiredfool @hugovk I'd like to do something, because I'm a PEP8 kind of a guy (as well as ``yapf``)

**Comment by radarhere** [comment]
Is this now resolved in light of the now built-in lint job, that passes, from #3412?

**Comment by radarhere** [comment]
As of #3733, we are using Black. So I think this can be closed
