### ISSUE TITLE
 python setup.py install: Jpeg2KDecode.c: undefined reference to `opj_stream_create'

### ISSUE THREAD

**Issue by krzychb** [python-pillow/Pillow#2848]
### What did you do?

Attempted to install Pillow on Windows using `setup.py` in a MSYS2 (MINGW32) environment
```
$ python setup.py install
```
### What actually happened?
Compilation failed with:
```
build/temp.mingw-2.7/libImaging/Jpeg2KEncode.o:Jpeg2KEncode.c:(.text+0xfd9): undefined reference to `opj_end_compress'
collect2.exe: error: ld returned 1 exit status
error: command 'C:\\msys32\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1
```
[pillow-compilation.log](https://github.com/python-pillow/Pillow/files/1464226/pillow-compilation.log)

### What versions of Pillow and Python are you using?
* Pillow - `git clone https://github.com/python-pillow/Pillow`
* Python 2.7.13

**Comment by krzychb** [comment]
I have managed to build and install the latest pillow (4.3.0) in the MSYS2 (MINGW32) environment using `pacman`, and  https://github.com/Alexpux/MINGW-packages/pull/3138

**Comment by wiredfool** [comment]
We've only got the basics of msys2 tested, with none of the extra libraries.  What packaging of openjpeg were you using?  I suspect that it's notfinding the shared library at the compile time, even though the shared library was found in the setup file.

**Comment by krzychb** [comment]
Hi @wiredfool,

I am not familiar with openjpeg or packaging of openjpeg. I was just trying to install the latest pillow in MSYS2 (MINGW32) environment.

Pillow is required by https://github.com/blockdiag/sphinxcontrib-blockdiag, but sphinxcontrib-blockdiag failed to install it correctly for me in MSYS2.

The workaround was to install pillow before installing sphinxcontrib-blockdiag.

**Comment by wiredfool** [comment]
If you didn't explicitly install openjpeg from source, it's likely from the msys2 package system.

**Comment by nulano** [comment]
It looks like Pillow is trying to link against `/lib/libopenjp2.a`, but should be linking against `/lib/libopenjp2.dll.a`. While this shouldn't case an issue like this, adding a special case for MinGW solves this. Looking at distutils, it seems to be using UnixCompiler instead of the special case CygwinCompiler, which might handle this correctly (I didn't investigate further).
