### ISSUE TITLE
Can't run on PyPy on ARM

### ISSUE THREAD

**Issue by Depau** [python-pillow/Pillow#2850]
### What did you do?
```console
$ pypy -m pip install pillow
Collecting pillow
  Downloading Pillow-4.3.0.tar.gz (13.9MB)
    100% |████████████████████████████████| 13.9MB 11kB/s 
 Collecting olefile (from pillow)
  Downloading olefile-0.44.zip (74kB)
    100% |████████████████████████████████| 81kB 498kB/s 
Installing collected packages: olefile, pillow
  Running setup.py install for olefile ... done
  Running setup.py install for pillow ... done
Successfully installed olefile-0.44 pillow-4.3.0

$ pypy
Python 2.7.12 (5.6.0+dfsg-4, Nov 20 2016, 10:56:52)
[PyPy 5.6.0 with GCC 6.2.0 20161103] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>>> from PIL import Image
```
### What did you expect to happen?
I expected it to import Image.

### What actually happened?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/pypy2.7/dist-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: function _cffi_pypyinit__imaging or init_imaging not found in library /usr/local/lib/pypy2.7/dist-packages/PIL/_imaging.pypy-41-arm-linux-gnueabihf.so
```

### What versions of Pillow and Python are you using?

- Pillow 4.3.0
- PyPy 5.6.0 with GCC 6.2.0 20161103
- Debian Stretch on a Banana Pi M2 Berry
- Linux Banana 3.10.107-BPI-M2U-Kernel #1 SMP Thu Aug 24 08:01:24 CST 2017 armv7l GNU/Linux
- CPU reports itself as an ARMv7 Processor rev 5 (v7l)
- CPU flags: swp half thumb fastmult vfp edsp neon vfpv3 tls vfpv4 idiva idivt vfpd32

**Comment by wiredfool** [comment]
That's not a combination that I've ever heard of anyone trying. We could probably check on a raspberry pi, but that's about as close to that hardware as I've got access to.

**Comment by Depaulicious** [comment]
Raspberry Pi should have similar hardware. I was trying to run OctoPrint on PyPy as it's much faster (you can really notice the difference), but there's a plugin (the one that I referenced) that depends on Pillow.

**Comment by wiredfool** [comment]
I've tried this on a RaspberryPi2, running Raspbian Stretch, and I can't replicate this issue.

With system pypy, (and pypy-dev) I can build from source on current master (which includes a tweak for fixing compilation on Debian. Tests mostly pass. I can also install from `pip install pillow` (version 4.3.0), tests again mostly pass. The test to fail are mainly memory leaks that are very sensitive, and prone to false positives.

I was unable to get the latest pypy 5.9.0  to run at all -- it failed with a library error.

**Comment by Depaulicious** [comment]
I don't know, I just reinstalled it again in a new virtualenv and I still get

```
>>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/depaulicious/venv/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: function _cffi_pypyinit__imaging or init_imaging not found in library /home/depaulicious/venv/site-packages/PIL/_imaging.pypy-41-arm-linux-gnueabihf.so
```

As a temporary workaround, if it works on your setup, you should be able to build and upload an armhf wheel to PyPI, but that's just a workaround.

**Comment by Depaulicious** [comment]
Any updates on this? What options do I need to pass to get the most verbose build output so I can send it here?

**Comment by Depaulicious** [comment]
By the way, I tried to build it again with `-vf --debug`, build was successful but still  `cannot import name`.

https://hastebin.com/jisajetiba.hs

```
>>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```

I'll try to install all optional libraries and build it again.

**Comment by Depaulicious** [comment]
I tried to install it again after a few months and nothing has changed. I'll try to ask PyPy devs and see if they know why this happens.

**Comment by mattip** [comment]
PyPy 5.6 is quite an old version of PyPy, could you try with a newer version? We have worked quite a bit on the compatibility layer needed to support c-extension modules over the last 15 months, so you may find that [PyPy 5.10](www.pypy.org/download.html) just works, as it does for me on an Odroid board. You simply download the EL or HF (HF is modern, but check [this page](https://blogs.oracle.com/jtc/is-it-armhf-or-armel) to find out if your hardware needs EL), untar the file into a directory, and then call pypy-c -mensurepip to install pip and setuptools, then pypy -mpip install pillow

You seem to be using hf, maybe you should be using el with that hardware?

You could also use nm to find out whether that function is exported: `` nm library PIL/_imaging.pypy-41-arm-linux-gnueabihf.so | grep init_imaging``

@wiredfool - if 5.10 doesn't work for you, could you file an issue (assuming you haven't)?

**Comment by Depaulicious** [comment]
@mattip `nm _imaging.pypy-41-arm-linux-gnueabihf.so | grep init_imaging` outputs
```
0000d0f8 T init_imaging
```
so it is exported. I'll update PyPy and let you know.

**Comment by mattip** [comment]
it seems something is not right with your build tools. Can you build and run any gcc project with a shared library?

**Comment by Depaulicious** [comment]
I fried my Banana Pi a few days ago so I can't test it any more 🤦‍
I will get a new SBC soon and test it again.

**Comment by wiredfool** [comment]
Unfortunately, I'm between pis as well.

**Comment by aclark4life** [comment]
@Depau @wiredfool So we need a raspberry PI to test this?

**Comment by wiredfool** [comment]
We never did get it to replicate on a RaspberryPI.

**Comment by Depau** [comment]
@aclark4life I think so. Maybe you can replicate it with qemu.

**Comment by aclark4life** [comment]
I'm sure we could get someone to donate a Raspberry Pi, we just need a volunteer to fix it. @wiredfool If a Raspberry Pi shows up at your door, do you want to fix this one still?

**Comment by wiredfool** [comment]
I’ve got pis, I just need to retrieve them from teenager.

**Comment by radarhere** [comment]
The BitBucket link no longer works, but it can be seen at https://web.archive.org/web/20200801201818/https://bitbucket.org/pypy/pypy/issues/2762

Also, Pillow no longer supports Python 2.7, and Debian 9 has also stopped receiving security updates.

**Comment by mattip** [comment]
The correct link is now https://foss.heptapod.net/pypy/pypy/-/issues/2762

**Comment by radarhere** [comment]
Note that the BitBucket issue closed, with the comment that it "seems to be a specific system failure"

**Comment by radarhere** [comment]
Given that [we were unable to replicate this](https://github.com/python-pillow/Pillow/issues/2850#issuecomment-345527254), and the last report from the OP is they no longer have an environment to replicate this, closing.
