### ISSUE TITLE
Image.show and Image.save result does not match

### ISSUE THREAD

**Issue by universewill** [python-pillow/Pillow#2857]
I read image from a psd file and changed it into a pillow image.
However,  the Image.show  result and the Image.save result does not match.
I do not know why

**Comment by hugovk** [comment]
Please can you give more detail, and fill in these questions?

### What did you do?

### What did you expect to happen?

### What actually happened?

### What versions of Pillow and Python are you using?

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```
