### ISSUE TITLE
Play of animated Gif very very slow

### ISSUE THREAD

**Issue by mitsus** [python-pillow/Pillow#2859]
HI,
I want play an animated gif using Pillow over Tkinter
I run all on RaspBerry Pi3 with Raspbian GNU/Linux 9 (stretch) (Linux 4.9.59-v7+)
I've installed on my Raspberry board Pillow-4.3.0.

I've an animated gif (that on my windows machine work fine). When try to play it using https://github.com/python-pillow/Pillow/blob/master/Scripts/player.py with python3 it work fine, but it load very very very slow.

Why?
Thanks and Best regards

**Comment by wiredfool** [comment]
1) It's possible that it's an issue with the image file, but we'd need to be able to see it to tell.
2) It's also possible that it's a TK issue, as there's a note in the code that some operations on visible images can be very slow. I suspect that an animated GIF may fall under that note.

**Comment by mitsus** [comment]
Hi,
this is the animated gif file that I used.

![chitchat3](https://user-images.githubusercontent.com/5763982/32920187-adf8ac52-cb28-11e7-87f8-9ee10d4cd44b.gif)

**Comment by radarhere** [comment]
Testing on my machine, I find player.py to be 25% slower. I presume this is not what is meant by 'very very very slow'.

**Comment by hugovk** [comment]
Closing this as these scripts now live in their own repo at https://github.com/python-pillow/pillow-scripts.

Issues and PRs welcome over there.
