### ISSUE TITLE
imresize result different from skimage.transform.resize

### ISSUE THREAD

**Issue by biaojiang** [python-pillow/Pillow#2865]
To reduce the image size using "imresize". However, the results from scipy.misc.imresize and skimage.transform.resize are different, the former seems smoother than the latter, so whether "imresize" used an additional smoothing filter besides the interpolation filter? 
Skimage.transform.resize produced the similar results as Opencv.resize.

Pillow 4.3, Python 3.6.3

```python codes
from scipy.misc import face, imresize
from skimage.transform import resize
face = face(gray=True)
face1 = imresize(face, 0.10) / 255
face2 = resize(face, (face.shape[0]//10, face.shape[1]//10), mode= 'reflect')
```

**Comment by hugovk** [comment]
Do either of scipy and skimage use Pillow? You may be better off reporting this directly to scipy or skimage.

**Comment by wiredfool** [comment]
(closed, does not appear to involve Pillow)

**Comment by biaojiang** [comment]
scipy uses Pillow function of "imresize", but skimage developed their own codes.

**Comment by wiredfool** [comment]
#2718 may add some info.

**Comment by biaojiang** [comment]
#2718 showed the same problem, anyway, I like the Pillow result, but I just wondered what is the difference. By checking the source codes, no big difference in implementing. I reported it to Skimage.
