### ISSUE TITLE
Image.save as tiff image, and the compression parameter does not work

### ISSUE THREAD

**Issue by universewill** [python-pillow/Pillow#2866]
I use pillow to read and save tiff CMYK image. But the output file is as large as 1G while my input tiff is only 150M. 
I use compression 'deflate'. When i set it to 'tiff_lzw', the output file seems to be unreadble and can not open by photoshop.

My code:

```python
o = "image.tif"
img = Image.open("../data/tiff/" + o)
image = ImageCms.profileToProfile(img, 'USWebCoatedSWOP.icc', 'USWebCoatedSWOP.icc', renderingIntent=0, outputMode='CMYK')
image.save('out.tif', compression='deflate')
```

**Comment by universewill** [comment]
I changed the compression from 'deflate' to 'raw', and the result image file is still 1GB.

**Comment by wiredfool** [comment]
What's the compression on the original tiff?  Can you post it, or a small sample of a similar type?

I can take a look at it, but I can't guarantee anything with photoshop,

**Comment by universewill** [comment]
The compression of original tiff is lzw. I wonder if my libtiff is not installed properly. However, i tried several times to reinstall libtiff and pillow, the problem still exists

**Comment by wiredfool** [comment]
if you check the features, it should tell you if it's installed correctly:

```
from PIL import features
print(features.check('libtiff'))
```

There's a current issue where it appears that tiff_lzw decoding is incorrect when using the internal tiff decoder (rather than libtiff). 

'Raw' compression is not actually compressed, it's just an uncompressed bytestream. 

It would be helpful if you could post an example of the image, so that I can tell if there's something that's odd with it.

**Comment by universewill** [comment]
I run the 'features.check' code, and it prints True.
The tiff image file is big for github, i send it to your eric-github@soroos.net email

**Comment by wiredfool** [comment]
There's no way a 150meg image is going to get through email. Check it into a github repo somewhere, or dropbox/gdrive, or something.

**Comment by universewill** [comment]
i use drop box to share this tiff image file with you, please check your email.
Or try this link: https://www.dropbox.com/s/cfh2qyo2w1a5m95/%E5%B8%A6%E5%B8%BD%E5%8D%AB%E8%A1%A3-2134-L.tif?dl=0

**Comment by wiredfool** [comment]
Ok, so what I'm seeing is that it can read the tiff apparently properly, and if saved in a size smaller than about 1/5 the original size, it is apparently correct and openable in Preview.app. 

Above that threshold, it outputs a solid black tiff. I'm not clear if it's Preview that's the problem, or if it's the tiff. Imagemagick is showing that it's not all black, so I'm not sure. 

Saving it at 100%, using 'tiff_lzw' gives a 500mb file, rather than the original 160mb. So there is some compression taking place, as the uncompressed size is more like 1G.

**Comment by universewill** [comment]
I run image.save('out.tif', compression='tiff_lzw') to save it. The out.tif image is about 450mb and is unopennable in photoshop.
Beside, as the origin lzw image is 160mb, why the out.tif image is 400~500mb with tiff_lzw compression?

**Comment by wiredfool** [comment]
As I said, I can't tell about photoshop. But it does appear from Preview that there's something going wrong with the save at large sizes. I suspect that the size issue is correlated with the error. Alternately, it's possible that libtiff's lzw encoder isn't as good as whatever created the image.

**Comment by wiredfool** [comment]
And, fwiw, imagemagick converts the original to a roughly 500mb tiff when running: 
```
convert issue2866.tif -compress LZW t3.tiff
```

This is essentially the same converter as we use (libtiff), so I wouldn't expect different results.

**Comment by universewill** [comment]
OK. Many thanks for your reply!

**Comment by wiredfool** [comment]
Reopening: There's still the issue of apparently incorrect saves

**Comment by cgohlke** [comment]
> Saving it at 100%, using 'tiff_lzw' gives a 500mb file, rather than the original 160mb. So there is some compression taking place, as the uncompressed size is more like 1G.

Maybe that's because the file `带帽卫衣-2134-L.tif` was saved with [horizontal differencing](https://www.awaresystems.be/imaging/tiff/tifftags/predictor.html).

**Comment by universewill** [comment]
Do you find the way to save it as a 150MB tiff image file?
@cgohlke

**Comment by cgohlke** [comment]
> Do you find the way to save it as a 150MB tiff image file?

This seems to work for me:

```
from PIL import Image, TiffTags
TiffTags.LIBTIFF_CORE.add(317)
img = Image.open('issue2866.tif')
img.save('issue2866_out.tif', compression='tiff_lzw', tiffinfo={317: 2})
```

**Comment by universewill** [comment]
The image file size is about 160~180MB now by using your code. But it can not be opened by photoshop @cgohlke

**Comment by cgohlke** [comment]
The resulting image can be opened with IrfanView, ImageMagick, libtiff, tifffile on my system.  Probably Photoshop is too picky about the strip size.

**Comment by universewill** [comment]
What's the meaning of 'strip' size? Is there anyway to make it openable by photoshop?
My client only use photoshop to open the image.
@cgohlke

**Comment by cgohlke** [comment]
You might want to apply the following patch:
```Patch
diff --git a/PIL/TiffImagePlugin.py b/PIL/TiffImagePlugin.py
index 07fb97d1..86c7c837 100644
--- a/PIL/TiffImagePlugin.py
+++ b/PIL/TiffImagePlugin.py
@@ -1453,7 +1453,6 @@ def _save(im, fp, filename):
         ifd[COLORMAP] = tuple(i8(v) * 256 for v in lut)
     # data orientation
     stride = len(bits) * ((im.size[0]*bits[0]+7)//8)
-    ifd[ROWSPERSTRIP] = im.size[1]
     ifd[STRIPBYTECOUNTS] = stride * im.size[1]
     ifd[STRIPOFFSETS] = 0  # this is adjusted by IFD writer
     # no compression by default:
```
Works for me with libtiff-4.0.9.

**Comment by universewill** [comment]
Awesome! That really works. Thanks for your reply. @cgohlke 
However, i have to change the image to rgb and do some operation with opencv.
But when i transfer the image back, and save it the same way,  the image file is still can not be opened by photoshop.
The code is as bellow:
```
    o = "带帽卫衣-2134-L.tif"
    TiffTags.LIBTIFF_CORE.add(317)
    img= Image.open("../data/tiff/" + o)
    img = ImageCms.profileToProfile(img, 'USWebCoatedSWOP.icc', 'sRGB Color Space Profile.icm', renderingIntent=0,
                                    outputMode='RGB')
    mat = np.asarray(img)
    print mat.shape, mat.dtype

    matpil = Image.fromarray(mat, "RGB")

    image = ImageCms.profileToProfile(matpil, 'sRGB Color Space Profile.icm', 'USWebCoatedSWOP.icc', renderingIntent=0,
                                    outputMode='CMYK')

    TiffImagePlugin.WRITE_LIBTIFF =True
    image.save('out.tif',compression='tiff_lzw', tiffinfo={317: 2})
```

**Comment by cgohlke** [comment]
> the image file still can not be opened by photoshop.
> The code is as bellow:

Works for me.

**Comment by universewill** [comment]
You mean you tried my code and the out.tif image file can be opened by photoshop?
That's weird.

For  me, in the code below, the out0.tif can be opened while out.tif cannot be opened.

```
    o = "带帽卫衣-2134-L.tif"
    TiffTags.LIBTIFF_CORE.add(317)
    img= Image.open("../data/tiff/" + o)
    img.save('out0.tif', compression='tiff_lzw', tiffinfo={317: 2})
    img = ImageCms.profileToProfile(img, 'USWebCoatedSWOP.icc', 'sRGB Color Space Profile.icm', renderingIntent=0,
                                    outputMode='RGB')
    mat = np.asarray(img)
    print mat.shape, mat.dtype

    matpil = Image.fromarray(mat, "RGB")

    image = ImageCms.profileToProfile(matpil, 'sRGB Color Space Profile.icm', 'USWebCoatedSWOP.icc', renderingIntent=0,
                                    outputMode='CMYK')
    image.save('out.tif',compression='tiff_lzw', tiffinfo={317: 2})
```
@cgohlke

**Comment by cgohlke** [comment]
Try to set  `ROWSPERSTRIP` explicitly, e.g. `image.save('out.tif', compression='tiff_lzw', tiffinfo={317: 2, 278: 1})`

**Comment by universewill** [comment]
Yeah, it works! 
Thank to your kindly reply.
@cgohlke

**Comment by aclark4life** [comment]
@universewill This is fixed then? Thanks

**Comment by cgohlke** [comment]
> This is fixed then?

Pillow should set `ROWSPERSTRIP` to something more reasonable than `im.size[1]` or allow to specify the value. Photoshop fails when `ROWSPERSTRIP` is too large.
