### ISSUE TITLE
Publish wheel for Python 3.6 in pypi

### ISSUE THREAD

**Issue by KuttKatrea** [python-pillow/Pillow#2874]
### What did you do?

Tried to install Pillow with pip and easy_install on Python 3.6, on Windows (10)

### What did you expect to happen?

To pip to download and install Pillow's wheel

### What actually happened?

pip downloaded Pillow's source code and tried to compile it's native extensions, resulting in an error because of `zlib` library being missing

### What versions of Pillow and Python are you using?

Pillow 3.4.2, Python 3.6, Windows 10

**Comment by radarhere** [comment]
What operating system are you using?

**Comment by KuttKatrea** [comment]
I'm using Windows 10, sorry that I forgot to mention that...

**Comment by hugovk** [comment]
Please can you paste the full output? Are you using something like mingw,  or the default command prompt?

**Comment by hugovk** [comment]
And there already are wheels for Python 3.6 on PyPI, you could download the right one manually and try pip install filename.whl.

https://pypi.python.org/pypi/Pillow/4.3.0

**Comment by KuttKatrea** [comment]
Right, I was still using version 3, let me upgrade and test

**Comment by hugovk** [comment]
@KuttKatrea Any luck?
