### ISSUE TITLE
Failed binding libraqm to Pillow 4.3.0

### ISSUE THREAD

**Issue by houyining** [python-pillow/Pillow#2876]
After installing libraqm in `/usr/local/lib` successfully, and re-installed Pillow with `pip install Pillow --no-cache-dir`,  libraqm doesn't work.

**Install libraqm**
![image](https://user-images.githubusercontent.com/3396931/33525370-07b7674a-d869-11e7-99c7-8076057d085b.png)

**Install Pillow**
![image](https://user-images.githubusercontent.com/3396931/33525375-32e39600-d869-11e7-99f4-c7b08d2cf15c.png)

**Doesn't work**
![image](https://user-images.githubusercontent.com/3396931/33525381-4c6bf180-d869-11e7-8f19-1db21b884e65.png)

**what should I do additional to binding libraqm to Pillow correctly?**

### What versions of Pillow and Python are you using?
Pillow: 4.3.0
Python: 2.7.10
System: OS X 10.11.6

**Comment by wiredfool** [comment]
None of the precompiled Pillow binaries have support for libraqm, you need to build pillow from source after installing raqm.

**Comment by houyining** [comment]
@wiredfool Thanks for your answer!
