### ISSUE TITLE
Compilation environment for PyPi .so library wheel cache needs specification

### ISSUE THREAD

**Issue by acheronmedia** [python-pillow/Pillow#2879]
### What did you do?

Compared image processing execution time (color correction, resize, watermarking) between Pillow installed with PyPi wheel cache and Pillow installed with locally compiled .so libs.

### What did you expect to happen?

No difference in execution time.

### What actually happened?

When installed with "official" precompiled .so libs (manylinux wheel cache), the performance was 3 times better.

### What versions of Pillow and Python are you using?

Python 3.5.4, Pillow 3.4.2 and 4.3.0.

### Problem definition

Noticed 3x execution difference of our Pillow based image processing application, between FreeBSD and Gentoo Linux. FreeBSD was 3x slower on the same hardware. In both cases Pillow was installed in a virtualenv using pip, with no special options:

```
pip install Pillow
```

Upon inspection I noticed that on Linux, pip was pulling in pre-compiled .so libs, whereas on FreeBSD it compiled locally. When I compiled locally on Gentoo as well, image processing slowed down to match that on FreeBSD (using -vvv to check the compiler output):

```
pip install --force-reinstall -vvv --no-binary :all: -U Pillow
```

When I tried adding -O3 to CFLAGS, the execution time was improved 3x:

```
CFLAGS="-O3" pip install --force-reinstall -vvv --no-binary :all: -U Pillow
```

Same (fast) execution time with pre-compiled .so libs (no local compilation):

```
pip install --force-reinstall -vvv --no-cache-dir U Pillow
```

Testing the CFLAGS addition both on Gentoo Linux and FreeBSD yielded same (fast) execution time. My conclusion is that by compiling locally and adding CFLAGS="-O3" yielded 3x faster Pillow (for our use case), than compiling locally without -O3 OR installing on Linux with officially precompiled .so libs.

The test case takes a large JPEG (10k x 10k) and does the following transformations:

* im.resize() -- from source size to web-optimized size
* ImageEnhance.brightness()
* ImageEnhance.contrast()
* ImageEnhance.color()
* ImageFilter.GaussianBlur() and ImageFilter.UnsharpMask() variation
* im.paste() -- watermarking

Another test involving just resizing yielded same execution difference. The test case size is not special, our production use case takes images in the range of anywhere from 4 megapixels up to tested 100 megapixels, with average images being 16 - 20 megapixels.

I couldn't find anywhere in the source code how compilation options are defined for the manylinux wheel cache, whether really -O3 is added or I was just lucky with trying that first.

At any rate I would like to have locally compiled libs as fast as possible (with reasonable CFLAGS), and also to modify the official FreeBSD Pillow port (graphics/py-pillow) to match the execution speed of Pillow on Linux, but I do not want to deviate from officially recommended compilation environment.

So I'm not really sure what kind of issue I'm reporting here. Documentation lacking on precompiled wheel cache options? Thanks.

**Comment by acheronmedia** [comment]
It appears this is maybe a non-issue. After a few more tests I figured out what's going on. By itself, running pip in a virtualenv does not set any CFLAGS, not even the usually default -O2. I missed to observe that. So this is not about -O3 at all, it's about -O2 vs no -O at all.

Still, the 3x performance difference is quite interesting, even for -O2 vs no -O.

I am assuming the manylinux caches are built with at least -O2. If you think this is indeed so and not an issue, please close.

**Comment by wiredfool** [comment]
Interesting. That's a much larger effect from the -O flags than I've ever seen. (Generally, about 10% or so, from debug version to -O3)

The official binaries are produced from the pillow-wheels repo https://github.com/python-pillow/pillow-wheels, on travis, but helpfully enough, the actual compilation commands are not in the build logs there, so it's not clear what the optimization levels actually are. Flags for the freebsd port are up to the port maintainers, I have no idea what they're actually using there. 

If you're sensitive to the performance, you may want to investigate the smid version of pillow, https://github.com/uploadcare/pillow-simd .

**Comment by acheronmedia** [comment]
In conclusion, the problem is really pip. Because on Linux it pulls in (-O2 I assume) precompiled libs, while on FreeBSD it doesn't and compiles locally, but on both systems does not set any -O when it compiles locally.

Both FreeBSD and Gentoo ports do set CFLAGS (and they don't use pip). So this issue does not affect the official ports as I initially missed to observe. Only pip-installed stuff.

So users of "unsupported" systems (I'm guessing that's what's going on) will have to be careful to know this difference and to include sane CFLAGS in their virtualenv. This difference was a bit unexpected, I do remember pip always compiling even on  Linux. This must've changed sometime in the past year or two.

Also, btw, there is no statistically significant difference between -O2 and -O3 in my test case. Only between no -O and -O2 | -O3. There is also ~15% of improvement with -march=native on a haswell Xeon E3-1270 (which we have on the servers).

Thanks for recommending pillow-simd. I'll definitely take a look at it, because performance is indeed crucial in our case as even a few seconds of difference, on the scale of tens of seconds it takes to process an image, is very helpful.

As far as this issue is concerned, I'd stand by the recommendation to document compilation options used for official binaries.

**Comment by wiredfool** [comment]
The linux wheels were added in the last couple of years.

I'm not actually sure what the actual option flags are on the official binaries, since they're not visible in the build logs. It's going to take a bit of digging to enable that in the package we're using.

**Comment by aclark4life** [comment]
@acheronmedia OK to close then?

**Comment by acheronmedia** [comment]
Yes, thank you.
