### ISSUE TITLE
"cannot determine EPS bounding box" error on a valid file

### ISSUE THREAD

**Issue by IIanFumenchu** [python-pillow/Pillow#2881]
### the error
I do a `Image.open('file.eps')` and I get a "cannot determine EPS bounding box" error

The problem is in the Header of the eps file, some eps files have an empty line after the first line, like this:
````
%!PS-Adobe-2.0 EPSF-1.2

%%Title: PFB_4C+SW
%%Creator: FreeHand 10.0
%%CreationDate: 2/21/03 11:28 AM
%%BoundingBox: 0 0 74 35
%%FHPathName:Daten:arbeit:L.W:PFB_4C+SW
%ALDOriginalFile:Daten:arbeit:L.W:PFB_4C+SW
%ALDBoundingBox: -5 -6 80 40
%%FHPageNum:1
%%DocumentSuppliedResources: procset Altsys_header 4 0
%%ColorUsage: Color
````

is it still a valid eps with the empty line as second line? and in `EpsImagePlugin` is a bug? Or the empty line isn't allowed in a valid eps file?

### the solution
`EpsImageFile` exit from the while and stop to read the next lines if he doesn't find a `%` as first character.
to correct the error we can ignore empty lines, we can add this code on line 275 of `EpsImagePlugin`
````
while s == '':
    s = fp.readline().strip('\r\n')
````
as here:
````
                elif s[0] == '%':
                    # handle non-DSC Postscript comments that some
                    # tools mistakenly put in the Comments section
                    pass
                else:
                    raise IOError("bad EPS header")

            s = fp.readline().strip('\r\n')

--->        while s == '':
                 s = fp.readline().strip('\r\n')

            if s[:1] != "%":
                break

        #
        # Scan for an "ImageData" descriptor
````

**Comment by wiredfool** [comment]
I've looked at this, and it's not clear in the spec if a blank line is valid EPS. It's probably not a bad thing to trap, 

Though, the implementation would have to be different, as fp.readline() on a file at EOF is going to return an empty string causing an infinite loop.
