### ISSUE TITLE
ImageDraw.text adds random characters/bytes to text

### ISSUE THREAD

**Issue by wf-r** [python-pillow/Pillow#2889]
### What did you do?

Create RGB-image, select default font, and add text of form "ABCD_EFG" using ImageDraw.text() as stated below.

### What did you expect to happen?

Black text "ABCD_EFG" to appear in created png.

### What actually happened?

png as attached was created, containing random characters after text:
![test](https://user-images.githubusercontent.com/1708866/34050107-fa71cb34-e1b9-11e7-8a9f-3ed05d25605e.png)

### What versions of Pillow and Python are you using?

Pillow: 4.3.0 (Note: bug does not appear using Pillow 4.2.1)
Python: 3.6.3

### MWE
```python
from PIL import Image, ImageDraw, ImageFont

current_color = (0, 0, 0)

image = Image.new('RGB', (80, 10), "white")

image_draw = ImageDraw.Draw(image)
image_font = ImageFont.load_default()

image_draw.text(
    (10, 0),
    "ABCD_EFG",
    font=image_font,
    fill=current_color)

image.save("test.png")
```

**Comment by wiredfool** [comment]
Can you try with current master, this sounds very like a bug that's been fixed.

**Comment by wf-r** [comment]
Hmm, building on Windows seems to take some work. I will try next week..

**Comment by hugovk** [comment]
At least on macOS High Sierra with Python 3.6.3 I can't reproduce it with Pillow 4.2.1, 4.3.0 or latest master.

version | image
------------ | -------------
4.2.1 | ![4 2 1](https://user-images.githubusercontent.com/1324225/34096713-12c3eda8-e3df-11e7-8366-62cbb5e1a332.png)
4.3.0 | ![4 3 0](https://user-images.githubusercontent.com/1324225/34096720-16dabbc4-e3df-11e7-85c3-8366bcf0e729.png)
master | ![master](https://user-images.githubusercontent.com/1324225/34096722-18ae19b4-e3df-11e7-9ccf-fb1c0a25c0c5.png)

**Comment by wiredfool** [comment]
@hugovk That bug only showed itself in the 32bit builds in docker, so it's unlikely to ever trigger on OSX.

@wf-r you may be able to grab an appropriate post-merge build from here: https://ci.appveyor.com/project/Python-pillow/pillow/build/3148 . If your python version is on there, click on the run, then artifacts, then there are binaries for download.

**Comment by wf-r** [comment]
@wiredfool Sorry, I haven't had time to check with current master. However the bug does no longer appear in 5.0.0, therefore the issue can be closed. Thanks for fixing it.

**Comment by wiredfool** [comment]
Thanks for checking back.
