### ISSUE TITLE
GifImageFile and animated gif with mismatched color palettes

### ISSUE THREAD

**Issue by tomaszhlawiczka** [python-pillow/Pillow#2893]
I'm trying to resize an animated gif file with a different color palette for each frame.

Each frame should be composed with own colors, but because of buildin frames merge (see `GifImageFile.load_end`) colors are messed up.

Python: `3.6`
PIL: `4.4.0.dev0`

```python
from PIL import Image
source = Image.open("src.gif")
w, h = source.size
resized = []
try:
	for i in range(0, 0xffffffff):
		source.seek(i)
		resized.append(source.convert('RGBA').resize((w//2, h//2), Image.ANTIALIAS))
except EOFError:
	pass
resized[0].save("result.gif", "GIF", save_all=True, append_images=resized[1:], loop=1, duration=50)
```

I see following solutions here:
1. Merge color palettes as well and reindex frames to new colors (hard one, losing an original data, might be impossible due to the limit of colors in the palette)
2. First convert each frame from mode `P` → `RGBA` and then make a merge (losing an original data)
3. Move merging to another level of abstraction allowing users to open GIF files exactly how there were composed (opening GIF would require additional actions)

So far I've made a workaround as follow (might be helpful for someone):
```python

# Clear up the GifImageFile.load_end()
from PIL import Image, ImageFile
from PIL.GifImagePlugin import GifImageFile, _accept, _save, _save_all

class AnimatedGifImageFile(GifImageFile):
	def load_end(self):
		ImageFile.ImageFile.load_end(self)

Image.register_open(AnimatedGifImageFile.format, AnimatedGifImageFile, _accept)
Image.register_save(AnimatedGifImageFile.format, _save)
Image.register_save_all(AnimatedGifImageFile.format, _save_all)
Image.register_extension(AnimatedGifImageFile.format, ".gif")
Image.register_mime(AnimatedGifImageFile.format, "image/gif")


# Make merge by my own (losing an original palette 
# doesn't matter for this particular case - having RGBA is good enough):
im = Image.open("src.gif")
last_frame = None
all_frames = []
try:
	for i in range(0, 0xffffffff):
		im.seek(i)
		new_frame = im.convert('RGBA')
		if last_frame is not None and im.disposal_method == 1:
			updated = new_frame.crop(im.dispose_extent)
			last_frame.paste(updated, im.dispose_extent, updated)
			new_frame = last_frame
		else:
			last_frame = new_frame

		# do resizing on new_frame here...

		all_frames.append(new_frame)
except EOFError:
	pass
```

![src](https://user-images.githubusercontent.com/19405886/34098753-b5afd010-e3dd-11e7-88d6-0b4b29484f32.gif)
![result](https://user-images.githubusercontent.com/19405886/34098766-bed63300-e3dd-11e7-9524-c69f9d8b49ca.gif)

**Comment by wiredfool** [comment]
To be clear -- is the image incorrect when reading it in, or when writing back out?

**Comment by tomaszhlawiczka** [comment]
The reading part is incorrect (`GifImageFile.load_end`).

**Comment by JankesJanco** [comment]
@tomaszhlawiczka thanks for the workaround! it saved my day!

**Comment by JankesJanco** [comment]
This workaround helps with some GIFs, but I found some GIFs which are still incorrectly opened or saved even after applying the workaround. I simply just open the gif and then save it, the code looks like this:

```python
gif: Image.Image = Image.open('example.gif')
gif.save('example.saved.gif', save_all=True)
```

here are `example.gif` and `example.saved.gif`:
![bowie](https://user-images.githubusercontent.com/11212456/59613132-a6808e00-911e-11e9-8a7c-b08393d170cc.gif)
![bowie saved_1](https://user-images.githubusercontent.com/11212456/59613145-ada79c00-911e-11e9-839f-7e92cfdd3d8b.gif)

**Comment by radarhere** [comment]
#5333 doesn't completely fix, but does significantly improve the car gif.

**Comment by radarhere** [comment]
I've created PR #5857, which fixes both images listed here, resolving this.

**Comment by bongdang** [comment]
I've just upload my solution on github. [https://github.com/bongdang/gifraw](url)
testing above two animated gifs is ok.
please check it.
