### ISSUE TITLE
CMYK to RGB conversion makes image darker

### ISSUE THREAD

**Issue by vharitonsky** [python-pillow/Pillow#2907]
Tested on two independent images in Pillow == 4.3.0. 
Maybe color profile should be investigated, but documentation is a bit vague on how to do this.
```
from PIL import Image
Image.open('img.jpg').convert('RGB').save('img_rgb.jpg')
Image.open('header.jpg').convert('RGB').save('header_rgb.jpg')
```
https://f001.backblazeb2.com/file/CNNIMAGE/header.jpg
https://f001.backblazeb2.com/file/CNNIMAGE/header_rgb.jpg

https://f001.backblazeb2.com/file/CNNIMAGE/img.jpg
https://f001.backblazeb2.com/file/CNNIMAGE/img_rgb.jpg

**Comment by homm** [comment]
> Tested on two independent images in Pillow == 4.3.0.

Are you sure that you are using 4.3.0? CMYK to RGB conversion [was rewritten in 4.3.0](https://github.com/python-pillow/Pillow/pull/2699) and does not produce such dark result as on your examples.

My results:

![header_out](https://user-images.githubusercontent.com/128982/34360400-9ac6923a-ea71-11e7-8233-d912a6cc8b94.jpg)

Your result:

![header_rgb](https://user-images.githubusercontent.com/128982/34360405-a158b5ce-ea71-11e7-9931-0107893cac80.jpg)

**Comment by vharitonsky** [comment]
Sorry, I didn't test newest PIL with the second image, but first one reproduces the case even in new PIL

```
>>> import PIL
>>> from PIL import Image
>>> PIL.__version__
'4.3.0'
>>> Image.open('img.jpg').convert('RGB').save('img_rgb.jpg')
```

**Comment by homm** [comment]
Result in 4.3 for `img.jpg` is different from 4.2 and identical to Google Chrome render. What exactly is the issue?

**Comment by vharitonsky** [comment]
Seems that CMYK to RGB is a universal problem, sorry to bother you and thanks for the [fix](https://github.com/python-pillow/Pillow/pull/2699)!

**Comment by atulpant** [comment]
Hi @vharitonsky and @homm  . I am also having the same problem with respect to conversion from CMYK to RGB.
I am saving the images present in pdf which are in CMYK mode. When I convert it into RGB using the new and old formula it produces same result. The image getting saved is darker than the image in the pdf. 
Can you help with this problem?

**Comment by homm** [comment]
@atulpant 

> The image getting saved is darker than the image in the pdf.

You are mentioned that the image in PDF is in CMYK. You can't directly compare two images in different color modes, this doesn't make sense, so this is not clear what do you mean. Most likely when you are opening the PDF in a viewer, it converts CMYK image in RGB using a full-featured color management system. The `convert('RGB')` function doesn't use color management and doesn't take color profile into account.

If you want color management, you need [ImageCms](https://pillow.readthedocs.io/en/stable/reference/ImageCms.html) module.

**Comment by atulpant** [comment]
Hi @homm 

First of all thanks for the reply @homm : ) and sorry for replying you back so late.

What I was trying to say was that we have a pdf which we open using fitz(Pymupdf). When we extract images then some of them are in CMYK format which cannot be saved in .png format. Fitz has an option to convert that into RGB and save but when we do this we do not get image exactly as in pdf. The images we saved are darker as compared to the images in pdf.
Is there any way to extract the images from pdf exactly the way they are irrespective of being it cmyk or rgb?
If above is not possible then is there any way to convert the image which has been saved (darker image) as the image shown in pdf?

**Comment by homm** [comment]
If you want color management, you need [ImageCms](https://pillow.readthedocs.io/en/stable/reference/ImageCms.html) module. If you want to «extract the images from pdf exactly the way they are» you don't have to convert colors to RGB and use something else than PNG (TIFF, for example).

**Comment by pvtoan** [comment]
Hi @atulpant , I have exact the same problem as you encountered. 

Could I know if you already fixed this issue? If yes, please let me know the solution.

Thank you!

**Comment by atulpant** [comment]
Hi @pvtoan 
As homm mentioned CMYK and RGB are 2 different color spaces therefore direct comparison is not possible and images will be saved in that way. You can test it with other color spaces such as LAB, HSL or HSV.
Try using pix.WriteImage from Pymupdf to save images exactly from pdf.
