### ISSUE TITLE
Problem installing on MSYS2 with 5.0.0

### ISSUE THREAD

**Issue by lovetox** [python-pillow/Pillow#2925]
### What did you do?

git clone https://github.com/python-pillow/Pillow.git
cd Pillow
python3 setup.py install

### What actually happened?

```
C:\msys64\mingw32\bin/i686-w64-mingw32-gcc.exe -Wno-unused-result -Wsign-compare -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -march=i686 -mtune=generic -O2 -pipe -fwrapv -D__USE_MINGW_ANSI_STDIO=1 -DNDEBUG -IC:/msys64/mingw32/include/freetype2 -IC:/msys64/home/Philipp/Pillow/src/libImaging -IC:/msys64/mingw32/include -IC:/msys64/mingw32/include/python3.6m -c src/_imagingft.c -o build/temp.mingw-3.6/src/_imagingft.o
src/_imagingft.c:32:10: fatal error: dlfcn.h: No such file or directory
 #include <dlfcn.h>
          ^~~~~~~~~
compilation terminated.
error: command 'C:\\msys64\\mingw32\\bin/i686-w64-mingw32-gcc.exe' failed with exit status 1

```

I can post the full log on request, but i think its pretty clear that a file is missing

### What versions of Pillow and Python are you using?

5.0.0, python 3.6.3

i tested the same on 4.3.0/python 3.6.3 which worked **with no problems**

was there some kind of dependency added between 4.3.0 and 5.0.0?

i tried installing  `mingw-w64-i686-dlfcn` which resulted in:

```
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x14e7): undefined reference to `dlopen'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x1504): undefined reference to `dlsym'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x151e): undefined reference to `dlsym'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x1538): undefined reference to `dlsym'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x1552): undefined reference to `dlsym'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x156c): undefined reference to `dlsym'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x1586): more undefined references to `dlsym' follow
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x1605): undefined reference to `dlerror'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x16ab): undefined reference to `dlsym'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x16d4): undefined reference to `dlclose'
build/temp.mingw-3.6/src/_imagingft.o:_imagingft.c:(.text+0x1720): undefined reference to `dlopen'

```

**Comment by wiredfool** [comment]
That header is for dlopen/dlsym, which is used to dynamically load a dll/shared library. Our test on msys was successful:  https://ci.appveyor.com/project/Python-pillow/pillow/build/3266/job/xmpsb838yhyy6694, so I'm not sure what's going on on your system. 

It may be a version thing, as I've found something about it here: https://stackoverflow.com/questions/1397022/mingw-3-4-5-missing-dlfcn-h

**Comment by lovetox** [comment]
hm ok thanks

i will test this on a new env, will reopen if the issue persists.

**Comment by lovetox** [comment]
I found out why your Test is working and it fails on mine

normally you use MSYS either with a mingw32 env or mingw64 env

just set the env in appveyor right before you invoke bash

`- ps: $env:MSYSTEM = "MINGW32"`

or

`- ps: $env:MSYSTEM = "MINGW64"`

this will produce the above mentioned error with MINGW32

**Comment by lovetox** [comment]
for reference this seems a good description of how msys native windows build env work

https://stackoverflow.com/questions/37460073/msys-vs-mingw-internal-environment-variables

**Comment by aclark4life** [comment]
@lovetox Still a problem?

**Comment by lovetox** [comment]
yes, still have the same problem.

I need pillow to be installed in the MSYS MINGW32 or MINGW64 env

in both envs, `pip install pillow` fails

im still at pillow 4.3.0 which installs fine

**Comment by docbrown** [comment]
I'm having this problem with Pillow 7.0 while trying to install WeasyPrint in MSYS2. I've installed the `mingw-w64-x86_64-dlfcn` package, but the build of Pillow fails with the same linker errors noted by OP.

**Comment by docbrown** [comment]
Right after I posted, I was able to solve it by forcing Pillow to link with libdl:

    pip install --global-option=build_ext --global-option="-ldl" pillow
