### ISSUE TITLE
Coveralls is scanning files once for each environment

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#2934]
Comparing https://coveralls.io/builds/14844080 and https://coveralls.io/builds/14827315, it looks like after #2911, Coveralls started scanning files once for each environment, taking the total number of files from 164 to 725.

**Comment by hugovk** [comment]
Codecov seems to be working quite nicely since it was added in https://github.com/python-pillow/Pillow/pull/2528. Shall we just ditch Coveralls? 

Or, we can keep sending coverage to the site, but remove it from the PR status check and switch the badges on the README.

**Comment by wiredfool** [comment]
I took a hack at stripping the leading path up to sitepackages/foo.egg in the coveralls-merge, but it's not working at the moment.

**Comment by aclark4life** [comment]
@radarhere Do we still need to fix this?

**Comment by radarhere** [comment]
Yes.

**Comment by hugovk** [comment]
Can we remove the Coveralls Status API checks from PRs?

![image](https://user-images.githubusercontent.com/1324225/39671648-bf48d16c-5124-11e8-95d7-d9befe84d7b5.png)

https://coveralls.io/github/python-pillow/Pillow/settings

It's sometimes reporting coverage has dropped, and marking PRs as failed, when really coverage has increased.

For example, https://github.com/python-pillow/Pillow/pull/3123 adds lines which are covered by tests. Coverage should increase. Codecov coverage increases. Coveralls coverage decreases.

**Comment by aclark4life** [comment]
Done

![screenshot 2018-05-06 07 06 27](https://user-images.githubusercontent.com/72164/39672631-10699c8a-50fc-11e8-839c-622ebc2125ec.png)

**Comment by radarhere** [comment]
Okay, having experimented with my own Coveralls repo, I've come up with a solution - if someone with authorisation could go to https://coveralls.io/builds/17528306/source?filename=/home/travis/virtualenv/python2.7.14/lib/python2.7/site-packages/Pillow-5.2.0.dev0-py2.7-linux-x86_64.egg/PIL/BdfFontFile.py - they should see a field labelled 'Git repo root directory'.

This issue should then be fixed if you set that to /src/

**Comment by radarhere** [comment]
Ah, sorry, looks like I came to that conclusion too soon. Disregard my previous comment.
