### ISSUE TITLE
DNS changes for python-pillow.org

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#2940]
I've just **moved python-pillow.org from Cloudflare to AWS Route 53** which presents at least one problem, as far as I can tell:

- Cloudflare has a nice CNAME flattening feature and I'm not sure what the equivalent is in AWS Route 53.

In the meantime, I've created a CNAME for www.python-pillow.org and am wondering if anyone has any suggests about how to handle this situation e.g. redirect to www will probably suffice … I think I can do that with S3 and if I don't hear any better ideas, that's probably what I'll do.

Oh, and SSL probably needs some thought/discussion too. (I want to support it.)

**Comment by wiredfool** [comment]
A redirect is probably simplest, since github is hosting the project website.

**Comment by aclark4life** [comment]
@python-pillow/pillow-team Never mind, for now I'm just going to redirect www & python-pillow.org to pillow.readthedocs.io. "One less thing." (I don't want a public facing "marketing" website anymore, unless it's awesome and awesome will take some effort & time.)
