### ISSUE TITLE
TypeError occurred when converting transparent WebP to transparent GIF

### ISSUE THREAD

**Issue by blueset** [python-pillow/Pillow#2949]
### What did you do?

```python
from PIL import Image
from io import BytesIO

image = Image.open('test.webp')
destination = BytesIO()
image.save(destination, 'gif', transparency=0)
```

### What did you expect to happen?

Transparent WebP image is converted to transparent GIF, and stored in `destination`.

### What actually happened?

```python
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 1930, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 468, in _save
    _write_single_frame(im, fp, palette)
  File "/usr/local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 376, in _write_single_frame
    for s in _get_global_header(im_out, im.encoderinfo):
  File "/usr/local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 715, in _get_global_header
    o8(background) + o8(0),
  File "/usr/local/lib/python3.6/site-packages/PIL/_binary.py", line 27, in o8
    return bytes((i & 255,))
TypeError: unsupported operand type(s) for &: 'tuple' and 'int'
```

### What versions of Pillow and Python are you using?

```python
>>> PIL.VERSION
'1.1.7'
>>> PIL.PILLOW_VERSION
'5.0.0'
>>> sys.version
'3.6.4 (default, Dec 19 2017, 15:26:29) \n[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)]'
```

```shell
$ brew info webp
webp: stable 0.6.1 (bottled), HEAD
Image format providing lossless and lossy compression for web images
https://developers.google.com/speed/webp/
/usr/local/Cellar/webp/0.6.0_2 (36 files, 1.9MB)
  Poured from bottle on 2017-11-27 at 16:55:56
/usr/local/Cellar/webp/0.6.1 (38 files, 2.0MB) *
  Poured from bottle on 2017-12-07 at 11:16:14
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/webp.rb
==> Dependencies
Required: libpng ✔
Recommended: jpeg ✔
Optional: libtiff ✔, giflib ✘
```

### Attachments

[test.webp.zip](https://github.com/python-pillow/Pillow/files/1621667/test.webp.zip)

**Comment by wiredfool** [comment]
Your image is an RGBA webp with 8 bits of transparency. What color does '255' correspond to?

**Comment by blueset** [comment]
@wiredfool I was trying to keep the transparency of the WEBP image when the pixel is fully transparent.
This piece of code raises exception with:
* `image.save(destination, 'gif', transparency=0)`
* `image.save(destination, 'gif', transparency=255)`
*  `image.save(destination, 'gif')`

**Comment by wiredfool** [comment]
There are two ways of specifying transparency in an image. One is the alpha channel, or mask, which is essentially a grayscale image for pixel by pixel transparency. The other is for one color to be considered transparent, implemented in the transparency value. Some formats use this transparency value to map one color in the image to a fully transparent value. (Generally, they're formats that store image colors in a palette, and that value corresponds to a palette index) The transparency value has to correspond to the pixel type of the image, in this case it's either a 3 or 4 tuple. (I'm not sure which without digging through the code)

In general, you can't replace an alpha channel with a single transparency number, even just going for the locations with full transparency. In this case though, given that it's just a white background, you can get close with passing in (255,255,255) or (255,255,255,255) for the transparency value.

**Comment by radarhere** [comment]
@homm good work on catching this after the issue had been closed

I have created PR #3385 as a suggestion.

**Comment by radarhere** [comment]
#3385 has now been merged, so this should be resolved
