### ISSUE TITLE
Error when loading image

### ISSUE THREAD

**Issue by matthiasbeyer** [python-pillow/Pillow#2955]
### What did you do?

Using `sigal` to build a gallery. `sigal` uses Pillow in version 4.3.0, though I build it with 5.0.0 as well and it did not work out (see [full history of my issue there](https://github.com/saimn/sigal/issues/287)).

### What did you expect to happen?

No error...

### What actually happened?

See [here](https://github.com/saimn/sigal/issues/287). For the lazy:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/kl0wavrf8a2syn3cfa33hl0b03yyvx80-python-2.7.14-env/lib/python2.7/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file './P1010375.png'
```

### What versions of Pillow and Python are you using?

> an **image** that demonstrates the issue. 

![p1010375-small](https://user-images.githubusercontent.com/427866/34873803-d87c55ce-f796-11e7-9202-11a9435c6836.png)

(Image was resized from ~85MB size)

The code below was executed with pillow 4.3.0 - the same error was produced with 5.0.0, though:

```python
>>> import PIL
>>> from PIL import Image
>>> Image.open('./P1010375.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/nix/store/kl0wavrf8a2syn3cfa33hl0b03yyvx80-python-2.7.14-env/lib/python2.7/site-packages/PIL/Image.py", line 2572, in open
    % (filename if filename else fp))
IOError: cannot identify image file './P1010375.png'
```

**Comment by wiredfool** [comment]
That's a 16 bit per channel RGB image, and Pillow doesn't support multi channel images with more than 8 bpc. It's a longstanding issue.

**Comment by hugovk** [comment]
See https://github.com/python-pillow/Pillow/issues/1888.

**Comment by matthiasbeyer** [comment]
Thanks for the quick reply.

I just exported the image from darktable again with 8 bit (adobe pdf) and with 8 bit sRGB... same issue, though (or I did something terribly wrong).

**Comment by wiredfool** [comment]
Can you post that one?

**Comment by matthiasbeyer** [comment]
![p1010375_01-small](https://user-images.githubusercontent.com/427866/34875303-fdff429c-f79c-11e7-8be1-26666a8ac823.png)

and

![p1010375_02-small](https://user-images.githubusercontent.com/427866/34875323-11f5249c-f79d-11e7-910f-3c29a3f8cb68.png)

Both resized because of upload limit, using `convert P1010375_02.png -resize 25% P1010375_02-small.png`.

**Comment by wiredfool** [comment]
Both of those worked for me.

**Comment by matthiasbeyer** [comment]
Fun times. I have to hit the road now, I will reconfirm this when back home (probably Sunday) thanks for your time and support!

**Comment by matthiasbeyer** [comment]
Hi. This issue still exists. What can we do?

**Comment by matthiasbeyer** [comment]
Fun fact: I just checked old pictures I already processed with sigal and they are adobe RGB 16 bit ... and they worked!

**Comment by matthiasbeyer** [comment]
I tried the following: Exported an images as Adobe RGB and sRGB in both 8 bit and 16 bit (so 4 images). None was recognized.

Using sigal 1.3.0.

**Comment by matthiasbeyer** [comment]
For example, this 16 bit Adobe RGB file gets recognized:

( resized because of upload limit, using `convert ... -resize 25% ...`)

![p1020317_small](https://user-images.githubusercontent.com/427866/36538804-074d40e4-17d5-11e8-96cb-5bc170738552.png)

But others do not.

**Comment by wiredfool** [comment]
There's a recently added mode for PNG and TIFF that's a truncated RGB;16B mode, where it returns an 8 bit/channel image from a 16bit original.

**Comment by wiredfool** [comment]
I think it may be 4.3.0, here: https://github.com/python-pillow/Pillow/blob/master/docs/releasenotes/4.3.0.rst#loading-16-bit-tiff-images

**Comment by aclark4life** [comment]
@matthiasbeyer Still an issue?

**Comment by radarhere** [comment]
I can open and load all of the attached images with Pillow 4.3.0 with Python 2.7 on macOS 10.14. @matthiasbeyer what operating system are you using?

**Comment by radarhere** [comment]
Closing, as I am unable to reproduce, and due to lack of response.
