### ISSUE TITLE
Support for appending to existing PDF / TIFF files

### ISSUE THREAD

**Issue by vashek** [python-pillow/Pillow#2959]
I need the ability to append images as pages to existing PDF files.
I have an implementation for PDFs up to version 1.4. Seems to be working fine as far as I can tell, but if anyone knows of any tools to verify the correctness of a PDF, or in general an idea for how to test this other than verify that I can open the PDF file and it looks right...

Would a pull request be welcome for this?

The same could also easily be done for TIFFs, I believe.

**Comment by radarhere** [comment]
Hi. Have a read of http://pillow.readthedocs.io/en/5.0.0/handbook/image-file-formats.html?highlight=append_images#saving

**Comment by vashek** [comment]
I'm aware of that, but as far as I can tell, you can only create new PDF files (and yes, then append more images to them).
What I have in mind is appending pages to *existing* PDF files.

(I have actually since realized that I'm stupid and what I really need is merge two PDFs into one (or, open a PDF image and append it to another PDF). But appending images to an existing PDF is potentially still at least half a solution, and I have it done, so I might as well contribute it.)

**Comment by radarhere** [comment]
You're right, sorry, I have forgotten that Pillow does not read PDFs. Regarding the TIFF format though, that at least should be able to be handled by Pillow, yes?

**Comment by vashek** [comment]
Well in the sense that you can open a TIFF file and then write it back from scratch while appending another image, yes. If you want to avoid the overhead of reading and writing back, there actually is an existing solution in Pillow called TiffImagePlugin.AppendingTiffWriter, but there is no standard API and I don't even think AppendingTiffWriter is documented. (It is used internally by TiffImagePlugin for writing multipage TIFFs.)

**Comment by vashek** [comment]
So, here's my attempt at an implementation for PDFs. Supports PDFs up to version 1.4. Tested with Python 3.6 and as far as I can tell, works great. The pdfReader module itself is tested with Python 2.7 as well, but not the PdfImagePlugin part. I haven't touched the documentation at all yet.

**Comment by vashek** [comment]
So this has turned into a major rework of PdfImagePlugin. :) I have now added tests and am confident it works nicely, and in fact opens the path for some more new features, such as specifying key+value metadata when saving PDFs, specifying margins or placing on the page and perhaps even opening bitmap PDFs.

Any feedback, please? Pretty please? :)

**Comment by wiredfool** [comment]
I'll take a look.

**Comment by vashek** [comment]
I'm now reasonably satisfied with the result. Documentation and tests are done as well. What do you say?

**Comment by vashek** [comment]
Sorry to nag but... merge please? Or more feedback? Thanks. :)

**Comment by wiredfool** [comment]
I'm not going to have time to look at this until friday at the very earliest.

**Comment by vashek** [comment]
Would it help, hypothetically, if I somehow split this into multiple smaller pull requests?
