### ISSUE TITLE
Convert list of points into a "polygon" list of points

### ISSUE THREAD

**Issue by YuriGagarine** [python-pillow/Pillow#2963]
Hi,

I'd like to draw polygons from a set of points I have but my list is not designed correctly. Indeed my points did'nt link as we draw a curve.

I'd like with any list of points make this coversion : 
points=[(1,1),(200,200),(1,200),(200,1)] => points=[(1,1),(1,200),(200,200),(200,1)]

![test_fusion](https://user-images.githubusercontent.com/25841396/35065889-f526a404-fbce-11e7-9511-f6e87e271959.png)

![test_fusion](https://user-images.githubusercontent.com/25841396/35065877-e9c3d596-fbce-11e7-8eeb-033acf64b97d.png)

**Comment by radarhere** [comment]
Interesting. If were to write up a function to do what you're describing and post it here, would that solve your problem? Or do you think that this is a useful feature that should be a part of Pillow?

**Comment by hugovk** [comment]
I don't think class of problem belongs in Pillow. 

Given these points:

![image](https://user-images.githubusercontent.com/1324225/35088807-90496142-fc3d-11e7-942d-74f863985230.png)

Which is "correct"?

![image](https://user-images.githubusercontent.com/1324225/35088816-99dcbf38-fc3d-11e7-84ba-47a791598869.png)

![image](https://user-images.githubusercontent.com/1324225/35088821-9e0a401c-fc3d-11e7-92cc-380dc65960fb.png)

![image](https://user-images.githubusercontent.com/1324225/35088824-a28e3cc4-fc3d-11e7-9f39-90bfbf8a8eab.png)

**Comment by YuriGagarine** [comment]
> 

Interesting. If were to write up a function to do what you're describing and post it here, would that solve your problem? Or do you think that this is a useful feature that should be a part of Pillow?
--

It will solve my problem and I also think it will be usefull to put it into PIL.ImageDraw.Draw.polygon function. 

> I don't think class of problem belongs in Pillow.

Given these points:

image

Which is "correct"?

image

image

image


The second one is the correct answer for my problem

**Comment by radarhere** [comment]
```
import math
from PIL import Image, ImageDraw

def sortPoints(points):
	# Start with one point. Doesn't matter which
	newPoints = [points.pop()]
	
	# Work through the list of points
	while points:
		# The next point in the polygon is the closest point to the last one
		lastPoint = newPoints[-1]
		
		closestPointIndex = None
		closestDistance = None
		for i, point in enumerate(points):
			# Pythagorean theorem
			distance = math.sqrt(abs(point[0] - lastPoint[0])**2 + abs(point[1] - lastPoint[1])**2)
			if closestDistance is None or distance < closestDistance:
				closestDistance = distance
				closestPointIndex = i
		# Now that we know the closest point, append to to the list
		newPoints.append(points.pop(closestPointIndex))
	return newPoints

def drawShape(points):
	im = Image.new('RGB', (300, 300), '#000')
	
	draw = ImageDraw.Draw(im)
	draw.polygon(sortPoints(points), None, '#f00')
	del draw
	
	im.show()

# YuriGagarine's shape
drawShape([(1,1),(200,200),(1,200),(200,1)])

# hugovk's shape
drawShape([(43,67),(165,177),(118,16),(17,175),(98,164),(188,48),(279,119)])
```

**Comment by wiredfool** [comment]
This is unsolvable in the general case. Think of something like a figure 8, where the curvature is much less than the distance between the curves. Or a grid of points where every point is equidistant from its neighbors.  You could go adding points to make it work, but then you might as well just get the ordering right in the first place. 

There are strategies for taking points and making polygons, but they're not something that's really in Pillow's scope.
