### ISSUE TITLE
Font rendering has different result on different platform?

### ISSUE THREAD

**Issue by prajnamort** [python-pillow/Pillow#2964]
### What did you do?

I've using the same code and same .ttf font to render CJK text on different platform.

### What did you expect to happen?

On my local linux (Debian), I got normal result:

<img src="https://user-images.githubusercontent.com/5914441/35086507-c0eaa3d6-fc67-11e7-916b-25f73ff6dcf2.png" width="200">

### What actually happened?

But on my online docker image ( `python2/jessie`, which I've installed all pillow dependencies), 
I got something different:

<img src="https://user-images.githubusercontent.com/5914441/35086577-f47a0656-fc67-11e7-9b40-e4c208afac4e.png" width="200">

As you can see, the 5th CJK character is thinner than it should.

### What versions of Pillow and Python are you using?

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

Pillow: 5.0.0
Python: 2.7

Is there any additional package I need to install in my docker image?

**Comment by wiredfool** [comment]
I'd suspect that you've got different versions of freetype, the font rendering library. Are you installing the prebuilt wheels, or are you compiling from source?
