### ISSUE TITLE
WMF on Centos: cannot find loader for this WMF file

### ISSUE THREAD

**Issue by dinhvankiet124** [python-pillow/Pillow#2971]
### What did you do?
from PIL import Image
Image.open('aaa.wmf').save('aaa.png')

### What did you expect to happen?
Saved as aaa.png

### What actually happened?
throw cannot find loader for this WMF file 
I debug and know error happen with .save() operation

### What versions of Pillow and Python are you using?
4.2.1 and 5.0 on centos 6.5
python 3.4

P/S: Windows run perfect

Sorry for my bad English
Please help me! Many thanls

**Comment by hugovk** [comment]
Pillow only supports WMF to identify files. It cannot open or read them. 

https://github.com/python-pillow/Pillow/blob/master/docs/handbook/image-file-formats.rst#wmf
