### ISSUE TITLE
memory leak when loading images in webp format with Pillow 5.0.0

### ISSUE THREAD

**Issue by Dobiasd** [python-pillow/Pillow#2972]
With Pillow `4.3.0` the following code works fine with constant memory usage.

```python
# download example image here:
# http://www.gstatic.com/webp/gallery/1.webp
from PIL import Image
while True:
    img = Image.open('1.webp') # no problem with png
    img = img.convert('L') # just a dummy operation on the image
    print(img.size)
```
When using Pillow `5.0.0` however, the memory usage of the process constantly grows quite fast.

I'm using Python 3.5.2 and Ubuntu 16.04.

**Comment by wiredfool** [comment]
I'm not seeing that here, running under `valgrind --tool=massif`:

![image](https://user-images.githubusercontent.com/19792/35327633-07f8d5ca-00f2-11e8-9f6d-9ab6e28d3287.png)

I've tried this with and without the convert line, and it looks like a steady state after the initial ramp. 

```
from PIL import Image
for _ in range(100):
  im = Image.open('issue_2972.webp')
  im.load()
  im.convert('L')
  print (im.size)
```

**Comment by Dobiasd** [comment]
I'm using the wheels from `pip3`.

Right now I'm at a Windows 7 machine with `Python 3.6.4`, and the problem also occurs here.

```python
#issue_2972.py
from PIL import Image
for _ in range(1000): # 1000 instead of 100 to have an even bigger effect
  im = Image.open('issue_2972.webp')
  im.load()
  im.convert('L')
  print (im.size)
```

When running `pip3 install pillow==4.3.0` and then `python issue_2972.py` the process is constantly at about 8 MB in the task manager.

But with `pip3 install pillow==5.0.0` and `python issue_2972.py` it reaches over 700 MB at the end.

**Comment by wiredfool** [comment]
Ok, with the binary wheels I get a slightly different view:

![image](https://user-images.githubusercontent.com/19792/35331195-4ea7b4c6-00fe-11e8-944e-ca462d1ad945.png)

**Comment by wiredfool** [comment]
Ok, now with patch:
![image](https://user-images.githubusercontent.com/19792/35333363-5e0e1222-0106-11e8-8178-2a5a3b7628cc.png)

**Comment by Dobiasd** [comment]
Wow, very nice analysis and a lightning fast fix.
`10/10, would open issue here again` ;-)

**Comment by wiredfool** [comment]
Don't take this the wrong way, but just because I'm good at locating memory leaks doesn't mean that I want to be finding more of them here.
