### ISSUE TITLE
A typo in document

### ISSUE THREAD

**Issue by yangwg** [python-pillow/Pillow#2976]
Hi, I think one number in the document might be typo.

>lut – A lookup table, containing 256 (or 65336 if self.mode==”I” and mode == “L”) values per band in the image. 

The above is from the description of Image.point 

Link: http://pillow.readthedocs.io/en/3.1.x/reference/Image.html

65336 is a strange number, should it be 65536 instead?

**Comment by radarhere** [comment]
Yep. Thanks for reporting this. I've created a PR to resolve the situation.

If you're interested, see https://github.com/python-pillow/Pillow/blob/master/src/_imaging.c#L1142 for the value that this documentation refers to.
