### ISSUE TITLE
Image.thumbnail() corrupts image for certain software if the provided size is bigger than the image's

### ISSUE THREAD

**Issue by Alphare** [python-pillow/Pillow#2981]
### What did you do?
I have an image as a `bytestring` that I sometimes want to `thumbnail`. I create a new `Image` using said `bytestring` and apply `thumbnail` with a size of `(500, 500)`. I passed in an image of 333x500px.

### What did you expect to happen?
For any given image, I expect Pillow to produce a valid image no larger than 500px for either dimensions while maintaining the aspect ratio. There, it should be a noop, since the image's biggest dimension is equal to the max size.

### What actually happened?
The image produced by Pillow can be read by most browsers, but appears black in Safari 10.1 (MacOS Sierra) and breaks in XViewer 1.4.3 (Linux Mint 18.2, Linux 4.8.0-53-generic) with the following exception:
`Fatal error reading PNG image file: IDAT: CRC error`

If I don't resize (in the code below: if I don't go into the `if`) or if I `thumbnail` to a smaller resolution than the image's, it works fine.

### What versions of Pillow and Python are you using?
Python 3.6.4, Pillow 5.0.0

```python
image_bytes = io.BytesIO(result)
image_bytes.seek(0)

if self.resize_image:
    image = Image.open(image_bytes)

    # If I remove this line, the error disappears (and nothing happens, of course)
    image.thumbnail((500, 500))  

    image_bytes.seek(0)
    image.save(image_bytes, format='PNG')
    image_bytes.seek(0)
```

Here is an example of a broken image:
![test_render](https://user-images.githubusercontent.com/9445758/35436086-5b3424be-028d-11e8-880f-5615aca84adc.png)

**Comment by wiredfool** [comment]
Don't write into the same buffer, write into a new buffer. And if you still get the same problem, post the image that's having an issue.

**Comment by Alphare** [comment]
Ah that was it! This fixed my problem, thanks.
This is strange behavior, because the image is only partially corrupted, I wonder why.

**Comment by radarhere** [comment]
@Alphare so is this issue right to be closed?

**Comment by Alphare** [comment]
@radarhere: Yes, absolutely
