### ISSUE TITLE
ImageChops.difference(im1, im2).getbbox() return None, but the images are different

### ISSUE THREAD

**Issue by adigrabcad** [python-pillow/Pillow#2982]
### What did you do?
I'm trying to compare two bitmaps. Please see [two_bitmaps.zip](https://github.com/python-pillow/Pillow/files/1669076/two_bitmaps.zip)

### What did you expect to happen?
Why `ImageChops.difference(im1, im2).getbbox()` return `None` in this case? Is this a bug? 
![image](https://user-images.githubusercontent.com/15086504/35469714-607c6c78-0333-11e8-9c55-c40fdabbb539.png)

### What actually happened?
`ImageChops.difference(im1, im2).getbbox()` return `None` and I think should not.

### What versions of Pillow and Python are you using?
Python 2.7.14, PIL 1.1.7, Pillow 3.4.2

```python
from PIL import Image
from PIL import ImageChops

im1 = Image.open('ImageA.bmp')
im2 = Image.open('ImageB.bmp')

print ImageChops.difference(im1, im2).getbbox()
```

**Comment by hugovk** [comment]
What did you expect to happen?

See https://www.blog.pythonlibrary.org/2016/10/11/how-to-create-a-diff-of-an-image-in-python/ for an example of how it works.

Maybe you'll get better results if ImageA and ImageB are the same sizes to begin with.

**Comment by adigrabcad** [comment]
I was expecting ImageA and ImageB to be different. It seems if ImageA is "included" in ImageB, then there is no difference. This is what is expected?

**Comment by hugovk** [comment]
It only calculates the difference of subset images of size: 

https://github.com/python-pillow/Pillow/blob/81c88b1ead5343d9778a82977c9c6c1150fd9738/src/libImaging/Chops.c#L72-L73

Which in this case are identical.

Try resizing them to be the same.

**Comment by adigrabcad** [comment]
Thank you @hugovk. Feel free to close this as not an issue. 
In my test I will check also the size `if im1.size == im2.size and diff.getbbox() is None:`

**Comment by kodph** [comment]
i have met similiar problem with this function. i use ImageChops.difference(im1, im2).getbbox() to compare two pictures. The code is just same as above. Two pictures have same size. The cars in the two pictures are identical. One is closer to the camera and one is farther away. ImageChops.difference(im1, im2).getbbox() returns None.
![test_distance 0](https://user-images.githubusercontent.com/89945628/174409674-cf65a780-daef-49c5-8c39-45bfcb4d786b.png)
![test_distance 1](https://user-images.githubusercontent.com/89945628/174409680-00e77992-f369-48e9-8cef-bb8f1d3de102.png)

**Comment by radarhere** [comment]
Running
```python
from PIL import Image
from PIL import ImageChops

im1 = Image.open('test_distance.0.png')
im2 = Image.open('test_distance.1.png')

print(ImageChops.difference(im1, im2).getbbox())
```
over your two images does indeed return `None`.

Your two images are RGBA.
```python
from PIL import Image
from PIL import ImageChops

im1 = Image.open('test_distance.0.png')
print(im1.mode)
im2 = Image.open('test_distance.1.png')
print(im2.mode)
```
gives
```
RGBA
RGBA
```

But you would guess that your images are opaque, with nothing in the alpha channel. So Pillow would be calculating the difference for each channel, and computing that there is no difference in the alpha channel. This means that the difference image has an alpha channel of zero. Completely transparent.

https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#if-present-only-use-alpha-channel-for-bounding-box
> When the [getbbox()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getbbox) method calculates the bounding box, for an RGB image it trims black pixels. Similarly, for an RGBA image it would trim black transparent pixels. This is now changed so that if an image has an alpha channel (RGBA, RGBa, PA, LA, La), any transparent pixels are trimmed.

So the `getbbox()` of a transparent image is `None`.

As an alternative, you may wish to convert your images to RGB first.

```python
from PIL import Image
from PIL import ImageChops

im1 = Image.open('test_distance.0.png').convert('RGB')
im2 = Image.open('test_distance.1.png').convert('RGB')

print(ImageChops.difference(im1, im2).getbbox())
```
gives
```
(98, 243, 752, 455)
```

**Comment by adigrabcad** [comment]
>Two pictures have same size. 
I don't think this is the case for your pictures. Have you tried with `if im1.size == im2.size and diff.getbbox() is None:`  ?

**Comment by kodph** [comment]
> 

Yes, they are both 800*600.

**Comment by kodph** [comment]
> Running
> 
> ```python
> from PIL import Image
> from PIL import ImageChops
> 
> im1 = Image.open('test_distance.0.png')
> im2 = Image.open('test_distance.1.png')
> 
> print(ImageChops.difference(im1, im2).getbbox())
> ```
> 
> over your two images does indeed return `None`.
> 
> Your two images are RGBA.
> 
> ```python
> from PIL import Image
> from PIL import ImageChops
> 
> im1 = Image.open('test_distance.0.png')
> print(im1.mode)
> im2 = Image.open('test_distance.1.png')
> print(im2.mode)
> ```
> 
> gives
> 
> ```
> RGBA
> RGBA
> ```
> 
> But you would guess that your images are opaque, with nothing in the alpha channel. So Pillow would be calculating the difference for each channel, and computing that there is no difference in the alpha channel. This means that the difference image has an alpha channel of zero. Completely transparent.
> 
> https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#if-present-only-use-alpha-channel-for-bounding-box
> 
> > When the [getbbox()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getbbox) method calculates the bounding box, for an RGB image it trims black pixels. Similarly, for an RGBA image it would trim black transparent pixels. This is now changed so that if an image has an alpha channel (RGBA, RGBa, PA, LA, La), any transparent pixels are trimmed.
> 
> So the `getbbox()` of a transparent image is `None`.
> 
> As an alternative, you may wish to convert your images to RGB first.
> 
> ```python
> from PIL import Image
> from PIL import ImageChops
> 
> im1 = Image.open('test_distance.0.png').convert('RGB')
> im2 = Image.open('test_distance.1.png').convert('RGB')
> 
> print(ImageChops.difference(im1, im2).getbbox())
> ```
> 
> gives
> 
> ```
> (98, 243, 752, 455)
> ```
I think this explanation is reasonable, thank you very much
