### ISSUE TITLE
It's "register_extension", instead of "register_extensions"

### ISSUE THREAD

**Issue by minghao-wu** [python-pillow/Pillow#2986]
PIL.Image has an attribute called `register_extension`, not `register_extensions`

In https://github.com/python-pillow/Pillow/blob/9a19858fb741fd1f4e7d529e59936ae73c6ae436/src/PIL/TiffImagePlugin.py

`register_extension` was miswritten as `register_extensions`.

**Comment by hugovk** [comment]
`register_extensions` was added in PR https://github.com/python-pillow/Pillow/pull/1860 and released in Pillow 4.3.0 last October.

**Comment by minghao-wu** [comment]
@hugovk 
Thank you for your reply.
Problem solved.

**Comment by malikshubham827** [comment]
@minghao-wu were you able to run the fast.ai lesson1 notebook successfully?
