### ISSUE TITLE
ImportError: The _imagingft C module is not installed with pypy3

### ISSUE THREAD

**Issue by Fover23** [python-pillow/Pillow#2992]
I try to run pypy3 on Macos version 10.13.2 
I install Pillow by pypy3's pip 
Pillow version is 5.0.0

Install succeed. But when I run code ,it raise error.

```python
ImportError: The _imagingft C module is not installed
```

**Comment by radarhere** [comment]
Please include more details, such your exact error message, your precise version of pypy3 or your installation method.

**Comment by Fover23** [comment]
@radarhere  I had install libjpeg and freetype via brew.

**Comment by hugovk** [comment]
@Fover23 Please copy and paste the full log of uninstalling and re-installing Pillow using pip.

And which version of pypy3 are you using?

**Comment by Fover23** [comment]
@hugovk I try to uninstall and install Pillow again,but raise the same error.
pypy3 version is PyPy 5.10.1 for macos 
The logs:
```python
Traceback (most recent call last):
  File "screen.py", line 151, in <module>
    draw_text(s="   some chinese word like 你好 \n")
  File "screen.py", line 144, in draw_text
    return create(txt, height, book, chapter_id)
  File "screen.py", line 71, in create
    font = create_font(font_path, font_size)
  File "screen.py", line 44, in create_font
    return ImageFont.truetype(font=font_path, size=size)
  File "/Volumes/Users/Downloads/pypyenv/site-packages/PIL/ImageFont.py", line 260, in truetype
    return FreeTypeFont(font, size, index, encoding, layout_engine)
  File "/Volumes/Users/Downloads/pypyenv/site-packages/PIL/ImageFont.py", line 135, in __init__
    if core.HAVE_RAQM:
  File "/Volumes/Users/Downloads/pypyenv/site-packages/PIL/ImageFont.py", line 39, in __getattr__
    raise ImportError("The _imagingft C module is not installed")
```

**Comment by radarhere** [comment]
@Fover23 did you ever make progress on this?

**Comment by Fover23** [comment]
@radarhere Hello,I try it again on my Macos today, it work. The pillow version is 5.2.0 . I run my code on pypy3-5.10.1 for Macos and least pypy3 version(pypy3-6.0.0) ,both version work perfect.
Thanks for pillow team :)
