### ISSUE TITLE
Multiprocessing and loading images

### ISSUE THREAD

**Issue by pyxplorer** [python-pillow/Pillow#2995]
So, I wanted to load different images using Pool from multiprocessing.
The code is:

```python
from PIL import Image
from multiprocessing import Pool

def f(path):
   return Image.open(path)

impath = ['/home/usr/Desktop/img1.jp2', '/home/usr/Desktop/img2.jp2', '/home/usr/Desktop/img3.jp2']
p = Pool()
im = p.map(f, impath)
```

But when I try to edit im (e.g. im.getpixel(0,0)) that happens:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/usr/.local/lib/python3.6/site-packages/PIL/Image.py", line 1054, in copy
    self.load()
  File "/home/usr/.local/lib/python3.6/site-packages/PIL/Jpeg2KImagePlugin.py", line 198, in load
    if self.reduce:
AttributeError: 'Jpeg2KImageFile' object has no attribute 'reduce'

```

Is that an issue that occurs when working with jp2 images?

**Comment by wiredfool** [comment]
1) Does the image work without multiprocessing?

2) Multiprocessing is unlikely to be useful if you're passing back full images, as it requires the return values to be pickled, and pickling images then passing them over the socket to unpickle is not a well used path.

**Comment by pyxplorer** [comment]
Thank you for the reply!
Yes, the image works without multiprocessing.  If I write:
```
im = f(impath[0])
im.getpixel((0,0))
```
everything works fine.
The goal of this piece of code was to speed up the loading of images since I have to work with a lot of images at a time. I saw that
```
for x in range(0,len(impath)):
     im.append(f(impath[x]))
     im[x].load()
```
is a lot slower than the code with multiprocessing (where I put the .load() inside the function f).  The code with multiprocessing works fine until I call the methods of the images ( load, getpixel etc.) from the output of it.
This works:
im = p.map(f, impath)
creating an im variable containing this:
`[<PIL.Jpeg2KImagePlugin.Jpeg2KImageFile image mode=I;16 size=10980x10980 at 0x7F1D99F65D68>, <PIL.Jpeg2KImagePlugin.Jpeg2KImageFile image mode=I;16 size=10980x10980 at 0x7F1D99F65DD8>, <PIL.Jpeg2KImagePlugin.Jpeg2KImageFile image mode=I;16 size=10980x10980 at 0x7F1D99F65CF8>]`
but calling something like
im[0].getpixel((0,0)) or im[0].load() triggers the error.

**Comment by wiredfool** [comment]
Pickle support is more likely to work with Image objects than any of the individual image format types, but I wouldn't recommend it.

Multiprocessing is a strange beast in Python, if you can do your processing completely in a separate process it might be worth it, passing back a small result or something.  If you need more back than that, look at multi threading, as iirc we do release the GIL when we're in the library code.

**Comment by mooncrater31** [comment]
pyxplorer, did you solve this problem? I'm facing a similar issue with .tiff files, for multiprocessing.
