### ISSUE TITLE
Can't identify some psd files because of layer mode type number

### ISSUE THREAD

**Issue by tdesvenain** [python-pillow/Pillow#3]
On many psd i have tested, we have a layerinfo which layer image mode is 3

but code supports now mode type 65535, 0, 1 and 2

```
    for i in range(i16(read(2))):
        type = i16(read(2))
        if type == 65535:
            m = "A"
        else:
            m = "RGB"[type]
```

so we finally get a "can't identify image file..." exception

we supposed that mode 3 is "A", so if we write :

```
    for i in range(i16(read(2))):
        type = i16(read(2))
        if type == 65535:
            m = "A"
        else:
            m = "RGBA"[type]
```

and then it works very fine

i'll submit a pull request

**Comment by soorajsasi** [comment]
hi,
how to convert psd file to xml file in python
