### ISSUE TITLE
ImageDraw examples - is "del" really necessary?

### ISSUE THREAD

**Issue by CRImier** [python-pillow/Pillow#3002]
Hi! In our project, we have a "canvas" system, based off `PIL.Image` and `PIL.ImageDraw`. [The code](https://github.com/ZeroPhone/ZPUI/blob/devel/ui/canvas.py) is simple - create an `Image`, create an `ImageDraw` object, allow the user to do stuff with it, then allow the user to get the resulting image.

So, a question about `ImageDraw` - [in the first example](http://pillow.readthedocs.io/en/5.0.0/reference/ImageDraw.html#example-draw-a-gray-cross-over-an-image), `del` is used - what's the reasoning behind it? Is the `draw` object not collected by GC eventually (IIRC Python can deal with cyclic references quite well)?

**Comment by wiredfool** [comment]
I don't think it's necessary now, but it's possible that it was in the past when the GC wasn't as good.  If it does become a memory leak, it should probably be fixed.

**Comment by CRImier** [comment]
Fixed - in the code using PIL, or in the PIL code itself?

**Comment by wiredfool** [comment]
I think the GC in CPython has gotten better, especially with circular references.

**Comment by CRImier** [comment]
Oh, understood. Okay, I assume there's no weird stuff going on (like defined __del__ methods) and it's safe to use it without `del`. If so, maybe it'd be safe to remove it from the mentioned example, too? (assuming that nobody remembers the reason why it was put there)

**Comment by wiredfool** [comment]
There is, but only on python > 3.4 which should be safe. 

I'd say that it's safe to not use them, but if you see memory leaks in a long running process, that's a good place to start looking for them. If you get a test case, I can probably find it pretty quickly.
