### ISSUE TITLE
How to detect if my image is truncated?

### ISSUE THREAD

**Issue by zerazobz** [python-pillow/Pillow#3012]
### What did you do?
I'm using VersatileImageField and everything was working fine until we meet a [jpeg ](https://drive.google.com/file/d/16JtaXneRvL03_1S0v9k-tsgZvw4hZVeB/view) file.
This file can't be rendered by VersatileImageField and we understand that VersatileImageFiled uses Pillow itlself.
By the way we are trying to determine what kind of error exists with this image and maybe this can be the 
[error](https://github.com/python-pillow/Pillow/issues/1510#issuecomment-152697768). 

 

This code was tested and it worked fine with a lot of other images.

### What did you expect to happen?
It should render a resized image

### What actually happened?
Returns the following error

The error says:
> Django Version:	1.11
> Exception Type:	OSError
> Exception Value: broken data stream when reading image file
> Exception Location: C:\..myenv\lib\site-packages\PIL\ImageFile.py in raise_ioerror, line 59

### What versions of Pillow and Python are you using?
- Pillow 4.3.0
- Django 1.11
- django-cms 3.4.5, I can't upgrade Django 1.11 by this package
- Python 3.6.3

I trigger the error from:

`<img src="{{ imagemodel.versatileimageproperty.crop.255x255 }}" srcset="{{ imagemodel.versatileimageproperty.crop.255x255 }} 1x, {{ imagemodel.versatileimageproperty.crop.255x255 }} 2x" alt="">`

I was wondering if I can use the verify method to **test if this image is truncated**, avoid the yellow error page and show a message.
```
from PIL import Image
im = Image.open("C:\\absolutepathtoimage\\_DSC1318.jpg")
im.verify()
```

But verify returns nothing, no errors.

**Comment by wiredfool** [comment]
`Image.verify` is only implemented for `PNG` images, and it only verifies the CRC checksum in the image. 

The only way to check from within Pillow is to load the image in a try/except and check the error. If you need as much info as possible from the image, you can set `ImageFile.LOAD_TRUNCATED_IMAGES=True` and it will attempt to parse as much as possible.

**Comment by jfthuong** [comment]
You can open the picture and load the data to check that everything is fine:
```python
    try:
        # try to open that image and load the data
        Image.open(img_path).load()
    except Exception as e:
        ... do something if there is an error
```

Note that truncated image will return a `OSError: image file is truncated` so you could also do `except OSError` to be more specific.

**Comment by jfthuong** [comment]
It is actually inspired by the code of `Pillow` :)

**Comment by robycuccurese** [comment]
Hi guys,

I have a python lambda (3.8) and I try to check if the image download on AWS S3 is corrupted or not, and I notice that the code shown previously:

`    try:
        # try to open that image and load the data
        Image.open(img_path).load()
    except Exception as e:
        ... do something if there is an error`

in my case, the source code above produce always an exception also if the image not is corrupted, do you have an idea on how can I detect if an image downloaded by the lambda and putted on S3 bucket is corrupted or not?

**Comment by radarhere** [comment]
What is the exception produced when the image is not corrupted? Could you attach a copy of the image?

**Comment by robycuccurese** [comment]
This is the image:
![d766c299-970d-4b97-a21b-f5459be2b03e_T74](https://user-images.githubusercontent.com/88253038/167103321-2bbffb47-fcc6-4b4e-b451-65b7d95cb30b.png)

and the error is:

![image](https://user-images.githubusercontent.com/88253038/167103964-a3a92333-79b0-44ca-b910-898909f50754.png)

but the image on bucket is present.

**Comment by radarhere** [comment]
If the error is "No such file or directory", then the problem is not with the image data itself, because Pillow never receives it.

If you're using "s3://..." as `img_path`, then that is incorrect. Pillow is expecting your string to be a path to a local file.

Instead, you are trying to [read from a URL.](https://pillow.readthedocs.io/en/latest/handbook/tutorial.html#reading-from-url)

So I would adjust your code as follows.
```python
from PIL import Image
from urllib.request import urlopen
url = "s3://..."
f = urlopen(url)
try:
	# try to open that image and load the data
	Image.open(f).load()
except Exception as e:
	# do something if there is an error
```

**Comment by robycuccurese** [comment]
I try as you suggest:
![image](https://user-images.githubusercontent.com/88253038/167108612-ea57bbfc-df1e-4040-bd47-c1e1ba2282b8.png)
but I've got this error:
![image](https://user-images.githubusercontent.com/88253038/167108836-1574fac7-9852-49fb-a266-b8a0c04b5040.png)

**Comment by robycuccurese** [comment]
Ok thanks a lot @radarhere now also in my env the image is detected as truncted!!
