### ISSUE TITLE
_webp.so: undefined symbol: WebPAnimEncoderAdd

### ISSUE THREAD

**Issue by petervanderdoes** [python-pillow/Pillow#3013]
### What did you do?
Rebuild Pillow from source adding Webp support

### What did you expect to happen?
No import failure

### What actually happened?
Import failure 

### What versions of Pillow and Python are you using?
Python 2.76
Pillow 5.0.0
WebP 0.6.1 build from source

Same process used for Pillow 4.2.1 results in no errors.

##### Building WebP
```
./configure --prefix=/usr --enable-libwebpmux --enable-libwebpdemux && make -j4 && sudo make -j4 install
```

##### Rebuilding Pillow Latest
```
pip install --upgrade --no-cache-dir --force-reinstall --no-binary :all: --compile -v Pillow
```

```python
>>> from PIL import _webp
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /home/vagrant/env/local/lib/python2.7/site-packages/PIL/_webp.so: undefined symbol: WebPAnimEncoderAdd`
```

##### Rebuilding Pillow 4.2.1
```
pip install --upgrade --no-cache-dir --force-reinstall --no-binary :all: --compile -v Pillow==4.2.1
```

```python
>>> from PIL import _webp
>>>
```

**Comment by radarhere** [comment]
Hi. What operating system are you using?

**Comment by petervanderdoes** [comment]
Ubuntu 14.04

**Comment by wiredfool** [comment]
I'm going to guess that you've got 2 versions of the library installed, and the runtime is picking up the wrong one.

**Comment by petervanderdoes** [comment]
Which library? WebP?

**Comment by wiredfool** [comment]
Yes, I think you have two copies of webp, one that the build scripts are finding, and one that's found at runtime.

**Comment by petervanderdoes** [comment]
That seemed to be the case, after creating a completely new Trusty Virtual Machine, the steps to reproduce did not produce the same error. Thank you.
