### ISSUE TITLE
Release for WebP memory leak issue?

### ISSUE THREAD

**Issue by seandkim** [python-pillow/Pillow#3014]
We are using pillow 5.0.0 for loading WebP images (for performance/memory), but we are on hold due to the following memory leak issue.

https://github.com/python-pillow/Pillow/issues/2972

It seems like the issue has been fixed–would it be possible to know when the next release will be?

**Comment by radarhere** [comment]
April 1st. See https://github.com/python-pillow/Pillow/blob/master/RELEASING.md for the release schedule

**Comment by w4-seandkim** [comment]
Any chance of point release before April?

**Comment by seandkim** [comment]
Thank you. Any chance of point release before April?

**Comment by radarhere** [comment]
Ah, yes, sorry, should have talked about that in my initial comment.

That is the plan, but we shall have to see how time permits - https://github.com/python-pillow/Pillow/issues/3010#issuecomment-367237868

**Comment by aclark4life** [comment]
@seandkim Hopefully this will go out today-ish.
