### ISSUE TITLE
Image saved and opened again are different

### ISSUE THREAD

**Issue by mohssine54** [python-pillow/Pillow#3015]
### What did you do?
Hi, when ever I save a file (L or RGB), and open it again, I find that the pixel values are different??
### What did you expect to happen?
I expect to have the same pixel values because it is juste saving the file and opening it again.
### What versions of Pillow and Python are you using? the latest one 5.

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
    im = Image.open(image)
    im = im.convert("L") # or RGB
    im_pix = im.load()
    (width, hight) = im.size
    im.save("test.jpg")
    im = Image.open("test.jpg")
    im_pix2 = im.load()

    for i in range(width):
        for j in range(hight):
            if im_pix[i,j] != im_pix2[i,j]:
                print(im_pix[i,j],im_pix2[i,j],"   ",i,"   ",j)
```
as you can see, I did not change anything but, the pixels are different?

**Comment by wiredfool** [comment]
JPEG is a lossy compression method, so there are going to be differences when saved. If you want lossless compression where all the pixels are the same, use something like PNG, or some other lossless format.
