### ISSUE TITLE
typo?  if PILLOW_VERSION  to  if core.PILLOW_VERSION

### ISSUE THREAD

**Issue by grabchance** [python-pillow/Pillow#3019]
### What did you **do?**
from PIL import Image
### What did you expect to happen?
The code works
### What actually happened?
raised ImportError: The _imaging extension was built for another version of pillow or PIL

### What versions of Pillow and Python are you using?
Pillow :4.2.1, Python(Anaconda3):3.6

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

from PIL import Image
any other modules that use PIL Image. In my case, it was wordcloud

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```
File need to be changed:
C:\Anaconda\lib\site-packages\PIL\Image.py

Code:  Image.py line 57. _Need to add "core."_
    if **core.**PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):
        raise ImportError("The _imaging extension was built for another "
                          "version of Pillow or PIL")

**Comment by hugovk** [comment]
No, 

if **core.**PILLOW_VERSION != getattr(core, 'PILLOW_VERSION', None):

Is comparing a variable with itself, like:  

If x != x:

This may be related to or a duplicate of https://github.com/python-pillow/Pillow/issues/2945. You must have two versions of Pillow installed. Try uninstalling all conda/anaconda/pip installs, then reinstalling.

**Comment by grabchance** [comment]
Oops, thanks!
