### ISSUE TITLE
Corrupt jpeg opens as all black image

### ISSUE THREAD

**Issue by kkopachev** [python-pillow/Pillow#3022]
### What did you do?
```python
from PIL import Image
from PIL import ImageFile

ImageFile.LOAD_TRUNCATED_IMAGES = True

im = Image.open('pic263134.jpg')
im.save('1.png')
```
### What did you expect to happen?
Image could be saved up to corruption point. 
### What actually happened?
All black image is saved. Tried saving to different output formats - it's all black anyway.
![1.png](https://user-images.githubusercontent.com/2279051/36819127-dc9e33ea-1c9c-11e8-9a93-0d3c0a674f02.png)

### What versions of Pillow and Python are you using?
Python2. Pillow 5.0.0 and 3.0.0

Original image:
![original_image](https://user-images.githubusercontent.com/2279051/36819109-d04f6f32-1c9c-11e8-97cf-fc244d5aa5e3.jpg)

`djpeg` can output image correctly (up to corruption point)

Looks like it's problem with decoding step, since after opening, all image bands contain 0-only bytes:
```python
sum(im.split()[0].point(lambda x: 0 if x else 1).getdata())
# returns 3097440
```

**Comment by alexandertsema** [comment]
have the same problem, moreover the image I try to open can be displayed in any viewer and browser

**Comment by hugovk** [comment]
@alexandertsema Do the changes in PR https://github.com/python-pillow/Pillow/pull/3023 fix it for you?
