### ISSUE TITLE
it do not to support png format?

### ISSUE THREAD

**Issue by 727023460** [python-pillow/Pillow#3024]
my code is very simple
```
from PIL import Image

im=Image.open("xx.png")
im.show()
```

but it can not  show image
I change othen image with jpg format,
it is normal

**Comment by hugovk** [comment]
Yes, PNG is supported. Perhaps the problem is with your image. Please can you share the file?

What exactly happens when you do `im.show()`?

What operating system are you using?

What version of Python and Pillow are you using?

**Comment by 727023460** [comment]
thanks , 
both python version : 3.6
in windows use Pillow  with version 5.0 is  normal
fedora
 Pillow   version : 4.3
run python file is nothing to happen
maybe the fedora setting

**Comment by 727023460** [comment]
fedora
Pillow version update to 5.0.0
show good
