### ISSUE TITLE
Low color quality in JPG image generated with quality=100 option

### ISSUE THREAD

**Issue by gokceneraslan** [python-pillow/Pillow#3028]
### What did you do?
I observe that the colors of an image saved as jpg (quality=100) and png look very different.

### What did you expect to happen?
I expect jpg image saved with quality=100 to look similar to the original image. The JPG image I convert from PNG using imagemagick looks same as PNG image.

### What actually happened?

![image](https://user-images.githubusercontent.com/1140359/36953417-ceb01a74-201a-11e8-8c74-cd22af681507.png)

### What versions of Pillow and Python are you using?

Pillow 5.0.0, Python 3.6.4

```python
from PIL import Image
import numpy as np
import os

im = Image.open('x.png')
im = Image.fromarray(np.asarray(im)[:,:,:-1]) #remove alpha channel
img = np.asarray(im)
print(img[0])
im.save('pil.jpg', quality=100)

im = Image.open('pil.jpg')
print(np.asarray(im)[0])

# compare with imagemagick png->jpg conversion
os.system('convert x.png x.jpg')
print(np.asarray(Image.open('x.jpg'))[0])
```

Output:

```
[[255 127  14]
 [214  39  40]
 [214  39  40]
 ...
 [214  39  40]
 [ 44 160  44]
 [214  39  40]]
[[255 121  30]
 [214  43  13]
 [182  49  68]
 ...
 [150  80   0]
 [158 102  41]
 [154  66  52]]
[[254 126  16]
 [213  41  41]
 [213  39  38]
 ...
 [210  40  41]
 [ 46 159  41]
 [211  38  42]]
```

`x.png` image:

![image](https://user-images.githubusercontent.com/1140359/36953463-39039176-201b-11e8-86c4-94eb781ceddb.png)

**Comment by wiredfool** [comment]
This is very likely a managed/unmanaged color issue with sgb profiles. If you make the conversion, you need to make sure that any color profiles are saved in the new file.

**Comment by homm** [comment]
Besides `quality`, JPEGs also have `subsampling` parameter. The default depends on installed JPEG codes, and the highest quality is subsampling = 0.

```python
Image.open('x.png').convert('RGB').save('_out.s0.jpeg', subsampling=0)
```

![_out s0](https://user-images.githubusercontent.com/128982/37950272-99e4c730-31a0-11e8-859e-b4b553062fe7.jpeg)

**Comment by gokceneraslan** [comment]
What about setting subsampling to zero if quality >=90 is given? That seems to be the case for ImageMagick: https://github.com/libgd/libgd/issues/18 This is more intuitive, isn't it?
