### ISSUE TITLE
Undefined behavior in Effects.c

### ISSUE THREAD

**Issue by sk-** [python-pillow/Pillow#3030]
In `libImaging/Effects.c` the function `ImagingEffectNoise` has an undefined behavior in [line 109](https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Effects.c#L109):

```c
out[x] = (unsigned char) (128 + sigma * this);
```

This is detected when running the test `test_image.py` and compiling the library with UndefinedBehaviorSanitizer. See https://clang.llvm.org/docs/UndefinedBehaviorSanitizer.html to see how to detect this.

This code is easy to fix with something like:

```c
int d = 128 + sigma * this;
out[x] = d<0? 0: (d > UCHAR_MAX: UCHAR_MAX: d);
```

**Comment by aclark4life** [comment]
@sk- Send a PR?

**Comment by wiredfool** [comment]
Probably need to add the clip macro.

**Comment by sk-** [comment]
I found 4 clip macros (https://github.com/python-pillow/Pillow/search?utf8=%E2%9C%93&q=CLIP&type=) and they are defined in C files, so they are not reusable.

The pasted code is essentially the same as the clip macro.

**Comment by radarhere** [comment]
Minor syntax correction - you wrote `out[x] = d<0? 0: (d > UCHAR_MAX: UCHAR_MAX: d);`. This presumably should have been `out[x] = d<0? 0: (d > UCHAR_MAX? UCHAR_MAX: d);`, with the contents of the brackets being a ternary operator.
