### ISSUE TITLE
IOError: cannot open resource

### ISSUE THREAD

**Issue by TheRainManPY** [python-pillow/Pillow#3032]
### What versions of Pillow and Python are you using?

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```
self.font = core.getfont(font, size, index, encoding, layout_engine=layout_engine) 
font is SimSun.ttf

**Comment by hugovk** [comment]
Please can you include your full, yet minimal, code example?

This works for me:
```
$ python
Python 3.6.4 (default, Mar  1 2018, 18:36:50)
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image, ImageFont, ImageDraw
>>> FONT_PATH = "/Applications/Microsoft Excel.app/Contents/Resources/Fonts/SimSun.ttf"
>>> FONT_SIZE = 20
>>>
>>> ttf = ImageFont.truetype(FONT_PATH, FONT_SIZE, ImageFont.LAYOUT_BASIC)
>>> im = Image.new("RGB", (256, 64), "white")
>>> d = ImageDraw.Draw(im)
>>> d.text((10, 10), "hello", font=ttf, fill='black')
>>> im.show()
>>> im.save("out.png")
>>>
```
Produces:

![out.png showing "hello" in black text](https://user-images.githubusercontent.com/1324225/37086776-10e19afc-2201-11e8-9377-5db8dbe51bad.png)

**Comment by TheRainManPY** [comment]
Sorry, is my path error. but thanks! :+1:
