### ISSUE TITLE
[Request] Add dependencies to Pillow's Alpine package

### ISSUE THREAD

**Issue by thenets** [python-pillow/Pillow#3038]
## Problem

I've installed the `apk add py3-pillow` and later I tried to install `pip install Pillow` and doesn't work. Many errors raised.

## Solution

After install those packages everything works great:

``` bash
apk --no-cache add jpeg-dev \
        zlib-dev \
        freetype-dev \
        lcms2-dev \
        openjpeg-dev \
        tiff-dev \
        tk-dev \
        tcl-dev \
        harfbuzz-dev \
        fribidi-dev
```

## Request

Will be very useful add those packages as dependencies of `py3-pillow`.

Thanks.

**Comment by hugovk** [comment]
Let's ask the maintainer of [Alpine's py3-pillow](https://pkgs.alpinelinux.org/package/edge/main/x86/py3-pillow), @fabaff: any thoughts on this ^?

For reference, here are the Pillow installation instructions: https://pillow.readthedocs.io/en/latest/installation.html

**Comment by thenets** [comment]
@hugovk I've checked the installation instructions and I don't know why some dependencies aren't included in `py3-pillow` cause the `libjpeg` and `zlib` are required to install pip package and not only for some Pillow extra features.

And about the installation instructions I think is better add some notes. The package `py3-pillow` is required on Alpine in order to install the `pip` package.

**Comment by thenets** [comment]
Why this issue was closed? 😕 
It's not an issue?

**Comment by aclark4life** [comment]
@thenets Because this is Pillow and not py3-pillow? Not sure we can do anything in Pillow to help you …

**Comment by thenets** [comment]
Ah... I see. Are different teams. Sorry and thank you.
I'll try to contact the @fabaff.
