### ISSUE TITLE
'JpegImageFile' object has no attribute '_committed' error 

### ISSUE THREAD

**Issue by 96street** [python-pillow/Pillow#3039]
### What did you do?
I'm using PIL to compress uploaded images(`FileField`) on my Django site. However I'm getting an error which I believe is a problem of double saving? (saving my image, and then saving the whole form which includes the image). I wanted to perform `commit=False` when I'm saving the image but it doesn't appear it's possible with PIL.

### What versions of Pillow and Python are you using?
Pillow==4.0.0

My code returns returns `'JpegImageFile' object has no attribute '_committed'` error on the last line (`instance.save()`)

### My views.py
```python
    def post(request):
    
        if request.user.is_authenticated():
            form_post = PostForm(request.POST or None, request.FILES or None)
            if form_post.is_valid():
                instance = form_post.save(commit=False)
                instance.user = request.user
    
                if instance.image:
                    filename = instance.image
                    instance.image = Image.open(instance.image)
                    instance.image.thumbnail((220, 130), Image.ANTIALIAS)
                    instance.image.save(filename, quality=60)
    
                instance.save()
    
                return HttpResponseRedirect('/home/)
            else:
                form_post = PostForm()
    
            context = {
                'form_post': form_post,
            }
    
            return render(request, 'post/post.html', context)
        else:
            return HttpResponseRedirect("/accounts/signup/")


```

Can someone identify the problem? - and any idea how I can fix it?

**Comment by radarhere** [comment]
Could you post a complete example, as in a script that can be run by itself? My investigation so far leads me to suspect that `PostForm` is not an import from Django, but a custom class that you have written. If I'm wrong, great, but yes, adding in import statements would be appreciated.

**Comment by 96street** [comment]
I'll show you my `PostForm`:

```
from post.models import Post

class PostForm(forms.ModelForm):

    class Meta:
        model = Post
        fields = [
            'image',
            'user'
        ]
```

and the accompanying model:

```
class Post(models.Model):
    user = models.ForeignKey(User, blank=True, null=True)
    image = models.FileField(null=True, blank=True)
```

**Comment by 96street** [comment]
And here is the full Traceback:

Traceback:

```
File "/Users/zorgan/Desktop/app/lib/python3.5/site-packages/django/core/handlers/exception.py" in inner
  41.             response = get_response(request)

File "/Users/zorgan/Desktop/app/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  187.                 response = self.process_exception_by_middleware(e, request)

File "/Users/zorgan/Desktop/app/lib/python3.5/site-packages/django/core/handlers/base.py" in _get_response
  185.                 response = wrapped_callback(request, *callback_args, **callback_kwargs)

File "/Users/zorgan/Desktop/app/lib/python3.5/site-packages/django/contrib/auth/decorators.py" in _wrapped_view
  23.                 return view_func(request, *args, **kwargs)

File "/Users/zorgan/Desktop/project/site/post/views.py" in post
  68.                 if uploaded_file_type(instance) is True:

File "/Users/zorgan/Desktop/project/site/functions/helper_functions.py" in uploaded_file_type
  12.     f = file.image.read(1024)

Exception Type: AttributeError at /post/
Exception Value: 'JpegImageFile' object has no attribute 'read'

```

**Comment by wiredfool** [comment]
You're confusing things in your app. Some tips to help you track it down:
* Don't change the type of any variable. e.g.:
```
                    filename = instance.image
                    instance.image = Image.open(instance.image)
```
is likely going to cause issues, especially since I think instance.image is some form of django field. 
* Don't store pillow image objects in django fields. Keep them in other variables in the object. 
* If you're storing the image in a database, then keep a clear separation between the pillow image object and the saved bytestream (which is going to be png or jpeg or whatever).
