### ISSUE TITLE
Cannot identify image file from url

### ISSUE THREAD

**Issue by lx1054331851** [python-pillow/Pillow#3040]
```python
from PIL import Image
import requests

url = 'https://mmbiz.qpic.cn/mmbiz_png/Qog8F38YicGZf1Ttf8Y28fTwic0bhZYeZyDsATZhuLggaSlcgzAGaaA0FVTuYiaS0zWSXwbSyAZhpSBSurU6peb5g/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1'

r = requests.get(url, stream=True)
im = Image.open(r.raw)
```

error hits:
```
  File "D:\Program Files (x86)\Anaconda3\envs\normal\lib\site-packages\PIL\Image.py", line 2585, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x000001E246696CA8>
```

**Comment by hugovk** [comment]
It works for me with:

* macOS, Python 3.6.4, Pillow 5.0.0
* macOS, Python 2.7.14, Pillow 4.4.0 and 5.0.0
* Windows 7, Python 2.7.11, Pillow 5.0.0

I'm guessing the file didn't download properly for you. 

Does it work if you download the image manually, and then do this?
```python
from PIL import Image
im = Image.open("3040.png")
im.show()
```

**Comment by lx1054331851** [comment]
My environment is ：
`
Windows 10 x64, the latest Anaconda3, python 3 x64
`

@hugovk , have you tested the url i posted, other formats images i can open correctlly, just the URL posted below not work even if i download it and open locally: 
```
url = 'https://mmbiz.qpic.cn/mmbiz_png/Qog8F38YicGZf1Ttf8Y28fTwic0bhZYeZyDsATZhuLggaSlcgzAGaaA0FVTuYiaS0zWSXwbSyAZhpSBSurU6peb5g/640?wx_fmt=png&tp=webp&wxfrom=5&wx_lazy=1'
```
when i download the image from chrome web browser, the image's format is ".webp",  i though it has something to do with the "webp" format.

Does i need to install some other packages to support the webp format?

**Comment by homm** [comment]
> My environment is

Which Pillow version are you using?

**Comment by aclark4life** [comment]
@lx1054331851 Which Pillow version are you using?

**Comment by aclark4life** [comment]
@lx1054331851 Please reopen when you're ready to report Pillow version
