### ISSUE TITLE
Image.Open() and 16bit gray images - int32 output

### ISSUE THREAD

**Issue by lschaupp** [python-pillow/Pillow#3041]
If you use Image.Open("test.png") on a uint16 png depth image
-> Pillow opens is with the mode "I" which is int32.
I'm wondering if this behaviour is intentional?
I guess there is no information loss involved - but why would you do this conversion to int32 instead
of the uint16?

Thanks!

**Comment by wiredfool** [comment]
There's better support for image operations on int32 images than int16, especially for signed 16 bit images.

**Comment by anntzer** [comment]
Is there any change this issue can be revisited?  AFAICT Pillow's TIFF and JPEG handlers, for example, will happily open 16-bit data without upcasting, so I don't see why thg PNG handler can't do the same.

**Comment by radarhere** [comment]
This has been revisited in the form of #3796

**Comment by radarhere** [comment]
I've created PR #7849 to address this.
