### ISSUE TITLE
How to get Pillow to ignore DYLD_LIBRARY_PATH on macOS

### ISSUE THREAD

**Issue by johnthagen** [python-pillow/Pillow#3052]
I am trying to use Pillow with the MATLAB Runtime 2017b.

In order to use the MATLAB runtime on macOS, the `DYLD_LIBRARY_PATH` must be updated to point to the MATLAB Runtime.

```
export DYLD_LIBRARY_PATH=$DYLD_LIBRARY_PATH:/Applications/MATLAB_R2017b.app/runtime/maci64:/Applications/MATLAB_R2017b.app/sys/os/maci64:/Applications/MATLAB_R2017b.app/bin/maci64
```

Then, to use Pillow, it is installed with `pip`:

```
$ pip3 install Pillow
```

When running the following code:

```py
from PIL import Image, ImageTk

print('Hello World')
```

The following error is shown:

```
Traceback (most recent call last):
  File "main.py", line 1, in <module>
    from PIL import Image, ImageTk
  File "/Users/user/venv/py-test/lib/python3.6/site-packages/PIL/Image.py", line 58, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/user/venv/py-test/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so, 2): Library not loaded: @loader_path/.dylibs/libtiff.5.dylib
  Referenced from: /Users/user/venv/py-test/lib/python3.6/site-packages/PIL/_imaging.cpython-36m-darwin.so
  Reason: Incompatible library version: _imaging.cpython-36m-darwin.so requires version 9.0.0 or later, but libtiff.5.dylib provides version 6.0.0
```

If run without the first `export` command, Pillow works fine, but I can't find out a way to get both to work at once. The MATLAB Runtime is exporting an older version of libtiff that Pillow (even though it's install via a binary wheel) is loading:

```
/Applications/MATLAB_R2017b.app/bin/maci64/libtiff.5.dylib
```

System configuration

- macOS 10.11.6
- Python 3.6.4 installed via Homebrew
- Pillow 5.0.0
- MATLAB Runtime 2017b

If Pillow is installed using a wheel on macOS, why does `DYLD_LIBRARY_PATH` affect Pillow? Is there a way to force Pillow to use the version of libtiff it is bundled with?

**Comment by wiredfool** [comment]
The `DYLD_LIBRARY_PATH` affects an entire process, so adding Matlab's path in that variable gives it priority for all the dlls that it ships, which unfortunately includes libtiff. Our binary builds require a specific version that's shipped with the wheel, but changing the loading path forces the process to look for libraries that we're not expecting to use.  So, installing from our binary wheels is unlikely to work. 

There are a couple of options that might help you:
* You can try to build Pillow in the context of the Matlab runtime. This would use any library versions that Matlab is shipping, but it would also require that they ship appropriate headers. 
* You can try to build a version of Pillow against the same versions of libraries that Matlab is using. This is going to be an iterative process to discover everything that they're shipping. 
* You can build a version of Pillow without libtiff, assuming that you don't need that support. 
* You might be able to get Matlab to provide a binary package. 

If it's just libtiff that they're shipping, matching library versions might not be hard. If they're also shipping things like libz or libjpeg, then it's just going to get more complicated.

**Comment by johnthagen** [comment]
Thanks for the detailed response!

I did a quick search and there are actually 1750 dylibs shipped in that MATLAB path 😮. I don't see `libz` or `libjpeg` in there (only `libitkjpeg-4.8.dylib`).

I'll continue to investigate the options you provided to see if I can get one to work.

**Comment by wiredfool** [comment]
Oh man. That’s a lot of old libraries.

**Comment by johnthagen** [comment]
I added `~/venv/pcb/lib/python3.6/site-packages/PIL/.dylibs` to the front of the path (so Pillow's `libtiff` was loaded first) as well as `/usr/local/Cellar/python/3.6.4_4/Frameworks/Python.framework/Versions/3.6/lib` (needed for `libpython3.6m.dylib`) just to see if I could at least get the needed dylibs loaded, and it seemed to get through everything up until:

```
RuntimeError: On the Mac, use 'mwpython' rather than 'python' to start a script or session that will call deployed MATLAB code from Python.
```

Which is what they say in their [docs](https://www.mathworks.com/help/compiler_sdk/gs/create-a-python-application-with-matlab-code.html), but I wasn't sure how to launch Python 3 from that.

Mostly want to record this in case someone else runs into this in the future. I'll keep looking for a solution.

**Comment by johnthagen** [comment]
After a long fight with the MATLAB Runtime, I wasn't able to get it working. It doesn't seem to really be designed to work with virtual environments, Homebrew installs, PyPI packages, etc.

I'll go ahead and close this since there doesn't seem to be anything to be done from the Pillow side.
