### ISSUE TITLE
RGBA quality loss 

### ISSUE THREAD

**Issue by tux777** [python-pillow/Pillow#3059]
### What did you do?

Consider my code example below. I'm trying to read the image data and save it back with the same extension. Image has lower quality despite the fact that no data was altered. 

### What did you expect to happen?

I would expect the same quality as input file.

### What actually happened?

The output file has noticeably lower quality not to mention it converts the transparent background to white but i guess i could just replace white values with 0s. The problem is the quality drop. 

### What versions of Pillow and Python are you using?
Tested on Python 2.7 and 3.6
![tuxman](https://user-images.githubusercontent.com/37755791/37943912-8ff62694-3171-11e8-8dab-46b200cd91f7.gif)
![output](https://user-images.githubusercontent.com/37755791/37943969-c46a455e-3171-11e8-8c4c-8dc475911ad8.gif)
```python
    from PIL import Image
    from numpy import array
    img = Image.open("input.gif").convert('RGBA')
    arr = array(img)

    img = Image.fromarray(arr)
    img.save("output.gif")
```

**Comment by homm** [comment]
It's quantization issue. This gives the same result:

```python
(Image.open('./37943912.gif')
    .convert('RGBA')
    .quantize()
    .save('_out.png'))
```

**Comment by tux777** [comment]
Awesome .. Thank you very much. This solves it.
