### ISSUE TITLE
Pillow-perf page is not available on python-pillow.org

### ISSUE THREAD

**Issue by homm** [python-pillow/Pillow#3060]
Pillow-perf page used to open on https://python-pillow.org/pillow-perf/.

Now there are two Issues: python-pillow.org is not available via HTTPS and there is no /pillow-perf/ page on python-pillow.org at all as well as there is no redirect.

The current working link to pillow-perf is https://python-pillow.github.io/pillow-perf/.

If someone is able, please turn on HTTPS on python-pillow.org and add a redirect to https://python-pillow.github.io/pillow-perf/ at least.

**Comment by hugovk** [comment]
See https://github.com/python-pillow/Pillow/issues/2940.

Ping @aclark4life, should we use https://python-pillow.github.io/pillow-perf/ ?

**Comment by aclark4life** [comment]
@homm @hugovk Sorry, let me think about this … I'll have a fix by the next release (5 days from now)

**Comment by aclark4life** [comment]
@homm New ETA: early April. I'm going to leave Pillow notifications on so I don't forget to think about this one… then once I resolve it, I'll tune out again until late June (i.e. respond to mentions only.) 🤔

**Comment by aclark4life** [comment]
@homm @hugovk Alternatively I can just revert everything I did in #2940

**Comment by homm** [comment]
> compromise with HTTP redirect

It doesn't make sense because all links which could be to the former page most likely are https

**Comment by homm** [comment]
> Alternatively I can just revert everything I did in #2940

This is not required I think. Not such a big deal.

But anyway, I think https should be restored because of most links to python-pillow.org itself are https.

**Comment by aclark4life** [comment]
@python-pillow/owners OK I'm annoyed enough now to completely revert #2940 , including nameservers back to Cloudflare (I had previously moved them to AWS). If all goes well, we'll have https://python-pillow.org/pillow-perf restored shortly. It seems Cloudflare's CNAME flattening + GitHub's CNAME support w/https is not easily mapped to AWS features no matter how much clicking I do … not to mention cost comparison (free on Cloudflare, vs. some number of cents on AWS for various micro-charges.) 🤦‍♂️

**Comment by aclark4life** [comment]
@homm OK now I can at least say:

- Back to Cloudflare with CNAME flattening on python-pillow.org (CNAME for python-pillow.github.io)
- www CNAME added for python-pillow.org

I'm not sure how https ever worked, unless you are referring to "insecure" https (i.e. click through browser warnings to load).

**Comment by aclark4life** [comment]
@hugovk It gets tricky because with Cloudflare's CNAME flattening we're able to create a CNAME for python-pillow.org such that it can be used with GitHub Pages' CNAME support. So GitHub answers as python-pillow.org at least over HTTP. But currently it's not possible to force HTTPS on GitHub Pages with a custom domain, and it's not clear to me if SSL is supported at all… aside from self-signed certificates e.g. https://python-pillow.org.

**Comment by homm** [comment]
For some reasons https://python-pillow.github.io/pillow-perf redirects to HTTP:

```
$ curl -i https://python-pillow.github.io/pillow-perf
HTTP/1.1 301 Moved Permanently
Server: GitHub.com
Content-Type: text/html
Location: http://python-pillow.org/pillow-perf
X-GitHub-Request-Id: 55C8:7831:11940C0:182A953:5ADC7D76
Content-Length: 178
Accept-Ranges: bytes
Date: Sun, 22 Apr 2018 12:17:59 GMT
Via: 1.1 varnish
Age: 0
Connection: keep-alive
X-Served-By: cache-ams4122-AMS
X-Cache: MISS
X-Cache-Hits: 0
X-Timer: S1524399479.273347,VS0,VE91
Vary: Accept-Encoding
X-Fastly-Request-ID: 61573b4f45d0302da4fbb8972cfd8d21181a69d8
```

In my opinion secure protocol is much preferable than handsome URL. I'd like to revert this redirect, especially **permanently** redirect.

The URL https://python-pillow.github.io/pillow-perf is totally fit me. At some point, someone proposes to use shorter https://python-pillow.org/pillow-perf because it already works. I agreed and starting to use it everywhere. Then it broke because of no one guaranteed that it will work. I understand it.

What I want to achieve now is the redirect from https://python-pillow.org/pillow-perf to https://python-pillow.github.io/pillow-perf for all old links which could exist in my articles and normal work of https://python-pillow.github.io/pillow-perf, which is basic Github feature and I thought can't be broken.

What I have now: https://python-pillow.org/pillow-perf still doesn't work because of certificate issues. 
https://python-pillow.github.io/pillow-perf for some reason redirects to HTTP.

It's ok if it's impossible to make the redirect from https://python-pillow.org/pillow-perf to https://python-pillow.github.io/pillow-perf. But please leave the working https://python-pillow.github.io/pillow-perf at least.

**Comment by aclark4life** [comment]
Let's see if removing and re-adding with enforce HTTPS helps

![screen shot 2018-07-08 at 7 45 23 am](https://user-images.githubusercontent.com/72164/42419438-121835d8-8283-11e8-8a06-6180af6a39fa.png)

**Comment by hugovk** [comment]
It's working! https://python-pillow.org/

**Comment by aclark4life** [comment]
Yeah looks like we finally fixed @homm's issue, sorry for the delay @homm. And thanks @github for adding support for HTTPS on custom domains, much appreciated!

<img width="1031" alt="screenshot 2018-07-08 08 56 01" src="https://user-images.githubusercontent.com/72164/42419985-d36ac5e4-828c-11e8-8340-5acf89c21a8c.png">
