### ISSUE TITLE
AttributeError: 'JpegImageFile' object has no attribute 'read'

### ISSUE THREAD

**Issue by santhoshdc1590** [python-pillow/Pillow#3079]
### Pillow (5.0.0) and Python3.6

```python
from google.cloud import storage
import cv2
from tempfile import TemporaryFile
from PIL import Image

client = storage.Client()

bucket = client.get_bucket('document')
image = cv2.imread('15.png')
ima2 = cv2.cvtColor(image,cv2.COLOR_BGR2RGB)
out = Image.fromarray(ima2.reshape(ima2.shape[0],ima2.shape[1],3),"RGB")
buf = TemporaryFile()
out.save(buf,'JPEG')
buf.seek(0)
blob =  bucket.blob('Test15.jpg')
blob.upload_from_file(Image.open(buf))
```

Can anyone help?

**Comment by hugovk** [comment]
Please can you post the full error traceback?

**Comment by santhoshdc1590** [comment]
> Traceback (most recent call last):
>   File "/Users/santhosh/Documents/ImageShapeSize/Rough1.py", line 23, in <module>
>     blob.upload_from_file((Image.open(buf)))
>   File "/Users/santhosh/.virtualenvs/test/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 975, in upload_from_file
>     size, num_retries, predefined_acl)
>   File "/Users/santhosh/.virtualenvs/test/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 888, in _do_upload
>     size, num_retries, predefined_acl)
>   File "/Users/santhosh/.virtualenvs/test/lib/python3.6/site-packages/google/cloud/storage/blob.py", line 678, in _do_multipart_upload
>     data = stream.read()
> AttributeError: 'JpegImageFile' object has no attribute 'read'

**Comment by wiredfool** [comment]
You are trying to use a subclass of an image as a file, which it is not.  Your last line above should probably just be bucket.upload_from_file(buf). 

Also, if the point of the code is just to convert from a bgr png to a jpg, cv really isn’t necessary.

**Comment by santhoshdc1590** [comment]
@wiredfool This is for just for testing propose. Here's my main [objective](https://stackoverflow.com/questions/49671827/upload-an-image-from-cloud-function-python-to-google-cloud-storage)

if I replace only 

`blob.upload_from_file(Image.open(buf))`

with

`bucket.upload_from_file(buf)`

what will be the name of the uploaded file?

I got his error on trying in out

> Traceback (most recent call last):
>   File "/Users/santhosh/Documents/ImageShapeSize/Rough1.py", line 20, in <module>
>     bucket.upload_from_file((Image.open(buf)))
> AttributeError: 'Bucket' object has no attribute 'upload_from_file'

**Comment by wiredfool** [comment]
Sorry, that should have been `blob.upload_from_file`. 

I'm familiar with what you're using for the upload, but attempting to upload a Pillow object is not what you want. If it's not working with a TemporaryFile, it might need a NamedTemporaryFile.  But that's really a question for the other project.

**Comment by santhoshdc1590** [comment]
@wiredfool I did try it with `blob.upload_from_file(buf)` using `buf = TemporaryFile()` as well as with `buf = NamedTemporaryFile()`. It returns no error, but I don't seem to see the uploaded file on the `cloud-storage`.

Can you please suggestion a solution, I am full confused?

**Comment by wiredfool** [comment]
Your problem is with `google.cloud`, not Pillow. Your basic issue is that blob.upload_from_file([something]) isn't working with what you're passing in, so you need to dig into that, either on your own or with google.cloud's support.

**Comment by a2xchip** [comment]
@wiredfool Writing out buffer streams instead of `save` to file is something general for image library. However bypassing with temp file solution works using both `TemporaryFile` and `NamedTemporaryFile` @santhoshdc1590 

```python
f = TemporaryFile()
img.save(f, 'JPEG')
f.seek(0)

s3_client.upload_fileobj(f, bucket_name, 'path/name.jpg')
```
