### ISSUE TITLE
Problems with Layer Mask

### ISSUE THREAD

**Issue by andrey-hider** [python-pillow/Pillow#3096]
### What did you do?

Try to generate thumbnails using Pillow 5.1.0 for layer and for overall psd. 

### What did you expect to happen?

To have layer thumbnail grouped with layer mask

### What actually happened?

I got just layer thumbnail without layer mask.

### What versions of Pillow and Python are you using?

Pillow 5.1.0
Python 3.6.4

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
# for layer, using pillow with psd-tools2: https://github.com/kyamagu/psd-tools2
layer_image = layer.as_PIL()
layer_image.save('mask_layer_test.psd_o_layer_1_Layer 0.png')

# for overall psd, using pillow with psd-tools2: https://github.com/kyamagu/psd-tools2
merged_image = psd.as_PIL()
merged_image.save('mask_layer_test.psd_o_overall.png')
```

In attachment added two thumbnails and test psd with layer mask:
[mask_layer_test.zip](https://github.com/python-pillow/Pillow/files/1908153/mask_layer_test.zip)

**Comment by wiredfool** [comment]
If you look at the channels that you get in the image object, are you getting what you expect to see? If not, then your issue should be with the psd-tools project. 

Given that saving a png is a pretty well tested operation, I'd be surprised if that was the root of your issue.

**Comment by andrey-hider** [comment]
My issue solved here: [https://github.com/kyamagu/psd-tools2/issues/31](url)
