### ISSUE TITLE
Supporting 'shape' attribute for PIL.Image.Image?

### ISSUE THREAD

**Issue by shiba24** [python-pillow/Pillow#3106]
This is a suggestion (or question for the policy of the library, maybe). OK, I follow the template.

### What did you do?
```python
a = np.ones((100, 120, 3))
b = Image.fromarray(a.astype(np.uint8))
b.shape
```

### What did you expect to happen?
```python
(120, 100, 3)
```
for the output of `b.shape`.

### What actually happened?
And got
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-20-a8244287b6af> in <module>()
----> 1 b.shape

AttributeError: 'Image' object has no attribute 'shape'
```

### What versions of Pillow and Python are you using?
 - python 3.5.4
 - PIL version 4.1.1

So, I would like to know why this is not supported. I searched the word `shape` for the issues in this repo but could not find answers.
And if it does not cause any problem, why not?

Actually, this suggestion comes from my experience.
I was developing another library depending on Pillow. Then, I tried to expand possible input types, from PIL.Image.Image only to support numpy.ndarray as well. In order to support these types, it is more useful that both of them have the same API for the `shape` function, returning (h, w, c). OpenCV image type is actually numpy.ndarray as well.

I think this kind of things would happen in other libraries depending on PIL/Pillow as well.
But I am new to this community, so I am not sure this has been discussed.

Thank you very much in advance!

**Comment by hugovk** [comment]
My first impression is it's probably best not to mix these concepts up.

Like you say, an OpenCV image is really an array, and Pillow images are not.

The order difference in Pillow's x, y and OpenCV's h, w could also cause some confusion. 

But let's hear what others think too! 

In the meantime, you could probably subclass `Image` to your own class, which adds a `shape` attribute.

**Comment by wiredfool** [comment]
I don’t think subclassing will work easily.

**Comment by hugovk** [comment]
What do you think about adding `shape`?

**Comment by wiredfool** [comment]
Not convinced it's a good idea.

**Comment by homm** [comment]
You already have an error in expectations:

> What did you expect to happen?

```
(120, 100, 3)
```

```python
In [11]: a = numpy.ones((100, 120, 3))

In [12]: a.shape
Out[12]: (100, 120, 3)
```

As you see, shape is very confusing.

"Shape" is an attribute which is defined for `numpy.ndarray`. Pillow never defines than Pillow images and `numpy.ndarray` are compatible types somehow. APIs are totally different, so I don't see how this could be useful.

**Comment by shiba24** [comment]
Thank you everyone!! 
It makes sense. I will try to treat Image object in my own subclass and close this issue! 👍

**Comment by tcapelle** [comment]
I am curious how did you subclassed `PIL.Image.Image`. I am currently "patching" Image with `fastcore` like this:
```
@patch(as_prop=True)
def n_px(self: Image.Image):
    return self.size[0] * self.size[1]


@patch(as_prop=True)
def shape(self: Image.Image):
    return self.size[1], self.size[0]


@patch(as_prop=True)
def aspect(self: Image.Image):
    return self.size[0] / self.size[1]


@patch
def reshape(self: Image.Image, h, w, resample=0):
    "`resize` `x` to `(w,h)`"
    return self.resize((w, h), resample=resample)
```

but wanted to try a more traditional approach by subclassing `Image`.

**Comment by LOUEY233** [comment]
you can use 
`[h,w,c] = np,shape(img)`
