### ISSUE TITLE
Mode incorrectly determined on Image.fromarray with bool input dtype

### ISSUE THREAD

**Issue by akhmerov** [python-pillow/Pillow#3109]
### What did you do?

I observed that `Image.fromarray` works incorrectly on `bool` array input, likely due to an incorrectly determined mode or rawmode.

```python
import PIL
import numpy as np
print(np.array(PIL.Image.fromarray(np.eye(5, dtype=bool))))
```

### What did you expect to happen?

Same as `print(np.eye(5, dtype=bool))`, so:
```
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]
```

### What actually happened?

```
[[ True False False False False]
 [False False False False False]
 [False False False False  True]
 [False False False  True False]
 [False False  True False False]]
```

### What versions of Pillow and Python are you using?

Pillow: 5.1.0
python: '3.6.5 | packaged by conda-forge | (default, Apr  6 2018, 13:39:56) \n[GCC 4.8.2 20140120 (Red Hat 4.8.2-15)]'
numpy: 1.14.2

### Workaround

Use `Image.fromarray(boolean_array * np.uint(255))`

**Comment by aclark4life** [comment]
@akhmerov How about a PR to address this issue?

**Comment by wiredfool** [comment]
Probably related to: https://github.com/python-pillow/Pillow/issues/2044 and #350

**Comment by radarhere** [comment]
I've created PR #3790 to resolve this.

**Comment by zhangchenkai** [comment]
Bad news for guys, this bug still exists: 
```
print(np.array(Image.fromarray(np.eye(5, dtype=bool))))
[[ True False False False False]
 [False False False False False]
 [False False False False  True]
 [False False False  True False]
 [False False  True False False]]
```
Even worse, it will crash when you set argument `mode='1'` for fromarray function:

```
print(np.array(Image.fromarray(np.eye(5, dtype=bool), mode='1')))
[[False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]
 [False False False False False]]
```

Related issues:
#350
#1228
#1727
Oops, this bug has a long history since 2013.

My environment:
python:3.7.3
Pillow: 6.0
numpy: 1.16.3

**Comment by hugovk** [comment]
@zhangchenkai The fix is not in Pillow 6.0.0 (released ~2019-04-01), it will be in Pillow 6.1.0 due for release on 2019-07-01.

Please retest with master or wait for the release.

**Comment by stranskj** [comment]
The bug is still in releases on Pypi. Pillow 7.1.1, Python 3.8.2

**Comment by akhmerov** [comment]
@stranskj can't confirm with the same versions of Pillow and Python.

**Comment by hugovk** [comment]
Also cannot reproduce (both installed from PyPI via pip):

```pycon
Python 3.8.2 (v3.8.2:7b3ab5921f, Feb 24 2020, 17:52:18)
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
(.startup.py)
(imported collections, datetime, itertools, math, os, pprint, re, sys, time)
>>> from PIL import Image
>>> import numpy as np
>>> Image.__version__
'7.1.1'
>>> np.__version__
'1.18.2'
>>> print(np.array(Image.fromarray(np.eye(5, dtype=bool))))
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]
>>> print(np.eye(5, dtype=bool))
[[ True False False False False]
 [False  True False False False]
 [False False  True False False]
 [False False False  True False]
 [False False False False  True]]
>>> np.array(Image.fromarray(np.eye(5, dtype=bool))) == np.eye(5, dtype=bool)
array([[ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True],
       [ True,  True,  True,  True,  True]])
```

@stranskj If you still have a problem, please open a new issue and fill in the template with more details. Thanks.

https://github.com/python-pillow/Pillow/issues/new/choose
