### ISSUE TITLE
Support for OpenJPEG on Windows

### ISSUE THREAD

**Issue by tazr** [python-pillow/Pillow#3112]
### What did you do?

I am trying to use the OpenJPEG encoder with pillow on Windows.

* installed OpenJPEG 2.3 x64 and added its `bin` subdirectory to `PATH`
* then

      import numpy as np
      from PIL import Image
      Image.fromarray(np.zeros((128, 128), dtype=np.uint8)).save('foo.jp2')

### What did you expect to happen?

A `foo.jp2` file should have been created containing a 128×128 black image in the jpeg-2000 format.

### What actually happened?

An exception is returned with the message `OSError: encoder jpeg2k not available`

### What versions of Pillow and Python are you using?

python 3.6.5
pillow 5.1.0

**Comment by wiredfool** [comment]
Please review the installation docs: http://pillow.readthedocs.io/en/5.1.x/installation.html

You either need a pillow binary wheel with open joeg support, or you need to build one.

**Comment by tazr** [comment]
Oh OK. I think I have been fooled by [this part of the docs](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#jpeg-2000):

> To enable JPEG 2000 support, you need to build and install the OpenJPEG library, version 2.0.0 or higher, before building the Python Imaging Library.
>
>Windows users can install the OpenJPEG binaries available on the OpenJPEG website, but must add them to their PATH in order to use PIL (if you fail to do this, you will get errors about not being able to load the _imaging DLL).

Somehow I understood that on Windows, setting the OpenJPEG on the PATH is an alternative to building the entire library. Probably my bad.
