### ISSUE TITLE
Libjpeg 9c: ImportError, image not found

### ISSUE THREAD

**Issue by miguelmorin** [python-pillow/Pillow#3115]
### What did you do?
I installed a different software on Sunday 22 April and ran `brew update` and `brew cleanup`. This upgraded `libjpeg` to version 9c:
```bash
>brew info libjpeg
jpeg: stable 9c (bottled)
```
### What did you expect to happen?
I expected this line to work as it had been working prior to 22 April:
```python
from PIL import Image
```
### What actually happened?
Now I get this error:
```
from PIL import Image
  File "build/bdist.macosx-10.11-intel/egg/PIL/Image.py", line 56, in <module>
  File "build/bdist.macosx-10.11-intel/egg/PIL/_imaging.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/PIL/_imaging.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/miguel/.python-eggs/Pillow-4.3.0.dev0-py2.7-macosx-10.11-intel.egg-tmp/PIL/_imaging.so, 2): Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /Users/miguel/.python-eggs/Pillow-4.3.0.dev0-py2.7-macosx-10.11-intel.egg-tmp/PIL/_imaging.so
  Reason: image not found
```
### What versions of Pillow and Python are you using?

I confirm that I have the latest version of Pillow with
```bash
> pip install Pillow --upgrade
Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/site-packages (5.1.0)
```
I am running Python 2.7.10:
```bash
> /usr/bin/python --version
Python 2.7.10
```
I am running macOS 10.11.16.

I also tried to install `Libjpeg.8.dynlib` again with directions from [here](https://stackoverflow.com/questions/49728960/install-libjpeg-v8-to-opt-local)
```bash
curl -O -J -L http://www.ijg.org/files/jpegsrc.v8.tar.gz
tar xvfz jpeg*tar.gz
cd jpeg-8
./configure --prefix="/usr/local"    # prefix has to be "/usr/local/" for Pillow to work
make
sudo make install
```

Then I get a compatibility error:
```
 from PIL import Image
  File "build/bdist.macosx-10.11-intel/egg/PIL/Image.py", line 56, in <module>
  File "build/bdist.macosx-10.11-intel/egg/PIL/_imaging.py", line 7, in <module>
  File "build/bdist.macosx-10.11-intel/egg/PIL/_imaging.py", line 6, in __bootstrap__
ImportError: dlopen(/Users/miguel/.python-eggs/Pillow-4.3.0.dev0-py2.7-macosx-10.11-intel.egg-tmp/PIL/_imaging.so, 2): Library not loaded: /usr/local/lib/libjpeg.8.dylib
  Referenced from: /Users/miguel/.python-eggs/Pillow-4.3.0.dev0-py2.7-macosx-10.11-intel.egg-tmp/PIL/_imaging.so
  Reason: Incompatible library version: _imaging.so requires version 13.0.0 or later, but libjpeg.8.dylib provides version 9.0.0
```

**Comment by wiredfool** [comment]
You've got at least two versions of pillow installed, potentially in different pythons: 

`ImportError: dlopen(/Users/miguel/.python-eggs/Pillow-4.3.0.dev0-py2.7-macosx-10.11-intel.egg-tmp/PIL/_imaging.so, 2): Library not loaded: /usr/local/lib/libjpeg.8.dylib`

`Requirement already up-to-date: Pillow in /usr/local/lib/python2.7/site-packages (5.1.0)`

Likely what you had was Pillow 4.3, installed from source dynamically linked your old libjpeg. A new one got installed and that broke the dynamic linking. Then, you're going in circles because pip thinks you have pillow 5.1.0 installed.

**Comment by miguelmorin** [comment]
Thanks @wiredfool , well spotted! I can't remember how I installed Pillow 4.3, and it's not listed with these two methods:
```bash
> pip list
Package    Version
---------- -------
Pillow     5.1.0  
pip        10.0.1 
setuptools 38.5.2 
svgwrite   1.1.12 
wheel      0.30.0 
> find /Library/Python/2.7/site-packages -maxdepth 2 -name __init__.py
/Library/Python/2.7/site-packages/pip/__init__.py
/Library/Python/2.7/site-packages/pytz/__init__.py
/Library/Python/2.7/site-packages/virtualenv_support/__init__.py
```

I deleted the `~/.python-eggs/` directory but it was re-built when I ran my Python code again. I could not find how to delete this conflicting version. Do you know?

**Comment by wiredfool** [comment]
You probably have two python installations. Try `which pip` and `which python`.  I'm not seeing how you're invoking python for your stuff, but you should track down which one it's using as well.

**Comment by miguelmorin** [comment]
Thanks @wiredfool . Indeed, I found the issue in a previous Pillow library that I had installed with Eclipse. I run this in Eclipse:
```python
import os
print(os.system("echo $PYTHONPATH"))
```
and I get:
```console
pydev debugger: starting (pid: 903)
.../Library/Python/2.7/site-packages/Pillow-4.3.0.dev0-py2.7-macosx-10.11-intel.egg:...
```

I removed that and now it works fine. Keep up the great work!
