### ISSUE TITLE
Pillow installed but still say "No module named 'Pillow'"

### ISSUE THREAD

**Issue by ahmedelbendary** [python-pillow/Pillow#3117]
Actually i installed Pillow-5.1.0

so, when i import the module it should work 

it gives me "No module named 'Pillow'"

### Pillow-5.1.0 and Python 3.5

from tkinter import * 
import tkinter as tk
import time 
from Pillow import ImageTk, Image

root = tk.Tk()

![pillow](https://user-images.githubusercontent.com/25745226/39407207-578bb9a0-4bd3-11e8-9b83-b316425559f9.jpg)
![error](https://user-images.githubusercontent.com/25745226/39407215-62c3de6a-4bd3-11e8-95c8-3d4b0616741f.jpg)

**Comment by hugovk** [comment]
You need to do:
```python
from Pillow import ImageTk, Image
```

See https://pillow.readthedocs.io/en/5.1.x/handbook/tutorial.html for examples.

**Comment by ahmedelbendary** [comment]
@hugovk Thank you but it work with 
from PIL import ImageTk, Image

**Comment by 1997showroom** [comment]
i have installed the latest pillow and i still get this error

**Comment by radarhere** [comment]
@1997showroom if you are receiving the error "No module named 'Pillow'", that's because you should not be importing 'Pillow' - you should be importing 'PIL'.

**Comment by 1997showroom** [comment]
> @1997showroom if you are receiving the error "No module named 'Pillow'", that's because you should not be importing 'Pillow' - you should be importing 'PIL'.

So I have PIL and I am using python 3.7 I see a PIL folder in my 2.7 directory but not in 3.7
I downloaded homebrew also, I'm not sure if this made things worse or better.

**Comment by 1997showroom** [comment]
> @1997showroom if you are receiving the error "No module named 'Pillow'", that's because you should not be importing 'Pillow' - you should be importing 'PIL'.

Is pycharm just not finding Pillow, this is what I get from my terminal when I try to install pillow
Requirement already satisfied: pillow in /Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages (6.1.0)

**Comment by radarhere** [comment]
I would guess that it's not finding it, yes. pip is telling that Pillow is already installed. If you would like to talk more about this, please create a new issue. Alternatively, since your situation doesn't indicate any fault in Pillow itself, you could ask on StackOverflow.

**Comment by 1997showroom** [comment]
Yes I got it to work by going to preferences and adding it in the
interpreter, thank you !!
I actually didn't realize stack was for that , im still figuring out this
stuff having so much fun though
https://www.instagram.com/little___river/

**Comment by RXVAN** [comment]
Hey, i am kinda new to all this, i have installed pillow and it's saying "ModuleNotFoundError: No module named 'PIL'",
i run "pip install pillow" and get this: "Requirement already satisfied: pillow in c:\python37\lib\site-packages (7.2.0)",
Maybe i am doing something wrong? please, let me know, thanks.

also, what im doing is: "from PIL import Image" <- maybe that is wrong? im not sure, anyway, thanks in advance!

**Comment by radarhere** [comment]
Hi @RXVAN. If it's conceivable that you have more than one version of Python installed, then it is possible that pip and your Pillow import are running on different copies of Python.

If, for example, you are running
```
pip install Pillow
python3 script.py
```
then `pip` might not be attached to `python3`. To guard against this, you can run
```
python3 -m pip install --upgrade Pillow
```

This suggestion can also be seen at https://pillow.readthedocs.io/en/stable/installation.html#windows-installation

**Comment by BlitzJB** [comment]
from how they introduced Pillow in their docs, i thought it was an intendent library and depended on PIL. Thanks you guys for clarifying
