### ISSUE TITLE
The correct way to transform gif image to png image

### ISSUE THREAD

**Issue by wenouyang** [python-pillow/Pillow#3119]
Hello,

I am trying to transform images from gif format to png format. This is how I did

```
   def _gif_to_png(gif_dir, png_dir):  
        img_names = tf.gfile.ListDirectory(gif_dir)
 
         for f in img_names:
        # get the filename without the extension
         basename = os.path.basename(f).split(".")[0]
    
         im = Image.open(os.path.join(gif_dir,f))
         transparency = im.info['transparency'] 
         png_file_name = os.path.join(png_dir, basename+'.png')
         im.save(png_file_name, transparency=transparency)
         png_names = tf.gfile.ListDirectory(png_dir)
```
However, I got the following error message

 ```
  transparency = im.info['transparency']
KeyError: 'transparency'
```
What might be the problem and how to fix it?

**Comment by radarhere** [comment]
The problem would be that at least some of the images you are processing don't have a 'transparency' info value.

So, I would change the line to `transparency = im.info.get('transparency')`, which will either get the value from the info dictionary, or set the `transparency` variable to `None` if there is no 'transparency' key in info.
