### ISSUE TITLE
DeprecationWarning: Using or import the ABCs from 'collections' is deprecated

### ISSUE THREAD

**Issue by JianXin-Yun** [python-pillow/Pillow#3122]
![default](https://user-images.githubusercontent.com/26893563/39669450-a4f8636e-511e-11e8-97e7-50aa6a3df01b.PNG)
![default](https://user-images.githubusercontent.com/26893563/39669456-b11ed056-511e-11e8-9fc9-4ec42ea37ac3.PNG)
Warning above,look screenshots above,how to solve this warning?

**Comment by hugovk** [comment]
Thanks, some abstract base classes were moved from `collections` to `collections.abc` in Python 3.3, raise a `DeprecationWarning` in 3.7, and will be removed in 3.8.

https://docs.python.org/3.7/whatsnew/3.7.html#deprecated

See PR #3123 for a fix.
