### ISSUE TITLE
How can I use PIllow.Image from C program?

### ISSUE THREAD

**Issue by jczaja** [python-pillow/Pillow#3127]
Hi,

Is it possible to use Pillow.Image in C application?  
What I want is that I need to call: *PIL.Image.resize(...,interpolation=PIL.Image.ANTIALIAS)*
from C program. 

If this is not possible then could you please kindly point me to code of Pillow where I can find implementation of :  *PIL.Image.resize(...,interpolation=PIL.Image.ANTIALIAS)*

If possible I would love to **avoid** embedding python into C code.

Why I need that? I'm working on C program that is using machine learning model. Model whas trained
in Pythin+PIL program. But I want to infer (use) model in C application. I was not able to get resize
of OpenCV(I tried number of available options) to produce the same result (to the values) as when using PIL.Image.ANTIALIAS

Thanks in advance for answering to this thread

**Comment by homm** [comment]
> If this is not possible then could you please kindly point me to code of Pillow where I can find implementation of : PIL.Image.resize

Sure: https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Resample.c#L537

**Comment by jczaja** [comment]
@homm Thank you very much!
