### ISSUE TITLE
Tiff conversion to PDF produces (mostly) blank file

### ISSUE THREAD

**Issue by Saintroi** [python-pillow/Pillow#3131]
### Intro
I'm using the following function to get a TIFF image off of a server, save it as a PDF and then eventually present it as the result of an API request. Currently the function just returns the path of the PDF, I also have some stuff in there where I try saving the TIFF locally to see if it converts any better, also tried converting it to L, P, and RGB with no success.

To be clear, the code executes with no errors.

### Result
The resulting PDF is mostly blank with some white bars that are pretty small. Saving the TIFF from the network to the local directory works fine.

I will attach the PDF, I cannot attach the TIFF image as it contains sensitive financial information.
[VendNo 3form InvNo 524174.pdf](https://github.com/python-pillow/Pillow/files/2006800/VendNo.3form.InvNo.524174.pdf)

### Code
```python
def getImage(self, path):
    pth = path.replace("\\\\", "\\")
    if pth == "" or path == "None": return ""
    spl = pth.split('\\')
    fname, ext = os.path.splitext(spl[len(spl)-1])
    outfile = "C:/railway/static/" + fname +  ".pdf"
    temp = "C:/railway/static/" + fname +  ".tiff"
    if path != outfile:
        try:
            image = Image.open(path)
            image.save(temp, save_all = True)
            image = Image.open(temp)
            image.convert("L")
            print("opened")
            image.save(outfile, save_all = True)
        except IOError as e:
            print("cannot convert", path, e)
            return "API I/O Error"

        #os.remove(outfile)
    return outfile
```

**Comment by radarhere** [comment]
Are you able to obscure the financial information? Attach the image would help in replicating the problem.

If you tell me that editing the image to obscure the information causes the problem to be resolved, I understand. In that case, could you at least try saving the image in a different format? At the moment, I look at this issue and I'm unclear on whether the issue is reading the image from the TIFF or saving the image as a PDF.

**Comment by radarhere** [comment]
Okay, so, the simplest code to replicate then is -

```
from PIL import Image
image = Image.open('in.tif')
image.save("out.pdf", save_all=True)
```

Running it without `save_all` produces a different error.

@Saintroi in your code, you have a line `image.convert("L")`. This doesn't transform the image in place, but instead returns the transformed object. So it should be `image = image.convert("L")`.

I presume you'll be interested to know that with that change, a correct looking PDF is generated. However, the `convert` operation does change it to be a one page image. So I would suggest changing -

```
image.convert("L")
print("opened")
image.save(outfile, save_all = True)
```

to -

```
from PIL import ImageSequence
pages = []
for page in ImageSequence.Iterator(image):
    pages.append(page.convert("L"))
print("opened")
pages[0].save(outfile, save_all = True, append_images=pages[1:])
```

That should give you a working multi-page PDF.

**Comment by Saintroi** [comment]
@radarhere That worked perfectly, thank you so much! I didn't see anything about the Iterator or append_images from the documentation or googling, so maybe someone wants to make those more clear. I appreciate the assistance!
