### ISSUE TITLE
Size of object after conversion doesn't change!

### ISSUE THREAD

**Issue by Abhisek-** [python-pillow/Pillow#3139]
![pillow-grey2rgb](https://user-images.githubusercontent.com/9455582/40279896-899888a6-5c68-11e8-9632-e8c47f91f88b.png)
### What did you do?
I tried to convert a *black and white* image to *RGB* image.

### What did you expect to happen?
After conversion I thought the size would be (X, X, 3)

### What actually happened?
But after conversion the size became (X, X). But when I convert to numpy array, the size is as expected.

### What versions of Pillow and Python are you using?
Python - 3.5.2
Pillow - 5.1.0

```python
img = Image.open(image)
img = img.convert('RGB')
img.load()
print(img.size)             # (2048, 2048)
ar = np.asarray(img, dtype = "int32")
print(ar.shape)             # (2048, 2048, 3)
```

**Comment by hugovk** [comment]
`Image.size` always returns a (width, height) 2-tuple.

https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.size

**Comment by Abhisek-** [comment]
@hugovk my bad! Didn't see that
