### ISSUE TITLE
Save fails after converting 16-bit RGB to grayscale

### ISSUE THREAD

**Issue by nelarsen** [python-pillow/Pillow#3150]
### What did you do?
Downloaded test-PNG from "pngsuite" (see below), converted to grayscale using the matrix-option, saved the result.

### What did you expect to happen?
that the script would succeed like with almost all other PNGs from "pngsuite"

### What actually happened?
Save fails with

```
Traceback (most recent call last):
  File "C:/base2_nl/py-grayscale/minimalExampleBug.py", line 5, in <module>
    im.save('tbbn2c16-out.png')
  File "C:\Python36\lib\site-packages\PIL\Image.py", line 1935, in save
    save_handler(self, fp, filename)
  File "C:\Python36\lib\site-packages\PIL\PngImagePlugin.py", line 790, in _save
    transparency = max(0, min(65535, transparency))
TypeError: '<' not supported between instances of 'tuple' and 'int'
```

### What versions of Pillow and Python are you using?
Pillow 5.1.0
Python 3.6.5

### Minimal example to reproduce the error
```python
from PIL import Image

im = Image.open('tbbn2c16.png') # from here: http://www.schaik.com/pngsuite/tbbn2c16.png
im = im.convert("L",  (0.22, 0.72, 0.06, 0))
im.save('tbbn2c16-out.png') # fails
```

BTW in this case transparency is a tuple with the following value before the exception:
```python
transparency  = (65535,65535,65535)
```

Probably line 790 would have produced the expected result in Python 2.7, but is invalid in Python 3.x when mixing integers and tuple parameters.

**Comment by radarhere** [comment]
The problem as I see it is that the transparency value is not being converted along with the image pixel values - `(65535,65535,65535)` is an RGB value, not an L value. I have created #3205 to add this functionality.

While this doesn't raise an error in Python 2, Python 2 still does not have the correct behaviour. Python 2 works through the different transparency type with it's idea that `min(4, (1,2,3))` is 4.
