### ISSUE TITLE
Random image

### ISSUE THREAD

**Issue by solarzc** [python-pillow/Pillow#3162]
### What did you do?
create a random image
### What actually happened?
not random
### What versions of Pillow and Python are you using?
3.6

```python
from PIL import Image
import numpy as np

arr = np.random.randint(0,255,(100,100,3))
print(arr)
im = Image.fromarray(arr,'RGB')
im.show()
```
pic
![image](https://user-images.githubusercontent.com/33649176/41144732-6eb8cede-6b30-11e8-9700-292b30b44415.png)

**Comment by radarhere** [comment]
Could you elaborate on what the problem is? When I run your script, I get an image that looks similar to your attached image, but is different each time - so I would conclude that it is random.

**Comment by radarhere** [comment]
If your goal is to simply get a random image, I can suggest the following code -

```
import random
from PIL import Image
im = Image.new('RGB',(100,100))
pixels = im.load()
for x in range(im.size[0]):
	for y in range(im.size[1]):
		pixels[x, y] = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
im.show()
```

**Comment by cgohlke** [comment]
`arr = np.random.randint(0,255,(100,100,3)` is `int32`. Pillow seems to read it as `uint8`. Hence the repeating red, green, blue, black columns. Using `arr = np.random.randint(0,255,(100,100,3), dtype='uint8')` works as expected.

**Comment by solarzc** [comment]
@cgohlke yes, i miss the type.thank u

**Comment by paulo20223** [comment]
> If your goal is to simply get a random image, I can suggest the following code -
> 
> ```
> import random
> from PIL import Image
> im = Image.new('RGB',(100,100))
> pixels = im.load()
> for x in range(im.size[0]):
> 	for y in range(im.size[1]):
> 		pixels[x, y] = (random.randint(0, 255), random.randint(0, 255), random.randint(0, 255))
> im.show()
> ```

pixels[x, y] = random.choices(range(255), k=3)
