### ISSUE TITLE
winbuild SP1 download no longer available

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#3167]
https://github.com/python-pillow/Pillow/blob/master/winbuild/build.rst has a 'Microsoft Windows SDK for Windows 7 and .NET Framework 3.5 SP1' link - https://www.microsoft.com/en-us/download/details.aspx?id=3138. That URL now reports that the download that is no longer available.

**Comment by aclark4life** [comment]
@radarhere Thanks, removed it for now
