### ISSUE TITLE
Saving BLP files

### ISSUE THREAD

**Issue by Promises** [python-pillow/Pillow#3176]
Any chance for saving BLP1 files being added in the near future?

**Comment by hugovk** [comment]
There's partial support for reading BLP1: 
https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html?highlight=blp1#blp

There's no plans for further support, but pull requests are welcome. Please see: 
https://github.com/python-pillow/Pillow/blob/master/.github/CONTRIBUTING.md.

**Comment by Promises** [comment]
i would make a pull request if I had any idea of how images work :P

**Comment by radarhere** [comment]
PR #6069 resolves this. By default, BLP images will be saved as BLP2, but you can save as BLP1 with `im.save("out.blp", blp_version="BLP1")`.
