### ISSUE TITLE
Website SSL error

### ISSUE THREAD

**Issue by JMoVS** [python-pillow/Pillow#3179]
### What did you do?

Opened https://python-pillow.org/ - got an SSL error warning

### What did you expect to happen?

No warnings ;-)

**Comment by radarhere** [comment]
Did you find this link somewhere, or did you just decide to try https?

**Comment by JMoVS** [comment]
Duckduckgo turned it up:

https://duckduckgo.com/?q=pillow+python&ia=web

**Comment by MrYoda** [comment]
This address exists on the [Pillow PyPi](https://pypi.org/project/Pillow/) page too.

**Comment by hugovk** [comment]
I expect there's not much we can do about DuckDuckGo, just need to wait for them to update their index.

The PyPI link was updated to http://python-pillow.org in https://github.com/python-pillow/Pillow/pull/3045, which will be updated on PyPI in the next release in a couple of weeks.

Thanks both, I'll close this now. Please let us know if you spot any more showing up!

**Comment by hugovk** [comment]
I don't think it's been tried yet, but it's been suggested: https://github.com/python-pillow/Pillow/issues/3060#issuecomment-385978701.

**Comment by aclark4life** [comment]
@JMoVS Yeah please track #3060 for this, hopefully will get to it soon.
