### ISSUE TITLE
"ResourceWarning: unclosed file" with raw data (mmap)

### ISSUE THREAD

**Issue by danpla** [python-pillow/Pillow#3184]
Images containing raw data sometimes give `ResourceWarning: unclosed file` on my Linux machine, because the file opened for `mmap` is not closed.

https://github.com/python-pillow/Pillow/blob/968c2cf3c9c1e82f074a65c8c80d0da222d42eff/src/PIL/ImageFile.py#L177-L179

**Comment by aclark4life** [comment]
@danpla Open a PR?
