### ISSUE TITLE
How do I perform a "clean" uninstall of Pillow and libraqm?

### ISSUE THREAD

**Issue by mostafaasadi** [python-pillow/Pillow#3194]
### What did you do?
I installed pillow from github and libraqm with install_raqm.sh
so I prefered to downgrade because of some reason, and uninstall it and installed from pypi.
for now it seems that libraqm has some problem with my code (or ...) and I want to totally remove old installation of pillow(from source)  + raqm and fresh install pypi version.
is there any method?
### What did you expect to happen?
it works perfectly
### What actually happened?
```
Traceback (most recent call last):
  File "gent.py", line 221, in <module>
    main()
  File "gent.py", line 137, in main
    font=ImageFont.truetype("iransansb.ttf", 30)
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageDraw.py", line 220, in text
    mask, offset = font.getmask2(text, self.fontmode, *args, **kwargs)
  File "/usr/local/lib/python3.5/dist-packages/PIL/ImageFont.py", line 167, in getmask2
    size, offset = self.font.getsize(text, direction, features)
OSError: invalid face handle
[1]    24128 segmentation fault (core dumped)  python3 gent.py
```
### What versions of Pillow and Python are you using?
```
>>> from PIL import Image
>>> Image.PILLOW_VERSION
'5.1.0'
```

**Comment by hugovk** [comment]
Did you get this sorted?

If not, does this help? 

```sh
cd raqm-0.5.0
make clean
pip uninstall pillow
```
