### ISSUE TITLE
module 'PIL._imaging' has no attribute 'tiff_lzw_decoder'

### ISSUE THREAD

**Issue by YubinXie** [python-pillow/Pillow#3195]
### What did you do?
I tried to use PIL to open tiled TIFF image, compressed in tiff lzw format. Then I got the error:
`module 'PIL._imaging' has no attribute 'tiff_lzw_decoder'`

I did not find any helpful information yet.
### What versions of Pillow and Python are you using?
Python 3.6 (and 2.7), PILLOW 5.1.0

### Code:

```python
import PIL
from PIL import Image, TiffImagePlugin
TiffImagePlugin.READ_LIBTIFF=True
dir(PIL._imaging)
[‘DEFAULT_STRATEGY’, ‘FILTERED’, ‘FIXED’, ‘HUFFMAN_ONLY’,
 ‘PILLOW_VERSION’, ‘RLE’, ‘__doc__‘, ‘__file__‘, ‘__loader__‘, ‘__name__‘, ‘__package__‘, ‘__spec__‘, 
‘alpha_composite’, ‘bcn_decoder’, ‘bit_decoder’, ‘blend’, ‘convert’, ‘copy’, ‘crc32’, ‘draw’, 
‘effect_mandelbrot’, ‘effect_noise’, ‘eps_encoder’, ‘fill’, ‘fli_decoder’, ‘font’, ‘getcodecstatus’, 
‘getcount’, ‘gif_decoder’, ‘gif_encoder’, ‘hex_decoder’, ‘hex_encoder’, ‘jpeg_decoder’, 
‘jpeg_encoder’, ‘jpeglib_version’, ‘libtiff_decoder’, ‘libtiff_encoder’, ‘linear_gradient’, ‘map_buffer’, 
‘new’, ‘outline’, ‘packbits_decoder’, ‘path’, ‘pcd_decoder’, ‘pcx_decoder’, ‘pcx_encoder’, 
‘radial_gradient’, ‘raw_decoder’, ‘raw_encoder’, ‘sun_rle_decoder’, ‘tga_rle_decoder’, 
‘tiff_lzw_decoder’, ‘wedge’, ‘xbm_decoder’, ‘xbm_encoder’, ‘zip_decoder’, ‘zip_encoder’, 
‘zlib_version’]
```

### Update:
Only when I down-grade to Pillow 4.2.1, `tiff_lzw_decoder` appears in my dir(PIL._imaging)

**Comment by radarhere** [comment]
You say that only when you downgrade does tiff_lzw_decoder appear, but it is listed in the code output above?

**Comment by YubinXie** [comment]
I did not mention the PIL version in my question, it is 4.2.1. The point of that codes is to show 'how I identify library'. But it is true that PIL version above 4.2 does not contain tiff_lzw_decoder, as you found that it was removed. 

So this is not a bug, it is function removal. The image I am using is medical data. It can not go public yet. Sorry. But it has nothing special. You can find any tiff image with lzw encoding.

**Comment by kkopachev** [comment]
@YubinXie I suspect you are using tiled tiff image, which currently only supported without compression. #3227 should fix that.

**Comment by hugovk** [comment]
Probably fixed by https://github.com/python-pillow/Pillow/pull/3227.
