### ISSUE TITLE
OSError: decoder tiff_adobe_deflate not available

### ISSUE THREAD

**Issue by YubinXie** [python-pillow/Pillow#3206]
### What did you do?
I tried to open and display a tiff file compressed in tiff_adobe_deflate and it failed.

`OSError: decoder tiff_adobe_deflate not available`

How can I get tiff_adobe_deflate decoder? I have installed libtiff. 

System: Mac OS

**Comment by radarhere** [comment]
What operating system are you using?

**Comment by YubinXie** [comment]
Mac OS

**Comment by kkopachev** [comment]
Is that tiled tiff?

**Comment by YubinXie** [comment]
Yes, tilted tiff image.

**Comment by kkopachev** [comment]
In that case Pillow is forced to not use libtiff. I'm currently working to add support for reading tiled images through libtiff and fighting with jpeg downsampling issues. 
Related issues #3044 #2754. 
In order to read your image, you could convert it to baseline image.

**Comment by YubinXie** [comment]
@kkopachev By re-defining im.size, loading the general tiled images are fine. I am able to work with tiled tiff_lzw compressed images. 

I think the main issues is absence of the tiff decoder. I did not find that decoder in my PILLOW plug-in library. It is not due to tiled tiff.

**Comment by kkopachev** [comment]
It's not using libtiff if image is tiled tiff 
https://github.com/python-pillow/Pillow/blob/master/src/PIL/TiffImagePlugin.py#L1243
https://github.com/python-pillow/Pillow/blob/master/src/PIL/TiffImagePlugin.py#L1313

**Comment by YubinXie** [comment]
@kkopachev Did you mean that even if I do not have  tiff_adobe_deflate decoder, as long as libtiff works,  tiff_adobe_deflate images can be handled? 

I saw other people's PIL._imaging has  tiff_adobe_deflate. I do not know why it is not in my PIL and do not know how to get it. 

`import PIL
from PIL import Image, TiffImagePlugin
TiffImagePlugin.READ_LIBTIFF=True
dir(PIL._imaging)
[‘DEFAULT_STRATEGY’, ‘FILTERED’, ‘FIXED’, ‘HUFFMAN_ONLY’,
 ‘PILLOW_VERSION’, ‘RLE’, ‘__doc__‘, ‘__file__‘, ‘__loader__‘, ‘__name__‘, ‘__package__‘, ‘__spec__‘, 
‘alpha_composite’, ‘bcn_decoder’, ‘bit_decoder’, ‘blend’, ‘convert’, ‘copy’, ‘crc32’, ‘draw’, 
‘effect_mandelbrot’, ‘effect_noise’, ‘eps_encoder’, ‘fill’, ‘fli_decoder’, ‘font’, ‘getcodecstatus’, 
‘getcount’, ‘gif_decoder’, ‘gif_encoder’, ‘hex_decoder’, ‘hex_encoder’, ‘jpeg_decoder’, 
‘jpeg_encoder’, ‘jpeglib_version’, ‘libtiff_decoder’, ‘libtiff_encoder’, ‘linear_gradient’, ‘map_buffer’, 
‘new’, ‘outline’, ‘packbits_decoder’, ‘path’, ‘pcd_decoder’, ‘pcx_decoder’, ‘pcx_encoder’, 
‘radial_gradient’, ‘raw_decoder’, ‘raw_encoder’, ‘sun_rle_decoder’, ‘tga_rle_decoder’, 
‘tiff_lzw_decoder’, ‘wedge’, ‘xbm_decoder’, ‘xbm_encoder’, ‘zip_decoder’, ‘zip_encoder’, 
‘zlib_version’]`

**Comment by hugovk** [comment]
Probably fixed by https://github.com/python-pillow/Pillow/pull/3227.
