### ISSUE TITLE
Can't open tiff files

### ISSUE THREAD

**Issue by udion** [python-pillow/Pillow#3210]
I ran 

`Image.open('Test_026.tiff')`

I got the following error:

```
>>> PIL.Image.open('Test_026.tiff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/udion/anaconda3/lib/python3.6/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file 'Test_026.tiff'
```

pillow version is 5.1.0

**Comment by radarhere** [comment]
If you download https://github.com/python-pillow/Pillow/blob/master/Tests/images/copyleft.tiff?raw=true, do you experience this error with that file?
If yes, then what operating system are you using? How did you install Pillow?
If no, then it is not all tiff files, so would you mind uploading Test_026?

**Comment by udion** [comment]
I think something was wrong with the file. Thanks.

**Comment by fractional-ray** [comment]
I am also having this issue. I tried to download and tried that image it produced the same error

**Comment by hugovk** [comment]
@fractional-ray Please can you open a new issue?

**Comment by Praewizz** [comment]
I'm also having this issue. Can you fix this issue?

**Comment by hugovk** [comment]
@Praewizz Please can you open a new issue?
