### ISSUE TITLE
Image.copy() does not copy "Image.format" attribute

### ISSUE THREAD

**Issue by SandeR2012** [python-pillow/Pillow#3212]
`Image.format` attribute is not being copied when using `Image.copy()` method. I was expecting that this data will be also copied. 

### What versions of Pillow and Python are you using?
PIllow 5.1.0, Python 2.7.12, Ubuntu 16.04

```python
from PIL import Image

img = Image.open("image.jpg")
print(img.format)  #  'JPEG'

img_copy = img.copy()
print(img_copy.format)  # None
```

**Comment by amppumas** [comment]
The docs specify this behaviour http://pillow.readthedocs.io/en/5.2.x/reference/Image.html#PIL.Image.filename , not sure if it is the best design.

**Comment by SandeR2012** [comment]
Thanks, should've checked the docs first, but looked only on source code. 
Is there any rationale why it was made like this? And, please, close the issue if it's irrelevant.

**Comment by homm** [comment]
When you open an image from a file, you get the instance of one of the image plugins, for example, JpegImageFile(). After applying of any operation (including `copy`), you get an instance of `Image` class, which is not familiar with any storage. Information about the original file exists only in original image, after any operation, it is not the original image.
