### ISSUE TITLE
Unaligned access crash

### ISSUE THREAD

**Issue by DerDakon** [python-pillow/Pillow#3213]
The test suite crashes when run on sparc machines at several places because of SIGBUS errors, i.e. unaligned memory accesses. This usually affects also other platforms (ARM, Itanium), but to a lesser degree (often only slowdown and no crashes).

I have a unfinished patch, currently targetting 4.3.0 as that is what is my current problem in Gentoo. A port to master and PR will follow later once I get the testsuite to pass again.

Further details and preliminary patch at https://bugs.gentoo.org/659460

**Comment by aclark4life** [comment]
@DerDakon Sparc?! Well that makes my day. Anyway, feel free to open a PR with that patch …

**Comment by DerDakon** [comment]
The first one is already there…

**Comment by aclark4life** [comment]
Ah #3219 I assume, thanks

**Comment by DerDakon** [comment]
No, #3219 is totally irrelevant for this and was just spotted while trying to fix those. #3215 has a few fixes, but they are not enough. My current working set can be found in [this branch](https://github.com/DerDakon/Pillow/tree/unaligned-access).
