### ISSUE TITLE
Bad X.509 certificate in https://python-pillow.org/

### ISSUE THREAD

**Issue by jcea** [python-pillow/Pillow#3223]
Trying to enter https://python-pillow.org/ , I get a "bad certificate" notification. Checking it, I see a github X.509 certificate not listing "python-pillow.org" as an acceptable domain.

Please, fix. You can use, for instance, https://letsencrypt.org/ for free.

**Comment by aclark4life** [comment]
Thanks, let's wrangle this one under #3060
