### ISSUE TITLE
Sanitize TGA Image.info

### ISSUE THREAD

**Issue by danpla** [python-pillow/Pillow#3226]
Currently, the TGA image plugin sets `Image.info` "compression" to "tga_rle" on `load()`, while `save()` takes "rle" (bool) option. Both methods should use the same option for consistency. It probably makes sense to keep "rle" as TGA format doesn't support other compression methods, but "compression" may be more consistent with BMP and TIFF plugins. Neither of the options is documented, so there is no danger of breaking backward compatibility.

Also, it's not very clear whether `save()`  method should "inherit" info like TIFF and PNG plugins do:

https://github.com/python-pillow/Pillow/blob/4407cb65079a7d1150277e3b9a144996f56357c9/src/PIL/TiffImagePlugin.py#L1399-L1400

Currently, TGA plugin only inherits "orientation" but doesn't allow to specify it as a keyword to `save()`, and "id_section" is ignored altogether.

**Comment by radarhere** [comment]
I have created PR #3327 to fix this.
