### ISSUE TITLE
Clipping when rendering Khmer text using Pillow and libraqm

### ISSUE THREAD

**Issue by bluman88** [python-pillow/Pillow#3235]
### What did you do?
I used Pillow (5.3.0) to draw Khmer text onto an image using libraqm (0.5.0) for complex layout support (`layout_engine=ImageFont.LAYOUT_RAQM`).

### What did you expect to happen?
I expected the word "លោកុប្បត្តិ" to be rendered like this (output from MS Word):
![khmer-word](https://user-images.githubusercontent.com/40858377/42330976-40e56ee4-806c-11e8-9113-213634821421.png)

### What actually happened?
The left offset of the text was too large and resulted in clipping on the right-hand side of the bounding box (shown in red):
![khmer-pillow](https://user-images.githubusercontent.com/40858377/42330983-48c86f9e-806c-11e8-807a-22cb9b0fabe1.png)

Depending on how many glyphs of the word I chose to render, the offset became larger.

### What versions of Pillow and Python are you using?
I am using the following versions on Ubuntu 18.04:

- Python 3.4.3
- Pillow 5.3.0.dev0 
- libraqm 0.5.0 (from https://github.com/python-pillow/pillow-depends)
- libfreetype6: 2.8.1-2ubuntu2 
- libharfbuzz0b: 1.7.2-1ubuntu1

Code to reproduce clipping effect:

```python
#!/usr/bin/python3
# -*- coding: utf-8 -*-
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

img = Image.new("RGB", (512, 512), "white")
draw = ImageDraw.Draw(img)
font = ImageFont.truetype("Battambang-Regular.ttf", 60, layout_engine=ImageFont.LAYOUT_RAQM)
text = "លោកុប្បត្តិ"
draw.text((0, 0), text, (0, 0, 0), font=font)
img.save('out.png')
```

**Comment by bluman88** [comment]
Thanks for linking the raqm issue, Hugo. This is still a problem. Does anyone know what is causing the issue?

**Comment by bluman88** [comment]
Confirmed that this is still a problem with Pillow 5.5.0 and libraqm 0.5.0.

Does anyone know where to start looking?

**Comment by radarhere** [comment]
From #597, I find that the widths are different if Unicode numbers are used instead of characters. Neither is correct though.

```python
from PIL import Image, ImageDraw, ImageFont
img = Image.new('L', (300, 130))
d = ImageDraw.Draw(img)
font = ImageFont.truetype("KhmerOS.ttf", 30)
d.text((50, 30), u'\u179f\u17d2\u1793\u17b6', fill=(255), font=font)
d.text((150, 30), u'ស្នាក់', fill=(255), font=font)
img.save('test.tif')
```

**Comment by radarhere** [comment]
I've created PR #3787 to resolve this.

**Comment by bluman88** [comment]
Perfect. Thank you. PR #3787 fixes the issue I have been having. Here is the original text with correct layout using the new code:

![sample-out](https://user-images.githubusercontent.com/40858377/55947420-5250bd80-5c46-11e9-8976-9fd7ddbff1d0.png)
