### ISSUE TITLE
Release Pillow 5.3.0 on October 1, 2018

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#3236]
# [Release Checklist](https://github.com/python-pillow/Pillow/blob/master/RELEASING.md)

## Main Release

* [x] Open a release ticket e.g. https://github.com/python-pillow/Pillow/issues/3236
* [x] Develop and prepare release in ``master`` branch.
* [x] Check [Travis CI](https://travis-ci.org/python-pillow/Pillow) and [AppVeyor CI](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm passing tests in ``master`` branch.
* [x] Check that all of the wheel builds [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels) pass the tests in Travis CI.
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Update `CHANGES.rst`.
* [x] Run pre-release check via `make release-test` in a freshly cloned repo.
* [x] Create branch and tag for release e.g.:
```
    $ git branch 5.3.x
    $ git tag 5.3.0
    $ git push --all
    $ git push --tags
```
* [x] Create source distributions e.g.:
```
    $ make sdist
```
* [x] Create [binary distributions](#binary-distributions)
* [x] Upload all binaries and source distributions e.g. ``twine upload dist/Pillow-5.3.0-*``
* [x] Create a [new release on GitHub](https://github.com/python-pillow/Pillow/releases/new)
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), append `.dev0` to version identifier in `src/PIL/_version.py`

### Windows
* [x] Contact @cgohlke for Windows binaries via release ticket e.g. https://github.com/python-pillow/Pillow/issues/1174.
* [x] Download and extract tarball from @cgohlke and ``twine upload *``.

### Mac and Linux
* [x] Use the [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels):
```
    $ git clone https://github.com/python-pillow/pillow-wheels
    $ cd pillow-wheels
    $ git submodule init
    $ git submodule update
    $ cd Pillow
    $ git fetch --all
    $ git checkout [[release tag]]
    $ cd ..
    $ git commit -m "Pillow -> 5.3.0" Pillow
    $ git push
```
* [x] Download distributions from the [Pillow Wheel Builder container](http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/).

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the default version for Read the Docs is the latest release version, i.e. ``5.3.0`` rather than ``latest`` e.g. https://pillow.readthedocs.io/en/5.3.x/

**Comment by radarhere** [comment]
Is there anything that anyone would particularly like to see in this release?

**Comment by aclark4life** [comment]
@radarhere Good q. I like to try to make sure all issues are triaged and include everything that we can possibly include based on the backlog of requests. If we tag every untagged issue, that should give us a good idea of what is realistic to include by Oct 1. Not to mention, asking for updates on various outstanding issues and either getting a reply or not.

**Comment by hsoft** [comment]
Well, #3272 would simplify distro's jobs and make pillow move away from it's mp_compile hack.

**Comment by radarhere** [comment]
Okay, working my way through the checklist - @cgohlke would you be able to provide Windows binaries? Thanks!

**Comment by cgohlke** [comment]
[Here you go](https://www.lfd.uci.edu/~gohlke/download/Pillow-5.3.0-win-dist.zip).

**Comment by radarhere** [comment]
Thanks very much @cgohlke 

Okay, uploaded and released, although I don't have access to the Pillow Twitter account or Read The Docs account for the last two items in the checklist.

Thanks to everyone involved in this release.

**Comment by hugovk** [comment]
https://twitter.com/PythonPillow/status/1046694777150984192

**Comment by aclark4life** [comment]
@hugovk Can you share pw for Twitter with @radarhere ?

Thanks @radarhere, @python-pillow/pillow-team, all! Great job @radarhere; I'd say let's toggle back and forth now between @hugovk and @radarhere for future releases, unless folks have other suggestions.

**Comment by hugovk** [comment]
Shared!

Fine by me, except it's possible I might be away on 2018-01-01 meaning it might have to wait a couple of days.

**Comment by aclark4life** [comment]
@hugovk OK well we'll figure it out, I can always do it 2018-01-01 if no one else is available.
