### ISSUE TITLE
DLL load failed with Python 2.7.3 [MSC v.1900 64 bit (AMD64)]

### ISSUE THREAD

**Issue by mnpica** [python-pillow/Pillow#3238]
When  I import PIL, the dll load failed.

```
#* ImportError: DLL load failed: The specified module could not be found.
#* File 
#*"e:/PcbModelingToolKernel.py", 
#* line 24, in <module>
#*     from PIL import Image, ImageChops,ImageDraw
#* File 
#*"e:/PcbModelingTool\PIL\Image.py", 
#* line 56, in <module>
#*     from . import _imaging as core
```

I've searched many solutions but none of those works.
I installed it with pip, so it's not a conda problem.

Environment:
Pillow: 
  I've tried 4.0.0,4.1.1,5.0.0 and 5.2.0.
Python: 
 failed with '2.7.3  [MSC v.1900 64 bit (AMD64)]'
 success with '2.7.3  [MSC v.1700 64 bit (AMD64)]'

But I need to use new version of MSC for other libraries.

**Comment by cgohlke** [comment]
The Pillow wheels for Windows on PyPI are compiled for the [official CPython distributions](https://www.python.org/downloads/). 
For example, `Pillow-5.2.0-cp27-cp27m-win_amd64.whl` will work with `Python 2.7.x (...) [MSC v.1500 64 bit (AMD64)] on win32`.
You will have to build Pillow from source for `Python 2.7.3 [MSC v.1900 64 bit (AMD64)]` or `Python 2.7.3 [MSC v.1700 64 bit (AMD64)]`

**Comment by radarhere** [comment]
@mnpica how did you go with this? Were you able to build Pillow from source?

**Comment by radarhere** [comment]
Closing, as this question looks answered. Feel free to comment again if there is anything further.
