### ISSUE TITLE
Pillow setup.py find_library_file logic issue

### ISSUE THREAD

**Issue by tao12345666333** [python-pillow/Pillow#3244]
### What did you do?
Install Pillow by source code
### What did you expect to happen?
Install successfully.
### What actually happened?
Build error. 

      During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-_pl57v2h/setup.py", line 807, in <module>
        raise RequiredDependencyException(msg)
    __main__.RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

### What versions of Pillow and Python are you using?

Pillow：
Pillow-5.2.0
Python:
Python 3.7.0

detail see: https://github.com/docker-library/python/issues/305

Because the `library_dirs` lose `/usr/lib/x86_64-linux-gnu` or `/lib/x86_64-linux-gnu`

**Comment by tao12345666333** [comment]
The https://github.com/python-pillow/Pillow/blob/5.2.x/setup.py#L736  `dpkg-architecture` tool need install `dpkg-dev` to use.

**Comment by pslacerda** [comment]
The following warn/todo happened: https://github.com/python-pillow/Pillow/blob/5.2.x/setup.py#L340

**Comment by radarhere** [comment]
@tao12345666333 so to be clear, if you install dpkg-dev, installation works fine, and you're just interested in Pillow installation working without that requirement?

**Comment by tao12345666333** [comment]
@radarhere  yes. I want to find a way install Pillow without `dpkg-dev` requirement.

**Comment by hugovk** [comment]
https://github.com/docker-library/python/issues/305#issuecomment-404688760 says:

> `dpkg-dev` has not existed in the python:3 image since https://github.com/docker-library/python/commit/cd1f11aa745a05ddf6329678d5b12a097084681b. This is an oversight on our part and we will look to change the build dependency installation to be more like https://github.com/docker-library/php/pull/556 so that this won't happen in the future.

It was added back in https://github.com/docker-library/python/pull/310.

Does that fix it?

**Comment by tao12345666333** [comment]
@hugovk  Thanks. It has fixed.

```
(Tao) ➜  docker git:(master) ✗ docker run -it --rm python:3.7.0-stretch /bin/bash
root@f1eb0b20daa2:/# cd /tmp/
root@f1eb0b20daa2:/tmp# 
root@f1eb0b20daa2:/tmp# wget https://files.pythonhosted.org/packages/d3/c4/b45b9c0d549f482dd072055e2d3ced88f3b977f7b87c7a990228b20e7da1/Pillow-5.2.0.tar.gz 
--2018-09-18 03:07:52--  https://files.pythonhosted.org/packages/d3/c4/b45b9c0d549f482dd072055e2d3ced88f3b977f7b87c7a990228b20e7da1/Pillow-5.2.0.tar.gz
Resolving files.pythonhosted.org (files.pythonhosted.org)... 151.101.65.63, 151.101.193.63, 151.101.1.63, ...
Connecting to files.pythonhosted.org (files.pythonhosted.org)|151.101.65.63|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 14499068 (14M) [binary/octet-stream]
Saving to: ‘Pillow-5.2.0.tar.gz’

Pillow-5.2.0.tar.gz            100%[===================================================>]  13.83M  8.53MB/s    in 1.6s    

2018-09-18 03:07:55 (8.53 MB/s) - ‘Pillow-5.2.0.tar.gz’ saved [14499068/14499068]

root@f1eb0b20daa2:/tmp# pip install Pillow-5.2.0.tar.gz 
Processing ./Pillow-5.2.0.tar.gz
Building wheels for collected packages: Pillow
  Running setup.py bdist_wheel for Pillow ... done
  Stored in directory: /root/.cache/pip/wheels/19/4b/f9/db70c6f140d97dc73399e3b03ce2c748c2b09f8e507d325f27
Successfully built Pillow
Installing collected packages: Pillow
Successfully installed Pillow-5.2.0
root@f1eb0b20daa2:/tmp# 
root@f1eb0b20daa2:/tmp# 


```
