### ISSUE TITLE
PySide2

### ISSUE THREAD

**Issue by williamgeraldo** [python-pillow/Pillow#3247]
The PySide2 (Qt for Python)[1] project developed by qt is now available even in pypi[2], I have always changed ImageQt.py manually, but I think it's time to add such changing to the official source

[1] https://wiki.qt.io/Qt_for_Python
[2] https://pypi.org/project/PySide2

**Comment by hugovk** [comment]
Good to hear, although it looks like it's still at alpha at the moment: 5.11.0a1.dev1530776631953.

https://pypi.org/project/PySide2/#history

**Comment by williamgeraldo** [comment]
The project is yes in alpha, but has been developed since 2015, it is the version of the old pyside (which is not being developed anymore) for Qt 5.

Now that they have managed to increase the file size limit on pypi (something that took a while) else is fully functional.

Even other projects such as QtPy support PySide2 [1] since 2017-08.

[1] https://github.com/spyder-ide/qtpy/blob/master/CHANGELOG.md

**Comment by radarhere** [comment]
I think that this has since jumped out of alpha. The latest version at https://pypi.org/project/PySide2/#history is 5.11.1

**Comment by hugovk** [comment]
@williamgeraldo Please could you test https://github.com/python-pillow/Pillow/pull/3279? The next release is due on 2018-10-01.
