### ISSUE TITLE
`loop` parameter to `Image.save()` with `save_all=True` does not have correct default

### ISSUE THREAD

**Issue by rec** [python-pillow/Pillow#3255]
### What did you do?

I called `im.save(filename, save_all=True, append_images=images)`

### What did you expect to happen?

I expected to get a GIF image that looped forever, as per [the docs](https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving-sequences).

### What actually happened?

I got a GIF image that played once and stopped.

### What versions of Pillow and Python are you using?

4.3.0

### More comments.

The workaround is to call `im.save(filename, save_all=True, append_images=images, loop=0)`

The code causing this behavior is [this line](https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L538
) in Pillow.

If you wanted to make the code correspond to the documentation, then [this](https://github.com/rec/Pillow/commit/e12d989f66d7c7928a384c957aed1733e0e30946) might be the sort of change you wanted and I could send this out as a pull request.

Or, the docs could change to match the code.

Given the workaround, this isn't any sort of blocking issue for me, but felt I should report it now I found it!  Thanks for an excellent library...

**Comment by radarhere** [comment]
You linked to https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving-sequences. This is the WebP documentation. https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving is the GIF documentation. So, the GIF documentation does not actually say that it defaults to zero.

**Comment by rec** [comment]
You're right that I'm linking to the wrong documentation - sorry!  :-)

The documentation for GIFs should say what the default is, though.  

And IMHO the default that WebP uses is much more logical.  I venture to guess that 99% of all the animated GIFs in existence loop forever.

**Comment by radarhere** [comment]
Okay, I have created a PR to improve the documentation.

Regarding your comment that default should be to loop forever, generally the maintainers of Pillow do not like to change existing Pillow behaviour.

**Comment by rec** [comment]
Fair enough!  You don't want to change behavior without an excellent reason.
