### ISSUE TITLE
UnicodeEncodeError

### ISSUE THREAD

**Issue by betepok13** [python-pillow/Pillow#3259]
### Python 3.6.4, Pillow 5.2.0

```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont

font = ImageFont.truetype('10423.ttf', 70)
text = '18 июля'
img = Image.open('18144592.jpg')
draw = ImageDraw.Draw(img)
w1, h1 = draw.textsize(text)
```
An error occurred while executing the code:

![dfcvbvcb](https://user-images.githubusercontent.com/40733196/42848548-9b52f430-8a28-11e8-9e27-e48be21786ae.jpg)

**How can I fix it?**

Font:
[10423.zip](https://github.com/python-pillow/Pillow/files/2203591/10423.zip)

**Comment by hugovk** [comment]
You're using the default font, not 10423.ttf.

Change your last line to:
```python
w1, h1 = draw.textsize(text, font)
```

Docs: https://pillow.readthedocs.io/en/latest/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.textsize

**Comment by betepok13** [comment]
@hugovk 
Thank you for your help. Everything is working!
