### ISSUE TITLE
Can't save multi-page TIFF as PDF

### ISSUE THREAD

**Issue by darkdragon-001** [python-pillow/Pillow#3267]
I have a `tiff` image with multiple pages. [`tiffinfo`](http://manpages.ubuntu.com/manpages/bionic/man1/tiff2pdf.1.html) gives the following output

    TIFF Directory at offset 0x13384 (78724)
      Image Width: 2479 Image Length: 3504
      Resolution: 300, 300 pixels/inch
      Bits/Sample: 1
      Compression Scheme: CCITT Group 4
      Photometric Interpretation: min-is-white
      FillOrder: msb-to-lsb
      Orientation: row 0 top, col 0 lhs
      Samples/Pixel: 1
      Rows/Strip: 3504
      Planar Configuration: single image plane
      Page Number: 0-0
    TIFF Directory at offset 0x2d38c (185228)
      Image Width: 2479 Image Length: 3504
      Resolution: 300, 300 pixels/inch
      Bits/Sample: 1
      Compression Scheme: CCITT Group 4
      Photometric Interpretation: min-is-white
      FillOrder: msb-to-lsb
      Orientation: row 0 top, col 0 lhs
      Samples/Pixel: 1
      Rows/Strip: 3504
      Planar Configuration: single image plane
      Page Number: 1-0

When I save it again as multi-page `tiff`, I can also view it without problems:

    from PIL import Image
    im = Image.open('input.tiff')
    im.save('output.tiff', save_all=True)

When I save it as multi-page `pdf`, it has the correct number of pages, but a page size of `383201 x 0 mm`.

    from PIL import Image
    path = 'input.tiff'
    im = Image.open(path)
    im.save('output.pdf', save_all=True)

When I save the pages separately as `png`, everything works without problems. 

    from PIL import Image, ImageSequence
    im = Image.open('input.tiff')
    for i, page in enumerate(ImageSequence.Iterator(im)):
        page.save("page%d.png" % i)

When I save the pages separately as `pdf`

    from PIL import Image, ImageSequence
    im = Image.open('input.tiff')
    for i, page in enumerate(ImageSequence.Iterator(im)):
        page.save("page%d.pdf" % i)

an error is thrown

    Traceback (most recent call last):
      File "./convert.py", line 31, in <module>
        page.save("page%d.pdf" % i)
      File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1935, in save
        save_handler(self, fp, filename)
      File "/usr/lib/python3/dist-packages/PIL/PdfImagePlugin.py", line 177, in _save
        existing_pdf.write_obj(image_refs[pageNumber], stream=op.getvalue(),
    IndexError: list index out of range

For copyright reasons, I can't include my test image. I verified that the code works in general, by using a multi-page `tiff` created via #2804. The format from that image is:

    TIFF Directory at offset 0x8 (8)
      Image Width: 100 Image Length: 100
      Bits/Sample: 8
      Compression Scheme: None
      Photometric Interpretation: RGB color
      Samples/Pixel: 3
      Rows/Strip: 100
      Planar Configuration: single image plane
    TIFF Directory at offset 0x75c8 (30152)
      Image Width: 100 Image Length: 100
      Bits/Sample: 8
      Compression Scheme: None
      Photometric Interpretation: RGB color
      Samples/Pixel: 3
      Rows/Strip: 100
      Planar Configuration: single image plane

So it uses 3 channels with 8 bits each whereas my sample usees a black/white 1 bit image and specifies additional attributes like resolution, compression, fill-order, orientation, page number.

I am using Pillow `5.1.0` with Python `3.6.5` on Ubuntu `18.04`.

**Comment by radarhere** [comment]
To provide a partial answer, the 'IndexError: list index out of range' issue was fixed in #3137, so if you update to Pillow 5.2.0, that should be fixed.

**Comment by darkdragon-001** [comment]
I can confirm that the `IndexError` is solved in `5.2.0`. Although the dimensions of the single `pdf` pages are not the same as for the multi-page pdf (`383201 x 0 mm`). I just checked that the same problem exists for single-page `tiff`s of the same kind.

> Are you able to provide the tiffinfo from the generated 383201 x 0 image?

Unfortunately, since this is a `pdf` file, `tiffinfo` does not work. Tell me another tool to produce similar output for `pdf` files.

@radarhere: I can also offer you to privately send you test files when you promise to not share them and destroy them afterwards.

**Comment by radarhere** [comment]
Are you able to check if PR #3827 helps? It could be that this is really just the same as #1775

**Comment by darkdragon-001** [comment]
@radarhere Indeed the issue is fixed in master now!

**Comment by hugovk** [comment]
Thanks both!
