### ISSUE TITLE
Tests in the pypi .tar.gz archive

### ISSUE THREAD

**Issue by bcroq** [python-pillow/Pillow#3269]
The  `Pillow-5.2.0.tar.gz` archive on pypi weights 14MB but it only weights 574KB once the `Tests` folder is removed.

Do the tests really need to be pushed to pypi?

**Comment by hugovk** [comment]
Yes:

> Tests are distributed in the source version, which is the canonical reference for all of the distro packagers.

https://github.com/python-pillow/Pillow/pull/3007#issuecomment-370151930

**Comment by radarhere** [comment]
This question looks like it has been answered. Feel free to comment again if there is anything further.
