### ISSUE TITLE
Can't get "icc_profile"

### ISSUE THREAD

**Issue by fangcunguolin** [python-pillow/Pillow#3270]
I used the following code to get ICC profile, but ICC returned None. There is no "icc_profile" in im.info
```python
image = Image.open('test.jpg')
icc = image.info.get('icc_profile')
for x in im.info:
      print(x)
```
The JPG picture taken by the camera has "EXIF, DPI, MP" in im.info. After Photoshop saves and embeds ICC, there are "JFIF, jfif_version, DPI, jfif_unit, jfif_density, icc_profile".

I took photos with Nikon and Sony cameras, without any software processing, and did not find ICC profile using Pillow. But when GIMP and Photoshop are opened, you can check the use of Adobe RGB (1998) configuration files.

python 3.6  
Pliiow 5.2

**Comment by radarhere** [comment]
Are you able to upload a sample image here so that we can inspect it?

**Comment by fangcunguolin** [comment]
@radarhere This is the picture I used for testing. This picture was taken directly by Sony a7riii, and was not processed by Photoshop or other software. Thank you！
![_dsc4949](https://user-images.githubusercontent.com/33274131/43180348-33b8b282-900a-11e8-82b8-243c7f4caefd.JPG)

**Comment by fangcunguolin** [comment]
![image](https://user-images.githubusercontent.com/33274131/43180467-eb75fbd2-900a-11e8-93ea-64af9efedb47.png)

**Comment by bestvibes** [comment]
+1 same issue for me, shooting with a Sony A6000 and my file browser shows the same color profile as above but `image.info.get('icc_profile')` returns `None`. Please help!

**Comment by radarhere** [comment]
@bestvibes are you able to provide a sample image so that it can be inspected?

**Comment by kkopachev** [comment]
I've checked the attached image. Exiftool reports there is no embedded ICC profile. 
However, Exif data contains 
```
[EXIF] ColorSpace: Uncalibrated
[EXIF] InteropIndex: R03 - DCF option file (Adobe RGB)
```

[There is an article ](https://ninedegreesbelow.com/photography/embedded-color-space-information.html) explaining that some cameras don't bother embedding color profiles into files, but only indicate in Exif data what profile to be used. Presumably, image editing software should be smart enough to figure that out and save image with Adobe RGB profile embedded, so image is usable.

There is also old bug reported in firefox https://bugzilla.mozilla.org/show_bug.cgi?id=1322030 stating FF does not automatically apply Adobe RGB profile if EXIF contains InteropIndex=R03.

**Comment by radarhere** [comment]
https://www.sno.phy.queensu.ca/~phil/exiftool/TagNames/EXIF.html says that for ColorSpace 'an Adobe RGB image is indicated by "Uncalibrated" with an InteropIndex of "R03"'.

Regarding the ColorSpace, that link will show you that the ColorSpace tag ID is 0xa001. So
```
>>> from PIL import Image
>>> image = Image.open('test.jpg')
>>> print(image._getexif()[0xa001])
65535
```
65535 is 0xffff, which the link lists as the ColorSpace value for 'Uncalibrated'.

Regarding the InteropIndex, Pillow does not currently read data from the Interop subdirectory, so I have added that in PR #3594. 

The other information in the screenshot is '(8bpc)' - for that, you will find that `image.bits` is 8.

**Comment by radarhere** [comment]
In the impending Pillow 6.0.0 release, you will now be able to read the InteropIndex like so -

```python
>>> from PIL import Image
>>> im = Image.open("Tests/images/test.jpg")
>>> exif = im.getexif()
>>> exif.get_ifd(0xa005)
{1: 'R03', 2: b'0100'}
```

`0xa005` being the Interoperability IFD - https://www.awaresystems.be/imaging/tiff/tifftags/interoperabilityifd.html

@fangcunguolin do you consider this issue resolved?

**Comment by fangcunguolin** [comment]
@radarhere It’s great! Thanks a lot.
