### ISSUE TITLE
build error: --disable-tcl not recognised

### ISSUE THREAD

**Issue by prlw1** [python-pillow/Pillow#3275]
Essentially that says it all - I tried to build 5.2.0 using python 3.6 and --disable-tcl wasn't recognised.
An aside: is there a --disable flag for libimagequant?

This is all based on: http://pillow.readthedocs.io/en/3.0.x/installation.html#external-libraries
so may be a documentation bug.

**Comment by prlw1** [comment]
Search engine was hiding

http://pillow.readthedocs.io/en/5.2.x/installation.html

which mentions --disable-imagequant. Original problem still stands: using

```
/usr/pkg/bin/python3.6  setup.py  build_ext --disable-jpeg2000 --disable-tcl --disable-tk
```
gets option --disable-tcl not recognized

**Comment by radarhere** [comment]
Hi. Yes, this is a documentation problem, and thanks for finding it. #1932 changed Tk and Tcl to no longer be build requirements, but instead be loaded in runtime. Consequently, you don't need to enable or disable Tk or Tcl when building.

I've created a PR to remove the options from the documentation.
