### ISSUE TITLE
BMP open image shows inversion contradiction

### ISSUE THREAD

**Issue by morawi** [python-pillow/Pillow#3276]
### What did you do?
Loading handwriting word images via Image.open(); BMP format.

### What did you expect to happen?
Same background and foreground, but not contradiction

### What actually happened?
One set has a max of 255, the images of this set came with 255 as background, but 0 as foreground (the script of the word). The other images have 1 as max value, in this case, 0 came as background and 1 as foreground (the script of the word). Using show() functions, both images have white background, which should be the max value.
### What versions of Pillow and Python are you using?
Python 3.6; Pillow 5.1.0

[Images.zip](https://github.com/python-pillow/Pillow/files/2242290/Images.zip)

```python
from PIL import Image
import numpy as np
...
img = Image.open('the_image.bmp')
img.show()
img = np.array(img.getdata(), np.uint8).reshape(img.size[1], img.size[0], 1)

```

**Comment by radarhere** [comment]
Are you able to upload one of the images here?

**Comment by radarhere** [comment]
Wait, I see the zip now, nevermind

**Comment by radarhere** [comment]
Okay, so the question is - why does the numpy array produced by your code from ae07_001.bmp have a different max value than one from pe001_000.bmp?

The answer is [image modes.](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes)

Maybe you think that these images are in RGB mode, where (0,0,0) is black and (255,255,255) is white.

Actually, pe001_000.bmp is in 1 mode. This is black and white, where 0 is black and 255 is white - and there are no colours in between.

So far though, that doesn't break your expectations. However, ae07_001.bmp is in P mode. This means that it isn't storing the pixel values independently. Instead, the pixel values are stored as an index from a palette of colors. A pixel value of 0 means the first value in the palette, 1 is the second, and so on. Each image may have a different palette, and so 0 in one image doesn't have to be the same as 0 in another image at all. For this image, 0 is white and 1 is black.

If you would like to compare individual pixel values across images, I suggest you convert them to the same mode, without a palette.

```python
from PIL import Image
import numpy as np

ae07_001 = Image.open("ae07_001.bmp")
pe001_000 = Image.open("pe001_000.bmp")

print(ae07_001.mode)  # P
print(pe001_000.mode)  # 1

print("Without conversion, they are different")
print(np.amax(np.array(ae07_001.getdata())))  # 1
print(np.amax(np.array(pe001_000.getdata())))  # 255

print("If you convert ae07_001.bmp to 1, they are the same")
print(np.amax(np.array(ae07_001.convert("1").getdata())))  # 255
print(np.amax(np.array(pe001_000.getdata())))  # 255

print("If you convert them both to RGB, they are the same")
print(np.amax(np.array(ae07_001.convert("RGB").getdata())))  # 255
print(np.amax(np.array(pe001_000.convert("RGB").getdata())))  # 255
```

Let us know if you have any further questions about that.
