### ISSUE TITLE
How to open gif file in python 3, anybody knows a perfect method, please do a favour on me

### ISSUE THREAD

**Issue by amithnikhade** [python-pillow/Pillow#3292]
### What versions of Pillow and Python are you using?

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```

**Comment by radarhere** [comment]
```
from PIL import Image
im = Image.open('test.gif')
```

For more information, see http://pillow.readthedocs.io/en/5.2.x/handbook/tutorial.html

**Comment by yo1995** [comment]
```python
def decode_gif_file(filename):
    img = Image.open(filename)
    try:
        img.seek(1)
    except EOFError:
        print('Warning: it is a single frame GIF.')
        return img, 1
    return img, 2

# if multiframe
current_index = img.tell() + 1
img.seek(current_index)
# use ur frame with img below. loop current index and judge EOFError to get all frames.

```

hope it helps

**Comment by radarhere** [comment]
@yo1995 Thanks, you're right, I didn't consider that the question might be about multiple frames

There is also ImageSequence - http://pillow.readthedocs.io/en/5.2.x/reference/ImageSequence.html

```
from PIL import Image, ImageSequence

im = Image.open("animation.gif")

index = 1
for frame in ImageSequence.Iterator(im):
    frame.save("frame%d.png" % index)
    index += 1
```

**Comment by radarhere** [comment]
Feel free to comment if you have any further questions

**Comment by Darkiee2003** [comment]
what if the gif file is "tenor gif" if u check its link format is different ,how to open tenor gifs

**Comment by Darkiee2003** [comment]
https://tenor.com/view/lazycat-lazy-cat-food-coma-knackered-gif-6453121913169784842

this is the format of tenor gif

**Comment by radarhere** [comment]
If you open that webpage,
right-click on the image and open the image in a new tab,
and then again, right-click on the image and open the image in a new tab,
you will come to https://c.tenor.com/WY4YMJ7GMAoAAAAd/tenor.gif

That is a GIF that you can download and open with Pillow.
