### ISSUE TITLE
ImageGrab on mac ( coordinate problem ? )

### ISSUE THREAD

**Issue by jerb6** [python-pillow/Pillow#3293]
Hello ! 
I'm actually watching a tutorial on making a bot with Python using AI M, I want to take a snapshot of a specific area on my screen ( the little flash video game ) : 

<img width="1678" alt="capture d ecran 2018-08-05 a 21 26 31" src="https://user-images.githubusercontent.com/42121527/43689160-49a1df02-98f6-11e8-8ef2-2fb26f11c037.png">

so I did this code : 

```
 from PIL import ImageGrab
import os
import time

def screenGrab():
    x = 351
    y = 237
    im = ImageGrab.grab((x,y,x+645,y+484))
    im.save(os.getcwd() + "\\full_snap_" + str(int(time.time()) ) + ".png", "PNG")

if __name__ == '__main__':
    screenGrab() 
```

Normally the program should be doing this : 

<img width="646" alt="capture d ecran 2018-08-05 a 21 14 53" src="https://user-images.githubusercontent.com/42121527/43689174-77c516f6-98f6-11e8-93a2-5f07a13c505e.png">

But for whatever reason he took this instead : 

![sushigoround full_snap_1533497364](https://user-images.githubusercontent.com/42121527/43689184-a40eb79e-98f6-11e8-8711-f05bb433090f.png)

As you can see, the coordinates does not correspond to what I've wrote and it looks like he zoom on the screen too.. Weird..

and I use a macbook pro with High Sierra : 
<img width="301" alt="capture d ecran 2018-08-05 a 21 33 00" src="https://user-images.githubusercontent.com/42121527/43689216-3109cae4-98f7-11e8-9793-f90c2cf7ff72.png">

I use : 
Pillow  5.2.0    
pip  10.0.1   
python  (from my terminal ) 2.7.10
and Pycharm 

Can someone help me please ?? I'm desesperate... 
thank you very much !

**Comment by radarhere** [comment]
I can't replicate your problem, but here are some thoughts.

I would suggest running `im = ImageGrab()`, with no coordinates, and then looking at the resulting image to create the co-ordinates. Internally, `ImageGrab.grab` works by taking a screenshot of the whole screen, and then running `crop` - https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageGrab.py#L48 - https://pillow.readthedocs.io/en/5.2.x/reference/Image.html#PIL.Image.Image.crop

For me, starting with your initial image, the following coordinates produced the desired image -

```
x = 708
y = 497
im = im.crop((x,y,x+1272,y+960))
```

Note also that the coordinate system in Pillow starts at the upper left corner - http://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#coordinate-system

**Comment by jerb6** [comment]
Ok, than you so much for your answer ! So I did ``im = ImageGrab()`` with no coordinates, and here's the result : 
![sushigoround full_snap_1533501286](https://user-images.githubusercontent.com/42121527/43689822-25a0e738-9900-11e8-9f1b-715d67f73b6f.png)

He screen capture the hole screen.
and for the coordinate system, I originally started with the upper left corner ( 351,237,993,738 ).
If it works with you, I don't really know what to do..

**Comment by jerb6** [comment]
hello ! 
So, I enter your coordinates into my code and here's what he capture :

![sushigoround full_snap_1533530650](https://user-images.githubusercontent.com/42121527/43697412-74024bee-9944-11e8-9f00-f9e4cf572fd8.png)

``` 
from PIL import ImageGrab
import os
import time

def screenGrab():
    x = 708
    y = 497
    im = ImageGrab.grab(bbox=(x,y,x+1272,y+960))
    im.save(os.getcwd() + "\\full_snap_" + str(int(time.time()) ) + ".png", "PNG")

if __name__ == '__main__':
    screenGrab() 
```

But I think it's a little bit bigger than the original
I take a screenshot of the same thing with my mac internal screen capture ( cmd+shift+4 ) and the result is smaller, it fits the actual size of the game ( more accurate ? ).
 It's also with this (mac internal screen capture ) that I take the coordinate.

I don't know, if it's good or not.. And why with my coordinate it doesn't work.. ?

**Comment by jerb6** [comment]
Okay ! I found the solution ! 
After reading the link you gave me http://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#coordinate-system
It says : 
> The Python Imaging Library uses a Cartesian **pixel coordinate** system

I was taking the coordinate of my screen, and not the pixel coordinate !
the internal mac screen capture ( cmd+shift+4 ), **is not taking the pixel coordinate**!
Now it works perfectly !

**Comment by kllmctrl** [comment]
shift+ctrl+cmd+4

**Comment by rishav394** [comment]
> Okay ! I found the solution !
> After reading the link you gave me http://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#coordinate-system
> It says :
> 
> > The Python Imaging Library uses a Cartesian **pixel coordinate** system
> 
> I was taking the coordinate of my screen, and not the pixel coordinate !
> the internal mac screen capture ( cmd+shift+4 ), **is not taking the pixel coordinate**!
> Now it works perfectly !

ik its been 3 years but do you have any idea how I can get pixel coordinate on click?

**Comment by Tim-Ganger** [comment]
> > Okay ! I found the solution !
> > After reading the link you gave me http://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#coordinate-system
> > It says :
> > > The Python Imaging Library uses a Cartesian **pixel coordinate** system
> > 
> > 
> > I was taking the coordinate of my screen, and not the pixel coordinate !
> > the internal mac screen capture ( cmd+shift+4 ), **is not taking the pixel coordinate**!
> > Now it works perfectly !
> 
> ik its been 3 years but do you have any idea how I can get pixel coordinate on click on macos? All libs I've used gives me the screen coordinates.

Maybe this is a little bit too late, but I got it to work just by multiplying by 2. Not sure why this is, maybe it has something to do with the pixel density...? Unclear.
