### ISSUE TITLE
Saving a gif using `save` with append_images doesn't consider the parameter `delay`

### ISSUE THREAD

**Issue by zHaytam** [python-pillow/Pillow#3304]
### What did you do?
I created 4 images and added them to a list.
I then used the first image to save all the images in a gif animation using the `append_images` argument.

### What did you expect to happen?
Each frame in the GIF should last 2 seconds.

### What actually happened?
The gif loops very quickly.
The parameter `delay` is ignored, putting e.g. 'str' as the value still works so I'm guessing its not taken in consideration.

### What versions of Pillow and Python are you using?
Python 3.7.0
Pillow 5.2.0

```python
size = width, height = 400, 300
cards_folder = os.path.dirname(__file__) + '/../../../cards/'

imgs = []
for card in cards:
    file_name = ennemy_card.type.name.lower() + '_' + str(ennemy_card.number) + '.bmp'
    ennemy_card_img = Image.open(cards_folder + file_name)
    full_img = Image.new('RGB', size)
    full_img.paste(ennemy_card_img, (0, 0))
    imgs.append(full_img)

imgs[0].save('test.gif', format='GIF', save_all=True, append_images=imgs[1:], delay=2, loop=0)
```

**Comment by radarhere** [comment]
Use `duration=2000` instead of `delay=2`

https://pillow.readthedocs.io/en/5.2.x/handbook/image-file-formats.html#saving

> **duration**
> The display duration of each frame of the multiframe gif, in milliseconds. Pass a single integer for a constant duration, or a list or tuple to set the duration for each frame separately.

I'm interested to know if there is mistaken documentation out there, so why did you use the `delay` argument?

**Comment by zHaytam** [comment]
I'm actually ashamed that I didn't even look at the official documentation...
I saw the parameter in this article: http://pythoninformer.com/python-libraries/pillow/creating-animated-gif/.
Was `delay` ever used in Pillow or is the article just plain wrong?

**Comment by hugovk** [comment]
I've asked Python Informer to update their article.

**Comment by zHaytam** [comment]
Okay thank you!
