### ISSUE TITLE
TypeError: object of type 'NoneType' has no len()

### ISSUE THREAD

**Issue by tytarenko** [python-pillow/Pillow#3315]
### TypeError: object of type 'NoneType' has no len()

This image has a value "comment" is None. It raises that error.  

This is my PR 
https://github.com/python-pillow/Pillow/pull/3314

https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L527
```python
>    if "comment" in im.encoderinfo and 1 <= len(im.encoderinfo["comment"]) <= 255:
E                  TypeError: object of type 'NoneType' has no len()

```

https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L697

```python
    def _get_global_header(im, info):
        """Return a list of strings representing a GIF header"""
    
        # Header Block
        # http://www.matthewflickinger.com/lab/whatsinagif/bits_and_bytes.asp
    
        version = b"87a"
        for extensionKey in ["transparency", "duration", "loop", "comment"]:
            if info and extensionKey in info:
                if ((extensionKey == "duration" and info[extensionKey] == 0) or
>                  (extensionKey == "comment" and not (1 <= len(info[extensionKey]) <= 255))):
E                  TypeError: object of type 'NoneType' has no len()
```

```python
{'background': 160,
 'comment': None,
 'duration': 500,
 'optimize': True,
 'version': b'GIF89a'}
```

This code is reproducing that issue
```python
from PIL import Image
from io import BytesIO

filename = 'test.gif'


with open(filename, "rb") as fp:

    img = Image.open(fp)
    file_obj = BytesIO()

    print(img.info)

    getattr(img, "is_animated", False)

    print(img.info)

    img.save(file_obj, format="GIF")
```
![test2](https://user-images.githubusercontent.com/9821654/44784628-f9408780-ab96-11e8-9e9b-038467b6058a.gif)

**Comment by radarhere** [comment]
The code you have quoted is from GifImagePlugin, but the image you have attached is a PNG. Are you able to attach the problematic GIF file?

**Comment by tytarenko** [comment]
@radarhere Yes. You are right. I've added right gif image.
But I've dived into the code and find a sequence of action where it's happening

this is the method "is_animate" as the property, which is calling  
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L103

there are points where called the private method "_seek"
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L111
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L116

there is  the comment is setting the value from the value "block" 
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L203

there are points where the variable "block" is setting the value from the method "data"
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L180
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L210

in one of the cases, this method returns "None" 
https://github.com/python-pillow/Pillow/blob/master/src/PIL/GifImagePlugin.py#L58

This code is reproducing that issue
```
from PIL import Image
from io import BytesIO

filename = 'test.gif'


with open(filename, "rb") as fp:

    img = Image.open(fp)
    file_obj = BytesIO()

    print(img.info)

    getattr(img, "is_animated", False)

    print(img.info)

    img.save(file_obj, format="GIF")
```

**Comment by radarhere** [comment]
Thanks very much for reporting this, and thanks for creating a PR to deal with the `None` value of 'comment'. However, I believe that `is_animated` should not change `img.info` in the first place, and I have created a PR to resolve that, which would also fix this problem in turn.
