### ISSUE TITLE
Documentation on readthedocs.io should list functions on the left navigation bar

### ISSUE THREAD

**Issue by Scyntrus** [python-pillow/Pillow#3318]
It's difficult to see an overview of the available functions in a class.
Each function should be listed on the navigation panel.

**Comment by radarhere** [comment]
To be clear, you're suggesting a list of functions instead of 'Image processing', 'Constructing images', 'Registering plugins' in this screenshot, yes?
![readthedocs](https://user-images.githubusercontent.com/3112309/44615900-005e5180-a888-11e8-8e4c-6875d61f0216.png)

**Comment by Scyntrus** [comment]
Exactly

**Comment by radarhere** [comment]
I have created PR #3476. Let us know if you have any thoughts on that.

**Comment by Scyntrus** [comment]
Wow the demo is great! Please get it submitted.
