### ISSUE TITLE
IOError: cannot identify image file 'mosfet.png'

### ISSUE THREAD

**Issue by shirriff** [python-pillow/Pillow#3319]
When I try to open a specific png file, Pillow gives me a "cannot identify image file" error.

There's nothing unusual about this file; I created it with gimp and it opens fine in Mac Preview, Chrome and github. Other image files work fine in Pillow. So it seems like this specific file has something mysterious that Pillow doesn't like.

### What did you expect to happen?
File should be opened

### What actually happened?
IOError: cannot identify image file 'mosfet.png'

### What versions of Pillow and Python are you using?

I'm using Pillow-5.2.0. I reinstalled Pillow and it made no difference.

Python 2.7.15 (default, Jun 17 2018, 12:46:58)
[GCC 4.2.1 Compatible Apple LLVM 9.1.0 (clang-902.0.39.2)] on darwin

macOS High Sierra Version 1013.6 (17G65)

### To reproduce

```
>>> from PIL import Image
>>> Image.open('mosfet.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/ken/blog/blogger/venv/lib/python2.7/site-packages/PIL/Image.py", line 2622, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'mosfet.png'
```
![mosfet.png](https://user-images.githubusercontent.com/188116/44629442-3e00c000-a904-11e8-819e-192d3276dd60.png)

**Comment by hugovk** [comment]
There's something wrong with this image's iCCP profile, ImageMagick has a similar problem.

---

The exception is raised here:

https://github.com/python-pillow/Pillow/blob/1ec5a6452fba3f892505572eb1c50f0f88cd8935/src/PIL/Image.py#L2632

After the original exception was caught here:

https://github.com/python-pillow/Pillow/blob/1ec5a6452fba3f892505572eb1c50f0f88cd8935/src/PIL/Image.py#L2613

The original exception is a `SyntaxError: broken PNG file (bad header checksum in 'iCCP')` from here:

https://github.com/python-pillow/Pillow/blob/959db43d22b633519ac61ad6f58cbe63f8c1a1d0/src/PIL/PngImagePlugin.py#L153-L156

---

ImageMagick's `identify` command also has problems:

```console
$ identify mosfet.png
3319.png PNG 644x324 644x324+0+0 8-bit sRGB 37610B 0.010u 0:00.009
identify: iCCP: CRC error `3319.png' @ warning/png.c/MagickPNGWarningHandler/1744.
```

And also can't open it for conversion:

```console
$ convert mosfet.png mosfet.jpg
convert: iCCP: CRC error `mosfet.png' @ warning/png.c/MagickPNGWarningHandler/1744.
```

**Comment by shirriff** [comment]
Thanks hugovk for looking at this. I've filed a bug against GIMP [here](https://gitlab.gnome.org/GNOME/gimp/issues/2111) since this appears to be a problem in GIMP. So you can close this Pillow bug.
