### ISSUE TITLE
EpsImagePlugin fail when call ghostscript on windows (OSError: [WinError 6] The handle is invalid)

### ISSUE THREAD

**Issue by rfg007** [python-pillow/Pillow#3322]
Context:
Win7pro32
python 3.5.4 and python 3.6.6
Pillow 5.2.0

Trying to save an Image build from an EPS buffer EpsImagePlugin.py fail when call ghostscript via subprocess. This only happen when you are running from a detached console on windows. This is the case in apps frozen with tools like cx_freeze.

This is a little example to test this:
```python
# -*- coding: utf-8 -*-
from tkinter import *
from tkinter.messagebox import showerror
import io
from PIL import Image


def save_image():
    try:
        x0, y0, x1, y1 = canvas.bbox(ALL)
        ps = canvas.postscript(colormode='color',
                               x=x0 - 10,
                               y=y0 - 10,
                               width=x1 + 5,
                               height=y1 + 5,
                               pagewidth='7.05c',   # 200px / 72 * 2.54
                               pageheight='7.05c',  # 200px
                               )
        # this is to trim the Title line in ps, 
        # PIL don't like lines longer than 255 chars. Maybe a fault in tk.
        s = ps.split('\n')
        for n, line in enumerate(s):
            if line.startswith('%%Title:'):
                s[n] = '%%Title: '
                break
        ps = '\n'.join(s)
        im = Image.open(io.BytesIO(ps.encode('utf-8')))
        im.save('test.png')
    except:
        showerror('error', sys.exc_info()[1])

root = Tk()
canvas = Canvas(root, width=200, height=200)
canvas.pack(expand=1, fill=BOTH)
canvas.create_oval(10, 10, 150, 150, fill='blue', width=3, outline='black')
root.after(200, save_image)
root.mainloop()
```
If you run this using python.exe everything is ok. But if you run with pythonw.exe this fail with
"OSError: [WinError 6] The handle is invalid"

I'm not an expert in windows but it seem that happen when subprocess call to _make_inheritable(...) and something was wrong with the filehandlers passed to subprocess.check_call(...) in EpsImagePlugin.py

My solution was change the call to subprocess.check_call(...) in EpsImagePlugin.py from this:
```
#143        with open(os.devnull, 'w+b') as devnull:
#144            subprocess.check_call(command, stdin=devnull, stdout=devnull)
```

To this, and left to subprocess redirect the handlers:
```
#143        subprocess.check_call(command)
```

**Comment by rfg007** [comment]
Context: Win7pro32 python 3.5.4 Pillow 5.4.1
```
Traceback (most recent call last):
  File "test_pillow.py", line 30, in save_image
    im.save('test.png')
  File "e:\pillow_35\lib\site-packages\PIL\Image.py", line 1960, in save
    self.load()
  File "e:\pillow_35\lib\site-packages\PIL\EpsImagePlugin.py", line 333, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "e:\pillow_35\lib\site-packages\PIL\EpsImagePlugin.py", line 148, in Ghostscript
    startupinfo=startupinfo)
  File "c:\Python35\Lib\subprocess.py", line 266, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\Python35\Lib\subprocess.py", line 247, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\Python35\Lib\subprocess.py", line 640, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "c:\Python35\Lib\subprocess.py", line 903, in _get_handles
    errwrite = self._make_inheritable(errwrite)
  File "c:\Python35\Lib\subprocess.py", line 915, in _make_inheritable
    _winapi.DUPLICATE_SAME_ACCESS)
OSError: [WinError 6] Controlador no válido
---------------------------------------------------------------------------------------------------------------------------------------
Context: Win7pro32 python 3.6.6 Pillow 5.4.1
```
Traceback (most recent call last):
  File "test_pillow.py", line 30, in save_image
    im.save('test.png')
  File "e:\pillow_36\lib\site-packages\PIL\Image.py", line 1960, in save
    self.load()
  File "e:\pillow_36\lib\site-packages\PIL\EpsImagePlugin.py", line 333, in load
    self.im = Ghostscript(self.tile, self.size, self.fp, scale)
  File "e:\pillow_36\lib\site-packages\PIL\EpsImagePlugin.py", line 148, in Ghostscript
    startupinfo=startupinfo)
  File "c:\Python36\Lib\subprocess.py", line 286, in check_call
    retcode = call(*popenargs, **kwargs)
  File "c:\Python36\Lib\subprocess.py", line 267, in call
    with Popen(*popenargs, **kwargs) as p:
  File "c:\Python36\Lib\subprocess.py", line 667, in __init__
    errread, errwrite) = self._get_handles(stdin, stdout, stderr)
  File "c:\Python36\Lib\subprocess.py", line 943, in _get_handles
    errwrite = self._make_inheritable(errwrite)
  File "c:\Python36\Lib\subprocess.py", line 955, in _make_inheritable
    _winapi.DUPLICATE_SAME_ACCESS)
OSError: [WinError 6] Controlador no válido

----------------------------------------------------------------------------------------------------------------------------------
Comment:
I try with pyhon 3.7.0 and it fail in the same way. The issue is that you pass the same file descriptor (os.devnull) to both stdout and stderr in subprocess.check_call(...). My suggestion is use the defaults (None) in this file descriptors.

But, look at this [https://bugs.python.org/issue32270](https://bugs.python.org/issue32270)
This bug was closed 2018-09-11 and included in releases 3.6.7 and 3.7.1 (2018-10-20)

I've checked with python 3.7.1, 3.7.2, 3.6.7 and 3.6.8 and not fail.

hth
```



```

**Comment by radarhere** [comment]
I've created PR #3611 to address this. Let us know if you have any thoughts.

**Comment by radarhere** [comment]
Okay, #3611 has been merged, so this should now be fixed in master. If you could test and confirm, that would be great.

**Comment by radarhere** [comment]
Okay, thanks. I've created PR #3635.

**Comment by radarhere** [comment]
Okay, now that #3635 has been merged, could you test again and confirm that this is now fixed in master?

**Comment by rfg007** [comment]
Ok. I can see it in master.
I can't clone and install because I haven't the whole toolchain to install in windows . Life in windows in not easy.
I copied EpsImagePlugin.py over the last pip'ed version (5.4.1) and every work fine. So I assume that the problem was solved.

**Comment by radarhere** [comment]
Okay, thanks.
