### ISSUE TITLE
Issues with setup.py install for Pillow on Windows

### ISSUE THREAD

**Issue by git-AlexS** [python-pillow/Pillow#3329]
### What did you do?
 Run setup.py install for Pillow
### What did you expect to happen?
Successful install
### What actually happened?
`Running setup.py install for Pillow ... error`

...

` c:\users\stefa\appdata\local\programs\python\python36\include\pyconfig.h(59): fatal error C1083: Cannot open include file: 'io.h': No such file or directory
    error: command 'F:\\Program Files (x86)\\Microsoft Visual Studio\\2017\\Professional\\VC\\Tools\\MSVC\\14.12.25827\\bin\\HostX86\\x64\\cl.exe' failed with exit status 2
  Rolling back uninstall of pillow
Command "c:\users\stefa\appdata\local\programs\python\python36\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\stefa\\AppData\\Local\\Temp\\pip-install-o_u09_8s\\Pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\stefa\AppData\Local\Temp\pip-record-0qey88u5\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\stefa\AppData\Local\Temp\pip-install-o_u09_8s\Pillow\ `

### What versions of Pillow and Python are you using?

Latest versions of both

Please let me know if there's any more information I can give, very new to this so not sure what is relevant. I assume the issue is caused by the missing file/directory, but no idea what to do with that information.

**Comment by radarhere** [comment]
You may not find this answer very helpful, but https://pillow.readthedocs.io/en/5.2.x/installation.html#building-on-windows

> We don’t recommend trying to build on Windows. It is a maze of twisty passages, mostly dead ends. There are build scripts and notes for the Windows build in the winbuild directory.

Have you considered using one of the downloads from https://pypi.org/project/Pillow/#files, rather than trying to build from source?

**Comment by git-AlexS** [comment]
Thanks for the response. I am a little confused about the distinction between setup.py install for Pillow and just installing Pillow using pip install Pillow or similar. The latter method always results in a successful installation, so does the setup,py error imply it is not working properly? 

Another thing I've noticed is that the microsoft visual directory that it opens is in my F: drive, whereas Python etc. is all installed in the other directory above in the C: drive - could this be an issue?

If I fail to get it to work on windows, what would you recommend I do instead? I have seen some references to a virtualenv - could I run this from a windows PC to emulate a different environment?

**Comment by hugovk** [comment]
`pip install pillow` install pre-compiled binaries which are specially created for each release.

`python setup.py install` will attempt a fresh build from the source code.

It's important to note that Pillow is made up of Python code and also C code. It's the C code which needs compiling.

Setting up compilers is difficult on Windows, and that's why we make pre-compiled binaries (called "wheels").

So please use the pip installed version. 

Or do you have a special reason to build from source?

**Comment by git-AlexS** [comment]
It is one of the dependencies of InstaPy. I have tried to install each individual dependency using pip install . --no-dependencies (since doing pip install InstaPy always leads to that error) but I am not convinced that it has worked properly. It may be some other issue that is preventing InstaPy from working as intended but this is the only error that I've seen so I was wondering if this was a problem. 

That said, if they are just two different methods for installing the same package then I suppose installing everything separately should work.

**Comment by radarhere** [comment]
Closing due to lack of response. Feel free to comment again and this can be re-opened

**Comment by isConic** [comment]
Running into the same error on Mac

**Comment by hugovk** [comment]
@isConic This issue is for Windows, please open a new issue with details.
