### ISSUE TITLE
Autocontrast cutoff behaves unexpectedly

### ISSUE THREAD

**Issue by jnweiger** [python-pillow/Pillow#3331]
### What did you do?
python-3.6 with Pillow-5.2.0
![leaf-gr](https://user-images.githubusercontent.com/1108546/45062236-50b78980-b0a8-11e8-8ffe-63d449e80e05.jpg)
Download this image as leaf-gr.jpg then start python and do
```python
from PIL import Image, ImageOps
im = Image.open('leaf-gr.jpg')
ImageOps.autocontrast(im, cutoff=2).show()
```
![grafik](https://user-images.githubusercontent.com/1108546/45062365-da675700-b0a8-11e8-8b13-4bda846d4edd.png)

### What did you expect to happen?
The background is two light gray values. I expect both to become brighter.
The foreground is darker gray values, I expect these to touch black.

Histogram stretching until the outermost gray values hit 0 and 255 respectively.
Then some more linear stretching so that the outermost gray values would go 2 percent beyond, ca -5 and 260, then clip everything back to be within 0..255 

### What actually happened?
The background is half black 0x000000 and half white 0xffffff. That is unexpected. 
The darker gray of the background is in any case more than 2% percent brighter than the darkest point of the foreground. (Or we must be measuring very non-inear)

### What versions of Pillow and Python are you using?
python-3.6 with Pillow-5.2.0

**Comment by radarhere** [comment]
> The background is two light gray values. I expect both to become brighter.
> The foreground is darker gray values, I expect these to touch black.

If you don't specify `cutoff=2`, then the result matches this part of the expectation.

https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.autocontrast
> This function calculates a histogram of the input image (or mask region), removes `cutoff` percent of the lightest and darkest pixels from the histogram, and remaps the image so that the darkest pixel becomes black (0), and the lightest becomes white (255).

I think your expectation is that the cutoff would apply after scaling, whereas Pillow is applying it before scaling. This behaviour is what is described in the documentation, so I don't think there's anything to do here.
