### ISSUE TITLE
Suggestion: option to pad instead of crop in ImageOps.fit

### ISSUE THREAD

**Issue by danvk** [python-pillow/Pillow#3339]
I recently wanted to use Pillow to generate thumbnails of a directory of images. I wanted each thumbnail to be exactly 300x200, but preserve the aspect ratio of the original image by padding one of the dimensions.

I thought [`PIL.ImageOps.fit`](https://pillow.readthedocs.io/en/latest/reference/ImageOps.html?highlight=ImageOps#PIL.ImageOps.fit) might do exactly what I wanted, but it crops rather than padding.

Would there be interest in an option to pad rather than crop? Or another method? I'd be happy to contribute if so.

PIL 1.1.7, Python 3.6.5

**Comment by radarhere** [comment]
Here is another method -
```
from PIL import Image
im = Image.open("test.png")
w, h = 300, 200
ratio = im.width / im.height
if ratio == w / h:
	out = im
else:
	out = Image.new(im.mode, (w, h))
	if ratio > w / h:
		new_h = int(im.height / im.width * w)
		im = im.resize((w, new_h))
		out.paste(im, (0, int((h - new_h) / 2)))
	else:
		new_w = int(im.width / im.height * h)
		im = im.resize((new_w, h))
		out.paste(im, (int((w - new_w) / 2), 0))
```

**Comment by danvk** [comment]
Yep, that's a way to do it. My proposal would be to either fold that in to `PIL.ImageOps.fit` or make it another method on `ImageOps`.

**Comment by radarhere** [comment]
Oh, apologies - when you said 'Or another method?', I interpreted that differently.

**Comment by radarhere** [comment]
I have created PR #3364 to add a method for this.
