### ISSUE TITLE
Is it possible to use colored Whatsapp/Facebook emoji?

### ISSUE THREAD

**Issue by guitar9** [python-pillow/Pillow#3346]
### What did you do?

```python
from PIL import Image, ImageDraw, ImageFont
import textwrap

astr = ''' 👩‍⚕️: H👩‍'''
para = textwrap.wrap(astr, width=40)

MAX_W, MAX_H = 400, 100 + 30 * len(para)
im = Image.new('RGB', (MAX_W, MAX_H), (0, 45, 0, 0))
draw = ImageDraw.Draw(im)
font = ImageFont.truetype('DejaVuSans.ttf', size=18)

current_h, pad = 50, 10
for line in para:
    w, h = draw.textsize(line, font=font)
    draw.text(((MAX_W - w) / 2, current_h), line, font=font)
    current_h += h + pad
im.save('test.png')

```
### What did you expect to happen?
Is it possible to show colored Whatsapp oder Facebook Emoji?
### What actually happened?
For the woman emoji i only get a white rect. 
### What versions of Pillow and Python are you using?
Pillow 3.1.2
Python 3.5.2

**Comment by guitar9** [comment]
I think this is not implemented. But have somebody ideas to do a workaround? For example to tranform the emoji to a image and open the image and render it in text

**Comment by hugovk** [comment]
A workaround is to call something like ImageMagick to create an image south emoji, then open that. 

For example, https://stackoverflow.com/a/52131155/724176

**Comment by guitar9** [comment]
this does not work under linux

**Comment by hugovk** [comment]
Does this still happen? 

How about when using a Noto font? 

* https://www.google.com/get/noto/

**Comment by Exploder98** [comment]
Noto Emoji gives black and white emojis, and Noto Color Emoji fails to load with `OSError: invalid pixel size`. I'm using Pillow 7.0.0 on Ubuntu.

**Comment by nulano** [comment]
> Noto Emoji gives black and white emojis, and Noto Color Emoji fails to load with `OSError: invalid pixel size`. I'm using Pillow 7.0.0 on Ubuntu.

This error is due to a freetype limitation. Bitmap fonts don't support scaling with freetype, so you must specify a valid size, which is 109 for Noto Color Emoji.

Additionally, freetype must be built with libpng to support this font (png bitmaps). However, due to #960, bitmap fonts will not work with Pillow at all. And even if they did, you would get a grayscale version of the emojis, because Pillow only returns one channel from the C layer font functions.

**Comment by boringcactus** [comment]
it looks like FreeType 2.10.0 adds support for COLR/CPAL tables, which Noto Color Emoji uses for scalable color emoji glyphs. could this be taken advantage of to add support for this type of emoji font to Pillow?

**Comment by nulano** [comment]
@boringcactus I've got it partially implemented, but it is not PR ready. I'm not sure when I'll have time to work on it, but it will be either next week or a few weeks later.

**Comment by GanerCodes** [comment]
> @boringcactus I've got it partially implemented, but it is not PR ready. I'm not sure when I'll have time to work on it, but it will be either next week or a few weeks later.

_cough_

**Comment by nulano** [comment]
I ended up working on #4724 first 😄 and postponed this until that gets merged to avoid merge conflicts. Thinking about it again, I don't think these two actually conflict too badly, so perhaps I can submit this soon as well. I'm hoping both of these can be included in version 8.0.0 planned for release in 6 weeks.

**Comment by GanerCodes** [comment]
Ah thanks, if you have the patch could you send it to me? I can implement it locally

**Comment by nulano** [comment]
See my branch https://github.com/nulano/Pillow/compare/06ba0838...nulano:ft-color. IIRC it should work, but there are some extra unnecessary changes that should be removed, and parts of it can be simplified, before submitting it as a PR. Please treat it as a WIP, the API will likely change in the final version.

**Comment by GanerCodes** [comment]
Hey, can you send me a compiled version for windows?

**Comment by nulano** [comment]
I've re-triggered the GHA run, you can get wheels there: https://github.com/nulano/Pillow/actions/runs/232647949

**Comment by GanerCodes** [comment]
I'm dumb, how do I install it with that?

**Comment by hugovk** [comment]
Not dumb, it's not so obvious! :)

If you click dist"-ft-color" under Artifacts it'll download a zip file.

Extract that, and then `pip install filename.whl`, where `filename.whl` is the one that closest matches your system (e.g. `cp38` for Python 3.8).

**Comment by GanerCodes** [comment]
Hey, thank you so much, the new version installed correctly
However, it seems that fonts with color don't work, can you tell me what is wrong with this code?
```
# -*- coding: utf-8 -*-
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

import os

im = Image.open('purple.png')
draw = ImageDraw.Draw(im)
font = ImageFont.truetype('seguiemj.ttf', 64, encoding = 'unic')
textToDraw = u'😀'
print(textToDraw)
draw.text((20,20), textToDraw, (255,255,255), font=font)
im.show()
```

**Comment by nulano** [comment]
For backwards compatibility you have to use `draw.text(..., embedded_color=True)`. This parameter might be renamed in the final version.

**Comment by GanerCodes** [comment]
POG IT WORKS thank you so much man

**Comment by GanerCodes** [comment]
Also, is there a way to have a secondary font for mission glyphs? like many fonts don't have emoji and ideally I want to support them still

**Comment by nulano** [comment]
> Also, is there a way to have a secondary font for mission glyphs? like many fonts don't have emoji and ideally I want to support them still

See #4807.

The best you can do for now is use [`unicodedata.category`](https://docs.python.org/3/howto/unicode.html#unicode-properties) to break up text into "spans" each rendered separately with their own font. You can use `font.getsize(...)[0]` or `draw.textsize(...)[0]` as the horizontal offset between spans for now (#4724 proposes adding a faster and more precise `font.getlength(...)`).  You will also have to handle linebreaks yourself, see [`draw.multiline_text`](https://github.com/python-pillow/Pillow/blob/1ff90e7bdb0ae59a5b858bcbe68bd28379e47aba/src/PIL/ImageDraw.py#L354) for inspiration.

**Comment by nulano** [comment]
Pillow 8.0.0 has now been released, adding support for CBDT and COLR fonts.
FreeType (and hence also Pillow) does not yet support SBIX or SVG fonts.
To enable color support, use `draw.text(..., embedded_color=True)`.

**Comment by jdhao** [comment]
@nulano  I tried Pillow 9.0 and it seems that I still can not use noto color emoji font. The same error persists:

> OSError: invalid pixel size

**Comment by radarhere** [comment]
@jdhao would you be able to create a new issue with a self-contained example, and information about your environment?

**Comment by jdhao** [comment]
Okay, will do it.

**Comment by shula** [comment]
@nulano  How to obtain the size of a font? 
How do you know that NotoColorEmoji will render in **109** pixels?

**Comment by radarhere** [comment]
I'm not sure what kind of answer you're interested in.

If you're asking how you can determine that using Pillow,
```python
from PIL import ImageFont

for i in range(1, 500):
  try:
    font = ImageFont.truetype("NotoColorEmoji.ttf", i)
    print("Font size "+str(i)+" is available")
  except OSError:
    pass
```
will try all font sizes between 1 and 500 and then only print
```
Font size 109 is available
```
