### ISSUE TITLE
AttributeError in Image.open

### ISSUE THREAD

**Issue by lubyrex** [python-pillow/Pillow#3349]
I was trying to build a server where the client can send image stream to be processed.

I'm using Python 2.7 and Pillow 5.2.0

And I got this error:

```
2018/09/12 18:11:07|ERROR|8827|Traceback (most recent call last):
  File "/home/someone/myproject/lib/util.py", line 45, in _trace
    res = f(*args, **kwargs)
  File "/home/someone/myproject/lib/imgutil.py", line 61, in filter
    src_img = Image.open(bytesobj)
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 2004, in open
    containing a copy of one of the original bands (red, green,
  File "/usr/lib64/python2.7/site-packages/PIL/Image.py", line 298, in preinit
    def _conv_type_shape(im):
  File "/usr/lib64/python2.7/site-packages/PIL/GifImagePlugin.py", line 806, in <module>
    Image.register_save_all(GifImageFile.format, _save_all)
AttributeError: 'module' object has no attribute 'register_save_all'
```

Here's my code:

```python
...
for field_name, files in self.request.files.items():
    logging.info(self.log_msg("file field name: {0}".format(field_name.encode('utf-8'))))
    for info in files:
        filename, content_type = info["filename"], info["content_type"]
        imgbody = info["body"]
        logging.info(self.log_msg('POST "{0}" "{1}" {2} bytes'.format(
                     filename.encode('utf-8'), content_type, len(imgbody))))
        break
    break
 ...
```

and I passed imgbody as imginbytes to the next part

```python
@util.trace
...
bytesobj = io.BytesIO(imginbytes)
src_img = None
try:
    src_img = Image.open(bytesobj)
    src_img.load()
except IOError as e:
    logging.error("img_enhance: IOError raised reading byte_string")
    return "IOError"
...
```

trace definition:
```python
def trace(f):
    def _trace(*args, **kwargs):
        try:
            res = f(*args, **kwargs)
        except:
            fp = cStringIO.StringIO()
            traceback.print_exc(file=fp)
            logging.error(fp.getvalue())
            res = None
        return res
    return _trace
```

I can no longer reproduce this as it wasn't me that sent the request
I was expecting IOError since that was the only error the documentation mentioned

I'm very confused as there are many versions of documentations floating around, and none of them give detailed explanations of the methods

**Comment by radarhere** [comment]
When you say that there are ‘many versions of documentations floating around’, I don’t know what you’re referring to. https://pillow.readthedocs.io/ contains the documentation. True, it changes with each new release of Pillow, but that is necessary.

If you run the following code -

```
from PIL import Image
Image.register_save_all
```

you will get something like -

```
<function register_save_all at 0x10942ef11>
```

The error that you have received is saying that these simple two lines are failing. This is unexpected, to say the least.

What does this code give you?

```
from PIL import Image
Image.PILLOW_VERSION
```

My best idea is that you have corrupted your Pillow installation somehow, and you should uninstall and re-install it.

**Comment by lubyrex** [comment]
Thanks for the reply! And I'm not a native english speaker so reading documentation is difficult for me. I apologize about that.
So i ran the program below:
    from PIL import Image
    print Image.register_save_all
    print Image.PILLOW_VERSION

and got these:
<function register_save_all at 0x7f9c83674f50>
5.2.0

But supposedly everything happened in the Image.open method, so I'm still quite confused

**Comment by lubyrex** [comment]
Thanks for the reply again. I'm fairly certain I've found the cause of the error. I downgraded the PIL version and "Image.register_save_all" method isn't in the package which helped me determine the cause.  I ran the server on and older version of PIL (2.something) before my administrator updated the PIL package. The package is probably loaded into the memory and therefore not affected by the update. Your suspicion at first is probably right. Thanks again for the help, and please close this issue.
