### ISSUE TITLE
Converting MCIDAS to PDF results in empty file

### ISSUE THREAD

**Issue by OskarPersson** [python-pillow/Pillow#3351]
### What did you do?
Converted MCIDAS .ara-file to PDF

### What did you expect to happen?
A PDF would be created with content similar to the source

### What actually happened?
An empty PDF was created

### What versions of Pillow and Python are you using?
Pillow 5.2.0 and Python 2.7.15

[The tested file](https://github.com/python-pillow/Pillow/blob/9626e49c0bf571d83a99b08709ef4e0c8dc01e03/Tests/images/cmx3g8_wv_1998.260_0745_mcidas.ara)

```python
ara = Image.open("Tests/images/cmx3g8_wv_1998.260_0745_mcidas.ara")
rgb_ara = ara.convert('RGB')
rgb_ara.save('output.pdf')
```

**Comment by radarhere** [comment]
If I run your code, the PDF is a white image 1,800 by 400.

However, this is also what I get if I `show` the image instead -

```
from PIL import Image
ara = Image.open("cmx3g8_wv_1998.260_0745_mcidas.ara")
ara.show()
```

I presume that you think the image is not just a while rectangle? What program are you using to view the original file?

**Comment by OskarPersson** [comment]
I viewed it by converting it to a PNG and then opening the resulting file in Apples Preview app

```python
from PIL import Image
ara = Image.open("cmx3g8_wv_1998.260_0745_mcidas.ara")
ara.save("output.png")
```

**Comment by radarhere** [comment]
I think this is related to #3159

**Comment by radarhere** [comment]
I've created PR #3838 to resolve this.

**Comment by radarhere** [comment]
Resolved by #3838

**Comment by radarhere** [comment]
It turns out that this situation is more complicated. See https://github.com/python-pillow/Pillow/pull/3838#discussion_r292114051

**Comment by radarhere** [comment]
Closing, as part of #3159
