### ISSUE TITLE
How to save a gif with transparency without ruining all of it?

### ISSUE THREAD

**Issue by jamesguessis** [python-pillow/Pillow#3357]
### What did you do?
Tried to save a transparent gif
### What did you expect to happen?
I expected the gif to maintain transparency without issue
### What actually happened?
It did not maintain transparency without issue
### What versions of Pillow and Python are you using?
Using Python 3.7 with pillow 5.2.0

```python
def makegif(path, images):
    images[0].save(
        path,
        save_all=True,
        append_images=images[1:],
        duration=16,
        transparency=0,
        disposal=3)
```
This example doesn't have transparency, but I need to support transparency for rounded corners.
When saving without the transparency and disposal kwargs:
![test2](https://user-images.githubusercontent.com/14200370/45592413-a73f8600-b93a-11e8-8033-d5a3656e8449.gif)

When saving without the disposal kwarg:
![test3](https://user-images.githubusercontent.com/14200370/45592414-b292b180-b93a-11e8-8f37-567fe3ebf9a5.gif)

Eventually someone told me disposal=3 was what I wanted, but this is what that produces:
![test](https://user-images.githubusercontent.com/14200370/45592402-fc2ecc80-b939-11e8-8a7a-553baee154f1.gif)

I tried to google a solution, but couldn't find anything similar to this? I probably suck at googling, but here I am anyways.

**Comment by sircinnamon** [comment]
I'm having this same problem, it looks like even when each image represents an entire frame (with the disposal=2 or disposal=3) Pillow tries to strip out pixels that are the same as the previous frame and create an optimized file. This obviously shouldn't happen with transparent gifs, especially when optimize is set to false, bit I'm seeing the same thing. Pixels that are the same as the were the previous frame are missing.

**Comment by ThePlasmaRailgun** [comment]
I'm having the same problem.

**Comment by Artheau** [comment]
The fix is described in #3665

**Comment by radarhere** [comment]
@jamesguessis could you actually attach the original images you combined, so that this is a complete example?

**Comment by radarhere** [comment]
I'm closing this, as there is no complete example of the problem. If anyone has a complete example that they don't feel is covered by an existing issue, feel free to comment, and this can be re-opened.

**Comment by jamesguessis** [comment]
ah sorry, I don't have that project anymore. I'll try redoing what I was trying sometime this week.
