### ISSUE TITLE
Resize images while loading into Python using Pillow

### ISSUE THREAD

**Issue by sagar-m** [python-pillow/Pillow#3360]
### What did you do?
Hi: I would like load some 2400 images from a folder into python 3.6 for Neural Networks, the following code works, however, it loads images in its original size, which is (2443, 320, 400, 3), after converting into an array. How do I resize it to 64x96? so it is (2443, 64, 96, 3) and less of a load on memory. I tried two different ways, as written below.:

```python
# this works, however it uploads images in its original size which is 320x400.

IMAGE_PATH = 'drive/xyz/data/'
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images
images = [misc.imread(path) for path in file_paths]
images = np.asarray(images)
```

Inspired by this [link](https://stackoverflow.com/questions/273946/how-do-i-resize-an-image-using-pil-and-maintain-its-aspect-ratio?noredirect=1&lq=1), I tried to do the following:

```python
from PIL import Image

basewidth = 96
IMAGE_PATH = 'drive/xyz/data/' 
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images img = [misc.imread(path) for path in file_paths]

wpercent = (basewidth/float(img.size[0])) 
hsize = int((float(img.size[1])*float(wpercent))) 
img = img.resize((basewidth,hsize), Image.ANTIALIAS) 
images = np.asarray(img)

```
### What did you expect to happen?
Convert the 2400 images to numpy array, of size (2443, 64, 96, 3) so that I can further process it for autoencoders.

### What actually happened?
The first code manages to upload all the images in its current size, which is (2443, 320, 400, 3).

The error for the second code:

```python
AttributeError                            Traceback (most recent call last)
<ipython-input-7-56ac1d841c56> in <module>()
      9 img = [misc.imread(path) for path in file_paths]
     10 
---> 11 wpercent = (basewidth/float(img.size[0]))
     12 hsize = int((float(img.size[1])*float(wpercent)))
     13 img = img.resize((basewidth,hsize), Image.ANTIALIAS)

AttributeError: 'list' object has no attribute 'size'
```

### What versions of Pillow and Python are you using?

I just added the package, thus, it must be the latest package. Thank you very much. Highly appreciate it.

**Comment by hugovk** [comment]
First, `img` is a list of images, and not an image, so you can't call `.size` to get the width and height on the list.

Second, each "image" in the list isn't a Pillow image, but is actually an array as returned by [`scipy.misc.imread`](https://docs.scipy.org/doc/scipy/reference/generated/scipy.misc.imread.html). So you can't call `.size` or `.resize` on that either.

One way is to proceed is to (1) load the images as Pillow images, then (2) resize them using Pillow, and then (3) convert them into the array format needed.

Here's (1) and (2), with (3) left as an exercise.

This assumes the input images are all the same size, because it makes calculations using the first image in the list, `imgs[0]`.

```python
import glob
from os import path

from PIL import Image

basewidth = 96
IMAGE_PATH = 'drive/xyz/data/' 
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images
imgs = [Image.open(path) for path in file_paths]

wpercent = (basewidth/float(imgs[0].size[0]))
hsize = int((float(imgs[0].size[1])*float(wpercent)))
imgs = [img.resize((basewidth,hsize), Image.ANTIALIAS) for img in imgs]

# imgs is now a list of resized Pillow images
print(imgs)

# TODO: convert into array
```

**Comment by sagar-m** [comment]
Hi @hugovk thank you very much. The above code worked beautifully. The following code works. Should I be converting it into a list of arrays? How do I convert just to arrays and not a list of it? images = np.asarray(img) results in an error. 

```
import glob
from os import path
from PIL import Image

basewidth = 96
IMAGE_PATH = 'drive/dataprophet/precipitation_data/data/'
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images
imgs = [Image.open(path) for path in file_paths]

wpercent = (basewidth/float(imgs[0].size[0]))
hsize = int((float(imgs[0].size[1])*float(wpercent)))
imgs = [img.resize((basewidth,hsize), Image.ANTIALIAS) for img in imgs]
images = [np.asarray(img) for img in imgs]
# imgs is now a list of resized Pillow images
#print(imgs)

# TODO: convert into array
```

**Comment by sagar-m** [comment]
Last few lines:

However, I need it to be of ((2443, 96, 76, 3)). Also, wait a minute, how is 320x400 getting resized into 96x76 below?

```
images = [np.asarray(img) for img in imgs]
images = np.vstack(images)
print(images.shape)

# imgs is now a list of resized Pillow images
print(imgs)

(185668, 96)
[<PIL.Image.Image image mode=P size=96x76 at 0x7FC25F8F8E48>.....
```

**Comment by sagar-m** [comment]
Hi @hugovk, I managed to get it almost right below. There's one final issue: how do I change the shape from (2443, 96, 120) to (2443, 96, 120,3)? Thank you very much.


```

import glob
from os import path
from PIL import Image
import numpy as np

basewidth = 120
IMAGE_PATH = 'drive/xyz/data/'
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images
imgs = [Image.open(path) for path in file_paths]

wpercent = (basewidth/float(imgs[0].size[0]))
print(wpercent)
hsize = int((float(imgs[0].size[1])*float(wpercent)))
imgs = [img.resize((basewidth,hsize), Image.ANTIALIAS) for img in imgs]
images = np.array([np.array(img) for img in imgs])
#images = np.vstack(images)
print(np.shape(images))

# imgs is now a list of resized Pillow images
print(imgs)

# TODO: convert into array


```

**Comment by sagar-m** [comment]
Hi again, I had colored images. However, it is turning into black and white. How do I change from (2443, 96, 120, 1) to (2443, 96, 120, 3). Thank you.

**Comment by sagar-m** [comment]
Hi @hugovk, when you have time, would you be able to write why the second code which you helped me out with changes number of channels from 3 (RGB) to 1 (grayscale). And how to get back (2443, 96, 120, 3) instead of (2443, 96, 120, 1). These are heatmaps, I will lose out info, if I convert them them grayscale. Thank you so much. Sorry to bother you.

```
# this code generated a numpy array of  2443x320x400x3.

IMAGE_PATH = 'drive/xyz/data/'
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images
images = [misc.imread(path) for path in file_paths]
images = np.asarray(images)
```

While this one does (2443, 96, 120, 1)

```
import glob
from os import path
from PIL import Image
import numpy as np
from keras.preprocessing import image 

basewidth = 120
IMAGE_PATH = 'drive/xyz/data/'
file_paths = glob.glob(path.join(IMAGE_PATH, '*.gif'))

# Load the images
imgs = [Image.open(path) for path in file_paths]

wpercent = (basewidth/float(imgs[0].size[0]))
print(wpercent)
hsize = int((float(imgs[0].size[1])*float(wpercent)))
imgs = [img.resize((basewidth,hsize), Image.ANTIALIAS) for img in imgs]
images = np.array([image.img_to_array(img) for img in imgs])

print(np.shape(images))

# imgs is now a list of resized Pillow images
print(imgs)
```

**Comment by hugovk** [comment]
The first array must be `number-of-images x width x height x rgb`.

The second must be `number-of-images x width x height x mono`.

It could be that your images are `P` mode: "8-bit pixels, mapped to any other mode using a color palette", and `RGB` would be better: "3x8-bit pixels, true color".

https://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#modes

Here's a demo:
```python
>>> from PIL import Image
>>> import numpy as np

>>> im = Image.open("hopper.gif")
>>> im.show()  # Confirm it's colour
>>> print(im)
<PIL.Image.Image image mode=P size=120x120 at 0x11100C6A0>

>>> # Convert to array
>>> im2arr = np.array(im)
>>> print(np.shape(im2arr))
(120, 120)

>>> # Convert array back to image
>>> arr2im = Image.fromarray(im2arr)
>>> arr2im.show()  # It's now greyscale :(

>>> # Instead, let's convert the image to RGB first
>>> im2 = im.convert("RGB")
>>> im2.show()  # Confirm it's colour
>>> print(im2)
<PIL.Image.Image image mode=RGB size=120x120 at 0x111020C18>

>>> # Convert to array
>>> im2arr2 = np.array(im2)
>>> print(np.shape(im2arr2))
(120, 120, 3)

>>> # Convert array back to image
>>> arr2im2 = Image.fromarray(im2arr2)
>>> arr2im2.show()  # It's colour :)
```

So perhaps something like this:
```python
imgs = [img.resize((basewidth,hsize), Image.ANTIALIAS) for img in imgs]
imgs = [img.convert("RGB") for img in imgs]
images = np.array([np.array(img) for img in imgs])

print(imgs)
# [<PIL.Image.Image image mode=RGB size=120x120 at 0x111020FD0>, <PIL.Image.Image image mode=RGB size=120x120 at 0x111035080>]
print(np.shape(images))
# (2, 120, 120, 3)
```

**Comment by sagar-m** [comment]
Hi @hugovk that worked very well. Thank you. I will go through this: https://pillow.readthedocs.io/en/5.2.x/handbook/concepts.html#modes

**Comment by KurniaKhaikal** [comment]
#Define the path and add as a new column
skin_df_balanced['path'] = skin_df['image_id'].map(image_path.get)
#Use the path to read images.
skin_df_balanced['image'] = skin_df_balanced['path'].map(lambda x: np.asarray(Image.open(x).resize((SIZE,SIZE))))


Problem is AttributeError: 'NoneType' object has no attribute 'read'

may someone help me fix this?

**Comment by radarhere** [comment]
Googling, your code comes from https://github.com/bnsreenu/python_for_microscopists/blob/9eac4c3a7184f8a337dbe3b45e60cf709fbd8e46/202_2_ways_to_load_HAM10000_data.py#L39-L42, yes?

Could you provide a copy of the full error? Or show us `print(x)`? Or remove parts of your code gradually until you have a short, self-contained example you can show us?

**Comment by KurniaKhaikal** [comment]
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2846     try:
-> 2847         fp.seek(0)
   2848     except (AttributeError, io.UnsupportedOperation):

AttributeError: 'NoneType' object has no attribute 'seek'

During handling of the above exception, another exception occurred:

AttributeError                            Traceback (most recent call last)
4 frames
pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
   2847         fp.seek(0)
   2848     except (AttributeError, io.UnsupportedOperation):
-> 2849         fp = io.BytesIO(fp.read())
   2850         exclusive_fp = True
   2851 

AttributeError: 'NoneType' object has no attribute 'read'

**Comment by KurniaKhaikal** [comment]
yes its from the link, i tried to use the code with google colab, and after i balanced the data i confuse why the path is doesnt exist

**Comment by radarhere** [comment]
If `x` is `None`, as it seems to be, then this isn't really a Pillow problem. https://github.com/pandas-dev/pandas might be a better place to ask your question.

Also, have you seen https://youtu.be/qB6h5CohLbs, linked to from the top of the script? That walkthrough might be helpful.

**Comment by tienquyet28** [comment]
> ```
> ---------------------------------------------------------------------------
> AttributeError                            Traceback (most recent call last)
> /usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
>    2846     try:
> -> 2847         fp.seek(0)
>    2848     except (AttributeError, io.UnsupportedOperation):
> 
> AttributeError: 'NoneType' object has no attribute 'seek'
> 
> During handling of the above exception, another exception occurred:
> 
> AttributeError                            Traceback (most recent call last)
> 4 frames
> pandas/_libs/lib.pyx in pandas._libs.lib.map_infer()
> 
> /usr/local/lib/python3.7/dist-packages/PIL/Image.py in open(fp, mode)
>    2847         fp.seek(0)
>    2848     except (AttributeError, io.UnsupportedOperation):
> -> 2849         fp = io.BytesIO(fp.read())
>    2850         exclusive_fp = True
>    2851 
> 
> AttributeError: 'NoneType' object has no attribute 'read'
> ```
You can replace these code then problem is sovled
image_path = {os.path.splitext(os.path.basename(x))[0]: x
                     for x in glob(os.path.join('data/HAM10000/', '*', '*.jpg'))}
by:
image_path = {os.path.splitext(os.path.basename(x))[0]: x
                     for x in glob(os.path.join('data/HAM10000/',  '*.jpg'))}
