### ISSUE TITLE
Transparent pixels in specific PNG are read as black

### ISSUE THREAD

**Issue by xapienz** [python-pillow/Pillow#3379]
### What did you do?
I have an image containing only white and transparent pixels.
I tried to read the pixels from greyscale image in RGBA format using Pillow library.

### What did you expect to happen?
I expect that transparent pixels are read as (0, 0, 0, 0) when image is opened as RGBA.
When I open the image in Preview/GIMP, I see transparency correctly.

### What actually happened?
Transparent pixels were read as black (0, 0, 0, 255).

### What are your OS, Python and Pillow versions?

* OS: macOS 10.13.6
* Python: 3.7.0
* Pillow: 5.2.0

### Code
```python
from PIL import Image
im = Image.open("test.png").convert("RGBA")
im.load()
print(im.getpixel((0, 0)))
```

### Image
https://user-images.githubusercontent.com/3826188/46113793-b1684c80-c1a4-11e8-98e9-38b1f0baa7fa.png

![test](https://user-images.githubusercontent.com/3826188/46113793-b1684c80-c1a4-11e8-98e9-38b1f0baa7fa.png)

**Comment by radarhere** [comment]
This is because the image has mode '1', which isn't yet supported for PNG transparency. I've created PR #3744 to resolve this.

**Comment by xapienz** [comment]
Thank you! I just verified, the fix worked for me
