### ISSUE TITLE
Regression in font rendering on Windows?

### ISSUE THREAD

**Issue by v-python** [python-pillow/Pillow#3407]
### What did you do?

Upgraded PILLOW from an older version to latest released version 5.3.0

### What did you expect to happen?

Things to work better.

### What actually happened?

Programs that used to work started failing.  Particularly, 

```python
    font.font.render( line, im.id, True )
```

Now produces the following error:

```python
KeyError: 'setting text direction or font features is not supported without libraqm'
```

Googling, I find that raqm isn't installed or supported on Windows? Does this mean that text support has been broken on Windows, as a regression? Is it now unsupported?  I'm not even sure what "font feature" the above line uses, it certainly isn't text direction.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6
* Pillow: 5.3.0

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python

from PIL import Image, ImageDraw, ImageFont
def foo():
    line = "foo"
    im = Image.new( "1", ( 1200, 600 ), 'white')
    font = ImageFont.truetype("times.ttf", 30 )

    lxMin, lyMin, lxMax, lyMax, line = 60, 60, 600, 300, "foo"
    im = Image.core.fill("L", ( lxMax - lxMin, lyMax - lyMin ), 0 )
    font.font.render( line, im.id, True )

foo()
```

**Comment by v-python** [comment]
And sadly, I don't recall what old version I was using, to try to install back to a working version :(
Any suggestions? It must have predated the dependency or raqm, I guess. Maybe any such version would then work for me.

**Comment by v-python** [comment]
And sadly, the documentation for installing Old versions is unclear:

Old Versions

You can download old distributions from PyPI. Only the latest major releases for Python 2.x and 3.x are visible, but all releases are available by direct URL access e.g. https://pypi.org/project/Pillow/1.0/.

So I tried the following, but got an error:

C:\WINDOWS\system32>pip install https://pypi.org/project/Pillow/3.4.1/
Collecting https://pypi.org/project/Pillow/3.4.1/
  Downloading  (132kB)
    100% |████████████████████████████████| 133kB 892kB/s
  Cannot unpack file D:\temp\pip-unpack-_f_hf8x3\3.4.1 (downloaded from D:\temp\pip-req-build-37jmxq98, content-type: text/html; charset=UTF-8); cannot detect archive format
Cannot determine archive format of D:\temp\pip-req-build-37jmxq98

**Comment by hugovk** [comment]
This is usually the easiest way to install an old version:
```
pip install pillow==3.4.1
```

Alternatively, go to https://pypi.org/project/Pillow/3.4.1/ and click "Download files" (https://pypi.org/project/Pillow/3.4.1/#files) and you'll see files there you can download and install.

**Comment by v-python** [comment]
Thanks @hugovk , now I get a longer error message:

C:\WINDOWS\system32>pip install pillow==3.4.1
Collecting pillow==3.4.1
  Using cached https://files.pythonhosted.org/packages/80/b5/359ac53b4986abbb5da766f809def82958bbbddf169139cdef8f0880522b/Pillow-3.4.1.tar.gz
Installing collected packages: pillow
  Found existing installation: pillow 5.3.0
    Uninstalling pillow-5.3.0:
      Successfully uninstalled pillow-5.3.0
  Running setup.py install for pillow ... error
    Complete output from command "c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='D:\\temp\\pip-install-q3_gt5ch\\pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\temp\pip-record-umnb4qnb\install-record.txt --single-version-externally-managed --compile:
    Single threaded build for windows
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.6
    creating build\lib.win-amd64-3.6\PIL
    copying PIL\BdfFontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ContainerIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\CurImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ExifTags.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\features.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FliImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GdImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GifImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GimpGradientFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Image.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageChops.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageCms.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageColor.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageDraw.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageDraw2.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageEnhance.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFilter.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageFont.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageGrab.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMath.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMode.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageMorph.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageOps.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImagePalette.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImagePath.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageQt.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageSequence.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageShow.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageStat.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageTk.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageTransform.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImageWin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\JpegPresets.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MicImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\MspImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\OleFileIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PaletteFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcfFontFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PngImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PSDraw.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\PyAccess.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\SunImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TarIO.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\TiffTags.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WalImageFile.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\_binary.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\_tkinter_finder.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\_util.py -> build\lib.win-amd64-3.6\PIL
    copying PIL\__init__.py -> build\lib.win-amd64-3.6\PIL
    running egg_info
    writing Pillow.egg-info\PKG-INFO
    writing dependency_links to Pillow.egg-info\dependency_links.txt
    writing top-level names to Pillow.egg-info\top_level.txt
    warning: manifest_maker: standard file '-c' not found

    reading manifest file 'Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.sh'
    no previously-included directories found matching 'docs\_static'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.landscape.yaml'
    warning: no previously-included files found matching 'appveyor.yml'
    warning: no previously-included files found matching 'build_children.sh'
    warning: no previously-included files found matching 'tox.ini'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    writing manifest file 'Pillow.egg-info\SOURCES.txt'
    copying PIL\OleFileIO-README.md -> build\lib.win-amd64-3.6\PIL
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "D:\temp\pip-install-q3_gt5ch\pillow\setup.py", line 753, in <module>
        zip_safe=not debug_build(), )
      File "c:\program files\python36\lib\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "c:\program files\python36\lib\distutils\dist.py", line 955, in run_commands
        self.run_command(cmd)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "c:\program files\python36\lib\distutils\command\install.py", line 545, in run
        self.run_command('build')
      File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "c:\program files\python36\lib\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "c:\program files\python36\lib\distutils\dist.py", line 974, in run_command
        cmd_obj.run()
      File "c:\program files\python36\lib\distutils\command\build_ext.py", line 339, in run
        self.build_extensions()
      File "D:\temp\pip-install-q3_gt5ch\pillow\setup.py", line 521, in build_extensions
        ' using --disable-%s, aborting' % (f, f))
    ValueError: zlib is required unless explicitly disabled using --disable-zlib, aborting

    ----------------------------------------
  Rolling back uninstall of pillow
Command ""c:\program files\python36\python.exe" -u -c "import setuptools, tokenize;__file__='D:\\temp\\pip-install-q3_gt5ch\\pillow\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record D:\temp\pip-record-umnb4qnb\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in D:\temp\pip-install-q3_gt5ch\pillow\

C:\WINDOWS\system32>

**Comment by hugovk** [comment]
Hmm, that's because it's trying to build from source (not a good idea on Windows) and we only have prebuilt binary wheels for Python 3.6 for Pillow 4.x and up. 

https://pillow.readthedocs.io/en/5.3.x/installation.html

**Comment by v-python** [comment]
Thanks again, @hugovk the link you pointed to doesn't even mention the existence of support for Windows 10 or any version numbers greater than 3.4.  This means I don't know if there is a version 4.x, or if versions went from 3.4 to 5.3.0.  I don't know if libraqm is required by 4.x although it appears to be used in 5.3.0 (the current version reported by pip but not documented in the link). So What should I try next? Or am I expected to read all the development notes to figure this out?

**Comment by hugovk** [comment]
Release history is here: https://pypi.org/project/Pillow/

It went 3.4, 4.0, 4.1, 4.2, 4.3, 5.0...

What exactly are you trying to achieve with your code? Text drawing should still be working, and the unit tests are passing on Windows, you could check and compare with the text drawing unit tests.

**Comment by v-python** [comment]
Thanks for the list. I tried 4.3, and it produces the same error. I don't seem to be able to install 3.4, so I'm still stuck.

I just extracted enough code from a previously working program that failed to demonstrate the error: it should not be considered an application in an of itself.

The code from which the extraction happened was attempting to figure out the largest font that could be used to place text in a given rectangular area, filling the area in one dimension (depending on the length of each line and number of lines of text).

I guess the unit tests are not testing the function that fails for me.

**Comment by hugovk** [comment]
I also get `KeyError: 'setting text direction or font features is not supported without libraqm'` on macOS High Sierra / Python 3.7.0 / Pillow 5.3.0. I've not tested any older versions.

In the example, `line` and the first `im` aren't used:

```python
from PIL import Image, ImageDraw, ImageFont
def foo():
    line = "foo"
    im = Image.new( "1", ( 1200, 600 ), 'white')
    font = ImageFont.truetype("times.ttf", 30 )

    lxMin, lyMin, lxMax, lyMax, line = 60, 60, 600, 300, "foo"
    im = Image.core.fill("L", ( lxMax - lxMin, lyMax - lyMin ), 0 )
    font.font.render( line, im.id, True )

foo()
```

But more importantly `Image.core` is a private, internal interface:

https://github.com/python-pillow/Pillow/blob/e9221cf84fd2074c3f0f85f3932bf3bcee6ac92f/src/PIL/Image.py#L62-L63

Perhaps we should rename it as `Image._core` in the next major version, and certainly we should document it more clearly in the [Image docs](https://pillow.readthedocs.io/en/5.3.x/reference/Image.html).

Here's an alternative method for finding the largest font that will fit in an area: https://stackoverflow.com/a/4902713/724176

With some modification for multiline text:
```python
from PIL import Image, ImageDraw, ImageFont

font_path = "times.ttf"

im = Image.new("1", (1200, 600), "white")
draw = ImageDraw.Draw(im)
# txt = "foo"
txt = "Hello World\nHello there\nHello again"

# Starting font size
font_size = 1

# Portion of image width you want text width to be
img_fraction = 1

font = ImageFont.truetype(font_path, font_size)
while (
    font.getsize_multiline(txt)[0] < img_fraction * im.size[0]
    and font.getsize_multiline(txt)[1] < img_fraction * im.size[1]
):

    print(im.size, font.getsize_multiline(txt), font_size)

    # Iterate until the text size is just larger than the criteria
    font_size += 1
    font = ImageFont.truetype(font_path, font_size)


# Optionally de-increment to be sure it is less than criteria
font_size -= 1
font = ImageFont.truetype(font_path, font_size)

print("Final font size", font_size)

# Put the text on the image
draw.text((0, 0), txt, font=font)

# im.save('out.png')
im.show()
```

![image](https://user-images.githubusercontent.com/1324225/46996911-d9edc180-d126-11e8-8a0e-d67ffe4e05d6.png)

You'll see this doesn't take care of [descenders](https://en.wikipedia.org/wiki/Descender) very well, this might be a bug. Perhaps there's another metric that can be checked to get the full height, but you could add some padding or change `img_fraction` to something like `0.9`:

![image](https://user-images.githubusercontent.com/1324225/46996875-c0e51080-d126-11e8-9f38-4374094c68bc.png)

**Comment by v-python** [comment]
Thanks for your continued efforts and responses.  The code was extracted from the PillowPatch code that I've been using since submitting it a couple years ago, and was intended/hoped to be internal to PIL eventually, so that the use of internal functions seemed OK in that context.  Two years later, I've forgotten some of the details of what does what and why I used that function, but it seems that development and testing of PIL cannot easily be done on Windows by contributors, so I was not able to further the submittal process beyond the original patch code. Someone else tried, but apparently also gave up.

The multiline code I was trying to improve, and which works fine in versions from two years ago through version 4.0, used heuristics and didn't expose accurate metrics, and I tried to write code that would be a useful update to that, using accurate metrics, and returning useful information based on text baselines, ascenders and descenders.

Like the code I was trying to improve, your code uses inaccurate metrics, and attempts to paper over them with heuristics that might work for some fonts, but will likely fail for others, and probably won't achieve the desired edge-to-edge filling of the image area. Probably it will get close, most of the time, for most fonts, and could be tuned for a particular font. Handling only some fonts, or getting only close to the desired results is a sad state of affairs, when precise calculations are (at least through version 4.0) quite possible.

I don't claim to be an expert in PIL internals, but I spent a fair bit of time coming up with the accurate code in PillowPatch.  I guess the use of internals doomed it to eventual failure (4.1+). Someone with better knowledge of the internals of PIL could perhaps do the implementation without using internals... if the proper metrics have been exposed since I submitted the patch.

PIL is a very useful tool in many ways, but its text handling has been limited because of not fully exposing the font metrics. IIRC it is the ascent and/or descent size of the font, from the font metrics, that was not exposed, forcing me to dive into internals. Also, at the time, the concept of "point = pixel" (ignoring DPI) was not very well documented either.

Given the inability to contribute to PIL from a Windows platform, I haven't been following its development very closely.  The other day, I ran into a bug attempting to .expand a color image. .expand had been working with B&W images, but not color. That inspired me to upgrade PIL to see if there was a fix (it is still broken, unfortunately), and so I ran into this other problem as a result.

Thanks for your help in finding a version that I can install and that works. However, I am now facing an uncertain future with trepidation: how many future versions of Python will continue to be supported by the only version of PIL (4.0) on which my code will run?

I'd be happy to upgrade my code to remove internals, if appropriate font metrics are now exposed by PIL... are they? Without use of raqm?

**Comment by hugovk** [comment]
Pillow 4.0 supports [Python 2.7 and 3.3-3.6](https://pillow.readthedocs.io/en/5.3.x/installation.html#notes). 

Two extra parameters were added to the `render` call in https://github.com/python-pillow/Pillow/pull/2576 for RAQM support, so try adding `None, None`:
```diff
from PIL import Image, ImageDraw, ImageFont
def foo():
    line = "foo"
    im = Image.new( "1", ( 1200, 600 ), 'white')
    font = ImageFont.truetype("times.ttf", 30 )

    lxMin, lyMin, lxMax, lyMax, line = 60, 60, 600, 300, "foo"
    im = Image.core.fill("L", ( lxMax - lxMin, lyMax - lyMin ), 0 )
-   font.font.render( line, im.id, True )
+   font.font.render( line, im.id, True, None, None )

foo()
```

That at least runs without the `KeyError` for me.

**Comment by hugovk** [comment]
Pillow does expose font (ascent and) descent height via `ImageFont.getmetrics`. Here's the other code modified to take the descent into account:

```diff
from PIL import Image, ImageDraw, ImageFont

font_path = "times.ttf"

im = Image.new("1", (1200, 600), "white")
draw = ImageDraw.Draw(im)
# txt = "foo"
txt = "Hello World\nHello there\nHello again"

# Starting font size
font_size = 1

# Portion of image width you want text width to be
img_fraction = 1

font = ImageFont.truetype(font_path, font_size)
+ascent, descent = font.getmetrics()

while (
    font.getsize_multiline(txt)[0] < img_fraction * im.size[0]
-   and font.getsize_multiline(txt)[1] < img_fraction * im.size[1]
+   and font.getsize_multiline(txt)[1] + descent < img_fraction * im.size[1]
):

    print(im.size, font.getsize_multiline(txt), font_size)

    # Iterate until the text size is just larger than the criteria
    font_size += 1
    font = ImageFont.truetype(font_path, font_size)
+   ascent, descent = font.getmetrics()


# Optionally de-increment to be sure it is less than criteria
font_size -= 1
font = ImageFont.truetype(font_path, font_size)

print("Final font size", font_size)

# Put the text on the image
draw.text((0, 0), txt, font=font)

# im.save('out.png')
im.show()
```

![image](https://user-images.githubusercontent.com/1324225/47107286-993e9700-d251-11e8-9062-01b28f0a6880.png)

**Comment by v-python** [comment]
Thanks again @hugovk for your continued help.  I found a comment in my code indicating that the missing metric is "font.font.height" Maybe that has been exposed by now?  It can be approximated by sum( font.getmetrics()) but height is sometimes larger than that to allow the font designer to give a recommended line spacing (a.k.a. leading).  While my code was using getmetrics(), searching the pillow online docs doesn't find any hits for getmetrics() so is it internal too? Or where documented? Since I can't find getmetrics(), I can't search nearby documentation to see if the height metric has yet been exposed.

Is there a way to use font.font.render without using the internal Image.core.fill operation which seems to produce the im.id which is needed for the font.font.render function?

Adding the two additional parameters of None to the font.font.render call "fixed" my code to work as well as before (without the height metric available). Thanks again. However, it would seem that this is an incompatible change in interface for code/systems that do not have raqm available: such systems should use a default that is functional, such as None, None, yet perhaps the current defaults are better for systems that do have raqm available. Adding parameters having defaults that cannot work when environmental dependencies cannot be met seems not to be a good practice, regarding compatibliity.

**Comment by hugovk** [comment]
`FreeTypeFont.getmetrics()` should be public, but for some reason is not documented. I've created https://github.com/python-pillow/Pillow/issues/3411 to add it.

Here it is:

https://github.com/python-pillow/Pillow/blob/0378fede70d0d8609468a38d22238eefd53c3a9e/src/PIL/ImageFont.py#L158-L159

_Generally_, methods in the Python layer are the public API, unless they begin with `_`, or they're commented in the code as internal.

There's also `getsize` and `getsize_multiline` nearby in that file.

The only place `FreeTypeFont.font.render` is used is in `FreeTypeFont.getmask2`. Can you use that?

https://github.com/python-pillow/Pillow/blob/0378fede70d0d8609468a38d22238eefd53c3a9e/src/PIL/ImageFont.py#L183-L188

When RAQM was added, an internal interface was changed, which isn't a breaking change in the public API. We try hard to avoid breaking changes in the public API, and only intentionally do so in major releases after a period of deprecation (and I don't think it was for RAQM). 

`None, None` are the defaults Pillow uses internally. If public functions are used via the public API, it should be compatible for systems both with and without RAQM. We make no guarantees for internal functions and recommend they are not used.

Glad to hear you got your code working in meantime. Are we good to close this issue?

**Comment by v-python** [comment]
Well, the multiline stuff is in just as bad of shape as two years ago, it seems, with a vertical 'A' size and a hard-coded constant being used instead of the ascent + descent (or better, height).

    def getsize_multiline(self, text, direction=None,
        spacing=4, features=None):

And the return value from that doesn't tell you where the baseline is so you can align multiline text with other text.  This is why I wrote PillowPatch in the first place.

But as far as this particular issue, it seems to be complete. I've converted the code to use font.getmask (documented, unlike font.getmask2) instead of directly calling font.render, and that, in place of the direct call with the extra None, None parameters also works with Pillow 5.3. I now have better hopes of being able to upgrade to Python 3.7, without further breakage.

I'll make a different issue for the other bug I encountered, that made me try upgrading PIL in the first place, which then caused this issue. Assuming I can reproduce it in a test case: I already recodeded my application to avoid the failing operation.
