### ISSUE TITLE
Document font getmetrics

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3411]
### What did you do?

Check the docs for ~`ImageFont.getmetrics`~ (actually, `FreeTypeFont.getmetrics`).

* https://pillow.readthedocs.io/en/5.3.x/reference/ImageFont.html
* https://pillow.readthedocs.io/en/5.3.x/search.html?q=getmetrics&check_keywords=yes&area=default

### What did you expect to happen?

Find it.

### What actually happened?

It's not there.

### Notes

We should add it, and check the other sibling functions. 

Should it be added automatically (and is that broken?), or is it manual documentation (and can it be automated instead)?

**Comment by hugovk** [comment]
Also need to add the font metric getters from https://github.com/python-pillow/Pillow/issues/3414#issuecomment-430912358.

**Comment by anudeepsamaiya** [comment]
I would like to work on this issue. Is this still open?

**Comment by hugovk** [comment]
@anudeepsamaiya Yes, it is still open!

Docs are under https://github.com/python-pillow/Pillow/tree/master/docs, and please ask if you've any questions.
