### ISSUE TITLE
Font metric for font height not available

### ISSUE THREAD

**Issue by v-python** [python-pillow/Pillow#3414]
### What did you do?

read documentation

### What did you expect to happen?

find a way to obtain the font height metric, which is not always the same as the ascent + descent returned by font.getmetric()

### What actually happened?

Couldn't find any way to obtain the font height metric.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6
* Pillow: 5.3

**Comment by hugovk** [comment]
For [reference](https://material.io/design/typography/understanding-typography.html#type-properties):
![image](https://user-images.githubusercontent.com/1324225/47139426-7e593a80-d2c4-11e8-8709-21a31ebe2b5a.png)


These values come directly from FreeType (see https://github.com/python-pillow/Pillow/issues/1540#issuecomment-157741134):

```python
from PIL import ImageFont

t = ImageFont.truetype("times.ttf", 40)
print("t.getmetrics()\t", t.getmetrics())
print("t.font.ascent\t", t.font.ascent)
print("t.font.descent\t", t.font.descent)
print("t.font.height\t", t.font.height)
print("t.font.x_ppem\t", t.font.x_ppem)
print("t.font.y_ppem\t", t.font.y_ppem)
print('t.getsize("A")\t', t.getsize("A"))
print('t.getsize("AB")\t', t.getsize("AB"))
print('t.getsize("M")\t', t.getsize("M"))
print('t.getsize("y")\t', t.getsize("y"))
print('t.getsize("a")\t', t.getsize("a"))
```
```python
t.getmetrics()	 (36, 9)
t.font.ascent	 36
t.font.descent	 9
t.font.height	 44
t.font.x_ppem	 40
t.font.y_ppem	 40
t.getsize("A")	 (29, 36)
t.getsize("AB")	 (56, 36)
t.getsize("M")	 (36, 36)
t.getsize("y")	 (20, 45)
t.getsize("a")	 (18, 36)
```

Does this help?

I'll add a note in https://github.com/python-pillow/Pillow/issues/3411 that these need to go into the docs.

**Comment by v-python** [comment]
Sure does.  I tracked through getmetrics 2 years ago, and couldn't find any way to get at it. I found some tools that let me crack open the font file, and knew the value was in there, but sure couldn't find a way to get at it via Pillow.  Maybe this wasn't there then.
