### ISSUE TITLE
TIFF images read through Pillow are corrupted (Information around the edge gets lost and displays black)

### ISSUE THREAD

**Issue by RyanZHe** [python-pillow/Pillow#3416]
### What did you do?
Load a tiff image through Image.open()

### What did you expect to happen?
The tiff image correctly loaded and displayed.

### What actually happened?
Black areas along the right and bottom edge of the picture

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 16.04
* Python: 3.6.6
* Pillow: 4.0.0

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

The local image file
[2017_03_TB_landsat.tif.tar.gz](https://github.com/python-pillow/Pillow/files/2493449/2017_03_TB_landsat.tif.tar.gz)

```
img = Image.open("2017_03_TB_landsat.tif")
img
```

![index](https://user-images.githubusercontent.com/16871889/47180796-664ae080-d2ef-11e8-91f5-291b937a6ad5.png)

**Comment by RyanZHe** [comment]
Same image correctly read through tifffile
```
a = tiff.imread("/content/gdrive/My Drive/Snow_coverage/2017_03_TB_landsat.tif")
img =  scipy.misc.toimage(a)
img
```
![index1](https://user-images.githubusercontent.com/16871889/47181550-38669b80-d2f1-11e8-8248-76de5d619c33.png)

**Comment by RyanZHe** [comment]
The problem also exist for PILLOW 5.3.0

**Comment by kkopachev** [comment]
Just tried 5.3.0 and works fine. 
```
python
Python 2.7.15 (default, Jul 25 2018, 18:19:34) 
[GCC 6.3.0 20170516] on linux2
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> img = Image.open("2017_03_TB_landsat.tif")
>>> img
<PIL.TiffImagePlugin.TiffImageFile image mode=RGB size=3751x1380 at 0x7FB741E7E410>
```
Saved as jpg and no borders visible.

**Comment by radarhere** [comment]
@RyanZHe could you provide the exact code that you're using to save - `im.save('out.jpg')` - or view - `im.show()` - the image? It would help us to know for certain whether we are testing your issue or not.

**Comment by RyanZHe** [comment]
> @RyanZHe could you provide the exact code that you're using to save - `im.save('out.jpg')` - or view - `im.show()` - the image? It would help us to know for certain whether we are testing your issue or not.

All the code were run in a jupyter notebook. I also converted the images to numpy arrays to check the differences:

```
img = Image.open("2017_03_TB_landsat.tif")
np.array(img)
```
The pixels along the edges are all black(0, 0, 0) when the image is read.
```
array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],
       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],
       ...,

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]],

       [[  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0],
        ...,
        [  0,   0,   0],
        [  0,   0,   0],
        [  0,   0,   0]]], dtype=uint8)
```

```
a = tiff.imread("/content/gdrive/My Drive/Snow_coverage/2017_03_TB_landsat.tif")
img =  scipy.misc.toimage(a)
np.array(image)
```
Correctly read RGB values along the edges.
```
array([[[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [222, 205, 181],
        [223, 207, 183],
        [225, 209, 185]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [216, 200, 177],
        [225, 209, 185],
        [228, 211, 187]],

       [[255, 255, 255],
        [255, 255, 255],
        [255, 255, 255],
        ...,
        [223, 207, 182],
        [227, 210, 186],
        [227, 210, 186]],

       ...,

       [[ 83,  83,  67],
        [ 76,  81,  67],
        [ 73,  82,  68],
        ...,
        [238, 243, 234],
        [255, 255, 255],
        [255, 255, 255]],

       [[ 91,  86,  69],
        [ 82,  85,  68],
        [ 80,  81,  69],
        ...,
        [229, 234, 226],
        [255, 255, 255],
        [247, 250, 244]],

       [[ 95,  91,  70],
        [ 95,  91,  74],
        [ 85,  88,  73],
        ...,
        [255, 255, 255],
        [255, 255, 255],
        [240, 242, 238]]], dtype=uint8)
```

**Comment by radarhere** [comment]
I am unable to reproduce this in Google's Colaboratory Jupyter environment, either with Pillow 6.0.0 or 5.3.0.

@RyanZHe are you able to reproduce it there - https://colab.research.google.com/? If yes, then sharing that with us would be very helpful.

**Comment by radarhere** [comment]
Closing due to lack of response and reproducibility.
