### ISSUE TITLE
Can't capture the whole screen on Windows 10

### ISSUE THREAD

**Issue by Nevss** [python-pillow/Pillow#3432]
when I use 

ImageGrab.grab()

I get this picture.

![bb138a4ccfd5a280s](https://user-images.githubusercontent.com/10334358/47361926-c5509100-d705-11e8-85d2-25d143b0096b.jpg)

I think  windows display zoom caused this.

Could someone help me?

Thanks.

**Comment by radarhere** [comment]
Hi. Just to be clear, could you attach a regular screenshot for comparison?

**Comment by Nevss** [comment]
ok

I mean , I want to shot the whole screen , like this ：


![wx20181026-165008](https://user-images.githubusercontent.com/10334358/47556424-dafdca80-d940-11e8-9a01-686fc3a4f0c0.png)

**Comment by hugovk** [comment]
As a workaround, do either https://github.com/BoboTiG/python-mss or https://github.com/ponty/pyscreenshot help?

**Comment by radarhere** [comment]
This should now have been fixed by #4000
