### ISSUE TITLE
Weird behaviors of using color name on some modes

### ISSUE THREAD

**Issue by Gsllchb** [python-pillow/Pillow#3436]
### What did you do?
**new** a CMYK (or YCbCr, LAB, HSV) image with "white" as color.

### What did you expect to happen?
Create a white image.

### What actually happened?
Created a image which is not white at all, or raised error.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: CPython 3.7
* Pillow: 5.3.0

```python
from PIL import Image
Image.new(mode="CMYK", size=(100, 100), color="white").show()  # see picture1
Image.new(mode="YCbCr", size=(100, 100), color="white").show()  # see picture2
Image.new(mode="LAB", size=(100, 100), color="white").show()  # raise ValueError
Image.new(mode="HSV", size=(100, 100), color="white").show()  # see picture3
```
*picture1*
![cmyk](https://user-images.githubusercontent.com/19491121/47431588-b97cd180-d7ce-11e8-9b5d-884065b00295.jpeg)

*picture2*
![ycbcr](https://user-images.githubusercontent.com/19491121/47431693-12e50080-d7cf-11e8-852d-8cb9101b2f39.jpeg)

*picture3*
roughly red
(Sorry, I don't know how to save HSV image.)

**Comment by hugovk** [comment]
Thanks for the report. The docs say (italics mine):


> **color** – What color to use for the image. Default is black. If given, this should be a single integer or floating point value for single-band modes, and a tuple for multi-band modes (one value per band). _When creating RGB images, you can also use color strings as supported by the ImageColor module._ If the color is None, the image is not initialised.

https://pillow.readthedocs.io/en/5.3.x/reference/Image.html#PIL.Image.new

So the colour name is only supported for RGB images.

That's because, when supplying a colour string, it's converted to an RGB colour using `ImageColor.getcolor`, which only supports RGB:

https://pillow.readthedocs.io/en/5.3.x/reference/ImageColor.html#PIL.ImageColor.getcolor

Please use a non-string value for non-RGB images.

**Comment by Gsllchb** [comment]
Thank you for your detailed reply.

But, I think Pillow should raise exceptions for these situations as [_The Zen of Python_](https://www.python.org/dev/peps/pep-0020/) suggested: `Errors should never pass silently`.

**Comment by hugovk** [comment]
The _Zen of Pillow_: `don't break existing code` :)

Your suggestion is generally good, we could consider issuing a deprecation warning and then later replace it with an exception.

Having said that, I see it does also support those with basemode `L`:

https://github.com/python-pillow/Pillow/blob/da9a3dae6389ed4a39c32ce36b22b035dd566fe1/src/PIL/ImageColor.py#L146

ie. `LA`, `La`, `I;16`, `I;16L` and `I;16B`:
https://github.com/python-pillow/Pillow/blob/959db43d22b633519ac61ad6f58cbe63f8c1a1d0/src/PIL/ImageMode.py#L42-L53

And:

```python
>>> from PIL import Image
>>> Image.getmodebase("RGB")
'RGB'
>>> Image.getmodebase("HSV")
'RGB'
>>> Image.getmodebase("CMYK")
'RGB'
>>> Image.getmodebase("YCbCr")
'RGB'
>>> Image.getmodebase("LAB")
'RGB'
>>> Image.getmodebase("HSV")
'RGB'
```

So looks like this needs more investigation.

**Comment by Gsllchb** [comment]
That’s great! I am so glad you agree my opinion.

I’m a little confused now. What is the meaning of __base mode__? Are there any document about this?

**Comment by Gsllchb** [comment]
Let's make it clear.

A mode is a wrapper of its base mode. What actually stores in memory only are the images with base modes.

Am I correct?
