### ISSUE TITLE
Noise/antialiasing being added to images

### ISSUE THREAD

**Issue by ejj28** [python-pillow/Pillow#3437]
### What did you do?
I've been trying to combine a few images into one single image, but the result looks like it's been antialiased or something.
### What did you expect to happen?
This is the desired image:
![Image](https://dl.dropboxusercontent.com/s/afanznlrazx62tr/properimage.png?dl=0)
### What actually happened?
![Image](https://dl.dropboxusercontent.com/s/b2b0qk3h7jmpt12/image2.jpg?dl=0)

(both images have been enlarged, the actual resolution is 50x50)
### What are your OS, Python and Pillow versions?
OS: macOS 10.12.6
Python: 2.7.15
Pillow: 1.1.7

This is my code:
```
import os

from PIL import Image

files = [
  '/Users/.../.../.../assets/upperrightcorner.png',
  '/Users/.../.../.../assets/bottomrightcorner.png',
  '/Users/.../.../.../assets/upperleftcorner.png',
  '/Users/.../.../.../assets/bottomleftcorner.png',
  '/Users/.../.../.../assets/testbackground.png'
  ]
  
result = Image.new("RGB", (50, 50))
img0 = Image.open(files[4])
img1 = Image.open(files[2])
img2 = Image.open(files[3])
img3 = Image.open(files[0])
img4 = Image.open(files[1])

w1, h1 = img1.size
w2, h2 = img2.size
w3, h3 = img3.size
w4, h4 = img4.size
result.paste(img0, (0, 0))
result.paste(img1, (0, 0), img1)
result.paste(img2, (0, h1 + 1), img2)
result.paste(img3, (w1 + 1, 0), img3)
result.paste(img4, (w1 + 1, h1 + 1), img4)

result.save('/Users/.../.../.../image.jpg')
```

**Comment by hugovk** [comment]
JPEG is generally better suited for photos.

Try saving as PNG instead, or add the `quality ` parameter:

https://pillow.readthedocs.io/en/5.3.x/handbook/image-file-formats.html?highlight=Quality#jpeg

**Comment by ejj28** [comment]
That worked, thanks! For some reason I never realized I was exporting to jpeg, as soon as I changed to png I got the desired image.
