### ISSUE TITLE
Jpeg load performance regression for Pillow 5.1+ from wheels

### ISSUE THREAD

**Issue by kkopachev** [python-pillow/Pillow#3441]
### What did you do?
Performance regression when opening (and loading) a jpeg file in Pillow, installed from wheels on x86_64 linux. Affects loading of jpeg files. Regression happened updating from Pillow 5.0.0 to 5.1.0 (up to 5.3.0)

### What are your OS, Python and Pillow versions?

* OS: linux, x86_64
* Python: 2.7, 3.7
* Pillow: 5.1.0+

I am not sure where this issue belongs to, seems to be related to wheels building somehow.

Original issue was created in thumbor repo https://github.com/thumbor/thumbor/issues/1102 saying there was a noticeable performance regression. Upon further investigation, I was able to come up with simple reproduction steps.

```
docker run --rm -it python:2 bash
root@9e6e1f13f44a:/# wget -q wget https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg
root@9e6e1f13f44a:/# pip install pillow==5.0.0
Collecting pillow==5.0.0
  Downloading https://files.pythonhosted.org/packages/89/bd/1d9a10f3e8157b7df275740b0782a892a0db387f8286620110c41e5146c7/Pillow-5.0.0-cp27-cp27mu-manylinux1_x86_64.whl (5.8MB)
    100% |████████████████████████████████| 5.9MB 1.5MB/s 
Installing collected packages: pillow
Successfully installed pillow-5.0.0
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@9e6e1f13f44a:/# wget https://upload.wikimedia.org/wikipedia/commons/b/b4/JPEG_example_JPG_RIP_100.jpg
root@9e6e1f13f44a:/#
root@9e6e1f13f44a:/#
root@9e6e1f13f44a:/# python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
1000 loops, best of 5: 2.58 msec per loop
root@9e6e1f13f44a:/#
root@9e6e1f13f44a:/#
root@9e6e1f13f44a:/# pip install pillow==5.1.0
Collecting pillow==5.1.0
  Using cached https://files.pythonhosted.org/packages/00/49/a0483e7308b4b04b5a898789911dbb876d9fea54e7df0453915e47744cfd/Pillow-5.1.0-cp27-cp27mu-manylinux1_x86_64.whl
Installing collected packages: pillow
  Found existing installation: Pillow 5.0.0
    Uninstalling Pillow-5.0.0:
      Successfully uninstalled Pillow-5.0.0
Successfully installed pillow-5.1.0
You are using pip version 18.0, however version 18.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
root@9e6e1f13f44a:/#
root@9e6e1f13f44a:/#
root@9e6e1f13f44a:/# python -m timeit -n1000 -r5 -s'from PIL import Image' 'Image.open("JPEG_example_JPG_RIP_100.jpg").load()'
1000 loops, best of 5: 5.77 msec per loop
root@9e6e1f13f44a:/#
```

In short - Pillow 5.1.0 takes 5.77 msec to open test JPEG file. However Pillow 5.0.0 took 2.58 msec to open the same file.

I did try to build both Pillow versions from source (only enabling libjpeg) and in that case they show same performance.
I thought maybe for Pillow 5.1 you switched to libjpeg9c, so I built both Pillow versions with libjpeg9c - no performance difference.

As people report in original thumbor ticket, they are not able to repro it on OSX, so I assume it's linux only.

As a last resort, I copied libjpeg.so from what was shipped with wheels for Pillow 5.0.0 and copied it over to Pillow 5.1 installed from wheels - no performance difference.

I suspect something wrong with how libjpeg got build starting from Pillow 5.1.0. I tried 5.2.0 and 5.3.0 - both experience same issue.

**Comment by hugovk** [comment]
I can reproduce on Linux (Ubuntu/Travis CI) and not on macOS (High Sierra).

msec per loop:

Pillow version | 2.7 wheel | 2.7 source | 3.7 wheel | 3.7 source
-- | -- | -- | -- | --
5.0.0 | 2.75 | 2.6 | n/a | 2.94
5.1.0 | 5.41 | 2.58 | n/a | 2.95
5.2.0 | 5.45 | 2.61 | 5.67 | 2.94
5.3.0 | 5.44 | 2.62 | 5.69 | 2.94

https://travis-ci.org/hugovk/test/builds/447090663

Wheels are built on https://github.com/python-pillow/pillow-wheels (see 
https://github.com/python-pillow/Pillow/blob/master/RELEASING.md for the full process).

* 5.0.0 was released on 2018-01-02 (https://github.com/python-pillow/pillow-wheels/commit/31f13e7058314a5c8ccbae85716bfcebe39bce1d)
* 5.1.0 was released on 2018-04-02 (https://github.com/python-pillow/pillow-wheels/commit/1cab7ad46cad74bbbf62767bbde6100d3993b0bf)

Here's the diff:
* https://github.com/python-pillow/pillow-wheels/compare/31f13e7058314a5c8ccbae85716bfcebe39bce1d..1cab7ad46cad74bbbf62767bbde6100d3993b0bf
* FreeType 2.8.1 -> 2.9
* multibuild was updated

**Comment by matthew-brett** [comment]
Might be - but I can't think what might have caused that.   Have you tried going back to earlier versions of the JPEG libraries?

**Comment by matthew-brett** [comment]
I'm sorry - I don't know what could have caused that.   I can't see
anything obvious in the commits between 2 January and 2 April.

Maybe worth clearing the ccaches with the travis interface, and trying a
rebuild?

Could it be the Docker image?  Have the Mac builds slowed down as well?

**Comment by hugovk** [comment]
I cleared the Travis caches for https://travis-ci.org/python-pillow/Pillow/

There are no caches for https://travis-ci.org/python-pillow/pillow-wheels or https://travis-ci.org/python-pillow/docker-images

---

Actually, the Mac wheels are consistent for all versions 5.0.0 -> 5.3.0, and also when building from source, but wheels are about twice as slow as source.

macOS High Sierra / Python 2.7.15 and 3.7.0 / msec per loop:

Pillow version | 2.7 wheel | 2.7 source | 3.7 wheel | 3.7 source
-- | -- | -- | -- | --
5.0.0 | 7.56 | 3.31 | n/a | 3.84
5.1.0 | 8.05 | 3.26 | n/a | 3.37
5.2.0 | 7.88 | 3.57 | 7.55 | 3.61
5.3.0 | 7.2 | 3.5 | 7.35 | 3.59

**Comment by matthew-brett** [comment]
Is it possible that the JPEG library is using things like AVX intrinsics, and so on, when built from source?   Is the compiler the same?  I mean, maybe clang has got faster, and you see that on your machine, but we are using an old clang on the OSX images we use for building?  The gcc on the Manylinux docker image is pretty old too.

**Comment by hugovk** [comment]
My Mac when building source:
```console
$ clang --version
Apple LLVM version 10.0.0 (clang-1000.10.44.2)
Target: x86_64-apple-darwin17.7.0
Thread model: posix
InstalledDir: /Library/Developer/CommandLineTools/usr/bin
```
Linux / Travis / Python 2.7 when building source:
```
gcc (Ubuntu 4.8.4-2ubuntu1~14.04.3) 4.8.4
```
Linux / Travis / Python 3.7 when building source:
```
gcc (Ubuntu 5.4.0-6ubuntu1~16.04.10) 5.4.0 20160609
```

**Comment by hugovk** [comment]
Here's the PR where it was added, "Strip binaries on non-OSX builds".

https://github.com/matthew-brett/multibuild/pull/140

**Comment by kkopachev** [comment]
Looks like libjpeg would use `-g -O2`, but since CFLAGS is already passed, then it's used instead.

**Comment by matthew-brett** [comment]
Yes, that makes more sense (that CFLAGS isn't getting set to something nice for libjpeg, and that started happening because of the strip flags going in there).

You could set CFLAGS explicitly for libjpeg?

**Comment by kkopachev** [comment]
libjpeg install.txt says:
> * The default CFLAGS setting is "-g" for non-gcc compilers, "-g -O2" for gcc.

**Comment by hugovk** [comment]
There's also a ~x2 difference for webp, ~x1.5 for png.

macOS High Sierra, msec per loop:

Format | Pillow version | 2.7 wheel | 2.7 source | wheel / source | 3.7 wheel | 3.7 source | wheel / source
-- | -- | -- | -- | -- | -- | -- | --
webp | 5.3.0 | 2.08 | 1.02 | 2.04 | 2.46 | 1.1 | 2.24
jpg  | 5.3.0 | 5.44 | 2.62 | 2.08 | 5.69 | 2.94 | 1.94
png  | 5.3.0 | 1.61 | 1.27 | 1.27 | 1.59 | 1.05 | 1.51
tif  | 5.3.0 | 1.01 | 0.947 | 1.07 | 0.814 | 0.763 | 1.07

With JPEG_example_JPG_RIP_100.jpg and hopper.* for the others.

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/pillow-wheels/pull/117 as a solution to this.
