### ISSUE TITLE
Support for more bitfields in bmp

### ISSUE THREAD

**Issue by hmaarrfk** [python-pillow/Pillow#3444]
Image format: 32bpp BMP with bitfields

I am wondering if supporting bitfields with the following configuration

```python
                     (0xff, 0xff00, 0xff0000, 0xff000000),
```
is in scope

Currently, it is not supported
https://github.com/python-pillow/Pillow/blob/2fa54408d46411be9978e3b7ec6a5c70f44e09ab/src/PIL/BmpImagePlugin.py#L159-L166

The idea is that these bitfields allow one to store a contiguous C ordered `RGBA` array in memory and just dump it tofile. Doing so, I get a nice 20% boost in speed compared to pillow. But if I save my files in this format, PILLOW can't open them.

That said, pillow is kinda ubiquitous and saving in a BMP format that isn't supported by pillow is a little too dangerous for my taste.

I'm glad to submit a PR, but help navigating the Pillow database would be appreciated.

**Comment by radarhere** [comment]
Are you able to provide an image saved in that way, to be added to the test suite under the Pillow license?

**Comment by hmaarrfk** [comment]
yeah, i can make something like the bmp suite images and put it in public domain

**Comment by hugovk** [comment]
@hmaarrfk That would be great, we have PR #3705 to add support but it's using a hexexited image and it'd be much better to use a "real" one. Thanks!

**Comment by hmaarrfk** [comment]
hexexited? im not sure my image would be eany better. i would have created myself using the spec. RGB definitely isnt the norm 

https://github.com/hmaarrfk/redpil

**Comment by hmaarrfk** [comment]
I think the hexedited version is just as good as the file I would provide. Thanks guys!
