### ISSUE TITLE
codec configuration error when used with tkinter

### ISSUE THREAD

**Issue by guibou** [python-pillow/Pillow#3449]
### What did you do?

I'm trying to load this image:

![image](https://user-images.githubusercontent.com/9705357/47924398-ec545300-debb-11e8-9f64-543bdd3e29a7.png)

Using this script:

```python
from tkinter import ttk
from PIL import Image

im = Image.open("image.png")
print(im.tile)
im.load()
```

### What did you expect to happen?

No error

### What actually happened?

An error.

```
$ python repro.py 
[('zip', (0, 0, 19, 14), 507, 'P')]
Traceback (most recent call last):
  File "repro.py", line 6, in <module>
    im.load()
  File "/nix/store/kaymr52l64afckrlprsfxnnhy1lj5bxd-python3.6-Pillow-5.2.0/lib/python3.6/site-packages/PIL/ImageFile.py", line 254, in load
    raise_ioerror(err_code)
  File "/nix/store/kaymr52l64afckrlprsfxnnhy1lj5bxd-python3.6-Pillow-5.2.0/lib/python3.6/site-packages/PIL/ImageFile.py", line 59, in raise_ioerror
    raise IOError(message + " when reading image file")
OSError: codec configuration error when reading image file
```

If I comment out or move after `from PIL import Image` the line `from tkinter import ttk`, it works:

```
python repro.py 
[('zip', (0, 0, 19, 14), 507, 'P')]
```

### What are your OS, Python and Pillow versions?

* OS: linux (nixos)
* Python: 3.6.6
* Pillow: 5.2.0

**Comment by radarhere** [comment]
How did you install Pillow?

**Comment by guibou** [comment]
Using nix. `nix-shell -p python36Packages.pillow --pure -p python36Packages.tkinter`

**Comment by radarhere** [comment]
I attempted to recreate this on NixOS using Docker,
```
FROM nixos/nix:2.0

RUN nix-shell --pure -p python36Packages.pillow -p python36Packages.tkinter

RUN /nix/store/96wn2gz3mwi71gwcrvpfg39bsymd7gqx-python3-3.6.5/bin/python3.6 -c "from tkinter import ttk"
```
but I couldn't even import tkinter - `ModuleNotFoundError: No module named '_tkinter'`

Testing with our CI environments where we have tkinter installed, I was unable to reproduce this using other operating systems.

The error you're receiving is IMAGING_CODEC_CONFIG - this should mean that the error is actually within zlib. It is conceivable that the problem is with Pillow not passing data to it correctly, but given the lack of reproducibility, the simplest theory is that there is something specific about your install.

**Comment by guibou** [comment]
@radarhere thank you for having a look.

unrelated: with `nix-shell --pure -p 'python37.withPackages(p: [p.pillow p.tkinter])'` I'm able to run `from tkinter import ttk`. I think that recently the way python packages are working with nix changed and you need to use `withPackages`.

I can reproduce the problem with:

```
nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs/archive/959b199991fccfd11f13c0c7351c4c0d2a0747b5.tar.gz -p python36Packages.pillow -p python36Packages.tkinter --run 'python foo.py'
```

This is the latest commit on nixpkgs with this problem (I bisected nixpkgs).

I cannot reproduce it anymore starting at the following commit, which is the direct child of the previous one:

```
nix-shell -I nixpkgs=https://github.com/nixos/nixpkgs/archive/3ee1b5237118b8380141382ce82cb9732f06d4d0.tar.gz -p python36Packages.pillow -p python36Packages.tkinter --run 'python foo.py'
```

This commit was authored the 22 april 2019:

```
Author:     c0bw3b <c0bw3b@users.noreply.github.com>                                                                                                                                                                                            
AuthorDate: Mon Apr 22 23:47:48 2019 +0200                                                                                                                                                                                                      
Commit:     Frederik Rietdijk <freddyrietdijk@fridh.nl>                                                                                                                                                                                         
CommitDate: Sat Apr 27 07:09:05 2019 +0200                                                                                                                                                                                                      

    tcl/tk: 8.6.6 -> 8.6.9

    Changelog for Tcl: https://github.com/tcltk/tcl/blob/core-8-6-9/changes#L8797
    Changelog for Tk: https://github.com/tcltk/tk/blob/master/changes#L7417

    Tk release is actually v8.6.9.1 while Tcl is v8.6.9
```

It upgrades tcl/tk from 8.6.6 to 8.6.9.

So I do suspect a bug in tcl/tk which is now fixed. That's surprising (and a bit alarming) how the order of import may be affected by this bug.

I bisected the introduction of the regression to:

```
commit 948e9edce6902c6b9dfc67b0c53ccc96101ed299 (refs/bisect/bad)
Author: Vladimír Čunát <vcunat@gmail.com>
Date:   Fri Jan 6 21:45:20 2017 +0100

    zlib: maintenance 1.2.8 -> 1.2.10
    
    The removed CVEs should be fixed in the release.
```

That's not really informative.

As far as I'm concerned, I think we can close this bug.

(damned, this bisect took the night and filled my hard drive with so many version of python / gcc / ... ;)

**Comment by radarhere** [comment]
Thanks very much for investigating!
