### ISSUE TITLE
getsize() seems wrong

### ISSUE THREAD

**Issue by victorcombalweiss** [python-pillow/Pillow#3453]
### What did you do?

I am trying to check results of `font.getsize()` by comparing it with the size of text typed into Adobe Illustrator. They very rarely seem to match.

I chose the following settings in Adobe Illustrator for my text:

 - unit: `pt`
 - tracking: `0`
 - kerning: `auto`
 - font size: `9`
 - text content: a sequence of 25 "i"s

In the python REPL, I created fonts using the `ImageFont.truetype('...', 9)` instruction, then called `font.getsize('...')`, with the same text as in Adobe Illustrator

### What did you expect to happen?

I expected the result from `font.getsize()[0]` to be the same as the text box in Adobe Illustrator. 

### What actually happened?

Numbers were different for all fonts that I tested except Arial:

| Font                | Width in Illustrator | Result with Pillow |
|---------------------|----------------------|--------------------|
| Arial               | 49.987               | 50                 |
| AppleGothic         | 35.774               | 26                 |
| Times New Roman     | 62.513               | 75                 |
| Museo Sans 700      | 60.074               | 50                 |
| StixIntegralsD Bold | 60.074               | 50                 |

### What are your OS, Python and Pillow versions?

* OS: macOS 10.13.6
* Python: 3.6.5
* Pillow: 5.3.0

**Comment by hugovk** [comment]
* OS: macOS High Sierra
* Python: 3.7.1
* Pillow 5.3.0 (master)

This code:
```python

from PIL import ImageFont, Image, ImageDraw

path = "/Library/Fonts/Times New Roman.ttf"
text = "i" * 25
# print(text)

font = ImageFont.truetype(path, 9)

print(font.getsize(text)[0])


im = Image.new("RGB", (100, 30), "black")
draw = ImageDraw.Draw(im)
draw.text((10, 10), text, font=font)
im.show()
im.save("25is.png")
```

Produces:
```
(75, 9)
```

And:
![25is](https://user-images.githubusercontent.com/1324225/48315186-b447c100-e5db-11e8-90cc-90e9aa34bf8b.png)

Zooming in, each `i` is three pixels wide (`3*25=75`):
![image](https://user-images.githubusercontent.com/1324225/48315211-ebb66d80-e5db-11e8-973d-017a5ed74f2d.png)

---

Similarly in ImageMagick:

```bash
convert -size 100x30 xc:white -font "/Library/Fonts/Times New Roman.ttf" -pointsize 9 -annotate +10+10 "iiiiiiiiiiiiiiiiiiiiiiiii" imagemagick_font.png
```

![imagemagick_font](https://user-images.githubusercontent.com/1324225/48315291-f1f91980-e5dc-11e8-871e-cb3195608afe.png)

![image](https://user-images.githubusercontent.com/1324225/48315305-2371e500-e5dd-11e8-8e17-f328ef7c87c6.png)


---

How does it look in Adobe Illustrator?

**Comment by victorcombalweiss** [comment]
Thanks for the reply!

I am realising that actually `textsize()` returns a number of pixels, whereas I was comparing with `pt`s.

Nevertheless, choosing `px` as unit in Illustrator yields exactly the same results.

I can't seem to understand how to make a correspondence. Illustrator is vectorial, so however deep I zoom, it is always vectorial, I can't count pixels.

**Comment by victorcombalweiss** [comment]
I managed to understand and found out how to get the desired effect.

Thanks to the person who helped me on [stackoverflow](https://stackoverflow.com/questions/53205954/what-is-the-unit-of-imagefont-textsize-returned-values/53212070?noredirect=1#comment93476605_53212070)

What I got to understand was that pillow only cares about pixels, not about resolution. Thus I need to multiply the font size I am giving it by the resolution I intend to print at, then divide the result by that resolution, and finally convert from pts to millimeters.

The final formula is `getfont('...', resolution * font_size).getsize('...')[0] / resolution * 0.352778`

Thanks a lot for your help in narrowing down the problem!

**Comment by hugovk** [comment]
You're welcome, good to hear you got it figured out!

**Comment by arnavmehta7** [comment]
Hey, can you explain me what is resolution and how it is?

**Comment by radarhere** [comment]
You're asking about the `resolution` variable using in the second last comment? To be clear, this is just a variable that the user has defined themselves, and not part of Pillow. If you just want to draw text at a certain font size in pixels, you can ignore `resolution` altogether.

`font_size` is in points, as the user mentions in the first comment, and `0.352778` would be used to convert from points to milimeters.

![Screen Shot 2022-09-25 at 5 56 41 pm](https://user-images.githubusercontent.com/3112309/192134540-bcdc955b-bc43-4874-89de-a5baeb6c2464.png)

The units seem to cancel out, so I can't say what `resolution` is.

It is also worth noting that `getsize()` has now been deprecated - https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods

**Comment by arnavmehta7** [comment]
okk
