### ISSUE TITLE
Image dies for large CMYK JPEG

### ISSUE THREAD

**Issue by ashilen** [python-pillow/Pillow#3457]
### What did you do?
Opened an image and called `load`:
```python
img = Image.open('file.jpg')
img.load()
```

### What did you expect to happen?
Expected the method to finish executing and to return either an Image object or an informative message, or to raise an exception during execution.
### What actually happened?
The process died after several seconds. I expect the issue is with file corruption, but pillow should return an informative message or raise an exception. Debugging with pdb got as far as [this line](https://github.com/python-pillow/Pillow/blob/f8fbac68ded91d8371ad7f04582a0991eb220f3c/src/PIL/ImageFile.py#L239) before dying.

### What are your OS, Python and Pillow versions?

* OS: Debian GNU/Linux 9.5 (stretch)
* Python: 3.6 
* Pillow: 5.3.0

### To reproduce

Run the following with the image attached below:
```python
from PIL import Image
img = Image.open('image.jpg')
img.load()
```

![file](https://user-images.githubusercontent.com/3759694/48294264-293abf80-e451-11e8-9656-7e06901c25f3.jpg)

**Comment by cgohlke** [comment]
The image seems to have an alpha channel. It might depend on which jpeg library Pillow was used to built with. On Windows, which was built with libjpeg-turbo:
```Python
>>> from PIL import Image
>>> img = Image.open('image.jpg').convert('RGB')
>>> img.load()
<PixelAccess object at 0x000002714AE0FF50>
```

**Comment by ashilen** [comment]
Thanks @cgohlke and @hugovk for taking a look. In the interest of resolving this as quickly as possible for my application, what's the best way to build Pillow with a specific jpeg library?

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/5.3.x/installation.html#external-libraries

> If they are installed in a non-standard location, you may need to configure setuptools to use those locations by editing setup.py or setup.cfg, or by adding environment variables on the command line:
> 
> $ CFLAGS="-I/usr/pkg/include" pip install pillow

**Comment by radarhere** [comment]
Testing on a Ubuntu VM, I find that it dies at this line, after a varying number of iterations, whereas on Mac, it goes through the loop without any problems.
https://github.com/python-pillow/Pillow/blob/ee063af32fb4178138a06691c70c8a9763676f5a/src/libImaging/JpegDecode.c#L265

For a simpler test case, I found that if I create this image on my Mac -
```python
from PIL import Image
im = Image.new("CMYK", (8000, 8000))
im.save('cmyk.jpg', progressive=True)
```

and copy it to Ubuntu -
```python
from PIL import Image
im = Image.open('cmyk.jpg')
im.load()
```
'Killed' occurs.

You might ask 'Why not just create the image on Ubuntu?'. Well, on Ubuntu, the code to generate the image -

```python
from PIL import Image
im = Image.new("CMYK", (8000, 8000))
im.save('cmyk.jpg', progressive=True)
```

Also causes 'Killed'.

**Comment by radarhere** [comment]
That dying is most likely due to memory usage, which doesn't seem surprising.
