### ISSUE TITLE
Tidelift Funding

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#3469]
In late October, I got an email from @kszu @ @tidelift that read in part:

> I'm reaching out because I'm connecting with active open source maintainers to be part of our maintainer funding initiative at Tidelift, where we recently committed to paying $1 million to open source maintainers. We're already working with the maintainers of over 130 packages, including Python packages such as Coverage, setuptools, beautifulsoup, and Fabric.

I subsequently discussed funding with @kszu and @wiredfool and am feeling optimistic about the opportunity for @python-pillow/pillow-team to participate. 

As some of you may know, I received a small amount of $$$ over the course of 5 years from https://gratipay.com/ (I don't recall how much, but probably no more than a few hundred dollars per year, if that.) Since Gratipay folded (thanks again @chadwhitacre!) I've been interested in finding a replacement, and this could definitely be it.

In short, here's how it will work:

- Members of the @python-pillow/pillow-team should add a comment here indicating whether or not they'd like to participate (i.e. get paid for your contributions to Pillow!)
- Members of @python-pillow/owners will decide what percentage of Tidelift's contribution each member of the @python-pillow/pillow-team will receive (most likely an equal distribution amongst those who are interested in funding) and report percentage to @tidelift.
- Each interested member of the @python-pillow/pillow-team will sign a contract with @tidelift to facilitate payment.

So for example, if @tidelift is offering 10K over two years (which I believe they are) and @wiredfool @hugovk @radarhere @homm and myself would each get $83.33 a month.

To get started, let's first figure out which members of the current @python-pillow/pillow-team would like to participate. After that, we can discuss percentages (as I said, most likely an equal split amongst all active contributors.)

Thanks @kszu and @tidelift for the opportunity!

**Comment by aclark4life** [comment]
@python-pillow/pillow-team OK that's 3 so far, assuming @wiredfool and myself. Anyone else?

**Comment by radarhere** [comment]
Okay, sure. Thanks for organising.

**Comment by aclark4life** [comment]
And last but not least, @homm ?

**Comment by homm** [comment]
Thanks, Alex! I'm in.

**Comment by aclark4life** [comment]
@kszu OK first question, what does Tidelift do with write-ability? Just want to make sure I understand what I'm authorizing. I'd love to get going by end-of-month, but practically speaking end-of-year sounds more realistic. Thank you!!

<img width="714" alt="screen shot 2018-11-26 at 3 47 51 pm" src="https://user-images.githubusercontent.com/72164/49041357-091a3880-f193-11e8-9742-a9991eaa0f91.png">

**Comment by kszu** [comment]
Makes sense to me!

On tidelift.com there's an option to set up 'PR checks' which will set up a webhook and then set commit statuses on pull requests (failing PRs that have issues in their dependencies). We don't actually require lifters to set this up, so the write would be unused. We're in the process of porting to be a 'GitHub app' instead of using oauth, and then these permissions would go away. In the meantime it's OK to sign in with username/password instead of your GitHub if you want.

**Comment by aclark4life** [comment]
@kszu I don't see where I can create an account on https://tidelift.com, am I missing it somewhere? I'd probably prefer to skip OAuth for now if possible. Thanks

**Comment by kszu** [comment]
@aclark4life sorry for the confusion on that! If you go to https://tidelift.com/lifter/signup, you should be able to create an account with just an email and password. After going through that process myself, I can see how it's hard to find! We should make that more accessible 😄

**Comment by aclark4life** [comment]
Thanks @kszu and done!

![screenshot 2018-11-30 09 54 55](https://user-images.githubusercontent.com/72164/49296379-129eeb80-f486-11e8-9ad6-4fb2513153eb.png)

**Comment by kszu** [comment]
Awesome! It looks like @aclark4life and @hugovk have now both taken care of this. Still waiting for the rest of the team, when they have a chance. 

@aclark4life and @hugovk I can send the signable version of our agreement to both of you now, if you'd like, or I can wait until everyone is ready. Let me know what you'd like to do!

**Comment by aclark4life** [comment]
Let’s wait. @radarhere @wiredfool @homm can you sign up, sign in and lift Pillow on Tidelift based on instructions above? Thanks all

**Comment by radarhere** [comment]
Okay, done

**Comment by aclark4life** [comment]
3/5 😄

**Comment by wiredfool** [comment]
Yeah, I’m off at a cross race this morning, I’ll do it today.

**Comment by wiredfool** [comment]
I'm in now.

**Comment by kszu** [comment]
Looks like everyone has signed up now! Unless anyone has any objections, I'll plan to send the individual signable agreements to everyone's personal emails in the next 24 hours.

**Comment by aclark4life** [comment]
Sounds good, thanks @kszu

**Comment by chadwhitacre** [comment]
Best of luck @aclark4life et al.! I hope this works out for you. ☺️ ❤️

**Comment by kszu** [comment]
👋 I want to give everyone a heads up, as we'll be issuing our first payment to you all on December 28th (the final business day of the month). We're still waiting on signed agreements from @aclark4life and @wiredfool , and it looks like the agreements I sent before have expired, so I'm going to resend those to you now. 

If you're able to complete them by the 27th, we'll divide the payment evenly 5 ways as planned, otherwise we'll have to divide it 3 ways between the folks who have already signed up. Let me know if you have any problems or questions!

**Comment by aclark4life** [comment]
@kszu Sorry, I filled mine out and didn't get a chance to send yet. I'll fill out the new one and send over the weekend, Mon latest.

**Comment by aclark4life** [comment]
@kszu Done! 

@wiredfool It only takes a minute or so to e-sign FYI, so please try to get it done by the 27th if possible.

Thanks all & happy holidays 🎄 ✡️ 🍾

**Comment by wiredfool** [comment]
All done.

**Comment by radarhere** [comment]
If everyone else successfully received the first payment like I did, can this issue be closed?

**Comment by radarhere** [comment]
Just to check - Tidelift is still due to finish up at the end of this year, yes?

**Comment by aclark4life** [comment]
@radarhere As far as I know, we're going to keep going in 2021 but I'll confirm

**Comment by aclark4life** [comment]
@radarhere Still going! Via @brennaheaps
