### ISSUE TITLE
By using Image.frombytes to handle bytes from Pywin32, the bitmap becomes too bluish 

### ISSUE THREAD

**Issue by sociometry** [python-pillow/Pillow#3470]
I used python win32api to capture a screen shot of a window. By using GetBitmapBits, 
```python
rtns = saveBitMap.GetBitmapBits(True)
```
I got a string like this:
```string
b'\x97\x9d\xad\xff\x97\x9d\xae\......
```
According to the documentation:
http://timgolden.me.uk/pywin32-docs/PyCBitmap__GetBitmapBits_meth.html
```string
tuple/string = GetBitmapBits(asString)
Returns the bitmap bits.
```
So I guess I can use Image.frombytes to handle such string and crop it later(I don't want to save it), like this:
```python
bmp = Image.frombytes('RGBA', width, height, such_string)
bmp_cr = Image.crop(rect)
# bmp.save("b.bmp")
```
However, the bitmap I got was too **bluish**.
Then I saved the bitmap directly after Image.frombytes, not cropped. The bitmap was still bluish. Using Image.frombuffer was the same. I don't know why.

* OS: Win10
* Python: 3.7.0
* Pillow: 5.3.0
* pywin32: 224

Here is the source code:
```python
#!/usr/bin/env python 
# -*- coding:utf-8 -*-
from PIL import Image
import win32gui, win32ui, win32con, win32api

def window_capture(window_name):
    hwnd = win32gui.FindWindow(None, window_name)
    if not hwnd:
        print('Window not found!')
        return 0
    # using pywin32api for the screen shot
    win32gui.ShowWindow(hwnd, win32con.SW_RESTORE)
    win32gui.SetForegroundWindow(hwnd)
    hwndDC = win32gui.GetWindowDC(hwnd)
    mfcDC = win32ui.CreateDCFromHandle(hwndDC)
    saveDC = mfcDC.CreateCompatibleDC()
    saveBitMap = win32ui.CreateBitmap()
    left, top, right, bottom = win32gui.GetWindowRect(hwnd)
    if left < 0:
        return 0
    saveBitMap.CreateCompatibleBitmap(mfcDC, right - left, bottom - top)
    saveDC.SelectObject(saveBitMap)
    saveDC.BitBlt((0, 0), (right - left, bottom - top) , mfcDC, (0, 0), win32con.SRCCOPY)
    # Returns the bitmap bits
    rtns = saveBitMap.GetBitmapBits(True)
    print(rtns[:20])
    bmp = Image.frombytes('RGBA', (saveBitMap.GetInfo()['bmWidth'], saveBitMap.GetInfo()['bmHeight']), rtns)
    # using pywin32api to save, what I got was a normal bitmap
    saveBitMap.SaveBitmapFile(saveDC, "a.bmp")
    # what I got was too bluish
    bmp.save("b.bmp")
    win32gui.DeleteObject(saveBitMap.GetHandle())
    saveDC.DeleteDC()
    mfcDC.DeleteDC()
    win32gui.ReleaseDC(hwnd, hwndDC)
    return hwnd

window_capture(######  the name of a window  #######)
```

**Comment by cgohlke** [comment]
>  the bitmap I got was too bluish

That's probably because the color samples are ordered BGR instead of RGB. Try `bmp = Image.frombytes('RGB', (saveBitMap.GetInfo()['bmWidth'], saveBitMap.GetInfo()['bmHeight']), rtns, 'raw', 'BGRX')`

**Comment by sociometry** [comment]
> 
> 
> > the bitmap I got was too bluish
> 
> That's probably because the color samples are ordered BGR instead of RGB. Try `bmp = Image.frombytes('RGB', (saveBitMap.GetInfo()['bmWidth'], saveBitMap.GetInfo()['bmHeight']), rtns, 'raw', 'BGRX')`

You are right. Thanks a lot!
