### ISSUE TITLE
Img.crop won't insert last pixel row

### ISSUE THREAD

**Issue by albcunha** [python-pillow/Pillow#3475]
### What did you do?
I used image.crop to crop a image on several pieces.

### What did you expect to happen?
The bottom pixel row would be included on the triangle.

### What actually happened?
It was not included.

### What are your OS, Python and Pillow versions?

* OS: Windows 7
* Python: 3.6.4
* Pillow: 5.0

Code:

```python
def long_slice(image_path, outdir):
    """slice an image into parts slice_size tall"""
    img = Image.open(image_path)
    width, height = img.size
    tamanho_linha_imagem = 75
    pedaços = math.ceil(height / tamanho_linha_imagem) # como cada linha é 1, não precisa dividir    
    largura_tabela = width 
    upper = 0
    left = 0
    count = 1
    #slices = math.ceil(height/)
    for slice in range(pedaços):
        #if we are at the end, set the lower bound to be the bottom of the image
        if count == pedaços:
            lower = height
        else:
            lower = int(count) * tamanho_linha_imagem
        #set the bounding box! The important bit.      
        bbox = (left, upper, width, lower) 
        working_slice = img.crop(bbox)
        # addd transparent bottom padding to the last image, so the last row wont have distortion
        if slice == pedaços - 1:
            blank_image = Image.new('RGBA', (width,tamanho_linha_imagem ), color= (0,0,0,0))
            blank_image.paste(working_slice, (0,0))
            blank_image.convert('RGBA')
            working_slice = blank_image 
            
        upper += 1 * tamanho_linha_imagem
        #save the slice
        out_name = re.sub('[\W_]','',image_path)
        arquivo_saida = os.path.join(outdir, "slice" + out_name  + str(count)+".png")
        lista_arquivos.append(arquivo_saida)
        working_slice.save(arquivo_saida, quality=100)
        count +=1
    img.close()
```

The important bit is this one:
```python
bbox = (left, upper, width, lower) 
working_slice = img.crop(bbox)
```
if a set it to:
```python
bbox = (left, upper, width, lower +1)
```
it works fine!

The script where i´m using it is on this gist:
https://gist.github.com/albcunha/0d6feb6953e77b93ee3a119fb200ed34

I use it to convet any image on its folder to a libreoffice write odt file with a table inside. Each row is piece of the previous image. This way, when i copy the table to my petitions, it will automatically split the images according to the text.

Isn´t img.crop supposed to get this last pixel row?

**Comment by vashek** [comment]
Check https://pillow.readthedocs.io/en/5.3.x/handbook/concepts.html#coordinate-system please.
Basically, yes you should add 1 to the bottom (and also right!) coordinates, it works as designed I believe.

**Comment by hugovk** [comment]
Here's a small example:
```python
>>> from PIL import Image
>>> im = Image.open("hopper.jpg")
>>> im.size
(128, 128)
>>> cropped = im.crop((0, 0, 128, 128))
>>> cropped.size
(128, 128)
```

**Comment by albcunha** [comment]
I think you are right. I´ll recheck my code.
Thanks!
