### ISSUE TITLE
No alpha weighted color mixing with GaussianBlur 

### ISSUE THREAD

**Issue by kravemir** [python-pillow/Pillow#3494]
### Example of current behavior

I produced it for first time with blurred drawn text on transparent background...

But, for sake of issue description simplicity, I've prepared example with circles. For all samples below, I've used following first input in Jupyter:

```python
from PIL import Image, ImageDraw, ImageFilter
from IPython.display import display # to display images
```

First, with zero alpha black background:

```
img = Image.new("RGBA", (200, 200), (0,0,0,0))
ImageDraw.Draw(img).ellipse((20,20,180,180), fill=(255,0,0,255))
img = img.filter(ImageFilter.GaussianBlur(10))
display(img)
```

Resulting image takes black background to output:

![image](https://user-images.githubusercontent.com/1643935/49960550-b2418c80-ff10-11e8-9bd9-30511f61537f.png)

Another example is with green zero alpha background:

```
img = Image.new("RGBA", (200, 200), (0,255,0,0))
ImageDraw.Draw(img).ellipse((20,20,180,180), fill=(255,0,0,255))
img = img.filter(ImageFilter.GaussianBlur(10))
display(img)
```

![image](https://user-images.githubusercontent.com/1643935/49960503-9c33cc00-ff10-11e8-9b0d-fc35b847975f.png)

### Expected behavior

Zero alpha color doesn't get mixed into output color.

### What's wrong with current behavior?

Zero alpha color got mixed into output color.

Assuming, there's only one color in image, I can fake it by setting background color to drawn image, but that's not really possible with mixed colors within single image on same transparent background.

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: `2.7.15+ (default, Oct  2 2018, 22:12:08) `
* Pillow: `Pillow==5.3.0`

**Comment by kravemir** [comment]
Also, a green for implementation of fix would be nice.

I would take a closer look, make a fix and create a PR, when I'll have time (estimate 1 week to 10 weeks). However, I don't want to spend time (which is the most precious commodity) on contribution, which wouldn't get accepted.

**Comment by wiredfool** [comment]
I think that this is working as expected. The alpha mask and the background color are both being blurred, which is going to result in the formerly hidden color being visible.

**Comment by kravemir** [comment]
> I think that this is working as expected. The alpha mask and the background color are both being blurred, which is going to result in the formerly hidden color being visible.

@wiredfool, are you sure? Have you tried GaussianBlur in graphical editors? For example, GIMP:

![screenshot from 2018-12-15 19-11-25](https://user-images.githubusercontent.com/1643935/50046062-6112d380-009d-11e9-8da4-5a32aee9d3a7.png)

And, with white color layer turned off (no change to original image):

![screenshot from 2018-12-15 19-11-59](https://user-images.githubusercontent.com/1643935/50046063-62dc9700-009d-11e9-82da-76c49af78b2d.png)

The original blurred purple circle was made by:

1. initial image with alpha layer, empty,
2. make circle selection,
3. fill with purple,
4. select everything,
5. apply Gaussian Blur.

**Comment by kravemir** [comment]
Related theory - Alpha compositing / blending: https://en.wikipedia.org/wiki/Alpha_compositing#Alpha_blending

**Comment by wiredfool** [comment]
A gaussian blur is a kernel operation, independently applied over the n channels of the image. In this case, there is an image in three channels which is getting blurred, and an alpha channel, which is also getting blurred. 

It's possible that the effect that you're looking for is a bulr over a premultiplied alpha image (RGBa), but that will tend to force the halo color to black. You may also be looking tor a blur over just the alpha channel, as that would be softening the transparency without blending the underlying colors. You also might be looking for a blur with a mask which will only apply to the areas selected by the mask (This is not something that is currently supported/implemented, IIRC).

**Comment by kravemir** [comment]
> A gaussian blur is a kernel operation, independently applied over the n channels of the image. In this case, there is an image in three channels which is getting blurred, and an alpha channel, which is also getting blurred.

From mathematical point of view, it makes sense. From user's point of view, it's weird. However, I'm don't know whether this library is inclined towards mathematics, or towards convenience for simple users, therefore it I'm not sure whether it's a bug, or not,.. anymore.

> It's possible that the effect that you're looking for is a bulr over a premultiplied alpha image (RGBa), but that will tend to force the halo color to black. 

Yes, that's one of away ways to perform alpha blending, and it seems to be solution with better performance. I had also found it under name alpha bleed: https://stackoverflow.com/q/4854839/409102.

Is there any support for premultiplied alpha image `RGBa` in Pillow? I didn't manage to find any docs for supported image memory formats, just image file formats as jpg, png,...

**Comment by kravemir** [comment]
@wiredfool thank you for help, and it's not a bug (ie. it's possible to blur it correctly using `RGBa`).

>> A gaussian blur is a kernel operation, independently applied over the n channels of the image. In this case, there is an image in three channels which is getting blurred, and an alpha channel, which is also getting blurred.
> 
> From mathematical point of view, it makes sense. From user's point of view, it's weird. However, I don't know whether this library is inclined towards mathematics, or towards convenience for simple users, therefore I'm not sure whether it's a bug, or not,.. anymore.

I take that back, as your advice works:

>> It's possible that the effect that you're looking for is a bulr over a premultiplied alpha image (RGBa), but that will tend to force the halo color to black.

With following code:

```
img = Image.new("RGBa", (200, 200), (0,0,0,0))
ImageDraw.Draw(img).ellipse((20,20,180,180), fill=(255,0,0,255))
img = img.filter(ImageFilter.GaussianBlur(10))
display(img.convert("RGBA"))
```
