### ISSUE TITLE
pillow conda recipe

### ISSUE THREAD

**Issue by stas00** [python-pillow/Pillow#3497]
We are trying to build a pillow conda package linked against libjpeg-turbo.

Where do you I find the current conda recipe that you use for the anaconda channel?

Any reason why you don't have it in the pillow repository?

Thank you.

**Comment by stas00** [comment]
Yes, thank you, @hugovk -  I found the conda-forge recipe, but I wasn't sure whether the same one is used for the anaconda channel. Is there a way to check whether the same recipe is used for both, since ideally we would like the 'anaconda' channel now - who would I talk to about this, in case you know who is building the 'anaconda' channel `pillow'.

**Comment by hugovk** [comment]
Looks like they're different things:

* https://anaconda.org/anaconda/pillow (184,940 total downloads)
* https://anaconda.org/conda-forge/pillow (1,698,137 total downloads)

I don't know much about Anaconda/Conda, perhaps https://github.com/conda-forge/pillow-feedstock maintainer @ocefpaf can help?

**Comment by stas00** [comment]
Yes, that's why I'm asking - since it's hard to derive the recipe backwards from the final product. And source-forge libraries are not the same as anaconda's.

@ocefpaf, would you by chance know where to find the pillow conda recipe used by the anaconda channel?  Contacting anaconda customer service proved useless in the past, so I don't think it's a good idea to try. Thank you!

**Comment by ocefpaf** [comment]
> Where do you I find the current conda recipe that you use for the anaconda channel?

Community: https://github.com/conda-forge/pillow-feedstock
Official: https://github.com/AnacondaRecipes/pillow-feedstock

> Any reason why you don't have it in the pillow repository?

As @hugovk said above, there is no need for the recipe to be here b/c that would put a strain on the developer to maintain a builds system and the build system could fragment when everybody is building their own artifacts. (I would love to see a centralized build system for wheels too, it would avoid some headaches like tensorflow wheels not being compliant but still uploaded as compliant...)

> @ocefpaf, would you by chance know where to find the pillow conda recipe used by the anaconda channel?

As you will notice above the official recipe is based on the community, conda-forge, recipe. That allows for a nice workflow where the community can, in the long term, influence the default channel while still having the changes they need ASAP. (Kind of debian unstable/stable model.) 

> We are trying to build a pillow conda package linked against libjpeg-turbo.

In conda-forge we are slowly moving towards `libjpeg-turbo`. Consider joining us in that effort and send a PR upstream ;-p

**Comment by stas00** [comment]
Thank you for the detailed follow up, @ocefpaf. You answered all my questions.

> > We are trying to build a pillow conda package linked against libjpeg-turbo.
> 
> In conda-forge we are slowly moving towards `libjpeg-turbo`. Consider joining us in that effort and send a PR upstream ;-p

I don't have any PRs at the moment, but I'll share my success/failure notes:

I did the following:

I started with the conda-forge recipes.

I rebuilt the `libjpeg-turbo` conda package against the `anaconda` channel dependencies, since currently `fastai` relies on the `defaults` channel.

Then I removed tk and libtiff dependencies from the pillow recipe as they are dependent on `jpeg` (which would lead to libjpeg library conflict). To make full support of tk/libtiff, these also need to be rebuilt against libjpeg-turbo.

I then built pillow w/ libjpeg-turbo dependency.

I was able to make linux-64 py3.6 and py3.7 builds using pillow-5.4.0.dev (git master HEAD) and also pillow-simd-5.3.0.post1 against py3.6. 

py3.7 won't build pillow-5.3.0 due to: 
ModuleNotFoundError: No module named '_sysconfigdata_x86_64_conda_cos6_linux_gnu'
Unresolved issue of mixing conda-forge and main channels - toolchain conflicts:
https://github.com/conda-forge/python-feedstock/issues/220
as I said above this problem doesn't appear in the master HEAD of pillow.

My build notes are here:
https://github.com/fastai/fastai/blob/master/builds/custom-conda-builds/pillow/conda-build.txt
https://github.com/fastai/fastai/blob/master/builds/custom-conda-builds/pillow-simd/conda-build.txt

The modified recipes are here:
https://github.com/fastai/fastai/tree/master/builds/custom-conda-builds

If someone wants to try those packages, the notes are here:
https://docs.fast.ai/performance.html#conda-packages

**Comment by ocefpaf** [comment]
> Thank you for the detailed follow up, @ocefpaf. You answered all my questions.

Thanks for the feedback. Let's move this discussion to the pillow feedstock in conda-forge b/c it is not really a topic for the upstream source code :-)
