### ISSUE TITLE
Gaps in ImageDraw arc

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#3499]
The following code is based on 'test_arc_width' - https://github.com/python-pillow/Pillow/blob/master/Tests/test_imagedraw.py#L105. It generates https://github.com/python-pillow/Pillow/blob/master/Tests/images/imagedraw_arc_width.png first, just for comparison, and then generates the attached image, which has gaps in the fill.

OS: macOS 10.14
Python: 3.7.1
Pillow: 5.3.0

```python
from PIL import Image, ImageDraw

def drawArc(W, H, width, path):
	# Bounding box points
	X0 = int(W / 4)
	X1 = int(X0 * 3)
	Y0 = int(H / 4)
	Y1 = int(X0 * 3)

	# Two kinds of bounding box
	BBOX1 = [(X0, Y0), (X1, Y1)]

	im = Image.new("RGB", (W, H))
	draw = ImageDraw.Draw(im)
	draw.arc(BBOX1, 10, 260, width=width)
	im.save(path)

# Existing test
drawArc(100, 100, 5, 'imagedraw_arc_width.png')

# Problem image
drawArc(500, 500, 50, 'problem.png')
```

![problem](https://user-images.githubusercontent.com/3112309/50118585-321a7e80-02a4-11e9-9024-d9387a8c4317.png)

**Comment by DevilXD** [comment]
Just ran into the same issue. The width option seems to be undocumented too.

**Comment by radarhere** [comment]
@DevilXD `width` should be documented at https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.arc

**Comment by DevilXD** [comment]
Huh, not sure what docs I was looking at then... But yeah, I'm getting the same issue.
Found out this issue can be semi-repeated by drawing arcs in a for loop, shrinking the bounding box by one each time. Seems like this exact thing is happening internally when you use width.
