### ISSUE TITLE
1 bit images to 1 bit nd arrays

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#350]
The conversion of 1 bit images to an ndarray is listed as broken in test_numpy.py, Image.py lines 217 and 1931.

**Comment by pv** [comment]
Ping; this is causing crashes for people.

**Comment by aclark4life** [comment]
@pv Can you elaborate?

**Comment by pv** [comment]
cf https://github.com/scipy/scipy/issues/5285, https://github.com/numpy/numpy/issues/5861 for repro

**Comment by matthew-brett** [comment]
Another ping about this one - it's still causing confusing segfaults for numpy users - see e.g. numpy/numpy#7877
