### ISSUE TITLE
Incorrect description of Image.convert() function

### ISSUE THREAD

**Issue by VasuDeoSankrityayan** [python-pillow/Pillow#3510]
### What did you do?

Went to Image Module in official pillow documentation  :- https://pillow.readthedocs.io/en/5.3.x/reference/Image.html

And was looking through the Image.convert() function

### What is stated

When translating a color image to black and white (mode “L”), the library uses the ITU-R 601-2 luma transform:

                                   L = R * 299/1000 + G * 587/1000 + B * 114/1000

### What is supposed to be stated:-

When translating a color image to Greyscale (mode “L”), the library uses the ITU-R 601-2 luma transform:

                                  L = R * 299/1000 + G * 587/1000 + B * 114/1000

### Explaination:-

Luma transform takes in RGB input and convert it into a 0 - 255 range single channel output (Greyscale)
given that the values of RGB are in range of 0 - 255.

So according to the luma transform, we will get a result in a range 0-255, but a black and white image could only have 2 discrete pixel values, namely black ( 0 ) or white ( 1 ). 

This states that the above formula provided does not result into a black and white image, but rather in a greyscale image. Even the mode stated inside the parenthesis is for greyscale conversion. 

### Suggestion

An edit on the corresponding lines of the convert function description

### Screenshot of the description :-

![incorrectinfo](https://user-images.githubusercontent.com/46196312/50486769-8f4aba00-099f-11e9-85e9-a920bb727905.png)

**Comment by radarhere** [comment]
Thanks. I have created PR #3511 to resolve this.

**Comment by VasuDeoSankrityayan** [comment]
I didn't received any updates. Are the changes i mentioned gonna get finalized ?

I an new to github so i am not familiar with how things work over here.

**Comment by radarhere** [comment]
Hi. So I suggested a change in https://github.com/python-pillow/Pillow/pull/3511 - changing 'black and white' to 'greyscale'. This change has been accepted, meaning that it is now a part of Pillow, and will be present in any future releases of Pillow.

When you go to https://pillow.readthedocs.io, you will notice that it redirects to https://pillow.readthedocs.io/en/5.3.x/ - 5.3.x refers to version 5.3.0 of Pillow (and any 5.3.1, 5.3.2, etc. that might have existed).

[Pillow 5.3.0 was released on the 1st of October](https://github.com/python-pillow/Pillow/releases), before the change, and so does not have it. Pillow 5.4.0 will have your change. So once 5.4.0 is out [on the 1st of January](https://github.com/python-pillow/Pillow/blob/master/RELEASING.md), https://pillow.readthedocs.io will redirect to https://pillow.readthedocs.io/en/5.4.x/ and you will see the change in the documentation.

**Comment by VasuDeoSankrityayan** [comment]
Thanks for Replying

**Comment by radarhere** [comment]
Okay, the next version of Pillow has been released, https://pillow.readthedocs.io/ redirects to https://pillow.readthedocs.io/en/5.4.x/ and the updated documentation can be seen at https://pillow.readthedocs.io/en/5.4.x/reference/Image.html#PIL.Image.Image.convert
