### ISSUE TITLE
Release Pillow 5.4.1

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3535]
Follow on from 5.4.0 (#3391).

TODO:

* Fix PNG MIME type regression: https://github.com/python-pillow/Pillow/pull/3501#issuecomment-450764968 / PR https://github.com/python-pillow/Pillow/pull/3525 (cherry pick just the PNG fix)
  * [x] Merge to master
  * [x] Cherry picked
* Fix Termux regression: https://github.com/python-pillow/Pillow/issues/3526 / PR: https://github.com/python-pillow/Pillow/pull/3529
  * [x] Merge to master
  * [x] Cherry picked
* Fix PNG "IDAT chunks after image end" regression: #3527 / PR #3532
  * [x] Merge to master
  * [x] Cherry picked
* Fix file closing regression: https://github.com/python-pillow/Pillow/issues/3536 / PR #3540
  * [x] Merge to master
  * [x] Cherry picked
* Release notes: PRs https://github.com/python-pillow/Pillow/pull/3544 & https://github.com/python-pillow/Pillow/pull/3553
  * [x] Merge to master
  * [x] Cherry picked

## Point Release

Released as needed for security, installation or critical bug fixes.

* [x] Make necessary changes in ``master`` branch.
* [x] Update `CHANGES.rst`.
* [x] Cherry pick individual commits from ``master`` branch to release branch e.g. ``5.4.x``.
* [x] Check [Travis CI](https://travis-ci.org/python-pillow/Pillow) to confirm passing tests in release branch e.g. ``5.4.x``.
* [x] Check out release branch e.g.:
```
    git checkout -t remotes/origin/5.4.x
```
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Run pre-release check via `make release-test`.
* [x] Create tag for release e.g.:
```
    $ git tag 5.4.1
    $ git push --tags
```
* [x] Create source distributions e.g.:
```
    $ make sdist
```
* [x] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#binary-distributions)
* [x] Create a [new release on GitHub](https://github.com/python-pillow/Pillow/releases/new)

### Windows
* [x] Contact `@cgohlke` for Windows binaries via release ticket e.g. https://github.com/python-pillow/Pillow/issues/1174.
* [x] Download and extract tarball from `@cgohlke` and ``twine upload *``.

### Mac and Linux
* [x] Use the [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels):
```
    $ git clone https://github.com/python-pillow/pillow-wheels
    $ cd pillow-wheels
    $ git submodule init
    $ git submodule update Pillow
    $ cd Pillow
    $ git fetch --all
    $ git checkout [[release tag]]
    $ cd ..
    $ git commit -m "Pillow -> 5.4.1" Pillow
    $ git push
```
* [x] Download distributions from the [Pillow Wheel Builder container](http://a365fff413fe338398b6-1c8a9b3114517dc5fe17b7c3f8c63a43.r19.cf2.rackcdn.com/).

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the default version for Read the Docs is the latest tagged release e.g. ``d2d43879`` (5.4.1)

**Comment by hugovk** [comment]
Thoughts on including the PNG "IDAT chunks after image end" regression?

https://github.com/python-pillow/Pillow/issues/3527 / PR https://github.com/python-pillow/Pillow/pull/3532

**Comment by aclark4life** [comment]
@wiredfool ^^^ ?

**Comment by wiredfool** [comment]
Yeah, it's a regression. It's been reported, we have a fix, we're doing the release. Put it in.

**Comment by hugovk** [comment]
Added to the list. I'll do the release this weekend.

**Comment by radarhere** [comment]
#3540? In #3536, an `OSError: cannot identify image file` became `ValueError: seek of closed file` in 5.4.0.

**Comment by hugovk** [comment]
> #3540? In #3536, an `OSError: cannot identify image file` became `ValueError: seek of closed file` in 5.4.0.

If there's no objections by tomorrow, let's include it. Please could you update the 5.4.1 release notes?

**Comment by hugovk** [comment]
A question about the [release checklist for point releases](https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#point-release
):

> ...
> * [ ] Cherry pick individual commits from ``master`` branch to release branch e.g. ``5.2.x``.
> * [ ] Check [Travis CI](https://travis-ci.org/python-pillow/Pillow) to confirm passing tests in release branch e.g. ``5.2.x``.
> * [ ] Check out release branch e.g.:
> ```
>     git checkout -t remotes/origin/5.2.x
> ```
> * [ ] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
>
> ...

Presumably that `git checkout -t remotes/origin/5.2.x` should really come before the cherry picks?

**Comment by aclark4life** [comment]
@hugovk Sounds about right. I don't think you can specify a target branch when cherry-picking …

**Comment by hugovk** [comment]
@cgohlke Please could we have Windows binaries for 5.4.1?

**Comment by cgohlke** [comment]
[Here you go](https://www.lfd.uci.edu/~gohlke/download/Pillow-5.4.1-win-dist.zip).

**Comment by hugovk** [comment]
@cgohlke Thanks!

---

5.4.1 is all uploaded and released, bar Twitter and Read the Docs.

RTD has got jammed again... I've started a manual build of stable.

![image](https://user-images.githubusercontent.com/1324225/50740197-881f7980-11f3-11e9-84bd-03a0e6bbd690.png)

**Comment by hugovk** [comment]
The RTD build completed, but it's not showing up yet.

https://pillow.readthedocs.io/ redirects to stable:

* https://pillow.readthedocs.io/en/stable/releasenotes/index.html

https://readthedocs.org/projects/pillow/versions/ shows the same commit f38f01bb for stable and 5.4.1:

![image](https://user-images.githubusercontent.com/1324225/50740281-df721980-11f4-11e9-87e8-f5e5fefe3bae.png)

But 5.4.1 isn't showing here:

* https://pillow.readthedocs.io/en/stable/releasenotes/index.html

**Comment by radarhere** [comment]
5.4.1 is now showing at https://pillow.readthedocs.io/en/stable/releasenotes/index.html

**Comment by hugovk** [comment]
RTD seems to have sorted itself out.

* https://pillow.readthedocs.io/en/stable/releasenotes/5.4.1.html

So, all done!

* https://twitter.com/PythonPillow/status/1082025834947448837
