### ISSUE TITLE
Let's use Tidelift's Security Process

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#3543]
https://tidelift.com/docs/lifting/security-process

**Comment by aclark4life** [comment]
If nothing else, I'd prefer to rely on their domain vs python-pillow.org domain…

**Comment by hugovk** [comment]
Please see PR https://github.com/python-pillow/Pillow/pull/3702.

**Comment by radarhere** [comment]
On https://tidelift.com/lifter/pypi/Pillow/tasks/2614, it asks who should be emailed when a report is received.

![screen shot 2019-03-08 at 9 40 16 am](https://user-images.githubusercontent.com/3112309/53994352-3d37c900-4186-11e9-8429-2849536b09f5.png)

Should we just enter security@python-pillow.org, or is there another suggestion?

**Comment by aclark4life** [comment]
@radarhere Yes, let's keep that address. It currently forwards to @wiredfool and myself, but we can and probably should add the entire team.

**Comment by radarhere** [comment]
Okay. So is this issue resolved then?
