### ISSUE TITLE
Burmese fonts are not rendered/interpreted in correct order

### ISSUE THREAD

**Issue by HtutLynn** [python-pillow/Pillow#3548]
What did you do?

I am trying to print Burmese characters(Myanmar3.ttf) on images for data generation for OCR. Unlike other languages, in Burmese language, word/character is constructed using syllables and there is order in syllables. Therefore, unicode for Burmese language uses complex ordering. When I print the characters on image, the syllables doesn't combine together to form a word.
Here's some reference to Burmese language:
http://www.unicode.org/cldr/charts/30/collation/my.html

Here is my Code: 

```
from PIL import Image
from PIL import ImageFont
from PIL import ImageDraw

img = Image.open("BG.png")
draw = ImageDraw.Draw(img)
unicode_font = ImageFont.truetype("Myanmar3.ttf", 13)
draw.text((0, 0), u"ကြည့်ရှုခွင့်ရသူ", (0, 0, 0), font = unicode_font)
img.save("sample1.png")
```

The way it should appear:
![screenshot 54](https://user-images.githubusercontent.com/42746452/50726989-112aa800-1143-11e9-9099-c404e96323a5.png)

The way it shouldn't appear:
![sample1](https://user-images.githubusercontent.com/42746452/50727124-a5e1d580-1144-11e9-81cf-56f8e310c133.png)

**Comment by radarhere** [comment]
What operating system are you using? What version of Pillow?

**Comment by HtutLynn** [comment]
WIndows 10 Prof and latest Pillow. Pillow doesn't support for complex text layout but thankfully, Libraqm solved the problem.
