### ISSUE TITLE
It looks like Pillow changed pic's metadata a little after Image.open and Image.save

### ISSUE THREAD

**Issue by cloud-yu** [python-pillow/Pillow#3564]
when I use tesseract-ocr for image recognition, I got two different results.
Example:
  I got a pic named captcha.jpg. it looks like this
 ![captcha](https://user-images.githubusercontent.com/8436078/50951699-198b3600-14e9-11e9-8758-319cf7a2bf66.jpg)

1. run tesseract-ocr with this pic，i got a result  **69231**
> command:  tesseract.exe captcha.jpg stdout --psm 13
2. PILLOW load the pic then saved as another name
> from Pillow import Image
> image = Image.open(r'captcha.jpg')
> image = Image.save(r'captcah1.jpg')
3. run tesseract-ocr with this new pic, i got another result **6921**
> command: tesseract.ext captcha1.jpg stdout --psm 13

so here comes the question , what happened?
I've tried many times , it's goes the same. 

when I execute tesseract.exe with captcha.jpg , i always got the same result --- 69321
and got 6921 when execute with captcha1.jpg

Is there a possibility that pillow has changed some metadata of pic?

### What are your OS, Python and Pillow versions?

* OS:  Windows
* Python:  python 3.6.6
* Pillow:  5.3.0

**Comment by radarhere** [comment]
It is entirely possible that the metadata is not resaved exactly. For example, when I resave your image using Pillow, I find that the JFIF Version goes from 1.0.2 to 1.0.1. We would aim to not lose any information however, and if you can find any specific failure of Pillow, that would be something to point out.

When I run `tessearct` on my local machine with your image and a version of your image resaved using Pillow, I get the same output - 6931.

It is also worth noting that, with regards to the image data itself, https://github.com/python-pillow/Pillow/issues/3015#issuecomment-368218971

> JPEG is a lossy compression method, so there are going to be differences when saved. If you want lossless compression where all the pixels are the same, use something like PNG, or some other lossless format.

If you are still interested in JPEGs though, you may want to use the [`quality` argument](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg) - by default it is 75, but it can be set to 100 - `im.save('test.jpg', quality=100)`.

**Comment by cloud-yu** [comment]
Maybe that's the point.
I'm just a little confused why does this affect the result of OCR ，maybe that would be another question with the OCR algorithm .
Thanks.
