### ISSUE TITLE
Save as PDF with resolution/dpi float dpi result

### ISSUE THREAD

**Issue by Fabian1337** [python-pillow/Pillow#3565]
### What did you do?
Saved the PDF with `resolution=300`
`img.save(outpath + "/" + "test.pdf", resolution=300)`

### What did you expect to happen?
PDF with 300 resolution...
If you save with ".jpg" as extension the resolution will be 300 integer

### What actually happened?
PDF with 300.235 resolution ...
Photoshop CC 2019
![grafik](https://user-images.githubusercontent.com/5721838/50969565-37ec3400-14df-11e9-8344-0a961decb689.png)

Also shown in Adobe Acrobat DC
![grafik](https://user-images.githubusercontent.com/5721838/51019607-c7dfbb80-157b-11e9-9642-1e1e20f4f48f.png)
How to get resolution in Adobe Acrobat DC
Tools > Print Production/ Output Preview > Preview: Object Inspector >Click on image

### What are your OS, Python and Pillow versions?

* OS: 
Windows 10
* Python: 
3.5.2
* Pillow: 
5.4.1

**Comment by radarhere** [comment]
What application is that a screenshot from?

**Comment by Fabian1337** [comment]
> 
> 
> What application is that a screenshot from?

Photoshop CC
I think more common would be Adobe Acrobat CC also shown in edited post.

**Comment by radarhere** [comment]
Pillow uses `resolution` to set the MediaBox and "stream" of the "obj" dimensions as `int(width * 72.0 / resolution)` (and correspondingly for height). This rounding to `int` has been present since PIL.

So that makes sense as an explanation for why the value might be changed when saving.

**Comment by radarhere** [comment]
This at least doesn't need to be the case for the MediaBox - at https://books.google.com.au/books?id=JJN_BAAAQBAJ&pg=PA102#v=onepage&q&f=false, I see a MediaBox with float values, and I'm also able to using GIMP to export a PDF with float values in a MediaBox.

**Comment by radarhere** [comment]
I've created #5459 to remove the rounding.
