### ISSUE TITLE
Continuous smooth drawing

### ISSUE THREAD

**Issue by Huluti** [python-pillow/Pillow#3567]
I'm the co-developer of [ImEditor](https://github.com/ImEditor/ImEditor), a little image editor in Python and Gtk3. Our main image library is Pillow (so thank you for your work).
We want to improve our drawing feature. Currently, we are drawing a point (an ellipse or a square) following the mouse cursor. The mouse goes faster than the code... Here's the result:

![image](https://user-images.githubusercontent.com/5782198/50994039-74d61c00-151b-11e9-9e1a-7fbba005823a.png)

So I'm trying to join the last point with the newer to get a continuous line but here's the result:

![image](https://user-images.githubusercontent.com/5782198/50994461-97b50000-151c-11e9-8dce-4a5b1b668949.png)

It's better but needs some smoothing. Do you know if Pillow permits to draw nicer lines between many coordinates ?

* OS: Ubuntu 18.10
* Python: 3.6
* Pillow: 5.4.1

**Comment by matkoniecz** [comment]
>  I'm trying to join the last point with the newer to get a continuous line

Can you attach reproducible sample with code that you used?

**Comment by Huluti** [comment]
Of course!

Here's the drawing functions (editor/draw.py):

```python
#!/usr/bin/env python3

from PIL import ImageDraw

def draw_shape(img, coords, size):
    """Prepare the draw object"""
    draw = ImageDraw.Draw(img)
    if size > 0:
        size /= 2
    x = [coords[0][0] - size, coords[0][1] - size]
    y = [coords[1][0] + size, coords[1][1] + size]
    return draw, x + y

def draw_rectangle(img, coords, size, fill_color=None, outline_color=None):
    """Draw a rectangle on an image"""
    draw, xy = draw_shape(img, coords, size)
    draw.rectangle(xy, fill=fill_color, outline=outline_color)
    return xy

def draw_ellipse(img, coords, size, fill_color=None, outline_color=None):
    """Draw an ellipse on an image"""
    draw, xy = draw_shape(img, coords, size)
    draw.ellipse(xy, fill=fill_color, outline=outline_color)
    return xy

def draw_line(img, coords, size, fill_color=None):
    """Draw a line on an image"""
    draw, xy = draw_shape(img, coords, size)
    draw.line(xy, fill=fill_color, width=size)`
```
And here's the code that handle the move (editor/editor.py)::

```python
def move_task(self, img, mouse_coords):
# others remove code for lisibility
elif self.task == 2:
    coords = ((mouse_coords[0], mouse_coords[1]),
        (mouse_coords[0], mouse_coords[1]))
    if self.pencil_shape == 'ellipse':
        new_coords = draw_ellipse(img, coords, self.pencil_size, self.pencil_color)
    elif self.pencil_shape == 'square':
        new_coords = draw_rectangle(img, coords, self.pencil_size, self.pencil_color)

    # Draw a line between the last and the newer points
    # Continuous drawing
    if mouse_coords != self.last_drawn_point:
        coords2 = (self.last_drawn_point, new_coords)
        draw_line(img, coords2, self.pencil_size, self.pencil_color)

    self.last_drawn_point = mouse_coords
    self.do_tmp_change(img)
```

The move_task function is called at each mouse movement and is connected to a Gtk.EventBox.

**Comment by radarhere** [comment]
I think that as far as the current functionality of Pillow is concerned, the key element not mentioned here already is the `arc` function - https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.arc

**Comment by Huluti** [comment]
@radarhere Thank's for your answer. I'll take a look at this.

**Comment by Rousan99** [comment]
Can you tell me how can I draw a continuous boundary of a image??..like suppoze I want to make my face from a continuous curve...can I make it from this code?

**Comment by Huluti** [comment]
I'm closing this issue for now to not burden your issues.
