### ISSUE TITLE
Travis has been disabled

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#3589]
If you visit https://travis-ci.org/python-pillow/Pillow, there is a message that 'This is not an active repository'.

![travis](https://user-images.githubusercontent.com/3112309/51345220-8bb5d900-1aee-11e9-92ac-8d3b2c1ba61e.png)

**Comment by hugovk** [comment]
I don't have permission to re-enable it.

@aclark4life Please could you check it?

**Comment by aclark4life** [comment]
Done!

**Comment by radarhere** [comment]
Thanks
