### ISSUE TITLE
Pillow RTD project webhook needs to be updated

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#3590]
FYI, from RTD:

---

Hello!
Your project, Pillow, is currently using GitHub Services to trigger builds on Read the Docs. Effective January 31, 2019, GitHub will no longer process requests using the Services feature, and so Read the Docs will not receive notifications on updates to your repository.To continue building your Read the Docs project on changes to your repository, you will need to add a new webhook on your GitHub repository. You can either connect your GitHub account and configure a GitHub webhook integration, or you can add a generic webhook integration.You can find more information on our webhook intergrations in our documentation, at:https://docs.readthedocs.io/en/latest/webhooks.html#webhook-github-services
Keep documenting,Read the Docs

**Comment by hugovk** [comment]
As promised, there's not been any RTD builds for a few weeks:

https://readthedocs.org/projects/pillow/builds/

@aclark4life I don't have access to this repo's settings, please could you set it up like this? https://docs.readthedocs.io/en/latest/webhooks.html#webhook-integration-github

**Comment by aclark4life** [comment]
@hugovk Done! Thanks

<img width="1920" alt="screenshot 2019-02-21 10 34 15" src="https://user-images.githubusercontent.com/72164/53180759-48a2c600-35c4-11e9-832e-8b79ce7b3cc6.png">

**Comment by hugovk** [comment]
Thanks, I just merged something and RTD built:

![image](https://user-images.githubusercontent.com/1324225/53184783-54af7780-3606-11e9-884b-dc20c7bf53c8.png)
