### ISSUE TITLE
js/script.js is missing in the source tarball

### ISSUE THREAD

**Issue by doko42** [python-pillow/Pillow#3592]
js/script.js is missing in the 5.4.1 source tarball. Apparently it was added in 5.4.x.  It's needed for the built documentation.

**Comment by radarhere** [comment]
The script was added to 'docs/_static' in #3476. However, [`prune docs/_static` was added to the manifest](https://github.com/python-pillow/Pillow/blob/8e4d547195e76da2005284e546cacb8b8172d3f0/MANIFEST.in#L17) in #1656

@wiredfool what was your thinking behind pruning docs/_static?

**Comment by wiredfool** [comment]
Pretty sure that's because the contents were generated from the doc build.

**Comment by radarhere** [comment]
I've created PR #3595 to address this.
