### ISSUE TITLE
ImageDraw support for Bangla language

### ISSUE THREAD

**Issue by menon92** [python-pillow/Pillow#3593]
I am trying to convert [Bangla](https://en.wikipedia.org/wiki/Bengali_language) text to Image using PIL ImageDraw method. To do this is use following code, 
```
from PIL import ImageFont, Image, ImageDraw, ImageChops, ImageOps

w, h = 64, 64
w0, h0 = 256, 256
blank = Image.new('L', (w0 * 5, h0 * 3), 255)
font = '/path/to/font/Siyamrupali.ttf'
font = ImageFont.truetype(font, 20)  
char = 'দৃষ্টিভঙ্গি'
img = Image.new("L", (w0 * 5, h0 * 3), 255) 
draw = ImageDraw.Draw(img)
draw.text((w0, h0), char, font=font)
diff = ImageChops.difference(img, blank)
lx, ly, hx, hy = diff.getbbox()
img = img.crop((lx, ly, hx, hy))
img.save('image' + '.png')
```
It should convert text `দৃষ্টিভঙ্গি` to `.png` file. It does 

But  the image is broken like below
![image](https://user-images.githubusercontent.com/11752205/51385490-a4071180-1b49-11e9-9a8e-bc60f6eff959.png)

### My OS, Python and Pillow versions
* OS: Ubuntu 14.04 LTS
* Python: 3.6.3
* Pillow: 4.2.1

**Comment by radarhere** [comment]
If I mention that [complex text rendering](https://pillow.readthedocs.io/en/stable/releasenotes/4.2.0.html#added-complex-text-rendering) can be used through setting the [ImageFont.truetype layout_engine argument](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype) to raqm, is that new and helpful information?

**Comment by menon92** [comment]
@radarhere 
I replace line
`font = ImageFont.truetype(font, 20)`
by
`font = ImageFont.truetype(font=font, size=20, layout_engine=ImageFont.LAYOUT_RAQM) ` 

still It generate same broken image

**Comment by radarhere** [comment]
Okay. Loading up a VM instance of Ubuntu 14.04, I tried your script, and it didn't work.
I installed libharfbuzz-dev and libfribidi-dev, re-installed Pillow, and it didn't work.
I then ran [depends/install_raqm.sh](https://github.com/python-pillow/Pillow/blob/master/depends/install_raqm.sh), re-installed Pillow, and without requiring the `layout_engine=ImageFont.LAYOUT_RAQM` option, it worked.

So I expect if you try some combination of that, you should find a solution.

**Comment by menon92** [comment]
@radarhere 
I install libharfbuzz-dev and libfribidi-dev by
```
sudo apt-get install libharfbuzz-dev libfribidi-dev
```
then I create a virtual environment using `conda create -n env-name` then I clone https://github.com/python-pillow/Pillow/ after that I go to ` depends/install_raqm.sh` and run, 
```
sudo bash install_raqm.sh
```
and this command execute without any error. after that I run my script but it give the same result

**Comment by radarhere** [comment]
Excellent.

**Comment by rakeshvar** [comment]
The following worked for me on Ubuntu 18.04 with Python3.6.7:

0. `sudo pip3 install Pillow` -> installs `5.4.1`
1. `sudo apt-get install libfreetype6-dev libharfbuzz-dev libfribidi-dev gtk-doc-tools`
2. Install `libraqm` as described here (using `configure`, `make`, `make install`)
3. `sudo ldconfig` **This step was needed!** 
4. Run the following test script: (Make sure the fonts are installed `sudo apt install fonts-indic`)
```py
from PIL import Image, ImageFont, ImageDraw

im = Image.new("RGB",(160, 160))
draw = ImageDraw.Draw(im)

font_telugu = ImageFont.truetype("/usr/share/fonts/truetype/fonts-telu-extra/Pothana2000.ttf",50)
text_telugu = "నిత్య"

font_hindi = ImageFont.truetype("/usr/share/fonts/truetype/Gargi/Gargi.ttf",50)
text_hindi = "नित्य"

draw.text((10, 10), text_telugu, font=font_telugu)
draw.text((10, 90), text_hindi, font=font_hindi)
im.show()
```

**Comment by saiful79** [comment]
I install pillow ==5.4.1 version but it does not save Bangla font  to image properly. it broken still now.
It is the same problem like menon92.

**Comment by nazmul284** [comment]
@menon92  Did you find any solution for this problem? I am facing the same problem. If find any solution please help me. Thank you.

**Comment by zarif25** [comment]
how do i fix it for windows?

**Comment by radarhere** [comment]
Regarding the question from @nazmul284, @menon92 liked [this comment](https://github.com/python-pillow/Pillow/issues/3593#issuecomment-455725034), so I presume that worked for them.

@zarif25 I suggest installing raqm. https://stackoverflow.com/questions/62939101/how-to-install-pre-built-pillow-wheel-with-libraqm-dlls-on-windows might interest you.

**Comment by debdip** [comment]
I found a workaround for windows 10 (64 bit).


As followed this [answer](https://stackoverflow.com/a/75918197/3505172), I put both libraqm.dll and fribidi-0.dll (found in x64 folder and downloaded from [pillow_website](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow) ) in python.exe folder 
and added to the PATH variable. 

After that it worked for me.
