### ISSUE TITLE
Drawing a Font Awesome Icon results in an empty image

### ISSUE THREAD

**Issue by M4GNV5** [python-pillow/Pillow#3601]
### What did you do?
I'm trying to render a fontawesome icon to an image

### What did you expect to happen?
The icon to appear on the image

### What actually happened?
A completely blank (white) image. Printing `draw.textsize` gives a width of zero: `(0, 53)`
### What are your OS, Python and Pillow versions?

* OS: Debian GNU/Linux 9.6 (stretch)
* Python: 2.7.13
* Pillow: 5.4.1 (from pip)

### Code

```python
from PIL import ImageFont, ImageDraw, Image

img = Image.new("L", (400, 400), 255)
draw = ImageDraw.Draw(img)

fontAwesome = ImageFont.truetype("fontawesome-regular.ttf", 60)

text = unichr(0xf207)
print draw.textsize(text, fontAwesome)
draw.text((100, 100), text, 0, fontAwesome)

img.save("output.png")
```

### Text Output
```
(0, 53)
```

### Image Output

![output](https://user-images.githubusercontent.com/5504713/51541469-2a2c9c00-1e59-11e9-9666-9de055178c3d.png)

(output.png above, its completely white though)

### Additional Information

[Bus icon on Font Awesome](https://fontawesome.com/icons/bus?style=solid), Unicode `0xf207`

**Comment by radarhere** [comment]
This works for me on macOS 10.14. In the interest of responding to your problem as quickly as issue, have you tried [installing raqm](https://pillow.readthedocs.io/en/stable/releasenotes/4.2.0.html#added-complex-text-rendering)?

**Comment by hugovk** [comment]
Using this [fontawesome-regular.ttf](https://github.com/gabrielelana/awesome-terminal-fonts/blob/master/fonts/fontawesome-regular.ttf) and no RAQM, also works for me with:

OS | Python | Pillow
-- | -- | --
macOS 10.13.6 High Sierra | 2.7.15 | 5.4.1
Ubuntu 16.04.2 Xenial | 2.7.15 | 4.3.1
Ubuntu 16.04.2 Xenial | 2.7.15 | 5.4.1
Ubuntu 16.04.2 Xenial | 3.5.2 | 5.4.1

![output](https://user-images.githubusercontent.com/1324225/51601940-5c4c0580-1f0e-11e9-86cf-3d0eb3ca119b.png)

**Comment by M4GNV5** [comment]
`libraqm` is not available in Debian 9 [see here](https://packages.debian.org/search?suite=all&searchon=names&keywords=libraqm). So I can now either manually install `libraqm` or wait for Debian 10 to be released sometime this summer.
Thanks for the quick responses!
