### ISSUE TITLE
Option to disable gif delta frame optimizations

### ISSUE THREAD

**Issue by FelixWolf** [python-pillow/Pillow#3603]
I feel it would be nice/useful to have the option to disable delta frame (allowing full frame redraw). Delta Frame can cause issues with specific types of animations.
A case example would be a animation which uses transparency. It will need to overwrite pixels that are no longer used, but delta frames *will* crop out these pixels resulting in a broken animation, leaving the programmer with one of two types of images:
1. A animation with random cropping(Notice the feet/head): https://i.imgur.com/xnh6Lq5.gif
2. A animation with ghosting: https://i.imgur.com/uCekDte.gif

Example of a implementation:
[GifImagePlugin.py.diff.txt](https://github.com/python-pillow/Pillow/files/2789326/GifImagePlugin.py.diff.txt) (Had to save it as a .txt because for some reason Github doesn't allow diff of all file types to reject)
Attached diff is messy, could be optimized (doesn't disable cropping code), and the name probably could be less long.

--
Edit: This might actually be a bug?
Turns out the issue only seems to occur if the background transparency data in a png contains color information and isn't empty/same color.

**Comment by hugovk** [comment]
The diff:
```diff
420a421
>     no_frame_optimization = im.encoderinfo.get("no_frame_optimization", im.info.get("no_frame_optimization"))
443,447c444,445
<                 previous = im_frames[-1]
<                 if _get_palette_bytes(im_frame) == \
<                    _get_palette_bytes(previous['im']):
<                     delta = ImageChops.subtract_modulo(im_frame,
<                                                        previous['im'])
---
>                 if no_frame_optimization:
>                     bbox = im_frame.getbbox()
449,457c447,461
<                     delta = ImageChops.subtract_modulo(
<                         im_frame.convert('RGB'), previous['im'].convert('RGB'))
<                 bbox = delta.getbbox()
<                 if not bbox:
<                     # This frame is identical to the previous frame
<                     if duration:
<                         previous['encoderinfo']['duration'] += \
<                             encoderinfo['duration']
<                     continue
---
>                     previous = im_frames[-1]
>                     if _get_palette_bytes(im_frame) == \
>                     _get_palette_bytes(previous['im']):
>                         delta = ImageChops.subtract_modulo(im_frame,
>                                                         previous['im'])
>                     else:
>                         delta = ImageChops.subtract_modulo(
>                             im_frame.convert('RGB'), previous['im'].convert('RGB'))
>                     bbox = delta.getbbox()
>                     if not bbox:
>                         # This frame is identical to the previous frame
>                         if duration:
>                             previous['encoderinfo']['duration'] += \
>                                 encoderinfo['duration']
>                         continue
```

**Comment by radarhere** [comment]
Could you provide
- an image that is an example of this, before it is saved incorrectly by Pillow?
- code that uses Pillow to produce the two incorrect outputs that you mention?

**Comment by FelixWolf** [comment]
[pilbug-3603.tar.gz](https://github.com/python-pillow/Pillow/files/2791976/pilbug-3603.tar.gz)

I've attached sprite data and 4 scripts. Two which will produce desired outputs(using a work around of background colour normalizing) and two which produce undesired outputs(using no background normalizing).

**Comment by Artheau** [comment]
The fix is described in #3665

**Comment by radarhere** [comment]
The first gif now produces correct output with disposal 2, but the second has an unexpected green box.

**Comment by radarhere** [comment]
For the second, your input images have two different transparent colours. They were being translated to two different palette indexes, and GIF can only use one as transparency. I've created #5282 to resolve this, by setting all fully transparent pixels to the same color.

**Comment by radarhere** [comment]
#5282 has been merged, solving the second part.
