### ISSUE TITLE
CI Review

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#3606]
With the news that travis has been acquired, I've seen a bunch of discussion about CI platforms, leading to some questions:

* Is the current CI system covering what we need it to do now?
* Is it working with our long term goals?

One of the goals that I had originally with Appveyor was to be able to produce our windows binaries off of a CI system, rather than bothering @cgohlke for them every single time, as he's a single point of failure for the entire windows python ecosystem.   I'm not sure where we are on the windows testing WRT external dependency completeness or python version coverage.  Azure pipelines has now introduced free build time for open source projects, and I believe that the python core is now on that for their packages. I believe that they also do linux builds, but not macos. It may be worth investigating if their environment is any easier to get all the dependencies to build.

**Comment by hugovk** [comment]
It's definitely worth looking into. Building Windows binaries would definitely be great.

More info from GitHub: https://github.blog/2018-09-10-azure-pipelines-now-available-in-github-marketplace/

I've seen a few other projects move over to Azure Pipelines, but haven't looked into it much. It can do Linux, Windows and macOS, and [CPython](https://github.com/python/cpython/), [pip](https://github.com/pypa/pip/) and [NumPy](https://github.com/numpy/numpy) are testing those with Azure.

I think our current CI system is doing quite a good job, it'd be nice for all three platforms to be tested in one place, and especially if Azure is faster (with 10 parallel builds).

Right now:
* Appveyor has just 1 parallel worker and takes ~1h15m for 12 jobs
* Travis CI has 5 parallel workers and takes ~26m for 24 jobs

From a [NumPy discussion](https://mail.python.org/pipermail/numpy-discussion/2018-September/078707.html):

> The "free for open source" tier is 10 concurrent jobs that can run up to 60
minutes each (although the website says 30 minutes), and no limit on
minutes per month.  Like the other CI services, it uses YAML files to
define the build and test process.  I found the documentation of the YAML
pipeline spec to be large, but still missing a number of small details and
explanations about how features worked together.  That said, the build
performance is *significantly* better than Travis CI and AppVeyor for all 3
platforms, and the convenience of all major platforms going through one
service is very nice.  Despite not liking the UI quite as much as Travis
CI, I think Numba will likely switch completely over to Azure assuming the
free offering continues to be this good.

What are our long term goals?

* Run tests time, with good coverage of supported platforms, Python versions and depedencies
* Build binaries

**Comment by hugovk** [comment]
See https://github.com/python-pillow/Pillow/pull/3670 for a first step to get the plumbing installed.

**Comment by aclark4life** [comment]
Weee thanks @hugovk. Looks like I'm aclark4life@hotmail.com.

<img width="459" alt="screenshot 2019-03-06 09 56 49" src="https://user-images.githubusercontent.com/72164/53890463-4560fe80-3ff6-11e9-93cb-630932576870.png">

**Comment by hugovk** [comment]
@aclark4life Added!

Please could you add a new CI "pipeline"? Something like this:

1. At https://dev.azure.com/python-pillow/pillow/_build click "New pipeline"
2. Select GitHub (do OAuth)
3. Select python-pillow/Pillow
4. Select "Existing Azure Pipelines YAML file"
5. Install the Azure Pipelines GitHub App to this repository (above of the YAML)
6. After installed, select the project at Azure 
7. Click "Run"
8. That should save it and trigger the first build

**Comment by aclark4life** [comment]
Thanks, looks like it's doing something.

<img width="1451" alt="screenshot 2019-03-06 10 42 35" src="https://user-images.githubusercontent.com/72164/53893658-9c69d200-3ffc-11e9-8b19-f888423c9df8.png">

**Comment by hugovk** [comment]
Thanks, it's working!

I rebased PR https://github.com/python-pillow/Pillow/pull/3661 to test automated builds, and that's working too:

![image](https://user-images.githubusercontent.com/1324225/53894430-c3de9000-4038-11e9-9b98-5bc8df1eb498.png)

https://dev.azure.com/python-pillow/pillow/_build/results?buildId=2

**Comment by hugovk** [comment]
In the time it takes for 12 Azure jobs to finish (5m 43s), 6 Travis jobs finish (full build ~22m), and the first AppVeyor job is still going (full build ~63m).

TODO:
* Get Windows builds onto Azure, remove AppVeyor
* Get coverage working from Docker builds on AP, remove Docker from Travis
* Get non-Docker builds onto Azure, remove Travis (or, because Travis is more familiar and contributors are more likely to enable it, reduce matrix to most important jobs)

**Comment by aclark4life** [comment]
Do we have a way to skip Azure builds per commit?

**Comment by hugovk** [comment]
We can now skip Azure Pipelines builds using any of these:

* `[skip ci]` or `[ci skip]`
* `skip-checks: true` or `skip-checks:true`
* `[skip azurepipelines]` or `[azurepipelines skip]`
* `[skip azpipelines]` or `[azpipelines skip]`
* `[skip azp]` or `[azp skip]`
* `***NO_CI***`

Re: https://github.com/Microsoft/azure-pipelines-agent/issues/1270#issuecomment-475768025

**BUT** for some reason Microsoft decided to ignore it on what they call "PR builds", and only honour it for what they call "CI builds". They've decided they know better and that builds will be run for PRs even when we specifically add `[CI skip]`.

Re: https://github.com/Microsoft/azure-pipelines-agent/issues/1270#issuecomment-486782068

We need to suggest they make it consistent with Travis, AppVeyor, etc.:

> If adding an option to skip PR builds is feature you would like to see, please be sure to suggest a feature on [Developer Community](https://developercommunity.visualstudio.com/spaces/21/visual-studio-team-services.html?sort=votes&type=idea&openOnly=true)!

Re: https://github.com/Microsoft/azure-pipelines-agent/issues/1270#issuecomment-486715008

**Comment by hugovk** [comment]
@aclark4life Please could you put `python-pillow` on the waitlist for the GitHub Actions beta?

* https://github.com/features/actions/signup/?account=python-pillow

It looks good, very similar to Azure Pipelines for CI with a huge 20 parallel build jobs (compared to AP's 10, Travis 5, AppVeyor 1).

**Comment by wiredfool** [comment]
@hugovk, I just pushed the button for the beta. 

I’m kind of excited to get this set up on a day job repo to see how it goesg, we’ll see who gets it first.

**Comment by hugovk** [comment]
Thanks!

It took 6 months for my account to be approved, but hopefully it won't be so long for new signups, as they're launching in November.

Good luck setting up the day job repo, have a look at https://github.com/hugovk/pypistats/pull/70 for tips.

**Comment by wiredfool** [comment]
Just got notification that my account is in the beta, so I’m pretty sure that means that it’s setup on this org. Let me know if there’s something else that needs to be done.

**Comment by hugovk** [comment]
Looks like it's not enabled yet for this org, there's no GitHub Actions showing for https://github.com/python-pillow/Pillow/pull/4058:

![image](https://user-images.githubusercontent.com/1324225/64713724-14421900-d4c6-11e9-9ca0-95b18c4f317d.png)

On my account, I see this:

![image](https://user-images.githubusercontent.com/1324225/64713851-46537b00-d4c6-11e9-863f-9bf92ffcb93d.png)

I think you need to request access separately for each user and organisation from the dropdown at https://github.com/features/actions/signup/?account=python-pillow.

**Comment by hugovk** [comment]
GitHub Actions is enabled, here's some PRs to replicate the Travis builds:

* [x] Lint: https://github.com/python-pillow/Pillow/pull/4058
* [ ] Linux: https://github.com/python-pillow/Pillow/pull/4081
* [ ] Docker: https://github.com/python-pillow/Pillow/pull/4066 (no coverage)

**Comment by nulano** [comment]
Discussion about Travis CI continued in #5028.

**Comment by hugovk** [comment]
I just heard about Oregon State University's Open Source Lab, they offer services for open-source projects, perhaps something here could help replace the unique CPUs from Travis?

https://osuosl.org/services/

**Comment by aclark4life** [comment]
@hugovk What do we need? I worked with them a while back on some @plone infrastructure but I don't remember exactly how it turned out, aside from @plone was paying for some of it and didn't want to spend as much as I wanted OSU to buy 😄 In any event, if you want to summarize I'll submit a request here: https://osuosl.org/request-hosting/

**Comment by radarhere** [comment]
Just to state it in this issue - if Travis CI ever does run out of credits, https://github.com/python-pillow/pillow-wheels/pull/247 can be used to move the aarch64 jobs to GitHub Actions, albeit with a much longer execution time.

**Comment by radarhere** [comment]
Pillow 9.3.0 has just been released - the first release with Windows wheels generated by our CIs.
