### ISSUE TITLE
Draw.rectangle not drawing complete outline

### ISSUE THREAD

**Issue by joh10891** [python-pillow/Pillow#3621]
<img width="569" alt="screen shot 2019-01-29 at 3 28 28 pm" src="https://user-images.githubusercontent.com/29440741/51942865-b997f900-23dd-11e9-9172-c66a6188bbe7.png">
<img width="565" alt="screen shot 2019-01-29 at 3 43 37 pm" src="https://user-images.githubusercontent.com/29440741/51942866-b997f900-23dd-11e9-8c84-82338d5407bf.png">

### What did you do?
I am drawing some bounding boxes over images using draw.rectangle

### What did you expect to happen?
I expected the full rectangles to draw, and am trying to use no fill and just outlines for the bounding boxes. 

### What actually happened?
Only part of the outline of the rectangles actually draw. When I set the outline to None, and try the fill, the whole rectangles render. So the rectangles are properly being fed, it's just there must be some sort of issue with the 'outline' parameter. 

Shown below are examples of rectangles with fill but no outline, which draws correctly, and outline but no fill, which draws incorrectly. 

NOTE: I realize that my x and y coords aren't properly named for their correct order, but they still draw correctly, so the issue is something with rectangle's outline

### What are your OS, Python and Pillow versions?

* OS: Google Colab
* Python: 3
* Pillow: I tried both 5.4.1 and 4.0.0

```python
im = Image.open('training_images/Images/20161029_NTU_00024.png')
draw = ImageDraw.Draw(im)

for item in bboxes:
  item = item.split()
  x1= int(item[0])
  x2= int(item[1])
  y1= int(item[2])
  y2= int(item[3] )
  xy= (x1,x2,y1,y2)
  print(xy)
  draw.rectangle(xy, fill = None, outline=255)
im.save("drawing.png")
import matplotlib.image as mpimg
img=mpimg.imread('drawing.png')
plt.figure(figsize=(12.8,7.2))
plt.axis('off')
plt.imshow(img)
plt.show()
```

**Comment by hugovk** [comment]
Please can you make a self-contained code snippet? Ideally without matplotlib.

Please define what is in `bboxes`, and ideally only include relevant entries.

Thank you.

**Comment by joh10891** [comment]
Sorry about that. I wrote a contained snippet, but as I was running it, it appears that the issue is something with matplotlib rather than PIL. When viewing PIL drawn rectangles on images in matplotlib, the outlines have the issues shown above, but if you manually download the modified image file and view it, the complete outlines are there. Sorry about that, issue must be somewhere with matplotlib! Thank you
