### ISSUE TITLE
PlanarConfiguration save

### ISSUE THREAD

**Issue by VariableDeclared** [python-pillow/Pillow#3622]
### What did you do?
- Open a file using Pillow Image.open `im = Image.open(..blah)`
- downscale the image using Image.thumnail `im.thumbnail(..blah)`
   - (Args: (512, 512), Image.ANTIALIAS) 
- Save the image using save function, only passing new file name `im.save('file_two.tif/tiff')` - Same issue for tiff and tif.
### What did you expect to happen?
Image would be saved, scaled down, and viewable.

### What actually happened?
Image was downscaled, but corrupt, appears red and pixellated, cannot be opened in some image viewers.

Note: I cannot repeat this on Mac OS, haven't tried this on Debian... yet.

### What are your OS, Python and Pillow versions?
* OS: Windows 10 Version 10.0.17763 Build 17763
* Python:  Python 3.6.8 
* Pillow: Pillow 5.4.1

![Corrupted Image](https://github.com/VariableDeclared/Mask_RCNN/blob/5f9f89dbc55301cee09cac42ad06a8d8d7abe211/samples/datasets/xview_dataset/PILissue.tiff)
```python
from PIL import Image
import os


mode = input("Enter mode")

files = [f for f in os.listdir('./{}'.format(mode)) if os.path.isfile(os.path.join('./{}'.format(mode), f))]

im = Image.open('./{}/{}'.format(mode, files[0]))
im.show()

input()
im.thumbnail((512, 512), Image.ANTIALIAS)

im.save('./PILissue.tiff')
```

**Comment by radarhere** [comment]
You've provided a copy of the output image. Are you able to provide a copy of one of the images that you are running this script over?

**Comment by cgohlke** [comment]
It seems any input image with PlanarConfiguration=2 will trigger this bug.

**Comment by radarhere** [comment]
Ok, thanks. On macOS 10.14, if I try to save https://github.com/python-pillow/Pillow/blob/master/Tests/images/tiff_tiled_planar_raw.tif I get a black image.

```
im = Image.open('tiff_tiled_planar_raw.tif')
im.save('out.tif')
```

Presuming that this is the same issue, if you're interested in an immediate solution, I would recommend adding in `im._planar_configuration = 1` -

```
from PIL import Image
import os


mode = input("Enter mode")

files = [f for f in os.listdir('./{}'.format(mode)) if os.path.isfile(os.path.join('./{}'.format(mode), f))]

im = Image.open('./{}/{}'.format(mode, files[0]))
im.show()

input()
im.thumbnail((512, 512), Image.ANTIALIAS)
im._planar_configuration = 1
im.save('./PILissue.tiff')
```

**Comment by radarhere** [comment]
I've created #5973 to fix this.
