### ISSUE TITLE
Pasting image to ImageSequence.Iterator frames produces pixels kinda frames

### ISSUE THREAD

**Issue by thec0sm0s** [python-pillow/Pillow#3629]
Trying to paste an image on Image frames taken from ImageSequence.Iterator

### Expected 

Image to be pasted on all of the frames.

### Actual

Pixel, unclear frames. Huge gif file size. New gif doesn't contains pasted image: same as original but massive file size.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04.1 LTS
* Python: 3.6.7
* Pillow: 5.4.1

```python
from PIL import Image, ImageSequence

gif = Image.open("giphy.gif")
image = Image.open("cosmos.jpeg")

frames = [f for f in ImageSequence.Iterator(gif)]

for frame in frames:
    frame.paste(image, (100, 100))

frames[0].save("test.png")
frames[0].save("test.gif", save_all=True, append_images=frames[1:])

```

**PS: test.gif is so huge to upload. Moreover, last save function eats up whole memory and I have to break it using ctrl+c to avoid crash.**
![giphy](https://user-images.githubusercontent.com/34530901/52173076-81f4cc80-27a2-11e9-9a95-120b7520fbaf.gif)
![cosmos](https://user-images.githubusercontent.com/34530901/52173080-933dd900-27a2-11e9-9b25-6f701be88f0a.jpeg)
![test](https://user-images.githubusercontent.com/34530901/52173084-9f299b00-27a2-11e9-8634-2729f6b77487.png)
![image](https://user-images.githubusercontent.com/34530901/52173093-c1bbb400-27a2-11e9-8f88-69e53c641957.png)

**Comment by radarhere** [comment]
Hi. There are a couple of things happening here, but the most significant is that ImageSequence does not return single frame images - it seeks the image to different positions. So `frames` is actually a list of 91 images, each of which has 91 frames. This is why your final file is large. To convert a multiframe image to a single frame image, I suggest using `copy()` -

```python
from PIL import Image, ImageSequence

gif = Image.open("giphy.gif")
image = Image.open("cosmos.jpeg")

frames = [f.copy() for f in ImageSequence.Iterator(gif)]

for frame in frames:
    frame.paste(image, (100, 100))

frames[0].save("test.png")
frames[0].save("test.gif", save_all=True, append_images=frames[1:])
```

**Comment by thec0sm0s** [comment]
Thanks for the response. That actually worked about the huge GIF size but the appearance of image which is being pasted is really weird.

```python
from PIL import Image, ImageSequence

GIF_PATH = "space.gif"
IMAGE_PATH = "cosmos.jpg"

gif = Image.open(GIF_PATH)
image = Image.open(IMAGE_PATH).resize((120, 120))

frames = [f.copy() for f in ImageSequence.Iterator(gif)]

for frame in frames:
    frame.paste(image, (100, 100))

frames[0].save("test.gif", save_all=True, append_images=frames[1:])
```
![image](https://user-images.githubusercontent.com/34530901/54485435-5cc5a480-489e-11e9-869c-3f7db6df5b94.png)

**Comment by radarhere** [comment]
Regarding the colours of the pasted image, from my understanding it's because the base image is in P mode. When the new image is pasted on top of it, it takes on the palette, and so the colors become limited to that.

After some experimentation with converting between different modes, I find that this looks okay.

```python
from PIL import Image, ImageSequence

gif = Image.open("giphy.gif")
image = Image.open("cosmos.jpeg").convert("P")

frames = [f.copy() for f in ImageSequence.Iterator(gif)]

for i, frame in enumerate(frames):
    frame = frame.convert("RGBA")
    frame.paste(image, (100, 100))
    frames[i] = frame

frames[0].save("test.png")
frames[0].save("test.gif", save_all=True, append_images=frames[1:])
```

**Comment by thec0sm0s** [comment]
Thanks a lot, that fixed the colour problem due to pasting the image.
Moreover I would like to report that when using another GIF file `space.gif` for same purpose, the results are same as before using the following code:
```python
from PIL import Image, ImageSequence

GIF_PATH = "minions.gif"
IMAGE_PATH = "cosmos.jpg"

gif = Image.open(GIF_PATH)
image = Image.open(IMAGE_PATH).resize((120, 120)).convert("P")

frames = [f.copy() for f in ImageSequence.Iterator(gif)]

for i, frame in enumerate(frames):
    frame = frame.convert("RGBA")
    frame.paste(image, (50, 50))
    frames[i] = frame

frames[0].save("test.gif", save_all=True, append_images=frames[1:])
```
**Though it works perfectly fine for that `minions.gif`** but not for `space.gif`.
So I am assuming I would have to convert the frames into suitable image mode before pasting for every unique GIF frames.

But I also noticed something which might be helpful. **The first frame of edited gif using `space.gif` is perfectly fine.** Only the rest of the frames have colors like that.
Confirming, `minions.gif` is working perfectly fine with using that code and looks as expected.

![space](https://user-images.githubusercontent.com/34530901/54545418-a78f0b80-49c7-11e9-9e30-479694aef3fb.gif)
![image](https://user-images.githubusercontent.com/34530901/54545511-d60ce680-49c7-11e9-9bc1-c8ffa8d5ab1f.png)

**Comment by radarhere** [comment]
If it helps, the issue with space.gif is actually reproducible without pasting at all -

```python
from PIL import Image
gif = Image.open("space.gif")
gif.save("test1.gif")
gif.seek(1)
gif.save("test2.gif")
```

**Comment by thec0sm0s** [comment]
Oh right, that issue arises only on using `space.gif`. I passed different GIFs to that code and results are as expected and neat.
Really thank you for helping me out with this.

**Comment by Phant0m-123** [comment]
when I do this method it doesn't copy the frame instead raises an error

**Comment by radarhere** [comment]
@Phant0m-123 if you would like some help, please open a new issue with more details. At the moment, I don't know what your error is.

**Comment by radarhere** [comment]
The new issue was #5550

**Comment by GuruCM** [comment]
@radarhere  Your solution works , only change need when we add transparent image on GIF file 

`from PIL import Image, ImageSequence

GIF_PATH = "minions.gif"
IMAGE_PATH = "cosmos.jpg"

gif = Image.open(GIF_PATH)
image = Image.open(IMAGE_PATH).resize((120, 120)).convert("P")

frames = [f.copy() for f in ImageSequence.Iterator(gif)]

for i, frame in enumerate(frames):
    frame = frame.convert("RGBA")
    frame.paste(image, (50, 50),image) #mask value is need
    frames[i] = frame

frames[0].save("test.gif", save_all=True, append_images=frames[1:])`

thank you for helping
