### ISSUE TITLE
Flash Values in exif tags

### ISSUE THREAD

**Issue by nina-hua** [python-pillow/Pillow#3633]
### What did you do?
Used Pillow to extract flash values from images 

### What are your OS, Python and Pillow versions?
Python 
* OS: 10.13.6
* Python: Python 3.6.7
* Pillow: 5.1.0

What are the Flash values defined as in PIL? I can't seem to find a dictionary that relates the flash tag to a value similar to [here](https://github.com/ianare/exif-py/blob/develop/exifread/tags/exif.py).

**Comment by radarhere** [comment]
In the link that you provided, it lists 'Flash' as '0x9209' -

```
0x9209: ('Flash', {
     0: 'Flash did not fire',
     1: 'Flash fired',
     ...
     24: 'Flash did not fire, auto mode',
     ...
     95: 'Flash fired, auto mode, return light detected, red-eye reduction mode'
}),
```

Using the [flower.jpg test image](https://raw.githubusercontent.com/python-pillow/Pillow/master/Tests/images/flower.jpg) -

```
>>> from PIL import Image
>>> im = Image.open('Tests/images/flower.jpg')
>>> exif = im._getexif()
>>> print(exif[0x9209])
24
```

So, for our flower.jpg test image, the 'Flash' value is 'Flash did not fire, auto mode'

**Comment by radarhere** [comment]
If you have any further questions, feel free to ask and this can be re-opened.
