### ISSUE TITLE
Save multiple images in a tiff file

### ISSUE THREAD

**Issue by romain7594** [python-pillow/Pillow#3636]
### What did you do?
I open a tiff file, I add tags to some of the images in it, then save

### What did you expect to happen?
Save modifications

### What actually happened?
The added tag isn't saved

### What are your OS, Python and Pillow versions?

* OS: windows 7
* Python: 3.6
* Pillow: 5.1.0

```python
from PIL import Image, TiffImagePlugin

im = Image.open("test.tiff")
im.seek(6)
info = TiffImagePlugin.ImageFileDirectory()
info[56] = 54
info.tagtype[56] = 3
im.save("test_out.tiff", save_all=True, tiffinfo = info)
```

**Comment by radarhere** [comment]
Hi. Could you try updating to the latest Pillow, 5.4.1? #3350 added writing of custom TIFF tags to Pillow 5.4.0, so that may resolve your problem. If it does not, could you give a more complete example - the file you are using, and the way that you know that the tag hasn't been added successfully?

**Comment by romain7594** [comment]
I haven't administrator rights to update it, but I could try to ask.

For now, I'm just doing tests to see if it works with a "random" tiff file. The tag isn't added because when I re-open it, they are not here.

I saw that with libtiff, it could be possible and easier ... ?

**Comment by radarhere** [comment]
What method are you using to open it and inspect that the tag is not there? Are you using something like Photoshop, or are you checking the values using Pillow?

If you add in `TiffImagePlugin.WRITE_LIBTIFF = True` then Pillow will use libtiff.

Here is an example script, using one of the Pillow test suite images, and also using libtiff, just to demonstrate it. This works for me with 5.4.1. It does not work with 5.1.0.

```python
from PIL import Image, TiffImagePlugin

im = Image.open("Tests/images/compression.tif")
TiffImagePlugin.WRITE_LIBTIFF = True
im.seek(1)
info = TiffImagePlugin.ImageFileDirectory()
info[56] = 54
info.tagtype[56] = 3
im.save("out.tiff", save_all=True, tiffinfo = info)

reloaded = Image.open("out.tiff")
print(reloaded.tag_v2[56])  # 54
```

**Comment by romain7594** [comment]
I checked the values as you done. I'm also using AsTiffTagViewer.

Your example works for one image in the file. How about 2 or more ?

**Comment by radarhere** [comment]
compression.tif has 2 frames, and if I change the end of my code, I see the value even after seeking to 1.

```python
reloaded = Image.open("out.tiff")
print(reloaded.tag_v2[56])  # 54
reloaded.seek(1)
print(reloaded.tag_v2[56])  # 54
```

So I don't understand your request for a situation involving 2 or more frames, as I think this already does that.

`_v2` was added in the rewrite in #1419. Pillow highly values not breaking existing code.

**Comment by romain7594** [comment]
The point is, for 2 different frames I want to set different value for the tag 56. For frame 1, tag[56]=4, and for frame 2, tag[56]=6, and not the same value for all the frames.

**Comment by radarhere** [comment]
Okay, here's what I have come up with as a quick and immediate solution.

```python
from PIL import Image, ImageSequence, TiffImagePlugin

im = Image.open("Tests/images/compression.tif")
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
	frame = frame.convert(frame.mode)
	info = TiffImagePlugin.ImageFileDirectory()
	info[56] = 54 + i
	info.tagtype[56] = 3
	frame.encoderinfo = {'tiffinfo': info}
	frames.append(frame)
with open("out.tiff", "w+b") as fp:
	with TiffImagePlugin.AppendingTiffWriter(fp) as tf:
		for frame in frames:
			frame.encoderconfig = ()
			TiffImagePlugin._save(frame, tf, "out.tiff")
			tf.newFrame()

reloaded = Image.open("out.tiff")
print(reloaded.tag_v2.get(56))  # 54
reloaded.seek(1)
print(reloaded.tag_v2.get(56))  # 55
```

**Comment by romain7594** [comment]
Oh, I could never have found that. It works very well (and it works with version 5.1.0), but it seems that it doesn't like float values as a tag value.

**Comment by romain7594** [comment]
I'm coming here again to ask if it is possible to set the name of the tag ? By default it takes the tag number, 56 for this example.

**Comment by radarhere** [comment]
Is it possible to specify a name for a custom tag? This is conceivable, but it is not currently a feature of Pillow. If you would like this feature, please request it in a new issue.

**Comment by radarhere** [comment]
Hi. So, what are you after in re-opening this issue?

**Comment by romain7594** [comment]
According to the code you wrote @radarhere, it is used from a tiff file. Now I want to do the same operation but starting from an array of images : one element of the array is an array representing one image. The following code works :
   
    # images in my list of images arrays
    from PIL import Image
    image_list = []
    for image in images :
        image_list.append(Image.fromarray(image))
    image_list[0].save("images.tiff", save_all=true append_images=image_list[1:])
        
Now considering a list of tuples (id_tag, tags), it is possible to add them with the code I wrote ? Acutally I need to create the tiff file first, then open it and add the tags which takes double time.

**Comment by radarhere** [comment]
Okay, see if I've understood correctly -

```python
from PIL import Image, ImageSequence, TiffImagePlugin

# Preparation
import numpy as np
images = [np.asarray(im) for im in [
	Image.new("RGB", (100, 100), "#f00"),
	Image.new("RGB", (100, 100), "#0f0")
]]
listOfTuples = [
	(55, [1, 3]),
	(56, [2, 4])
]

# Script
image_list = []
for image in images:
	image_list.append(Image.fromarray(image))
frames = []
for i, frame in enumerate(image_list):
	info = TiffImagePlugin.ImageFileDirectory()
	
	for tupleIdTag, tupleTags in listOfTuples:
		info[tupleIdTag] = tupleTags[i]
		info.tagtype[tupleIdTag] = 3
	
	frame.encoderinfo = {'tiffinfo': info}
	frames.append(frame)
with open("out.tiff", "w+b") as fp:
	with TiffImagePlugin.AppendingTiffWriter(fp) as tf:
		for frame in frames:
			frame.encoderconfig = ()
			TiffImagePlugin._save(frame, tf, "out.tiff")
			tf.newFrame()

reloaded = Image.open("out.tiff")
for tupleIdTag, _ in listOfTuples:
	print(reloaded.tag_v2.get(tupleIdTag))
reloaded.seek(1)
for tupleIdTag, _ in listOfTuples:
	print(reloaded.tag_v2.get(tupleIdTag))
```

**Comment by romain7594** [comment]
Yes it works well. Thanks a lot
