### ISSUE TITLE
Constant value for GIF duration, IndexError for passed list in duration param

### ISSUE THREAD

**Issue by Cylifio** [python-pillow/Pillow#3639]
### What did you do?
Save a GIF that has different frame durations.

### What did you expect to happen?
Output GIF frame durations should be the same as the original.

### What actually happened?
Output GIF frames all have the same duration.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 17.10
* Python: 3.6.3
* Pillow: 5.4.1

```python
from PIL import Image, ImageSequence

img = Image.open("image0.gif")
frames = []
frame_duration = []

for f in ImageSequence.Iterator(img):
    frame_duration.append(f.info["duration"])
    frames.append(f)

frames[0].save('outimage1.gif',
                save_all=True,
                append_images=frames,
                loop=0)

print(frame_duration)

dframes = []
img1 = Image.open("outimage1.gif")
for fr in ImageSequence.Iterator(img1):
    dframes.append(fr.info["duration"])

print(dframes)
```
Before Image:
![image0](https://user-images.githubusercontent.com/32244810/52497232-8f93c300-2ba3-11e9-8c05-045d536ed90c.gif)

**Running script and After Image:**
cyl@MachineName:/home/cyl/$ python3 testscript.py
[50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 2000]
[50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50, 50]

![outimage1](https://user-images.githubusercontent.com/32244810/52498032-a3402900-2ba5-11e9-9d16-b8b05053c3db.gif)

I ran this script on a Windows 10 machine and found that the last frame's duration is used instead of the first frame's duration compared to Linux.

Also, passing a list to the `duration` parameter in `save()`causes an `IndexError`. Traceback:
```python
Traceback (most recent call last):
  File "testscript.py", line 15, in <module>
    duration=frame_duration)
  File "/home/cyl/.local/lib/python3.6/site-packages/PIL/Image.py", line 1994, in save
    save_handler(self, fp, filename)
  File "/home/cyl/.local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 486, in _save_all
    _save(im, fp, filename, save_all=True)
  File "/home/cyl/.local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 497, in _save
    if not save_all or not _write_multiple_frames(im, fp, palette):
  File "/home/cyl/.local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 436, in _write_multiple_frames
    encoderinfo['duration'] = duration[frame_count]
IndexError: list index out of range
```

**Comment by radarhere** [comment]
Hi. I presume you've wondered why the length of `dframes`, your array of duration times from the output image, is so much longer than `frame_duration`, your array of duration times from your input image.

The ImageSequence Iterator is not giving you single frames. It is seeking the image to a different frame in the image.

```
>>> for f in ImageSequence.Iterator(img):
>>>	print([f.tell(), f.n_frames])
[0, 11]
[1, 11]
[2, 11]
[3, 11]
[4, 11]
[5, 11]
[6, 11]
[7, 11]
[8, 11]
[9, 11]
[10, 11]
```

Which means that

```
frames[0].save('outimage1.gif',
                save_all=True,
                append_images=frames,
                loop=0)
```

is actually combining 12 images of 11 frames each, making 132, the length of `dframes`.

So, if we fix that, and use the `duration` parameter, your problem is solved.

```
from PIL import Image, ImageSequence

img = Image.open("image0.gif")
frame_duration = []

for f in ImageSequence.Iterator(img):
    frame_duration.append(f.info["duration"])

img.save('outimage1.gif',
		 save_all=True,
		 duration=frame_duration,
		 loop=0)

print(frame_duration)

dframes = []
img1 = Image.open("outimage1.gif")
for fr in ImageSequence.Iterator(img1):
    dframes.append(fr.info["duration"])

print(dframes)
```

```
[50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 2000]
[50, 100, 150, 200, 250, 300, 350, 400, 450, 500, 2000]
```

**Comment by Cylifio** [comment]
Understood, thank you for clearing that up. But, if I were to manipulate each frame in the first iteration, how would I be able to save each manipulated frame without using the `append_images` parameter?

**Comment by radarhere** [comment]
```python
from PIL import Image, ImageSequence

img = Image.open("image0.gif")
frames = []
frame_duration = []

for f in ImageSequence.Iterator(img):
    frame_duration.append(f.info["duration"])
    
    # To convert a multiframe image to a single frame,
    # I would suggest this
    f = f.convert(f.mode)
    
    # However, that may not be necessary
    # If, for example, the manipulation you wanted to do is to rotate each frame,
    # that would already convert the image to a single frame
    #f = f.rotate(90)
    
    frames.append(f)

# This is using 'append_images' and 'frame_duration'
# Note as well that I've added '[1:]', which wasn't in your original code
# This is because we are not appending all images, only the images after the first frame
frames[0].save('outimage1.gif',
                save_all=True,
                append_images=frames[1:],
                duration=frame_duration,
                loop=0)

print(frame_duration)

dframes = []
img1 = Image.open("outimage1.gif")
for fr in ImageSequence.Iterator(img1):
    dframes.append(fr.info["duration"])

print(dframes)
```

**Comment by Cylifio** [comment]
I appreciate the help, I have no issues with this and everything works as expected. Closing this issue.
