### ISSUE TITLE
CI: Arch build failing

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3641]
### What did you do?

Test the code on Travis CI.

### What did you expect to happen?

Pass, as it did 4 days ago on master:

* https://travis-ci.org/python-pillow/Pillow/builds/489433692

### What actually happened?

It failed. Here's the next build on master (with only an AppVeyor config change):

* https://travis-ci.org/python-pillow/Pillow/builds/490240861

```
Tests/test_qt_image_fromqpixmap.py::TestFromQPixmap::test_sanity_1 PASSED [ 98%]
Tests/test_qt_image_fromqpixmap.py::TestFromQPixmap::test_sanity_l PASSED [ 98%]
Tests/test_qt_image_fromqpixmap.py::TestFromQPixmap::test_sanity_p PASSED [ 98%]
Tests/test_qt_image_fromqpixmap.py::TestFromQPixmap::test_sanity_rgb PASSED [ 98%]
Tests/test_qt_image_fromqpixmap.py::TestFromQPixmap::test_sanity_rgba PASSED [ 98%]/usr/bin/xvfb-run: line 181:   715 Segmentation fault      (core dumped) DISPLAY=:$SERVERNUM XAUTHORITY=$AUTHFILE "$@" 2>&1
The command "if [ "$LINT" == "true" ]; then
  tox -e lint
elif [ "$DOCKER" == "" ]; then
  .travis/script.sh
elif [ "$DOCKER" ]; then
  # the Pillow user in the docker container is UID 1000
  sudo chown -R 1000 $TRAVIS_BUILD_DIR
  docker run -v $TRAVIS_BUILD_DIR:/Pillow pythonpillow/$DOCKER:$DOCKER_TAG
fi
" exited with 139.
cache.2
store build cache
0.00s1.21snothing changed, not updating cache
Done. Your build exited with 1.
```

Comparing last-pass and first-fail logs, the only notable difference is pytest has upgraded from 4.1.1 to 4.2.0:

![image](https://user-images.githubusercontent.com/1324225/52533795-c6074480-2d41-11e9-8466-50d50bcd5dd4.png)

Possibly related:
* https://bugs.python.org/issue34095

The https://github.com/python-pillow/docker-images builds are still [passing](https://travis-ci.org/python-pillow/docker-images/builds/491227210).

**Comment by hugovk** [comment]
I'm hesitant to merge anything non-trivial until this is fixed. And I think this red build is preventing coverage reports on other PRs. 

Any thoughts on either of the PRs for this?

**Comment by wiredfool** [comment]
Can we revert or pin pytest?

**Comment by hugovk** [comment]
We can and it passes! See PR https://github.com/python-pillow/docker-images/pull/55.

Nothing stands out in the pytest 4.1.1->4.2.0 release notes to account for it:

https://docs.pytest.org/en/latest/changelog.html#pytest-4-2-0-2019-01-30

**Comment by wiredfool** [comment]
Glad to see that worked. This doesn't sound like it's really our problem, so it's good to make progress while it gets sorted out.
