### ISSUE TITLE
Doc description for Image.crop() is wrong 

### ISSUE THREAD

**Issue by dustss** [python-pillow/Pillow#3643]
Parameters: | box – The crop rectangle, as a (left, upper, right, lower)-tuple.

actually, here should be  (left, **lower,** right, **upper**)-tuple

it leads to the failure of crop.

**Comment by radarhere** [comment]
The following code works for me.
```python
>>> from PIL import Image
>>> im = Image.new("RGB", (100, 100))
>>> print("Image size: "+str(im.size))
Image size: (100, 100)
>>> points = {'left': 25, 'upper': 25, 'right': 75, 'lower': 75}
>>> im_cropped = im.crop((points['left'], points['upper'], points['right'], points['lower']))
>>> im_cropped.load()
<PixelAccess object at 0x1019c1190>
>>> print("Cropped image size: "+str(im_cropped.size))
Cropped image size: (50, 50)
```

I'm guessing that you think that 'upper' should mean the coordinate of greater magnitude, 75 not 25? In that case, I would point you towards the documentation about [Pillow's coordinate system](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#coordinate-system), which states that Pillow 'uses a Cartesian pixel coordinate system, with (0,0) in the upper left corner'
