### ISSUE TITLE
Support for EXIF in PNG format

### ISSUE THREAD

**Issue by jaddison** [python-pillow/Pillow#3644]
Based on http://ftp-osl.osuosl.org/pub/libpng/documents/pngext-1.5.0.html#C.eXIf, ~it looks like there is a push to officially add exif support into the PNG image format~, it looks like they have defined how to include EXIF data in a PNG 'data chunk' (a standard mechanism 'adding extra data' to PNG files).

Given the work EXIF-related started in #3625 (which addresses #520), is it reasonable to consider this feature request for Pillow?

**Comment by radarhere** [comment]
Yes, it is reasonable. However, by 'there is a push to officially add', do you mean that it is not yet officially supported?

**Comment by jaddison** [comment]
That was poor wording on my part, I think. The PNG format 'extension' seems to be legitimate, and official. The PNG format isn't modified at all, but the 'extension' merely defines how EXIF should be included as a 'data chunk', which the format already supports. 

I'll edit the original description above.

**Comment by radarhere** [comment]
I've created #3674 to resolve this.
