### ISSUE TITLE
Value range of the HSV mode 

### ISSUE THREAD

**Issue by Usief** [python-pillow/Pillow#3650]
### What did you do?
When I tried to find is there a specific color point in the image, I find there is not clear comment in the pillow document.

### What did you expect to happen?
I hope I could find the HSV value range in Pillow. 

### What actually happened?
I am not sure the value range of HSV in Pillow. I read the pillow document, but it only says the HSV model is 3*8 pixels, Hue, Saturation, Value color space. Unfortunately, there are different HSV models with different value range I found on google. That confused me.

Could you give more explanation in the document?

### What are your OS, Python and Pillow versions?

* OS: Windows 7
* Python:  2.7
* Pillow: 5.3.0

[Pillow Concepts](https://pillow.readthedocs.io/en/latest/handbook/concepts.html)

**Comment by radarhere** [comment]
Any thoughts on https://pillow.readthedocs.io/en/latest/reference/ImageColor.html?highlight=hsv#color-names?

**Comment by Usief** [comment]
> Any thoughts on https://pillow.readthedocs.io/en/latest/reference/ImageColor.html?highlight=hsv#color-names?

Thanks for your help.

That page implies the value range of the HSV mode in Pillow is not CSS3-style, but the real value range is still unclear. 

I did some tests.

![image](https://user-images.githubusercontent.com/13103405/52705859-e42da880-2fbe-11e9-9f30-fa92d8ba646d.png)

![image](https://user-images.githubusercontent.com/13103405/52705884-f3acf180-2fbe-11e9-98d5-61632dbd3563.png)

The color should be red if it is CSS3-style, but the true value for red is 

![image](https://user-images.githubusercontent.com/13103405/52706084-7c2b9200-2fbf-11e9-90b1-0af17774adf3.png)

![image](https://user-images.githubusercontent.com/13103405/52706107-877ebd80-2fbf-11e9-84a7-5f38a2545896.png)

I guess the value range for HSV model is H: 0-255, S: 0-255, V:0-255, Maybe?

**Comment by hugovk** [comment]
HSV isn't a `mode` for `Image.new(mode, size, color)`:

![image](https://user-images.githubusercontent.com/1324225/52708310-871bfd80-2f92-11e9-84c6-5d3b2184c29b.png)

* https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.new
* https://pillow.readthedocs.io/en/latest/handbook/concepts.html#concept-modes

Use something like this, where HSV is the usual 0-360, 0-100%, 0-100%:

```python
from PIL import Image, ImageColor

Image.new(mode="RGB", size=(100, 100), color=ImageColor.getrgb("hsv(0, 100%, 100%)")).show()
```

![image](https://user-images.githubusercontent.com/1324225/52708452-d3ffd400-2f92-11e9-913a-8631d16fda5c.png)

**Comment by Usief** [comment]
> HSV isn't a `mode` for `Image.new(mode, size, color)`:
> 
> ![image](https://user-images.githubusercontent.com/1324225/52708310-871bfd80-2f92-11e9-84c6-5d3b2184c29b.png)
> 
> * https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.new
> * https://pillow.readthedocs.io/en/latest/handbook/concepts.html#concept-modes
> 
> Use something like this, where HSV is the usual 0-360, 0-100%, 0-100%:
> 
> ```python
> from PIL import Image, ImageColor
> 
> Image.new(mode="RGB", size=(100, 100), color=ImageColor.getrgb("hsv(0, 100%, 100%)")).show()
> ```
> 
> ![image](https://user-images.githubusercontent.com/1324225/52708452-d3ffd400-2f92-11e9-913a-8631d16fda5c.png)

Thanks a lot. It is really helpful.

I wrote some extra code to show the problem.

![image](https://user-images.githubusercontent.com/13103405/52757335-4b8b3d00-303f-11e9-8caa-b3b9c8b537bb.png)

![image](https://user-images.githubusercontent.com/13103405/52757538-f996e700-303f-11e9-8653-5a5a15edd621.png)

When I used the getpixel in the HSV mode, the return values are between 0-255, which is not consistent with the common value ranges.

**Comment by hugovk** [comment]
There's no such thing as HSV mode for Pillow images. See https://pillow.readthedocs.io/en/stable/handbook/concepts.html

You cannot convert to HSV mode. This is documented: https://pillow.readthedocs.io/en/stable/reference/Image.html

You have an RGB mode image (`print(im.mode))`) and the getpixel values are RGB.

**Comment by Usief** [comment]
> There's no such thing as HSV mode for Pillow images. See https://pillow.readthedocs.io/en/stable/handbook/concepts.html
> 
> You cannot convert to HSV mode. This is documented: https://pillow.readthedocs.io/en/stable/reference/Image.html
> 
> You have an RGB mode image (`print(im.mode)`) and the getpixel values are RGB.

Sorry, my bad. I did not read the comment of convert carefully.

The page says HSV is supported by the current release
![image](https://user-images.githubusercontent.com/13103405/52770161-58bf2080-306d-11e9-818f-d8586fcbe400.png)


In practice, I found that if I convert the image to HSV mode it can work and the color value of the pixel is different from the value in RGB mode.
![image](https://user-images.githubusercontent.com/13103405/52770561-6aed8e80-306e-11e9-95d1-7b4074f75ef1.png)

![image](https://user-images.githubusercontent.com/13103405/52770527-50b3b080-306e-11e9-9fab-ca79dac10082.png)

If I convert the same image to HSL mode, the code cannot run.
![image](https://user-images.githubusercontent.com/13103405/52770666-a8eab280-306e-11e9-92cc-ea5f7bc208f7.png)

If Pillow images cannot convert to HSV, why the convert can work for HSV but cannot work for HSL? It is strange.

**Comment by hugovk** [comment]
Sorry, it does indeed say HSV there! Will check again!

**Comment by hugovk** [comment]
> > Any thoughts on [pillow.readthedocs.io/en/latest/reference/ImageColor.html?highlight=hsv#color-names](https://pillow.readthedocs.io/en/latest/reference/ImageColor.html?highlight=hsv#color-names)?
> 
> Thanks for your help.
> 
> That page implies the value range of the HSV mode in Pillow is not CSS3-style, but the real value range is still unclear.
> 
> I did some tests.
> 
> ![image](https://user-images.githubusercontent.com/13103405/52705859-e42da880-2fbe-11e9-9f30-fa92d8ba646d.png)
> 
> ![image](https://user-images.githubusercontent.com/13103405/52705884-f3acf180-2fbe-11e9-98d5-61632dbd3563.png)
> 
> The color should be red if it is CSS3-style, but the true value for red is
> 
> ![image](https://user-images.githubusercontent.com/13103405/52706084-7c2b9200-2fbf-11e9-90b1-0af17774adf3.png)
> 
> ![image](https://user-images.githubusercontent.com/13103405/52706107-877ebd80-2fbf-11e9-84a7-5f38a2545896.png)
> 
> I guess the value range for HSV model is H: 0-255, S: 0-255, V:0-255, Maybe?

Yes, that's right, all three are 0-255 here. Sorry for the confusion!

**Comment by wiredfool** [comment]
Fundamentally, anything in Pillow that’s not explicitly bigger or smaller is an 8bit per channel image.

**Comment by FrancoisChastel** [comment]
Is there any reason to range between 0-255 on values that should be degrees and percentage ? Range from 0-1 or the actual range is fundamentally less confusing.. even if the doc try to fill that gap.

**Comment by radarhere** [comment]
I suspect it would just have been for similarity with the other modes. Even if we did agree that HSV should be 0-1, Pillow values backwards compatibility highly, so I don't think a change like adjusting the value range for a mode would make it in, given that it otherwise works.

**Comment by wiredfool** [comment]
They're 0-255 because they're 8 bit ints, the same as all of the other multichannel images in Pillow.
