### ISSUE TITLE
[Solved] Pillow 5.2.0 loads jpeg image differently between two machines

### ISSUE THREAD

**Issue by StarsThu2016** [python-pillow/Pillow#3651]
Note: To show less subjective and personal analysis which actually misleads the reader, I edited this issue to be more objective.
### What did you do?
I use Pillow 5.2.0 to load jpeg images in two machines.

### What did you expect to happen?
The loaded pixel values should be exactly the same.

### What actually happened?
They are different.

### What are your OS, Python and Pillow versions?

* OS: Both Ubuntu 16.04
* Python: machine 1 - python 3.5.2, machine 2 - python 3.6.4 anaconda 
* Pillow: 5.2.0
* Linked jpeg library: machine 1 - libjpeg 8, machine 2 - libjpeg 9.
As Andrew points out,
from PIL import Image
print(Image.core.jpeglib_version)

Code and image to reproduce the issue: https://github.com/StarsThu2016/PIL_Load_Debug
Solution to the issue: same as above

Reference 1: https://github.com/python-pillow/Pillow/issues/2316 
Reference 2: https://stackoverflow.com/questions/31607731/opencv-vs-matlab-different-values-on-pixels-with-imread

**Comment by radarhere** [comment]
```python
from PIL import Image
print(Image.core.jpeglib_version)
```
However, I don't think that will have enough detail to be helpful.

**Comment by StarsThu2016** [comment]
@radarhere Hi Andrew,
Thanks very much for your code snippet. I found it is truly due to the different libjpeg versions. My detailed solution to this issue is written in https://github.com/StarsThu2016/PIL_Load_Debug.

**Comment by radarhere** [comment]
Excellent
