### ISSUE TITLE
Pillow and PyQt4 don't play nicely with each other

### ISSUE THREAD

**Issue by konulv** [python-pillow/Pillow#3652]
### What did you do?
trying to open image with Pillow
converting it to ImageQT, and Qimage of PyQt4
putting that image onto a window in the GUI
`imgLabel` is Qlabel object of PyQt4
```python
img = Image.open("Lenna.png")
qimg = QtGui.QImage(ImageQt.ImageQt(img))
pixImg = QtGui.QPixmap.fromImage(qimg)
self.imgLabel.setPixmap(pixImg)
```
### What did you expect to happen?
Image to be displayed
### What actually happened?
Segmentation fault
### What are your OS, Python and Pillow versions?

* OS: Linux mint 19
* Python: 3.6.7
* Pillow: 5.3.0

**Comment by hugovk** [comment]
Does this work?
```diff
img = Image.open("Lenna.png")
-qimg = QtGui.QImage(ImageQt.ImageQt(img))
-pixImg = QtGui.QPixmap.fromImage(qimg)
+pixImg = ImageQt.toqimage(img)
self.imgLabel.setPixmap(pixImg)
```

**Comment by konulv** [comment]
if I take your suggestion at face value, it doesn't because `.setPixmap(img)` is expecting QPixmap and `pixImg` in this case is Qimage. Converting it to Pixmap however, still results in segfault.
I've did however just noticed there is a `toqpixmap(img)` method in `ImageQt`, which makes it all work
```python
img = Image.open("Lenna.png")
pixImg = ImageQt.toqpixmap(img)
self.imgLabel.setPixmap(pixImg)

**Comment by hugovk** [comment]
Ah yes, `toqpixmap` makes more sense :)
