### ISSUE TITLE
How To Create A4 PDF

### ISSUE THREAD

**Issue by LouisPi** [python-pillow/Pillow#3653]
As the title says. The documentation here - https://pillow.readthedocs.io/en/5.2.x/handbook/image-file-formats.html#pdf is quite vague and the closest I get to working it out is "Image resolution in DPI. This, together with the number of pixels in the image, will determine the physical dimensions of the page that will be saved in the PDF" but this does not explain how to get particular dimension of the PDF file.

Thanks,
Louis

**Comment by vashek** [comment]
It does, unless I'm missing something. A4 is 210 x 297 mm. An inch is 25.4 mm, so A4 is 8.27 x 11.69 in. Let's say you want the PDF to have 300 DPI, so that means 2480 x 3508 pixels.

**Comment by LouisPi** [comment]
Ah thanks for the help! So if I give it a 2480 x 3508 pixel image will I get an A4 page as long as I set the resolution to 300?

**Comment by vashek** [comment]
I believe so. Are you getting something else?

**Comment by LouisPi** [comment]
Thanks again for the help, I just tried it and confirm it works a treat.
