### ISSUE TITLE
DDS Plugin cannot handle uncompressed files

### ISSUE THREAD

**Issue by Xfel** [python-pillow/Pillow#3659]
Loading a DDS file without compression gives me the following error:
```
  File "<SNIP>\PIL\Image.py", line 2676, in open
    im = _open_core(fp, filename, prefix)
  File "<SNIP>\PIL\Image.py", line 2658, in _open_core
    im = factory(fp, filename)
  File "<SNIP>\PIL\ImageFile.py", line 103, in __init__
    self._open()
  File "<SNIP>\PIL\DdsImagePlugin.py", line 158, in _open
    (fourcc))
NotImplementedError: Unimplemented pixel format b'\x00\x00\x00\x00'
```

To demonstrate the issue, I created a simple DDS file as demonstration. Calling `Image.open()` on that file will not work. 
[uncompressed_dds.zip](https://github.com/python-pillow/Pillow/files/2872238/uncompressed_dds.zip)

Looking over the source code of DdsImagePlugin, it seems that only FourCC DDS files are supported.

Pillow version: 5.4.1
Python version: 3.7.2

**Comment by hugovk** [comment]
The docs say only DXT1, DXT3 and DXT5 in `RGBA`:

> DDS is a popular container texture format used in video games and natively supported by DirectX. Currently, DXT1, DXT3, and DXT5 pixel formats are supported and only in `RGBA` mode.

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html?highlight=dds#dds

The code also includes three DXGI formats of DXT10:

https://github.com/python-pillow/Pillow/blob/daa8b5133923561d2c6d4d1f7b2c9d9aa233007e/src/PIL/DdsImagePlugin.py#L131-L158

**Comment by Xfel** [comment]
Ah, I hadn't seen the documentation. Let's turn this into a feature request, then.

**Comment by radarhere** [comment]
@Xfel is the file that you have provided able to added to the test suite under the Pillow license?

**Comment by Xfel** [comment]
I created this file specifically for this demonstration, so it should be fine. (it's just a bunch of random scribbles anyways).

**Comment by radarhere** [comment]
Thanks. I've created PR #3673 to resolve this.

**Comment by hugovk** [comment]
@Xfel Please can you test PR #3673?
