### ISSUE TITLE
AttributeError: module 'PIL.Image' has no attribute 'mage'

### ISSUE THREAD

**Issue by oppne** [python-pillow/Pillow#3662]
### What did you do?
Tried to make an image converter, from PNG to JPEG/JPG

### What did you expect to happen?
That it converted the image

### What actually happened?

The error is the following
Traceback (most recent call last):
  File "C:/Users/xxx/.PyCharmEdu2018.3/config/scratches/ImageConvertion.py", line 4, in <module>
    im = Image.mage.open ("2.png")
AttributeError: module 'PIL.Image' has no attribute 'mage

### What are your OS, Python and Pillow versions?
* OS: windows 10
* Python: 3.7.0
* Pillow: 5.4.1

```
from PIL import Image
im = Image.mage.open ("2.png")
bg = Image.new ("RGB", im.size, (255,255,255))
bg.paste (im, (0,0), im)
bg.save("file.jpg", quality=95)
```

**Comment by dhsdshdhk** [comment]
Image.mage.open?

**Comment by hugovk** [comment]
It's `im = Image.open("2.png")`

**Comment by lalitpatil58** [comment]
img=Image.open("2.png")
