### ISSUE TITLE
How can Pillow draw ®

### ISSUE THREAD

**Issue by lx1054331851** [python-pillow/Pillow#3668]
How can Pillow draw text "®", such as <COLORO®>. 
It seems Pillow can not recognise "®".

**Comment by radarhere** [comment]
The following works for me.

```python
from PIL import Image, ImageDraw
im = Image.new("RGB", (80, 40))
d = ImageDraw.Draw(im)
d.text((10, 10), "<COLORO®>")
im.save("out.png")
```

![out](https://user-images.githubusercontent.com/3112309/53155385-081d6980-3611-11e9-98e9-85d4860a06ab.png)

If it also works for you, then could you let us know what operating system, Pillow version and font you are using?

**Comment by lx1054331851** [comment]
Thank you very much!
I checked my font type, and changed to another font, it works.
