### ISSUE TITLE
Raspbian install documentation

### ISSUE THREAD

**Issue by robodhhb** [python-pillow/Pillow#3671]
### What did you do?
I want to import PIL modules with the following statement
```python
#!/usr/bin/python3
import tkinter
from PIL import Image, ImageTk
```

But ImageTk was NOT imported. I got it by executing:
sudo aptitude install python3-pil.imagetk
This fact should be added to the documentation which would be of great help for beginners.
All modules which are not installed by default should have a hint that a user must install these modules!

### What did you expect to happen?
The module Image and ImageTk shall be imported

### What actually happened?
Only the module Image was imported
### What are your OS, Python and Pillow versions?

* OS: Raspbian GNU/Linux 9.6 (stretch), Release:	9.6
         Codename:	stretch
* Python: 3.5.3
* Pillow: 
Version: 4.0.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: Standard PIL License
Location: /usr/lib/python3/dist-packages

**Comment by radarhere** [comment]
How did you initially install Pillow? You've outlined what you did to get ImageTk working, but what method did you use to set up Pillow so that just Image could be installed?

**Comment by radarhere** [comment]
I've created #5360 to resolve this.
