### ISSUE TITLE
ImageFilter.Kernel uses kernel weights in the wrong order?

### ISSUE THREAD

**Issue by carlosefr** [python-pillow/Pillow#3678]
### What did you do?

I'm using the `ImageFilter.Kernel` filter with a 3x3 kernel that should shift the image down by one pixel, but instead it is shifting the image one pixel up.

I'm assuming the order of weights in the kernel is left-right, top-bottom because, AFAIK, the documentation doesn't specify the order and I assume it uses the same ordering/coordinates as the image itself.

So, this is either a bug in the code, or a bug in the documentation.

### What did you expect to happen?

The image should be shifted one pixel **down**.

### What actually happened?

The image is shifted one pixel **up**.

### What are your OS, Python and Pillow versions?

* OS: CentOS Linux 7.6
* Python: 3.6.7
* Pillow: 5.4.1

```python
from PIL import Image, ImageFilter

shift_down = (
    0, 1, 0,
    0, 0, 0,
    0, 0, 0,
)

original_image = Image.open("images/example.png", mode="r")
filtered_image = original_image.filter(ImageFilter.Kernel((3, 3), shift_down))
filtered_image.save("filtered.png", format="PNG")
```

**Comment by carlosefr** [comment]
Additional note, this kernel shifts the image left by one pixel as expected:
```
shift_left = (
    0, 0, 0,
    0, 0, 1,
    0, 0, 0,
)
```

**Comment by hugovk** [comment]
Possibly related to https://github.com/python-pillow/Pillow/issues/3134?

**Comment by homm** [comment]
This can't ever be fixed due to backward compatibility. Think about this as a call convention. The only we can do is update documentation. Pull requests are welcome.

**Comment by radarhere** [comment]
The previous comment states that we should retain the current behaviour for backwards compatibility, whereas [an earlier comment on a different issue suggests that we change it](https://github.com/python-pillow/Pillow/issues/3134#issuecomment-390659123).

I'm more inclined to go with retaining the current behaviour - I don't think there's a neat way to transition users into reversing the operation, even with deprecation.

I've created PR #7204 to document this.
