### ISSUE TITLE
Double builds on Travis CI

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3681]
### What did you do?

Create a PR or merge a PR.

### What did you expect to happen?

A single build on Travis CI.

### What actually happened?

Two builds were queued.

https://travis-ci.org/python-pillow/Pillow/builds

![image](https://user-images.githubusercontent.com/1324225/53684752-fecf8380-3d19-11e9-8dab-d8f0a24860ce.png)

---

I asked on Travis CI forum and the (unofficial) answer was:

> I guess you have two references to Travis with the same purpose in your Github project’s intergration settings because of a recent migration: https://changelog.travis-ci.com/migration-completed-github-services-to-webhooks-88817 1 .
>
> The simplest way would be to delete all Travis-related integration entries and re-add your project in Travis UI.

This started around the time Travis CI was disabled (https://github.com/python-pillow/Pillow/issues/3589):

> Yeah, this looks related. If some integration entry stopped working, you added an updated one, then it started working again, you would end up in the current situation.

* https://travis-ci.community/t/double-builds-for-all-merges-and-prs/2316

---

@aclark4life I don't have access to https://github.com/python-pillow/Pillow/settings, please could you have another poke around? Thanks!

**Comment by aclark4life** [comment]
@hugovk OK I removed all our services since services are deprecated, does that help? Hopefully didn't break anything in the process.

**Comment by hugovk** [comment]
Hmm, I just made a PR but it still triggered a double build: 

![image](https://user-images.githubusercontent.com/1324225/53686040-17946500-3d2b-11e9-976a-7167e927a735.png)

https://travis-ci.org/python-pillow/Pillow/pull_requests

**Comment by aclark4life** [comment]
@hugovk Is it because we're telling it to build twice via these settings?

<img width="1680" alt="screenshot 2019-03-02 13 50 24" src="https://user-images.githubusercontent.com/72164/53686204-362a3a00-3cf2-11e9-8367-63fddf5f4f03.png">

**Comment by hugovk** [comment]
I don't think so, but let's wait and see what happens for the next merge, and if it's still doing double builds we can ask Travis again. Thanks for checking!

**Comment by hugovk** [comment]
It's still doing double builds for merges too: https://travis-ci.org/python-pillow/Pillow/builds

https://travis-ci.community/t/double-builds-for-all-merges-and-prs/2316/4 also suggested:

> The integration entries are in https://github.com/python-pillow/Pillow/settings, under “webhooks” and “services”. Only someone with appropriate permissions can see them.

Perhaps removing webhooks and services, then re-adding will help?

**Comment by aclark4life** [comment]
@hugovk Hah, perhaps it's that there are actually two Travis webhooks!! Services are gone:

<img width="1680" alt="screenshot 2019-03-03 17 34 25" src="https://user-images.githubusercontent.com/72164/53702993-b1671b00-3dda-11e9-9dbb-3156d3eb4a9c.png">

But checkout webhooks, "oops":

<img width="1680" alt="screenshot 2019-03-03 17 34 40" src="https://user-images.githubusercontent.com/72164/53702997-c5ab1800-3dda-11e9-9166-d13eea904ec2.png">

Removing the extra one now.

**Comment by hugovk** [comment]
That fixed it, thanks!

![image](https://user-images.githubusercontent.com/1324225/53823051-a4346280-3f79-11e9-9a0d-17c6ded0a181.png)
