### ISSUE TITLE
'TiffImageFile' object has no attribute 'use_load_libtiff'

### ISSUE THREAD

**Issue by eLvErDe** [python-pillow/Pillow#3690]
Hello,

When trying to save a TiffImage to BytesIO() object I get 'TiffImageFile' object has no attribute 'use_load_libtiff' error.

```
    image.save(buffer, format=image_format)
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 1960, in save
    self.load()
  File "/usr/lib/python3/dist-packages/PIL/TiffImagePlugin.py", line 1078, in load
    if self.use_load_libtiff:
AttributeError: 'TiffImageFile' object has no attribute 'use_load_libtiff'
```

* OS: Debian Stretch / MacOS something (both fails)
* Python: 3.5 or 3.6
* Pillow: 5.3.0 or 5.4.1

Changing Pillow TiffImagePlugin.py file like this, workarounds the issue

```python
    def load(self):
        #if self.use_load_libtiff:
        #    return self._load_libtiff()
        return super(TiffImageFile, self).load()
```

But that's obviously not suitable, in the meanwhile I dirty-patched my code like this

```python
            if isinstance(image, TiffImagePlugin.TiffImageFile):
                if not hasattr(image, "use_load_libtiff"):
                    image.use_load_libtiff = True
```

But this is still a crappy workaround. I really think there's something wrong in Pillow, load() method can be called on TiffImageFile instances without having use_load_libtiff attribute being set.

Thanks in advance,

**Comment by radarhere** [comment]
The following code works for me with Pillow 5.4.1 -

```python
from PIL import Image
import io
fp = io.BytesIO()
im = Image.open("Tests/images/hopper.tif")
im.save(fp, 'TIFF')

# Just to demonstrate that the contents are a correct TIFF
with open('check_contents.tiff', 'wb') as fp2:
	fp2.write(fp.getvalue())
```

So could you provide a self-contained code sample that demonstrate the problem?

**Comment by radarhere** [comment]
Feel free to comment, and this can be re-opened.

**Comment by mattpepin** [comment]
I can trigger the issue when trying to Pickle a TIFF Image (needed to save temporary session user data along with other data). The relevant stack trace:

```
6]:   File "/.venv/lib/python3.7/site-packages/PIL/Image.py", line 707, in __getstate__
6]:     self.getpalette(),
6]:   File "/.venv/lib/python3.7/site-packages/PIL/Image.py", line 1324, in getpalette
6]:     self.load()
6]:   File "/.venv/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 1076, in load
6]:     if self.use_load_libtiff:
6]: AttributeError: 'TiffImageFile' object has no attribute 'use_load_libtiff'
```

**Comment by mattpepin** [comment]
I fixed it by changing TiffImagePlugin.py:

```
    def load(self):
        if getattr(self, 'use_load_libtiff', False):
            return self._load_libtiff()
        return super(TiffImageFile, self).load()
```

**Comment by radarhere** [comment]
@mattpepin could you provide a self-contained code example to demonstrate the problem? So a simple block of code picking the TIFF? Also, what version of Pillow are you using?

**Comment by mattpepin** [comment]
> @mattpepin could you provide a self-contained code example to demonstrate the problem? So a simple block of code picking the TIFF? Also, what version of Pillow are you using?

I'll try to generate a small sample later this afternoon with latest Pillow. Our production server runs version 6.0.

**Comment by mattpepin** [comment]
Got it:

```
import pickle
from PIL import Image

with open('/tmp/image.tif', 'rb') as f:
    img = Image.open(f)
    s = pickle.dumps(img)
    img2 = pickle.loads(s)
    pickle.dumps(img2)
```

**Comment by matemax** [comment]
I have same problems. Object TiffimageFile has not attributes `_n_frames` and  `_is_animated`  after using asyncio function `run_in_executor` (this function use pickle for execution in sub processes). And method numpy.array(image) is broken

**Comment by radarhere** [comment]
@matemax while you may very well have the same root cause to your problem, could we have a self-contained code example, just so we will know when we have resolved your issue?

**Comment by matemax** [comment]
@radarhere example of @mattpepin reproduces the problem.

**Comment by Fover23** [comment]
I reproduces  the  problem.
I use pickle to serializer pillow's Image object and when use pickle.loads functions decode the object ,the Image object not work correct and arise the error as title is.
But I find something special the tiff file (the image I used)  has empty image extend infomation,no exif no device infomation ...

other infomations:
```
Pillow version: 6.0.0
Python verion: 3.7.2
platform: win10
```

**Comment by radarhere** [comment]
@Fover23 if you have a problem beyond the error mentioned, please create a new issue with more information, and ideally a script demonstrating the specific problem

**Comment by radarhere** [comment]
I've created PR #4565 to resolve this.
