### ISSUE TITLE
File descriptor closed after with block despite _exclusive_fp being False

### ISSUE THREAD

**Issue by Lonami** [python-pillow/Pillow#3694]
### What did you do?
```python
import PIL.Image

file = open('r.png', 'rb')
with PIL.Image.open(file) as image:
    print('Exclusive FP =', image._exclusive_fp)

try:
    file.read()
    print('OK')
except ValueError as e:
    print('BAD', e)
```

### What did you expect to happen?
```
Exclusive FP = False
OK
```

### What actually happened?
```
Exclusive FP = False
BAD read of closed file
```
### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7
* Pillow: 5.4.1

---

I believe this is what's causing https://github.com/LonamiWebs/Telethon/issues/1121. I can work around it by not using the `with` block:

```python
file = open('r.png', 'rb')
image = PIL.Image.open(file)
print('Exclusive FP =', image._exclusive_fp)

try:
    file.read()
    print('OK')
except ValueError as e:
    print('BAD', e)
```
...which shows OK, but it sounds like an issue here. Sorry if it's a duplicate, couldn't find anything similar.

**Comment by radarhere** [comment]
Thanks for reporting this. I've created #3698 to fix the problem.

**Comment by Lonami** [comment]
Thank you very much for looking into (and fixing!) it so quickly :)
