### ISSUE TITLE
Understanding resizing with Lanczos filter

### ISSUE THREAD

**Issue by YowanR** [python-pillow/Pillow#3706]
Hello everyone,

I am currently investigating the math between the resize function and I am unable to fully understand how it works. The function itself just calls im.resize(args), but I can't see how the python code connects to the c code and how the filter itself is used to resize the image. Can anyone help me in understanding this better, please?

Best,
Yowan

**Comment by radarhere** [comment]
As you have already determined, the `resize` function -
https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/PIL/Image.py#L1758

calls `im.resize` -

https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/PIL/Image.py#L1798-L1803

However, `im` in this context is not a `PIL.Image.Image` instance. It is an `ImagingCore` instance -

https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/PIL/Image.py#L93
https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/PIL/Image.py#L717
https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/_imaging.c#L3707-L3713

So `im.resize` is actually calling -
https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/_imaging.c#L3208
https://github.com/python-pillow/Pillow/blob/22ae782320741e4fab3197be261bce6b14f45478/src/_imaging.c#L1699-L1701

**Comment by radarhere** [comment]
As to how the filter is used to resize the image... I'm precisely sure what you're after, so please feel free to ask more questions, but perhaps you would interested in this article by @homm - https://blog.uploadcare.com/the-fastest-production-ready-image-resize-out-there-part-0-7c974d520ad9

**Comment by radarhere** [comment]
@YowanR do you feel that answers your questions?

**Comment by radarhere** [comment]
Feel free to comment and this can be reopened if there is anything more.
