### ISSUE TITLE
IOError: cannot identify image file 

### ISSUE THREAD

**Issue by essalahsouad** [python-pillow/Pillow#3727]
When I try to open a specific png file, Pillow gives me a "cannot identify image file" error.
```python
from PIL import Image
import os
for img in os.listdir('/home/dell/Bureau/myDataset/VOC2019/JPEGImages'):
    image= Image.open(img, mode='r')
    width, height = image.size
```
**Traceback**
`IOError: cannot identify image file 'S1179R01.jpg'`
the path
![Capture du 2019-03-19 13-07-24](https://user-images.githubusercontent.com/34586193/54604821-05fbce80-4a48-11e9-8140-745d8316ab4b.png)

**Comment by radarhere** [comment]
Hi. You're passing in just the filename to Pillow, and you're presumably not running this script from the JPEGImages directory. So I would suggest passing in the absolute path -

```python
from PIL import Image
import os
for img in os.listdir('/home/dell/Bureau/myDataset/VOC2019/JPEGImages'):
    image = Image.open(os.path.join('/home/dell/Bureau/myDataset/VOC2019/JPEGImages', img), mode='r')
    width, height = image.size
```

If that doesn't work - let's be clear, you would like to open a JPG, not a PNG, yes? Would you be able to attach one of the JPG files? What version of Pillow and Python are you using, and what operating system?

**Comment by essalahsouad** [comment]
@radarhere 
Thank you for your reply.  This is very helpful

**Comment by radarhere** [comment]
@essalahsouad is this issue resolved then?

**Comment by essalahsouad** [comment]
@radarhere 
yes,thank you.
