### ISSUE TITLE
Missing zlib on PyPy pip installing

### ISSUE THREAD

**Issue by matcool** [python-pillow/Pillow#3731]
### What did you do?
Try to install Pillow 5.4.1 on PyPy 3.6 / 3.7 on windows.
### What did you expect to happen?
For Pillow to be installed normally
### What actually happened?
I got the error:
```
    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html
```
### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: Tested on both PyPy 3.5.3 v7.0.0 and PyPy 3.6 v7.0.0
* Pillow: 5.4.1

**Comment by radarhere** [comment]
How did you try to install Pillow?

**Comment by matcool** [comment]
`pypy3 -m pip install pillow`

**Comment by hugovk** [comment]
Please can you show the full output of the pip command?

For Windows, we recommend installing using prebuilt binary wheels, which usually happens automatically. I suspect in your case it's defaulting back to attempting to build from source, which isn't the best idea on Windows.

You're using the new PyPy 7.0.0 which came out after our last release, and so it didn't get a wheel. 

https://pypi.org/project/Pillow/5.4.1/#files shows a Pillow-5.4.1-pp360-pp360-win32.whl, which I think is the 6.0.0 wheel. 

Two options:

1. Wait until 1st April for the next Pillow release
2. Try the unofficial wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow. For example, download Pillow‑5.4.1‑pp370‑pp370‑win32.whl and run:

`pypy3 -m pip install Pillow‑5.4.1‑pp370‑pp370‑win32.whl`

**Comment by matcool** [comment]
Installing from the unofficial wheel worked, thanks!

**Comment by C0rn3j** [comment]
I was installing via pip, so had to export the include lib before running pip. LDFLAGS was not necessary but leaving it here just in case.

```bash
export CFLAGS="-I/mingw64/include"
#export LDFLAGS="-L/mingw64/lib"
```
