### ISSUE TITLE
[minor] Pillow goals?

### ISSUE THREAD

**Issue by pirate486743186** [python-pillow/Pillow#3732]
In the documentation, the goals of pillow are .... to be a fork of PIL.
https://pillow.readthedocs.io/en/stable/about.html

That may be accurate, but it's not very informative.

**Comment by hugovk** [comment]
I don't follow, that page looks clear to me:

> Goals
> -----
> 
> The fork author's goal is to foster and support active development of PIL through:
> 
> - Continuous integration testing via Travis CI and AppVeyor
> - Publicized development activity on GitHub
> - Regular releases to the Python Package Index

**Comment by pirate486743186** [comment]
and whats PIL? You swallow it when you are sick?

**Comment by hugovk** [comment]
> Pillow is the friendly PIL fork by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.

https://pillow.readthedocs.io/
