### ISSUE TITLE
Text clipping arabic fonts

### ISSUE THREAD

**Issue by hsidky** [python-pillow/Pillow#3745]
### What did you do?
I used Pillow (5.4.1) to draw Arabic text onto a canvas using libraqm (0.5.0) 

### What did you expect to happen?

I expected the arabic text to be rendered without clipping. 

### What actually happened?

The text was clipped. 

<img width="225" alt="image" src="https://user-images.githubusercontent.com/7806885/54885080-7a6aaf00-4e46-11e9-8f1b-dd7659ee273d.png">

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04 
* Python: 3.6.8
* Pillow: 5.4.1

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
%matplotlib inline 
from PIL import Image, ImageDraw, ImageFont
import matplotlib.pyplot as plt

font = ImageFont.truetype('ArefRuqaa-Regular.ttf', 70)
canvas = Image.new('RGB', (128, 128), color='white')
draw = ImageDraw.Draw(canvas)
draw.text((0, 0), 'لح', 'black', font, layout_engine=ImageFont.LAYOUT_RAQM)
canvas.save('test.png', format='PNG')

plt.imshow(plt.imread('test.png'))
```

I am using the Aref-Ruqaa font. The exact version I am using is here:
https://github.com/alif-type/aref-ruqaa/blob/master/ArefRuqaa-Regular.ttf

Using `font.getsize('لح')` gives me `(29, 121)` but as you can see from the image above, while the text is `121` pixels high it is still clipped from the top. It is also clipped on the right side, even though there is an offset of `(-2, 46)`. 

So the dimensions are correct but the actual drawn text is clipped. I was informed that the font is cascading so font global metrics cannot be used reliably for clipping. 

Is there any way to correct this clipping? 

Thanks!

**Comment by radarhere** [comment]
This is likely related to #3235

**Comment by radarhere** [comment]
I've created PR #3864 to resolve this.
