### ISSUE TITLE
Python support for a Pleiade elaboration

### ISSUE THREAD

**Issue by planera63** [python-pillow/Pillow#3753]
Hello.

At moment I have ArcGIS and QGIS 5.3.

I have a pleiade image (RGB+NIR) and I need to elaborate this image to produce a new 
one from this procedure:

Ln = natural log

imgIn = file raster input “ file raster with radiance value (RGB + NIR)
imgOut = file raster output (double format) “ file raster with value of Depth_Index
Lb = Blue radiance (pixel value)
Lg = Green radiance (pixel value) 
Kbg = a numeric costant
Depth_Index = depth-invariant index

IF Lb.pixel.value > 0 “  OR  Lb >0 AND Lg.pixel.value > 0

Depth_Index = Ln(Lb) – Kbg*Ln(Lg) 

ENDIF

Someone could help me to write a python script for QGIS or a Arcpy script for ArcGIS ?
I think Pillow module is the right module, but I'm at the beginning of my experience with Python.

Thanks

**Comment by radarhere** [comment]
I don't actually think that Pillow is the right module for this. Googling, I would suggest that you look at rasterio - https://rasterio.readthedocs.io/en/stable/quickstart.html

**Comment by radarhere** [comment]
@planera63 did you make any progress with this?

**Comment by aclark4life** [comment]
@planera63 Please reopen if you still want us to take a look at this, thank you!
