### ISSUE TITLE
Anaconda ImportError

### ISSUE THREAD

**Issue by aneenaanna26** [python-pillow/Pillow#3755]
error :
```python
Traceback (most recent call last):
  File "C:\Users\HP\Desktop\Project\new program\PlantPathology\training.py", line 3, in <module>
    from PIL import Image
  File "C:\Users\HP\Anaconda3\envs\env3.6\lib\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: DLL load failed: The specified module could not be found.
```

I got this error when i used python 3.6.0 and pillow 5.4.1

**Comment by radarhere** [comment]
How did you install Pillow?

**Comment by aneenaanna26** [comment]
I'm using Anaconda3, so I installed it directly from Anaconda.

**Comment by radarhere** [comment]
I recommend looking at https://github.com/python-pillow/Pillow/issues/2945. Does anything in that discussion solve your issue?

**Comment by aneenaanna26** [comment]
No. I didn't get any help. It's not working for me.

**Comment by radarhere** [comment]
Okay. For the sake of readability in this thread, the ideas suggested there are -

- 'conda uninstall pillow' and then 'pip install pillow'
- 'conda install --channel conda-forge pillow=5.4.1'
- 'conda update conda'
- 'conda update --all'
- 'conda install -c anaconda pillow'
- Installing pywin32-ctypes

What specific version of Anaconda are you using?

**Comment by aneenaanna26** [comment]
I'm using Anaconda3 5.3.0.0

**Comment by radarhere** [comment]
What version of Windows are you using?

Another suggestion, this time from https://github.com/conda-forge/pillow-feedstock/issues/45, is 'conda remove pillow' and then 'pip install pillow'.

If you uninstall Pillow, and then try to `import PIL`, do you get `ModuleNotFoundError`? If not, then you have multiple Pillows installed. Try resolving this so that you only have one.

**Comment by aneenaanna26** [comment]
When I try to do import PIL, it shows error and it does not get installed.
Should I do "conda remove pillow" in conda or in the conda prompt??

**Comment by radarhere** [comment]
Could you include the error that you've just mentioned, and the command you ran to receive it?

While I'm not sure what you mean by your question, and not helped by the fact that I'm not using Anaconda or Windows, I would suggest the conda prompt.

**Comment by aneenaanna26** [comment]
Now I'm getting a Flask error for one program and PIL error for another
program... I'm attaching few screenshots which will help you understand
what I mean and help me. For Flask I did "conda install flask" and all the
modules and packages were installed but still it shows error.

**Comment by radarhere** [comment]
The screenshots didn't appear. Would you be able to try attaching them through the GitHub interface? I'm guessing you tried to attach them in a reply email.

**Comment by radarhere** [comment]
@aneenaanna26 any updates on this?

**Comment by kiwi0fruit** [comment]
I have this problem in Anaconda Python 3.6.8 and Pillow 6.0.0. But everything works OK wih Anaconda Python 3.7.2 and Pillow 6.0.0.

**Comment by kiwi0fruit** [comment]
Reinstalled the whole environment with Aaconda Python 3.7.3 and Pillow 6.0.0. Now it works OK.
