### ISSUE TITLE
Transforms and enhancements across all frames

### ISSUE THREAD

**Issue by pirate486743186** [python-pillow/Pillow#3758]
It would be nice if transforms and enhancements could be applied on animations.

**Comment by radarhere** [comment]
What sort of transforms and enhancements?

**Comment by pirate486743186** [comment]
for example.
https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#geometrical-transforms

https://pillow.readthedocs.io/en/stable/handbook/tutorial.html#image-enhancement

**Comment by radarhere** [comment]
So when you say that you'd like them to be applied on animations, what you mean is that you'd like to be able to apply them across all frames of an image at once?

**Comment by pirate486743186** [comment]
yes. It seams to me that a lot of application would want a functionality like that.

**Comment by radarhere** [comment]
Okay. What about a generic way to apply a method to all frames of an image?

So, for example -

```python
from PIL import Image, ImageSequence
im = Image.open('Tests/images/g4-multi.tiff')
ims = ImageSequence.all_frames(im, lambda im_frame: im_frame.rotate(180))
ims[0].save('out.tiff', save_all=True, append_images=ims[1:])
```

I've created this in PR #3778

**Comment by pirate486743186** [comment]
lol, i was expecting a solution to this in....~5-10 years XD

**Comment by aclark4life** [comment]
@radarhere is that good 😄
