### ISSUE TITLE
Compatibility with Python 3.8?

### ISSUE THREAD

**Issue by gotexis** [python-pillow/Pillow#3763]
Hi is the master branch working for 3.8 yet?

**Comment by hugovk** [comment]
It's not officially supported yet for things like binary releases, but it's [tested on Travis CI](https://github.com/python-pillow/Pillow/pull/3648) and we've fixed some [deprecations](https://github.com/python-pillow/Pillow/pull/3123). Official support will likely come after Python 3.8.0 is out ([expected 2019-10-21](https://www.python.org/dev/peps/pep-0569/#release-schedule)).

Feel free to try it out, and please let us know if you find anything amiss.

**Comment by gotexis** [comment]
Hey :)

Yeah, I actually got this message 

"Pillow does not yet support Python 3.8 and does not yet provide prebuilt Windows binaries. We do not recommend building from source on Windows."

Hmm, I guess this is it?

I wanted to use the Walrus operator `:=` to save like 2 lines of code but end up having to put python in Docker and compile Pillow myself ;)

I guess, No Walrus operator for me for another months XD

**Comment by hugovk** [comment]
Yep, that's the one.

**Comment by cgohlke** [comment]
I uploaded Pillow‑6.0.0‑cp38 wheels for Windows at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow
