### ISSUE TITLE
Saving bitonal TIFF without compression has no BitsPerSample tag

### ISSUE THREAD

**Issue by photosbyjeremy** [python-pillow/Pillow#3766]
### What did you do?
Saved a bitonal TIFF, loaded the saved image, then printed its BitsPerSample tag with ```print(image.tag_v2[258])```

### What did you expect to happen?
To receive the output: ```(1, )```

### What actually happened?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jeremy/miniconda3/envs/pillow_test/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 532, in __getitem__
    data = self._tagdata[tag]
KeyError: 258
```

### What are your OS, Python and Pillow versions?

* OS: macOS 10.14.3
* Python: 3.7.3 (conda)
* Pillow: 6.0.0 (installed with Pip)

**Code below**
```
from PIL import Image
image = Image.new(mode='1', size=(1000,1000))
image.save('test1.tif')
image1 = Image.open('test1.tif')
image1.tag_v2[258]
```

If I save the image with Group4 or LZW compression then it works as expected:
```
image.save('test2.tif', compression='group4')
image2 = Image.open('test2.tif')
image2.tag_v2[258]
image.save('test3.tif', compression='LZW')
image3 = Image.open('test3.tif')
image3.tag_v2[258]
```

Saving the image with ```compression=None``` throws the same key error
```
image.save('test4.tif', compression=None)
image4 = Image.open('test4.tif')
image4.tag_v2[258]
```

I checked the tags of image1 (compression not set) and image2 (group4 compression) and only tag 258 is missing:
<img width="626" alt="Screen Shot 2019-04-02 at 3 56 36 PM" src="https://user-images.githubusercontent.com/5132339/55432072-fb6d2900-555f-11e9-9e59-cd22e1e6dfd9.png">

**Comment by photosbyjeremy** [comment]
I did test, and there's no problem with rgb and grayscale images like with bitonal.

<img width="626" alt="Screen Shot 2019-04-02 at 4 17 25 PM" src="https://user-images.githubusercontent.com/5132339/55433190-cf06dc00-5562-11e9-9a32-671b115dffb4.png">

**Comment by radarhere** [comment]
This behaviour is the result of this condition - https://github.com/python-pillow/Pillow/blob/5a2ecd13ddf7f4f57ebb687600ecf710caf413ce/src/PIL/TiffImagePlugin.py#L1474-L1475

Using compression triggers libtiff, which presumably adds the value in the line -
https://github.com/python-pillow/Pillow/blob/5a2ecd13ddf7f4f57ebb687600ecf710caf413ce/src/PIL/TiffImagePlugin.py#L1513

The condition has been there since PIL. It's deliberate, not accidental. Why do you feel that the value should be present?

**Comment by photosbyjeremy** [comment]
Reading the TIFF 6.0 spec it's not a required tag for bitonal images, so I'll change my code to reflect either a KeyError or BITSPERSAMPLE of 1: 
<img width="1005" alt="Screen Shot 2019-04-09 at 5 41 50 PM" src="https://user-images.githubusercontent.com/5132339/55837241-ce37f200-5aee-11e9-995d-19715a0854fa.png">

**Comment by radarhere** [comment]
Thanks
