### ISSUE TITLE
Compressed GeoTiff with GDAL no longer plotting with version 6.0.0

### ISSUE THREAD

**Issue by jomey** [python-pillow/Pillow#3770]
### What did you do?
Plotting an image with matplotlib `imshow()` broke with version 6.0.0

I have a compressed (LZW) GeoTiff that was produced by GDAL (v 2.4.1, released 2019/03/15). After upgrading from Pillow 5.4.1. to 6.0.0 the background image for a plot was no longer plotting properly.

### What are your OS, Python and Pillow versions?

* OS: Mac OS X and Linux
* Python: 3.7.3
* Pillow: 6.0.0

Code to reproduce:
```python
# Python 3.7.3 | packaged by conda-forge | (default, Mar 27 2019, 15:43:19) 
import matplotlib.pyplot as plt
plt.figure()
plt.imshow(plt.imread('/Path/To/sample.tiff'))
plt.show()
```

## With Pillow 5.4.1
![pillow-5 4 1](https://user-images.githubusercontent.com/178649/55593022-a6fcb180-56f7-11e9-97a1-6072a7c56e85.png)

## With Pillow 6.0.0
![pillow-6](https://user-images.githubusercontent.com/178649/55593027-b0861980-56f7-11e9-816e-0fcd9a4ef07e.png)

Used image: [sample.tif.zip](https://github.com/python-pillow/Pillow/files/3045702/sample.tif.zip)

## Compressed with GDAL (2.4.1):
```
gdal_translate -co COMPRESS=LZW -co TILED=YES -co BIGTIFF=IF_SAFER -co NUM_THREADS=ALL_CPUS -co COPY_SRC_OVERVIEWS=YES
```

**Comment by jomey** [comment]
The image plots properly in version 6.0.0 again when removing the compression via `gdal_translate`

**Comment by radarhere** [comment]
Testing, I find that this relates to #3489
