### ISSUE TITLE
 No preview of .ico file on Windows 10

### ISSUE THREAD

**Issue by MagTun** [python-pillow/Pillow#3773]
### What did you do and what did you expect to happen?
I ran this code and tried to preview the `.ico` file created in Windows folder explorer, Windows Photo Viewer and  Windows Photo: 
```python
from PIL import Image
img = Image.new('RGB', (50, 50), color = (130, 173, 242))  
img.save('pillow.ico')
```
### What actually happened?
Although I can preview others `.ico` files on my computer, I can't preview the  `.ico` created by Pillow  (the file on the left is an `.ico` created by pillow, the one on the right is "genuine" `ico`)

- Windows folder explorer
![2019-04-05_18-02-08_explorer](https://user-images.githubusercontent.com/15843700/55640942-f6f97800-57cc-11e9-8488-d56a95b3d90c.png)

- Windows Photo Viewer  
![2019-04-05_17-55-58_explorer](https://user-images.githubusercontent.com/15843700/55640583-3b384880-57cc-11e9-9ad6-f29ef65db6e2.png)

- Windows Photo
![2019-04-05_17-55-09_explorer](https://user-images.githubusercontent.com/15843700/55640593-40959300-57cc-11e9-97db-89748cef4d82.png)

It was tested on 2 computers (same OS, Python and Pillow versions)
I can preview the `.ico` if I drag them in chrome. I can also preview them if I load them as an icon for a systray app. 

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python:  3.6
* Pillow:   5.1.0

**Comment by radarhere** [comment]
Could you upload an ICO file that previews correctly, and the Pillow generated one that doesn't?

**Comment by MagTun** [comment]
Here is a [link ](https://drive.google.com/open?id=1_ppImgx4S7riMuBfNpWUJmBwF4J5z6U9)to the `.ico`. `pillow.ico` is the one that isn't working, `190.ico` is the one that is working (it comes from Windows shell32.dll) 

I can see the preview of the ico in google drive but I am still unable to see them in Windows folder explorer, Windows Photo Viewer, Windows Photo.

**Comment by radarhere** [comment]
Thanks. Looking at the two files, pillow.ico has the sizes (16, 16), (24, 24), (32, 32) and (48, 48), while 190.ico just has (40, 40).

My guess is that the problem you are seeing is due to the lack of 40x40 size in the Pillow image. I have generated two images, one with an additional (40, 40), and one without. Could you test and report back if 'pillow_without40x40.ico' fails and 'pillow_with40x40.ico' previews correctly?

[40x40.zip](https://github.com/python-pillow/Pillow/files/3167927/40x40.zip)

**Comment by MagTun** [comment]
I downloaded your images and I can't preview any of them. I also tried your code, the image are created, the printed size are correct but I still can't preview them. 

When I create `.ico` with several size in 1 file on this [website](https://icoconvert.com/image_to_icon_converter/), I don't have any problem previewing the file. So I think the problem comes from somewhere else.

**Comment by nulano** [comment]
Using your original code, I can see a preview in Windows Explorer, but not in Windows Photo Viewer.

Using mode `RGBA` I can't reproduce this (the icon is always visible):

```python
from PIL import Image
original = Image.new('RGBA', (50, 50), color = (130, 173, 242))  
original.save('pillow.ico')
```

**Comment by MagTun** [comment]
Yes this is working! Why does changing the color mode fix this?

**Comment by nulano** [comment]
Windows has very specific requirements on ICO files, one of them being the
RGBA color mode.

**Comment by MagTun** [comment]
Would it be possible for `pillow `to automatically convert `ICO `file to `RGBA `? (or at least to add a comment in the console when we uses `RGB ` with `ICO` so that we know it's better to use `RGBA`)

**Comment by nulano** [comment]
I wasn't home when you asked earlier, so here's a quote from [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/uxguide/vis-icons) (scroll almost to the end, under step 5 of subheading Icon Development):

> Icon (.ico format) files must contain the 4- and 8-bit versions, as well as the 24-bit + alpha.

This to me suggests that RGB is a perfectly valid mode for image frames, but Windows will ignore it and look for a different frame.

Pillow currently doesn't support saving a single ICO file with multiple different image modes. Perhaps it would be a good idea to add automatic conversion to RGBA.

**Comment by radarhere** [comment]
The Microsoft document you linked to talks about creating icons for Windows application, but this isn't the only application of the ICO format - there are also favicons. If there are users happily creating ICO files for favicons, I don't think their result needs to be changed - is a good alternative for a note to be made in the Pillow documentation instead?

**Comment by nulano** [comment]
I just tried this in Internet Explorer 11 and Microsoft Edge and both just show an error box for RGB, but render correctly with RGBA.

Whether or not automatic mode conversion is added, I think there should definitely be a note in the docs; it should also mention, that the current Pillow implementation saves ICOs as PNGs internally, not DIBs (support was only added in Windows Vista).

**Comment by radarhere** [comment]
> Windows has very specific requirements on ICO files, one of them being the RGBA color mode.

Searching for documentation to support this, I find http://interface.free.fr/Archives/GUI_Xp.pdf that does seem to indicate that Windows jumped right over 24-bit to 32-bit.
Perhaps better is https://docs.microsoft.com/en-gb/windows/win32/uxguide/vis-icons?redirectedfrom=MSDN
> Only a 32-bit copy of the 256x256 pixel image should be included
