### ISSUE TITLE
Pillow cannot read from array gray image?

### ISSUE THREAD

**Issue by zjplab** [python-pillow/Pillow#3781]
I have a pic:
![391](https://user-images.githubusercontent.com/16349466/55764637-73dd5980-5a3a-11e9-8395-76e7eebac6fe.jpg)

Do some conversion:

```python
AB = Image.open("./391.jpg").convert('RGB')
arr=np.array(AB)
gray=arr@np.array([0.2125, 0.7154, 0.0721]) # gray scale now 
```
Whatever mode you use, it just looks like fucked up:
![image](https://user-images.githubusercontent.com/16349466/55764777-0251db00-5a3b-11e9-81ec-50e3f2fcb7eb.png)

But if you use `scipy.misc.toimage`
it is still usable:
![image](https://user-images.githubusercontent.com/16349466/55764950-899f4e80-5a3b-11e9-999a-54e1cfe6c8af.png)

I don't know how. Just very strange

**Comment by radarhere** [comment]
Taking your code, I find that `fromarray` with L looks as you described, but if I omit the mode, it looks fine. Does this look okay for you? If not, what operating system and Pillow version are you using?

```python
import numpy as np
from PIL import Image

AB = Image.open("im.jpg")
arr=np.array(AB)
arr=arr@np.array([0.2125, 0.7154, 0.0721])

# I agree that this does not look good
im = Image.fromarray(arr, 'L')

# This looks fine however
im = Image.fromarray(arr)

im.convert('RGB').save('out.jpg')
```

**Comment by zjplab** [comment]
@radarhere This is very strange since `fromarray` by default should read data as `RGB`. I checked the code from scipy.misc.toimage they use a different way to circumvent this bug:
`
    if len(shape) == 2:
        shape = (shape[1], shape[0])  # columns show up first
        if mode == 'F':
            data32 = data.astype(numpy.float32)
            image = Image.frombytes(mode, shape, data32.tostring())
            return image
        if mode in [None, 'L', 'P']:
            bytedata = bytescale(data, high=high, low=low,
                                 cmin=cmin, cmax=cmax)
            image = Image.frombytes('L', shape, bytedata.tostring())
            if pal is not None:
                image.putpalette(asarray(pal, dtype=uint8).tostring())
                # Becomes a mode='P' automagically.
            elif mode == 'P':  # default gray-scale
                pal = (arange(0, 256, 1, dtype=uint8)[:, newaxis] *
                       ones((3,), dtype=uint8)[newaxis, :])
                image.putpalette(asarray(pal, dtype=uint8).tostring())
            return image
        if mode == '1':  # high input gives threshold for 1
            bytedata = (data > high)
            image = Image.frombytes('1', shape, bytedata.tostring())
            return image
        if cmin is None:
            cmin = amin(ravel(data))
        if cmax is None:
            cmax = amax(ravel(data))
        data = (data*1.0 - cmin)*(high - low)/(cmax - cmin) + low
        if mode == 'I':
            data32 = data.astype(numpy.uint32)
            image = Image.frombytes(mode, shape, data32.tostring())
        else:
            raise ValueError(_errstr)
        return image
`

**Comment by radarhere** [comment]
'`fromarray` by default should read data as `RGB`' - What leads you to this conclusion?

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray

> mode – Mode to use (will be determined from type if None) See: Modes.

scipy's `toimage` doesn't even read it as RGB by default, it reads it as L.

```python
>>> import numpy as np
>>> import scipy.misc
>>> from PIL import Image
>>> AB = Image.open("391.jpg").convert('RGB')
>>> arr=np.array(AB)
>>> gray=arr@np.array([0.2125, 0.7154, 0.0721]) # gray scale now 
>>> scipy.misc.toimage(gray).mode
'L'
```

I'm confused. Could you clarify what you are after in this issue? Do you feel that `Image.fromarray(arr, 'L')` should work, and are asking why is does not?

**Comment by zjplab** [comment]
@radarhere Yes I used `scipy.misc.toiamge` in my code and I issued this just because I think `Image.fromarray(arr, 'L')` should work(many users might think this way too) but it does not.

**Comment by jgodwin** [comment]
Here's an even simpler example that triggers this behavior:
``
import numpy as np
x = np.tile(np.arange(0,100).reshape(-1,1),300)
Image.fromarray(x,mode='L').show()
``

Should get this (with scipy.misc.toimage): 
![image](https://user-images.githubusercontent.com/379511/59883121-4b92a500-9371-11e9-8f8c-05004e7fe83d.png)

Instead get this:
![image](https://user-images.githubusercontent.com/379511/59883138-5b11ee00-9371-11e9-8bd9-37c1dced9259.png)

**Comment by dettmar** [comment]
Having been dealing with similar problems for a whole day, I realized that the issue was resolved by tacking on `.astype(np.uint8)` to your array before passing it into `Image.fromarray()`, as such:
```
AB = Image.open("im.jpg")
arr=np.array(AB)
arr=arr@np.array([0.2125, 0.7154, 0.0721])
im = Image.fromarray(arr.astype(np.uint8), 'L')
```
or
```
x = np.tile(np.arange(0,100).reshape(-1,1),300)
Image.fromarray(x.astype(np.uint8), mode='L').show()
```

**Comment by radarhere** [comment]
Regarding the original image, it is an RGB image.

```python
from PIL import Image
AB = Image.open("391.jpg")
print(AB.mode)  # RGB
```

If you try to apply `fromarray()` to this using "L",
```python
import numpy as np
from PIL import Image

AB = Image.open("391.jpg")
arr=np.array(AB)
im = Image.fromarray(arr, "L")
```
you get `ValueError: Too many dimensions: 3 > 2`. L is a single channel image, with two dimensions, width and height. RGB is a three channel image, and so has a third dimension.

However, you've used the following line.
```python
gray=arr@np.array([0.2125, 0.7154, 0.0721]) # gray scale now 
```
Before this, the "typestr" of the NumPy array is "|u1". The above line turns it into "<f8". If the `mode` argument is not given when using `fromarray`, then Pillow observes that the ["typestr" of the NumPy array is "<f8"](https://github.com/python-pillow/Pillow/blob/6c7d6cf4a97b2dbbbd2c928a29ea0204a7f3c697/src/PIL/Image.py#L3069-L3075), which is [an F image.](https://github.com/python-pillow/Pillow/blob/6c7d6cf4a97b2dbbbd2c928a29ea0204a7f3c697/src/PIL/Image.py#L3142) If you would like `fromarray()` to correctly understand the image as an L mode image, then it should have only one channel and ["typestr" should be kept as "|u1"](https://github.com/python-pillow/Pillow/blob/6c7d6cf4a97b2dbbbd2c928a29ea0204a7f3c697/src/PIL/Image.py#L3130)

Pillow is internally calling `arr.tobytes()`, and then stepping over each row. It's not trying to interpret each value in the array in sequence. So if the data isn't related to the mode in a meaningful way, then the final image will not be meaningful.

In the second image, the array has a "typestr" of "<i8". This isn't [a type that Pillow supports.](https://github.com/python-pillow/Pillow/blob/6c7d6cf4a97b2dbbbd2c928a29ea0204a7f3c697/src/PIL/Image.py#L3126-L3150)

`Image.fromarray(arr.astype(np.uint8), 'L')` is certainly a solution, converting the NumPy data to a form that Pillow will understand. However, I stand by my original note on the first image that `Image.fromarray(arr)` works. If you would like it to be an L mode image afterwards, `Image.fromarray(arr).convert('L')` will take care of that.

From what I see above, scipy is calling `astype` internally. So why doesn't Pillow also do that, to match the `mode` parameter?

https://github.com/python-pillow/Pillow/issues/2856#issuecomment-345688646
> My impression of this parameter (which, tbh, is not well documented) is that it's for overriding the mode that's detected from the dtype. Raising an error where it doesn't match is going to be problematical for the intended use case.

If the idea is that it is to override the detected mode, then automatically converting data to match the mode will break backwards compatibility.
