### ISSUE TITLE
Some jpg-images cannot be read

### ISSUE THREAD

**Issue by nkoerb** [python-pillow/Pillow#3784]
When I try to read an image I get the following error:

```
from PIL import Image
im = Image.open('..\\WikiArt\\915.jpg')
```
_local variable 'photoshop' referenced before assignment_

I think the error is in 
https://github.com/python-pillow/Pillow/blob/master/src/PIL/JpegImagePlugin.py

line 139,  the indentation should be inside the if-statement

### What are your OS, Python and Pillow versions?

* OS: win10
* Python:  3.6
* Pillow: 6.0.0

wikiart-915.jpg:
![915](https://user-images.githubusercontent.com/47297576/55825336-131b5300-5b06-11e9-8d32-49a477129417.jpg)

**Comment by nulano** [comment]
This is probably a duplicate of #3769 and #3772, fixed by #3771.

**Comment by nkoerb** [comment]
Thank you!

**Comment by jschierl** [comment]
Indented this line and it worked. Thanks!!

**Comment by klory** [comment]
> Indented this line and it worked. Thanks!!

What do you mean by indent?
