### ISSUE TITLE
Support for variable fonts?

### ISSUE THREAD

**Issue by jansindl3r** [python-pillow/Pillow#3789]
Hi, <br>
are you planning to support variable fonts? Would be a great feature allowing people to work with it. DrawBot is the only Python tool that supports it as far as I know - Mac only, it has some dependencies. Most reliable for others on other platforms is recording it from Google Chrome and that the way I do it as well.  

https://en.wikipedia.org/wiki/Variable_fonts

**Comment by radarhere** [comment]
I've created PR #3802 for this. If you could give it a look, that could be good.

**Comment by jansindl3r** [comment]
> I've created PR #3802 for this. If you could give it a look, that could be good.

Thanks, looking forward. As a potentional user and designer I wanted to test it, but it seems that I am too lame to build it from source.

**Comment by radarhere** [comment]
@jansindl3r what operating system do you use?

**Comment by jansindl3r** [comment]
@radarhere Win7

**Comment by radarhere** [comment]
Courtesy of AppVeyor, here are some [builds](https://github.com/python-pillow/Pillow/files/3186620/builds.zip) of the PR that you should be able to use.
