### ISSUE TITLE
Testsuite fails on alpine linux s390x

### ISSUE THREAD

**Issue by ncopa** [python-pillow/Pillow#3798]
### What did you do?

Tried to rebuild the alpine linux py-pillow package with python 3.7

### What did you expect to happen?

Successful build and successful testsuite run

### What actually happened?
````
Tests/test_imagefont.py::TestImageFont::test_multiline_spacing FAILED                                          [ 81%]

====================================================== FAILURES ======================================================
________________________________________ TestImageFont.test_multiline_spacing ________________________________________

self = <test_imagefont.TestImageFont testMethod=test_multiline_spacing>

    def test_multiline_spacing(self):
        ttf = self.get_font()
    
        im = Image.new(mode='RGB', size=(300, 100))
        draw = ImageDraw.Draw(im)
        draw.multiline_text((0, 0), TEST_TEXT, font=ttf, spacing=10)
    
        target = 'Tests/images/multiline_text_spacing.png'
        target_img = Image.open(target)
    
        # Epsilon ~.5 fails with FreeType 2.7
>       self.assert_image_similar(im, target_img, self.metrics['multiline'])

Tests/test_imagefont.py:267: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 

self = <test_imagefont.TestImageFont testMethod=test_multiline_spacing>
a = <PIL.Image.Image image mode=RGB size=300x100 at 0x7F14F42FE9D0>
b = <PIL.PngImagePlugin.PngImageFile image mode=RGB size=300x100 at 0x7F14F42FEC10>, epsilon = 0.5, msg = None

    def assert_image_similar(self, a, b, epsilon, msg=None):
        epsilon = float(epsilon)
        self.assertEqual(
            a.mode, b.mode,
            msg or "got mode %r, expected %r" % (a.mode, b.mode))
        self.assertEqual(
            a.size, b.size,
            msg or "got size %r, expected %r" % (a.size, b.size))
    
        a, b = convert_to_comparable(a, b)
    
        diff = 0
        for ach, bch in zip(a.split(), b.split()):
            chdiff = ImageMath.eval("abs(a - b)", a=ach, b=bch).convert('L')
            diff += sum(i * num for i, num in enumerate(chdiff.histogram()))
    
        ave_diff = float(diff)/(a.size[0]*a.size[1])
        try:
            self.assertGreaterEqual(
                epsilon, ave_diff,
                (msg or '') +
                " average pixel value difference %.4f > epsilon %.4f" % (
                    ave_diff, epsilon))
        except Exception as e:
            if HAS_UPLOADER:
                try:
                    url = test_image_results.upload(a, b)
                    logger.error("Url for test images: %s" % url)
                except Exception:
                    pass
>           raise e
E           AssertionError:  average pixel value difference 6.1854 > epsilon 0.5000

Tests/helper.py:154: AssertionError
================================= 1 failed, 964 passed, 68 skipped in 21.24 seconds ==================================
````

### What are your OS, Python and Pillow versions?

* OS: Alpine linux edge (rolling release) x86, x86_64 and ppc64le
* Python: 3.7.3
* Pillow: 5.4.1

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
code goes here
```

**Comment by radarhere** [comment]
Would you be able to update to Pilow 6.0.0, and try again? I would guess that this is failing with freetype 2.10.0, and Pillow 6.0.0 includes an update for that.

**Comment by ncopa** [comment]
seems like tests fails on s390x: https://build.alpinelinux.org/buildlogs/build-edge-s390x/main/py-pillow/py-pillow-6.0.0-r0.log

**Comment by tuan-hoang1** [comment]
It seems it fails on s390x in general on both Ubuntu and Fedora.

**Comment by tuan-hoang1** [comment]
I believe it relates to : https://github.com/python-pillow/Pillow/issues/1204

**Comment by radarhere** [comment]
Interestingly, we now have separate alpine and s390x jobs in our testing matrix, and they pass for this test.

**Comment by radarhere** [comment]
Note that the linked log in an [earlier comment](https://github.com/python-pillow/Pillow/issues/3798#issuecomment-485388305) no longer works.

**Comment by radarhere** [comment]
In Pillow master, we have now dropped support for FreeType 2.7, and updated the test image that is failing here.

If I try and run [alpine s390x in Docker](https://github.com/radarhere/docker-images/commit/5e3822eb530f68b7960ffa34117738a12144911f), it only has [1 failing test.](https://github.com/radarhere/docker-images/runs/4159065976)

That's a timeout failure though, and I don't think it's due to a problem, but just because emulation is slow. [Increasing the timeout to 10s](https://github.com/radarhere/docker-images/commit/a70726fb2eae69b512e22d99c9db6a5d0e3f85aa) allows it to [pass.](https://github.com/radarhere/docker-images/runs/4159102982)

So unless anyone says that they're still experiencing this problem, I don't think there's anything more to do here.
