### ISSUE TITLE
numpy->bytes->Image failed and output OSError: cannot identify image file 

### ISSUE THREAD

**Issue by Ethanwl** [python-pillow/Pillow#3799]
Both systems' results are the same:
Windows10 python3.7 pillow6.0.0 opencv3.4.1
Ubuntu16.04 python3.5.2 pillow5.4.1 opencv4.0.0

```python
import cv2 
from PIL import Image
from io import BytesIO

img = cv2.imread('img.jpg')
img_bytes = img.tobytes()

bytesdata = BytesIO(img_bytes)
image = Image.open(bytesdata)
```
Above codes output:OSError: cannot identify image file <_io.BytesIO object at 0x0000025AA4036AF0>
Below codes run successfully.
```python
import cv2 
from PIL import Image
from io import BytesIO

with open('img.jpg', 'rb') as img:
    img_bytes = BytesIO(img.read())
    image = Image.open(img_bytes)
```
I want to send pictures via http. I don't want to open picture from file directly. I use opencv to read picture, do some changes and then send picture as bytes format. But the receiver can't get the picture successfully. How to solve it? Thank you!

**Comment by radarhere** [comment]
```python
import cv2 
from PIL import Image
from io import BytesIO

img = cv2.imread('img.jpg')
img_bytes = cv2.imencode('.jpg', img)[1]

bytesdata = BytesIO(img_bytes)
image = Image.open(bytesdata)
```

**Comment by Ethanwl** [comment]
It works well. Thanks!
