### ISSUE TITLE
Feature Request: LittleCMS Support

### ISSUE THREAD

**Issue by tenberg** [python-pillow/Pillow#3803]
I was just curious about littlecms support in Pillow. One of the issues I’ve found with switching from Matlab to Python is ICC profile support. I happened to come across https://pypi.org/project/littlecms/ and I was able to get it working on MacOS Mojave. It hasn’t been updated in awhile (I had some issues getting it to install on a Mac), but I modified a few lines in setup.py and got it working now. John Jefferies was helpful in helping me out with the issues. I have some example files and code for testing if you would like them as a starting point.

Knowing that Pillow has some ICC profile functionality, although it’s more image based, is this something that you would consider adding/supporting through Pillow?

**Comment by radarhere** [comment]
Hi. Are you aware of https://pillow.readthedocs.io/en/stable/_modules/PIL/ImageCms.html?highlight=littlecms? Or have I not understand that you are asking for more specific functionality?

**Comment by radarhere** [comment]
Closing, as it looks like we already have this functionality. Feel free to comment if you have other thoughts, and this can be re-opened.
