### ISSUE TITLE
Small terminology mixup

### ISSUE THREAD

**Issue by lucbloom** [python-pillow/Pillow#3813]
On this page: https://pillow.readthedocs.io/en/3.1.x/reference/Image.html
With this function: `Image.convert`
It states: `When translating a color image to black and white (mode “L”), ...`
Technically, it's not "black and white", but grayscale. You could say "grayscale (black and white)".
Why I'm nitpicking: This confused me. I thought for a short moment, "L" was 1-bit.

**Comment by radarhere** [comment]
You are reading an old version of the documentation. The current version - https://pillow.readthedocs.io/en/stable/reference/Image.html - states

> When translating a color image to greyscale (mode “L”)

**Comment by hugovk** [comment]
Closing as duplicate, but thanks for the report!
