### ISSUE TITLE
Why can't PIL load an Indonesian font file?

### ISSUE THREAD

**Issue by nyanmn** [python-pillow/Pillow#3816]
I used ImageFont from PIL to load Indonesia Font shown in the [link](https://www.dropbox.com/sh/k0a0in932xo8p0u/AABGovbsBV_hsYwoKS8A1Srsa?dl=0).

The font is loaded as follow.
```python
font = ImageFont.truetype(fontpath, int(fontsize))
```

fontpath is the path to Indonesia License Plate.ttf

Then write font as follows.

```python
org_pil = Image.fromarray(org)
draw = ImageDraw.Draw(org_pil)
for idx,alp in enumerate(text):
        w,h = font.getsize(alp)
        xpt=boxes[idx][0]+(boxes[idx][2]/2)-(w/2)
        ypt=boxes[idx][1]+(boxes[idx][3]/2)-(h/2)-1
        draw.text((int(xpt),int(ypt)), alp, font=font, fill=(b, g, r, a))
org=np.array(org_pil)
```
Nothing is written on the image.
Tested with other fonts was ok.
What could be wrong?

**Comment by radarhere** [comment]
On my Mac, the font failed validation by the operating system with '3 serious errors were found. Do not use these font files.'

So I'm inclined to think that the answer to your question is that the font is corrupt.

**Comment by nyanmn** [comment]
Thanks for the quick response. All Indonesia license plate.ttf found have same issue.

**Comment by radarhere** [comment]
Take the font, and run it through https://font-converter.net/. I think you will find that it works after that.

**Comment by nyanmn** [comment]
Yes it works. Thanks a lot.

**Comment by nyanmn** [comment]
It is closed now.
