### ISSUE TITLE
On Windows, opening a TIFF with a pathlib.Path argument fails

### ISSUE THREAD

**Issue by anntzer** [python-pillow/Pillow#3823]
### What did you do?

1. Create a tiff file (e.g. `from pylab import *; savefig("test.tiff")` using matplotlib).
2. Try to load it with Pillow, passing the path as pathlib.Path: `from PIL import Image; from pathlib import Path; Image.open(Path("test.tiff")).tobytes()`

### What did you expect to happen?

The image is correctly loaded (the same as `Image.open("test.tiff").tobytes()`; using a pathlib.Path also works just fine on Linux).

### What actually happened?

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "...\Miniconda3\lib\site-packages\PIL\Image.py", line 746, in tobytes
    self.load()
  File "...\Miniconda3\lib\site-packages\PIL\TiffImagePlugin.py", line 1078, in load
    return super(TiffImageFile, self).load()
  File "...\Miniconda3\lib\site-packages\PIL\ImageFile.py", line 177, in load
    self.map = Image.core.map(self.filename)
TypeError: argument 1 must be str, not WindowsPath
```

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7
* Pillow: 6.0.0

**Comment by radarhere** [comment]
I wasn't able to replicate this on AppVeyor. I don't suppose you could say if you're only experiencing this on Windows 10, and not Windows 7?

Also, while you would think this should be easy to reproduce in the right environment, could you provide a script from start to end, attaching a file if necessary, without matplotlib?

**Comment by anntzer** [comment]
```
from pathlib import Path
from PIL import Image

Image.new("RGBA", (100, 100)).save("test.tiff")
Image.open(Path("test.tiff")).tobytes()
```
reproes the bug for me.

I don't have readily access to a win7 machine with python.

This Pillow install is from PyPI, fwiw.

**Comment by radarhere** [comment]
Thanks. I've created PR #3825 to resolve this.
