### ISSUE TITLE
'ValueError: unknown raw mode' when converting large TIF file

### ISSUE THREAD

**Issue by anpr** [python-pillow/Pillow#3828]
### What did you do?

I tried to open [this large TIF file](https://umg-public-image-bucket.s3-eu-west-1.amazonaws.com/alp-1978-big-tif.tif) with Pillow 6.1.0 (sha 0e36b288dd9d7e932afeda5c01548d04baa9f93b) in the following way:
```python
from PIL import Image
image = Image.open(input_path)
thumbnail_size = (800, 800)
image.thumbnail(thumbnail_size, Image.ANTIALIAS)
```

### What did you expect to happen?

No exception. I can later save the image with `image.save(output_path)`

### What actually happened?

The following exception occurred:
`ValueError: unknown raw mode`

### What are your OS, Python and Pillow versions?

* OS: Inside a Docker container, Debian stretch 9
* Python: Python 3.7.3
* Pillow: Pillow 6.1.0 (sha 0e36b288dd9d7e932afeda5c01548d04baa9f93b)

This is a follow-up issue of https://github.com/python-pillow/Pillow/issues/3815

**Comment by anpr** [comment]
Any news on this? Is there any way to help?

**Comment by radarhere** [comment]
Apologies for not getting this the first time. I've created PR #3913 to help. If that is merged, you will be able to do -

```python
from PIL import Image
image = Image.open('alp-1978-big-tif.tif')
image.thumbnail((800, 800))
image.copy().save('out.tif')
```

You will not be able to run that code without the `copy()` - presumably this is because of something more complicated to do with the TIFF format.

**Comment by hugovk** [comment]
@anpr Please can you check if the PR helps?

**Comment by radarhere** [comment]
The PR has now been merged, so you can check master.

**Comment by radarhere** [comment]
Pillow 6.1.0 has now been released, so the improvement is now a part of that.

**Comment by anpr** [comment]
Sorry for the delay, we only could test it now. We did using the 6.1.0 release, and indeed everything works as expected!

Thanks a lot :-)

**Comment by Dionysusnu** [comment]
I'm having this same issue, even if using `.copy()` in between.
```
Traceback (most recent call last):
  File "convertdds.py", line 11, in <module>
    img.copy().save(filename[0:len(filename)-4]+".png")
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 1115, in copy
    self.load()
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\ImageFile.py", line 230, in load
    decoder = Image._getdecoder(
  File "C:\Users\myusername\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 439, in _getdecoder
    return decoder(mode, *args + extra)
ValueError: unknown raw mode
```
```py
import os
import sys
from PIL import Image

directory = sys.argv[1]
for filename in os.listdir(directory):
    if filename.endswith(".dds"):
        filename = os.path.join(directory, filename)
        print(filename)
        with Image.open(filename) as img:
            img.copy().save(filename[0:len(filename)-4]+".png")
```
I'm iterating over a directory of dds files and converting them to png. The first 20 or so work fine, but I consistently get this error at a specific file. Any ideas why or how to fix it?

**Comment by radarhere** [comment]
To offer a very delayed response, if you're able to upload a copy of the problem file, we can take a look.
