### ISSUE TITLE
Can't verify a picture

### ISSUE THREAD

**Issue by Suyn** [python-pillow/Pillow#3831]
`Image.open(pathfile).verify()`, there is a problem in it.

### What did you do?
I found this method couldn't verify a picture in fact, in my windows10, I can't open my picture because it was broken, but I use this function that nothing to happen, there is no error or exception to raise.
### What did you expect to happen?
Modify this method and solve the problem.
### What actually happened?
As you see.
### What are your OS, Python and Pillow versions?

* OS: windows10
* Python: 3.6.6
* Pillow: 6.0.0

```python
Image.open(path).verify()
```
The test img in my local and my E-mail: liquid777@163.com. If you need, please contact me.

**Comment by radarhere** [comment]
When you say 'I can't open my picture because it was broken', I presume that Pillow `open` still works fine, or you'd be talking about that instead of `verify`.

What format does your image have? JPG? PNG? TIFF?

**Comment by Suyn** [comment]
JPG.
And picture in my enclosure.

**Comment by Suyn** [comment]
Did you get my img in enclosure?You can use this function to test it.And nothing to happen,no exception to raise,I tested it.




------------------ 原始邮件 ------------------
发件人: "Andrew Murray"<notifications@github.com>; 
发送时间: 2019年5月7日(星期二) 上午10:48
收件人: "python-pillow/Pillow"<Pillow@noreply.github.com>; 
抄送: "肃允"<594154545@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [python-pillow/Pillow] Image.open(pathfile).verify()  method can't verify a picture in fact (#3831)




When you say 'I can't open my picture because it was broken', I presume that Pillow open still works fine, or you'd be talking about that instead of verify.
 
What format does your image have? JPG? PNG? TIFF?

**Comment by radarhere** [comment]
I don't know what you mean by 'enclosure'. I'm not seeing an image. If you mean that you're attaching an image to the e-mails that you are using to reply, then since that's not working, I would try attaching them through Github directly instead.

The `verify` method is unimplemented except for PNG, so this isn't just an error to fix. If you attach your image, we might be able to change `verify` for JPG so that it detects whatever problem is occurring for your file.

**Comment by Suyn** [comment]
My English is not good.I used a translator to communicate with you, and sometimes use my personal "grammer and word".It maybe let you feel stiff.But I didn't know you understood me. That's great! yes,yes!I am attaching an image to the e-mails.



------------------ 原始邮件 ------------------
发件人: "Andrew Murray"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 中午11:25
收件人: "python-pillow/Pillow"<Pillow@noreply.github.com>;
抄送: "肃允"<594154545@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [python-pillow/Pillow] Can't verify a picture (#3831)




I don't know what you mean by 'enclosure'. I'm not seeing an image. If you mean that you're attaching an image to the e-mails that you are using to reply, then since that's not working, I would try attaching them through Github directly instead.
 
The verify method is unimplemented except for PNG, so this isn't just an error to fix. If you attach your image, we might be able to change verify for JPG so that it detects whatever problem is occurring for your file.

**Comment by hugovk** [comment]
No, the image is not attached. I think images are removed from email replies. Please upload the image via the web interface in a browser.

**Comment by Suyn** [comment]
Ok,I upload it to a website,the link is http://i1.bvimg.com/686511/b4944e1a62350a34.jpg




------------------ 原始邮件 ------------------
发件人: "Hugo"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 下午4:27
收件人: "python-pillow/Pillow"<Pillow@noreply.github.com>;
抄送: "肃允"<594154545@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [python-pillow/Pillow] Can't verify a picture (#3831)




No, the image is not attached. I think images are removed from email replies. Please upload the image via the web interface in a browser.

**Comment by Suyn** [comment]
Have you tried it?And how to solve it?Did you receive my last email, the address with the picture above?



------------------ 原始邮件 ------------------
发件人: "Hugo"<notifications@github.com>;
发送时间: 2019年5月7日(星期二) 下午4:27
收件人: "python-pillow/Pillow"<Pillow@noreply.github.com>;
抄送: "肃允"<594154545@qq.com>; "Author"<author@noreply.github.com>; 
主题: Re: [python-pillow/Pillow] Can't verify a picture (#3831)




No, the image is not attached. I think images are removed from email replies. Please upload the image via the web interface in a browser.

**Comment by radarhere** [comment]
The link to the image no longer works.

**Comment by Suyn** [comment]
You can try this link, http:// landson.net/ssuynn/test.jpg


 
---Original---

**Comment by radarhere** [comment]
For the latest image at least, my macOS environment can read the image. So I don't think it's completely broken. Regarding Pillow -

```python
from PIL import Image
im = Image.open('test.jpg')
im.load()
```

raises `OSError: broken data stream when reading image file`. So then, using the setting to load truncated images instead -

```
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
im = Image.open('test.jpg')
im.load()
```

This works without a problem. So it looks like your image is not completely broken, merely truncated. You might say that this is still broken, but in the description of [the verify method](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.verify) -

> For data read from a file, this method attempts to determine if the file is broken, without actually decoding the image data.

I don't imagine that you could detect a truncated image without decoding the image data. So others should feel free to give their opinions on this, but I don't think this is actually a suitable case for `verify`.
