### ISSUE TITLE
Loads different pixel values on Windows vs Linux

### ISSUE THREAD

**Issue by mikeobr** [python-pillow/Pillow#3833]
### What did you do?
Loaded an image and checked a pixel value.

### What did you expect to happen?
Identical values on windows and linux.

### What actually happened?
Values differed by a visible amount.

### What are your OS, Python and Pillow versions?

* OS: Windows 10, Amazon Linux
* Python: 3.7
* Pillow: 6.0.0

```python
from PIL import Image
import numpy as np
import cv2

test = Image.open("test.jpg")
print(Image.core.jpeglib_version)
print(np.array(test)[35][97])
print(cv2.imread("test.jpg")[35][97][::-1])
# output on windows 10, python 3.7, Pillow 6.0.0
# 6.2
# [188  87 145]
# [188  87 145]

# output on linux, python 3.7, pillow 6.0.0, cv2 is the same, pillow differs
# 9.0
# [196  83 147]
# [188  87 145]
```
![test](https://user-images.githubusercontent.com/14041237/57309940-f21f3100-70b6-11e9-836c-c8081966572e.jpg)

### Additional Debug info

The input image has an sRGB color profile.

Based on what I've read online, this is may be related to the jpeglib version. However I'm confused about how Pillow links to this dependency and uses it. I'm a little stuck as to how to make the code consistent between os + versions.

**Comment by radarhere** [comment]
How did you install Pillow on Windows and Linux? If you are just interested in consistency, the simplest thing might be to install jpeg 6.2 on Linux.

**Comment by cgohlke** [comment]
The Windows wheels are built with `libjpeg-turbo-2.0`, which emulates the libjpeg v6b API/ABI by default. libjpeg-turbo can be compiled for the v7 or v8 API/ABI, but not v9.

**Comment by albert-92** [comment]
Will there be a fix any time soon?

**Comment by envil** [comment]
I encounter the same problem. Step to reproduce:
1. Read an image on Windows and Linux/UNIX:
``` python
def image_from_data(image_data: bytes) -> Image:
    buffer = io.BytesIO(image_data)

    return Image.open(buffer)
```
2. Save the pickles of both versions of Pillow image objects:
``` python
# on Windows
pickle.dump(image_windows, open('image_windows.pickle', 'wb'))

# on Linux/UNIX
pickle.dump(image_linux, open('image_linux.pickle', 'wb'))
```
3. Compare both images:
``` python
image_diff = ImageChops.logical_xor(image_windows.convert('1'), image_linux.convert('1'))
image_diff.show()
```

Here's the result:
![penguin](https://user-images.githubusercontent.com/775364/74323717-9e045400-4d8e-11ea-9f48-23f6a9a2b951.png)

Black dots mean similar, white dots means different.

We've tried to use the same python version, Pillow version but the results are still the same.

**Comment by cgohlke** [comment]
As mentioned before, the Windows wheels are built with libjpeg-turbo, the Linux wheels are not. JPEG decoders are allowed to produce slightly different results, "a maximum of one bit of difference for each pixel component" according to Wikipedia.

**Comment by radarhere** [comment]
For more discussion on this, see #4686

**Comment by radarhere** [comment]
Closing, as the conclusion here is that there should not be an expectation for different JPEG decoders to produce the same results.

If you want to ensure the same output, please ensure you are using the same version of libjpeg on both environments. If the Pillow wheel does not have the version of libjpeg that you require, then install it and try compiling Pillow from source. Compiling on Windows became easier after the opening of this issue, thanks to #4495.

**Comment by martinbenes1996** [comment]
A relevant read to this is following research paper:

https://dl.acm.org/doi/pdf/10.1145/3531536.3532962
