### ISSUE TITLE
"Unknown resampling filter" error message can be improved

### ISSUE THREAD

**Issue by AlecBenzer** [python-pillow/Pillow#3849]
https://github.com/python-pillow/Pillow/blob/2766d943a1a39ea5beafd3cc10b115f5b608a9ab/src/PIL/Image.py#L1797

https://github.com/python-pillow/Pillow/blob/2766d943a1a39ea5beafd3cc10b115f5b608a9ab/src/PIL/Image.py#L2266

1. "unknown" feels vague/wrong. The resampling filter may very well be a valid one that Pillow is aware of _in general_, it's just that it's _unsupported_ for the current use-case.
2. The error could include both the sampling filter passed in _and_ what filters are supported/expected. Both of these are currently hard to gleam without reading the source code.

**Comment by radarhere** [comment]
1. `resize` supports all the available filters, so in that case, the supplied filter is unknown.
2. When you say that it is hard to determine which filters are supported without reading the source code, https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.transform and https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize lists the relevant filters.

**Comment by radarhere** [comment]
I've created PR #3859 to resolve this.
