### ISSUE TITLE
Error with fontsize 

### ISSUE THREAD

**Issue by cheekysim** [python-pillow/Pillow#3862]
### What did you do?
I wrote some code to create a black image and put text in the centre but if the text is too big it makes it smaller and if its too small it makes it bigger
### What did you expect to happen?
The text would be bigger or smaller
### What actually happened?
It only goes bigger and I get an error:
  File "C:\Users\cs-admin\PycharmProjects\DiscordBot\venv\lib\site-packages\discord\ext\commands\core.py", line 72, in wrapped
    raise CommandInvokeError(exc) from exc
discord.ext.commands.errors.CommandInvokeError: Command raised an exception: TypeError: getsize() got an unexpected keyword argument 'font'
### What are your OS, Python and Pillow versions?

* OS: windows 10
* Python: 3.6
* Pillow: 6.0.0

Please include **code** that reproduces the issue and whenever possible, an **image** that demonstrates the issue. Please upload images to GitHub, not to third-party file hosting sites. If necessary, add the image to a zip or tar archive.

The best reproductions are self-contained scripts with minimal dependencies. If you are using a framework such as plone, Django, or buildout, try to replicate the issue just using Pillow. 

```python
@bot.command()
async def quote(ctx, *, text = "I'm Gay!"):
    MAX_W, MAX_H = 1024, 512
    im = Image.new('RGB', (MAX_W, MAX_H), (0, 0, 0, 0))
    draw = ImageDraw.Draw(im)
    size = 50
    font = ImageFont.truetype('arial.ttf', size)
    w, h = font.getsize(text, font=font)
    if w > MAX_W:
        j = w - MAX_W
        for i in range(j):
            if size > 5:
                size = size - 1
    if w < MAX_W:
        j = MAX_W - w
        for i in range(j):
            if size < 200:
                size = size + 1
    font = ImageFont.truetype('arial.ttf', size)
    MAX_W, MAX_H = 1024, 512
    w, h = draw.textsize(text, font=font)
    draw.text(((MAX_W - w) / 2, ((MAX_H - h) / 2)), text, font=font)
    im.save('quote.jpg')
    await ctx.send(file=discord.File('quote.jpg'))
```

**Comment by cheekysim** [comment]
nobody?

**Comment by hugovk** [comment]
There's quite a bit of extra unnecessary code there. It gives:

```
Traceback (most recent call last):
  File "1.py", line 1, in <module>
    @bot.command()
NameError: name 'bot' is not defined
```

Please can you reduce it down to the bare minimum and fewest lines required to reproduce your problem as a self-contained script?

For tips, please see https://stackoverflow.com/help/minimal-reproducible-example.

**Comment by cheekysim** [comment]
```python
text = "Hello so hey whats up -_-"
MAX_W, MAX_H = 1024, 512
im = Image.new('RGB', (MAX_W, MAX_H), (0, 0, 0, 0))
draw = ImageDraw.Draw(im)
size = 50
font = ImageFont.truetype('arial.ttf', size)
w, h = font.getsize(text, font=font)
if w > MAX_W:
    j = w - MAX_W
    for i in range(j):
        if size > 5:
            size = size - 1
if w < MAX_W:
     j = MAX_W - w
    for i in range(j):
        if size < 200:
            size = size + 1
font = ImageFont.truetype('arial.ttf', size)
MAX_W, MAX_H = 1024, 512
w, h = draw.textsize(text, font=font)
draw.text(((MAX_W - w) / 2, ((MAX_H - h) / 2)), text, font=font)
im.save('quote.jpg')```

**Comment by hugovk** [comment]
Thanks, it still needs a bit of work to make it a self-contained, runnable script:

```
  File "3862.py", line 15
    for i in range(j):
                     ^
IndentationError: unindent does not match any outer indentation level
```

Deleting a space on that line:

```
Traceback (most recent call last):
  File "3862.py", line 3, in <module>
    im = Image.new('RGB', (MAX_W, MAX_H), (0, 0, 0, 0))
NameError: name 'Image' is not defined
```

Adding imports:
```
Traceback (most recent call last):
  File "3862.py", line 9, in <module>
    w, h = font.getsize(text, font=font)
TypeError: getsize() got an unexpected keyword argument 'font'
```

Makes it now reproducible. And there's more we can remove, here's a much smaller version:

```python
from PIL import Image, ImageDraw, ImageFont

text = "Hello so hey whats up -_-"
MAX_W, MAX_H = 1024, 512
im = Image.new('RGB', (MAX_W, MAX_H), (0, 0, 0, 0))
draw = ImageDraw.Draw(im)
size = 50
font = ImageFont.truetype('arial.ttf', size)
w, h = font.getsize(text, font=font)
```

**Comment by hugovk** [comment]
`font` is a `PIL.ImageFont.FreeTypeFont`.

Its parameters are `text, direction=None, features=None, language=None`, so it doesn't take a font parameter.

https://github.com/python-pillow/Pillow/blob/45df9ad8824f45eebeeba1996da619bccd2dccac/src/PIL/ImageFont.py#L183-L219

```python
from PIL import Image, ImageDraw, ImageFont

text = "Hello so hey whats up -_-"
MAX_W, MAX_H = 1024, 512
im = Image.new('RGB', (MAX_W, MAX_H), (0, 0, 0, 0))
draw = ImageDraw.Draw(im)
size = 50
font = ImageFont.truetype('arial.ttf', size)

w, h = font.getsize(text)
print(w, h)
```
```
567 57
```

**Comment by cheekysim** [comment]
Thanks for the help, i managed to fix it,
