### ISSUE TITLE
Conversion of image to array fails

### ISSUE THREAD

**Issue by sommerfelt** [python-pillow/Pillow#3863]
Tried to load and convert an image (attached) to a numpy array. Fails on first try, succeeds on second. Strange! 

Guessing cause may be that the image is slightly corrupted, but this is not detected or reported by PIL. 

### What are your OS, Python and Pillow versions?

* OS: Windows 10 pro
* Python: Python 3.7.3 (default, Apr 24 2019, 15:29:51) [MSC v.1915 64 bit (AMD64)] :: Anaconda, Inc. on win32
* Pillow: 6.0.0

![doesNotConvertToArray](https://user-images.githubusercontent.com/8694392/58248803-6ca9ab00-7d5d-11e9-9dc0-ca024bf63915.jpg)

```python
import numpy as np
from PIL import Image
# This image is to some extent corrupted, but is displayed correctly by viewing programs:
im = Image.open("doesNotConvertToArray.jpg") 
a1 = np.asarray(im) # First conversion fails
print(repr(a1))
# Only a singleton object array is printed: 
# array(<PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2703x1018 at 0x1AA4F6E1048>, dtype=object)

a2 = np.asarray(im) # Succeeds, strangely
print(a2.shape) # Prints correct shape: (1018, 2703, 3)
```

**Comment by radarhere** [comment]
I find that if I add in `ImageFile.LOAD_TRUNCATED_IMAGES = True`, it works.
```python
>>> import numpy as np
>>> from PIL import Image, ImageFile
>>> ImageFile.LOAD_TRUNCATED_IMAGES = True
>>> im = Image.open("doesNotConvertToArray.jpg") 
>>> a1 = np.asarray(im)
>>> print(a1.shape)
(1018, 2703, 3)
>>> a2 = np.asarray(im)
>>> print(a2.shape)
(1018, 2703, 3)
```

**Comment by hugovk** [comment]
@sommerfelt Did that help? Okay to close this issue?

**Comment by sommerfelt** [comment]
I reported the issue more because indicates a bug in PIL and not so much because it causes a problem for me. In my case it is better to use the dtype (a1.dtype==object) of the array as an indicator of a corrupted image rather than cloaking it by setting ImageFile.LOAD_TRUNCATED_IMAGES = True

So to conclude: For my purposes the issue is closed, but for PIL it remains a bug AFAIK.

**Comment by radarhere** [comment]
I've created PR #3965 to resolve this, by fixing the inconsistent behaviour.

**Comment by youssouf-abd** [comment]
I had the same problem.
When I opened my images in the grayscale mode, the problem did not appear. I am not expert, I don't know why it worked. But at least this comment may help other people.

To do so:
im = Image.open("doesNotConvertToArray.jpg").convert('L') 
a1 = np.asarray(im) 
a2 = np.asarray(im) 
print a1
print a2
