### ISSUE TITLE
Automated security fixes with Dependabot?

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3866]
GitHub will be sending automated PRs with security fixes for accounts with security alerts enabled.

Pillow does not have any Python dependencies for production code, only testing, but shall we enabled the setting to see how it goes?

It's at https://github.com/python-pillow/Pillow/network/alerts (I don't have access).

More info: 

* https://github.blog/2019-05-23-introducing-new-ways-to-keep-your-code-secure/#automated-security-fixes-with-dependabot
* https://help.github.com/en/articles/configuring-automated-security-fixes

**Comment by aclark4life** [comment]
Thanks @hugovk @radarhere , done. Looks like a good idea with no downside, worst case we don't merge the PR. 🎉

**Comment by hugovk** [comment]
Thanks!
