### ISSUE TITLE
Image.show() on image with mode LA does not show transparency

### ISSUE THREAD

**Issue by gerritholl** [python-pillow/Pillow#3868]
When I use `Image.show()` on an image with mode `LA`, transparency is not shown.  When I use `.save(...)`, the resulting image has transparency included correctly.  With mode `RGBA`, transparency is correctly displayed on `.show()` (and correctly written on `.save(...)`).

### What did you do?

I used `.show()` on an image with mode `LA`.

### What did you expect to happen?

I expected it to display an image with transparency:

![im1](https://user-images.githubusercontent.com/500246/58331700-faf35f00-7e39-11e9-973a-d1d2dd1414cf.png)

### What actually happened?

It showed an image without transparency:

![tmplevyr9u2](https://user-images.githubusercontent.com/500246/58331737-0fcff280-7e3a-11e9-9179-baf3a324f971.PNG)

### What are your OS, Python and Pillow versions?

* OS: openSUSE 15.0
* Python: 3.7.3
* Pillow: 6.0.0

```python
from numpy import linspace, block, concatenate, zeros, full
from PIL import Image

L = linspace(0, 255, 200*200, dtype="u1").reshape(200, 200, 1)
A = block([[zeros((100, 100), "u1"),             full((100, 100), 255, "u1")],
            [full((100, 100), 255, "u1"),
            zeros((100, 100), "u1")]]).reshape(200, 200, 1)
im1 = Image.fromarray((concatenate((L, A), 2)), mode="LA")
im2 = Image.fromarray((concatenate((L, L, L, A), 2)), mode="RGBA")
im1.show()
im2.show()
```

**Comment by radarhere** [comment]
This is not a bug as such. ImageShow is deliberately converting the image from LA to L, removing the transparency.

https://github.com/python-pillow/Pillow/blob/3368500f180eb14bf5b6d5b936db0eb8e084ba4d/src/PIL/ImageShow.py#L73-L75

However, the exception for RGBA that you see was added in https://github.com/python-pillow/Pillow/commit/74da5878c5b42ef8fee193bf4c394061. So it seems feasible to do so for LA as well.

However, ImageShow uses the BMP format for Windows, and Pillow cannot save LA as BMP. Looking at https://en.wikipedia.org/wiki/BMP_file_format

> The 32-bit per pixel (32bpp) format supports 4,294,967,296 distinct colors and stores 1 pixel per 4-byte DWORD. Each DWORD can define the alpha, red, green and blue samples of the pixel.

I could be wrong, but I think that BMP can't handle greyscale with alpha.

So I've created PR #3869 to allow ImageShow to use the LA mode, except for Windows.
