### ISSUE TITLE
local variable 'photoshop' referenced before assignment

### ISSUE THREAD

**Issue by bctiemann** [python-pillow/Pillow#3874]
`PIL/JpegImagePlugin.py:139`

`self.info["photoshop"] = photoshop`

This depends on `photoshop = {}` on line 112, but if the `if` condition on line 108 is not satisfied, the module crashes with the above ref error.

This bug is present in 6.0.0 and the master branch as of now.

**Comment by radarhere** [comment]
This should have been fixed by #3771.

Are you sure that this is in the master branch? If so, then please provide a self-contained example to reproduce the problem.

**Comment by bctiemann** [comment]
Oh, you're right, my bad. I didn't look closely enough at the indents in the master branch.
