### ISSUE TITLE
Not installed

### ISSUE THREAD

**Issue by Ruchey** [python-pillow/Pillow#3876]
Your pillow-simd is not installed either on ubuntu or on centos.

> Collecting pillow-simd
 

>  Using cached https://files.pythonhosted.org/packages/c1/14/7503657df68b428cb38e1f2cb5f8f086b53e9b6f4b79546596d1fcc30256/Pillow-SIMD-5.3.0.post1.tar.gz
> Building wheels for collected packages: pillow-simd
>   Running setup.py bdist_wheel for pillow-simd ... error
>   Complete output from command /mnt/d/dj/env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ynx5wube/pillow-simd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmp4yh0ahrxpip-wheel- --python-tag cp36:
>   running bdist_wheel
>   running build
>   running build_py
>   creating build
>   creating build/lib.linux-x86_64-3.6
>   creating build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/_version.py -> build/lib.linux-x86_64-3.6/PIL
>   copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
>   running egg_info
>   writing src/Pillow_SIMD.egg-info/PKG-INFO
>   writing dependency_links to src/Pillow_SIMD.egg-info/dependency_links.txt
>   writing top-level names to src/Pillow_SIMD.egg-info/top_level.txt
>   reading manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
>   reading manifest template 'MANIFEST.in'
>   warning: no files found matching '*.c'
>   warning: no files found matching '*.h'
>   warning: no files found matching '*.sh'
>   warning: no directories found matching 'Tests'
>   no previously-included directories found matching 'docs/_static'
>   no previously-included directories found matching 'Tests'
>   warning: no previously-included files found matching '.appveyor.yml'
>   warning: no previously-included files found matching '.coveragerc'
>   warning: no previously-included files found matching '.codecov.yml'
>   warning: no previously-included files found matching '.editorconfig'
>   warning: no previously-included files found matching '.landscape.yaml'
>   warning: no previously-included files found matching '.travis'
>   warning: no previously-included files found matching '.travis/*'
>   warning: no previously-included files found matching 'tox.ini'
>   warning: no previously-included files matching '.git*' found anywhere in distribution
>   warning: no previously-included files matching '*.pyc' found anywhere in distribution
>   warning: no previously-included files matching '*.so' found anywhere in distribution
>   writing manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
>   copying src/PIL/.DS_Store -> build/lib.linux-x86_64-3.6/PIL
>   running build_ext
> 
> 
>   The headers or library files could not be found for jpeg,
>   a required dependency when compiling Pillow from source.
> 
>   Please see the install instructions at:
>      https://pillow.readthedocs.io/en/latest/installation.html
> 
>   Traceback (most recent call last):
>     File "/tmp/pip-build-ynx5wube/pillow-simd/setup.py", line 803, in <module>
>       zip_safe=not (debug_build() or PLATFORM_MINGW), )
>     File "/mnt/d/dj/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>       return distutils.core.setup(**attrs)
>     File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>       dist.run_commands()
>     File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>       self.run_command(cmd)
>     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/mnt/d/dj/env/lib/python3.6/site-packages/wheel/bdist_wheel.py", line 192, in run
>       self.run_command('build')
>     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>       self.run_command(cmd_name)
>     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>       self.distribution.run_command(command)
>     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>       cmd_obj.run()
>     File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>       self.build_extensions()
>     File "/tmp/pip-build-ynx5wube/pillow-simd/setup.py", line 589, in build_extensions
>       raise RequiredDependencyException(f)
>   __main__.RequiredDependencyException: jpeg
> 
>   During handling of the above exception, another exception occurred:
> 
>   Traceback (most recent call last):
>     File "<string>", line 1, in <module>
>     File "/tmp/pip-build-ynx5wube/pillow-simd/setup.py", line 815, in <module>
>       raise RequiredDependencyException(msg)
>   __main__.RequiredDependencyException:
> 
>   The headers or library files could not be found for jpeg,
>   a required dependency when compiling Pillow from source.
> 
>   Please see the install instructions at:
>      https://pillow.readthedocs.io/en/latest/installation.html
> 
> 
> 
>   ----------------------------------------
>   Failed building wheel for pillow-simd
>   Running setup.py clean for pillow-simd
> Failed to build pillow-simd
> Installing collected packages: pillow-simd
>   Running setup.py install for pillow-simd ... error
>     Complete output from command /mnt/d/dj/env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ynx5wube/pillow-simd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rj_xgd5r-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/d/dj/env/include/site/python3.6/pillow-simd:
>     running install
>     running build
>     running build_py
>     creating build
>     creating build/lib.linux-x86_64-3.6
>     creating build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/OleFileIO.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/_version.py -> build/lib.linux-x86_64-3.6/PIL
>     copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL
>     running egg_info
>     writing src/Pillow_SIMD.egg-info/PKG-INFO
>     writing dependency_links to src/Pillow_SIMD.egg-info/dependency_links.txt
>     writing top-level names to src/Pillow_SIMD.egg-info/top_level.txt
>     reading manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
>     reading manifest template 'MANIFEST.in'
>     warning: no files found matching '*.c'
>     warning: no files found matching '*.h'
>     warning: no files found matching '*.sh'
>     warning: no directories found matching 'Tests'
>     no previously-included directories found matching 'docs/_static'
>     no previously-included directories found matching 'Tests'
>     warning: no previously-included files found matching '.appveyor.yml'
>     warning: no previously-included files found matching '.coveragerc'
>     warning: no previously-included files found matching '.codecov.yml'
>     warning: no previously-included files found matching '.editorconfig'
>     warning: no previously-included files found matching '.landscape.yaml'
>     warning: no previously-included files found matching '.travis'
>     warning: no previously-included files found matching '.travis/*'
>     warning: no previously-included files found matching 'tox.ini'
>     warning: no previously-included files matching '.git*' found anywhere in distribution
>     warning: no previously-included files matching '*.pyc' found anywhere in distribution
>     warning: no previously-included files matching '*.so' found anywhere in distribution
>     writing manifest file 'src/Pillow_SIMD.egg-info/SOURCES.txt'
>     copying src/PIL/.DS_Store -> build/lib.linux-x86_64-3.6/PIL
>     running build_ext
> 
> 
>     The headers or library files could not be found for jpeg,
>     a required dependency when compiling Pillow from source.
> 
>     Please see the install instructions at:
>        https://pillow.readthedocs.io/en/latest/installation.html
> 
>     Traceback (most recent call last):
>       File "/tmp/pip-build-ynx5wube/pillow-simd/setup.py", line 803, in <module>
>         zip_safe=not (debug_build() or PLATFORM_MINGW), )
>       File "/mnt/d/dj/env/lib/python3.6/site-packages/setuptools/__init__.py", line 129, in setup
>         return distutils.core.setup(**attrs)
>       File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
>         dist.run_commands()
>       File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
>         self.run_command(cmd)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/mnt/d/dj/env/lib/python3.6/site-packages/setuptools/command/install.py", line 61, in run
>         return orig.install.run(self)
>       File "/usr/lib/python3.6/distutils/command/install.py", line 589, in run
>         self.run_command('build')
>       File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
>         self.run_command(cmd_name)
>       File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
>         self.distribution.run_command(command)
>       File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
>         cmd_obj.run()
>       File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
>         self.build_extensions()
>       File "/tmp/pip-build-ynx5wube/pillow-simd/setup.py", line 589, in build_extensions
>         raise RequiredDependencyException(f)
>     __main__.RequiredDependencyException: jpeg
> 
>     During handling of the above exception, another exception occurred:
> 
>     Traceback (most recent call last):
>       File "<string>", line 1, in <module>
>       File "/tmp/pip-build-ynx5wube/pillow-simd/setup.py", line 815, in <module>
>         raise RequiredDependencyException(msg)
>     __main__.RequiredDependencyException:
> 
>     The headers or library files could not be found for jpeg,
>     a required dependency when compiling Pillow from source.
> 
>     Please see the install instructions at:
>        https://pillow.readthedocs.io/en/latest/installation.html
> 
> 
> 
>     ----------------------------------------
> Command "/mnt/d/dj/env/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-ynx5wube/pillow-simd/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-rj_xgd5r-record/install-record.txt --single-version-externally-managed --compile --install-headers /mnt/d/dj/env/include/site/python3.6/pillow-simd" failed with error code 1 in /tmp/pip-build-ynx5wube/pillow-simd/

**Comment by hugovk** [comment]
The headers or library files could not be found for JPEG, a required dependency when compiling Pillow from source.

Please see the install instructions at:
   https://pillow.readthedocs.io/en/latest/installation.html

**Comment by radarhere** [comment]
It may also be worth pointing out that this repository is Pillow, while pillow-simd is at https://github.com/uploadcare/pillow-simd

Were you able to install Pillow successfully after installing the dependencies?

**Comment by Ruchey** [comment]
Помогла установка
```
sudo apt-get install libtiff5-dev libjpeg8-dev zlib1g-dev \
    libfreetype6-dev liblcms2-dev libwebp-dev libharfbuzz-dev libfribidi-dev \
    tcl8.6-dev tk8.6-dev python-tk
```

**Comment by radarhere** [comment]
Cool. Closing this issue then.
