### ISSUE TITLE
Segmentation fault on Python 3.8.0a4+

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3884]
### What did you do?

Build master on Python 3.8-dev.

### What did you expect to happen?

Build passes.

### What actually happened?

Build fails.

```
.travis/script.sh: line 10: 16886 Segmentation fault      (core dumped) python -m pytest -vx --cov PIL --cov-report term Tests
```

* https://travis-ci.org/python-pillow/Pillow/jobs/540003603#L3245

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 16.04.6 LTS Xenial
* Python: 3.8.0a4+
* Pillow: master

The last passing master build used Python 3.8.0a3+:

* https://travis-ci.org/python-pillow/Pillow/jobs/538572358#L185

Python 3.8.0 release schedule:

* https://www.python.org/dev/peps/pep-0569/#schedule

**Comment by radarhere** [comment]
Testing, I find that removing `--cov PIL` from `python -m pytest -vx --cov PIL --cov-report term Tests` resolves the issue.

It is perhaps worth noting that pytest-cov is already looking into [a different problem with Python 3.8a4](https://github.com/pytest-dev/pytest-cov/issues/295).

**Comment by hugovk** [comment]
Fixed by deleting the build caches at https://travis-ci.org/python-pillow/Pillow/caches. Thanks to @radarhere for figuring it out.
