### ISSUE TITLE
Unpacking raw XRGB

### ISSUE THREAD

**Issue by flaviojs** [python-pillow/Pillow#3885]
I found these bugs while inspecting `src/libImaging/Unpack.c` and it's history to see what raw modes I could use before falling back to generic and slow python code in the decoder for my image plugin.

1. `RGBX` for mode `RGB` uses `copy4`, which does not set the X part to 255 like the other RGB unpackers

2. `XRGB` is listed with 24 bits but `ImagingUnpackXRGB` expects 32 bits

PS- Ideally I would be able to use the RGBA component masks and color depth to query Pillow for a compatible raw mode, but there is no way to query or inspect that information.

**Comment by flaviojs** [comment]
3. the 'RGBX' packer for mode 'RGB' also uses copy4, which does not set the X part to 0 like the other RGB packers

**Comment by wiredfool** [comment]
RGBX is 3 bytes of image data in a 4 byte alignment, so the X part is undefined. If you want a specific value, use RGBA. 

There are a few ways to unpack bits that are programmatically available, but it's not to the point of using masks. What are you trying to do?

**Comment by flaviojs** [comment]
I'm making a plugin for an undocumented image format that already exists and has the color depth and the mask+depth of each RGBA band, which I use to determine the pixel format. Technically it can support any color combination that fits 32 bits. I'm trying to use raw decoders/encoders when available and fall back to generic python code otherwise.

Anyway, If you guys consider it's ok to produce different values for the undefined X depending on where it is, then 1 and 3 aren't bugs and I would appreciate a note in the source noting the difference. I'll just not use the raw RGBX decoder/encoder since I want consistency.

But 2 is still a bug, since that 24 is exposed to other code by `ImagingFindUnpacker`:
```C
{"RGB", "XRGB", 24, ImagingUnpackXRGB},
{"RGBX", "XRGB", 24, ImagingUnpackXRGB},
```

**Comment by radarhere** [comment]
The XRGB values in Unpack.c have been that way since PIL. The best argument for me is that they are inconsistent with ImagingUnpackXBGR.

I've created PR #3910. Let us know what you think.
