### ISSUE TITLE
Add a specific exception if image not recognized?

### ISSUE THREAD

**Issue by sblondon** [python-pillow/Pillow#3892]
Hello,

if the file provided as parameter to `Image.open()` is not recognized, an `IOError` is raised. It's nice but the exception is not really precise and, in python3.3+, it equals to `OSError` so it can be surprising depending on the used traceback.

The raised exception could be specific like `UnknownImageError`. It should inherit from `IOError` for backward compatibility.

The main modification would be in Image.py, line 2730:
```python
    for message in accept_warnings:
        warnings.warn(message)
-    raise IOError("cannot identify image file %r"
+    raise UnknownImageError("cannot identify image file %r"
                 % (filename if filename else fp))
```

What do you think about it? I will send a PR if you agree with the idea.

**Comment by radarhere** [comment]
Related to, but not the same as, #1643 and #2339

**Comment by rgov** [comment]
Similarly, this is definitely not an OSError. It has nothing to do with the underlying operating system.

> OSError: cannot identify image file 'blah.tif'

**Comment by ccppoo** [comment]
I think it needs custom exception classes to check what's the problem like above, Tracebacks are too poor. 
Pillow is almost used as standard library.
