### ISSUE TITLE
Install problem

### ISSUE THREAD

**Issue by liyijii** [python-pillow/Pillow#3894]
when I install pillow
OSversion:
ERROR: Could not find a version that satisfies the requirement Pillow (from versions: none)
ERROR: No matching distribution found for Pillow

**Comment by radarhere** [comment]
Hi. Could you provide some more details? What is your operating system, and what is the exact command that you ran to install Pillow?

**Comment by radarhere** [comment]
Feel free to comment with any more details, and this can be re-opened.
