### ISSUE TITLE
Image.show() uses hardcoded path no longer valid in macOS 10.15

### ISSUE THREAD

**Issue by FlowerCode** [python-pillow/Pillow#3895]
### What did you do?
```Image.show()```

### What did you expect to happen?
Shows image in Preview.app

### What actually happened?
Crashes with invalid path for Preview.app

### What are your OS, Python and Pillow versions?

* OS: macOS 10.15
* Python: Python 3.7.3
* Pillow: 6.0.0

https://github.com/python-pillow/Pillow/blob/f1ed79229ece02a52e4d0df4acda2e26419ea8f4/src/PIL/ImageShow.py#L141

As part of security improvements, operating system is now separated from user data in macOS 10.15, in a read-only volume. [[ref]](https://developer.apple.com/videos/play/wwdc2019/710/)
```/Applications/Preview.app``` is now ```/System/Applications/Preview.app```.

**Comment by radarhere** [comment]
Thanks for testing Pillow with beta macOS! I've created PR #3896 to address this.

**Comment by eirnym** [comment]
The best option compatible with all macOS systems would be: `open -a Preview <params>`

**Comment by hugovk** [comment]
> The best option compatible with all macOS systems would be: `open -a Preview <params>`

The PR has `open -a Preview.app`. Is it better to omit the `.app` extension?

**Comment by eirnym** [comment]
basically it's the same. `.app` extension will say explicitly that you opens the app.
