### ISSUE TITLE
FPX fill decoder not available

### ISSUE THREAD

**Issue by faheemziker** [python-pillow/Pillow#3900]
### What did you do?

opened a fpx file using FpxImagePlugin and tried to save the same file as jpg.
the file is compressed fpx file.

```python
Image.open("/opt/project/test.fpx")
im.save("/opt/project/fpx_jpg.jpg")
```

### What did you expect to happen?
it should save without any error

### What actually happened?
it gives me exception
```pycon
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 1961, in save
    self.load()
  File "/usr/local/lib/python2.7/dist-packages/PIL/FpxImagePlugin.py", line 227, in load
    return ImageFile.ImageFile.load(self)
  File "/usr/local/lib/python2.7/dist-packages/PIL/ImageFile.py", line 213, in load
    args, self.decoderconfig)
  File "/usr/local/lib/python2.7/dist-packages/PIL/Image.py", line 457, in _getdecoder
    raise IOError("decoder %s not available" % decoder_name)
IOError: decoder fill not available
```

### What are your OS, Python and Pillow versions?

* OS: ubuntu
* Python: 2.7
* Pillow: latest

Test file
https://github.com/python-pillow/Pillow/files/3281304/test.fpx.zip

```python
Image.open("/opt/project/test.fpx")
im.save("/opt/project/fpx_jpg.jpg")
```

**Comment by radarhere** [comment]
You have hit https://github.com/python-pillow/Pillow/blob/a986fed5b445bc9586476167b08d46e19cba1bbc/src/PIL/FpxImagePlugin.py#L175

**Comment by faheemziker** [comment]
How can we write fill decoder implementation any hint ??

**Comment by radarhere** [comment]
As far as hints go, this looks like 4.2.2.2 of http://graphcomp.com/info/specs/livepicture/fpx.pdf. For information on Pillow decoders, see https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-file-decoder.html#writing-your-own-file-decoder-in-c

**Comment by radarhere** [comment]
If a fix is created, is the image that you attached able to be included as a test image under the Pillow license?

**Comment by faheemziker** [comment]
i need to ask my our project owner but i think there should be no issue but lets wait for confirmation

**Comment by faheemziker** [comment]
i am also trying its fix for placing single color tile in case of fill. but still having issues. can you ping here if you have the fix

**Comment by radarhere** [comment]
> i need to ask our project owner but i think there should be no issue but lets wait for confirmation

Did you ever get confirmation?

**Comment by faheemziker** [comment]
Sorry was just forgot as we fixed this issue in our fork of pillow.
ill follow up with someone in management for permissionn

**Comment by radarhere** [comment]
Could we get a JPG of what the FPX image should look like?

**Comment by radarhere** [comment]
I've created PR #6372 to add the fill decoder.

With that PR, the following code generates this image.
```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
im = Image.open("test.fpx")
im.save("fpx_jpg.jpg")
```
![fpx_jpg](https://user-images.githubusercontent.com/3112309/174038191-1fe570a3-597b-41db-86ec-3508c5f1e932.jpg)

**Comment by radarhere** [comment]
Apparently #6372 isn't correct, but an alternative PR hasn't been suggested yet, and no more information has been provided about what the correct output would be. So I'm flagging this as 'Awaiting OP Action'.
