### ISSUE TITLE
ImageDraw.text ttb can't use Korean sequence

### ISSUE THREAD

**Issue by bharatsubedi** [python-pillow/Pillow#3920]
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```python
code goes here
```

**Comment by radarhere** [comment]
Could you provide some more details? Can you provide a self-contained code example? What happens when you attempt to run your code? What version of Pillow are you using?

**Comment by radarhere** [comment]
If you are using Pillow 6.0 or earlier, then this is not unexpected - ttb was improved in #3856, so if you would like, you can use the master branch of Pillow for this. Alternatively, Pillow 6.1.0 will be released on July 1 with this change.

Note that in either case, raqm 0.7 will be required.

**Comment by radarhere** [comment]
Pillow 6.1.0 has now been released. If you try that, it will hopefully fix your problem.

**Comment by hugovk** [comment]
If 6.1.0 doesn't fix it, please comment and we can re-open. Thanks.
