### ISSUE TITLE
Fix Codecov integration

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#3934]
Follow on from https://github.com/python-pillow/Pillow/pull/3913#issuecomment-504881781.

Again the Codecov integration isn't reporting on PRs:

![image](https://user-images.githubusercontent.com/1324225/60488622-165c5000-9cab-11e9-94a3-29c785e066a8.png)

https://github.com/python-pillow/Pillow/pull/3933

Ping @aclark4life. Perhaps removing and re-adding it may help?

**Comment by hugovk** [comment]
The next two PRs did report coverage (#3935, #3936) but not the third (#3937).

**Comment by hugovk** [comment]
We're still getting some PRs with coverage reports and some PRs without.

**Comment by aclark4life** [comment]
@hugovk Based on last time I looked at this, the only suggestion I can make is for the authors of all the commits to ensure they've logged into Codecov recently. And click on whatever they want you to click on (if anything). After that, we can at least rule out "developer hasn't logged into Codecov" as a possibility.

**Comment by hugovk** [comment]
@radarhere Please can you log in to Codecov and see if anything needs clicking? Today's https://github.com/python-pillow/Pillow/pull/3964 doesn't have coverage notifications, but it does have coverage on the site: https://codecov.io/gh/python-pillow/Pillow/commit/386002e8923ec9586d4221529963c22f01212ac4

If there's nothing out of the ordinary, let's ask at https://community.codecov.io/. Thanks!

**Comment by radarhere** [comment]
I was logged in to Codecov at the time of making that PR. Checking now, the only notification that I can see is this, but I doubt it's going to the solution.

![codecov](https://user-images.githubusercontent.com/3112309/61159618-f432bf80-a53f-11e9-9571-41376f39b3ac.png)

**Comment by hugovk** [comment]
Reported to Codecov:

* https://community.codecov.io/t/missing-checks-on-github/361

With a new account there I can frustratingly only post one link in the report, here's the same report with all the links:

---

### Description

Coverage reports are being created for PRs on Codecov, but most of the time they're not showing as checks the PRs on GitHub. They used to. This makes it hard to see if the PR has tested the changed code.

https://codecov.io/gh/python-pillow/Pillow/pulls

Here's 5 recent PRs, none have Codecov checks on GitHub:

* https://github.com/python-pillow/Pillow/pull/3967
* https://github.com/python-pillow/Pillow/pull/3965
* https://github.com/python-pillow/Pillow/pull/3964
* https://github.com/python-pillow/Pillow/pull/3953
* https://github.com/python-pillow/Pillow/pull/3950

These mostly show up on the Codecov website itself with coverage:

* https://codecov.io/gh/python-pillow/Pillow/pull/3967
* https://codecov.io/gh/python-pillow/Pillow/pull/3965
* https://codecov.io/gh/python-pillow/Pillow/pull/3964
* #3953: "No report uploaded yet."
* https://codecov.io/gh/python-pillow/Pillow/pull/3950

The most recent to have a Codecov check on GitHub was 8 days ago, but there are older ones without checks:
https://github.com/python-pillow/Pillow/pull/3956

### Repository

https://github.com/python-pillow/Pillow

### Versions

codecov 2.0.15 for Python

**Comment by radarhere** [comment]
I think this may have resolved itself - every PR for the last three weeks has had code coverage.
