### ISSUE TITLE
`pip show pillow` shows the licence as UNKNOWN

### ISSUE THREAD

**Issue by GadgetSteve** [python-pillow/Pillow#3938]
### What did you do?
`pip show Pillow`
look for Licence
### What did you expect to happen?
Recognisable Licence
### What actually happened?
Currently `pip show pillow` shows the licence as UNKNOWN. 

### What are your OS, Python and Pillow versions?

* OS: Win 7/10 32/64 expect all
* Python: 2.7, 3.5, 3.6, 3.7
* Pillow: 6.0.0

I believe that adding a `licence` entry to setup.py would resolve this - it would remove the step of visiting the repository to check the licence type for those that have to worry about such things.

**Comment by hugovk** [comment]
PR https://github.com/python-pillow/Pillow/pull/3752 updated the licence in `classifiers` from `"License :: Other/Proprietary License",` to `"License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)"`.

It also removed the `license` parameter due, because:

> * "this argument is meant for deviations from the Trove classifier, not instead of it" (pypa/packaging.python.org#492)

Maybe pip isn't recognising HPND in the Trove classifier?

**Comment by aclark4life** [comment]
@GadgetSteve makes a good point, we've somehow avoided adding ``license`` to setup.py  😄 

- https://the-hitchhikers-guide-to-packaging.readthedocs.io/en/latest/quickstart.html#describe-your-project

**Comment by hugovk** [comment]
These suggest `license=` shouldn't be used when there's a license in the Trove `classifiers=`:

* https://packaging.python.org/guides/distributing-packages-using-setuptools/?highlight=license#license

* https://packaging.python.org/specifications/core-metadata/?highlight=license#license

**Comment by aclark4life** [comment]
@hugovk I'd still add it, because I get the feeling other people haven't gotten the memo… at least until we can rule out the pip thing.

**Comment by aclark4life** [comment]
E.g.

```

license = "License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)"

```

or 


```
license = "Historical Permission Notice and Disclaimer (HPND)"

```

or 

```
license = "HPND"

```

Just to populate that field with *something* and see what happens.

**Comment by GadgetSteve** [comment]
Or even "See classifier in pip show -v" would do the job.

**Comment by aclark4life** [comment]
When in doubt, copy someone else :smile: e.g. https://github.com/django/django/blob/master/setup.py

**Comment by hugovk** [comment]
Yeah, let's add `license=`.

And in general, if `pip show` shows `License: UNKNOWN`, then `pip show -v` is a good tip to see if there's a licence in the classifiers, to avoid visiting the repo.

```console
$ pip show pillow
Name: Pillow
Version: 6.1.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by:
```
```console
$ pip show pillow -v
Name: Pillow
Version: 6.1.0
Summary: Python Imaging Library (Fork)
Home-page: http://python-pillow.org
Author: Alex Clark (Fork Author)
Author-email: aclark@aclark.net
License: UNKNOWN
Location: /usr/local/lib/python3.7/site-packages
Requires:
Required-by:
Metadata-Version: 2.1
Installer: pip
Classifiers:
  Development Status :: 6 - Mature
  License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)
  Programming Language :: Python :: 2
  Programming Language :: Python :: 2.7
  Programming Language :: Python :: 3
  Programming Language :: Python :: 3.5
  Programming Language :: Python :: 3.6
  Programming Language :: Python :: 3.7
  Programming Language :: Python :: Implementation :: CPython
  Programming Language :: Python :: Implementation :: PyPy
  Topic :: Multimedia :: Graphics
  Topic :: Multimedia :: Graphics :: Capture :: Digital Camera
  Topic :: Multimedia :: Graphics :: Capture :: Screen Capture
  Topic :: Multimedia :: Graphics :: Graphics Conversion
  Topic :: Multimedia :: Graphics :: Viewers
Entry-points:
```

I reported this to pip here: https://github.com/pypa/pip/issues/6677.

**Comment by radarhere** [comment]
#3943 has now been merged.

**Comment by hugovk** [comment]
Thanks for the report and fix!
