### ISSUE TITLE
MemoryError: Integer overflow in ysize

### ISSUE THREAD

**Issue by elhuhdron** [python-pillow/Pillow#3963]
Many PIL operations are working for me for image manipulations of images over 32 bit in size, which is fantastic. However, I still have a problem with fromarray, tested using PIL version 6.1.0 and numpy version 1.16.4. I believe this version already incorporates fix #3791 (?)

The test case is relatively simple:

```python
from PIL import Image
import numpy as np

# this works
a = np.zeros((46340, 46340), dtype=np.uint8)
b = Image.fromarray(a)
del a,b

# this works
b = Image.new('L', (46341, 46341))
del b

# this does not work, fails with:
# MemoryError: Integer overflow in ysize
a = np.zeros((46341, 46341), dtype=np.uint8)
b = Image.fromarray(a)
```

This is likely because 46341*46341 > 2^31-1
Is this easily fixable?

**Comment by radarhere** [comment]
#3791 was included as part of Pillow 6.1.0, yes.

I've created PR #3964 to resolve this.

**Comment by hugovk** [comment]
@elhuhdron Please could you test PR #3964?

**Comment by elhuhdron** [comment]
> @elhuhdron Please could you test PR #3964?

Yes, verified. I built and installed the PR branch and the overflow error is no longer thrown. Thanks!

**Comment by hugovk** [comment]
Thanks both, merged!

**Comment by 00krishna** [comment]
I am still running into this problem now. I tried to download through pip and reinstall. I also cloned the repo and installed from source, but still running into the same error message when using `fromarray`. My image is (156093, 91380).

**Comment by hugovk** [comment]
@00krishna It's not been released yet, it'll be in the next release due on 1st October. In the meantime you can build from source using the latest master: 

* https://pillow.readthedocs.io/en/stable/installation.html#building-from-source

**Comment by 00krishna** [comment]
@hugovk Oh thanks for the tip. Okay I looked at the link you included and it said to download the latest source from PYPI. On PYPI it indicates that the latest version is 6.1 uploaded on July 2, 2019. But I suppose I need the latest version of the software that includes the fix for this particular issue. Is there some way to fix the `Integer overflow in ysize` error when I build from source? Thanks for your help.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/archive/master.zip

**Comment by 00krishna** [comment]
Thanks @radarhere . I appreciate your posting the link to the dev branch.
