### ISSUE TITLE
A mishandling of Python/C API Exception?

### ISSUE THREAD

**Issue by Elaphurus** [python-pillow/Pillow#3966]
I know that in the wrapper functions of Python C extensions, Exceptions threw using Python/C API like ```PyErr_SetString``` should be followed by a ```return``` statement, it's what Pillow does almost everywhere, but is the following one I found a carelessness?

```c
// src/encode.c#L1211

/* Error on illegal tile offsets */
if (context->tile_size_x && context->tile_size_y) {
    if (context->tile_offset_x <= context->offset_x - context->tile_size_x
        || context->tile_offset_y <= context->offset_y - context->tile_size_y) {
        PyErr_SetString(PyExc_ValueError,
                        "JPEG 2000 tile offset too small; top left tile must "
                        "intersect image area");
    }

    if (context->tile_offset_x > context->offset_x
        || context->tile_offset_y > context->offset_y) {
        PyErr_SetString(PyExc_ValueError,
                        "JPEG 2000 tile offset too large to cover image area");
        Py_DECREF(encoder);
        return NULL;
    }
}
```

Why is not the first ```PyErr_SetString``` followed by a ```return``` just like the second one?

But if this is a wrong issue for my limited understanding, please tell me, I will appreciate that very much.

**Comment by radarhere** [comment]
Looks good to me - thanks for pointing it out. I've created PR #3967 to correct it.
