### ISSUE TITLE
Support CMYK Rich/True Black

### ISSUE THREAD

**Issue by Gibbz** [python-pillow/Pillow#3974]
### What did you do?
Convert CMYK to RGB is missing True Black, or Rich Black support

### What did you expect to happen?
Blacks come out incorrect in RGB conversion from CMYK.
Attached is the function bellow.

[crop.zip](https://github.com/python-pillow/Pillow/files/3400283/crop.zip)

### What are your OS, Python and Pillow versions?

* OS:  Win 10
* Python: 3.7
* Pillow: 6.1.0

```python
def convert_to_srgb(img):
    # this doesn't support rich black, so blacks are incorrectly coloured!
    icc = img.info.get('icc_profile', '')
    if icc:
        io_handle = io.BytesIO(icc)     # virtual file
        src_profile = ImageCms.ImageCmsProfile(io_handle)
        dst_profile = ImageCms.createProfile('sRGB')
        # INTENT_PERCEPTUAL = 0 (DEFAULT) (ImageCms.INTENT_PERCEPTUAL) 
        # INTENT_RELATIVE_COLORIMETRIC = 1 (ImageCms.INTENT_RELATIVE_COLORIMETRIC) 
        # INTENT_SATURATION = 2 (ImageCms.INTENT_SATURATION) 
        # INTENT_ABSOLUTE_COLORIMETRIC = 3 (ImageCms.INTENT_ABSOLUTE_COLORIMETRIC)
        new_img = ImageCms.profileToProfile(img, src_profile, dst_profile, renderingIntent=0, outputMode='RGB')
        new_img.info['dpi'] = img.info['dpi']
    return new_img
```

**Comment by radarhere** [comment]
The image that you attached is in RGB mode, not CMYK? Ideally, it would be great if you could attach both the image that you are passing into the method and the resulting image.

**Comment by Gibbz** [comment]
Actually this is not an issue. After further investigation it looks correct. 
My confusion comes from the fact that I would expect CMYK (0,0,0,100) to come out as RGB(0,0,0). However it looks like only CMYK(100,100,100,100) should come out to RGB(0,0,0).
