### ISSUE TITLE
Can't open tiff file

### ISSUE THREAD

**Issue by rbavery** [python-pillow/Pillow#3984]
### What did you do?
I tried to open a float32 geotiff with pillow version `6.1.0`
```python
from PIL import Image 
Image.open("L5_september_29_smallclip.tiff") 
```
### What did you expect to happen?

Pillow would open the tiff without error

### What actually happened?

```
In [3]: PIL.Image.open("L5_september_29_smallclip.tiff")                        
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
<ipython-input-3-19fe77078e5e> in <module>
----> 1 PIL.Image.open("L5_september_29_smallclip.tiff")

AttributeError: module 'PIL' has no attribute 'Image'

In [4]: from PIL import Image                                                   

In [5]: Image.open("L5_september_29_smallclip.tiff")                            
---------------------------------------------------------------------------
OSError                                   Traceback (most recent call last)
<ipython-input-5-49e5afbd3bfa> in <module>
----> 1 Image.open("L5_september_29_smallclip.tiff")

~/miniconda3/lib/python3.7/site-packages/PIL/Image.py in open(fp, mode)
   2820     for message in accept_warnings:
   2821         warnings.warn(message)
-> 2822     raise IOError("cannot identify image file %r" % (filename if filename else fp))
   2823 
   2824 

OSError: cannot identify image file 'L5_september_29_smallclip.tiff'
```
The file exists, this is different than the `no such file or directory` error.
I've seen other issues and posts that inspect the first values in the bytearray of the file, so here it is in case it helps diagnose the issue.

```
with open("L5_september_29_smallclip.tiff", 'rb') as img: 
    ...:     f = img.read() 
    ...:     b = bytearray(f) 

In [17]: b[0:20]                                                                                     
Out[17]: bytearray(b'II*\x00\x08\x00\x00\x00\x11\x00\x00\x01\x03\x00\x01\x00\x00\x00\xaa\x01')

```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 10.04
* Python: 3.7.3
* Pillow: 6.1.0

Github won't let me upload the tiff image so here is a link: https://ucsb.box.com/s/taz9fb3rcur1d24bt6s7g6cw2ynkw747

**Comment by Gibbz** [comment]
I'm having an issue opening some of my TIF files also!
For me it seems to be on anything with transparency?

Ive included a few more test files.
Simply crashes on Image.open();

File "C:\Users\bronson\AppData\Local\Programs\Python\Python37-32\lib\site-packages\PIL\Image.py", line 2822, in open raise IOError("cannot identify image file %r" % (filename if filename else fp))

[resource.zip](https://github.com/python-pillow/Pillow/files/3415475/resource.zip)

**Comment by radarhere** [comment]
The format keys for the different images are -
* L5_september_29_smallclip.tiff - (b'II', 1, (3, 3, 3), 1, (32, 32, 32), (0, 0))
* resource/workbook_spine.tif and gradient_spine.tif - (b'II', 5, (1,), 1, (8, 8, 8, 8, 8), (2,))

The image from @rbavery has three bands of float data, so that looks like part of #1888.

The images from @Gibbz are CMYK. Looking at the format key, I would say that it is CMYKA, which lines up with the statement that it's failing for images with transparency. So again, this isn't a bug, it's something that haven't supported yet.

**Comment by Gibbz** [comment]
@radarhere should I open a new issue for support for CMYKA?
Thanks

**Comment by radarhere** [comment]
If you wanted to, that would could improve clarity, yeah. Also, if you have an image that could be included under the Pillow license as part of the test suite, and if you could let us know what you would like to do with the image once you have loaded it.

**Comment by rbavery** [comment]
Closing since this is a duplicate, I included the test data in the main issue where this is being tracked: https://github.com/python-pillow/Pillow/issues/1888

**Comment by Dan-De** [comment]
tif only has one f. May have been the initial problem
