### ISSUE TITLE
Add tiff_zip compression to TIFF files

### ISSUE THREAD

**Issue by Gibbz** [python-pillow/Pillow#3990]
### What did you do?
Add TIFF zip compression support

### What are your OS, Python and Pillow versions?
* OS: Windows 10
* Python: 3.7
* Pillow: 6.1

**Comment by radarhere** [comment]
Looking into this, I think Pillow already does support TIFF zip compression, just using the value 'tiff_deflate'. Feel free to let know if you think that doesn't work.

**Comment by Gibbz** [comment]
Ive just checked this, its an unusual name for zip compression, but it looks like it is correct!
Thanks
