### ISSUE TITLE
Image.mode incorrectly identifies image as RGB while it has transparency

### ISSUE THREAD

**Issue by mHaisham** [python-pillow/Pillow#3992]
### What did you do?
Convert all RBGA images to RGB

### What did you expect to happen?
expected [image](https://s6.mkklcdnv6.com/mangakakalot/s2/spirit_sword_sovereign/chapter_82_remain_strong/12.jpg) to be identified RGBA

### What actually happened?
[image](https://s6.mkklcdnv6.com/mangakakalot/s2/spirit_sword_sovereign/chapter_82_remain_strong/12.jpg) was identified as RGB

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.4
* Pillow: 6.1.0

```python
from PIL import Image
import requests

path = '12.jpg'
response = requests.get("https://s6.mkklcdnv6.com/mangakakalot/s2/spirit_sword_sovereign/chapter_82_remain_strong/12.jpg")
with open(path, 'wb') as f:
    f.write(response.content)

img = Image.open(path)

print('[MODE] [{0}] {1}'.format(img.mode, path))
```
output
```
[MODE] [RGB] 12.jpg
```

expected
```
[MODE] [RGBA] 12.jpg
```

**Comment by radarhere** [comment]
Be aware that whatever the filename might suggest, this is a PNG, not a JPEG.

This image is not in RGBA mode, where an alpha value can be specified for each pixel, but in RGB mode with a single colour marked to represent transparency - in this case, #fefefe.

So yes, this looks correct to me. Is there a particular task that you are struggling with?

**Comment by mHaisham** [comment]
> This image is not in RGBA mode, where an alpha value can be specified for each pixel, but in RGB mode with a single colour marked to represent transparency - in this case, #fefefe.

How did you figure this out?
Is there a way to detect this using Pillow, if so could you point me to that direction.

> So yes, this looks correct to me. Is there a particular task that you are struggling with because of this?

I'm trying to convert these images to pdf using img2pdf,
img2pdf gives the error ```Exception: Refusing to work on images with alpha channel```

**Comment by radarhere** [comment]
```python
from PIL import Image
im = Image.open("12.jpg")
print(im.mode)  # RGB
print(im.info)  # {'transparency': (254, 254, 254), 'dpi': (96, 96)}

# One way to remove the transparency would be to save it as an actual JPG
im.save("out.jpg")

# To save it as a PNG without the transparency
im = Image.open("12.jpg")
del im.info["transparency"]
im.save("out.png")

# I think these are both hard to read because of the #fefefe transparent colour
# So this changes the transparent pixels to another colour
im = Image.open("12.jpg")
pixels = im.load()
for i in range(im.width):
    for j in range(im.height):
        if pixels[i, j] == im.info["transparency"]:
            pixels[i, j] = (0, 0, 0)
del im.info["transparency"]
im.save("out2.png")
```

**Comment by mHaisham** [comment]
Thank you
