### ISSUE TITLE
Converting P mode images to HSV fails with "ValueError: conversion not supported" in version 6.0.0 and later

### ISSUE THREAD

**Issue by BaconRanch** [python-pillow/Pillow#3997]
### What did you do?
I want to take an RGB PNG as input, quantize it, convert to HSV and call getcolors() on the result to see a listing of (pixel count, (H,S,V)) values.  As a bigger-picture idea of what I'm trying to accomplish, the goal is to look for a certain hue and determine if the number of pixels that are "close" to that hue are above a certain threshold.  Eg: "Do more than 10% of the pixels in the image have a hue near 250?"  The information from getcolors helps quite a bit with answering that question and the quantization helps with the "near 250" part of the question.  The code below is what I've been using, and it works fine up through Pillow 5.4.1.

### What did you expect to happen?
Pillow 5.4.1 produces this output when calling getcolors():
```python
[(3601, (244, 227, 146)),
 (3605, (155, 255, 128)),
 (21059, (117, 37, 171)),
 (44719, (63, 195, 136)),
 (6406, (26, 137, 250)),
 (4166, (11, 203, 237)),
 (1912, (194, 184, 255)),
 (5664, (159, 220, 255)),
 (411983, (0, 0, 255)),
 (1137, (0, 0, 0))]
```

### What actually happened?
Pillow 6.0.0 and later throws an exception as part of the convert() call:
```
ValueError                                Traceback (most recent call last)
script.py in <module>()
      1 from PIL import Image
      2 x = Image.open('PNG-Gradient_hex.png').quantize(colors=10,method=1)
----> 3 print x.convert(mode='HSV').getcolors()

PIL/Image.pyc in convert(self, mode, matrix, dither, palette, colors)
   1030                 # normalize source image and try again
   1031                 im = self.im.convert(getmodebase(self.mode))
-> 1032                 im = im.convert(mode, dither)
   1033             except KeyError:
   1034                 raise ValueError("illegal conversion")

ValueError: conversion not supported
```
### What are your OS, Python and Pillow versions?

* OS: macOS Mojave (10.14.5)
* Python: 2.7.16
* Pillow: 6.0.0 and later

```python
from PIL import Image
x = Image.open('PNG-Gradient_hex.png').quantize(colors=10,method=1)
print x.convert(mode='HSV').getcolors()
```

Sample input image:
![PNG-Gradient_hex](https://user-images.githubusercontent.com/1821299/62164064-51b96100-b2e1-11e9-8a66-9508c1dbd93b.png)

**Comment by hugovk** [comment]
`git bisect` points to f61828acdcc846cbf29ff991425eb40d966d5b03 from PR https://github.com/python-pillow/Pillow/pull/3726:

`bisect.sh`:
```bash
#!/usr/bin/env bash
python3 setup.py clean
rm -f "PIL/*.so"
pip3 uninstall pillow -y
python3 setup.py install
python3 3997.py
```
`3997.py`:
```python
from PIL import Image
x = Image.open("3997.png").quantize(colors=10, method=1)
print(x.convert(mode="HSV").getcolors())
```
```console
$ python --version
Python 3.7.4
$ git bisect start
$ git bisect good 5.4.1
$ git bisect bad 6.0.0
$ git bisect run ./bisect.sh
...
f61828acdcc846cbf29ff991425eb40d966d5b03 is the first bad commit
commit f61828acdcc846cbf29ff991425eb40d966d5b03
Date:   Tue Mar 19 11:13:58 2019 +1100

    Promote P images to PA in putalpha

:040000 040000 fbea0af0f1959311d72dd269fd70607cf255e84a 9aa294c996483580d0752a74c7d9d27a7ecfe487 M	Tests
:040000 040000 d2b9276a992da843d799dc94a578981e5eed635f 2759727adb9e49468f91217bfc19bb266cf8d6ae M	src
bisect run success
```

---

**Comment by radarhere** [comment]
If you're interested in an immediate workaround, I would suggest converting to RGB first. Quickly looking at the situation, that is what Pillow would have been doing internally in 5.4.1.

```python
from PIL import Image
x = Image.open('PNG-Gradient_hex.png').quantize(colors=10,method=1)
print x.convert('RGB').convert('HSV').getcolors()
```

**Comment by BaconRanch** [comment]
Thank you!  Yes, that fixes my problem.
While I'm personally happy with this solution, I understand this is still an issue since the calling code has to be explicit about converting to RGB first, so I'll keep the ticket open and leave it to you all to decide what to do with it.

**Comment by radarhere** [comment]
I've created PR #4004 to resolve this.

**Comment by radarhere** [comment]
Also, while this has no bearing on the problem that you've reported, since you are using Python 2.7, you should be aware that Pillow is a project that has committed to dropping support for Python 2.7 in 2020 - https://python3statement.org/.

**Comment by BaconRanch** [comment]
I'm in the slow process of converting codebases at work over from 2.7 to 3 now.  I think about the end of 2019 bearing down as a deadline all the time.  Thank you for supporting 2.7 through the end of 2019 and not leaving earlier!  I need every day I can get!
