### ISSUE TITLE
Creating ICNS files from RGB image

### ISSUE THREAD

**Issue by rzllmr** [python-pillow/Pillow#3999]
There is an issue with creating ICNS files from images without an alpha channel that leads to a crash. It is due to the **iconutil** returning the error "*Unsuported image format*", at least on Mac OS X 10.11. I could not check for the behavior on later distributions, but provide the code for replicating it here:

```python
import sys
import os
from PIL import Image

if sys.platform != "darwin":
  print("creation of ICNS files only supported on a Mac")
else:
  script_dir = os.path.dirname(os.path.realpath(sys.argv[0]))
  png_path = os.path.join(script_dir, "test.png")
  icns_path = os.path.join(script_dir, "test.icns")

  img = Image.open(png_path, "r")
  if img.mode == "RGBA":
    # simulate using an image without alpha channel
    img = img.convert("RGB")
  img.save(icns_path, format="ICNS")
```
Running the script with the attached file in the same directory results in the output:
```
Traceback (most recent call last):
  File "/obscured/path/to/icns_test.py", line 16, in <module>
    img.save(icns_path, format="ICNS")
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/Image.py", line 1994, in save
    save_handler(self, fp, filename)
  File "/Library/Frameworks/Python.framework/Versions/3.7/lib/python3.7/site-packages/PIL/IcnsImagePlugin.py", line 354, in _save
    raise CalledProcessError(retcode, convert_cmd)
subprocess.CalledProcessError: Command '['iconutil', '-c', 'icns', '-o', '/obscured/path/to/test.icns', '/var/folders/2y/_5tnr_ps4rg2mljz0v7kxpg40000gn/T/tmp2wjc0orx.iconset']' returned non-zero exit status 1.
```
![test](https://user-images.githubusercontent.com/30299783/62213744-e84e5680-b3a3-11e9-9600-2c26d4bb0979.png)

**Comment by rzllmr** [comment]
A quick fix would be:
``` python
if im.mode == 'RGB':
  im.putalpha(Image.new('L', im.size, 255))
```
in *src/PIL/IcnsImagePlugin.py* line 314

**Comment by radarhere** [comment]
What version of Pillow are you using?

**Comment by hugovk** [comment]
Cannot reproduce with latest Pillow 6.1.0 and latest macOS Mojave 10.14.6.

**Comment by rzllmr** [comment]
I'm on Mac OS X 10.11.5 with Pillow 6.1.0 for Python 3.7.
So it seems they fixed the issue in the **iconutil** tool distributed with later OS X version. Maybe we can isolate the problem to the distributions affected, but I don't know about the **iconutil** version history.

**Comment by hugovk** [comment]
Are you able to upgrade your macOS version? 

10.11 El Capitan is unsupported as of August 2018.

https://en.wikipedia.org/wiki/OS_X_El_Capitan

**Comment by rzllmr** [comment]
Ah ok, didn't notice it being unsupported but found respective page in the docs. Thanks for the hint!
Unfortunately I cannot upgrade the macOS version as of now and use the workaround until I can. But it seems there is no need for this issue then.
