### ISSUE TITLE
Cannot bundle Pillow using py2app on macOS

### ISSUE THREAD

**Issue by kollivier** [python-pillow/Pillow#4001]
### What did you do?

Tried to bundle python apps that use Pillow into a .app bundle on macOS using py2app.

### What did you expect to happen?

A working .app bundle of my Python code would be produced.

### What actually happened?

py2app failed to properly bundle Pillow due to an issue with re-writing the dylib install path when moving the dependency dylibs into the app bundle. The reported error is:

ValueError: New Mach-O header is too large to relocate in '/code/LearningEquality/exelearning/dist/exe.app/Contents/Resources/lib/python2.7/PIL/.dylibs/liblcms2.2.dylib' (new size=1688L, max size=1680L, delta=48L)

I was able to fix this locally by rebuilding Pillow after recompiling the homebrew dependencies with the following added linker flags: `-Wl,-headerpad_max_install_names`

### What are your OS, Python and Pillow versions?

* OS: macOS 10.13.6
* Python: 2.7, 3.4, 3.6
* Pillow: 6.1.0

I could work on a reproducible app if needed, but it would need at least two files, a setup.py file and a main.py that imports pillow, so would probably upload a zip somewhere. If the code for installing the brew dependencies on macOS are in the repo, would be happy to submit a PR with the fix.

**Comment by radarhere** [comment]
What version of py2app are you using? I ask as this is a known issue for py2app - https://bitbucket.org/ronaldoussoren/py2app/issues/219/new-mach-o-header-is-too-large-to-relocate - and updating might fix it.

**Comment by kollivier** [comment]
Thanks for the prompt reply! I have tried with a couple different py2app versions, including the latest versions of both py2app and macholib (0.19 and 1.11, respectively), and the problem still occurs. Note also the last two comments in that thread, from June, saying they still are having the issue, and reporting how they fixed it by recompiling Pillow. It looks like the FAQ on this issue also still recommends recompiling libraries that trigger this issue: https://py2app.readthedocs.io/en/latest/faq.html

I've compiled C++ / Obj-C macOS apps as well, and it's important in those cases too to specify `-headerpad_max_install_names`, so I was surprised when he said he could fix it in `macholib`. I don't know if there is a general fix to be had, but in the meantime, I can confirm that re-compiling the homebrew libraries with that flag as described in the ticket fixes the issue. I've just had to go through the Pillow recompile several times at this point (we use virtualenvs extensively) so I thought I would file the issue in case it was not known.

**Comment by radarhere** [comment]
Thanks. If you're willing to go through the process of putting together a reproducible app, that would be interesting - one that works without Pillow, but fails with Pillow. You should be able to upload a zip in a comment on this issue. My other question to help with reproducibility is - how did you install your Python libraries?

**Comment by radarhere** [comment]
Also, while not related to your issue, be aware that in 2020, Pillow will no longer support Python 2.7, Pillow being committed to https://python3statement.org/

**Comment by kollivier** [comment]
Sorry for the delayed reply! My Mac laptop had a swollen battery and it took it about a week to get it fixed and restored, making it difficult to put together a sample Mac app!

Now that I'm up and running again, here is a minimal sample application:

[pillow_mac_setup.zip](https://github.com/python-pillow/Pillow/files/3499539/pillow_mac_setup.zip)

Please let me know if you have any questions about it, etc.

**Comment by kollivier** [comment]
Oh, I didn't make a version that works without Pillow, but if you comment out the Pillow usage and replace it with `print("Hello World")`, and remove the `PIL` package requirement in `setup.py`, it should build and run okay. (If you call `./dist/main.app/Contents/MacOS/main` of course, as it will have no actual GUI to present.)

**Comment by radarhere** [comment]
Thanks. I'm able to replicate using TravisCI.

To link the issues, this is the re-emergence of #3297

**Comment by radarhere** [comment]
Testing, I find that Pillow 5.3 works. To check that I am correctly reproducing your situation, could you tell me if it works for you?

**Comment by kollivier** [comment]
Yes, it does! When I use `otool -L` to check the linked deps paths, everything looks pretty much the same to me, so I'm not sure what has changed between the two versions. My current theory is that something in the latest builds is causing the `@loader_path` check in `macholib` to fail and causing it to try and 'fix' the dependency link, but nothing about the libs I've checked so far jumps out at me as causing this.

**Comment by yig** [comment]
[reproduce.txt](https://github.com/python-pillow/Pillow/files/4423153/reproduce.txt)
I ran into this as well. PIL's littlecms dependency needs an additional linker flag (`-headerpad_max_install_names`) to make relocating with `py2app` possible.

Here is a very short reproducible example:

```
$ mkdir py2app_PIL
$ cd py2app_PIL/
$ python3 -m venv .venv
$ . .venv/bin/activate
(.venv) $ pip install Pillow py2app
...
Successfully installed Pillow-7.1.1 altgraph-0.17 macholib-1.14 modulegraph-0.18 py2app-0.21
(.venv) $ echo 'import PIL' > main.py
(.venv) $ echo 'print( PIL.__version__ )' >> main.py
(.venv) $ py2applet --packages=PIL main.py 
running py2app
...
ValueError: New Mach-O header is too large to relocate in '/private/var/folders/z9/y340rgqs6ydbc7c54smlyt900000gn/T/tmpxayxil_9/dist/main.app/Contents/Resources/lib/python3.7/PIL/.dylibs/liblcms2.2.dylib' (new size=1688, max size=1680, delta=48)
```

I am running macOS 10.14.6 with homebrew Python 3.7.7 and Pillow 7.1.1.

As asked above ( https://github.com/python-pillow/Pillow/issues/4001#issuecomment-521573935 ), this error does not occur with Pillow 5.3.

The other related issue ( https://github.com/python-pillow/Pillow/issues/3297 ) says the non-relocatability of `libtiff` was fixed in `macholib` 1.11. The output of `pip` shows that it installed `macholib-1.14`.

Someone on stackoverflow ( https://stackoverflow.com/questions/56604893/python-py2app-and-pillow-error-mach-o-header-is-too-large ) fixed the problem by recompiling littlecms with the aforementioned linker flag. They also suggested just deleting `liblcms2.2.dylib`, as in `rm .venv/lib/python3.7/site-packages/PIL/.dylibs/liblcms2.2.dylib`. That also "works".

Here are the commands without output for copying-and-pasting:

```
mkdir py2app_PIL
cd py2app_PIL/
python3 -m venv .venv
. .venv/bin/activate
pip install 'Pillow==5.3' py2app
echo 'import PIL' > main.py
echo 'print( PIL.__version__ )' >> main.py
py2applet --packages=PIL main.py
```

The full output is attached.

**Comment by radarhere** [comment]
Linking to https://github.com/ronaldoussoren/py2app/issues/258

**Comment by radarhere** [comment]
Testing, I find that this started working with Pillow 7.2, presumably as a result of updating to lcms2 2.10 in the wheels.
If anyone is still experiencing this, feel free to comment and this can be re-opened.
