### ISSUE TITLE
Unable to create a PDF out of generated images

### ISSUE THREAD

**Issue by hallowf** [python-pillow/Pillow#4007]
Hey there,

### What did you do?

So I generated 500 images using the snippet of code below:
```python
import os
from random import choice
from PIL import Image


def generate_images(count):
    cv = [i for i in range(251) if i != 0]
    if not os.path.isdir("images"):
        os.mkdir("images")
    for i in range(count + 1):
        if i != 0:
            img = Image.new("RGB", (1000, 1000),
                            color=(choice(cv), choice(cv), choice(cv)))
            img.save("images/%i.png" % i)
            img.close()
```
Then I tried to create a pdf out of them with the 2 following methods
```python
# creates a pdf
def make_pdf(handles):
    letters = string.ascii_lowercase
    name = "".join(choice(letters) for i in range(10)) + ".pdf"
    print("making pdf: %s" % name)
    first = handles[0]
    handles.pop(0)
    first.save(name, "PDF", resolution=90.0, save_all=True,
               append_images=handles)

# Opens the image verifies it and appends it to list
def test_img_with():
    images = []
    for root, __, files in os.walk("images", topdown=False):
        for file in files:
            source_path = os.path.join(root, file)
            with Image.open(source_path) as img:
                try:
                    img.verify()
                    images.append(img)
                except Exception as e:
                    print(e)
                    print("skipping image")
    print(len(images))
    print("opening all images")
    make_pdf(images)
    print("done")

# Just appends to list and opens the images with list comprehension
def test_img_comp():
    images = []
    for root, __, files in os.walk("images", topdown=False):
        for file in files:
            source_path = os.path.join(root, file)
            print("appending image: %s" % source_path)
            images.append(source_path)
    print("opening all images")
    images = [Image.open(img) for img in images]
    make_pdf(images)
    print("done")
```

### What did you expect to happen?

I expected both methods to work

### What actually happened?

the `test_img_comp` function succeeds
the `test_img_with` function fails with the following traceback:

```
Traceback (most recent call last):
  File "/home/hallowf/Documents/Github/STPDF/venv/lib/python3.6/site-packages/PIL/ImageFile.py", line 163, in load
    seek = self.load_seek
AttributeError: 'PngImageFile' object has no attribute 'load_seek'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "processing.py", line 115, in <module>
    test_img_with()
  File "processing.py", line 97, in test_img_with
    make_pdf(images)
  File "processing.py", line 80, in make_pdf
    append_images=handles)
  File "/home/hallowf/Documents/Github/STPDF/venv/lib/python3.6/site-packages/PIL/Image.py", line 1973, in save
    self._ensure_mutable()
  File "/home/hallowf/Documents/Github/STPDF/venv/lib/python3.6/site-packages/PIL/Image.py", line 628, in _ensure_mutable
    self._copy()
  File "/home/hallowf/Documents/Github/STPDF/venv/lib/python3.6/site-packages/PIL/Image.py", line 621, in _copy
    self.load()
  File "/home/hallowf/Documents/Github/STPDF/venv/lib/python3.6/site-packages/PIL/ImageFile.py", line 166, in load
    seek = self.fp.seek
AttributeError: 'NoneType' object has no attribute 'seek'
```

### What have you tried ?

So replacing the `img.verify()` function call in `test_image_with` with `img = img.rotate(...) # or some other method of manipulation` makes the code execute successfully and generate a pdf.

However any other methods like adding `handles = [img.load() for img in handles]` before trying to create a pdf seem to fail with always the same error.

```python
seeks = [hasattr(img, "seek") for img in handles]
print(False in seeks) # Prints False
```

I have also tried to install Pillow 6.0 but since it failed with the exact same error my guess is there is something wrong with the generated images

### More info

I have the need to manipulate a batch of images before actually storing them as a pdf, I have found out that storing these images in memory using the  `Image.open` method can easily increment the memory usage of the device (**as shown in the Attached images**), but i do need to process them before actually making a pdf

#### Attached images

`test_img_with`
![with](https://user-images.githubusercontent.com/34419077/62416481-8d329300-b633-11e9-9e42-8a71e82b3d43.png)

`test_img_comp`
![comp](https://user-images.githubusercontent.com/34419077/62416485-915eb080-b633-11e9-9257-38c43c0153e5.png)

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04 LTS
* Python: 3.6.8 (default, Jan 14 2019, 11:02:34)
* Pillow: 6.1/6.0

Thank you for your attention,
Alexandre Cortegaça

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.verify

> **Image.verify()**
> Verifies the contents of a file. For data read from a file, this method attempts to determine if the file is broken, without actually decoding the image data. If this method finds any problems, it raises suitable exceptions. If you need to load the image after using this method, you must reopen the image file.

So one problem is that the file is being closed by `verify`, before the image data is loaded. You could just open the image twice from the file, but a better way would be to only open the file once, while opening the image twice.

However, the other problem is that because you have opened the image with a context manager, the image is also closed when the context manager exits before it is image data is loaded.

https://pillow.readthedocs.io/en/stable/reference/open_files.html

> I don’t think that there’s any way to make this safe without changing the lazy loading:
> 
> Dangerous FAIL:
> with open('test.jpg', 'rb') as f:
> &nbsp;&nbsp;&nbsp;&nbsp;im5 = Image.open(f)
> im5.load() # FAILS, closed file

Part of `rotate()` or another manipulation operation is loading in the image data, so yes, a side effect of that would be that your code works.

So out of that, here is my suggestion. Let me know if anything is unclear or if you have further questions.

```python
def test_img_with():
    images = []
    for root, __, files in os.walk("images", topdown=False):
        for file in files:
            source_path = os.path.join(root, file)
            with open(source_path, "rb") as fp:
                with Image.open(source_path) as img:
                    try:
                        img.verify()
                    except Exception as e:
                        print(e)
                        print("skipping image")
                        continue
                with Image.open(source_path) as img:
                    img.load()  # Loading the image before the context manager exits
                    images.append(img)
    print(len(images))
    print("opening all images")
    make_pdf(images)
    print("done")
```

Also, maybe you know this already, but

```python
first = handles[0]
handles.pop(0)
```

could be made shorter as

```python
first = handles.pop(0)
```

**Comment by hallowf** [comment]
Thank you very much for the detailed explanation!, no further questions :+1:
