### ISSUE TITLE
Improve documentation on Source Build options

### ISSUE THREAD

**Issue by scottfurry** [python-pillow/Pillow#4008]
While build from source for distribution upgrade, I encountered a problem with package building instructions. Build was painfully slow. Research led to [Source Build -> Build Options](https://pillow.readthedocs.io/en/stable/installation.html#build-options) explanation. Instructions being used had not implemented `MAX_CONCURRENCY` environment variable.

However, description provide for was rather unclear. Yes, setting to a value of `1` disables parallel building. And from variable naming, it is assumed, intent was to direct build process on how to maximize CPU usage. A better explanation could be provided for this option.

Feature request - w/o ENV variable - what happens? I'm _assuming_, though could be made clearer, value has to be a non-zero positive integer. What effect is implied when a value of 2 or greater is used? Description in link is vague, IMHO.

### What are your OS, Python and Pillow versions?

* OS: Funtoo (Gentoo derivative)
* Python: 3.7
* Pillow: 5.2.0

**Comment by radarhere** [comment]
Okay. What do you think of this idea?

> Environment variable: MAX_CONCURRENCY=n. Pillow can use multiprocessing to build the extension. Setting MAX_CONCURRENCY sets the number of CPUs to use, or can disable parallel building by using a setting of 1. By default, it uses 4 CPUs, or if 4 are not available, as many as are present.

**Comment by scottfurry** [comment]
@radarhere - much improved and very clear. Yes, please?
Just to clarify. Without the setting build process does a `best guess`?

**Comment by radarhere** [comment]
If it is not set, and there are 4 CPUs, or more than 4 CPUs, it uses 4.
If it is not set, and there are 3 CPUs, it uses 3.
If it is not set, and there are 2 CPUs, it uses 2.
If it is not set, and there is 1 CPU, it uses 1.

Do you think the description needs to be updated to explain this better?

**Comment by scottfurry** [comment]
Ouch...
How about:
"If not set, build process will do a best guess based on CPU core count to a maximum of four."

**Comment by radarhere** [comment]
Didn't mean to offend, just trying to avoid any further miscommunication by breaking things down as much as possible.

I've created PR #4011 to resolve this.

**Comment by scottfurry** [comment]
@radarhere - No offense taken. I was being obtuse and not paying attention to details being given. It's been a frustrating few days patching and upgrading a system (problems upstream from me but I have to clean up). You did great. Thanks for helping to clear up my foolishness. Hopefully others will LFMF's. :wink:

FWIW, I've been building locally w/ `MAX_CONCURRENCY` changes and have seen some improvement in building load averages. Just wished it didn't take so long. Time to convince someone to provide a `binary` version for this...
