### ISSUE TITLE
Unclear (incorrect?) documentation of "dpi" parameter for saving TIFF images

### ISSUE THREAD

**Issue by jkrankl** [python-pillow/Pillow#4013]
# What did you do?

I wanted to save a TIFF image.

On https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving-tiff-images, I read the following documentation for the `dpi` parameter (below the `resolution`, `x_resolution`, `y_resolution` parameters):

> Either a Float, 2 tuple of (numerator, denominator) or a IFDRational. Resolution implies an equal x and y resolution, dpi also implies a unit of inches.

I read this as:

* I can specify _one_ numeric value for the `dpi` parameter ("Either **a** Float, **[a]** 2 tuple of (numerator, denominator) or **a** IFDRational."
* This one numeric value will specify the x and the y resolution in dots per inch
* The format of this one numeric value can either be
  - a `float`
  - a tuple representing one rational number (numerator, denominator)
  - an IFDRational number 

I wanted to save an image with an x- and a y-resolution of 300 dpi (numerator 300, denominator 1). I called

```python
my_image.save('my_filename.tif', dpi=(300, 1))
```

### What did you expect to happen?

To get an image with an x- and a y-resolution of 300 dpi. 

### What actually happened?

I got an image with an x-resolution of 300 dpi and a y-resolution of 1 dpi

### What are your OS, Python and Pillow versions?

* OS: debian 10
* Python: 3.7.3
* Pillow:  6.1.0

**Comment by radarhere** [comment]
The documentation was added in #369

Looking at code, this functionality was removed in #1419, where 'A tuple of more than one rational tuples' 'flatten to floats' was removed, along with `ifd[X_RESOLUTION] = _cvt_res(dpi[0])` being changed to `ifd[X_RESOLUTION] = dpi[0]`.

So yes, this documentation is now incorrect. I've created PR #4015 to fix it.
