### ISSUE TITLE
floodfill wraps around

### ISSUE THREAD

**Issue by snoopyjc** [python-pillow/Pillow#4016]
The ImageDraw.floodfill code assumes a negative index will raise an IndexError, but python wraps that around to the last element, which is not the desired effect.  This causes a floodfill that hits the left side or the top of the image to wrap around to the other side.  Code:

```python
                    try:
                        p = pixel[s, t]
                    except (ValueError, IndexError):
                        pass
                    else:
```

Fix:

```python
                    try:
                        if s < 0 or t < 0:
                            raise IndexError
                        p = pixel[s, t]
                    except (ValueError, IndexError):
                        pass
                    else:
```

**Comment by radarhere** [comment]
Thanks. I've created PR #4017 to resolve this, adjusting your solution slightly.

**Comment by hugovk** [comment]
Thanks both, merged!

**Comment by snoopyjc** [comment]
Great - thanks!!

-joe
