### ISSUE TITLE
ImageColor getrgb

### ISSUE THREAD

**Issue by as485** [python-pillow/Pillow#4023]
Hi there, When I was learning and trying to understand the function "getrgb(color)" in Pillow/src/PIL/ImageColor.py, I was confused about the description of the its delivered function. My understanding of this code snippet is "test the fit of a block of color". Do I understand that right?

**Comment by hugovk** [comment]
The docs say:

> Convert a color string to an RGB tuple. If the string cannot be parsed, this function raises a ValueError exception.

https://pillow.readthedocs.io/en/stable/reference/ImageColor.html#PIL.ImageColor.getrgb

For example:

```python
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import ImageColor
>>> ImageColor.getrgb("blue")
(0, 0, 255)
>>> ImageColor.getrgb("yellow")
(255, 255, 0)
>>> ImageColor.getrgb("#224466")
(34, 68, 102)
>>> ImageColor.getrgb("#aa44ff")
(170, 68, 255)
>>> ImageColor.getrgb("#a37")
(170, 51, 119)
>>> ImageColor.getrgb("#CDEF")
(204, 221, 238, 255)
>>> ImageColor.getrgb("rgb(0,255,0)")
(0, 255, 0)
>>> ImageColor.getrgb("rgba(0,0,255,0)")
(0, 0, 255, 0)
>>> ImageColor.getrgb("hsl(360,100%,50%)")
(255, 0, 0)
>>> ImageColor.getrgb("hsv(360,100%,100%)")
(255, 0, 0)
>>>
```

See also "Color Names" at https://pillow.readthedocs.io/en/stable/reference/ImageColor.html#imagecolor-module.

**Comment by radarhere** [comment]
Hi. Looking at your GitHub profile, you have opened a large number of issues titled 'code understanding' in a short amount of time, with very similar descriptions - this seems abnormal to me, so I am closing this issue. If you are genuine and have further questions, or feel that your question has not been answered, feel free to comment and this can be re-opened.

**Comment by as485** [comment]
Thanks for your response very much. I will read the code more carefully.
