### ISSUE TITLE
Pillow for Enterprise

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4026]
This one is for the @python-pillow/pillow-team, but anyone welcome to comment! Please review and give feedback; I'm most likely going to approve Tidelift's proposal to experiment with "Pillow for Enterprise" and other lead generation strategies, but I wanted to include everyone in the process in case I'm missing anything or anyone's potential concerns. (I have mostly zero concern… and Tidelift's success is our success. My only real concern is that we don't annoy anyone :smile: Oh, and I somewhat _hate_ the _overused-and-devoid-of-real-meaning_ marketing term "Enterprise", but I don't have a better idea, so…)

As @brennaheaps explained,

> At the lifter meeting in Boston we talked to many of the attending lifters about co-marketing strategies that might help drive more leads (and thus increase the potential income for your package(s)). The maintainers shared their thoughts with us about the ideas they were most interested in testing. We've suggested a few of these for your package, and are happy to work with you to modify any of these in a way that would work best for your particular case.

And here are the proposal details:

**Pillow for enterprise**
This experiment involves adding a top navigation “For Enterprise” link and creating an Enterprise page on your site that describes the Tidelift Subscription. Full details are here. 

**Social**
Promotion via Twitter or other social networks (such as LinkedIn, which is particularly successful). We’d love to test some language with your audience! Full details are here. 

**Email**
If you have an email list and would like to experiment with promotional emails, we’ve created some sample text. Full details are here.

**Payment for workable leads**
Along with these marketing experiments we’d also like to test paying for what we deem “workable” leads. As you know, we currently offer a $250 payment for any lead that converts to a sale, but we’d like to test paying out $50 for each workable sales lead. Full details are here. 

**Timeline**
We’d like to run these experiments for roughly three months and our hope is that after initial set up this won’t take a ton of time on your part. We’ll continue to monitor on our end and share the results, as well as the payment for leads!

And here's a doc she sent me with more details (nice of GitHub to support file upload!):

- [Pillow + Tidelift marketing tests - share.docx](https://github.com/python-pillow/Pillow/files/3510282/Pillow.%2B.Tidelift.marketing.tests.-.share.docx)

Anyway, I'd love to hear some feedback about how we can proactively help with some of the testing aside from just agreeing to it. That and all other thoughts and comments welcome!

👍

**Comment by hugovk** [comment]
Well, what I'd really like is more help reviewing PRs, but these things sound fine. 

We don't have an email list, so skipping that. We do have Twitter, no problem about sending the occasional thing there, if not too spammy. 

The doc also mentions LinkedIn as something particularly successful; does that mean setting up some sort of Pillow account on there? That's also fine by me.

Would you like to make a start by making PRs to add homepage and docs links? Maybe also something on the README?

Thanks!

**Comment by aclark4life** [comment]
@hugovk Any promising volunteers you know of? I'd also like to start planning for Year Two of funding, which could include:

- Re-up for each of the current members of the 5 person team
- Addition of new team member, previously vetted during a trial period of some reasonable length of time.

The most active members since funding have been you and @radarhere (when did funding start? I don't remember now.) I'd like to keep going as Creator & Project Leader (one day maybe I won't be project leader anymore … but that's probably 5-10 years away at least). And I'm sure @wiredfool would like to keep going as Pillow Man Number Two (2nd in command, resident low level i.e. ``C`` expert). @homm did/does http://python-pillow.org/pillow-perf/, which earned him at least one year's funding as far as I'm concerned 😄 

**Anyway, I'm just going to pick an arbitrary date to tell @brennaheaps to start testing: Sep 1.**

I'll try to get a PR together by then if no one else gets around to it.

**Comment by radarhere** [comment]
We have now passed September 1.

**Comment by aclark4life** [comment]
@radarhere Sep 1 and beyond is the date we've authorized @brennaheaps & Tidelift to start testing … presumably there's lots of things we can do to help them with this e.g. #4046

**Comment by aclark4life** [comment]
Anyone know if this is implemented now? I assume so, because I've seen a lot of hits to https://tidelift.com/subscription/pkg/pypi-pillow lately (via Weekly update from Tidelift)

**Comment by hugovk** [comment]
Yes, done in https://github.com/python-pillow/python-pillow.github.io/pull/15 and https://github.com/python-pillow/Pillow/pull/4046.

**Comment by radarhere** [comment]
If this has been implemented, can this issue be closed then?
