### ISSUE TITLE
Cannot use 'keep'. jpg not recognized as jpg

### ISSUE THREAD

**Issue by soundreactor** [python-pillow/Pillow#4036]
i was trying to resize images and keep the quality setting.
with quality set to a digit it works fine.
probably similar to issue:
https://github.com/python-pillow/Pillow/issues/857

i suspect i have some sort of jpg type that is also not recognized as jpg, just like in the issue.
so i added it inside a zip. 

### What are your OS, Python and Pillow versions?

* OS: windows
* Python: 3.7.3
* Pillow: 6.1.0

[IMG_7679.zip](https://github.com/python-pillow/Pillow/files/3539081/IMG_7679.zip)

```python

from PIL import Image
import os, sys

Image.MAX_IMAGE_PIXELS = None

path = "C:/Users/KE/Desktop/omas 80 Panting Images/"
dirs = os.listdir( path )

def resize():
    for item in dirs:
        if os.path.isfile(path+item) and item.endswith('.jpg'):
            print(path+item)
            # break
            im = Image.open(path+item)
            size = im.size


            f, e = os.path.splitext(path+item)

            if(size[0]>size[1]):
                imResize = im.resize((5000,int(5000*size[1]/size[0])), Image.ANTIALIAS)

            if(size[0]<size[1]):
                imResize = im.resize((int(5000*size[0]/size[1]),5000), Image.ANTIALIAS)


            f = f.replace(path, path + "max/")
            imResize.save(f + '.jpg', 'JPEG', quality='keep')
            # imResize.save(f + '.jpg', 'JPEG', quality=20)

resize()

```

**Comment by hugovk** [comment]
Thank you for the report. 

That's quite a bit of code, please could you reduce it to the smallest self-contained, runnable amount that still reproduces the problem? Tips here:

   * https://stackoverflow.com/help/mcve

**Comment by soundreactor** [comment]
so i think i fount the problem.

this is what happens.

```
im = Image.open(path)
print(im.format)
```
JPEG

```
imResize = im.resize((500,500), Image.ANTIALIAS)
print(imResize .format)
```
None

somehow after  `im.resize ` the image is not a jpeg anymore.
i guess its not intended for that use case.
i'm now using. `im.thumbnail((500,500))` which works fine. its still a jpeg and so it can keep the quality.

the only question is: if the None format is intended behavior or not?

**Comment by radarhere** [comment]
Yes. So `im.thumbnail` is modifying the image in-place, while `im.resize` is creating a copy of the image. The copy is no longer a JPEG - it doesn't take with it all of the information from `im`. This is how the Pillow copy operation behaves in general, it's not specific to your situation.

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.format

> **PIL.Image.format**
> The file format of the source file. For images created by the library itself (via a factory function, or by running a method on an existing image), this attribute is set to None.

**Comment by soundreactor** [comment]
okey. makes sense.
i think i was confused by the error message and that's why i didn't look at the right place.
"Cannot use 'keep' when original image is not a JPEG"
i directly thought of the original input image. now its clear to me that that is of course silly, how would save know what the original input image was in the first place. it just cares if it gets a type JPEG or not.

**Comment by radarhere** [comment]
Cool. Enjoy continuing to use Pillow. Let us know if you have any further questions
