### ISSUE TITLE
EXIF tobytes: ushort format requires 0 <= number <= (0x7fff * 2 + 1)

### ISSUE THREAD

**Issue by andreymal** [python-pillow/Pillow#4037]
1. Download this image: https://cdn.everypony.ru/storage/06/18/58/2019/08/19/3e8e6e42ca.jpg

2. Run `Image.open('3e8e6e42ca.jpg').getexif().tobytes()`

3. Not sure if this is a corrupt image or a Pillow bug, but:

```
PIL/TiffImagePlugin.py:605: UserWarning: Metadata Warning, tag 283 had too many entries: 2, expected 1
  % (tag, len(values))

  File "PIL/Image.py", line 3213, in tobytes
    return b"Exif\x00\x00" + head + ifd.tobytes(offset)
  File "PIL/TiffImagePlugin.py", line 824, in tobytes
    data = self._write_dispatch[typ](self, *values)
  File "PIL/TiffImagePlugin.py", line 659, in <lambda>
    b"".join(self._pack(fmt, value) for value in values)
  File "PIL/TiffImagePlugin.py", line 659, in <genexpr>
    b"".join(self._pack(fmt, value) for value in values)
  File "PIL/TiffImagePlugin.py", line 626, in _pack
    return struct.pack(self._endian + fmt, *values)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

P. S. Why Tiff?

**Comment by radarhere** [comment]
This is failing on tag 37379, https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/brightnessvalue.html.

So, if you want an immediate solution,
```python
from PIL import Image
exif = Image.open('3e8e6e42ca.jpg').getexif()
del exif[37379]
exif.tobytes()
```

**Comment by radarhere** [comment]
Why TIFF? That's where the code for this has lived since Pillow was PIL. Your image is still a JPEG. I guess that the code could live somewhere else, but on the other hand -

https://en.wikipedia.org/wiki/Exif

> The Exif tag structure is borrowed from TIFF files.
