### ISSUE TITLE
Picture's thumbnail partially rendering in Windows explorer

### ISSUE THREAD

**Issue by RoscoeTheDog** [python-pillow/Pillow#4039]
Python 3.7
Pillow 6.1.0

I am doing a batch conversion of files from a few different source photo libraries for testing. The conversion works fine but as I am previewing the file thumbnails through the windows explorer, some of them are obscured by just _blackness_ on the screen. I am not sure if this is a rendering issue within Windows or an encoding problem with Pillow. Please see the screenshot for an example. This occurs when the computer is not under a heavy load and zooming in and out of the explorer also does not fix it- so it is not just the system hanging.

The photos open and display just fine, it is only the preview in the windows explorer that gives this odd behavior. Most of the photos are being converted from JPEG to PNG (yes I know that doesn't make much sense in practicality but it's just for testing the library).

I was using the python _Wand_ library for my project library prior and I do not think this same behavior occurred but there were other performance and decoder related issues that lead me dumping the library from my project.

Although the Pillow source code used is extremely short and simple, I will include it here as well:

```python
def convert_image(input, output, format):

    image = Image.open(input)
    copy = image.copy()

    copy.save(output, format)
```

![image](https://user-images.githubusercontent.com/54086262/64004862-0226aa80-cac4-11e9-96d8-7fa9bcc83a76.png)

**Comment by radarhere** [comment]
- What Windows version are you using?
- Are you able to provide a copy of an image before conversion, and the same image after conversion?

**Comment by RoscoeTheDog** [comment]
Windows 7 Ultimate x64 bit (yes I know I'm old school).

Here are the photo samples. The JPG is before, PNG is after. 
[photo samples.zip](https://github.com/python-pillow/Pillow/files/3561943/photo.samples.zip)

_Note: after copying the converted photo (png) to another directory, the thumbnail problem resolved itself **on the new copy**. The originally outputed copy still has the thumbnail issue._

**Comment by hugovk** [comment]
Sounds like a  Windows issue, that it's creating the thumbnail before the image has been fully saved by Pillow. Then when you copy to  new folder, it can create the thumbnail properly.

Try refreshing thumbnails using a method from https://social.technet.microsoft.com/Forums/windows/en-US/3d37b5ab-5592-4eff-9082-cf25ec9e31da/how-do-i-refresh-thumbnails-in-windows-7?forum=w7itprogeneral

Or copy all your images to a new dir, then move them back. 

And next time Pillow is saving, don't have the folder open showing thumbnails. Either have it showing a list, or close that window.

**Comment by RoscoeTheDog** [comment]
Interestingly, refreshing the thumbnails did not resolve the issue. Maybe because I still had the file-explorer window open while turn on/off the preference? I think I would need to try it again using another file-explorer window that is separate to the photos directory so I can close it while I refresh the Windows preferences.

Having the folder closed as the photos were saving fixed the issue as you mentioned however.
