### ISSUE TITLE
Performance issues on webp save for Pillow >= 5.2.0 from wheel

### ISSUE THREAD

**Issue by stefan8** [python-pillow/Pillow#4040]
### What did you do?
called save on image in webp format

### What did you expect to happen?
it saves quickly

### What actually happened?
it takes 8x time than the same pillow version installed with --no-binary :all:

### What are your OS, Python and Pillow versions?

* OS: Fedora 30 / Ubuntu 16.04
* Python: 3.7.4
* Pillow: >=5.2.0, <=6.1.0

**Comment by radarhere** [comment]
I'm able to reproduce this in testing. I checked if this was a difference between libwebp 1.0.2 (used in the Pillow 6.1.0 wheel) and libwebp 1.0.3, but no such luck. This might be similar to #3441

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/pillow-wheels/pull/125 to resolve this.

**Comment by stefan8** [comment]
great, thanks :)
