### ISSUE TITLE
Saving still WebP image does not use method argument

### ISSUE THREAD

**Issue by sbruder** [python-pillow/Pillow#4042]
### What did you do?

Add the `method` argument (as documented in [the handbook](https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#webp)) with `0` as value to the `Image.save()` function with webp as format.

### What did you expect to happen?

Pillow/WebP encoding the image with that method.

### What actually happened?

The image always got encoded with the default method.

### What are your OS, Python and Pillow versions?

* OS: Debian testing (bullseye)
* Python: 3.7.4
* Pillow: 6.1.0 (from pypi)

Used image: https://upload.wikimedia.org/wikipedia/commons/thumb/c/c3/Python-logo-notext.svg/512px-Python-logo-notext.svg.png (as `image.png`)

```python
from PIL import Image
from io import BytesIO

image = Image.open('image.png')

buffer = BytesIO()
image.save(buffer, format='webp', method=0)
print(buffer.getbuffer().nbytes) # 9212

buffer = BytesIO()
image.save(buffer, format='webp', method=6)
print(buffer.getbuffer().nbytes) # 9212
```

Both of these have the exact same size, which should not be the case given the different method.
Example of different sizes (encoding with `cwebp` tool):
<pre>
$ cwebp -m 0 image.png 2>&1 | grep Output
Output:    <strong>11396</strong> bytes Y-U-V-All-PSNR 52.79 45.11 45.20   48.64 dB
$ cwebp -m 6 image.png 2>&1 | grep Output
Output:    <strong>8408</strong> bytes Y-U-V-All-PSNR 53.12 44.73 44.82   48.43 dB
</pre>

Encoding as animation, however, uses the set method for encoding, as you can see from the different sizes:

```python
# (continuation from above code snippet)

buffer = BytesIO()
image.save(buffer, format='webp', save_all=True, append_images=[image], method=0)
print(buffer.getbuffer().nbytes) # 12310

buffer = BytesIO()
image.save(buffer, format='webp', save_all=True, append_images=[image], method=6)
print(buffer.getbuffer().nbytes) # 9220
```

This pull request might be related: #1263

**Comment by radarhere** [comment]
Yes, I would conclude that #1263 is the solution to this.

**Comment by radarhere** [comment]
Minor note: At the beginning of your description, you talk about saving with 0, instead of the default. The documentation states that 0 is the default.

**Comment by radarhere** [comment]
I've created PR #4547 to resolve this.
