### ISSUE TITLE
Document 16-bit modes?

### ISSUE THREAD

**Issue by anntzer** [python-pillow/Pillow#4043]
### What did you do?

The 16-bit-per-channel modes are not documented or even mentioned under https://pillow.readthedocs.io/en/stable/handbook/concepts.html

### What did you expect to happen?

At least mention them.

### What actually happened?

Open e.g. Tests/images/16bit.MM.cropped.tif and check that the image mode is "I;16B".

### What are your OS, Python and Pillow versions?

* OS: any
* Python: any
* Pillow: 6.1.0

```
In [1]: PIL.Image.open("Tests/images/16bit.MM.cropped.tif").mode
Out[1]: 'I;16B'
```

**Comment by radarhere** [comment]
I've created PR #4047 to resolve this.
