### ISSUE TITLE
Can Pillow crop an image within a yellow frame?

### ISSUE THREAD

**Issue by Elmit2015** [python-pillow/Pillow#4049]
I am trying to find a solution and was pointed to possible use Pillow.

I make pictures with a camera and a Raspberry PI. 
The objects have to be placed within a yellow frame on a green background.
I put three sample pictures at:
https://bc.elmit.com/john/test1.jpg
https://bc.elmit.com/john/test2.jpg
https://bc.elmit.com/john/test3.jpg
The original picture size is 3280x2464 pixels
The outer coordinates of the yellow frame is about 1812x1812 (but that changes!!!)
The inner coordinates of the yellow frame is about 1350x1350 (but that changes!!!)
That gives you a frame of 240 pixels.
Different objects require different size of the yellow frame. Unfortunately the frame also moves, so it is not at each picture at the same place (maybe tilt and resized).

I want to crop the picture within the yellow frame.

My idea is to scan the picture line by line and find a yellow point, which would get larger with each line and split into two yellow lines opening the green between. When the green dot (space) appears after the long yellow line is one (or both) of the top corners. Same I do for the lower part of the picture.
That way I get four coordinates of the frame. By adjust the coordinates by looking to the other corners, I would find a rectangle within the yellow frame that would have no part of the yellow frame, only green background and the object. This rectangle I want to crop out and save.

1. can pillow do that?
2. can pillow be installed on a Raspberry 4?

**Comment by radarhere** [comment]
1. Pillow can read the value of individual image pixels, yes - https://pillow.readthedocs.io/en/stable/reference/PixelAccess.html.
2. Yes. For example, #3671 is a report from a Raspberry Pi user.

**Comment by radarhere** [comment]
Here's some code to demonstrate. I've taken the approach of presuming that the yellow frame is roughly centered, and starting with a rectangle around that, expanding each side of the rectangle until I hit yellow.

```python
from PIL import Image

def is_yellow(rgb):
	r, g, b = rgb
	yellow_r, yellow_g, yellow_b = (216, 211, 58)
	tolerance = 120
	return abs(r - yellow_r) < tolerance and abs(g - yellow_g) < tolerance and abs(b - yellow_b) < tolerance

for file in ['test1', 'test2', 'test3']:
	with Image.open(file+'.jpg') as im:
		center = im.width / 2, im.height / 2
		minimum_box_dimension = 1000
		box = [int(center[0] - minimum_box_dimension / 2),
			   int(center[1] - minimum_box_dimension / 2),
			   int(center[0] + minimum_box_dimension / 2),
			   int(center[1] + minimum_box_dimension / 2)]
		px = im.load()
		while box[0] > 0:
			box[0] -= 1
			line_is_yellow = True
			for y in range(box[1], box[3]):
				if not is_yellow(px[box[0], y]):
					line_is_yellow = False
					break
			if line_is_yellow:
				break
		while box[1] > 0:
			box[1] -= 1
			line_is_yellow = True
			for x in range(box[0], box[2]):
				if not is_yellow(px[x, box[1]]):
					line_is_yellow = False
					break
			if line_is_yellow:
				break
		while box[2] < im.width:
			box[2] += 1
			line_is_yellow = True
			for y in range(box[1], box[3]):
				if not is_yellow(px[box[2], y]):
					line_is_yellow = False
					break
			if line_is_yellow:
				break
		while box[3] < im.height:
			box[3] += 1
			line_is_yellow = True
			for x in range(box[0], box[2]):
				if not is_yellow(px[x, box[3]]):
					line_is_yellow = False
					break
			if line_is_yellow:
				break
		im.crop(box).save(file+'_out.jpg')
```

**Comment by radarhere** [comment]
@Elmit2015 did that answer your questions?

**Comment by Elmit2015** [comment]
Thank you, that works.
