### ISSUE TITLE
TIFF orientation tag handled differently from most other software when loading G4 TIFF files

### ISSUE THREAD

**Issue by ailintom** [python-pillow/Pillow#4053]
Most image software handles TIFF orientation tags  (tag 274) differently from Pillow when loading  binary G4 TIFF images. This means that only images having the orientation tag == 1 (The 0th row represents the visual top of the image, and the 0th column represents the visual left-hand side) are loaded correctly (in the same way as in other software), other images should be corrected manually. 
I am not sure whether Pillow regards the orientation tags while other software ignores or vice versa. At least  they are loaded transposed.
I use Pillow-6.1.0 with Python 3.8 on Windows.

I've developed the following procedure in my script to load TIFF files correctly (basically I only have files with orientation==8 from my office copier machine, so I have not tested other orientations). I think this something similar should be part of the TIFFImagePlugin

```python
from PIL import Image
from tkinter import filedialog, Tk
ORIENTATION = 274
root = Tk()
root.withdraw()
file_selected = filedialog.askopenfilename()
srcim = Image.open(filename)
orientation = srcim.tag[ORIENTATION][0]
format = os.path.splitext(filename)[1]
if format.lower() in [".tif", ".tiff"]:
     try:
        if orientation == 8:
            srcim = srcim.transpose(Image.ROTATE_90)
        elif orientation == 3:
            srcim = srcim.transpose(Image.ROTATE_180)
        elif orientation == 6:
            srcim = srcim.transpose(Image.ROTATE_270)
        elif orientation == 2:
            srcim = srcim.transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 4:
            srcim = srcim.transpose(Image.FLIP_TOP_BOTTOM)
        elif orientation == 5:
            srcim = srcim.transpose(Image.ROTATE_90).transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 7:
            srcim = srcim.transpose(Image.ROTATE_270).transpose(Image.FLIP_LEFT_RIGHT)
     except:
          print("Can't detect orientation")
```

**Comment by radarhere** [comment]
Hi. In Pillow 6.0, `ImageOps.exif_tranpose` was added - https://github.com/python-pillow/Pillow/blob/1e3c2c9ce1aea8536e95ce74086a79793e467618/src/PIL/ImageOps.py#L523-L530

So you should be able to simplify your code down to -

```python
from PIL import Image, ImageOps
from tkinter import filedialog, Tk
root = Tk()
root.withdraw()
file_selected = filedialog.askopenfilename()
srcim = Image.open(filename)
srcim = ImageOps.exif_transpose(src_im)
```

If you're asking why this is not applied automatically, the answer would be that `ImageOps.exif_transpose` has not always been a part of Pillow, and we value backwards compatibility highly.

**Comment by ailintom** [comment]
Hi, thanks for the reply. No, `exif_transpose` does not help. I mean TIFF tags, not the EXIF, it is a different thing. Try loading this file with PIL 
It shows upright in most graphic software, but PIL displays it rotated, because it disregards the TIFF 274 tag (orientation)
[test1.zip](https://github.com/python-pillow/Pillow/files/3587110/test1.zip)

**Comment by ailintom** [comment]
Here is the updated procedure for correcting TIFF file orientation: 

```
from PIL import Image
TIFFTAG_ORIENTATION = 274
def correct_tiff(srcim):
    try:
        orientation = srcim.tag[TIFFTAG_ORIENTATION][0]
        

        if orientation == 2:
            srcim = srcim.transpose(Image.FLIP_LEFT_RIGHT)
        elif orientation == 3:
            srcim = srcim.transpose(Image.ROTATE_180)            
        elif orientation == 4:
            srcim = srcim.transpose(Image.FLIP_TOP_BOTTOM)
        elif orientation == 5:
            srcim = srcim.transpose(Image.TRANSPOSE)
        elif orientation == 6:
            srcim = srcim.transpose(Image.ROTATE_270)            
        elif orientation == 7:
            srcim = srcim.transpose(Image.TRANSVERSE)
        elif orientation == 8:
            srcim = srcim.transpose(Image.ROTATE_90)       
    except:
        pass
    return srcim
```
and a small test script with a full set of test files (tiff G4 and uncompressed)
attached.
 
[tiff orientation test.zip](https://github.com/python-pillow/Pillow/files/3587366/tiff.orientation.test.zip)

**Comment by radarhere** [comment]
Thanks for all that. Could any of those images be be added to the test suite, under the Pillow license?

**Comment by ailintom** [comment]
Yes, both code snippets and the images are absolutely free to use under any license.

**Comment by radarhere** [comment]
Okay. I've created #4062 to add an `ImageOps.auto_transpose` method. See what you think.

**Comment by radarhere** [comment]
I've now created #4063 to transpose TIFF images on load instead.
