### ISSUE TITLE
Reading FITS images

### ISSUE THREAD

**Issue by burhankhanlodhy** [python-pillow/Pillow#4054]
Whenever I try to run PIL.FitsStubImagePlugin.register_handler()
it gives me an error saying PIL doesn't have any FitsStubImagePlugin module.
How do I open my fits file as it says I need a handler to operate .fits file

**Comment by radarhere** [comment]
You will see [in the docs that FITS is listed as an identify-only format](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#identify-only-formats) - meaning that read and write functionality is not yet supported in Pillow. If you have code for reading or writing FITS files, and would like to connect your code to Pillow, then you can register a handler -

```python
from PIL import Image
from PIL import FitsStubImagePlugin

class FitsHandler:
    def open(self, im):
        ...

    def load(self, im):
        ...
        return image

    def save(self, im, fp, filename):
        ...

fits_handler = FitsHandler()
FitsImagePlugin.register_handler(fits_handler)

im = Image.open("sample.fits")
```

**Comment by radarhere** [comment]
I've created #5405 to help in a small way, reading the image headers to determine the mode and size of the image.

**Comment by radarhere** [comment]
I've created PR #6056 to resolve this. If that is merged, you should no longer have to worry about `register_handler()`, but can instead just `Image.open("sample.fits")`.
