### ISSUE TITLE
Why is the following memory allocation not checked?

### ISSUE THREAD

**Issue by Elaphurus** [python-pillow/Pillow#4055]
As far as I know, memory allocations can fail for some reasons, so the return value should be checked after calling these  functions (like malloc).

But why is the following ```block.ptr``` not checked? [here](https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Storage.c#L344)

```c
// libImaging/Storage.c#L344

if (arena->blocks_cached > 0) {
// ...
} else {
    if (dirty) {
        block.ptr = malloc(requested_size);
    } else {
        block.ptr = calloc(1, requested_size);
    }
    arena->stats_allocated_blocks += 1;
}
block.size = requested_size;
return block;
```

If there are some circumstances where the check is not necessary, please tell me, that will be great help.

**Comment by radarhere** [comment]
I think the answer to your question is - it is actually checked, just after the function ends, rather than within it. The function that the code is in is `memory_get_block`, and here is the only time that `memory_get_block` is called - 

https://github.com/python-pillow/Pillow/blob/cce7a76f79e491040792963c32e463d9d399fe3e/src/libImaging/Storage.c#L425-L429

**Comment by Elaphurus** [comment]
Thank you for explaining this. But it's still a little strange - if it is not checked within ```memory_get_block```, then each time (maybe another one in the future?) it's called, an extra check that is almost the same is needed. Why not just do it within?

**Comment by Elaphurus** [comment]
Ok, sounds reasonable for me. As for 

> checking if a value is null vs checking if a value inside a struct is null

maybe the former is better (?), as it provides consistency with normal behavior.

Thank you again, this discussion is helpful for me.
