### ISSUE TITLE
PyEncoder doesn't exist

### ISSUE THREAD

**Issue by sheatsm** [python-pillow/Pillow#4059]
### What did you do?

Attempted to implement a Python based encoder for an image plugin.

### What did you expect to happen?

From the documentation of 'register_encoder', I expected ImageFile.PyEncoder to exist.

```python
def register_encoder(name, encoder):
    """
    Registers an image encoder.  This function should not be
    used in application code.

    :param name: The name of the encoder
    :param encoder: A callable(mode, args) that returns an
                    ImageFile.PyEncoder object

    .. versionadded:: 4.1.0
    """
    ENCODERS[name] = encoder
```

### What actually happened?

It does not exist in any namespace that I can find.  Is this an oversight or is there a new way to implement Python based encoders suitable for addition to register_encoder?

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.3
* Pillow: 6.0.0

```python

class MyEncoder(ImageFile.PyEncoder):
    pass
```

**Comment by drewcassidy** [comment]
Im interested in this as well, since I'd like to write a DXT compression plugin but don't know where to begin with writing the encoder

**Comment by Piolie** [comment]
@drewcassidy I managed to get an encoder working by manually implementing the encoder class. The required public methods are `__init__`, (`@property`) `pushes_fd`, `setimage`, `setfd`, `encode_to_pyfd` and `cleanup`. Though a bit of a kludge, it was easier than I expected.

You can check [my work](https://github.com/Piolie/DjvuRleImagePlugin/blob/master/DjvuRleImagePlugin.py) and hopefully adapt it to your image format. Good luck.

**Comment by radarhere** [comment]
I've created PR #6069 to add PyEncoder.
