### ISSUE TITLE
How can Pillow draw superscript text?

### ISSUE THREAD

**Issue by lx1054331851** [python-pillow/Pillow#4069]
Can Pillow draw superscript text like below:

![image](https://user-images.githubusercontent.com/12423206/64954061-11c13400-d8b7-11e9-8a0a-daba96a6be0b.png)

**Comment by radarhere** [comment]
There is no built-in functionality for this, but there's also no reason why you couldn't just draw two text items to achieve the effect.

```python
from PIL import Image, ImageDraw, ImageFont
im = Image.new("RGB", (180, 100), "#fff")
font = ImageFont.truetype("/Library/Fonts/Arial.ttf", 60)
d = ImageDraw.Draw(im)
x, y = 20, 20
d.text((x, y), "US", font=font, fill="#000")
w = d.textsize("US", font=font)[0]
x += w
y += font.getoffset("US")[1]

font = ImageFont.truetype("/Library/Fonts/Arial.ttf", 40)
h2 = d.textsize("TM", font=font)[1]
y -= h2 / 2

d.text((x, y), "TM", font=font, fill="#000")

im.save("out.png")
```

![out](https://user-images.githubusercontent.com/3112309/64955260-1db6f100-d8cb-11e9-92c9-9ac0ac441879.png)

**Comment by lx1054331851** [comment]
@hugovk  Thank you for your reply.
I get it that there is no built-in function to do that. 
Because I need to draw a text area on the image, and I'am not sure which word has a superscript mark, so it may very difficult for me to calculate the location of the superscript.
This issue can be closed.

**Comment by Tomaubier** [comment]
For reference, using unicode codes for super/subscript characters works: https://en.wikipedia.org/wiki/Unicode_subscripts_and_superscripts
