### ISSUE TITLE
Unicode devanagari fonts rendered incorrectly

### ISSUE THREAD

**Issue by pranphy** [python-pillow/Pillow#4070]
Devanagari fonts are not rendered correctly. 
```python
from PIL import Image
from PIL import ImageFont, ImageDraw, ImageOps
import matplotlib.pyplot as plt

im=Image.new('L',(500,200))
font = ImageFont.truetype('Laila-Regular.ttf', 85)
                # transpose font optionally
transposed_font = ImageFont.TransposedFont(font)

f = ImageFont.load_default()
txt=Image.new('L', (500,200))
d = ImageDraw.Draw(txt)
d.text( (0, 0), u"राष्ट्रिय दृश्य",  font=font, fill=255)
w=txt.rotate(0,  expand=50)
im.paste( ImageOps.colorize(w, (0,0,0), (255,255,84)), (0,60),  w)
plt.imshow(im)
```
![image](https://user-images.githubusercontent.com/10902216/65010985-c7a07880-d8df-11e9-8fa1-f863d9eadd6c.png)
Which should have been rendered as 
![image](https://user-images.githubusercontent.com/10902216/65011063-177f3f80-d8e0-11e9-8626-e7c54e03d9eb.png)
The second image is a screenshot of word processer displaying same two words in the same font.

**Comment by radarhere** [comment]
Is this covered by issues #3191 and #2255?

**Comment by pranphy** [comment]
Yes its the same issue as #3191.  There doesn't seem to be a solution in that issue as well.

**Comment by radarhere** [comment]
Closing as a duplicate.

**Comment by radarhere** [comment]
Running the following code with Pillow 10.0.0 with RAQM enabled
```python
from PIL import Image
from PIL import ImageFont, ImageDraw, ImageOps

im=Image.new('L',(500,200))
font = ImageFont.truetype('Laila-Regular.ttf', 85)

f = ImageFont.load_default()
txt=Image.new('L', (500,200))
d = ImageDraw.Draw(txt)
d.text( (0, 0), u"राष्ट्रिय दृश्य",  font=font, fill=255)
w=txt.rotate(0,  expand=50)
im.paste( ImageOps.colorize(w, (0,0,0), (255,255,84)), (0,60),  w)
im.save("out.png")
```

I get

![out](https://github.com/python-pillow/Pillow/assets/3112309/d28bc023-8d6d-4f9d-a04c-1eee1bb02150)

So this looks like it has been resolved.
