### ISSUE TITLE
Do we have any mechanism to check crop image available in real image (or in Screenshot) using PIL

### ISSUE THREAD

**Issue by Nagesh1504** [python-pillow/Pillow#4072]
I am automating one of the test-case defined for Automation Suite. In this, I took screenshot of one of the infotainment head up display page and Save it (Screenshot take by Uiautomator library), using PIL, i opened this screenshot and cropped one of the UI object (For example: Chrome UI object) and saved it. 
Now My question is that, How to check crop image (i.e UI object) is available on the real image or screenshot image.

@jezdez could please help me on this one

**Comment by radarhere** [comment]
To clarify - are you saying that you would like to check if the cropped image is contained with another image - if a small image is part of a larger image?

**Comment by Nagesh1504** [comment]
@radarhere  Hello,

Yes exactly! do have any method in PIL?

**Comment by hugovk** [comment]
Do any of these help? 

* https://stackoverflow.com/a/38474539/724176
* https://stackoverflow.com/q/17566752/724176

**Comment by Nagesh1504** [comment]
@hugovk  Hello,

Thank you, those links were help me lot and i have modified above code as per automation purpose.
Thank you once again :)

One question need to ask from the above code, Can we reduce the time for process taking to find crop image contained with another image. 

what exactly i am asking that do we have any method so that reduce process time on taking comparison?

**Comment by hugovk** [comment]
There's no method built in to Pillow, so you'll need to something like those methods. It sounds like an intensive operation, so likely to be slow. 

An possibly faster alternative is to use something like Numpy or OpenCV, for example https://stackoverflow.com/q/7670112/724176.

**Comment by radarhere** [comment]
Depending on your situation, you might also be interested in Python multiprocessing - https://docs.python.org/2/library/multiprocessing.html

@Nagesh1504 do you have any further questions? If you would like more help with speeding up the code, it would be good to have a self-contained code example with images, so that we can try and optimise something specific.

**Comment by Nagesh1504** [comment]
Thanks @radarhere  and @hugovk  for helping me out from these question.
As of now i am happy with script which you were suggested. 

Thanks a lot once again :)
