### ISSUE TITLE
Auto bit rate adjustment? (16-bpc)

### ISSUE THREAD

**Issue by ccppoo** [python-pillow/Pillow#4073]
### What did you do?
Where I joined in a project using PIL, I checked PIL doesn't support 16-bit depth images as I saw issues and searched in PIL documentation ([link](https://pillow.readthedocs.io/en/stable/search.html?q=16-bit+per&check_keywords=yes&area=default#).

The issue, that project had, is user tried to open 16-bit depth image so that caused an "error".

Although I knew PIL didn't support over 8 bpc, I tested opening 16 bpc (48 bits for a pixel) using sample 16 bpc images from [here1](https://www.fnordware.com/superpng/pnggrad16rgb.png), [here2 ](https://www.fnordware.com/superpng/pnggradHDrgba.png)

but there were no exceptions

by this test code
```python
from PIL import Image

if __name__ == '__main__':
    a =Image.open('./16rgb.png')
    print('a :', a)
    print('a size : ', a.size)
    print('a.getcolors :', a.getcolors(256))
    print('a.format :',a.format)
    print('a.mode :', a.mode)
    print('a.getextrema :',a.getextrema())
    print('-------------')
    a = Image.open('./pnggradHDrgba.png')
    print('a :', a)
    print('a size : ', a.size)
    print('a.getcolors :', a.getcolors(256))
    print('a.format :',a.format)
    print('a.mode :', a.mode)
    print('a.getextrema :',a.getextrema())
    print('-------------')
```
I got this
```txt
a : <PIL.PngImagePlugin.PngImageFile image mode=RGB size=600x600 at 0x1D0F96CEDA0>
a size :  (600, 600)
a.getcolors : None
a.format : PNG
a.mode : RGB
a.getextrema : ((0, 255), (0, 255), (0, 255))
-------------
a : <PIL.PngImagePlugin.PngImageFile image mode=RGBA size=1920x1080 at 0x1D0F96CE668>
a size :  (1920, 1080)
a.getcolors : None
a.format : PNG
a.mode : RGBA
a.getextrema : ((0, 255), (0, 255), (0, 255), (0, 255))
```
image info(what I downloaded)
First image  [here1](https://www.fnordware.com/superpng/pnggrad16rgb.png),:
![image](https://user-images.githubusercontent.com/46418312/65368545-80b6d800-dc7d-11e9-98b7-4989a13e7348.png)

Second image  [here2 ](https://www.fnordware.com/superpng/pnggradHDrgba.png)
:
![image](https://user-images.githubusercontent.com/46418312/65368549-90ceb780-dc7d-11e9-9197-50015b3add14.png)

### What did you expect to happen?

I expected a io error but didn't happend

### What actually happened?

a.getextrema() show as 8 bpc (0,255)
so it means PIL.Image read that image as 8 bpc (24-bit per pixel)
why did this happen?
did I miss something from the documentation?

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.3
* Pillow:  6.1.0
![image](https://user-images.githubusercontent.com/46418312/65368526-4f3e0c80-dc7d-11e9-982b-67ffd07aad06.png)

**Comment by radarhere** [comment]
As a general answer, Pillow does provide limited support for some 16-bit modes - https://pillow.readthedocs.io/en/latest/handbook/concepts.html?highlight=16-bit#modes

As a specific answer, the images that you linked to are -

https://github.com/python-pillow/Pillow/blob/b7ad0d8852f1830a9bf20a6823b7fd09a2eb2484/src/PIL/PngImagePlugin.py#L65

and

https://github.com/python-pillow/Pillow/blob/b7ad0d8852f1830a9bf20a6823b7fd09a2eb2484/src/PIL/PngImagePlugin.py#L76

These have been there since the PIL fork. They are converting the images from the raw mode RGB;16B and RGBA;16B to RGB and RGBA respectively. That would be why you are seeing the pixels as having only 8-bit values.

**Comment by ccppoo** [comment]
Thanks, I got confused with some PIL issues which were asking some formats and 16bps aren't readable for PIL
Can you add some examples or show how PIL works on special mode?
at https://pillow.readthedocs.io/en/latest/handbook/concepts.html?highlight=16-bit#modes

**Comment by radarhere** [comment]
The special modes can be used just like the normal modes - they simply have limited support, meaning that if some types of operations create errors, it should not come as a surprise.

**Comment by radarhere** [comment]
Did that answer your question?

**Comment by ccppoo** [comment]
@radarhere
Yes thanks, forgot to click the comment button
