### ISSUE TITLE
Problem with TIFFs in Pillow 3.4.2 on Python 2.7

### ISSUE THREAD

**Issue by Themanwithoutaplan** [python-pillow/Pillow#4075]
### What did you do?

Got an error from my CI setup that PIL can't read a TIFF. Happening on both MacOS and the Docker image but seems to be limited to Python 2.7. TIFF support is installed and the test has been around since February. The failing test is blocking my final release for Python 2.7. Tested again the wheel and locally built.
[plain.tif.zip](https://github.com/python-pillow/Pillow/files/3638652/plain.tif.zip)

See https://bitbucket.org/openpyxl/openpyxl/src/541b5c125bf127a63f9f331f91dc21d8f7bff264/openpyxl/drawing/tests/test_image.py#lines-56

### What did you expect to happen?

PIL to open the file and convert it to PNG

### What actually happened?

It raises an error that it can't read the file

### What are your OS, Python and Pillow versions?

* OS: MacOS 10.14.6
* Python: 2.7.16
* Pillow: 3.4.2

```python
>>> from PIL import Image
>>> img = Image.open("plain.tif")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/charlieclark/temp/pp/lib/python2.7/site-packages/PIL/Image.py", line 2319, in open
    % (filename if filename else fp))
IOError: cannot identify image file 'plain.tif'
```

**Comment by hugovk** [comment]
Please upgrade Pillow.

Pillow 3.4.2 is very old (released Oct 18, 2016) and I cannot reproduce with latest Pillow, with both Python 2.7.16 and 3.7.4 on the same macOS version.

```console
⌂101% [hugo:/private/tmp/Downloads] % p
Python 3.7.4 (default, Jul  9 2019, 18:13:23)
[Clang 10.0.1 (clang-1001.0.46.4)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> img = Image.open("plain.tif")
>>> img.show()
>>>
⌂94% [hugo:/private/tmp/Downloads] 11s % p2
Python 2.7.16 (default, Mar  4 2019, 09:02:22)
[GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> img = Image.open("plain.tif")
>>> img.show()
>>>
```

**Comment by Themanwithoutaplan** [comment]
Yeah, I got a bit confused. IIRC for a while Python 2.7 was limited to < 4.

Just checking the pipeline and I think I was looking at the wrong thing. Got some other random 2.7 issue to fix: https://bitbucket.org/openpyxl/openpyxl/addon/pipelines/home#!/results/787

Thanks for the quick reply and sorry for the noise!

**Comment by hugovk** [comment]
No problem! Python 2.7 is still supported, but will be dropped in Pillow 7.0.0 on 2020-01-01 when 2.7 reaches EOL. So the next release, Pillow 6.2.0 will be the last to support 2.7.

**Comment by Themanwithoutaplan** [comment]
Same for me with openpyxl.
