### ISSUE TITLE
ValueError: box offset can't be negative

### ISSUE THREAD

**Issue by icemac** [python-pillow/Pillow#4087]
### What did you do?
I wanted to transform a PNG file using `PIL.ImageOps.fit()`.

### What did you expect to happen?
I expected to get back the transformed image.

### What actually happened?
```
Traceback (most recent call last):
  File "example.py", line 6, in <module>
    PIL.ImageOps.fit(img, (600, 453), PIL.Image.ANTIALIAS)
  File ".../lib/python3.7/site-packages/PIL/ImageOps.py", line 445, in fit
    return image.resize(size, method, box=crop)
  File ".../lib/python3.7/site-packages/PIL/Image.py", line 1892, in resize
    return self._new(self.im.resize(size, resample, box))
ValueError: box offset can't be negative
```

This exception seems to be dependent on the size of the image `(1000, 755)` and the target size `(600, 453)`. In this case the value for `box` gets `(-5.684341886080802e-14, 0.0, 1000.0, 755.0)` which leads to the exception. (The attached PNG is not the original one where the problem happened in production but an arbitrarily constructed one having the same dimensions.)

### What are your OS, Python and Pillow versions?

* OS: MacOS
* Python: 2.7 and 3.7
* Pillow: 6.1.0

```python
import PIL.Image
import PIL.ImageOps

with open('example.png', 'rb') as reader:
    img = PIL.Image.open(reader)
    PIL.ImageOps.fit(img, (600, 453), PIL.Image.ANTIALIAS)
```

![example](https://user-images.githubusercontent.com/386619/65522942-d2fd3080-deeb-11e9-9544-fadf5ec7422c.png)

**Comment by radarhere** [comment]
I can reproduce the error simply with
```python
from PIL import Image, ImageOps
img = Image.new("RGB", (1000, 755))
ImageOps.fit(img, (1000, 755))
```

The ratio for this image is 1000.0 / 755 = 1.3245033112582782. Pillow currently treats the case where the ratios are equal the same as the case where the width needs to be cropped - https://github.com/python-pillow/Pillow/blob/0118a8fdb05b144f79ef48e5760dd7054f842811/src/PIL/ImageOps.py#L429

So calculating the width from the ratio gives 1.3245033112582782 * 755 = 1000.0000000000001. Pillow then tries to center this greater width, causing a negative x offset when cropping, leading to the error.

I've created PR #4088 to resolve this.

**Comment by icemac** [comment]
Thank you very much!
