### ISSUE TITLE
How to output a binary byte stream of a GIF picture

### ISSUE THREAD

**Issue by LIMr1209** [python-pillow/Pillow#4092]

**Comment by nulano** [comment]
Are you trying to save an image as GIF to a bytes object?

From https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.tobytes:
> [...] For compressed image data (e.g. PNG, JPEG) use save(), with a BytesIO parameter for in-memory data.

So this should work:
```
from io import BytesIO
from PIL import Image

im = Image.new("RGB", (50, 50))
data = BytesIO()
im.save(data, "gif")
data.seek(0)

# e.g. save to file
import shutil
with open("image.gif", "wb") as f:
    shutil.copyfileobj(data, f)
```

**Comment by LIMr1209** [comment]
@nulano thanks  It can be used.
