### ISSUE TITLE
Spider format header bug for random image size

### ISSUE THREAD

**Issue by arpit15** [python-pillow/Pillow#4093]
### What did you do?
I am trying to save `float` image in `SPIDER` format

### What did you expect to happen?
I accepted it to work for any image size.

### What actually happened?
The saved spider file has corrupt header when the width of the image is not a power of 2. 

### What are your OS, Python and Pillow versions?

* OS: Windows 10 
* Python: 3.6
* Pillow: 6.1.1

```python
from PIL import Image
import numpy as np

filename= "im.spi"
width = 100  # change it to any natural number not a power of 2
im = np.random.random((64, width))-1
pil_image = Image.fromarray(im, 'F')
pil_image.save(filename, format='SPIDER')

im2 = Image.open(filename)
print(im2.size)
```

I was able to trace the bug to [this](https://github.com/python-pillow/Pillow/blob/master/src/PIL/SpiderImagePlugin.py#L239) line.
Changing the line from `labrec = 1024 / lenbyt` to `labrec = int(1024 / lenbyt)` fixes the bug for me.

**Comment by nulano** [comment]
I've created PR #4094 to resolve this.

**Comment by arpit15** [comment]
Thanks @nulano. I will keep the issue open until the PR goes in.
