### ISSUE TITLE
save_all documentation fails to specify supported file types

### ISSUE THREAD

**Issue by kimasenbeck** [python-pillow/Pillow#4095]
Pillow's [save_all documentation](https://pillow.readthedocs.io/en/5.1.x/handbook/image-file-formats.html#saving) indicates that "If present and true, all frames of the image will be saved. If not, then only the first frame of a multiframe image will be saved."
However, the [release notes](https://pillow.readthedocs.io/en/3.1.x/releasenotes/3.0.0.html) for the same specify that this flag only applies to pdfs and gifs. 
Please specify supported file types to avoid misuse on multi-frame files of other types (e.g. multiframe jpeg, jpg, or png)

**Comment by nulano** [comment]
Running grep on PIL suggests `save_all` is supported for WebP, PDF, GIF, and TIFF.

**Comment by radarhere** [comment]
The first link that you provided is to the 'Saving' part of the 'GIF' format. It is not meant to be discussing saving regardless of format.

Elsewhere on that same page, it mentions 'save_all' for WebP, PDF and TIFF.

**Comment by radarhere** [comment]
After the release notes for 3.0.0, TIFF save_all support was added in 3.4.0, and WebP save_all support was added in 5.0.0.

I've created PR #4117 to clarify the documentation.
