### ISSUE TITLE
Return the number of bytes written from Image.save()

### ISSUE THREAD

**Issue by 0x2b3bfa0** [python-pillow/Pillow#4098]
### What did you do?
```python
from PIL import Image
result = Image.open("/path/input.png").save("/path/output.png")
```

### What did you expect to happen?
The `Image.save()` method should return the number of bytes written to the output stream or file. As long as this behavior doesn't conflict with the Pillow conventions, would be a very handy feature in certain cases where one needs to write various images into a binary blob.

### What actually happened?
```python
assert result == None
```

### What are your Operating System, Python and Pillow versions?
* Operating System: macOS 10.14
* Python: 3.7.3
* Pillow: 5.2.0

**Comment by radarhere** [comment]
Is this something that you've seen implemented by other libraries?

I'm also not sure what should happen in the case of using `append` to append to an existing PDF - https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#pdf

**Comment by 0x2b3bfa0** [comment]
I've never seen that function in another library, but the desired behavior seems to be consistent with [`io.RawIOBase.write(b)`](https://docs.python.org/3/library/io.html#io.RawIOBase.write) and, therefore, for all the file-like objects.

The problem arises, as you suggest, when the specific `_save` method uses `seek` or opens the file for appending. In fact, the documentation of [`Image.save`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) clearly states that the file object must implement the `seek`, `tell`, and `write` methods.

Pillow could use an `io` buffer for the entire file and then write it at once, but this method would probably add a huge overhead in order to achieve only a small improvement. The only obvious advantage would be the ability to work seamlessly with streams and user-defined file writing methods.

**Comment by wiredfool** [comment]
This is unlikely to be feasible, as there are several places where Pillow hands off a raw file descriptor to external libraries.

**Comment by 0x2b3bfa0** [comment]
I see; the only sane way would probably be  to use a temporary file, and that feels very unpythonic. Doing it otherwise would require a major rewrite of Pillow, and my request doesn't deserve such amount of work for a dubious improvement.

**Comment by 0x2b3bfa0** [comment]
I've implemented a simple workaround that proved to be effective for my use case:

```python
from io import BytesIO
from PIL import Image

def save(input: Image, output: BytesIO, *arguments, **keyword_arguments) -> int:
    buffer = BytesIO()  # Create a buffer to emulate a file-like object.
    input.save(buffer, *arguments, **keyword_arguments)
    buffer.seek(0)  # Rewind the buffer.
    return output.write(buffer.read())

input = Image.open("/path/to/input.png")
with open("/path/to/output.bmp", "wb") as output:
    size = save(input, output, 'BMP')
    print("Size:", size)
```

I don't know to what extent this method can be used with other output file formats, but at least it's elegant enough to use in production-grade code.
