### ISSUE TITLE
MPO seek error

### ISSUE THREAD

**Issue by danielsiwiec** [python-pillow/Pillow#4099]
### What did you do?
I perform an `Image.seek` operation.

### What did you expect to happen?
I expect a successful function invocation.

### What actually happened?
I get an error:

```
~/.local/share/virtualenvs/muffinchihuahua-VbII3yUl/lib/python3.7/site-packages/PIL/MpoImagePlugin.py in seek(self, frame)
     89         if "parsed_exif" in self.info:
     90             del self.info["parsed_exif"]
---> 91         if i16(self.fp.read(2)) == 0xFFE1:  # APP1
     92             n = i16(self.fp.read(2)) - 2
     93             self.info["exif"] = ImageFile._safe_read(self.fp, n)

~/.local/share/virtualenvs/muffinchihuahua-VbII3yUl/lib/python3.7/site-packages/PIL/_binary.py in i16be(c, o)
     75
     76 def i16be(c, o=0):
---> 77     return unpack_from(">H", c, o)[0]
     78
     79

error: unpack_from requires a buffer of at least 2 bytes
```

### What are your OS, Python and Pillow versions?

* OS: macOs Mojave 10.14.6
* Python: 3.7
* Pillow: 6.1.0

```python
import urllib.request
from PIL import Image

urllib.request.urlretrieve('https://srv-file7.gofile.io/download/X30JBL/137.DSC_0733-3-blueberry-muffins-.jpg', 'muffin.jpg')

im=Image.open('muffin.jpg')
im.seek(0)
im.seek(1)
```

**Comment by radarhere** [comment]
If I navigate to https://srv-file7.gofile.io/download/X30JBL/137.DSC_0733-3-blueberry-muffins-.jpg in my browser, I get 'You are not authorized to download this file.'

**Comment by danielsiwiec** [comment]
Hmm that's bizarre @radarhere. My browser (Chrome) just downloads the file. Same for Python if I run the above.

**Comment by radarhere** [comment]
Could you just attach the file in a GitHub comment?

**Comment by danielsiwiec** [comment]
Yup, right here @radarhere 

![muffin](https://user-images.githubusercontent.com/1505227/65825093-81281380-e227-11e9-8d6a-0ee326d766db.jpg)

**Comment by danielsiwiec** [comment]
The updated snippet using the above GitHub attachment:

```python
import urllib.request
from PIL import Image

urllib.request.urlretrieve('https://user-images.githubusercontent.com/1505227/65825093-81281380-e227-11e9-8d6a-0ee326d766db.jpg', 'muffin.jpg')

im=Image.open('muffin.jpg')
im.seek(0)
im.seek(1)

```

**Comment by radarhere** [comment]
Investigating, the offsets for the three images within the file are 0, 7353813 and 7386069. However, the file only has a size of 125510.

So my simple theory is that this image is simply truncated - it should be at least 7mb, but it's only 123kb. We could add a clearer error message, but I'm not seeing a way to get the image data.

Feel free to prove me wrong by demonstrating a way to extract the image using another program, ideally exiftool.

**Comment by radarhere** [comment]
I've created PR #4240 to clarify the error occurring.
