### ISSUE TITLE
Support Python 3.8

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#4110]
The Python 3.8.0 release candidate 1 came out yesterday, with the final release scheduled for **2019-10-14**.

* https://discuss.python.org/t/python-3-8-0rc1-is-now-available/2421

Our next scheduled release is **2020-01-01**.

Do we want to do anything to support 3.8 before that? Or wait until 2020-01-01?

We normally do have people asking for a new Pillow release quite soon after a new Python release is out (and often before, eg. https://github.com/python-pillow/Pillow/issues/3763).

We're already testing 3.8 dev versions on Travis CI, so we do have some confidence things work. As noted in https://github.com/python-pillow/Pillow/issues/3763, there are already Windows wheels available for 3.8. 

TODO for 3.8:

* Test on 3.8.0 final
* Add 3.8 to CIs (when available)
* Add the 3.8 Trove classifier to `setup.py` 
* Bump to `(3, 9)`: https://github.com/python-pillow/Pillow/blob/94a64ea09c8e21f7f2e19daac0eab00a0c5bf6e8/setup.py#L27-L33

**Comment by hugovk** [comment]
Yep, or when all the pieces are in place.

**Comment by tacaswell** [comment]
We are trying to run Matplotlib CI with the pre-releases of Python (see https://github.com/matplotlib/matplotlib/pull/15418) and are currently stuck on getting Pillow to compile (Matplotlib master branch now has a hard-dep on pillow as we removed our home-grown png writer).

Any pointers on how to make this work?

**Comment by hugovk** [comment]
There are unofficial builds for Windows at https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow. Download the one you need and then you should be able to pip install it, for example:

```
pip install Pillow‑6.2.0‑cp38‑cp38‑win_amd64.whl
```

**Comment by tacaswell** [comment]
I'm not sure how to do that CI though (as reverse engineering Christoph's js obfuscation seems rude).

**Comment by hugovk** [comment]
We have a [pillow-depends](https://github.com/python-pillow/pillow-depends) repo especially for [CI dependencies](https://github.com/python-pillow/Pillow/search?q=pillow-depends&unscoped_q=pillow-depends), how about doing something like that?

**Comment by radarhere** [comment]
Just as an fyi, Python 3.8 has now been released.

**Comment by hugovk** [comment]
PR to add support for 3.8 into master: https://github.com/python-pillow/Pillow/pull/4141. Will make one into the 6.1.x branch after that's merged.

What else is needed? Do we need to wait for anything from multibuild before updating https://github.com/python-pillow/pillow-wheels?

**Comment by radarhere** [comment]
Yes, we will need https://github.com/matthew-brett/multibuild/pull/265

**Comment by radarhere** [comment]
I've created PR https://github.com/python-pillow/pillow-wheels/pull/127 to add Python 3.8 to pillow-wheels.

**Comment by hugovk** [comment]
I think we're good to do the release. Shall I do this one? I can start the prep today, although may have to finish it tomorrow.

Release issue:

* https://github.com/python-pillow/Pillow/issues/4152

**Comment by radarhere** [comment]
6.2.1 has now been released with support for Python 3.8.
