### ISSUE TITLE
Freeing pointers

### ISSUE THREAD

**Issue by Elaphurus** [python-pillow/Pillow#4115]
There seems to be a memory leak issue in [Pillow/src/libImaging/Resample.c#L622](https://github.com/python-pillow/Pillow/blob/master/src/libImaging/Resample.c#L622)

```C
ksize_horiz = precompute_coeffs(imIn->xsize, box[0], box[2], xsize,
                                    filterp, &bounds_horiz, &kk_horiz);
if ( ! ksize_horiz) {
    return NULL;
}

ksize_vert = precompute_coeffs(imIn->ysize, box[1], box[3], ysize,
                                filterp, &bounds_vert, &kk_vert);
if ( ! ksize_vert) {
    free(bounds_horiz);
    free(kk_horiz);
    free(bounds_vert);
    free(kk_vert);
    return NULL;
}
```

There should be ```free``` statements before the first ```return```.

**Comment by radarhere** [comment]
Thanks for this. I agree that you have found an inconsistency. However, the problem is not that all of those variables should be freed in the first return - it's that some of them should not be freed in the second return.

I've created PR #4116 to resolve this.

**Comment by Elaphurus** [comment]
Thank you for pointing this out. When I opened this issue, although I'm sure something is wrong, the code was still confusing. Now I understand what happens within, when entering the second conditional, it means ```*_horiz``` have been allocated, while ```*_vert``` have not and they should not be freed. So it's not memory leak here, it's dereferencing dangling pointer. Thank you again.
