### ISSUE TITLE
Specific image can be opened by browser, but not by Pillow 6.2

### ISSUE THREAD

**Issue by beipang2** [python-pillow/Pillow#4146]
### What did you do?
Tried to open a .jpg image with PIL

### What did you expect to happen?
The photo can be opened in a browser and on Preview in Mac

### What actually happened?
```python
from PIL import Image
Image.open("/Users/dir/Desktop/3-full.jpg")
```
```Traceback (most recent call last):
  File "pillow_test.py", line 2, in <module>
    Image.open("/User/dir/Desktop/3-full.jpg")
  File "/User/dir/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PIL/Image.py", line 2804, in open
    im = _open_core(fp, filename, prefix)
  File "/User/dir/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PIL/Image.py", line 2790, in _open_core
    im = factory(fp, filename)
  File "/User/dir/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 789, in jpeg_factory
    im = JpegImageFile(fp, filename)
  File "/User/dir/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PIL/ImageFile.py", line 106, in __init__
    self._open()
  File "/User/dir/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 376, in _open
    handler(self, i)
  File "/User/dir/.pyenv/versions/3.6.6/lib/python3.6/site-packages/PIL/JpegImagePlugin.py", line 165, in APP
    dpi = float(x_resolution[0]) / x_resolution[1]
ValueError: could not convert string to float: '\x00'
```

### What are your OS, Python and Pillow versions?
* OS: mac OS
* Python: 3.6.9
* Pillow: 6.2

For this particular image, I found out that the `x_resolution` is a byte string instead of an actual number. Therefore, we get the above error "ValueError: could not convert string to float: '\x00'"

```
(Pdb) x_resolution
'\x00\x04\x95\x0c\x00\x00\x00\x01'
```

https://github.com/python-pillow/Pillow/pull/2632 mentioned that getting dpi shouldn't be broken if the exif is invalid. Therefore, I propose the change of adding `ValueError` to the block:
```python
except (KeyError, SyntaxError, ZeroDivisionError):
            # SyntaxError for invalid/unreadable EXIF
            # KeyError for dpi not included
            # ZeroDivisionError for invalid dpi rational value
            self.info["dpi"] = 72, 72
```

**Comment by beipang2** [comment]
After examing the file info, I think the XRespolution value is presented. Just Pillow somehow failed to read the value correctly.
```
         <tiff:XResolution>72/1</tiff:XResolution>
         <tiff:YResolution>72/1</tiff:YResolution>
         <tiff:ResolutionUnit>3</tiff:ResolutionUnit>
```

**Comment by radarhere** [comment]
Could you attach the image, so that we can also reproduce the problem?

**Comment by beipang2** [comment]
@radarhere 
I make this test image. And the PR is attached.
![invalid-exif-without-x-resolution](https://user-images.githubusercontent.com/11450884/67031233-eef88a00-f0c5-11e9-95c5-a5f35f8899c5.jpg)
