### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL' 

### ISSUE THREAD

**Issue by kylefoley76** [python-pillow/Pillow#4149]
My question is very similar to
https://stackoverflow.com/questions/26505958/why-cant-python-import-image-from-pil/31728305
but a lot has changed in 5 years.  I'm using `python 3.7.3` and I'm also using `pyenv`.  I would eventually like to use the interpreter `pypy` but I have to fix this problem first.  I had `pillow` and `PIL` working back when I was not using `pyenv` and I was using `3.6` but not any more.  Essentially when I run Python using Pycharm

```python
from PIL import Image
```

I get:

```
Traceback (most recent call last):
  File "/Users/kylefoley/.pyenv/versions/3.7.3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3267, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "<ipython-input-5-4dba96fe377b>", line 1, in <module>
    from PIL import ImageColor
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/kylefoley/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PIL/ImageColor.py", line 20, in <module>
    from . import Image
  File "/Applications/PyCharm CE.app/Contents/helpers/pydev/_pydev_bundle/pydev_import_hook.py", line 21, in do_import
    module = self._system_import(name, *args, **kwargs)
  File "/Users/kylefoley/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/Users/kylefoley/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PIL/__init__.py)
```

When I run Python from Terminal I get
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/kylefoley/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PIL/Image.py", line 56, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/Users/kylefoley/.pyenv/versions/3.7.3/lib/python3.7/site-packages/PIL/__init__.py)
```

If you look at the `Image.py` module at line 56 it says:

```python
        # should match _PyUnicodeUCS4_FromString and
        # _PyUnicodeUCS4_AsLatin1String
        warnings.warn(
            "The _imaging extension was built for Python with UCS4 support; "
            "recompile Pillow or build Python --with-wide-unicode. ",
            RuntimeWarning
            )
    # Fail here anyway. Don't let people run with a mostly broken Pillow.
    # see docs/porting.rst
```

I don't know what to do.  Also I tried the solutions recommended here
https://stackoverflow.com/questions/26505958/why-cant-python-import-image-from-pil/31728305

They were from 5 years ago, many of them geared toward Linux and did not work.

**Comment by radarhere** [comment]
How are you installing Pillow? What version of Pillow are you using?

**Comment by kylefoley76** [comment]
I was using Pyenv.  I tried both `pip install` and `brew install`, both didn't work.  Some guy at my computer club recommended I use `miniconda3`.  He did it so fast that I don't how it worked but it did.  When I type `help(PIL)` it says

DATA
    PILLOW_VERSION = '4.3.0'
    VERSION = '1.1.7'

VERSION
    4.3.0

**Comment by radarhere** [comment]
Are you saying that your problem is now resolved? Or no, you're still looking for advice on another installation method?

**Comment by hugovk** [comment]
Looks like this is solved:

> I eventually solved this by using `miniconda3` installer.  Someone else showed me how to install `miniconda3` so unfortunately I cannot be of more help than this since he did it so fast that I've forgotten how he did it.

https://stackoverflow.com/a/58481026/724176
