### ISSUE TITLE
"ImportError: DLL load failed: The specified module could not be found" on new env in fresh conda installation

### ISSUE THREAD

**Issue by JoerivanEngelen** [python-pillow/Pillow#4155]
### What did you do?
In short:
After having the same error on an older miniconda installation. I decided to reinstall miniconda, created a new environment and then installed pillow. I still get the ImportError

1. Install the latest version of miniconda (Windows 64-bit, Python 3.7 version)
https://docs.conda.io/en/latest/miniconda.html
2. Then run the following lines of code in the Anaconda Prompt (also reproduced in the Windows command prompt)

```
conda create -n dlta python=3.7
activate dlta
conda config --add channels conda-forge
conda install pillow ipython
ipython
```

And then in ipython
```python
from PIL import Image
```

### What did you expect to happen?

No import errors

### What actually happened?

```
---------------------------------------------------------------------------
ImportError                               Traceback (most recent call last)
<ipython-input-1-b7f01c2f8cfe> in <module>
----> 1 from PIL import Image

~\miniconda3\envs\dlta\lib\site-packages\PIL\Image.py in <module>
     92     # Also note that Image.core is not a publicly documented interface,
     93     # and should be considered private and subject to change.
---> 94     from . import _imaging as core
     95     if __version__ != getattr(core, 'PILLOW_VERSION', None):
     96         raise ImportError("The _imaging extension was built for another "

ImportError: DLL load failed: The specified module could not be found.
```

### What are your OS, Python and Pillow versions?

* OS: Windows 10 64-bit Enterprise, Version 1803
* Python: 3.7.3
* Pillow: 6.2.0 (also tried 5.4, did not work)

**Comment by hugovk** [comment]
Does this help, or other suggestions in this issue? https://github.com/python-pillow/Pillow/issues/2945#issuecomment-356905216

**Comment by JoerivanEngelen** [comment]
I looked through that yesterday and thought it was not applicable to me as:
-I did not mix pip and conda installations
-Used conda-forge
-Used a fresh installation + environment

However reading a bit more carefully, I now see that you also suggested:
```
conda uninstall pillow
pip install pillow
```

This seems to fix it for me, I don't know why. I would prefer having everything working via conda, as conda ignores packages installed with pip.

**Comment by hugovk** [comment]
Good to hear you got it working. We're not involved in any of the conda packaging, only the ones on PyPI used by pip, so if the problem is reproducible, you may be best raising it with the relevant conda project.

What's happening in the error: Pillow is made up of Python and C code. The public API is Python code, and the C code is considered private, internal stuff.

We include a version number in both, to ensure that the Python code is only accessing the corresponding C side, to keep them in sync. But if they're not, that usually indicates some build or install problem.

It might also be that the C interface is failing to load at all from the Python side.

**Comment by JoerivanEngelen** [comment]
Thank you for the insightful information. Since I heard a colleague is experiencing a similar problem, I'll probably open an issue in this project:
https://github.com/conda-forge/pillow-feedstock/issues/45

I think this issue can be closed now, you have done your job ;-)

**Comment by andrewww** [comment]
I just created an issue on the pillow-feedstock project (https://github.com/conda-forge/pillow-feedstock/issues/66), as I am experiencing this as of today.
