### ISSUE TITLE
OSError: cannot identify image file

### ISSUE THREAD

**Issue by oebilgen** [python-pillow/Pillow#4163]
Hi, I have a PNG that cannot be opened by the latest Pillow (6.2.1). `LOAD_TRUNCATED_IMAGES = True` was advised in earlier issues but it did not help.

```console
$ which pip
/...project root.../env/bin/pip
$ pip install --upgrade pillow
Requirement already up-to-date: pillow in /...project root.../env/lib/python3.7/site-packages (6.2.1)
$ python
Python 3.7.2 (v3.7.2:9a3ffc0492, Dec 24 2018, 02:44:43) 
[Clang 6.0 (clang-600.0.57)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image, ImageFile
>>> ImageFile.LOAD_TRUNCATED_IMAGES = True
>>> Image.open('IMG_2342.png')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/...project root.../env/lib/python3.7/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file 'IMG_2342.png'
```

I am attaching it as a zip to avoid reformatting by Github. [IMG_2342.png.zip](https://github.com/python-pillow/Pillow/files/3763934/IMG_2342.png.zip)

The image file can be opened by file, MacOS (Finder and Preview) and Gimp.

```console
$ file IMG_2342.png
IMG_2342.png: ISO Media, HEIF Image HEVC Main or Main Still Picture Profile
```
![image](https://user-images.githubusercontent.com/1641185/67425749-a3068300-f5a6-11e9-91e1-b7b8befaf5ec.png)

Github bug report and latest Chrome cannot open it. Slack thinks that it's a movie.

**Github:**
 ![IMG_2342](https://user-images.githubusercontent.com/1641185/67424757-bc0e3480-f5a4-11e9-8ceb-b902eb303eb7.png)

**Chrome:**
![image](https://user-images.githubusercontent.com/1641185/67425157-81f16280-f5a5-11e9-9f16-362c42dea558.png)

**Slack:**
![image](https://user-images.githubusercontent.com/1641185/67425070-553d4b00-f5a5-11e9-8956-93abed5c9e3f.png)

OS: MacOS Catalina 10.15 (latest)
Python: 3.7.2

Thank you for looking into it!

**Comment by qihua** [comment]
me too,
OSError: cannot identify image file 'upload/images/201910241359171005.tif'
201910241359171005.tif size 6.7G

**Comment by radarhere** [comment]
@qihua without more information, we won't be able to diagnose your problem. Please open another issue, to avoid confusion with the original post which most likely has a different cause. Linking to your image would be ideal, although that image is very large, so a smaller image that you think is similar would be better.

**Comment by kkopachev** [comment]
Based on `file` command output provided in issue description, the image is not PNG, but in HEIF format.

**Comment by hugovk** [comment]
Unfortunately HEIF is not supported, see https://github.com/python-pillow/Pillow/issues/2806.

Thanks anyway for the report.
