### ISSUE TITLE
DdsImagePlugin fails when dxgi_format == DXGI_FORMAT_BC7_UNORM_SRGB

### ISSUE THREAD

**Issue by ouroborus** [python-pillow/Pillow#4164]
https://github.com/python-pillow/Pillow/blob/84fed4d213a50b359188aa59f99ed06ba1249c14/src/PIL/DdsImagePlugin.py#L156-L159

At `self.im_info["gamma"] = 1 / 2.2`, `self.im_info` has never been initialized and so trying to set `self.im_info["gamma"]` fails with:
```
AttributeError: 'DdsImageFile' object has no attribute 'im_info'
```
As far as I can tell, this is the only place `im_info` is ever referenced in this or the ancestor classes.

A possible solution would be to change this section to:
```python
                elif dxgi_format == DXGI_FORMAT_BC7_UNORM_SRGB:
                    self.pixel_format = "BC7"
                    if not hasattr(self, 'im_info'):
                        self.im_info = {}
                    self.im_info["gamma"] = 1 / 2.2
                    n = 7
```

An alternate solution would be to initialize `im_info` earlier in the loader method.

**Comment by ouroborus** [comment]
None of the images I'm working with are available for that and I don't have a way to generate a new file. I'll see what I can do, but you shouldn't get your hopes up.

**Comment by ouroborus** [comment]
@radarhere In a rare alignment of fortune, I was able to produce a file that triggers this issue. See contents of [DXGI_FORMAT_BC7_UNORM_SRGB.zip](https://github.com/python-pillow/Pillow/files/3769280/DXGI_FORMAT_BC7_UNORM_SRGB.zip)
.

**Comment by radarhere** [comment]
Thanks. My conclusion would be that it should be `self.info` rather than `self.im_info` - I've created PR #4171 with this solution.
