### ISSUE TITLE
wmf file to bitmap was forced to 72 dpi

### ISSUE THREAD

**Issue by FrankLiu007** [python-pillow/Pillow#4223]
### What did you do?
I read in an wmf image and then save it as a png image. I found the resolution of the result image is rather low no matter how I set the quality parameters. 

When I looking into the source code ( src/PIL/WmfImagePlugin.py), I found the resolution was fixed to 72dpi.

### What are your OS, Python and Pillow versions?

* OS:  win10
* Python: 3.6.8
* Pillow: 6.1.0

**Comment by radarhere** [comment]
Could you attach the WMF image?

**Comment by FrankLiu007** [comment]
do not support wmf file, @radarhere

**Comment by hugovk** [comment]
If GitHub won't allow you to upload a WMF file, please zip it and upload the zip file.

**Comment by FrankLiu007** [comment]
[image2.zip](https://github.com/python-pillow/Pillow/files/3886606/image2.zip)
Lucy, zip is permitted.

**Comment by radarhere** [comment]
For now, I think you should be able to use this code to set the size that the image is rendered at, and so effectively, the DPI that is used to create the image -
```python
from PIL import Image
im = Image.open("test.wmf")
im._size = (300, 300)
im.load()
```

**Comment by radarhere** [comment]
I've created PR #4311 to resolve this, by adding a `dpi` argument to the WmfImagePlugin `load` method -

```python
with Image.open("Tests/images/drawing.wmf") as im:
    im.load(144)
```
