### ISSUE TITLE
Unhelpful error message when reading too large image from array

### ISSUE THREAD

**Issue by PiRK** [python-pillow/Pillow#4233]
### What did you do?

I tried to read in a series of large numpy RGB arrays with `Image.fromarray`

### What actually happened?
About half of the arrays were properly converted into PIL images, and the other half failed with error `ValueError("not enough image data")`. After investigation, I found out that the failure was related to the number of pixels. I narrowed the failure threshold down to the range 2051700378--2294405760 values. I then googled "pil image from array size limit" and found out about the 2^32 pixels limit.

```python
pil_img = PIL.Image.fromarray(numpy.ones((25922, 26683, 3), dtype=numpy.uint8))   # OK
pil_img = PIL.Image.fromarray(numpy.ones((29632, 25810, 3), dtype=numpy.uint8))   # fails
```

**Comment by PiRK** [comment]
Btw, does anyone know of a python library that offers an image resizing algorithm, that does not internally rely on PIL (like `scipy.misc.imresize`) and that does not have the size limitation?

**Comment by radarhere** [comment]
Could you provide a short code sample to raise the error? It would remove all doubt about which error message you're describing.

**Comment by hugovk** [comment]
Both work for me:

```python
Python 3.7.4 (default, Oct 12 2019, 18:55:28)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> import numpy
>>> Image.__version__
'6.2.1'
>>> numpy.__version__
'1.17.2'
>>> pil_img = Image.fromarray(numpy.ones((25922, 26683, 3), dtype=numpy.uint8))
>>> pil_img = Image.fromarray(numpy.ones((25922, 25810, 3), dtype=numpy.uint8))
>>> 
```

**Comment by PiRK** [comment]
You are right that my examples don't reproduce the error. There must be something special about my images, in addition to their size.

I can reliably reproduce the error with my larger image sizes

    >>> pil_img = Image.fromarray(numpy.ones((29611, 30791, 3), dtype=numpy.uint8))

**Comment by PiRK** [comment]
The problem seems to be solved by upgrading PIL to 6.2.1. Sorry for the disturbance.

**Comment by bijuangalees** [comment]
Now I am facing the same problem in PIL 8.2.0 
My image data size are 2090*1850

my_images = os.listdir(image_directory)
for i, image_name in enumerate(my_images):
    if (image_name.split('.')[1] == 'jpeg'):
        image = io.imread(image_directory + image_name)
        image = Image.fromarray(image, 'RGB')
        image = image.resize((SIZE,SIZE))
        dataset.append(np.array(image))
Traceback (most recent call last):

  File "<ipython-input-47-a54c586b874a>", line 5, in <module>
    image = Image.fromarray(image, 'RGB')

  File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 2793, in fromarray
    return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)

  File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 2733, in frombuffer
    return frombytes(mode, size, data, decoder_name, args)

  File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 2679, in frombytes
    im.frombytes(data, decoder_name, args)

  File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 800, in frombytes
    raise ValueError("not enough image data")

ValueError: not enough image data

**Comment by radarhere** [comment]
Could you attach a copy of the problem image?

**Comment by Guide4Ever** [comment]
> Now I am facing the same problem in PIL 8.2.0 My image data size are 2090*1850. Could you help me
> 
> ```python
> my_images = os.listdir(image_directory)
> for i, image_name in enumerate(my_images):
>     if (image_name.split('.')[1] == 'jpeg'):
>         image = io.imread(image_directory + image_name)
>         image = Image.fromarray(image, 'RGB')
>         image = image.resize((SIZE,SIZE))
>         dataset.append(np.array(image))
> ```
> 
> ```
> Traceback (most recent call last):
> 
>   File "<ipython-input-47-a54c586b874a>", line 5, in <module>
>     image = Image.fromarray(image, 'RGB')
> 
>   File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 2793, in fromarray
>     return frombuffer(mode, size, obj, "raw", rawmode, 0, 1)
> 
>   File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 2733, in frombuffer
>     return frombytes(mode, size, data, decoder_name, args)
> 
>   File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 2679, in frombytes
>     im.frombytes(data, decoder_name, args)
> 
>   File "C:\Users\bijuangalees\anaconda3\envs\py37tf25cpu\lib\site-packages\PIL\Image.py", line 800, in frombytes
>     raise ValueError("not enough image data")
> 
> ValueError: not enough image data
> ```

I see you were going through alibi-detect library hehe :P Same problem <3

**Comment by radarhere** [comment]
Could you attach a copy of the problem image?
