### ISSUE TITLE
Exceptions when users upload a GIF

### ISSUE THREAD

**Issue by uri-rodberg** [python-pillow/Pillow#4235]
Hi,

We are using `Pillow==6.2.1` in [Speedy Net](https://github.com/speedy-net/speedy-net). I found out that if users upload a GIF, whether animated or not - there is an internal server error on the website when viewing the user's profile (for users who uploaded a GIF). This is until I deleted the GIF from our server. I received an exception - `OSError` - `cannot write mode RGBA as JPEG` - in `env/lib/python3.6/site-packages/PIL/JpegImagePlugin.py in _save, line 621`. Is there a way to fix this bug or at least prevent users from uploading a GIF?

Thanks,
אורי.

**Comment by radarhere** [comment]
Hi. That doesn't make a lot of sense to me. Pillow GIFs have mode L or P. So if you're receiving an error that an RGBA image can't be saved as a JPEG, I imagine something else is happening. Are you able to provide a code sample to demonstrate the problem?

As for how to tell whether or not a Pillow image is a GIF -
```python
from PIL import Image
im = Image.open("Tests/images/hopper.gif")
print(im.format)  # GIF
```
But in the context of uploading a file, I'd be surprised if you couldn't just check the file extension first using regular Python.

**Comment by uri-rodberg** [comment]
I checked now and uploaded two gifs to our staging server - one not animated and one animated. The not-animated gif worked fine. The animated gif causes an internal server error when viewing the profile of the user who uploaded the image. Does it make sense? I'm not sure but maybe the problem is only when the gif is animated.

If you want I can give you access to our staging server as a user and you can try to create accounts and upload images. Contact me privately by email uri@speedy.net.

**Comment by uri-rodberg** [comment]
Hi,

I added a validator called [`validate_photo_for_user`](https://github.com/speedy-net/speedy-net/commit/b1ee35b41b82c12f5983d30ce0aa843e0af78ccf#diff-53f67b16827497bcf5311316b73f1d13R48) to catch this exception, and don't accept the file if there is an exception (any exception) when creating a thumbnail. But, if there is an exception in the user's profile view, the server will still fail. I hope you can fix this error so that exceptions will not be raised when creating a thumbnail.

**Comment by radarhere** [comment]
I am able to create a thumbnail using an animated GIF from the Pillow test suite, without throwing an error.
```python
from PIL import Image
im = Image.open("Tests/images/iss634.gif")
im.thumbnail((100, 100))
```
So unfortunately, things are not that simple.

**Comment by radarhere** [comment]
Unfortunately, unless you can provide an image and/or code to demonstrate a problem, there isn't anything to be done here - we don't know precisely what code is being run, and the general scenarios being described don't show a problem either.

**Comment by uri-rodberg** [comment]
I'm attaching 2 images - the first one (animated) cause an exception, and second one doesn't. The exception is when creating a thumbnail from the image.

![gif-shaking-back-forth](https://user-images.githubusercontent.com/12808124/69908925-2d8a9f80-13fb-11ea-9890-ab4564816963.gif)
![earth](https://user-images.githubusercontent.com/12808124/69908928-38ddcb00-13fb-11ea-9e22-0638b44ab54e.gif)

We are using `sorl.thumbnail` so if you create the thumbnail directly without using it, maybe you will not get an exception.

The excepton is created by a tag we created, `profile_picture`, in the templates:
https://github.com/speedy-net/speedy-net/blob/master/speedy/core/templates/profiles/user_photo_widget.html#L4

The tag calls another template which uses `sorl.thumbnail` to create the thumbnail.

**Comment by hugovk** [comment]
No problem for me exceptions those thumbnailing with Pillow master or 6.2.1:

```python
Python 3.7.4 (default, Oct 12 2019, 18:55:28)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.__version__
'7.0.0.dev0'
>>> im = Image.open("animated.gif")
>>> im.thumbnail((100, 100))
>>> im.show()
>>> im = Image.open("not-animated.gif")
>>> im.thumbnail((100, 100))
>>> im.show()
>>>
```

```python
Python 3.7.4 (default, Oct 12 2019, 18:55:28)
[Clang 11.0.0 (clang-1100.0.33.8)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> Image.__version__
'6.2.1'
>>> im = Image.open("animated.gif")
>>> im.thumbnail((100, 100))
>>> im.show()
>>> im = Image.open("not-animated.gif")
>>> im.thumbnail((100, 100))
>>> im.show()
>>>
```

> We are using `sorl.thumbnail` so if you create the thumbnail directly without using it, maybe you will not get an exception.

Yes, you may be better off reporting this to https://github.com/jazzband/sorl-thumbnail.

**Comment by uri-rodberg** [comment]
> > We are using `sorl.thumbnail` so if you create the thumbnail directly without using it, maybe you will not get an exception.
> 
> Yes, you may be better off reporting this to https://github.com/jazzband/sorl-thumbnail.

Already did. https://github.com/jazzband/sorl-thumbnail/issues/599

**Comment by radarhere** [comment]
Going to throw an idea out there.

https://github.com/jazzband/sorl-thumbnail/blob/4384015aabeeaf55c3eca61a9df2eac77f47d15e/sorl/thumbnail/engines/pil_engine.py#L143-L144 looks like it could be where the image becomes RGBA. The first image you attached has transparency, the second does not.

So why is it attempting to be saved as JPEG? JPEG is the default THUMBNAIL_FORMAT that sorl-thumbnail uses. If it can't determine the file type from the extension, it uses that.

Is it possible that the images you're passing in to sorl-thumbnail don't have a file extension? If so, then I would recommend changing your application so that the images are saved with a file extension, and see if that fixes it.

**Comment by radarhere** [comment]
Or, as a quicker test, if you set THUMBNAIL_FORMAT in your settings to PNG, that could also work.

**Comment by uri-rodberg** [comment]
> Or, as a quicker test, if you set THUMBNAIL_FORMAT in your settings to PNG, that could also work.

Yes, it works! Thank you! I'm closing this issue for now.
