### ISSUE TITLE
Pillow 6.2 fails to open JPEG image with corrupted Photoshop metadata

### ISSUE THREAD

**Issue by bstallenberger** [python-pillow/Pillow#4236]
### What did you do?
Tried to open a .jpg image with PIL.

### What did you expect to happen?
The photo can be opened in a browser and by IrfanView (v4.53, 64bit, Windows 7).

### What actually happened?
```python
from PIL import Image
Image.open("test.jpg")
```

```
File "testFIL.py", line 3, in <module>
  im = Image.open("test.jpg")
File "/home/fe/stallenberger/anaconda3/envs/pillow/lib/python3.8/site-packages/PIL/Images.py", line 2818, in open
  raise IOError("cannot identify image file %r" % (filename if filename else fp))
OSError: cannot identify image file 'test.jpg'
```

### What are your OS, Python and Pillow versions?
    OS: Scientific Linux release 7.7 (Nitrogen)
    Python: 3.8.0
    Pillow: 6.2

### Image file
![test](https://user-images.githubusercontent.com/58255551/69719202-46036d00-1110-11ea-8cff-594225f7e49c.jpg)

For this particular image, the PhotoShop metadata (APP13 segment) seems to be corrupted since it ends with "8BIM". Normally, this tag introduces an Image Resource Block but in this particular file there is no data following in the APP13 segment. Thus, parsing this block of metadata and therefore opening the image fails.

Opening the image in Pillow 5.3.0 works well, since this version ignores the APP13 segment.

**Comment by radarhere** [comment]
Thanks for reporting this. Is the image that you've supplied one that can be included in the test suite, and distributed under the Pillow license?

**Comment by radarhere** [comment]
I've created PR #4239 to resolve this.

**Comment by bstallenberger** [comment]
The image is from the Open Images dataset (V2, 2017-07) and can be retrieved from [https://c2.staticflickr.com/3/2332/2154341610_9734c06295_o.jpg](https://c2.staticflickr.com/3/2332/2154341610_9734c06295_o.jpg). Thus, the image should be under CC BY 2.0 license (see [https://github.com/openimages/dataset/blob/master/READMEV2.md](https://github.com/openimages/dataset/blob/master/READMEV2.md)).

It should be OK to include the image in the test suite as long as a reference to the original source is included as well, but I'm not sure about this.
