### ISSUE TITLE
Tweetdeck for teams

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4241]
Probably should set this up at some point, so I can change the python-pillow Twitter account password:

- https://help.twitter.com/en/using-twitter/tweetdeck-teams

**Comment by radarhere** [comment]
Would you like help on this? Those of us who have managed releases already have the password - we could start this by setting up the team, just leaving you to change the password.

**Comment by aclark4life** [comment]
@radarhere Yes please! Basically I'd like to be able to change the account password occasionally without having to send the new password to the @python-pillow/pillow-team. As far as I can tell, we can do that with this feature.

**Comment by hugovk** [comment]
I received the invite and accepted it in Tweetdeck.

**Comment by radarhere** [comment]
Yes. aclark4life, hugovk and myself are now all part of the team. @wiredfool is pending acceptance. Those are all the people who have managed a release in the past.

So now, when authoring a new tweet from my personal account at https://tweetdeck.twitter.com/, there is the option to tweet as PythonPillow.

**Comment by hugovk** [comment]
Will I still be able to check the account from Android or will it only be possible using Tweetdeck on desktop?

**Comment by radarhere** [comment]
You should be able to use the Tweetdeck website on mobile.

As for the Twitter Android app, it seems like [you could once](https://techcrunch.com/2017/09/08/twitter-enables-account-sharing-in-its-mobile-app-powered-by-tweetdeck-teams/), but I'm not so sure any more -
https://help.twitter.com/en/using-twitter/tweetdeck-teams
> **Can I use Teams outside of TweetDeck?**
> Team features are only available in TweetDeck.

**Comment by hugovk** [comment]
OK. I can use Tweetdeck for releases but don't use it otherwise. 

I sometimes do replies, retweets and likes from mobile due to convenience, but it's not essential.

**Comment by aclark4life** [comment]
Thanks @radarhere ; I haven't changed the password yet, so @hugovk your mobile should still work. Next time I change it, I can still send the new one, just don't want to have to worry everyone is locked out.

**Comment by hugovk** [comment]
Sounds good, thanks!
