### ISSUE TITLE
"Noise" in the background of GIF animations

### ISSUE THREAD

**Issue by jiannmeng** [python-pillow/Pillow#4263]
### What did you do?
Saved an animated GIF with a plain background and an incrementing integer in the middle.

### What did you expect to happen?
The output should look like this (the "good" gif):
![good](https://user-images.githubusercontent.com/8881844/70501673-ab684c80-1b59-11ea-8fec-9b467df0c299.gif)

### What actually happened?
The output looks like this (the "bad" gif):
![bad](https://user-images.githubusercontent.com/8881844/70501681-b7eca500-1b59-11ea-8204-2c14b2c8f32b.gif)
Notice the background is full of noise, and the noise at the bottom right changes every frame.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7
* Pillow: 6.2.1

```python
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

save_kwargs = {
    "format": "GIF",
    "save_all": True,
    "duration": 100,
    "loop": False,
}

font = ImageFont.truetype(font="arial", size=36)
frames = []
for i in range(0, 20):
    frame = Image.new("RGB", (200, 200), color="#FFAD94")
    draw = ImageDraw.Draw(frame)
    draw.text((90, 90), str(i), font=font)
    frames.append(frame)

# Bad - Save the Image objects directly to an animated GIF.
frames[0].save("bad.gif", append_images=frames[1:], **save_kwargs)

# Good - Save each Image object as a static GIF, then stitch the GIFs together
# to form the animated GIF.
byteframes = []
for f in frames:
    byte = BytesIO()
    byteframes.append(byte)
    f.save(byte, format="GIF")
imgs = [Image.open(byteframe) for byteframe in byteframes]
imgs[0].save("good.gif", append_images=imgs[1:], **save_kwargs)
```

**Comment by radarhere** [comment]
By changing the mode of the image to P, I find that the following code works -

```python
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

save_kwargs = {
    "format": "GIF",
    "save_all": True,
    "duration": 100,
    "loop": False,
}

font = ImageFont.truetype(font="/System/Library/Fonts/Supplemental/Arial.ttf", size=36)
frames = []
for i in range(0, 20):
    frame = Image.new("P", (200, 200), color="#FFAD94")
    draw = ImageDraw.Draw(frame)
    draw.text((90, 90), str(i), "#fff", font=font)
    frames.append(frame)

frames[0].save("bad.gif", append_images=frames[1:], **save_kwargs)
```

**Comment by jiannmeng** [comment]
Thanks @radarhere , changing "RGB" to "P" works perfectly - and was about 10x faster than "RGB" mode!

**Comment by radarhere** [comment]
Does that resolve this issue for you then?

**Comment by jiannmeng** [comment]
Yes, thank you!

**Comment by vikky1992** [comment]
If we are not creating the image by `Image.new()` method and we are reading an existing `.png `image, how can we set the `mode` parameter?

**Comment by radarhere** [comment]
To change an image from one mode to another, use the `convert` method - https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.Image.convert
