### ISSUE TITLE
RGB dds file's mode attribute is RGBA

### ISSUE THREAD

**Issue by juiceyang** [python-pillow/Pillow#4264]
### What did you do?

```python
Python 3.7.1 (v3.7.1:260ec2c36a, Oct 20 2018, 14:57:15) [MSC v.1915 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> PIL.__version__
'6.2.0'
>>> from PIL import Image
>>> img = Image.open('sample.dds')
>>> img.mode
'RGBA'
>>> img.tile
[('raw', (0, 0, 1024, 1024), 0, ('RGB', 0, 1))]
>>> img.load()
[('raw', (0, 0, 1024, 1024), 0, ('RGB', 0, 1))]
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python37\lib\site-packages\PIL\ImageFile.py", line 224, in load
    self.mode, decoder_name, args, self.decoderconfig
  File "C:\Python37\lib\site-packages\PIL\Image.py", line 455, in _getdecoder
    return decoder(mode, *args + extra)
ValueError: unknown raw mode
```

img.mode, which is "RGBA", and img.tile[0][3][0], which is "RGB", mismatch.

### What did you expect to happen?

img.mode is expected to be "RGB".

### What actually happened?

Loading a DDS file containing no alpha data may raise ValueError. I cannot use img.mode attribute to check if the file contains alpha data.

### What are your OS, Python and Pillow versions?

OS: windows10 v10.0.17763
Python: 3.7.1
Pillow: 6.2.1

```
Code is attached in What did you do section.
```

I cannot upload the image to github due to company restriction.

But the 0x50--0x53 of the dds file is 0x40 0x00 x00 0x00.

From [this document](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-pixelformat), I think the pixel format is RGB but not RGBA.

**Comment by radarhere** [comment]
Using ImageMagick (`convert -format dds -define dds:compression=none hopper.jpg hopper.dds`) I was able to create a file that reproduces your error. Do you agree this is a sufficient recreation of the file type you're dealing with?

[hopper.dds.zip](https://github.com/python-pillow/Pillow/files/3955291/hopper.dds.zip)

**Comment by juiceyang** [comment]
Yes.

**Comment by juiceyang** [comment]
The uint32 of [this file](https://github.com/python-pillow/Pillow/blob/master/Tests/images/uncompressed_rgb.dds) at address 0x1c824, which is the pixel at (361, 36), is 0x44FFADFF.

```
0x1c824 = 29161 * 4 + 0x80 = (800 * 36 + 361) * 4 + 0x80
```

From [this document](https://docs.microsoft.com/en-us/windows/win32/direct3ddds/dds-pixelformat), we know the fields (value is little endian) of DDS_PIXELFORMAT struct of dds header as following.

```
dwRBitMask = 0x0000FF00
dwGBitMask = 0x00FF0000
dwBBitMask = 0xFF000000
dwABitMask = 0x000000FF
```

Because of little endianness, the actual pixel rawmode is "ARGB". So the pixel content at position (361, 36) is A255 R173 G255 B68. (A0xFF R0xAD G0xFF B0x44)

I get the same value by this [Windows Texture Viewer](https://developer.nvidia.com/legacy-texture-tools) provided by nvidia.
![image](https://user-images.githubusercontent.com/3899797/72717146-7ca8b180-3bae-11ea-8a3a-a82176a7a203.png)

But when using Pillow parsing the uncompressed_rgb.dds file, I got different result.

```python
>>> from PIL import Image
>>> img_dds = Image.open('uncompressed_rgb.dds')
>>> img_dds.getpixel((361, 36))
(255, 173, 255, 68)
>>> img_dds.getbands()
('R', 'G', 'B', 'A')
```

Is this a bug?

**Comment by radarhere** [comment]
The final mode is RGBA, yes - that part isn't a bug. There is a `rawmode` that Pillow uses to interpret the data before it is converted to RGBA.

**Comment by radarhere** [comment]
I've created #5383 to resolve this.

As for why the mode of one of our test images is not ARGB, this is what Pillow considers to be the 'raw mode'. The final mode is RGBA. See https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-file-decoder.html#the-raw-decoder
> **raw mode**
> The pixel layout used in the file, and is used to properly convert data to PIL’s internal layout. For a summary of the available formats, see the table below.
