### ISSUE TITLE
Allow non-standard chunks to be saved in PNG files

### ISSUE THREAD

**Issue by ewewukek** [python-pillow/Pillow#4265]
### What did you do?
I'm making a simple tool that's modifying sprites for ZDoom source port of Doom video game. It uses non-standard PNG chunks to store additional information, eg sprite offsets.

```python
import struct
from PIL import Image
from PIL.PngImagePlugin import PngInfo

img = Image.open('src.png')
pnginfo = PngInfo()
pnginfo.add(b'grAb', struct.pack('>II', 10, 49))
img.save('dst.png', pnginfo=pnginfo)
```

### What did you expect to happen?
To see a 'grAb' chunk inside saved PNG file (like source image has)

### What actually happened?
Chunk have not been saved because there is a forced list of chunks that's being saved inside `src/PIL/PngImagePlugin.py`

### What are your OS, Python and Pillow versions?

* OS: GNU/Linux
* Python: 3.8.0
* Pillow: 6.2.1

As far as I understand PNG specification doesn't strictly forbid saving unknown chunks with "Safe-to-copy bit" set to 0. PIL is great tool for image manipulation automation, I think it would be great to give developers more ways of using it. Thanks!

**Comment by radarhere** [comment]
I've created PR #4292 to resolve this.
