### ISSUE TITLE
Where do I enter the pip command to install libraries

### ISSUE THREAD

**Issue by Sundew23** [python-pillow/Pillow#4269]
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```python
code goes here
```

**Comment by Sundew23** [comment]
I try the command prompt but it says pip is not a command
Window 10 64 bit python 3.8 and not downloaded

**Comment by radarhere** [comment]
Sounds like you need to install pip - https://pip.pypa.io/en/stable/installing/#installing-with-get-pip-py

**Comment by radarhere** [comment]
Let us know if you have any further questions.
