### ISSUE TITLE
KeyError: 34864 during getexif().items()

### ISSUE THREAD

**Issue by squeezer44** [python-pillow/Pillow#4270]
## What did I do?

  I was trying to read the exif tags from an image.

## What did I expect to happen?

  Display all existing exif-tags of an image without any errors.

## What happened actually?

  The reading of existing exif-tags has started but was interrupted with a key-error.
  Existing exif tags in this image: 49
  Read exif tags by Pillow: 34
  
  This was the stacktrace:
```
    ExifVersion: b'0230'
    ComponentsConfiguration: b'\x01\x02\x03\x00'
    ShutterSpeedValue: (7, 1)
    DateTimeOriginal: 2017:03:05 16:37:48
    DateTimeDigitized: 2017:03:05 16:37:48
    ApertureValue: (13, 8)
    ExposureBiasValue: (-1, 3)
    MaxApertureValue: (453, 247)
    MeteringMode: 6
    Flash: 16
    FocalLength: (50, 1)
    ExifImageWidth: 1500
    ExifImageHeight: 1000
    SceneCaptureType: 0
    FocalPlaneXResolution: (201961, 53)
    FocalPlaneYResolution: (873841, 229)
    SubsecTime: 00
    SubsecTimeOriginal: 00
    SubsecTimeDigitized: 00
    FocalPlaneResolutionUnit: 2
    Model: Canon EOS 6D
    Orientation: 1
    Make: Canon
    ExposureTime: (1, 125)
    XResolution: (72, 1)
    YResolution: (72, 1)
    FNumber: (9, 5)
    ExposureProgram: 3
    CustomRendered: 0
    ISOSpeedRatings: 400
    ResolutionUnit: 2
    Gamma: (11, 5)
    ExposureMode: 0
    FlashPixVersion: b'0100'

    ---------------------------------------------------------------------------
    KeyError                                  Traceback (most recent call last)
    <ipython-input-8-d265900dfda7> in <module>
          1 for i, j in img._getexif().items():
    ----> 2     print(ExifTags.TAGS[i] + ": " + str(j))

    KeyError: 34864
```

## OS, Python and Pillow versions

  OS: Windows 10 Pro
  Python 3.7.3
  Pillow: 6.2.1

**Comment by radarhere** [comment]
`ExifTags.TAGS` isn't a complete list of TIFF tags. We can add 34864, SensitivityType, if you would like, but what you're trying to do isn't actually possible in the general case, because custom TIFF tags can exist - numbers selected by the creator of the TIFF that don't correspond to any public registry.

**Comment by radarhere** [comment]
Instead of
```python
for i, j in img._getexif().items():
     print(ExifTags.TAGS[i] + ": " + str(j))
```

I might suggest

```python
for i, j in im._getexif().items():
     print(ExifTags.TAGS.get(i, "Unknown tag") + ": " + str(j))
```

That would allow you to continue to iterate through the rest of the tags.

**Comment by radarhere** [comment]
Let us know if you have any further questions, or think that we should develop a more comprehensive list of tags, but for now at least, I'm closing this, as it isn't possible to do what you would like in a general case.

**Comment by mixmastamyk** [comment]
Hmm, this is the one key not recognized in the Exif from my Canon point and shoot.  Searching for this I came across:

```
JEITA CP-3451C         CIPA DC-008-2012

Table 8 Exif IFD Attribute Information (2)
    G. Tags Relating to Picture-Taking Conditions

    Sensitivity Type  SensitivityType 34864

(Page) 43
```
http://www.cipa.jp/std/documents/e/DC-008-2012_E.pdf

It isn't a custom key as far as I can tell, but a part of the Exif 2.3 standard, dated 2012.  Looks like it should be included.

**Comment by radarhere** [comment]
It was added to `ExifTags.TAGS` in #5419.

Could you attach the image and some code to demonstrate your problem?

**Comment by mixmastamyk** [comment]
Thanks, didn't have a problem exactly.  I looked up the missing id number and it brought me here.  Easy to work around, but the response here led me to believe it wouldn't be added.  Looks like it was and my pillow was a bit out of date. (8.1.2)
