### ISSUE TITLE
PSD file that cannot be read

### ISSUE THREAD

**Issue by eshellman** [python-pillow/Pillow#4279]
### What did you do?
tried to open a file that some readers (macOS preview, for example) can handle and others can't (Chrome on MacOS).

(we have maybe a 100,000 to 500,000 images - not sure how common this is.)

(files, code  attached)
good:
![illus-152b](https://user-images.githubusercontent.com/926513/71152179-ba0ecd80-2203-11ea-8c97-2d617609d7d6.jpg)
bad:
![illus-030b](https://user-images.githubusercontent.com/926513/71152180-ba0ecd80-2203-11ea-9b0e-5d341c7bc090.jpg)

The images are in the public domain.

### What did you expect to happen?
both files should open
### What actually happened?
```
Traceback (most recent call last):
  File "badjpg.py", line 6, in <module>
    image = Image.open ('illus-030b.jpg')
  File "/Users/eric/.virtualenvs/ebookmaker-m5_93t2a/lib/python3.6/site-packages/PIL/Image.py", line 2818, in open
    raise IOError("cannot identify image file %r" % (filename if filename else fp))
```
### What are your OS, Python and Pillow versions?

* OS: MacOS, CentOS
* Python: Python 3.6.4, 3.6.9
* Pillow: 6.2.1

Code:
```python
from PIL import Image
# works
image = Image.open ('illus-152b.jpg')
# fails
image = Image.open ('illus-030b.jpg')

```

**Comment by radarhere** [comment]
Could you clarify - what is the relation between the good and bad file? They were both created by the same process?

**Comment by radarhere** [comment]
The 'bad' file is actually an Adobe Photoshop document. You can see this in macOS Preview's info panel

![bad](https://user-images.githubusercontent.com/3112309/71156183-91ceaf80-2293-11ea-8948-02442582f961.png)

**Comment by eshellman** [comment]
OK, that's just my mistake. Was confused because I didn't realize OSX could open that sort of file.
