### ISSUE TITLE
About the time of opening image

### ISSUE THREAD

**Issue by dong798** [python-pillow/Pillow#4289]
Thanks for sharing, I found the following interesting things:  If you continue to read the image, the running time will gradually  decrease to a certain degree; 2. If you sleep and read for 20s after  reading an image, the running time is the same as the first time, can  you help me analyze what Why, can you find a way to keep the image  reading at a relatively fast speed regardless of the time interval?
--

**Comment by radarhere** [comment]
Hi. You've also just posted a duplicate of this at https://github.com/ajkxyz/jpeg4py/issues/5. Considering these two projects don't look connected, I am skeptical. If you are genuine, please provide more information, such as self-contained code demonstrating your problem, and any images required to reproduce.
