### ISSUE TITLE
Upload an image to customize your repository’s social media preview

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4312]
@python-pillow/pillow-team OK I'll bite, can we do this, or get someone to make something for us? 

In repo settings, GitHub have added a Social preview field with description:

  Upload an image to customize your repository’s social media preview.
Images should be at least 640×320px (1280×640px for best display).

And they provide a template.

![repository-open-graph-template](https://user-images.githubusercontent.com/72164/71543464-031bfb80-2941-11ea-9684-eb0ca4d35688.png)

Not urgent, obviously, but may be fun to try and get it in for 2020.

**Comment by hugovk** [comment]
Yes, let's.

How about a higher-res version of https://python-pillow.org/images/pillow-logo.png, possibly with darker text? It should use transparency and work well with both light and dark Twitter themes. 

![pillow-logo](https://user-images.githubusercontent.com/1324225/71544023-bbb65f00-2982-11ea-9143-d4eb4cf30fd5.png)

https://github.com/python-pillow/pillow-logo has high-res versions of the logo only, but not with the text.

**Comment by radarhere** [comment]
Here's my attempt at putting together higher-resolution versions. I used the existing high res logo, used an online service to identify the font as Flux Bold, and left the shadow as just a scaled up image, because it's blurry already.
![pillow-logo](https://user-images.githubusercontent.com/3112309/71551727-1662c000-2a42-11ea-830d-e4fc8ff810fd.png)
![pillow-logo-dark](https://user-images.githubusercontent.com/3112309/71551726-1662c000-2a42-11ea-8f33-de13f61f0835.png)

**Comment by aclark4life** [comment]
Very nice! Thanks @radarhere and @hugovk

**Comment by hugovk** [comment]
Great! Please could you add them to https://github.com/python-pillow/pillow-logo?

PS @aclark4life I don't have merge rights for that repo, please could you merge https://github.com/python-pillow/pillow-logo/pull/3?

**Comment by aclark4life** [comment]
@hugovk Added Pillow Team as Collaborator with write permission in pillow-logo repo

**Comment by hugovk** [comment]
Thanks, merged https://github.com/python-pillow/pillow-logo/pull/3 and created https://github.com/python-pillow/pillow-logo/pull/4.

**Comment by hugovk** [comment]
Testing the second one from https://github.com/python-pillow/Pillow/issues/4312#issuecomment-569468904 in my fork shows it needs some extra padding:

---

![image](https://user-images.githubusercontent.com/1324225/72783459-2b8cd200-3c2f-11ea-954b-5e8ec7fa51e0.png)

---

And then in https://cards-dev.twitter.com/validator:

![image](https://user-images.githubusercontent.com/1324225/72783554-6262e800-3c2f-11ea-8a0e-95b183f79e34.png)

---

And https://developers.facebook.com/tools/debug/:

![image](https://user-images.githubusercontent.com/1324225/72783638-9c33ee80-3c2f-11ea-9bca-0eae8a315cb8.png)

**Comment by hugovk** [comment]
Here are some with extra padding:
* https://github.com/python-pillow/pillow-logo/pull/5

---

Here's how `pillow-logo-dark-text-1280x640.png` looks from my fork:

![image](https://user-images.githubusercontent.com/1324225/75553207-97d5cf00-5a40-11ea-8522-0595a287dc80.png)

---

# Twitter

![image](https://user-images.githubusercontent.com/1324225/75553249-b045e980-5a40-11ea-810b-b2a7c674dfc4.png)

---

# Facebook

![image](https://user-images.githubusercontent.com/1324225/75553273-be940580-5a40-11ea-95a1-e0f7776315c2.png)

---

@aclark4life Would you like to add `pillow-logo-dark-text-1280x640.png` at https://github.com/python-pillow/Pillow/settings?

**Comment by aclark4life** [comment]
@radarhere Sure, is that the same as this one ? https://github.com/python-pillow/pillow-logo/blob/master/pillow-logo-dark-text.png

**Comment by hugovk** [comment]
No, it's in this PR: https://github.com/python-pillow/pillow-logo/pull/5

**Comment by aclark4life** [comment]
Thanks both, done!
