### ISSUE TITLE
Converting animated gif to webp produces faulty images

### ISSUE THREAD

**Issue by madeddy** [python-pillow/Pillow#4313]
### What did you do?
Converted some animated gifs to animated webp. Used different qualtity settings.

### What did you expect to happen?
Getting a identical converted image. Beside the(logical) format and possible size change.

### What actually happened?
Webp outputs are defect. Three different problems appear.
The output images:
1. play too slow
2. do not play in a image viewer (gwenview for me OR in Pillow's Image.show() method)
3. some images have after convert also visual defects like wrong pixels (flickering and line style artifacts)

ps.: Converting the same images with the same settings with webp CLI tools works without issues.

### What are your OS, Python and Pillow versions?

* OS: Kubuntu 18.04.3
* Python: 3.6.9
* Pillow: 6.2.1

### Code example
Python:
```python
from pathlib import Path as pt
from PIL import Image

src_f = pt("animated.gif")
dst_f = pt(src_f).with_suffix('.webp')

# other used quality settings for fast copy past:
# {'lossless': True} {'allow_mixed': True}
quali = {'quality': 90}

Image.open(src_f).save(dst_f, 'webp', **quali, save_all=True)
```
Shell variant:
```bash
gif2webp -v -lossy -q 90 paris_metro.gif -o paris_metro.webp
```

### Example images
Content of the archive:
- Two input gifs
- both output files (converted with "quality 90") with problems 1. and 2.
- paris_metro.webp has also problem 3. present. (pixel errors are to see while playing)
[anim.tar.gz](https://github.com/python-pillow/Pillow/files/4008165/anim.tar.gz)

**Comment by radarhere** [comment]
I'm unable to replicate 2. The following code works for me with your attached images.
```python
from PIL import Image
Image.open("animated.webp").show()
Image.open("paris_metro.webp").show()
```

**Comment by radarhere** [comment]
To fix 1, you just need to pass in the duration -
```python
im = Image.open(src_f)
im.save(dst_f, 'webp', **quali, duration=im.info["duration"], save_all=True)
```

**Comment by madeddy** [comment]
OK. Lets see.
1. With duration passed in _it works now correct._ (What the ...! Not true. I come back to this.) 
2. Was a two pronged problem:
- Not playing with .show()  - i did'n notice it uses a viewer app from underlying OS. So its _not pillow related_ - totally my fault (For me it uses imagemagick and still doesn't play.)
- Did'n work in Kubuntu's gwenview, but _now it does play_. Was imo caused by 1. 
3. Um... Does this mean the convert is ok, however the input gets corrupted because of a faulty read in?

Problem 1. is solvable with the mentioned workaround but i consider this now even more a bug as before. Pillow has the input file and can get all needed infos by himself. Or whats next? 

Do you find it a acceptable approach if i would make a enhancement issue out of it? Chances? So basically pillow takes the duration in the above fashion, if not passed in by user.

Greets

**Comment by radarhere** [comment]
1. Pillow values backwards compatibility. So I don't think that changing defaults is likely to be accepted.
3. Saving is ok, but reading is not. This may or may not be helpful to you, but it's more an explanation here.

**Comment by madeddy** [comment]
For 3) Ah no, thats good. The explanation is appreciated. Even if i cannot do anything about it, but i hope you folks find the problem.
For 1) I feared something like this. https://pillow.readthedocs.io/en/latest/reference/Image.html#PIL.Image.info A pitty.
To get this under control, Pillow would imho need a extended analysis module for the input image attributes with tons of checks and rechecks and compares and tests etc.

**Comment by radarhere** [comment]
Testing, I find 3 is resolved by #5333

**Comment by radarhere** [comment]
I've created #5338 to change the default behaviour for 1, since I realised that GIF already behaves in this way.

**Comment by madeddy** [comment]
Really great! 🥳 
Thanks your work for and getting back to this. (This can then be closed with the successful pull merge.)

Greets
