### ISSUE TITLE
Saving as GIF throws exception when source image has "comment" metadata

### ISSUE THREAD

**Issue by mdiller** [python-pillow/Pillow#4325]
### What did you do?
Attempted to open a png image file, and save it as a gif file.

### What did you expect to happen?
The file should have been successfully saved/converted

### What actually happened?
This exception was thrown:
```
Traceback (most recent call last):
  File "test.py", line 8, in <module>
    image.save("out.gif", "gif")
  File "/usr/local/lib/python3.6/site-packages/PIL/Image.py", line 2084, in save
    save_handler(self, fp, filename)
  File "/usr/local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 513, in _save
    _write_single_frame(im, fp, palette)
  File "/usr/local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 415, in _write_single_frame
    _write_local_header(fp, im, (0, 0), flags)
  File "/usr/local/lib/python3.6/site-packages/PIL/GifImagePlugin.py", line 577, in _write_local_header
    fp.write(o8(len(subblock)) + subblock)
TypeError: can't concat str to bytes
```

### What are your OS, Python and Pillow versions?
* OS: Ubuntu 14.04.5
* Python: 3.6.6
* Pillow: 6.2.1

## Code to Reproduce
```python
from PIL import Image
image = Image.open("example.png")
image.save("out.gif", "gif")
```
Have this image in the directory while running the code:
![example.png](https://user-images.githubusercontent.com/3231343/71637322-bc562c00-2bf4-11ea-8198-7712d87eda23.png)

## My diagnosis
It appears that it is erroring because when it tries to write the "comment" field from the encoderinfo of the image, the "comment" field is a string instead of bytes. I'm guessing either that should be checked here, or it should be read in differently when `Image.open` is called. I checked this by checking the metadata of the image via `identify -verbose example.png`. When I stripped the metadata from the image using `mogrify -strip example.png`, the issue went away and the conversion was successful.

Heres the stripped version of the image that has no issues when converted using the code above:
![example_stripped.png](https://user-images.githubusercontent.com/3231343/71637362-42bf3d80-2bf6-11ea-8931-45482fc05116.png)

I'd create a pull request for this myself, except I'm not sure if the fix needs to be on reading it in, or attempting to write it when writing the gif.

**Comment by radarhere** [comment]
Thanks for the report. I've created PR #4326 to fix it when writing the GIF.
