### ISSUE TITLE
frombytes does not appear to support PNG image bytes

### ISSUE THREAD

**Issue by ResidentMario** [python-pillow/Pillow#4337]
I have created a 512x512 transparent PNG image (uploaded [here](https://i.imgur.com/e37wAxu.png) on Imgur, for reference). When I load this image into memory, and then attempt to load it into a PIL image using `fromarray`:

```python
with open('test_image_512.png', 'rb') as f:
    img_b = f.read()
Image.frombytes('RGBA', (512,512), img_b, 'raw')
```

I get `ValueError: not enough image data`.

When I load this image using a different code path&mdash;with `BytesIO` and `Image.open`&mdash;it works as expected:

```python
with open('test_image_512.png', 'rb') as f:
    img_b = f.read()
Image.open(BytesIO(img_b))
```

Does PIL not support loading PNG images from raw PNG bytes using` frombytes`? It seems like this ought to be supported.

**Comment by wiredfool** [comment]
Frombytes doesn’t take images encoded in file formats, it takes raw binary data of the image’s pixels. The function is expecting 512x512x4 bytes and will copy that directly into the pixels of the image. 

To read a PNG image, you need to use Image.open with a file or BytesIO object.

**Comment by ResidentMario** [comment]
Must this be true?

Looking through the code there are other options besides `'raw'` that seem to be intended for decoding encoded image bytes: e.g. I see a `'jpeg'` decoder option, and a `'gif'` one. Assuming these do what I think they do (decode encoded bytes), it's surprising that there is no `png` decoder available in the `fromarray` interface.

**Comment by wiredfool** [comment]
The docs are here: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.frombytes

Practically, this is for raw pixel data. Yes, it’s possible to feed encoded image pixel data into it, but crucially, you’d still have to implement/duplicate all of the other metadata and chunk parsing from the image openers to produce data in the proper form to use this function.

**Comment by radarhere** [comment]
Closing, as this seems like the question has been answered.
