### ISSUE TITLE
Differences between Pillow 4.3.0 and 7.0.0 PNG saving

### ISSUE THREAD

**Issue by xiazhibin** [python-pillow/Pillow#4341]
Firstly, My code run on py2.7 with Pillow==4.3.0
And Now, I upgrade my working env to py3.6 with Pillow==7.0.0
But I found that when I saving the same png to file, png created by Pillow==7.0.0 is larger than Pillow==4.3.0

Is it expected? What make it changes?

**Comment by radarhere** [comment]
Using one of our test images, and comparing the results on Python 3.5 between the two Pillow versions, I don't find any difference.

```python
from PIL import Image
im = Image.open("Tests/images/hopper.jpg")
im.save("hopper.png")
```

Would you mind providing a self-contained example?

**Comment by xiazhibin** [comment]
My condition is somehow complex.
I have three image A.png, B.png, C.png, and I get "R" channel from A.png, "G" channel from B.png and "B" channel from C.png
After that I merge "R","G","B" channels with `Image.merge` and then `Image.save` to file.
I test in my env many times, it shows py2.7+Pillow4.3.0  is different between  from py3.6+Pillow7.0.0

Thanks!

**Comment by radarhere** [comment]
```python
import PIL
import platform
print("Pillow "+PIL.__version__)
print("Python "+platform.python_version())

from PIL import Image
im = Image.open("Tests/images/hopper.jpg")
im.save("hopper.png")

import os
print("hopper.jpg to PNG: "+str(os.path.getsize("hopper.png")))

im = Image.open("Tests/images/hopper.png")
r, g, b = im.split()
im = Image.merge("RGB", (r, g, b))
im.save("hopper.png")

print("Merged PNG channels: "+str(os.path.getsize("hopper.png")))
```

```
$ python3.6 png.py
Pillow 7.0.0
Python 3.6.10
hopper.jpg to PNG: 30493
Merged PNG channels: 30343

$ python2.7 png.py
Pillow 4.3.0
Python 2.7.17
hopper.jpg to PNG: 30493
Merged PNG channels: 30343
```

So I'm still unable to reproduce.

**Comment by radarhere** [comment]
To try and be helpful, here is a search through CHANGES for PNG -

6.2.0
- Changed WindowsViewer format to PNG

6.1.0
- Do not down-convert if image is LA when showing with PNG format

6.0.0
- Added transparency for all PNG greyscale modes
- Add I;16 PNG save
- Add EXIF support for PNG
- Allow for unknown PNG chunks after image data

5.4.1
- PNG: Detect MIME types
- PNG: Handle IDAT chunks after image end

5.4.0
- Add APNG extension to PNG plugin
- Read textual chunks located after IDAT chunks for PNG

5.2.0
- Tests: TestFilePng: Fix test_save_l_transparency()

5.0.0
- PNG: Add support for sRGB and cHRM chunks, permit sRGB when no iCCP chunk present
- Removed check parameter from _save in BmpImagePlugin, PngImagePlugin, ImImagePlugin, PalmImagePlugin, and PcxImagePlugin.
- Make PngImagePlugin.add_text() zip argument type bool
- Add context manager support to ImageFile.Parser and PngImagePlugin.ChunkStream

**Comment by xiazhibin** [comment]
@radarhere Thanks! I will test again

**Comment by homm** [comment]
PNG size depends on compression options. If you don't specify any, you are using default options. This is not an issue that default options are changed. Just set the options you need.

**Comment by homm** [comment]
By the way, the default resizing filter was changed in Pillow 7.0.0, so you are saving different images in different versions, no doubt you will get a different size.

**Comment by xiazhibin** [comment]
@homm Soga, Thanks a lot! So, it worked expected
