### ISSUE TITLE
JPEG 2000 file cannot be Image.reduce() 'd

### ISSUE THREAD

**Issue by Eximius** [python-pillow/Pillow#4343]
JPEG 2000 file cannot be Image.reduce() 'd

... because img.reduce becomes a integer 0 during loading somehow.

Can be repeated with

[this image](https://drive.google.com/open?id=1UbSkNdOuUCt50TTu7Zc4PnuP6f-5RkKK)

```
$ python -c 'import PIL;from PIL import Image; im = Image.open("pillow_bug.jp2"); print(PIL.__version__);print(im.reduce)'
7.1.0.dev0
0
```

**Comment by radarhere** [comment]
Hi. Thanks for reporting this. The bug you've found applies to Jpeg2000 images. I've created PR #4344 to resolve the situation.

In the meantime, you can workaround this by simply copying the image first -

```python
from PIL import Image
im = Image.open("pillow_bug.jp2")
im.copy().reduce(2)
```

**Comment by homm** [comment]
Unfortunately, this breaks a very common use case: 
```python
Image.open("pillow_bug.jp2").thumbnail((100, 100))
```
because thumbnail now uses `.reduce()` method internal.
