### ISSUE TITLE
ImageDraw.Draw.polygon output is sometimes discontiguous

### ISSUE THREAD

**Issue by elfprince13** [python-pillow/Pillow#4347]
### What did you do?
I drew a filled quadrilateral.

### What did you expect to happen?
The output would be a contiguous quadrilateral.

### What actually happened?
The output was discontiguous.

### What are your OS, Python and Pillow versions?

* OS: macOS 10.14.6
* Python: Python 3.7.4 (default, Jul 11 2019, 01:08:00) [Clang 10.0.1 (clang-1001.0.46.4)] on darwin
* Pillow: 6.1.0

```python3
from PIL import Image, ImageDraw
img = Image.new("1", (128, 128))
coords = [(29.0, 74.0), (62.0, 57.0), (99.0, 54.0), (66.0, 71.0)]
drawer = ImageDraw.Draw(img)
drawer.polygon(coords,1,1)
img.show()
```

<img width="332" alt="Screen Shot 2020-01-08 at 4 58 26 PM" src="https://user-images.githubusercontent.com/2703145/72019827-66a70280-3238-11ea-8f1b-8a209452e873.png">

**Comment by shidharthbammani11** [comment]
I ran the code but no display of the polygon
 Below is the code:

from PIL import Image, ImageDraw

img = Image.new("1", (128, 128))
coords = [(29.0, 74.0), (62.0, 57.0), (99.0, 54.0), (66.0, 71.0)]
drawer = ImageDraw.Draw(img)
drawer.polygon(coords,1,1)

**Comment by radarhere** [comment]
The way Pillow draws this polygon is by plotting on each row where each of the edges intersect, and then going through row by row and drawing horizontal lines. Here's an image to help illustrate.

<img width="582" alt="points" src="https://user-images.githubusercontent.com/3112309/150444451-50f41b88-c8d1-4e7c-8d0e-8adde8e7c3ff.png">

No point in any of the lines is out of place. The angles have just conspired to create your discontiguous image.

I have created PR #5980 to resolve this.
