### ISSUE TITLE
NameError: name 'hasattr' is not defined - in Image destructor

### ISSUE THREAD

**Issue by hiren1771** [python-pillow/Pillow#4349]
### What did you do?
I get this traceback:

```
"Traceback (most recent call last):
  File "/opt/venv/lib/python3.7/site-packages/PIL/Image.py", line 630, in \_\_del__
  File "/opt/venv/lib/python3.7/site-packages/PIL/Image.py", line 592, in \_\_exit__
NameError: name 'hasattr' is not defined
```

### What did you expect to happen?

I do not expect a traceback error here.

### What are your OS, Python and Pillow versions?

* OS: alpine linux 3.10
* Python: 3.7.5
* Pillow: 6.2.1

Using with apache2, django 1.11 and mod_wsgi.

It seems that using hasattr in a destructor can result in this issue. As seen from: https://github.com/Legrandin/pycryptodome/issues/39 which is the same issue faced in another python project, where they reworked destructor due to same traceback.

Pillow is doing the same here https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L546 in the destructor.

**Comment by radarhere** [comment]
While not exactly the solution to your problem, you may be interested to know that in Pillow 7.0.0, the use of `__del__` has been removed - https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#image-del

**Comment by radarhere** [comment]
Does using a context manager work? That would trigger the `__exit__` method by itself.

```python
with Image.open("hopper.png") as im:
    im.save("out.jpg")
```

If it does work, then you should just be able to upgrade to Pillow 7.0.0, and this issue is resolved.

**Comment by hiren1771** [comment]
Thanks for the info, will look to move to pillow 7. Appreciate the quick response, closing this issue then. Thanks.
