### ISSUE TITLE
GHA: PyPy3 tests failing on macOS 

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#4350]
### What did you do?

On GitHub Actions, test macOS-latest on PyPy3.

### What did you expect to happen?

Tests pass.

### What actually happened?

Tests fail:

```
Run .travis/test.sh
  .travis/test.sh
  shell: /bin/bash -e {0}
  env:
    pythonLocation: /Users/runner/hostedtoolcache/PyPy/3.6.9/x64/bin
============================= test session starts ==============================
platform darwin -- Python 2.7.17, pytest-4.6.9, py-1.8.1, pluggy-0.13.1 -- /usr/local/opt/python@2/bin/python2.7
cachedir: .pytest_cache
pytest_report_header failed: No module named PIL
rootdir: /Users/runner/runners/2.163.1/work/Pillow/Pillow, inifile: setup.cfg
plugins: cov-2.8.1
collecting ... collected 0 items / 1 errors

==================================== ERRORS ====================================
__________________ ERROR collecting Tests/test_000_sanity.py ___________________
ImportError while importing test module '/Users/runner/runners/2.163.1/work/Pillow/Pillow/Tests/test_000_sanity.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
Tests/test_000_sanity.py:1: in <module>
    import PIL
E   ImportError: No module named PIL
=========================== 1 error in 0.56 seconds ============================
##[error]Process completed with exit code 1.
```

### What are your OS, Python and Pillow versions?

* OS: `macOS-latest` 10.15.2
* Python: PyPy3
* Pillow: `master`

# Last pass

Two days ago: https://github.com/python-pillow/Pillow/runs/379447500

# First fail

Yesterday: https://github.com/python-pillow/Pillow/runs/380647169

**Comment by hugovk** [comment]
As the snippet above shows, there's some mixup between Python 2 and Python 3 executables.

Before, `python` was PyPy 3; now it's CPython 2 and `python3` is CPython 3.

Here's a diff of the last pass and first fail logs, and the "Build system information" step, which runs `python .github/workflows/system-info.py`:

![image](https://user-images.githubusercontent.com/1324225/72152967-3cc71a80-33b5-11ea-861e-34c864306065.png)

And further down the fail logs, we can see `pip install ...` installing for Python 2.

I'll report it to GitHub Actions.

**Comment by hugovk** [comment]
Reported: https://github.com/actions/setup-python/issues/54.

**Comment by hugovk** [comment]
> We have confirmed that it is an issue on our side. Thank you for the report!
PyPy 3.x is available via pypy and pypy3 but links to python and python3 are broken.
As a temporary solution, you can invoke PyPy as pypy or pypy3.
We are working on a fix now.

https://github.com/actions/virtual-environments/issues/249#issuecomment-573039667

**Comment by radarhere** [comment]
https://github.com/microsoft/azure-pipelines-image-generation/issues/1460#issuecomment-573558508

> We have a fix but it will be deployed with next image-rollout (Approximately, at the middle of this week).

**Comment by hugovk** [comment]
Now macOS/PyPy3 passes and "Build system information" looks good, 3.6.9 + PyPy 7.3.0:

```
Run python .github/workflows/system-info.py
Build system information

sys.version		 ['3.6.9 (1608da62bfc7, Dec 23 2019, 10:50:17)', '[PyPy 7.3.0 with GCC 4.2.1 Compatible Apple LLVM 10.0.0 (clang-1000.11.45.5)]']
os.name			 posix
sys.platform		 darwin
platform.system()	 Darwin
platform.machine()	 x86_64
platform.platform()	 Darwin-19.2.0-x86_64-i386-64bit
platform.version()	 Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64
platform.uname()	 uname_result(system='Darwin', node='Mac-1333.local', release='19.2.0', version='Darwin Kernel Version 19.2.0: Sat Nov  9 03:47:04 PST 2019; root:xnu-6153.61.1~20/RELEASE_X86_64', machine='x86_64', processor='i386')
platform.mac_ver()	 ('10.15.2', ('', '', ''), 'x86_64')
```

https://github.com/python-pillow/Pillow/runs/392723770
