### ISSUE TITLE
[Termux] ImportError with dlopen failed

### ISSUE THREAD

**Issue by LLIAJIYH** [python-pillow/Pillow#4355]
### What did you do?
Run [qrcode](https://github.com/h0nus/QRGen) to make a qrcode
### What did you expect to happen?
qrcode.py should be started
### What actually happened?
error
```
┌─[05:00:45]─────[Bayram]───[20]
|
└─[QRGen]────►python3 qrgen.py
WARNING: linker: _imaging.cpython-38.so: unused DT entry: type 0x6ffffef5 arg 0xd00
Traceback (most recent call last):
  File "qrgen.py", line 8, in <module>
    from PIL import Image
  File "/data/data/com.termux/files/usr/lib/python3.8/site-packages/PIL/Image.py", line 69, in <module>
    from . import _imaging as core
ImportError: dlopen failed: cannot locate symbol "modf" referenced by "_imaging.cpython-38.so"...
```
### What are your OS, Python and Pillow versions?

* OS: Android 5.1.1
* Python: 3.8
* Pillow: 7.0.0

**Comment by hugovk** [comment]
Do any of the suggestions at https://github.com/termux/termux-packages/issues/2722 help?

**Comment by LLIAJIYH** [comment]
yay, thanks a lot

this method helped me to solve the problem
```
rm -rf $HOME/.cache
pip uninstall pillow
LDFLAGS=" -lm" pip install pillow
```
did this commands step by step

**Comment by mdtausifiqbal** [comment]
Not working these steps in termux.

**Comment by hugovk** [comment]
@mdtausifiqbal Please open a new issue with details of what you've tried and the exact output.
