### ISSUE TITLE
Issue opening jpg from url

### ISSUE THREAD

**Issue by Jcook65** [python-pillow/Pillow#4359]
I have been trying to get PIL Image.open() to open an image from a url, this is the code I have been using:

```python
import urllib.request
from PIL import Image
import io

url = 'https://files.slack.com/files-pri/TBHLY2TNU-FSL2M7MR6/00000001_024.jpg'
with urllib.request.urlopen(url) as i:
	byteImg = io.BytesIO(i.read())
	image = Image.open(byteImg)
	image.save('out.jpg')
```

This throws an error:

> "cannot identify image file %r" % (filename if filename else fp)
> PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001936647B1C8>

However, I have found a similar situation in one of the posts on this github that uses the same code but a different url and it works fine:

```python
import urllib.request
from PIL import Image
import io

url = 'https://cdn.wccftech.com/wp-content/uploads/2017/11/windows-10-iphone-1480x897-86x60.png'
with urllib.request.urlopen(url) as i:
	byteImg = io.BytesIO(i.read())
	image = Image.open(byteImg)
	image.save('out.png')
```

The only differences I am seeing here is that one is a .png (also smaller in size) and the other is a .jpg. Is there something I am missing here? I am using Pillow v7.0 and Python 3.7.6

**Comment by radarhere** [comment]
If it works for a different image, then the code should be fine. Are you able to provide a copy of the JPG image?

**Comment by wiredfool** [comment]
I suspect that the download is the HTML of a login page, which doesn’t work well as a jpg image.

**Comment by Jcook65** [comment]
Yea you're totally right, the link redirects to a log in page. 🤷‍♂️. I'm closing the ticket. Thank you!
