### ISSUE TITLE
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)

### ISSUE THREAD

**Issue by AndyLuckert** [python-pillow/Pillow#4360]
[Denia_CORINE_CODE_18_reclass_NLCD92_reproj_ADAPTED_Europe_AEA.tif.zip](https://github.com/python-pillow/Pillow/files/4070890/Denia_CORINE_CODE_18_reclass_NLCD92_reproj_ADAPTED_Europe_AEA.tif.zip)

### What did you do?
I wanted to add the orientation TIFF-Tag with number 274 to my TIFF via the following code:

```python
image = PIL.Image.open(image_path)
image.tag[274] = 1
image.save(save_path, tiffinfo=image.tag, bigtiff=False)
```

### What did you expect to happen?
That the raster image (TIFF) is saved with updated TAGs.

### What actually happened?
When executing the save-command `image.save(save_path, tiffinfo=image.tag, bigtiff=False)`
it threw the following error:
`struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)`.

### Traceback of full-stack error output
```
Traceback (most recent call last):
  File "/home/andylu/Dokumente/Allgemeines_material/Sonstiges/Programming/Python/Scripts/General/GIS_n_image_manipulations.py", line 1131, in change_TIFF_tags_to_desired_values
    image.save(save_path, tiffinfo=image.tag, bigtiff=bigtiff)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/Image.py", line 2102, in save
    save_handler(self, fp, filename)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 1629, in _save
    offset = ifd.save(fp)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 865, in save
    result = self.tobytes(offset)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 808, in tobytes
    data = self._write_dispatch[typ](self, *values)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 644, in <lambda>
    b"".join(self._pack(fmt, value) for value in values)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 644, in <genexpr>
    b"".join(self._pack(fmt, value) for value in values)
  File "/home/andylu/anaconda3/lib/python3.7/site-packages/PIL/TiffImagePlugin.py", line 611, in _pack
    return struct.pack(self._endian + fmt, *values)
struct.error: ushort format requires 0 <= number <= (0x7fff * 2 + 1)
```

### What are your OS, Python and Pillow versions?

* OS: NAME="Ubuntu"
VERSION="18.04.3 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.3 LTS"
VERSION_ID="18.04"

* Python: Python 3.7.6 (default, Jan  8 2020, 19:59:22) 
[GCC 7.3.0] :: Anaconda, Inc. on linux

* Pillow: pillow                    7.0.0            py37hb39fc2d_0

**Comment by hugovk** [comment]
Please can you include the full error traceback?

**Comment by radarhere** [comment]
It would also be helpful if you could provide the image that you open at the start.

**Comment by AndyLuckert** [comment]
> It would also be helpful if you could provide the image that you open at the start.

I've just uploaded it within a .zip since I cannot upload .tif - files directly. See edited post.

**Comment by hugovk** [comment]
Thanks! And what's the full error output?

**Comment by radarhere** [comment]
@hugovk the original post has been edited

**Comment by AndyLuckert** [comment]
> Please can you include the full error traceback?

I've just included it into my original post, if this is what you were after:

```
import traceback

try:
    something_that_causes_an_error()
except:
    print(traceback.format_exc())

```

**Comment by radarhere** [comment]
The tag that is causing the problem here is StripByteCounts. [According to documentation, it can be a SHORT or LONG.](https://www.awaresystems.be/imaging/tiff/tifftags/stripbytecounts.html)

When [TiffImagePlugin reads the value](https://github.com/python-pillow/Pillow/blob/4634eafe3c695a014267eefdce830b4a825beed7/src/PIL/TiffImagePlugin.py#L736) from this image, it is reading it as a SHORT.

Then when [it is updated on saving](https://github.com/python-pillow/Pillow/blob/4634eafe3c695a014267eefdce830b4a825beed7/src/PIL/TiffImagePlugin.py#L1511), it is set to 5351198, not a SHORT, but a LONG. An error is then thrown because we'd established that this tag was a SHORT, and it's now being written with a LONG value.

I've created PR #4626 to resolve this.

**Comment by radarhere** [comment]
As a workaround, you could add in `image.tag.tagtype[279] = 4`,
```python
import PIL.Image
image_path = "Denia_CORINE_CODE_18_reclass_NLCD92_reproj_ADAPTED_Europe_AEA.tif"
save_path = "out.tif"

image = PIL.Image.open(image_path)
image.tag[274] = 1
image.tag.tagtype[279] = 4
image.save(save_path, tiffinfo=image.tag, bigtiff=False)
```

**Comment by AndyLuckert** [comment]
Alright, thanks for the workaround and the explanation!
