### ISSUE TITLE
Repeated calls to ImageFont.getsize() results in C/C++ error

### ISSUE THREAD

**Issue by evanlesmez** [python-pillow/Pillow#4362]
### What did you do?

I tried to work with the font.getsize method to dynamically draw text over an image.

### What did you expect to happen?

I expected the execution to work fine every time and be able to draw text using the size retrieved from getsize.

### What actually happened?

Execution crashes with C/C++ errors, breaking the entire python process this code is contained in.
Not bueno if you are running this inside a large application since you cannot catch these errors Pythonically.
The output itself is also variable. 
Examples I have seen:
```bash
corrupted size vs. prev_size
[1]    603629 abort (core dumped)

mremap_chunk(): invalid pointer
[1]    603807 abort (core dumped)

[1]    608639 segmentation fault (core dumped)
```
### What are your OS, Python and Pillow versions?

* OS: Fedora Linux 31
* Python: 3.7.6
* Pillow: 7.0.0

snag any font you want to work with from here https://www.fontsquirrel.com/fonts/list/popular 
```python
from PIL import ImageFont
import time

count = 0
while True:
    count +=1
    font_file = 'arial.ttf'
    font = ImageFont.truetype(font_file, 12)
    font_size = font.getsize("repeating font.getsize() breaks execution")
    time.sleep(.01)
    print(f'run {count}')
```

**Comment by hugovk** [comment]
Couldn't reproduce on macOS Mojave 10.14.6 / Python 3.8, got up to "run 211480" after more than an hour before I stopped it. Not tested Linux.

**Comment by evanlesmez** [comment]
Note I installed pillow inside a virtual env using `python -m venv env`. When I run pillow from OS, it works fine with version 6.1.2. Think there is a bug with the pypackage build versus the build that was distributed with Fedora OS.

**Comment by evanlesmez** [comment]
Solved by re installing with the 'build-ext' flag to build with extra dependencies https://pillow.readthedocs.io/en/stable/installation.html#building-on-linux
```bash
python -m pip uninstall pillow
python -m pip install --global-option="build_ext" --no-cache-dir
# no-cache-dir is just to ignore cached package, don't need it on first install
```
