### ISSUE TITLE
docker pillow memory leak

### ISSUE THREAD

**Issue by l1351868270** [python-pillow/Pillow#4364]
### What did you do?
I run codes in docker and physical machine。

### What did you expect to happen?
when i run codes in the docker, it is ok.

### What actually happened?
In physical machine it is ok, but in the docker appears memory leak. When I debug, I find that the error is caused by the file WebPImagePlugin.py:60

self._decoder = _webp.WebPAnimDecoder(self.fp.read())

### What are your OS, Python and Pillow versions?

* OS:   linux
* Python: docker pull python:3.7.4
* Pillow: 7.0.0 or 6.2.0
* Image
![ChsEeV4fB3yALzXIAABC7Nmhuw8028](https://user-images.githubusercontent.com/32282854/72596141-57196f00-3946-11ea-8eb5-c0d2e261ce23.jpg)

```python
from PIL import Image
from PIL import ImageFile

img_file = r"./ChsEeV4fB3yALzXIAABC7Nmhuw8028.jpg"

ImageFile.LOAD_TRUNCATED_IMAGES = True
while True:
    try:
        im = Image.open(img_file)
    except Exception as e:
        # print("err={}".format(e))
        pass
```

**Comment by radarhere** [comment]
You're talking about a WebP image leak, and the file you have attached is WebP, but the sample code mentions a JPG?

**Comment by homm** [comment]
You shouldn't use `Image.open(file_name)`, please use `Image.open(file_object)` instead or call `im.close()` manually. This is not a Pillow's leak, this is Python's leak. See #2019.

**Comment by homm** [comment]
Sorry, this shouldn't be related since the filename isn't changing during the loop.

**Comment by homm** [comment]
@radarhere this `.jpg` file is actually a webp image.

```
$ head ../imgs/72596141-57196f00-3946-11ea-8eb5-c0d2e261ce23.jpg -c 50
RIFFz?WEBPVP8 n?:?*h?>E?D??!???x8D????
```

**Comment by homm** [comment]
Memory leaks with speed about 500 megabytes on 29000 iterations which is ≈17kb/it, the same as image file size.

**Comment by l1351868270** [comment]
@homm I modify the WebPImagePlugin.py:43 like this "if _webp.HAVE_WEBPANIM:", thus delete the 
 "not". Now , it is ok!

**Comment by l1351868270** [comment]
@homn When i modify the WebPImagePlugin.py:43, there is other question. Do you has a plan to solve the memory leak question.

**Comment by radarhere** [comment]
While I don't encourage this as a solution, be aware that you can get that effect without modifying the Pillow source code.

```python
from PIL import _webp, Image
_webp.HAVE_WEBPANIM = False
im = Image.open("Tests/images/hopper.webp")
```

**Comment by l1351868270** [comment]
@homm thanks very much!  Just take your suggestions,  I modify my codes. Until now, it is ok!
