### ISSUE TITLE
Documentation Error: Default Spacing in ImageDraw.text()

### ISSUE THREAD

**Issue by HalfWhitt** [python-pillow/Pillow#4367]
I'm not 100% sure this is the right place for this, as it's not a bug in PIL but an error in the online documentation. The headings for [ImageDraw.text()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.text) and [ImageDraw.multiline_text()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.multiline_text) both list the default spacing value as 0. But the actual default value is 4, which matches the listed defaults for [ImageDraw.textsize()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.textsize) and [ImageDraw.multiline_textsize()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.multiline_textsize) and can be verified with the following code:

```python
img = Image.new('RGB', (200, 200), 'white')
draw = ImageDraw.Draw(img)
text = 'This is sample text.\nIt has a newline in it.'
draw.text((0,0), text, fill='black')
draw.text((0,0), text, fill='black', spacing=4)
img.show()
```

The two copies of the text overlap each other perfectly; if the default value were not four, the lower line would be offset from its previous copy.

**Comment by radarhere** [comment]
Thanks for reporting. This is the right place for this. The documentation is also a part of this repository.

I've created PR #4368 to resolve this.

**Comment by radarhere** [comment]
The PR has been merged. So while you won't see [the stable documentation](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.text) update until the next Pillow release on April 1, you can see the updated version in the [the latest documentation](https://pillow.readthedocs.io/en/latest/reference/ImageDraw.html#PIL.ImageDraw.PIL.ImageDraw.ImageDraw.text).

**Comment by HalfWhitt** [comment]
Awesome, thanks!
