### ISSUE TITLE
How to merge cropped images back to original image 

### ISSUE THREAD

**Issue by yasir2afaq** [python-pillow/Pillow#4374]
I have an image of size 10980x10980 and I cropped this image by using python script into 256x256 size. the script I used for cropping is :

```python
      from PIL import Image

      infile = 'Amritsar_T43SDR.tif'
      chopsize = 256

       img = Image.open(infile)
        width, height = img.size

         for x0 in range(0, width, chopsize):
              for y0 in range(0, height, chopsize):
              box = (x0, y0,
                    x0+chopsize if x0+chopsize <  width else  width - 1,
                    y0+chopsize if y0+chopsize < height else height - 1)
              print('%s %s' % (infile, box))
              img.crop(box).save('Train.%s.x%03d.y%03d.tif' % (infile.replace('.tif',''), x0, y0))
```

image is successfully cropped as per given dimension in 1855 images (the majority of image file size is 193K but some image of size 171Kb generated) 

now  I want to roll back the whole procedure i.e. using cropped images, merging all tiles back to the original image. we found a function rollback which is as follows

```python
    def roll(image, delta):
        x0, y0 = img.size

    delta = delta % xsize
    if delta == 0: return image

    part1 = image.crop((0, 0, delta, y0))
    part2 = image.crop((delta, 0, x0, y0))
    image.paste(part1, (x0-delta, 0, x0, y0))
    image.paste(part2, (0, 0, x0-delta, y0))

    return image
```

It doesn't catch the original dimensions
alternatively, we used ImageMajik program and issued the command as
`montage -mode concatenate -tile 43x85 Train*.tif new_amritsar.tif`
resultantly it merge the images but not in real order

Please suggest me the solution

regards
Yasir
![1](https://user-images.githubusercontent.com/32522237/72720544-38161980-3ba0-11ea-975d-3710e0064a9c.png)

![2](https://user-images.githubusercontent.com/32522237/72720567-45330880-3ba0-11ea-8d6e-c4f6bf72d4a5.png)

**Comment by radarhere** [comment]
Here is my idea.

```python
import os
from PIL import Image

def get_offsets(file):
	return [int(dimension[1:]) for dimension in file.split('.')[2:4]]

# Get the list of files
files = [file for file in sorted(os.listdir('.')) if file.startswith('Train.')]

if not files:
	print("No input files found")
else:
	lastFile = files[-1]
	outfile = lastFile[len('Train.'):].split('.')[0]+'.tif'

	# The width and height of the original image can be determined from the last tile
	with Image.open(lastFile) as lastIm:
		w, h = lastIm.size
	x, y = get_offsets(lastFile)
	w += x
	h += y
	
	# Create the new image
	im_out = Image.new(lastIm.mode, (w, h))
	for file in files:
		x, y = get_offsets(file)
		
		# Paste each tile
		with Image.open(file) as im:
			im_out.paste(im, (x, y))
	im_out.save(outfile)
```

**Comment by yasir2afaq** [comment]
Thanks, @radarhere for your response

I tried your code, It runs successfully but doesn't generate the output file. I am hoping a new output file in which all cropped images were restacked in the same manner as they were cropped. Our objective is to standardize a procedure and to ensure the cropped images were overlapping exactly to the original image.

I need little clarification form this code line
`outfile = lastFile[len('Train.'):].split('.')[0]+'.tif'`

Does this generate the output file with the name of the last file name, if it did so, then I checked, there's no such file, even I listed files sorted with size? 

Please help regarding this issue
Yasir

**Comment by radarhere** [comment]
I am surprised when you say that my script runs successfully with no output. Really, it should either
a) run with an error
b) print "No input files found"
or c) save an output image

I have an idea for the source of the confusion though - I wrote the script to save back to 'Amritsar_T43SDR.tif'. So I think my script ran correctly, saving the image on top of the original image, meaning that you didn't notice anything happening.

I have edited my code to instead save to 'Amritsar_T43SDR_new.tif' so that there will be an obvious new file. I have also added some more print statements to be clearer.

Please run [my updated code.](https://github.com/python-pillow/Pillow/issues/4374#issuecomment-576236193)

---

As for `outfile = lastFile[len('Train.'):].split('.')[0]+'.tif'` -

```python
lastFile = 'Train.Amritsar_T43SDR.x000.y1536.tif'
# First, remove 'Train.' from the start
print(lastFile[len('Train.'):])  # Amritsar_T43SDR.x000.y1536.tif
# Then, get the content before the next period
print(lastFile[len('Train.'):].split('.')[0])  # Amritsar_T43SDR
# Then add '.tif'
print(lastFile[len('Train.'):].split('.')[0]+'.tif')  # Amritsar_T43SDR.tif
```

**Comment by yasir2afaq** [comment]
@radarhere  You are a hero.... your updated code and description of an output statement cleared my doubts. The confusion was I kept the original file in the cropped image file folder. Now everything is sorted. Thanks for your prompt help ... Kudos for your efforts

**Comment by saurabhsharma495** [comment]
img_size = [384,216]
def grouped(iterable, n):
    return zip(*[iter(iterable)]*n)
#images ==> list of images 
for x,y,a,b,c in grouped(images, 5):
    temp = []
    temp.append([x,y,a,b,c])
    print(temp[0])
    print(len(temp[0]))
    for lsingle_img in temp[0]:
        # print(lsingle_img)
        print("x_y_offset: ", (x_offset, y_offset))
        new_im.paste(lsingle_img, (x_offset, y_offset))
        x_offset += img_size[0]
    temp = []
    x_offset = 0
    y_offset += img_size[1]
new_im.save('test.jpg')
