### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by L3o-pold** [python-pillow/Pillow#4392]
Pillow seems to not be able to load `.ia` file using Pillow 7.0

```
  File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)
PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='/tmp/images/9c45e6aa-4ffa-42d3-a0db-fe7e109a959awoman.ai'>
```

**Comment by hugovk** [comment]
Pillow doesn't support AI format. Here's the list of supported formats:

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html

**Comment by loretoparisi** [comment]
@hugovk I'm getting this error on a `PNG` image, that should be supported right?

**Comment by loretoparisi** [comment]
@hugovk ah ok, the error happens for a `PNG` image with size `0 bytes`!

**Comment by sumeysh** [comment]
Getting"UnidentifiedImageError"  error while executing the following code
Using Pillow 7.1.2

import requests
from PIL import Image
url = 'https://images.homedepot-static.com/productImages/007164ea-d47e-4f66-8d8c-fd9f621984a2/svn/architectural-mailboxes-house-letters-numbers-3585b-5-64_1000.jpg'
response = requests.get(url, stream = True)
img = Image.open(response.raw)
======================================
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-5-2d696589590a> in <module>()
      1 import matplotlib.pyplot as plt
----> 2 img = Image.open(response.raw)
      3 #plt.imshow(img)

/usr/local/lib/python3.6/dist-packages/PIL/Image.py in open(fp, mode)
   2894         warnings.warn(message)
   2895     raise UnidentifiedImageError(
-> 2896         "cannot identify image file %r" % (filename if filename else fp)
   2897     )
   2898 

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f93f30c96d0>

**Comment by radarhere** [comment]
@sumeysh I'm unable to replicate your problem. Could you make check that you're actually receiving a valid image from requests? I would suggest running this code and taking a look at out.jpg

```python
import requests
url = 'https://images.homedepot-static.com/productImages/007164ea-d47e-4f66-8d8c-fd9f621984a2/svn/architectural-mailboxes-house-letters-numbers-3585b-5-64_1000.jpg'
response = requests.get(url, stream = True)
with open('out.jpg', 'wb') as f:
	f.write(response.content)
```

**Comment by anis-agwan** [comment]
Getting UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x63a807fb0>
while executing this code
''
classifier.fit_generator(training_set,
steps_per_epoch = 8000,
epochs = 25,
validation_data = test_set,
validation_steps = 2000)
'''

![Screenshot 2020-06-07 at 9 33 20 PM](https://user-images.githubusercontent.com/59297399/83974082-3effb780-a908-11ea-9fde-41ba86b06ed1.png)

**Comment by hugovk** [comment]
@anis-agwan Please open a new issue, thank you.

**Comment by krovel** [comment]
how to rectify the error @anis-agwan

**Comment by radarhere** [comment]
@krovel the error from @anis-agwan is currently under discussion in #4678. However, if are not having a problem with `keras_preprocessing` and have a just generic `UnidentifiedImageError`, please open a new issue, supplying the image and a short self-contained example of the code you are using.
