### ISSUE TITLE
Bicubic resize of an uint16 image

### ISSUE THREAD

**Issue by clkotnik** [python-pillow/Pillow#4402]
### What did you do?
I moved an existing Python app from a machine with Pillow 6.2.1 to a new machine which had Pillow 7.0.0 installed.  The app failed to resize a PIL.Image.

### What did you expect to happen?
I expected it to work as before

### What actually happened?
resize threw an exception ValueError: image has wrong mode

### What are your OS, Python and Pillow versions?

* OS: ubuntu 18.04
* Python: 3.6.9
* Pillow: 7.0.0

```python
import numpy as np
from PIL import Image

imgdata = np.array( [[484, 451, 481, 465, 488, 442],
 [823, 897, 971, 920, 855, 908],
 [758, 919, 854, 920, 850, 854],
 [840, 873, 950, 893, 872, 881],
 [937, 940, 835, 879, 895, 774],
 [841, 914, 867, 886, 922, 952]]).astype(np.uint16)

pimg = Image.fromarray(imgdata)
scale_factor = 0.5
size = tuple((np.array(pimg.size) * scale_factor).astype(int))
newim = pimg.resize(size)
---------------------------------------------------------------------------
ValueError                                Traceback (most recent call last)
<ipython-input-1-5c0c4827f11b> in <module>
     12 scale_factor = 0.5
     13 size = tuple((np.array(pimg.size) * scale_factor).astype(int))
---> 14 newim = pimg.resize(size)

e:\program files\python37\lib\site-packages\PIL\Image.py in resize(self, size, resample, box, reducing_gap)
   1871                 )
   1872 
-> 1873         return self._new(self.im.resize(size, resample, box))
   1874 
   1875     def reduce(self, factor, box=None):

ValueError: image has wrong mode


```

**Comment by radarhere** [comment]
#4255 changed the default `resampling` argument for the `resize` method to `Image.BICUBIC`.

Adjusting the last line of your code to `newim = pimg.resize(size, resample=Image.NEAREST)`, I find that the code runs again without exception.

**Comment by clkotnik** [comment]
Yes, I can reproduce that

**Comment by din14970** [comment]
Same issue, bicubic and bilinear used to work in earlier PIL versions on 16 bit images; no longer.

**Comment by radarhere** [comment]
@din14970 this issue is about the default resampling of resizing being different. If you find that BICUBIC and BILINEAR used to work and no longer do, please create a new issue with more detail (which was the last Pillow version to work for you?), a self-contained script and images.

**Comment by OrielBanne** [comment]
yup. I have the same issue. However, I need to use bicubic, nearest is not good enough. is there a solution?

**Comment by radarhere** [comment]
@OrielBanne at the moment, all I can suggest is converting your image to another mode first.

**Comment by radarhere** [comment]
I've created #5411 to allow the defaults to work again.

@OrielBanne could you provide an example of your situation? When you say you have the 'same issue', I'm not certain if you're dealing with I;16 image or something else.

**Comment by radarhere** [comment]
#5411 has been merged. So with the next release of Pillow, scheduled for July 1, @clkotnik's problem should be resolved. @OrielBanne's problem is not.

**Comment by radarhere** [comment]
Closing. #5411 fixed the default behaviour, and the other request doesn't involve a specific image.
