### ISSUE TITLE
Unable to draw special Japanese font

### ISSUE THREAD

**Issue by lunasdejavu** [python-pillow/Pillow#4403]
### What did you do?
I am trying to draw Japanese words from this [font](http://expwyandstamps.web.fc2.com/sozai/FZcarnumberJA-OTF_ver10.otf)
```python
self.fontTop = ImageFont.truetype(fontCh_file, 60, 0)
val = u'\u2FA6'
draw = ImageDraw.Draw(img)
draw.text(( 0, 0), val, color, font=self.fontTopRight)
```
then it is still blank
### What did you expect to happen?
it should be something like 金
### What actually happened?
blank
### What are your OS, Python and Pillow versions?

* OS: ubuntu 16.04
* Python: 3.6
* Pillow: 5.2

**Comment by radarhere** [comment]
I'm able to perform this task without a problem using Pillow 5.2 on macOS.

Looking at your code, you set `self.fontTop`, but later use `self.fontTopRight`. Since this isn't a self-contained example, I'm wondering if the problem is somewhere else in the code that you're running.

Would you be able to run this code, and see if it works?

```python
from PIL import Image, ImageDraw, ImageFont
img = Image.new("RGB", (100, 100), "#fff")
fontCh_file = 'FZcarnumberJA-OTF_ver10.otf'
fontTop = ImageFont.truetype(fontCh_file, 60, 0)
val = u'\u2FA6'
draw = ImageDraw.Draw(img)
color = '#000'
draw.text((0, 0), val, color, font=fontTop)
img.save("out.png")
```

**Comment by lunasdejavu** [comment]
> I'm able to perform this task without a problem using Pillow 5.2 on macOS.
> 
> Looking at your code, you set `self.fontTop`, but later use `self.fontTopRight`. Since this isn't a self-contained example, I'm wondering if the problem is somewhere else in the code that you're running.
> 
> Would you be able to run this code, and see if it works?
> 
> ```python
> from PIL import Image, ImageDraw, ImageFont
> img = Image.new("RGB", (100, 100), "#fff")
> fontCh_file = 'FZcarnumberJA-OTF_ver10.otf'
> fontTop = ImageFont.truetype(fontCh_file, 60, 0)
> val = u'\u2FA6'
> draw = ImageDraw.Draw(img)
> color = '#000'
> draw.text((0, 0), val, color, font=fontTop)
> img.save("out.png")
> ```
thanks it works!  let me check the other part first
