### ISSUE TITLE
Wrong frame snapshot in GIF animated file

### ISSUE THREAD

**Issue by imfantuan** [python-pillow/Pillow#4418]
### What did you do?

```python
im.open(gif.stream)
im.convert("RGB/RGBA/P", dither=None)
im.seek(frame_number)
im.save(outfile, fmt)
```

### What did you expect to happen?
orgi_GIF: http://gif.imgix.net/imgix-logo-ani.gif
Right_Frame_44_in_Imgix.com: http://gif.imgix.net/imgix-logo-ani.gif?frame=44
### What actually happened?
Wrong_Frame_44_in_my_system: https://files.soft.org/?url=/imgix.gif&frame=44
### What are your OS, Python and Pillow versions?

* OS: Centos 7 & 8
* Python: 3.6.8
* Pillow: 7.0.0

**Comment by radarhere** [comment]
It's worth noting that `im.convert("RGB", dither=None)` doesn't change the image. It returns a new image.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert
> **Image.convert**(mode=None, matrix=None, dither=None, palette=0, colors=256)
> Returns a converted copy of this image.

Also, while I presume you somehow had this working, `im.open(gif.stream)` is not correct. It should be `Image.open(gif.stream)`.

I've created #5386 to resolve this.
