### ISSUE TITLE
Symbols aren't supported in text

### ISSUE THREAD

**Issue by HTG-YT** [python-pillow/Pillow#4426]
* OS: Windows 10 Home
* Python: 3.8.1
* Pillow: 7.0.0

```python
draw_rank_card.text((200, 140), f"#{user.discriminator}", fill="black", font=rank_card_font3)
```

Expected Result: The output should be **#{user.discriminator}**.

Returned Result:
![card](https://user-images.githubusercontent.com/39023054/74653353-f7231c00-51c2-11ea-88dc-453253b4f140.png)

**Comment by nulano** [comment]
You seem to be using an f-string. Did you mean to use a regular string? This looks like standard Python behaviour.

**Comment by HTG-YT** [comment]
For me, f-strings and normal strings both have the bug, symbols aren't supported.

**Comment by hugovk** [comment]
`draw_rank_card.text` isn't part of Pillow. Please include a self-contained, copy-pastable example that generates the issue. Be concise with code posted.

Guidelines on how to provide a good bug report:

* https://stackoverflow.com/help/mcve

Bug reports which follow these guidelines are easier to diagnose, and are often handled much more quickly.

**Comment by HTG-YT** [comment]
Following is the original:
```python
from PIL import ImageDraw

draw_rank_card = ImageDraw.Draw(rank_card)
draw_rank_card.text((50, 125), f"{user.name} # {user.discriminator}", fill="white", font=rank_card_font)
```
@hugovk does that help?

**Comment by hugovk** [comment]
Better! What's `rank_card`?

**Comment by HTG-YT** [comment]
```python
rank_card = Image.new('RGB', (934, 282), color='gray')
```

**Comment by hugovk** [comment]
Thanks! Putting those together:

```python
from PIL import Image, ImageDraw

rank_card = Image.new('RGB', (934, 282), color='gray')
draw_rank_card = ImageDraw.Draw(rank_card)
draw_rank_card.text((50, 125), f"{user.name} # {user.discriminator}", fill="white", font=rank_card_font)
```

What is `user.name` and `user.discriminator`?

**Comment by HTG-YT** [comment]
I'll put my full code here(basically I am using discord.py and PIL together...:
```python
    async def rank(self, ctx, member: discord.Member = None):
        rank_card = Image.new('RGB', (934, 282), color=0xafb6b8)

        rank_card_font = ImageFont.truetype('Font/01_APompadourTextSample.ttf', 50)

        rank_card_font2 = ImageFont.truetype('Font/02_APompadourTextSample.ttf', 100)

        rank_card_font3 = ImageFont.truetype('Font/03_APompadourTextSample.ttf', 30)

        draw_rank_card = ImageDraw.Draw(rank_card)

        if member is None:
            try:
                user_guild: discord.Guild = ctx.message.guild

                user: discord.User = ctx.message.author

                with open(f'levels/{user_guild.id}_levels.yaml') as accessor:
                    data = yaml.safe_load(accessor)

                    print(data)

                current_xp = data[user.id]['xp']

                level_end_xp = 5 * (int(data[user.id]['level']) ** 2) + 50 * int(data[user.id]['level']) + 100

                draw_rank_card.text((450, 50), "Rank", fill="white", font=rank_card_font)
                draw_rank_card.text((575, 14), "N", fill="white", font=rank_card_font2)
                draw_rank_card.text((675, 50), "Level", fill="blue", font=rank_card_font)
                draw_rank_card.text((810, 14), str(data[user.id]['level']), fill="blue", font=rank_card_font2)
                draw_rank_card.text((50, 125), f"{user.name} # {user.discriminator}", fill="white", font=rank_card_font)
                draw_rank_card.text((700, 140), f"{current_xp}", fill="white", font=rank_card_font3)
                draw_rank_card.text((750, 140), f" / {level_end_xp} XP", fill=0x333434, font=rank_card_font3)

                rank_card.save('card.png')

                await ctx.send(file=discord.File('card.png'))
```

**Comment by hugovk** [comment]
We'd rather something we can copy and paste with no other dependencies, and it doesn't it tell us what `user.name` and `user.discriminator` are, but with Pillow 7.0.0 and Python 3.8.1 on macOS and this:

```python
from PIL import Image, ImageDraw, ImageFont


rank_card_font = ImageFont.truetype("path/to/a/font.ttf", 50)


user_name = "Bob"
user_discriminator = 123

rank_card = Image.new("RGB", (934, 282), color="gray")
draw_rank_card = ImageDraw.Draw(rank_card)
draw_rank_card.text(
    (50, 125), f"{user_name} # {user_discriminator}", fill="white", font=rank_card_font
)

rank_card.show()

```

I get:

![image](https://user-images.githubusercontent.com/1324225/74656901-c4aff980-5197-11ea-9e1c-46654253e18c.png)

And removing the f-string:

```diff
-    (50, 125), f"{user_name} # {user_discriminator}", fill="white", )
+    (50, 125), "{user_name} # {user_discriminator}", fill="white", )
```

I get:

![image](https://user-images.githubusercontent.com/1324225/74656993-fd4fd300-5197-11ea-909e-82d7ff913b42.png)

Is that what you're after?

**Comment by HTG-YT** [comment]
Yeah so that means I cannot use f-string?

**Comment by HTG-YT** [comment]
But even though with a normal string, the symbol is still missing.

**Comment by HTG-YT** [comment]
Is that any kind of compatibility issues or...?

**Comment by hugovk** [comment]
> Yeah so that means I cannot use f-string?

If you want to print `{` brackets using f-strings, you can do it like this:

```python
Python 3.8.1 (v3.8.1:1b293b6006, Dec 18 2019, 14:08:53)
[Clang 6.0 (clang-600.0.57)] on darwin
>>> foo = 123
>>> "{foo}"
'{foo}'
>>> f"{foo}"
'123'
>>> foo = 123
>>> bar = 456
>>> "{foo} {bar}"
'{foo} {bar}'
>>> f"{foo} {bar}"
'123 456'
>>> f"{{foo}} {bar}"
'{foo} 456'
>>>
```


> But even though with a normal string, the symbol is still missing.
> Is that any kind of compatibility issues or...?

I don't have a Windows machine to test, but can you try this foo/bar code and paste the output?

**Comment by HTG-YT** [comment]
Will try it tomorrow. Thanks

**Comment by HTG-YT** [comment]
![image](https://user-images.githubusercontent.com/39023054/74704316-eae2a180-524a-11ea-9c12-ecac0f97570d.png)

**Comment by HTG-YT** [comment]
That is my output

**Comment by HTG-YT** [comment]
Testing it today, the symbols didn't appear

**Comment by HTG-YT** [comment]
Now I am facing another problem: Chinese characters are NOT supported.
![image](https://user-images.githubusercontent.com/39023054/74713499-aca5ac00-5263-11ea-9997-e8c84c069bc3.png)

**Comment by HTG-YT** [comment]
@hugovk any solution to that?

**Comment by radarhere** [comment]
@HTG-YT it's still unclear what your situation is. Could we please have some self-contained code to run to demonstrate the problem?

Pillow can write Chinese characters. Using a situation from #3125, the font file https://github.com/micmro/Stylify-Me/raw/master/.fonts/SimSun.ttf can be used like so -

```python
from PIL import Image, ImageDraw, ImageFont
font = ImageFont.truetype('SimSun.ttf', 32)
im = Image.new('RGBA', (100, 100), (0, 0, 0, 0))
draw = ImageDraw.Draw(im)
draw.text((0, 0), '我和你', 'black', font, direction='ttb')
im.save('out.png')
```

**Comment by nulano** [comment]
@HTG-YT Could it be that your font doesn't contain a glyph for the given characters?
I think your font is available here: https://www.fontspace.com/justlikethistrain/a-pompadour-sample If I type "Bob # 123" into the preview box, I don't see the "#" symbol:
![image](https://user-images.githubusercontent.com/3819630/74833732-f4830c80-5311-11ea-9cd6-d981829a2d36.png)
I expect that Chinese characters are also not supported by this font.

**Comment by radarhere** [comment]
Thanks @nulano for figuring this one out
