### ISSUE TITLE
Can't produce a Quality 0 JPEG

### ISSUE THREAD

**Issue by Queuecumber** [python-pillow/Pillow#4439]
### What did you do?

```
im.save(output_path / i.with_suffix('.jpg').name, quality=0)
```

### What did you expect to happen?

A JPEG with libjpeg quantization equivalent to zero quality to be output.

### What actually happened?

A JPEG with libjpeg quantization equivalent to quality 75 was output

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.5
* Pillow: 

###  Comments

I do research in image compression and as part of that research I wanted to produce some quality 0 JPEG files, the quantization matrix for that should filled with 255, dumping the resulting JPEGs quantization tables with `djpeg` I see that they are quality 75, and from the source code it looks like `quality=0` indicates to use the defaulty quality which is 75. 

Quality zero is a completely valid quality for libjpeg, but it doesn't work in Pillow. I'm not sure how many people care about quality 0 JPEGs so it might not be worth fixing but I still figured I'd leave this here.

**Comment by radarhere** [comment]
I've created PR #4440 to resolve this.
