### ISSUE TITLE
Converting Pillow .tiff image to numpy uint8 produces TypeError on Windows 10

### ISSUE THREAD

**Issue by mvanlierBCG** [python-pillow/Pillow#4447]
### What did you do?
Loading a .tiff image:
```python
img = Image.open(img_name)
```

Convert the loaded image to a NumPy array:
```python
image_array = np.array(img, dtype='uint8')
```

### What did you expect to happen?
That I am able to covert the loaded image to a NumPy array.
In OS: Ubuntu 18.04.5 the environment, same version names don't throw an error and it works.

### What actually happened?
TypeError:
`int() argument must be a string, a bytes-like object or a number, not 'TiffImageFile'`

### What are your OS, Python and Pillow versions?

* OS: Windows 10 
* Python: 3.7
* Pillow: 7.0.0

```python
from PIL import Image
import numpy as np
img = Image.open(img_name)
image_array = np.array(img, dtype='uint8')
```

Tiff image
[test_tiff.zip](https://github.com/python-pillow/Pillow/files/4245244/test_tiff.zip)

**Comment by cgohlke** [comment]
Cannot reproduce:
```
Python 3.7.6 (tags/v3.7.6:43364a7ae0, Dec 19 2019, 00:42:30) [MSC v.1916 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> import numpy as np
>>> img = Image.open('test_tiff.tiff')
>>> image_array = np.array(img, dtype='uint8')
>>> image_array.shape
(1028, 2448, 3)
>>> np.__version__
'1.16.6'
```

**Comment by kmilos** [comment]
This is a compressed TIFF file, and I suspect, the same problem as https://github.com/python-pillow/Pillow/issues/4237

**Comment by radarhere** [comment]
Could we get a complete traceback for the error?

Could you check if your Windows and Ubuntu systems are using different versions of libtiff? That could also be helpful.
```
>>> from PIL import Image
>>> Image.core.libtiff_version
'LIBTIFF, Version 4.1.0\nCopyright (c) 1988-1996 Sam Leffler\nCopyright (c) 1991-1996 Silicon Graphics, Inc.'
>>> 
```

**Comment by radarhere** [comment]
I'm not able to reproduce this on our GitHub Actions or AppVeyor jobs, so closing due to lack of response.

**Comment by zhangsan5213** [comment]
I just got the same thing on conda 4.9.2 python 3.7
