### ISSUE TITLE
PIL cannot read JPEG comment

### ISSUE THREAD

**Issue by ganego** [python-pillow/Pillow#4450]
### What did you do?
I want PIL to read the JPEG comment (marker: 0xFF 0xFE).  
  
I took an image with an attached JPEG comment - verified with exiftools & IrfanView to exist.

```python
from PIL import Image, JpegImagePlugin
pic = Image.open(<path_to_pic_with_JPEG_comment>)
print(pic.info)
```

### What did you expect to happen?
Show the JPEG comment in the dict.

### What actually happened?
> {'jfif': 257, 'jfif_version': (1, 1), 'dpi': (96, 96), 'jfif_unit': 1, 'jfif_density': (96, 96), 'exif': b'...'}

### What are your OS, Python and Pillow versions?

* OS: W7x64
* Python: Python 3.8.1 x64
* Pillow: Pillow           7.0.0

I cannot attach an image via github ("Something went really wrong, ..."), so here is the file (5.61 KiB) (I downloaded it and verified it's byte-identical to the uploaded one): [![jpeg-comment-test.jpg](https://i.postimg.cc/nrz1xV1r/jpeg-comment-test.jpg)](https://postimg.cc/BLrFc0kf)

**Comment by kkopachev** [comment]
It's not exposed under `info` right now, but could be easily added in https://github.com/python-pillow/Pillow/blob/master/src/PIL/JpegImagePlugin.py#L180

**Comment by radarhere** [comment]
Yes, for the moment, you can access it through
```python
from PIL import Image
im = Image.open("comment.jpg")
print(im.app["COM"])  # b'JPEG-COMMENT-TEST\x00'
```

**Comment by radarhere** [comment]
I've created PR #4455 to resolve this.

**Comment by ganego** [comment]
Thank you both.
