### ISSUE TITLE
[ bug ] getbbox()

### ISSUE THREAD

**Issue by chiboreache** [python-pillow/Pillow#4453]
Simply won't crop exactly that image, meanwhile with others works fine.

When i move image slightly to right in GIMP and save - it is works again, plain resaving with gimp png defaults - does not helps.

* OS: Arch Linux Linux 5.4.22-1-lts
* Python: 3.8.1
* Pillow: community/python-pillow 6.2.1-1

```python
	from PIL import Image
    png_path = './22-108-20179696.png'
    im = Image.open(png_path)
    im = im.crop(im.getbbox())
    im.save('./test.png')

```

![22-108-20179696](https://user-images.githubusercontent.com/16459251/75441270-68569200-596e-11ea-87f1-748eff0f9f23.png)

**Comment by radarhere** [comment]
Testing, I find that it is trimming black transparent pixels, while you have white transparent pixels - that may sound strange, but yes, there is a difference.

I've created PR #4454 to resolve this.

In the meantime, here is code to change black transparent pixels into white transparent pixels before cropping, in case you are interested -

```python
from PIL import Image
png_path = './22-108-20179696.png'
im = Image.open(png_path)

px = im.load()
for x in range(0, im.width):
	for y in range(0, im.height):
		if px[x, y] == (255, 255, 255, 0):
			px[x, y] = (0, 0, 0, 0)

im = im.crop(im.getbbox())
im.save('./test.png')
```
