### ISSUE TITLE
[PyPI] Notice: Deprecation of underused file types/extensions

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4469]
FYI

---

Hello,

We're emailing because you're listed as a maintainer or owner for a package that has uploaded a legacy file type to PyPI in the past year:

* Project: Pillow, package type: bdist_wininst

Following PEP 527, it will soon not be possible to upload legacy file types.

https://www.python.org/dev/peps/pep-0527/

This restriction will apply to new uploads after 30 days from today (2020-04-12). Existing uploads will remain on PyPI, but soon new ones cannot be uploaded.

See PEP 527 for suggestions of replacement file types, and if you have any questions, please comment on the tracking issue for this deprecation:

https://github.com/pypa/warehouse/issues/6792

Thank you,
The PyPI Administrators

**Comment by hugovk** [comment]
Thanks, was just about to post about this (I actually drafted the email: https://github.com/pypa/warehouse/issues/6792#issuecomment-581506685 :)

We're all good, we already dropped bdist_wininst in 6.2.0 (1 Oct 2019) and provide wheels instead.

* https://pillow.readthedocs.io/en/stable/releasenotes/6.2.0.html#removed-bdist-wininst-exe-installers
* https://github.com/python-pillow/Pillow/pull/4029
