### ISSUE TITLE
Pillow fails to load PNG file

### ISSUE THREAD

**Issue by MiikaH** [python-pillow/Pillow#4472]
I noticed that Pillow doesn't seem to be able to load certain types of PNG files. It fails with "cannot parse this image" error.

The problem is present at least in all Pillow versions between 5.4.1 - 7.0.0. I haven't tested any older ones.

Bug seems to happen with "Normal" images on this web page: https://www.cgbookcase.com/textures/small-tiles-01

Here is a direct mirror to an image file for permanent reference: https://miikah.fi/other/Small_tiles_01_1K_Normal.png

The PNG file in question seems to open fine in any other image viewer, editor, web browsers or any other software.

**Comment by radarhere** [comment]
The image is failing because of `SyntaxError: broken PNG file (bad header checksum in b'iCCP')`. This check is skipped if you tell Pillow to load truncated images.

```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.open("Small_tiles_01_1K_Normal.png")
```

**Comment by MiikaH** [comment]
Thanks, that indeed gets rid of the error. 👍
