### ISSUE TITLE
Unknown pixel mode in TIFF

### ISSUE THREAD

**Issue by bmgraff** [python-pillow/Pillow#4480]
I have a TIFF file that I'm trying to convert, but opening the file causes the "cannot identify image file" error. Digging in a little deeper, it seems something about the TIFF is not supported, as the format key is not found in the OPEN_INFO structure in TiffImagePlugin.py. I'm not super familiar with the TIFF format, so I'm not certain how to better describe the issue. The file can be found at https://catalog.belden.com/prodimgs/AllAssets-approved/EN/92/79/TIFF_179279.tif (10 MB)

Could this mode be supported? I don't know if this should be considered a bug or an enhancement.

**Comment by radarhere** [comment]
Hi. So, TiffImagePlugin is producing a `KeyError: (b'MM', 5, (1,), 1, (8, 8, 8, 8, 8), (1,))`. This was also reported in https://github.com/python-pillow/Pillow/issues/3989#issuecomment-585747707.

In other words, your image is CMYK with alpha, which Pillow doesn't support yet. So happy to help interpret your problem, but yes, this feature request already exists.

**Comment by bmgraff** [comment]
Thanks, @radarhere . I appreciate the response and understanding of the situation.
