### ISSUE TITLE
Re-enable Zenodo for citable releases

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#4490]
In https://github.com/python-pillow/Pillow/issues/1322 we enabled Zenodo to create DOIs for Pillow releases, so it can be citable. And it's worked! We have some [citations](https://zenodo.org/record/44297#.Xn-z5dP7QWo)!

![image](https://user-images.githubusercontent.com/1324225/77833256-a1884a80-7144-11ea-9a91-71e0c904ebf7.png)

However, at https://doi.org/10.5281/zenodo.596518, we can see Pillow 3.0.0 and 3.1.0, but nothing newer.

@aclark4life Please could you check the settings? I don't have permission.

For example, at https://zenodo.org/account/settings/github/repository/hugovk/Pillow I can see:

![image](https://user-images.githubusercontent.com/1324225/77833240-86b5d600-7144-11ea-8a7f-65b9ba279d11.png)

How does https://zenodo.org/account/settings/github/repository/python-pillow/Pillow look?

General guide: https://guides.github.com/activities/citable-code/

**Comment by aclark4life** [comment]
@hugovk Any better now?

**Comment by hugovk** [comment]
I won't be able to see until we make the release next week. Is the switch now flipped?

**Comment by aclark4life** [comment]
@hugovk Copy that
<img width="1240" alt="Screen Shot 2020-03-28 at 5 50 19 PM" src="https://user-images.githubusercontent.com/72164/77834660-a0432780-711c-11ea-87f3-6809606c1f4c.png">

**Comment by hugovk** [comment]
Thanks for the screenshot. Hmm, well at least it's been trying to do it for each release... I sent this to https://zenodo.org/support:

> Hello,
> 
> We enabled Zenodo for the https://github.com/python-pillow/Pillow/ repository in 2015 (https://github.com/python-pillow/Pillow/issues/1322), but it only created a DOI for two quarterly releases:
> 
> https://doi.org/10.5281/zenodo.596518
> 
> Looking at https://zenodo.org/account/settings/github/repository/python-pillow/Pillow, it shows it has been trying for each release, but says "Failed".
> 
> Here's a screenshot in our tracking issue: https://github.com/python-pillow/Pillow/issues/4490#issuecomment-605524232
> 
> Please could you let us know if there's anything else extra we need to get it working?
> 
> Thank you!
> 
> Hugo

**Comment by hugovk** [comment]
Reply from Zenodo:

> Dear Hugo,
> 
> I apologize for this inconvenience.
> I have now manually published the missing releases, as a notice, we found a duplicate event in our system for the release tagged as '6.0.0', please let us know if this was not from your side.
> We plan on improving this feature since we are, sometimes, experiencing these seemingly random failures which can be frustrating for our users.
> 
> In the meantime, if you encounter any further issues or failed releases don't hesitate to contact us again.
> 
> Best regards,
> George


https://doi.org/10.5281/zenodo.596518 now has all the other releases.

Any ideas what may have caused a duplicate event for 6.0.0? 6.1.0 had a hiccup with a tag deleted and retagged - https://github.com/python-pillow/Pillow/issues/3835#issuecomment-507306188 - but 6.0.0 went out smoothly: https://github.com/python-pillow/Pillow/issues/3618.

**Comment by radarhere** [comment]
There was a [problem with building the Windows binaries for 6.0.0](https://github.com/python-pillow/Pillow/issues/3618#issuecomment-478613834), so I could easily have retagged that release after the issue was fixed.

Did this work for 7.1.0?

**Comment by hugovk** [comment]
OK, that could have been it. 

Yes, it worked for 7.1.0 and 7.1.1:

<img src=https://user-images.githubusercontent.com/1324225/79062368-8f5cef00-7ca2-11ea-80dd-effd862c0e95.png width=75%>

Closing, thanks!
