### ISSUE TITLE
Does PIL provide an implementation of KCF (Kernel Correlation Filter) tracking?

### ISSUE THREAD

**Issue by songyuc** [python-pillow/Pillow#4501]
Hi guys,
I found it seemed Pillow didn't provide a encapsulated function of  KCF (Kernel Correlation Filter) tracking, do you?
Your idea and answer will be appreciated!

**Comment by radarhere** [comment]
I don't think so. If you're after this functionality, might I suggest OpenCV instead? https://www.pyimagesearch.com/2018/07/30/opencv-object-tracking/

**Comment by songyuc** [comment]
@radarhere , thanks sincerely for the information!
