### ISSUE TITLE
Support for 3D Data

### ISSUE THREAD

**Issue by lufol** [python-pillow/Pillow#4531]
Enabling Pillow to deal with 3D data would enable a broader use case. 
Especially in the medical domain data often is 3D and being able to deal with it potentially also with torchvision and Pillow would be really nice.

Of course, slice-wise processing of 3D volumes is also possible, however, in certain cases, augmentations need to be applied to the whole volume.

I would be really interested to hear if support for 3D data is planned at some point.

**Comment by radarhere** [comment]
Based on the current issues and PRs, there are no plans for this at the moment.

Is there a specific format of 3D data that you're thinking about?

**Comment by lufol** [comment]
Mostly 3D volumes or stacks of 2D images.

**Comment by radarhere** [comment]
What file format for the 3D volumes?

If by stack of 2D images, you just mean a series of 2D images, then I would have thought you could already use Pillow's functionality to apply operations to one image after another. If you mean something else, then again, what file format are you interested in?

**Comment by lufol** [comment]
The file formats I am regularly dealing with are mhd and dicom. 

Applying functions to the individual slices of the volume is possible, however, sometimes the whole volume needs to be manipulated at once (e.g. if rotating an image in the direction of the slice).

**Comment by lufol** [comment]
#4672
