### ISSUE TITLE
ImageFont documentation does not match with current code

### ISSUE THREAD

**Issue by marado** [python-pillow/Pillow#4535]
### What did you do?

Read the docs on 
https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.ImageFont
and then the code by following the link provided there, to
https://pillow.readthedocs.io/en/stable/_modules/PIL/ImageFont.html#load

### What did you expect to happen?

Since the documentation claims that only an IOError is raised, I expected to see the code raising an IOError.

### What actually happened?

The code shows an OSError being raised, as a result of this commit: https://github.com/python-pillow/Pillow/commit/538d9e2e5d252bea23e12da08495945d776aed78#diff-0b53b789652f38dc633674dd3671e636L82

**Comment by RioBaer** [comment]
Marcus, how do you mean what did I do? Please illuminate?
Regards Dan AKA BoomerNaut
Google Maps local guide level eight

**Comment by hugovk** [comment]
Thanks for the report! I've made https://github.com/python-pillow/Pillow/pull/4536 to fix the docs, plus some related updates.

**Comment by radarhere** [comment]
You can now see the updated documentation at https://pillow.readthedocs.io/en/latest/_modules/PIL/ImageFont.html#load. It will become 'stable' with the next release of Pillow on July 1st.
