### ISSUE TITLE
EXIF orientation is not updated when saving rotated/transposed image

### ISSUE THREAD

**Issue by RomanKosobrodov** [python-pillow/Pillow#4537]
### What did you do?
Saved a transposed image in PNG format

### What did you expect to happen?
EXIF orientation to be updated accordingly

### What actually happened?
EXIF orientation information in the saved image is incorrect

### What are your OS, Python and Pillow versions?
* OS: Ubuntu 18.04 LTS 
* Python: 3.8.0
* Pillow: 7.1.0

```python
from PIL import Image, __version__

EXIF_ORIENTATION = 0x0112
ROTATION = {3: Image.ROTATE_180, 6: Image.ROTATE_270, 8: Image.ROTATE_90}


def convert(input_filename, output_filename, image_format="PNG"):
    img = Image.open(input_filename)
    exif = img._getexif()
    if exif is not None:
        if EXIF_ORIENTATION in exif.keys():
            code = exif[EXIF_ORIENTATION]
            angle = ROTATION.get(code, None)
            print(f"filename: {input_filename};  EXIF rotation code: {code}")
            if angle is not None:
                img = img.transpose(angle)
    img.save(output_filename, format=image_format)


if __name__ == "__main__":
    print(f"PIL version: {__version__}")

    convert("A.JPG", "B.PNG")
    convert("B.PNG", "C.PNG")
```

Code output:
```bash
PIL version: 7.1.0
filename: A.JPG;  EXIF rotation code: 8
filename: B.PNG;  EXIF rotation code: 8
```
Expected output
```bash
PIL version: 7.1.0
filename: A.JPG;  EXIF rotation code: 8
filename: B.PNG;  EXIF rotation code: 1
```
Repository including code and test image:
[https://github.com/RomanKosobrodov/test-pillow-rotation](https://github.com/RomanKosobrodov/test-pillow-rotation)

**Comment by radarhere** [comment]
Pillow makes a distinction between the image data itself, and the image metadata. The EXIF orientation describes how the actual image should be transposed, it is not the image itself.

The Pillow `transpose` operations adjusts the image data, not the image metadata, and Pillow PNG saving retains the image metadata by default.

To be simple about it, if I just throw in `del img.info["exif"]`, the image orientation will no longer stay the same.

```python
            if angle is not None:
                img = img.transpose(angle)
		del img.info["exif"]
```

To be less simple about it, you might be more interested in https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.exif_transpose, https://github.com/python-pillow/Pillow/blob/master/src/PIL/ImageOps.py#L527. You will also want to know that Pillow does not set the EXIF orientation to 1 when an image is transposed - it just removes the EXIF orientation entry.

```python
from PIL import Image, ImageOps, __version__

EXIF_ORIENTATION = 0x0112
ROTATION = {3: Image.ROTATE_180, 6: Image.ROTATE_270, 8: Image.ROTATE_90}


def convert(input_filename, output_filename, image_format="PNG"):
    img = Image.open(input_filename)
    exif = img._getexif()
    if exif is not None:
        if EXIF_ORIENTATION in exif.keys():
            code = exif[EXIF_ORIENTATION]
            angle = ROTATION.get(code, None)
            print(f"filename: {input_filename};  EXIF rotation code: {code}")
            if angle is not None:
                img = ImageOps.exif_transpose(img)
    img.save(output_filename, format=image_format)


if __name__ == "__main__":
    print(f"PIL version: {__version__}")

    convert("A.JPG", "B.PNG")
    convert("B.PNG", "C.PNG")
```

I would actually like to make further changes.

```python
from PIL import Image, ImageOps, __version__

EXIF_ORIENTATION = 0x0112


def convert(input_filename, output_filename, image_format="PNG"):
    img = Image.open(input_filename)
    code = img.getexif().get(EXIF_ORIENTATION, 1)
    print(f"filename: {input_filename};  EXIF rotation code: {code}")
    if code and code != 1:
        img = ImageOps.exif_transpose(img)
    img.save(output_filename, format=image_format)


if __name__ == "__main__":
    print(f"PIL version: {__version__}")

    convert("A.JPG", "B.PNG")
    convert("B.PNG", "C.PNG")
```

**Comment by RomanKosobrodov** [comment]
Hi radarhere,

Thank you. That solves my problem. I understand what Pillow is doing but I am probably not the first person who find this behaviour surprising. Is this documented anywhere? I could not find any documentation on `getexif()` method either. Is it a method of `Image`? 

Also, I am getting the following warnings when converting a test image that comes directly from my Canon 450D:

```bash
/home/roman/Projects/mikula/venv/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 282 had too many entries: 2, expected 1
  warnings.warn(
/home/roman/Projects/mikula/venv/lib/python3.8/site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 283 had too many entries: 2, expected 1
  warnings.warn(
```

I'm curious why you return `image.copy()` from `ImageOps.exif_transpose` instead of `image`.

Thanks again for your help!

Regards,
Roman

**Comment by radarhere** [comment]
There is https://pillow.readthedocs.io/en/stable/handbook/concepts.html#orientation

`getexif()` was added in Pillow 6 - https://pillow.readthedocs.io/en/stable/releasenotes/6.0.0.html#added-exif-class. It is part of the Image class - https://github.com/python-pillow/Pillow/blob/3bb39c73dd75f34c470c6ee1521f9bfa22162f5f/src/PIL/Image.py#L1300

If `exif_transpose` is run on an image that will be changed, then `transpose` is called on it. `transpose`, as you already understand from the code you've written, returns a copy of the image. When the image doesn't need to be changed, `image.copy` is called, also returning a copy of the image for the sake of consistency - if this wasn't the case, and the function sometimes returned the original image instance and sometimes returned a new image instance, that could lead to unexpected behaviour.

**Comment by RomanKosobrodov** [comment]
Hi radarhere,
Thank you. I saw the Release Notes. You probably want to add this method to `Image` documentation at some stage.
Any comments on the warnings? My code is a command line tool and I don't want the user to see them. `TiffImagePlugin.py` is complaining about tags 282 and 283 (XResolution and YResolution) which have Rational type according to the standard (a tuple in Python). It is two integers (72,1) in my test file. So what is it complaining about? 
Regards,
Roman

**Comment by radarhere** [comment]
The warnings are a problem with Pillow, not with your image.

You could hide the warnings by catching them -

```python
import warnings

with warnings.catch_warnings():
	warnings.simplefilter("ignore", category=UserWarning)
	convert("A.JPG", "B.PNG")
```

**Comment by RomanKosobrodov** [comment]
Yes. I looked in the code and I don't think it treats Rational type properly.
Thanks for your help, once again.
Regards,
Roman

**Comment by RomanKosobrodov** [comment]
Closing the issue as the described behaviour is expected from the library.

**Comment by radarhere** [comment]
The warnings have now been fixed in Pillow master, and will be part of the next Pillow release, due out on July 1.
