### ISSUE TITLE
Can I create GIF from PIL

### ISSUE THREAD

**Issue by Eshan-Agarwal** [python-pillow/Pillow#4544]
I am working on creating a GIF and save it using numpy 4D arrays of shape (frames,height,width,channels) can I do this with the help of PIL?

**Comment by radarhere** [comment]
Sure. Using one of our animated test images, this code converts it into a 4D array, and then back to an animated GIF.

```python
from PIL import Image, ImageSequence
import numpy

# Setup the 4 dimensional array
a_frames = []
im = Image.open('Tests/images/chi.gif')
for im_frame in ImageSequence.Iterator(im):
	# Converting it to RGB to ensure that it has 3 dimensions as requested
	im_frame = im_frame.convert('RGB')
	a_frames.append(numpy.asarray(im_frame))
a = numpy.stack(a_frames)

print("Array shape:", a.shape)  # (31, 240, 320, 3)

# Save as an animated GIF
ims = [Image.fromarray(a_frame) for a_frame in a]
ims[0].save("out.gif", save_all=True, append_images=ims[1:])
```

**Comment by Eshan-Agarwal** [comment]
thanks you so much it works , but problem is that generated gif loop only once and when I apply loop param let say 2 then it loops twice, can i set gif to loop over and over not to stop? also there is no fps param ?

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving

> **duration**
> The display duration of each frame of the multiframe gif, in milliseconds. Pass a single integer for a constant duration, or a list or tuple to set the duration for each frame separately.
>
> **loop**
> Integer number of times the GIF should loop. 0 means that it will loop forever. By default, the image will not loop.

```python
ims[0].save("out.gif", save_all=True, append_images=ims[1:], loop=0, duration=500)
```

**Comment by Eshan-Agarwal** [comment]
Thanks again I read doc on this [page](https://pillow.readthedocs.io/en/3.1.x/handbook/image-file-formats.html)

**Comment by radarhere** [comment]
Note that the docs you have linked to are for Pillow 3.1.x. It may still be correct in places, but the one I linked to is the 'stable' branch, for the most up-to-date release.

**Comment by Eshan-Agarwal** [comment]
For duration I am passing `duration=fps*(10**-3)` so to convert frame per millisecond to fps, but changing fps value is not change duration it shows frame with same rate?

**Comment by radarhere** [comment]
You don't want -3, you want 3.

```
>>> 2*(10**-3)
0.002
>>> 2*(10**3)
2000
```

**Comment by radarhere** [comment]
Wait, scratch that.

**Comment by radarhere** [comment]
You want `duration=1000/fps`. 1000/(2fps) = 500.

**Comment by Eshan-Agarwal** [comment]
By apply 1000/2fps it shows me still image when fps value is 30

**Comment by radarhere** [comment]
Here's a simple script. When I run this, I get three images, each different. Maybe this should come with an epilepsy warning.

```python
from PIL import Image

def save_with_fps(fps):
	ims = []
	for i in range(200):
		im = Image.new("RGB", (100, 100), ["#f00", "#0f0", "#00f"][i % 3])
		ims.append(im)
	ims[0].save("fps_"+str(fps)+".gif", save_all=True, append_images=ims[1:], duration=1000/fps)

save_with_fps(2)
save_with_fps(30)
save_with_fps(60)
```

**Comment by Eshan-Agarwal** [comment]
![sample](https://user-images.githubusercontent.com/47007275/79033605-088a1280-7bcd-11ea-945f-ce0513a9304a.gif)
This is gif i got at 60 fps

**Comment by Eshan-Agarwal** [comment]
@radarhere  thanks for your help, just one more, I am generating some 5 such gif one by one by overwrite so that it not use more memory to store them and want to display all of these gif using subplots in .ipynb, I am trying to open gif using `im = Image.open("Sample.gif"`) & `im.show()`, but it's showing nothing

**Comment by radarhere** [comment]
Unfortunately, I'm not familiar with Jupyter Notebook. Googling, this seems like a possible answer - https://stackoverflow.com/a/50723518

**Comment by Eshan-Agarwal** [comment]
> Unfortunately, I'm not familiar with Jupyter Notebook. Googling, this seems like a possible answer - https://stackoverflow.com/a/50723518

@radarhere . I am also using this but it's not support subplots.

**Comment by Eshan-Agarwal** [comment]
@radarhere  I am doing this
```py
video_seq = [Image.fromarray(v_frame) for v_frame in video]
  video_seq[0].save("sample.gif", save_all=True, append_images=video_seq[1:]\
                    ,loop=0,duration=int((1000)/fps))
```
and gif I got is blur can we increase quality ?
![sample (1)](https://user-images.githubusercontent.com/47007275/79041736-aa325380-7c0f-11ea-8878-3f1a497b5b9f.gif)

**Comment by radarhere** [comment]
Could you provide a self-contained script showing how the image is generated?

**Comment by Eshan-Agarwal** [comment]
Please see this code 

```py
import tensorflow_datasets as tfds
from IPython import display
from PIL import Image
import numpy as np

ds, ds_info = tfds.load("starcraft_video/move_unit_to_border_64", with_info = True,split="test")

num_examples = 3
examples = list(tfds.as_numpy(ds.take(num_examples)))

for i, ex in enumerate(examples):
   video = ex["rgb_screen"]
   frame,height, width, c = video.shape

   if c == 1:
       video = video.reshape(video.shape[:3])
   video_seq = [Image.fromarray(v_frame) for v_frame in video]
   video_seq[0].save("sample.gif", save_all=True, append_images=video_seq[1:]\
                    ,loop=0,duration=int((1000)/10))
   with open('sample.gif','rb') as f:
      display.display(display.Image(data=f.read(),format="png",
                                    width=150,height=150))
```

**Comment by Eshan-Agarwal** [comment]
@radarhere  using `.quantize()` with fromarray method gives good results, is there is anything else to do to increase quality. Thanks

**Comment by radarhere** [comment]
I'm less keen on trying to analyse a problem involving a nearly 2 gigabyte file. #3059 seems to indicate that you're on the right track with `quantize`.

If your final dimensions are 150 pixels and that is smaller than the original size, you may be interested in using the `resize` method to scale it down, rather than having `display` do it.

**Comment by Eshan-Agarwal** [comment]
Thank you so much for your help ☺️
