### ISSUE TITLE
Vertical text alignment ignores yOffset

### ISSUE THREAD

**Issue by nulano** [python-pillow/Pillow#4553]
While working on implementing the `anchor` parameter of `ImageDraw.text` (see https://github.com/python-pillow/Pillow/issues/4511#issuecomment-612940904), I noticed a bug with the handling of y_offset with raqm.

For the following code:

```python
from PIL import Image, ImageDraw, ImageFont
font = ImageFont.truetype("segoeui.ttf", 60, layout_engine=ImageFont.LAYOUT_RAQM)
def test(text):
    im = Image.new("RGB", (200,200), "white")
    d = ImageDraw.Draw(im)
    d.line(((0,100),(200,100)), "black")
    d.line(((100,0),(100,200)), "black")
    d.text((100,100),text,"black", font=font)
    im.show()
test("a" + ("\u030C" * 20))    # a + 20 * Unicode Character 'COMBINING CARON' (U+030C)
```

I expect to get the following image:
![image](https://user-images.githubusercontent.com/3819630/79150886-ced22b00-7dc9-11ea-8d7d-3a7da6a96db0.png)

But I get the following image (with master):
![image](https://user-images.githubusercontent.com/3819630/79151082-1ce72e80-7dca-11ea-9952-5262d59c039f.png)

This is because when raqm support was added, the `yoffset` variable was not updated to look at the `glyphinfo[i].y_offset` value: https://github.com/python-pillow/Pillow/blob/97280a045cc2544ef8855dac2765e765565772cd/src/_imagingft.c#L665-L674

Since `font_render` looks at the `bitmap.top` value anyway (see below), which should be equal to `bbox.yMax`, I believe `yoffset` is supposed to calculate the same value as `y_max`, so it can just be removed and `y_max` used instead (in second snippet below).
https://github.com/python-pillow/Pillow/blob/97280a045cc2544ef8855dac2765e765565772cd/src/_imagingft.c#L801-L804
https://github.com/python-pillow/Pillow/blob/97280a045cc2544ef8855dac2765e765565772cd/src/_imagingft.c#L710-L712

I am planning to include this change in the PR implementing the `anchor` parameter, but I wanted to document this as a separate issue.

**Comment by radarhere** [comment]
@nulano are you still working on this PR? If you're simply still getting around to it, no worries, whenever you can, just wondering if you encountered a problem and would like some help.

**Comment by nulano** [comment]
The `anchor` parameter and related bugfixes are finished (see my branch 'anchor'), but there are a few more things I wanted to add with it (better measurement functions), and I will be really busy until early April.
