### ISSUE TITLE
ImageSequence.Iterator color issue

### ISSUE THREAD

**Issue by HansolEom** [python-pillow/Pillow#4554]
![test](https://user-images.githubusercontent.com/45479160/79192863-79972780-7e64-11ea-8a61-2dd10f9e8d81.GIF)

```python
from PIL import Image, ImageSequence
img = Image.open(path)
imgs = ImageSequence.Iterator(img)
for idx, i in enumerate(imgs,1):
    i.convert('RGB').save('{}.jpg'.format(idx))
```

I made the code as above.
I got the image below.

![1](https://user-images.githubusercontent.com/45479160/79193244-325d6680-7e65-11ea-93af-675028fea95d.jpg)
![2](https://user-images.githubusercontent.com/45479160/79193245-338e9380-7e65-11ea-8c08-34e7acc45b79.jpg)

Why is the color broken? Can I solve this problem?

**Comment by Infinitemarcus** [comment]
Today, I faced the same problem. Did anyone managed to solve this?

**Comment by radarhere** [comment]
Pillow 9.0.0 has significantly improved reading animated GIFs thanks to #5857.

If this issue is still a problem when using Pillow 9.0.0, please let us know.

**Comment by InfiniteMarcus** [comment]
I tested my code with v9.0.0 and my issue is solved. Thanks!
