### ISSUE TITLE
Text outline on a transparent background

### ISSUE THREAD

**Issue by ODtian** [python-pillow/Pillow#4557]
### What did you do?
```python
bg_img = Image.new('RGB', charsize, color)
mask_img = Image.new('L', bg_img.size, 0)
draw = ImageDraw.Draw(mask_img)
draw.text((0, 0), letter, font=font, fill='white')
bg_img.putalpha(mask_img)    
```
I try to draw a char on a total transparent background, however there are some black outlines on text,it should not be happened since background is transparent.There are other post about this:

https://stackoverflow.com/questions/14442086/pils-image-paste-operation-degrades-image-drawn-text-quality/14444743#14444743
and

https://nedbatchelder.com/blog/200801/truly_transparent_text_with_pil.html

it's 12 years passed, any solutions?
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```python
bg_img = Image.new('RGB', charsize, color)
mask_img = Image.new('L', bg_img.size, 0)
draw = ImageDraw.Draw(mask_img)
draw.text((0, 0), letter, font=font, fill='white')
bg_img.putalpha(mask_img)
```

**Comment by radarhere** [comment]
If I run the following code with a font from our test suite -

```
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype('Tests/fonts/FreeMono.ttf', 40)
charsize = (128, 128)
color = '#fff'
letter = 'Test'

bg_img = Image.new('RGB', charsize, color)
mask_img = Image.new('L', bg_img.size, 0)
draw = ImageDraw.Draw(mask_img)
draw.text((0, 0), letter, font=font, fill='white')
bg_img.putalpha(mask_img)

bg_img.save('out.png')
```

I get this image -

![out](https://user-images.githubusercontent.com/3112309/79320177-b76f7b00-7f4c-11ea-9bb3-8670c89f58c2.png)

I'm not seeing any black outlines? In fact, you have to check to see that I've included an image at all in this post, because it's white text on a transparent background on a white GitHub page. If you are seeing black outlines in a way that I'm not, could you provide the font that you're using, the image created and some details about your setup?

**Comment by ODtian** [comment]
Thanks for your reply!
Actually, the origin code is here, the code I post works well because I handle the alpha channel manually.
The deltail you could see the two link I post on the top:
[](https://nedbatchelder.com/blog/200801/truly_transparent_text_with_pil.html)
[](https://stackoverflow.com/questions/14442086/pils-image-paste-operation-degrades-image-drawn-text-quality/14444743#14444743)

these two link analyzed the reason, and I will explain it once again myself at below.

```
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype('Tests/fonts/FreeMono.ttf', 40)
charsize = (128, 128)
color = '#fff'
letter = 'Test'
bg = Image.new('RGBA', charsize)
draw = ImageDraw.Draw(bg)
draw.text((0, 0), letter, font=font, color=color)
bg.save('out.png')
```
the result: 
![out](https://user-images.githubusercontent.com/40318251/79323549-ef70c100-7f40-11ea-9929-1c7b922721f5.png)
you can see there are some black outlines around text.
It's not such a big problem, but If you paste a transparent background image on a transparent background using Image.paste and pass a mask, the edge will be black. 
```
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype('Tests/fonts/FreeMono.ttf', 40)
charsize = (128, 128)
color = '#fff'
letter = 'Test'

bg_img = Image.new('RGB', charsize, color)
mask_img = Image.new('L', bg_img.size, 0)
draw = ImageDraw.Draw(mask_img)
draw.text((0, 0), letter, font=font, fill='white')
bg_img.putalpha(mask_img) # bg_img is text with no outlines
new_img = Image.new('RGBA', (300, 300))  # default color is (0, 0, 0, 0)
new_img.paste(bg_img, (0, 0), mask_img)
new_img.save('out2.png')
new_img2 = Image.new('RGBA', (300, 300), (255, 0, 0, 0))  # color is red and alpha is 0
new_img2.paste(bg_img, (0, 0), mask_img)
new_img2.save('out3.png')
```
as result, out2.png and out3.png is:
![out2](https://user-images.githubusercontent.com/40318251/79326019-bc303100-7f44-11ea-861f-520560888b1a.png)
(edge is black)
![out3](https://user-images.githubusercontent.com/40318251/79326025-bf2b2180-7f44-11ea-8191-aa0ffd41b920.png)
(edge is red)
This is mainly due to the mask calculation inside PIL, and the same algorithm is used in Image.paste, the background color It is (0, 0, 0, 0), and PIL does not consider the transparency of the background when calculating, so the image pasted is actually on a pure black background, and then the mask is calculated, which leads to the background, The black pixel is calculated with a transparency to (127, 127, 127, 85), which appears at the edge of the text, and it should have been (255, 255, 255, 85).

**Comment by radarhere** [comment]
Thanks for further detail. Hopefully a solution will be devised for this in due course, and I feel like you're probably more interested in a solution at this point than a workaround - but here is a workaround anyway: set the RGB value of the background to the same as RGB value of your text.

```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype('Tests/fonts/FreeMono.ttf', 40)
charsize = (128, 128)
color = '#fff'
letter = 'Test'
bg = Image.new('RGBA', charsize, (255,255,255,0))  # 'white' transparent
draw = ImageDraw.Draw(bg)
draw.text((0, 0), letter, font=font, color=color)
bg.save('out.png')
```

**Comment by radarhere** [comment]
I've created PR #4566. If you could test that branch and confirm that it resolves this issue, that would be helpful, thanks.

**Comment by ODtian** [comment]
Yes, it's work for me. Thanks a lot!
