### ISSUE TITLE
Webp images cannot be pickled

### ISSUE THREAD

**Issue by Lebuin** [python-pillow/Pillow#4559]
### What did you do?

I'm trying to pickle and unpickle webp images. My code works for other image formats, but fails for webp images. For example, run the following code with [this image](https://github.com/python-pillow/Pillow/files/4485578/image.zip) (compressed because GitHub doesn't support webp files):

```python
from PIL import Image
import pickle

image = Image.open('image.webp')
unpickled_image = pickle.loads(pickle.dumps(image))
resized_image = unpickled_image.resize((50, 50))
```

### What did you expect to happen?

A resized `Image` instance should have been created.

### What actually happened?

The following error was thrown:

```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/seppe/.local/lib/python3.7/site-packages/PIL/Image.py", line 1886, in resize
    self.load()
  File "/home/seppe/.local/lib/python3.7/site-packages/PIL/WebPImagePlugin.py", line 156, in load
    if self.__loaded != self.__logical_frame:
AttributeError: 'WebPImageFile' object has no attribute '_WebPImageFile__loaded'
```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 19.10
* Python: 3.7.5
* Pillow: 7.1.1

**Comment by hugovk** [comment]
Thanks for the report, please can you test PR https://github.com/python-pillow/Pillow/pull/4561?

**Comment by Lebuin** [comment]
I can confirm that the issue has been fixed in your PR. Thank you for the quick fix!
