### ISSUE TITLE
Absent pixels when drawing font

### ISSUE THREAD

**Issue by gaoxinge** [python-pillow/Pillow#4569]
### What did you do?

- I use pillow to draw font.

### What actually happened?

![1](https://user-images.githubusercontent.com/16648345/79721975-d63b8c00-8315-11ea-802d-094c8f1c084d.png)

- I observe there are some absence pixels on the top of numbers: `0`, `2`, `3`, `8`, `9` .

### What are your OS, Python and Pillow versions?

* OS: win10
* Python: 3.6.1
* Pillow: 7.1.1

```python
from PIL import Image, ImageFont, ImageDraw

ttf_path = "vista-hei-all.ttf"
text = "0123456789"
text_size = 35

font = ImageFont.truetype(ttf_path, text_size)
text_width, text_height = font.getsize(text)
canvas = Image.new("RGBA", [text_width, text_height], (255, 0, 0, 0))
draw = ImageDraw.Draw(canvas)
draw.text((0, 0), text, font=font, fill="#000000")
canvas.show()
```

**Comment by radarhere** [comment]
Are you able to replicate this problem with a font that you can link to?

**Comment by gaoxinge** [comment]
@radarhere I place a zip here.

- [vista-hei-all.zip](https://github.com/python-pillow/Pillow/files/4502112/vista-hei-all.zip)

**Comment by radarhere** [comment]
As a note for future investigation of this, here's a clear way to demonstrate that this is a bug - removing the '0' from '0123456789' causes the missing pixels to be drawn without a problem.

**Comment by nulano** [comment]
I have seen this before in some previous tests. I believe the cause is #185, as the solution there seems to be to count the text distance from the bottom instead of from the top. (Confusingly, this patch made the `ascender` variable refer to the descender height.) This is wrong and works only because most fonts tend to have a gap at the top. I believe I have fixed this properly in my WIP PR for https://github.com/python-pillow/Pillow/issues/4511#issuecomment-612940904, by enabling hinting for `FT_GetGlyphCBox` in `_imageft.getsize`.

**Comment by gaoxinge** [comment]
@nulano Nice!

**Comment by gaoxinge** [comment]
I have run the code below on pillow version 7.1.1 and 8.0.1 respectively, and the bug seems to be fixed.

```python
from PIL import Image, ImageFont, ImageDraw

ttf_path = "vista-hei-all.ttf"
text = "0123456789"
text_size = 35

font = ImageFont.truetype(ttf_path, text_size)
text_width, text_height = font.getsize(text)
canvas = Image.new("RGBA", [text_width, text_height], (255, 0, 0, 255))
draw = ImageDraw.Draw(canvas)
draw.text((0, 0), text, font=font, fill="#000000")
canvas.show()
```

- 7.1.1

![7-1-1](https://user-images.githubusercontent.com/16648345/102743229-fe422a00-4391-11eb-88db-630392a9653c.PNG)

- 8.0.1

![8-0-1](https://user-images.githubusercontent.com/16648345/102743260-0e5a0980-4392-11eb-9c24-430c026dc421.png)

**Comment by radarhere** [comment]
Thanks for letting us know!
