### ISSUE TITLE
format is missing after cropping

### ISSUE THREAD

**Issue by tony612** [python-pillow/Pillow#4571]
### What did you do?

Cropping an image and fetch its `format`.

### What did you expect to happen?

I expect the `format` is same with the original image.

### What actually happened?

The `format` of the new image is `None`.

### What are your OS, Python and Pillow versions?

* OS: OS X; Darwin Kernel Version 18.7.0
* Python: 3.7.6
* Pillow: 7.0.0

```python
# I used this image https://upload.wikimedia.org/wikipedia/commons/6/62/Starsinthesky.jpg
>>> im2 = Image.open('~/Downloads/Starsinthesky.jpg')
>>> im2.format
'JPEG'
>>> im3 = im2.crop((0, 0, 600, 500))
>>> im3.format
>>> im3.format == None
True
```

Is this a bug? If this is by design, why?

**Comment by tony612** [comment]
I found this is because when cropping an image, a new image will be created, but no `format` is set:
https://github.com/python-pillow/Pillow/blob/a0d8e550ec34729d4b67774069ccc2b1319f44b1/src/PIL/Image.py#L1134
https://github.com/python-pillow/Pillow/blob/a0d8e550ec34729d4b67774069ccc2b1319f44b1/src/PIL/Image.py#L554-L567

**Comment by radarhere** [comment]
Hi. It's not just that `format` isn't set. The class is no longer specific to the format, but a generic `Image`.

```python
>>> from PIL import Image
>>> im = Image.open("Tests/images/hopper.png")
>>> im
<PIL.PngImagePlugin.PngImageFile image mode=RGB size=128x128 at 0x10327E460>
>>> im.format
'PNG'
>>> cropped_im = im.crop((0, 0, 10, 10))
>>> cropped_im
<PIL.Image.Image image mode=RGB size=10x10 at 0x1031B46D0>
>>> cropped_im.format is None
True
```

Why is this? I can't argue for the original programmers, but here's my thinking.

Having been cropped, I might argue that the image is no longer a good representation of what is in the file. The image data from the file has been loaded into Pillow. In your case, you could close `im2` and Pillow can continue to use `im3` without a problem. You could delete the original file even without causing an issue.

A JPEG or a PNG or whatever is a file format. Pillow reads those file formats and interprets the image data from them. It doesn't store the entire file in memory, and it doesn't really make sense to call the internal Pillow collection of data a JPEG. To make an analogy, let's say that a JPEG is a hardback book. If we copy the story out of the book, the story isn't a hardback, it's just words. Pillow image data isn't a JPEG, it's just image data.

If there is some specific functionality you think is lost by converting a `JpegImageFile` into a generic `Image`, let us know and perhaps we can help figure out another way to do it.

**Comment by tony612** [comment]
@radarhere Thanks! I think your explanation is reasonable. The reason why I need the original format is I want to save the cropped image to another file by `save`, so it's useful to have the original format to keep the format consistent. But I can solve my problem by saving the format somewhere else.
