### ISSUE TITLE
New edge detection method - want to contribute

### ISSUE THREAD

**Issue by SujoyKG** [python-pillow/Pillow#4572]
I am attaching my one paper on a new image-edge detection method which is more general than the similar popular techniques for the same.
Please read it.  If you like it, I will post the source code & contribute to 'pillow'.
Thanks in advance.
[a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf](https://github.com/python-pillow/Pillow/files/4514043/a-better-first-derivative-approach-for-edge-detection-IJERTV2IS110616.pdf)

**Comment by wiredfool** [comment]
We don't currently ship any techniques for edge detection, so I'm not sure that this is the appropriate library for that. OpenCV or SciPy would probably be better choices.

**Comment by radarhere** [comment]
To link, here are the other attempts to find a home for this method
- https://github.com/jrosebr1/imutils/issues/197
- https://github.com/lessthanoptimal/BoofCV/issues/164
- https://github.com/sightmachine/SimpleCV/issues/728

**Comment by SujoyKG** [comment]
I hope this would find many homes soon. Also I would make a home myself in near future. :-)

**Comment by radarhere** [comment]
Here is a link to code from the OP based on the paper - https://github.com/SujoyKG/Sujoy_Edge/blob/master/edge.py

**Comment by radarhere** [comment]
Closing, [for reasons stated earlier.](https://github.com/python-pillow/Pillow/issues/4572#issuecomment-618246247)
