### ISSUE TITLE
Dithering is added when creating gif

### ISSUE THREAD

**Issue by djachenko** [python-pillow/Pillow#4573]
### What did you do?

I tried to make a gif animation from set of still .jpegs.

```python
path = Path("src")
size = 1000

frames = [Image.open(frame) for frame in path.iterdir()]

for frame in frames:
    frame.thumbnail((size, size))

frames[0].save(
    Path("res/res.gif"),
    format="GIF",
    save_all=True,
    append_images=frames[1:],
    duration=10,
    loop=0
)
```

### What did you expect to happen?

Animation to be created with frames looking exactly as still images.

![DSC_3546](https://user-images.githubusercontent.com/2458264/79945231-8f759f80-8497-11ea-965d-d6783d5c811c.jpg)

### What actually happened?

Animation was created, but dithering artefacts were added to frames.

![Screenshot 2020-04-22 12 45 25](https://user-images.githubusercontent.com/2458264/79945337-bd5ae400-8497-11ea-8ad9-a0cb3f6b2fb3.png)

### What are your OS, Python and Pillow versions?

* OS: Windows 10 Pro 1909 64-bit
* Python: 3.7.7
* Pillow: 7.1.1

**Comment by radarhere** [comment]
When you say that you expected 'Animation to be created with frames looking exactly as still images', you should be aware that GIF frames can only hold up to 256 colors.

https://en.wikipedia.org/wiki/GIF
> The format supports up to 8 bits per pixel for each image, allowing a single image to reference its own palette of up to 256 different colors

**Comment by radarhere** [comment]
Could you provide all of the images that you used, so that we can completely reproduce the problem? If there are many images, perhaps you could simplify the example?

**Comment by djachenko** [comment]
Yes, of course:

![DSC_3461](https://user-images.githubusercontent.com/2458264/80050280-5ee94080-853f-11ea-82e8-c6f877069161.jpg)
![DSC_3462](https://user-images.githubusercontent.com/2458264/80050288-60b30400-853f-11ea-9817-8229afb9bf79.jpg)
![DSC_3464](https://user-images.githubusercontent.com/2458264/80050289-614b9a80-853f-11ea-80fd-4d63e0ba4494.jpg)

**Comment by radarhere** [comment]
To confirm: each of your JPEGs have a lot more than 256 colors, even after using `thumbnail()` to reduce the size to (1000, 1000). So the output GIF can't perfectly match the input JPEGs.

For reference, here is a GIF from your images.

![ditheringdefault](https://user-images.githubusercontent.com/3112309/125268200-d379ec00-e34a-11eb-8d9d-3b904d2f5484.gif)

As to the question of why dithering is present, https://webstyleguide.com/wsg2/graphics/dither.html
>  Dithering is the most common means of reducing the color range of images down to the 256 (or fewer) colors seen in 8-bit GIF images.

If I go into Pillow's code and disable the dithering, here is the GIF output.

![ditheringoff](https://user-images.githubusercontent.com/3112309/125268217-d5dc4600-e34a-11eb-8c7b-152e5dcb90d7.gif)

I doubt you would prefer this.

There may be algorithms that produce a different result, but this isn't necessarily a problem. This is just a result of the 256 color GIF limitation. If you have any other thoughts, this can be re-opened.
