### ISSUE TITLE
loop=1 actually loops twice?

### ISSUE THREAD

**Issue by maxhumber** [python-pillow/Pillow#4575]
### What did you do?

```python
from PIL import Image

r = Image.new('RGB', (500, 500), (255, 0, 0))
g = Image.new('RGB', (500, 500), (0, 255, 0))
b = Image.new('RGB', (500, 500), (0, 0, 255))

frames = [r, g, b]

frames[0].save(
    'rgb.gif',
    save_all=True,
    append_images=frames[1:],
    duration=500, # TURNED WAY UP TO BE CAREFUL
    loop=1
)
```

### What did you expect to happen?

Play through once.

### What actually happened?

Plays twice, loops once. Hard to know what argument to use because, as documented, `loop=0` makes it loop infinitely.

![rgb](https://user-images.githubusercontent.com/2367311/80044064-6114b600-84d1-11ea-9012-5f55001af591.gif)

### What are your OS, Python and Pillow versions?

* OS: macOS
* Python: 3.7
* Pillow: 7.0.0 (seems PNG gifs are broken in 7.1.0 and 7.1.1?)

**Comment by radarhere** [comment]
If you would like it to play through once, without repeating, just omit the `loop` argument.

```python
frames[0].save(
    'rgb.gif',
    save_all=True,
    append_images=frames[1:],
    duration=500, # TURNED WAY UP TO BE CAREFUL
)
```

Zero will make it loop forever, yes. This is [documented](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif).

> **loop**
> May not be present. The number of times the GIF should loop. 0 means that it will loop forever.

Why is it the case that 0 makes it loop forever, and 1 makes it play through twice? Well, Pillow is not actually transforming these numbers when it is writing the GIF. We're following the [specification](https://web.archive.org/web/20140830100320/http://odur.let.rug.nl/~kleiweg/gif/netscape.html) and writing the number that 'indicate the number of iterations the loop should be executed'. That document later says that 'an iteration count of zero indicates infinite'.

For the sake of consistency with other image reading and writing code in the world, using this value directly is probably best.

**Comment by radarhere** [comment]
Would you be able to elaborate on what you mean by 'Loops are broken in 7.1.0 and 7.1.1'?

**Comment by maxhumber** [comment]
@radarhere thanks for the clarification! I wouldn't have thought to just lose the `loop` argument entirely. 

I recognize that we're probably stuck with `loop=0` = infinity now. Wondering if it would have been nice to have "loop=0" as play through once, and loop=-1 as play infinitely? No matter. Thanks for helping me out!

**Comment by maxhumber** [comment]
I created a separate issue: https://github.com/python-pillow/Pillow/issues/4578 for "Loops are broken in 7.1.0 and 7.1.1"! 

Closing out this now! :)

**Comment by fahaihappy** [comment]
If i want to play through once, how to do?

**Comment by fahaihappy** [comment]
If i want to just play gif through once, how to do?

**Comment by nulano** [comment]
> If you would like it to play through once, without repeating, just omit the loop argument.
