### ISSUE TITLE
Cropping a TiffImageFile removes other images in stack

### ISSUE THREAD

**Issue by mb1069** [python-pillow/Pillow#4581]
I'm trying to crop a imageJ hyperstack along the x,y axis. Calling .crop on the Image file converts it into a PIL.Image.Image, and I can't see a way to re-create an image stack without saving a new image to a file (+ using append_images=[...]).

I this an implementation issue or am I looking at this issue from the wrong perspective?

**Comment by radarhere** [comment]
Yes, your description is accurate. However, what are you trying to do such that this is a problem?

**Comment by mb1069** [comment]
I've got a stack of scans of a cell surrounded by a lot of blank space as the field of view is much larger than the cell. 

I tried a layer-by-layer approach, but when saving an image using append_images with more than 1 appended image the resulting image only appears to have 2 layers when re-loaded by Pillow?

**Comment by radarhere** [comment]
Hmm. If you have a self-contained example, that would be the best way to help you. Otherwise, here's an example of loading a multiframe TIFF, cropping it, saving it and loading it again, using one of our test images.

```python
from PIL import Image, ImageSequence
im = Image.open("Tests/images/total-pages-zero.tif")

print("Before")
for i, im_frame in enumerate(ImageSequence.Iterator(im)):
	print("Frame "+str(i)+": "+str(im_frame.size))
print("")

cropped_ims = ImageSequence.all_frames(im, lambda im_frame: im_frame.crop((0, 0, 500, 500)))
cropped_ims[0].save("out.tif", save_all=True, append_images=cropped_ims[1:])

im = Image.open("out.tif")
print("After")
for i, im_frame in enumerate(ImageSequence.Iterator(im)):
	print("Frame "+str(i)+": "+str(im_frame.size))
```

This outputs
```
Before
Frame 0: (1728, 2156)
Frame 1: (1728, 2156)
Frame 2: (1728, 2156)

After
Frame 0: (500, 500)
Frame 1: (500, 500)
Frame 2: (500, 500)
```

**Comment by mb1069** [comment]
That works brilliantly, thank you! The key difference with my solution was the save_all=True. What would be the use case for save_all=False and setting append_images to a non-empty list?

**Comment by radarhere** [comment]
My only answer? There isn't one.

**Comment by mb1069** [comment]
OK 👍  right thanks for the help, I'll close
