### ISSUE TITLE
7.1.2: missing olefile module dependency

### ISSUE THREAD

**Issue by kloczek** [python-pillow/Pillow#4585]
```
[tkloczko@barrel site-packages]$ grep -r olefile
PIL/FpxImagePlugin.py:import olefile
PIL/FpxImagePlugin.py:    return prefix[:8] == olefile.MAGIC
PIL/FpxImagePlugin.py:            self.ole = olefile.OleFileIO(self.fp)
PIL/MicImagePlugin.py:import olefile
PIL/MicImagePlugin.py:    return prefix[:8] == olefile.MAGIC
PIL/MicImagePlugin.py:            self.ole = olefile.OleFileIO(self.fp)
Binary file PIL/__pycache__/FpxImagePlugin.cpython-38.pyc matches
Binary file PIL/__pycache__/MicImagePlugin.cpython-38.pyc matches
Binary file PIL/__pycache__/FpxImagePlugin.cpython-38.opt-1.pyc matches
Binary file PIL/__pycache__/MicImagePlugin.cpython-38.opt-1.pyc matches
```
And at the same time dependency file is empty:
```
[tkloczko@barrel site-packages]$ cat Pillow-7.1.2-py3.8.egg-info/dependency_links.txt

[tkloczko@barrel site-packages]$
```

**Comment by hugovk** [comment]
Olefile was removed as a vendored dependency in Pillow 4.0 (2017-01), and is now an optional dependency.

If you need it, please install from PyPI, for example:

```sh
python3 -m pip install olefile
```

**Comment by kloczek** [comment]
I  know how to install it :)

I've been pointing only on fact tht pillow modiule has completly empty metadata about dependencies (build or runtime).

**Comment by hugovk** [comment]
What sort of thing do you expect?

Please could you link to some docs about it?

**Comment by radarhere** [comment]
The docs do mention olefile in a few places - https://pillow.readthedocs.io/en/stable/search.html?q=olefile

**Comment by kloczek** [comment]
Issue is that python executable is not able read and understant and use that documentation :P

**Comment by hugovk** [comment]
@kloczek Please could you fill out the issue template, to help us understand the concrete problem you're running into, and what sort of solution you expect?

Sorry, when I said documentation, I meant Python documentation. If we should be packaging stuff up wrongly, it'd be nice to see how it's meant to be done :)

Thanks!

### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 



```python
code goes here
```

**Comment by kloczek** [comment]
Please don't waste your and my time on asking questions which are nor relevant in this case.

Missing module dependencies is 100% independent from OS, python version. Pillow version you have issue title.

**Comment by hugovk** [comment]
I don't see any concrete problem here. 

Olefile is an optional dependency. If you need it, install it. 

Pillow does not require it as a dependency because not everyone uses `FpxImagePlugin` and `MicImagePlugin`. Other than testing, Pillow has zero Python dependencies.

Please at least let us know these things:

### What did you do?

### What did you expect to happen?

### What actually happened?

**Comment by kloczek** [comment]
Below is fragment of y rpm package spec file for your module about build dependencies:
```
BuildRequires:  python3dist(cffi)
BuildRequires:  python3dist(numpy)
BuildRequires:  python3dist(olefile)
BuildRequires:  python3-qt5
BuildRequires:  python3dist(setuptools)
BuildRequires:  python3dist(sphinx)
BuildRequires:  python3-tkinter
````
None of those python modules are picked automatically because you pillow module dependencies metadata are completely EMPTY.

**Comment by wiredfool** [comment]
* Pillow will use olefile if it's installed to open certain types of files. It is not required, unless you want to use some uncommon formats. 
* Pillow will optionally use CFFI in some cases if it's installed. It is not required. It significantly speeds some operations on pypy, where it is installed by default. 
* Pillow does not require numpy to build in any case, it interops with it. No pillow functionality relies on numpy. 
* Pillow may use QT and TK, for QT or TK specific functionality. Those functions are completely optional. 
* Pillow uses sphinx to build documentation. It is not required for usage of the library. 
* I'm not sure why setuptools is required as part of the build here, but there is an implicit requirement on pip or setuptools to install the package in the first place.

**Comment by kloczek** [comment]
So as you see you can way better describe all those dependences than I've few other people done.

So again: it would be nice to have list of fixed and weak dependencies in modiule description :)

**Comment by wiredfool** [comment]
The (python) development requirements are in requirements.txt. FWIW, that list is pretty incomplete, since what you really need to completely build (and test, headless) on fedora is here: https://github.com/python-pillow/docker-images/blob/master/fedora-31-amd64/Dockerfile

```
RUN dnf install -y redhat-rpm-config \
    python3-devel python3-virtualenv make gcc \
    libtiff-devel libjpeg-devel zlib-devel freetype-devel \
    lcms2-devel libwebp-devel openjpeg2-devel python3-tkinter \
    tcl-devel tk-devel harfbuzz-devel fribidi-devel libraqm-devel \
    libimagequant-devel \
    xorg-x11-server-Xvfb which
```

If you've got specific suggestions, feel free to offer them.

**Comment by kloczek** [comment]
You can replace that command by `dnd builddep <package>spec`.

Never the less looks like you still don't get my point ... each python module should have proper metadata description. Without that even pip is not able prepare proper build env.

**Comment by wiredfool** [comment]
I do understand. 

dnd builddep package will get you what you need to build the distributed fedora package, which is not necessarily what we need to build master on our test systems.

But, as far as I know, there’s no way to specify non python dependencies, nor optional dependencies. 

Once again, do you have a specific suggestion or patch that you would like us to use?
