### ISSUE TITLE
ImageDraw.Draw.fontmode = '1' not working in 7.0.0

### ISSUE THREAD

**Issue by Belval** [python-pillow/Pillow#4602]
### What did you do?

Updated my Pillow dependency from 6.x to 7.x.

### What did you expect to happen?

For the anti-anti-aliasing workaround to still be working. 

```
txt_mask_draw = ImageDraw.Draw(txt_mask, mode="RGB")
txt_mask_draw.fontmode = "1"
```
By setting `fontmode = "1"`, text would be rendered only with the color given.

### What actually happened?

The font is anti-aliased which means that it is not all the same color.

### What are your OS, Python and Pillow versions?

* OS: Archlinux
* Python: 3.8
* Pillow: 7.1

I don't have a repro yet, my usecase is tangled in some other code, but it clearly broke with the version change because I can toggle it by switching between `pillow==6.0.0` and `pillow==7.1.0` with `pip`.

Pillow 7.1.0
![alias](https://user-images.githubusercontent.com/5399488/80870495-c7899900-8c74-11ea-819a-841ef5aabed7.png)

Pillow 6.0.0
![out_0](https://user-images.githubusercontent.com/5399488/80870498-cb1d2000-8c74-11ea-8490-741bac4bf2d8.png)

**Comment by Belval** [comment]
Closing, the fontmode = "1" still works, its the default resize becoming "Bicubic" that was the culprit.

I will read the changelog more carefully next time. Thank you for your work.

**Comment by jon32446** [comment]
> 
> 
> Closing, the fontmode = "1" still works, its the default resize becoming "Bicubic" that was the culprit.
> 
> I will read the changelog more carefully next time. Thank you for your work.

Could you post how you changed your code to work?

**Comment by Belval** [comment]
When using Image.resize, set the resize method to NEAREST. This will prevent the font edges from blending with the background.
