### ISSUE TITLE
Image.fromarray() cannot handle 1-D arrays

### ISSUE THREAD

**Issue by jwesolo** [python-pillow/Pillow#4606]
Running Pillow ~~7.0.0~~ (EDIT: now 7.1.2) on Python 3.7.6 on Windows 10 x64

I am converting a float32 grayscale array to Pillow so that I can use some of the image operations. This is not strictly an actual image and I want to preserve the order of the grayscale values. Having to reshape the array to use these operations doesn't seem intended. The grayscale values are stored in index 3 of the dataset. When I try to load the array into the Pillow Image class, it throws an error because `__array_interface__['shape'][1]` is missing on a 1-D array. This is the Numpy intended behavior (see https://numpy.org/doc/stable/reference/generated/numpy.ndarray.shape.html). There is no check for this in `Image.fromarray()`.

Relevant code:
```python
rows = np.loadtxt (f, dtype = int, max_rows = 1)
columns = np.loadtxt (f, dtype = int, max_rows = 1)
inputPoints = np.loadtxt (f, delimiter=' ', max_rows = (rows * columns))
testArray = 255 * inputPoints[:,3]
print (testArray.__array_interface__)
print (len (testArray.__array_interface__['shape']))
grayImage = Image.fromarray (testArray, mode = 'L')
```

Output:

```python
{'data': (2080565403600, False), 'strides': None, 'descr': [('', '<f8')], 'typestr': '<f8', 'shape': (29118,), 'version': 3}
1
Traceback (most recent call last):
  File ".\test.py", line 333, in <module>
    grayImage = Image.fromarray (testArray, mode = 'L')
  File "D:\ProgramData\Anaconda3\envs\vtkvista37env\lib\site-packages\PIL\Image.py", line 2694, in fromarray
    size = shape[1], shape[0]
IndexError: tuple index out of range
```

Context in Image.py:

```python
    arr = obj.__array_interface__
    shape = arr["shape"]
    ndim = len(shape)
    strides = arr.get("strides", None)

    [some code for mode and dimensions]

    size = shape[1], shape[0]
```

I might suggest something like:

```python
    size = 1 if ndim == 1 else shape[1],  shape[0]
```

Thank you!

**Comment by radarhere** [comment]
Good suggestion. I've created PR #4608 to resolve this.

**Comment by jwesolo** [comment]
Many thanks!
