### ISSUE TITLE
Pillow appears to stop Ortho4XP from running

### ISSUE THREAD

**Issue by OldSubSailor** [python-pillow/Pillow#4632]
### What did you do? 
I tried to run Ortho4XP as I did in the past. I did remove and reinstall all related Homebrew and Python packages and am now getting this error. 
### What did you expect to happen? 
Ortho4XP to run as it did in the past (earlier this morning)

### What actually happened?
 It did not run 
```
Traceback (most recent call last):
  File "Ortho4XP_v130.py", line 9, in <module>
    import O4_Imagery_Utils as IMG
  File "./src/O4_Imagery_Utils.py", line 11, in <module>
    from PIL import Image, ImageFilter, ImageEnhance,  ImageOps
ImportError: cannot import name 'Image' from 'PIL' (unknown location)
```
### What are your OS, Python and Pillow versions?

* OS: macOS
* Python: 3.8.3
* Pillow: 7.1.2

```python
code goes here (This I guess?)
 1 #!/usr/bin/env python3
 2 import sys
 3 import os
 4 Ortho4XP_dir='..' if getattr(sys,'frozen',False) else '.'
 5 sys.path.append(os.path.join(Ortho4XP_dir,'src'))
 6 
 7 import O4_File_Names as FNAMES
 8 sys.path.append(FNAMES.Provider_dir)
 9 import O4_Imagery_Utils as IMG
10 import O4_Vector_Map as VMAP
11 import O4_Mesh_Utils as MESH
12 import O4_Mask_Utils as MASK
13 import O4_Tile_Utils as TILE
14 import O4_GUI_Utils as GUI
15 import O4_Config_Utils as CFG  # CFG imported last because it can modify other modules variables
16 
17 
18 cmd_line="USAGE: Ortho4XP_v130.py lat lon imagery zl (won't read a tile config)\n   OR:  Ortho4XP_v130.py lat lon (with existing tile config file)"
19 
20 if __name__ == '__main__':
21     if not os.path.isdir(FNAMES.Utils_dir):
22         print("Missing ",FNAMES.Utils_dir,"directory, check your install. Exiting.")
23         sys.exit()   
24     for directory in (FNAMES.Preview_dir, FNAMES.Provider_dir, FNAMES.Extent_dir, FNAMES.Filter_dir, FNAMES.OSM_dir,
25                       FNAMES.Mask_dir,FNAMES.Imagery_dir,FNAMES.Elevation_dir,FNAMES.Geotiff_dir,FNAMES.Patch_dir,
26                       FNAMES.Tile_dir,FNAMES.Tmp_dir):
27         if not os.path.isdir(directory):
28             try: 
29                 os.makedirs(directory)
30                 print("Creating missing directory",directory)
31             except: 
32                 print("Could not create required directory",directory,". Exit.")
33                 sys.exit()
34     IMG.initialize_extents_dict()
35     IMG.initialize_color_filters_dict()
36     IMG.initialize_providers_dict()
37     IMG.initialize_combined_providers_dict()
38     if len(sys.argv)==1: # switch to the graphical interface
39         Ortho4XP = GUI.Ortho4XP_GUI()
40 
41         Ortho4XP.mainloop()	    
42         print("Bon vol!")
43     else: # sequel is only concerned with command line 
44         if len(sys.argv)<3:
45             print(cmd_line); sys.exit()
46         try:
47             lat=int(sys.argv[1])
48             lon=int(sys.argv[2])
49         except:
50             print(cmd_line); sys.exit()
51         if len(sys.argv)==3:
52             try:
53                 tile=CFG.Tile(lat,lon,'')
54             except Exception as e:
55                 print(e)
56                 print("ERROR: could not read tile config file."); sys.exit()
57         else:
58             try:
59                 provider_code=sys.argv[3]
60                 zoomlevel=int(sys.argv[4])
61                 tile=CFG.Tile(lat,lon,'')
62                 tile.default_website=provider_code
63                 tile.default_zl=zoomlevel
64             except:
65                 print(cmd_line); sys.exit()
66         try:
67             VMAP.build_poly_file(tile)
68             MESH.build_mesh(tile)
69             MASK.build_masks(tile)
70             TILE.build_tile(tile)
71             print("Bon vol!")
72         except:
73             print("Crash!")
74  
75         




```

**Comment by hugovk** [comment]
Have you also re-installed Pillow?

What do you get for these commands?

```console
$ python --version
Python 3.8.3
$ python -m pip install pillow
Collecting pillow
  Using cached Pillow-7.1.2-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
Installing collected packages: pillow
Successfully installed pillow-7.1.2
$ python -c "from PIL import Image; print(Image.__version__)"
7.1.2
```

**Comment by OldSubSailor** [comment]
pip3 list
Package    Version    
---------- -----------
certifi    2020.4.5.1 
chardet    3.0.4      
Cython     0.29.18    
GDAL       2.4.2      
idna       2.9        
numpy      1.18.4     
Pillow     7.1.2      
pip        20.0.2     
pyproj     2.6.1.post1
requests   2.23.0     
Rtree      0.9.4      
setuptools 46.0.0     
Shapely    1.7.0      
urllib3    1.25.9     
wheel      0.34.2     
But what do I know? % 

A C program is like a fast dance on a newly waxed dance floor by people carrying razors.  -W.R.

And now for something completely different. -M.P

**Comment by hugovk** [comment]
Thanks, it could be you have more than one Python interpreter (and pip command) installed, it'd be good to also run the other commands.

**Comment by OldSubSailor** [comment]
ok, I shall give it a run

**Comment by OldSubSailor** [comment]
But what do I know? % python3 --version
Python 3.8.3
But what do I know? % python --version
Python 2.7.16
But what do I know? % python3 -m install pillow
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: No module named install
But what do I know? % pip3 install pillow
Requirement already satisfied: pillow in /usr/local/lib/python3.7/site-packages (7.1.2)
But what do I know? %  python3 -c "from PIL import Image; print(Image.__version__)"                                                   
Traceback (most recent call last):
  File "<string>", line 1, in <module>
ImportError: cannot import name 'Image' from 'PIL' (unknown location)
But what do I know? %

**Comment by hugovk** [comment]
Try `python3 -m pip install pillow` rather than `python3 -m install pillow` :)

**Comment by OldSubSailor** [comment]
oops, red face.
But what do I know? % python -m pip install pillow
/System/Library/Frameworks/Python.framework/Versions/2.7/Resources/Python.app/Contents/MacOS/Python: No module named pip
But what do I know? %

**Comment by OldSubSailor** [comment]
Last login: Tue May 19 10:40:39 on ttys000
But what do I know? % python3 -m pip install pillow
/Library/Frameworks/Python.framework/Versions/3.8/bin/python3: No module named pip.__main__; 'pip' is a package and cannot be directly executed
But what do I know? %

**Comment by OldSubSailor** [comment]
Also,
But what do I know? % pip3 install pip 
Requirement already satisfied: pip in /usr/local/lib/python3.7/site-packages (20.0.2)
But what do I know? % 

I wonder why it would not be in python3.8?

**Comment by hugovk** [comment]
Sounds similar to https://stackoverflow.com/a/41731443/724176


What do you get for these?

```
pip --version
pip3 --version
python3 -m ensurepip
python3 -m pip --version
python3 -m pip install pillow
```

**Comment by OldSubSailor** [comment]
But what do I know? % pip3 --version
pip 20.0.2 from /usr/local/lib/python3.7/site-packages/pip (python 3.7)
But what do I know? % python3 -m ensurepip
Looking in links: /var/folders/81/dknbj9t122v60nzlhfx5sspc0000gn/T/tmpgmyo7dtc
Collecting setuptools
Collecting pip
Installing collected packages: setuptools, pip
Successfully installed pip-19.2.3 setuptools-41.2.0
But what do I know? % python3 -m pip --version
pip 19.2.3 from /Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/site-packages/pip (python 3.8)
But what do I know? % python3 -m pip install pillow
Collecting pillow
  Downloading https://files.pythonhosted.org/packages/20/20/a0f9f20469aae7017a578fdc4c55ea18f7c8911d2d10668687f95748442b/Pillow-7.1.2-cp38-cp38-macosx_10_10_x86_64.whl (2.2MB)
     |████████████████████████████████| 2.2MB 2.1MB/s 
Installing collected packages: pillow
Successfully installed pillow-7.1.2
WARNING: You are using pip version 19.2.3, however version 20.1.1 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.
But what do I know? %

**Comment by hugovk** [comment]
Looks like we're nearly there. Could you try this?

```
python3 -c "from PIL import Image; print(Image.__version__)"
```

And we might as get the newest pip too:
```
python3 -m pip install --upgrade pip
```

**Comment by OldSubSailor** [comment]
% python3 -c "from PIL import Image; print(Image.__version__)"

7.1.2
But what do I know? % python3 -m pip install --upgrade pip

Collecting pip
  Using cached https://files.pythonhosted.org/packages/43/84/23ed6a1796480a6f1a2d38f2802901d078266bda38388954d01d3f2e821d/pip-20.1.1-py2.py3-none-any.whl
Installing collected packages: pip
  Found existing installation: pip 19.2.3
    Uninstalling pip-19.2.3:
      Successfully uninstalled pip-19.2.3
Successfully installed pip-20.1.1
But what do I know? %

**Comment by OldSubSailor** [comment]
Holy smokes, I sure seemed to have lost a lot:pip3 list
Package    Version
---------- -------
Pillow     7.1.2
pip        20.1.1
setuptools 41.2.0
But what do I know? %

**Comment by OldSubSailor** [comment]
This is what the Ortho4XP has one install:
# Install dependencies
brew install python gdal spatialindex p7zip

# Install package 
pip3 install wheel

# Install pyproj
pip3 install cython
pip3 install pyproj

# Install other dependencies
pip3 install numpy shapely rtree pillow requests

**Comment by OldSubSailor** [comment]
Well, I added wheel, because we were getting some sort of missing wheel error messages

**Comment by OldSubSailor** [comment]
just an FYI
brew list
cairo		freexl		giflib		jpeg		libmpc		libxml2		nss		pcre		python@3.8	unixodbc
cfitsio		gcc		glib		json-c		libpng		little-cms2	numpy		pixman		qt		webp
epsilon		gdal		gmp		krb5		libpq		lzo		openblas	poppler		readline	xerces-c
expat		gdbm		hdf5		libdap		libspatialite	mpfr		openjpeg	popt		spatialindex	xz
fontconfig	geos		isl		libffi		libtiff		netcdf		openssl@1.1	proj		sqlite		zstd
freetype	gettext		jasper		libgeotiff	libtool		nspr		p7zip		python		szip
But what do I know? %

**Comment by OldSubSailor** [comment]
So I guess that I need to start reinstalling the other pip things now?

**Comment by hugovk** [comment]
Yeah, so it looks like before, `pip3` was pointing to Python 3.7, and you'd installed Pillow (and other stuff) for Python 3.7, but `python3` was pointing to Python 3.8.

Now, looks like `pip3` points to Python 3.8 as well.

It can be quite confusing when this happens, and especially when you throw `pip` (pointing to 2.7, or could it even be 3.x) into the mix.

This is why it's recommended not to run `pip install X` or `pip3 install X`, but instead always use `python -m pip install X` or `python3 -m pip install X`, so you always know which Python interpreter you're installing for.

For more on this, see:

* https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by OldSubSailor** [comment]
I truly appreciate all your help, hugovk.  I believe that the homebrew master install does put python 3.7 into the mix, I do not know why, so I guess I need to ask them now.  
You had me doing a lot here, so I need to make sure that I understand the real fix so that I can help others on the X-Plane forum. Is the python3 -m pip install X the fix to all this?

**Comment by OldSubSailor** [comment]
I guess for now that I will go back and install PiPish this as per your instruction. If ortho works, I guess that we can close it?

**Comment by hugovk** [comment]
> Is the python3 -m pip install X the fix to all this?

Yes, in the future, if you see instructions like one of these:

```
pip install X
pip3 install X
```

It's generally better to do:

```
python3 -m pip install X
```

That way you know you're installing `X` for the same exact same Python you get when you run `python3`

**Comment by OldSubSailor** [comment]
Should be uninstall things before using the python3 -m method?

**Comment by hugovk** [comment]
I wouldn't worry too much about uninstalling old things.

**Comment by radarhere** [comment]
So were you able to run Ortho4XP in the end?

**Comment by OldSubSailor** [comment]
> So were you able to run Ortho4XP in the end?

Yes it appears to be so.  I have not to hear back from Ortho4XP, but one of the install steps included installing python from Homebrew along with other items. This version of Python was 3.7 and so we ended up having 3 versions of python on the Mac.  I cant help but feel that this was messing things up also. 
Again, thank you for all your help folks.
