### ISSUE TITLE
Cannot find pilfont

### ISSUE THREAD

**Issue by ozone89** [python-pillow/Pillow#4635]
### What did you do?
I tried to convert a BDF font using the pilfont utility, Pillow installed as per docs

### What did you expect to happen?
To at least find the utility

### What actually happened?
pilfont is nowhere to be found

### What are your OS, Python and Pillow versions?

* OS: Raspbian Buster (latest, updated)
* Python: 3.7.3
* pip: 20.1.1
* Pillow: 7.1.2

**Comment by hugovk** [comment]
pilfont has been moved to the https://github.com/python-pillow/pillow-scripts repo, installable via `python -m pip install pillow-scripts`.

I see https://pillow.readthedocs.io/en/stable/reference/ImageFont.html?highlight=pilfont#imagefont-module references it, let's update the docs.

**Comment by hugovk** [comment]
Please see PR https://github.com/python-pillow/Pillow/pull/4636.

**Comment by ozone89** [comment]
thank you! :smiley:
