### ISSUE TITLE
ImageFont cant find _imagingft C module when CV2 is also imported

### ISSUE THREAD

**Issue by IsCoelacanth** [python-pillow/Pillow#4648]
### What did you do?
I have a workflow where some of the image processing is done in Pillow and some in OpenCV(4.2.0) ImageFont can't load fonts when cv2 is also imported. Issue does not happen when cv2 is imported after PIL, only when cv2 is imported before PIL

### What did you expect to happen?
ImageFont Loads the font.
### What actually happened?
```shell
----> 1 font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf', size=28)

####/miniconda3/envs/image_env/lib/python3.6/site-packages/PIL/ImageFont.py in truetype(font, size, index, encoding, layout_engine)
    640
    641     try:
--> 642         return freetype(font)
    643     except OSError:
    644         if not isPath(font):

####/miniconda3/envs/image_env/lib/python3.6/site-packages/PIL/ImageFont.py in freetype(font)
    637
    638     def freetype(font):
--> 639         return FreeTypeFont(font, size, index, encoding, layout_engine)
    640
    641     try:

####/miniconda3/envs/image_env/lib/python3.6/site-packages/PIL/ImageFont.py in __init__(self, font, size, index, encoding, layout_engine)
    161         if layout_engine not in (LAYOUT_BASIC, LAYOUT_RAQM):
    162             layout_engine = LAYOUT_BASIC
--> 163             if core.HAVE_RAQM:
    164                 layout_engine = LAYOUT_RAQM
    165         elif layout_engine == LAYOUT_RAQM and not core.HAVE_RAQM:

####/miniconda3/envs/image_env/lib/python3.6/site-packages/PIL/ImageFont.py in __getattr__(self, id)
     41     # module placeholder
     42     def __getattr__(self, id):
---> 43         raise ImportError("The _imagingft C module is not installed")
     44
     45

ImportError: The _imagingft C module is not installed
```

I have confirmed and reinstalled the external libraries involved.
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 16.04
* Python: 3.6.0
* Pillow: 7.0.0.post3

```python
>>> import cv2
>>> from PIL import Image, ImageFilter, ImageDraw, ImageFont
>>> font = ImageFont.truetype('/usr/share/fonts/truetype/dejavu/DejaVuSansMono-Bold.ttf', size=28)
```

**Comment by hugovk** [comment]
I can't reproduce on macOS with OpenCV 3.4.9 or newest 4.2.0, with Pillow 7.2.0 (actually master version).

You're using Pillow 7.0.0.post3, which suggests this is [Pillow-SIMD](https://github.com/uploadcare/pillow-simd). Can you reproduce using "pure" Pillow?

**Comment by IsCoelacanth** [comment]
clean install from pip (`pip install --no-cache-dir pillow`)
Pillow 7.1.2 (from pip)
issue doesn't seem to happen. looks like an SIMD specific issue.

**Comment by hugovk** [comment]
Please could you report it over at https://github.com/uploadcare/pillow-simd/issues? Thanks!
