### ISSUE TITLE
Pillow7.1.2.tar.gz Installation error

### ISSUE THREAD

**Issue by vinayprydotinfotech** [python-pillow/Pillow#4654]
I have following error in alias python=python3.7.3 while installation of pillow7.1.2
![Pillow_error](https://user-images.githubusercontent.com/45288623/83228919-aa2ce980-a1a4-11ea-8c8c-285f13c56cf6.jpg)

**Comment by hugovk** [comment]
Please can you show your output for this?

```sh
python --version
sudo python --version
```

**Comment by vinayprydotinfotech** [comment]
i Have been using since a Month s python version is 3.7.3

I will put up that image P.F.A

**Comment by vinayprydotinfotech** [comment]
> Please can you show your output for this?
> 
> ```shell
> python --version
> sudo python --version
> ```

![Pillow_error](https://user-images.githubusercontent.com/45288623/83237831-26c6c480-a1b3-11ea-89d2-f3c873843146.jpg)

**Comment by vinayprydotinfotech** [comment]
sorry it my bad some issue from my system .  issue resolved only some dependencies error now
