### ISSUE TITLE
Propose to publish wheels for armv7/arm64

### ISSUE THREAD

**Issue by jokester** [python-pillow/Pillow#4656]
to make arm user's life easier :) 

Can this be done with TravisCI's build matrix in https://github.com/python-pillow/pillow-wheels/blob/master/.travis.yml ?

**Comment by hugovk** [comment]
See also https://github.com/python-pillow/Pillow/issues/4655.

**Comment by mattip** [comment]
xref python-pillow/pillow-wheels#147 which adds wheels for arm64 and PyPy

**Comment by radarhere** [comment]
Ok, https://github.com/python-pillow/pillow-wheels/pull/147 has been merged. arm64 wheels should be available with the next Pillow release, due out on July 1
