### ISSUE TITLE
APNG conversion issue

### ISSUE THREAD

**Issue by karolyi** [python-pillow/Pillow#4657]
Hey,

I tried to convert an APNG with Pillow and got a bad looking output. It seems that WEBP saving works a bit better but there are also problems. This issue is about converting an APNG into an APNG while having the same watermarking/thumbnailing as in #4644. I've attached a self-contained test code [apng-test.zip](https://github.com/python-pillow/Pillow/files/4705464/apng-test.zip) to reproduce the problem.

The used APNG is downloaded from https://en.wikipedia.org/wiki/APNG, the wikipedia article about APNG formats.

Hope to get this fixed soon, because I have to convert all APNG-s into WEBPs to be able to look half decent.

**Comment by radarhere** [comment]
While I recognise the output is still not good, on a practical level, I found that if you remove `disposals` from your save arguments, the disappearing effect is fixed.

![out](https://user-images.githubusercontent.com/3112309/83326226-7b526880-a2b5-11ea-8b73-cd34b71a9bbc.png)

**Comment by karolyi** [comment]
Interesting. Can you post the adjusted code please? I thought the `disposal` argument in the `save_kwargs` is that one.

**Comment by karolyi** [comment]
Oh, I misread, my bad. It's actually *removing* that argument that helps? Odd, one would think you'd have to add that back to the save parameters.

**Comment by karolyi** [comment]
Even if you remove the watermarking, you'll get a bad looking result after conversion:
![out](https://user-images.githubusercontent.com/987055/83326462-8afd8d00-a274-11ea-9e76-90da804fab80.png)

**Comment by radarhere** [comment]
I find that if you remove `disposals` from the save arguments, and run your code with #5126, the result looks correct.

**Comment by radarhere** [comment]
I think the reason that you don't need `disposals` when saving is that Pillow isn't giving you each frame as it was originally encoded, as a series of cropped regions to be combined later - it's applying disposals and blends to give you the combined result that a user would see. 

So by the same logic you shouldn't need `blend` when saving either.

**Comment by radarhere** [comment]
This should now be fixed in Pillow 8.1.0, due to be released in the next day or so.

**Comment by karolyi** [comment]
Hey,

it's a bit belated but can confirm it works with Pillow 10.x :)
