### ISSUE TITLE
Install command not work ("py" "python3")

### ISSUE THREAD

**Issue by samrrr** [python-pillow/Pillow#4661]
I am download python https://www.python.org/downloads/release/python-383/
I am try this commands:
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow
From this page https://pillow.readthedocs.io/en/stable/installation.html

But its fail on my 64x win. Because python command is "py" not "python3".

**Comment by radarhere** [comment]
If your python command is 'py', then you should run
```
py -m pip install --upgrade pip
py -m pip install --upgrade Pillow
```
