### ISSUE TITLE
EXIF tobytes: TypeError: bad operand type for abs(): 'tuple'

### ISSUE THREAD

**Issue by andreymal** [python-pillow/Pillow#4665]
*(It seems there is a lot of tobytes bugs... There is another one)*

I have a photo rotated by Windows Explorer and I want to exif_transpose it: https://cdn.everypony.ru/storage/01/42/24/2020/06/02/c2fe022fd2.jpg

It seems that EXIF is broken here, but some applications can read it. For example, Firefox and Chrome can rotate it properly. And I want to rotate it by Pillow, but it fails because of tobytes.

Could Pillow simply ignore invalid tags, for example?

```python
PIL.Image.open('c2fe022fd2.jpg').getexif().tobytes()
```

```
site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 282 had too many entries: 2, expected 1
  warnings.warn(
site-packages/PIL/TiffImagePlugin.py:588: UserWarning: Metadata Warning, tag 283 had too many entries: 2, expected 1
  warnings.warn(
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "site-packages/PIL/Image.py", line 3292, in tobytes
    return b"Exif\x00\x00" + head + ifd.tobytes(offset)
  File "site-packages/PIL/TiffImagePlugin.py", line 808, in tobytes
    data = self._write_dispatch[typ](self, *values)
  File "site-packages/PIL/TiffImagePlugin.py", line 692, in write_rational
    return b"".join(
  File "site-packages/PIL/TiffImagePlugin.py", line 693, in <genexpr>
    self._pack("2L", *_limit_rational(frac, 2 ** 32 - 1)) for frac in values
  File "site-packages/PIL/TiffImagePlugin.py", line 261, in _limit_rational
    inv = abs(val) > 1
TypeError: bad operand type for abs(): 'tuple'
```

**Comment by radarhere** [comment]
There is actually already a PR in the pipeline to fix the warnings and error that you've found - #4637

**Comment by andreymal** [comment]
Oops, I forgot to explore PRs :)

**Comment by radarhere** [comment]
That PR has now been merged, so this issue should be resolved with the next Pillow release, due on July 1.
