### ISSUE TITLE
PIL convert('ycbcr') gives different result from formula

### ISSUE THREAD

**Issue by BarCodeReader** [python-pillow/Pillow#4668]
### What did you do?
compare PIL convert('ycbcr') function with formula listed on wikipedia
### What did you expect to happen?
they should have the same result
### What actually happened?
they have different result
### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.4
* Pillow: 7.0.0

```python
# The formula of RGB to YCbCr is from Wiki: https://en.wikipedia.org/wiki/YCbCr
from PIL import Image
import numpy as np

# use PIL library
img = Image.open('any_image_you_have_in_hand.png').convert('RGB')
img, cb, cr = img.convert('YCbCr').split()
img = np.array(img).astype(np.float32) / 255.
print(img[:48,:48])

# use formula
def rgb_to_y(img_array):
    # formula is from wikipedia
    R,G,B = img_array[0], img_array[1], img_array[2]
    return 16. + (65.481 * R + 128.553 * G + 24.966 * B) / 255.

img2 = Image.open('any_image_you_have_in_hand.png').convert('RGB')
img2 = np.array(img2).transpose((2, 0, 1)).astype(np.float32) # c,h,w
img2 = rgb_to_y(img2) / 255.
print(img2[:48,:48])
```
different results will be generated...and I have no idea which one to use...

**Comment by radarhere** [comment]
Here is the formula that Pillow advertises as the one it uses for this conversion.

https://github.com/python-pillow/Pillow/blob/61a35f94cf8a217db3e67d32db943b05e593e781/src/libImaging/ConvertYCbCr.c#L17-L21

This is also listed on that wikipedia page, under [JPEG Conversion](https://en.wikipedia.org/wiki/YCbCr#JPEG_conversion).

**Comment by BarCodeReader** [comment]
> Here is the formula that Pillow advertises as the one it uses for this conversion.
> 
> https://github.com/python-pillow/Pillow/blob/61a35f94cf8a217db3e67d32db943b05e593e781/src/libImaging/ConvertYCbCr.c#L17-L21
> 
> This is also listed on that wikipedia page, under [JPEG Conversion](https://en.wikipedia.org/wiki/YCbCr#JPEG_conversion).

Thanks for this point.
Actually in wikipedia we have different formular, may I know why PIL choose this instead of the formula I used in my code? Is there a reason or I missed something?

**Comment by radarhere** [comment]
Just to show that Pillow is fully aware of this -
https://pillow.readthedocs.io/en/stable/handbook/concepts.html
> YCbCr (3x8-bit pixels, color video format)
Note that this refers to the JPEG, and not the ITU-R BT.2020, standard

https://stackoverflow.com/questions/7041172/pils-colour-space-conversion-ycbcr-rgb/7042835#7042835 may be of interest to you.

I'm really summarising the discussion in #1002.

**Comment by wiredfool** [comment]
I’m going to go out on a limb and say that that code predates Wikipedia.

But the more correct answer is that we aren’t converting from a digital component video colorspace, were converting from a raw RGB colorspace.

**Comment by BarCodeReader** [comment]
@radarhere Thanks for the information! 
I noticed that **img.convert()** provides an option to pass a matrix and perform the transformation we want, so I tried by defining the matrix below, following the **ITU-R BT.601** stated in wikipedia. now my code becomes something like this:
```
from PIL import Image
import numpy as np

# use PIL library
matrix = (65.481/255., 128.553/255., 24.966/255., 16,
          -37.797/255., -74.203/255., 112.0/255., 128,
          112.0/255., -93.786/255., -18.214/255., 128)

img = Image.open('any_image_you_have_in_hand.png').convert('RGB')
img, cb, cr = img.convert('RGB', matrix).split()
img = np.array(img).astype(np.float32) / 255.
print(img[:48,:48])

# use formula
def rgb_to_y(img_array):
    # formula is from wikipedia
    R,G,B = img_array[0], img_array[1], img_array[2]
    return 16. + (65.481 * R + 128.553 * G + 24.966 * B) / 255.

img2 = Image.open('any_image_you_have_in_hand.png').convert('RGB')
img2 = np.array(img2).transpose((2, 0, 1)).astype(np.float32) # c,h,w
img2 = rgb_to_y(img2) / 255.
print(img2[:48,:48])
```
but still, i got different results from these 2 methods...

**Comment by radarhere** [comment]
It looks like the difference is that Pillow is limiting RGB to an integer value between 0 and 255. In the last version of your code, if I replace
```python
return 16. + (65.481 * R + 128.553 * G + 24.966 * B) / 255.
```
with
```python
return np.rint(16. + (65.481 * R + 128.553 * G + 24.966 * B) / 255.)
```
Then both outputs match.

**Comment by BarCodeReader** [comment]
@radarhere Really thanks for your help!
