### ISSUE TITLE
Odd behaviour of ImageDraw.Draw.polygon

### ISSUE THREAD

**Issue by jmsteitz** [python-pillow/Pillow#4674]
### What did you do?
I drew two polygons, each specified by only two vertices that are both on a vertical or horizontal line.

### What did you expect to happen?
Expected to get a one pixel wide vertical and a one pixel wide horizontal line.

### What actually happened?
The vertical line shows but not the horizontal one.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04.4
* Python: 3.7.6
* Pillow: 7.1.1

```python
import numpy as np
from PIL import Image, ImageDraw
img = Image.new("L", size=(2,2), color=0)
ImageDraw.Draw(img).polygon([(0,0),(0,1)], outline=1, fill=1)
np.array(img)
```

gives

```python
array([[1, 0],
       [1, 0]], dtype=uint8)
```
but 
```python
import numpy as np
from PIL import Image, ImageDraw
img = Image.new("L", size=(2,2), color=0)
ImageDraw.Draw(img).polygon([(0,0),(1,0)], outline=1, fill=1)
np.array(img)
```
results in 
```python
array([[0, 0],
       [0, 0]], dtype=uint8)
```

**Comment by radarhere** [comment]
I understand that you might be trying to just raise a general inconsistency with `polygon`, but, on a practical level, if you change `polygon` to `line`, and remove the `outline` argument, the following works.

```python
import numpy as np
from PIL import Image, ImageDraw
img = Image.new("L", size=(2,2), color=0)
ImageDraw.Draw(img).line([(0,0),(1,0)], fill=1)
print(np.array(img))
```
```
[[1 1]
 [0 0]]
```

**Comment by radarhere** [comment]
I've created PR #4675 to fix this.

**Comment by jmsteitz** [comment]
Thanks for the PR and the suggested workaround! We encountered the problem while generating mask images with arbitrary polygons that sometimes happen to be degenerated, i.e. falling onto a horizontal line.
