### ISSUE TITLE
getexif() crashes when reading empty EXIF data from a PNG file saved by RawTherapy 5.8

### ISSUE THREAD

**Issue by RomanKosobrodov** [python-pillow/Pillow#4676]
### What did you do?
Converted a RAW file to PNG using RawTherapy 5.8.
Opened the image file with Pillow and called getexif()

### What did you expect to happen?
Since the file has no EXIF data, the expected output is None or an empty dictionary.
`pyexiv2` returns an empty dictionary.

### What actually happened?
```
Traceback (most recent call last):
  File "/home/roman/Projects/pillow-png-getexif/read_png_exif.py", line 8, in <module>
    exif = img.getexif()
  File "/home/roman/Projects/mikula/venv/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 951, in getexif
    self._exif.load(exif_info)
  File "/home/roman/Projects/mikula/venv/lib/python3.8/site-packages/PIL/Image.py", line 3271, in load
    self._info = TiffImagePlugin.ImageFileDirectory_v1(self.head)
  File "/home/roman/Projects/mikula/venv/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 900, in __init__
    super().__init__(*args, **kwargs)
  File "/home/roman/Projects/mikula/venv/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 466, in __init__
    raise SyntaxError("not a TIFF file (header %r not valid)" % ifh)
SyntaxError: not a TIFF file (header b'\x00\x00\x11\x00\x00\x01\x04\x00' not valid)
```

### What are your OS, Python and Pillow versions?
* OS:  Ubuntu 20.04
* Python: Python version 3.8.2 [GCC 9.3.0]
* Pillow: 7.1.1

```python
fn = "mug_small.png"
img = Image.open(fn)
exif = img.getexif()
```
The code and the test image are available on [github](https://github.com/RomanKosobrodov/pillow-png-getexif).

**Comment by radarhere** [comment]
The file actually does have EXIF data. It may not have an eXIf chunk, but it has a zTXt chunk, "Raw profile type exif". See https://exiftool.org/TagNames/PNG.html#TextualData for some more information.

Pillow has an assumption that EXIF data starts with "Exif\x00\x00", but that is not the case for your image. Here is some code as a demonstration.

```python
from PIL import Image
img = Image.open("mug_small.png")
if "Raw profile type exif" in img.info:
	rawProfileTypeExif = bytes.fromhex(
		"".join(img.info["Raw profile type exif"].split("\n")[3:])
	)
	if rawProfileTypeExif[:6] != "Exif\x00\x00":
		print("Fix missing EXIF prefix")
		img.info["exif"] = b"Exif\x00\x00"+rawProfileTypeExif
exif = img.getexif()
print(exif)
```

Is the image that you've linked to able to be added to the test suite under the Pillow licemse?

**Comment by RomanKosobrodov** [comment]
The image is generated with RawThreapy which is popular image-editing software at least in the Linux world. It would be great if Pillow could support it. I updated the licence on the repository to MIT which should allow you to use the image in your tests.

**Comment by radarhere** [comment]
I've found an existing image with similar data in the test suite. I've created PR #4677 to resolve this.

**Comment by radarhere** [comment]
The PR has been merged, so the fix for your issue will be part of the next Pillow release, due out on July 1.
