### ISSUE TITLE
putalpha() added some black background to the output

### ISSUE THREAD

**Issue by thekillgfx** [python-pillow/Pillow#4687]
### What did you do?
I opened a .PNG image with PIL, then I've applicate some transparency and then saved it.
### What did you expect to happen?
The image saved properly with the transparency.
### What actually happened?
The image went saved with the trasparency as long with a black background. 
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 16.04.6 LTS
* Python: 3.6
* Pillow: 7.1.2

```python
    logo = Image.open('files/logo.png').convert('RGBA')
    logo.putalpha(180)
    logo.save('files/output.png', format='PNG')
```
![image](https://user-images.githubusercontent.com/39156526/84557177-2be65080-ad29-11ea-9e5e-e14afd24cd5d.png)

**Comment by nulano** [comment]
Can you please provide the original image? Running your code on the combined image in your post works properly for me.

![fr2](https://user-images.githubusercontent.com/3819630/84558072-51c32380-ad30-11ea-835e-11245c5a47b6.png)

**Comment by thekillgfx** [comment]
![logo](https://user-images.githubusercontent.com/39156526/84558149-ef1e5780-ad30-11ea-8c15-b2790009c365.png)
that should be it @nulano

**Comment by radarhere** [comment]
@thekillgfx your second post looks like it's been deleted

**Comment by nulano** [comment]
Checking with your deleted image from my email, I get a png with a semi-transparent black background as I would expect. Fully transparent pixels in images are often either black or white, but there is no requirement for either; `putalpha` just makes them semi-transparent.

If you only wish to modify the transparent pixels, the following code might help you:

```python
from PIL import Image
with Image.open("file.png") as im:
    im2 = im.copy()
    im2.putalpha(180)
    im.paste(im2, im)
    im.save("file2.png")
```

**Comment by thekillgfx** [comment]
@nulano this code is working fine.
But why is this happening? Like operating directly on the image cause the problem, but doing the same thing on a copy let the problem away..

**Comment by nulano** [comment]
Like I said, `putalpha` modifies all pixels by setting their alpha value, so fully transparent pixels become only partially transparent. The code I posted above first sets (`putalpha`) all pixels to semi-transparent in a copy, then copies (`paste`) all pixels to the original image using the original alpha values as a mask. This means that fully transparent pixels in the original image are skipped during the `paste`.

**Comment by thekillgfx** [comment]
Ok, I got it. Wouldn't be better if the `putalpha` function manage this kind of situations by itself without need to work on a copy to then merge the Images?

**Comment by nulano** [comment]
From [the docs](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.putalpha):
> **Image.putalpha(alpha)**
> Adds or replaces the alpha layer in this image. If the image does not have an alpha layer, it’s converted to “LA” or “RGBA”. The new layer must be either “L” or “1”.

So the function is designed to replace the layer, not multiply/blend it.

I can't find a function which only works on one colour band, most functions apply the same operation to each band. The only other way I can think of doing this, is to extract the alpha band from the image using `getdata('A')`, update the alpha band using e.g. `eval` or `point`, then replace the alpha band in the original image using `putalpha`. I haven't tested this to see which is faster.

**Comment by radarhere** [comment]
@thekillgfx are you happy for this to be closed? It seems to me like your problem has been solved and your question answered

**Comment by AdhTri-001** [comment]
@nulano You are awesome my dude. Thanks

**Comment by relector-tuxnix** [comment]
I ended up using the below solution to replace full transparency (255, 255, 255, 0) with a substitute colour:

```
try: 
                
    with Image.open(imagePath) as im:
  
        width = im.size[0] 
        height = im.size[1] 
  
        for i in range(0, width): # process all pixels

            for j in range(0, height):

                data = im.getpixel((i,j))
     
                #print(data)

                if data[0] == 255 and data[1] == 255 and data[2] == 255 and data[3] == 0:

                    im.putpixel((i,j), (155, 155, 155))

        im.convert('RGB').save(outFile, 'JPEG')

except Exception as why: 

    print("Cannot convert: %s -> %s" % (imagePath, why))
```
