### ISSUE TITLE
Unable to draw a unicode character with a variation selector

### ISSUE THREAD

**Issue by danny0838** [python-pillow/Pillow#4690]
### What did you do?
Draw a char with a variation selector `\u51DE\U000E010B` using [HanaMin](http://fonts.jp/hanazono/). (See code below)

### What did you expect to happen?
The output should be ![圖片](https://user-images.githubusercontent.com/531417/84581543-e30bc600-ae14-11ea-88c6-9a3379949624.png).

### What actually happened?
The output is ![image](https://user-images.githubusercontent.com/531417/84581562-06cf0c00-ae15-11ea-86cf-92f317de794e.png).

### What are your OS, Python and Pillow versions?

* OS: Windows 7 SP1
* Python: 3.8.1
* Pillow: 7.1.2

```python
from PIL import Image, ImageDraw, ImageFont

text = "\u51DE\U000E010B"
font = "HanaMinA.ttf"

img = Image.new('RGBA', (160, 80))
draw = ImageDraw.Draw(img)
fnt = ImageFont.truetype(font, 80)
dx, dy = fnt.getoffset(text)
draw.text((-dx, -dy), text, font=fnt, fill="#000")
img.save("image.png")
```

**Comment by nulano** [comment]
Combined unicode characters require the Raqm library. To make sure you are using Raqm, you can use `fnt = ImageFont.truetype(font, 80, layout_engine=ImageFont.LAYOUT_RAQM)`, but this is the default, so you will have to install Raqm first.

**Comment by danny0838** [comment]
After some work raqm seems to be installed correctly:

```python
from PIL import Image, ImageDraw, ImageFont, features
print (features.check('raqm'))
```

which reports "True".

However, running the original code still gets an error:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    dx, dy = fnt.getoffset(text)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 338, in getoffset
    return self.font.getsize(text)[1]
OSError: invalid face handle
Segmentation fault
```

For another case of text = `"a\u0308\u0325"`, it's also not working, but simply:

```
Segmentation fault
```

More badly, using text = `"N"` also fails after installing raqm:

```
Traceback (most recent call last):
  File "test.py", line 9, in <module>
    dx, dy = fnt.getoffset(text)
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFont.py", line 338, in getoffset
    return self.font.getsize(text)[1]
OSError: invalid face handle
Segmentation fault
```

If I add `layout_engine=ImageFont.LAYOUT_BASIC` to `ImageFont.truetype`, no error happens again (but the image issue still persists)

**Comment by radarhere** [comment]
Just to try and help debug the situation, if you use `ImageFont.LAYOUT_RAQM` with a font other than HanaMin, say https://github.com/python-pillow/Pillow/raw/master/Tests/fonts/FreeMono.ttf, does it produce an `OSError` or segmentation fault then?

**Comment by nulano** [comment]
I don't think `Pillow/depends/install_raqm.sh` is compatible with Windows, I'm actually somewhat surprised you even managed to get it to load. You can use the scripts from `winbuild` in master to build Raqm on Windows. There is also an unofficial prebuilt version from @cgohlke if you search on the internet (I'm not sure if he is ok with linking to it?).

**Comment by danny0838** [comment]
Sorry I forgot to mention, for easier test of raqm I was using another device:
- OS: Ubuntu 16.04.6 LTS
- Python: 3.8.3
- Pillow: 7.1.2

Using FreeMono.ttf gets same error.

**Comment by nulano** [comment]
> Sorry I forgot to mention, for easier test of raqm I was using another device:
> 
> * OS: Ubuntu 16.04.6 LTS
> * Python: 3.8.3
> * Pillow: 7.1.2
> 
> Using FreeMono.ttf gets same error.

In that case you have probably run into #3066; the suggested workaround there is to compile Pillow from source.

**Comment by danny0838** [comment]
@nulano Can you be more clear about how to build Pillow from source? And which version?

**Comment by nulano** [comment]
The instructions are [here](https://pillow.readthedocs.io/en/stable/installation.html#building-on-linux). Any version should be fine.

**Comment by danny0838** [comment]
Thank you. I finally get it work on the Ubuntu. But still not yet get libraqm work on Windows. :(

**Comment by nulano** [comment]
Is the Windows issue with building it or enabling it? To let Pillow detect it, it is necessary to add it to PATH before running Python, or to copy it to the Python or Pillow directory.
