### ISSUE TITLE
Why does the app crash when using the KivyMD and asks for a PIL?

### ISSUE THREAD

**Issue by grabtrap** [python-pillow/Pillow#4699]
Used buildozer
```
Traceback (most recent call last):
File "/home/m/8/.buildozer/android/app/main.py", line 10, in <module>
File "/home/m/8/.buildozer/android/platform/build-armeabi-v7a/build/python-installs/myapp/kivymd/uix/filemanager.py", line 119, in <module>
ModuleNotFoundError: No module named 'PIL'
Python for android ended.
```
buildozer.spec:
`requirments = python3, kivy, kivymd, yandex-geocoder, requests, mapview, geopy`
I tried to add pillow / PIL in the requirements, but then the application is not going to

**Comment by radarhere** [comment]
Hi. The question of why KivyMD requires PIL seems like it is better asked over at https://github.com/HeaTTheatR/KivyMD

I feel like your last sentence was cut off. You tried to add PIL, 'but then the application is not going to'...? What is your concern?

**Comment by grabtrap** [comment]
@radarhere I meant that I can not add PIL to the requirements, the application is not built through Buildozer

**Comment by radarhere** [comment]
As your traceback says, KivyMD uses PIL - https://github.com/HeaTTheatR/KivyMD/blob/d4fb15aef32f94f6333e2ee34dc09f60e8f35496/kivymd/uix/filemanager.py#L135

I see now that you have actually asked the question on the KivyMD GitHub, and received an answer - https://github.com/HeaTTheatR/KivyMD/issues/353#issuecomment-643832007
> specify the PIL package in the specification file to dependency of your project. If you have problems installing the PIL package, contact the Kivy community for help.

I think that the Kivy Users Forum might be a better group of people than us to help you with this problem - https://kivy.org/#forum. It has topics like this that may be helpful to you
- https://groups.google.com/forum/embed/?place=forum/kivy-users&hidesubject=true&hideforumtitle=true&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fkivy.org%2F%23#!searchin/kivy-users/pil/kivy-users/ZHhxg9DuMPs/A42oB6bYCAAJ
- https://groups.google.com/forum/embed/?place=forum/kivy-users&hidesubject=true&hideforumtitle=true&showsearch=true&showpopout=true&parenturl=https%3A%2F%2Fkivy.org%2F%23#!searchin/kivy-users/android$20no$20module$20named$20pil/kivy-users/rTPrHw3mhX4/FzJer9P_CAAJ
