### ISSUE TITLE
dlopen failed cannot locate local symbol

### ISSUE THREAD

**Issue by fahadali32** [python-pillow/Pillow#4717]
### What did you do?
I just install pillow for opencv 
my phone is xioami android pi 
### What actually happened?
dlopen failed....
### What are your OS, Python and Pillow versions?

* OS: Android pi
* Python: 3.8.3
* Pillow: 
Please help me i am beginer/... I'm use this on mobile for checking .. I am also install opencv on laptop using pip but here  i can't do this ./.

```python
site-packages/cv2/__init__.py", line 86, in bootstrap   
  import cv2                                        ImportError: dlopen failed: 
cannot locate symbol 
"_ZN6google8protobuf8internal17UnknownFieldParseEjPNS1_25InternalMetadataWithArenaEPKcPNS1_12ParseContextE" referenced by 
"/data/data/com.termux/files/usr/lib/libopencv_dnn.so.4.2.0"...                                    >>>
```

**Comment by radarhere** [comment]
The error looks like it relates to opencv/cv2, not Pillow. Are you sure you have come to the right place?

https://github.com/skvark/opencv-python/issues might be relevant GitHub project for this, or StackOverflow could be helpful. There's a user called 'hyperturtle' over here - https://gitter.im/termux/termux?at=5dafa19414d55a37855acaa4 - that seems to be reporting a similar issue to you.

**Comment by fahadali32** [comment]
but it's not work can tell me what i am doing now? Same erorr

**Comment by radarhere** [comment]
Without Googling, I don't know what the solution to your problem is. This isn't the right place to ask your question. This GitHub project is about the Python Pillow library, not OpenCV.
