### ISSUE TITLE
Line width is broken for super long lines

### ISSUE THREAD

**Issue by FloraCanou** [python-pillow/Pillow#4718]
Code for two images with diagonal lines differing only in coordinates of the points: 

```python
from PIL import Image, ImageDraw

im_size = 1600

im1 = Image.new ('RGB', (im_size, im_size), (255, 255, 255))
draw1 = ImageDraw.Draw (im1)
point1 = ((-16000, -16000), (16000, 16000))
draw1.line (point1, fill = (0, 255, 0), width = 2)
im1.save ("./im1.png", "PNG", optimize = True)

im2 = Image.new ('RGB', (im_size, im_size), (255, 255, 255))
draw2 = ImageDraw.Draw (im2)
point2 = ((-16400, -16400), (16400, 16400))
draw2.line (point2, fill = (0, 255, 0), width = 2)
im2.save ("./im2.png", "PNG", optimize = True)
```

Python 3.8.2, Pillow 7.1.2 on Windows 10

Result: 
![im1](https://user-images.githubusercontent.com/33727311/85308817-4b793800-b4e4-11ea-8385-90377caf5a1c.png)
![im2](https://user-images.githubusercontent.com/33727311/85308824-4f0cbf00-b4e4-11ea-89d1-b9eb2525a9ae.png)

Seems something strange happens if the coordinate difference in either dimension goes beyond 32768. 

Not adding `width = 2` would be fine. 

I hope this will get fixed. My work involves mass auto-generated coordinates, and managing them within a bounded region without changing their appearance on the image seems too difficult a task.

**Comment by hugovk** [comment]
Can reproduce on macOS, Python 3.8.3 and Pillow master.

Quick guess: the lower C layer is using `int`s for drawing, which are ["Capable of containing at least the [−32,767, +32,767] range"](https://en.wikipedia.org/wiki/C_data_types#Main_types) and the +32768 x and y offsets trigger this undefined behaviour.

**Comment by radarhere** [comment]
Quick guess is right. I've created PR #4721 to resolve this.
