### ISSUE TITLE
RGBA PNG image read problem

### ISSUE THREAD

**Issue by spital** [python-pillow/Pillow#4727]
### What did you do?

Tried to read PNG

### What did you expect to happen?

RGBA imported correctly as an array of tuples length 4

### What actually happened?

imported only as an array of 'int'

### What are your OS, Python and Pillow versions?

* OS: 
Fedora 31 x64
* Python: 
python --version
Python 3.7.7

* Pillow: 
7.1.2

test code attached
[pillow_rgba_png_problem.zip](https://github.com/python-pillow/Pillow/files/4826336/pillow_rgba_png_problem.zip)

**Comment by hugovk** [comment]
For reference, test code is:

# requirements.txt
```
imageio
Pillow
```

# test.py
```python


# sudo pip3 install -r requirements.txt -U


import imageio

import PIL

assert PIL.__version__ >= '7.1.2'
for filename in ('0307.png','0300.png'):
  im1 = imageio.imread(filename)
  print('image "{}" has {} channels'.format(filename,im1.shape[2]))
  assert im1.shape[0] == 18 and im1.shape[1] == 1920
  assert im1.shape[2] in [3,4]
  # Pillow
  im = PIL.Image.open(filename)
  assert im.size == (1920, 18)
  pix = im.load()
  assert len(pix[0,0]) in [3,4]
  assert len(pix[1919,17]) in [3,4]
```

# 0300.png

![0300](https://user-images.githubusercontent.com/1324225/85595109-379f1480-b651-11ea-8f85-0aec08eabfa7.png)

# 0307.png

![0307](https://user-images.githubusercontent.com/1324225/85595151-408fe600-b651-11ea-8310-df93c473b77d.png)

**Comment by radarhere** [comment]
Here are some thoughts. 0307.png is read as RGB. The 0300.png is read as P. If you convert the P mode image to RGB, then your code passes.
```python
import PIL.Image

for filename in ('0307.png','0300.png'):
  # Pillow
  im = PIL.Image.open(filename)
  if im.mode == 'P':
  	im = im.convert('RGB')
  assert im.size == (1920, 18)
  pix = im.load()
  assert len(pix[0,0]) in [3,4]
  assert len(pix[1919,17]) in [3,4]
```

As evidence that they are different, here are screenshots from macOS Preview. One 'Is Indexed', the other is not.
![0307_preview](https://user-images.githubusercontent.com/3112309/85631199-6f8d7280-b6b8-11ea-8a53-d04a66e80a1e.png)
![0300_preview](https://user-images.githubusercontent.com/3112309/85631202-71573600-b6b8-11ea-8e42-02292d16dde3.png)

**Comment by radarhere** [comment]
Testing, I find that when imageio reads 0300.png, it goes through this section of code - https://github.com/imageio/imageio/blob/d1bd16e44390819ccfd5d9da96491758817abdc9/imageio/plugins/pillow.py#L721-L723 where imageio converts a P mode image to RGB or RGBA.

So that explains the difference. I don't think there's anything to do here, unless you have anything further to add.
