### ISSUE TITLE
Wrong ImageChops function names

### ISSUE THREAD

**Issue by nooruldeen** [python-pillow/Pillow#4728]
### What did you do?
Used ImageChops.logical_or 
### What did you expect to happen?
Pillow generates the union of two images 
### What actually happened?
Pillow returned image intersection instead

### What did you do?
Used ImageChops.logical_and
### What did you expect to happen?
Pillow generates the intersection of two images 
### What actually happened?
Pillow returned image union instead

### What are your OS, Python and Pillow versions?
* OS: Windows
* Python: 3.7
* Pillow: 7.1.2

```python
code goes here
```

**Comment by radarhere** [comment]
Hi. To start with the basics.
- 0 or 0 = 0
- 0 or 1 = 1
- 1 or 1 = 1
- 0 and 0 = 0
- 0 and 1 = 0
- 1 and 1 = 1

In 1 bit images, 0 is black and 1 is white.
- black or black = black
- black or white = white
- white or white = white
- black and black = black
- black and white = black
- white and white = white

This means that we are looking for the union or intersection of white shapes. I'm guessing you made the same mistake I did at first here, expecting the union and intersection of black shapes? Here is some code and images to visually demonstrate.
```python
from PIL import Image, ImageChops, ImageDraw
im = Image.new("1", (200, 200), 0)
d = ImageDraw.Draw(im)
d.ellipse((0, 0, 150, 150), 1)
im.save("im1.png")

im2 = Image.new("1", (200, 200), 0)
d2 = ImageDraw.Draw(im2)
d2.ellipse((50, 50, 200, 200), 1)
im2.save("im2.png")

ImageChops.logical_and(im, im2).save("im1_and_im2.png")
ImageChops.logical_or(im, im2).save("im1_or_im2.png")
```
- 1
![im1](https://user-images.githubusercontent.com/3112309/85685799-bdcf5f80-b712-11ea-9392-b5d443df7fb3.png)
- 2
![im2](https://user-images.githubusercontent.com/3112309/85685811-c0ca5000-b712-11ea-83b8-e7d29a05760e.png)
- AND
![im1_and_im2](https://user-images.githubusercontent.com/3112309/85685822-c3c54080-b712-11ea-9fe4-df375e4305d3.png)
- OR
![im1_or_im2](https://user-images.githubusercontent.com/3112309/85685829-c6279a80-b712-11ea-9489-875a61a7eabf.png)

Let us know if this was helpful or if you have further thoughts.

**Comment by nooruldeen** [comment]
Gotcha. Thanks for your prompt response. Closing the issue.
