### ISSUE TITLE
armbian install

### ISSUE THREAD

**Issue by speeskeek** [python-pillow/Pillow#4743]
**What did you do?**
python3 -m pip install --upgrade Pillow

**What did you expect to happen?**
pillow installed

**What actually happened?**
fatal error: Python.h: No such file or directory

**What versions of Pillow and Python are you using?**
Python 3.7.3

[Link topastebin](https://pastebin.com/g0mNCa5V)

**Comment by radarhere** [comment]
To give you a quick response, have you tried `apt-get install python-dev`?

**Comment by speeskeek** [comment]
simple as that ....
