### ISSUE TITLE
Proposition of code refactoring

### ISSUE THREAD

**Issue by lbteixeira** [python-pillow/Pillow#4754]
Hello, everyone.

I've been using Pillow for some parts of my PhD thesis, and it's been very useful for me. Because of this, I would like to find a way to contribute to make it even better, if I can.

My initial idea was to check the code base to find possible missing features I could implement. Nevertheless, I had some problem to do this, because I found the code was a little too difficult to read (for newcomers, at least). In my opinion, some part of this difficult is related too:

1. The package PIL has a lot of modules, it's not divided in subpackages.
2. Some modules are too long. For example, the module `Image.py` has more than 3000 lines, and the `Image` class alone has more than 2000 lines.
3. Many methods and functions are missing docstrings, or don't have names that make them easy to understand.
4. The "Pythonic" style isn't always used.

Would you be interested to make some refactoring on the code? If you like this idea, I could come up with some propositions for the reorganization of the module `Image.py`, for example, and we could discuss. After we agree on something, I would be happy to work on this topic.

Looking forward to cooperate with you!

**Comment by radarhere** [comment]
Hi. Congrats on being able to use Pillow for your PhD. It is good that you were able to do so, and that you appreciated it enough to want to contribute back.

What is your PhD thesis about? If you have a specialty in some kind of image manipulation, then maybe there is a related area of Pillow that you could work on.

Pillow values backwards compatibility highly, so if you attempt to remove classes or change function names, this may not be accepted, as it would break code for our users.

If you're interested in improving the documentation, that could be good, though do be aware that we don't just use docstrings, we also have a 'docs' directory - the combined result can be seen at https://pillow.readthedocs.io/en/latest/
If you would like to rework code to be more Pythonic, feel free to create a PR to make those suggestions.
In general, if you're looking for problems to solve, well... there are 181 issues that currently exist for you to choose from! Or 34 suggested solutions to problems that need to be checked.

**Comment by lbteixeira** [comment]
Hello, @radarhere.

My thesis is about digital image correlation to calculate displacement fields during mechanical tests. I don't do anything fancy related to the image treatment itself, my algorithm just uses Pillow to manipulate some images.

I understand backwards compatibility is really important, that's why I wanted to open this issue first to see what are your feelings about this kind of refactoring. I'll take a look on what I can do to help, privileging the open issues.
