### ISSUE TITLE
Wheel support for linux aarch64

### ISSUE THREAD

**Issue by odidev** [python-pillow/Pillow#4758]
**Summary**
Installing pillow on aarch64 via pip using command "pip3 install pillow" tries to build wheel from source code

**Problem description**
pillow don't have wheel for aarch64 on PyPI repository. So, while installing pillow via pip on aarch64, pip builds wheel for same resulting in it takes more time to install pillow. Making wheel available for aarch64 will benefit aarch64 users by minimizing pillow installation time.

**Expected Output**
Pip should be able to download pillow wheel from PyPI repository rather than building it from source code.

@pillow-team, please let me know if I can help you building wheel/uploading to PyPI repository. I am curious to make pillow wheel available for aarch64. It will be a great opportunity for me to work with you.

**Comment by radarhere** [comment]
Hmm. The expectation is that there should already be aarch64 wheels - https://pypi.org/project/Pillow/#files
- Pillow-7.2.0-cp35-cp35m-manylinux2014_aarch64.whl
- Pillow-7.2.0-cp36-cp36m-manylinux2014_aarch64.whl
- Pillow-7.2.0-cp37-cp37m-manylinux2014_aarch64.whl
- Pillow-7.2.0-cp38-cp38-manylinux2014_aarch64.whl

**Comment by hugovk** [comment]
@odidev Please could try installing with the verbose flag (and here's a few others to narrow things down a bit), and share the logs?


```sh
pip uninstall pillow -y
pip install pillow==7.2.0 --no-cache-dir --disable-pip-version-check -v > logs.txt
```

That should list each of the PyPI distribution files and the reason why something was skipped.

For example for me on macOS with Python 3.8:

```
...
  Skipping link: none of the wheel's tags match: cp37-cp37m-win32: https://files.pythonhosted.org/packages/75/f7/5487b57b9f908e2a952c2376ec6fddb21a02b1d7dd2f35d0b5dd79ac0005/Pillow-7.2.0-cp37-cp37m-win32.whl#sha256=c79f9c5fb846285f943aafeafda3358992d64f0ef58566e23484132ecd8d7d63 (from https://pypi.org/simple/pillow/) (requires-python:>=3.5)
  Skipping link: none of the wheel's tags match: cp37-cp37m-win_amd64: https://files.pythonhosted.org/packages/36/fd/f83806d04175c0a58332578143ee7a9c5702e6e0f134e157684c737ae55b/Pillow-7.2.0-cp37-cp37m-win_amd64.whl#sha256=d350f0f2c2421e65fbc62690f26b59b0bcda1b614beb318c81e38647e0f673a1 (from https://pypi.org/simple/pillow/) (requires-python:>=3.5)
  Found link https://files.pythonhosted.org/packages/53/7d/c0db10e5f990905aa4bc4f8166414d8a30fb766c1624ced9fe9a43a211d9/Pillow-7.2.0-cp38-cp38-macosx_10_10_x86_64.whl#sha256=6d7741e65835716ceea0fd13a7d0192961212fd59e741a46bbed7a473c634ed6 (from https://pypi.org/simple/pillow/) (requires-python:>=3.5), version: 7.2.0
  Skipping link: none of the wheel's tags match: cp38-cp38-manylinux1_i686: https://files.pythonhosted.org/packages/d0/6e/89afd38b5a0d1a07d2e3c7aa282df0b20eddf0802b4e6c8f8c8d0d629039/Pillow-7.2.0-cp38-cp38-manylinux1_i686.whl#sha256=edf31f1150778abd4322444c393ab9c7bd2af271dd4dafb4208fb613b1f3cdc9 (from https://pypi.org/simple/pillow/) (requires-python:>=3.5)
...
  Downloading Pillow-7.2.0-cp38-cp38-macosx_10_10_x86_64.whl (2.2 MB)
...
```

**Comment by hugovk** [comment]
A quick test on Travis CI with AArch64 (aka ARM64) and Xenial installed the wheels okay for Python 3.5-3.8:


```console
$ pip install -U pillow
Collecting pillow
  Downloading Pillow-7.2.0-cp35-cp35m-manylinux2014_aarch64.whl (2.2 MB)
Installing collected packages: pillow
Successfully installed pillow-7.2.0
```
https://travis-ci.org/github/hugovk/test/jobs/704653823#L120


```console
$ pip install -U pillow
Collecting pillow
  Downloading Pillow-7.2.0-cp36-cp36m-manylinux2014_aarch64.whl (2.2 MB)
Installing collected packages: pillow
Successfully installed pillow-7.2.0
```
https://travis-ci.org/github/hugovk/test/jobs/704653822

```console
$ pip install -U pillow
Collecting pillow
  Downloading Pillow-7.2.0-cp37-cp37m-manylinux2014_aarch64.whl (2.2 MB)
Installing collected packages: pillow
Successfully installed pillow-7.2.0
```
https://travis-ci.org/github/hugovk/test/jobs/704653821#L120

```console
$ pip install -U pillow
Collecting pillow
  Downloading Pillow-7.2.0-cp38-cp38-manylinux2014_aarch64.whl (2.2 MB)
Installing collected packages: pillow
Successfully installed pillow-7.2.0
```
https://travis-ci.org/github/hugovk/test/jobs/704653820#L120

@odidev Which Python and OS versions are you using?

**Comment by Dish1306** [comment]
Hi @hugovk,

Python: Python3.8. 
OS: linux 5.4.0-37-generic

I am able to successfully install pillow with the help of pillow's wheel for aarch64 but it is taking around 25 secs to install pillow. I am attaching the logs for your reference. 
[logs.txt](https://github.com/python-pillow/Pillow/files/4869873/logs.txt)

Thanks

**Comment by odidev** [comment]
Hi @hugovk,

Python: Python3.8.
OS: linux 5.4.0-37-generic

I am able to successfully install pillow with the help of pillow's wheel for aarch64 but it is taking around 25 secs to install pillow. I am attaching the logs for your reference.
[logs.txt](https://github.com/python-pillow/Pillow/files/4869966/logs.txt)


Thanks

**Comment by hugovk** [comment]
That's good news it's installing with the wheel!

I see in the logs it's matching and downloading the wheel:

```
...
  Found link https://files.pythonhosted.org/packages/72/01/71f076c58ea64cc80a3db19580ef2c961518d999275afb9eec16032af294/Pillow-7.2.0-cp38-cp38-manylinux2014_aarch64.whl#sha256=5e51ee2b8114def244384eda1c82b10e307ad9778dac5c83fb0943775a653cd8 (from https://pypi.org/simple/pillow/) (requires-python:>=3.5), version: 7.2.0
...
  Downloading Pillow-7.2.0-cp38-cp38-manylinux2014_aarch64.whl (2.2 MB)
...
```

About the time, not sure what to suggest. I see Travis took 23s, 5s, 8s and 8s respectively for the builds, so 1/4 is not that far off from what you saw. Perhaps a question for pip?

Anyway, I'm happy to see it installing the wheel and not building from source, and 7.2.0 is first release with these wheels so good timing :)

Is there anything further you think we can check with these wheels? If you'd like to see the details, https://github.com/python-pillow/pillow-wheels/pull/147 is the PR and repo where they're built.

**Comment by odidev** [comment]
@hugovk Thank you for the help. 
In my opinion for now timing can not be reduced further. So, you can close this issue.

Thanks

**Comment by odidev** [comment]
@hugovk, Manylinux2014_aarch64 container has patchelf issue which has been fixed via PR#739. May I know when the next release for pillow is scheduled?

**Comment by radarhere** [comment]
Pillow 8.0.0 is due out on October 15.

**Comment by makuser** [comment]
The wheel will not be installed on the latest Raspberry OS if set to 64bit. Python 3.7.3 is installed there and once you set it in the boot config, the platform is then no longer armv7l but aarch64, so theoretically it should work, but pip shows this:
```
    Skipping link https://files.pythonhosted.org/packages/51/59/705a8792244098c3e1b217ddf7567d5f5bcbdef4486c98a9d26a1fa1e4a4/Pillow-7.2.0-cp37-cp37m-manylinux2014_aarch64.whl#sha256=9ad7f865eebde135d526bb3163d0b23ffff365cf87e767c649550964ad72785d (from https://pypi.org/simple/pillow/) (requires-python:>=3.5); it is not compatible with this Python
```

**Comment by radarhere** [comment]
That doesn't sound like a problem with the wheel itself, but with pip identifying your environment.
