### ISSUE TITLE
Processing big images

### ISSUE THREAD

**Issue by welrbraga** [python-pillow/Pillow#4761]
Hi guys,

I'm a newbie with Pillow, but I have giant problem to solve. I have approximately 8milions of images (JPG, TIFF, and some different RAW types) to process (almost 200TiB of files) and transform in "tiles" (I'm using Deepzoom, that use Pillow to do the magic).

In my tests it was everything OK until I found a bigger image with almost 200mpixels, when the system crashed with this exception:

```
Traceback (most recent call last):
[...]
  File "/home/wbraga/Git/dzi-tools/.nox/teste_mosaico/lib/python3.8/site-packages/PIL/Image.py", line 2868, in _open_core
    _decompression_bomb_check(im.size)
  File "/home/wbraga/Git/dzi-tools/.nox/teste_mosaico/lib/python3.8/site-packages/PIL/Image.py", line 2791, in _decompression_bomb_check
    raise DecompressionBombError(
PIL.Image.DecompressionBombError: Image size (199968786 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
```

After view some code I arrived to the line 84 on site-packages/PIL/Image.py, with this formule:

`MAX_IMAGE_PIXELS` = int(1024 * 1024 * 1024 // 4 // 3)

where I changed to:

`MAX_IMAGE_PIXELS = int(1024 * 1024 * 1024 * 2 // 4 // 3)`

... and after that my code ran. Not fine, yet, but ran. The image was processed but I'm receiving this warning bellow:

```
 /home/wbraga/Git/dzi-tools/.nox/teste_mosaico/lib/python3.8/site-packages/Pillow-7.1.2-py3.8-linux-x86_64.egg/PIL/Image.py:2797: DecompressionBombWarning: Image size (199968786 pixels) exceeds limit of 178956970 pixels, could be decompression bomb DOS attack.
  warnings.warn(
```

My doubt is: Is there a more easy way to change this (a variable, atribute, function...) or in fact it is hardcoded?

Thanks for an help or suggest.

* OS: Ubuntu Linux 20.04 / Ubuntu Linux 16.04 
* Python: 3.8.2  / 3.8.3
* Pillow: 7.2.0 / 7.0.0

**Comment by radarhere** [comment]
Here is a snippet of the Pillow source code.

https://github.com/python-pillow/Pillow/blob/b9f1add34b0731a6f0e8ae23676109d428aeecda/src/PIL/Image.py#L2825-L2836

The warning is triggered when greater than the value of `MAX_IMAGE_PIXELS`, the error is triggered when greater than double the value of `MAX_IMAGE_PIXELS`. If you have managed to avoid the error, but not the warning, then it would sound like you've successfully increased `MAX_IMAGE_PIXELS`, just not enough.

To change `MAX_IMAGE_PIXELS`, you don't need to modify the source code. You can change it from the outside by
```python
from PIL import Image
Image.MAX_IMAGE_PIXELS = int(1024 * 1024 * 1024 * 2 // 4 // 3)
```

**Comment by radarhere** [comment]
Does that answer your question?
