### ISSUE TITLE
Can't use PIL with Pillow 7.2

### ISSUE THREAD

**Issue by nesrinebnh** [python-pillow/Pillow#4766]
I tried to use imageio.imread but it's saying PIL module not named, so i installed pillow with the following command pip install pillow but it is already installed the version is 7.2.
I am using virtualenv, i installed tensorflow2.2, it requires Pillow 7.2 but seems PIL not found

* OS: windows10
* Python: python-3.8.4rcr1
* Pillow: 7.2

**Comment by radarhere** [comment]
Is it possible that pip is running on a different version of Python to what you are using the rest of the time? Could you try installing Pillow using [`python3 -m pip install Pillow`](https://pillow.readthedocs.io/en/stable/installation.html#basic-installation) (or whatever your Python command is if not 'python3')?

**Comment by nesrinebnh** [comment]
> Is it possible that pip is running on a different version of Python to what you are using the rest of the time? Could you try installing Pillow using [`python3 -m pip install Pillow`](https://pillow.readthedocs.io/en/stable/installation.html#basic-installation) (or whatever your Python command is if not 'python3')?

i get this message when i try your command
Requirement already satisfied: Pillow in c:\users\asus\desktop\flank-tutorial\mnist\gputest\lib\site-packages (7.2.0)

**Comment by radarhere** [comment]
For comparison then, could you provide the output of this?
```python
import tensorflow
print(tensorflow)
```

**Comment by nesrinebnh** [comment]
> ```python
> import tensorflow
> print(tensorflow)
> ```

when i try what you told me
import tensorflow 
print(tensorflow)
print(tensorflow.__version__)
i get:
2020-07-09 11:26:33.101147: I tensorflow/stream_executor/platform/default/dso_loader.cc:44] Successfully opened dynamic library cudart64_101.dll
<module 'tensorflow' from 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\lib\\site-packages\\tensorflow\\__init__.py'>      
2.2.0

**Comment by radarhere** [comment]
I am surprised that you're able to import tensorflow, but not Pillow, given the similarity of the paths. Are you modifying `sys.path` in any way?

```python
import sys
print(sys.path)
```

**Comment by nesrinebnh** [comment]
> ```python
> import sys
> print(sys.path)
> ```

i get this
['C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\Scripts\\python38.zip', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\DLLs', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\lib', 
'c:\\users\\asus\\appdata\\local\\programs\\python\\python38', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\lib\\site-packages']

**Comment by nesrinebnh** [comment]
i want to mention that i am using an empty .py file.
The only thing i did in this file is import PIL but just couldn't

**Comment by radarhere** [comment]
For lack of other ideas, could you show the full traceback of the error when you try to import PIL?

**Comment by nesrinebnh** [comment]
> For lack of other ideas, could you show the full traceback of the error when you try to import PIL?

Traceback (most recent call last):
  File "test.py", line 5, in <module>
    import PIL
ModuleNotFoundError: No module named 'PIL'

**Comment by radarhere** [comment]
Ok, just because I feel like it is better to err on the side of too many questions rather than too few - you say that you can't import PIL when you run test.py. If you try to import PIL from the Python interpreter, does that work?

**Comment by nesrinebnh** [comment]
> Ok, just because I feel like it is better to err on the side of too many questions rather than too few - you say that you can't import PIL when you run test.py. If you try to import PIL from the Python interpreter, does that work?

no it doesn't work

**Comment by nulano** [comment]
Just to double-check, is the following the same if run from a file vs the interpreter?

> > ```python
> > import sys
> > print(sys.path)
> > ```
> 
> i get this
> 
> ```python
> ['C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\Scripts\\python38.zip', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\DLLs', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\lib', 
> 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\lib\\site-packages']
> ```

**Comment by nesrinebnh** [comment]
> Just to double-check, is the following the same if run from a file vs the interpreter?
> 
> > > ```python
> > > import sys
> > > print(sys.path)
> > > ```
> > 
> > 
> > i get this
> > ```python
> > ['C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\Scripts\\python38.zip', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\DLLs', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\lib', 
> > 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\lib\\site-packages']
> > ```

['', 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\python38.zip', 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\DLLs', 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib', 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38', 'C:\\Users\\ASUS\\AppData\\Roaming\\Python\\Python38\\site-packages', 'C:\\Users\\ASUS\\AppData\\Local\\Programs\\Python\\Python38\\lib\\site-packages']

not really the same but as mentioned i am using virtualenv

**Comment by nesrinebnh** [comment]
> Just to double-check, is the following the same if run from a file vs the interpreter?
> 
> > > ```python
> > > import sys
> > > print(sys.path)
> > > ```
> > 
> > 
> > i get this
> > ```python
> > ['C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\Scripts\\python38.zip', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\DLLs', 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38\\lib', 
> > 'c:\\users\\asus\\appdata\\local\\programs\\python\\python38', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest', 'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\lib\\site-packages']
> > ```

Btw, i tried to execute the file not in the virtualenv and it worked, but still don't understand why it is not working with virtualenv

**Comment by nulano** [comment]
> ```
> ['', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\python38.zip', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\DLLs', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38', 'C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages']
> ```
> not really the same but as mentioned i am using virtualenv

Is this when running the file? It looks like you are running the file without enabling the virtual environment. To run the file using the virtual environment, run it from the command prompt using the `python file.py` command with the virtual environment activated.

Why does tensorflow import properly both from the file and venv? I would guess you have tensorflow install both in your system package directory and the virtual environment.

**Comment by nesrinebnh** [comment]
> > ```
> > ['', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\python38.zip', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\DLLs', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38', 'C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages']
> > ```
> > 
> > 
> > not really the same but as mentioned i am using virtualenv
> 
> Is this when running the file? It looks like you are running the file without enabling the virtual environment. To run the file using the virtual environment, run it from the command prompt using the `python file.py` command with the virtual environment activated.
> 
> Why does tensorflow import properly both from the file and venv? I would guess you have tensorflow install both in your system package directory and the virtual environment.

My vitualenv is activated when i run the file.
and yes, i installed tensorflow in both to try if it is working or not

**Comment by nulano** [comment]
> ```
> ['', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\python38.zip', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\DLLs', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38', 'C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages', 'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages']
> ```
> not really the same but as mentioned i am using virtualenv

I do not see the venv in the output above.

* There are the system package paths:
  ```
  'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\python38.zip', 
  'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\DLLs', 
  'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib', 
  'C:\Users\ASUS\AppData\Local\Programs\Python\Python38'
  ```

* The global package paths:
  ```
  'C:\Users\ASUS\AppData\Roaming\Python\Python38\site-packages'
  ```

* And the user package paths:
  ```
  'C:\Users\ASUS\AppData\Local\Programs\Python\Python38\lib\site-packages'
  ```

I do not see the venv package paths:

```
'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist',
'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\Scripts\\python38.zip'
'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest',
'C:\\Users\\ASUS\\Desktop\\Flank-tutorial\\mnist\\gputest\\lib\\site-packages'
```
