### ISSUE TITLE
ResourceWarning: unclosed file (for Python 3)

### ISSUE THREAD

**Issue by pashinin** [python-pillow/Pillow#477]
A single line

```
img=Image.open(filename)
```

causes a warning in Python 3.3:

```
ResourceWarning: unclosed file <_io.BufferedReader name='...'>
```

This is usually when `data = open(filename, 'r').read()` is used. It's better to use:

```
with open(filename, 'r') as f:
    data = f.read()
```

**Comment by hugovk** [comment]
Note: The above code was added in https://github.com/python-pillow/Pillow/pull/551
