### ISSUE TITLE
PSD Plugin does not register a MIME type

### ISSUE THREAD

**Issue by samamorgan** [python-pillow/Pillow#4787]
The [`PSDImagePlugin`](https://github.com/python-pillow/Pillow/blob/master/src/PIL/PsdImagePlugin.py) does not register a MIME type as I'd expect it to. The correct MIME for PSD images, according to IANA, is ["image/vnd.adobe.photoshop"](https://www.iana.org/assignments/media-types/image/vnd.adobe.photoshop).

Is there a reason this isn't registered?

**Comment by radarhere** [comment]
No reason, so your PR to add it is valid.
