### ISSUE TITLE
Tag 262 (PhotometricInterpretation) is changed when saving as a TIFF

### ISSUE THREAD

**Issue by eliu-alltrust** [python-pillow/Pillow#4804]
### What did you do?
save an uncompressed tiff file to group 4 compressed tiff file
### What did you expect to happen?
I expected to get a group 4 compressed tiff file and kept all other tags the same as original file
### What actually happened?
I got a group 4 compressed tiff file, but Tag 262 (PhotometricInterpretation) was changed from 0 to 1
### What are your OS, Python and Pillow versions?

* OS: Window 10
* Python: Python 3.6.8
* Pillow:  7.2.0

```python
from PIL import Image

img = Image.open('uncompressed.tiff')
print(img.tag)
img.save('group4.tiff', compression="group4", tiffinfo=img.tag)
img = Image.open('group4.tiff')
print(img.tag)
```

[pillowIssue.zip](https://github.com/python-pillow/Pillow/files/4949280/pillowIssue.zip)

**Comment by radarhere** [comment]
As an explanation of what is happening, the image you have provided has mode 1. This is how we are setting the photometric interpretation when saving.

https://github.com/python-pillow/Pillow/blob/5c9faf043f693e2c25b9aaf20e7e2f970e92b174/src/PIL/TiffImagePlugin.py#L1446
https://github.com/python-pillow/Pillow/blob/5c9faf043f693e2c25b9aaf20e7e2f970e92b174/src/PIL/TiffImagePlugin.py#L1418-L1421

So depending on the mode, it will not always be 1. But I agree that we're not using the same value that was set.

It controls ["the color space of the image data"](https://www.awaresystems.be/imaging/tiff/tifftags/photometricinterpretation.html). This is not a random tag that we've just missed - if we were to just flip a switch and set it to 0, it would invert the colors for this case. We could invert the pixels correspondingly, but the value of doing so is not clear - is there any reason you would like it to be the same?

**Comment by TebanoE** [comment]
I am facing the same problem as eliu-alltrust and I think it is a bug in pillow.

The reason for the existence of tag 262 is that there is no general agreement on how values in 1-bit images are interpreted. "1" can be seen as "high intensity" = white or as "set a point" = black. Tag 262 specifies which of those two interpretations should be used when reading a file, not wether pixels are to be inverted when writing a file. 

However, the later is what happens in pillow: I changed the hard coded photometrics value in TiffImagePlugin.py line 1421 to 0 and pillow inverted my image data when saving. It should, however, leave the pixels unchanged regardless of photometrics and write tag 262 with the value specified by the user.

**Comment by radarhere** [comment]
So there is a specific need for tag 262 to be set to zero for 1-bit images? Ok then, I have created PR #5655 to resolve this.
