### ISSUE TITLE
Print Hindi text

### ISSUE THREAD

**Issue by N1NG4** [python-pillow/Pillow#4805]
I am using termux. All packages are upgraded and Updated.I am trying to print hindi text on Images From last 2 Days. Here is what i want to write. शनिवार and this is what pillow print on Image ‌शनवािर . How to Solver this. I am installed harfbuzz, Freebidi & Libraqm but don't know how to use them. There is no pillow docs Available for how to use libraqm. On the official website of Libraqm the examples are in c language so I can't understand them. So I think you should create docs for this or remove this text rendering isuue. I am newbiw to Python. Please share what code i should write here is the code.
```python
from PIL import Image, ImageDraw, ImageFont
import WebPanchangExtractor as WPE
import harfbuzz as hb

mystr = WPE.nakshatras[12].lstrip().rstrip()


img = Image.new('RGB', (1280, 720), color = (73, 109, 137))

fnt = ImageFont.truetype('./Fonts/NirmalaB.ttf', 200)
d = ImageDraw.Draw(img)
d.text((50,50),mystr, font=fnt, fill=(255, 255, 0))
print('Process Done')
img.save('pil_text_font.png')
```
Thanks for Your Help in Advance.. ❤️
I am installed [HarfPy](https://github.com/ldo/harfpy) .

**Comment by radarhere** [comment]
Hi. Could you include the value of `mystr` in your code example? At the moment, I don't know the value, so I can't run your code.

https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype documents how you can use raqm in your code, through the `layout_engine` argument. So
```python
fnt = ImageFont.truetype('./Fonts/NirmalaB.ttf', 200, layout_engine=ImageFont.LAYOUT_RAQM)
```

**Comment by N1NG4** [comment]
@radarhere Hello Bro, Here is the full code with mystr 
`
from​ ​PIL​ ​import​ ​Image​, ​ImageDraw​, ​ImageFont

​mystr​ ​=​ ​शनिवार


​img​ ​=​ ​Image​.​new​(​'RGB'​, (​1280​, ​720​), ​color​ ​=​ (​73​, ​109​, ​137​))

​fnt​ ​=​ ​ImageFont​.​truetype​(​'./Fonts/NirmalaB.ttf'​, ​200​)
​d​ ​=​ ​ImageDraw​.​Draw​(​img​)
​d​.​text​((​50​,​50​),​mystr​, ​font​=​fnt​, ​fill​=​(​255​, ​255​, ​0​))
​print​(​'Process Done'​)
​img​.​save​(​'pil_text_font.png'​)
`
I think this would work. Please Test It, & Thanks For Your Help 🙏🏻

**Comment by radarhere** [comment]
I ran your code with NotoSans-Regular.ttf and slightly adjusted numbers, and this is what I see. Even without libraqm, I'm not seeing a problem. This image is what you are after, correct?

```python
from PIL import Image, ImageDraw, ImageFont

mystr = "शनिवार"

img = Image.new('RGB', (300, 150), color = (73, 109, 137))
fnt = ImageFont.truetype('NotoSans-Regular.ttf', 100)
d = ImageDraw.Draw(img)
d.text((10, 10), mystr, font=fnt)
img.save('pil_text_font.png')
```

![pil_text_font](https://user-images.githubusercontent.com/3112309/88053420-1cb3b780-cb9f-11ea-87f0-008eaa819a12.png)

**Comment by N1NG4** [comment]
@radarhere I don't know why you are not getting error in my case this is not rendering Correct text. Now I will try this with Libraqm. & Check it that would work or not. Thanks for Testing this 🙂

One More thing I am not using this font. My font is different because of the client.. I am not tested with Notosans Font.

**Comment by nulano** [comment]
@N1NG4, can you try your code with `, layout_engine=ImageFont.LAYOUT_RAQM` added? If it crashes it means Raqm is not correctly installed, if it creates a wrong image, it means the font is likely the issue.

```python
from PIL import Image, ImageDraw, ImageFont

mystr = "शनिवार"

​img​ ​=​ ​Image​.​new​(​'RGB'​, (​1280​, ​720​), ​color​ ​=​ (​73​, ​109​, ​137​))
​fnt​ ​=​ ​ImageFont​.​truetype​(​'./Fonts/NirmalaB.ttf'​, ​200​, layout_engine=ImageFont.LAYOUT_RAQM)
d = ImageDraw.Draw(img)
​d​.​text​((​50​,​50​),​ mystr​, ​font​=​fnt​, ​fill​=​(​255​, ​255​, ​0​))
img.save('pil_text_font.png')
```

**Comment by N1NG4** [comment]
@radarhere & @nulano Bro I am using Termux in My Mobile. All Packages Harfbuzz, FreeBidi, Freetype are available in Termux-packages(https://github.com/termux/termux-packages) & I am installed them. But my Libraqm is crashing. So I think I need to change something in setup or config file. Can you please tell me what I need to change or what flags I need to use when installing pillow.this is my last question.

**Comment by N1NG4** [comment]
@radarhere @nulano I run the following code with Libraqm but my problem is not solved.
```python
from PIL import Image, ImageDraw, ImageFont

mystr = "शनिवार"

img = Image.new('RGB', (300, 150), color = (73, 109, 137))
fnt = ImageFont.truetype('./Fonts/NirmalaB.ttf', 100, layout_engine=ImageFont.LAYOUT_RAQM)
d = ImageDraw.Draw(img)
d.text((10, 10), mystr, font=fnt)
img.save('pil_text_font.png')
```
Here is what I got. Please Solve it.
![pil_text_font](https://user-images.githubusercontent.com/50990494/88069557-3d741100-cb8f-11ea-9b17-e34fe3a24068.png)

**Comment by nulano** [comment]
AFAIK Raqm has not been tested previously with Termux. Do you know the filename/path where libraqm is installed? It is possible that Termux is using a non-standard location (which you would need to add to `LD_LIBRARY_PATH`), or name which would need to be added to `_imagingft.c`: https://github.com/python-pillow/Pillow/blob/696aac95cb16cd108abda155a60b8567bbec2cd2/src/_imagingft.c#L161-L164

BTW how did you install Raqm on Termux? It doesn't seem to be available in the Termux package repository. Did you build it from source?

**Comment by N1NG4** [comment]
@nulano @radarhere Thanks for Your Help Bro, LibRaqm is not available in termux packages i built it from source. But i built it wrong i think. so i installed Ubuntu in termux then all the libraries and then i run the program with libraqm and my problem is solved this is printing correct text.. also without libraqm this is printing correct text so the issue is inside termux that is solved by installing Ubuntu in termux. Thanks for Your Precious time.
