### ISSUE TITLE
cannot identify image file %r" % (filename if filename else fp) PIL.UnidentifiedImageError: cannot identify image file <_io.BufferedReader name='SourceData/anime-faces/aqua_eyes/._danbooru_2559693_dc628b766d7142f2d2d9c75559e36eb5.jpg'>

### ISSUE THREAD

**Issue by easquelcannotcode** [python-pillow/Pillow#4807]
I use the ImageFolder and DataLoader from torch and torch vision to open the images in dataset. It just cannot read **some** images and throw this error. (These images are not broken.)

I found it is strange that the actual image name is **danbooru_2559693_dc628b766d7142f2d2d9c75559e36eb5.jpg**, while the error (shown in the title) indicates that as **._danbooru_2559693_dc628b766d7142f2d2d9c75559e36eb5.jpg**. Where does the **._** come from?

Here is the code:
```python
dataset=torchvision.datasets.ImageFolder(opt.data_path, transform=transform)
dataloader=torch.utils.data.DataLoader(dataset,
                                           batch_size=opt.batch_size,
                                           shuffle=True,
                                           num_workers=opt.num_workers,
                                           drop_last=True
                                           )
```
ps: opt.data_path is "SourceData/anime-faces/" Under the anime-faces directory, there are lots of subdirectories containing different images.

**Comment by hugovk** [comment]
I don't see any Pillow code here, please report this to either PyTorch or torchvision.

* https://github.com/pytorch/pytorch
* https://github.com/pytorch/vision

**Comment by easquelcannotcode** [comment]
> I don't see any Pillow code here, please report this to either PyTorch or torchvision.
> 
> * https://github.com/pytorch/pytorch
> * https://github.com/pytorch/vision

Thanks! I solved it!
