### ISSUE TITLE
GIF split into frames saves corrupted png images

### ISSUE THREAD

**Issue by noambaron1989** [python-pillow/Pillow#4810]
I'm trying to split gif into frames and save as PNG.
The issue is, some gifs are low quality and when getting to the second frame onwards, the frames are corrupted.

this is the code I'm using:

```python
import logging
import os

from PIL import Image
from logger import Logger

toddler_lq = '/Users/noambaron/Downloads/toddler_LQ.gif'
toddler_dir = '/Users/noambaron/Desktop/toddler_f'
gif_path = toddler_lq
frame_dir = toddler_dir
logger = Logger(logging.INFO, 'gif_test')

try:
    frame = Image.open(gif_path)
    palette = frame.palette
    num_of_frames = 0
    while frame:
        base_name = os.path.basename(gif_path).split('.')[0]
        frame.show()
        frame.save(os.path.join(frame_dir, '%s-%s.png' % (base_name, num_of_frames)), 'PNG')
        num_of_frames += 1
        try:
            frame.seek(num_of_frames)
        except EOFError:
            break
except Exception as e:
    logger.error('failed extracting frames from gif %s due to %s', gif_path, e)
```

attached is the gif, and the 3 first frames 
![toddler_LQ-2](https://user-images.githubusercontent.com/40001659/88272538-8c31c000-cce1-11ea-8394-f2f6751b1f5c.png)
![toddler_LQ-1](https://user-images.githubusercontent.com/40001659/88272545-8e941a00-cce1-11ea-92e3-156573eadc30.png)
![toddler_LQ-0](https://user-images.githubusercontent.com/40001659/88272548-8f2cb080-cce1-11ea-9ff8-c190f8845c71.png)
![toddler_LQ](https://user-images.githubusercontent.com/40001659/88272574-9784eb80-cce1-11ea-95d0-eea691386a98.gif)

**Comment by peterableda** [comment]
I have the same issue with similar code:

`import PIL 
from PIL import Image

gif = Image.open('/home/pi/Photos/ANIMATION.gif')

# for frame in ImageSequence.Iterator(gif):
for n in range(0,gif.n_frames):
    gif.seek(n)
    im = ImageOps.grayscale(gif)
    im.save("/home/pi/Photos/tmp/gif_{}.bmp".format(n))
`

**Comment by radarhere** [comment]
@peterableda please open a new issue with your specific image.

**Comment by radarhere** [comment]
Pillow 9.0.0 has significantly improved reading animated GIFs thanks to #5857.

If this issue is still a problem when using Pillow 9.0.0, please let us know.
