### ISSUE TITLE
TypeError: exif.startswith(b"Exif\x00\x00"): arg must be str

### ISSUE THREAD

**Issue by sduthaler** [python-pillow/Pillow#4820]
https://github.com/python-pillow/Pillow/blob/893489c57227f76cff8816de167ad329e5862756/src/PIL/PngImagePlugin.py#L1306
This line hits a TypeError when trying to save a png file (while trying to save a thumbnail of a png image)

```python
if exif.startswith(b"Exif\x00\x00"):
```
```
TypeError: startswith first arg must be str or a tuple of str, not bytes
```

OS: Ubuntu18.04 x86_64
Python 3.6
PIL: 7.2.0

**Comment by radarhere** [comment]
Could you upload the image that causes the problem?

**Comment by sduthaler** [comment]
I'll have to check with legal and actually find the image that caused it.
I'm using BytesIO() to read/write the image data in case that matters.

**Comment by radarhere** [comment]
Yes, it could matter. Are you able to post a simple version of your code?

**Comment by sduthaler** [comment]
The code looks something like this, image_data comes over network.

`
from PIL import Image
from io import BytesIO

resolutions=[(138, 108), (256, 256)]
with BytesIO(bytes(image_data)) as buf, Image.open(buf) as img:
    if img.mode != "RGB":
        img = img.convert("RGBA")
    for resolution in resolutions:
        thumbnail = img.copy()
        thumbnail.thumbnail(resolution)
        with BytesIO() as mem:
            thumbnail.save(mem, format="PNG", optimize=True)
            yield mem.getvalue(), resolution
`

**Comment by radarhere** [comment]
Hmm. Reading a file as `image_data`, the code runs fine for me.

```python
from PIL import Image
from io import BytesIO

resolutions=[(138, 108), (256, 256)]
with open("Tests/images/hopper.png", "rb") as f:
    image_data = f.read()
with BytesIO(bytes(image_data)) as buf, Image.open(buf) as img:
    if img.mode != "RGB":
        img = img.convert("RGBA")
    for resolution in resolutions:
        thumbnail = img.copy()
        thumbnail.thumbnail(resolution)
        with BytesIO() as mem:
            thumbnail.save(mem, format="PNG", optimize=True)
```

Are you able to test if https://github.com/python-pillow/Pillow/raw/master/Tests/images/exif.png works in your program?
If it works, then there is something different about your image and posting it is the next step.
If it doesn't work, then there might be something missing from your code example.

**Comment by sduthaler** [comment]
Above exif.png works fine in my program without triggering the TypeError.
I'll let you know when I have a repro that I can share.

**Comment by sduthaler** [comment]
I've found the image that caused the error and compared its meta data to yours. It turns out the file that triggers the issue has a tEXt chunk: "exif":"Exif <some more meta data>". I modified your file accordingly and it triggers the issue as well.

[PIL_repro.zip](https://github.com/python-pillow/Pillow/files/5000472/PIL_repro.zip)

**Comment by radarhere** [comment]
Thanks. I've created #4828 to resolve this.
