### ISSUE TITLE
py -3.9 -m pip install -U pillow fails with pip 20.2

### ISSUE THREAD

**Issue by djhenderson** [python-pillow/Pillow#4827]
`py -3.9 -m pip install -U pillow`

fails, includes these messages:

```
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
Failed to build pillow
DEPRECATION: Could not build wheels for pillow which do not use PEP 517. pip will fall back to legacy 'setup.py install' for these. pip 21.0 will remove support for this functionality. A possible replacement is to fix the wheel build issue reported above. You can find discussion regarding this at https://github.com/pypa/pip/issues/8368.
Installing collected packages: pillow
    Running setup.py install for pillow ... error
    ERROR: Command errored out with exit status 1:
```

using: 

```
> py -3.9 -m pip --version
pip 20.2 from C:\Users\Doug\AppData\Local\Programs\Python\Python39\lib\site-packages\pip (python 3.9)
```

```
> py -3.9
Python 3.9.0b5 (tags/v3.9.0b5:8ad7d50, Jul 20 2020, 18:35:09) [MSC v.1924 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>>
```

On windows 10 pro 1909, full patched as of 2020-07-30.

**Comment by Dinoosawruss** [comment]
I'm experiencing the same issue

**Comment by hugovk** [comment]
Pillow doesn't yet provide prebuilt wheels for Python 3.9, and it's attempting to build from source, which is fiddly on Windows. The 3.9 wheels are scheduled for Pillow 8 in October after Python 3.9.0 is out. (Unofficial Windows wheels for 3.9 are here: https://www.lfd.uci.edu/~gohlke/pythonlibs/#Pillow) 

You should be getting this warning:

https://github.com/python-pillow/Pillow/blob/48c7d84bf771c3cf9bf9c0aba96b4ce12c449c8c/setup.py#L40-L46

Do you get it? Please could you post the full traceback?

If not, do you get the warning with pip 20.1?

**Comment by hugovk** [comment]
I tested Python 3.9 with pip 20.1 and 20.2 on GitHub Actions, on Windows, and got the warning at the top of each traceback:

* https://github.com/hugovk/test/runs/931018810?check_suite_focus=true
* https://github.com/hugovk/test/runs/931018847?check_suite_focus=true

Also tested with wheel installed, similar thing:

* https://github.com/hugovk/test/runs/931032374?check_suite_focus=true
* https://github.com/hugovk/test/runs/931032376?check_suite_focus=true

[logs.zip](https://github.com/python-pillow/Pillow/files/5005805/logs.zip)

Please either wait for Python 3.9.0 and Pillow 8 (https://github.com/python-pillow/Pillow/issues/4764), or use the [unofficial wheels](https://www.lfd.uci.edu/~gohlke/pythonlibs/#Pillow).
