### ISSUE TITLE
How to make a clear JPEG thumbnail

### ISSUE THREAD

**Issue by imfantuan** [python-pillow/Pillow#4839]
### What did you do?
```python
Image.open('unsplash.jpeg')  ## https://images.unsplash.com/photo-1522521976874-e5d7c6b90db3
Image.thumbnail(size = (1500, 2250))
Image.save('unsplash_t.jpeg', 'JPEG', quality=70, filter="antialias")
```

### What did you expect to happen?
thumbnail it like this: https://images.unsplash.com/photo-1522521976874-e5d7c6b90db3?w=1500&q=55 (a clear plane with 133k)
### What actually happened?
I got this picture (some artifacts around the plane with 131k): 
![photo-1522521976874-e5d7c6b90db3](https://user-images.githubusercontent.com/16457655/89443959-993fbc00-d783-11ea-9444-0746edd90055.jpeg)
### What are your OS, Python and Pillow versions?

* OS: Centos 8
* Python: 3.8
* Pillow: 7.0

Some infomations:
https://graphicdesign.stackexchange.com/questions/51933/how-does-this-image-interleave-from-grayscale-to-color
https://cloudinary.com/blog/progressive_jpegs_and_green_martians

**Comment by hugovk** [comment]
Increase `quality=70` to `95` or so.

**Comment by imfantuan** [comment]
Thanks for this, it would be better. But also:

131k to 635k. 😂

And Unsplash still: 133k.

**Comment by imfantuan** [comment]
Very interesting: 
```python
Image.open('unsplash.jpeg')  ## https://images.unsplash.com/photo-1596420661047-d5debc649383
Image.thumbnail(size = (634, 951))
Image.save('unsplash_t.jpeg', 'JPEG', quality=13, filter="antialias")
```
I got a 21k jpeg file:
![unsplash-pillow-low-q](https://user-images.githubusercontent.com/16457655/89526868-fcc8f880-d81a-11ea-9de8-fa3995515c4b.jpeg)

21k jpeg file in Unsplash (powered by imgix):
https://images.unsplash.com/photo-1596420661047-d5debc649383?fit=crop&w=634&q=10
![unsplash-imgix-low-q](https://images.unsplash.com/photo-1596420661047-d5debc649383?fit=crop&w=634&q=10)

**Comment by radarhere** [comment]
I'm not following - what do you find interesting about this?

**Comment by imfantuan** [comment]
> I'm not following - what do you find interesting about this?

A thumbnail from pillow: 21k, not so clear.
B thumbnail from imgix: 21k, super clear (tiny size).

**Comment by radarhere** [comment]
For an improvement at least, here is a 21k file I was able to generate with Pillow.

```python
from PIL import Image
im = Image.open('unsplash.jpeg')
im.thumbnail((634, 951))
im.save('out.jpg', optimize=True, quality=29)
```
![out](https://user-images.githubusercontent.com/3112309/90299166-7a0a0280-ded8-11ea-9693-782399159307.jpg)

**Comment by imfantuan** [comment]
May be mozjpeg.
