### ISSUE TITLE
When try to get an image's exif, get error: SyntaxError: not a TIFF file (header b'' not valid)

### ISSUE THREAD

**Issue by Julymycin** [python-pillow/Pillow#4852]
### What did you do?
```python
image = Image.open(image_file_path)
image.getexif()
```

### What did you expect to happen?
to get the image's exif info
this error occurs for a few images, such as 
![2705](https://user-images.githubusercontent.com/24741969/89874500-81868e80-dbee-11ea-8fdb-6becd1181e53.jpg)

### What actually happened?

```
SyntaxError: not a TIFF file (header b'' not valid)
```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04LTS
* Python: 3.7.7
* Pillow: 7.2.0

**Comment by radarhere** [comment]
Hi. How was this image created?

If I open the image and print `im.info["exif"]` the output is `b'Exif\x00\x00'`.

If I inspect the image with exiftool, part of the output is
```
Warning                         : Malformed APP1 EXIF segment
```

So can you demonstrate in any way that the image isn't malformed, or that there is EXIF data to be found?

**Comment by Julymycin** [comment]
Sorry for late reply. And I don't know clearly about these images, because they are contained in a dataset, named MHP:Multi-Human Parsing. This error occurs when I tried to load them in detectron2, [detectron2 issue #1885](https://github.com/facebookresearch/detectron2/issues/1885#issue-675845814). Thanks for your reply.

**Comment by radarhere** [comment]
Could you link to the image in the detectron2 repository, so that we can understand which image in there you've attached?

**Comment by radarhere** [comment]
Closing, as there's no reason to think that the image isn't malformed.

**Comment by radarhere** [comment]
Closing, as there's no reason to think the image isn't malformed.

**Comment by radarhere** [comment]
This has re-appeared as #6123, and I've created #6124 to fix that issue.
