### ISSUE TITLE
Installing PIL on Python 3.8

### ISSUE THREAD

**Issue by DwealthJossy** [python-pillow/Pillow#4855]
### What did you do?
How can I install PIL on Python 3.8
### What did you expect to happen?
How to install it
### What actually happened?
I haven't seen any explanation on how to install it
### What are your OS, Python, and Pillow versions?

* OS: 
* Python: 3.8
* Pillow: The one that works for Python 3.8

```python
code goes here
```

**Comment by radarhere** [comment]
Is https://pillow.readthedocs.io/en/stable/installation.html helpful?

**Comment by radarhere** [comment]
If you're wondering where you could have find this link, it is 'Installation' at the bottom of https://github.com/python-pillow/Pillow

**Comment by radarhere** [comment]
Let us know if you have any further questions.
