### ISSUE TITLE
ImportError

### ISSUE THREAD

**Issue by Frozen520** [python-pillow/Pillow#4856]
Hi,
SO i am stuck here for 4 hours and i can't understand why. please help me

```
Traceback (most recent call last):
  File "C:/Users/user/PycharmProjects/PythonProject1/ImageToText/main.py", line 2, in <module>
    from PIL import image
ImportError: cannot import name 'image' from 'PIL' (C:\Users\user\PycharmProjects\PythonProject1\ImageToText\venv\lib\site-packages\PIL\__init__.py)
```

**Comment by radarhere** [comment]
I would try replacing `from PIL import image` with `from PIL import Image` - Image with a capital I.

**Comment by radarhere** [comment]
This seems pretty straightforward, so I'm closing. If you have any further questions, let us know.
