### ISSUE TITLE
Pillow built with libraqm insists it has no libraqm

### ISSUE THREAD

**Issue by newfeatureengineer** [python-pillow/Pillow#4859]
### What did you do?
Built pillow from source with all dependencies and installed it using `python setup.py install`. 

Running selftest.py works, and seems to corroborate that raqm is [indeed installed](https://justpaste.it/9e93v).

### What did you expect to happen?
I expected to be able to set text direction

### What actually happened?
I got the following exception:

```
  File "C:\venv\lib\site-packages\pillow-7.2.0-py3.7-win-amd64.egg\PIL\ImageFont.py", line 262, in getsize
KeyError: 'setting text direction, language or font features is not supported without libraqm'
```

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.7.7
* Pillow: 7.2.0

```python
from PIL import ImageFont
font = ImageFont.truetype(r'C:\Windows\Fonts\Arial.ttf', 120)
size = font.getsize("hello world", 'rtl')
```

**Comment by radarhere** [comment]
Hi. Would you mind trying this?
```python
from PIL import ImageFont
font = ImageFont.truetype(r'C:\Windows\Fonts\Arial.ttf', 120, layout_engine=ImageFont.LAYOUT_RAQM)
size = font.getsize("hello world", 'rtl')
```

**Comment by nulano** [comment]
"Pillow built with Raqm" doesn't actually mean anything in the current version; Raqm is only linked at runtime. Raqm support can be loaded if Pillow is compiled with FreeType and `libraqm.dll` is found by the system functions.

In other words, to load Raqm you need to have `libraqm.dll` available in your `PATH`, the `site-packages\PIL` directory, or the Python directory (in decreasing order of good practice, but increasing order of convenience 😄 ).

**Comment by newfeatureengineer** [comment]
@nulano Placing it in `site-packages\PIL` didn't work, but placing it in my root project directory (available in my PATH), it did.

Thanks :)

Is there a way to statically link libraqm to avoid the dll issue?

**Comment by nulano** [comment]
> Is there a way to statically link libraqm to avoid the dll issue?

Not currently, but it shouldn't be too difficult to make a patch.

First you have to add `#include <raqm.h>` to `src/_imagingft.c`, then replace the [`setraqm`](https://github.com/python-pillow/Pillow/blob/master/src/_imagingft.c#L154) function with code that links each required function statically, e.g. replace
```c
    p_raqm.version_string = (t_raqm_version_string)GetProcAddress(p_raqm.raqm, "raqm_version_string");
```
with
```c
    p_raqm.version_string = raqm_version_string;
```
and finally add raqm to `setup.py`; I think the following (untested) patch should be sufficient:
```diff
        features = [
            "zlib",
            "jpeg",
            "tiff",
            "freetype",
            "lcms",
            "webp",
            "webpmux",
            "jpeg2000",
            "imagequant",
            "xcb",
+           "raqm",
        ]
# -----
        if feature.want("xcb"):
            _dbg("Looking for xcb")
            if _find_include_file(self, "xcb/xcb.h"):
                if _find_library_file(self, "xcb"):
                    feature.xcb = "xcb"

+       if feature.want("raqm"):
+           _dbg("Looking for raqm")
+           if _find_include_file(self, "raqm.h"):
+               if _find_library_file(self, "libraqm"):
+                   feature.raqm = "libraqm"
# -----
        if feature.xcb:
            libs.append(feature.xcb)
            defs.append(("HAVE_XCB", None))
+       if feature.raqm:
+           libs.append(feature.raqm)
+           defs.append(("HAVE_RAQM", None))
        if sys.platform == "win32":
```

---

The reason this is not currently supported is that Raqm depends on FriBiDi which has an LGPL license. The current runtime linking mechanism allows Pillow to avoid any licensing issues, while linking statically could add LGPL requirements to using Pillow.

**Comment by radarhere** [comment]
Is there anything left to do for this issue @newfeatureengineer ? It looks like it's been resolved to me.

**Comment by h4xw4r** [comment]
> First you have to add `#include <raqm.h>` to `src/_imagingft.c`,

Where _imagingft.c please ? 
I placed `libraqm.dll` everywhere possible with no luck.

**Comment by nulano** [comment]
The changes from my comment above are now the default for source builds on Linux since Pillow 8.2.0. To enable Raqm for binary wheels, it is sufficient to install FriBiDi on Linux (Raqm is linked statically but runtime loading is used for its dependency FriBiDi in wheels).

For Windows wheels (source builds are not recommended) you should be able to enable Raqm by installing `fribidi.dll` or `libfribidi.dll` into a system or Python directory, but I'm not sure this was enabled for the release. Installing from source on Windows is not recommended, but the instructions are here: https://github.com/python-pillow/Pillow/blob/master/winbuild/build.rst

**Comment by h4xw4r** [comment]
I have used it on Linux without any problems. Sadly the problem still exists on Windows and I'm not the only one. 
checkout this post:
https://stackoverflow.com/questions/67805726/pillow-not-detecting-the-libraqm-dll-file/68183126#68183126 
I couldn't find online `libfribidi.dll` is it a different library or just renaming `fribidi.dll` will do ?

**Comment by h4xw4r** [comment]
@radarhere Should I make a new Issue or this one can be changed from Closed to Open ?

**Comment by nulano** [comment]
> I couldn't find online `libfribidi.dll` is it a different library or just renaming `fribidi.dll` will do ?

Actually, that's a typo. When trying to load Raqm's dependency FriBiDi, Pillow will attempt to open `fribidi.dll`, `fribidi-0.dll` or `libfribidi-0.dll` in that order. These are all different names for the same library, FriBiDi.

**Comment by h4xw4r** [comment]
I went out and tried this on Manjaro Linux with Wine set as Windows 10 and Windows 8.1. Still no luck getting it to work.

**Comment by nulano** [comment]
The Python 3.7 Pillow 8.3.0 release wheel doesn't detect Raqm/FriBiDi for me either, but the CI test run wheel does: https://github.com/python-pillow/Pillow/actions/runs/988696864

**Comment by radarhere** [comment]
@h4xw4r here is one of the wheels linked to from the previous comment. Installing this might solve your immediate problem - [Pillow-8.3.0-cp37-cp37m-win_amd64.whl.zip](https://github.com/python-pillow/Pillow/files/6759366/Pillow-8.3.0-cp37-cp37m-win_amd64.whl.zip)

@nulano does the 8.2.0 release wheel work? Is this possibly just the same problem as #5573?

**Comment by maaldheefee** [comment]
Same issue with 8.2.0 also. I've tried a week ago and had to use WSL after trying every other option.

The wheel from @nulano's link worked finally.

**Comment by nulano** [comment]
> @nulano does the 8.2.0 release wheel work? Is this possibly just the same problem as #5573?

8.2.0 had the same issue when I tested it right after the release.

The problem and solution is https://github.com/python-pillow/Pillow/issues/5413#issuecomment-871978953

**Comment by h4xw4r** [comment]
> 
> 
> @h4xw4r here is one of the wheels linked to from the previous comment. Installing this might solve your immediate problem - [Pillow-8.3.0-cp37-cp37m-win_amd64.whl.zip](https://github.com/python-pillow/Pillow/files/6759366/Pillow-8.3.0-cp37-cp37m-win_amd64.whl.zip)
 It doesn't seem to work for me 
` pip install Pillow-8.3.0-cp37-cp37m-win_amd64.whl`
 spits out:
`ERROR: Pillow-8.3.0-cp37-cp37m-win_amd64.whl is not a supported wheel on this platform`

**Comment by nulano** [comment]
> It doesn't seem to work for me ... `is not a supported wheel on this platform`

That wheel is for Python 3.7 64-bit, you are probably running a different version of Python.

I have checked the 8.3.1 wheel from cgohlke's website also works with Raqm/FriBiDi properly (the official release should be uploaded to PyPI later today I think, you can subscribe to #5578 to be notified).

**Comment by h4xw4r** [comment]
Thanks I just noticed the `cp37-cp37m`, stupid me. 
> subscribe to #5578 to be notified
Neat I will be waiting for it 👍

**Comment by radarhere** [comment]
Pillow 8.3.1 has now been released and uploaded to PyPI.

**Comment by h4xw4r** [comment]
I installed Pillow 8.3.1 on my work computer and placed the DLL files at the folder of Python.exe it didn't work. 
However, on my personal computer everything worked fine maybe because I placed the DLL files everywhere possible. I think it will be worth it to put the right way of doing this on Windows in the documentation.

**Comment by nulano** [comment]
> I installed Pillow 8.3.1 on my work computer and placed the DLL files at the folder of Python.exe it didn't work.

This works for me. The [installation docs](https://pillow.readthedocs.io/en/stable/installation.html#external-libraries) link to this [Microsoft Docs page](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications) in the paragraph for Raqm, which lists the application directory as the first checked option (i.e. next to Python.exe). Did you perhaps install a 32-bit fribidi.dll for a 64-bit Python or vice-versa?

**Comment by h4xw4r** [comment]
>  Did you perhaps install a 32-bit fribidi.dll for a 64-bit Python or vice-versa?

I don't think I did that wrong. However, just be sure I made a virtual environment with python and put the DLL files next Python.exe and it still didn't work.

**Comment by nulano** [comment]
> > Did you perhaps install a 32-bit fribidi.dll for a 64-bit Python or vice-versa?
> 
> I don't think I did that wrong. However, just to be sure, I made a virtual environment with python and put the DLL files next Python.exe and it still didn't work.

I haven't tried it, but I'm pretty sure you can't put the DLL next to python.exe in a virtual environment as the python.exe is just a link to the system directory of the Python install. See `sys.executable`, I'm pretty sure the DLL must be in the same directory, or one of the other options specified by Microsoft. The other options are the system and Windows directories, any directory in the PATH variable, or the current working directory at the time `PIL.ImageFont` is first imported (the search order varies by Python version, see the link in my previous comment for the two orders).

**Comment by h4xw4r** [comment]
There is a Python.exe in Scripts folder which VS Code uses to run python code inside the virtual environment.
libraqm works fine outside virtual environments for me which is weird.

**Comment by nulano** [comment]
I have an old virtual environment that has link files in the Scripts folder, but I don't remember how it was created.

I just tried creating a new virtual environment, and it does in fact place a python.exe in the Scripts folder, but this seems to be just a wrapper that calls the system Python executable. This is not visible from `sys.executable` (it shows the venv exe), but I can see two python.exe processes in the Task Manager, one from the venv and one from the system directory:

![image](https://user-images.githubusercontent.com/3819630/125158489-de2d5900-e171-11eb-9646-dde8b41c641d.png)

Therefore the search for fribidi.dll starts by looking in the system Python directory first. I checked this using Process Monitor to be sure, from this I can see Python 3.9b5 uses the order with `SafeDllSearchMode` enabled, which is (from [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications)):

> 1. The directory from which the application loaded.
> 2. The system directory. Use the GetSystemDirectory function to get the path of this directory.
> 3. The 16-bit system directory. There is no function that obtains the path of this directory, but it is searched.
> 4. The Windows directory. Use the GetWindowsDirectory function to get the path of this directory.
> 5. The current directory.
> 6. The directories that are listed in the PATH environment variable. Note that this does not include the per-application path specified by the App Paths registry key. The App Paths key is not used when computing the DLL search path.

![image](https://user-images.githubusercontent.com/3819630/125158272-2a779980-e170-11eb-8b42-aaa0226804bf.png)

Note that `C:\Users\Nulano\Documents\venv\raqmtest2\Scripts\fribidi.DLL` is only checked if `C:\Users\Nulano\Documents\venv\raqmtest2\Scripts` is listed in the PATH variable, which only happens if you run `Scripts\activate.bat` from the command prompt (I don't think VS Code does this, but I could be wrong).

Older versions of Python have `SafeDllSearchMode` disabled, but the same directories are searched, just in different order (the current directory is checked 2nd instead of 5th).

Therefore the most reliable option is to place fribidi.dll into the directory containing the system python.exe.

---

Returning to your earlier comment:

> > Did you perhaps install a 32-bit fribidi.dll for a 64-bit Python or vice-versa?
>
> I don't think I did that wrong. However, just to be sure, I made a virtual environment with python and put the DLL files next Python.exe and it still didn't work.

The search above terminates as soon as it finds a match, so if you have a non-functional fribidi.dll in the system python directory, the other paths will never be checked at all. To show this I created a blank file named fribidi.dll in the system python directory and also captured the search with Process Monitor:

![image](https://user-images.githubusercontent.com/3819630/125158375-11bbb380-e171-11eb-8def-f887e633d65c.png)

You can see from this that the fribidi.dll search terminated with a failure and a search using the alternative name fribidi-0.dll is started.

**Comment by h4xw4r** [comment]
> I have an old virtual environment 

This. I double checked everything then I realized I haven't updated pillow inside the virtual environment. Now it works without any issues.
In addition, putting the DLL files at the same path of Python.exe is enough for all virtual environments.

**Comment by monzzzz** [comment]
Hello, I have this problem too on Mac. Can someone help me, please? I'm using Pillow version 9.5.0 because the newest version doesn't support some specific functions I need to use.

**Comment by radarhere** [comment]
How did you install Pillow? What is the output of `python3 -m PIL`?

Have you tried installing fribidi?

https://pillow.readthedocs.io/en/stable/installation/basic-installation.html
> Raqm support requires FriBiDi to be installed separately

**Comment by monzzzz** [comment]
This is what was displayed I ran python3 -m PIL

```--- PIL CORE support ok, compiled for 9.5.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.4.0
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.3
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.12
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
```

and this is what I fused and installed

`Pillow-10.0.0-cp312-cp312-macosx_11_0_universal2.whl`

**Comment by nulano** [comment]
> --- RAQM (Bidirectional Text) support ok, loaded 0.10.1

This means raqm is working for you.

**Comment by monzzzz** [comment]
Ohh, but when I tried to run template.py in Synthtiger library, I still got `'setting text direction, language or font features is not supported without libraqm'`

**Comment by monzzzz** [comment]
Now, I think the problem is that I can't use the function getsize after Pillow version 9.2.0. Do you know if there is any way I can fix this or do I have to manually change to getbbox?

**Comment by monzzzz** [comment]
My PIL library features contain raqm, but the `core` object in the C file of the library doesn't have raqm

**Comment by radarhere** [comment]
> Now, I think the problem is that I can't use the function getsize after Pillow version 9.2.0.

Technically, it's only deprecated after 9.2.0. It was removed in 10.0.0.

> Do you know if there is any way I can fix this or do I have to manually change to getbbox?

You will have to change your code to use `getbbox()`. You can read about how to do this at https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods

**Comment by radarhere** [comment]
> My PIL library features contain raqm, but the `core` object in the C file of the library doesn't have raqm

Considering that `python3 -m PIL` uses
```pycon
>>> from PIL import _imagingft
>>> _imagingft.HAVE_RAQM
True
```
to check for raqm, what you're describing sounds unusual. Could you use code to depict what you're seeing?

**Comment by monzzzz** [comment]
I tried it. I got False

**Comment by radarhere** [comment]
You previously reported the output of `python3 -m PIL`. When you're running your code, what command are you using? Are you running `python3`, or something else? We occasionally have people running two different versions of Python.

**Comment by monzzzz** [comment]
Wait. Sorry, I actually got true

**Comment by radarhere** [comment]
> the `core` object in the C file of the library doesn't have raqm

How do you know this?

**Comment by monzzzz** [comment]
I edited in PIL/ImageFont.py file in my Python environment by adding:

```if (core.HAVE_RAQM):
            print(True)
       else:
            print(False)
```
 , and it gave me False when I ran it

**Comment by radarhere** [comment]
`core` in ImageFont is
https://github.com/python-pillow/Pillow/blob/3c2d36e11379a69d6bcff0ed9a02cf54deda8b19/src/PIL/ImageFont.py#L52

So you're reporting that
```python
from PIL import _imagingft
print(_imagingft.HAVE_RAQM)
```
is true, but
```python
from PIL import _imagingft as core
print(core.HAVE_RAQM)
```
is false.

This doesn't make sense?

**Comment by monzzzz** [comment]
Since I used this command to run `synthtiger -o results -w 4 -v examples/synthtiger/template.py SynthTiger config.yaml`, I'm not sure if there is any issue associated with it. When I directly ran the checking file by using the python3 command, there was no problem, and it printed True while when I used this command, it gave me False.

**Comment by radarhere** [comment]
Ok, so it does sound like you're using a different version of Python for synthtiger.

Since you're open to modifying Pillow code, could you edit ImageFont.py, insert `import sys; print(sys.executable)`, and then run synthtiger.

That should print something like '/Applications/Xcode.app/Contents/Developer/usr/bin/python3'

Then, using the path that was printed, run `/Applications/Xcode.app/Contents/Developer/usr/bin/python3 -m PIL`. That should report the status of Pillow within this other Python installation.

**Comment by monzzzz** [comment]
I got this `/opt/anaconda3/bin/python` which means that synthtiger ran on the anaconda not my virtual env, right?, and I also got this `/opt/anaconda3/bin/python: No module named Pillow`

**Comment by radarhere** [comment]
Yes, nothing in that path says 'venv', so it wouldn't be inside your virtual environment.

It's not clear to me why synthtiger was complaining about raqm, and not about Pillow not being installed in the first place. When you've been modifying ImageFont.py, and then running synthtiger, where is ImageFont.py located?

I don't know if your goal is to run synthtiger inside your virtual environment though. If so, there's no point to continuing to debug this other installation.

**Comment by nulano** [comment]
`sys.executable` can be unreliable to detect virtual environments, maybe check also `sys.prefix`?

**Comment by monzzzz** [comment]
> It's not clear to me why synthtiger was complaining about raqm, and not about Pillow not being installed in the first place
Now, I installed Pillow, and when I ran /opt/anaconda3/bin/python, I got 
```
--- PIL CORE support ok, compiled for 10.3.0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.12.1
--- LITTLECMS2 support ok, loaded 2.12
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for 9.0
--- OPENJPEG (JPEG2000) support ok, loaded 2.4.0
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.13
--- LIBTIFF support ok, loaded 4.5.1
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
*** XCB (X protocol) support not installed
```
Is there any way that I can install raqm in conda env?

**Comment by monzzzz** [comment]
> IIRC sys.executable can be unreliable to detect virtual environments, maybe check also sys.prefix?

I also got /opt/anaconda3

**Comment by nulano** [comment]
Which version of the Pillow package did you install (default, conda-forge, something else)? I think `conda list` should show it, but not sure.

**Comment by monzzzz** [comment]
I got this after running `conda list pillow`
```
# Name                    Version                   Build  Channel
pillow                    9.5.0                    pypi_0    pypi
```

**Comment by nulano** [comment]
> --- PIL CORE support ok, compiled for 10.3.0

> pillow                    9.5.0                    pypi_0    pypi

This makes no sense, you can't have both 10.3.0 and 9.5.0 installed at the same time.
Can you also provide the start of the output of `python -m PIL` (i.e. the part listing various paths)?

**Comment by monzzzz** [comment]
If I run from base env, I got this 

```
Pillow 10.3.0
Python 3.11.7 (main, Dec 15 2023, 12:09:04) [Clang 14.0.6 ]
--------------------------------------------------------------------
Python executable is /opt/anaconda3/bin/python
System Python files loaded from /opt/anaconda3
--------------------------------------------------------------------
Python Pillow modules loaded from /opt/anaconda3/lib/python3.11/site-packages/PIL
Binary Pillow modules loaded from /opt/anaconda3/lib/python3.11/site-packages/PIL
```
I'm not sure if they are in a different environment.

**Comment by monzzzz** [comment]
I just switched to the environment in which Pillow 10.3.0 is installed. When I run the synthtiger command, I got the getsize error instead of raqm

```
width = font.getsize(text, direction=direction)[0]
            ^^^^^^^^^^^^
AttributeError: 'FreeTypeFont' object has no attribute 'getsize'
```

Does this mean I have to replace getsize by getbbox in every function in the synthtiger library?

**Comment by radarhere** [comment]
If synthtiger is where that line of code resides, then yes.

https://github.com/clovaai/synthtiger/issues/66 is the open issue in synthtiger for fixing this properly.

**Comment by monzzzz** [comment]
I got it. Thank you so much for your help!!!!!!
