### ISSUE TITLE
Cannot use any Image or ImageDraw function expecting tuple input

### ISSUE THREAD

**Issue by Void2258** [python-pillow/Pillow#486]
Attempted to use multiple function in image draw and image, and every single one that takes a tuple input gives the error "SystemError: new style getargs format but argument is not a tuple."

For example a call I attempted to use was:

```
  im = Image.new("RGB", (2400, 2400), "white")
  draw = ImageDraw.Draw(im)
  draw.line((0,0,0,2400), fill = 155, width = 1)
```

which should produce a single pixel vertical line. Most of the package is nonfunctional due to this issue. Working on a windows 7 64 machine with Python XY 2.7.5.0.

**Comment by wiredfool** [comment]
I'm getting this error from getink in #1663, on appveyor: https://ci.appveyor.com/project/Python-pillow/pillow/build/3.2.pre.647/job/k8lqm46kndbrjtaw

**Comment by solsticedhiver** [comment]
I am still seeing something like that in a bug triggered by GAE:  https://code.google.com/p/googleappengine/issues/detail?id=12887&can=1&q=type%3DDefect%20Images&colspec=ID%20Type%20Component%20Status%20Stars%20Summary%20Language%20Priority%20Owner%20Log&start=100

I can't even compile PIL 1.1.7 here... trying to find a way.

**Comment by aclark4life** [comment]
@solsticedhiver Not much we can do to help if @GoogleCloudPlatform won't upgrade to latest Pillow, as far as I can tell at a glance.

**Comment by hugovk** [comment]
From that Google issue:

> Should you wish to see full Pillow support for App Engine, please feel free to file a new feature request including a thorough use case.

A good reason for updating to Pillow is security. PIL 1.1.7 was released in 2009. Pillow fixes a number of security vulnerabilities which are still present in PIL 1.1.7. You can find some with CVE numbers in the [changelog](https://github.com/python-pillow/Pillow/blob/master/CHANGES.rst), and more by searching for "DOS" or "overflow".

**Comment by solsticedhiver** [comment]
I have found a work-around by using Pillow 2.9 (locally) as the bug is not triggered there.
