### ISSUE TITLE
Directly querying libimaging functions from C

### ISSUE THREAD

**Issue by bit-twidd1er** [python-pillow/Pillow#4863]
Hello, is there any documentation or example of what is required in order to directly call the libimaging functions from C? I am envisioning an application that is written in C that will use the existing C-based libimaging code to perform basic decoding and encoding of images.

I have read over the "Writing Your Own Image Plugin" page, but I still was not sure after reading that of what was going on behind the scenes as far as initialization/cleanup goes. Does anyone know if there are any examples of programs that directly use the libimaging decode/encode functions or what would be required to write such an application?

**Comment by radarhere** [comment]
Hi. Pillow is a Python library. As discussed in #4532, we don't currently have a commitment to direct use of our C code.

https://github.com/python-pillow/Pillow/issues/4532#issuecomment-618255798)
> Pillow makes a commitment to stable public interfaces, which are defined at the Python layer. The C interfaces are explicitly internal, and no effort is made to keep them stable even between minor releases, and no support or warning is given when they change. (IIRC, there are/were people using the internal interfaces, but they've always been explicitly on their own with that)

**Comment by bit-twidd1er** [comment]
I completely understand that and ask this primarily for my own usage (rather than a feature requiest). However, for my personal needs here, I still am interested in working independently to get direct C support working. In #4532, they note that some people have done just this. Do you know of where that code lives and could you point me in that direction?

**Comment by nulano** [comment]
My understanding is that they used a Java library to call the CPython API to interact with Pillow through Python functions. See https://docs.python.org/3/extending/embedding.html for more information.

The internal APIs can be called from Python, although no attempt is made to preserve backwards-compatibility.
