### ISSUE TITLE
FileNotFoundError: [Errno 2] No such file or directory: ...... default.png

### ISSUE THREAD

**Issue by az7139** [python-pillow/Pillow#4870]
After used pyinstaller:
Traceback (most recent call last):
  File "heatmap.py", line 123, in downSmall
  File "heatmap.py", line 150, in addPicture
  File "heatmappy\heatmap.py", line 45, in __init__
  File "heatmappy\heatmap.py", line 70, in colours
  File "heatmappy\heatmap.py", line 121, in _cmap_from_image_path
  File "PIL\Image.py", line 2634, in open
FileNotFoundError: [Errno 2] No such file or directory: 'C:\\Users\\Y.Z\\AppData\\Local\\Temp\\_MEI32202\\heatmappy\\assets\\default.png'
The '_MEI32202' is a random number.

**Comment by radarhere** [comment]
Hi. I think that your question might better be asked over at https://github.com/LumenResearch/heatmappy.

If you think otherwise, please let us know the contents of your initial heatmap.py - at the moment, this isn't a self-contained example.

**Comment by radarhere** [comment]
'C:\Users\Y.Z\AppData\Local\Temp\_MEI32202\heatmappy\assets\default.png' would be determined by
[`_asset_file = partial(os.path.join, os.path.dirname(__file__), 'assets')`](https://github.com/az7139/heatmappy/blob/8fbc1cc5d96667f7a347051c186fc62effece7ed/heatmappy/heatmap.py#L17)
and
[`'default': _asset_file('default.png'),`](https://github.com/az7139/heatmappy/blob/8fbc1cc5d96667f7a347051c186fc62effece7ed/heatmappy/heatmap.py#L66)
So if they aren't finding https://github.com/az7139/heatmappy/blob/master/heatmappy/assets/default.png out of that, it's interesting. What is the path to 'heatmappy\heatmap.py' on your system?

However, yes, if the file doesn't exist at that location, and the path to the image is determined by heatmappy, then this isn't a Pillow question.
