### ISSUE TITLE
.kpg image

### ISSUE THREAD

**Issue by wahello** [python-pillow/Pillow#4877]
[kpg](https://www.fileviewpro.com/en/file-extension-kpg/) format support.

**Comment by radarhere** [comment]
Hi. Am I correct in thinking that you're talking about images generated by Kai's Power Goo, released in 1996? If so, in what situation, and well how, are you using 26 year old software?

Are you interested in Pillow being able to read images from this format, or save images into this format, or both?

**Comment by hugovk** [comment]
Closing due to lack of response.
