### ISSUE TITLE
Can't use Pillow in multi-stage docker build (pre-compiling wheel)

### ISSUE THREAD

**Issue by bailer** [python-pillow/Pillow#4878]
### What did you do?
I have a python application which is dockerized and the docker image is built using multi-stage building to reduce the final file size of the application. I.e. all compiling and building is done in one image and the results of the build is copied into a new image to avoid having tools like gcc in the final image. One approach to achieve this is to build the wheels in the first image, copy the wheels over to the final image and then install them. This seems to have worked in older Pillow versions: https://www.peterspython.com/en/blog/reducing-the-size-of-a-python-application-docker-image-using-python-wheels
### What did you expect to happen?
I expected Pillow to work in the final docker image, having the wheel compiled in the builder image.
### What actually happened?
Installation works but when running the application I receive the error:
```
File "/usr/local/lib/python3.7/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging'
```
### What are your OS, Python and Pillow versions?

* OS: Alpine 3.8
* Python: 3.7
* Pillow: 7.2.0

Stripped down Dockerfile to showcase:
```Dockerfile
FROM python:3.7-alpine3.8 as builderImage
RUN apk update && apk add zlib-dev jpeg-dev gcc musl-dev
COPY ./requirements.txt .
RUN pip wheel -r requirements.txt --wheel-dir=/wheels

FROM python:3.7-alpine3.8
RUN apk update && apk add zlib-dev jpeg-dev
COPY --from=builderImage /wheels /wheels
COPY ./requirements.txt .
RUN pip install --no-index --find-links=/wheels -r requirements.txt
COPY ./app /app
```

**Comment by hugovk** [comment]
What versions of pip and setuptools do you have? Could be worth updating those, just in case.

And please could you paste the output of building Pillow?

**Comment by bailer** [comment]
I seem to have isolated the problem. I was using `tiangolo/uwsgi-nginx-flask:python3.7-alpine3.8` for the final image (in the example Dockerfile I omitted that part) which seems to be the culprit. If I downgrade the python version in both the builder and the final image with the tag `python3.6-alpine3.8`, it works. Same if I upgrade both with tag  `python3.8-alpine`. 
So I don't see this issue being isolated to this repo. I apologize for opening the issue before discovering this. I thought I had explored most options but apparently not! 
If you don't want to investigate this behaviour in this setting you can close the issue

**Comment by radarhere** [comment]
If you would like to close the issue, you can.
What are the contents of requirements.txt? It would save time to be able to replicate this exactly.
