### ISSUE TITLE
FLIR EmbeddedImage

### ISSUE THREAD

**Issue by helenabdr** [python-pillow/Pillow#4880]
* OS: Linux Mint
* Python: 3.7.4
* Pillow: 5.1.0

The problem is when I pass the newly created path instead of the original image path to the ***get_embedded*** function. But I need of new path, I don't know what to do, any suggestion? Thanks ;)

Code:
```python
import io
from PIL import Image
import subprocess
import pathlib
import cv2

im1 = Image.open(pathlib.Path('input/FLIR2705.jpg'))  

im1 = im1.save('geeks.jpg')
print(im1)

def get_embedded(path):

    img_bytes = subprocess.check_output([
        "exiftool", "-EmbeddedImage", "-b", path
    ])

    print(type(img_bytes))

    img_stream = io.BytesIO(img_bytes)

    #print(img_stream.read())
    img = Image.open(img_stream)

    print(img)
    return img

get_embedded('geeks.jpg')

```
Error:
```
Traceback (most recent call last):
  File "/home/helena/Documents/LAR_Celesc/robocelesc_backend/w.py", line 39, in <module>
    get_embedded('geeks.jpg')
  File "/home/helena/Documents/LAR_Celesc/robocelesc_backend/w.py", line 34, in get_embedded
    img = Image.open(img_stream)
  File "/home/helena/Documents/LAR_Celesc/robocelesc_backend/fenv/lib/python3.7/site-packages/PIL/Image.py", line 2590, in open
    % (filename if filename else fp))
OSError: cannot identify image file <_io.BytesIO object at 0x7f28a1f23f50>
```

**Comment by radarhere** [comment]
If I run your code with https://github.com/python-pillow/Pillow/blob/master/Tests/images/hopper.jpg instead of FLIR2705.jpg, and modify your code so that
```python
img_bytes = subprocess.check_output([
    "exiftool", "-EmbeddedImage", "-b", path
])
print("Length of data: "+str(len(img_bytes)))
```
I find that the length of the data is zero.

Do you get zero when you run with your image?
If so, then it sounds like there's a problem with the way that you're calling exiftool.
If not, then could you provide a copy of FLIR2705.jpg so that we can run the script exactly?

**Comment by helenabdr** [comment]
Hi @radarhere! No, I get this result:

> Length of data: 538060
> <class 'bytes'>
> <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=2592x1944 at 0x7FBC6C051F10>

But when I run with **geeks.jpg** I get zero, too. 

Image used
![FLIR2705](https://user-images.githubusercontent.com/54956291/90769742-1d875880-e2c7-11ea-9105-5bbc5247370b.jpg)

**Comment by helenabdr** [comment]
> So the fact that you get zero back from geeks.jpg means that it makes sense that Pillow can't identify the image - there is no image in empty data.
> 
> I guess I just didn't understand what you were trying to say - you're asking why exiftool is able to extract an EmbeddedImage from your original image, but then the embedded image is missing from the image after it is resaved using Pillow.
> 
> Looking at the image, it makes sense that there is a FLIR EmbeddedImage in there. Pillow doesn't currently support this. Are you asking for us to add support for this? If so, is the image that you've attached able to be included in our test suite and distributed under the Pillow license?
> 
> On a practical level though, in your script example, you're not actually try to change the image at all - so could you just copy the file using `shutil`?
> 
> ```python
> import io
> from PIL import Image
> import subprocess
> import pathlib
> import shutil
> 
> shutil.copy('input/FLIR2705.jpg', 'geeks.jpg')
> 
> def get_embedded(path):
> 
>     img_bytes = subprocess.check_output([
>         "exiftool", "-EmbeddedImage", "-b", path
>     ])
> 
>     print(type(img_bytes))
> 
>     img_stream = io.BytesIO(img_bytes)
> 
>     #print(img_stream.read())
>     img = Image.open(img_stream)
> 
>     print(img)
>     return img
> 
> get_embedded('geeks.jpg')
> ```

Exactly! But now I understand that with `Image.save` metadata is not preserved. However, `shutil.copy2` is also not suitable for my question. Because, theoretically, I get only the image, not the image path. So I figured out how to solve without PIL like this: `open ('new_path.jpg', 'wb'). write (image)`
I find it interesting if the Pillow provides this type of support, this image can be used. :)
