### ISSUE TITLE
PIL has kicked the Bitbucket

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#4881]
Bitbucket has deleted old Mercurial repos (and projects and issues):

* https://bitbucket.org/blog/sunsetting-mercurial-support-in-bitbucket

We have a couple of now-dead links to the old PIL repo:

* https://github.com/python-pillow/Pillow/search?q=Bitbucket&type=
* https://github.com/python-pillow/Pillow/blob/3adb2b740f1a01050a6ceb017a444f2e0d1ad94f/docs/about.rst#what-about-pil
* https://github.com/python-pillow/Pillow/blob/cb79b1fa8900adc1617e9518bb8a83d671dc9246/CHANGES.rst#pre-fork

These need removing and the surrounding text rewritten/removed.

cc @aclark4life

**Comment by hugovk** [comment]
For the CHANGES link to https://bitbucket.org/effbot/pil-2009-raclette/commits/all:

I had imported and archived the Hg repo to GitHub a while back. We could link to it:

https://github.com/hugovk/pil-2009-raclette/commits/master

Or even import from there and archive it in the https://github.com/python-pillow org?

**Comment by aclark4life** [comment]
@hugovk Wow RIP mercurial, yeah let's archive everything in effbot related to PIL I guess, let me know if you need any help.

**Comment by hugovk** [comment]
Please could you do the import? I don't have permission. 

Go to https://github.com/new/import
Clone url: https://github.com/hugovk/pil-2009-raclette
Owner: python-pillow 
Name: pil-2009-raclette
Public 

Then import

Then go to https://github.com/python-pillow/pil-2009-raclette/settings and archive this repo.

Thanks!

**Comment by aclark4life** [comment]
@hugovk Oh I see they're gone already from Bitbucket, yes I'll import shortly thanks.

**Comment by aclark4life** [comment]
Curiously this SVN repo is still up http://svn.effbot.org/public/pil/ ...

**Comment by nulano** [comment]
There is also an archive at https://bitbucket-archive.softwareheritage.org/projects/ef/effbot/pil-2009-raclette.html

**Comment by aclark4life** [comment]
Sweet! That's what I was looking for @nulano , thanks

**Comment by nulano** [comment]
Credit for finding it to `@mattip`: https://quodlibet.duckdns.org/irc/pypy/pypy_2020-08-19.log.html#t20:58:41

**Comment by hugovk** [comment]
Interesting, one is not a subset of the other.

The newer Hg repo from https://bitbucket.org/effbot/pil-2009-raclette goes from March 2009 (1.1.6) to June 2011 (unreleased):

* https://github.com/hugovk/pil-2009-raclette/commits/master?after=aafdd4ded034aad7d5fb966dc2d3d287b565e5f3+489&branch=master
* https://github.com/hugovk/pil-2009-raclette/commits/master

The older SVN repo from http://svn.effbot.org/public/pil/ goes from March 2006 (1.1.1) to November 2009 (1.1.7).

* https://github.com/hugovk/pil-svn.effbot.org/commits/master?after=8a87d9b15825dab244d933468d8b05241b599f6e+489&branch=master
* https://github.com/hugovk/pil-svn.effbot.org/commits/master

**Comment by radarhere** [comment]
I feel like maybe we shouldn't be linking to the unreleased PIL changes. If Pillow was forked before that, then referencing it sounds like it just adds confusion.

So #4932 is my suggestion, just linking to http://svn.effbot.org/public/pil/

**Comment by radarhere** [comment]
Between #4894 and #4932, the links are now removed.

Did we still want to import the repository?

**Comment by aclark4life** [comment]
Whatever you think is best, I don't have a strong opinion at this point (I thought I would at some point earlier …)

**Comment by hugovk** [comment]
I'm fine either way too. At least I don't have access to do it, so it'd be someone else's task :)

Anyway, they're both archived under my account for future reference, I've no plans to move or change them:

* https://github.com/hugovk/pil-2009-raclette
* https://github.com/hugovk/pil-svn.effbot.org

**Comment by hugovk** [comment]
OK, let's close this! Thanks!
