### ISSUE TITLE
from PIL import Image causing _imaging.cpython-38-x86_64-linux-gnu.so: __strdup: symbol not found

### ISSUE THREAD

**Issue by rajashekar** [python-pillow/Pillow#4883]
### What did you do?
Used python:3.8.3-alpine3.11 docker image <br>
And Installed all necessary packages.   <br>
```
apk add --update-cache \
        pcre-dev \
        libc-dev \
        linux-headers \
        python3-dev \
        nginx \
        curl \
        bash \
        gcc \
        g++ \
        uwsgi-python3 \
        # psycopg
        postgresql-dev \
        musl-dev \
        libffi-dev \
        freetype-dev \
        lcms2-dev \
        # PILLOW 
        jpeg-dev \
        zlib-dev \
        # pylibmc
        libmemcached-dev \
        openjpeg-dev \
        jpeg \
        libjpeg \
        openjpeg \
        tiff-dev \
        tk-dev \
        tcl-dev \
        harfbuzz-dev \
        fribidi-dev \
        # opencv
        make \
        cmake \
        clang \ 
        clang-dev \
        ninja \
        # tesseract
        leptonica-dev \
        tesseract-ocr \
        tesseract-ocr-dev \
        openssh-server
```

### What did you expect to happen?
`from PIL import Image`. Import should happen without error. 

### What actually happened?
Import of Image is getting failed
```pycon
Python 3.8.3 (default, May 20 2020, 20:46:20)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: Error relocating /usr/local/lib/python3.8/site-packages/PIL/_imaging.cpython-38-x86_64-linux-gnu.so: __strdup: symbol not found
```

### What are your OS, Python and Pillow versions?

* OS: python:3.8.3-alpine3.11 
* Python: 3.8.3
* Pillow: 7.2.0

```pycon
Python 3.8.3 (default, May 20 2020, 20:46:20)
[GCC 9.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: Error relocating /usr/local/lib/python3.8/site-packages/PIL/_imaging.cpython-38-x86_64-linux-gnu.so: __strdup: symbol not found
```

**Comment by wiredfool** [comment]
You're using Alpine, and strdup is something in stdlib, so I'm suspecting that there's something odd with the stripped stdlib on alpine.   We do test on a docker image in alpine, but we're using build-base (gcc) rather than installing both clang and gcc.

I'd recommend installing one compiler stack, specifically the one that's used for building python in the base images. (I suspect that's gcc)

**Comment by loelkes** [comment]
Normally I would install and compile everything in a container and then copy then resulting venv to another container, without all the tools required for installation. This works fine, except for pillow.

With `python3.9-alpine` I have to add `gcc musl-dev zlib-dev jpeg-dev` (and run `pip install --force pillow`) in the final container. This doubles the size of my images. Is there really no other option?

**Comment by radarhere** [comment]
@loelkes if you're talking about docker containers, it looks like https://github.com/docker-library/docs/issues/904 might be preventing our prepackaged manylinux wheels from installing.

**Comment by nulano** [comment]
There is an ongoing effort to add support for musl based wheels to Python, but it's not fully implemented yet: https://discuss.python.org/t/wheels-for-musl-alpine/7084/56

> With python3.9-alpine I have to add gcc musl-dev zlib-dev jpeg-dev (and run pip install --force pillow) in the final container. This doubles the size of my images. Is there really no other option?

You should be able to remove those extra packages after installing Pillow and keep only the non-dev versions (zlib, jpeg). With other platforms you would be able to build a wheel and copy only that, but as mentioned above, this is not ready yet for musl based distributions such as Alpine.

**Comment by radarhere** [comment]
As for the original problem here, I'm unable to reproduce it using Docker, installing all of the apk packages mentioned, and installing Plllow through pip - https://github.com/radarhere/docker-images/commit/1e74aad83ca36c3fbef3b7c74958234f422a9a21 https://github.com/radarhere/docker-images/runs/2519179362

**Comment by rajashekar** [comment]
@radarhere  - we are currently using python:3.8.3-slim-buster instead of alpine. If its not reproducible, please close this issue. Thanks for looking into this issue.
