### ISSUE TITLE
PIL module is not working

### ISSUE THREAD

**Issue by suryakantamangaraj** [python-pillow/Pillow#4886]
## What did you do?
I try to import the PIL module but it gives an error

### What did you expect to happen?
It should import the module instead of throwing an error

### What actually happened?
It throws ModuleNotFoundError
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
```

### What are your OS, Python and Pillow versions?

* OS: Windows10
* Python: 3.8.5
* Pillow: 7.2.0

```python
import PIL.Image
```

**Comment by suryakantamangaraj** [comment]
```
pip install -U pillow
```
It shows the requirement already up to date.

I was writing a script for the ASCII image generator, and I got the modulenotfound error.

I tried to dry run like, ```import PIL.Image```, or ```import PIL```, however got same error.

**Comment by hugovk** [comment]
And what happens when you run these? Please copy and paste the full output.

```sh
pip --version
python -m site
python -m pip --version
python -m pip install -U pillow
```

How do you run your own script? For example, is it something `python myscript.py` or `python3 myscript.py`?

**Comment by suryakantamangaraj** [comment]
No these are not helpful. I think it's a bug for my system. However, the module is working fine whenever I use ```pil``` instead of ```PIL```.

**Comment by Samar-080301** [comment]
@suryakantamangaraj Can you please show me your code? I'm also having the same error. But writing `pil` didn't help me.
