### ISSUE TITLE
Drawn circle has torn edges

### ISSUE THREAD

**Issue by kawka-maciej** [python-pillow/Pillow#4895]
### What did you do?

Tried to draw a circle.

### What did you expect to happen?

Be able to draw a nice, smooth circle using `draw.ellipse()`.

### What actually happened?

The circle is torn and the edges are bad quality. Did I do something wrong?
<img width="446" alt="Screenshot 2020-09-01 at 18 51 11" src="https://user-images.githubusercontent.com/59606418/91883339-93ef6780-ec84-11ea-80eb-166649a8ddd3.png">

### What are your OS, Python and Pillow versions?

* OS: Mac OS Catalina 10.15.6
* Python:  3.6.7
* Pillow: 7.2.0

```python
from PIL import Image, ImageDraw

target = Image.new("RGB", (400,400), color=(255,255,255))

draw = ImageDraw.Draw(target)

draw.ellipse((50,50,250,250), fill=(0,0,0), outline=None, width=0)

target.save('circle.jpg')
```

**Comment by hugovk** [comment]
Please can you include a minimal code sample?

**Comment by kawka-maciej** [comment]
@hugovk I edited the issue.

**Comment by nulano** [comment]
Just to be clear, the gray pixels around the outside of the ellipse are JPEG compression artefacts. Saving as PNG produces a slightly better image, but the circle is still not smooth.

**Comment by radarhere** [comment]
Here is version of this image created by #4523
![circle](https://user-images.githubusercontent.com/3112309/91946637-ab8d2580-ed42-11ea-999e-756f9b322851.jpg)

**Comment by kawka-maciej** [comment]
This one looks much nicer! Are there any plans when it will be released?

**Comment by kawka-maciej** [comment]
Is there an easy way to build the .whl locally with the version from the PR? I tried reproducing `multibuild` pipeline inside a docker container but couldn't get it to work. The wheels that I'm building don't have required libraries (like the `Pillow.libs` that you get after installing it from pip).

**Comment by radarhere** [comment]
Is this what you're after? [Pillow-7.2.0.dev0-cp36-cp36m-macosx_10_10_x86_64.whl.zip](https://github.com/python-pillow/Pillow/files/5177338/Pillow-7.2.0.dev0-cp36-cp36m-macosx_10_10_x86_64.whl.zip)

**Comment by radarhere** [comment]
Ah. I presumed you were in the same environment as your original post.

For the releases, Pillow has the [pillow-wheels](https://github.com/python-pillow/pillow-wheels) repository, which runs on https://travis-ci.org/. I can create a [commit in my fork of pillow-wheels](https://github.com/radarhere/pillow-wheels/commit/bb646c4fa1afcd44d66fb9df9c535ea3136e8f2c), that
- checks out Pillow with the relevant commit
- removes the Travis jobs that I'm not interested in
- uploads the resulting wheel to https://www.file.io/

And the URL for the wheel is printed - https://travis-ci.org/github/radarhere/pillow-wheels/builds/724418755#L5539

**Comment by kawka-maciej** [comment]
Works perfectly, thank you very much for the explanation! Is there any way I could help with the `4523` issue so it could be merged?

**Comment by hugovk** [comment]
https://github.com/python-pillow/Pillow/pull/4523 has been merged and will be in next week's release.

**Comment by DeusAres** [comment]
Can we reopen this? It would really need an antialiasing method. Super sampling is expensive

**Comment by radarhere** [comment]
@DeusAres could you create a new issue with more detail?
