### ISSUE TITLE
OSError: screen grab failed (Windows Server 2012 R2)

### ISSUE THREAD

**Issue by daeeros** [python-pillow/Pillow#4899]
Hi, when i connecting in remote desktop, and see how work script in working normal, after i close remote desktop, my script going flood error with OsError: screen grab filed how i can fix it? Pillow last version, Caffeine not helped for me((

i see that https://github.com/python-pillow/Pillow/issues/1601 but i cant see there fix

**Comment by radarhere** [comment]
This sounds to me more like #2631.

https://github.com/python-pillow/Pillow/issues/2631#issuecomment-611380446

> Because of the secure concern, please check from this "https://stackoverflow.com/questions/27770010/powershell-screen-capture"
> Quote: In short, this can only create correct screenshots if run from under the logged in user. Scheduled tasks qualify if users match. Running as system or local admin won't allow you to get screenshots.

**Comment by nulano** [comment]
I think for Windows Server this might be closer to "there is no desktop to capture".

According to https://docs.microsoft.com/en-us/windows/win32/winstation/window-stations:
> A window station contains a clipboard, an atom table, and one or more desktop objects. [...] When a window station is created, it is associated with the calling process and assigned to the current session.
>
> The interactive window station is the only window station that can display a user interface or receive user input. [...] All other window stations are noninteractive, which means they cannot display a user interface or receive user input.
>
> When a user logs on to a computer using Remote Desktop Services, a session is started for the user. Each session is associated with its own interactive window station named "WinSta0". [...]

From this it sounds to me like the desktop doesn't exist (so you can't take a screenshot) while you are not logged in via Remote Desktop.

One idea I would try is to check whether the server is plugged in to a monitor (even if the monitor is off), or at least [thinks it is](https://superuser.com/questions/947291/can-a-fake-second-display-be-enabled-in-windows-10). This might trick Windows into keeping an interactive window session active after you log out.

**Comment by radarhere** [comment]
@daeeros did you come to any conclusions about this?

**Comment by daeeros** [comment]
@radarhere yes, i make a bat script with this:

```
@echo off
echo.
echo Remote Desktop will be temporarily disconnected . . . please reconnect after a few seconds.
echo.
pause
@echo on
REM The active session has an arrow as the first character
setlocal EnableDelayedExpansion
FOR /F %%A in ('qwinsta') do (
set tempSessionName=%%A
if "!tempSessionName:~0,1!"==">" (
@echo on
tscon.exe !tempSessionName:~1! /v /dest:console
@echo off
)
)
pause
```

you need tu run it, and after rdp is disconnecting you, its ok, now you need to connect with another remote app to you machine, i use, anydesk, you need to install it in machine before start script, now you run script and can close anydesk app it will worked.

**Comment by mhmehdi** [comment]
I have the same problem but I can not install anydesk Is there another solution?

**Comment by YeeaaahMan** [comment]
Hello,
We also faced with this problem on our remote BuildAgent. 
### Problem behavior
```
# After reboot [screenshot OK]
PS C:\BuildAgent\work\p> qwinsta
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
 services                                    0  Disc
>console           User                      1  Active

# After RDP connection [screenshot OK]
PS C:\BuildAgent\work\p> qwinsta
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
 services                                    0  Disc
>rdp-tcp#9         User                      1  Active

# Switch connection to console (RDP session will be terminated) [screenshot OK]
PS C:\BuildAgent\work\p> tscon 1 /dest:console
PS C:\BuildAgent\work\p> qwinsta
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE
 services                                    0  Disc
>console           User                      1  Active
 rdp-tcp                                 65536  Listen

# RDP is reconnected [screenshot OK]
PS C:\BuildAgent\work\p> qwinsta
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE 
 services                                    0  Disc
>rdp-tcp#11        User                      1  Active
 console                                     2  Conn
 rdp-tcp                                 65536  Listen
 
# RDP is disconnected [screenshot FAIL - OSError: screen grab failed]
PS C:\BuildAgent\work\p> qwinsta
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE 
 services                                    0  Disc
>                  User                      1  Disc
 console                                     2  Conn
 rdp-tcp                                 65536  Listen
 
# Set console seccion is active again [screenshot OK]
PS C:\BuildAgent\work\p> tscon 1 /dest:console
PS C:\BuildAgent\work\p> qwinsta
 SESSIONNAME       USERNAME                 ID  STATE   TYPE        DEVICE 
 services                                    0  Disc
>console           User                      1  Active
 rdp-tcp                                 65536  Listen
 ```
### Solution
Create a bat-file on remote machine
```
(qwinsta | findstr /r "Active" >NUL) || tscon 1 /dest:console
```
Add a rule in Task Scheduler on remote machine
- open Task Scheduler then click **Create task...**
- General: select **Run whether user is logged on or not**
- Triggers: 
  - Begin the task: **On disconnect from user session**
  - Specific user: **User**
  - Delay task for: **no** (or 2 seconds if not work)
  - Enabled: **yes**
- Actions: add bat-file
- Conditions: disable all
## How it works
When you disconnect, scheduler immediately start bat-file. If it don't match any Active sessions, it switch console to Active state automatically.
