### ISSUE TITLE
Approve & Install Mergify

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#4900]
OK give me your best Mergify pitch, @hugovk ! Thanks

<img width="928" alt="Screen Shot 2020-09-03 at 11 43 49 AM" src="https://user-images.githubusercontent.com/72164/92137266-f35f8b80-edda-11ea-85a2-13beb53e4c43.png">

**Comment by hugovk** [comment]
Was just about to open an issue for this :)

Use case: there's a PR I want to merge, but the CIs are still running. Right now, I need to hang around for ~10 minutes before clicking merge (well, I _could_ merge before they finish, but it's nearly always best to make sure they pass).

Sometimes I'll just approve it now, and check back later.

With Mergify, I can add a label like `automerge`, and it'll automatically merge when the CIs pass. No more hanging around, let the robots do the work for us.

We can define other rules too, and I'd suggest: only merge a PR that has been explicitly approved.

**Comment by aclark4life** [comment]
@wiredfool Any thoughts?

**Comment by aclark4life** [comment]
@hugovk Just Pillow repo needed right?

**Comment by hugovk** [comment]
It'd be of most use for the Pillow repo. And would be great to have docker-images and pillow-wheels too, they're updated less often but their CIs take [~30 mins](https://travis-ci.org/github/python-pillow/docker-images/builds/727648140) and [~60 mins](https://travis-ci.org/github/python-pillow/pillow-wheels/builds/726264804).

I don't need it for the other repos.

**Comment by aclark4life** [comment]
Done!

<img width="1131" alt="Screen Shot 2020-09-17 at 12 12 40 PM" src="https://user-images.githubusercontent.com/72164/93498116-56731700-f8df-11ea-9607-c24cfe5aa7c8.png">

**Comment by hugovk** [comment]
Thanks! I'll create the config files.

**Comment by hugovk** [comment]
* [ ] https://github.com/python-pillow/docker-images/pull/84
* [ ] https://github.com/python-pillow/pillow-wheels
* [ ] https://github.com/python-pillow/Pillow
