### ISSUE TITLE
Raster-to-vector conversion of color images using Pillow

### ISSUE THREAD

**Issue by hongyi-zhao** [python-pillow/Pillow#4903]
Hi,

Can I convert color images in raster formats, say, JPG, PNG, GIF, etc., to PDF, SVG, or EPS formats with Pillow?

Best regards,
HY

**Comment by radarhere** [comment]
Pillow can read JPG, PNG and GIF.
It can save to PDF and EPS, but it cannot currently save to SVG.

```python
from PIL import Image
im = Image.open("Tests/images/hopper.jpg")
im.save("hopper.pdf")

im = Image.open("Tests/images/hopper.png")
im.save("hopper.eps")```

**Comment by hongyi-zhao** [comment]
What's bitmap tracing algorithm used for this job?

**Comment by radarhere** [comment]
No, at the moment, Pillow isn't the library that you will want to use for this. The Pillow API handles images in terms of pixels. It does not allow you to remove vector lines.

**Comment by hongyi-zhao** [comment]
If so, what's the appropriate python libraries for me to do this type of job?

**Comment by radarhere** [comment]
https://pypi.org/project/pypotrace/ looks like it has potential.

**Comment by radarhere** [comment]
Was that helpful?

Do you have further questions, or a feature request for Pillow, or can this be closed?

**Comment by hongyi-zhao** [comment]
It seems there has so few such python libraries which can do the job disscussed here. Anyway, thanks for your help.
