### ISSUE TITLE
Having issue with Harfbuzz while following depends/install_raqm_cmake.sh to install libraqm

### ISSUE THREAD

**Issue by sssikarwar** [python-pillow/Pillow#4904]
Hi Team,

I am working on a project which requires Hindi font placement on image and I am getting the following error:
`'setting text direction, language or font features is not supported without libraqm'`

So I have tried libraqm installation process. I am at the last step when it's mentioned:
`"Then see depends/install_raqm_cmake.sh to install libraqm."`

So, when I run the following command:
`cmake ..`

Everything goes well except this error:
```
-- Checking for module 'harfbuzz>=0.9.20'
--   No package 'harfbuzz' found
CMake Error at /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindPkgConfig.cmake:545 (message):
  A required package was not found
Call Stack (most recent call first):
  /Applications/CMake.app/Contents/share/cmake-3.18/Modules/FindPkgConfig.cmake:733 (_pkg_check_modules_internal)
  CMakeLists.txt:147 (pkg_check_modules)
-- Configuring incomplete, errors occurred!
```

In fact, Harfbuzz is installed in my system because when I run the following code:
`brew install freetype harfbuzz fribidi`

I get this:
```
Warning: freetype 2.10.2 is already installed and up-to-date
To reinstall 2.10.2, run `brew reinstall freetype`
Warning: harfbuzz 2.7.2 is already installed and up-to-date
To reinstall 2.7.2, run `brew reinstall harfbuzz`
Warning: fribidi 1.0.10 is already installed and up-to-date
To reinstall 1.0.10, run `brew reinstall fribidi`
```

Installing libraqm is so critical for me. I am a bit new to coding but I really need the complex text layout solution for my project. I appreciate if you can help me to solve it.

**Comment by radarhere** [comment]
Hi. Could you run `python -m PIL | grep RAQM` and let us know the output? Just to check whether or not Pillow is detecting RAQM.

For example, on my system, I get
```
--- RAQM (Bidirectional Text) support ok, loaded 0.7.0
```

**Comment by khaledhosny** [comment]
You should be able to `brew install libraqm` instead of building it from source.

**Comment by sssikarwar** [comment]
> Hi. Could you run `python -m PIL | grep RAQM` and let us know the output? Just to check whether or not Pillow is detecting RAQM.
> 
> For example, on my system, I get
> 
> ```
> --- RAQM (Bidirectional Text) support ok, loaded 0.7.0
> ```

I am getting this message:
*** RAQM (Bidirectional Text) support not installed

**Comment by sssikarwar** [comment]
Sorry, I am new so closed this by mistake.

Thanks, @radarhere and @khaledhosny. 

When I ran `python -m PIL | grep RAQM`, I got the following message:
`*** RAQM (Bidirectional Text) support not installed`

But when I ran `brew install libraqm` and tried again, I got the following message:
`--- RAQM (Bidirectional Text) support ok, loaded 0.7.0`

But In Python, I am getting the same message:
`'setting text direction, language or font features is not supported without libraqm'`

`print(features.check('raqm'))` is also `False`

**Comment by radarhere** [comment]
If you're seeing `--- RAQM (Bidirectional Text) support ok, loaded 0.7.0`, then `print(features.check('raqm'))` really shouldn't return `False`.

Are you sure you're using the same version of Python for both of these commands?

**Comment by sssikarwar** [comment]
I guess you are right. A few minutes back, I also realized the same. Checking on it right now.

**Comment by sssikarwar** [comment]
@radarhere I am glad you mentioned the above question. Because of this, I could think more of this way and this is the reason and solution to my problem as well.

This is my current situation:

```
python -m PIL | grep RAQM
--- RAQM (Bidirectional Text) support ok, loaded 0.7.0
 
python3.7 -m PIL | grep RAQM
RAQM (Bidirectional Text) support not installed
```

So when I work in Pycharm with Project Interpreter "Python 3.7" It doesn't work. So I tried jupyter notebook which is showing "Python3", it worked perfectly.

I need one last favor please, how can I get `--- RAQM (Bidirectional Text) support ok, loaded 0.7.0` message on `python3.7 -m PIL | grep RAQM` command.

**Comment by radarhere** [comment]
Have you tried uninstalling and re-installing Pillow?

**Comment by sssikarwar** [comment]
I just uninstalled Pillow from Python3.7, Python3.8, and Jupyter notebook and re-installed using the command line.

It installed the Pillow with Python3.7 which is fine for my project in Pycharm but raqm feature is not working here.

I uninstalled and re-installed libraqm and it's dependencies as well.

**Comment by sssikarwar** [comment]
Hey @radarhere 

I used anaconda3 python path in Pycharm and it worked fine. When I made a build using py2app and Python3.8 (latest version), it was good to go. I tested the build in another mac also and it worked fine. I had to install brew and libraqm in another mac though.
