### ISSUE TITLE
ImagingEffectSpread: 0 division error

### ISSUE THREAD

**Issue by narupo** [python-pillow/Pillow#4906]
https://github.com/python-pillow/Pillow/blob/4634eafe3c695a014267eefdce830b4a825beed7/src/libImaging/Effects.c#L136

`distance` value is not checked in this function. So if `distance` value is `0` then happen `0` division error.
Need check this variable value before expression.

**Comment by radarhere** [comment]
Thanks for reporting this. I've created PR #4908 to fix it.
