### ISSUE TITLE
Not able to parse particular greyscale .ico file

### ISSUE THREAD

**Issue by IowaIowa** [python-pillow/Pillow#4911]
I have dumped this .ico file from ResHacker from some particular PE file. I use `IcoImagePlugin.IcoImageFile` but getting:
```
python37\lib\site-packages\PIL\Image.py:800: in frombytes
    raise ValueError("not enough image data")
```
when debugging it seems that it derives bpp as 8 instead of 1.
[Icon4.zip](https://github.com/python-pillow/Pillow/files/5192877/Icon4.zip)

**Comment by nulano** [comment]
It looks like `bpp` is coming from https://github.com/python-pillow/Pillow/blob/9e6dabf0e51b96146e4fa53642d3f8bf4a1ca460/src/PIL/IcoImagePlugin.py#L189-L195 using the table https://github.com/python-pillow/Pillow/blob/9e6dabf0e51b96146e4fa53642d3f8bf4a1ca460/src/PIL/BmpImagePlugin.py#L39-L47 but for 1bpp images, the mode is first set to `P` based on this table, but then converted to `1` here https://github.com/python-pillow/Pillow/blob/9e6dabf0e51b96146e4fa53642d3f8bf4a1ca460/src/PIL/BmpImagePlugin.py#L242-L244

Changing the first block to
```python
            bpp = header["color_depth"]
```
lets the image load with just a warning
![Icon4](https://user-images.githubusercontent.com/3819630/92562200-d82acb00-f275-11ea-9b46-4fefd2649d5b.png)
```
c:\git\pillow\src\PIL\IcoImagePlugin.py:299: UserWarning: Image was not the expected size
  warnings.warn("Image was not the expected size")
```
but I suspect this could introduce a security vulnerability. The proper fix would probably be to add a special case to `IcoImageFile` for 1bpp images.

**Comment by radarhere** [comment]
@IowaIowa are there any icons like this that we could add to our test suite, to be distributed under the Pillow license?

**Comment by radarhere** [comment]
Allowing the file to dictate `bpp` doesn't introduce a security problem because it's entirely within the Python layer.

I've created PR #5429 to resolve this.
