### ISSUE TITLE
Color of image changed after paste

### ISSUE THREAD

**Issue by caojianfeng** [python-pillow/Pillow#4913]
### What did you do?
Load an Image from jpeg file.And paste it to a new image.

### What did you expect to happen?

The  image pasted with out change.

### What actually happened?
The image color changed.(0x5196f7 -> 0x6295f0)

### What are your OS, Python and Pillow versions?

* OS: mac os 10.15.4
* Python: 3.7.8
* Pillow: 7.2.0

```python
from PIL import Image
img1 = Image.new('RGB', (1125, 2436), '#ffffffff')
img = Image.open("2.jpeg")
img.show()
img1.paste(img, (0, 0))
img1.show()
```
2.jpeg
![source image: 2.jpeg](https://user-images.githubusercontent.com/11853564/92728999-41106100-f3a4-11ea-9bad-442a4ca74589.jpeg)

<img width="407" alt="screen_shot for source image and paste image" src="https://user-images.githubusercontent.com/11853564/92729018-48376f00-f3a4-11ea-98c0-fa5fd0c991ae.png">

**Comment by radarhere** [comment]
Hi. The new image that you create has an empty [info dictionary](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#info). However, the image you opened has an [icc_profile](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg) - see https://en.wikipedia.org/wiki/ICC_profile for more information.

I find that if you copy the icc_profile, then both images look the same.

```python
from PIL import Image
img1 = Image.new('RGB', (1125, 2436), '#ffffff')
print("Number of values in new image info dictionary: "+str(len(img1.info)))  # Number of values in new image info dictionary: 0
img = Image.open("2.jpeg")
print("Number of values in opened image info dictionary: "+str(len(img.info)))  # Number of values in opened image info dictionary: 8
img.show()
img1.paste(img, (0, 0))
img1.info['icc_profile'] = img.info['icc_profile']
img1.show()
```

**Comment by caojianfeng** [comment]
Thank you very much. @radarhere . 
Your solution work for me .
And I learned a lot from you.

**Comment by caojianfeng** [comment]
And I have another question . 
If I had two image to be pasted, which had diff icc_profiles.
What should I do.

**Comment by caojianfeng** [comment]
```python
from PIL import Image
imgNew = Image.new('RGB', (1125, 2436), '#ffffff')
img2 = Image.open("2.jpeg")
imga = Image.open("a.jpg")
print("img2.icc_profile: ", img2.info['icc_profile'])
print("imga.icc_profile: ", imga.info)

imga.show()
imgNew.paste(img2, (0, 0))
imgNew.info['icc_profile'] = img2.info['icc_profile']
imgNew.paste(imga, (0, 200))
imgNew.show()

```
imga has no icc_profile 
and the color of imga changed after paste
![a](https://user-images.githubusercontent.com/11853564/92848327-b61f7d00-f41c-11ea-9a3b-9eb96c930576.jpg)

**Comment by radarhere** [comment]
It would seem to make sense to make that the color of 'imga' changed - it would be because  the ICC profile changed it.

As for how to fix the problem, instead of saving the icc_profile with the image, you can also use ImageCms to transform the image. Try this.

```python
from PIL import Image, ImageCms
import io
imgNew = Image.new('RGB', (1125, 2436), '#ffffff')
img2 = Image.open("2.jpeg")
imga = Image.open("a.jpg")

src_profile = ImageCms.getOpenProfile(io.BytesIO(img2.info['icc_profile']))
dst_profile = ImageCms.createProfile('sRGB')
img2 = ImageCms.profileToProfile(img2, src_profile, dst_profile)

imga.show()
imgNew.paste(img2, (0, 0))
imgNew.paste(imga, (0, 200))
imgNew.show()
```

**Comment by radarhere** [comment]
@caojianfeng did that answer your second question?
