### ISSUE TITLE
Trying to merge gif and image file but getting unexpected output... Plz help

### ISSUE THREAD

**Issue by Pratham31** [python-pillow/Pillow#4920]
### What did you do?
Actually I have two files. One is a Transparent gif and the second one is a JPG image and my aim is to use image as a background and gif as a foreground. In short, I want to merge them.

### What did you expect to happen?
I want an image as a background and gif as a foreground. In short, I want to merge them.
### What actually happened?
But using the pillow library is giving me output like this.
![output](https://user-images.githubusercontent.com/56548231/93100469-d07c8380-f6c6-11ea-9195-d3f6af96ef46.gif)

### What are your OS, Python, and Pillow versions?

* OS: Windows
* Python: Python 3.8.5
* Pillow: 

```python
from PIL import Image, ImageSequence
transparent_foreground = Image.open("C:\\Users\\PRATHAMESH\\Desktop\\Python try\\me.jpg")
animated_gif = Image.open("C:\\Users\\PRATHAMESH\\Desktop\\Python try\\celeb (2).gif")

x, y = transparent_foreground.size
frames = []
for frame in ImageSequence.Iterator(animated_gif):
    frame = frame.copy()
    frame.paste(transparent_foreground,(x,y),mask=transparent_foreground)
    frames.append(frame)
    
frames[0].save('output.gif', save_all=True, append_images=frames[1:])
```

**Comment by radarhere** [comment]
This is similar to #4917 - except that issue has disappeared.
Please provide copies of me.jpg and 'celeb (2).jpg' so that we have everything necessary to run your script like you do.

**Comment by Pratham31** [comment]
Yeah Sir, sure.
**me.jpg** - 
![me](https://user-images.githubusercontent.com/56548231/93158697-4ebe4180-f72a-11ea-821a-bda8a949050b.jpg)
**celeb (2).gif** -
![celeb (2)](https://user-images.githubusercontent.com/56548231/93158728-64cc0200-f72a-11ea-89db-5ee31882d70a.gif)
**I want output like this**(made this for reference) -
![final](https://user-images.githubusercontent.com/56548231/93158799-81683a00-f72a-11ea-8902-7077c1cfdc9c.gif)

Note - celeb (2) is a **gif** not jpg.

**Comment by radarhere** [comment]
A few comments.
- As per https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste, a 2-tuple for the `box` argument is the upper left corner of the paste. You want it to be 0, 0, to paste one image exactly on top of the other. If it is the width and height of one of the images, then it will be pasted off down and to the right.
- You've labelled your JPG image as 'transparent_foreground'. This is clearly not correct, as you want the JPG to be the background image.

Given that, and working around a transparency mask error, I get
```python
from PIL import Image, ImageSequence
background = Image.open("me.jpg")
animated_gif = Image.open("celeb (2).gif")

frames = []
for frame in ImageSequence.Iterator(animated_gif):
	output = background.copy()
	transparent_foreground = frame.convert('RGBA')
	output.paste(transparent_foreground, (0, 0), mask=transparent_foreground)
	frames.append(output)

frames[0].save('output.gif', save_all=True, append_images=frames[1:])
```
But there is an issue with the background there.

Instead, see what you think of this - it loops through the pixels and copies them individually, ignoring the transparent or background pixels.
```python
from PIL import Image, ImageSequence
background = Image.open("me.jpg")
animated_gif = Image.open("celeb (2).gif")

frames = []
for frame in ImageSequence.Iterator(animated_gif):
	output = background.copy()
	frame_px = frame.load()
	output_px = output.load()
	transparent_foreground = frame.convert('RGBA')
	transparent_foreground_px = transparent_foreground.load()
	for x in range(frame.width):
		for y in range(frame.height):
			if frame_px[x, y] in (frame.info["background"], frame.info["transparency"]):
				continue
			output_px[x, y] = transparent_foreground_px[x, y]
	frames.append(output)

frames[0].save('output.gif', save_all=True, append_images=frames[1:])
```

**Comment by Pratham31** [comment]
Thank you, sir. It works 👍🏻

**Comment by Pratham31** [comment]
But I have one question that It is taking time to save the GIF, right. Why is it so?

**Comment by Pratham31** [comment]
And after some time it is again showing that weird image.

**Comment by radarhere** [comment]
As is noted in the docs, [manipulating individual pixels like I am doing in my second example is slow](https://pillow.readthedocs.io/en/stable/reference/PixelAccess.html#pixelaccess-class). The first code example I provided is much faster, but has a problem with the background.

With the 'weird image', I presume you're referring to the very last frame of the output GIF?

**Comment by radarhere** [comment]
Not the best way, but the easiest way to fix that would be to just remove the last frame.

```python
from PIL import Image, ImageSequence
background = Image.open("me.jpg")
animated_gif = Image.open("celeb (2).gif")

frames = []
for frame in ImageSequence.Iterator(animated_gif):
	output = background.copy()
	frame_px = frame.load()
	output_px = output.load()
	transparent_foreground = frame.convert('RGBA')
	transparent_foreground_px = transparent_foreground.load()
	for x in range(frame.width):
		for y in range(frame.height):
			if frame_px[x, y] in (frame.info["background"], frame.info["transparency"]):
				continue
			output_px[x, y] = transparent_foreground_px[x, y]
	frames.append(output)

frames[0].save('output.gif', save_all=True, append_images=frames[1:-1])
```

**Comment by Pratham31** [comment]
Can we reduce the file size of GIF?

**Comment by nulano** [comment]
> Can we reduce the file size of GIF?

Not with Pillow, see https://github.com/python-pillow/Pillow/issues/617#issuecomment-293540455 for that.

**Comment by Pratham31** [comment]
And what if I want gif at the left below corner ?

**Comment by Pratham31** [comment]
Any modification in the above removed last frame program ?

**Comment by radarhere** [comment]
Here is a modified version where I first scale down your GIF to half the size, and then locate it in the lower left corner.
```python
from PIL import Image, ImageSequence
background = Image.open("me.jpg")
animated_gif = Image.open("celeb (2).gif")

frames = []
for frame in ImageSequence.Iterator(animated_gif):
	output = background.copy()
	
	# Reduce the GIF to half the size
	frame = frame.resize((frame.width // 2, frame.height // 2))
	
	frame_px = frame.load()
	output_px = output.load()
	transparent_foreground = frame.convert('RGBA')
	transparent_foreground_px = transparent_foreground.load()
	for x in range(frame.width):
		for y in range(frame.height):
			if frame_px[x, y] in (frame.info["background"], frame.info["transparency"]):
				continue
			
			# Offset the y value when setting the pixel
			# since this is now the lower left, rather than the upper left
			output_px[x, y+output.width/2] = transparent_foreground_px[x, y]
	frames.append(output)

frames[0].save('output.gif', save_all=True, append_images=frames[1:-1])
```

There are some bugs in the way that Pillow handles GIFs. The code I have given you in this issue is not ideal, but works because I presume you are personally more interested in an immediate solution than in a permanent one.

**Comment by mahesh548** [comment]
how can we add multiple gif over a jpg file??

**Comment by radarhere** [comment]
You'd like to use a JPEG file as the background for an animated GIF that currently has transparency?

Taking two of our test images,
![hopper](https://user-images.githubusercontent.com/3112309/188261598-ba565800-ceb4-48c3-88d5-b398b281651a.jpg)
![dispose_none_load_end](https://user-images.githubusercontent.com/3112309/188261599-e2d765f7-11e6-4c98-800b-c7e2529494c8.gif)
this code will combine them. The `loop=0`  argument is just to make it loop infinitely, so it is clear that it is animated.
```python
from PIL import Image, ImageSequence

im = Image.open("dispose_none_load_end.gif")
background = Image.open("hopper.jpg")
frames = []
for im_frame in ImageSequence.Iterator(im):
	frame = background.copy()
	frame.paste(im_frame, mask=im_frame.convert("LA"))
	frames.append(frame)
frames[0].save("out.gif", save_all=True, append_images=frames[1:], loop=0)
```
![out](https://user-images.githubusercontent.com/3112309/188261637-b2e75c30-ee0b-44ec-b2c7-55c7ef94685f.gif)

**Comment by mahesh548** [comment]
I want to add 2 animated gif over a jpg image

**Comment by radarhere** [comment]
Ok, adding in another test image,
![dispose_prev_first_frame](https://user-images.githubusercontent.com/3112309/188262094-63f762ac-dbae-4581-8ff3-5382fd7c768a.gif)
```python
from PIL import Image, ImageSequence

gif1 = Image.open("dispose_none_load_end.gif")
gif2 = Image.open("dispose_prev_first_frame.gif")
background = Image.open("hopper.jpg")
frames = []
for gif1_frame in ImageSequence.Iterator(gif1):
	for gif2_frame in ImageSequence.Iterator(gif2):
		frame = background.copy()
		frame.paste(gif1_frame, mask=gif1_frame.convert("LA"))
		frame.paste(gif2_frame, mask=gif2_frame.convert("LA"))
		frames.append(frame)
frames[0].save("out.gif", save_all=True, append_images=frames[1:], loop=0)
```
![out](https://user-images.githubusercontent.com/3112309/188262104-e969a6b7-aeb2-4625-a12a-a2d25b84f3d4.gif)

**Comment by mahesh548** [comment]
thank you soo much

**Comment by radarhere** [comment]
> > Can we reduce the file size of GIF?
> 
> Not with Pillow, see [#617 (comment)](https://github.com/python-pillow/Pillow/issues/617#issuecomment-293540455) for that.

Between #5291 in Pillow 8.2.0 and #7568 when using `optimize` in the upcoming Pillow 10.2.0, GIFs created by Pillow should now be smaller.
