### ISSUE TITLE
Error: unsupported operand type(s) for +: 'OmniClass' and 'list'

### ISSUE THREAD

**Issue by Marocfdshgt** [python-pillow/Pillow#4922]
**What did you do?**

Pip install Pillow
Manual install (download and execute setup.py)

**What did you expect to happen?**

Installing Pillow without issues

**What actually happened?**

Error: unsupported operand type(s) for +: 'OmniClass' and 'list'
Unsuccessful installation

**What are your OS, Python and Pillow versions?**

OS: IpadOS 13.7 (Pythonista App with StaSH)
Python: 3.6.1 (default, Aug 24 2017, 16:20:00) 
[GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
Pillow: 7.2.0

**Error** 

```
Traceback (most recent call last):
  File "/private/var/mobile/Containers/Shared/AppGroup/126F8651-64C6-4D51-B328-4785BA780CF6/Pythonista3/Documents/Pillow-7.2.0/setup.py", line 277, in <module>
    class pil_build_ext(build_ext):
  File "/private/var/mobile/Containers/Shared/AppGroup/126F8651-64C6-4D51-B328-4785BA780CF6/Pythonista3/Documents/Pillow-7.2.0/setup.py", line 317, in pil_build_ext
    + [("add-imaging-libs=", None, "Add libs to _imaging build")]
TypeError: unsupported operand type(s) for +: 'OmniClass' and 'list'
```

**Entered_Command**

Python3 setup.py

**Problem**
Hi, I really need to get this running ASAP for university. I am trying to use bokeh module and was able to install all dependencies except this one (pillow). If you need further info please contact me.

**Comment by radarhere** [comment]
The same error is reported over at https://forum.omz-software.com/topic/5328/can-pytorch-be-in-pythonista. According to that link,
> StaSh pip can only install pure python packages, which means no packages containing or depending on c code.

Pillow does contain C code, so perhaps that is the problem. However, that link does say that Pillow may be included in Pythonista by default. Googling, https://alexwlchan.net/2016/10/tiling-the-plane-with-pillow/ states that Pillow is included in Pythonista.

Are you sure you can't just `import PIL` and find that it's already there?

**Comment by hugovk** [comment]
See also https://omz-software.com/pythonista/docs/ios/PIL.html, which says:

> The version of PIL that is bundled with Pythonista includes some modifications to make it work well on iOS: ...

**Comment by Marocfdshgt** [comment]
aah gotcha ! Thank you ever so much for the links (especially the second one) - everything works fine now thank you for your help
