### ISSUE TITLE
pilfont reference in documentation unclear

### ISSUE THREAD

**Issue by rGunti** [python-pillow/Pillow#4928]
In the documentation about ImageFont (https://pillow.readthedocs.io/en/stable/reference/ImageFont.html) the `pilfont.py` script is referenced. However there is no link to said script and it doesn't exist in this repository (to my knowledge). Therefore it would be good to create a link to where this `pilfont.py` script can be obtained from.

This could also be considered a (low) security risk since inexperienced users may just search for the script online and maybe find malicious code that they might execute, but that is up for debate.

**Comment by hugovk** [comment]
There's already a link in the docs to where you can find it:

> You can use the **pilfont** utility from [pillow-scripts](https://pypi.org/project/pillow-scripts/) to convert BDF and PCF font descriptors (X window font formats) to this format.

(Here's the file: https://github.com/python-pillow/pillow-scripts/blob/master/Scripts/pilfont.py)

**Comment by radarhere** [comment]
Is the real problem perhaps that https://pypi.org/project/pillow-scripts/ lists various scripts, but doesn't list pilfont?

**Comment by rGunti** [comment]
This could definetly also be a problem (even if only for SEO reasons). But thanks for the hint.

**Comment by radarhere** [comment]
I've created PR #5030 as a suggestion to resolve this.
