### ISSUE TITLE
Main pages do not state what Pillow actually is, a short overview would be really useful

### ISSUE THREAD

**Issue by matyasf** [python-pillow/Pillow#4933]
https://pillow.readthedocs.io/en/stable/ begins with 
"Pillow is the friendly PIL fork by Alex Clark and Contributors. PIL is the Python Imaging Library by Fredrik Lundh and Contributors.
Pillow for enterprise is available via the Tidelift Subscription. Learn more."

And then comes a big table of contents beginning with the installation. Finally the project has a good overview at https://pillow.readthedocs.io/en/stable/handbook/overview.html

The situation is similar at this repo's main `readme.md`, I need 3 clicks and know where to look to get an explanation about what this library does. I think this can be confusing especially for beginners

**Comment by radarhere** [comment]
Is it sufficient to just add the Overview section to the README and ReadTheDocs homepage?

```
The Python Imaging Library adds image processing capabilities to your Python interpreter.

This library provides extensive file format support, an efficient internal representation, and fairly powerful image processing capabilities.

The core image library is designed for fast access to data stored in a few basic pixel formats. It should provide a solid foundation for a general image processing tool.
```

**Comment by matyasf** [comment]
I think yes.

**Comment by radarhere** [comment]
Ok, I've created PR #4934

Minor note - if the PR is merged, https://pillow.readthedocs.io/en/stable/ won't be updated until the next release of Pillow. https://pillow.readthedocs.io/en/latest/ will reflect the current state of the master branch though.
