### ISSUE TITLE
Feature request: Make image size check optional when reading bmp files

### ISSUE THREAD

**Issue by alicanb** [python-pillow/Pillow#4938]
Hello,

We are working in an environment where we frequently need to open bmp files larger than 2**31 pixels. The following check is preventing us:

https://github.com/python-pillow/Pillow/blob/44da2c3878c9def8a103b19b0915aa774985aee1/src/PIL/BmpImagePlugin.py#L166 

My understanding is PIL can actually support sizes larger than 2**31 pixels and this check is heuristic. Can we make this check optional, perhaps disable it if `Image.MAX_IMAGE_PIXELS = None` like DecompressionBombError?

Best

**Comment by radarhere** [comment]
Do you mind if we close this as a duplicate of #4939?

**Comment by alicanb** [comment]
Of course, I noticed that as well. Thank you for asking.
