### ISSUE TITLE
[Feature Request] Making BMP pixel size limit configurable

### ISSUE THREAD

**Issue by dhfromkorea** [python-pillow/Pillow#4939]
Hello, I have been a happy user of Pillow for a long time, but new to the developer community. Thank you for making such amazing work available to the world. 

I am writing to ask if **the community would be open to the idea of making the hard-coded BMP [file size limit](https://github.com/python-pillow/Pillow/blob/5ce2fac3d6cfcf9af0f84502d9bd0c2dfcfcb398/src/PIL/BmpImagePlugin.py#L166) configurable by clients**. I need to work with large bmp files whose pixel counts exceed the limit, which does not appear configurable by design. Therefore, when I try opening the large bmp files using PIL, I get `OSError: Unsupported BMP Size`. It appears I need to modify the source code to lift the hard-coded limit.  

I understand, as documented, the motivation is to mitigate the risk with DOS attacks. However, I suppose there might be clients, just like me, that use PIL in an environment where there's a relatively limited DOS risk and are willing to accept the risk in any case.

If the idea makes sense, I'd love to work on a PR.

Look forward to your advice and thoughts.

FYI: the relevant code.

![image](https://user-images.githubusercontent.com/3280262/94590121-2c4b2d00-02c1-11eb-9596-96eed378d6b5.png)

source:

https://github.com/python-pillow/Pillow/blob/5ce2fac3d6cfcf9af0f84502d9bd0c2dfcfcb398/src/PIL/BmpImagePlugin.py#L166

**Comment by radarhere** [comment]
Makes sense to me. `MAX_IMAGE_PIXELS * 2` is smaller than `2 ** 31`, so it's not like we would be loosening the restriction either.

**Comment by alicanb** [comment]
What would be the action here, removing the check altogether, or making it configurable?

**Comment by radarhere** [comment]
I would think the best way forward is to make it configurable, by replacing the check for a size of `2 ** 31` with the more standard `_decompression_bomb_check`.

Users could effectively configure it then by setting `Image.MAX_IMAGE_PIXELS`.

**Comment by dhfromkorea** [comment]
Thank you for sharing your advice about `_decompression_bomb_check`. Since the check is a function of `Image.MAX_IMAGE_PIXELS` that is already configurable, I think it sounds like a clean, natural solution. 

I think a path forward seems clear for us (@alicanb and I work together). We will send a PR soon.

**Comment by radarhere** [comment]
I've created PR #4966 as my suggestion to resolve this.
