### ISSUE TITLE
Windows - Image.save() - IOError: [Errno 13] Permission denied

### ISSUE THREAD

**Issue by Dooque** [python-pillow/Pillow#494]
Hello.

Problem:
When I try to save an opened Image object to a file that was previously created by Image.new() and saved, I have a permission denied error.

Steps to reproduce:
Environment:
Windows 7 (64-bits)
Python 2.7.3
Pillow 2.3.0

Execute the following code

``` python
from PIL import Image
img1 = Image.new('I;16', (10, 10))
img1.save('test.tiff', 'TIFF')
img2 = Image.open('test.tiff')
img2.save('test.tiff')
```

you should see this error

``` python
C:\Python27\lib\site-packages\PIL\Image.py
   1458         if isPath(fp):
-> 1459             fp = builtins.open(fp, "wb")
   1560             close = 1
   1461         else:

IOError: [Errno 13] Permission denied: 'test.tiff'
```

Expected behavior:
It should save the image file, no matter how many references to that file I have.

Of course, I have permission to read/write the file inside the directory I am.
I executed it as Admin, I tried to change the mode from the line 1459 to "r+b", and the error is the same.

NOTE: On Ubuntu 12.04 LTS (same python and pillow versions) this code works well.

Thanks.

**Comment by xiaokangzailushang** [comment]
when i use it , i only use the pathname, it needs a filename
