### ISSUE TITLE
Transparent png converted to green

### ISSUE THREAD

**Issue by German-Corpaz** [python-pillow/Pillow#4941]
Hi, I'm using libimagequant library to optimize a png, and the result is perfect, the only problem is that pngs with transparent background are converted to a green background, i don't know why this is happening, the palette generated is correct is there a solution for this, apart from replacing colors?

Code:

```python
img = img.convert('RGBA')
attr = liq.Attr()
input_image = attr.create_rgba(img.tobytes(), img.width, img.height, 0)
result = input_image.quantize(attr)
out_pixels = result.remap_image(input_image)
out_palette = result.get_palette()
out_img = Image.frombytes('P', (img.width, img.height), out_pixels)
palette_data = []
for color in out_palette:
    palette_data.append(color.r)
    palette_data.append(color.g)
    palette_data.append(color.b)
out_img.putpalette(palette_data)
out_img.save('output.png')
```

**Comment by hugovk** [comment]
Please can you share an example image that causes this?

Your code isn't self-contained. Please share runnable example code. For example, we don't know what's in `img`, or what `liq` is.

**Comment by German-Corpaz** [comment]
Sorry about that

```
from PIL import Image
import libimagequant as liq

img = Image.open("test.png")
img = img.convert('RGBA')
attr = liq.Attr()
input_image = attr.create_rgba(img.tobytes(), img.width, img.height, 0)
result = input_image.quantize(attr)
out_pixels = result.remap_image(input_image)
out_palette = result.get_palette()
out_img = Image.frombytes('P', (img.width, img.height), out_pixels)
palette_data = []
for color in out_palette:
    palette_data.append(color.r)
    palette_data.append(color.g)
    palette_data.append(color.b)
out_img.putpalette(palette_data)
out_img.save('output.png')
```

![test](https://user-images.githubusercontent.com/40673097/94939726-e8b31780-04a8-11eb-8f69-7d94fefb8733.png)

![output](https://user-images.githubusercontent.com/40673097/94939747-eea8f880-04a8-11eb-9c79-ad57cf6dfc03.png)

**Comment by wiredfool** [comment]
Have you tried something like this:


```
img = Image.open("test.png")
quantized = img.quantize(method=Image.LIBIMAGEQUANT)
quantized.save('out.png')
```

https://github.com/python-pillow/Pillow/blob/master/src/PIL/Image.py#L1039

**Comment by German-Corpaz** [comment]
I didnt build pillow to use libimagequant, thats why im doing it the other way.

But i think the error of the bg from transparent to green is coming in the putpalette method, i dont know why but its not using transparency

**Comment by wiredfool** [comment]
There are a few ways to do transparency, either using 'PA' mode (paletted w/ alpha) or setting the im.info['transparency'] value. 

But the basic palletted image doesn't have any transparency, as you can see by passing in the rgb values, but not alpha.

**Comment by delonleo** [comment]
Issue fixed by RoadrunnerWMC. Please see https://github.com/RoadrunnerWMC/libimagequant-python/issues/1.

**Comment by gofr** [comment]
`putpalette` doesn't look like it supports alpha. But there's an apparently undocumented function that does. Add the following line before the `save()` at the end and I think it works:

    out_img.im.putpalettealphas(bytes(c.a for c in out_palette))

**Comment by radarhere** [comment]
Using the suggestion from @gofr as a starting point, I've put together PR #5089. If that is merged, then the last few lines of your code could be changed to
```python
palette_data = []
for color in out_palette:
    palette_data.append(color.r)
    palette_data.append(color.g)
    palette_data.append(color.b)
    palette_data.append(color.a)
out_img.putpalette(palette_data, "RGBA")
out_img.save('output.png')
```
and the correct result would be generated.
