### ISSUE TITLE
GIF not loading correctly

### ISSUE THREAD

**Issue by mrgkingcs** [python-pillow/Pillow#4943]
![Mi4_broken](https://user-images.githubusercontent.com/39859365/95001291-7170a700-05c0-11eb-909a-dbc2767089b7.gif)
![Mi4_working](https://user-images.githubusercontent.com/39859365/95001292-72093d80-05c0-11eb-89ea-580aad572db5.gif)

### What did you do?
Loaded a GIF image and saved each individual frame as a png.

### What did you expect to happen?
Correct frames to be saved

### What actually happened?
Weird pixel corruption in saved images.

Both 'broken' and 'working' gifs render absolutely fine in Firefox.
If I re-open the 'broken' gif in Aseprite, delete the unused colours from the palette and re-save, then Pillow loads it fine.

Having re-created the GIF from scratch, Pillow loads it fine.

Could it be something to do with there being some pixel indices that are not in the first 10 colours in the broken version?
But then if so, why would Firefox render them perfectly?
I dunno.  I have a workaround anyways, but I found it an intriguing little bug.

### What are your OS, Python and Pillow versions?

* OS: Xubuntu 20.04
* Python: 3.6
* Pillow: 5.2 and 7.2

```python
# this is code from an image compiler for a game, with some debug lines added.
# it's the debug lines that illustrate the bug
testIndex = 0   # debug line

def loadFramesFromFile(self, path):
        file = open(path, "rb")
        result = self.loadFrames(file)
        file.close()
        return result

    def loadFrames(self, byteStream):
        global testIndex  # debug line

        resultList = []
        image = Image.open(byteStream)
        image.load()

        frameIndex = 0

        while True:
            try:
                image.seek(frameIndex)

                image.save("TEST_" + str(testIndex) + ".png")  # debug line
                testIndex += 1  # debug line

                result = FrameData()
                result.width = image.width
                result.height = image.height
                result.pixels = list(image.getdata())
                result.colours = self.generateColourTable(image)
                if "transparency" in image.info:
                    result.transparentIndex = image.info["transparency"]
                else:
                    result.transparentIndex = None
                resultList.append(result)

                frameIndex += 1
            except EOFError:
                break

        return resultList
```

**Comment by radarhere** [comment]
The Global Color Table Flag isn't set. Without it, https://www.w3.org/Graphics/GIF/spec-gif89a.txt
> No Global Color Table follows, the Background Color Index field is meaningless.

And yet, the disposal method is 2, 'Restore to background color'. So, we need to restore to the background color without knowing what that background color is.

**Comment by radarhere** [comment]
I don't suppose you are happy for the image to be included in our test suite, and distributed under the Pillow license?

**Comment by mrgkingcs** [comment]
I do not mind at all!  Thanks for looking into it. :)

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/5390. If you could check it and confirm that it fixes the issue for you, that would be good.

**Comment by mrgkingcs** [comment]
Hi Andrew,

That does indeed fix the issue for me.  Thanks again!

Greg
