### ISSUE TITLE
Need a help with understanding PIL license and its dependencies

### ISSUE THREAD

**Issue by elvisionary** [python-pillow/Pillow#4948]
Hello! 
 
I have a question for you. Maybe you can help me with understanding.
 
As part of the LegalTech project, we are working with documents, in particular with PDF. There are not many libraries for getting images from PDF. 
 
Previously, we used the pdf2image package (https://pypi.org/project/pdf2image/ ) which is MIT licensed.This package has internal dependencies, in particular pillow (https://pypi.org/project/Pillow/ ) whose license is listed as Historical Permission Notice and Disclaimer (HPND) (HPND)and they have indicated that they, like PIL, support the PIL Software License (https://raw.githubusercontent.com/python-pillow/Pillow/master/LICENSE). 
 
A package using PIL has a higher performance compared to its counterparts. I would like to understand is it possible to use this package or packages that have their own license, but have PIL as a dependency, in our project? If yes, then I wanted to understand what obligations are imposed on us in the end. 
 
 
Thanks!

**Comment by aclark4life** [comment]
Good q! Maybe @tieguy can help us with this one too… pretty sure the answer is “it doesn’t matter that it’s a dependency of another package; anyone and everyone that uses Pillow in any context should comply with its (Pillow’s) licensing terms”. Hope that helps!

**Comment by hugovk** [comment]
Not sure if I can help with your question, but noting the PIL Software License has been identified as [HPND](https://opensource.org/licenses/HPND):

* https://github.com/python-pillow/Pillow/issues/1507#issuecomment-476373096
* https://github.com/python-pillow/Pillow/pull/3752

![image](https://user-images.githubusercontent.com/1324225/95091259-e6fa8580-072e-11eb-8862-cf556df80e56.png)

**Comment by elvisionary** [comment]
> Good q! Maybe @tieguy can help us with this one too… pretty sure the answer is “it doesn’t matter that it’s a dependency of another package; anyone and everyone that uses Pillow in any context should comply with its (Pillow’s) licensing terms”. Hope that helps!


Alex, please clarify what restrictions are set by the license? I mean do I understand correctly that this is a permissive license, and you can use the library in a project, including for commercial purposes, without disclosing the source code of our program? Of course, it is necessary to put a copyright notice, but anything else? Thank you.

**Comment by aclark4life** [comment]
IANAL but that's how I read it, include the copyright and the license in any copies plus supporting documentation 😄 So you aren't obligated to publish your source, but you are obligated to include Pillow copyright and HPND license.

**Comment by elvisionary** [comment]
Alex, thanks again, very helpful. 2 more things to clarify (I am sorry to bother you) - 1) on Pillow license page it is said "This License has been voluntarily deprecated by its author" (https://opensource.org/licenses/historical.php). What does this mean for those who would like to use Pillow? 2) I am a bit confused with Pillow dependencies - PIL is licensed under PIL license and it is said that "Like PIL, Pillow is licensed under the open source PIL Software License", but as it is stated before Pillow is licensed under HPND license, right? Could you explain a bit more on this? Thank you.

**Comment by aclark4life** [comment]
@elvisionary Sure, IAMSNAL (I'm still not a lawyer, but) I think that means no new software will be licensed with HPND, that's all. At least, that's how "deprecated" is used in programming and stands to reason the intent is similar. Nothing to do with Pillow though, since Pillow is and will remain licensed HPND for the foreseeable future 😄
