### ISSUE TITLE
Release process creates a dist/*.egg file

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#4981]
### What did you do?

Ran `make release-test` as part of the 8.0.0 release checks.

### What did you expect to happen?

Release tests ran. Nothing created in `dist/`

### What actually happened?

Release tests ran. `dist/Pillow-8.1.0.dev0-py3.9-macosx-10.9-x86_64.egg` was created.

### What are your OS, Python and Pillow versions?

* OS: macOS Mojave
* Python: 3.9
* Pillow: 8.0.0

This comes from the `python3 setup.py install` command. I moved the file away before proceeding, to make sure it wasn't uploaded to PyPI as there wasn't one for the last release:

* https://pypi.org/project/Pillow/7.2.0/#files

But now I look again, these have a single egg:

| Release | egg |
|-|-|
| https://pypi.org/project/Pillow/7.1.2/#files | Pillow-7.1.2-py3.8-macosx-10.9-x86_64.egg |
| https://pypi.org/project/Pillow/7.1.1/#files | Pillow-7.1.1-py3.8-macosx-10.9-x86_64.egg |
| https://pypi.org/project/Pillow/7.1.0/#files | Pillow-7.1.0-py3.8-macosx-10.9-x86_64.egg |  

We don't need to release a single egg file for a single Python version, right? When we have all the wheels?

If we don't need it, can we prevent `python3 setup.py install` creating it, or alternatively, update `RELEASING.md` to remove it?

**Comment by radarhere** [comment]
See https://github.com/pypa/setuptools/issues/1347 for the setuptools issue about this.

See #4990 for my suggested solution - a PR that removes the egg file after `make release-test`.
