### ISSUE TITLE
How to suppress DecompressionBombWarning?

### ISSUE THREAD

**Issue by DankMemeGuy** [python-pillow/Pillow#4987]
### What did you do?

Accidentally submitted before writing the title. My bad.

I received the following error in my script:

C:\Python\lib\site-packages\PIL\Image.py:2834: DecompressionBombWarning: Image size (97542144 pixels) exceeds limit of 89478485 pixels, could be decompression bomb DOS attack.                                                                                                         warnings.warn( 

### What did you expect to happen?

For this not to come up. The image was not a decompression bomb DOS attack. How do I increase the pixel limit?

### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: 3.9
* Pillow: 8.0

```python
code goes here
```

**Comment by radarhere** [comment]
Hi. https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open

> To protect against potential DOS attacks caused by “decompression bombs” (i.e. malicious files which decompress into a huge amount of data and are designed to crash or cause disruption by using up a lot of memory), Pillow will issue a DecompressionBombWarning if the number of pixels in an image is over a certain limit, PIL.Image.MAX_IMAGE_PIXELS.
>
> This threshold can be changed by setting PIL.Image.MAX_IMAGE_PIXELS. It can be disabled by setting Image.MAX_IMAGE_PIXELS = None.
>
> If desired, the warning can be turned into an error with warnings.simplefilter('error', Image.DecompressionBombWarning) or suppressed entirely with warnings.simplefilter('ignore', Image.DecompressionBombWarning). See also the logging documentation to have warnings output to the logging facility instead of stderr.
>
> If the number of pixels is greater than twice PIL.Image.MAX_IMAGE_PIXELS, then a DecompressionBombError will be raised instead.

So
```python
from PIL import Image
Image.MAX_IMAGE_PIXELS = None   # disables the warning
Image.open(...)   # whatever operation you now run should work
```

**Comment by DankMemeGuy** [comment]
Thank you!
