### ISSUE TITLE
Noting GPLv3 licensed font

### ISSUE THREAD

**Issue by hyandell** [python-pillow/Pillow#4995]
I just wanted to note that the following file is under GPLv3, but is not mentioned on the subsequent license file:

* https://github.com/python-pillow/Pillow/blob/master/Tests/fonts/FreeMono.ttf (run strings on the file and the licensing is contained within)
* https://github.com/python-pillow/Pillow/blob/master/Tests/fonts/LICENSE.txt

As the licenses mentioned in the LICENSE.txt are more in line with Pillow's license, I wanted to flag the FreeMono.ttf license in case it was a surprise and wanted to be mentioned in LICENSE.txt, or removed.

**Comment by radarhere** [comment]
Just for reference, the font file was added in #209, a continuation of #202.

I've created #5002 to note the license.
