### ISSUE TITLE
Variable as text string

### ISSUE THREAD

**Issue by knoxvillesjoker** [python-pillow/Pillow#5005]
### What did you do?
Porting variable in python using PIL library in python 3.5

### What did you expect to happen?
Display of interpreted value pulled from array of changing values

### What actually happened?
No matter how I call it I get a string or bool error.  No matter what it will not allow use of an imported variable within the while True: loop.  
Going through the structures there does not appear to be documentation on using variables within the draw.text text string section.  

If I find the appropriate fix I will post an update.

### What are your OS, Python and Pillow versions?

* OS: Raspbian
* Python: 3.5
* Pillow: osdefault

```python
code goes here
```

**Comment by radarhere** [comment]
Hi. Could you post some self-contained code demonstrating the problem?

**Comment by knoxvillesjoker** [comment]
Good point.  

# -*- coding: utf-8 -*-
import time
import subprocess
import digitalio
import board
from PIL import Image, ImageDraw, ImageFont
import adafruit_rgb_display.st7789 as st7789
cs_pin = digitalio.DigitalInOut(board.CE0)
dc_pin = digitalio.DigitalInOut(board.D25)
reset_pin = None
BAUDRATE = 64000000
spi = board.SPI()
disp = st7789.ST7789(    spi,    cs=cs_pin,    dc=dc_pin,    rst=reset_pin,    baudrate=BAUDRATE,    width=240,    height=240,    x_offset=0,    y_offset=80,)
# button i2c assy
import busio
from i2c_button import I2C_Button
i2c = busio.I2C(board.SCL, board.SDA)
button = I2C_Button(i2c)
height = disp.width  # we swap height/width to rotate it to landscape!
width = disp.height
image = Image.new("RGB", (width, height))
rotation = 180
draw = ImageDraw.Draw(image)
draw.rectangle((0, 0, width, height), outline=0, fill=(0, 0, 0))
disp.image(image, rotation)
padding = -2
top = padding
bottom = height - padding
x = 0
font = ImageFont.truetype("/usr/share/fonts/truetype/dejavu/DejaVuSans.ttf", 20)
backlight = digitalio.DigitalInOut(board.D22)
backlight.switch_to_output()
backlight.value = True
while True:
    print(button.status)
    state = button.status[2]
    print(state)
    # Draw a black filled box to clear the image.
    draw.rectangle((0, 0, width, height), outline=0, fill=0)
    # Shell scripts for system monitoring from here:
    # https://unix.stackexchange.com/questions/119126/command-to-display-memory-usage-disk-usage-and-cpu-load
    cmd = "hostname -I | cut -d' ' -f1"
    IP = "IP: " + subprocess.check_output(cmd, shell=True).decode("utf-8")
    cmd = "cat /sys/class/thermal/thermal_zone0/temp |  awk '{printf \"CPU Temp: %.1f C\", $(NF-0) / 1000}'"  # pylint: disable=line-too-long
    Temp = subprocess.check_output(cmd, shell=True).decode("utf-8")
    text = "hello world!"
    raw = "but, bat, acc, nunchuck:, acc, stick, but"
    test = "echo button.status[2]"
    TEST =  subprocess.check_output(test, shell=True).decode("utf-8")
    print(IP)
    print(Temp)
    print(text)
    print(raw)
# Write four lines of text.
    y = top
    draw.text((x, y), IP, font=font, fill="#FFFFFF")
    y += font.getsize(IP)[1]
    draw.text((x, y), Temp, font=font, fill="#FF00FF")
    y += font.getsize(text)[1]
    draw.text((x, y), text, font=font, fill="#F0F0F0")
    y += font.getsize(raw)[1]
    draw.text((x, y), raw, font=font, fill="#ff1900")
    y += font.getsize("state")[1]
    draw.text((x, y), str(state), font=font, fill="#ff1900")
   # Display image.
    disp.image(image, rotation)
    time.sleep(0.1)

**Comment by knoxvillesjoker** [comment]
I discovered the fix after fighting with this for a few weeks.
    y += font.getsize("state")[1]
    draw.text((x, y), str(state), font=font, fill="#ff1900")

the variable has to be stated as: 
str(variablename)

This is not well documented or stated in the documentation anywhere.  

This is part of a bigger project and I am literally teaching myself python as I go.  Your support community is great so I try to contribute by making sure any issues are pointed out so that they can maybe be addressed.

**Comment by radarhere** [comment]
Ok, so from what I can see, `state` is either `0` or `1`.

So a simplified example of your problem is
```python
from PIL import Image, ImageDraw, ImageFont
im = Image.new("RGB", (100, 100))
d = ImageDraw.Draw(im)
d.text((10,10), 1)
```
giving
```
Traceback (most recent call last):
  File "drawtext.py", line 4, in <module>
    d.text((10,10), 1)
  File "PIL/ImageDraw.py", line 289, in text
    if self._multiline_check(text):
  File "PIL/ImageDraw.py", line 264, in _multiline_check
    return split_character in text
TypeError: argument of type 'int' is not iterable
```

I've created #5007 to resolve this by clarifying that the `text` argument must be a string. Let us know if you have any thoughts.

**Comment by knoxvillesjoker** [comment]
Yes the work around i found was to use:
Str(variablename)

To pass the information into the text array and onto the display.  That trick was not documented anywhere and took me a
While to figure out...

Vos | jokers komputer repair | ETCH | 865.278.7725  | Knoxvilles_joker@yahoo.com
