### ISSUE TITLE
PGM and PPM maximum grey/color value is ignored

### ISSUE THREAD

**Issue by gofr** [python-pillow/Pillow#5008]
### What did you do?

```python
from PIL import Image


header = b"""\
P5
15 7
11
"""
data = [
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,  0,  0,
    0,  3,  3,  3,  3,  0,  7,  7,  7,  0,  11,  0,  0,  0,  0,
    0,  3,  0,  0,  3,  0,  0,  7,  0,  0,  11,  0,  0,  0,  0,
    0,  3,  3,  3,  3,  0,  0,  7,  0,  0,  11,  0,  0,  0,  0,
    0,  3,  0,  0,  0,  0,  0,  7,  0,  0,  11,  0,  0,  0,  0,
    0,  3,  0,  0,  0,  0,  7,  7,  7,  0,  11, 11, 11, 11,  0,
    0,  0,  0,  0,  0,  0,  0,  0,  0,  0,   0,  0,  0,  0,  0
]
with open('pil.pgm', 'wb') as fp:
    fp.write(header)
    fp.write(bytes(data))

img = Image.open('pil.pgm')
img.show()
img.save('pil.png')
```

### What did you expect to happen?

Both the image preview and saved PNG show a 15x7 greyscale image with the letters "PIL", where the "P" is dark grey, the "I" light grey and the "L" is white. This is what I see if I load the "pil.pgm" in other software, such as Ubuntu's file manager, image viewer, ImageMagick and GIMP.

### What actually happened?

The PIL letters are all really dark grey.

Pillow only uses the "11" [maxval](http://netpbm.sourceforge.net/doc/pgm.html) to determine how many bytes to use for each pixel. E.g. a value of `10000` makes it use 2 bytes per pixel. It does not use it as the maximum value. It uses 255 as the maximum instead.

Similarly, with 16-bit grey values, the maximum is always 65535.
The same happens for the [RGB P6 format](http://netpbm.sourceforge.net/doc/ppm.html). The maxval is only used to determine the bit depth.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04
* Python: 3.8.5
* Pillow: built from 8dfc0364fef32eaa11fcbf4abe765c072840e27e

**Comment by radarhere** [comment]
I've created PR #6119 to help this. It adds support for arbitrary maxval for P6, and maxval less than 255 for P5 - that fixes the specific code example you've provided.
