### ISSUE TITLE
License inconsistency in setup.py and LICENSE file 

### ISSUE THREAD

**Issue by SoheilSaif** [python-pillow/Pillow#5017]
In setup.py, the license is marked as **HPND** but in LICENSE file, it is marked as **PIL** :

_LICENSE file_
Like PIL, Pillow is licensed under the open source PIL Software License:

_setup.py_
```
try:
    setup(
        ......
        license="HPND",        
        },
        classifiers=[
            "License :: OSI Approved :: Historical Permission Notice and Disclaimer (HPND)",  # noqa: E501
```

Would you please clarify what the actual license is? 
Please either update the LICENSE or setup.py file?

**Comment by aclark4life** [comment]
@SoheilSaif They are one-in-the-same, see #1507 for details. That said, if you want to submit a PR to change that LICENSE file to read "Like PIL, Pillow is licensed under the open source HPND license" … that would probably be a reasonable move at this point. Thanks
