### ISSUE TITLE
Migrate Travis CI from .org to .com

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5020]
https://travis-ci.org has been very slow the past few weeks because Travis CI are moving the infra over to https://travis-ci.com, and have reduced parallel workers on .org from 5 to max 4 (and it's often less).

We can still use https://travis-ci.com for open source.

We will we need to migrate by December 31st, 2020, and it'd be better to do it sooner because the .org performance is so poor.

@aclark4life Please could you migrate our repos over?

Info and instructions here:

* https://docs.travis-ci.com/user/migrate/open-source-repository-migration

I'd like to see at least these three done first:

* [x] https://travis-ci.org/github/python-pillow/Pillow
* [x] https://travis-ci.org/github/python-pillow/docker-images
* [x] https://travis-ci.org/github/python-pillow/pillow-wheels

Can be done later:

* [x] https://travis-ci.org/github/python-pillow/Sane
* [x] https://travis-ci.org/github/python-pillow/pillow-perf

**Comment by aclark4life** [comment]
Done!

<img width="1920" alt="Screen Shot 2020-10-30 at 2 22 46 PM" src="https://user-images.githubusercontent.com/72164/97743082-88b98c00-1abb-11eb-838a-6d021c412393.png">
<img width="1920" alt="Screen Shot 2020-10-30 at 2 22 30 PM" src="https://user-images.githubusercontent.com/72164/97743083-89522280-1abb-11eb-858a-25026ed7c132.png">
<img width="1920" alt="Screen Shot 2020-10-30 at 2 22 20 PM" src="https://user-images.githubusercontent.com/72164/97743085-8a834f80-1abb-11eb-9f2f-887aa9d76d4c.png">

**Comment by hugovk** [comment]
Thank you!

I cancelled the remaining builds on .org which had been running/stalled for 4-5 hours:

![image](https://user-images.githubusercontent.com/1324225/97744253-97ba3180-1aef-11eb-8dad-b357131c9923.png)

And restarted them on .com and they're now building properly!

![image](https://user-images.githubusercontent.com/1324225/97744901-b0771700-1af0-11eb-9f03-3aa7f8d53e1d.png)

There's a few links to update, I'll close this once they're done.

**Comment by hugovk** [comment]
PRs created for all, closing, thanks!
