### ISSUE TITLE
The new pricing model for Travis CI

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5028]
Travis CI announced a new pricing model today:

* https://blog.travis-ci.com/2020-11-02-travis-ci-new-billing

It's not entirely clear how this affects open source, but https://github.com/zopefoundation/meta/issues/38#issuecomment-720638731 looks like the best interpretation:

* You get a free trial of 10k credits to begin (equates to 1,000 Linux minutes; macOS costs more)
* When the trial runs out, they want you to pick a paid plan
* They will offer free credits for OSS "reviewed and allocated on a case by case basis", email support to apply
* Once these run out, you can email support again and ask for more (does this mean not being able to build during the review process?)

It looks like we should move more stuff from Travis CI to GitHub Actions.

cc @python-pillow/pillow-team

# Pillow

* https://travis-ci.com/python-pillow/Pillow

This repo, and the most active.

![image](https://user-images.githubusercontent.com/1324225/97916885-4c588b00-1d5c-11eb-80e1-a5642bb6b8b6.png)

* Let's ditch lint, it's on GHA
* The new CPU architectures Arm64, ppc64le, s390x are unique to Travis, let's keep them there
* 3.6-3.9 (AMD64) builds: let's remove these, we have them on GHA. Is there anything unique to these that aren't included in the equivalent GHA jobs?

# pillow-wheels

* https://travis-ci.com/python-pillow/pillow-wheels

The biggest build, less active. Essential for releases.

![image](https://user-images.githubusercontent.com/1324225/97917346-051eca00-1d5d-11eb-987e-45826b142e40.png)

With great timing, @nulano (thank you!) had already done the work and opened this PR to move all the jobs to GHA, except for Arm64 which need to stay there: https://github.com/python-pillow/pillow-wheels/pull/169.

Let's get that reviewed and merged.

# docker-images

* https://travis-ci.com/github/python-pillow/docker-images

A big build, less active.

![image](https://user-images.githubusercontent.com/1324225/97917243-de609380-1d5c-11eb-9381-aadbd653ce20.png)

Let's shift it all over to GHA. We'll need to set credentials as secrets to upload to Docker Hub. Or alternatively upload to [GitHub Packages](https://docs.github.com/en/free-pro-team@latest/actions/guides/publishing-docker-images#publishing-images-to-github-packages).

# Also

* https://travis-ci.com/github/python-pillow/Sane
* https://travis-ci.com/github/python-pillow/pillow-perf

Least active, might as well move these over too, should be easy enough.

# Checklist

* [x] https://github.com/python-pillow/Pillow/pull/5029
* [x] https://github.com/python-pillow/pillow-wheels/pull/169
* [x] https://github.com/python-pillow/docker-images/pull/94 
* [x] https://github.com/python-pillow/Sane/pull/64
* [x] https://github.com/python-pillow/pillow-perf/pull/107

**Comment by aclark4life** [comment]
Yeah I think @wiredfool likes GitHub Actions … I'm game.

**Comment by umarcor** [comment]
> The new CPU architectures Arm64, ppc64le, s390x are unique to Travis, let's keep them there

See [dbhi/qus](https://github.com/dbhi/qus). It was created and it is used precisely for migrating ARM, PPC64 and S390X jobs to GHA.

**Comment by nulano** [comment]
> > The new CPU architectures Arm64, ppc64le, s390x are unique to Travis, let's keep them there
> 
> See [dbhi/qus](https://github.com/dbhi/qus). It was created and it is used precisely for migrating ARM, PPC64 and S390X jobs to GHA.

Thanks for that, it works quite well. However, the performance is unsurprisingly an order of magnitude slower; arm64 takes ~30m, ppc64le ~50m, s390x ~40m.

Since most of that time is spent installing dependencies, I think it would be reasonable to migrate these jobs to https://github.com/python-pillow/docker-images (since they run in a Docker container anyway). I'm expecting about 5m-10m for the Build and Test steps which is much closer to the current times on Travis, but I haven't got the latter two to pass yet due to [new failed tests](https://github.com/python-pillow/Pillow/issues/4213#issuecomment-721425032).

**Comment by nulano** [comment]
> You get a free trial of 10k credits to begin (equates to 1,000 Linux minutes; macOS costs more)

To quantify this, here is the usage for the past month (6 Oct to 4 Nov):
https://travis-ci.com/github/python-pillow?tab=insights: 38 builds, 1,580 minutes
https://travis-ci.org/github/python-pillow?tab=insights: 208 builds, 12,503 minutes

That is ~140,000 credits per month, assuming it is all Linux (it is more if accounting for macOS builds).

Looking at just the [arm64 wheels on Travis](https://travis-ci.com/github/python-pillow/pillow-wheels/builds/196970155), one build takes ~1h54m, so 10,000 credits is enough for just 8 builds!

---

They do at least mention the possibility of a renewable amount:
> How many credits (build minutes) you’d like to request (should your run out of credits again you can repeat the process to request more or discuss a renewable amount)

**Comment by umarcor** [comment]
> Thanks for that, it works quite well. However, the performance is unsurprisingly an order of magnitude slower; arm64 takes ~30m, ppc64le ~55m, s390x ~45m.

Correct. qemu-user is 5-10 times slower than native execution or KVM. At the same time, in qemu-user some features (lower level signals, etc.) might not be complete, compared to qemu-system. Hence, combining qemu-user and containers might not fit all the use cases. However, when it does, it comes quite handy.

> Since most of that time is spent installing dependencies, I think it would be reasonable to migrate these jobs to python-pillow/docker-images (since they run in a Docker container anyway). The build and test steps alone take ~10m, which is much more reasonable.

Agree. Installing dependencies should be decoupled from building and testing a project. Images with dependencies can be updated weekly or monthly, while the project is expected to be tested more frequently.

**Comment by nulano** [comment]
I've created https://github.com/python-pillow/docker-images/pull/94 to migrate the docker-images job.

**Comment by hugovk** [comment]
Two weeks after the Travis CI change I'm now out of credits, their UI both says they will be replenished and that they won't be replenished. I've emailed them asking for credits, but nothing yet. So it'd be great to move ahead with this!

We now have PRs for all five repos:

* https://github.com/python-pillow/Pillow/pull/5029
* https://github.com/python-pillow/pillow-wheels/pull/169: merged
* https://github.com/python-pillow/docker-images/pull/94: merged, but needs Docker Hub credentials
* https://github.com/python-pillow/Sane/pull/64
* https://github.com/python-pillow/pillow-perf/pull/107

Reviews/merge especially welcome on https://github.com/python-pillow/Pillow/pull/5029.

And @wiredfool please could you add `DOCKER_USERNAME` and `DOCKER_PASSWORD` to https://github.com/python-pillow/docker-images/settings/secrets/actions?

Thanks!

**Comment by wiredfool** [comment]
I've added credentials to the docker-images repo. Any existing credentials aren't going to work anymore, so the automated build on travis is going to fail going forward, if it ever has credits to run again.

**Comment by hugovk** [comment]
Thanks! 

There's no `.travis.yml` at `docker-images` now, so there's nothing for it to build. For good measure, I've also deleted the cron at https://travis-ci.com/github/python-pillow/docker-images/settings and flipped off the "Build pushed branches" and "Build pushed pull requests" toggles.

**Comment by nulano** [comment]
I just got a sort-of notification (blue dot on my profile icon) on GitHub about "GitHub Container Registry" beta: [long link to docs](https://docs.github.com/en/free-pro-team@latest/packages/getting-started-with-github-container-registry/about-github-container-registry)

Looks like it is a free alternative to Docker Hub which recently introduced new usage limits of [200 container image requests per 6 hours](https://www.docker.com/pricing) and is replacing GitHub Packages Docker.

It seems to be easier to set up than before (maybe even easier than Docker Hub), so while I don't think this is needed right now, it might be worth looking into at some point in the future if the limit becomes an issue.

---

> For good measure, I've also deleted the cron at https://travis-ci.com/github/python-pillow/docker-images/settings and flipped off the "Build pushed branches" and "Build pushed pull requests" toggles.

I didn't realize there was a cron job as it was not specified in `.travis.yml`, but it should be easy to set up on GHA as well: https://docs.github.com/en/free-pro-team@latest/actions/reference/events-that-trigger-workflows#scheduled-events

**Comment by hugovk** [comment]
Yeah, the GitHub registry may be useful in the future, but we don't need it right now as GitHub has been working with Docker Hub so GHA isn't affected by the rate limits: https://github.com/actions/virtual-environments/issues/1445#issuecomment-713861495

That's not the case with Travis CI, where the limits do apply: https://travis-ci.community/t/docker-hub-you-have-reached-your-pull-rate-limit/10517. So it's good we've moved our Docker stuff off of Travis!

---

Yup, we had cron enabled for the three main repos, you can only set it via the web UI for Travis. The settings:

* Branch: master
* Interval: weekly (not daily or monthly)
* Options: Do not run if there has been a build in the last 24h (not "Always run")

It would be good to add cron to these three GHA once all merged. GHA is good that you can actually define POSIX cron syntax. We should set them to run at different times/days, would be nice to try and pick "quiet" times, but we're of course a global team so that might not exist :)

---

I'll merge https://github.com/python-pillow/Pillow/pull/5029 tomorrow if there's no further feedback.

**Comment by umarcor** [comment]
> It would be good to add cron to these three GHA once all merged. GHA is good that you can actually define POSIX cron syntax. We should set them to run at different times/days, would be nice to try and pick "quiet" times, but we're of course a global team so that might not exist :)

Hint: you can also set 'dispatch' event keys, in order to programmatically sequence workflows in the same repo or across repos. For example:

- https://github.com/ghdl/ghdl/blob/master/.github/workflows/push.yml#L173-L178
  - https://github.com/ghdl/docker/blob/master/.github/trigger.sh
- https://github.com/ghdl/docker/blob/master/.github/workflows/buster.yml#L8-L9
- https://github.com/ghdl/docker/blob/master/.github/workflows/buster.yml#L47
- https://github.com/ghdl/docker/blob/master/.github/workflows/vunit.yml#L10-L11
- https://github.com/ghdl/docker/blob/master/.github/workflows/vunit.yml#L38-L40
- ...

Note: the default GITHUB_TOKEN cannot trigger multiple subsequent workflows. That's a limitation for preventing unexperienced users creating infinite loops. However, you can achieve it if you use a regular token instead.

**Comment by hugovk** [comment]
I see the credits have now begun counting down at https://travis-ci.com/organizations/python-pillow/plan:

> ### Credits
> 3200 available credits (purchase date: December 02, 2020)
> You have used 6800 of 10000 credits
3200 available

![image](https://user-images.githubusercontent.com/1324225/100900781-de72c100-34cb-11eb-8e0f-f90c7499bf71.png)

---

> ### OSS only credits
> 0 available credits (next replenish date: December 02, 2020)
> You have used 0 of your 0 monthly credits
> 0 available

![image](https://user-images.githubusercontent.com/1324225/100900831-edf20a00-34cb-11eb-9c5e-dd5366dfddee.png)

---

I'll email Travis CI support requesting OSS credits for the python-pillow organisation. In the meantime, to save precious credits I've turned off the remaining crons at https://travis-ci.com/github/python-pillow/Pillow/settings and https://travis-ci.com/github/python-pillow/pillow-wheels/settings.

Let's also use `[CI skip]` when we don't want to test on Travis CI. (`[CI skip]` doesn't work on GHA.)

---

For reference, for my own account, after being out of credits and unable to test anything on Travis for 16 days, they've added 50k whilst they're waiting (11 days and counting) for "managerial approval":

https://twitter.com/hugovk/status/1334054612672901121

So I won't be too surprised if we're out of credits for the January release, which would prevent building aarch64 wheels (the rest are done by GHA). It might be that we can build those on a personal account, or add them to the release later on. Let's see how it goes.

**Comment by hugovk** [comment]
Seven days later, no reply beyond an autoreply, we're down 950 credits, from 3200 to 2250:

![image](https://user-images.githubusercontent.com/1324225/101654733-826ae800-3a49-11eb-8129-a6f5eef62770.png)

At this rate, we'll be out in 2.5 weeks, roughly Christmas day 🎅 🎄 🎁 

I'm not getting my hopes up, [someone else was told](https://twitter.com/james_hilliard/status/1336081776691843072) "credit allocation for OSS projects is on hold as per directives from management".

**Comment by aclark4life** [comment]
@hugovk Only loosely following but I'd say we don't need Travis anymore, and by that I mean I'm not waiting around for them to give us credits. I'd rather find an alternative, even if we have to pay a Travis competitor. Can you tell me if we've completely moved to GitHub Actions or if we need to do more work and once we move there are we done? Or do we need to look for additional, possibly paid alternatives? Thanks

**Comment by hugovk** [comment]
We're in quite a good situation now. 

We've moved pretty much everything we can and everything essential over to GitHub Actions.

We've kept testing of three CPU architectures on Travis for this repo, because they're not available elsewhere. These are quite new to Travis anyway. We could probably ditch two and just keep the big-endian one, that's the most useful.

Similarly, we've moved all wheel building to GHA except some (aarch64) not available elsewhere. These are additions this summer, so probably not the biggest loss if we need to skip them. 

All the other repos are migrated 👍 

I'm not too worried if these things suddenly stop working and have pretty much given up on Travis.

There may be alternatives to fill the gaps, it'll need further investigation (e.g. https://github.com/python-pillow/Pillow/issues/5028#issuecomment-721428190) to find sonething feasible, and see what other projects do.

**Comment by hugovk** [comment]
In https://github.com/python-pillow/pillow-wheels/pull/172#issuecomment-743269682 @nulano suggested temporarily switching off Travis to conserve the last remaining credits. That's a very good idea, as they're going to run out anyway soon.

At https://travis-ci.com/github/python-pillow/Pillow/settings and https://travis-ci.com/github/python-pillow/pillow-wheels/settings I've flipped these left two toggles off:

![image](https://user-images.githubusercontent.com/1324225/101925882-128c6700-3bdb-11eb-99ec-1bc5ec51bbad.png)

Let's remember to turn the pillow-wheels one back on for the release, and when/if we ever get credits.

**Comment by nulano** [comment]
> We've kept testing of three CPU architectures on Travis for this repo, because they're not available elsewhere. These are quite new to Travis anyway. We could probably ditch two and just keep the big-endian one, that's the most useful.
> (...)
> There may be alternatives to fill the gaps, it'll need further investigation (e.g. https://github.com/python-pillow/Pillow/issues/5028#issuecomment-721428190) to find sonething feasible, and see what other projects do.

I've created #5088 and https://github.com/python-pillow/docker-images/pull/98 to move the three non-x86 builds in this repo to GHA Docker tests.

I haven't investigated whether that approach is reasonable for the Arm64 wheel builds yet, but I'm guessing not.

**Comment by hugovk** [comment]
Update: After triggering a wheel build (https://github.com/python-pillow/Pillow/issues/4997#issuecomment-755181986), gone from 2250(?) to 1100:

![image](https://user-images.githubusercontent.com/1324225/103751298-c03f3a00-5010-11eb-9c47-990f255e8ca2.png)

Should be good for one more build (possibly two...) before we're out. I sent Travis support a ping 3 days ago, nothing yet.

**Comment by hugovk** [comment]
Amazing, after ignoring my ticket ping on 6th January, three days ago Travis sent me this!

> Hello Hugo​ ,
> 
> Please accept our sincere apologies for any inconvenience caused due to delays in processing your open-source credit request while we made improvements to the platform. 
> 
> Open source has always been and always will be at the core of what Travis CI stands for. After reviewing your open source qualifications, I am pleased to notify you that 25k credits were added to your account allowing you to resume running OSS builds. When your credits begin running low again, please reach back out to the Support team.
> 
> Credits Consumption Metric
> OS.              # CREDITS PER STARTED BUILD MINUTE
> Linux.          10
> Experimental FreeBSD.         10
> Windows.         20
> MacOS.         50
> 
> 
> Please let us know if you have any questions!
> 
> Thanks and happy building!,
> ​ 
> Your Friends @Travis-CI
> 
> _Note: OSS credits may be used solely with respect to open source projects that reside on a public repository. Please note that in no event shall OSS credits be used in support of commercial or enterprise projects or with respect to any project that resides on a private repository. Travis CI shall determine the amount and frequency of all OSS Credit allotments at its sole discretion and reserves the right to deny, reduce or suspend such allotments._

https://travis-ci.com/organizations/python-pillow/plan now shows:

![image](https://user-images.githubusercontent.com/1324225/114418936-a850f680-9bbb-11eb-9889-76ed0cf7bc19.png)

My confidence in Travis is low after this six-month episode, and I've not received any updates for other projects I'd contacted them about. Plus the necessity to keep an eye on and request credits again.

But I'll re-enable Travis for our repos here, and let's try it for a bit and see how it pans out.

**Comment by hugovk** [comment]
And now re-enabled for pushed branches and PRs at https://travis-ci.com/github/python-pillow/pillow-wheels/settings (our only remaining Travis dependency), and enabled a monthly cron:

![image](https://user-images.githubusercontent.com/1324225/114420416-fa464c00-9bbc-11eb-854f-24ffd2a486f7.png)

**Comment by aclark4life** [comment]
@hugovk Yeah reads more like "OOPS we got called out, and now here's some credits" … but yeah, give it a whirl, while at the same time not relying too heavily on it, I'd say.

**Comment by hugovk** [comment]
Let's close this now, we've moved nearly everything to GitHub Actions, and Travis CI is ticking over okay for where we are using it.

https://app.travis-ci.com/organizations/python-pillow/plan currently looks like:

![image](https://user-images.githubusercontent.com/1324225/132706815-76d7b741-29ab-4aa2-afbc-dd2d84c9e585.png)


Which is the same as April https://github.com/python-pillow/Pillow/issues/5028#issuecomment-817903201 :shrug:


OSS-only tab:

![image](https://user-images.githubusercontent.com/1324225/132706859-c7269ef0-468a-4b50-8775-38d835ed09cd.png)

**Comment by hugovk** [comment]
Another ~5 months later, the numbers haven't changed, and the same as April 2021: 

https://app.travis-ci.com/organizations/python-pillow/plan

![image](https://user-images.githubusercontent.com/1324225/151528487-7aaf794d-6969-41e7-b344-bff3daeaa3d7.png)

![image](https://user-images.githubusercontent.com/1324225/151528646-783c1f86-d53e-4094-baf9-17595bdebd87.png)

**Comment by radarhere** [comment]
Just to state it in this issue - if Travis CI ever does run out of credits, https://github.com/python-pillow/pillow-wheels/pull/247 can be used to move the aarch64 jobs to GitHub Actions, albeit with a much longer execution time.

**Comment by hugovk** [comment]
In https://github.com/python-pillow/pillow-wheels/pull/367 @radarhere noticed Travis CI is playing up again.

* Luckily, that PR is the backup plan, we can build those aarch64 wheels on GitHub Actions instead using emulation.
* Unluckily, instead of each wheel taking about 10 minutes to build on Travis CI, they each take between 1.5 and 4 hours on GHA!

Plan A is to get Travis CI working again.

At https://app.travis-ci.com/github/python-pillow/pillow-wheels, it says:

<img width="1506" alt="image" src="https://user-images.githubusercontent.com/1324225/216845827-4cbf40a6-9c31-4d07-b193-8f95d7ce2468.png">

> Builds have been temporarily disabled for public repositories due to a negative credit balance. Please go to the [Plan page](https://app.travis-ci.com/organizations/python-pillow/plan) to replenish your credit balance or alter your [Consume paid credits for OSS setting](https://app.travis-ci.com/organizations/python-pillow/plan?anchor=oss-consumption).

"More options" > ["Requests"](https://app.travis-ci.com/github/python-pillow/pillow-wheels/requests) confirms that recent builds have been cancelled: "Owner python-pillow does not have enough credits."  🤷 

OK, so let's go to the [Plan page](https://app.travis-ci.com/organizations/python-pillow/plan).

Nope! 🤷 

<img width="213" alt="image" src="https://user-images.githubusercontent.com/1324225/216845910-c960de85-fc43-4711-9bf2-709f20db8309.png">

> There was an error, please try again.

Trying again makes no difference. 🤷  Same thing for the link to "[Consume paid credits for OSS setting](https://app.travis-ci.com/organizations/python-pillow/plan?anchor=oss-consumption)".  🤷 

Well, I see the same error on _my own_ page at https://app.travis-ci.com/github/hugovk/pillow-wheels, but do have "Credits" although zero "OSS only credits". Neither are negative... 🤷 

<table>
<tr>
	<td>
<img width="664" alt="image" src="https://user-images.githubusercontent.com/1324225/216846020-39f2556c-b76b-4eb9-9481-18deba914b01.png">
	<td><img width="663" alt="image" src="https://user-images.githubusercontent.com/1324225/216846032-1adcb4a1-4ee8-4006-81f0-e90d11dc01b1.png">
</table>

Anyway, I also see this:

<img width="325" alt="image" src="https://user-images.githubusercontent.com/1324225/216846119-0de5f21e-92df-4c10-9760-1e5356b21360.png">

No Pillow listed. 🤷 Maybe I need to "[Review and add ](https://github.com/apps/travis-ci/installations/new)your authorized organizations".

But https://github.com/apps/travis-ci/installations/12696639 shows it's already installed for the wheels repo: 🤷 

<img width="541" alt="image" src="https://user-images.githubusercontent.com/1324225/216846202-2ebd6ec3-7d93-4009-a899-b6f90759d6e3.png">

At this point I give up and will contact Travis CI support...

**Comment by hugovk** [comment]
Good news! Quickly fixed by Travis support:

> Thanks for reaching out and very sorry for the issues described here. When you are ready please push a build and let us know if these issues now appear to be resolved.
> 
> Very sorry for the hassle once again and we will follow up on your reply.

Pushing a new build now works and the red banner has been removed:

* https://app.travis-ci.com/github/python-pillow/pillow-wheels/builds/260358931

However, I can't see the plan page, nor trigger or restart builds. I've replied to ask about that.

**Comment by hugovk** [comment]
> However, I can't see the plan page, nor trigger or restart builds. I've replied to ask about that.

After some back and forth, the response was that only admins can see the plan. And I could trigger and restart builds after logout/login/resync.

**Comment by hugovk** [comment]
Cross post from https://github.com/python-pillow/Pillow/pull/7418#issuecomment-1738953569:

<img width="1085" alt="Screenshot 2023-09-28 at 7 18 02 AM" src="https://github.com/python-pillow/Pillow/assets/72164/a25ad166-2e36-45ff-b3ad-4c4b8fb11cea">
