### ISSUE TITLE
Error in RGB to CMYK Calculations 

### ISSUE THREAD

**Issue by foohyfooh** [python-pillow/Pillow#5038]
### What did you do?
I am trying to convert from RGB to CMYK using the Image.convert method

### What did you expect to happen?
Based on the results from [Convert a Color](https://convertacolor.com/) and GIMP, the rgb values [103, 70, 53] should be converted [0, 32, 49, 60] which when scaled to 255 should be [0, 81, 124, 153].

### What actually happened?
When I am running my code, I am getting the CMYK values of [152, 185, 202, 0].

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04
* Python: 3.6.9
* Pillow: 8.0.1

### Code to Reproduce

```python
import numpy as np
from PIL import Image
    
# Original RGB Image
rgb_img = np.zeros((64, 64, 3), dtype=np.uint8)
rgb_img[:, :, 0:3] = [103, 70, 53]

# Convert to CMYK
cmyk_img = Image.fromarray(rgb_img).convert('CMYK')
cmyk_img = np.array(cmyk_img)
print('CMYK Values from Pillow:', cmyk_img[0, 0])

def rgb_to_cmyk(r, g, b, rgb_scale=255, cmyk_scale=255):
    if (r, g, b) == (0, 0, 0):
        # Black
        return 0, 0, 0, cmyk_scale

    # RGB [0, 255] -> CMY [0, 1]
    c = 1 - r / rgb_scale
    m = 1 - g / rgb_scale
    y = 1 - b / rgb_scale

    # Extract out K [0, 1]
    min_cmy = min(c, m, y)
    c = (c - min_cmy) / (1 - min_cmy)
    m = (m - min_cmy) / (1 - min_cmy)
    y = (y - min_cmy) / (1 - min_cmy)
    k = min_cmy

    # Get the CMYK values [0, 1] (2dp) to represent [0%, 100%]
    c, m, y, k = round(c, 2), round(m, 2), round(y, 2), round(k, 2)
    # return c, m, y, k
    
    # Rescale to the range [0, cmyk_scale]
    return int(c * cmyk_scale), int(m * cmyk_scale), int(y * cmyk_scale), int(k * cmyk_scale)

print('CMYK Values from calculations:', rgb_to_cmyk(103, 70, 53))
```

### Code Output
Output
CMYK Values from Pillow: [152 185 202   0]
CMYK Values from calculations: (0, 81, 124, 153)

**Comment by radarhere** [comment]
https://en.wikipedia.org/wiki/CMYK_color_model#Conversion
> Since RGB and CMYK spaces are both device-dependent spaces, there is no simple or general conversion formula that converts between them.

Pillow uses 'no undercolour removal', which is a method that sets K to 0 - https://www.reddit.com/r/photoshop/comments/6kr8m3/how_do_you_turn_off_undercolor_removal_when/djonlwu/
https://github.com/python-pillow/Pillow/blob/0bb6a19cbf250867e708c3c09aa68e857621d272/src/libImaging/Convert.c#L585-L596

So there isn't a single correct way to do this.

**Comment by foohyfooh** [comment]
Thanks for the explanation as to the difference in values.
