### ISSUE TITLE
Installation documentation does not specify dependencies for Alpine Linux Install

### ISSUE THREAD

**Issue by banagale** [python-pillow/Pillow#5045]
Alpine is a common flavor of linux and uses `apk`  as a package manager.

This issue suggests including Alpine in the [Building on Linux section](https://pillow.readthedocs.io/en/latest/installation.html#building-on-linux) of the Installation portion of the Pillow documentation.

It appears the most up-to-date Pillow dependencies under Alpine are listed in [this commit](https://git.alpinelinux.org/aports/commit/?id=7ca6949a98b7c2e77af6c0b5a6f321357909c7f5). Which are:

```
apk add python3-dev py3-setuptools freetype-dev openjpeg-dev \
libimagequant-dev  libwebp-dev tiff-dev libpng-dev lcms2-dev \ 
libjpeg-turbo-dev libxcb-dev zlib-dev
```

I tested the above using Pillow==8.02 and was successful.

Is there an appetite for including Alpine in the documentation? If so, is there any feedback on the above dependency list?

**Comment by radarhere** [comment]
For a dynamic link, see https://git.alpinelinux.org/aports/tree/main/py3-pillow/APKBUILD. The list hasn't changed since the creation of this issue though.

I've created #5361 to resolve this. I replaced libjpeg-turbo-dev with jpeg-dev, and added fribidi-dev, harfbuzz-dev, tcl-dev and tk-dev.

**Comment by banagale** [comment]
Great. Thank you for this and your work on Pillow.
