### ISSUE TITLE
Direct ROI loading of an image, instead of loading the whole image and then cropping

### ISSUE THREAD

**Issue by nai-kon** [python-pillow/Pillow#5046]
Is there any functions to load ROI region of image?
I have a very large image, but only needs specified region(coordinates).
In general, load the entire image using Image.open() then crop it. But it needs a lot of memory so don't wanna to do.
If there are no function like this, I want it on future update.

**Comment by radarhere** [comment]
'imread' is an OpenCV method. Are you sure that your question is about Pillow?

What format is your image in?

**Comment by nai-kon** [comment]
Sorry, I wrong the method name. In correctly, Image.open().

>What format is your image in?
It's a .jpg image.

Should I decode .jpg myself?
If it is uncompressed image, just calculating ROI region byte position then reading it, not difficult.

**Comment by radarhere** [comment]
Pillow does have functionality for decoding an image in pieces - https://pillow.readthedocs.io/en/stable/reference/ImageFile.html#imagefile-module - but according to [one comment](https://github.com/python-pillow/Pillow/issues/1971#issuecomment-227389591)
> Several of the image plugins are not compatible with the feed interface, so if you're actually decoding them, they basically loop around, store the data, and then finally decode it when you close the parser. This includes common types like JPEG and PNG. So, if you're using the feed interface to cut down on the duplicate copies of the data, you aren't.

**Comment by wiredfool** [comment]
There are some image types where decoding a portion of the image is supported by the underlying library (e.g, tiff, especially if stored in a tiled format), some where it may be possible (jpeg), and some where it would be exceedingly unlikely (webp, jpeg2000). 

While a PR would be something that would be considered, I don't see this as a high priority feature.

**Comment by nai-kon** [comment]
@radarhere 
@wiredfool 

Thank you the reply.
I will consider another way, such as use 3rd party library or self decoding.
Close this issue.
