### ISSUE TITLE
How to *efficiently* stream images from Pillow to ffmpeg?

### ISSUE THREAD

**Issue by s-m-e** [python-pillow/Pillow#5049]
I am generating images with Pillow and stream them to an ffmpeg subprocess via a pipe. [My solution](https://github.com/pleiszenburg/bewegung/blob/1d432c2916c4772645ba6b19a7b162235ca2955a/src/bewegung/core/video.py#L474) is inspired by other people doing similar things, e.g. [here](https://stackoverflow.com/q/43650860/1672565) and [here](https://stackoverflow.com/q/13294919/1672565). I am trying to develop a clean, generic and **efficient** solution as part of a [video rendering library](https://github.com/pleiszenburg/bewegung).

I am trying to eliminate unnecessary memory copies and image format conversions. In this context, I was wondering whether you, the Pillow developers, would have any ideas.

Currently, I am launching `ffmpeg` with the following options, among others:

```
                '-f', 'image2pipe', # force input format
                '-i', '-', # data from stdin
                '-vcodec', 'bmp', # input codec
```

It therefore accepts BMPs on stdin. I can now "save" the Pillow image directly into the pipe:

```python
            image.save(ffmpeg_subprocess.stdin, 'bmp')
            ffmpeg_subprocess.stdin.flush()
```

Initially, I was using PNGs - but eliminating the compression/decompression steps involved in using PNGs by going to BMPs alone gave me a significant performance boost.

I poked around in both `ffmpeg` and Pillow. `ffmpeg` can in fact efficiently handle raw binary image data of many formats, e.g. RGBA with & without pre-multiplied alpha etc. "All" I need to do is to tell `ffmpeg` via command line options how the data is structured. `Pillow` on the other hand manages images' data somehow inside the `Image.im` attribute / object, if I understand it correctly. However, I have not yet completely understood how it works internally. For instance, the method [`tobytes`](https://github.com/python-pillow/Pillow/blob/2b87ccae896c0b35a1215f2d454ffe4c547e7d93/src/PIL/Image.py#L707) appears to iterate through the data as part of an encoding procedure which involves iteratively growing a Python list and then joining it to a bytes object. If I knew that my data is available in a certain mode, say RGBA (uint8), in memory then ... could I access it in a different, probably more efficient manner?

What would be the "fastest", most "raw" thing that I could safely and reliably extract from a Pillow image object (for being used as binary data that is being written to a pipe)? Where would you recommend me to start reading (relevant source code for instance)?

**Comment by radarhere** [comment]
Hmm. I might suggest looking at https://github.com/python-pillow/Pillow/blob/master/src/PIL/PyAccess.py as it is actually dealing with the pointers?

**Comment by s-m-e** [comment]
@radarhere Thanks for the reply. This may have sent me onto [an interesting](https://github.com/python-pillow/Pillow/blob/dac4896639341e001a716386f8ad16b9a2ae3908/src/PIL/PyAccess.py#L51) yet also unsafe (?) track:

```python
f = open('/dev/null', 'wb')
print(a.mode, a.width, a.height)
# RGB 1920 1080

%timeit a.save(f, format = 'bmp')
# 3.26 ms ± 31.1 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

%timeit a.save(f, format = 'png')
# 113 ms ± 299 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)

%timeit f.write(a.tobytes())
# 2.69 ms ± 82.6 µs per loop (mean ± std. dev. of 7 runs, 100 loops each)

import ctypes

def get_bytes(image):
    return ctypes.cast(
        ctypes.c_void_p(dict(image.im.unsafe_ptrs)['image32']),
        ctypes.POINTER(ctypes.c_char * (image.width * image.height * 4)),
    ).contents.raw
%timeit f.write(get_bytes(a))
# 1.2 ms ± 62.6 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

def get_bytes_faster(image):
    return ctypes.cast(
        ctypes.c_void_p(dict(image.im.unsafe_ptrs)['image32']),
        ctypes.POINTER(ctypes.c_char * (image.width * image.height * 4)),
    ).contents # no more raw
%timeit f.write(get_bytes_faster(a))
# 8.63 µs ± 103 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

I hope I have done this correctly. The speed gains are impressive. The image however has some issues: Looks like there is some header data in front of the image which is part of the memory that `image.im.unsafe_ptrs` points to. It's 439920 bytes long.
Any idea what may I have missed? 

A "fix" looks about as follows:

```python
def get_bytes_faster_offset(image):
    # assert image.mode == 'RGB'
    return ctypes.cast(
        ctypes.c_void_p(dict(image.im.unsafe_ptrs)['image32'] + 439920), # what's in the 439920 bytes?
        ctypes.POINTER(ctypes.c_char * (image.width * image.height * 4)),
    ).contents
```

**Comment by wiredfool** [comment]
As you probably guessed, unsafe_ptrs isn't a reference to the image data. There isn't actually a block of data for the image (in general), as it's stored in rows, potentially in different blocks of memory. Additionally, each row is padded to a specific byte width, so for some image sizes, there will be gaps between the end of one row's data and the beginning of the next. 

IIRC, unsafe_ptrs is a set of row pointers that each have image.width*4 bytes in them in a contiguous chunk. (in an image32)

**Comment by s-m-e** [comment]
@wiredfool I was being stupid ... thanks! The following works as expected:

```python
def get_bytes_cols(f, image):
    ColType = ctypes.POINTER(ctypes.c_char * (4 * image.width))
    cols = ctypes.cast(
        ctypes.c_void_p(dict(image.im.unsafe_ptrs)['image32']),
        ctypes.POINTER(ColType * image.width),
    )
    for x in range(image.height):
        f.write(cols.contents[x].contents)
        
%timeit get_bytes_cols(f, a)
# 1.66 ms ± 11 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

The profiler tells me that this thing is "only" slowed down by the many calls to the CPython interpreter's `_io.BufferedWriter.write`. I *guess* this is how fast I can get it in pure Python. Doing something like `f.write(b''.join([cols.contents[x].contents.raw for x in range(image.height)]))` is even fife times slower. Maybe handing this particular bit off to C works as fast as I'd expect.

**Comment by wiredfool** [comment]
You might try exporting a raw image, as I think it's basically what you're looking for. It hoists that loop into C, but I don't remember if there are other transforms involved. 

Also.  Unsafe is... not generally safe to use from user code, nor guaranteed to not change implementation. It's a pointer into a raw C struct, and you can read things you don't expect or damage things if you start writing.  I'd generally expect that security releases won't change the unsafe pointers, but you're at your own risk there. Read the C code and make sure you understand what you're doing. I named it unsafe for a reason.

**Comment by s-m-e** [comment]
> You might try **exporting a raw image**, as I think it's basically what you're looking for. It hoists that loop into C, but I don't remember if there are other transforms involved.

This is ideally what I am looking for. It is my understanding that `Image.tobytes(encoder_name='raw', *args)` is doing exactly that, although it loops in Python. Is there another method for that in Pillow right now that I have missed?

>  Unsafe is... not generally safe to use from user code, nor guaranteed to not change implementation. [...]

Hmm I would - in theory - make it part of a library and put proper tests around it. I may also limit the compatibility to certain versions of Pillow if I have to. Well, I am not sure of the speed gain is worth the effort.

> Read the C code and make sure you understand what you're doing. I named it unsafe for a reason.

Understood.

**Comment by wiredfool** [comment]
`Image.tobytes` is probably what you want, but you might need to tweak the bufsize. That would take a patch, or a yanking of the code, but something like this should do all the looping in C:

```
        e = _getencoder(self.mode, encoder_name, args)
        e.setimage(self.im)

        bufsize = self.size[0] * self.size[1] * 4)  # set to the size of the raw bytes of the image

        l, s, d = e.encode(bufsize)
        f.write(d)
        if s < 0:
            raise RuntimeError(f"encoder error {s} in tobytes")
```

**Comment by s-m-e** [comment]
@wiredfool Thanks. Both solutions provide about the same speed as the risky pointer magic from above:

```python
def get_bytes_encoder(f, image):

    e = _getencoder(image.mode, encoder_name = 'raw', args = image.mode)
    e.setimage(image.im)
    
    fh = f.fileno()
    f.flush()
    
    s = e.encode_to_file(fh, image.width * image.height * 4)
    if s < 0:
        raise RuntimeError(f"encoder error {s} in tobytes")

%timeit get_bytes_encoder(f, a)
# 1.55 ms ± 52.9 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)

def get_bytes_encoder2(f, image):

    e = _getencoder(image.mode, encoder_name = 'raw', args = image.mode)
    e.setimage(image.im)
    
    l, s, d = e.encode(image.width * image.height * 4)
    f.write(d)
    if s < 0:
        raise RuntimeError(f"encoder error {s} in tobytes")

%timeit get_bytes_encoder2(f, a)
# 1.54 ms ± 28 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
```

**Comment by radarhere** [comment]
@s-m-e is this resolved for you?

**Comment by s-m-e** [comment]
More or less, yes. Let's close this issue.
