### ISSUE TITLE
Docs: 4th level menu items not showing in dark mode

### ISSUE THREAD

**Issue by MarkSetchell** [python-pillow/Pillow#5053]
The latest (coloured) documentation is completely unusable on macOS in "Dark Mode". You can't see anything in the table of contents (outlined in red in attached screen-grab)!

<img width="1193" alt="Screenshot 2020-11-21 at 18 21 14" src="https://user-images.githubusercontent.com/12937410/99884573-320d2100-2c27-11eb-977f-1e4c259a05a4.png">

**Comment by hugovk** [comment]
What browser and OS versions are you using?

Here's how it looks for me with Chrome 86 on macOS Mojave:

![image](https://user-images.githubusercontent.com/1324225/99884781-6ee21380-2c39-11eb-8413-90c8a999e7ed.png)

**Comment by hugovk** [comment]
Also https://pillow.readthedocs.io/en/stable/ is currently the 8.0.1 docs, but your title says 7.0.0. Please could you also empty your browser cache and reload?

**Comment by MarkSetchell** [comment]
Hi Hugo,

Not sure many Mac users will use Chrome - I think they are FAR more likely to be using Safari on a Mac!

I use Safari 13.1.2 on a macOS Catalina 10.15.6 in Dark Mode

Thank you
Mark

**Comment by hugovk** [comment]
This is how it looks for me with Safari 14.0:

![image](https://user-images.githubusercontent.com/1324225/99885978-a5239100-2c41-11eb-8599-dcdacb2ddb75.png)

Please could you clear your browser cache and reload?

**Comment by MarkSetchell** [comment]
Hi Hugo 

I cleared the cache but it doesn't seem to make any difference on Safari 13. I will probably upgrade to Big Sur macOS 11 in the next 3-5 weeks so maybe that will help.

Best regards
Mark

**Comment by hugovk** [comment]
Is it still showing 7.0.0?

![image](https://user-images.githubusercontent.com/1324225/99886372-a5715b80-2c44-11eb-8d22-f6c4e92a44a0.png)

It should be 8.0.1.

**Comment by hugovk** [comment]
@jeremy-rifkin Please can you show what version of the docs you're on? Is it 7.0.0 or 8.0.1? The release notes page is a good place to check the latest mentioned.

https://pillow.readthedocs.io/en/stable/releasenotes/index.html

Does clearing the browser cache make any difference?

**Comment by nulano** [comment]
I also see this on 8.0.1 release notes, as well as the PR #4968 build. Clearing the cache has no effect, the **4th level** of the menu is unreadable (using Vivaldi (Chromium based) on Windows). which matches **all** of the screenshots above.

@hugovk Try looking at https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#functions directly, that should open the 4th level of the menu.

**Comment by hugovk** [comment]
Thanks!

Please could you test this fix?

https://pillow--5056.org.readthedocs.build/en/5056/reference/ImageFont.html#functions

**Comment by MarkSetchell** [comment]
That looks much better - thank you.

**Comment by jeremy-rifkin** [comment]
@hugovk Apologies for the delayed reply. I was in 8.0.1 and cache clear made no difference.
I can confirm that the fix you just posted works on my end as well. Thank you!

**Comment by EpicWink** [comment]
Same issue in Firefox (83.0) on Linux (Ubuntu 20.04), fixed in [the link above](https://github.com/python-pillow/Pillow/issues/5053#issuecomment-732810383)

**Comment by hugovk** [comment]
This has now been merged and will be on the stable docs site when the next release is done on 2nd January. 
https://pillow.readthedocs.io/en/stable/

In the meantime, you can use the fix at the latest docs version:
https://pillow.readthedocs.io/en/latest/

Thanks all for the reports, reviews, fixes and tests!
