### ISSUE TITLE
Docs: add logo to menu

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5054]
We can add the Pillow logo to the docs menu:

> **`html_logo`**
> If given, this must be the name of an image file (path relative to the configuration directory) that is the logo of the docs. It is placed at the top of the sidebar; its width should therefore not exceed 200 pixels. Default: `None`.

https://www.sphinx-doc.org/en/master/usage/configuration.html

Here's a couple of options: one with the logo, another with logo+text.

Which do you prefer?

| https://pillow-hugovk.readthedocs.io/en/docs-logo/ | https://pillow-hugovk.readthedocs.io/en/docs-logo-text/ |
|:-:|:-:|
| https://github.com/hugovk/Pillow/tree/docs-logo | https://github.com/hugovk/Pillow/tree/docs-logo-text |
| ![image](https://user-images.githubusercontent.com/1324225/99886210-64c51280-2c43-11eb-89de-c576a22115ae.png) | ![image](https://user-images.githubusercontent.com/1324225/99886219-7c9c9680-2c43-11eb-94d6-1ce0e740904c.png) |
| ![image](https://user-images.githubusercontent.com/1324225/99886301-1a906100-2c44-11eb-864d-f05be3b75703.png) | ![image](https://user-images.githubusercontent.com/1324225/99886242-90e09380-2c43-11eb-964a-fd8b4429b00d.png) |
| ![Screenshot_20201121-220557_Chrome](https://user-images.githubusercontent.com/1324225/99886569-3b59b600-2c46-11eb-8c13-7b176bd3d6db.jpg) | ![Screenshot_20201121-220617_Chrome](https://user-images.githubusercontent.com/1324225/99886570-3c8ae300-2c46-11eb-8dd2-a8fa05140cab.jpg) |
| ![Screenshot_20201121-220825_Chrome](https://user-images.githubusercontent.com/1324225/99886572-3d237980-2c46-11eb-9f60-920e8c1eee6d.jpg) | ![Screenshot_20201121-220834_Chrome](https://user-images.githubusercontent.com/1324225/99886573-3d237980-2c46-11eb-8edd-6e76858d5248.jpg) |

**Comment by radarhere** [comment]
My preference is for logo+text. Logo by itself seems rather large.
