### ISSUE TITLE
Glyph transformation before rendering (rasterization)

### ISSUE THREAD

**Issue by SunHaozhe** [python-pillow/Pillow#5059]
With `ImageFont.truetype()` and `ImageDraw.text()`, one can generate text images (bitmaps), on which one can apply various affine transformations. However, applying affine transformations on pixels/bitmaps can induce artefacts and aberration. This is particularly the case when the images are low resolution, for example 32x32.

Since glyphs are defined by [control points of Bézier curve](https://docs.microsoft.com/en-us/typography/opentype/spec/ttch01#outlines) in TrueType fonts and OpenType fonts, it might be better to be able to apply affine transformations on the vector glyph representation before rendering it to images/bitmaps. 

I would like to know if this functionality is possible with `PIL 8.0.1`? If yes, how can I do so?

It seems to me that `PIL` uses FreeType to handle TrueType fonts and OpenType fonts. According to the documentation ([tutorial 1](https://www.freetype.org/freetype2/docs/tutorial/step1.html), [tutorial 2](https://www.freetype.org/freetype2/docs/tutorial/step2.html)) of FreeType, it is better to perform the affine transformation just before the glyph is rendered (section `b. Rendering a Transformed Glyph Sequence` in tutorial 2). FreeType also provides an API for affine transformations `FT_Set_Transform` (section `d. Glyph Transformations` in tutorial 1). Is this functionality supported by `PIL` somehow? 

Thanks for your help!

**Comment by nulano** [comment]
Docs for `FT_Set_Transform` state: https://www.freetype.org/freetype2/docs/reference/ft2-base_interface.html#ft_set_transform

>The transformation is only applied to scalable image formats after the glyph has been loaded. It means that hinting is unaltered by the transformation and is performed on the character size given in the last call to FT_Set_Char_Size or FT_Set_Pixel_Sizes.

From earlier testing `FT_Set_Transform` seems unnecessary to support, you can almost certainly get the same or better results using one of the existing Pillow transformations: https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.transform

`FT_Glyph_Transform` is a bit more interesting, but it is not currently supported in Pillow. I'm also not sure how easy it would be to make it work with Raqm.

**Comment by SunHaozhe** [comment]
Thanks for your reply!

I planned to use `PIL.Image.transform()` for affine transformations, but it turns out that it can introduce artefacts and aberration for low-resolution images, which is not surprising because this function operates on pixels. In consequence, it seems be better to transform the vector representation of glyphs before rendering (rasterizing) them for low-resolution images. That is why I posed this question.

**Comment by nulano** [comment]
I recall reading before that `FT_Set_Transform` only transformed the produced bitmap before, but now I see the docs state it is applied to the outline, so I'm not sure anymore. When I tried it before it produced bad results when shifting glyphs, so I assumed it would be the same for transforms as well. So I can't say whether it is worth supporting without trying it first, at which point the work would already be done...
