### ISSUE TITLE
Compile error on jailbroken ios

### ISSUE THREAD

**Issue by nxli** [python-pillow/Pillow#5079]
### What did you do?
`pip3 install Pillow`
### What did you expect to happen?
successful installation
### What actually happened?
```
ld: library not found for -ljpeg
Not signing file
clang-5.0: error: linker command failed with exit code 1 (use -v to see invocation)
error: command 'clang' failed with exit status 1
```
### What are your OS, Python and Pillow versions?

* OS: Darwin iPad-Pro-97 20.0.0 Darwin Kernel Version 20.0.0: Fri Aug 28 23:05:58 PDT 2020; root:xnu-7195.0.46~9/RELEASE_ARM64_S8000 iPad6,4 arm64 J128AP Darwin
* Python: 3.7.1
* Pillow: 8.0.1

I have already installed libjpeg-turbo and ios SDK
![image](https://user-images.githubusercontent.com/38049831/101288413-06a83b80-37bc-11eb-929a-66a655316dd1.png)

**Comment by aclark4life** [comment]
@nxli Not sure I'd expect successful installation on iOS, but kudos to you for the effort. Cool factor ++

**Comment by radarhere** [comment]
Do we provide support for jailbreaking? Without wanting to start a lengthly debate, there are ethical and [even legal](https://en.wikipedia.org/wiki/IOS_jailbreaking#Legality) questions, and if nothing else, it's not something we're going to be able to setup CI testing for.

**Comment by aclark4life** [comment]
@radarhere We definitely do not provide support for and/or encourage jailbreaking, good point!
