### ISSUE TITLE
ValueError: anchor not supported for multiline text

### ISSUE THREAD

**Issue by AndyZ-Salz** [python-pillow/Pillow#5080]
### What did you do?
use the parameter ``anchor`` in method `ImageDraw.text()` and`ImageDraw.textbbox()`

### What did you expect to happen?
As the Release Notes for 8.0.0:

> The ``anchor`` parameter of :py:meth:`.ImageDraw.text` has been implemented.

&

> Three new methods :py:meth:`.ImageDraw.textbbox`, :py:meth:`.ImageDraw.multiline_textbbox`,
> and :py:meth:`.FreeTypeFont.getbbox` return the bounding box of rendered text.
> 
> These functions accept an ``anchor`` parameter, see :ref:`text-anchors` for details.

so as the Doc for the Module [`ImageDraw`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html)
method [`ImageDraw.multiline_text()`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.multiline_text) and [`ImageDraw.multiline_textbbox()`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.multiline_textbbox) should also accept an ``anchor`` parameter

### What actually happened?
An error:
> "ValueError: anchor not supported for multiline text"

when the text is multi-line

### What are your OS, Python and Pillow versions?

* OS: Win10
* Python: 3.6 & 3.7
* Pillow: 8.0.1

See `text_body`

Single line text: work
```python
from PIL import Image, ImageDraw, ImageFont

# set text body
text_body = "LINE1:ABQJKP"

# make a blank image for the text, initialized to transparent text color
text_layer = Image.new("RGBA", (200, 500), (255, 255, 255, 0))

# get a font
font_size = 40
font_name = "font/FreeMono.ttf"
text_font = ImageFont.truetype(font_name, font_size)

# set text color
text_color = (0, 0, 0, 255)

# get a drawing context
draw_obj = ImageDraw.Draw(text_layer)

# bbox
text_bbox = draw_obj.textbbox((0, 0), text_body, font=text_font,anchor="lt")
print("text_bbox:", text_bbox)

# text
draw_obj.text((0,0), text_body, font=text_font, fill=text_color,anchor="lt")
```

multi line text:  not work
```python
from PIL import Image, ImageDraw, ImageFont

# set text body
text_body = "LINE1:ABQJKP\nline2:abqjkp"

# make a blank image for the text, initialized to transparent text color
text_layer = Image.new("RGBA", (200, 500), (255, 255, 255, 0))

# get a font
font_size = 40
font_name = "font/FreeMono.ttf"
text_font = ImageFont.truetype(font_name, font_size)

# set text color
text_color = (0, 0, 0, 255)

# get a drawing context
draw_obj = ImageDraw.Draw(text_layer)

# bbox
text_bbox = draw_obj.textbbox((0, 0), text_body, font=text_font,anchor="lt")
print("text_bbox:", text_bbox)

# text
draw_obj.text((0,0), text_body, font=text_font, fill=text_color,anchor="lt")
```

I just use the same method as the single-line because if it contains any newline characters, both two methods will call corresponding multi-line method.

**Comment by nulano** [comment]
The [Text Anchors](https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html#vertical-anchor-alignment) page states that the `t` vertical anchor is incompatible with multiline text:

> **`t` — top (single-line text only)**
> Anchor is at the top of the text.
> For vertical text this is the origin of the first glyph, as shown in the FreeType tutorial.
> For horizontal text it is recommended to use a (ascender) alignment instead, as it does not change based on the specific glyphs of the given text.

For horizontal (and especially multiline) text I would recommend using the `a` vertical anchor instead:

> **`a` — ascender / top (horizontal text only)**
> Anchor is at the ascender line (top) of the first line of text, as defined by the font.
> See Font metrics on Wikipedia for more information.

**Comment by AndyZ-Salz** [comment]
thx for your reply, I'm sorry for missed the introduction of anchors

but one more question:
How can i let the multi-line text's left and top touch the `xy` parameter?
I mean, if I set the `xy=(0,0)`, I'd like to let the bbox of multi-line text is (0, 0, ..., ...)

I built a demo for that,
![demo](https://raw.githubusercontent.com/AndyZ-Salz/Photo_adjust/master/Test/output/text_bbox_q95.png)

as the image, the gray rectangle is the bbox of the text, I want it to be displayed in the green box, But now due to the anchor problem, it has an 8pixel offset on the Y axis.


```Python
    # set text body
    text_body = "LINE1:ABQJKP\nline2:abqjkp"

    # get an image
    base_img = Image.new("RGBA", (500, 200), (255, 255, 255, 255))

    # make a blank image for the text, initialized to transparent text color
    text_layer = Image.new("RGBA", base_img.size, (255, 255, 255, 0))

    # get a font
    font_size = 40
    font_name = "font/FreeMono.ttf"

    text_font = ImageFont.truetype(font_name, font_size)

    # set text color
    text_color = (0   , 0    , 0   , 255)

    # get a drawing context
    draw_obj = ImageDraw.Draw(text_layer)

    # size
    text_size = draw_obj.textsize(text_body, font=text_font)
    print("text_size:", text_size)

    # bbox
    text_bbox = draw_obj.textbbox((0, 0), text_body, font=text_font)
    print("text_bbox:", text_bbox)

    # offset
    text_offset = text_bbox[:2]
    print("text_offset:", text_offset)

    # length # can't measure length of multiline text
    text_length = draw_obj.textlength("LINE1:ABQJKP", font=text_font)
    print("text_length:", text_length)

    # anchor coordinates of the text
    text_xy = (0, 0)

    # visualization master box
    draw_obj.rectangle([(0, 0), (base_img.size[0] - 1, base_img.size[1] - 1)], outline=(25, 25, 25, 255))

    # bbox
    draw_obj.rectangle(text_bbox), fill=(202, 205, 205, 255))

    # text
    draw_obj.text(text_xy, text_body, font=text_font, fill=text_color, align="left")

    # size
    draw_obj.rectangle([(0,0), text_size], outline=(0, 255, 0, 255))
```

output:
```
text_size: (288, 68)
text_bbox: (0, 8, 288, 75)
text_offset: (0, 8)
text_length: 288.0
```

**Comment by nulano** [comment]
> How can i let the multi-line text's left and top touch the xy parameter?
> I mean, if I set the xy=(0,0), I'd like to let the bbox of multi-line text is (0, 0, ..., ...)

You have to compute the bbox and then offset the text by the top amount, e.g.:

```python
bbox = draw.textbbox((0, 0), text, font=font)
draw.text((0, -bbox{1]), text, fill=color, font=font)
```

This is most likely how the `t` and `b` (using the bottom instead) vertical anchors would be implemented if they were supported, but they aren't because this is less efficient than the computations for the other anchors or for a single line of text. Therefore, if you really have to use the `t` anchor despite the slower performance (I would expect between 1.5x to 2x slower, but I haven't checked), you have to do this yourself explicitly.

**Comment by AndyZ-Salz** [comment]
okey.....
That mean just like the `text_offset` I calculated
I have to deal with this issue manually, e.g.
```python
ideal_xy=(0,0)
text_offset = bbox[:2]  # for me is (0, 8) 
input_xy = (ideal_xy[0] - text_offset[0], ideal_xy[1] - text_offset[1]) # for me is (0, -8) 
draw.text(input_xy, text, fill=color, font=font)
```
Am i right?

**Comment by nulano** [comment]
That looks right to me.

**Comment by AndyZ-Salz** [comment]
thanks a lot 💯
