### ISSUE TITLE
RGB conversion gives different results across Pillow versions

### ISSUE THREAD

**Issue by liyong126** [python-pillow/Pillow#5083]
### What did you do?
open image and convert to rgb mode
### What did you expect to happen?
the result are the same
### What actually happened?
when use multiple version pillows to process image，the result of some images  are different.
### What are your OS, Python and Pillow versions?

* OS:  centos
* Python:  3.7.2

* Pillow:  6.2.0 /8.0.1

```python
img = Image.open(buf).convert('RGB')
```

**Comment by radarhere** [comment]
Could you supply a copy of the image, to help clarify what is occurring?

**Comment by liyong126** [comment]
https://images.gitee.com/uploads/images/2020/1210/114436_d6632f17_6517938.png

**Comment by radarhere** [comment]
I'm having difficulty replicating. Is the different Pillow version the only difference? Is it the case that they're different machines with other differences? How did you install the Pillow versions?

**Comment by liyong126** [comment]
i tested in the same conda environment, just changed pillow version with `pip install pillow==`.

**Comment by radarhere** [comment]
If you think this is a silly question, please bear with me - how do you know the results are different? Are you saving them to file? If so, what file type?

**Comment by liyong126** [comment]
i found the issue https://github.com/python-pillow/Pillow/issues/5039.
and i also used JPEG images.

**Comment by liyong126** [comment]
> If you think this is a silly question, please bear with me - how do you know the results are different? Are you saving them to file? If so, what file type?

i use the following code to dump the image.
`
img = np.array(img, dtype=np.float32)
np.save("xxx.npy", img)
`

**Comment by kmilos** [comment]
> and i also used JPEG images

When dealing with lossy compression, different versions of the libjpeg library used by Pillow might produce different results.

When comparing output for bit exactness, you should use uncompressed or lossless compressed output formats like TIFF or PNG.

**Comment by radarhere** [comment]
Is it the case that RGB conversion is not the issue, but opening JPEGs is?

**Comment by radarhere** [comment]
> and i also used JPEG images.

To check - you don't mean that you only used JPEG images, right? Because the sample image you attached earlier was a PNG.

**Comment by radarhere** [comment]
Comparing 6.2.0 and 8.0.1 on our CIs where we had numpy installed for Linux (including CentOS) and macOS, keeping a copy the same as "comparsion.npy", I'm unable to find a difference.

```python
import numpy as np

img = Image.open("Tests/test.png").convert("RGB")
img = np.array(img, dtype=np.float32)
np.save("xxx.npy", img)
with open("xxx.npy", "rb") as fp:
	with open("Tests/comparison.npy", "rb") as fp2:
		assert fp.read() == fp2.read()
```

The only one that had a different result was our job for Ubuntu 18, but that had a different result from the other CI jobs, not between the Pillow versions - I compare the files using a hash.

**Comment by radarhere** [comment]
It's not clear to me if this issue is about the provided PNG - in which case I can't replicate the issue - or if this is about JPEGs - in which case the image hasn't been provided.

Either way, closing unless more information is provided.
