### ISSUE TITLE
np.array(img) should not hide errors for corrupted images

### ISSUE THREAD

**Issue by akamaus** [python-pillow/Pillow#5084]
### What did you do?
I spent a lot of time debugging a code which loads png images from disk and converts them to numpy arrays to do some processing.

### What did you expect to happen?

If I take any png and corrupt it, say, by truncating,
```
$ dd if=good.png of=corrupted.png bs=1024 count=10
$ python
```
 I expect the following code to fail with some exception because image pixels can not be read into an array.
```pycon
>>> from PIL import Image
>>> import numpy as np
>>> img = Image.open('corrupted.png') 
>>> arr = np.array(img)
```

### What actually happened?
Instead, I got an object array with a single element:
```pycon
>>> print(arr)
<PIL.PngImagePlugin.PngImageFile image mode=RGB size=384x288 at 0x7F38258C6240>
```

and now the code fails later with a strange error message, like:
```pycon
>>> arr / 255
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'int'
```

#### img.verify() behaves strangely, too
Funny and counter-intuitive thing, if I try instead doing:  
```pycon
>>> img = Image.open('good.png') 
>>> img.verify()
>>> arr = np.array(img)
>>> arr / 255
TypeError: unsupported operand type(s) for /: 'PngImageFile' and 'int'
```
I still got an error presumably because calling verify() makes image unusable, but again, np.array() doesn't care. So now the code fails for all good images.

### What are your OS, Python and Pillow versions?

* OS: ubuntu-18.04
* Python: 3.6
* Pillow: 8.0.1

**Comment by radarhere** [comment]
When I try and replicate this, I find that
```python
img.__array_interface__
```
throws an OSError, but
```python
np.array(img)
```
doesn't. So depending on how you look at this, the problem is either that Pillow's `__array_interface__` isn't throwing the right kind of exception, or it is that numpy is catching the OSError.

**Comment by kmilos** [comment]
I think this shows up in other guises, like https://github.com/python-pillow/Pillow/issues/3863

**Comment by radarhere** [comment]
Confirmed to be a bug in numpy - see the discussion starting at https://gitter.im/numpy/numpy?at=6067b4ef3153ce63a3b6dcad

<img width="626" alt="Screen Shot 2021-04-03 at 11 44 27 am" src="https://user-images.githubusercontent.com/3112309/113463544-feae8e80-9471-11eb-8519-b907fb3823ea.png">

We could raise a `RecursionError` or `MemoryError` to make `np.array` fail, but that wouldn't be reflecting the cause of the error.

**Comment by radarhere** [comment]
I've taken the suggestion of using `__array__` and created #5379

**Comment by radarhere** [comment]
NumPy 1.23 has been released, fixing the bug.

The Pillow workaround has been reverted, and will no longer be present in the next release of Pillow.
