### ISSUE TITLE
ValueError: tile cannot extend outside image

### ISSUE THREAD

**Issue by safoorasoltanian** [python-pillow/Pillow#5105]
Hi
### What did you do?
I am trying to extract faces by mtcnn on the folder of images of chokepoint dataset for my project:

``

### What did you expect to happen?
I should extract the faces and then match them
### What actually happened?
In the extract function for some images I have this error, ValueError: tile cannot extend outside image, notice that all the images in the folder are in the same size(800*600) 
### What are your OS, Python and Pillow versions?
I run my project on the google colab

* OS: 
* Python: 
* Pillow: 

```python
def extract_face_from_image(image_path, required_size=(224, 224)):
    image = plt.imread(image_path)
    detector = MTCNN()
    faces = detector.detect_faces(image)
    face_images = []
    for face in faces:
        x1, y1, width, height = face['box']
        x2, y2 = x1 + width, y1 + height
        face_boundary = image[y1:y2, x1:x2]
        face_image = Image.fromarray(face_boundary)
        face_image = face_image.resize(required_size)
        face_array = asarray(face_image)
        face_images.append(face_array)
    return face_images
extracted_face = extract_face_from_image('/content/234.jpg')
plt.imshow(extracted_face[0])
plt.show()
```

**Comment by radarhere** [comment]
Could you attach one of the images?
What version of Pillow are you using?

**Comment by radarhere** [comment]
Closing for now. Feel free to attach an image, and then this can be reopened.
