### ISSUE TITLE
Cannot render JinMeiMaoLiPoLieTiFan-1.ttf

### ISSUE THREAD

**Issue by gaoxinge** [python-pillow/Pillow#5118]
### What did you do?

I use pillow to draw font.

### What did you expect to happen?

I expect to see `0123456789`.

### What actually happened?

Pillow does not show any number on red canvas.

![1](https://user-images.githubusercontent.com/16648345/102749697-6f3c0e80-439f-11eb-8afb-81a0f82d4782.png)

### What are your OS, Python and Pillow versions?

* OS: win10
* Python: 3.6.1
* Pillow: 8.0.1

### resource

- code

```python
from PIL import Image, ImageFont, ImageDraw

ttf_path = "font/JinMeiMaoLiPoLieTiFan-1.ttf"
text = "0123456789"
text_size = 35

font = ImageFont.truetype(ttf_path, text_size)
text_width, text_height = font.getsize(text)
canvas = Image.new("RGBA", [text_width, text_height], (255, 0, 0, 255))
draw = ImageDraw.Draw(canvas)
draw.text((0, 0), text, font=font, fill="#000000")
canvas.show()
```

- Font is in [font.zip](https://github.com/python-pillow/Pillow/files/5722838/font.zip).
- I guess the pillow may not support [postscript wiki type 5](https://en.wikipedia.org/wiki/PostScript_fonts#Type_5), and this font's `post` is `5.0` format type.

**Comment by radarhere** [comment]
When I try to install that font on macOS, I see
![Screen Shot 2020-12-21 at 6 52 10 pm](https://user-images.githubusercontent.com/3112309/102752415-aae5d100-43bd-11eb-8975-9e5cd76a5cbd.png)

**Comment by gaoxinge** [comment]
@radarhere Thanks! This font may be an invalid font.
