### ISSUE TITLE
ImageDraw colors don't work on a black-and-white image

### ISSUE THREAD

**Issue by NielsRogge** [python-pillow/Pillow#5123]
Is it normal that on a black-and-white image, I can't draw colored rectangles? When I type `draw.rectangle(general_box, outline='blue', width=2)`, the bounding box is still black.

Is there a way to mitigate this?

I have a Google Colab notebook to reproduce my issue (it's quite technical - it's an AI model that learns to annotate PDF images):

https://drive.google.com/file/d/1iz4wR_jFu8BPMxXx06sQFgdT0swq-mXZ/view?usp=sharing

It would be cool if I can visualize the different annotations on an image in different colors.

**Comment by nulano** [comment]
A black-and-white image can only contain black and white content.
Before drawing color on it, you must convert it to a different format, e.g. RGB:

```python
image = Image.open("/content/data/testing_data/images/83443897.png")
print(image.mode)  # prints "L", meaning 8-bit grayscale
image = image.convert("RGB")
print(image.mode)  # prints "RGB", meaning 24-bit RGB
```

See https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes for more information on supported image modes.

**Comment by NielsRogge** [comment]
Thank you! This solved it.
