### ISSUE TITLE
Bitmap fonts don't support unicode characters

### ISSUE THREAD

**Issue by iliakonnov** [python-pillow/Pillow#5124]
### What did you do?
```python
from PIL import ImageFont
from PIL.BdfFontFile import BdfFontFile

src = "unifont.bdf"
dst = "unifont.pil"

with open(src, "rb") as f:
    bdf = BdfFontFile(f)
    bdf.save(dst)

font = ImageFont.load(dst)

normal = font.getsize('A')
print(f'Size of A is {normal}')

advanced = font.getsize('Ы')
print(f'Size of Ы is {advanced}')
```
`unifont.bdf` is available here: https://ftp.gnu.org/gnu/unifont/unifont-13.0.04/unifont-13.0.04.bdf.gz

### What did you expect to happen?
See the size of the text. Since the given font is monospace, it should be the same as letter `A`: (8, 16)

Unifont certainly contains glyph for such letter (grep `unifont.bdf` for `U+042B`). So it should work correctly.

### What actually happened?
Crash:
```
Size of A is (8, 16)
Traceback (most recent call last):
  File "/tmp/repro.py", line 16, in <module>
    advanced = font.getsize('Ы')
  File "/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 128, in getsize
    return self.font.getsize(text)
UnicodeEncodeError: 'latin-1' codec can't encode character '\u042b' in position 0: ordinal not in range(256)
```

### What are your OS, Python and Pillow versions?

* OS: ArchLinux
* Python: 3.9.1
* Pillow: 8.0.1

**Comment by iliakonnov** [comment]
There is similar issue: https://github.com/python-pillow/Pillow/issues/2779, but it is flooded with irrelevant comments and does not contain minimal reproducible example. Using TrueType fonts can be used as a workaround, but that does not solve the problem with bitmap fonts.

**Comment by nulano** [comment]
> Using TrueType fonts can be used as a workaround, but that does not solve the problem with bitmap fonts.

TrueType fonts can have embedded bitmaps, and these are supported starting with Pillow 8.0.0.

**Comment by iliakonnov** [comment]
> Do note that TrueType fonts can have embedded bitmaps, and these are supported starting with Pillow 8.0.0.

Oh, thanks! I'll give that a try later.

Probably, it is can be a documentation issue. [ImageFont's docs](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html) says that I can convert my `.bcf` file and use it in Pillow:
> PIL uses its own font file format to store bitmap fonts. You can use the pilfont utility from pillow-scripts to convert BDF and PCF font descriptors (X window font formats) to this format.

But it does not mention that Pillow can't handle chars with code > 256 after such conversion.

**Comment by nulano** [comment]
> Probably, it is can be a documentation issue.

That's a good point, I think most of the ImageFont documentation (non-TrueType parts) was just copied from PIL before the fork. Looking at the source, it looks like the PIL font format was designed with Python 2 `string`s in mind which are `bytes` in Python 3.

**Comment by radarhere** [comment]
I've created PR #5137 to update the documentation.

**Comment by radarhere** [comment]
The PR has now been merged. So https://pillow.readthedocs.io/en/latest/reference/ImageFont.html#imagefont-module now reads
> PIL uses its own font file format to store bitmap fonts, **limited to 256 characters**. You can use pilfont.py from pillow-scripts to convert BDF and PCF font descriptors (X window font formats) to this format.

@iliakonnov do you feel like this is resolved?

**Comment by iliakonnov** [comment]
@radarhere, oh, yeah. Thank you very much. Now it's more difficult to get confused.
