### ISSUE TITLE
"X get_image failed: error 8 (73, 0, 924)" when trying to execute a script

### ISSUE THREAD

**Issue by NotNotJustin** [python-pillow/Pillow#5130]
### What did you do?
I executed a script

### What did you expect to happen?
A bot to run so it would play the Chrome Dinosaur Game for me.

### What actually happened?
`X get_image failed: error 8 (73, 0, 924)`

### What are your OS, Python and Pillow versions?

* OS: Linux Command-Line VM on Chrome OS
* Python: Python 3.8.5
* Pillow: 8.0.1

```python
import pyautogui
import time
import PIL.ImageGrab as ImageGrab
pyautogui.FAILSAFE = True

box_area1 = (248, 206, 286, 250) #box coordinates(x1,y1, x2,y2) to detect obstacles
pixel_plant1 = (19, 9) #pixel coordinates(x1,y1) to detect plants
pixel_plant2 = (11, 21) #pixel coordinates(x1,y1) to detect plants
pixel_plant3 = (29, 15) #pixel coordinates(x1,y1) to detect plants
pixel_plant4 = (20, 33) #pixel coordinates(x1,y1) to detect plants
pixel_plant5 = (20, 42) #pixel coordinates(x1,y1) to detect plants

def jump():
    pyautogui.keyDown('space')
    time.sleep(0.05)
    pyautogui.keyUp('space')
    print('Jump')
play = True
while play:
    try:
        box = ImageGrab.grab(box_area1)
        p1 = box.getpixel(pixel_plant1)
        p2 = box.getpixel(pixel_plant2)
        p3 = box.getpixel(pixel_plant3)
        p4 = box.getpixel(pixel_plant4)
        p5 = box.getpixel(pixel_plant5)
        if p1 == (83, 83, 83) or p2 == (83, 83, 83) or p3 == (83, 83, 83) or p4 == (83, 83, 83) or p5 == (83, 83, 83):
            jump()
            time.sleep(0.06)
    except Exception as e:
        play = False
        print(e)

```
This is not my script, I don't know Python. I do, however, know that this is an issue with the Pillow Library and that's why I'm bringing it here and not the script owner's GitHub repo.

**Comment by radarhere** [comment]
Hi.

Yes, it is a Pillow error message. `ImageGrab.grab` would be triggering https://github.com/python-pillow/Pillow/blob/ff9715f079428b3f62b864d472f21fd33e367d94/src/display.c#L928

My guess is that the solution involves passing an `xdisplay` argument for [ImageGrab.grab](https://pillow.readthedocs.io/en/stable/reference/ImageGrab.html#PIL.ImageGrab.grab).

Not sure how familiar you are with X, but if you open up your command line and run `echo $DISPLAY`, a value should be printed. What is that value? Could you try taking that value, and inserting into your code? Changing
`box = ImageGrab.grab(box_area1)`
to
`box = ImageGrab.grab(box_area1, xdisplay="<INSERT $DISPLAY VALUE HERE>")`

**Comment by NotNotJustin** [comment]
The output from the command line when I ran that returned with `:0`

Don't know if I should use that, or...

**Comment by NotNotJustin** [comment]
Okay, update. I changed the code to
`box = ImageGrab.grab(box_area1, xdisplay="0")`
And got a return in the command line of `X connection failed: error 5`

Still have no clue what any of it means.

**Comment by radarhere** [comment]
`box = ImageGrab.grab(box_area1, xdisplay=":0")` - include the semicolon.

So, the bot is trying to take screenshots. That is the method it is using to determine where objects are in the game. [X](https://en.wikipedia.org/wiki/X_Window_System) is the name of a windowing system for Linux.

My suggestion was that maybe it's trying to take a screenshot of the wrong display.

**Comment by nulano** [comment]
The error codes are from the X server or library. I can only find the list at http://www.rahul.net/kenton/xproto/xevents_errors.html, but you can see that, for example, error 5 is a parse error (caused by the omitted semicolon).

Based on that list, error 8 is a bad parameter, but more information is hard to find. What are your screen settings (resolution, bit depth)? Since you mention you are running in a "Linux Command-Line VM", do you even have a screen (in the VM)?

**Comment by radarhere** [comment]
I don't think there's enough information here about the user's setup to solve this. It is entirely possible that the problem is that there isn't a display attached to the environment.

So closing due to lack of response. If you have more information, comment and this can be re-opened.

**Comment by MikeKall** [comment]
Hi,

I am getting the same error `OSError: X get_image failed: error 8 (73, 0, 1336)`
The script that I am running is very simple for now:

```
from PIL import ImageGrab

printscreen = ImageGrab.grab(xdisplay=":0")
```

### Environment 
Fedora 33
Screen resolution: `1920x1080`
If it's useful, here is the device model I am running on: HP EliteBook 840 G7 Notebook PC

Any help would be appreciated

**Comment by radarhere** [comment]
The error code is 8. After looking at https://stackoverflow.com/questions/56562823/xcb-get-image-reply-fails-for-window-on-another-workspace-desktop, it seems to be saying that Pillow is trying to screenshot something not on the screen.

...do you have multiple monitors attached?

**Comment by MikeKall** [comment]
No I have only one monitor

**Comment by radarhere** [comment]
What happens if you run just `ImageGrab.grab()`, without the `xdisplay` argument?

**Comment by MikeKall** [comment]
I get the same error

**Comment by radarhere** [comment]
If you open up your command line and run `echo $DISPLAY`, what is the output?

**Comment by MikeKall** [comment]
It shows `:0`

**Comment by radarhere** [comment]
https://stackoverflow.com/a/42447160 suggests that one needs to map the window first.

So I've thrown in [`xcb_map_window(connection, screen->root);`](https://github.com/radarhere/Pillow/commit/46aa721a28c49b4c5110c940849fc88e56ae2167) - did you want to download and install from https://github.com/radarhere/Pillow/tree/xcb and see if that works for you?

**Comment by MikeKall** [comment]
Ok, I am trying to install the library from the `xcb` branch but when I execute the setup.py it returns this error:

**Comment by radarhere** [comment]
That's a common error - you are, as it says, missing a jpeg dependency.

https://pillow.readthedocs.io/en/stable/installation.html#building-on-windows
> If you wish to compile Pillow manually, you can use the build scripts in the winbuild directory used for CI testing and development. These scripts require Visual Studio 2017 or newer and NASM.

**Comment by MikeKall** [comment]
Thanks I compiled it, but it can't find the `xcb_map_window`:
`NameError: name 'xcb_map_window' is not defined`

**Comment by radarhere** [comment]
I was unable to reproduce this in Ubuntu 20.04 in VirtualBox on my macOS machine.

Fedora 33 is now EOL. So I tried Fedora 35 in VirtualBox... and I could reproduce it!
After some Googling, I found [`xwd -root -display :0`](https://askubuntu.com/questions/226829/how-to-take-screenshot-of-an-x11-based-gui-from-a-text-terminal-such-as-tty1) as a command to simply take a screenshot. And I received BadMatch again. So I suspect there is just something going wrong between Fedora, X and VirtualBox. Or maybe just even Fedora and X, judging from https://stackoverflow.com/questions/68297504/major-opcode-of-failed-request-73-x-getimage-in-fedora-32-and-fedora-34.

So I'm unable to find any evidence that this is a problem with Pillow itself.

**Comment by vpcano** [comment]
I got the same error on Debian 11, and found that in my case it was caused by Gnome using Wayland and not Xorg. Loging in using Gnome on Xorg solved the problem.
Please notice that newest Linux distros come with Wayland enabled by default, so you may be getting this error because of the same reason as me.
Nevertheless, it would be great for Pillow to support Wayland...

**Comment by nulano** [comment]
Is there a built-in tool to take screenshots that works on Wayland? It might be worth looking at its source to compare differences.

**Comment by asweigart** [comment]
I get the same error running Ubuntu 21.10 running on VMware Worksation 15 Player on my Windows 10 laptop.

The Ubuntu VMware is running Python 3.9.7, with $DISPLAY set to ":0" and is simulting a single monitor. I installed Pillow 8.0.0.

I got the error running this from the command line:

```
>>> from PIL import ImageGrab
>>> ImageGrab.grab()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/home/al/.local/share/virtualenvs/deleteme-kZADQq03/lib/python3.9/site-packages/PIL/ImageGrab.py", line 64, in grab
    size, data = Image.core.grabscreen_x11(xdisplay)
OSError: X get_image failed: error 8 (73, 0, 335)
```

I get the same error when running the latest Pillow 9.1.0 too (except the error happens on line 68 of ImageGrab.py)

**Comment by asweigart** [comment]
This is definitely an issue of Pillow not working on Wayland. I made one change in my Ubuntu 21.10 vm: modifying `/etc/gdm3/custom.conf` to uncomment `#WaylandEnable=false` and then ran `sudo systemctl restart gdm3` to restart it so Ubuntu is using X instead of Wayland. Both `ImageGrab.grab()` and the mss module's screenshot function worked perfectly.

**Comment by radarhere** [comment]
The question of Wayland now has a dedicated issue - https://github.com/python-pillow/Pillow/issues/6312

**Comment by AmoghSaxena** [comment]
> This is definitely an issue of Pillow not working on Wayland. I made one change in my Ubuntu 21.10 vm: modifying `/etc/gdm3/custom.conf` to uncomment `#WaylandEnable=false` and then ran `sudo systemctl restart gdm3` to restart it so Ubuntu is using X instead of Wayland. Both `ImageGrab.grab()` and the mss module's screenshot function worked perfectly.

Thanks! It worked for me! :duck:  :clinking_glasses:

**Comment by mangatsukhbeer** [comment]
I was having the same issue, i read this thread and logged out of Ubuntu and changed my display protocol from wayland to xorg (using the small dial at the bottom right corner on the login screen) and ImageGrab.Grab() works perfectly now.

**Comment by g-cyan** [comment]
> 

How did u change that display protocol? I've been suffering the issue as same as the title one.

**Comment by tgwrite** [comment]
> This is definitely an issue of Pillow not working on Wayland. I made one change in my Ubuntu 21.10 vm: modifying `/etc/gdm3/custom.conf` to uncomment `#WaylandEnable=false` and then ran `sudo systemctl restart gdm3` to restart it so Ubuntu is using X instead of Wayland. Both `ImageGrab.grab()` and the mss module's screenshot function worked perfectly.

Thanks! It worked for me! 
yeah!

**Comment by JustStare** [comment]
> 这绝对是 Pillow 在 Wayland 上不起作用的问题。我在我的 Ubuntu 21.10 vm 中进行了一项更改：修改`/etc/gdm3/custom.conf`为取消注释`#WaylandEnable=false`，然后运行`sudo systemctl restart gdm3`以重新启动它，因此 Ubuntu 使用 X 而不是 Wayland。两者`ImageGrab.grab()`和 mss 模块的屏幕截图功能都运行良好。

thanks!!!!!!!!!!!!!!!

**Comment by nrg4** [comment]
> This is definitely an issue of Pillow not working on Wayland. I made one change in my Ubuntu 21.10 vm: modifying `/etc/gdm3/custom.conf` to uncomment `#WaylandEnable=false` and then ran `sudo systemctl restart gdm3` to restart it so Ubuntu is using X instead of Wayland. Both `ImageGrab.grab()` and the mss module's screenshot function worked perfectly.

It is worked !!! Thanks a lot!!!

**Comment by ElnuDev** [comment]
I have two computers with the same configuration, both using Wayland + XWayland. It works fine on one, but not the other, which is really strange.

**Comment by nyxxceo** [comment]
Still doesnt work on wayland and I dont know how to workaround

**Comment by radarhere** [comment]
If you'd like further assistance, please open a new issue with more details, so that we can discuss your individual situation specifically.
