### ISSUE TITLE
Cannot open PNG file with Image class from PIL: "PIL.UnidentifiedImageError: cannot identify image file"

### ISSUE THREAD

**Issue by fariparedes** [python-pillow/Pillow#5136]
**Ubuntu 20.04.1 LTS, Python 3.8.5, Pillow 8.0.1**

The below code is intended to download an image from an online gallery using [Requests](https://2.python-requests.org/en/master/), convert it into a BytesIO object, open that object with PIL, convert it to a numpy array, and then use [imagededup](https://idealo.github.io/imagededup/methods/hashing/) to turn it into a PHash suitable for storage in a PostgreSQL database BIGINT column. This database table is then used to compute hamming distance for a given hash and find duplicates.

```python
hasher = PHash()
img = get_image(IMAGE_URL.format(img_meta[0], img_meta[1]))
if img != None:
	img_b = io.BytesIO(img.content)
	pil_img = Image.open(img_b)
	hash = hasher.encode_image(image_array=np.array(pil_img))
	hash_int = int(hash, 16)
	hash_int = (hash_int & ((1 << 63) - 1)) - (hash_int & (1 << 63))
```

Normally, this works fine. However, the large dataset has returned a number of images which PIL fails to open, throwing an UnidentifiedImageError. The file comes directly from the gallery and the error can be reliably reproduced on the same images. I cannot share the images in question, but I have modified the script to download the image, save it on the server, and then downloaded that image onto my computer and it functions like a normal PNG image. I have no issue viewing it either on the gallery or on my computer.

Note: I first encountered this issue in Pillow 6.2.2, attempted to update to the latest version, and continued to encounter the issue with that version.

**Comment by fariparedes** [comment]
Cutting out Pillow does work:

```python
img = requests.get(url, stream=True)
np_array = np.asarray(bytearray(img.raw.read()), dtype="uint8")
hash = hasher.encode_image(image_array=np_array)
```

However it's quite a bit slower than PIL.

**Comment by fariparedes** [comment]
Reproduced this issue with the script on Windows, so I don't think it's an issue with my file format drivers. I can import PngImagePlugin just fine and have no issue with most images I load; this only happens to some of them.

**Comment by radarhere** [comment]
Hi. This will be a more interesting process without being able to examine the image directly.

Could you try adding this into your code and seeing what happens? I expect it will raise a more specific error message.

```python
import io
from PIL import Image, PngImagePlugin
img_b = io.BytesIO(img.content)
img_b.seek(0)
prefix = img_b.read(16)
if PngImagePlugin._accept(prefix):
    img_b.seek(0)
    im = PngImagePlugin.PngImageFile(img_b)
    print(im)
else:
    print("Prefix does not match magic")
```

**Comment by fariparedes** [comment]
@radarhere 
> Hi. This will be a more interesting process without being able to examine the image directly.
> 
> Could you try adding this into your code and seeing what happens? I expect it will raise a more specific error message.
> 
> ```python
> import io
> from PIL import Image, PngImagePlugin
> img_b = io.BytesIO(img.content)
> img_b.seek(0)
> prefix = img_b.read(16)
> if PngImagePlugin._accept(prefix):
>     img_b.seek(0)
>     im = PngImagePlugin.PngImageFile(img_b)
>     print(im)
> else:
>     print("Prefix does not match magic")
> ```

Sorry to steal your thunder, but I went into Image.py and changed the exception handling to print the error (which seems to be essentially what you suggested except more hacky), whereupon I found this error: **broken PNG file (bad header checksum in b'iCCP')**

A cursory Google search led me to this issue: https://github.com/python-pillow/Pillow/issues/4472

Just a bad header. Adding ImageFile.LOAD_TRUNCATED_IMAGES = True resolved the issue for me. However, I ran the code you suggested anyway and got the error in full:
``
Traceback (most recent call last):
  File "/var/www/lookout/lookout.py", line 135, in <module>
    lookout()
  File "/var/www/lookout/lookout.py", line 128, in lookout
    filtered_matches = find_hash_matches(char_json["images"], db)
  File "/var/www/lookout/lookout.py", line 101, in find_hash_matches
    im = PngImagePlugin.PngImageFile(img_b)
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFile.py", line 121, in __init__
    self._open()
  File "/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py", line 704, in _open
    self.png.crc(cid, s)
  File "/usr/local/lib/python3.8/dist-packages/PIL/PngImagePlugin.py", line 204, in crc
    raise SyntaxError(
SyntaxError: broken PNG file (bad header checksum in b'iCCP')
```

So, good instinct, I might suggest more descriptive error messages for UnidentifiedImageError in the future since it would have saved me some time! Thanks for your help. :)
