### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file 

### ISSUE THREAD

**Issue by dilipv09** [python-pillow/Pillow#5141]
Hi,

I am using Google Colab for training and getting the error while training. Any suggestion or input is greatly appreciated. Below is the error: 
```
---------------------------------------------------------------------------
UnknownError                              Traceback (most recent call last)
<ipython-input-155-d0ff08413f04> in <module>()
     11 
     12 history = model.fit(train_batches, epochs=epochs, callbacks=callbacks, shuffle=True, 
---> 13                     steps_per_epoch= len(train_batches) // batch_size,  validation_data=valid_batches)
     14 
     15 model.save_weights('save_50_epochss.h5')

7 frames
/usr/local/lib/python3.6/dist-packages/tensorflow/python/eager/execute.py in quick_execute(op_name, num_outputs, inputs, attrs, ctx, name)
     58     ctx.ensure_initialized()
     59     tensors = pywrap_tfe.TFE_Py_Execute(ctx._handle, device_name, op_name,
---> 60                                         inputs, attrs, num_outputs)
     61   except core._NotOkStatusException as e:
     62     if name is not None:

UnknownError:  UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f9c489460a0>
Traceback (most recent call last):

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/ops/script_ops.py", line 249, in __call__
    ret = func(*args)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/autograph/impl/api.py", line 620, in wrapper
    return func(*args, **kwargs)

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/data/ops/dataset_ops.py", line 891, in generator_py_func
    values = next(generator_state.get_iterator(iterator_id))

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 807, in wrapped_generator
    for data in generator_fn():

  File "/usr/local/lib/python3.6/dist-packages/tensorflow/python/keras/engine/data_adapter.py", line 933, in generator_fn
    yield x[i]

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/iterator.py", line 65, in __getitem__
    return self._get_batches_of_transformed_samples(index_array)

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/iterator.py", line 230, in _get_batches_of_transformed_samples
    interpolation=self.interpolation)

  File "/usr/local/lib/python3.6/dist-packages/keras_preprocessing/image/utils.py", line 114, in load_img
    img = pil_image.open(io.BytesIO(f.read()))

  File "/usr/local/lib/python3.6/dist-packages/PIL/Image.py", line 2862, in open
    "cannot identify image file %r" % (filename if filename else fp)

PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7f9c489460a0>


	 [[{{node PyFunc}}]]
	 [[IteratorGetNext]] [Op:__inference_test_function_760355]

Function call stack:
test_function
---------------------------------------------------------------------------
```

**Comment by wiredfool** [comment]
You probably have a bad/corrupted image. They seem to show up reasonably often in training datasets. 

Your best bet is to attempt to open `im = Image.open()` and validate by calling `im.load()` all of your images, and record the filenames that fail. 

Alternately, you can patch keras to call pil_image.open(filepath), instead of reading it and creating a BytesIO, and then the traceback would helpfully contain the filename rather than id of a BytesIO object.

**Comment by dilipv09** [comment]
> You probably have a bad/corrupted image. They seem to show up reasonably often in training datasets.
> 
> Your best bet is to attempt to open `im = Image.open()` and validate by calling `im.load()` all of your images, and record the filenames that fail.
> 
> Alternately, you can patch keras to call pil_image.open(filepath), instead of reading it and creating a BytesIO, and then the traceback would helpfully contain the filename rather than id of a BytesIO object.

Thanks for your response. 
Sure, I'll try to check.

**Comment by radarhere** [comment]
Previous issues of UnidentifiedImageErrors in keras_preprocessing - #4678 and #4834.
Just as a summary, #4678 couldn't create an isolated image that couldn't be opened by Pillow, and so concluded it was a problem with keras_preprocessing.

**Comment by dilipv09** [comment]
Hi Andrew, Thanks for sharing comments.I’ll post this question to keras link to check if they can help out in this regard. Stay safe! Best,Dilip  From: Andrew MurraySent: Sunday, December 27, 2020 2:25 PMTo: python-pillow/PillowCc: dilipv09; AuthorSubject: Re: [python-pillow/Pillow] PIL.UnidentifiedImageError: cannot identify image file (#5141) Previous issues of UnidentifiedImageErrors in keras_preprocessing - #4678 and #4834.Just as a summary, #4678 couldn't create an isolated image that couldn't be opened by Pillow, and so concluded it was a problem with keras_preprocessing.—You are receiving this because you authored the thread.Reply to this email directly, view it on GitHub, or unsubscribe.

**Comment by radarhere** [comment]
Would you be able to post the link to where you asked the question to keras?

**Comment by dilipv09** [comment]
> question

@radarhere, nope I wasn't able to get the keras link.
as you suggested in the issue #4678, I got some alternatives to resolve the issue.
Thanks!

**Comment by dilipv09** [comment]
> You probably have a bad/corrupted image. They seem to show up reasonably often in training datasets.
> 
> Your best bet is to attempt to open `im = Image.open()` and validate by calling `im.load()` all of your images, and record the filenames that fail.
> 
> Alternately, you can patch keras to call pil_image.open(filepath), instead of reading it and creating a BytesIO, and then the traceback would helpfully contain the filename rather than id of a BytesIO object.

I was able to train the model before augmention but after that I got this issue.

**Comment by radarhere** [comment]
Closing. Feel free to post if you can find an image that can't be opened with just Pillow, and this can be re-opened.

**Comment by simonmcnair** [comment]
![test](https://github.com/python-pillow/Pillow/assets/101189766/2c5a239c-f272-4265-9d43-936f1086c9ba)

This file can't be opened by Pillow (10.2.0), yet can be opened with ms paint, ms photos, windows explorer preview, irfanview64 and paint.net

**Comment by simonmcnair** [comment]
thx for the edit.  Didn't know you could do that.

**Comment by radarhere** [comment]
Hi. I'm not a fan of less-than-completely-appropriate images, so I won't personally be helpful in this instance.

Feel free to see if others would like to help, or post a more appropriate image.

**Comment by simonmcnair** [comment]
The image wasn't my choice.  It was purely one that displayed the error.  Hopefully the debug above will be helpful.

**Comment by simonmcnair** [comment]
I'd guess it's something to do with parsing a metadata field as the error is getattr and relating to a dictionary.  just a guess though
