### ISSUE TITLE
A bad GIF resize

### ISSUE THREAD

**Issue by imfantuan** [python-pillow/Pillow#5146]
### What did you do?

```python
from PIL import Image
im = Image.open("800_still_2x.gif")
(width, height) = (im.width // 2, im.height // 2)
im_resized = im.resize((width, height))
im_resized.save('800_still_2x.pillow.gif')
```

### What did you expect to happen?

![800_still_2x_good](https://user-images.githubusercontent.com/16457655/103192656-681f7e00-4914-11eb-8d12-568739dce819.gif)

### What actually happened?

![800_still_2x pillow](https://user-images.githubusercontent.com/16457655/103192634-5b028f00-4914-11eb-9421-70bf09c879e4.gif)

### What are your OS, Python and Pillow versions?

* OS: Centos 7
* Python: 3.8
* Pillow: 8.0.1
* Image file: https://cdn.dribbble.com/users/648258/screenshots/2984961/800_still_2x.gif

**Comment by hugovk** [comment]
What's the problem with the output?

**Comment by imfantuan** [comment]
> What's the problem with the output?

Thanks for reply, and there a some differences:
<img width="285" alt="a" src="https://user-images.githubusercontent.com/16457655/103196543-598a9400-491f-11eb-873a-6f1f097ed9af.png">
vs.
<img width="282" alt="b" src="https://user-images.githubusercontent.com/16457655/103196550-5d1e1b00-491f-11eb-9e02-216a0bc4dd28.png">

<img width="177" alt="c" src="https://user-images.githubusercontent.com/16457655/103196826-dcabea00-491f-11eb-8c20-c828a5004c9e.png">
vs.
<img width="179" alt="d" src="https://user-images.githubusercontent.com/16457655/103196830-dddd1700-491f-11eb-9cf9-b20d0e618f00.png">

**Comment by radarhere** [comment]
You closed this because you found a solution?

**Comment by imfantuan** [comment]
> You closed this because you found a solution?

Not yet. I still need some help.
But maybe it isn't a good title.

What I actually want to say is: https://stackoverflow.com/questions/64971675/pil-adding-text-to-a-gif-frames-adds-noize-to-the-picture/64974733

Unfortunately i can't fix it by using `image.quantize(method=Image.MEDIANCUT)`

Could you help to change the title (i don't post a same issue just with a diffrent title)?

**Comment by imfantuan** [comment]
Btw i fount this: https://stackoverflow.com/questions/29244307/effective-gif-image-color-quantization

It seems to give better result.

@radarhere

**Comment by radarhere** [comment]
This is a known problem. What would you like the updated title to be?

**Comment by radarhere** [comment]
Here's a suggestion.

```python
from PIL import Image
im = Image.open("800_still_2x.gif").convert("RGBA")
(width, height) = (im.width // 2, im.height // 2)
im_resized = im.resize((width, height))
im_resized.save('800_still_2x.pillow.gif')
```
gives

![convert_rgba](https://user-images.githubusercontent.com/3112309/103255343-15f65f80-49dd-11eb-9e5c-daf96142d576.gif)

**Comment by imfantuan** [comment]
> This is a known problem. What would you like the updated title to be?

May be "A bad GIF encoding." or ...



> Here's a suggestion.
> 
> ```python
> from PIL import Image
> im = Image.open("800_still_2x.gif").convert("RGBA")
> (width, height) = (im.width // 2, im.height // 2)
> im_resized = im.resize((width, height))
> im_resized.save('800_still_2x.pillow.gif')
> ```
> 
> gives
> 
> ![convert_rgba](https://user-images.githubusercontent.com/3112309/103255343-15f65f80-49dd-11eb-9e5c-daf96142d576.gif)

@radarhere 

Many thanks, it's better now.

However, the ImageMagick can gives a much better result with a tiny file.

Run: `convert 800_still_2x.gif -resize 400x300 800_still_2x.imagick.gif`

gives

![800_still_2x imagick](https://user-images.githubusercontent.com/16457655/103261017-cf076a80-49da-11eb-91c7-4ec73884f639.gif)

Maybe what i am looking for is about "Quantize for GIF(or something like that)"

**Comment by imfantuan** [comment]
Here is pyvips' version:
```python
image = pyvips.Image.new_from_file("800_still_2x.gif", access="sequential")
image = image.resize(0.5)
image.write_to_file("800_still_2x.pyvips.gif")
```

gives

![800_still_2x pyvips](https://user-images.githubusercontent.com/16457655/103269344-9d010300-49f0-11eb-8bf3-a2a9ee080e54.gif)

**Comment by imfantuan** [comment]
```python
from PIL import Image
import pyvips
import numpy as np

dtype_to_format = {
    'uint8': 'uchar',
    'int8': 'char',
    'uint16': 'ushort',
    'int16': 'short',
    'uint32': 'uint',
    'int32': 'int',
    'float32': 'float',
    'float64': 'double',
    'complex64': 'complex',
    'complex128': 'dpcomplex',
}

im = Image.open("800_still_2x.gif").convert("RGBA")
(width, height) = (im.width // 2, im.height // 2)
im_resized = im.resize((width, height))
im_resized_np = np.asarray(im_resized)
height, width, bands = im_resized_np.shape
linear = im_resized_np.reshape(width * height * bands)
vips_gif = pyvips.Image.new_from_memory(linear.data, width, height, bands, dtype_to_format[str(im_resized_np.dtype)])
vips_gif.write_to_file('800_still_2x.pillow+vips.gif')
```

gives

![800_still_2x pillow+vips](https://user-images.githubusercontent.com/16457655/103290500-ab691200-4a24-11eb-9674-a78596dc8ac5.gif)


Seems not a “resize” problem but “gif encoding"

**Comment by imfantuan** [comment]
> ```python
> from PIL import Image
> import pyvips
> import numpy as np
> 
> dtype_to_format = {
>     'uint8': 'uchar',
>     'int8': 'char',
>     'uint16': 'ushort',
>     'int16': 'short',
>     'uint32': 'uint',
>     'int32': 'int',
>     'float32': 'float',
>     'float64': 'double',
>     'complex64': 'complex',
>     'complex128': 'dpcomplex',
> }
> 
> im = Image.open("800_still_2x.gif").convert("RGBA")
> (width, height) = (im.width // 2, im.height // 2)
> im_resized = im.resize((width, height))
> im_resized_np = np.asarray(im_resized)
> height, width, bands = im_resized_np.shape
> linear = im_resized_np.reshape(width * height * bands)
> vips_gif = pyvips.Image.new_from_memory(linear.data, width, height, bands, dtype_to_format[str(im_resized_np.dtype)])
> vips_gif.write_to_file('800_still_2x.pillow+vips.gif')
> ```
> 
> gives
> 
> ![800_still_2x pillow+vips](https://user-images.githubusercontent.com/16457655/103290500-ab691200-4a24-11eb-9674-a78596dc8ac5.gif)
> 
> Seems not a “resize” problem but “gif encoding"

This is my final solution so i close it.
