### ISSUE TITLE
Cannot open webp image: UnidentifiedImageError

### ISSUE THREAD

**Issue by mrgou** [python-pillow/Pillow#5147]
On an Anaconda distribution, after installing the `libwebp` package and `pillow`, I cannot open a `webp` file (e.g. the `test.webp` file from the libwebp library).

```python
In [1]: from PIL import Image

In [2]: img = Image.open('test.webp')
C:\Users\user\anaconda3\lib\site-packages\PIL\Image.py:2942: UserWarning: image file could not be identified because WEBP support not installed
  warnings.warn(message)
---------------------------------------------------------------------------
UnidentifiedImageError                    Traceback (most recent call last)
<ipython-input-2-79ee787a81b3> in <module>
----> 1 img = Image.open('test.webp')

~\anaconda3\lib\site-packages\PIL\Image.py in open(fp, mode, formats)
   2941     for message in accept_warnings:
   2942         warnings.warn(message)
-> 2943     raise UnidentifiedImageError(
   2944         "cannot identify image file %r" % (filename if filename else fp)
   2945     )

UnidentifiedImageError: cannot identify image file 'test.webp'
```

Looks like Pillow/libwebp aren't properly set up on the Anaconda packages.

**Comment by hugovk** [comment]
This works for me with https://github.com/webmproject/libwebp/blob/master/examples/test.webp on Mac with the 8.0.1 wheel from PyPI:
```pycon
>>> from PIL import Image
>>> im = Image.open("test.webp")
>>> im
<PIL.WebPImagePlugin.WebPImageFile image mode=RGB size=128x128 at 0x1096EED00>
>>> im.show()
>>>
```

Does the same thing happen for you with any webp file? And with https://github.com/python-pillow/Pillow/blob/master/Tests/images/hopper.webp?

If so, we don't create or maintain the Anaconda packages here, you might be best reporting at  https://github.com/conda-forge/pillow-feedstock

**Comment by mrgou** [comment]
OK, thanks, I'll report it in that feed.

**Comment by mrgou** [comment]
Resubmitted [here](https://github.com/conda-forge/pillow-feedstock/issues/86).
