### ISSUE TITLE
Decompression bomb protection

### ISSUE THREAD

**Issue by masklinn** [python-pillow/Pillow#515]
"zip bombs" are a somewhat know threat, but it also applies to images and can't be protected against by checking the filesystem size of the data:
- http://www.aerasec.de/security/advisories/decompression-bomb-vulnerability.html provides 2 PNG bomb demos, a 4KB 6000x6000 images decompressing to 100MB in memory and a 44KB 19000x19000 image decompressing to 1GB
- JPEG is somewhat less efficient, but e.g. NASA Visible Earth's [Blue Marble](http://visibleearth.nasa.gov/view.php?id=73884) has 21600x21600 tiles as small as 5MB ([tile A2, southern pacific](http://eoimages.gsfc.nasa.gov/images/imagerecords/73000/73884/world.topo.bathy.200411.3x21600x21600.A2.jpg)) decompressing to 1.4GB

This means it's possible to DOS e.g. a web application performing image resizing by sending one of these bombs. As far as I can tell the protection possibilities are limited:
- assert source image sizes before doing any operation which will need the image data, the documentation may benefit from a warning on that subject (similar to [warnings about XML vulnerabilities in the Python documentation](http://docs.python.org/2/library/xml.etree.elementtree.html)), `Image.open` could be augmented with e.g. a `maximum_pixels` parameter raising an error in case `image.h * image.w` goes above the specified limit to make this easier for users
- during image loading/decompression, raise an error if the decompressed data size gets above a specific threshold

**Comment by regsgiter** [comment]
yeah
