### ISSUE TITLE
MPO format loading error when EXIF data is present

### ISSUE THREAD

**Issue by JackDesBwa** [python-pillow/Pillow#5164]
Someone sent me a MPO file that I was not able to open with Pillow
It looks like the second image of the file has EXIF data that might conflict with the loading process.
In particular, the reported size does not correspond to the image, but I was not able to figure out if it is the root cause of the bug.

I created a similar image that you can use for your tests and publish if you need. I copied the EXIF of the original file with some subtractions such as the embedded thumbnail. It exhibits the same behavior and is correctly loaded by some other players, such as geeqie or sView.

In this ZIP ([pillow_mpo_exif_error.zip](https://github.com/python-pillow/Pillow/files/5757456/pillow_mpo_exif_error.zip)), you will find the sample image and a script that show the error with this output: [visible with 8.0.1]

> Image 0 size: (64, 64)
> Image 0 loaded
> Image 1 size: (5472, 3648)
> Image 1 error: image file is truncated (0 bytes not processed)

As you can see, the second image is reported to be 5472×3648 but is actually 64×64 like the first one.

**Comment by radarhere** [comment]
Thanks very much for providing a test image. The incorrect reported size would be the cause, yes.

Here is a link to the specification - https://web.archive.org/web/20190227081740/http://www.cipa.jp/std/documents/e/DC-007_E.pdf.

I do think your image is just malformed. I've created PR #5168 as a possible solution though, where I posit that only 'Large Thumbnail' images can have frames of different sizes.

**Comment by JackDesBwa** [comment]
The image that I received was created with the popular StereoPhotoMaker program.
It is possible that this case is badly managed in it. But then, there are many MPOs of this form in the wild that are perfectly read with several programs, including with the embedded software of 3D TV sets and the ones I cited before.

**Comment by radarhere** [comment]
Are you able to upload the original image? I understand that you don't want it to be included in the test images, but it could be helpful to just verify that there isn't a 5472 by 3648 frame hiding in there.

**Comment by JackDesBwa** [comment]
He did not explicitly give permission to share the image publicly, but he would certainly not be against using it for a private analysis.
One time download link: https://framadrop.org/lufi/r/jekSuYQL9n#GgTzjJq3uwZ8DRM8D5uXXW1NZY6/6XHwpfRBFpQrDQk=
