### ISSUE TITLE
Trying to create rounded brackets & overlaying on the other image is getting unexpected output...

### ISSUE THREAD

**Issue by debparth** [python-pillow/Pillow#5169]
### What did you do?
I've 2 Images and I want to overlay them (Both of the images are not transparent). I've the code for rounded borders using Pillow and Cairosvg (but need more optimization cause I only want to use PIllow). After getting rounded borders of image and then trying to superimposing it on other image then the transparent portion of the outside of the rounded box is getting black / white color (depending upon the background)

### What did you expect to happen?
I want to create an image with rounded borders and overlay each other while not changing any colors

### What actually happened?
Please, look closely (The Bicycle image with rounded borders is converted to rectangle borders)
![download (3)](https://user-images.githubusercontent.com/53347017/103438179-4bf24880-4c56-11eb-897d-abe1525da444.png)

### What are your OS, Python and Pillow versions?

* OS: Colab
* Python: 3.6.9
* Pillow: 7.0.0

### Code:
Rounded Borders
```python
from PIL import ImageOps, Image
from cairosvg import svg2png
from io import BytesIO

def frame(im, thickness=5):
    # Get input image width and height, and calculate output width and height
    iw, ih = im.size
    ow, oh = iw+2*thickness, ih+2*thickness

    # Draw outer black rounded rect into memory as PNG
    outer = f'<svg width="{ow}" height="{oh}" style="background-color:none"><rect rx="20" ry="20" width="{ow}" height="{oh}" fill="black"/></svg>'
    png   = svg2png(bytestring=outer)
    outer = Image.open(BytesIO(png))

    # Draw inner white rounded rect, offset by thickness into memory as PNG
    inner = f'<svg width="{ow}" height="{oh}"><rect x="{thickness}" y="{thickness}" rx="20" ry="20" width="{iw}" height="{ih}" fill="white"/></svg>'
    png   = svg2png(bytestring=inner)
    inner = Image.open(BytesIO(png)).convert('L')

    # Expand original canvas with black to match output size
    expanded = ImageOps.expand(im, border=thickness, fill=(0,0,0)).convert('RGB')

    # Paste expanded image onto outer black border using inner white rectangle as mask
    outer.paste(expanded, None, inner)
    return outer

# Open image, frame it and save
im = Image.open('Bicycle.png')
result = frame(im, thickness=50)
image_re = result.resize((800, 500), Image.BILINEAR)
image_re.save('Bicycle_new.png')
```

Overlaying
```python
background_image = Image.open("landscape.jpg").resize((3000, 2000))
foreground_image = Image.open("Bicycle_new.png")

background_image.paste(foreground_image, (800, 500))
background_image.save("out.png", "PNG")
```

### Images:
The output of rounded border code
![3f385b6a-390b-42e8-827a-bd1170e501ff](https://user-images.githubusercontent.com/53347017/103438235-1ef26580-4c57-11eb-9187-35415ee98fe9.png)

The 2 images which I used
![greenery-landscape-with-grass-and-lake-indian-lake](https://user-images.githubusercontent.com/53347017/103438212-ccb14480-4c56-11eb-9fed-dac8872f6bf6.jpg)
![Top-10-Best-Mountain-Bikes-2020-Reviews](https://user-images.githubusercontent.com/53347017/103438216-d470e900-4c56-11eb-9b01-76f0a3a5cb80.png)

**Comment by radarhere** [comment]
Hi.

Change your overlaying code to
```python
background_image = Image.open("landscape.jpg").resize((3000, 2000))
foreground_image = Image.open("Bicycle_new.png")

background_image.paste(foreground_image, (800, 500), foreground_image)
background_image.save("out.png", "PNG")
```

This makes use of the `mask` argument - https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste

**Comment by debparth** [comment]
Hi @radarhere, Thanks for your help. I can use the same code to have rounded corners for mask image but, is there a simple way to do this (To create a border and have round corners in image only using PIL)?

**Comment by radarhere** [comment]
Check out the code in #4765. Let us know if that's not clear enough.
