### ISSUE TITLE
Incorrect border color in corners when drawing rectangles with border color with opacity < 1

### ISSUE THREAD

**Issue by macjohnny** [python-pillow/Pillow#5182]
### What did you do?
Draw a rectangle with a color with opacity < 1 for border (e.g. `outline='#0000ffaa'`)

### What did you expect to happen?
The border color should be homogenous, and not altered by the `fill` color, if set.

### What actually happened?
![image](https://user-images.githubusercontent.com/5589029/103621305-4b4b0200-4f35-11eb-9765-ffbac953e37e.png)
The border color is different in the corners, probably due to overlapping line segments.
Moreover, when a `fill` color is set, the border color is changed due to the overlap of the border and fill rectangle.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8
* Pillow: 8.0.1

#### Code
```python
import PIL.Image
import PIL.ImageDraw

image = PIL.Image.new(mode='RGB', size=(500, 500), color='#ffffff')
draw = PIL.ImageDraw.ImageDraw(image, mode='RGBA')
draw.rectangle(xy=((100,100), (200,200)),
               fill='#ffff00',
               outline='#0000ffaa',
               width=10)
draw.rectangle(xy=((205,100), (305,200)),
               outline='#0000ffaa',
               width=10)

image.save('image.png')
```
#### Result
![image](https://user-images.githubusercontent.com/5589029/103621117-032bdf80-4f35-11eb-8814-047f6389e77e.png)

### Related Sources
https://github.com/python-pillow/Pillow/blob/d374015504df2c7f0316154deade1bc1fa5075df/src/PIL/ImageDraw.py#L255-L258
https://github.com/python-pillow/Pillow/blob/d374015504df2c7f0316154deade1bc1fa5075df/src/_imaging.c#L3171-L3180
https://github.com/python-pillow/Pillow/blob/d374015504df2c7f0316154deade1bc1fa5075df/src/libImaging/Draw.c#L724-L729

**Comment by radarhere** [comment]
I've created PR #5183 to fix the corners.

For my part at least, I'm not convinced that a translucent outline shouldn't be drawn on top of the fill color? Seems like that decision could go either way.

**Comment by macjohnny** [comment]
> I've created PR #5183 to fix the corners.

thanks for the quick fix, looks good.

> For my part at least, I'm not convinced that a translucent outline shouldn't be drawn on top of the fill color? Seems like that decision could go either way.

the rectangle drawing option in e.g. Skia (https://api.skia.org/classSkCanvas.html#a15a77a3479b8f8731442d4a4ea2772b3) uses the same color for stroke and fill. 
the web apis offer two different functions:
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/strokeRect
https://developer.mozilla.org/en-US/docs/Web/API/CanvasRenderingContext2D/fillRect

so I guess it is ok to combine two rectangles if we want to have a translucent outline not overlapping with the fill rectangle.

**Comment by radarhere** [comment]
Thanks. I think it is best to leave the translucent outline drawing on top of the fill then, for the sake of backwards compatibility.
