### ISSUE TITLE
Make EXIF plugin

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#520]
Exif support (labeled experimental since 2003) is somewhat adequate for reading, but there's no clear way to change a value and then write it out.  We currently support writing Exif as byte strings, with no way to make them apart from manually setting up nested `TiffImagePlugin.ImageFileDirectory` instances, then calling save into a file pointer.
-  `Image.getexif()` should exist, and return an Exif object. 
-  The Exif object should export a dictionary interface.
-  The Exif object should have a `toBytes()` method returning the correct bytes.
-  `Exif.load(bytes).toBytes()` should roundtrip. 
-  This should work: 

```python
exif = Exif()
exif['Orientation'] = 1  
im.save('temp.jpg', exif=exif)
```

**Comment by reagle** [comment]
I noticed the bump to 2.7.0, so any thought to this bug?

**Comment by wiredfool** [comment]
It didn't get worked on.

**Comment by wiredfool** [comment]
There is some action on dealing with tiff IFDs in #1059, so something may still come of it. (Though, that PR needs to be worked on due to incompatibilities with existing code)

**Comment by reagle** [comment]
We're now in version 3+, I wonder if this has this been touched?

**Comment by wiredfool** [comment]
No, but there have been some underlying changes to the tiff ifd code that may lead to motion.  It certainly needs to be done.

**Comment by radarhere** [comment]
Trying to understand, can anyone explain to me what the purpose of a `toBytes()` method is? I mean, it's not so that it can be passed back into Pillow, since this new class could do that itself, and it's not for humans to read. Is it so that the value can be stored for later use? Is it so that the value can be used in another program?

**Comment by radarhere** [comment]
I've created PR #3625 to resolve this.

**Comment by jaddison** [comment]
> Trying to understand, can anyone explain to me what the purpose of a `toBytes()` method is? I mean, it's not so that it can be passed back into Pillow, since this new class could do that itself, and it's not for humans to read. Is it so that the value can be stored for later use? Is it so that the value can be used in another program?

I would assume being able to load them in another package like `piexif` is what would make the most sense.

Although, I believe you can just do `piexif.load(image.info['exif'])` which bypasses the need for `toBytes()` here, correct?
