### ISSUE TITLE
webp cannot be identified

### ISSUE THREAD

**Issue by DCHACKZzz** [python-pillow/Pillow#5205]
program
```python
from PIL import Image

im = Image.open("a0001.webp").convert("RGB")
im.save("test.jpg","jpeg")
```

```
/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/PIL/Image.py:2894: UserWarning: image file could not be identified because WEBP support not installed
  warnings.warn(message)
Traceback (most recent call last):
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 31, in <module>
    start(fakepyfile,mainpyfile)
  File "/data/user/0/ru.iiec.pydroid3/files/accomp_files/iiec_run/iiec_run.py", line 30, in start
    exec(open(mainpyfile).read(),  __main__.__dict__)
  File "<string>", line 11, in <module>
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/PIL/Image.py", line 2895, in open
    raise UnidentifiedImageError(
**PIL.UnidentifiedImageError: cannot identify image file 'a0001.webp'**
``[
[Program finished]

**Comment by radarhere** [comment]
> UserWarning: image file could not be identified because WEBP support not installed

You do not have WEBP support in your Pillow installation. You will need to install the dependency, and I expect then reinstall Pillow.
What version of Linux are you using?

**Comment by DCHACKZzz** [comment]
Am coding on android pydroid 3

How I can set external dependency

**Comment by DCHACKZzz** [comment]
Hello anybody can help me????

**Comment by YiminWang-MIT** [comment]
Could you try the following?

> from PIL import features
print (features.check_module('webp'))

**Comment by radarhere** [comment]
Are you using a package manager? If so, it will likely have webp - `apt-get install webp` for example.
Otherwise, you can download webp from https://developers.google.com/speed/webp/download

**Comment by radarhere** [comment]
I'll ask a more basic question - how did you install Pillow?

**Comment by radarhere** [comment]
https://play.google.com/store/apps/details?id=ru.iiec.pydroid3&hl=en&gl=US
> You can also build & install dependencies from a command line.

Looking at https://www.reddit.com/r/Anki/comments/hzyqdg/generate_anki_deck_on_android_using_pydroid_3_and/, there is an option in the sidebar of the app, 'Terminal'.

So if you can't access a package manager, the best strategy would seem to be downloading the webp source, installing it from the PyDroid 3 Terminal, and then probably re-installing Pillow.

**Comment by CrowSt** [comment]
![Screenshot_2022-08-01-22-13-26-080_ru iiec pydroid3](https://user-images.githubusercontent.com/62943446/182196205-48c50d4f-312d-423a-af81-821702570a71.jpg)
I've got the same problem. There is no compiled '_webp.c' module. I have installed webp module then recompilled Pillow. It seems that the problem shows only on the mobile, but nonetheless how to fix it?

**Comment by radarhere** [comment]
Could we have some more details? Could you specify what environment you are in?

How did you install WebP? Could you report the path to `webp/encode.h` and `*webp.so*` on your system?

**Comment by iqiancheng** [comment]
```
pip3 install Pillow --upgrade 
```
and use `pip list|grep pillow` check the Pillow version >= `10.1.0`

**Comment by radarhere** [comment]
Hi. Are you describing a problem, or are you saying that those steps solved your problem?

**Comment by songron** [comment]
> Pillow reads and writes WebP files. Requires libwebp v0.5.0 or later.

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#webp

You can check supported formats:
```
from PIL import Image
print(Image.registered_extensions())
```

**Comment by radarhere** [comment]
You can also use `features` - https://pillow.readthedocs.io/en/stable/reference/features.html

```python
>>> from PIL import features
>>> features.check("webp")
True
```
