### ISSUE TITLE
Writing the same image got a different hash

### ISSUE THREAD

**Issue by RonaldinhoL** [python-pillow/Pillow#5207]
i just open the png img, and write it to another file, why i got it not the same, it has a different md5 hash.

code like this:

``` python
imgA = Image.open("demo.png")

with open("AAA.png", "wb") as f:
    imgA.save(f, "png")
```
how can i save it with the same param as demo.png?

**Comment by radarhere** [comment]
For my two cents, image formats such as PNG are defined by a specification - a document explaining what makes up a valid PNG. When saving a PNG, programs make sure that they follow that specification, but that doesn't mean that different programs will generate exactly the same file.

For example,
- https://www.w3.org/TR/2003/REC-PNG-20031110/#5ChunkOrdering has a table showing that a 'gAMA' chunk and a 'cHRM' chunk may appear 'Before PLTE and IDAT'. It doesn't specify the order, so Pillow could write gAMA first, and Photoshop could write cHRM first, and both would still be considered valid PNGs.
- It's entirely likely that Pillow doesn't support every feature of an image format. Only as recently as #4292 did we add support for private PNG chunks.

Also, not all images actually do follow the specification correctly. See #4592 for a PNG file with a bad header

**Comment by RonaldinhoL** [comment]
> For my two cents, image formats such as PNG are defined by a specification - a document explaining what makes up a valid PNG. When saving a PNG, programs make sure that they follow that specification, but that doesn't mean that different programs will generate exactly the same file.
> 
> For example,
> 
> * https://www.w3.org/TR/2003/REC-PNG-20031110/#5ChunkOrdering has a table showing that a 'gAMA' chunk and a 'cHRM' chunk may appear 'Before PLTE and IDAT'. It doesn't specify the order, so Pillow could write gAMA first, and Photoshop could write cHRM first, and both would still be considered valid PNGs.
> * It's entirely likely that Pillow doesn't support every feature of an image format. Only as recently as #4292 did we add support for private PNG chunks.
> 
> Also, not all images actually do follow the specification correctly. See #4592 for a PNG file with a bad header

i got it, thank you!
