### ISSUE TITLE
No module named PIL on heroku

### ISSUE THREAD

**Issue by MrMiracle2005** [python-pillow/Pillow#5209]
When i run my code in my visual studio code there is no error but when i try to run it on heroku with github it says no module named pillow! help me pls!!

### What did you do?
i imported pillow 
### What did you expect to happen?
run perfectly fine
### What actually happened?
no module named PIL
### What are your OS, Python and Pillow versions?

* OS: Windows 10 
* Python:3.9 
* Pillow: 8.1.0

```python
from PIL import Image
```

**Comment by radarhere** [comment]
Would you be able to provide a more detailed explanation?

'run it on heroku with github' - I'm not quite sure what you're saying, but is https://devcenter.heroku.com/articles/getting-started-with-python#declare-app-dependencies helpful? It recommends setting up a 'requirements.txt' file, that you could put 'Pillow' inside.

**Comment by radarhere** [comment]
Here's another link with the same solution - https://bootcamp.berkeley.edu/resources/coding/learn-django/django-installing-heroku/

**Comment by radarhere** [comment]
Closing for now at least. If you have further detail to help us analyse the problem, feel free to comment and this can be reopened.
