### ISSUE TITLE
Unable to install PIL in Python 2.7.16 official docker image

### ISSUE THREAD

**Issue by triumph1** [python-pillow/Pillow#5210]
### What did you do?
I'm trying to build PIL with all the support included (tkinter, jpeg, zlib... etc)

below is my `Dockerfile`
``` docker
FROM python:2.7.16

# Inject Imaging-1.1.7.tar.gz into docker image
ADD . /tmp/

ENV LDFLAGS=-L/usr/lib/x86_64-linux-gnu/

RUN apt-get update -y
RUN apt-get install -y python-dev build-essential
RUN apt-get install -y libtiff5-dev libjpeg62-turbo-dev zlib1g-dev libfreetype6-dev liblcms2-dev libwebp-dev
# RUN ln -s /usr/lib/x86_64-linux-gnu/libz.so /lib/
# RUN ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /lib/

RUN cd /tmp/packages/
RUN tar xvfz /tmp/packages/Imaging-1.1.7.tar.gz -C /tmp/packages
RUN python /tmp/packages/Imaging-1.1.7/setup.py install
CMD ["bin/bash"]
```

### What did you expect to happen?
all the support enabled.

### What actually happened?

```
--------------------------------------------------------------------
PIL 1.1.7 SETUP SUMMARY
--------------------------------------------------------------------
version       1.1.7
platform      linux2 2.7.16 (default, Oct 17 2019, 07:35:32)
              [GCC 8.3.0]
--------------------------------------------------------------------
*** TKINTER support not available (Tcl/Tk 8.6 libraries needed)
*** JPEG support not available
*** ZLIB (PNG/ZIP) support not available
*** FREETYPE2 support not available
*** LITTLECMS support not available
--------------------------------------------------------------------
To add a missing option, make sure you have the required
library, and set the corresponding ROOT variable in the
setup.py script.

```

### What are your OS, Python and Pillow versions?

* OS: debian buster (docker image)
* Python: python 2.7.16

what am I missing??

**Comment by hugovk** [comment]
You're using the old PIL from 2009 which is no longer supported.

This project is Pillow, a fork of PIL. 

Use Pillow instead. Try installing a binary wheel using pip:

https://pillow.readthedocs.io/en/stable/installation.html

**Comment by radarhere** [comment]
Also, be aware that you are using Python 2.7, which is not supported by the latest version of Pillow.
If you want to use Python 2.7, the most recent version you will be able to use is Pillow 6.2.2.

**Comment by triumph1** [comment]
No.. I have legacy project that can not escape from old PIL...
I just do need to install the exact version...!

**Comment by radarhere** [comment]
Running your Dockerfile, this fixed most dependencies.
```
RUN ln -s /usr/lib/x86_64-linux-gnu/libtk8.6.so /usr/lib
RUN ln -s /usr/lib/x86_64-linux-gnu/libtcl8.6.so /usr/lib
RUN ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
RUN ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
RUN ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
```
I say most because it doesn't fix lcms. It's important to note though that PIL doesn't support lcms2, so you need to install version 1 specifically.

**Comment by wiredfool** [comment]
Not only is PIL not supported, there are quite a few CVEs that apply to it. Don't run it against untrusted input. Don't connect it to the internet.

**Comment by triumph1** [comment]
> Running your Dockerfile, this fixed most dependencies.
> 
> ```
> RUN ln -s /usr/lib/x86_64-linux-gnu/libtk8.6.so /usr/lib
> RUN ln -s /usr/lib/x86_64-linux-gnu/libtcl8.6.so /usr/lib
> RUN ln -s /usr/lib/x86_64-linux-gnu/libjpeg.so /usr/lib
> RUN ln -s /usr/lib/x86_64-linux-gnu/libz.so /usr/lib
> RUN ln -s /usr/lib/x86_64-linux-gnu/libfreetype.so /usr/lib
> ```
> 
> I say most because it doesn't fix lcms. This is because PIL doesn't support lcms2, so you need to install version 1 specifically.

Thank you! that pretty much solved the issue!
