### ISSUE TITLE
GIFs not moving and different name assigned when opened via Pillow

### ISSUE THREAD

**Issue by ithenPL** [python-pillow/Pillow#5211]
Hi there.

I recently started to have fun with Pillow images and wanted to improve my code with some gifs. I have no problem with opening it, but when it does, it's not moving. When I open the gif outside Python, it works normally. I noticed that after gif is opened via Python, it has PNG format and different name. Same applies to JPG pictures - format changed to PNG with different name. I can't see what the issue might be. 

How can I force Python to display opened file a proper name, not just temporary?
How can I force python to display moving gif?

**Comment by hugovk** [comment]
Please give minimal example code so we know exactly what you're doing. 

 ### What did you do?

### What did you expect to happen?

### What actually happened?

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow:

**Comment by ithenPL** [comment]
**What did you do?**
`from PIL import Image

img = Image.open('cat.gif')
img.show()`

**What did you expect to happen?**
I expected my code to open a window with title 'cat.gif' with moving GIF.

**What actually happened?**
Window was opened, but it was titled differently and with different format - tmp3s8qjx0s.PNG - and gif wasn't moving (steady picture).

**What are your OS, Python and Pillow versions?**
OS: Windows 10
Python: 3.9.0
Pillow: 8.1.0

**Comment by radarhere** [comment]
Here's what [the documentation for `show()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.show) says -
> Displays this image. This method is mainly intended for debugging purposes.
>
> This method calls PIL.ImageShow.show() internally. You can use PIL.ImageShow.register() to override its default behaviour.
>
> The image is first saved to a temporary file. By default, it will be in PNG format.
>
> On Unix, the image is then opened using the display, eog or xv utility, depending on which one can be found.
>
> On macOS, the image is opened with the native Preview application.
>
> On Windows, the image is opened with the standard PNG display utility.

It's 'mainly intended for debugging purposes'. Pillow doesn't really offer the ability to open files in an image viewer.

As for the reason it converts to PNG, the thinking is to ensure that your image viewer can open it.

If you want a file with a proper name -
```python
im.save("proper_name.jpg")
```

**Comment by radarhere** [comment]
Animated GIFs are made up of a series of images. Here is a simple example of how to open a GIF and save all of the images back to a new location.
```python
from PIL import Image, ImageSequence
with Image.open("Tests/images/iss634.gif") as im:
    ims = ImageSequence.all_frames(im)
    ims[0].save("out.gif", save_all=True, append_images=ims[1:])
```

**Comment by radarhere** [comment]
Looking at ImageShow, here is how you should be able open a file on Windows after saving, just using Python -
```python
import os
os.system('start "Pillow" out.gif')
```

https://superuser.com/questions/246825/open-file-from-the-command-line-on-windows thinks that you can abandon the title argument altogether -

```python
import os
os.system('start out.gif')
```

Note that I haven't tested this.

**Comment by ithenPL** [comment]
Thanks for the tip radarhere! I managed to run it smoothly with only last two lines of code. Thanks again! Upper part of your code will deffinietly be useful later in my project.

**Comment by yazan1107** [comment]
had the same issue lol thanks
