### ISSUE TITLE
ICC Profile not saved for TIF files

### ISSUE THREAD

**Issue by Crubert-digit** [python-pillow/Pillow#5225]
When loading an image from an array(image opened with cv2, skimage, etc.) and then saving it in .tif format, the icc_profile is not saved. For example:

```python
import cv2
from PIL import Image, ImageCms

profile = ImageCms.getOpenProfile("AdobeRGB.icm")

img_cv2 = cv2.imread("original.png")
img_pil = Image.fromarray(cv2.cvtColor(img_cv2, cv2.COLOR_BGR2RGB))
img_pil.save("result_cv2_to_pil_tif.tif", icc_profile=profile.tobytes())
```

However, when doing the same for a ".png" file the icc_profile is saved

```python
img_pil.save("result_cv2_to_pil_tif.tif", icc_profile=profile.tobytes())
```

I solved it adding the icc_profile to the info attribute prior saving the image:

```python
img_pil.info['icc_profile'] = profile.tobytes()
img_pil.save("result_cv2_to_pil_tif.tif")
```

It seems a bug in the **save** method when the file format is .tif, as it not considers adding the icc_profile to the output image if it was not previously in the info attribute.

I haven't tested it with other file formats.

**Comment by GvdBend** [comment]
Hi Crubert-digit, 
I justed wanted to add that I'm having the same problem. For me the ".tobytes()" give me an error as well "AttributeError: 'bytes' object has no attribute 'tobytes'". If I save the images without going to bytes it works for saving it, but the colors of the image do not change (for .tif format). 

I checked my images color spaces before and after the convert (.jpg and .tif). Both of them shows after the convert that there is a Adobe RGB profile, but only the .jpg shows the correct colors. 

Does anyone know how to fix this problem?

**Comment by Crubert-digit** [comment]
Hi GvdBend, 

Are you opening the profile file with ImageCms.getOpenProfile("AdobeRGB.icm")?? It seems you're trying to convert to Bytes an object which is already Bytes. I use the tobytes() method to convert the profile file to the icc_profile bytes format after opening it with ImageCms.

For the TIF files try assigning the profile on the info attribute prior saving it (I'm assuming the profile variable already has the icc profile loaded and it is a Bytes object):

image.info['icc_profile'] = profile

**Comment by GvdBend** [comment]
Hi Crubert-digit, 

Sorry, I'm quite new to Python and I indeed didn't use the "ImageCms.getOpenProfile("AdobeRGB.icm")". Now when I try to use your code it gives me the following error : 'PIL.ImageCms.PyCMSError: cannot open profile file'. My understanding is that I haven't created the AdobeRGB profile yet, as it does not standard exist in Pillow? 

I've checked the website and tried to read more in to the getOpenProfile and buildTransformFromOpenProfiles, but can't really figure out what to do. Could you please explain to me what you did. Thanks in advance!

**Comment by Crubert-digit** [comment]
Hi GvdBend,

ImageCms.getOpenProfile("AdobeRGB.icm") is opening a file in my path called 'AdobeRGB.icm' which contains the icc profile, so actually the method is:
ImageCms.getOpenProfile(file_path)

**Comment by GvdBend** [comment]
Hi Crubert-digit, 

Thanks to you I made it work, thank you!

**Comment by radarhere** [comment]
> However, when doing the same for a ".png" file the icc_profile is saved
> 
> ```python
> img_pil.save("result_cv2_to_pil_tif.tif", icc_profile=profile.tobytes())
> ```

This is confusing - I presume you meant to write "result_cv2_to_pil_tif.png" in your code example.
