### ISSUE TITLE
Numpy array computed using vector multiplication not correctly converted

### ISSUE THREAD

**Issue by thomas-maschler** [python-pillow/Pillow#5227]
### What did you do?

I am trying to create a PNG image from a Numpy Array. Before converting the array, I transformed values using multiplication.

### What did you expect to happen?
I would expect that the array values used as input correspond 1 to 1 with the output, no matter how they were computed.

### What actually happened?
When I multiply my initial array using a vector, the final image has wrong pixel values (lots of zeros). However, if I replace the vector with a scalar the pixel values are correct.

### What are your OS, Python and Pillow versions?

* OS: MacOS
* Python: 3.8
* Pillow: 8.0.1

```python
import numpy as np
from PIL import Image

vector = np.ones((5, 5, 3)).astype("uint8") * np.array([3])
scalar = np.ones((5, 5, 3)).astype("uint8") * 3

assert np.array_equal(vector, scalar)

vector_img = Image.fromarray(vector, mode="RGB")
scalar_img = Image.fromarray(scalar, mode="RGB")

assert np.array_equal(np.array(vector_img), np.array(scalar_img))
```

**Comment by radarhere** [comment]
Hi. Removing `mode="RGB"` from your code,
```python
vector_img = Image.fromarray(vector)
```
gives me
```
TypeError: Cannot handle this data type: (1, 1, 3), <i8
```
So my diagnosis is that this is just a form of data that we haven't added support for yet. I believe it corresponds to RGB mode with RGB;64S rawmode.

Let us know if you think that it should still be working with `mode="RGB"` at the end.

**Comment by radarhere** [comment]
I think the fact that an error isn't displayed can be considered part of #2856, and the lack of support for this format part of #1888
