### ISSUE TITLE
Unicode fonts are not rendering properly while using them to write on pdfs

### ISSUE THREAD

**Issue by agrawalar** [python-pillow/Pillow#5245]
### What did you do?
I used the Reportlab library available in Python to generate an Indic-language (HINDI) pdf file, my data is of UTF-8 encoding format. To print that data in a pdf file I had used several Unicode fonts. However, I am facing font rendering issues mainly with ि, and a few other Hindi alphabets.

**Comment by radarhere** [comment]
Hi. Could you provide some code to demonstrate the issue? That way we could talk about a specific situation.

**Comment by agrawalar** [comment]
> Hi Andrew. 
Example: [This is the expected  outcome]
मै यह घोषणा करता/करती हूँ कि मैने विज्ञापन के सभी निर्देषों को ध्यानपूर्वक पढ़ लिया है एवं आवेदन पत्र में भरे गए सभी विवरण मेरी अधिकतम जानकारी और विश्वास के अनुसार सत्य है। मै यह भी घोषणा करता / करती हूँ कि मैने कोई भी महत्वपूर्ण सूचना नहीं छिपाई है जिससे कि आवेदित पद हेतु मेरा आवेदन निरस्त किया जा सके। मैं समझता / समझती हूँ कि अगर भरे गए आवेदन पत्र में कोई भी सत्यता जैसे जाति या शैक्षिक योग्यता आदि छिपाया या विरूपित किया गया हो तो मै संस्थान में कोई भी रोजगार के लिए अस्वीकार किया जाऊँगा और यदि मै पहले से ही संस्थान के किसी पद पर कार्यरत हँ तो मेरी सेवा बिना किसी सूचना अथवा हर्जाने के तुरन्त समाप्त कर दी जाएगी।
However, this is what the execution outcome is!
![image](https://user-images.githubusercontent.com/62441297/106664678-69a32c80-65cb-11eb-90b4-3f1baa7de6e6.png)

**Comment by radarhere** [comment]
If I understand you correctly, you're having trouble rendering the character ' ि'? According to https://graphemica.com/%E0%A4%BF, this is a 'devanagari vowel sign'.

We already have two issues raised about Devanagari not rendering correctly with Pillow - #2255 and #3191.

If you have a specific situation you feel is not described in those two issues, feel free to let us know.

**Comment by radarhere** [comment]
I would recommend installing libraqm, and seeing if that helps your situation.

See https://github.com/rakeshvar/unicode_text_to_image_array/commit/061b14bb20f023ac6eef0187c0dc5722bc320e42 or the 'layout_engine' argument at https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype

**Comment by prakash084** [comment]
म पागल भइसके तर मिलाउन सकिन ।
its not supported while rendering in pdf from html in django by using xhtml2pdf and pisa

**Comment by radarhere** [comment]
You've mentioned three other libraries there. Are you able to put together an example using just Pillow?
