### ISSUE TITLE
Endless loop when using font.getsize() with specific characters

### ISSUE THREAD

**Issue by Luc1412** [python-pillow/Pillow#5262]
### What did you do?
I used myfont.getsize with special characters eg. `⚡ꎇ꒒ꍏꌚꀍ_test⚡`

### What did you expect to happen?
The size gets calculated properly (at least with ? or square for unsupported characters)

### What actually happened?
The code get stuck in an endless loop

### What are your OS, Python and Pillow versions?

* OS: Linux Alpine Linux-3.12.3
* Python: 3.9.1-final
* Pillow: 8.1.0

```python
username = '⚡ꎇ꒒ꍏꌚꀍ_test⚡'
font = ImageFont.truetype('assets/fonts/Segoe.ttf', 25)
name_width, name_height = font.getsize(username)  # <- Code got stuck here
print('fished')  # <- Will be never reached
 ```

**Comment by radarhere** [comment]
I'm unable to replicate. Where did you get Segoe.ttf from?

**Comment by Luc1412** [comment]
It's my bad. My code involved font resizing depending on the length and got stuck in a while loop. 
The error showed pillow `getsize()` as root, which led me to the conclusion that the special chars are the reason.
