### ISSUE TITLE
ImageQt does not work as expected in PyQt5

### ISSUE THREAD

**Issue by driscollis** [python-pillow/Pillow#5266]
### What did you do?

Attempted to use ImageQt to load a Pillow image in a PyQt5 application

### What did you expect to happen?

I expected the image to load correctly. There are no errors, but it does not load the image in PyQt5 correctly.

### What actually happened?

The image loaded as a mostly white image with kind of ghost image of the actual photo (see screenshot). I have attached the PyQt5 and PySide6 code, including screenshots from when I ran both files.

**Note: The same code works in PySide6, but not in PyQt5.**

### What are your OS, Python and Pillow versions?

* OS: MacOS Mojave and Windows 10
* Python: Python 3.9
* Pillow: 8.0.0
![pink_flower](https://user-images.githubusercontent.com/2895418/107862335-d27f7580-6e11-11eb-9cf9-d4a19d2d615b.jpg)

```python
import sys

from PIL import Image, ImageQt
from PyQt5.QtGui import QPixmap, QImage
from PyQt5.QtWidgets import QWidget, QLabel
from PyQt5.QtWidgets import QVBoxLayout, QApplication


class ImageViewer(QWidget):

    def __init__(self):
        QWidget.__init__(self)
        self.setWindowTitle("PyQt Image Viewer")

        # Open up image in Pillow
        image = Image.open("pink_flower.jpg")
        qt_image = ImageQt.ImageQt(image)
        pixmap = QPixmap.fromImage(qt_image)

        self.image_label = QLabel('')
        self.image_label.setPixmap(pixmap)

        self.main_layout = QVBoxLayout()
        self.main_layout.addWidget(self.image_label)
        self.setLayout(self.main_layout)


if __name__ == "__main__":
    app = QApplication(sys.argv)
    viewer = ImageViewer()
    viewer.show()
    app.exec_()
```

[pyqt_pillow_issue.zip](https://github.com/python-pillow/Pillow/files/5976581/pyqt_pillow_issue.zip)

**Comment by radarhere** [comment]
Something that may or may not be interesting - if I modify your code to converting the image to ImageQt and then back to Pillow, the resulting image is fine. So there's no loss of information.

```python
import sys

from PIL import Image, ImageQt
from PyQt5.QtWidgets import QWidget
from PyQt5.QtWidgets import QApplication


class ImageViewer(QWidget):

    def __init__(self):
        QWidget.__init__(self)
        # Open up image in Pillow
        expected = Image.open("pink_flower.jpg")
        ImageQt.fromqpixmap(ImageQt.toqpixmap(expected)).show()


if __name__ == "__main__":
    app = QApplication(sys.argv)
    ImageViewer()
```

**Comment by radarhere** [comment]
Ok, got it. You're hitting this bug

https://github.com/python-pillow/Pillow/blob/fdd8b68b83fd1afdbbe5d0a0460ac1413299dcc5/src/PIL/ImageQt.py#L203-L205

If I change your code to
```python
        # Open up image in Pillow
        image = Image.open("pink_flower.jpg")
        pixmap = ImageQt.toqpixmap(image)
```
then it works.

**Comment by driscollis** [comment]
Huh. That's interesting. I know I tried that, but I didn't remove the `pixmap = QPixmap.fromImage(qt_image)` line, which raises an error if left in there.

This definitely works if you remove that line too.

**Comment by driscollis** [comment]
Thanks for looking into this and finding the error so quickly!

**Comment by radarhere** [comment]
I've created #5268 to change Pillow so that your original code works.

**Comment by driscollis** [comment]
Thanks for looking into this. I appreciate it!
