### ISSUE TITLE
GIF writing should use LZW encoding

### ISSUE THREAD

**Issue by raygard** [python-pillow/Pillow#5278]
### What did you do?
Create a GIF
### What did you expect to happen?
It should use LZW encoding, as most GIF applications do.
### What actually happened?
It used Fredrik Lundh's cleverly compatible but suboptimal encoding from 1999.
### What are your OS, Python and Pillow versions?

* OS: Windows, Linux
* Python: 3.7, 3.8, 3.9, any other
* Pillow: Doesn't matter; does this on everything since 1999.

This isn't a bug report, it's an enhancement request. I'm pretty sure Fredrik did it this way to avoid the then-current LZW patent problems with Unisys. Those ended in 2004 after all Unisys patents on LZW expired. I'm puzzled why, 17 years later, LZW has been barely mentioned anywhere regarding GIFs from PIL. I see a mention in #617 and #4644. Both of these say GIFs are currently "uncompressed"; that's not quite right. Fredrik had a clever sort-of-run-length-encoding technique. I think using LZW still won't fix all the concerns in #617, I think PIL could use more work for animated GIFs but would need to look into that more.

I see in #617 "Filesize concerns" an invite from @wiredfool "If you’d like to contribute a gif compressor under the PIL license, go for it."

I have one ready to go, well tested at my end in Windows and Linux (WSL2 and Raspios). It's a mod to Gif.h and a major overhaul of GifEncode.c. A drop-in replacement that does not require any other changes.

PIL currently writes all GIFs as 256-color, with full 8 bits in the uncompressed pixels (as in tobytes()). My GifEncode.c writes them this way, but it is ready to go for shorter codes (smaller color tables) when the rest of PIL is (probably GifImagePlugin.py and others).

**Comment by raygard** [comment]
Hi Scott,

The short answer is I'm pretty sure this has nothing to do with the LZW
encoding.

[An aside: I don't know how you got this to me; I don't know all about how
github works. I don't see anything from you on the issue page despite the
"view it on github" link
https://github.com/python-pillow/Pillow/issues/5278#issuecomment-1096991984
. I would prefer this get discussed in the issue or as a new issue,
so @radarhere and others can contribute to understanding the problem.]

How I know: I used a couple utilities, dumpgif and runlzw (in
https://github.com/raygard/giflzw/tree/main/utilities) to extract the LZW
content and the corresponding unencoded pixel data from both gif files
(call them ok.gif and bad.gif) above. I can see that the pixel data is not
the same, which accounts for the size difference. I dumped with dumpgif,
then for ok.gif, I used runlzw (which uses the same LZW encoder as the one
in  PIL) to re-encode the extracted pixel data, and it exactly matches the
LZW data in ok.gif. (That was likely but not sure to happen. Some LZW
encoders may get slightly better encoding, mostly by manipulating when LZW
"clear" codes are emitted, but my encoder sends a clear code as soon as the
hash table is full, and most other encoders do the same.)

So it is still a mystery why the PIL image has trouble in Teams. I have no
knowledge of Teams. The only significant difference I can see between these
two files is that ok.gif uses GIF disposal method 1 (do not dispose) for
all four frames after the first, while bad.gif uses disposal method 3
(restore to previous image) on the fourth frame and 1 on the other three
frames (after the first, which has no graphics control extension block in
either file and so has no disposal specified.)

As to the size difference: ok.gif has a significantly smaller third frame
than bad.gif (105 x 105 vs 256 x 129), and also has fewer colors in each of
its color tables. GIF writers try to reduce the size by use of disposal
methods and transparency to get some degree of "delta compression" between
frames, by noting the parts of the image that have not changed and making
them transparent. I suspect GIMP does a better job of locating these areas
and maybe better quantization to get fewer colors in the tables (or
something like that).

Just for kicks, try this version in place of the bad.gif above and see if
it shows the same problem:

[image: trythis.gif]

This is the bad.gif above but patched to use disposal method 1 on all
frames after the first.

I am curious exactly how you use PIL to create the bad.gif to begin with.
Does PIL automatically use different disposal methods from one frame to the
next or is that something you do? I am (coincidentally) just starting to
get back into trying to improve GIF handling in PIL.

And to answer your question "is this issue fully implemented": No. PIL
always encodes GIFs from 8-bit pixels, even when the GIF has 2, 4, 8, 16,
32, or 128 colors. The spec allows shorter pixel codes (indexes to the
color tables) to be encoded starting with shorter LZW codes. My encoder can
handle that but PIL needs some work to actually do it. That's another thing
I'm intending to work on. It should make GIFs that use fewer colors
somewhat smaller.

Ray

**Comment by smccombie** [comment]
Holy smokes, yes that image works!

**Comment by raygard** [comment]
@smccombie Scott, try just putting `disposal=1` as an arg to `.save()`. I don't know how that will affect the size or if they'll look the way you want. Let us know how it works for you.

About the "NETSCAPE" looping application extension appearing each frame: yes, I've seen that, and it would be nice to be rid of it. But I did not see that in the sample bad animation you said came from PIL. How did that happen? Did you do something to remove the extra extensions? And, it is really supposed to appear right after the global color table. I may report this as an issue, but may try to fix it myself first.

**Comment by raygard** [comment]
@smccombie I love a good mystery, don't you? Let's continue this as a [discussion #6207](https://github.com/python-pillow/Pillow/discussions/6207), as I think it has nothing to do with this (LZW) issue. But I would like to get to the bottom of it...

**Comment by radarhere** [comment]
Quick summary for anyone who visits this thread in the future - the above issues should have been fixed as of Pillow 9.2.0.
