### ISSUE TITLE
Unexpected layers when saving frames to GIF

### ISSUE THREAD

**Issue by caojianfeng** [python-pillow/Pillow#5281]
Pillow                                            8.1.0

### What did you do?
merge png files to a gif
each files has there alpha
inputs:
![1](https://user-images.githubusercontent.com/11853564/109102918-d6da5580-7764-11eb-9c3f-2cfd7a83cd0b.png)
![2](https://user-images.githubusercontent.com/11853564/109102923-d8a41900-7764-11eb-8586-60bddca183ca.png)
![3](https://user-images.githubusercontent.com/11853564/109102926-d93caf80-7764-11eb-9bf2-e6df1e928a12.png)

outputs:

![pilgif](https://user-images.githubusercontent.com/11853564/109102941-de99fa00-7764-11eb-9588-cebd567e04e2.gif)

error_frame:
<img width="281" alt="error_frames" src="https://user-images.githubusercontent.com/11853564/109103187-5d8f3280-7765-11eb-991a-9598ba56e9bf.png">

### What did you expect to happen?

Create a gif with alpha without error layers

### What actually happened?
frames in the gif  not expect layers

the frame[1]` is frame[0]+frame[1] 
the frame[2]` is frame[0]+frame[1] +frame[2] 

### What are your OS, Python and Pillow versions?

* OS:             macOS 10.15.4
* Python:      3.7.8
* Pillow:         8.1.0

```python
from PIL import Image, ImageSequence

infiles = ['input/1.png', 'input/2.png', 'input/3.png']


def pngs2gif(infiles, outfile, overwrite, preview, duration):
    print("===== pngs2gif =====")
    print('FROM:', infiles)
    print('preview:', preview)
    print('TO:', outfile)
    print('duration:', duration)

    images = []
    durations = []
    for infile in infiles:
        images.append(Image.open(infile))
        durations.append(int(duration))

    images[0].save(outfile,
                   format="GIF",
                   save_all=True,
                   append_images=images[1:],
                   duration=durations,
                   background=1,
                   version="GIF89a",
                   transparency=0)
    index = 0
    for frame in images:
        frame.save(f"frame{index}.png")
        index += 1

    print("----- pngs2gif -----")


if __name__ == "__main__":
    pngs2gif(infiles, 'pilgif.gif', True, False, 300)

```

**Comment by radarhere** [comment]
If I add in `disposal=2`, I find that it works.
```python
    images[0].save(outfile,
                   format="GIF",
                   save_all=True,
                   append_images=images[1:],
                   duration=durations,
                   background=1,
                   disposal=2,
                   version="GIF89a",
                   transparency=0)
```
![pilgif](https://user-images.githubusercontent.com/3112309/109119550-f2f7ea00-7798-11eb-88ac-853a6a9f020e.gif)

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving
> disposal
> Indicates the way in which the graphic is to be treated after being displayed.
> - 0 - No disposal specified.
> - 1 - Do not dispose.
> - 2 - Restore to background color.
> - 3 - Restore to previous content.
>
> Pass a single integer for a constant disposal, or a list or tuple to set the disposal for each frame separately.

**Comment by caojianfeng** [comment]
@radarhere Thank you very much. It work for me!
And thank you for the doc link. Its what I need.
