### ISSUE TITLE
save and load jpeg image from io.BytesIO() do not agree

### ISSUE THREAD

**Issue by Ykid** [python-pillow/Pillow#5284]
### What did you do?
try to serialize and deserialize a pillow image in jpeg format

### What did you expect to happen?
the deserialized image should be the same as the input image

### What actually happened?
the deserialized image is not the same as the input image

### What are your OS, Python and Pillow versions?

* OS: 
```
NAME="Ubuntu"
VERSION="18.04.5 LTS (Bionic Beaver)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 18.04.5 LTS"
VERSION_ID="18.04"
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
VERSION_CODENAME=bionic
UBUNTU_CODENAME=bionic
```

* Python: Python 3.6.9

* Pillow: 8.1.0

image to test
![foo](https://user-images.githubusercontent.com/4862636/109158184-ff3a7200-77ad-11eb-8339-be36d3b7a2e5.jpg)

```python
def test_convert_pillow_img_to_bytes_and_back_demo():
    test_image_path = Path("path to test image above")
    sample_img_pil = Image.open(str(test_image_path))
    img_byte_arr = io.BytesIO()
    sample_img_pil.save(img_byte_arr, format=sample_img_pil.format)
    expected = Image.open(img_byte_arr, formats=[sample_img_pil.format])
    assert ImageChops.difference(sample_img_pil, expected).getbbox() is None
```

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/issues/4686#issuecomment-643421525
> JPEG is a lossy image format, so the exact encoded or decoded pixel values can vary, depending on compression settings, the exact version of the underlying jpeg library, and other settings. It is meant to gradually throw away data that is unlikely to be noticed in photographic type images.
>
> If you require exact pixel perfect images, you need an image format that doesn't use lossy compression, such as PNG or TIFF (with a lossless compression method).

If I try run your test method with a PNG file, it passes.

**Comment by Ykid** [comment]
thanks @radarhere !
