### ISSUE TITLE
Save an excel with image on it doesn't work on AWS Lambda (no error raised)

### ISSUE THREAD

**Issue by AvekIA** [python-pillow/Pillow#5285]
### What did you do?
prerequisite: AWS account, create a IAM user with AmazonS3FullAccess and AWSLambda_FullAccess.
I create an AWS lambda. This lambda load a model.xlsx, save it as a temporary file and upload it on an s3. Then I go to my s3 and I download the file.

### What did you expect to happen?
I expected to see image on the output.xlsx file on the s3 as I had theses images on the model.xlsx.

### What actually happened?
Everything is fine except that I don't have my images on the output.xlsx on the s3. There should be an error raised like `ImageError: You can't save image because ....` because I did what I could to keep the images and now, I don't know what to do. To create my lambda, I used `pip3 install --target ./MYPATH pillow` and `pip3 install --target ./MYPATH pillow` to have the necessary libraries. (maybe it's not enough ?)

### What are your OS, Python and Pillow versions?

* OS: Linux kernel – 4.14.165-102.205.amzn2.x86_64
* Python: 3.8
* Pillow: 8.1.0

```python
import json
import openpyxl
from tempfile import NamedTemporaryFile
import boto3
import botocore


def lambda_handler(event, context):
    s3_client = boto3.client('s3', aws_access_key_id='*****', aws_secret_access_key='*****')
    wb = openpyxl.load_workbook('model.xlsx')
    #doing some stuff on the wb
    with NamedTemporaryFile() as tmp:
        wb.save(tmp.name)
        tmp.seek(0)
        s3_client.upload_file(tmp.name, "my-bucket-name", "filename-in-the-bucket")

    return {
        'statusCode': 200,
        'body': json.dumps("Hello World")
    }
```

**Comment by wiredfool** [comment]
It doesn't appear that there's anything here related to Pillow.

**Comment by radarhere** [comment]
I see that Pillow is a requirement of openpyxl. What makes you think this is a problem with the way that Pillow handles images, rather than a problem with the way that openpyxl is reading your spreadsheet?

**Comment by radarhere** [comment]
Could we get a copy of model.xlsx?

**Comment by radarhere** [comment]
How are you invoking the lambda? Is it actually done in a way that you could see an error if it was output?

Does this run successfully when you try it locally? If this only happens in AWS, can you save any file from Python? I would expect no, leading to the simplest explanation that this is a problem unrelated to Pillow. I would say that Pillow's save methods write files in a simple enough way such that I don't expect this to require a change to our library.

**Comment by radarhere** [comment]
Closing unless more information is provided - considering that the [official Lambda documentation has an example saving an image with Piilow](https://docs.aws.amazon.com/lambda/latest/dg/with-s3-example-deployment-pkg.html), it's hard to see how this could be a Pillow problem.
