### ISSUE TITLE
Install doesn't work consistently on Python >3.7?

### ISSUE THREAD

**Issue by zulc22** [python-pillow/Pillow#5294]
### What did you do?
Get issues using PIL and reinstalled Python and PIL.

### What did you expect to happen?
The line `from PIL import Image` to work.

### What actually happened?
It doesn't work. Read below.

### What are your OS, Python and Pillow versions?

* OS: Windows 10 x64 (10.0.19042.804)
* Python: 3.9.2
* Pillow: 

```
PS C:\Users\zulc22> # Fresh install of Python 3.9.2 from Python.org
PS C:\Users\zulc22> python -m pip install -U pip
Requirement already satisfied: pip in c:\users\zulc22\appdata\local\programs\python\python39\lib\site-packages (21.0.1)
PS C:\Users\zulc22> pip install Pillow
Requirement already satisfied: Pillow in c:\users\zulc22\appdata\local\programs\python\python39\lib\site-packages (8.1.0)
PS C:\Users\zulc22> python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\zulc22\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\zulc22\AppData\Local\Programs\Python\Python39\lib\site-packages\PIL\__init__.py)
>>> import PIL; PIL.__file__
'C:\\Users\\zulc22\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PIL\\__init__.py'
```

**Comment by radarhere** [comment]
> Get issues using PIL and reinstalled Python and PIL.

When speaking, we prefer to use PIL to refer to [the earlier version of this package](https://pypi.org/project/PIL/) before it was forked and became Pillow.
Just to be clear - you didn't try to install PIL, right? You don't have multiple copies of PIL and/or Pillow installed? If you uninstall Pillow, you get a `ModuleNotFoundError` instead?

**Comment by zulc22** [comment]
Sorry, yes, that was a typo. I only tried Pillow, PIL hasn't touched this computer.

**Comment by zulc22** [comment]
I also don't have any other copies.
```
PS C:\Users\zulc22> pip uninstall Pillow
Found existing installation: Pillow 8.1.0
Uninstalling Pillow-8.1.0:
  Would remove:
    c:\users\zulc22\appdata\local\programs\python\python39\lib\site-packages\pil\*
    c:\users\zulc22\appdata\local\programs\python\python39\lib\site-packages\pillow-8.1.0.dist-info\*
Proceed (y/n)? y
  Successfully uninstalled Pillow-8.1.0
PS C:\Users\zulc22> python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ModuleNotFoundError: No module named 'PIL'
```

**Comment by cgohlke** [comment]
I can't reproduce this in a Windows Sandbox:
```
Microsoft Windows [Version 10.0.19041.844]
(c) 2020 Microsoft Corporation. All rights reserved.

C:\Users\WDAGUtilityAccount>python -m pip install Pillow
Collecting Pillow
  Downloading Pillow-8.1.0-cp39-cp39-win_amd64.whl (2.2 MB)
     |████████████████████████████████| 2.2 MB ...
Installing collected packages: Pillow
Successfully installed Pillow-8.1.0
WARNING: You are using pip version 20.2.3; however, version 21.0.1 is available.
You should consider upgrading via the 'C:\Users\WDAGUtilityAccount\AppData\Local\Programs\Python\Python39\python.exe -m pip install --upgrade pip' command.

C:\Users\WDAGUtilityAccount>python
Python 3.9.2 (tags/v3.9.2:1a79785, Feb 19 2021, 13:44:55) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
>>> import PIL; PIL.__file__
'C:\\Users\\WDAGUtilityAccount\\AppData\\Local\\Programs\\Python\\Python39\\lib\\site-packages\\PIL\\__init__.py'
>>>

```

**Comment by zulc22** [comment]
for some reason if I run by `python -m pip` it works, but by `pip` alone it doesn't??

**Comment by zulc22** [comment]
i'm going to close this because it isn't Pillow's fault, but I think we still need to look into this to figure out why this is happening

**Comment by zulc22** [comment]
now I can't load it from [`poetry`](https://python-poetry.org) either...!
```
PS C:\Users\zulc22\code\fnforiginizer> poetry install
Creating virtualenv fnforiginizer-pH8RzrvN-py3.9 in C:\Users\zulc22\pypoetry\Cache\virtualenvs
Installing dependencies from lock file

Package operations: 4 installs, 0 updates, 0 removals

  • Installing defusedxml (0.6.0)
  • Installing numpy (1.20.1)
  • Installing pillow (8.1.1)
PS C:\Users\zulc22\code\fnforiginizer> poetry run python .\originizer.py DADDY_DEAREST
Traceback (most recent call last):
  File "C:\Users\zulc22\code\fnforiginizer\originizer.py", line 3, in <module>
    import os, sys, pyora
  File "C:\Users\zulc22\pypoetry\Cache\virtualenvs\fnforiginizer-pH8RzrvN-py3.9\lib\site-packages\pyora\__init__.py", line 5, in <module>
    from .Project import Project
  File "C:\Users\zulc22\pypoetry\Cache\virtualenvs\fnforiginizer-pH8RzrvN-py3.9\lib\site-packages\pyora\Project.py", line 3, in <module>
    from PIL import Image
  File "C:\Users\zulc22\pypoetry\Cache\virtualenvs\fnforiginizer-pH8RzrvN-py3.9\lib\site-packages\PIL\Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\zulc22\pypoetry\Cache\virtualenvs\fnforiginizer-pH8RzrvN-py3.9\lib\site-packages\PIL\__init__.py)
PS C:\Users\zulc22\code\fnforiginizer>
```

**Comment by hugovk** [comment]
> for some reason if I run by `python -m pip` it works, but by `pip` alone it doesn't??

See https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by zulc22** [comment]
still unsure whether I should open a new issue for poetry

**Comment by radarhere** [comment]
If you can install from Python directly, but not from poetry, then doesn't that sound like it's better suited to reporting at https://github.com/python-poetry/poetry ?

**Comment by zulc22** [comment]
even FURTER INTO the rabbit hole. Pillow _and_ numpy only work without issues for me on Python 3.7 x64 at the latest, through pip and poetry.

**Comment by radarhere** [comment]
> Pillow and numpy only work without issues for me on Python 3.7 x64 at the latest, through pip and poetry.

Could you reword this? I don't understand.

**Comment by zulc22** [comment]
If I use anything newer than Python 3.7 on Windows, I have none of the above issues at all. The issues don't happen on Linux.

**Comment by radarhere** [comment]
If `python -m pip` works but `pip` doesn't, I would suggest that `pip` is connected to another Python installation.

If `python -m pip` works but `poetry` doesn't, then it sounds to me like that is an issue with poetry, not Pillow - I say this not to try and pass the buck, but because I would think that as a package management tool, it would be poetry's plan to help users install our package, not for our package to help poetry.

**Comment by zulc22** [comment]
I didn't have any other Python installations. I've only ever had one at a time and deleted all remaining files.

**Comment by c13-github** [comment]
I also reproduced this today with a new Python 3.8.7 install on Windows amd64

Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\*\AppData\Roaming\Python\Python38\site-packages\PIL\Image.py",
line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\*\AppData\Roamin
g\Python\Python38\site-packages\PIL\__init__.py)
>>>

Installation was via python -m. Uninstalling and using pip install causes same issue for me.

C:\Users\*\AppData\Local\Programs\Python\Python38>python -m pip install pillow --user
Collecting pillow
  Using cached Pillow-8.1.1-cp38-cp38-win32.whl (1.9 MB)
Installing collected packages: pillow
Successfully installed pillow-8.1.1

Comparison of the pip versions using both suggested approaches shows they are identical and reading the same locations:

C:\Users\*\AppData\Local\Programs\Python\Python38>python -m pip --version
pip 21.0.1 from C:\Users\C\AppData\Local\Programs\Python\Python38\lib\site-packages\pip (python 3.8)

C:\Users\*\AppData\Local\Programs\Python\Python38>pip --version
pip 21.0.1 from c:\users\c\appdata\local\programs\python\python38\lib\site-packages\pip (python 3.8)

**Comment by nulano** [comment]
@c13-github Is there a file with the name starting with `_imaging.` in the directory `C:\Users\*\AppData\Roaming\Python\Python38\site-packages\PIL`? What is the full name of this file?

**Comment by c13-github** [comment]
There is a matching file

Directory of c:\Users\*\AppData\Roaming\Python\Python38\site-packages\PIL

3/03/2021  01:39 PM         2,280,448 _imaging.cp38-win32.pyd

**Comment by nulano** [comment]
@c13-github That is the 32-bit file. I also just noticed that your output above is installing `Pillow-8.1.1-cp38-cp38-win32.whl`, which is the 32-bit version of Pillow.

To use Pillow in 64-bit Python, reinstall it using 64-bit python/pip. The filename for the 64-bit files should end with `-win_amd64.pyd` or `-win_amd64.whl`.

**Comment by c13-github** [comment]
I also believed the Pillow bitness fetched was unusual given python.exe as installed from (python-3.8.7-amd64.exe) opens up with a 64-bit banner, however it seems to do the same when I switched to the 64-bit cmd.exe and installed -win_amd64 version:

`c:\Users\*\AppData\Local\Programs\Python\Python38>python -m pip install https://
files.pythonhosted.org/packages/56/a8/769f1def4d283e71393319eee44f0c04ca49805a91
d07dcba15b490f2395/Pillow-8.1.1-cp38-cp38-win_amd64.whl
Collecting Pillow==8.1.1
  **Downloading Pillow-8.1.1-cp38-cp38-win_amd64.whl (2.2 MB)**`
 
`c:\Users\C\AppData\Local\Programs\Python\Python38>python
Python 3.8.7 (tags/v3.8.7:6503f05, Dec 21 2020, 17:59:51) [MSC v.1928 **64 bit** (AM
D64)] on **win32**    
from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Users\C\AppData\Roaming\Python\Python38\site-packages\PIL\Image.py",
line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (C:\Users\C\AppData\Roamin
g\Python\Python38\site-packages\PIL\__init__.py)
`

and asserting the required 64-bit file fails:

`c:\Users\C\AppData\Roaming\Python\Python38\site-packages\PIL>dir _imaging*win64*.*
Directory of c:\Users\*\AppData\Roaming\Python\Python38\site-packages\PIL
File Not Found`

**Comment by nulano** [comment]
Whether you use 32-bit or 64-bit cmd.exe is irrelevant. Since the 64-bit file is still not there, the installation probably failed. Can you try uninstalling Pillow and making sure the directory `C:\Users\*\AppData\Roaming\Python\Python38\site-packages\PIL` doesn't exist before you try installing again?

**Comment by c13-github** [comment]
Stand corrected on the bitness of cmd.exe affecting amd64 installation. Also I agree that pip failed silently on the x64 wheel.  Went through wikified steps at https://izziswift.com/installing-pil-python-imaging-library-in-win7-64-bits-python-2-6-4/ to solution #6 which seemed most applicable to my case and I ensured vc_redist.x64.exe was installed and latest.

Thereafter Pillow 8.1.1 installs at 'C:\\Users\\*\\AppData\\Local\\Programs\\Python\\Python38\\Lib\\site-packages\PIL' and 'Image' can be imported as expected.

vc_redist.x64 isn't mentioned on either python.org or pillow.readthedocs.io as an amd64 dependency so will try flagging that up.

**Comment by zulc22** [comment]
@c13-github THAT was the actual issue here.
