### ISSUE TITLE
RGBA Image.resize with Nearest Neighbor Interpolation introduces new RGB Values

### ISSUE THREAD

**Issue by gerhardneuhold** [python-pillow/Pillow#5300]
### What did you do?

Resizing an RGBA image with Image.resize and nearest neighbor interpolation.

### What did you expect to happen?

Image resized to given size, no new RGB values introduced.

### What actually happened?

New RGB values introduced.

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.8.6
* Pillow: 6.2.1

### Python Example

```python
import numpy as np
from PIL import Image

image = np.asarray([[[1, 1, 0, 128]], [[2, 2, 0, 64]]], dtype=np.uint8)

print("Input")
print(image)
print("")

image = Image.fromarray(image)
image = image.resize((1, 1), Image.NEAREST)
image = np.asarray(image)

print("Output")
print(image)
```

```
Input
[[[  1   1   0 128]]
 [[  2   2   0  64]]]

Output
[[[ 3  3  0 64]]]
```

**Comment by radarhere** [comment]
Would you be able to provide an input image, so that we can potentially discuss a specific example?
Also, and this may not be related, Pillow 6.2.1 is a bit old. Is there any reason you haven't upgraded to a newer Pillow version?

**Comment by radarhere** [comment]
Oh, apologies, I see that you have provided an input.

**Comment by gerhardneuhold** [comment]
The version if fixed for the project I am working on but it's also happening with Pillow 8.1.0. Maybe issue #4516 is related?

**Comment by radarhere** [comment]
You'll likely think this is a basic question, but could you link me to something explaining that nearest neighbor interpolation shouldn't introduce new values?

**Comment by nulano** [comment]
> You'll likely think this is a basic question, but could you link me to something explaining that nearest neighbor interpolation shouldn't introduce new values?

From https://pillow.readthedocs.io/en/stable/handbook/concepts.html#PIL.Image.NEAREST:

> Pick one nearest pixel from the input image. Ignore all other input pixels.

I would interpret that as meaning that each pixel in the output will be equal to one of the original pixels, i.e. not introducing new values.

**Comment by nulano** [comment]
I've created #5304 to disable premultiplying with NEAREST resampling.
