### ISSUE TITLE
ImportError: cannot import name '_imagingcms' from 'PIL'

### ISSUE THREAD

**Issue by kennedyjosh** [python-pillow/Pillow#5308]
### What did you do?

Tried to convert an image to SRGB format using the following function:

```python
# source: https://www.reddit.com/r/learnpython/comments/k7xk7r/failed_minimal_tag_size_sanity_pyqt5/givnexh?utm_source=share&utm_medium=web2x&context=3                                     
def convert_to_srgb(file_path):
    '''Convert PIL image to sRGB color space (if possible)'''
    img = Image.open(file_path)
    icc = img.info.get('icc_profile', '')

    if icc:
        io_handle = io.BytesIO(icc)  # virtual file                                                                                                                                         
        src_profile = ImageCms.ImageCmsProfile(io_handle)
        dst_profile = ImageCms.createProfile('sRGB')
        img_conv = ImageCms.profileToProfile(img, src_profile, dst_profile)
        icc_conv = img_conv.info.get('icc_profile', '')

        if icc != icc_conv:
            # ICC profile was changed -> save converted file                                                                                                                                
            img_conv.save(file_path, format='JPEG', quality=50, icc_profile=icc_conv)

``` 

### What did you expect to happen?

The function to work as intended.

### What actually happened?

Execution stops with an error:
```
Traceback (most recent call last):
  File "/app/main.py", line 108, in <module>
    img_dr.convert_to_srgb(img)    # avoids a warning
  File "/app/img_dr.py", line 12, in convert_to_srgb
    src_profile = ImageCms.ImageCmsProfile(io_handle)
  File "/usr/local/lib/python3.7/dist-packages/PIL/ImageCms.py", line 172, in __init__
    self._set(core.profile_frombytes(profile.read()))
  File "/usr/local/lib/python3.7/dist-packages/PIL/_util.py", line 19, in __getattr__
    raise self.ex
  File "/usr/local/lib/python3.7/dist-packages/PIL/ImageCms.py", line 23, in <module>
    from PIL import _imagingcms
ImportError: cannot import name '_imagingcms' from 'PIL' (/usr/local/lib/python3.7/dist-packages/PIL/__init__.py)
```

### What are your OS, Python and Pillow versions?

* OS: Debian (Buster) 10.8 inside of a Docker container on a Raspberry Pi (ARM architecture)
* Python: 3.7.3
* Pillow: 8.1.1

The full code for this project can be found here (it isn't much): https://github.com/kennedyjosh/rpi_gui

The problem does not reproduce when running outside of Docker on Debian 10.7, same python and pillow versions. This leads me to believe that perhaps my Docker instance is missing some kind of dependency. Here are the packages installed on the OS inside of Docker: `python3-pyqt5 python3-pip python3-dev zlib1g-dev libjpeg-dev gcc musl-dev`. The last 4 are required for Pillow to work at all.

**Comment by radarhere** [comment]
Could you install liblcms2-dev, re-install Pillow and try again?

As an aside, from https://github.com/python-pillow/Pillow/issues/5202#issuecomment-788554261, it is apparent that you're on armv7l architecture, which we don't have a wheel for.

**Comment by kennedyjosh** [comment]
> install liblcms2-dev

This solved this issue. Thanks!
