### ISSUE TITLE
Misleading error message

### ISSUE THREAD

**Issue by Eskapp** [python-pillow/Pillow#5310]
Minor usability request

### What did you do?
Used the `getpixel()` method on an image passing the position as two arguments instead of a tuple.

### What did you expect to happen?
It crashed which is the expected behavior yet the error message is misleading:

```
img.getpixel(300, 300)

Traceback (most recent call last):
  File "/opt/.pycharm_helpers/pydev/_pydevd_bundle/pydevd_exec2.py", line 3, in Exec
    exec(exp, global_vars, local_vars)
  File "<input>", line 1, in <module>
TypeError: getpixel() takes 2 positional arguments but 3 were given
```

I passed 2 positional arguments not 3. I think that the message should be `getpixel() takes 1 positional argument but 2 were given`.

### What are your OS, Python and Pillow versions?
* OS: Linux Ubuntu (Docker)
* Python: 3.8
* Pillow: 7.1.2

**Comment by radarhere** [comment]
If you take a look at this example in the console,
```pycon
>>> class Demo:
...     def test(self, xy):
...         pass
... 
>>> demo = Demo()
>>> demo.test(100, 100)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: test() takes 2 positional arguments but 3 were given
```
I think you will find that this is just Python's standard behaviour. To do anything else would be breaking from how all other libraries would behave by default, and confuse users who were used to that.

**Comment by radarhere** [comment]
You responded with a thumbs up. Does that mean that you're happy for this issue to be closed?
