### ISSUE TITLE
Could not import pillow 

### ISSUE THREAD

**Issue by deadlylaid** [python-pillow/Pillow#5322]
Hi i install pillow on MacOS M1 BigSur

but when i import PIL like
```python
from PIL import Image
```
raise an error about import 

```pycon
>>> from PIL import Image
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/jade/Works/myproject/venv/lib/python3.8/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/jade/Works/myproject/venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so, 2): no suitable image found.  Did find:
        /Users/jade/Works/myproject/venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wrong architecture
        /Users/jade/Works/myproject/venv/lib/python3.8/site-packages/PIL/_imaging.cpython-38-darwin.so: mach-o, but wrong architecture
```

I tried reinstall pip and virtualenv but raise same error...

can somebody help me? thank you :)

**Comment by radarhere** [comment]
How did you install Pillow?

**Comment by radarhere** [comment]
You are using Python 3.8. [3.9.1 is the first version of Python to support macOS 11 Big Sur. ](https://www.python.org/downloads/release/python-391/). So I would recommend changing to Python 3.9.

If you change, then I think you will find that `pip install` now works, as it will detect our M1 wheel.

**Comment by hugovk** [comment]
Could/should we detect if we're on M1 and < 3.9.1 and put out a warning like for source builds on Windows:

https://github.com/python-pillow/Pillow/blob/21da5b1ed8e905b7f3e4198207486317304b8698/setup.py#L40-L51

**Comment by radarhere** [comment]
https://www.python.org/downloads/release/python-387/
> Python 3.8.7 is not yet fully supported on macOS 11 Big Sur. It will install on macOS 11 Big Sur and will run on Apple Silicon Macs using Rosetta 2 translation. However, a few features do not work correctly... We are looking into improving the situation for Python 3.8.8.

While there is no mention of Big Sur in the [3.8.8 announcement](https://www.python.org/downloads/release/python-388/), the 3.8.7 message indicates to me that they would like to support Big Sur for Python 3.8. In which case, it seems to me that a message about it could become outdated.

**Comment by deadlylaid** [comment]
thank you i solved my issue using python3.9 :)

**Comment by radarhere** [comment]
For the record, Python 3.8.10 now supports Big Sur - https://www.python.org/downloads/release/python-3810/
> But there's a bunch of important updates here regardless, the biggest being Big Sur and Apple Silicon build support.
