### ISSUE TITLE
Clarify saving LZW-compressed TIFFs in the documentation

### ISSUE THREAD

**Issue by pkkm** [python-pillow/Pillow#5335]
The [documentation about saving TIFF images](https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving-tiff-images) says that

> Valid compression methods are: None, "tiff_ccitt", "group3", "group4", "tiff_jpeg", "tiff_adobe_deflate", "tiff_thunderscan", "tiff_deflate", "tiff_sgilog", "tiff_sgilog24", "tiff_raw_16"

However, I can create LZW-compressed TIFFs by passing a "tiff_lzw" value:

```python
image.save("image.tif", compression="tiff_lzw")
```

Since LZW is a commonly used compression method, I think it would be good to clarify what's going on here:

* Does it accidentally happen to work but with problems I'm not seeing?
* Is the support dependent on the user's software configuration?
* Is the value "tiff_lzw" officially supported and the fact that it isn't in the documentation is an oversight?

**Comment by radarhere** [comment]
My answer is that it is a documentation oversight, so I've created #5336.

**Comment by pkkm** [comment]
Thanks!

**Comment by kmilos** [comment]
Also, I suggest taking out `tiff_deflate` from this doc list, as it should not be used for writing, [see this TIFF tech note](https://www.adobe.io/content/dam/udp/en/open/standards/tiff/TIFFphotoshop.pdf):

> A proprietary ZIP/Flate compression code (0x80b2) has been used by some software vendors. This code should be considered obsolete. The compression used by the obsolete code is identical to that defined above. We recommend that TIFF implementations recognize and read the obsolete code, but only write the official compression code (8).

**Comment by radarhere** [comment]
I've removed `tiff_deflate` in #5336, and created #5343 to change it to `tiff_adobe_deflate` when writing.
