### ISSUE TITLE
Updating __main__.py to allow basic conversions

### ISSUE THREAD

**Issue by Salaah01** [python-pillow/Pillow#5337]
At the moment running `python3 -m PIL` only returns information about PIL.
Perhaps it's worth using allows some basic conversion by calling it as a module?
e.g: `python3 -m PIL -s /path/to/img -r "1000x500" -f "png" -o /path/to/output` would take an image, resize to 1000x500, convert to png and then output to a specified path.

**Comment by radarhere** [comment]
Currently, the way that Pillow is used is through Python code. You're effectively suggesting opening up another way of using Pillow, by the command line.

I'm concerned that there's no clearly defined boundary of which features we should make available through the command line, and which ones can be left to just Python code, but let me ask this instead - isn't ImageMagick already a tool for doing this? What do you think that Pillow has to offer above and beyond that?

**Comment by Salaah01** [comment]
Hi,
I never actually knew ImageMagick even existed.
This idea is a dud.
Thanks for taking the time to reply!
