### ISSUE TITLE
 draw.text((50,5),str(d['类型']), font=font25bd, fill='#eaca67')

### ISSUE THREAD

**Issue by kerwinxu** [python-pillow/Pillow#5346]
File "批量添加文字.py", line 108, in draw_content
    draw.text((50,5),str(d['类型']), font=font25bd, fill='#eaca67')
  File "d:\anaconda3\lib\site-packages\PIL\ImageDraw.py", line 379, in text
    draw_text(ink)
  File "d:\anaconda3\lib\site-packages\PIL\ImageDraw.py", line 324, in draw_text
    mask, offset = font.getmask2(
  File "d:\anaconda3\lib\site-packages\PIL\ImageFont.py", line 667, in getmask2
    size, offset = self.font.getsize(
OSError: invalid face handle

```python
code goes here
```

**Comment by radarhere** [comment]
If your error is "OSError: invalid face handle", then you might be experiencing the same problem as #3066 and #4225.

If so, #5062 is an upcoming solution.

**Comment by kerwinxu** [comment]
> If your error is "OSError: invalid face handle", then you might be experiencing the same problem as #3066 and #4225.
> 
> If so, #5062 is an upcoming solution.

Thank you , 



Here's how to fix it

fnt = ImageFont.truetype('../fonts/georgiai.ttf', 36, layout_engine=ImageFont.LAYOUT_BASIC)
