### ISSUE TITLE
Memory usage increasing when converting from JPEG to WebP - causes OOM by OS

### ISSUE THREAD

**Issue by Desttro** [python-pillow/Pillow#5348]
### What did you do?
Processing a list with about 2300 JPEG images paths with these steps:

1. thumbnailing
2. convert to RGBA
3. pasting a PNG image over that as a watermark
4. finally saving as WebP

### What did you expect to happen?
Get WebP images with low-memory usage, as it is with JPEG

### What actually happened?
Memory usage of this process is still increasing and that causes OutOfMemory process kill by OS - if I am processing about 100k+ images.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.10 x64
* Python: 3.8.6
* Pillow: 8.1.2

This is code, which works well and memory usage is normal - seems that memory is released properly after image was processed.

```python
from pathlib import Path

from PIL import Image as PillowImage

LOGO = PillowImage.open(BASE_DIR / 'assets/watermark/watermark.png').convert('RGBA')
THUMB_SIZE = (960, 720)

def watermark_and_convert(images_list):
    images = []

    for image in images_list:
        output_img_path = str(image).replace('input', 'output')
        with PillowImage.open(image) as im:
            try:
                im.thumbnail(THUMB_SIZE)
                im.convert('RGBA')
                position = ((im.width - LOGO.width), (im.height - LOGO.height))
                im.paste(LOGO, position, LOGO)
                im.save(output_img_path, 'JPEG')
            except Exception as e:
                logger.exception(f'(2) watermark_and_convert: {e} ')

        images.append(Path(output_img_path))
        logger.info('(2) watermark_and_convert: ' + output_img_path + ' DONE!')

    return images
```

But this code is not working properly - memory is not released and it is increasing over time. Here I just added a new replace method to change the extension and changed the save method to WEBP:

```python
from pathlib import Path

from PIL import Image as PillowImage

LOGO = PillowImage.open(BASE_DIR / 'assets/watermark/watermark.png').convert('RGBA')
THUMB_SIZE = (960, 720)

def watermark_and_convert(images_list):
    images = []

    for image in images_list:
        output_img_path = str(image).replace('input', 'output').replace('.jpg', '.webp')  # here is change
        with PillowImage.open(image) as im:
            try:
                im.thumbnail(THUMB_SIZE)
                im.convert('RGBA')
                position = ((im.width - LOGO.width), (im.height - LOGO.height))
                im.paste(LOGO, position, LOGO)
                im.save(output_img_path, 'WEBP')  # here is change
            except Exception as e:
                logger.exception(f'(2) watermark_and_convert: {e} ')

        images.append(Path(output_img_path))
        logger.info('(2) watermark_and_convert: ' + output_img_path + ' DONE!')

    return images
```

What is wrong here, please? Is there something wrong with WebP conversion on a background? That for example image is not closing? Or why it is not releasing memory?

**Comment by radarhere** [comment]
Not an answer to your question, but note that `im.convert('RGBA')` has no effect. You want `im = im.convert('RGBA')` instead - see https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert
> Returns a converted copy of this image.

**Comment by Desttro** [comment]
I did not notice that. So `im.paste` works also without this conversion. I was thinking, that it is needed to do this `im.convert` to apply a watermark. I can remove it from my code now, thank you!

**Comment by radarhere** [comment]
I'm not able to consistently see a difference between saving as JPEG and WEBP on my machine.

Could you modify your example so that it is more defined? Say, attach an image and a code example that uses it that still demonstrates the problem - so that we don't have the unknown input of many images?

Also, what version of WEBP are you using?
```pycon
>>> from PIL import _webp
>>> _webp.webpdecoder_version
'1.2.0'
```

**Comment by Desttro** [comment]
Thank you very much for your time. I have found, that it seems that the issue is on the Django side of from `django.core.files.images.ImageFile` or combination that with Pillow.

When I will pass images from my function `watermark_and_convert` to Django's `ImageFile` in JPEG, everything works perfectly. But when I change that to WEBP, a memory leak occurs. I have tested only Pillow without Django and there is no memory leak, so it may be an issue in Django.

```python
from django.core.files.images import ImageFile

img = Image(vehicle=data)
for image in images_webp:
    img = Image(vehicle=data)
    img.image.save(image.name, ImageFile(open(image, 'rb')), save=True)
```

My _webp encoder version is also '1.2.0'.

So I will close this issue. Thanks!

**Comment by nulano** [comment]
#5132 might be relevant given the reference to Django.

The solution suggested there seems to be
```python
with django_image.file.open(), PIL.Image.open(django_image.file) as pillow_image:
    pass
```

**Comment by Desttro** [comment]
Thank you very much! It seems, that it makes sense. Just wondering, this code uses an image, that is already saved in DB. What when I want to upload an image programmatically a script, please? I am doing these steps:

1. Download multiple images for a product
2. Covert these images related to the product to WebP format and return a list of all images with `Path`
3. Get a related `Image` table for an `Product`
4. Save all images to `Image` table for product

I am just wondering, how to format this `with` statement correctly, this is my original code:

```python
from PIL import Image as PillowImage
from django.core.files.images import ImageFile

from catalog.models import Product, Image

product = Product(pk=1)  # get a product
img = Image(product=product)  # get related Image table for a product - there are stored all images for a single product

images_webp = watermark_and_convert(down_images)  # this method returns a list of all converted images in WebP format in Path type

# I am just wondering, how to reformat this code to handle both files to close - Pillow and Django, as @nulano suggested (Thank you!)
for image in images_webp:
    with open(image, 'rb') as im:
        img.image.save(image.name, ImageFile(im), save=True)
```
