### ISSUE TITLE
AttributeError: 'module' object has no attribute '_Condition'

### ISSUE THREAD

**Issue by qcq** [python-pillow/Pillow#5355]
I need to install other third library which need Pillow in jython of pip, which complain about below, please help

robot@ni11-853:~/jython2.7.2/bin$ ./pip install Pillow --no-cache-dir
DEPRECATION: A future version of pip will drop support for Python 2.7.
Collecting Pillow
  Downloading https://files.pythonhosted.org/packages/b3/d0/a20d8440b71adfbf133452d4f6e0fe80de2df7c2578c9b498fb812083383/Pillow-6.2.2.tar.gz (37.8MB)
     |████████████████████████████████| 37.8MB 386kB/s
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-install-xuDF86/Pillow/setup.py", line 25, in <module>
        import mp_compile
      File "mp_compile.py", line 11, in <module>
        from multiprocessing import Pool, cpu_count
      File "/home/robot/jython2.7.2/Lib/site-packages/multiprocessing/__init__.py", line 64, in <module>
        import multiprocessing.patch
      File "/home/robot/jython2.7.2/Lib/site-packages/multiprocessing/patch.py", line 58, in <module>
        class ConditionPatch(object):
      File "/home/robot/jython2.7.2/Lib/site-packages/multiprocessing/patch.py", line 61, in ConditionPatch
        notify_all = threading._Condition.notifyAll.im_func
    AttributeError: 'module' object has no attribute '_Condition'
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-install-xuDF86/Pillow/

**Comment by radarhere** [comment]
Given that `from multiprocessing import Pool, cpu_count` is failing, I expect there is a problem with the `multiprocessing` module in your Python installation.

However, if you would only like to solve the Pillow problem, a solution would be
1. Download https://github.com/python-pillow/Pillow/archive/refs/tags/6.2.2.tar.gz
2. Expand the file
3. Inside the Pillow-6.2.2 directory, open setup.py, find the line 'import mp_compile', remove it, and save. This should be fine for your Python 2.7 environment.
4. Inside the Pillow-6.2.2 directory, run `pip install .`

**Comment by qcq** [comment]
@radarhere  Thanks for your quick help, I tried which more error, what's more it is **jython2.7.2** not python

robot@ni11-853:/tmp/Pillow-6.2.2$ ~/jython2.7.2/bin/pip install .
DEPRECATION: A future version of pip will drop support for Python 2.7.
Processing /tmp/Pillow-6.2.2
Installing collected packages: Pillow
  Running setup.py install for Pillow ... error
    ERROR: Complete output from command /home/robot/jython2.7.2/bin/jython -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-0z12_9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-knafO0/install-record.txt --single-version-externally-managed --compile:
    ERROR: running install
    running build
    running build_py
    creating build
    creating build/lib.java1.8.0_281-2.7
    creating build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PngImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/_util.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageDraw2.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageQt.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PdfImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PalmImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/EpsImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/XVThumbImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/JpegPresets.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/Image.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/MpoImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/BufrStubImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/GdImageFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageOps.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/IptcImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageMode.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PcfFontFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/XbmImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/_binary.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/TiffImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageColor.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/GimpPaletteFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImagePalette.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/GimpGradientFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/TgaImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/JpegImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/FtexImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PixarImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageSequence.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/GribStubImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/McIdasImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/FliImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PaletteFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/BmpImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/_tkinter_finder.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/BlpImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageFont.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/GifImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageTk.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/DdsImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/FitsStubImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/TiffTags.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ContainerIO.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PSDraw.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/XpmImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageMath.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/__main__.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/GbrImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PcxImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/features.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageGrab.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PdfParser.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageDraw.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PpmImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PcdImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/DcxImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageEnhance.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/_version.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImagePath.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageChops.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageWin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/WmfImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/IcoImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/CurImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PyAccess.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/MspImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ExifTags.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageStat.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/PsdImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/SgiImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageTransform.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/SunImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageCms.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/BdfFontFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/FontFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/MicImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/TarIO.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageMorph.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/__init__.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/SpiderImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageFilter.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/FpxImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImtImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/WebPImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/ImageShow.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/WalImageFile.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/MpegImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    copying src/PIL/IcnsImagePlugin.py -> build/lib.java1.8.0_281-2.7/PIL
    running egg_info
    creating src/Pillow.egg-info
    writing dependency_links to src/Pillow.egg-info/dependency_links.txt
    writing top-level names to src/Pillow.egg-info/top_level.txt
    writing src/Pillow.egg-info/PKG-INFO
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.codecov.yml'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'azure-pipelines.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.azure-pipelines'
    no previously-included directories found matching '.travis'
    writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
    running build_ext
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-0z12_9/setup.py", line 852, in <module>
        setup(
      File "/tmp/pip-req-build-0z12_9/setup.py", line 852, in <module>
        setup(
      File "/home/robot/jython2.7.2/Lib/site-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/home/robot/jython2.7.2/Lib/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/robot/jython2.7.2/Lib/distutils/core.py", line 151, in setup
        dist.run_commands()
      File "/home/robot/jython2.7.2/Lib/distutils/dist.py", line 953, in run_commands
        self.run_command(cmd)
      File "/home/robot/jython2.7.2/Lib/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/robot/jython2.7.2/Lib/site-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/home/robot/jython2.7.2/Lib/distutils/command/install.py", line 577, in run
        self.run_command('build')
      File "/home/robot/jython2.7.2/Lib/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/robot/jython2.7.2/Lib/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/robot/jython2.7.2/Lib/distutils/command/build.py", line 127, in run
        self.run_command(cmd_name)
      File "/home/robot/jython2.7.2/Lib/distutils/cmd.py", line 326, in run_command
        self.distribution.run_command(command)
      File "/home/robot/jython2.7.2/Lib/distutils/dist.py", line 972, in run_command
        cmd_obj.run()
      File "/home/robot/jython2.7.2/Lib/distutils/command/build_ext.py", line 337, in run
        self.build_extensions()
      File "/tmp/pip-req-build-0z12_9/setup.py", line 556, in build_extensions
        if _find_library_file(self, "z"):
      File "/tmp/pip-req-build-0z12_9/setup.py", line 216, in _find_library_file
        ret = self.compiler.find_library_file(self.compiler.library_dirs, library)
      File "/home/robot/jython2.7.2/Lib/distutils/ccompiler.py", line 777, in find_library_file
        raise NotImplementedError
    NotImplementedError
    ----------------------------------------
ERROR: Command "/home/robot/jython2.7.2/bin/jython -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-req-build-0z12_9/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record /tmp/pip-record-knafO0/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-req-build-0z12_9/
WARNING: You are using pip version 19.1, however version 20.3.4 is available.
You should consider upgrading via the 'pip install --upgrade pip' command.

**Comment by radarhere** [comment]
Searching online, I found the following

https://stackoverflow.com/a/60030349/4093019
> Pillow is partially written in C, so it won't work on Jython.

https://answers.launchpad.net/sikuli/+question/630628
> Python modules like PIL/Pillow cannot be used in SikuliX directly, since they contain C-based code and access to native libraries.
> SikuliX uses Jython as interpreter, which is Java based and only allows Python modules completely written in Python language

So it seems like you may not be able to do this.

**Comment by qcq** [comment]
oh, Thanks for your quick help again, I check that link, seems that is old more than 1 year, seems jython not do some effort on it, even java also has JNI.
anyway Thanks again.
