### ISSUE TITLE
PIL Image function inversing width and height of image

### ISSUE THREAD

**Issue by Vaibhavbrkn** [python-pillow/Pillow#5362]
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```python
code goes here
```

**Comment by radarhere** [comment]
Hi. Would you be able to provide more information? Ideally, a code example to demonstrate what you are doing?

To take a wild guess, are you dealing with numpy at all?

**Comment by Vaibhavbrkn** [comment]
No I'm not dealing with numpy at all.
here's the example:

`>>> import pandas as pd
>>> from PIL import Image
>>> df = pd.read_csv('final_tagging.csv')
>>> df[df['filename'] == 'IMG_20210301_150409.jpg'][['height' , 'width']].iloc[0]
height    4608
width     3456
Name: 575, dtype: int64
>>> Image.open('train/images/IMG_20210301_150409.jpg').size
(4608, 3456)
>>> df[df['filename'] == 'IMG_20210301_144505.jpg'][['height' , 'width']].iloc[0]
height    3120
width     4160
Name: 637, dtype: int64
>>> Image.open('val/images/IMG_20210301_144505.JPG').size
(4160, 3120)
`
as you can see for the first image I'm getting size in (height , width) format , while for second image I'm getting size in (width , height) format.

**Comment by nulano** [comment]
It's hard to say what is going on without knowing how the csv was generated or seeing the images, but taking a guess, the following might be helpful. From https://github.com/python-pillow/Pillow/issues/4703#issuecomment-645219973:

>I would imagine that the images you are dealing with have an EXIF orientation tag. This means that the image data is save in one position, and then the image instructs the viewer to rotate it another way.
>
>Pillow does not automatically apply this transformation to the data. However, it has a method to do so - https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.exif_transpose
>
>Here is an example using it. You can try this and check if it resolves your problem.
>```python
>from PIL import Image, ImageOps
>im = Image.open("file.jpg")
>im = ImageOps.exif_transpose(im)
>```
>However, this is all a guess. To be sure, please provide an image, and ideally, the code that you are running over it.

**Comment by radarhere** [comment]
@Vaibhavbrkn are you able to provide a copy of the problem image? Or did the previous post explain what is happening?

**Comment by radarhere** [comment]
Closing unless further information is given, as a possible explanation has been provided.
