### ISSUE TITLE
ImageOps.expand distorts image and converts png to grayscale

### ISSUE THREAD

**Issue by glisignoli** [python-pillow/Pillow#5375]
### What did you do?
Resize an image and add a black border

### What did you expect to happen?
Image would be resized with a black border

### What actually happened?
Image is distorted converted to grayscale, resized and border added

### What are your OS, Python and Pillow versions?

* OS: Fedora 33
* Python: 3.8.6
* Pillow: 8.1.2

```shell
git clone https://github.com/hampusborgos/country-flags.git
cd country-flags/png1000px
```

```python
from PIL import Image, ImageOps
i = Image.open('./bo.png')
i = i.resize((128,96))

# File saves correctly
i.save('./test.png')

i = ImageOps.expand(i, border=10, fill='black')

# File gets converted to grayscale and is distorted
i.save('./test.png')
```

**Comment by radarhere** [comment]
The bug is because the image is in P mode. If you are interested in an immediate solution, convert it to RGB.
```python
from PIL import Image, ImageOps
i = Image.open('./bo.png')
i = i.resize((128,96))

# File saves correctly
i.save('./test.png')

i = ImageOps.expand(i.convert("RGB"), border=10, fill='black')

# File gets converted to grayscale and is distorted
i.save('./test.png')
```

**Comment by glisignoli** [comment]
Thanks! Would this still be classified as a bug? I think it could be considered one?

**Comment by radarhere** [comment]
Yes, this is still a bug that we should address.

**Comment by ahammadshawki8** [comment]
I faced the same problem and solved it by converting it to RGB, Thanks.

**Comment by radarhere** [comment]
#5551 stopped the output from being grayscale, but the colors were wrong.
#5552 fixed the colors, but accidentally shifted the border slightly.

#5562 fixes the border position, resolving this.

![test](https://user-images.githubusercontent.com/3112309/123790595-daa00380-d921-11eb-8933-7415fbdc711f.png)
