### ISSUE TITLE
Rounded rectangle corners got an offset 

### ISSUE THREAD

**Issue by Luc1412** [python-pillow/Pillow#5381]
### What did you do?

I use the new rounded rectangle method with the given code and values.

### What did you expect to happen?

I get a rounded rectangle

### What actually happened?

I got a rounded rectangle, but the bottom corners got an offset:

![test](https://user-images.githubusercontent.com/24532065/113515659-196a2b80-9576-11eb-97ea-4462b12a3bad.png)

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.9
* Pillow: 8.2.0

```python
xy =  [(104, 37), (109, 87)]
radius = 3
fill = (196, 196, 196, 255)

fac = 5
width, height = (xy[1][0] - xy[0][0]) * fac, (xy[1][1] - xy[0][1]) * fac
img = Image.new('RGBA', (width, height))
image_draw = ImageDraw.Draw(img)
image_draw.rounded_rectangle([(0, 0), (width, height)], radius * fac, fill=fill)
img.save('test.png')  # <- Image was taken from here
img = img.resize((int(width / fac), int(height / fac)), Image.ANTIALIAS)
image.paste(img, (xy[0][0], xy[0][1]), img)
```

**Comment by radarhere** [comment]
To explain what is happening -

`width` is (109-104) * 5 = 25.
`radius * fac` is 15.
Pillow limits the radius to half the width, making the radius 12.5.

This has uncovered a bug, where we are not handling a non-integer radius correctly in `rounded_rectangle`.

I've created #5382 to resolve this.
