### ISSUE TITLE
Artifacts when saving as JPEG

### ISSUE THREAD

**Issue by driscollis** [python-pillow/Pillow#5388]
### What did you do?

I drew some text using an `ImageDraw.Draw()` object.

### What did you expect to happen?

I expected the text to appear on the image without artifacts

### What actually happened?

There is pixelization around the text. It makes the image appear to be very highly compressed.

### What are your OS, Python and Pillow versions?

* OS: Mac Mojave
* Python: 3.9
* Pillow: 8.0.0

```python
# text_colors.py

from PIL import Image, ImageDraw, ImageFont


def text_color(output_path):
    image = Image.new("RGB", (200, 200), "white")
    draw = ImageDraw.Draw(image)
    colors = ["green", "blue", "red", "yellow", "purple"]
    font = ImageFont.truetype("Gidole-Regular.ttf", size=12)
    y = 10
    for color in colors:
        draw.text((10, y), f"Hello from Pillow", font=font, fill=color)
        y += 35
    image.save(output_path)

if __name__ == "__main__":
    text_color("colored_text.jpg")
```

**Comment by radarhere** [comment]
Hi. You're currently saving as JPG. Could you try saving as PNG instead? I find this makes a difference.

I understand you might still wish for JPG to produce a better quality output, but it will at least help clarify the problem.

**Comment by driscollis** [comment]
I do think that may be slightly better. However, if I was doing some batch processing on hundreds or thousands of files, adding a watermark or a copyright, I wouldn't want to convert to PNG. Those tend to be much larger in size, which could be a concern if done in the cloud.

**Comment by hugovk** [comment]
JPEG is lossy, but you can increase the save `quality` from default 75 to 95.

https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html?highlight=quality#jpeg

**Comment by hugovk** [comment]
Does increasing the `quality` help?

**Comment by hugovk** [comment]
Closing due to lack of response, please increase `quality`. We can re-open this if necessary.
