### ISSUE TITLE
Tags are changed or being dropped since 8.2.0

### ISSUE THREAD

**Issue by Segelzwerg** [python-pillow/Pillow#5389]
### What did you do?
I used to get meta information of a jpg file with Pillow.

### What did you expect to happen?
The last version that was working was 8.1.2.

### What actually happened?
 Since 8.2.0 some exif tags like 
```
ExifImageWidth,
ExifImageHeight,
Flash',
FNumber,
FocalLength,
ISOSpeedRatings
```
are missing. There are actually more (see example below). And `DateTimeOriginal` was changed to `DateTime`.

### What are your OS, Python and Pillow versions?

* OS: ubuntu 20.04
* Python: 3.9.3
* Pillow: 8.2.0

![example](https://user-images.githubusercontent.com/25705862/113871938-af3eca00-97b3-11eb-8d29-62aa8e2f9659.jpg)

```python
from PIL import ExifTags, Image

path = '/example_1.jpg'
with Image.open(path) as image:
    exif = {ExifTags.TAGS[k]: v for k, v in image.getexif().items() if k in
            ExifTags.TAGS}
    exif = {k: str(v) for k, v in exif.items()}
    print(exif)
```

**Comment by radarhere** [comment]
Hi. This is a result of https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#image-getexif-exif-and-gps-ifd
> **Image.getexif: EXIF and GPS IFD**
> Previously, getexif() flattened the EXIF IFD into the rest of the data, losing information. This information is now kept separate, moved under im.getexif().get_ifd(0x8769).
>
> Direct access to the GPS IFD dictionary was possible through im.getexif()[0x8825]. This is now consistent with other IFDs, and must be accessed through im.getexif().get_ifd(0x8825).
>
> These changes only affect getexif(), introduced in Pillow 6.0. The older _getexif() methods are unaffected.

So if I change your script like so, I see the missing information again.
```python
from PIL import ExifTags, Image

path = 'im.jpeg'
with Image.open(path) as image:
    exif = {ExifTags.TAGS[k]: v for k, v in image.getexif().items() if k in
            ExifTags.TAGS}
    exif = {k: str(v) for k, v in exif.items()}
    print(exif)
    exif = {ExifTags.TAGS[k]: v for k, v in image.getexif().get_ifd(0x8769).items() if k in
            ExifTags.TAGS}
    exif = {k: str(v) for k, v in exif.items()}
    print(exif)
```

**Comment by radarhere** [comment]
@Segelzwerg did that answer your question?

**Comment by Segelzwerg** [comment]
> @Segelzwerg did that answer your question?

@radarhere  it looks like it would, but haven't got the chance to try it myself. I will do so and report.

**Comment by Segelzwerg** [comment]
> Hi. This is a result of https://pillow.readthedocs.io/en/stable/releasenotes/8.2.0.html#image-getexif-exif-and-gps-ifd
> 
> > **Image.getexif: EXIF and GPS IFD**
> > Previously, getexif() flattened the EXIF IFD into the rest of the data, losing information. This information is now kept separate, moved under im.getexif().get_ifd(0x8769).
> > Direct access to the GPS IFD dictionary was possible through im.getexif()[0x8825]. This is now consistent with other IFDs, and must be accessed through im.getexif().get_ifd(0x8825).
> > These changes only affect getexif(), introduced in Pillow 6.0. The older _getexif() methods are unaffected.
> 
> So if I change your script like so, I see the missing information again.
> 
> ```python
> from PIL import ExifTags, Image
> 
> path = 'im.jpeg'
> with Image.open(path) as image:
>     exif = {ExifTags.TAGS[k]: v for k, v in image.getexif().items() if k in
>             ExifTags.TAGS}
>     exif = {k: str(v) for k, v in exif.items()}
>     print(exif)
>     exif = {ExifTags.TAGS[k]: v for k, v in image.getexif().get_ifd(0x8769).items() if k in
>             ExifTags.TAGS}
>     exif = {k: str(v) for k, v in exif.items()}
>     print(exif)
> ```

thank you very much that workers like a charm
