### ISSUE TITLE
Building problem wheel for cp38-cp38-macosx_11_0_arm64 (python provided by apple)

### ISSUE THREAD

**Issue by gordio** [python-pillow/Pillow#5394]
I don't understand why
`make clean && CFLAGS='-g -O0' python3 setup.py clean build_ext bdist_wheel && ./selftest.py`:
```
…
Traceback (most recent call last):
  File "./selftest.py", line 6, in <module>
    from PIL import Image, features
  File "/Users/gordio/Development/Pillow/src/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/Users/gordio/Development/Pillow/src/PIL/__init__.py)
```
but
`make clean && CFLAGS='-g -O0' python3 setup.py clean develop build_ext bdist_wheel && ./selftest.py`:
```
…
--- 58 tests passed.
```
in both cases on linking stage I can see: 
```
ld: warning: ignoring file /opt/homebrew/lib/libjpeg.dylib, building for macOS-x86_64 but attempting to link with file built for macOS-arm64
```
This is a bug?

**Comment by radarhere** [comment]
Hi. Some thoughts.

`_imaging` is not a Python script, but a .so file, for our C code.

I think this isn't a problem with building Pillow as such - selftest.py is not able to locate the Pillow that you've just built properly.

When you are running the 'develop' version, it is permanently adding the Pillow 'src' directory to `sys.path`. Then, when you run the non-develop version, it is trying to import the .so file from 'src' - except they're not there still time around, they're in 'build/lib.macosx-11.0-arm64-3.8'.

To test this, move your Pillow repository to a new location and run the non-develop version. I think you will find that it can't import Pillow at all, not just `_imaging`. Then if you run the 'develop' version and then go back to non-develop, the error you reported will reappear.

I find that copying selftest.py into the build directory makes the non-develop version work, by allowing it to find the Pillow it should be using. Something like `make clean && CFLAGS='-g -O0' python3 setup.py clean build_ext bdist_wheel && cp selftest.py build/lib.macosx-11.0-arm64-3.8 && ./build/lib.macosx-11.0-arm64-3.8/selftest.py`

**Comment by gordio** [comment]
@radarhere Yep, you right. Can I close Issue?

**Comment by radarhere** [comment]
Cool.
Sure, it's your issue.
