### ISSUE TITLE
10 bit pgm file not read correctly

### ISSUE THREAD

**Issue by jesmanson** [python-pillow/Pillow#5403]
### What did you do?
Load 10 bit pgm image and saved it as png image

### What did you expect to happen?
Pixel values scaled to use the 16 bit range 
(http://www.libpng.org/pub/png/spec/1.2/PNG-Chunks.html)

### What actually happened?
pixel values stored in the least significant bytes and hence the image is too dark

### What are your OS, Python and Pillow versions?

* OS:  Ubuntu 18.04.5 LTS
* Python: 3.6
* Pillow: 8.2.0

```python
from PIL import Image

input_path_pgm = 'path-to-10-bit-pgm-image'
output_path_png = 'path-to-16-bit-png-image'
image = Image.open(input_path_pgm)
image.save(output_path_png, format='PNG')
```

**Comment by radarhere** [comment]
Could you provide a copy of the input image?

**Comment by jesmanson** [comment]
Yeah sure! Here is an example of a 10 bit pgm image.
[cat.zip](https://github.com/python-pillow/Pillow/files/6308903/cat.zip)

**Comment by radarhere** [comment]
Just for the record, the rawmode of this image is detected as I;16B

**Comment by wiredfool** [comment]
Pillow does not auto-scale image values, even when converting between 8 bit and 16 bit formats.

This is a longstanding issue with expectations, but changing it at this point would be a breaking change.

**Comment by morincl** [comment]
Considering that this unexpected behavior is undocumented (correct me if I am wrong) and violates the PNG specification, such a breaking change would maybe be acceptable?

**Comment by radarhere** [comment]
I've created PR #6107 to resolve this.

Just to be clear - there is no problem with the PNG in the original post here. The problem is just in how a 10-bit PGM file is read by Pillow.

**Comment by kmilos** [comment]
Why stop at 10-bit? There are 12-bit pixel formats as well, e.g. used in very high quality HDR production. [FFmpeg](http://git.videolan.org/?p=ffmpeg.git;a=blob;f=libavutil/pixfmt.h;hb=HEAD) also defines 14-bit, and even 9-bit... 12 and 14 are also common bit depths for camera sensors, and raw data is sometimes dumped/converted to PGM(-like) files.

**Comment by radarhere** [comment]
Ok, I've added 9, 12 and 14 to the PR as well.
