### ISSUE TITLE
ImportError 2): Symbol not found: _PyObject_CheckBuffer Referenced from: site-packages/PIL/_imaging.cpython-39-darwin.so Expected in: flat namespace

### ISSUE THREAD

**Issue by yexin123987** [python-pillow/Pillow#5407]
Try to import
```python
from PIL import Image, ImageDraw
```

get error below:
```
from PIL import Image, ImageDraw
File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/Image.py", line 94, in <module>
from . import _imaging as core
ImportError: dlopen(/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): Symbol not found: _PyObject_CheckBuffer
Referenced from: /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so
Expected in: flat namespace
in /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so
```

Pillow version:
Seem issue on both 8.0.1 and 8.2.0
macOS - High Sierra 10.13.6
Python 3.9.0

**Comment by radarhere** [comment]
I presume you installed Pillow through pip?

**Comment by yexin123987** [comment]
> I presume you installed Pillow through pip?

Yes, I used 'pip install Pillow'

**Comment by radarhere** [comment]
And how did you install Python?

**Comment by radarhere** [comment]
A likely solution would be to compile Pillow, rather than using the prebuilt wheels. You can do this through `pip install Pillow --no-binary :all:` - but that does mean that you will have to install dependencies.

**Comment by hugovk** [comment]
And please make sure you have recent pip:

```sh
python3 -m pip install --upgrade pip
```

https://pillow.readthedocs.io/en/stable/installation.html#basic-installation

**Comment by radarhere** [comment]
@yexin123987 did any of the above comments help?

**Comment by yexin123987** [comment]
No...none of these works...

**Comment by radarhere** [comment]
How about
1. trying to uninstall Pillow
2. checking that you can't import PIL to ensure that there aren't multiple copies on your system
3. and then installing Pillow again and pasting the output from `pip install Pillow` here?

**Comment by radarhere** [comment]
Have you considered upgrading to a newer version of Python 3.9 and seeing if that changes anything?

**Comment by yexin123987** [comment]
Able to install on another machine.

**Comment by isaacsun0813** [comment]
I'm running the same error, do you know how to fix it?

**Comment by radarhere** [comment]
The above suggestions were to `python3 -m pip install --upgrade pip` or to `python3 -m pip install Pillow --no-binary :all:`

If the problem still persists, please provide more detail about your situation, including your macOS version, how you installed Pillow and the exact error that is being returned.

**Comment by isaacsun0813** [comment]
Hey there!
To both of them it says that the requirement has already been satisfied.
My code was working fine before winter break but after I came back to
school the UI I was using stopped working.
Specifically the line "from PIP import Image" keeps erroring out with this
attached:
from . import _imaging as core
ImportError:
dlopen(/Users/Isaac/Library/Python/3.8/lib/python/site-packages/PIL/_
imaging.cpython-38-darwin.so, 0x0002): tried:
'/Users/Isaac/Library/Python/3.8/lib/python/site-packages/PIL/_
imaging.cpython-38-darwin.so' (mach-o file, but is an incompatible
architecture (have 'arm64', need 'x86_64')), '/usr/local/lib/_
imaging.cpython-38-darwin.so' (no such file), '/usr/lib/_
imaging.cpython-38-darwin.so' (no such file)
I've spent over 4-5 hours this week just trying to figure it out and I
can't seem to get it. I installed pillow using pip install Pillow and it is
currently in the latest version.
Thank you so much for your help.

**Comment by isaacsun0813** [comment]
I am on macOS version 12.1

**Comment by radarhere** [comment]
The error is telling you that Pillow was built for an M1 mac, but you are on a mac with an Intel chip.
I would try uninstalling and re-installing Pillow.
```
python3 -m pip uninstall Pillow
python3 -m pip install Pillow
```

**Comment by isaacsun0813** [comment]
But the thing is I have an M1 Mac…hence why I’m confused.
I also tried installing and reinstalling to no avail.
Is there any other fix?

**Comment by radarhere** [comment]
Ah, ok. So if you run `python3 -c "import platform;print(platform.machine())"`, then you are seeing `x86_64`, and not `arm64`?

If so, I suggest re-installing Python. How did you install Python? Was it from an Intel-only installer from https://www.python.org/downloads/macos/? universal2 is the one you are after.

If re-installing Python sounds scary to you, you could instead try
```
python3 -m pip uninstall Pillow
python3 -m pip install https://files.pythonhosted.org/packages/e1/91/b50b616b77fd6a3ab46e6a4724e07c898a5172cb8f4faf5b3b6f3c7aa17a/Pillow-9.0.0-cp38-cp38-macosx_10_10_x86_64.whl
```

**Comment by isaacsun0813** [comment]
Ah okay nvm you are correct I am seeing arm64.
However, I have an apple M1 Chip...
So I'm not entirely sure what I should do from here to fix my error. I
don't understand how it suddenly didn't work after a couple of weeks.

**Comment by radarhere** [comment]
> Ah okay nvm you are correct I am seeing arm64. However, I have an apple M1 Chip

This comment has confused me. `arm64` is the value you should be seeing on an M1. Are you seeing `arm64`?

**Comment by isaacsun0813** [comment]
Also, I installed and uninstalled pillow to no avail.
I'm running python on Pycharm CE if that makes any difference...

**Comment by isaacsun0813** [comment]
Shoot sorry yes I got the two confused.
I am seeing arm64

**Comment by radarhere** [comment]
To check that you're uninstalling Pillow correctly, when you uninstall Pillow, does Pillow fail to import with `ModuleNotFoundError`?

**Comment by isaacsun0813** [comment]
[image: Screen Shot 2022-01-26 at 9.14.32 PM.png]
I get this error once I uninstall Pillow.

**Comment by radarhere** [comment]
Your screenshot has not attached itself correctly.

**Comment by isaacsun0813** [comment]
Sorry!
But when I uninstall Pillow I just get an error saying that "No module
named 'Pil' with a ModuleNotFoundError

**Comment by radarhere** [comment]
> I'm running python on Pycharm CE if that makes any difference...

If you uninstall Pillow, install Pillow and try to import Pillow just from Terminal, ignoring Pycharm, does it work then?

**Comment by isaacsun0813** [comment]
It still doesn't work.
I might've also imported Pillow wrong from Terminal. What's the correct
syntax?

**Comment by radarhere** [comment]
Once inside Python, `from PIL import Image`

**Comment by isaacsun0813** [comment]
[image: Screen Shot 2022-01-26 at 9.30.57 PM.png]
Here's what I have at the top of my code and still the error appears

**Comment by radarhere** [comment]
Your screenshot has not attached itself correctly.

**Comment by isaacsun0813** [comment]
try:
    import tkinter as tk
    import PIL
    from tkinter import font as tkfont, CENTER, font
    from PIL import ImageTk, Image
    from PIL import Image
except ImportError:
    import tkinter as tk
    import tkinter.font as tkfont
    from PIL import ImageTk, Image
<img width="421" alt="Screen Shot 2022-01-26 at 9 33 08 PM" src="https://user-images.githubusercontent.com/67129199/151287296-79eeaa1e-880f-4bca-a464-29f3cd17922a.png">

    from PIL import Image

Here's the direct code!

**Comment by radarhere** [comment]
Ok, did you want to try installing Pillow from source instead of from a wheel? It may require you to install some dependencies.

`python3 -m pip install Pillow --no-binary :all:`

**Comment by isaacsun0813** [comment]
Here's the error that I get when I tried that:
<img width="1434" alt="Screen Shot 2022-01-26 at 10 04 45 PM" src="https://user-images.githubusercontent.com/67129199/151290040-005b75fc-adb0-4003-a4e0-154aa489e24d.png">
I'm so sorry I'm pretty new to coding and I've never encountered bugs like this before.

**Comment by radarhere** [comment]
Things are often easier than this, and I know this can't be an issue for all M1 users, because we would be receiving many more complaints if it was.

When installing Pillow from source, you will require libjpeg and zlib. The error you're seeing is telling you that you need libjpeg. Do you use brew or macports?

Another idea - when you downloaded PyCharm, did you perhaps download the Intel version rather than the Apple Silicon version? https://www.jetbrains.com/pycharm/download/#section=mac

**Comment by gerhard-gs68** [comment]
I had the same problem (M1 silicon) but installing from source helped.

**Comment by aniagarwal97** [comment]
I'm facing the same issue when deploying the PIL on AWS Lambda, it works fine on my local environment though. 

My code looks somewhat like this:

`from PIL import Image`

and the error I receive is:

`[ERROR] ImportError: cannot import name '_imaging' from 'PIL' (/var/task/PIL/__init__.py)
Traceback (most recent call last):
  File "/var/task/serverless_sdk/__init__.py", line 144, in wrapped_handler
    return user_handler(event, context)
  File "/var/task/s_list.py", line 25, in error_handler
    raise e
  File "/var/task/s_list.py", line 20, in <module>
    user_handler = serverless_sdk.get_user_handler('src/handlers/list.list')
  File "/var/task/serverless_sdk/__init__.py", line 56, in get_user_handler
    user_module = import_module(user_module_name)
  File "/var/lang/lib/python3.8/importlib/__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 843, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/var/task/src/handlers/list.py", line 6, in <module>
    from src.storage.modelNames import findResource
  File "/var/task/src/storage/modelNames.py", line 8, in <module>
    from src.engines.image import set_b64image_dpi
  File "/var/task/src/engines/image.py", line 3, in <module>
    from PIL import Image
  File "/var/task/PIL/Image.py", line 94, in <module>
    from . import _imaging as core`

**Comment by iwutung** [comment]
installing from source helped through this problem too

**Comment by ZachNagengast** [comment]
M2 silicon here, had a lot of issues with this as well building from source because it wasn't finding the include paths for one reason or another. My solution was to explicitly set 

`export LDFLAGS="-L/opt/homebrew/Cellar/libraqm/0.10.1/lib $LDFLAGS"` 
`export CPPFLAGS="-I/opt/homebrew/Cellar/libraqm/0.10.1/include $CPPFLAGS"`
`make clean`
`make install-coverage`

for each library it was missing.

One tool that helped was checking if the libraries were linked directly on the compiled output:

`otool -L /.../Pillow/build/lib.macosx-14-arm64-cpython-310/PIL/_imaging.cpython-310-darwin.so`

Also if you need to check a library for the missing symbol you can use this:

`nm -gU /opt/homebrew/opt/libtiff/lib/libtiff.dylib`

Combination of brew reinstalls and brew links and the above got it compiling.
