### ISSUE TITLE
Multipage PDF doesn't work

### ISSUE THREAD

**Issue by CrazyJannis44** [python-pillow/Pillow#5409]
### What did you do?

I readed in a pdf with pdf2image (that bases on pillow) took all pages and converted them into RGB. Then it should write the image pages into a new pdf

### What did you expect to happen?

A multipage RGB PDF

### What actually happened?

Only the first page was in the output PDF

### What are your OS, Python and Pillow versions?

* OS: Win 10 Pro 20H2
* Python: 3.9.2
* Pillow: 8.2.0
* pdf2image: 1.14.0

```python
import shutil
from pathlib import Path
from sys import argv

from PIL import Image
from pdf2image import convert_from_path

pages = convert_from_path(argv[1], 500)

images: Image = []
for i in range(1, len(pages)):
    images.append(pages[i].convert("RGB"))

out = str(Path(argv[1]).absolute()) + ".pnged.pdf"
with open(out, 'w+b') as out_file:
    pages[0].convert("RGB").save(out_file, save_all=True, append=images)
```

**Comment by radarhere** [comment]
Hi. I think you're after [`append_images`](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#pdf), rather than `append`. Try changing your last line to
```python
pages[0].convert("RGB").save(out_file, save_all=True, append_images=images)
```

**Comment by CrazyJannis44** [comment]
Thx. couldn't find it in the sources
