### ISSUE TITLE
Function similar to pad but returns resized image without padding

### ISSUE THREAD

**Issue by axu2** [python-pillow/Pillow#5415]
I'd sure like a function that looks like ImageOps.pad
https://pillow.readthedocs.io/en/stable/_modules/PIL/ImageOps.html#pad

but just returns the image after resizing without adding the padding.

What would be a good name for such a function? Where would it best be placed?

ImageOps.fit is already taken.

EDIT: Looking at #3364 `contain` seems like a decent candidate. Seems a refactor would be required. @radarhere thoughts?

**Comment by radarhere** [comment]
Hi. I'm not following what you're after. Could you illustrate?

**Comment by radarhere** [comment]
I've created #5417, going with `contain`. Let us know if you have any thoughts.

**Comment by axu2** [comment]
Seems good, honestly `fit` would have been a better choice, but that's already taken. And fit should have been called `fill`
