### ISSUE TITLE
Can't override libraries with buildout zc.recipe.egg:custom

### ISSUE THREAD

**Issue by djay** [python-pillow/Pillow#542]
If you run a recipe like 

```
[Pillow]
recipe = zc.recipe.egg:custom
egg = Pillow
include-dirs =
    ${zlib:location}/include
    ${libjpeg:location}/include
    ${libpng:location}/include
    ${libtiff:location}/include
library-dirs =
    ${zlib:location}/lib
    ${libjpeg:location}/lib
    ${libtiff:location}/lib
rpath =
    ${zlib:location}/lib
    ${libjpeg:location}/lib
    ${libtiff:location}/lib
```

on a platform like osx that already includes libjpeg etc, it will ignore the specified paths and prefer the system libraries. I haven't yet found a way to ensure Pillow setup.py uses just the libraries I want it to. This is related to #169

**Comment by aclark4life** [comment]
@djay Just noticing this one while searching for ``disable-tk`` issues possibly related to #1168. Sorry I got annoyed and I apologize for my inappropriate comments. Now let me reiterate our position in the event you are still struggling with this:

- I have no doubt there are any number of issues remaining with Pillow, including those present in ``setup.py``. This is unfortunate, but not a surprise given a 20 year old code base and ~1000 lines in ``setup.py``.
- We don't have the capacity to support Buildout beyond ``eggs = Pillow`` at present, but we're always open to suggestions, pull requests, etc.
- To fix this I suspect one would need to examine the normal build process i.e. without Buildout. Then apply that knowledge to Buildout. Maybe fixing the general case will fix Buildout too, but I'm not sure.

Hope that helps!

**Comment by arterrey** [comment]
The following environment also seems to fix it too. http://stackoverflow.com/a/23452657
<code>
[Pillow-env]
CFLAGS=-Qunused-arguments
CPPFLAGS=-Qunused-arguments
</code>

**Comment by hugovk** [comment]
The last comment is from 4 years ago and suggests a fix, so closing this. If the issue can still be reproduced, please open a new issue. Thanks!
