### ISSUE TITLE
How can I install dependencies?

### ISSUE THREAD

**Issue by MatroskinGG** [python-pillow/Pillow#5428]
I tried to install libjpeg or libwebp or zlib files to my host for discord bot a lot of times with different ways, but it didnt work. When i tried to just download Pillow with pip, it said that cant find jpeg files. Then i found way to disable jpeg, but as i understood, it disables all libraries, because when i try to open different file types with Image.open(), It always crashes with error "Cant indificate file ...". I get my image from url, so can i can do without Image.open()? Or there are file type that dont need library? If there arent any way, so how can i install depended libraries to host? I am pretty new to this, and may be i cant understand simple things, but i really need help with this

* OS: may be Windows, i actually dont know host's OS
* Python: 3.7
* Pillow: 8.2.0

**Comment by MatroskinGG** [comment]
I tried just to move library files to host container and install it with commands, which found in the internet , also tried install pylibjpeg, so i actually cant understand, what was written in the Pillow-depends. May be it isnt for my OS.

**Comment by radarhere** [comment]
Hi. I wouldn't try and disable jpeg.

Bear with me while I try and follow your situation. Could you explain in basic terms what your setup is?
> my host for discord bot

Are you SSHing in to a machine? Is that why you're unsure about the operating system? If so, did you want to run `uname -srm` and report back what it says? Or at least, what is the company that you're using for this?

> I tried just to move library files to host container

You're using Docker?

**Comment by MatroskinGG** [comment]
I am using ready discord host https://bill.discord-bot.net/ , its just website, where i put my files, set up startup command, and see the cmd. I think, you can see it yourself and answer your questions.

**Comment by MatroskinGG** [comment]
I googled what ssh means, and think you are right. I tried `uname - sfm` and it said `Linux 4.19.0-12-amd64 x86_64`. What do i need to do next?

**Comment by radarhere** [comment]
Ok, you might be on Debian 10. Try this -
`apt-get install libjpeg-dev zlib1g-dev`.
If that works, then try installing Pillow again. It should be able to find libjpeg now.

**Comment by MatroskinGG** [comment]
it crashes with `proxychains can't load process....: No such file or directory`, do i need to download something?

**Comment by radarhere** [comment]
Hmm, that is unexpected. Does it output anything before that?

`lsb_release -d` should clarify if I'm right about Debian or not.

**Comment by MatroskinGG** [comment]
No, it doesn't
After `lsb_release - d` it failed with the same error `proxychains can't load process....: No such file or directory`

**Comment by MatroskinGG** [comment]
Oh, i missed, its always says `nohup: appending output to nohup.out` when i start it

**Comment by radarhere** [comment]
Maybe that is just the response that it is giving when it doesn't recognise the command.
If you just enter random characters, does it say the same thing?
If it does, then we just need to find a package manager that works - do any of the commands `apt`, `yum`, `snap`, `pacman` or `rpm` work?

**Comment by MatroskinGG** [comment]
Yes
Tried all of that, no one works

**Comment by MatroskinGG** [comment]
Actually, there wasnt any way to install packages by myself on that host. I contacted hoster and he made it by himself. But anyway thanks for attempt
