### ISSUE TITLE
Pillow ImportError

### ISSUE THREAD

**Issue by Toadman30** [python-pillow/Pillow#543]
I've gotten Pillow to install using pip install Pillow, but I get this error when trying to import it. I'm on OSX 10.7.5

Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from PIL import Image
  File "/Library/Python/2.7/site-packages/PIL/Image.py", line 53, in <module>
    from PIL import _imaging as core
ImportError: dlopen(/Library/Python/2.7/site-packages/PIL/_imaging.so, 2): Symbol not found: _jpeg_resync_to_restart
  Referenced from: /Library/Python/2.7/site-packages/PIL/_imaging.so
  Expected in: flat namespace
 in /Library/Python/2.7/site-packages/PIL/_imaging.so

Does anyone know what this means?

**Comment by linzhi** [comment]
I have this question too....

Traceback (most recent call last):
  File "videotogif.py", line 8, in <module>
    from PIL import Image
  File "/home/work/.jumbo/lib/python2.7/site-packages/PIL/Image.py", line 67, in <module>
    from PIL import _imaging as core
ImportError: /home/work/.jumbo/lib/python2.7/site-packages/PIL/_imaging.so: undefined symbol: TIFFSetWarningHandlerExt

**Comment by hugovk** [comment]
@linzhi Make sure you have Pillow installed and not PIL. If you have both, uninstall both then install only Pillow.

**Comment by wiredfool** [comment]
That error sounds like you've got a version of Pillow that's compiled against libtiff (but not a manylinux wheel), but the libtiff libraries aren't installed on the machine you're running it on.
