### ISSUE TITLE
Drawing text on image works incorrectly if the image opacity is 0

### ISSUE THREAD

**Issue by victor-radivchev** [python-pillow/Pillow#5431]
### What did you do?
Wanted to draw text on an image with 0 opacity

### What did you expect to happen?
RGB channels to have changed values only for the pixels of the letters:
![image](https://user-images.githubusercontent.com/55085526/115750968-61c08080-a3a1-11eb-979f-df884f81fca4.png)

### What actually happened?
The channels changed for the entire bounding box of the text:
![image](https://user-images.githubusercontent.com/55085526/115751182-9b918700-a3a1-11eb-8ccb-4f96882f53c6.png)

Also if `opacity` for the image is `>= 1`, the font is `ImageFont.load_default().font` or the version of Pillow is `6.2.2`, then I get the expected behavior. 

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04.5 LTS / MacOS 10.15.7
* Python: 3.7.8
* Pillow: 8.2.0

```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("Pillow/Tests/fonts/FreeMono.ttf", 40)
text = 'TEXT'
text_im = Image.new('RGBA', (100, 50), (255, 255, 255, 0))
draw = ImageDraw.Draw(text_im)
draw.text((0, 0), text, fill=(0, 0, 0), font=font)
r, g, b, _ = text_im.split()
```

**Comment by radarhere** [comment]
I'm not able to replicate this on my machine. I also get the [expected result](https://github.com/radarhere/Pillow/commit/b177aff2fb304e1a1ad3246b1541c2670387e8a5) on our CIs - [AppVeyor](https://ci.appveyor.com/project/radarhere/pillow/builds/38835729) and GitHub Actions ([Windows](https://github.com/radarhere/Pillow/actions/runs/775984772), [our Docker images](https://github.com/radarhere/Pillow/actions/runs/775984775) and [Linux and macOS](https://github.com/radarhere/Pillow/runs/2415253872))

I don't really have any ideas about why your machine is different. What version of FreeType are you using?
```pycon
>>> from PIL import _imagingft
>>> _imagingft.freetype2_version
'2.10.4'
```

**Comment by victor-radivchev** [comment]
This is the image that the Pillow 8 generates (this one is the same as "Tests/images/5431.png"):
![text_pil_8](https://user-images.githubusercontent.com/55085526/115837303-1948a780-a421-11eb-904b-a546287f1360.png)
And this is the one that Pillow 6 generates (this one is different from "Tests/images/5431.png"):
![text_pil_6](https://user-images.githubusercontent.com/55085526/115837344-24033c80-a421-11eb-9bc4-c469d73b48d1.png)
They look to be the same, but they aren't:
```python
>>> text_im_6.tobytes() == text_im_8.tobytes()
False
```
The difference becomes visible if I either split them by channels or convert them to grayscale:
```python
text_im_8.convert('L')
```
![text_pil_8_grayscale](https://user-images.githubusercontent.com/55085526/115837976-daffb800-a421-11eb-99e5-02c698848151.png)
```python
text_im_6.convert('L')
```
![text_pil_6_grayscale](https://user-images.githubusercontent.com/55085526/115838018-e7841080-a421-11eb-9594-5c61b9fa7878.png)

**Comment by radarhere** [comment]
Thanks for the explanation. Testing, this is the result of #4566.

Testing, it only happens when the opacity is 0. For even an opacity of 1, it is fine. If you'll allow me to ask - why is it a problem that the RGB values change? My inclination is to think that if the opacity is 0, it doesn't matter what color the pixels are.

**Comment by victor-radivchev** [comment]
As long as the image stays in `RGBA`  there is no problem, but if it ever gets converted to `RGB` or `L`, then it becomes an issue. That's how I stumbled upon it - my script was ending with a grayscale image as a result.

**Comment by radarhere** [comment]
I've created PR #5434 to resolve this.
