### ISSUE TITLE
`pieslice` draws very thin sectors incorrectly

### ISSUE THREAD

**Issue by hwjsnc** [python-pillow/Pillow#5432]
### What did you do?
I drew a circle sector with a very small central angle using `pieslice`.

### What did you expect to happen?
I expected to get a shape approximating a line from the edge of the (imagined) disk to its center.

### What actually happened?
The (approximate) line extends past the disk's center.

The effect is more pronounced for smaller central angles and less pronounced for arcs starting/ending near 0° and 180°.

The following images show 1° arcs drawn using `pieslice` and a small red circle marking the center of the corresponding disk. The script creating them is given at the end.

These results are as expected (base angles 0°, 180°):
![test0](https://user-images.githubusercontent.com/53428415/115914773-aec05780-a472-11eb-84dc-988bb93892a7.png) ![test180](https://user-images.githubusercontent.com/53428415/115914903-d4e5f780-a472-11eb-992a-3bea5f7b4e74.png)

The following demonstrate the problem (base angles 15°, 45°, 90°, 270°):
![test15](https://user-images.githubusercontent.com/53428415/115914882-ce578000-a472-11eb-8b51-9529ca2b6425.png) ![test45](https://user-images.githubusercontent.com/53428415/115914786-b2ec7500-a472-11eb-9172-48cdbfd4cf0f.png) ![test90](https://user-images.githubusercontent.com/53428415/115914801-b5e76580-a472-11eb-9bf8-f23dd4d95f9a.png) ![test270](https://user-images.githubusercontent.com/53428415/115914912-da434200-a472-11eb-903d-56b2ff3dab0a.png)

### What are your OS, Python and Pillow versions?

* OS: archlinux
* Python: 3.9.3
* Pillow: 8.1.2

```python
# This code creates several files, only a few selected ones are shown above.
from PIL import Image, ImageDraw

r = 100 # radius in px
angle = 1 # in degrees
stepsize = 15

for angle_offset in range(0, 360+stepsize, stepsize):
    img = Image.new(mode="RGB", size=(2*r, 2*r), color=(255, 255, 255))

    # draw a sector
    draw = ImageDraw.Draw(img)
    draw.pieslice((0, 0, 2*r, 2*r), start=angle_offset, end=angle_offset+angle, fill=(0, 0, 0))

    # draw a small circle to mark the center
    draw.ellipse((r-1, r-1, r+1, r+1), fill=(255, 0, 0))

    img.save(f"test{angle_offset}.png")
```

**Comment by radarhere** [comment]
Testing, this worked as expected before #4523

@xtsm did you have any thoughts on this?

**Comment by xtsm** [comment]
https://github.com/xtsm/Pillow/blob/17d83d6a7c619e87fab84c59860989772fdcdb7d/src/libImaging/Draw.c#L1342
this function builds clipping semiplane tree for pies, the quick and dirty solution would be just add another semiplane that cuts off that spike

**Comment by radarhere** [comment]
Thanks for #5460. That is the 'quick and dirty solution' you mention. For the record, does that mean you're aware of a better solution?

**Comment by xtsm** [comment]
Nope. I just don't like the entire "clip ellipse down to an arc with semiplanes" stuff because I suspect there is a better algorithm for drawing arcs. Not sure which exactly though, maybe some generalized path drawing like in cairo, don't have much time to research rn.

If we stick with the current approach, this seems to be a legit solution.
