### ISSUE TITLE
Cannot pip install in Windows amd64 PyPy

### ISSUE THREAD

**Issue by Liujiarui-Mr** [python-pillow/Pillow#5435]
Pillow can not be installed in pypy 
my computer version: windows10
pypy version: 3.7

**Comment by radarhere** [comment]
How are you trying to install? What is the output when you do?

**Comment by Liujiarui-Mr** [comment]
> How are you trying to install? What is the output when you do?

Microsoft Windows [版本 10.0.18363.1500]
(c) 2019 Microsoft Corporation。保留所有权利。

C:\Users\Administrator.DESKTOP-ETEM65C>pypy3 -m pip install Pillow
Collecting Pillow
  Using cached Pillow-8.2.0.tar.gz (47.9 MB)
Building wheels for collected packages: Pillow
  Building wheel for Pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'D:\Pypy3\pypy3.7-v7.3.4-win64\pypy3.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-zkqj1khx\\pillow_3cf7cbd33eb14a09969441a9fe013663\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-zkqj1khx\\pillow_3cf7cbd33eb14a09969441a9fe013663\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-wheel-3_lrkvr5'
       cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\
  Complete output (174 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\PIL
  copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\features.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\FontFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\Image.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\TarIO.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\_binary.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\_util.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\_version.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\__init__.py -> build\lib.win-amd64-3.7\PIL
  copying src\PIL\__main__.py -> build\lib.win-amd64-3.7\PIL
  running egg_info
  writing src\Pillow.egg-info\PKG-INFO
  writing dependency_links to src\Pillow.egg-info\dependency_links.txt
  writing top-level names to src\Pillow.egg-info\top_level.txt
  adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
  reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.clang-format'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
  running build_ext


  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

  Traceback (most recent call last):
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\setup.py", line 1020, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW),
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\site-packages\setuptools\__init__.py", line 153, in setup
      return distutils.core.setup(**attrs)
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\core.py", line 148, in setup
      dist.run_commands()
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\site-packages\wheel\bdist_wheel.py", line 299, in run
      self.run_command('build')
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\command\build.py", line 135, in run
      self.run_command(cmd_name)
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 985, in run_command
      cmd_obj.run()
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\site-packages\setuptools\command\build_ext.py", line 79, in run
      _build_ext.run(self)
    File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\command\build_ext.py", line 343, in run
      self.build_extensions()
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\setup.py", line 788, in build_extensions
      raise RequiredDependencyException(f)
  RequiredDependencyException: zlib

  During handling of the above exception, another exception occurred:

  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\setup.py", line 1033, in <module>
      raise RequiredDependencyException(msg)
  RequiredDependencyException:

  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.

  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html


  ----------------------------------------
  ERROR: Failed building wheel for Pillow
  Running setup.py clean for Pillow
Failed to build Pillow
Installing collected packages: Pillow
    Running setup.py install for Pillow ... error
    ERROR: Command errored out with exit status 1:
     command: 'D:\Pypy3\pypy3.7-v7.3.4-win64\pypy3.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-zkqj1khx\\pillow_3cf7cbd33eb14a09969441a9fe013663\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-zkqj1khx\\pillow_3cf7cbd33eb14a09969441a9fe013663\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-lbgmtd9_\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Pypy3\pypy3.7-v7.3.4-win64\include\Pillow'
         cwd: C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\
    Complete output (176 lines):
    running install
    running build
    running build_py
    creating build
    creating build\lib.win-amd64-3.7
    creating build\lib.win-amd64-3.7\PIL
    copying src\PIL\BdfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\BlpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\BmpImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\BufrStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ContainerIO.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\CurImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\DcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\DdsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\EpsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ExifTags.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\features.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\FitsStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\FliImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\FontFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\FpxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\FtexImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\GbrImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\GdImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\GifImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\GimpGradientFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\GimpPaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\GribStubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\Hdf5StubImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\IcnsImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\IcoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\Image.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageChops.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageCms.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageColor.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageDraw.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageDraw2.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageEnhance.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageFilter.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageFont.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageGrab.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageMath.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageMode.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageMorph.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageOps.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImagePalette.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImagePath.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageQt.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageSequence.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageShow.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageStat.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageTk.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageTransform.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImageWin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\ImtImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\IptcImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\Jpeg2KImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\JpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\JpegPresets.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\McIdasImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\MicImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\MpegImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\MpoImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\MspImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PaletteFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PalmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PcdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PcfFontFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PcxImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PdfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PdfParser.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PixarImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PngImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PsdImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PSDraw.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\PyAccess.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\SgiImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\SpiderImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\SunImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\TarIO.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\TgaImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\TiffImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\TiffTags.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\WalImageFile.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\WebPImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\WmfImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\XbmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\XpmImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\XVThumbImagePlugin.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\_binary.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\_tkinter_finder.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\_util.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\_version.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\__init__.py -> build\lib.win-amd64-3.7\PIL
    copying src\PIL\__main__.py -> build\lib.win-amd64-3.7\PIL
    running egg_info
    writing src\Pillow.egg-info\PKG-INFO
    writing dependency_links to src\Pillow.egg-info\dependency_links.txt
    writing top-level names to src\Pillow.egg-info\top_level.txt
    adding license file 'LICENSE' (matched pattern 'LICEN[CS]E*')
    reading manifest file 'src\Pillow.egg-info\SOURCES.txt'
    reading manifest template 'MANIFEST.in'
    warning: no files found matching '*.c'
    warning: no files found matching '*.h'
    warning: no files found matching '*.sh'
    warning: no previously-included files found matching '.appveyor.yml'
    warning: no previously-included files found matching '.clang-format'
    warning: no previously-included files found matching '.coveragerc'
    warning: no previously-included files found matching '.editorconfig'
    warning: no previously-included files found matching '.readthedocs.yml'
    warning: no previously-included files found matching 'codecov.yml'
    warning: no previously-included files matching '.git*' found anywhere in distribution
    warning: no previously-included files matching '*.pyc' found anywhere in distribution
    warning: no previously-included files matching '*.so' found anywhere in distribution
    no previously-included directories found matching '.ci'
    writing manifest file 'src\Pillow.egg-info\SOURCES.txt'
    running build_ext


    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html

    Traceback (most recent call last):
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\setup.py", line 1020, in <module>
        zip_safe=not (debug_build() or PLATFORM_MINGW),
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\site-packages\setuptools\__init__.py", line 153, in setup
        return distutils.core.setup(**attrs)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\core.py", line 148, in setup
        dist.run_commands()
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\site-packages\setuptools\command\install.py", line 61, in run
        return orig.install.run(self)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\command\install.py", line 572, in run
        self.run_command('build')
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\command\build.py", line 135, in run
        self.run_command(cmd_name)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\dist.py", line 985, in run_command
        cmd_obj.run()
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\site-packages\setuptools\command\build_ext.py", line 79, in run
        _build_ext.run(self)
      File "D:\Pypy3\pypy3.7-v7.3.4-win64\lib-python\3\distutils\command\build_ext.py", line 343, in run
        self.build_extensions()
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\setup.py", line 788, in build_extensions
        raise RequiredDependencyException(f)
    RequiredDependencyException: zlib

    During handling of the above exception, another exception occurred:

    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-install-zkqj1khx\pillow_3cf7cbd33eb14a09969441a9fe013663\setup.py", line 1033, in <module>
        raise RequiredDependencyException(msg)
    RequiredDependencyException:

    The headers or library files could not be found for zlib,
    a required dependency when compiling Pillow from source.

    Please see the install instructions at:
       https://pillow.readthedocs.io/en/latest/installation.html


    ----------------------------------------
ERROR: Command errored out with exit status 1: 'D:\Pypy3\pypy3.7-v7.3.4-win64\pypy3.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-zkqj1khx\\pillow_3cf7cbd33eb14a09969441a9fe013663\\setup.py'"'"'; __file__='"'"'C:\\Users\\Public\\Documents\\Wondershare\\CreatorTemp\\pip-install-zkqj1khx\\pillow_3cf7cbd33eb14a09969441a9fe013663\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\Public\Documents\Wondershare\CreatorTemp\pip-record-lbgmtd9_\install-record.txt' --single-version-externally-managed --compile --install-headers 'D:\Pypy3\pypy3.7-v7.3.4-win64\include\Pillow' Check the logs for full command output.

C:\Users\Administrator.DESKTOP-ETEM65C>

**Comment by radarhere** [comment]
Thanks. So, looks like we don't currently supply a prepackaged wheel for Windows amd64 PyPy. Because of this, the install script is instead trying to compile from source, and finds that a dependency is missing - zlib.

https://pillow.readthedocs.io/en/latest/installation.html#building-on-windows
> If you wish to compile Pillow manually, you can use the build scripts in the winbuild directory used for CI testing and development. These scripts require Visual Studio 2017 or newer and NASM.

Please have a look at https://github.com/python-pillow/Pillow/blob/master/winbuild/build.rst and see if that is helpful.

**Comment by cgohlke** [comment]
See also https://foss.heptapod.net/pypy/pypy/-/issues/3443#note_158074. pypy3.7-v7.3.4-win64 should not be used to publish wheels.

**Comment by radarhere** [comment]
@Liujiarui-Mr did that answer your question? Or are you requesting that we supply a prepackaged wheel?

**Comment by realmax20x** [comment]
@radarhere I have the same issue and would like to request a prepackaged wheel for Windows amd64 PyPy. Much thanks.

**Comment by nulano** [comment]
> I have the same issue and would like to request a prepackaged wheel for Windows amd64 PyPy. Much thanks.

I would assume a wheel will eventually be released after the issue linked by cgohlke above is resolved (with the release of PyPy 7.3.5).

If you need an immediate solution, you should be able to download and unzip the `dist-master` artifact from the [latest `master` branch CI run](https://github.com/python-pillow/Pillow/actions/runs/795840379) and install the wheel with `pypy -m pip install Pillow-8.3.0.dev0-pp37-pypy37_pp73-win_amd64.whl`.

**Comment by radarhere** [comment]
Fyi, PyPy 7.3.5 has now been released.

**Comment by cgohlke** [comment]
Feel free to use or upload the wheel from https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow

**Comment by hugovk** [comment]
Good idea, it's `Pillow‑8.2.0‑pp37‑pypy37_pp73‑win_amd64.whl` right?

**Comment by cgohlke** [comment]
> it's Pillow‑8.2.0‑pp37‑pypy37_pp73‑win_amd64.whl right?

Yes.

**Comment by hugovk** [comment]
Uploaded to https://pypi.org/project/Pillow/8.2.0/#files: 

![image](https://user-images.githubusercontent.com/1324225/119517630-73ba8800-bd80-11eb-8209-7787383376f4.png)

Thanks everyone!
