### ISSUE TITLE
Can't save PNG to sys.stdout

### ISSUE THREAD

**Issue by shalomori123** [python-pillow/Pillow#5436]
### What did you do? 
Just tried to run simple code (ImageDraw)

### What actually happened? 
Exception looks very basic:
```  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/PIL/Image.py", line 2164, in save
    save_handler(self, fp, filename)
  File "/data/user/0/ru.iiec.pydroid3/files/aarch64-linux-android/lib/python3.8/site-packages/PIL/PngImagePlugin.py", line 1225, in _save
    fp.write(_MAGIC)
TypeError: write() argument must be str, not bytes
```

### What are your OS, Python and Pillow versions?

* OS: Android app, "pydroid3" (I don't have a computer now to check it)
* Python: 3.8.3
* Pillow: 8.1.2

```python
import sys
from PIL import Image, ImageDraw

# list of dots, in the following format: [x, y, x, y, x, y,...]
first = (146, 399, 163, 403, 170, 393, 169, 391, 166, 386, 170, 381, 170) #.... long tuple

with Image.open("draw image.jpg") as img:

    draw = ImageDraw.Draw(img)
    for i in range(len(first)//2 - 1):
    	draw.line(first[2*i : 2*i + 4])

    # write to stdout
    img.save(sys.stdout, "PNG")
```
Sorry if I didn't understand the concept... This is my first issue ever...

**Comment by radarhere** [comment]
Hi. You're free to say that Pillow should be able to work with your code, and that you'd like it to be fixed in the next Pillow release - but if you'd like an immediate solution, I'd suggest changing `sys.stdout` to `sys.stdout.buffer`.

```python
import sys
from PIL import Image, ImageDraw

# list of dots, in the following format: [x, y, x, y, x, y,...]
first = (146, 399, 163, 403, 170, 393, 169, 391, 166, 386, 170, 381, 170) #.... long tuple

with Image.open("draw image.jpg") as img:

    draw = ImageDraw.Draw(img)
    for i in range(len(first)//2 - 1):
    	draw.line(first[2*i : 2*i + 4])

    # write to stdout
    img.save(sys.stdout.buffer, "PNG")
```

This makes a difference because while `sys.stdout` requires strings, `sys.stdout.buffer` uses bytes.

```pycon
>>> import sys
>>> sys.stdout.mode
'w'
>>> sys.stdout.buffer.mode
'wb'
```

**Comment by radarhere** [comment]
I've found that we have an example in our documentation that is similar to this, so yes, this is a bug.

I've created PR #5437 to resolve it. The earliest that could become a part of a Pillow release is July 1.

**Comment by shalomori123** [comment]
> I've found that we have an example in our documentation that is similar to this, so yes, this is a bug.
> 
> I've created PR #5437 to resolve it. The earliest that could become a part of a Pillow release is July 1.

Yes, I copied the code from the documentation, and that's why I was surprised that it's not working. I assumed this is problem with my system...
