### ISSUE TITLE
TypeError when checking FreeType version

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5444]
After PR https://github.com/python-pillow/Pillow/pull/5098:

```
$ python
Python 3.9.4 (default, Apr 20 2021, 15:51:38) 
[GCC 10.2.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL.ImageFont
>>> PIL.ImageFont.FreeTypeFont()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.9/site-packages/PIL/ImageFont.py", line 173, in __init__
    freetype_version = parse_version(features.version_module("freetype2"))
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 57, in parse
    return Version(version)
  File "/usr/lib/python3.9/site-packages/packaging/version.py", line 296, in __init__
    match = self._regex.search(version)
TypeError: expected string or bytes-like object
```

The ImageFont module tries to be accepting of missing (optional) system dependencies for the _imagingft module. But then features.version_module() returns None, which cannot be parsed as a version, so this dumps a completely incomprehensible traceback rather than what most of the rest of this module does, which is:

https://github.com/python-pillow/Pillow/blob/56730906f2e0262cb2528287635c03c3fab128cf/src/PIL/ImageFont.py#L41-L50

_Originally posted by @eli-schwartz in https://github.com/python-pillow/Pillow/issues/5098#issuecomment-827071705_

**Comment by radarhere** [comment]
I've created PR #5445 to resolve this.

**Comment by mohammed70777** [comment]
ز

**Comment by GoatSara** [comment]
I had this problem a few days ago and first suspected packaging to be behind it which I reported and having a better error message there might also be a good thing
https://github.com/pypa/packaging/issues/434

**Comment by radarhere** [comment]
The plan is for the next version of Pillow to return "ImportError: The _imagingft C module is not installed" instead.
