### ISSUE TITLE
Mac M1 Pycharm use PIL 

### ISSUE THREAD

**Issue by Leuan12** [python-pillow/Pillow#5449]
* OS: M1 
* Python: 3.8.2
* Pillow: 
* 
![image](https://user-images.githubusercontent.com/30170943/116343195-92c40980-a816-11eb-9d5a-917afca33a5d.png)

**Comment by radarhere** [comment]
"[Python 3.8.7 is not yet fully supported on macOS 11 Big Sur.](https://www.python.org/downloads/release/python-387/)" (and you're actually using earlier than that) - so the official Python guideline would be to use Python 3.9 instead, as "[3.9.1 is the first version of Python to support macOS 11 Big Sur.](https://www.python.org/downloads/release/python-391/)"

Are you interested in upgrading to Python 3.9 and then trying again?

**Comment by radarhere** [comment]
If you do want to use Python 3.8, you could try downloading [Pillow-8.2.0-cp38-cp38-macosx_11_0_arm64.whl.zip](https://github.com/python-pillow/Pillow/files/6377137/Pillow-8.2.0-cp38-cp38-macosx_11_0_arm64.whl.zip), expanding the zip, moving into the directory and then running `python3 -m pip install Pillow-8.2.0-cp38-cp38-macosx_11_0_arm64.whl` - adjusting the command for your virtual environment.

**Comment by Leuan12** [comment]
It's worked out perfectly. Thank you very much
