### ISSUE TITLE
RPATH error when including 8.2.0 in a RPM build

### ISSUE THREAD

**Issue by louisconcentricsky** [python-pillow/Pillow#5463]
### What did you do?

I tried to include pillow in a python project that would be deployed via RPM

### What did you expect to happen?

The RPM would pass the `check-rpaths` part. (It passed with the 7.1.0 build)

### What actually happened?

The `check-paths` stage fails with the error:

> 16 7.944 + '[' x86_64 = noarch ']'
> 16 7.944 + QA_CHECK_RPATHS=1
> 16 7.944 + case "${QA_CHECK_RPATHS:-}" in
> 16 7.944 + /usr/lib/rpm/check-rpaths
> 16 9.366 *******************************************************************************
> 16 9.366 *
> 16 9.366 * WARNING: 'check-rpaths' detected a broken RPATH and will cause 'rpmbuild'
> 16 9.366 *          to fail. To ignore these errors, you can set the '$QA_RPATHS'
> 16 9.366 *          environment variable which is a bitmask allowing the values
> 16 9.366 *          below. The current value of QA_RPATHS is 0x0000.
> 16 9.366 *
> 16 9.366 *    0x0001 ... standard RPATHs (e.g. /usr/lib); such RPATHs are a minor
> 16 9.366 *               issue but are introducing redundant searchpaths without
> 16 9.366 *               providing a benefit. They can also cause errors in multilib
> 16 9.366 *               environments.
> 16 9.366 *    0x0002 ... invalid RPATHs; these are RPATHs which are neither absolute
> 16 9.366 *               nor relative filenames and can therefore be a SECURITY risk
> 16 9.366 *    0x0004 ... insecure RPATHs; these are relative RPATHs which are a
> 16 9.366 *               SECURITY risk
> 16 9.366 *    0x0008 ... the special '$ORIGIN' RPATHs are appearing after other
> 16 9.366 *               RPATHs; this is just a minor issue but usually unwanted
> 16 9.366 *    0x0010 ... the RPATH is empty; there is no reason for such RPATHs
> 16 9.366 *               and they cause unneeded work while loading libraries
> 16 9.366 *    0x0020 ... an RPATH references '..' of an absolute path; this will break
> 16 9.366 *               the functionality when the path before '..' is a symlink
> 16 9.366 *
> 16 9.366 *
> 16 9.366 * Examples:
> 16 9.366 * - to ignore standard and empty RPATHs, execute 'rpmbuild' like
> 16 9.366 *   $ QA_RPATHS=$(( 0x0001|0x0010 )) rpmbuild my-package.src.rpm
> 16 9.366 * - to check existing files, set $RPM_BUILD_ROOT and execute check-rpaths like
> 16 9.366 *   $ RPM_BUILD_ROOT=<top-dir> /usr/lib/rpm/check-rpaths
> 16 9.366 *
> 16 9.366 *******************************************************************************
> 16 9.366 ERROR   0002: file '/opt/site/env/lib/python3.6/site-packages/Pillow.libs/libfreetype-6ad068c6.so.6.17.4' contains an invalid rpath 'Pillow.libs' in [Pillow.libs]
> 16 9.375 ERROR   0002: file '/opt/site/env/lib/python3.6/site-packages/Pillow.libs/libtiff-d147fec3.so.5.6.0' contains an invalid rpath 'Pillow.libs' in [Pillow.libs]
> 16 9.391 ERROR   0002: file '/opt/site/env/lib/python3.6/site-packages/Pillow.libs/libharfbuzz-ba5e3cba.so.0.20800.0' contains an invalid rpath 'Pillow.libs' in [Pillow.libs]
> 16 9.403 ERROR   0002: file '/opt/site/env/lib/python3.6/site-packages/Pillow.libs/libwebpdemux-2a7a19d5.so.2.0.7' contains an invalid rpath 'Pillow.libs' in [Pillow.libs]
> 16 9.413 ERROR   0002: file '/opt/site/env/lib/python3.6/site-packages/Pillow.libs/libwebpmux-1d369df0.so.3.0.6' contains an invalid rpath 'Pillow.libs' in [Pillow.libs]

### What are your OS, Python and Pillow versions?

* OS: centos 8 in a docker image
* Python: 3.6
* Pillow: 8.2.0

Example project with README:

[pillow-test-rpm.zip](https://github.com/python-pillow/Pillow/files/6417854/pillow-test-rpm.zip)

**Comment by louisconcentricsky** [comment]
If you follow the instructions to disable the check for invalid rpaths (feels bad man), by using `QA_RPATHS=$(( 0x0002 ))` before the rpm build step, the resulting built image does work.

I have attached an updated zip with a updated docker file and rpm spec file (silly requires left in), that if you build it, run the container, then shell into it and run the following commands you will see it works.

[pillow-test-rpm-workaround.zip](https://github.com/python-pillow/Pillow/files/6418235/pillow-test-rpm-workaround.zip)

`rpm -i RPMS/x86_64/pillow-test-latest-0.1.x86_64.rpm`
`python3 /opt/site/code/pillow-test-main.py`

you should see the output: `Image Size: $(300, 300) / Image Mode: $RGBA`

**Comment by radarhere** [comment]
Thanks for the clear example. Testing, I find that 7.2.0 passes, but 8.0.0 does not.

Also, if it helps, modifying pillow-test.spec to append `--no-binary :all:` -
`%{install_dir}/env/bin/pip3 install -I -r %{src_dir}/code/requirements.txt --no-binary :all:`
also causes it to pass.

**Comment by louisconcentricsky** [comment]
Thanks for that workaround, of course I'll need to be more specific in my usage thus `--no-binary pillow`.

I'll update here if that sorts it for our whole env.

**Comment by louisconcentricsky** [comment]
@radarhere using the `no-binary` switch thus far seems to have worked well for us. Thank you very much for your help.
