### ISSUE TITLE
Values change with implicit conversion from mode F to L

### ISSUE THREAD

**Issue by meyerjo** [python-pillow/Pillow#5465]
Might be somewhat related to for instance #3011 

### What did you do?

```python
import numpy as np
from PIL import Image
tgt = np.ones(shape=(2, 2)) # float32
tgt_im = Image.fromarray(tgt)
tgt_im_np = np.asarray(tgt_im)
final_img = Image.fromarray(tgt_im_np, mode='L')

print(np.asarray(final_img))
```

### What did you expect to happen?
I assumed that the resulting matrix values still have the value of 1 but are implictly converted to 8-bit range.

### What actually happened?
```pycon
>>> print(np.asarray(final_img))
[[  0   0]
 [128  63]]
```
None of the resulting values keep the original value of 1  and (for me even more surprising) they change to different values at different places in the matrix.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.10
* Python: Python 3.8.8
* Pillow: 
```
pip list
Package    Version
---------- -------------------
certifi    2020.12.5
numpy      1.20.2
Pillow     8.2.0
pip        21.0.1
setuptools 52.0.0.post20210125
wheel      0.36.2
```

**Comment by radarhere** [comment]
Mode for fromarray is the ["Mode to use"](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray). I think this is the mode to use when reading the numpy data - if so, then it makes sense that the values change when it is told to interpret the input data dirrectly.

You might be interested in `.convert('L')` instead of `, mode='L'`,
```python
import numpy as np
from PIL import Image
tgt = np.ones(shape=(2, 2)) # float32
tgt_im = Image.fromarray(tgt)
tgt_im_np = np.asarray(tgt_im)
final_img = Image.fromarray(tgt_im_np).convert('L')

print(np.asarray(final_img))
```
gives
```
[[1 1]
 [1 1]]
```

**Comment by meyerjo** [comment]
Okay thanks for the workaround.

However, is it an expected behavior that random numbers appear in the matrix after doing the implicit conversion?
I assumed that the ``fromarray`` method either
- calls the conversion script, if the input is np.float32, or,
- raises an exception if the array.dtype does not match the specified mode.

**Comment by wiredfool** [comment]
I think that the mode to use parameter is a footgun. It’s not an implicit conversion, it’s a cast. In this case, you’re interpreting an array of 32 bit floats as 8 bit ints. 

I’m not sure if there is a good use case at all for the mode parameter here, as we need to be pretty sure what we’re getting from numpy to interpret the array correctly.

**Comment by dtoniolo** [comment]
I had a similar issue in #5723. So, if `mode` is given to `Image.fromarray()`, then what happens is:
1. the image is created interpreting the array in a predefined manner (e.g. `F` if the `dtype` is `np.float32` and the values all reside in the `[0, 1]`.
1. The image is then converted to the requested mode, changing the `dtype` and value range of the data array if necessary.

Is this correct?

**Comment by radarhere** [comment]
Some notes.

1. The initial post states that
```python
tgt = np.ones(shape=(2, 2)) # float32
```

This is not correct. `tgt.dtype` is "float64".

2.
```python
import numpy as np
from PIL import Image
tgt = np.ones(shape=(2, 2))
tgt_im = Image.fromarray(tgt)
tgt_im_np = np.asarray(tgt_im)
```
gives `tgt_im_np` of
```
[[1. 1.]
 [1. 1.]]
```

You might assume this is equal to `np.ones(shape=(2, 2))`, but `tgt.dtype` is "float64" and `tgt_im_np.dtype` is "float32". So the `dtype` changes, but I'm not convinced it's a problem that Pillow doesn't have a different mode for all of numpy's different modes.

**Comment by radarhere** [comment]
Closing. #2856 is also about this situation.

**Comment by radarhere** [comment]
I've created PR #5849 to clarify this in the documentation.
