### ISSUE TITLE
Possible Get Pixel Memory Leak

### ISSUE THREAD

**Issue by GameDungeon** [python-pillow/Pillow#5467]
### What did you do?
I'm creating a thread art generator

### What happened?
I saw there was a memory leak in my code. After running some debugging I got this output

![image](https://user-images.githubusercontent.com/60719255/117079078-b0a2da00-ad00-11eb-94d0-88598b3d91f3.png)

* OS: Windows 10
* Python: 3.9

```python
tracemalloc.start()

points = points_gen(img.size[0] / 2, nail_count)

base_point = 0

for _ in range(1000):
    #get avg lumin
    vals = dict()
    lines = (bresenham_line(*points[base_point], *point) for point in points)
    for x, line in enumerate(lines):
        values = [img.getpixel(value) for value in line]
        vals[sum(values)/len(values)] = x
    
    while True:
        min_val = vals[min(vals.keys())]
        max_num = len(vals)

        if min_val in range((base_point - min_dist)%max_num, (base_point + min_dist)%max_num):
            del vals[min(vals.keys())]
            continue

        line = min_val
        break

    draws = [*points[base_point], *points[line]] 
    out_draw.line(draws)
    for pixel in bresenham_line(*draws):
        img.putpixel(pixel, 255)

    base_point = line

    snapshot = tracemalloc.take_snapshot()
    top_stats = snapshot.statistics('lineno')

    #print("[ Top 10 ]")
    for stat in top_stats[:1]:
        print(stat)
```

**Comment by GameDungeon** [comment]
I made the code independent and ran that and the leak vanished. I wonder what tracemalloc picked up on?

```python
import tracemalloc
from PIL import Image

tracemalloc.start()
img = Image.open("test.jpg")

while 1:
    for q in range(100):
        for i in range(img.size[0]):
            for x in range(img.size[1]):
                values = img.getpixel((i, x))
        
    snapshot = tracemalloc.take_snapshot()
    top_stats = snapshot.statistics('lineno')
    print("[ Top ]")
    for stat in top_stats[:1]:
        print(stat)
```

**Comment by radarhere** [comment]
Are you saying that you're unable to reproduce the problem using just Pillow? You can only reproduce the leak in the context of your program?

Could we have more information about how you're detecting the memory leak? The command that you're running and the full text output would sound good.

**Comment by GameDungeon** [comment]
I am unable to reproduce the leak in the code snippet in the comment above. I left in my code that returns the output, and have an image of the output for my original code.

**Comment by GameDungeon** [comment]
I just reopened this issue as I noticed once making the image into a NumPy array the leak went away. Something strange is going on here.

**Comment by radarhere** [comment]
This is difficult to investigate if you're unable to provide a self-contained example that can demonstrate the leak.

What tool are you using to detect the leak? Valgrind?

**Comment by GameDungeon** [comment]
I used tracemalloc and you can see its output in the first image.

**Comment by wiredfool** [comment]
Without being able to reproduce it, You should probably go through and break the iterations of the loop into pieces and see where things are accumulating, rather than just checking at the end of the loop. You're looking for about 200k 28b items per iteration. That's a lot of allocations, of rather small objects. (28 bytes is approximately the space for an empty tuple). 

It's not clear that GC is ever being run here, so the mallocs may just be going into the python memory pool.

**Comment by GameDungeon** [comment]
Ok. As I worked around this by converting it to a numpy array, can't find the source, and have since moved on I'm going to close this issue.
