### ISSUE TITLE
Indefinite loop while counting frames in truncated tiff image

### ISSUE THREAD

**Issue by bauerji** [python-pillow/Pillow#5472]
### What did you do?
I tried to count number of frames in a tiff image. However, the image is corrupted.

### What did you expect to happen?
I expected some kind of exception (OSError).

### What actually happened?
Warning is logged
`.../lib/python3.9/site-packages/PIL/TiffImagePlugin.py:793: UserWarning: Truncated File Read`
and code is trapped inside indefinite for loop.

### What are your OS, Python and Pillow versions?

* OS: MacOS Big Sur
* Python: 3.9.4
* Pillow: 8.2.0

also occurs in docker container with
* OS: Ubuntu focal
* Python: 3.9.0
* Pillow: 8.2.0

```python
from pathlib import Path
from PIL import Image

# path to the attached image
file_path = Path("truncated_img.tiff")

Image.open(file_path).n_frames
```
[truncated_img.tiff.zip](https://github.com/python-pillow/Pillow/files/6440092/truncated_img.tiff.zip)

**Comment by radarhere** [comment]
Thanks for reporting. Your file is telling Pillow that the next frame is in the same position as the current frame, leading to an infinite loop.

I've created PR #5473 to resolve this - although my change doesn't raise an error like you are expecting, it just concludes that your image only has 1 frame.

**Comment by bauerji** [comment]
Thank you for quick solution. This seems to work when the last frame is corrupted. But when the image contains e.g. 4 frames and the third one is corrupted, `n_frames` returns `2` which is incorrect.

**Comment by radarhere** [comment]
Would you be able to attach that image?

**Comment by radarhere** [comment]
Just to be clear, my change doesn't affect the `UserWarning` that you're seeing for your image.

**Comment by radarhere** [comment]
It's not clear to me - are you still interested in `n_frames` throwing an error? I've been mulling it over.

**Comment by bauerji** [comment]
I am sorry for not being clear enough. I like the solution just with `UserWarning`. Throwing an error is not necessary.
