### ISSUE TITLE
Error importing _imaging on M1

### ISSUE THREAD

**Issue by frankwat** [python-pillow/Pillow#5478]
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```python
code goes here
```

**Comment by radarhere** [comment]
Hi. What version of Python are you using?

**Comment by frankwat** [comment]
Hi.  Thanks for your help.

I'm using Python 3.9.5 on two different Macs.  One is an older Mac and everything is working fine.  The other is an M1 MacBook Air and that is the one where I'm having difficulties.  I've done some more investigating and the problem seems to be with "secondary" or indirect imports if that makes sense.  It looks like Python finds the modules I installed but then when those modules try to import things that are there it doesn't find them.  I'm not sure that makes sense.  I had a lot of trouble figuring out what to change ands eventually added a path to .zprofile.

Thanks again for any help you can give me.

Frank

**Comment by frankwat** [comment]
Here is an standard example with the log.  This example runs fine on my older Mac but asbyou can see not on my M1 MacBook Air.  I'm using the same versions of everything on both machines.  I had to add a path to .zprofile on the M1 Mac to get this far.

from PIL import Image
#Open image using Image module
im = Image.open("images/cuba.jpg")
#Show actual Image
im.show()
#Show rotated Image
im = im.rotate(45)
im.show()




================================================================================
May 8, 2021 at 7:02:43 PM
~/Library/Mobile Documents/iCloud~com~barebones~bbedit/Documents/pillowTest.py
--------------------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/frankwattenberg/Library/Mobile Documents/iCloud~com~barebones~bbedit/Documents/pillowTest.py", line 1, in <module>
    from PIL import Image
  File "/Users/frankwattenberg/Library/Python/3.9/lib/python/site-packages/PIL/Image.py", line 109, in <module>
    from . import _imaging as core
ImportError: dlopen(/Users/frankwattenberg/Library/Python/3.9/lib/python/site-packages/PIL/_imaging.cpython-39-darwin.so, 2): no suitable image found.  Did find:
	/Users/frankwattenberg/Library/Python/3.9/lib/python/site-packages/PIL/_imaging.cpython-39-darwin.so: mach-o, but wrong architecture
	/Users/frankwattenberg/Library/Python/3.9/lib/python/site-packages/PIL/_imaging.cpython-39-darwin.so: mach-o, but wrong architecture

**Comment by radarhere** [comment]
What command are you running to install Pillow?

> I had to add a path to .zprofile on the M1 Mac to get this far.

What path did you add?

**Comment by radarhere** [comment]
To try and explain a bit, https://github.com/python-pillow/Pillow/blob/2a94728c0f342a9a6a44175faee9bbeb573297e4/src/PIL/Image.py#L109 is trying to import our compiled C code. There shouldn't be anything wrong with this line itself. It has worked for a long time, and we do have users on M1 machines.
However, when it is doing so on your machine, it finds that the code has been compiled not for an M1, but probably for Intel. This problem has been reported a few times, but the usual quick solution is for pip to download one of our prebuilt wheels - that should be happening automatically.

If you're just running `pip install Pillow`, I would suggest running `python3.9 -m pip install Pillow` instead. If that still doesn't work, I'd be interested in seeing the output when installing Pillow through pip.

I'm wondering if the path that you added to .zprofile is disguising the real problem.

**Comment by frankwat** [comment]
Many thanks.  Running python3.9 -m pip install Pillow solved the problem but I did have to uninstall first.
I really appreciate your help!!!

Now I'm running into problems with numpy.  There are lots of moments about numpy on M1 Macs but I haven't found a fix yet.  I'm using BBEdit and others seem to be using different environments.  

I know this is not in your wheelhouse and you've probably seen this before but here are few lines of what happens when I try to install numpy

Collecting numpy
  Using cached numpy-1.20.2.zip (7.8 MB)
  Installing build dependencies ... done
  Getting requirements to build wheel ... done
    Preparing wheel metadata ... done
Building wheels for collected packages: numpy
  Building wheel for numpy (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: /Library/Frameworks/Python.framework/Versions/3.9/bin/python3 /Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/pip/_vendor/pep517/in_process/_in_process.py build_wheel /var/folders/hl/fpw9m1z92cj31cvqj0yf5mrw0000gn/T/tmp1tz3w7x2

I'm trying to adapt some earlier work I've done using other languages for wide use in STEAM education and workshops.  I keep running into Python issues because of the proliferation of different Python environments. Everyone has one they use and like but the result is that Python is difficult for wide use.

Thanks again for your help and solving my Pillow problem.

**Comment by radarhere** [comment]
Well, there's an open issue for installing numpy on M1s over at https://github.com/numpy/numpy/issues/17784, so this doesn't seem surprising. If you scroll down, towards the end they mention that they have put together experimental wheels.

So I would try
```
python3.9 -m pip -install https://pypi.anaconda.org/scipy-wheels-nightly/simple/numpy/1.21.0.dev0+1518.ge3583316c/numpy-1.21.0.dev0+1518.ge3583316c-cp39-cp39-macosx_11_0_arm64.whl
```

**Comment by frankwat** [comment]
Magic!!!  Many, many thanks!!!

Frank
