### ISSUE TITLE
Colors don't match images used when saving GIF

### ISSUE THREAD

**Issue by julienguegan** [python-pillow/Pillow#5484]
Hello all, 

I have a weird behaviour when trying to save a .gif

### Save a gif
I want to generate a gif from a sequence of image. I first create images with differents colors and transparence. Then, I save them. To generate a .gif, I read this images with `Image.open()` and then append them in a list.

### Behaviour wanted
I want that the gif generated is exactly composed of the images I have generated/saved

### What actually happened
The gif generated look a bit like that the images used but colors are not the same, I can see a frame where a part is completely black where it should be white/gray.

image in gif : ![image](https://user-images.githubusercontent.com/45081450/117687332-fc013080-b1b7-11eb-9be9-b8474da72aa4.png)  image used : ![image](https://user-images.githubusercontent.com/45081450/117687371-06232f00-b1b8-11eb-8e78-b5a14a7db3f4.png)

I feel that it could be **because of the transparency channel** but I need to have transparency when I generate my images and also in my final .gif file ...

### Configuration

* OS:  Windows 10
* Python: 3.8.3
* Pillow: 8.1.2

### Minimal Example

```python
import numpy as np
import matplotlib.pyplot as plt
from PIL import Image
# generate images
alphas = np.linspace(0, 1, 10)
img = np.ones((200,200,4))
for i, a in enumerate(alphas):
    img[75:125,75:125,:] = a
    plt.imsave(str(i)+'.png', img)
# save as gif
images_gif = []
for i, a in enumerate(alphas):
    im = Image.open(str(i)+'.png')
    images_gif.append(im)
    plt.imshow(np.array(im))
    plt.show()
images_gif[0].save('file.gif', save_all=True, append_images=images_gif[1:], loop=0, duration=250)
```

**Comment by julienguegan** [comment]
Just saw that it seems to be related to some previous opened issues : (https://github.com/python-pillow/Pillow/issues/4644 and https://github.com/python-pillow/Pillow/issues/4640). The issue does not seem to be resolved but it might exist some workaround proposed in the previous opened issues ...

**Comment by lilisako** [comment]
@julienguegan Could I take this issue? This seems interesting.

**Comment by julienguegan** [comment]
@radarhere Attention, I have been using Pillow: 8.1.2 and I just saw that the new version 8.2 (April) has some update concerning .gif files. I am still trying to understand if it helps my problem ...

**Comment by julienguegan** [comment]
I confirm it helps !
