### ISSUE TITLE
Calling conventions of some Python foreign functions mismatch with their C implementations

### ISSUE THREAD

**Issue by Elaphurus** [python-pillow/Pillow#5487]
For example, Python foreign function `ImagingCore.isblock()` takes no arguments, as in its C implementation, arguments passed from the Python side will not be used:

https://github.com/python-pillow/Pillow/blob/d393cfb65ae7d99b4b8e1cb8c0ced4cf79d12835/src/_imaging.c#L2097-L2100

parameter `args` is not used in the function body.

However, its calling convention given by Python/C API when declaring the foreign function is `METH_VARARGS (0x0001)`, which should be `METH_NOARGS` instead in this case:

https://github.com/python-pillow/Pillow/blob/d393cfb65ae7d99b4b8e1cb8c0ced4cf79d12835/src/_imaging.c#L3460

This mismatch makes parameter of any type can be passed to this foreign function designed to be parameter free without getting a TypeError:

```Python
from PIL import Image
im = Image.open("./test.png")
ic = im.getdata()
ic.isblock('str', 1) # passing anything is legal because of the mismatch
```

The same mismatch can be found for foreign functions `ImagingCore.split()`, `ImagingCore.getbbox()`, `ImagingCore.chop_invert()`, `ImagingCore.getextrema()`, `ImagingCore.getpalettemode()`, `ImagingCore.getprojection()`.

We also found a mismatch in NumPy, which has been fixed in https://github.com/numpy/numpy/pull/18679. 

Please let me know if I miss something or get something wrong here.

**Comment by radarhere** [comment]
I've created #5488 to resolve this.
