### ISSUE TITLE
Grayscale conversion on large images (PNG/JPG) produce artifacts

### ISSUE THREAD

**Issue by DeusAres** [python-pillow/Pillow#5489]
### What did you do?
Trying to convert to grayscale a large image

### What did you expect to happen?
![image](https://user-images.githubusercontent.com/60852205/117809705-c9f6d980-b25e-11eb-95f7-4b8ebb00e2aa.png)

### What actually happened?
![image](https://user-images.githubusercontent.com/60852205/117809779-e09d3080-b25e-11eb-9af1-a3b30bc4659a.png)

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.9
* Pillow: 8.0.1

```python
from PIL import Image
image = Image.open("nasa.png").convert('L')
```
Tested with files exactly 5000x5000, when resized to even 1 pixel of difference, there are no artifacts

**Comment by DeusAres** [comment]
> Could you attach a copy of nasa.png, so that we can exactly replicate your situation?

![nasa](https://user-images.githubusercontent.com/60852205/117888347-37802580-b2b2-11eb-9181-c0a6a48782da.png)

**Comment by radarhere** [comment]
Hi. Even though the pixels around the logo are fully transparent (A is 0), that doesn't mean that R, G and B don't have values. Take a look at what happens if I convert your RGBA image to RGB (I'm just resizing to make my attachments here smaller)
```python
from PIL import Image
Image.open("nasa.png").convert("RGB").resize((500, 500))
```
![rgb](https://user-images.githubusercontent.com/3112309/117945587-d019b280-b351-11eb-9608-0e380e4c9d80.png)

So  I don't think this is a bug in Pillow's behaviour. To get the result you're after, I recommend this instead.
```python
from PIL import Image
im = Image.open("nasa.png")
out = Image.new("L", im.size)
out.paste(im.convert("L"), (0, 0), mask=im)
out.resize((500, 500)).save("result.png")
```
![result](https://user-images.githubusercontent.com/3112309/117947377-7b773700-b353-11eb-8c85-e81b55887bec.png)

I'm using the `mask` argument of [`paste`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste) to place the logo into a new image.
> If a mask is given, this method updates only the regions indicated by the mask. You can use either “1”, “L” or “RGBA” images (in the latter case, the alpha band is used as mask)

**Comment by DeusAres** [comment]
Very strange I didn't about that alpha could contain these values. As soon as possible I will check if the culprit of the strange values around the object is the pasting method using a mask of the red line layer (item, (x, y), item2). Because these objects come from Photoshop, I'm quite sure the alpha = 0 pixels were settled with 255,255,255 when deleted, but I will check into that as soon as possible

**Comment by radarhere** [comment]
@DeusAres any luck investigating?

**Comment by radarhere** [comment]
For the test, is that what you mean?

Running
```python
from PIL import Image
im = Image.open("Tests/images/hopper_45.png")
im.save("out.png")
```
over https://github.com/python-pillow/Pillow/blob/master/Tests/images/hopper_45.png, which has no iCCP chunk, and seeing that it gives visually identical output?
![out](https://user-images.githubusercontent.com/3112309/119087400-6e8cce80-ba4a-11eb-8c3f-23affa9644ac.png)

**Comment by DeusAres** [comment]
I was talking of testing on other PNGs (compressed, non compressed with photoshop, from the web, etc.), making any transparent pixel of a PNG image visible (not hopper case since it's every pixel is visible) to be sure that `Image.open()` is not messing up

With a simple test on PNGs on photoshop, I made this with a brush, 1000x1000px:

![image](https://user-images.githubusercontent.com/60852205/119129723-945ca800-ba37-11eb-9f50-020755861351.png)

Exported/Saved in the 4 ways possible (big one/ big one with interlacing/ medium one/ small one)
Replacing any alpha pixel == 0 value with 255 gives the same result 

![image](https://user-images.githubusercontent.com/60852205/119130137-1351e080-ba38-11eb-9e3e-f346e65a9735.png)

Runned the test with a png found on the internet

![minecraft-1816996_960_720](https://user-images.githubusercontent.com/60852205/119130291-501dd780-ba38-11eb-9c28-df472f739c56.png)

Which gave this result

![image](https://user-images.githubusercontent.com/60852205/119130448-8a877480-ba38-11eb-85dd-3a5f49d8e8aa.png)

I think it's clear it's not PIL fault, but something that has to do with Photoshop in specific

Well, hope this will be useful for future googler with the same issue. 

> So I don't think this is a bug in Pillow's behaviour. To get the result you're after, I recommend this instead.

    from PIL import Image
    im = Image.open("nasa.png")
    out = Image.new("L", im.size)
    out.paste(im.convert("L"), (0, 0), mask=im)
    #out.resize((500, 500)).save("result.png")

This should be the right solution without exploring why Photoshop does this. I can consider it case solved!

**Comment by radarhere** [comment]
Thanks for investigating further.
