### ISSUE TITLE
Exposing the OpenJPEG sgnd parameter when JPEG2000 encoding 

### ISSUE THREAD

**Issue by scaramallion** [python-pillow/Pillow#5502]
I'd like to be able to perform JPEG2K encoding of medical images using Pillow, particularly 16-bit signed greyscale (commonly used with CT and MR). Because of the limited supported `modes` in `Jpeg2KEncode.c` this is not currently possible as all input data is [treated as unsigned](https://github.com/python-pillow/Pillow/blob/eed337eacc58bb77b1d20c194507693ed4a40a80/src/libImaging/Jpeg2KEncode.c#L345).

Would it be acceptable if I provided a PR exposing the `sgnd` compression parameter to end users when saving? I ask because it feels more like a workaround than a true solution. Ideally I'd add support for `I` mode but OpenJPEG only supports a maximum of 31 bit samples.

**Comment by radarhere** [comment]
I've created PR #6709 to resolve this.
