### ISSUE TITLE
Cryptic error message if you draw in color on a grayscale image

### ISSUE THREAD

**Issue by shirriff** [python-pillow/Pillow#5503]
### What did you do?

Draw a color rectangle on a grayscale image.

### What did you expect to happen?

Should draw a rectangle, or at least give an error explaining that you can't draw in color on a grayscale image

### What actually happened?

The error message:

`TypeError: function takes exactly 1 argument (3 given)`

This error message is confusing since the `rect` function isn't being given 3 arguments; the arguments to `rect` match the documentation.

I ran into this problem and put an [explanation on stackoverflow](https://stackoverflow.com/questions/39080087/pillow-strange-behavior-using-draw-rectangle/42322058). This has received dozens of upvotes, so a lot of other people are hitting this problem. (This is why I think it's worth filing an issue on this.)

### What are your OS, Python and Pillow versions?

* OS:  macOS Big Sur 11.2.3
* Python: 3.9.4
* Pillow:  8.2.0

Code to reproduce the problem:
```python
from PIL import Image, ImageDraw
img = Image.new('L', (100, 100))
draw = ImageDraw.Draw(img)
draw.rectangle((0, 0, 10, 10), outline=(255, 0, 0))
```

**Comment by radarhere** [comment]
I've created PR #5504 to change the error message to "color must be int or single-element tuple".
