### ISSUE TITLE
`ImageDraw.textbbox` doesn't work with the default font

### ISSUE THREAD

**Issue by iguessthislldo** [python-pillow/Pillow#5506]
### What did you do?

I tried to use `ImageDraw.textbbox` without specifying a font.

### What did you expect to happen?

I expected `ImageDraw.textbbox` to work without specifying a font like `ImageDraw.text` does.

### What actually happened?

It throws an `AttributeError`:

```
File "<...>/PIL/ImageDraw.py", line 657, in textbbox
    bbox = font.getbbox(
AttributeError: 'ImageFont' object has no attribute 'getbbox'
```

It also does this when specifying `ImageFont.load_default()` manually as shown below. It does work when using another font, as shown below in the commented out line.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04
* Python: 3.6.9
* Pillow: 8.2.0

```python
from PIL import Image, ImageDraw, ImageFont
from io import BytesIO

size = (256, 256)

def thumbnail(orig, fmt, text=None):
    if isinstance(orig, bytes):
        orig = BytesIO(orig)
    image = Image.open(orig)
    image.thumbnail(size)
    if text is not None:
        draw = ImageDraw.Draw(image)
        # font = ImageFont.truetype("FreeSans", size=20)
        font = ImageFont.load_default()
        print(draw.textbbox((0, 0), text, font=font))
        draw.text((0, 0), text, font=font)
    result = BytesIO()
    image.save(result, fmt)
    return result.getvalue()
```

**Comment by nulano** [comment]
From the docs (emphasis added) https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textbbox:

> Returns bounding box (in pixels) of given text relative to given anchor when rendered in font with provided direction, features, and language. **Only supported for TrueType fonts.**

The default ImageDraw font is in PIL font format, not TrueType.

**Comment by iguessthislldo** [comment]
Alright, thanks I missed that it only worked for TrueType fonts. It would be nice if there was a check for that in `textbbox` so the mistake made was clear.

**Comment by radarhere** [comment]
I've created #5510 to add a specific error for that.
