### ISSUE TITLE
Old pypi homepage is SEO spam

### ISSUE THREAD

**Issue by za3k** [python-pillow/Pillow#5516]
Taking a look at https://pypi.org/project/Pillow/2.2.1/ (a very old version I realize, but also the first google result for me), the homepage it points at is https://python-imaging.github.io/, which is some kind of computer-generated SEO garbage. Is there any way you could get this pointed at something more reasonable, such as https://python-pillow.org/ ?

Alex clark said:
> Thanks! Any chance you could open a ticket for this? https://github.com/python-pillow/Pillow/issues I'll take a look in the meantime ... Thanks again.

**Comment by aclark4life** [comment]
@za3k True enough, thanks, that used to be our URL … @python-pillow/pillow-team I guess we should report to GitHub ? That'd be easier than fixing old PyPI releases (which may not be possible or easy)

**Comment by hugovk** [comment]
We renamed the org in 2014 in https://github.com/python-imaging, and it's not possible to fix old PyPI releases.

I don't the page at https://python-imaging.github.io/ is _complete_ SEO garbage, Dweep is a real Windows game, but it's a bit weird that the [mission statement](https://github.com/python-imaging/python-imaging.github.io/commit/36b71b3e3990b06e0fd0451a4ad40d2949c21724) bit got inserted in there, and the page definitely is inactive.

I've emailed the address associated with the commits and will contact GitHub support if I don't get a reply in, say, a couple of weeks? At least the mail hasn't bounced.

> Hi there!
>
> I'm from the Pillow project (https://github.com/python-pillow/Pillow).
> 
> Are you still using the "python-imaging" name on GitHub? I see the only repo https://github.com/python-imaging/python-imaging.github.io repo was created and last updated 4 years ago and looks inactive.
>
> It would be nice if we could use the https://github.com/python-imaging name as well, because the Pillow project used it in the past, and there's metadata in old releases still pointing to https://python-imaging.github.io/ which we cannot change, and it's a bit confusing for our users to find something unrelated.
>
> If you're no longer using it, would you be able to delete or rename it?
>
> Thank you!
>
> Hugo

**Comment by hugovk** [comment]
> Taking a look at [pypi.org/project/Pillow/2.2.1](https://pypi.org/project/Pillow/2.2.1/) (a very old version I realize, but also the first google result for me)...

I was going to ask what search terms turned up this old version, but then I tried "pillow python" and I can see four old versions underneath the main PyPI link. Strange Google is choosing those! Ah well.

![image](https://user-images.githubusercontent.com/1324225/120506775-e9e96b00-c3ce-11eb-8338-14ef9b37660c.png)

**Comment by aclark4life** [comment]
@hugovk Maybe our SEO was better on those releases 😄   Thanks for looking into it! Agree it's not urgent but may try to mention to @github at some point since, whatever it is, it probably doesn't belong at ``python-imaging``.

**Comment by radarhere** [comment]
I presume we haven't heard anything back yet. I'm going to tag @python-imaging here as another potential way of making contact.

**Comment by hugovk** [comment]
Correct, no reply to my earlier email to @python-imaging.

---

I've sent this to GitHub support:

> Hello,
> 
> I'm writing to ask if it's possible to claim an organisation name which may be name squatting, and at least is misleading, and also appears inactive.
> 
> I'm a member of the Pillow project, the popular Python imaging library with 33m downloads per month: https://github.com/python-pillow. Our project used to be at https://github.com/python-imaging but renamed in 2014.
> 
> Since then, someone else has signed up that org name and has put something up which is definitely not related to Python or imaging, and is a mix of an old Windows game review with a mission statement for a dead website shoved in the middle:
> 
> * https://python-imaging.github.io/
> * https://github.com/python-imaging/python-imaging.github.io
> 
> Further, it's not been updated in 4.5 years, and I don't see any other public activity in the org.
> 
> This causes us problems: we have metadata in old releases still pointing to python-imaging.github.io which we cannot change, and it's confusing for our users to find something unrelated.
> 
> A month ago I tried to make contact with the email address associated with the commits, but have received no reply (see https://github.com/python-pillow/Pillow/issues/5516).
> 
> Would it be possible for the org name to be released? We could then host useful, active and up-to-date relevant information at https://python-imaging.github.io/ pointing users to our newest documentation.
> 
> Thank you,
> 
> Hugo

**Comment by hugovk** [comment]
GitHub says no:

> IMPORTANT: Support Ticket Declined
> 
> Thank you for your request. It appears that you are asking about releasing a dormant or inactive username. We no longer review requests to release dormant or inactive usernames. You can view our Username Policy here:
> 
> https://docs.github.com/en/github/site-policy/github-username-policy
> 
> If you hold a trademark to this name and believe there is a clear case of confusion between the account and your trademark, please review our Trademark Policy:
> 
> https://docs.github.com/en/github/site-policy/github-trademark-policy
> 
> Thank you,
> The GitHub Team

**Comment by za3k** [comment]
Github said "dormant or inactive username", which it is not clear to me is what you are asking about. You should write back and ask if this might be prohibited under their name squatting policy, linked on the same page: 

```Name Squatting Policy
GitHub prohibits account name squatting, and account names may not be reserved or inactively held for future use. Accounts violating this name squatting policy may be removed or renamed without notice. Attempts to sell, buy, or solicit other forms of payment in exchange for account names are prohibited and may result in permanent account suspension.```

It's not clearly prohibited but I think it's worth asking again.

**Comment by hugovk** [comment]
Done:

> Hello,
> 
> Please could you check if this violates the name squatting policy?
> 
> > GitHub prohibits account name squatting, and account names may not be reserved or inactively held for future use. Accounts violating this name squatting policy may be removed or renamed without notice. Attempts to sell, buy, or solicit other forms of payment in exchange for account names are prohibited and may result in permanent account suspension.
> 
> https://docs.github.com/en/github/site-policy/github-username-policy#name-squatting-policy
> 
> Thank you,
> 
> Hugo
>

**Comment by hugovk** [comment]
GitHub support replied:

> We won't be able to release the account name to you. It's not possible to determine from public activity whether an account is being squatted on or not.

I don't think there's more we can do, but thanks for raising the issue!
