### ISSUE TITLE
Elaboration on the ImagingMemoryInstance struct

### ISSUE THREAD

**Issue by AD2605** [python-pillow/Pillow#5520]
Hello all, 

I am trying to understand the way PIL stores the image data once the image is loaded(I understand it is lazy loading). I Know the data is stored in the `ImagingMemoryInstance` struct. I final aim to try to run the algorithms on the GPU, therefore I want to convert the actual image data in a more GPU-friendly way(preferably without significant time complexity), maybe like a structure of shape [h, w, channels] or something of that sort. 
However, to do so I would want to understand this struct in question. 
So my question is, the double pointers that contain the data, (`**image`, `**image8`, and `**image32`), where exactly do these double pointers point to? From what I understand they all point to a struct(containing rgba values).

If that is so, can I convert it to an n-dimensional array?

I did post this question on StackOverflow but did not attract any answers (https://stackoverflow.com/questions/67646334/elaboration-on-the-imagingmemoryinstance-struct-in-pil)

TIA

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/blob/b25bdbc377dda29881046067b8b12fd26cb767fc/src/libImaging/Imaging.h#L93-L95

So `image32` is used if `pixelsize` is 4 - but RGBA isn't the only mode that has `pixelsize` 4 - there is PA, LA, La, F, I, RGB, BGR;32, RGBX, RGBA, RGBa, CMYK, YCbCr, LAB and HSV.

https://github.com/python-pillow/Pillow/blob/b25bdbc377dda29881046067b8b12fd26cb767fc/src/libImaging/Storage.c#L168-L171

https://github.com/python-pillow/Pillow/blob/b25bdbc377dda29881046067b8b12fd26cb767fc/src/libImaging/Storage.c#L77-L80

`pixelsize` 1 is 1, P and L.

Take a look at this as well.

https://github.com/python-pillow/Pillow/blob/b25bdbc377dda29881046067b8b12fd26cb767fc/src/libImaging/Storage.c#L211-L213

https://github.com/python-pillow/Pillow/blob/b25bdbc377dda29881046067b8b12fd26cb767fc/src/libImaging/Storage.c#L220-L228

**Comment by radarhere** [comment]
@AD2605 was that helpful?

**Comment by AD2605** [comment]
hello @radarhere, thanks a lot for your reply. Sorry I was not able to log in for long. 
It was indeed helpful, and I must say, the storage method PIL opts for is really complex(I wonder why they didn't go for a contiguous memory). 
Thanks a lot for your help

**Comment by wiredfool** [comment]
See also this: https://github.com/python-pillow/Pillow/issues/5049

For reasons, Pillow storage is: `ImageX-> row pointers -> row data`, where the row data is either 8 or 32 bit packed data. This is optimized for both handling pixel access (x,y) and bulk operations (reading the whole file at a time), but not doing things like picking out an individual channel.
