### ISSUE TITLE
ImageOps.exif_transpose removes format information

### ISSUE THREAD

**Issue by lswainemoore** [python-pillow/Pillow#5527]
### What did you do?

Used `ImageOps.exif_transpose` on a portrait-oriented image, and checked format of the initial image versus the returned one.

### What did you expect to happen?

The formats of the two images to both be `JPEG`.

### What actually happened?

The original image had format `JPEG`, the image returned by `ImageOps.exif_transpose` had format `None`.

### What are your OS, Python and Pillow versions?

* OS: macOS 11.3.1
* Python: 3.9.4
* Pillow: 8.2.0

```python
from PIL import Image, ImageOps
with Image.open('mona_lisa.jpg') as img:
    print(img.format)
    print(ImageOps.exif_transpose(img).format)
```
->
```
JPEG
None
```

Input image `mona_lisa.jpg`: 
![image](https://user-images.githubusercontent.com/5581503/121123531-64602380-c7f1-11eb-950a-92f3fc02aa35.png) ([src](https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/1200px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg))

**Comment by radarhere** [comment]
Hi. This is what happens when Pillow makes a copy of an image. See this simple example.

```python
from PIL import Image
im = Image.open("Tests/images/hopper.jpg")
print(im.format)  # JPEG
print(im.copy().format)  # None
```

While the original image was JPEG because you opened it from a JPEG image, once it is copied, it loses the connection to the file, and is just generic image data.

Does this behaviour present a problem for you in any way?

**Comment by lswainemoore** [comment]
Thanks for your patience--sounds like I have misunderstood the expected behavior.

I wouldn't say it poses an insurmountable problem (I can save the format before doing this), but I guess it does seem odd to me that there's not a way to apply the image's natural rotation without removing unrelated metadata. Are there other metadata fields that are lost after a copy?

**Comment by radarhere** [comment]
From the perspective of the code, it's not which excluding attributes, it's including them. So `mode`, `info` and `palette` are copied.

Specific attributes will vary between formats, but for the JPEG format, this means that `fp`, `tile`, `decoderconfig`, `app`, `applist`, `icclist`, `bits`, `layer`, `huffman_dc`, `huffman_ac`, `quantization` are not copied.

I've found a better explanation for this behaviour that I'd given [previously.](https://github.com/python-pillow/Pillow/issues/4571#issuecomment-617053589)
> Why is this? I can't argue for the original programmers, but here's my thinking.
>
> Having been cropped, I might argue that the image is no longer a good representation of what is in the file. The image data from the file has been loaded into Pillow. In your case, you could close im2 and Pillow can continue to use im3 without a problem. You could delete the original file even without causing an issue.
>
> A JPEG or a PNG or whatever is a file format. Pillow reads those file formats and interprets the image data from them. It doesn't store the entire file in memory, and it doesn't really make sense to call the internal Pillow collection of data a JPEG. To make an analogy, let's say that a JPEG is a hardback book. If we copy the story out of the book, the story isn't a hardback, it's just words. Pillow image data isn't a JPEG, it's just image data.
>
> If there is some specific functionality you think is lost by converting a JpegImageFile into a generic Image, let us know and perhaps we can help figure out another way to do it.

**Comment by lswainemoore** [comment]
Ha, if my searching had turned up that issue your quoting, I definitely would not have filed this issue! OP's use case is almost identical to mine, just with a different image alteration.

But thank you--I can appreciate now why this makes sense from an implementation perspective. I do wonder if there could be more documentation around this behavior--perhaps on the [copy method](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.copy) or at the top of the [ImageOps Module](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html) if it applies broadly to all of those methods? Just since I think the side effect we're discussing is a little unintuitive. But otherwise we can certainly close this "issue" and chalk it up to my misunderstanding.

**Comment by radarhere** [comment]
How about that the top of https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html? See #5532 for my suggestion - https://pillow--5532.org.readthedocs.build/en/5532/handbook/image-file-formats.html

**Comment by lswainemoore** [comment]
That seems reasonable! Candidly, I don't think I would've found that unless it was on the `exif_transpose` method itself, but that applies to both of my suggestions as well, and I don't think it's reasonable to put it on every method that uses `copy`. 

Anyway, thank you for your help! I've implemented my workaround, and all is resolved from my perspective.
