### ISSUE TITLE
Current Windows Build/Testing process

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#553]
What is the current best practices for building and testing Pillow on Windows?
- What compiler works with the precompiled official python releases?
- What versions of the dependencies -- the official tar/zipballs, or installerified versions, or something from cygwin?
- Does buildout or something similar work?
- Are there prebuild images (on azure or aws) that already have the appropriate version of VS installed (assuming that it's the correct compiler)?

@cgohlke?

**Comment by wiredfool** [comment]
I've got the beginnings of a Windows CI at https://ci.appveyor.com/project/wiredfool/pillow/build/2.9.pre.18 .  So far it's only one Python and not all the libraries but it is CI, on windows, and the tests are almost passing. This is based on my winbuild branch which is now merged up to current master. 

I think i'm going to clean up this first and then try to get all the other pythons  and dependencies to build so that we can get at least basic windows CI going as soon as possible.

**Comment by hugovk** [comment]
Great news!

**Comment by hugovk** [comment]
@wiredfool Is it possible to move the main Pillow builds to a python-pillow account, rather than on your own account?

The reason is free plans have only [one concurrent job](http://www.appveyor.com/pricing), which means there can be a bigger backlog for builds coming from both your repo and the main repo.

Two accounts = two build queues.

Here's how:
http://help.appveyor.com/discussions/questions/1154-appveyor-account-for-github-organizations

**Comment by wiredfool** [comment]
I'll take a look at that. Another build queue would be good.

**Comment by wiredfool** [comment]
https://ci.appveyor.com/project/Pythonpillow/pillow/history

**Comment by radarhere** [comment]
Remind me why 3.3 isn't activated in AppVeyor? If it was initially disabled for speed, that would have made perfect sense at the time, but the builds are much faster now, consistently outperforming TravisCI.

**Comment by hugovk** [comment]
I guess we just wanted to get the main ones working and merged.

AppVeyor accounts are free: how about just branching and giving it a shot?

**Comment by wiredfool** [comment]
Probably speed, and I was working on maximal coverage with minimal implementations.  Now that we're working, mostly, we should go towards more completeness.

**Comment by radarhere** [comment]
It passes - https://ci.appveyor.com/project/radarhere/pillow/build/3.0.pre.173 - and so I've created a PR.

**Comment by radarhere** [comment]
At the end of [an AppVeyor build](https://ci.appveyor.com/project/python-pillow/pillow/build/job/q5w7sd5cvgqjwm1w), it outputs

> Uploading artifact Pillow-6.1.0.dev0-cp37-cp37m-win32.whl (1,064,340 bytes)...100%
> Uploading artifact Pillow-6.1.0.dev0-py3.7-win32.egg (1,469,913 bytes)...100%
> Deploying using S3 provider
> Uploading artifact "Pillow-6.1.0.dev0-py3.7-win32.egg" (0 bytes) to S3 bucket "pillow-nightly" as "win/5171/Pillow-6.1.0.dev0-py3.7-win32.egg"...

Is the only thing stopping us from using these as our Windows releases the fact that we are missing some dependencies?

**Comment by wiredfool** [comment]
I think so, as long as we’re  covering all the windows python versions.  At the time this was done, we were covering a much smaller part of the matrix.

**Comment by nulano** [comment]
Just to link, #4084 and #4495 improve the situation quite a bit, with the former adding testing and wheel-building support for all optional libraries on GitHub Actions, and the latter making the build script portable and using it on AppVeyor.

**Comment by radarhere** [comment]
@nulano given that #4495 has [significantly improved](https://github.com/python-pillow/Pillow/pull/4495#pullrequestreview-395900016) compiling Pillow on Windows, do you think there's anything left to do here?
