### ISSUE TITLE
Specific font causing getsize_multiline to throw an error

### ISSUE THREAD

**Issue by TheElementalOfDestruction** [python-pillow/Pillow#5530]
### What did you do?
I loaded a font file (successfully, I might add) and ran the code `dictionary = {chr(x): font.getsize_multiline(chr(x)) for x in range(256)}` with a specific font.

### What did you expect to happen?
I ran the same code with the same font on windows and had no issues, so I expected to successfully get the size of the text.

### What actually happened?
```
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "<stdin>", line 1, in <dictcomp>
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 489, in getsize_multiline
    line_width, line_height = self.getsize(
  File "/usr/local/lib/python3.8/dist-packages/PIL/ImageFont.py", line 430, in getsize
    size, offset = self.font.getsize(text, "L", direction, features, language)
OSError: unknown freetype error
```
This is the traceback I got when recreating it in the terminal, but when doing so I found something interesting. When I ran the code a second time it suddenly succeeded and I have no idea why. I have a module that uses this code (the getsize_multiline calls are way too slow and I decided I would do a precalculation before hand and accept the slight inaccuracy in return for running something like 10 times faster) and I would prefer not to have to try to run the line twice each time.

This only seems to happen with this one font on this machine.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04.2 LTS (Works on Windows 10)
* Python: 3.8.5
* Pillow: 8.2.0

(Sorry if the title is bad)

**Comment by TheElementalOfDestruction** [comment]
Ah, So some more information is that the reason it worked on my Windows computer is because it was using an old version of pillow (5.4.1). Changing to the new version netted the same error. Tracking the issue back I can say it was introduced first in 6.2.0 (as 6.1.0 has no issues). If you need the font I can give it to you.

**Comment by radarhere** [comment]
A copy of the font would be helpful, thanks.

**Comment by TheElementalOfDestruction** [comment]
I've attached the font to this message.

[As I Lay Dying.zip](https://github.com/python-pillow/Pillow/files/6622147/As.I.Lay.Dying.zip)

**Comment by radarhere** [comment]
I can replicate the problem with Pillow master on my machine. `FT_Load_Glyph` is returning -1. I don't know why yet.

**Comment by TheElementalOfDestruction** [comment]
What does that error (I'm assuming that's an error) mean?

**Comment by radarhere** [comment]
I've asked the question over at https://gitlab.freedesktop.org/freetype/freetype/-/issues/1063

**Comment by radarhere** [comment]
Currently, there are two possible answers in the FreeType issue. Either it is
- `invalid offset (11040)`, meaning that the font is broken
or
- a bug in FreeType

**Comment by radarhere** [comment]
I don't imagine that the FreeType issue will end up suggesting any change for Pillow - but it's your call what you'd like to happen with this Pillow issue. We can leave it open if you want, or we can close it and you can just watch the FreeType issue.

If you'd like a workaround for your situation in the meantime, it seems to only happen for that sequence of characters, so I find that you could just open the font again in the middle and it works.
```python
from PIL import Image, ImageDraw, ImageFont
im = Image.new("RGB", (1, 1))
d = ImageDraw.Draw(im)

# Passes
font = ImageFont.truetype('As I Lay Dying.ttf')
dictionary = {chr(x): font.getsize_multiline(chr(x)) for x in range(128)}
font = ImageFont.truetype('As I Lay Dying.ttf')
dictionary.update({chr(x): font.getsize_multiline(chr(x)) for x in range(128, 256)})

# Fails
font = ImageFont.truetype('As I Lay Dying.ttf')
dictionary = {chr(x): font.getsize_multiline(chr(x)) for x in range(256)}
```

**Comment by TheElementalOfDestruction** [comment]
I'm watching the free type one as well, so I suppose we can close this issue. For now I found that trying it and then retrying it works consistently, so I have that as a work around but I'll see how yours fairs in my code. I noticed that in the issue with freetype the character where the error starts is actually different from the one I got (171) which is interesting.
