### ISSUE TITLE
Does ImageGrab on Windows release *all* DC handles/objects?

### ISSUE THREAD

**Issue by jwhendy** [python-pillow/Pillow#5536]
Greetings,

I was chasing down an issue on `pyautogui` and thought something was awry in their `pixel()` function (returns the rgb color of a pixel), however somewhat by accident I found out it's actually an interaction between `pixel()` and `screenshot()`. The latter uses `PIL.ImageGrab.grab()` and I'm wondering how to diagnose further.

Here is [the issue](https://github.com/asweigart/pyautogui/issues/579) at `pyautogui`. I replaced their screenshot function for windows (which uses `PIL`) with some direct win32 code I found [here](https://www.programmersought.com/article/49766989757/) and the issue went away.

The error stems from when `pyautogui` calls `windll.user32.ReleaseDC` ([here](https://github.com/asweigart/pyscreeze/blob/0446e87235e0079f591f0c49ece7d487dedc2f9a/pyscreeze/__init__.py#L112)). Given that it only happens with back and forth calls to `pixel()` ([here](https://github.com/asweigart/pyscreeze/blob/0446e87235e0079f591f0c49ece7d487dedc2f9a/pyscreeze/__init__.py#L571)) and screenshot (yours, [here](https://github.com/python-pillow/Pillow/blob/2be12dec2b231d31400f44bfa855966484997c16/display.c#L323)), I'm wondering if there is some handle/DC/object not being released by `grab()` which causes the issue?

Happy to test something out if you'd like and thanks for taking a look!

**Comment by jwhendy** [comment]
Thanks for taking a look. Indeed, I saw those as well. I also don't think it's the error case. I'm trying to troubleshoot:
- `pyautogui.pixel()` works on it's own
- `pyautogui.pixel()` and `pyautogui.screenshot()` (calling `ImageGrab.grab()` results in an error with `windll.user32.releaseDC()`
- re-writing the `grab()` function like [this](https://www.programmersought.com/article/49766989757/) also doesn't cause the error

I am mediocre at python and far worse at windows internals. Since I'd tracked this to some interaction between the two, and the error seems related to how one interacts with these DC functions, I was hoping someone with more expertise could point me in the next direction.

I also raise it here as perhaps it's helpful to know if there is, indeed, some type of interaction between these windows objects. For example, perhaps the issue is in mixing `getDC` and `releaseDC` (in `pyautogui`) vs. `createDC` and `deleteDC` (used here). A complete and utter guess... just have no idea how to pinpoint the issue. If it *was* something like these interactions, that would be helpful for others to know and avoid.

Thanks again.

**Comment by jwhendy** [comment]
Sorry for the sort of dual posting (issue on `pyscreeze` as well as here), but I updated [my issue there](https://github.com/asweigart/pyautogui/issues/579#issuecomment-859266289) with some compatibility testing between various screenshot methods vs. various pixel color methods.

Maybe something stands out in my table of results?

**Comment by radarhere** [comment]
Hi. From your table, using Pillow never results in consistent failures. So the next best thing is the intermittent ones.

Could you put together two self-contained code examples - one with win32py and `pyautogui.pixel()` (which you say passes consistently), and one with `ImageGrab.grab()` with `pyautogui.pixel()` (which you say intermittently fails)?

**Comment by nulano** [comment]
In the notebook you linked from the other issue, the `__win32_openDC` method is wrong: it raises an error on success. From [Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-releasedc#return-value), a non-1 return value is a failure, but your code raises an error for a non-0 return value (the opposite).

After fixing that issue, I get no errors in 100 iterations of either `pixel(5,5),ImageGrab.grab()` nor `pyautogui.pixel(5,5),ImageGrab.grab()`.

**Comment by jwhendy** [comment]
@radarhere hanks for the suggestion. I'm in linux at the moment but will do this later today and post two py files.

@nulano : Good catch, and my apologies. The original code is [here](https://github.com/asweigart/pyscreeze/blob/0446e87235e0079f591f0c49ece7d487dedc2f9a/pyscreeze/__init__.py#L112). I adjusted that code so I could continue running my test loops and see the value of `hDC` instead of stopping, hastily just throwing my print into an `if` but leaving the original in `else` without thinking much about it. I missed putting this function back to the default structure when I made the notebook.
```
### used in pyautogui (from pyscreeze)
        finally:
            if windll.user32.ReleaseDC(hWnd, hDC) == 0:
                raise WindowsError("windll.user32.ReleaseDC failed : return 0")

### my adjusted version for troubleshooting in the notebook
        finally:
            if windll.user32.ReleaseDC(hWnd, hDC) == 0:
                print('error: ', hDC)
            else:
                raise WindowsError("windll.user32.ReleaseDC failed : return 0")
```

I also now realize this is probably why I had intermittent failures for my local `pixel()` reproduction! In theory the behavior should match `pyautogui.pixel()` exactly. I'll fix this and report back.

**Comment by jwhendy** [comment]
@nulano I reverted my modification and now both `pyautogui.pixel()` and my locally reproduced `pixel()` function produce the same results with all screenshot function pairings. Thanks for catching that.

> After fixing that issue, I get no errors in 100 iterations of either pixel(5,5),ImageGrab.grab() nor pyautogui.pixel(5,5),ImageGrab.grab().

It might be about the order? I'm doing the screenshot first and continue to regularly fail with `grab() + pixel()` or `grab() + pyautogui.pixel()`. Would you kindly reproduce with the attached test file (`grab-pixel.py`)?

@radarhere here's some test scripts. They all screenshot, followed by finding the pixel color with `pyautogui.pixel()`

- `grab-pixel.py`: uses `PIL.ImageGrab.grab()` to screenshot
- `pywin32-pixel.py`: uses [this](https://www.programmersought.com/article/49766989757/) screenshot method
- `pywin32b-pixel.py`: uses [this](https://stackoverflow.com/questions/3586046/fastest-way-to-take-a-screenshot-with-python-on-windows/3586280#3586280) screenshot method
- `pyautogui-both.py`: uses `pyautogui.screenshot()` (which is `ImageGrab.grab()` based)

I bumped to 1000 iterations and... the results are not as straightforward as I previously thought. I can get failures followed by 1000 passes with `pywin32`, but also several runs of 1000 passes and then failures. I am *never* seeing more than a handful of passes with `ImageGrab.grab()`, however. 

Here's some example output to illustrate what happens for me on successive runs:
```
### many runs of pywin32 variant, eventually with all 1000 passing
>python pywin32-pixel.py
failed after 5 runs

>python pywin32-pixel.py
failed after 3 runs

>python pywin32-pixel.py
failed after 0 runs

>python pywin32-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
all 1000 runs passed

### switching to ImageGrab.grab(), with none passing
>python grab-pixel.py
failed after 2 runs

>python grab-pixel.py
failed after 0 runs

>python grab-pixel.py
failed after 1 runs

>python grab-pixel.py
failed after 0 runs

>python grab-pixel.py
failed after 3 runs

>python grab-pixel.py
failed after 1 runs

>python grab-pixel.py
failed after 0 runs

### back to pywin32, eventually passing, then failing again
>python pywin32-pixel.py
failed after 90 runs

>python pywin32-pixel.py
failed after 6 runs

>python pywin32-pixel.py
failed after 0 runs

>python pywin32-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
failed after 816 runs

>python pywin32-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
failed after 50 runs
```

For a possible breakthrough, I was thinking about this fail-then-pass behavior, and recalled that [the `GetDC` documentation](https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-getdc) states:

> Note that the handle to the DC can only be used by a single thread at any one time. [...] ReleaseDC must be called from the same thread that called GetDC.

Each of these approaches is using something different to interact with the windows display:
- `pyscreeze` [uses](https://github.com/asweigart/pyscreeze/blob/master/pyscreeze/__init__.py#L97) `cytpes.windll`
- `pillow` [is using](https://github.com/python-pillow/Pillow/blob/a9b0adc57fa422ad31891a65a5c3a1465a5c5fd2/src/display.c#L318) a sort of C wrapper approach (I think?)
- these `pywin32` methods are using `win32gui`

Is there any chance for a mismatch between these DC handle requests? As a complete guess, I made one small change to `pyscreeze`, replacing `ctypes.windll.user32.ReleaseDC()` with `win32gui.ReleaseDC()` and I get 100% passing with `pyautogui.screenshot()` followed by `pyautogui.pixel()`.

Try `pyautogui-both.py` with the current pypi version of `pyscreeze` and then with [my fork](https://github.com/jwhendy/pyscreeze/tree/pywin32) (`pywin32` branch). I'm finding all scripts will go the 1000 iterations with this change.
```
>python grab-pixel.py
all 1000 runs passed

>python pyautogui-both.py
all 1000 runs passed

>python pywin32b-pixel.py
all 1000 runs passed

>python pywin32-pixel.py
all 1000 runs passed
```

If someone here familiar with win32 intricacies could confirm this seems like a possible cause, I can propose a PR at `pyscreeze`. I'm hesitant to base one on my utter and complete guess... though it's working. It'd just be nice to understand *why* this removes the issue!

[grab-pixel.py.txt](https://github.com/python-pillow/Pillow/files/6642886/grab-pixel.py.txt)
[pywin32-pixel.py.txt](https://github.com/python-pillow/Pillow/files/6642887/pywin32-pixel.py.txt)
[pywin32b-pixel.py.txt](https://github.com/python-pillow/Pillow/files/6642888/pywin32b-pixel.py.txt)
[pyautogui-both.py.txt](https://github.com/python-pillow/Pillow/files/6642889/pyautogui-both.py.txt)

**Comment by radarhere** [comment]
I half expect you've already seen this - when I test, it only fails when `hDC` is negative. Looking through the progression of the loops, `hDC` increases to a certain point, and then switches to a negative value. So an overflow issue.

I'm not a Windows expert by any means, but I would guess that the output of `GetDC` keeps increasing because Pillow is creating new DCs through `CreateDC`.

The `win32gui` version of `ReleaseDC` just doesn't seem to mind interpreting the negative values.

Also - `ctypes.windll.user32.ReleaseDC` is handling the negative values okay on 32-bit, just not 64-bit.

**Comment by nulano** [comment]
> Also - ctypes.windll.user32.ReleaseDC is handling the negative values okay on 32-bit, just not 64-bit.

Ah, that reminds me of something I have seen before.

Testing just the `ctypes.windll.user32.GetDC` and `ctypes.windll.user32.ReleaseDC` functions, I can see that it fails for negative values on Python 3.9b5 x64, but not on Python 3.7.6 x64 (arbitrary versions I have installed). However, the following works fine on both:

```python
import ctypes

GetDC = ctypes.windll.user32.GetDC
ReleaseDC = ctypes.windll.user32.ReleaseDC

GetDC.argtypes = [ctypes.c_ssize_t]
GetDC.restype = ctypes.c_ssize_t
ReleaseDC.argtypes = [ctypes.c_ssize_t, ctypes.c_ssize_t]
ReleaseDC.restype = ctypes.c_int

hdc = GetDC(0)
print(hdc, hex(hdc))
assert ReleaseDC(0, hdc)
```

I haven't checked the docs or source, but I suspect that the default argtype/restype are `c_int` which means that random garbage is passed in the top 32-bits of the call to `ReleaseDC` and it just so happens that on Python 3.7.6 this always produces a valid value (i.e. the handle is zero-extended).

**Comment by radarhere** [comment]
Thanks! I find that setting the ReleaseDC argtypes is the minimal change required to fix the problem.

So [setting up a test case using pyscreeze master on our CIs](https://github.com/radarhere/Pillow/commit/ee9e00212665857622e5b300449312e06b6eb913), it [fails](https://github.com/radarhere/Pillow/runs/2816046041?check_suite_focus=true#step:6:22). Then [adding that change](https://github.com/radarhere/pyscreeze/commit/78764626049de0cbe0032b21359d4d28ac698956) in a pyscreeze fork, and [using that fork](https://github.com/radarhere/Pillow/commit/3032af00ed5f561b8c74677510a19e6ed1e05819), it [finishes all runs](https://github.com/radarhere/Pillow/runs/2816047488?check_suite_focus=true#step:6:22).

@jwhendy I imagine that pyscreeze might be reluctant to add in a new Python module, so this alternative fix is simpler. Is that all enough for you to take it from here?

**Comment by jwhendy** [comment]
@radarhere indeed, I'd noticed the negative value occurrence as well when printing the return to look for patterns, but wasn't sure what to do with it. I wondered if negative was just another symptom of failure.

Thanks for the awesome work/insights, @nulano ! Feels good to have made some kind of breakthrough vs. this bug that appears to have plagued many `pyautogui`/`pyscreeze` users. If you google these `windll` errors, you find more hits for `pyautogui` issues than for people actually trying to uses these libs directly!

@radarhere indeed, I think I'll just link to your fork in my issue. Don't supposed you'd want to submit the PR to `pyscreeze` since you already forked/implemented, and I'll link to your PR form my `pyautogui` issue? Otherwise, I can take care of it as well.

Thanks again, really appreciate it!

**Comment by radarhere** [comment]
pyscreeze hasn't had a commit in almost a year and a half, so it sounds like it might take a while for such a PR to be accepted. I'd rather you take care of it.

**Comment by jwhendy** [comment]
Not a problem, I'll submit @radarhere . Thanks again everyone for the assistance in tracking this down!
