### ISSUE TITLE
Seeking to frame of GIF with transparency shows first frame in transparent areas

### ISSUE THREAD

**Issue by mdzirbel** [python-pillow/Pillow#5538]
When using seek() to get a specific frame of a GIF with transparency, the first frame shows up in the transparent sections of the requested frame

This works correctly in Pillow version 7.2

Input GIF: 
![blue_portal](https://user-images.githubusercontent.com/16024607/121721635-77554b00-cab2-11eb-9206-6d6f6eaef177.gif)

Expected third frame: 
![good_portal](https://user-images.githubusercontent.com/16024607/121727300-b89d2900-cab9-11eb-93b7-fdccbf773892.png)

Third frame given:
![bad_portal](https://user-images.githubusercontent.com/16024607/121721924-cb602f80-cab2-11eb-9188-c229495d5887.png)

```python
from PIL import Image
gif = Image.open("Images/blue_portal.gif")
gif.seek(2)
gif.show()
```

* OS: Microsoft Windows 10 Home, 10.0.19041 Build 19041
* Python:  3.8, 3.95
* Pillow:  8.20

**Comment by cgohlke** [comment]
All frames (including the first) specify the "restore to previous" disposal mode, which means that all frames should be rendered on the background/empty canvas, not on the first frame.

**Comment by radarhere** [comment]
Hi. Testing with master, I find this situation works as you expect. It started working after #5391.

So once Pillow 8.3.0 is released, due out on July 1, this should be fixed for you. If you would like this to work before then, you are free to compile from our master branch.

**Comment by radarhere** [comment]
As evidence, here's the image created by master with your code.
![out](https://user-images.githubusercontent.com/3112309/121832313-20977d80-cd0d-11eb-81bb-b1c0963c1408.png)

**Comment by mdzirbel** [comment]
Great, thanks! I switched to 7.2 for now, but will head over to 8.3 when it releases
