### ISSUE TITLE
Use libimagequant for palette + alpha quantization

### ISSUE THREAD

**Issue by pornel** [python-pillow/Pillow#554]
Octtree seems to be the only method in Pillow that supports palette with alpha:

```python
Image.open("in.png").convert("RGBA").quantize(method=2).save("out.png")
```

However, the result is heavily posterized:

![out](https://f.cloud.github.com/assets/72159/2446741/c0aad3c0-ae8a-11e3-967c-d85b7753d3d8.png)

It would be great if you could [use pngquant's algorithm instead](http://pngquant.org/lib/) (it's available as an embeddable BSD-licensed C library):

![in-or8](https://f.cloud.github.com/assets/72159/2446746/d6e221de-ae8a-11e3-830a-8ee2ef0c71a7.png)

Both images are 256-color without dithering, but pngquant doesn't throw away any bits of precision. ([source image](https://f.cloud.github.com/assets/72159/2446751/f788ab06-ae8a-11e3-9501-c52e65b77421.png))

**Comment by rr-** [comment]
I'm interested in this as well. I am willing to work on this, but I'm not sure where to begin with pngquant integration. For example, there seems to be no `install` target in libpngquant's `Makefile`, so I guess integrating it won't be as simple as doing `_find_include_file` inside `setup.py`?

**Comment by wiredfool** [comment]
No, it's not going to be that simple. It's going to take integrating at the C level, likely in `_imaging.c` or one of the quantize c files.

**Comment by rr-** [comment]
Clarification: I referred to wiring the library in terms of integrating it with the build process etc., rather than which C files to modify - in the latter case, I think I've got rough idea what to do (i.e. to add a new `method` inside `ImagingQuantize` function within `Quant.c`).

**Comment by wiredfool** [comment]
Ah, then you'd need to know what library and header files are necessary, looks like `libimagequant.h` and `libimagequant` as a shared library. You'd need to check for those files using `_find_include_file` and `_find_library_file`. Then add a build flag and you're good to go. 

Looking at the windows side through, it's probably not going to be usable on anything but python 3.5, due to the compiler limitations there. That's ok by me, as this is an enhancement.

**Comment by rr-** [comment]
Yep, that's what I'd initially think too, but apparently libpngquant doesn't offer installing (e.g. it has no `make install` target, and installing `pngquant` doesn't install its developer headers). It's not available even on AUR. So users will need to go out of their way to use it by manually tampering with environment variables to make it visible for Pillow's `setup.py`, which means the user base is going to be microscopic. Is there anything we can do to make pngquant more readily available?

**Comment by pornel** [comment]
There's `make -C lib shared` that produces `libimagequant.so.0` on Linux. I think Fedora uses it (https://www.rpmfind.net/linux/rpm2html/search.php?query=libimagequant.so.0)

**Comment by pornel** [comment]
BTW: since opening that issue I've changed my approach to distributing the library. Versions up to 2.4 are on a BSD license, but for later versions I've decided to use GPL. It may complicate bundling for you — sorry.

**Comment by wiredfool** [comment]
Looks like it's packaged on fedora, Debian (Jessie), and Ubuntu (trusty), which is a pretty reasonable cross section of big distros.

**Comment by wiredfool** [comment]
We wouldn't be able to distribute it as GPLv3, ruling out windows and directly embedding it.  I don't know if the licenses are strictly compatible, but I'm not a license lawyer.
