### ISSUE TITLE
ImageFont can't draw 32 bit unicode literal 

### ISSUE THREAD

**Issue by MPW1412** [python-pillow/Pillow#5545]
Hello,

### What did you do?

I'm trying to render a 32bit unicode literal with ImageFont.

### What did you expect to happen?

Draw direction arrow facing north: 🡱

### What actually happened?
![grafik](https://user-images.githubusercontent.com/1448950/122303390-bf85ca80-cf03-11eb-963c-c7e649928eda.png)

* OS: Ubuntu 20.04
* Python: 3.8.5
* Pillow: pillow-8.2.0

```python
from PIL import Image, ImageFont, ImageDraw
img = Image.new(str(1), (500, 500), color=1)
draw = ImageDraw.Draw(img)
fontObj = ImageFont.truetype('/usr/share/fonts/truetype/freefont/FreeMono.ttf', 150, encoding = 'utf-8')
draw.text((round(x*0.07), round(0.4*y)), u'\U0001f871, font = fontObj)

```

**Comment by nulano** [comment]
I get the same result using MS Word. Opening the font with [fontdrop.info](https://fontdrop.info) also doesn't show the arrow symbol to be present, the U00010323 symbol is the last I can see. So I'm pretty sure the font doesn't contain this symbol (at least not the version in Pillow's test directory).

**Comment by MPW1412** [comment]
Oh thanks, for the explanation! I thought there should have been some fallback as other, lower unicode literals work. But it seems that is not the case. I will search for a font that supports the desired literal.

Best! Matthias

**Comment by MPW1412** [comment]
e. g. /usr/share/fonts/truetype/noto/NotoSansSymbols2-Regular.ttf supports it on Ubuntu.

**Comment by nulano** [comment]
> Oh thanks, for the explanation! I thought there should have been some fallback as other, lower unicode literals work. But it seems that is not the case. I will search for a font that supports the desired literal.
> 
> Best! Matthias

The question mark you get with FreeMono is its "missing" character, used as a substitute for charatcers

**Comment by nulano** [comment]
> Oh thanks, for the explanation! I thought there should have been some fallback as other, lower unicode literals work. But it seems that is not the case. I will search for a font that supports the desired literal.
> 
> Best! Matthias

The question mark you get with FreeMono is its "missing" character, used as a substitute for characters not present in the font, so in a way that is the fallback. Most fonts have such a character. Some applications also support using a fallback font for missing characters, in particular web browsers, but Pillow does not support this yet, see #4808.
