### ISSUE TITLE
When pasting a gif on top of a png it raises an error

### ISSUE THREAD

**Issue by Phant0m-123** [python-pillow/Pillow#5550]
error is : AttributeError: 'function' object has no attribute 'copy'

```python
frames = [f.copy for f in ImageSequence.Iterator(pfp)]

for i, frame in enumerate(frames):
	fr = frame.copy() #error here
	blyat.paste(fr (21,21))
	frames.append(blyat.copy())
	frames[i] = frame
frames[0].save("aa.gif", save_all=True, append_images=frames[1:], optimize=False, delay=0, loop=0, fps = 1/24)
```

**Comment by radarhere** [comment]
Try changing your first line from
```python
frames = [f.copy for f in ImageSequence.Iterator(pfp)]
```
to
```python
frames = [f.copy() for f in ImageSequence.Iterator(pfp)]
```
adding brackets.

**Comment by Phant0m-123** [comment]
oh i missed the brackets lmao

**Comment by Phant0m-123** [comment]
Now it crashes my pc what do i do

**Comment by radarhere** [comment]
If there is an error when it crashes, please provide it.

If there isn't an error, please provide a self-contained example - a script that we can run from start to finish, with any input images, and let us know what your operating system is and which version of Pillow you have installed.

**Comment by Phant0m-123** [comment]
i fixed the crash but now the animation is not working
``python
frames = [f.copy() for f in ImageSequence.Iterator(pfp)]


        for i, frame in enumerate(frames):
            frame = frame.copy()
            frame = frame.resize((205,205))
            blyat.paste(frame, (21,21))
            frames[i] = blyat
        frames[0].save("aa.gif", save_all=True, append_images=frames[1:], delay=0.1, loop=0)
```
new code

**Comment by radarhere** [comment]
The example you're providing is not self-contained. I don't know what `pfp` or `blyat` are, so I can't see the problem you're describing.

**Comment by Phant0m-123** [comment]
```python
import discord
from discord.ext import commands
from PIL import Image, ImageSequence
from io import BytesIO
import requests

bot = commands.Bot(command_prefix=">")

@bot.command(name = "test", aliases = ["r"])
async def img_test(ctx, user: discord.Member = None):
    if user is not None:
        blyat = Image.open("blyat.png")
        asset = user.avatar_url_as(format="gif", size=1024)
        with open("aa.gif", "wb") as f:
            f.write(requests.get(asset).content)
        pfp = Image.open("aa.gif")


        frames = [f.copy() for f in ImageSequence.Iterator(pfp)]

        for i, frame in enumerate(frames):
            frame = frame.copy()
            frame = frame.resize((205,205))
            frame.show()
            blyat.paste(frame, (21,21))
            frames[i] = blyat
        frames[0].save("aa.gif", save_all=True, append_images=frames[1:], delay=0.1, loop=0)
        # pfp = pfp.resize((204, 204))
        # blyat.paste(pfp, (23, 23))
        # blyat.save("pfp.gif")
        await ctx.send(file=discord.File("aa.gif"))
    elif user is None:
        user = ctx.author
        blyat = Image.open("blyat.jpg")
        asset = user.avatar_url_as(format="gif",size=1024)
        with open("aa.gif","wb") as f:
            f.write(requests.get(asset).content)
        pfp = Image.open("aa.gif")
        frames = []
        for frame in ImageSequence.Iterator(pfp):
            frame = frame.resize((205,205))
            frame = frame.copy()
            blyat.paste(frame, (21,21))
            frames.append(blyat.copy())
        frames[0].save("aa.gif",save_all=True,append_images=frames[1:],optimize = False, delay = 0 , loop = 0)
        # pfp = pfp.resize((204, 204))
        # blyat.paste(pfp, (23, 23))
        # blyat.save("pfp.gif")
        await ctx.send(file=discord.File("aa.gif"))

@bot.command()
async def avatar(ctx, *, user: discord.Member = None):
    author = ctx.author

    if not user:
        user = author # Get your avatar if you do not mention someone

    if user.is_avatar_animated():
        url = user.avatar_url_as(format="gif") # Check if it is a GIF
    if not user.is_avatar_animated():
        url = user.avatar_url_as(static_format="png") # If it is not a GIF = PNG

    await ctx.send("{}'s avatar: {}".format(user.name, url)) # Output a link + picture


bot.run(mytoken)
```
![blyat](https://user-images.githubusercontent.com/78161037/122642548-972ae580-d128-11eb-95d9-6cc518fcfdd0.jpg)
![aa](https://user-images.githubusercontent.com/78161037/122642550-9d20c680-d128-11eb-8784-3513b0d21221.gif) <-output
pfp is being taken from discord and then downloaded locally and re opened as a var

**Comment by Phant0m-123** [comment]
it is only outputting last frame

**Comment by Phant0m-123** [comment]
In the .show() it shows all of the frames but with the same corruption
![a](https://user-images.githubusercontent.com/78161037/122642596-ea9d3380-d128-11eb-9f2d-b89affc796cb.gif) <-this the file that gets downloaded

**Comment by radarhere** [comment]
To fix the animation, change
```python
frames[i] = blyat
```
to
```python
frames[i] = blyat.copy()
```
The problem was that you were creating a list of the same image instance.

However, you will still tell me that the image does not have the correct colors. This is a known issue in Pillow, and I don't have an immediate fix for you.

**Comment by Phant0m-123** [comment]
Thanks man and I hope the Pixel issue gets fixed soon

**Comment by Phant0m-123** [comment]
nvm just noticed that the gifs are also slowing down for some reason

**Comment by Phant0m-123** [comment]
![ab](https://user-images.githubusercontent.com/78161037/122644074-e117c980-d130-11eb-884c-cdf309d13a81.gif) <- saved file
![aa](https://user-images.githubusercontent.com/78161037/122644080-ed038b80-d130-11eb-944c-62f998a4041d.gif) <- after pasting new image

**Comment by radarhere** [comment]
The speed is controlled by `duration` (`delay` is incoorect). If you'd like the speed to stay the same, use `duration=pfp.info["duration"]`

**Comment by Phant0m-123** [comment]
thanks
