### ISSUE TITLE
EXIF tag `InteropVersion` has wrong type

### ISSUE THREAD

**Issue by AdrienF** [python-pillow/Pillow#5553]
## What did you do?

Open an image with Pillow and save it with its exif data.

## What did you expect to happen?

The content of the exif field `InteropVersion` must be the same in both files.

## What actually happened?

The type of `InteropVersion`  field value is set to `TiffTags.BYTE` (1)  by Pillow where it should be of type `TiffTags.UNDEFINED` (7) to conform to standard. Some software might rely on that field to assess the validity of the file.

## What are your OS, Python and Pillow versions?

- OS: Ubuntu 20.04
- Python: 3.8.5
- Pillow: 8.2.0 + fix from #5490

```python
from PIL import Image
#open a jpeg image
im = Image.open("original.jpg")
# save it with original parameters, but it doesn't change the problem to use default values
im.save("copy.jpg", exif=im.getexif(), quality=95, progressive=True, subsampling="4:4:4")
```

Original image:
![pixelated](https://user-images.githubusercontent.com/4659733/123107550-ef6c2b00-d439-11eb-8a3e-458a8a651f08.jpg)

Result image:
![original_copy](https://user-images.githubusercontent.com/4659733/123107631-00b53780-d43a-11eb-9e4b-f6a9b469724f.jpg)

Extract of the EXIF data from the original file (using `exiftool -D -s original.jpg`):
```
40962 ExifImageWidth                  : 1920
40963 ExifImageHeight                 : 692
    1 InteropIndex                    : R98 - DCF basic file (sRGB)
    2 InteropVersion                  : 0100
```
In the saved file  (using `exiftool -D -s copy.jpg`):
```
40962 ExifImageWidth                  : 1920
40963 ExifImageHeight                 : 692
    1 InteropIndex                    : R98 - DCF basic file (sRGB)
    2 InteropVersion                  : 48 49 48 48
```

**Comment by AdrienF** [comment]
A workaround, from a user perspective, is to save file to a buffer, then seek and change the type of the IFD tag, and save the file.

**Comment by radarhere** [comment]
I created #5554 to resolve this, by adding tag data for specific tag groups.

**Comment by AdrienF** [comment]
I tested the fix and it does the job.
Thanks for the quick dev time!
