### ISSUE TITLE
"UnboundLocalError: local variable 'values' referenced before assignment" when `image.getexif().tobytes()` on specific JPEGs

### ISSUE THREAD

**Issue by christophebiocca** [python-pillow/Pillow#5555]
I can't post the picture itself because it's from a customer, but the offending exif data trying to be serialized is:

```
ifd: <PIL.TiffImagePlugin.ImageFileDirectory_v2 object at ...>
ifd.self._tags_v2.items : {34665: {}, 40962: 1920, 40963: 1440, 40961: 1}
```

That empty dictionary for 34665 seems to be the culprit.

The failing statement is the use of `str(values)` when `is_ifd` is true (and thus `values` never gets defined):
https://github.com/python-pillow/Pillow/blob/70ef50cf72992ab6c9330412d6f1340c593e2d8f/src/PIL/TiffImagePlugin.py#L840

This will silently do the wrong thing instead of exploding if this is the second+ tag being serialized (as it will inherit `values` from the previous iteration of the loop.
It probably won't take that path for non-empty dictionaries, as those would have non-trivial `data` length.

A simple fix would be `if len(data) >= 16 or is_ifd` but I'm not super familiar with the codebase so it may not be the best choice.

**Comment by radarhere** [comment]
Thanks for your analysis of the problem.

I've created #5556 to resolve this, with a simple test case. Rather than using `or is_ifd`, my suggestion is instead to set `values` when `is_ifd` is true as well.
