### ISSUE TITLE
Pillow 8.3 and NumPy

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#5571]
Throws exception with Pillow 8.3: `TypeError: __array__() takes 1 positional argument but 2 were given`

````python
with PIL.Image.open(filepath) as img:
    numpy.array( img, dtype=numpy.float32 )
````

**Comment by radarhere** [comment]
What version of Python are you using? What version of numpy?

**Comment by vgrabovets** [comment]
Same problem here.
Python 3.7.4
numpy 1.21.0

workaround:
```
with PIL.Image.open(filepath) as img:
    numpy.array(img).astype(np.float32)
```

**Comment by t-vi** [comment]
Works with just about anything. The problem is that pillow newly implemented `__array__`, but only without arguments. Numpy requires `__array__` to take an optional dtype argument.

**Comment by doublex** [comment]
python 3.9 works

**Comment by t-vi** [comment]
I'll send a patch.

**Comment by carmocca** [comment]
We are seeing errors in 3.{6,7,8,9}

**Comment by ericpre** [comment]
Same issue in https://github.com/hyperspy/hyperspy/runs/2961516889 for all python version >=3.6 using the `imageio` library:

```python
                # Apply palette
>               frame_paletted = np.array(im, np.uint8)
E               TypeError: __array__() takes 1 positional argument but 2 were given

/opt/hostedtoolcache/Python/3.9.5/x64/lib/python3.9/site-packages/imageio/plugins/pillow.py:745: TypeError
```

The python 3.6 build is with numpy 1.17.1

**Comment by cgebbe** [comment]
same here: windows, python=3.6.8, numpy=1.19.5, Pillow=8.3.0

**Comment by seberg** [comment]
Just to note, there is a small chance that some details changed in NumPy 1.19.x, but I doubt it matters.  NumPy itself actually does not care whether you do return the correct dtype here, it is more of a hint at the moment.  But, it is probably good habit to just return the requested `dtype` anyway.

**Comment by IceTDrinker** [comment]
Any chance of a hotfix release ?

**Comment by zrajna** [comment]
> Any chance of a hotfix release ?
> 
> Edit : Every torchvision user using the ToTensor transform (i.e. all the vision people) will encounter the issue (and their build systems)

A hotfix would be nice, the problem affects a lot of users.

**Comment by janosh** [comment]
Definitely needs a hot fix. This is all over the place.

**Comment by hugovk** [comment]
There'll be an 8.3.1 soon, keep an eye on https://github.com/python-pillow/Pillow/issues/5578. Thank you for your patience!

**Comment by radarhere** [comment]
Pillow 8.3.1 has now been released with a fix for this.
