### ISSUE TITLE
Anti-aliasing with rounded_rectangle()

### ISSUE THREAD

**Issue by ahmed4end** [python-pillow/Pillow#5577]
the rounded edges is very sharp for a squircle! is there a way to use anti aliasing in the edges?

**Comment by radarhere** [comment]
For the record, this was also discussed in #4765.

There isn't currently a direct way to do that. You could draw a larger image and then resize it using antialiasing.
```python
from PIL import Image, ImageDraw
im = Image.new("RGBA", (200, 100), (0, 0, 0, 0))
draw = ImageDraw.Draw(im, "RGBA")
draw.rounded_rectangle((20, 20, 180, 80), 30, outline="#000")
im.save("normal.png")

for factor in range(2, 5):
	im = Image.new("RGBA", (factor*200, factor*100), (0, 0, 0, 0))
	draw = ImageDraw.Draw(im, "RGBA")
	draw.rounded_rectangle((factor*20, factor*20, factor*180, factor*80), factor*30, outline="#000", width=factor)
	im = im.resize((200, 100), Image.ANTIALIAS)
	im.save(str(factor)+".png")
```
- Normal
![normal](https://user-images.githubusercontent.com/3112309/124388844-fba09400-dd27-11eb-95dc-18cf6701d122.png)
- 2
![2](https://user-images.githubusercontent.com/3112309/124388843-fba09400-dd27-11eb-8874-baabb86218d3.png)
- 3
![3](https://user-images.githubusercontent.com/3112309/124388842-fb07fd80-dd27-11eb-8f6a-669ec7cf7769.png)
- 4
![4](https://user-images.githubusercontent.com/3112309/124388841-f9d6d080-dd27-11eb-831e-f347697148c2.png)

**Comment by ahmed4end** [comment]
@radarhere this solution works for now, Is there any plans to implement anti-aliasing in general for the rounded rect and also the line func ?

**Comment by radarhere** [comment]
No active plans, no.

**Comment by Nakik** [comment]
@radarhere  I have a question I would really love to answer
That I am trying to use code:
draw = ImageDraw.Draw (im)
draw.rounded_rectangle ((20, 20, 180, 80), outline = "# 000")
I have this error:
AttributeError: 'ImageDraw' object has no attribute 'rounded_rectangle'
thank you very much

**Comment by radarhere** [comment]
What version of Pillow are you using?
```python
from PIL import Image
print(Image.__version__)
```
`rounded_rectangle()` was only added in 8.2.0.

**Comment by radarhere** [comment]
@ahmed4end is there something new that you were after?

**Comment by radarhere** [comment]
> on some projects

So it is ok on some projects? What is the difference between those?
