### ISSUE TITLE
Release 8.3.1 on July 6, 2021

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#5578]
* [x] Make necessary changes in master branch.
* [x] Update CHANGES.rst.
* [x] Check out release branch e.g.:
```
git checkout -t remotes/origin/8.3.x
```
* [x] Cherry pick individual commits from master branch to release branch e.g. 8.3.x, then git push.
* [x] Check GitHub Actions and AppVeyor to confirm passing tests in release branch e.g. 8.3.x.
* [x] In compliance with PEP 440, update version identifier in src/PIL/_version.py
* [x] Run pre-release check via make release-test.
* [x] Create tag for release e.g.:
```
git tag 8.3.1
git push
git push --tags
```
* [x] Create and check source distribution:
```
make sdist
twine check dist/*
```
* [x] Create binary distributions
* [x] Check and upload all binaries and source distributions e.g.:
```
twine check dist/*
twine upload dist/Pillow-8.3.1*
```
* [x] Publish the release on GitHub

**Comment by radarhere** [comment]
@cgohlke at your convenience, would you be able to put together wheels? And also take care of these issues that were present with 8.3.0?

https://github.com/python-pillow/Pillow/issues/5573#issuecomment-872691741
> Pillow 8.3.0 wheels for Windows are built with libtiff 4.3.0, which has a new dependency (LERC) that uses C++ code and requires the C++ runtime library (MSVCP140.DLL). I think we need to package that DLL in the wheels.

https://github.com/python-pillow/Pillow/issues/5413#issuecomment-871978953

> > I had to disable feature.raqm, otherwise _imagingft.pyd would depend on raqm.dll on my system.
>
> To solve some runtime linking issues with wheels on Linux, in #5062 I proposed some changes that turned out to be difficult to compile from source with pip (because Raqm is C99, which is incompatible with GCC defaults on some systems). So these changes should only be enabled when building **release** wheels, which requires building with the new `--global-option --vendor-raqm --global-option --vendor-fribidi` flags as seen here: https://github.com/python-pillow/pillow-wheels/pull/181#discussion_r550904961 Those prevent _imagingft.pyd from having a dependency on raqm.dll, and it should instead link fribidi.dll at runtime.

**Comment by cgohlke** [comment]
[Here](https://www.lfd.uci.edu/~gohlke/download/Pillow-8.3.1-win-dist.zip) you go. 

Wheels for Python 3.10 beta are [here](https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow) in case anyone is asking.

**Comment by radarhere** [comment]
Thanks very much!

[Released](https://pypi.org/project/Pillow/8.3.1/), and [announced.](https://twitter.com/PythonPillow/status/1412565781951352835)

**Comment by radarhere** [comment]
[Additional](https://github.com/python-pillow/Pillow/issues/5573#issuecomment-877868175) 64-bit Windows wheels for this release have been uploaded.
