### ISSUE TITLE
TypeError: __array__() takes 1 positional argument but 2 were given

### ISSUE THREAD

**Issue by alexisbenichoux** [python-pillow/Pillow#5582]
If anyone needs this compared to pillow 8.2, pillow 8.3 converting Image to numpy array does not accept dtype any more.

`np.array(img, dtype=np.float32)`

must be replaced by `np.array(img.__array__(), dtype=np.float32)`

**Comment by dstein64** [comment]
This was fixed in PR #5572.

**Comment by radarhere** [comment]
Pillow 8.3.1 has now been released with the fix.
