### ISSUE TITLE
8.3.0 Regression: Unhandled OSError running under Apache2/mod_wsgi 

### ISSUE THREAD

**Issue by leon-matthews** [python-pillow/Pillow#5583]
### What did you do?
After upgrading one of our Django projects to Pillow 8.3.0 we got  a 500 error when trying to create a thumbnail on any page. Downgrading to Pillow 8.2.0 resolved (worked around) the error.

### What did you expect to happen?
Image resizing to continue as normal.

### What actually happened?
A 500 error and a long backtrace in the logs:
```python

Internal Server Error: /case-studies/chronic-pelvic-pain/
Traceback (most recent call last):
    ...
    File "...lib/python3.8/site-packages/PIL/ImageFile.py", line 496, in _save
        if fp == sys.stdout or (hasattr(sys.stdout, "buffer") and fp == sys.stdout.buffer):
    OSError: sys.stdout access restricted by mod_wsgi

```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04.2 LTS (Linux 5.8.0-1038-aws)
* Python: Python 3.8.10
* Django 3.2.5
* Pillow: 8.3.0 (in a venv)
* Apache (v2.4.41) / mod_wsgi (v4.6.8)

### My guess

The default [settings for mod_wsgi](https://modwsgi.readthedocs.io/en/develop/configuration-directives/WSGIRestrictStdout.html) restrict access to ``sys.stdout``.

> In the interests of promoting portability of WSGI applications, mod_wsgi restricts 
> access to sys.stdout and will raise an exception if an attempt is made to use sys.stdout explicitly.

Recent commit [0f68e63](https://github.com/python-pillow/Pillow/commit/0f68e63793ec116728589264358050b2ce14f4df#diff-4668a28f508bbcb68e61f9b257415dc814c22e8bb24850629fe7788ae5b7475c) accesses ``sys.stdout`` explicitly in [line 496 of PIL/ImageFile.py](https://github.com/python-pillow/Pillow/blob/b057f5f40f1f17efeb5f441453b3274d325a1f0e/src/PIL/ImageFile.py#L496), as per the traceback above.

### Thanks

Thank you for looking into this. Please let me know how I can help with testing - or anything else that might be required.

**Comment by radarhere** [comment]
Hi. Thanks for investigating this.

I've created PR #5585 to resolve. Please check and let me know if it does.

Because we're doing more than one check in that line, could you test in your own code and see if the problem occurs when you compare against `sys.stdout` or when comparing against `sys.stdout.buffer`? It would be nice to know exactly what the trigger is. If it's just `sys.stdout`, then does the following code also produce an error?

```python
from PIL import Image

class FP:
	name = "out.jpg"	

im = Image.new("RGB", (100, 100))
fp = FP()
try:
	im.save(fp)
except AttributeError:
	pass
```

It's not a great example, but it should hit https://github.com/python-pillow/Pillow/blob/b057f5f40f1f17efeb5f441453b3274d325a1f0e/src/PIL/Image.py#L2189

**Comment by leon-matthews** [comment]
I can confirm that the patch works, thank you very much for your quick attention.

Apologies for the delay in getting back to you. I'm in New Zealand, and in this timezone I'm still drinking my morning coffee!

Thanks again.

**Comment by radarhere** [comment]
Pillow 8.3.1 has now been released with a fix for this.
