### ISSUE TITLE
Recent change in TIFF rows per strip break saving with JPEG compression

### ISSUE THREAD

**Issue by manthey** [python-pillow/Pillow#5586]
### What did you do?

Tried to save an image with TIFF JPEG compression.

### What did you expect to happen?

It to create a file.

### What actually happened?

It threw `OSError: encoder error -2 when writing image file`.  More specifically, I see `JPEGSetupEncode: RowsPerStrip must be multiple of 8 for JPEG.`.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04
* Python: 3.9
* Pillow: 8.3.0

```python
import PIL.Image
image = PIL.Image.new('RGB', (1760, 1046))
image.save('/tmp/junk.tiff', compression='tiff_jpeg')
```

The error was specifically introduced in https://github.com/python-pillow/Pillow/pull/5514/files#diff-6ad43f85f1a075181d4d8cfcd97ae27bba1eccf5c3db5a3457160f98218eba6eR1562-R1565

**Comment by kmilos** [comment]
I get the same error in 8.2.0 when writing as a single strip, 1046 is not a multiple of 8 either...

**Comment by radarhere** [comment]
Pillow 8.3.2 has just been released with the fix for this.
