### ISSUE TITLE
Compressed image size is larger than original image

### ISSUE THREAD

**Issue by amans-13** [python-pillow/Pillow#5587]
I am trying to compress an image that i am downloading from google drive using google googleapiclient api. But, the size of the compressed image is larger than the original. Please refer the code below:

```python
request = drive_service.files().get_media(fileId=file_id)
fh = io.BytesIO()
downloader = googleapiclient.http.MediaIoBaseDownload(fh, request)
done = False
while done is False:
	# download in chunks
	status, done = downloader.next_chunk()

print('original file size', fh.getbuffer().nbytes)
img = Image.open(fh)
img.save(fh, 'jpeg',quality=0, optimize=True, lossless=False)
print('new file size', fh.getbuffer().nbytes)
```
Even when I am using quality=0, I get following results

`Download 100%.
original file size 2499847
new file size 2624369
`

**Comment by radarhere** [comment]
Could you share a copy of the original image?

**Comment by amans-13** [comment]
> Could you share a copy of the original image?

Please use the following link to get the image: https://drive.google.com/file/d/1AyKUI9PkvvEZkGpkrB1wmCQZDaYFUyi2/view?usp=sharing

**Comment by radarhere** [comment]
When I run
```python
from PIL import Image
im = Image.open('in.jpg')
im.save('out.jpg', quality=0, optimize=True, lossless=False)
```
over that image on my machine, it goes from 2.5mb to 125kb.

What version of Pillow are you using?

**Comment by amans-13** [comment]
@radarhere 
I understand the issue now. Because the buffer was not cleared and I was saving the new image in same buffer, hence the buffer size was increasing. I tried with creating a new io.BytesIo object and now I am able to get a compressed image. Thank you very much for quick response.
