### ISSUE TITLE
YCbCr mode TIFF saving not functional

### ISSUE THREAD

**Issue by kmilos** [python-pillow/Pillow#5589]
This is w/ Pillow 8.3.1.

1. Uncompressed saving (i.e. not using libtiff_encode) doesn't set tag 530 to (1,1), and mandatory tag 532:

```python
import PIL.Image
image = PIL.Image.new('YCbCr', (1760, 1046))
image.save('test_ycbcr_nocomp.tif')
```

  Resulting file is invalid - compare to tags in tiff_strip_ycbcr_jpeg_1x1_sampling.tif

2. When using compression and/or libtiff_encode, even if added somehow, tag 530 doesn't get stored correctly and encoding fails:

```python
import PIL.Image
image = PIL.Image.new('YCbCr', (1760, 1046))
image.save('test_ycbcr_libtiff.tif', compression='jpeg')
```

See also https://github.com/python-pillow/Pillow/pull/5588#issuecomment-875490034

**Comment by radarhere** [comment]
I've created #5597 to fix 1.

**Comment by kmilos** [comment]
Thanks, that's what I had in mind as well for 1.

**Comment by kmilos** [comment]
As far as item 2 goes, would removing 530 and 532 from "core tags" in both PIL/TiffTags.py and encode.c perhaps let them be encoded properly from the ifd dictionary?

**Comment by radarhere** [comment]
I've updated the PR so that it should now cover 2 as well.

**Comment by radarhere** [comment]
In combination with #5588, that resolves this.
