### ISSUE TITLE
App icns modification breaks the icon display on macOS

### ISSUE THREAD

**Issue by asoluter** [python-pillow/Pillow#5590]
### What did you do?
Modified `*.icns` file inside the app on MacOS

### What did you expect to happen?
Updated icon to be visible using Finder/Get Info.

### What actually happened?
After upgrading Pillow to 8.3.0 version, updating `*.icns` file inside the application on MacOS, makes the app icon not visible/invalid in Finder, though all the icons are visible if you open the `icns` file directly.

### What are your OS, Python and Pillow versions?

* OS: MacOS 10.15 Catalina
* Python: 3.7.7, 3.9.7
* Pillow: 8.3.0 or 8.3.1, 8.4.0

```python
with Image.open(image_path) as image:
    draw=ImageDraw.Draw(image)
    draw.rectangle([(0,0), (image.width,image.height)], fill=(255,0,0))
    image.save(image.filename)
```

**Comment by radarhere** [comment]
Using an application on my computer, I'm not able to replicate this. Could you upload the original ICNS file? What version of macOS do you have?

**Comment by asoluter** [comment]
@radarhere Sorry about the invalid example, I've rechecked it and it requires drawing prior to saving in order to break the icon (Finder may cache the old icon, so it's easier to see the change using Get Info option on the application)

**Comment by asoluter** [comment]
@radarhere I've updated the example section of description. It was tested with both MacOS 10.15 Catalina and 11.6 Big Sur. The issue is present in 8.4.0 as well.

**Comment by radarhere** [comment]
Testing, I find that the problem is the file length in the header. I've created PR #5845 to resolve this.
