### ISSUE TITLE
Error using font (OSError: execution context too long)

### ISSUE THREAD

**Issue by ahmed4end** [python-pillow/Pillow#5592]
after i edited one gylph of my font in Fontlab(software to edit fonts) then tried to use it again:
`Font.font.getsize('text')` and an error is raised 
OSError: execution context too long
i know that the editing of the font that caused the issue by why ?

**Comment by radarhere** [comment]
"execution context too long" is a FreeType error.

https://www.freetype.org/freetype1/docs/api/freetype1.txt
> In order to get rid of "poison" fonts, the interpreter produces this error when more than a million opcodes have been interpreted in a single glyph program.  This detects infinite loops softly.

**Comment by ahmed4end** [comment]
@radarhere thanks

**Comment by ahmed4end** [comment]
solved it using Fontlab -> Window/Panels/FontAudit -> fix all .

**Comment by AeroDEmi** [comment]
I have this same error, is there a way to fix it from PIL?

**Comment by aclark4life** [comment]
> I have this same error, is there a way to fix it from PIL?

According to https://www.freetype.org/freetype1/docs/api/freetype1.txt and depending on what you mean by "fix", probably not. 

You could try catching the error, but PIL is often only as capable as its dependencies and, in this case, it looks like FreeType is already doing the right thing. 🤔
