### ISSUE TITLE
8.3.0: `convert` on a P image with transparency now returns a RGB image (used to be RGBA) 

### ISSUE THREAD

**Issue by benjaminrigaud** [python-pillow/Pillow#5593]
### What did you do?

I converted an image in P mode with transparency on the new 8.3.0 release.

### What did you expect to happen?

I expected the output to be RGBA.

### What actually happened?

it is now in RGB.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04
* Python: 3.7
* Pillow: 8.3.0 or 8.3.1

Please find the code and image to reproduce the issue on https://gist.github.com/benjaminrigaud/d98a4b54fb409bc8f745d169df0196fc

```python
def test_convert_p():
    with open("indexed_with_transparency.png", "rb") as f:
        data = BytesIO(f.read())

    img = Image.open(data)

    assert img.mode == "P"
    assert img.palette.mode == "RGB"
    assert img.info.get("transparency") == 0

    img2 = img.convert()

    assert img2.mode == "RGBA"
```

**Comment by radarhere** [comment]
This would be due to https://github.com/python-pillow/Pillow/pull/5552/commits/804183c2489242251fdd9858b6e781ceefb08c8b. It changed palettes for P images with `info["transparency"]` to RGB instead of RGBA. Separate to that, converting from a P image with no mode argument uses the palette mode if there is one.

I've created PR #5594 to fix this.

**Comment by NicolasHug** [comment]
I am facing a similar issue when converting a P image into LA: values of the transparency channel are all 255 with `pillow>=8.3`:

```py
from PIL import Image
import numpy as np

# same image that OP mentioned https://gist.github.com/benjaminrigaud/d98a4b54fb409bc8f745d169df0196fc
path = the_path_here

with Image.open(path) as img:
    img = img.convert("LA")
np.unique(np.asarray(img)[:, :, -1])
```

This will print `array([255], dtype=uint8)` on 8.3.1 and `array([  0, 255], dtype=uint8)` on 8.2

Using another P image like https://github.com/pytorch/vision/blob/master/test/assets/fakedata/logos/palette_pytorch.png, the results are even more drastic:

`array([255], dtype=uint8)` vs `array([  0,  16,  64,  80,  96, 128, 160, 208, 224, 240, 255], dtype=uint8)`

**Comment by radarhere** [comment]
I've created #5606 to fix this second problem. I validated the result just by visually inspecting the output.
