### ISSUE TITLE
How to save WebP?

### ISSUE THREAD

**Issue by ademaro** [python-pillow/Pillow#5600]
### What did you do?
Trying to save the image

### What did you expect to happen?
Saving image in webp format

### What actually happened?
Error
### What are your OS, Python and Pillow versions?

* OS: linux (debian) with libwebp 0.5.2-1+deb9u1 and macos bigsur 
* Python: 3.8.8 and 3.9.6
* Pillow: 8.3.1

When I try to save the image (jpg) - I get the error:

```python
    img.save(fp, format, **save_options)
  File "[...]/.venv/lib/python3.8/site-packages/PIL/Image.py", line 2235, in save
    save_handler(self, fp, filename)
  File "[...]/.venv/lib/python3.8/site-packages/PIL/WebPImagePlugin.py", line 327, in _save
    data = _webp.WebPEncode(
TypeError: a bytes-like object is required, not 'NoneType'
```

```python
# with `save_options['save_all'] = True` :
    img.save(fp, format, **save_options)
  File "[...]/.venv/lib/python3.9/site-packages/PIL/Image.py", line 2236, in save
    save_handler(self, fp, filename)
  File "[...]/.venv/lib/python3.9/site-packages/PIL/WebPImagePlugin.py", line 179, in _save_all
    _save(im, fp, filename)
  File "[...]/.venv/lib/python3.9/site-packages/PIL/WebPImagePlugin.py", line 328, in _save
    data = _webp.WebPEncode(
TypeError: a bytes-like object is required, not 'NoneType'
```

**Comment by radarhere** [comment]
If try this with one of our test images, it works for me without an error.

```python
from PIL import Image
im = Image.open("Tests/images/hopper.jpg")
im.save("hopper.webp")
```

Could you provide a copy of the specific JPEG image you're using?

**Comment by ademaro** [comment]
Thank you very much for your reply, actually works!

The error turned out to be that the parameters were passed 'icc_profile', which was equal to `None`. What is strange - for JPEG files it is processed without error at all, but for some WebP files, for some reason, saving does not work. Now I will try to find out on which image to stop, I will write down in more detail.

**Comment by ademaro** [comment]
In general - yes, apparently, WebP does not support this option at all. If you save together with the ICC profile in the JPEG, it will be saved in the final version. If you save the same image in the WebP, then the ICC profile will not be saved. If the color profile is not in the original (or rather, if you save it with the `icc_profile=None` parameter), then when you save the JPEG file, it will simply be saved without it, and in the case of WebP, there was an error that was difficult to find... 

Maybe make a more unified processing or a little more write about an error? Although, maybe it's just that I could not find it quickly... In general, everything works, thanks for the help, the issue can be closed. 🙏🏼

**Comment by radarhere** [comment]
I've created PR #5601 to fix the `icc_profile=None` error.

It sounds like you're also having trouble saving the ICC profile to WebP. If you'd like that addressed, please provide some example code.

**Comment by ademaro** [comment]
It would be great to add support for the ICC profile for the WebP. [Link to specification](https://developers.google.com/speed/webp/docs/riff_container#color_profile)

code example:
```python
import io
import pilkit.utils
from PIL import Image

QUALITY = 80
PROGRESSIVE = True

def image_data(img, format, **save_options):
    """Save a PIL Image instance and return its byte contents"""
    fp = io.BytesIO()
    img.save(fp, format, **save_options)
    fp.seek(0)
    return fp.read()

source_file = "Tests/images/hopper.jpg"
with open(source_file, "rb") as fp:
    source_data = fp.read()

fp = io.BytesIO(source_data)
img = Image.open(fp)
img_format = img.format

# some pilkit processing [...]

options = {
    "icc_profile": img.info.get("icc_profile"),  # Now I need refactor this line, jpeg — save okay, webp — error
}
if img_format in ["JPEG", "WEBP"]:
    options.update(
        quality=int(QUALITY)
    )

if img_format == "JPEG":
    options.update(
        progressive=PROGRESSIVE
    )

# one more processing (add new options)
img, save_kwargs = pilkit.utils.prepare_image(img, img_format)
save_kwargs.update(options)
options = save_kwargs

bdata = image_data(img, img_format, **options)

with open("hopper.webp", "xb") as fp:
    fp.write(bdata)
```

**Comment by radarhere** [comment]
I think that Pillow already supports WebP ICC Profile - I don't see any problems with your code.

Running it on Tests/images/hopper.jpg image raises the TypeError, yes, because Tests/images/hopper.jpg doesn't have an ICC Profile. If #5601 is merged though, that should be fixed in the a future Pillow release.

If I run your code on Tests/images/flower2.jpg, which does have an ICC Profile, then the created hopper.webp also has an ICC Profile.

**Comment by ademaro** [comment]
I just checked it on the images from the ICTs: there is no profile saving in the WebP.

original flower2.jpg:
![original flower2.jpg](https://i.imgur.com/k1qUEbo.png)

encoded to WebP:
![encoded to WebP](https://i.imgur.com/ueg9bho.png)

### Another picture:
original jpeg:
![original jpeg](https://i.imgur.com/rFXz8jO.png)

encoded to jpeg (saved with ICC profile):
![encoded to jpeg](https://i.imgur.com/XYvRLVL.png)

encoded to WebP (saved without ICC Profile):
![encoded to WebP](https://i.imgur.com/cABYijS.png)

**Comment by radarhere** [comment]
If I open up flower2.jpg and flower2.webp in http://metapicz.com/#landing, the ICC profiles match.

I'm not sure what program you're using to inspect the output. It looks like macOS Preview? My theory is that Preview just isn't detecting ICC profiles from WebP. If you can find a WebP image that Preview does show an ICC profile for, then I'm wrong, and comparing the two files would be a way forward.

**Comment by ademaro** [comment]
Yes, indeed, you are right, I am very surprised that the latest Mac OS does not read the ICC profile from the WebP. I'm sorry for disturbing.
