### ISSUE TITLE
method .text gives an error message

### ISSUE THREAD

**Issue by LuK050** [python-pillow/Pillow#5602]
### What did you do?
I wrote a code to add text to a picture, the font and image file is in the code folder. The image opens
### What did you expect to happen?
The fact that text will be added to the picture, without errors
### What actually happened?
An error has occurred: 
`Traceback (most recent call last):
  File "C:\Users\Кирилл\Desktop\test_image\test_images.py", line 7, in <module>
    img.text((809, 316), "1", font = font_my, fill='#ffffff')
TypeError: 'dict' object is not callable`
### What are your OS, Python and Pillow versions?

* OS: Windows 10 Home
* Python: 3.9.6
* Pillow: 8.3.1

```python
from PIL import Image, ImageFont, ImageDraw

img = Image.open("queue_ru.png")

font_my = ImageFont.truetype("Montserrat-ExtraBold.ttf", size=100)

img.text((809, 316), "1", font = font_my, fill='#ffffff')

img.save("queue_ru_fin.png")
img.show()
```

**Comment by nulano** [comment]
Hi. You have to use `ImageDraw.text`, not `img.text`:

```python
from PIL import Image, ImageFont, ImageDraw

img = Image.open("queue_ru.png")

font_my = ImageFont.truetype("Montserrat-ExtraBold.ttf", size=100)

draw = ImageDraw.Draw(img)

draw.text((809, 316), "1", font = font_my, fill='#ffffff')

img.save("queue_ru_fin.png")
img.show()
```
