### ISSUE TITLE
Pillow-Firefox crash

### ISSUE THREAD

**Issue by dpkesling** [python-pillow/Pillow#5607]
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```python
import csv
from PIL import Image, ImageDraw, ImageFont
import math

#-------------------------------------- ready output
print("+++start+++")
input_file = "C:\\GVA\\remaining-city-only.csv"

outfile = Image.new("RGB",(2000,800),color= 0x0)
drawpad = ImageDraw.Draw(outfile)
fnt = ImageFont.truetype("ARIAL.TTF",30)
littlefnt = ImageFont.truetype("ARIAL.TTF",8)

#-------------------------------------- create data dictionary
tally_db = {(0,0): 0}

#-------------------------------------- draw counties 
print("+++drawing counties+++")

mapfile = "C:\\mapz\\us-county-working.csv"

with open(mapfile, newline='') as in_map:
	readerf = csv.reader(in_map)
	for row_data in readerf:
#		print(row_data[0],row_data[1])
			
		xm = round(float(row_data[1])*30)+3800
		ym = 100 - round(float(row_data[0])*29)+1350
	
		drawpad.rectangle((xm-4,ym-4,xm+4,ym+4), fill = 0x490000)

#	drawpad.line((x1,y1,x2,y2), outcolor)	

#-------------------------------------- draw cities
print("+++drawing cities+++")

mapfile = "C:\\mapz\\top50cities.csv"

with open(mapfile, newline='') as in_map:
	readerf = csv.reader(in_map)
	for row_data in readerf:
#		print(row_data[0],row_data[1])
		if(row_data[0] == ""): continue
		
		cityname = row_data[2]
		xm = round(float(row_data[1])*30)+3800
		ym = 100 - round(float(row_data[0])*29)+1350	
		drawpad.ellipse((xm-4,ym-4,xm+4,ym+4), fill = 0x004000)
		drawpad.text((xm+6, ym-4),cityname, font=littlefnt, fill=0x007000)
		
#--------------------------------------
print("+++counting incidents per city+++")
lines_read = 0
dcount = 0


with open(input_file, newline='') as in_f:

	readerf = csv.reader(in_f)
	for row_data in readerf:
		lines_read += 1
#		print(row_data, row_data[2],row_data[3])
		xc = round(float(row_data[3])*30)+3800
		yc = 100 - round(float(row_data[2])*29)+1350
		db_index = str(xc) + "|" + str(yc)
#		print(xc,yc,db_index)
		
		if (xc,yc) in tally_db:
			cur_val = tally_db[(xc,yc)]
#			print(db_index, "in there", cur_val)
			cur_val += 1
			tally_db[(xc,yc)] = cur_val
			
		else:
#			print("nope")
			tally_db[(xc,yc)] = 2

#		pixval = outfile.getpixel((xc,yc))
#		print(pixval)
		


del tally_db[(0,0)]		# get rid of dictionary starter 'seed'

#--------------------------------------
print("+++drawing data points+++")

spectrum = [0xffffff,
		0xffffff,
		0xffffff,
		0xe5ffff,
		0xbcf7ff,
		0x91e3fe,
		0x299afb,
		0x2d93f1,
		0x1ccccc,
		0x1ceeee,
		0x1cffff]

for coords in list(tally_db):
	height = tally_db[coords]
	circ_radius = int((height+3) / 2)
	
	if (height > 10):
		outcolor = 0x1010ff
	else:
		outcolor = spectrum[height]
	
	px = coords[0]
	py = coords[1]
	print(coords, height, px, py)

	# draw the bar
	drawpad.ellipse((px-circ_radius,py-circ_radius,
		px+circ_radius,py+circ_radius), outcolor, 0x000000)


points_prt = "< " + str(lines_read) + " >  data points"
drawpad.text((50, 700),points_prt, font=fnt, fill=0x909090)
#-------------------------------------- conclusion
outfile.save("C:\\GVA\\GVA_maps\\0usacircles.png")
outfile.show()
print(lines_read)
print("dcount ", dcount)
print("+++END+++")
```
Python 3.9.6
Pillow 8.3.1
Firefox 89.0.2 (64 bit)
Windows 10.0.19042.1083
There appears to be a resource conflict between Pillow and Firefox. My machine locks up tight as a drum, can't even get Task Manager to run to analyze the problem, have to force shutdown and reboot. No apparent problem using Chrome 91.0.4472.124
The program was running fine and has been for months... don't which upgrade (Pythion, Pillow, Firefox) caused it break, but something has gone sideways. The program itself is doing nothing more than reading coordinates from a CSV file and plotting them.

**Comment by radarhere** [comment]
A few questions.
1) How did you install Pillow?

2) Your code is doing a number of things. If you comment out the Pillow parts of your code, are you saying that the problem disappears?

3) The Python code has nothing to do with your browser, right? You're saying that you're running Python code, and independently, you are running Firefox, and somehow, you've worked out that only when you have both Firefox open and the Python code running, that combination is causing your machine to hang?

**Comment by dpkesling** [comment]
I installed Pillow using the Pip utility.

I have several other Python programs in my toolbox, none of the others
having PIL calls, none of the others hanging.

The code I attached is the entirety of the program in question, no access
of Firefox or any external routines. It is very simple to achieve a simple
objective.

I'll also say that just ran things on Ubuntu 21.04... and everything is
good, but I have no idea what versions of anything over there. Didn't try
it with concurrent Firefox session, though.

**Comment by dpkesling** [comment]
Sorry I didn't fully answer your last question. I did try using both Scite
and IDLE... the IDE didn't seem to matter. Tried concurrent w/ GIMP 2.10.24
rev 3... no problem. Tried with Libre Office running, no problem. Even
tried with the Windows Screen Grab, no problems. My typical work session
involves using spreadsheet in Libre to access data to paste into a web app
on Firefox. The screengrab pulls snippets off a newsfeed. At the end of a
session, I leave all that stuff open and fire up Python routine you have to
analyze session progress. I did an upgrade session on all of this stuff at
the same time to the versions I listed earlier. Don't know if it was 3.9.6
Python or the 8.3.1 Pillow or Firefox... but something is grinding against
something. I don't really want to start doing downgrades to isolate the
stinker...

**Comment by dpkesling** [comment]
Just tried running the concurrent Python/PIL/Firefox on Ubuntu box
concurrently... no apparent problem.

One other thing in my notes as I look back through them. The program WILL
run to completion on the first try after a reboot of Windows, maybe even a
second time. My initial thoughts are a resident routine getting too many
threads going, eating the CPU and/or Memory cycles, starving the system.
Just guessing on my part, though.

**Comment by radarhere** [comment]
Here is a version of your code, where I have removed Pillow. Does this run without problems for you?

```python
import csv
import math

#-------------------------------------- ready output
print("+++start+++")
input_file = "C:\\GVA\\remaining-city-only.csv"

#-------------------------------------- create data dictionary
tally_db = {(0,0): 0}

#-------------------------------------- draw counties 
print("+++drawing counties+++")

mapfile = "C:\\mapz\\us-county-working.csv"

with open(mapfile, newline='') as in_map:
	readerf = csv.reader(in_map)
	for row_data in readerf:
#		print(row_data[0],row_data[1])
			
		xm = round(float(row_data[1])*30)+3800
		ym = 100 - round(float(row_data[0])*29)+1350

#-------------------------------------- draw cities
print("+++drawing cities+++")

mapfile = "C:\\mapz\\top50cities.csv"

with open(mapfile, newline='') as in_map:
	readerf = csv.reader(in_map)
	for row_data in readerf:
#		print(row_data[0],row_data[1])
		if(row_data[0] == ""): continue
		
		cityname = row_data[2]
		xm = round(float(row_data[1])*30)+3800
		ym = 100 - round(float(row_data[0])*29)+1350	
		
#--------------------------------------
print("+++counting incidents per city+++")
lines_read = 0
dcount = 0


with open(input_file, newline='') as in_f:

	readerf = csv.reader(in_f)
	for row_data in readerf:
		lines_read += 1
#		print(row_data, row_data[2],row_data[3])
		xc = round(float(row_data[3])*30)+3800
		yc = 100 - round(float(row_data[2])*29)+1350
		db_index = str(xc) + "|" + str(yc)
#		print(xc,yc,db_index)
		
		if (xc,yc) in tally_db:
			cur_val = tally_db[(xc,yc)]
#			print(db_index, "in there", cur_val)
			cur_val += 1
			tally_db[(xc,yc)] = cur_val
			
		else:
#			print("nope")
			tally_db[(xc,yc)] = 2
		


del tally_db[(0,0)]		# get rid of dictionary starter 'seed'

#--------------------------------------
print("+++drawing data points+++")

spectrum = [0xffffff,
		0xffffff,
		0xffffff,
		0xe5ffff,
		0xbcf7ff,
		0x91e3fe,
		0x299afb,
		0x2d93f1,
		0x1ccccc,
		0x1ceeee,
		0x1cffff]

for coords in list(tally_db):
	height = tally_db[coords]
	circ_radius = int((height+3) / 2)
	
	if (height > 10):
		outcolor = 0x1010ff
	else:
		outcolor = spectrum[height]
	
	px = coords[0]
	py = coords[1]
	print(coords, height, px, py)


points_prt = "< " + str(lines_read) + " >  data points"
#-------------------------------------- conclusion
print(lines_read)
print("dcount ", dcount)
print("+++END+++")
```

**Comment by dpkesling** [comment]
Ran your stripped down version with concurrent Firefox. No problem.
As a control, ran the original Pillow-ed version with just Firefox
(displaying Google Maps page). -> No problem (weird)
One-by-one, I added the other my other 'usual' programs, Libre, GIMP,
Snapping Tool... all from Scite/Scintilla IDE... -> still no problem.
In the midst of this Firefox pushed a new version out... 90.0 replacing
89.0.2 (64 bit).
I double-checked and Windows hadn't stealth-pushed a new mod pak on me.
I, like you, am greatly perplexed and frustrated.
BUT... for the moment, whatever went sideways seems to have straightened
itself out without any intervention. That's not to say
it won't blow up again... but things are smooth for the moment.
I remain suspicious, but won't bother you anymore unless it does blows up
again. If you don't mind, I'll hang onto your email addr for future ref
with the
sincere promise not to needlessly bother you.

One last observation (just FYI) the following snip has always concerned me
a bit

outfile.save("C:\\GVA\\GVA_maps\\0usacircles.png")
outfile.show()

... as the outfile_show() command and Windows Photos utility occasionally
time-out trying to talk to each other.
My program does not crash, but the Photos screen comes up with a 'took too
much time' msg. Not Pillow's fault.

Thanks for all your time and assistance,
David Kesling

**Comment by nulano** [comment]
> My machine locks up tight as a drum, can't even get Task Manager to run to analyze the problem, have to force shutdown and reboot.
> ...
> BUT... for the moment, whatever went sideways seems to have straightened
itself out without any intervention.

This sounds like your system might have run out of free RAM. After restarting you had fewer programs running (and fewer tabs open in Firefox) so there was no problem anymore. I would recommend you keep Task Manager open on the Performance>Memory page so that if this happens again you can confirm this easily.

**Comment by dpkesling** [comment]
I have been working the problem with someone else. Thank you for your input.

**Comment by dpkesling** [comment]
Just had another freeze at the end of a work session.
I want to add another possible culprit. The work I do on Firefox involves
heavy use of a website running
a Drupal routine for its web content management and presentation. Perhaps
Drupal is throwing some
processes out there that Python/Pillow are competing with.
While I hit Python -after- having closed the Drupal-based site... possibly
a lingering process.
I'm really just guessing now.

**Comment by dpkesling** [comment]
Finally have the culprit for you. "FireShot" is a browser extension for
both Firefox and Chrome which allows
you to do screen grabs of entire web pages, like a newspaper article, into
a single file. It apparently does this
by grabbing the screen buffer, scrolling to the next page, grabbing again,
until it hits the end of an article. Then,
under the covers, it assembles the individual grabs into a single, seamless
image.
An obvious conflict for the graphic memory access between FireShot and
Pillow.
Would also make sense about this just appearing out of the blue because the
Fireshot guys push minor
updates out all the time... and one of the recent ones must have been what
is clobbering me now.
My solution is to continue Pillow, but only after remembering to close any
browser window where I've utilized Fireshot.

**Comment by radarhere** [comment]
Thanks for figuring it out! Are you saying this issue can be closed then?

**Comment by dpkesling** [comment]
As far as I'm concerned, I guess so... but you folks might want to explore the Pillow - Fireshot contention issue a little more for its causes. Cautionary. Thanks again for your assistance.

**Comment by radarhere** [comment]
Noting here that https://addons.mozilla.org/en-US/firefox/addon/fireshot/ is Windows only.

**Comment by dpkesling** [comment]
Interesting development. Problem isn't at the application level at all, but
in the Windows system
Found this using Task Manager run BEFORE I started all the other stuff...
so it was running during the 'freeze'.
There is a module called "Service Host: SysMain" which went to 100% Disk
utilization and stayed there.
Researching, I discover this used to known as "Superfetch" and is supposed
adaptively keep learning how to keep your disk
service optimized. It also, apparently, receives many complaints precisely
like mine that Disk goes to 100% and Memory to 100%
utilization. Lots of complaints.
I ran some recommended system utilities suggested to make the service
happier, but also discover that it can
be disabled if it becomes too big a pain in the keister.
THAT seems to be my problem and has been all along.

Woof.

**Comment by radarhere** [comment]
Are you saying this has nothing to do with Pillow at all?

**Comment by dpkesling** [comment]
It would appear not. Good news for you and the crew.
I, on the other hand, have issues with Microsoft.

**Comment by radarhere** [comment]
Thanks for investigating

**Comment by dpkesling** [comment]
FYI To truly conclude my earlier reported issue analysis... the failure is
in LibreOffice Calc and its memory management process. Their developers
have, just this morning, acknowledged a bug in Calc. My Python/Pillow
problems stemmed from launching into a environment where Calc was trying to
suck 9 Gb out of an 8 Gb main memory. To summarize, Pillow was an innocent
bystander to Calc's trainwreck.
Thought you might like to know. Thanks again for your patience and help.
