### ISSUE TITLE
type list doesn't define __round__ method

### ISSUE THREAD

**Issue by thak1411** [python-pillow/Pillow#5608]
### What did you do?

I saved .apng file

### What did you expect to happen?

Running with no exception

### What actually happened?

I got "type list doesn't define \_\_round\_\_ method" error in function "_write_multiple_frames"
https://github.com/python-pillow/Pillow/blob/83c05aaf8daa930086257eb38b254f06808d13e5/src/PIL/PngImagePlugin.py#L1060

https://github.com/python-pillow/Pillow/blob/83c05aaf8daa930086257eb38b254f06808d13e5/src/PIL/PngImagePlugin.py#L1152

### What are your OS, Python and Pillow versions?

* OS: MacOS
* Python: 3.8.2
* Pillow: 8.3.1

**Comment by radarhere** [comment]
Could you provide a complete simple example that we can run to demonstrate the error?

**Comment by thak1411** [comment]
```python3
from PIL import Image

def main():
    img1 = Image.new('RGBA', (100, 100), (255, 0, 0, 0))
    img2 = Image.new('RGBA', (100, 100), (255, 255, 255, 0))
    img3 = Image.new('RGBA', (100, 100), (255, 255, 0, 0))
    img4 = Image.new('RGBA', (100, 100), (255, 255, 0, 0))
    img5 = Image.new('RGBA', (100, 100), (255, 255, 255, 0))

    img1.save('out.apng', save_all = True, append_images = [img2, img3, img4, img5], duration = [200, 200, 200, 200, 200])

if __name__ == '__main__':
    main()
```

**Comment by thak1411** [comment]
This issue occurs when consecutive duplicate frames exist.
