### ISSUE TITLE
ValueError: Decompressed Data Too Large

### ISSUE THREAD

**Issue by jS5t3r** [python-pillow/Pillow#5610]
Similar posts (some of them are outdated, links within posts do not work): 
https://github.com/python-pillow/Pillow/issues/515
https://github.com/python-pillow/Pillow/issues/2445
https://stackoverflow.com/questions/42671252/python-pillow-valueerror-decompressed-data-too-large

The difference: I use `Image.fromarray()`, instead of 'Image.open()'.

### What did you do?

I installed Python 3.9  and wanted to start an older but running project.

### What did you expect to happen?

Images are opened from the ImageNet dataset.

```python
img = Image.fromarray(img)
```

### What actually happened?

It seems to be that I use two different pillow libs... one from torchvision and the other one from python packages.

```
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 269, in default_loader
    return pil_loader(path)
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/torchvision/datasets/folder.py", line 250, in pil_loader
    img = Image.open(f)
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/Image.py", line 2953, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/Image.py", line 2939, in _open_core
    im = factory(fp, filename)
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/ImageFile.py", line 121, in __init__
    self._open()
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 694, in _open
    s = self.png.call(cid, pos, length)
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 187, in call
    return getattr(self, "chunk_" + cid.decode("ascii"))(pos, length)
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 397, in chunk_iCCP
    icc_profile = _safe_zlib_decompress(s[i + 2 :])
  File "/home/user/.conda/envs/cuda--11-1-1--pytorch--1-9-0/lib/python3.9/site-packages/PIL/PngImagePlugin.py", line 133, in _safe_zlib_decompress
    raise ValueError("Decompressed Data Too Large")
ValueError: Decompressed Data Too Large
```

### What are your OS, Python and Pillow versions?

* OS: Linux Debian
* Python: 3.9
* Pillow: 8.3.1
* Cuda 11.1.1
* Pytorch 1.9

What I have tried to fix it?

This:
```python
 PIL.ImageFile.LOAD_TRUNCATED_IMAGES = True
```
and that:

```python
from PIL import Image
Image.MAX_IMAGE_PIXELS = 1000000000 
```

**Comment by radarhere** [comment]
If you're looking for a value to change, try
```python
from PIL import PngImagePlugin
PngImagePlugin.MAX_TEXT_CHUNK = 1048576  # this is the current value
```

If you'd like this investigate further, please provide an image and code, so that we can run a self-contained example.

**Comment by wiredfool** [comment]
`Image.fromarray` wouldn't be going through that code path loading a png image, and the traceback is calling `Image.open`, presumably on a png file. 

It's most likely a bad/abnormally large compressed data chunk in the png image.

**Comment by jS5t3r** [comment]
@radarhere for the dataset 64x64 it seems to work... for 128x128 image size, it crashes... How come the value `1048576 `?

@wiredfool well... I explained it wrong... I think that torchvision also uses pillow implicitly...

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/PngImagePlugin.py#L83

https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/ImageFile.py#L40

**Comment by radarhere** [comment]
I wasn't suggesting that you use the value 1048576, but rather that this was a variable for your to try increasing, and that 1048576 is what it is at the moment.

So setting a very large value for that variable isn't fixing the problem for you? Are you able to share a specific image?

**Comment by jS5t3r** [comment]
yes, a very large value is fixing the problem...  1048576  * 10 

I am not able to send you an image... it is just a 128x128 png, but I can attach you a dummy once. 

![00001](https://user-images.githubusercontent.com/6324091/125648285-eef4cc84-eaeb-4f83-90c4-bf8fbc520d80.png)

After loading it around 60 times with the Pytorch data loader, it crashes... it uses implicitly the pillow function...

**Comment by radarhere** [comment]
Without any modifications, I'm able to load that image 6000 times on my local machine without a problem.
```python
from PIL import Image
for i in range(6000):
	im = Image.open("demo.png")
	im.load()
```

**Comment by radarhere** [comment]
As I said, the image you attached works for me. Does opening it with my code work for you?

@jS5t3r could we have a self-contained code example of the problem? Meaning code that we can run by itself, with any input images. Ideally, a small number of images, not the ImageNet dataset.

Without a specific scenario to discuss, it is hard to address this issue.

> yes, a very large value is fixing the problem... 1048576 * 10

Or is this issue already resolved for you?
