### ISSUE TITLE
Pillow fails/hangs on PSD hidden background layer

### ISSUE THREAD

**Issue by andreymal** [python-pillow/Pillow#5612]
Depending on file content, Pillow:

- fails with "cannot identify image file";
- fails with "Truncated File Read";
- just hangs inside the `PsdImagePlugin._layerinfo` function because it thinks there are 65534 layers.

See attachment: [pillow-psd-fail.zip](https://github.com/python-pillow/Pillow/files/6815914/pillow-psd-fail.zip)

GIMP works fine with these files.

**Comment by radarhere** [comment]
To provide some further information -

- pillow-cannot-identify.psd is hitting https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/PsdImagePlugin.py#L186
- pillow-truncated-file-read.psd is hitting https://github.com/python-pillow/Pillow/blob/696b82e44032500197734c4dc4669d7c3f8b9371/src/PIL/ImageFile.py#L562
- pillow-hangs.psd does not loop forever. It may take a minute, but it does finish

**Comment by radarhere** [comment]
Ok, I've realised that the problem is that we're not allowing for the layer count to be negative.

https://www.adobe.com/devnet-apps/photoshop/fileformatashtml/#50577409_pgfId-1031423
> Layer count. If it is a negative number, its absolute value is the number of layers and the first alpha channel contains the transparency data for the merged result.

Are we able to include pillow-cannot-identify.psd in our test suite and distribute it under the Pillow license?

**Comment by andreymal** [comment]
>Are we able to include pillow-cannot-identify.psd in our test suite and distribute it under the Pillow license?

Yes (if it doesn't contain any sensitive meta information) — it's completely empty and I think it is not copyrighted :)

(But pillow-hangs.psd contains a t-shirt image from an unknown source, so I can't relicense it)

Techically, you can recreate these files from scratch using the [Layer > New > Background from Layer](https://helpx.adobe.com/photoshop/key-concepts/background.html) menu and then hiding the background layer

**Comment by radarhere** [comment]
I don't actually have Photoshop. If you want to recreate an image with the same problem and attach it, I can use that instead.

**Comment by andreymal** [comment]
These files have already been recreated, so everything is fine I think

**Comment by radarhere** [comment]
Oh, wait - I managed to create a problem image using Gimp. I've attached that to the PR instead
