### ISSUE TITLE
EPS files are loaded without transparency

### ISSUE THREAD

**Issue by yngvem** [python-pillow/Pillow#5619]
EPS files can have transparency, and GhostScript have the option to keep it. However, if we use Pillow to open an EPS-file, then the alpha-channel is discarded. To my understanding, this is because Pillow is currently using the `ppm` (portable pixel map)-driver, which creates RGB-images, not RGBA-images. 

I therefore propose to add an option to specify which driver to use with GhostScript (or add a flag that can be enabled to use the `pngalpha` driver instead of the `ppmraw` driver)

To my understanding, this can be fixed by modifying line 120 in `src/PIL/EpsImagePlugin.py`: https://github.com/python-pillow/Pillow/blob/20b8a8377372b1f318ae275acd5e11bad4722e2e/src/PIL/EpsImagePlugin.py#L120
into
```python
        "-sDEVICE=pngalpha",  # png driver
```

I made the change locally on my machine, and it seemed to work well. 
### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8
* Pillow: 8.2.0

### Endnote: Script to generate a postscript file and convert it with Pillow
```python
import turtle
from PIL import Image

pen = turtle.Turtle()
for side in range(4):
    pen.forward(50)
    pen.right(90)

turtle.getscreen().getcanvas().postscript(file="square.eps")
img = Image.open('square.eps')
img.save("image.png")
```

**Comment by radarhere** [comment]
Thanks for finding a solution to your problem - I've created PR #5620
