### ISSUE TITLE
`OSError: unknown freetype error` when using certain characters from certain fonts

### ISSUE THREAD

**Issue by zpapakipos** [python-pillow/Pillow#5627]
### What did you do?
Overlay text on an image using ImageDraw with a specific ttf font file, using certain characters from the associated pkl file. I have a minimal reproducible code snippet below & in a colab notebook that can be run.

### What did you expect to happen?
We do this using many different fonts & characters, and 99% of the time it works fine.

### What actually happened?
There are certain combinations of font files & specific characters from those fonts (identified in https://github.com/facebookresearch/AugLy/issues/81) which cause a cryptic error when this code is run on them: `OSError: unknown freetype error`. Please see the original issue for more details & combinations of fonts & indices that cause this error.

### What are your OS, Python and Pillow versions?

* OS: colab notebook (linux?)
* Python: 3.7.11
* Pillow: 8.3.1

Colab notebook to repro the error: https://colab.research.google.com/drive/1H2ZIPNcssHO8q-I1X5D3FzOAUM1_jwgF?usp=sharing

```python
import os
import pickle
from augly.utils import FONTS_DIR, TEST_URI
from PIL import Image, ImageDraw, ImageFont

image_path = os.path.join(TEST_URI, "image", "inputs", "dfdc_1.jpg")
font_file = os.path.join(FONTS_DIR, "NotoSansBengaliUI-Regular.ttf")
pkl_file = os.path.join(FONTS_DIR, "NotoSansBengaliUI-Regular.pkl")
text = [166, 287]
font = ImageFont.truetype(font_file, 162)
with open(pkl_file, "rb") as f:
    chars = pickle.load(f)
text_str = "".join([chr(chars[c % len(chars)]) for c in text])

aug_image = Image.open(image_path).convert('RGBA')
draw = ImageDraw.Draw(aug_image)
draw.text(
    xy=(0.0, 200.0),
    text=text_str,
    fill=(0, 0, 0, 255),
    font=font,
)
```

**Comment by radarhere** [comment]
The notebook states that
> The font ttf & pkl files are downloaded from https://www.google.com/get/noto/

I can find the TTF file there, but I'm not seeing the pickle file?

**Comment by jbitton** [comment]
Hi @radarhere, you can find the `.pkl` file here: https://github.com/facebookresearch/AugLy/blob/main/augly/assets/fonts/NotoSansBengaliUI-Regular.pkl :)

**Comment by radarhere** [comment]
This reminded me of #5530, which was discussed further in FreeType at https://gitlab.freedesktop.org/freetype/freetype/-/issues/1063

So I [replicated this error in GitHub Actions](https://github.com/radarhere/Pillow/actions/runs/1058196276), and after running [`brew update`](https://github.com/radarhere/Pillow/commit/ec26e0a04451869ad6241b74d4daf9ac0f98d015) to update from FreeType 2.10.4 to 2.11.0, it [starts working.](https://github.com/radarhere/Pillow/actions/runs/1058197612).

So the solution to this `unknown freetype error` is just to upgrade to the latest freetype.

**Comment by jbitton** [comment]
Thank you @radarhere for helping resolve this issue on https://github.com/facebookresearch/AugLy/issues/81 :) 

@zpapakipos is currently out (and i can't close this issue) so feel free to close!
