### ISSUE TITLE
UnidentifiedImageError: cannot identify image file [PNG]

### ISSUE THREAD

**Issue by rimpy-custom** [python-pillow/Pillow#5631]
I am getting `UnidentifiedImageError cannot identify image file` for a PNG file (Google Drive link): https://drive.google.com/file/d/1GR5CZZERrsoDJU9TcP3RsKaevK7-_H52

The code is:
```python
from PIL import Image
Image.open('1.png')
```

**Comment by radarhere** [comment]
Hidden by that error is `SyntaxError: broken PNG file (bad header checksum in b'iCCP')`, coming from https://github.com/python-pillow/Pillow/blob/68c5f2dce11768e5334a97d17feb2a85a0fd0590/src/PIL/PngImagePlugin.py#L203-L205

If I run [pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) over the file, it agrees.
```
1.png  CRC error in chunk iCCP (computed 139d5c86, expected 42b3bd80)
ERROR: 1.png
```

So the simple answer is that your PNG file is corrupt.

**Comment by radarhere** [comment]
If you would like to use the file anyway, you can do this as a workaround.

```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
Image.open('1.png')
```

**Comment by rimpy-custom** [comment]
Thank you for clarification @radarhere Your solutions works as a charm.
