### ISSUE TITLE
Segmentation fault on import when gi is imported

### ISSUE THREAD

**Issue by Fogapod** [python-pillow/Pillow#5637]
### What did you do?
```python
from gi.repository import Gtk
from PIL import ImageOps
```
### What did you expect to happen?
No errors
### What actually happened?
```
[1]    85601 segmentation fault (core dumped)  python azote/main.py
```
### What are your OS, Python and Pillow versions?

* OS: Arch Linux
* Python: 3.9.6
* Pillow: 8.3.1

EDIT: shorter code causing segfault

**Comment by radarhere** [comment]
So gi is https://pypi.org/project/PyGObject/

If I take our arch Docker image, and [add this in](https://github.com/radarhere/docker-images/commit/271e8d313bcc14fc03d61150f908761db72e2a09), there is [no problem.](https://github.com/radarhere/docker-images/runs/3161998366)

**Comment by radarhere** [comment]
At the start of ImageOps, we have
https://github.com/python-pillow/Pillow/blob/55cec2a0d0ea345705b27c0e12e0ad30af89ffb3/src/PIL/ImageOps.py#L20-L22

Are you able to test this locally, and see if it is not ImageOps causing the problem directly, but actually `functools`, `operator` or `re`? Maybe this crash can be replicated without importing Pillow at all. Does this code load for you?

```python
from gi.repository import Gtk
import functools
import operator
import re
```

**Comment by Fogapod** [comment]
> ```python
> from gi.repository import Gtk
> import functools
> import operator
> import re
> ```

This code works for me. (assuming there is also `from PIL import Image` before that)
I only get segfault behaviour when I import Image, then gi, then ImageOps.
Changing order or removing any step removes segfault.

**Comment by Fogapod** [comment]
Actually, this is wrong.
```python
from gi.repository import Gtk
from PIL import ImageOps
```
These 2 lines cause segfault. No Image import needed.

**Comment by Fogapod** [comment]
I tried pasting entire imageops file under `from gi.repository import Gtk`, it does not cause segfault.
`from PIL import Image` doesn't do it either. Only `ImageOps` is problematic for some reason

**Comment by Fogapod** [comment]
On 8.3.x branch which I have: https://github.com/python-pillow/Pillow/blob/8.3.x
There is ImageDraw import which imports ImageFont which imports _imagingft.

```python
from gi.repository import Gtk
from PIL import _imagingft
```
This c file causes segfault.

**Comment by wiredfool** [comment]
I bet you're getting a shared library conflict with freetype or one of the other things in the font stack.

**Comment by wiredfool** [comment]
To unpack a bit -- your gtk is going to have some associated versions of the freetype/raqm libs, and we're not necessarily going to ship the same ones in our binary wheels. Since you're hosting this in the same process, you need to have one version of the libraries, and that's going to be whatever is on your system that GTK is linking to. (assuming that your gtk is using system packages, because the wheels would be immense otherwise).

So try building Pillow from source --activate your virtualenv or whatever, clone the source and check out 8.3.1. Then `make install` in the pillow directory should give you something that works.

**Comment by Fogapod** [comment]
Swapping imports does not cause segmentation fault though. Does this mean gtk has some workaround/fallback for this conflict which Pillow does not?

**Comment by radarhere** [comment]
> On 8.3.x branch which I have: https://github.com/python-pillow/Pillow/tree/8.3.x
> There is ImageDraw import which imports ImageFont which imports _imagingft.

That import was removed by #5615. So if it helps you at all, that will be removed from ImageOps in the next release of Pillow, on October 15th.

**Comment by radarhere** [comment]
> So try building Pillow from source --activate your virtualenv or whatever, clone the source and check out 8.3.1. Then `make install` in the pillow directory should give you something that works.

While my last attempt to replicate was through `make` - installing [through pip](https://github.com/radarhere/docker-images/commit/295ee8f74666eb925fa541b06ec52430c09cfbbf) instead does [trigger the segfault.](https://github.com/radarhere/docker-images/runs/3166764637)

**Comment by radarhere** [comment]
How did you actually install Pillow?

**Comment by Fogapod** [comment]
Using pip, from pypi

**Comment by radarhere** [comment]
Thanks. If you're interested, a simpler alternative to installing through `make` should be to use pip without binary wheels - `pip install Pillow --no-binary :all:`

**Comment by explode** [comment]
I saw a similar conflict with matplotlib:

    import matplotlib.pyplot as plt
    from PIL import ImageDraw

will cause a segmentation fault, or swap the lines (i.e. import PIL first) and it works OK.
(OS: Ubuntu 20.04, Python: 3.8.10, pip: 21.2.2, Matplotlib: 3.4.2, Pillow: 8.3.1)

**Comment by wyatt8740** [comment]
> I bet you're getting a shared library conflict with freetype or one of the other things in the font stack.

Yeah, I have this happening on my Debian Sid machine right now (Pillow 8.3.1, installed via `pip3`). It seems to be segfaulting in `fribidi_load()` (when running [mcomix3](https://github.com/multiSnow/mcomix3/)).

    Program received signal SIGSEGV, Segmentation fault.
    r0x00007ffff27c196a in load_fribidi ()
       from /home/wyatt/.local/lib/python3.9/site-packages/PIL/_imagingft.cpython-39-x86_64-linux-gnu.so

Seems like swapping import ordering is working here, too, but I don't think that's really a good solution since there's still some incorrect behavior happening somewhere that's not fundamentally fixed. Also, it's not very "pythonic" to segfault if `import` ordering is switched up :)

**Comment by nulano** [comment]
I managed to reproduce this [on the wheel builder](https://github.com/nulano/pillow-wheels/runs/3224825740?check_suite_focus=true) and made a [potential fix](https://github.com/nulano/Pillow/commit/259c671a559bc3f5468e38a9af5661ebdc448a13) that [fixes the segfault](https://github.com/nulano/pillow-wheels/runs/3225309489?check_suite_focus=true#step:6:138).

@Fogapod @wyatt8740 Could you please test with the wheel from https://github.com/nulano/pillow-wheels/actions/runs/1091871497 (download the `wheels` artifact, unzip, and install the wheel with `python -m pip install Pillow-8.4.0.dev0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl`, using Python 3.9 x64)?

**Comment by Fogapod** [comment]
> I managed to reproduce this [on the wheel builder](https://github.com/nulano/pillow-wheels/runs/3224825740?check_suite_focus=true) and made a [potential fix](https://github.com/nulano/Pillow/commit/259c671a559bc3f5468e38a9af5661ebdc448a13) that [fixes the segfault](https://github.com/nulano/pillow-wheels/runs/3225309489?check_suite_focus=true#step:6:138).
> 
> @Fogapod @wyatt8740 Could you please test with the wheel from https://github.com/nulano/pillow-wheels/actions/runs/1091871497 (download the `wheels` artifact, unzip, and install the wheel with `python -m pip install Pillow-8.4.0.dev0-cp39-cp39-manylinux_2_5_x86_64.manylinux1_x86_64.whl`, using Python 3.9 x64)?

It worked:
```sh
$ python -c "from gi.repository import Gtk;from PIL import _imagingft"
<string>:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
```
Older Pillow:
```sh
$ python -c "from gi.repository import Gtk;from PIL import _imagingft"
<string>:1: PyGIWarning: Gtk was imported without specifying a version first. Use gi.require_version('Gtk', '3.0') before import to ensure that the right version gets loaded.
[1]    708711 segmentation fault (core dumped)  python -c "from gi.repository import Gtk;from PIL import _imagingft"
```

**Comment by wyatt8740** [comment]
@nulano yes, this wheel fixes my crash. Thank you.

**Comment by cydanil** [comment]
Thanks, I also encountered a similar issue with `pillow==8.3.1` and `PyGObject==3.40.1`.

I could reduce it down to the code below:

```python
import gi
from gi.repository import Gtk, Gdk, GdkPixbuf
from PIL import ImageDraw
```

which would segfault.

Modifying this excerpt by importing `pillow` first resolved the issue:
```python
import gi
from PIL import ImageDraw
from gi.repository import Gtk, Gdk, GdkPixbuf
```

With `pillow==8.3.0`, the order does not matter and the code runs fine.
The wheel linked above also resolves the issue in my case!

**Comment by radarhere** [comment]
Pillow 8.3.2 has just been released with the fix for this.
