### ISSUE TITLE
Converting "I" image to RGB issue

### ISSUE THREAD

**Issue by Lucuz91** [python-pillow/Pillow#5642]
Hi all,

I am trying to convert a png image to a jpeg. 
The image is opened in "I" mode, but when I convert to RGB and save it in jpeg the image is very different from the original.

* OS: Ubuntu 20.04
* Python: 3.8.5
* Pillow: 8.3.1

```python
from PIL import Image
img = Image.open('black_bands.png')
img2 = img.convert('RGB')
img2.save('black_bands_out.jpg')
```

Original image
![black_bands](https://user-images.githubusercontent.com/18615313/127346781-0cda4842-624c-4a64-bc80-b973b01a7baf.png)

Converted image
![black_bands_out](https://user-images.githubusercontent.com/18615313/127347187-89654654-79ef-4050-b84f-b3ba1b5f746d.jpg)

**Comment by radarhere** [comment]
This is something of a known issue. #4044 found this converting to RGBA, and #3159 talks about this problem more generally.

**Comment by radarhere** [comment]
Closing as part of #3159
