### ISSUE TITLE
Problem rotating P images

### ISSUE THREAD

**Issue by LIMr1209** [python-pillow/Pillow#5643]
```python
from PIL import Image
import random

img = Image.open('test.png')
rate = random.randint(30, 330)
img = img.rotate(rate)
img.show()
img.save('test_rotate.png')
```
![test](https://user-images.githubusercontent.com/37957822/127455530-f7437db9-b2df-4b89-be5b-5582b67b4eb8.png)
![test_rotate](https://user-images.githubusercontent.com/37957822/127455537-05a6a378-4ba9-4018-a22f-5f2dabbe6eea.png)

**Comment by LIMr1209** [comment]
The image generated by rotating the picture is a binary image

**Comment by radarhere** [comment]
If you're looking for an immediate solution, you can convert it to RGB after opening.

```python
from PIL import Image
import random

img = Image.open('test.png').convert('RGB')
rate = random.randint(30, 330)
img = img.rotate(rate)
img.show()
img.save('test_rotate.png')
```

**Comment by LIMr1209** [comment]
Thank you for your answer. It's useful

**Comment by radarhere** [comment]
This problem was introduced by #5552

**Comment by radarhere** [comment]
I've created PR #5647 to resolve this. If you want, you can test it to confirm that it fixes your problem.
