### ISSUE TITLE
WebP with Palette is saved as 24 Bit ?

### ISSUE THREAD

**Issue by rebb** [python-pillow/Pillow#5650]
### What did you do?

Try to save an 8bit paletted image as WebP.

### What did you expect to happen?

The WebP to show as 8Bit ( i used a 256 color palette ) in image viewers.

**However since i know little about WebP i'm unsure if it at all supports or needs an 8Bit Mode.**
Specifically, this part of the description of WebP made me assume that this might be the case :

( from https://developers.google.com/speed/webp )
"Lossless WebP compression uses already seen image fragments in order to exactly reconstruct new pixels. It can also use a local palette if no interesting match is found."

### What actually happened?

The WebP shows as 24Bit in image viewers.

### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: 3.8.10
* Pillow: 8.3.1

```python
import sys
from PIL import Image

fileName = sys.argv[1]

im = Image.open( fileName )
im = im.convert("P", palette = Image.ADAPTIVE, colors = 256 )

# saving a PNG for comparison purposes, the PNG saves as 8 bit - the WebP does not
im.save( fileName + ".out.png", "PNG", lossless = True )
im.save( fileName + ".out.webp", "WEBP", lossless = True )
```

Source Image :
![sourceImage](https://user-images.githubusercontent.com/3278522/128009041-462d7f08-2a88-4414-8e5c-757b55bead13.png)

**Comment by radarhere** [comment]
When you say 'in image viewers', could you give a more specific example?

Just to be as clear as possible, could you also attach a sample input image?

**Comment by rebb** [comment]
> 
> 
> When you say 'in image viewers', could you give a more specific example?
> 
> Just to be as clear as possible, could you also attach a sample input image?

Using XnView MP in this case. I attached the file i used for testing in the first post now.

**Comment by radarhere** [comment]
Thanks. I see what you're saying now.

It does seem to be possible for this to be implemented - https://developers.google.com/speed/webp/docs/webp_lossless_bitstream_specification#color_indexing_transform

**Comment by rebb** [comment]
Interesting :o
Thanks much for looking into this.

I really wasn't sure if WebP has one, but since it's lossless mode is supposed to compete with PNG ( which has PNG8 ), i just assumed it may ?

It's probably a bit of a niche thing to have, especially since WebP is already really efficient. But it might be nice (tm)

**Comment by rebb** [comment]
Granted, ImageMagick has the same behaviour, producing an 8bit PNG but a 24bit WebP when using these commandlines :

```magick sourceImage.png -type Palette -strip out.png
magick sourceImage.png -type Palette -strip -define webp:lossless=true out.webp```

So .. not really sure if this is what is supposed to happen, or the same issue o_O

**Comment by rebb** [comment]
Hmm .. testing it with cwebp from google's libwebp binary package also does the same.

The nice thing about cwebp is, it shows what it is doing - this is what it listed :

```
cwebp sourceImage.png lossless -m 6 -q 100 -o out.webp

Saving file 'out.webp'
File:      sourceImage.png
Dimension: 640 x 400
Output:    3472 bytes (0.11 bpp)
Lossless-ARGB compressed size: 3472 bytes
  * Header size: 179 bytes, image data size: 3268
  * Lossless features used: PALETTE
  * Precision Bits: histogram=4 transform=4 cache=1
  * Palette size:   36
```

So it looks like WebP does select Palette mode on it's own already.

I guess that means everything is working as intended after all, and it's just Image Viewers that either show confusing information, or the WebP format doesn't have/need the notion of "8bit encoding" when displaying it.

Since both XnView and Irfanview report 24bit depth for the WebP file that cwebp created.

I'll mark this as closed then i guess. Sorry for any confusion.
