### ISSUE TITLE
Saving images to stdout using some file formats does not write the image correctly

### ISSUE THREAD

**Issue by infmagic2047** [python-pillow/Pillow#5657]
### What did you do?

I created a image and saved it to stdout using PPM format.

### What did you expect to happen?

The image is written correctly.

### What actually happened?

Only the PPM header is written, and the image data is not.

### What are your OS, Python and Pillow versions?

* OS: Gentoo Linux
* Python: Tested with both 3.8.11 and 3.9.6
* Pillow: 8.3.1

```python
import sys
from PIL import Image

im = Image.frombytes('RGB', (4, 4), b'\0' * 48)
im.save(sys.stdout, 'ppm')
```

**Comment by infmagic2047** [comment]
Additional note: This bug only happens when saving to stdout. It does not seem to happen when saving to a named file, file object, or other file-like objects like BytesIO.

Interestingly, some other file formats are affected as well: when saving the image as JPEG, no data is written at all. With GIF the image is corrupted (see below). PNG seems to be unaffected, though.

GIF example:
```python
im = Image.frombytes('RGB', (4, 4), b'\xff\0\0' * 16)
im.save(sys.stdout, 'gif')
```
The output has two black pixels (unexpected) in lower left.

**Comment by wiredfool** [comment]
Sys.stdout is effectively a text file, the equivalent of io.StringIO, likely to be in utf-8 or your specific locale. https://docs.python.org/3/library/sys.html#sys.stdout  Pillow has never been able to save to a io.StringIO instance on python 3, it has always required a io.BytesIO.

Most image formats have invalid utf-8 sequences in them, so they're not generally going to work with sys.stdout, unless you explicitly write the binary data to the underlying stream as mentioned in the link.

**Comment by infmagic2047** [comment]
Well, Pillow should be able to convert `sys.stdout` to `sys.stdout.buffer` according to #5437. Testing with `sys.stdout.buffer` returns the same erroneous results as well.

**Comment by wiredfool** [comment]
Missed that change.
