### ISSUE TITLE
Image distortion in GIFs when I use crop

### ISSUE THREAD

**Issue by marunqi** [python-pillow/Pillow#5661]
```python
img = pil_img.open(img_path)
width, height = img.size
del_width = random.randint(1, 10)
del_height = random.randint(1, 10)
box = (0, 0, width - del_width, height - del_height)
frames = [img.crop(box) for frame in range(0, img.n_frames) if not img.seek(frame)]
frames[0].save(new_path, save_all=True, append_images=frames, loop=0, duration=img.info['duration'])
```
![fbdpow](https://user-images.githubusercontent.com/37137713/128654147-fd2f1a93-fdd5-4a84-a1a6-d618265823b3.gif)

**Comment by marunqi** [comment]
The gif after deal is bigger than 10M，so I can’t  upload it

**Comment by radarhere** [comment]
I'm able to upload it. Is this what you're seeing? So you're talking about the occasional frame having incorrect colours?

![out](https://user-images.githubusercontent.com/3112309/128654318-f1b84ea2-cc1c-4a9b-bb8a-3a31654d9157.gif)

**Comment by marunqi** [comment]
img = pil_img.open(img_path)
    width, height = img.size
    box = (0, 0, width - 10, height - 10)
    frames = [img.crop(box) for frame in range(0, img.n_frames) if not img.seek(frame)]
    frames[0].save(new_path, save_all=True, append_images=frames[:60], loop=0, duration=img.info['duration'])

![fbdpow](https://user-images.githubusercontent.com/37137713/128655006-c7b2b184-c14e-48cb-bd74-46ceeff1c45c.gif)

![new](https://user-images.githubusercontent.com/37137713/128655024-e5f309fe-5092-409f-b2e8-9e6d5beef8d2.gif)

I saved less frames to limit gif size，my results of crop is serious distortion

**Comment by radarhere** [comment]
What version of Pillow are you using? If I go back to Pillow 8.1.2, then I get your version. So I expect if you upgrade to a more recent version of Pillow, your output will be improved to match mine.

**Comment by marunqi** [comment]
I updated pillow to 8.3.1，but It doesn't work，neither 8.1.2

**Comment by radarhere** [comment]
To confirm that you are using the upgraded Pillow, does `print(pil_img.__version__)` show 8.3.1?

**Comment by marunqi** [comment]
8.3.1 In another gif 
![dtax03](https://user-images.githubusercontent.com/37137713/128657248-fa152cfa-7407-40b5-9a73-734ef6913d24.gif)

![new](https://user-images.githubusercontent.com/37137713/128657261-3c9ce484-90b5-4224-8137-003b9df9fbc8.gif)

**Comment by radarhere** [comment]
Pillow 9.0.0 has significantly improved reading animated GIFs thanks to #5857.

If this issue is still a problem when using Pillow 9.0.0, please let us know.
