### ISSUE TITLE
Automatically scale text size into bounding box area

### ISSUE THREAD

**Issue by cubeserverdev** [python-pillow/Pillow#5669]
I'm currently trying to use Pillow to render text of any length into a specific area (x1, y1, x2, y2) in an image in a way where it will automatically change the font size, amount of lines and words per line automatically. Looking into the python ``textwrap`` module as well as the ``ImageDraw`` class, I'm not quite sure as to where/how to start implementing the logic for this. I've looked into this answer describing how to render multiline text but I'm unsure of how I'd implement the code to automatically change the font size depending on the width and height of the area of the user provided text area.

I'm trying to get the text line count and font size to dynamically be modified to fit the regions in an image like so
![Example](https://user-images.githubusercontent.com/83846259/129154985-510df474-9c7d-40d9-ac89-44fefa11fd94.png)

How can I do this?

**Comment by radarhere** [comment]
The situation you describe is not 100% clear, since I don't know when to break a line vs when to just keep making the text smaller.

Here is code to scale multiline text down until it fits into a box. Perhaps that will be enough for you to figure out the rest.

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGB", (500, 200), "#fff")
box = ((10, 10, 490, 190))
draw = ImageDraw.Draw(im)
draw.rectangle(box, outline="#000")

text = "This is some\nexample text"
font_size = 100
size = None
while (size is None or size[0] > box[2] - box[0] or size[1] > box[3] - box[1]) and font_size > 0:
	font = ImageFont.truetype("Tests/fonts/FreeMono.ttf", font_size)
	size = font.getsize_multiline(text)
	font_size -= 1
draw.multiline_text((box[0], box[1]), text, "#000", font)
im.save("out.png")
```
![out](https://user-images.githubusercontent.com/3112309/129161866-c3332459-a770-4b59-bb42-b907c8eed767.png)

**Comment by radarhere** [comment]
@cubeserverdev was that enough, or did you have further questions?

**Comment by satheeshkatipomu** [comment]
@cubeserverdev, are you able to implement this? I am also trying to do similar thing. Please let me know if you provide some pointers.

**Comment by swport** [comment]
`getsize_multiline` has been deprecated.

**Comment by radarhere** [comment]
In the time since I wrote my answer, `getsize_multiline` has been deprecated, yes. As per https://pillow.readthedocs.io/en/stable/deprecations.html#font-size-and-offset-methods, you can use [`ImageDraw.multiline_textbbox`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.multiline_textbbox) instead.

**Comment by nulano** [comment]
You can see an example using the bbox functions here: https://github.com/python-pillow/Pillow/issues/6938#issuecomment-1426298209

**Comment by MarcoDiMarek** [comment]
> The situation you describe is not 100% clear, since I don't know when to break a line vs when to just keep making the text smaller.
> 
> Here is code to scale multiline text down until it fits into a box. Perhaps that will be enough for you to figure out the rest.
> 
> ```python
> from PIL import Image, ImageDraw, ImageFont
> 
> im = Image.new("RGB", (500, 200), "#fff")
> box = ((10, 10, 490, 190))
> draw = ImageDraw.Draw(im)
> draw.rectangle(box, outline="#000")
> 
> text = "This is some\nexample text"
> font_size = 100
> size = None
> while (size is None or size[0] > box[2] - box[0] or size[1] > box[3] - box[1]) and font_size > 0:
> 	font = ImageFont.truetype("Tests/fonts/FreeMono.ttf", font_size)
> 	size = font.getsize_multiline(text)
> 	font_size -= 1
> draw.multiline_text((box[0], box[1]), text, "#000", font)
> im.save("out.png")
> ```
> 
> ![out](https://user-images.githubusercontent.com/3112309/129161866-c3332459-a770-4b59-bb42-b907c8eed767.png)

You can also initialize the font outside the loop and adjust the font size inside the loop to avoid loading the font from the file in each iteration.
outside the loop:
`font = ImageFont.truetype("Tests/fonts/FreeMono.ttf", MAX_FONT_SIZE)`
inside the loop:
`font = font.font_variant(size=adjusted_font_size)`
