### ISSUE TITLE
Rename master to main after Oct 15 release

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#5671]
Via https://github.com/github/renaming, 

> Many communities, both on GitHub and in the wider Git community, are considering renaming the default branch name of their repository from master.

Leaving the "does it matter?" debate aside, and erring on the side of "every little bit helps", and mostly because I've gotten used to using "main" on other projects, I propose we do this after the next release (we're in mid cycle now).

Should be trivial-ish, but we'll need to pay attention in case any unintended consequences pop up. 👍

**Comment by aclark4life** [comment]
Done!

Also here's the commands GH recommends that I don't understand in case that helps anyone 😄 :

```

git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin -a

```

**Comment by hugovk** [comment]
That's if you have a local clone of this upstreams.

I'm renaming in my forks too, and then running those commands to update my local fork.

**Comment by hugovk** [comment]
PRs for those repos:

* [ ] https://github.com/python-pillow/docker-images/pull/121
* [ ] TODO https://github.com/python-pillow/pillow-depends
* [ ] TODO https://github.com/python-pillow/pillow-logo
* [ ] TODO https://github.com/python-pillow/pillow-scripts
* [ ] TODO https://github.com/python-pillow/pillow-wheels

@aclark4life Please can you check `main` is selected at https://github.com/python-pillow/python-pillow.github.io/settings/pages for:

* [ ] TODO https://github.com/python-pillow/python-pillow.github.io

**Comment by hugovk** [comment]
All the above PRs were merged and things are building smoothly!

@aclark4life If you like, for completeness, these can be renamed too:

* https://github.com/python-pillow/grant-proposal
* https://github.com/python-pillow/grant-proposal2
* https://github.com/python-pillow/podcast-answers

And @homm: would you to rename the branch for https://github.com/python-pillow/pillow-perf? Looks like no code changes will be needed.

And same question for @manisandro about https://github.com/python-pillow/Sane, again no code changes needed.

**Comment by radarhere** [comment]
pillow-perf and Sane have now renamed master to main.

**Comment by radarhere** [comment]
If it's alright, assigning to @aclark4life, since the remaining parts of this - grant-proposal, grant-proposal2 and podcast-answers - can only be completed by him.

**Comment by aclark4life** [comment]
Will do thanks

**Comment by aclark4life** [comment]
Done! Thanks all, happy holidays 🦃
