### ISSUE TITLE
Please replace `num_frames` with `n_frames` in documentation

### ISSUE THREAD

**Issue by kawa-yo** [python-pillow/Pillow#5677]
I'm now working with .tiff images.

According to [PIL tiff doc](https://github.com/python-pillow/Pillow/blob/92933b86574b9c80764bf52c357ed29e1ef53382/docs/handbook/image-file-formats.rst#tiff),
it seems that `Image.num_frames` is the field to get number of pages,
but I had a problem with `AttributeError: num_frames`.

After some minutes' investigation, I found `Image.n_frames` is the correct one.

PIL will be more powerful and helpful library by refining documentation.

**Comment by radarhere** [comment]
Absolutely. I've created PR #5678 to resolve this.
