### ISSUE TITLE
Release Pillow 8.3.2 on September 2, 2021

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#5697]
Point release to include Python 3.10 wheels (https://github.com/python-pillow/Pillow/issues/5569) and some regressions (https://github.com/python-pillow/Pillow/issues/5569#issuecomment-907086699).

## Point Release

Released as needed for security, installation or critical bug fixes.

* [x] Make necessary changes in `master` branch.
* [x] Update `CHANGES.rst`.
* [x] Check out release branch e.g.:
  ```bash
  git checkout -t remotes/origin/5.2.x
  ```
* [x] Cherry pick individual commits from `master` branch to release branch e.g. `5.2.x`, then `git push`.
* [ ] Check [GitHub Actions](https://github.com/python-pillow/Pillow/actions) and [AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm passing tests in release branch e.g. `5.2.x`.
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Run pre-release check via `make release-test`.
* [x] Create tag for release e.g.:
  ```bash
  git tag 5.2.1
  git push
  git push --tags
  ```
* [x] Create and check source distribution:
  ```bash
  make sdist
  twine check dist/*
  ```
* [x] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/master/RELEASING.md#binary-distributions)
* [x] Check and upload all binaries and source distributions e.g.:
  ```bash
  twine check dist/*
  twine upload dist/Pillow-5.2.1*
  ```
* [x] Publish the [release on GitHub](https://github.com/python-pillow/Pillow/releases)

### Windows
* [x] Contact `@cgohlke` for Windows binaries via release ticket e.g. https://github.com/python-pillow/Pillow/issues/1174.
* [x] Download and extract tarball from `@cgohlke` and copy into `dist/`

### Mac and Linux
* [x] Use the [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels):
  ```bash
  git clone https://github.com/python-pillow/pillow-wheels
  cd pillow-wheels
  ./update-pillow-tag.sh [[release tag]]
  ```
* [x] Download wheels from the [Pillow Wheel Builder release](https://github.com/python-pillow/pillow-wheels/releases)
  and copy into `dist/`

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the [default version for Read the Docs](https://pillow.readthedocs.io/en/stable/) is up-to-date with the release changes

## Docker Images

* [x] Update Pillow in the Docker Images repository
  ```bash
  git clone https://github.com/python-pillow/docker-images
  cd docker-images
  ./update-pillow-tag.sh [[release tag]]
  ```

**Comment by radarhere** [comment]
For the purposes of https://pillow.readthedocs.io/en/latest/installation.html#python-support, I presume that Pillow 8.3.2 doesn't support 3.10, right?

**Comment by hugovk** [comment]
Good question!

We'll have wheels and the 3.10 classifier and updated Windows exit warning from https://github.com/python-pillow/Pillow/pull/5570.

We could do: Python 3.10 isn't officially out yet, we don't support it until 3.10 final and Pillow 8.4.0.

I suggest we do: 3.10 is in RC, we support it in 8.3.2, in the rare case that 3.10 final isn't ABI compatible with the RC, we'll make an update for 8.4.0.

So update the table like this?

* Pillow >= 8.3.2 supports 3.10
* Pillow 8.0 - 8.3.1 doesn't support 3.10

**Comment by hugovk** [comment]
Plan: I'm going to update the branches today (1st September) and tag and release tomorrow (2nd September).

**Comment by hugovk** [comment]
CIFuzz is failing on the `8.3.x` branch, but is also failing on `master`, both pre- and post release changes, so I think this is unrelated to the release changes and will continue the release. Let's follow up later.

* https://github.com/python-pillow/Pillow/actions/workflows/cifuzz.yml

**Comment by hugovk** [comment]
@cgohlke Please could we have Windows binaries, including for Python 3.10 RC1?

**Comment by cgohlke** [comment]
>could we have Windows binaries, including for Python 3.10 RC1?

The tests quit unexpectedly at 76% `TestImageFont::test_variation_set_by_name`. Need some time to investigate...

**Comment by wiredfool** [comment]
CI fuzz is failing, there's an issue in the oss-fuzz project. I can't reproduce locally, so I'm not sure what's up.

**Comment by cgohlke** [comment]
Has this release been tested with FreeType 2.11.0? I get a segfault in `TestImageFont::test_variation_set_by_axes` at https://github.com/python-pillow/Pillow/blob/8013f130a5077b238a4346b73e149432b180a8ea/src/_imagingft.c#L618

```
[0x0]   _imagingft_cp39_win_amd64!FT_Stream_Open + 0x7d07   
[0x1]   _imagingft_cp39_win_amd64!FT_Stream_Open + 0xd10   
[0x2]   _imagingft_cp39_win_amd64!FT_Load_Glyph + 0x30c   
[0x3]   _imagingft_cp39_win_amd64!font_getsize + 0x2dd
```

**Comment by hugovk** [comment]
We're currently testing against FreeType 2.10.4:

https://github.com/python-pillow/Pillow/blob/8013f130a5077b238a4346b73e149432b180a8ea/winbuild/build_prepare.py#L188

**Comment by nulano** [comment]
There is a known issue in FreeType 2.11.0 (found by @radarhere): https://gitlab.freedesktop.org/freetype/freetype/-/issues/1075

**Comment by cgohlke** [comment]
> could we have Windows binaries, including for Python 3.10 RC1?

[Here](https://www.lfd.uci.edu/~gohlke/download/Pillow-8.3.2-win-dist.zip) you go.

**Comment by hugovk** [comment]
Thanks!

And released!

* https://pypi.org/project/Pillow/8.3.2/
* https://pypi.org/project/Pillow/8.3.2/#files
* https://pillow.readthedocs.io/en/stable/releasenotes/8.3.2.html

```console
$ python3.10 -m pip install -U pillow
Requirement already satisfied: pillow in /Users/hugo/.pyenv/versions/3.10-dev/lib/python3.10/site-packages (8.3.1)
Collecting pillow
  Downloading Pillow-8.3.2-cp310-cp310-macosx_10_10_universal2.whl (3.0 MB)
     |████████████████████████████████| 3.0 MB 5.1 MB/s
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 8.3.1
    Uninstalling Pillow-8.3.1:
      Successfully uninstalled Pillow-8.3.1
Successfully installed pillow-8.3.2
```

Will tweet a bit later.

**Comment by hugovk** [comment]
🚀  https://twitter.com/PythonPillow/status/1433517261118185473

**Comment by jeeloo** [comment]
In our environment we are installing pillow as a dependency for another package and now after this release it started to try and compile pillow from source instead of installing a package. Any thoughts on this behavior  ? This is running in Ubuntu 18.04, with python 3.6.9.

**Comment by hugovk** [comment]
I just spotted `Pillow-8.3.2-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl` failed to download yesterday from https://github.com/python-pillow/pillow-wheels/releases so didn't go to PyPI.

Now uploaded:

* https://pypi.org/project/Pillow/8.3.2/#files

**Comment by hugovk** [comment]
For reference, noting we uploaded some manylinux1 and manylinux2010 wheels too: https://github.com/python-pillow/Pillow/issues/5701.
