### ISSUE TITLE
McAfee Endpoint Security reports a threat on _imagingft.cp39-win_amd64.pyd in 8.3.2

### ISSUE THREAD

**Issue by studioj** [python-pillow/Pillow#5716]
### What did you do?
`pip install pillow==8.3.2`

### What did you expect to happen?
- File not deleted by McAfee

### What actually happened?
- file detected as a trojan Artemis!6B0B201C2E37 (_imagingft.cp39-win_amd64.pyd)

![image](https://user-images.githubusercontent.com/22102283/133650141-e107a903-43b3-4c10-9c77-d4c53fd73296.png)

### What are your OS, Python and Pillow versions?

* OS: Windows10
* Python: 3.9.5
* Pillow: 8.3.2

A bug report with a possible false detection will be filed with McAfee
just wanted to make sure people searching for this issue would have a place to land

**Comment by studioj** [comment]
possibly similar to https://github.com/numpy/numpy/issues/19040

**Comment by studioj** [comment]
it wasnt detected as positive in the 3.7 whl

**Comment by radarhere** [comment]
With https://github.com/numpy/numpy/issues/19040, it looks like McAfee responded after 2 weeks. So let's see how that goes.

**Comment by radarhere** [comment]
@studioj nothing yet?

**Comment by studioj** [comment]
@radarhere no not yet. Our point of contact with McAfee is on holiday ... I didn't think this to be super urgent. I actually have no idea if I could contact McAfee ourselves

**Comment by studioj** [comment]
@radarhere, We submitted the files to McAfee last Wednesday without any proper response. But after retrying today the issue isnt reproducible anymore. I'll close
