### ISSUE TITLE
How to load my own TifImagePlugin.py 

### ISSUE THREAD

**Issue by mkmohamed** [python-pillow/Pillow#5721]
Hi community,
i would like to process .tif images. I use for this my own TifImagePlugin which is intended to define and read certain information from these images such as: Exposure Time, Local Time, etc .... 

When I type:
```python
from PIL import Image, ImageFile
import TifImagePlugin
d=Image.open('/home/mk-laptop/054/6300_0010.tif')
print(d.info.keys())
```
it returns only: dict_keys(['compression', 'resolution']) and several keys which the script must provide are missing which means that my script does not load the TifImagePlugin module.

On Ipython3 prompt:
```
 from PIL import Image                                                                         
 import TifImagePlugin                                                                         
 with Image.open('/home/mk-laptop/Desktop/054/6300_0031.tif') as d: 
   ...:     print(d) 
   ...:     print(d.format) 
   ...:     print(d.format_description) 
   ...:                                                                                               
```
```
<PIL.TiffImagePlugin.TiffImageFile image mode=I;16 size=728x490 at 0x7FC54C0326A0>
TIFF
Adobe TIFF
```

**So it loads the TiffImagePlugin and not TifImagePlugin.**

I tried to place TifImagePlugin.py on the location which contains the other ImagePlugins from PIL (like TiffImagePlugin and others)

Please I will be very grateful if you could help me to resolve this problem

**Comment by radarhere** [comment]
You shouldn't need to place your plugin in the plugin directory.

Your image plugin calls `register_open`?
```python
Image.register_open(TifImageFile.format, TifImageFile, _accept)
```

In general, you've seen https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-file-decoder.html ?

**Comment by mkmohamed** [comment]
Hi @radarhere  here is the TifImagePlugin I use to read the .tif images, ans YES i my image plugin calls register_open:

from PIL import Image, ImageFile
import string
import struct
import datetime

class TifImageFile(ImageFile.ImageFile):

    format = "TIF"
    format_description = "Garcia Image Format"

    def _open(self):

        # Skip the TIF header stuff
        self.fp.seek(200)

        # check header
        FileIdentifier = self.fp.read(3)
        if FileIdentifier != "CDF":
            raise SyntaxError("not a CDF TIF file")

        # Read in the number of rows and columns
        rows = struct.unpack('h', self.fp.read(2))
        cols = struct.unpack('h', self.fp.read(2))

        # Read in the autoscaled min and max pixel values
        pmin = struct.unpack('h', self.fp.read(2))
        pmax = struct.unpack('h', self.fp.read(2))

        # Read in the local and universal time structures
        tmp = struct.unpack('18h', self.fp.read(2*18))
        LocalTime = datetime.datetime(tmp[10]+1900,tmp[8]+1,tmp[6],tmp[4],tmp[2],tmp[0])
        tmp = struct.unpack('18h', self.fp.read(2*18))
        UniversalTime = datetime.datetime(tmp[10]+1900,tmp[8]+1,tmp[6],tmp[4],tmp[2],tmp[0])

        # Read the filter name
        tmp = struct.unpack('12s', self.fp.read(12))
        Filter = tmp[0].split('\x00')[0]

        # Read the emission height
        EmissionHeight = struct.unpack('f', self.fp.read(4))

        # Read the exposure time
        ExposureTime = struct.unpack('f', self.fp.read(4))

        # Read in CCD parameters
        gain = struct.unpack('B', self.fp.read(1))
        XBinning = struct.unpack('B', self.fp.read(1))
        YBinning = struct.unpack('B', self.fp.read(1))
        CCDTemperature = struct.unpack('f', self.fp.read(4))

        # Read in the FW temperature
        FWTemperature = struct.unpack('f', self.fp.read(4))

        # Read in XY spacing
        XSpacing = struct.unpack('f', self.fp.read(4))
        YSpacing = struct.unpack('f', self.fp.read(4))

        # Read in the spatial calibration coefficients
        a0 = struct.unpack('d', self.fp.read(8))
        a1 = struct.unpack('d', self.fp.read(8))
        a2 = struct.unpack('d', self.fp.read(8))
        b0 = struct.unpack('d', self.fp.read(8))
        b1 = struct.unpack('d', self.fp.read(8))
        b2 = struct.unpack('d', self.fp.read(8))
        Calibration = (a0[0], a1[0], a2[0], b0[0], b1[0], b2[0])

        # Read in site location
        lat = struct.unpack('f', self.fp.read(4))
        lon = struct.unpack('f', self.fp.read(4))
        alt = struct.unpack('f', self.fp.read(4))
        tmp = struct.unpack('30s', self.fp.read(30))
        Observatory = (tmp[0].split('\x00')[0], lat[0], lon[0], alt[0])

        # Read in comment
        tmp = struct.unpack('100s', self.fp.read(100))
        Comment = tmp[0].split('\x00')[0]

        # Read in additional information
        isAllSky = struct.unpack('B', self.fp.read(1))
        CenterAz = struct.unpack('d', self.fp.read(8))
        CenterEl = struct.unpack('d', self.fp.read(8))
        ProjectionAltitude =  struct.unpack('f', self.fp.read(4))
        ProjectionLon = struct.unpack('f', self.fp.read(4))
        tmp = struct.unpack('63B', self.fp.read(63))

        # Save pertinent header info
        self.info = {'LocalTime':LocalTime, 'UniversalTime': UniversalTime,
                     'pmin': pmin[0], 'pmax': pmax[0], 'Filter': Filter,
                     'EmissionHeight': EmissionHeight[0], 'ExposureTime': ExposureTime[0],
                     'gain': gain[0], 'XBinning': XBinning[0], 'YBinning': YBinning[0],
                     'CCDTemperature': CCDTemperature[0], 'FWTemperature': FWTemperature[0],
                     'Calibration': Calibration, 'Observatory': Observatory,
                     'Comment': Comment, 'isAllSky': isAllSky[0], 'CenterAz': CenterAz[0],
                     'CenterEl': CenterEl[0], 'ProjectionAltitude': ProjectionAltitude[0],
                     'ProjectionLon': ProjectionLon[0]}

        # size in pixels (width, height)
        self._size = rows[0], cols[0]

        # mode setting
        self.mode = "I;16L"

        # data descriptor
        self.tile = [
            ("raw", (0, 0) + self.size, 600, (self.mode, 0, 1))
        ]

Image.register_open(TifImageFile.format, TifImageFile, _accept)

#Image.register_open("TIF", TifImageFile)

Image.register_extension("TIF", ".tif")

**Comment by radarhere** [comment]
Is it possible that your plugin is throwing an error when it tries to load the file?

For example, when I run the following code, 

```python
from PIL import Image
import TifImagePlugin
with Image.open("Tests/images/no_rows_per_strip.tif") as im:
	print(im)
```

I get
```
<PIL.TiffImagePlugin.TiffImageFile image mode=P size=950x975 at 0x105262340>
```

That's not because your plugin isn't running, it's because your plugin is throwing an error, and Pillow is moving on to try other formats.

To see this, I call your plugin directly

```python
from PIL import Image
import TifImagePlugin
with open("Tests/images/no_rows_per_strip.tif", "rb") as fp:
	TifImagePlugin.TifImageFile(fp, "Tests/images/no_rows_per_strip.tif")
```

and get

```
Traceback (most recent call last):
  File "script.py", line 4, in <module>
    TifImagePlugin.TifImageFile(fp, "Tests/images/no_rows_per_strip.tif")
  File "PIL/ImageFile.py", line 121, in __init__
  File "TifImagePlugin.py", line 22, in _open
    raise SyntaxError("not a CDF TIF file")
SyntaxError: not a CDF TIF file
```

**Comment by mkmohamed** [comment]
Thank you @radarhere to spend you time on this; when i called TifImagePlugin directly i got:

with Image.open("/home/mk-laptop/Desktop/054/6300_0024.tif") as fp: 
   ...:     TifImagePlugin.TifImageFile(fp, "/home/mk-laptop/Desktop/054/6300_0024.tif") 
   ...:                                                                                         
Traceback (most recent call last):

  File "/home/mk-laptop/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-6-ad8170d7e434>", line 2, in <module>
    TifImagePlugin.TifImageFile(fp, "/home/mk-laptop/Desktop/054/6300_0024.tif")

  File "/home/mk-laptop/anaconda3/lib/python3.7/site-packages/PIL/ImageFile.py", line 129, in __init__
    raise SyntaxError(v) from v

  File "<string>", line unknown
SyntaxError: attempt to seek outside sequence

Do you have any idea on how i can resolve this...

**Comment by radarhere** [comment]
You've misread my code slightly. `fp` is not the image, it is the file contents.

Instead of

```python
with Image.open("/home/mk-laptop/Desktop/054/6300_0024.tif") as fp: 
    TifImagePlugin.TifImageFile(fp, "/home/mk-laptop/Desktop/054/6300_0024.tif") 

```

do this

```python
with open("/home/mk-laptop/Desktop/054/6300_0024.tif", "rb") as fp: 
    TifImagePlugin.TifImageFile(fp, "/home/mk-laptop/Desktop/054/6300_0024.tif") 

```

Alternatively, you could try posting 6300_0024.tif here.

**Comment by mkmohamed** [comment]
It returns the same error did you get:

`In [15]: with open("/home/mk-laptop/Desktop/054/6300_0024.tif", "rb") as fp: 
    ...:     TifImagePlugin.TifImageFile(fp, "/home/mk-laptop/Desktop/054/6300_0024.tif") 
    ...:                                                                                        
Traceback (most recent call last):

  File "/home/mk-laptop/anaconda3/lib/python3.7/site-packages/IPython/core/interactiveshell.py", line 3296, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)

  File "<ipython-input-15-b219b4ff69cd>", line 2, in <module>
    TifImagePlugin.TifImageFile(fp, "/home/mk-laptop/Desktop/054/6300_0024.tif")

  File "/home/mk-laptop/anaconda3/lib/python3.7/site-packages/PIL/ImageFile.py", line 121, in __init__
    self._open()

  File "/home/mk-laptop/anaconda3/lib/python3.7/site-packages/TifImagePlugin.py", line 40, in _open
    raise SyntaxError("not a CDF TIF file")

  File "<string>", line unknown
SyntaxError: not a CDF TIF file
`
For the image; it's not supported here. If you want i can send it to you by email or other way

**Comment by radarhere** [comment]
You can compress the image into a zip or tgz, and then attach that file.

**Comment by mkmohamed** [comment]
[6300_0024.zip](https://github.com/python-pillow/Pillow/files/7191932/6300_0024.zip)

**Comment by radarhere** [comment]
Testing with that file, I find that if I modify your code by replacing
```python
if FileIdentifier != "CDF":
```
with
```python
if FileIdentifier != b"CDF":
```
and similarly replace all three instances of `'\x00'` with `b'\x00'`, then your plugin runs without an error.

**Comment by mkmohamed** [comment]
WOW!!!!! Thank you very much. Finally the script returns keys values intended... thank you @radarhere
