### ISSUE TITLE
Inconsistent Image.fromarray() behaviour with mode '1'

### ISSUE THREAD

**Issue by dtoniolo** [python-pillow/Pillow#5723]
### What did you do?
The following code can reproduce the issue:
```python
import numpy as np
import PIL
from PIL import Image

print('Testing for Pillow version', PIL.__version__)


img_size = (2, 3)  # (w, h)
rng = np.random.default_rng()

test = rng.integers(0, 2, dtype=np.bool_, size=img_size[::-1])
no_mode = Image.fromarray(test)
no_mode_arr = np.array(no_mode)
outcome = np.all(no_mode_arr == test)
print('No mode specified. Mode:', no_mode.mode, 'dtype:',
      no_mode_arr.dtype, 'outcome:', outcome)
with_mode = Image.fromarray(test, mode='1')
with_mode_arr = np.array(with_mode)
outcome = np.all(with_mode_arr == test)
print('Mode specified. Mode:', with_mode.mode, 'dtype:',
      with_mode_arr.dtype, 'outcome:', outcome)

print('Input array:\n', test)
print('Output array with no mode specified:\n', no_mode_arr)
print('Output array with mode specified:\n', with_mode_arr)
```
Output:
```python
Testing for Pillow version 8.3.2
No mode specified. Mode: 1 dtype: bool outcome: True
Mode specified. Mode: 1 dtype: bool outcome: False
Input array:
 [[ True False]
 [ True False]
 [False False]]
Output array with no mode specified:
 [[ True False]
 [ True False]
 [False False]]
Output array with mode specified:
 [[False False]
 [False False]
 [False False]]
```

### What did you expect to happen?
When initialising an image from a boolean NumPy array, it is expected that `True` values are assigned to white pixels and `False` values to black ones. The resulting image should have `mode` `'1'` and if, converted back to an array, its contents should be equal to the initial input array.

### What actually happened?
If `Image.fromarray()` is called with `mode=None`, the code works as expected. If instead it is called with `mode='1'`, the array results in all `False` values. This is an issue for two reasons.

1. The conversion of the data is incorrect.
1. The behaviour of `Image.fromarray()` is inconsistent: given that when called with `mode=None` it detects the data as having `mode='1'`, passing `mode='1'` as an input argument should *not* change the result.

### What are your OS, Python and Pillow versions?
I have run the script with two different conda virtual environments. The OS is macOS Big Sur v11.5.2 (20G95). 
- Env 1:
  - * Python: 3.8.10
  - * Pillow: 8.3.2
- Env 2:
  - * Python: 3.8.10
  - * Pillow: 7.1.2

**Comment by radarhere** [comment]
Hi. This seems to be a duplicate of #5465. Try having a read through the comments there.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/issues/5465#issuecomment-831833783
> Mode for fromarray is the ["Mode to use"](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray). I think this is the mode to use when reading the numpy data - if so, then it makes sense that the values change when it is told to interpret the input data directly.

By default, the boolean data is inferred to have a mode of 1 and a rawmode of 1;8. Because you are explicitly setting it, they both become 1, and so the output data is different.

https://github.com/python-pillow/Pillow/issues/5465#issuecomment-831871276
> I think that the mode to use parameter is a footgun. It’s not an implicit conversion, it’s a cast.

**Comment by dtoniolo** [comment]
Yes, it's definitely the same issue, thanks

**Comment by radarhere** [comment]
The raw mode is the mode of the incoming data.
Pillow converts (unpacks) the data from the `rawmode` to the `mode` as a way of normalising it, reducing the number of modes that we have to support operations for.

Here is the unpack method from 1;8 to 1 - https://github.com/python-pillow/Pillow/blob/ffde039f26a5587dacf0d9fb86cbfe9e5e8bb7ba/src/libImaging/Unpack.c#L246-L255

As opposed to our method for just unpacking 1 to 1 - https://github.com/python-pillow/Pillow/blob/ffde039f26a5587dacf0d9fb86cbfe9e5e8bb7ba/src/libImaging/Unpack.c#L110-L142

**Comment by dtoniolo** [comment]
Ok, now it is starting to get more clear, thanks. Do you know if there's a table of all the possible rawmodes and the implicit conversions that users can read?

**Comment by radarhere** [comment]
For `fromarray`?

https://github.com/python-pillow/Pillow/blob/d76fd93a77eee4ea80b911928a09780d764c506e/src/PIL/Image.py#L2877-L2902

**Comment by dtoniolo** [comment]
Thanks
