### ISSUE TITLE
Improperly saving gif frame with some gif images

### ISSUE THREAD

**Issue by mrnextdoor0000** [python-pillow/Pillow#5734]
```python
from PIL import Image, ImageSequence

def getframe(src, out):
    with Image.open(src) as img:
        print(f'file opened')
        i = 0
        for frame in ImageSequence.Iterator(img):
            if i == 1:
                frame.save(out)
                break
            else:
                i += 1
```

i used this method to get a 2nd frame of a gif image.
i got the frame but it was not good.
source gif:
![test7](https://user-images.githubusercontent.com/88737649/134798657-8b1df440-acd9-4d3e-b8ae-9ce7185c929c.gif)

result 2nd frame i got (gif format):
![result7](https://user-images.githubusercontent.com/88737649/134798698-f810ad8f-1b7a-4b61-b9e7-68e22d46a640.gif)

i tried to get 1st frame and 1st frame was very good unlike the 2nd.

i also tried another gif image has transparency.
i added convert function before save the frame
```python
frame = frame.convert('RGB')
```
source gif:
![test8](https://user-images.githubusercontent.com/88737649/134798915-eb0ed794-9ab8-4709-8321-e44dafa373df.gif)

result 2nd frame i got (jpg format):
![result8](https://user-images.githubusercontent.com/88737649/134798935-3d0dce06-356e-45e3-a9e4-f6269a73063f.jpg)

i think the second case was occured since i did not set the background color. But there is no options about background of jpeg with `Image.save()`.

There is some bug.. or something i missed.
Please let me know, thank you.

i used python 3.9.7 and pillow 8.3.2

**Comment by mrnextdoor0000** [comment]
I tried to get frames of Merty Christmas file with another tools, photoscape, photoshop and they gave fine frames. So I think it might be a problem with decoding gif format in pillow.

**Comment by radarhere** [comment]
There is a known bug in Pillow when reading subsequent GIF frames with different palettes. For example, see #4977 for instance, which bizarrely enough, is dealing with your exact same image.

**Comment by mrnextdoor0000** [comment]
I found similar issues, #1692 , #1717 . It seems that no one has solved it in about 5 years..

**Comment by wiredfool** [comment]
@mrnextdoor0000  Feel free to send a PR!

**Comment by tomhaydn** [comment]
Related to #5837 ?

**Comment by radarhere** [comment]
#5857 will help with the first image. Here is the second frame with that PR.

![out](https://user-images.githubusercontent.com/3112309/143830813-c3d9254b-66a1-432a-9fd2-6b4b060dba0f.gif)

**Comment by radarhere** [comment]
For the second image, the background color is actually coming from the image. The way that GIF stores transparency is by designating a certain color to the "transparent" one. So when you remove that transparency in order to save it as a non-transparent JPEG, it becomes visible.

If you want to select a background color, here is an example where green is the background color -

```python
from PIL import Image

with Image.open("source.gif") as img:
    img.seek(1)
    img = img.convert("RGBA")
    background = Image.new("RGB", img.size, "#0f0")
    background.paste(img, (0, 0), img)
    background.save("out.jpg")
```

![out](https://user-images.githubusercontent.com/3112309/143833552-36dd3f1c-fa47-418c-abf7-e813865b07ab.jpg)

Let us know if that isn't satisfactory for any reason.
