### ISSUE TITLE
How to cross-compile?

### ISSUE THREAD

**Issue by Zero960612** [python-pillow/Pillow#5742]
I want to cross-compiling it, but I met a error:

/usr/include/i386-linux-gnu/bits/mathinline.h:751:3: error: invalid 'asm': invalid operand for code 'w'

Does anybody know how to deal with it?
thanks!

**Comment by radarhere** [comment]
Could we get a complete error log?

**Comment by Zero960612** [comment]
thank you for reply!
I don't know how to get complete error log,but i can provide the screenshot to you,I hope it can help.





I have searched for solution,then there are same solution said that path has problem, it shouldn't include '/usr',but I don't know how to set the include path,I hope you can help me!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "python-pillow/Pillow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 下午5:12
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [python-pillow/Pillow] How to cross-compiling it? (#5742)





 
Could we get a complete error log?
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by aclark4life** [comment]
Have we ever cross compiled Pillow for … say … raspberry pi? E.g. https://github.com/bazelbuild/bazel/issues/4765 If so, maybe that knowledge would be appropriate here. I don't recall off hand …

**Comment by Zero960612** [comment]
ok, i will see it ,thank you for you help!




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "python-pillow/Pillow"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月30日(星期四) 下午5:29
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [python-pillow/Pillow] How to cross-compiling it? (#5742)





 
Have we ever cross compiled Pillow for … say … raspberry pi? E.g. bazelbuild/bazel#4765 If so, maybe that knowledge would be appropriate here. I don't recall off hand …
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by wiredfool** [comment]
I don't think that we've ever cross compiled, when we did the pi stuff it was on a pi. I think the closest we get is running a docker image in a qemu cross platform mode.

**Comment by radarhere** [comment]
@Zero960612 did those answers help? If you have that screenshot, it would be good.
