### ISSUE TITLE
The headers or library files could not be found for zlib,   a required dependency when compiling Pillow from source

### ISSUE THREAD

**Issue by romayankin** [python-pillow/Pillow#5745]
This is a Bug report:

### What did you do?
I run pip install -r requirements.txt on the https://github.com/k-tamura/easybuggy4django.git

### What did you expect to happen?
Compile the project

### What actually happened?
The error which is in the title - it does seem to be a relatively common issue as far as I can tell from the search results I got on Google. But I do use the latest version of PIP (21.2.4), latest version of Pillow available to date (8.3.2) and Python 3.2 so I'm stuck with no resolution.

### What are your OS, Python and Pillow versions?

* OS: Mac 11.4
* Python: 3.9
* Pillow: 8.3.2

The error log is pretty lengthy so I had to paste it into the gist:
https://gist.github.com/romayankin/280f5ef88f31adf7bf2852a5f0aa0304

**Comment by radarhere** [comment]
You say that you're using the latest version of Pillow, except that's not what's listed in the requirements.txt, or in your gist

https://github.com/k-tamura/easybuggy4django/blob/6a1a494417ad96f52fec6942217be8482fcffe22/requirements.txt#L8
> Pillow==5.1.0

Pillow 5.1.0 was released about two years before macOS 11 was released, so it's not surprising that we don't have pre-built wheels for it.

The easiest solution would be to switch to using the latest version of Pillow and try again.

**Comment by nulano** [comment]
The [installation docs](https://pillow.readthedocs.io/en/stable/installation.html#python-support) don't even list Pillow 5.1.0 as supporting Python 3.8, much less Python 3.9. The earliest version of Pillow with Python 3.9 support is Pillow 8.0.0, so you could also try that in case the latest Pillow 8.3.2 isn't compatible with your project.

**Comment by romayankin** [comment]
@radarhere Thank you very much for your support - you are correct I did not notice the version that was in the requirements, the issue is now closed
