### ISSUE TITLE
Cannot load LZW compressed grayscale image

### ISSUE THREAD

**Issue by nkoerb** [python-pillow/Pillow#5749]
Python hangs up when loading LZW compressed tiff. When I save the image as tiff without compression the code works fine.
Did not had the same issue with other versions of PIL and/or numpy. 
The issue could be related to numpy or libtiff (v 4.3)

```python
import PIL
from PIL import Image
import numpy as np

print(PIL.__version__)
# 8.3.1
print(np.__version__)
# 1.20.3

def main():
    image = Image.open('my_image.tif')
    print(image.mode)
    #'L'    
    np.array(image)
    # python hangs up here


if __name__ == "__main__":
    main()
```
[my_image.zip](https://github.com/python-pillow/Pillow/files/7302493/my_image.zip)

**Comment by nkoerb** [comment]
update:
with `image.load()` it hangs, too

**Comment by radarhere** [comment]
@nkoerb was that previous comment helpful?

**Comment by nkoerb** [comment]
Hey @radarhere, 
I checked and with pillow from conda-forge it works. So I guess this is a duplicate of #5640.

**Comment by radarhere** [comment]
Thanks
