### ISSUE TITLE
Pillow should have a logo

### ISSUE THREAD

**Issue by al45tair** [python-pillow/Pillow#575]
This notion came out of #565, where I needed an icon file to test against. I knocked something simple up and checked it in to my fork of Pillow; I also turned on [Github pages for my fork](http://al45tair.github.io/Pillow/) and had a quick bash at using the logo on there. Comments welcome (remembering that it’s up to @wiredfool and @aclark4life to make any final decisions).

**Comment by aclark4life** [comment]
FYI I'm going to officially assume that the Pillow logo qualifies as
```
Use of derived logos for freely distributed 3rd-party modules or tools 
-- Allowed if for the Python programming language
```
(excerpted from https://www.python.org/psf/trademarks/)

If someone knows otherwise, please let us know. I'm also emailing the PSF as I write this comment, and will update this issue when I get their response.

**Comment by aclark4life** [comment]
PSF has given :+1:

**Comment by wiredfool** [comment]
Sweet.

**Comment by aclark4life** [comment]
And as soon as GitHub LFS gets rolled out to organizations, we can move it here! https://github.com/aclark4life/pillow-logo

**Comment by aclark4life** [comment]
Moved here! https://github.com/python-pillow/pillow-logo
