### ISSUE TITLE
Black background on frames after first frame in GIF using Pillow

### ISSUE THREAD

**Issue by AnasYasin** [python-pillow/Pillow#5755]
### What did you do?
I am trying to place a gif on png using Pillow. It's giving black background after the first frame. I have tried every solution on Github including  [#1987](https://github.com/python-pillow/Pillow/issues/1987) and [#1976](https://github.com/python-pillow/Pillow/issues/1976)

### What did you expect to happen?
It should make a transparent GIF place on a png. 

### What actually happened?
Currently, all frames after the first frame are having a black background. The code is working file on small GIFs.

**Orignal Gif**:
<img src="https://user-images.githubusercontent.com/34492965/136784497-c7c61318-50fa-47f3-b943-5a9dd18193db.GIF" width=20% height=20%>

**Background Image**:
<img src="https://user-images.githubusercontent.com/34492965/136784783-b8b53bff-f79e-417d-9b74-3dbd25f0e8c1.png" width=20% height=20%>

**Final Result**:
<img src="https://user-images.githubusercontent.com/34492965/136785161-d72f6fb6-a535-4eac-a02f-96b58bdafce2.gif" width=20% height=20%>

**Frames**:

<img src="https://user-images.githubusercontent.com/34492965/136785366-3588abdf-d702-4e7d-8452-4ceb2fb7bc22.png" width=10% height=10%> <img src="https://user-images.githubusercontent.com/34492965/136785383-c5977161-3e8d-4dfd-aaa8-2dfd9865215b.png" width=10% height=10%> <img src="https://user-images.githubusercontent.com/34492965/136785389-f4f61c4a-bc4e-444c-a7a2-96e8ef6babbb.png" width=10% height=10%> <img src="https://user-images.githubusercontent.com/34492965/136785393-cc2137d5-3256-45a3-b53e-22769cad1d9b.png" width=10% height=10%> 
 <img src="https://user-images.githubusercontent.com/34492965/136785396-ada9d6b9-4c63-4614-bc39-eb9254ce9bf8.png" width=10% height=10%>

### What are your OS, Python and Pillow versions?

* OS: Linux Mint 19.1 x86_64
* Python: 3.6.8
* Pillow: 8.2.0

```python
from PIL import Image, ImageSequence

gif = Image.open("gif4.GIF")
duration = 100
disposal = 2
frames = []
ind = 0

for frame in ImageSequence.Iterator(gif):
    bg2 = Image.open('test1.png')
    bg2.paste(frame, frame.convert('RGBA'))
    bg2.save('{}.png'.format(ind))
    frames.append(bg2)
    ind  += 1
    
frames[0].save('test.gif', save_all=True, append_images=frames[1:], loop=0, optimise=False, duration=duration, disposal=disposal, format='GIF')
```

**Comment by radarhere** [comment]
If you simplify your code to just reading and saving your GIF,
```python
from PIL import Image, ImageSequence

gif = Image.open("gif4.GIF")
ind = 0

for frame in ImageSequence.Iterator(gif):
    frame.save('{}.png'.format(ind))
    ind  += 1
```
you will see that the colours are still not correct. I expect this is part of a long standing bug where Pillow doesn't correctly read the colours from different palettes after the first GIF frame. See #3735 for a longer explanation.

**Comment by tomhaydn** [comment]
I am having this issue on 8.4.0

**Comment by tomhaydn** [comment]
from PIL import Image, ImageSequence, GifImagePlugin
import os


bg = Image.open('images/bg/Background Sky.gif')
body = Image.open('images/body/Body Blue.gif')
eyes = Image.open('images/eyes/Eyes Green.gif')
headwear = Image.open('images/headwear/Headwear Party Hat.gif')

frames = []
for idx, frame in enumerate(ImageSequence.Iterator(bg)):
    #frame.paste(ImageSequence.Iterator(bg)[idx], mask=ImageSequence.Iterator(bg)[idx].convert("RGB"))
    frame = frame.copy().convert('RGBA')
    frame = frame.resize((640,640))
    #frame.show()
    frame.paste(ImageSequence.Iterator(body)[idx], mask=ImageSequence.Iterator(body)[idx].convert("RGBA"))
    frame.paste(ImageSequence.Iterator(eyes)[idx], mask=ImageSequence.Iterator(eyes)[idx].convert("RGBA"))
    frame.paste(ImageSequence.Iterator(headwear)[idx], mask=ImageSequence.Iterator(headwear)[idx].convert("RGBA"))
    
    frames.append(frame)

print(frames)

frames[0].save('images/generated/output.gif', save_all=True, append_images=frames[1:], loop=0)

**Comment by radarhere** [comment]
Please create a new issue and attach the GIFs you are trying to load.

**Comment by radarhere** [comment]
The issue from @tomhaydn became #5837
