### ISSUE TITLE
PIL>UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0xf66b8809db0>

### ISSUE THREAD

**Issue by EricGPTI** [python-pillow/Pillow#5769]
I am trying to get a hash of image, this is my goal, so my architecture is using docker containers with some services.

I have a FASTAPI api that receive a form data and get the image uploaded. This API send this image to broker Rabbitmq that send this image to a queue. I have another service (Consumer) that get this image and process it to generate a Hash of image. The hash is returned to queue and da produce on API get and will to return to client a Hash.

On fastapi I have a route that receive one o more images:

```python
@app.post('images/)
async def images(id:str = Form(...), files: List[UploadFile] = File(...)):
    corr_id = id
    img = await files[0].read()
    producer = Producer(corr_id, img)
    hash = producer.producer()
    return hash
```

My class producer send this image to the queue.
My consumer receives this image and call a class that will generate the hash:

My file `get_image_hash.py`

```python
import base64
import imagehash
import io
import PIL.Image as Image
from PIL.ImageOps import mirror
from PIL import Image

class GetImageHash:
    def __init__(self, img):
        self.img = img

    def generate_hash(self):
        img_base64 = base64.b64encode(self.img)
        image = Image.open(io.BytesIO(img_base64))
        hashes = []
        mirrored_image = mirror(image)
        hashes.append(str(imagehash.phash(image)))
        hashes.append(str(imagehash.phash(mirrored_image)))
        hashes = ''.join(sorted(hashes))
        return hashes
```

When the class is called the error happen:

```
     raise unidentifiedImageError(
PIL>UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0xf66b8809db0>)
```

This error to happen when the line `image = Image.open(io.BytesIO(img_base64))` is executed.

I think that is because the file that should to contains the image be passed in the wrong way.

If I print img, I see that is a binary.

How can I fix it? What is the right way to pass my image?

* OS: Container Python 3.9.7
* Python: 3.9.7
* Pillow: 8.3.2

**Comment by radarhere** [comment]
> this problem fix, but the api call never end.

Perhaps the code is not with Pillow, but something else in your code? To determine whether the `Image.open` call is hanging or not, could you add a print statement after it and see if that runs?

If you believe Pillow is hanging, we will need a copy of the image to investigate further.

**Comment by EricGPTI** [comment]
> > this problem fix, but the api call never end.
> 
> Perhaps the code is not with Pillow, but something else in your code? To determine whether the `Image.open` call is hanging or not, could you add a print statement after it and see if that runs?
> 
> If you believe Pillow is hanging, we will need a copy of the image to investigate further.

Yes, now the error is with my code. using the way that @nulano said, stayed ok. My error was trying to convert the image to base64. 

Thanks a lot!
