### ISSUE TITLE
8.4.0: Pillow installation on arm64 broken

### ISSUE THREAD

**Issue by harshvp1621** [python-pillow/Pillow#5771]
It seems that all of a sudden Pillow installation in arm64 Debian Buster is failing. The following command for installation used to work fine until today. The pip3 version is 21.3 and Python version is Python3.7. What might I be missing?

```python
pip3 install --upgrade-strategy only-if-needed  pillow
```
The output and error obtained is below

```bash
Collecting pillow
  Downloading Pillow-8.4.0.tar.gz (49.4 MB)
     |████████████████████████████████| 49.4 MB 6.8 MB/s            
  Preparing metadata (setup.py) ... done
Building wheel for pillow (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: /usr/bin/python3 -u -c 'import io, os, sys, setuptools, tokenize; sys.argv[0] = '"'"'/tmp/pip-install-3qz2m_qc/pillow_eec61f8ff4a74a87b94dd809070dd65c/setup.py'"'"'; __file__='"'"'/tmp/pip-install-3qz2m_qc/pillow_eec61f8ff4a74a87b94dd809070dd65c/setup.py'"'"';f = getattr(tokenize, '"'"'open'"'"', open)(__file__) if os.path.exists(__file__) else io.StringIO('"'"'from setuptools import setup; setup()'"'"');code = f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-a7lp8ct_
       cwd: /tmp/pip-install-3qz2m_qc/pillow_eec61f8ff4a74a87b94dd809070dd65c/
  Complete output (173 lines):
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-aarch64-3.7
  creating build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImagePath.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/GdImageFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/features.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImagePalette.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/SunImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageDraw2.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/FtexImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/MpoImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageFilter.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/BdfFontFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageShow.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/GifImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/DdsImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageMorph.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PdfImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/EpsImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImtImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/TgaImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PcdImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/IcoImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageDraw.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageChops.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageStat.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/WmfImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageFont.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/CurImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PcxImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/FpxImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageSequence.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/__init__.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageOps.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/XbmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/JpegPresets.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PaletteFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/BlpImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PcfFontFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PpmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PalmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageTransform.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/TarIO.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PngImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PdfParser.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/IptcImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageGrab.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/BmpImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/Image.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageQt.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/GbrImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/MicImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/GimpPaletteFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/XpmImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/TiffImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/FliImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/GimpGradientFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PSDraw.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PsdImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/_tkinter_finder.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/WalImageFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ContainerIO.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageColor.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageMode.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PyAccess.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageTk.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageMath.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ExifTags.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/MspImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/PixarImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageEnhance.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/MpegImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageWin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/SgiImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/__main__.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/_version.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/WebPImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/FontFile.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/_binary.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/TiffTags.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/ImageCms.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/JpegImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/_util.py -> build/lib.linux-aarch64-3.7/PIL
  copying src/PIL/DcxImagePlugin.py -> build/lib.linux-aarch64-3.7/PIL
  running egg_info
  writing src/Pillow.egg-info/PKG-INFO
  writing dependency_links to src/Pillow.egg-info/dependency_links.txt
  writing top-level names to src/Pillow.egg-info/top_level.txt
  reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no files found matching '*.c'
  warning: no files found matching '*.h'
  warning: no files found matching '*.sh'
  warning: no previously-included files found matching '.appveyor.yml'
  warning: no previously-included files found matching '.clang-format'
  warning: no previously-included files found matching '.coveragerc'
  warning: no previously-included files found matching '.editorconfig'
  warning: no previously-included files found matching '.readthedocs.yml'
  warning: no previously-included files found matching 'codecov.yml'
  warning: no previously-included files matching '.git*' found anywhere in distribution
  warning: no previously-included files matching '*.pyc' found anywhere in distribution
  warning: no previously-included files matching '*.so' found anywhere in distribution
  no previously-included directories found matching '.ci'
  writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
  running build_ext
  
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  Traceback (most recent call last):
    File "/tmp/pip-install-3qz2m_qc/pillow_eec61f8ff4a74a87b94dd809070dd65c/setup.py", line 1024, in <module>
      zip_safe=not (debug_build() or PLATFORM_MINGW),
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/setuptools/command/build_ext.py", line 78, in run
      _build_ext.run(self)
    File "/usr/lib/python3.7/distutils/command/build_ext.py", line 340, in run
      self.build_extensions()
    File "/tmp/pip-install-3qz2m_qc/pillow_eec61f8ff4a74a87b94dd809070dd65c/setup.py", line 790, in build_extensions
      raise RequiredDependencyException(f)
  __main__.RequiredDependencyException: zlib
  
  During handling of the above exception, another exception occurred:
  
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-3qz2m_qc/pillow_eec61f8ff4a74a87b94dd809070dd65c/setup.py", line 1037, in <module>
      raise RequiredDependencyException(msg)
  __main__.RequiredDependencyException:
  
  The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html
  
  
  ----------------------------------------
  ERROR: Failed building wheel for pillow
  Running setup.py clean for pillow
```

**Comment by hugovk** [comment]
The headers or library files could not be found for zlib,
  a required dependency when compiling Pillow from source.
  
  Please see the install instructions at:
     https://pillow.readthedocs.io/en/latest/installation.html

**Comment by hugovk** [comment]
But 8.4.0 was only released today (7 hours ago) and the binary wheels for aarch64 were uploaded later (1 hour ago):

https://pypi.org/project/Pillow/#files

So perhaps you got the error before those wheels were uploaded and it tried to build from source.

Does it work if you try again now?

**Comment by vlajnaya-mol** [comment]
Hi, @hugovk. I've got the same problem, but with a different wheel. Everything worked fine for 8.3.2 PIL. Can you help me out?

hugovk#15 31.68   Running setup.py bdist_wheel for pillow: started                                                                                                              
#15 31.97   Running setup.py bdist_wheel for pillow: finished with status 'error'                                                                                         
#15 31.97   Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-build-1x94y0dr/pillow/setup.py';f=getattr(tokenize, 'open'
, open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/tmpzl7cn_typip-wheel- --python-tag cp36:       
#15 31.97   running bdist_wheel                                                                                                                                           
#15 31.97   running build                                                                                                                                                 
#15 31.97   running build_py                                                                                                                                              
#15 31.97   creating build                                                                                                                                                
#15 31.97   creating build/lib.linux-x86_64-3.6                                                                                                                           
#15 31.97   creating build/lib.linux-x86_64-3.6/PIL                                                                                                                       
#15 31.97   copying src/PIL/SgiImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/WmfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/TiffImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                          
#15 31.97   copying src/PIL/PSDraw.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                   
#15 31.97   copying src/PIL/ImageTransform.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/features.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                 
#15 31.97   copying src/PIL/MpoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/ImageGrab.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                
#15 31.97   copying src/PIL/IcoImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/_version.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                 
#15 31.97   copying src/PIL/__init__.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                 
#15 31.97   copying src/PIL/TgaImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/SunImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/GribStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                      
#15 31.97   copying src/PIL/ImageFilter.py -> build/lib.linux-x86_64-3.6/PIL                                                                                              
#15 31.97   copying src/PIL/GdImageFile.py -> build/lib.linux-x86_64-3.6/PIL                                                                                              
#15 31.97   copying src/PIL/ImageDraw.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                
#15 31.97   copying src/PIL/PsdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/ImageEnhance.py -> build/lib.linux-x86_64-3.6/PIL                                                                                             
#15 31.97   copying src/PIL/FontFile.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                 
#15 31.97   copying src/PIL/ImageDraw2.py -> build/lib.linux-x86_64-3.6/PIL                                                                                               
#15 31.97   copying src/PIL/ImageColor.py -> build/lib.linux-x86_64-3.6/PIL                                                                                               
#15 31.97   copying src/PIL/_util.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                    
#15 31.97   copying src/PIL/ImageWin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                 
#15 31.97   copying src/PIL/ImageChops.py -> build/lib.linux-x86_64-3.6/PIL                                                                                               
#15 31.97   copying src/PIL/ImagePalette.py -> build/lib.linux-x86_64-3.6/PIL                                                                                             
#15 31.97   copying src/PIL/XpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/ImageMath.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                
#15 31.97   copying src/PIL/ImageFont.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                            
#15 31.97   copying src/PIL/GbrImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/ExifTags.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                 
#15 31.97   copying src/PIL/ImtImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/GimpPaletteFile.py -> build/lib.linux-x86_64-3.6/PIL                                                                                          
#15 31.97   copying src/PIL/MpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                          
#15 31.97   copying src/PIL/XbmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/ImageShow.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                
#15 31.97   copying src/PIL/ImageQt.py -> build/lib.linux-x86_64-3.6/PIL                                                                                                  
#15 31.97   copying src/PIL/PcfFontFile.py -> build/lib.linux-x86_64-3.6/PIL                                                                                              
#15 31.97   copying src/PIL/Hdf5StubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                      
#15 31.97   copying src/PIL/ImageMorph.py -> build/lib.linux-x86_64-3.6/PIL                                                                                               
#15 31.97   copying src/PIL/GifImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL                                                                                           
#15 31.97   copying src/PIL/PdfImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/FliImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/WalImageFile.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageMode.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageFile.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageOps.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/McIdasImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/JpegImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/MicImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/JpegPresets.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/Image.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/__main__.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/FtexImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PdfParser.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/DcxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PcdImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/FpxImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/BmpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImagePath.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/TiffTags.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/BdfFontFile.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/TarIO.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageSequence.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/EpsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/SpiderImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ContainerIO.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/_tkinter_finder.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/BlpImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PalmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/IptcImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/XVThumbImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageCms.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PaletteFile.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageStat.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/GimpGradientFile.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/IcnsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/ImageTk.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/CurImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/WebPImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/BufrStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PngImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/FitsStubImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PpmImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/_binary.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PixarImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/PyAccess.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/Jpeg2KImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/MspImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   copying src/PIL/DdsImagePlugin.py -> build/lib.linux-x86_64-3.6/PIL
#15 31.97   running egg_info
#15 31.97   writing src/Pillow.egg-info/PKG-INFO
#15 31.97   writing dependency_links to src/Pillow.egg-info/dependency_links.txt
#15 31.97   writing top-level names to src/Pillow.egg-info/top_level.txt
#15 31.97   reading manifest file 'src/Pillow.egg-info/SOURCES.txt'
#15 31.97   reading manifest template 'MANIFEST.in'
#15 31.97   warning: no files found matching '*.c'
#15 31.97   warning: no files found matching '*.h'
#15 31.97   warning: no files found matching '*.sh'
#15 31.97   warning: no previously-included files found matching '.appveyor.yml'
#15 31.97   warning: no previously-included files found matching '.clang-format'
#15 31.97   warning: no previously-included files found matching '.coveragerc'
#15 31.97   warning: no previously-included files found matching '.editorconfig'
#15 31.97   warning: no previously-included files found matching '.readthedocs.yml'
#15 31.97   warning: no previously-included files found matching 'codecov.yml'
#15 31.97   warning: no previously-included files matching '.git*' found anywhere in distribution
#15 31.97   warning: no previously-included files matching '*.pyc' found anywhere in distribution
#15 31.97   warning: no previously-included files matching '*.so' found anywhere in distribution
#15 31.97   no previously-included directories found matching '.ci'
#15 31.97   adding license file 'LICENSE'
#15 31.97   writing manifest file 'src/Pillow.egg-info/SOURCES.txt'
#15 31.97   running build_ext
#15 31.97
#15 31.97
#15 31.97   The headers or library files could not be found for zlib,
#15 31.97   a required dependency when compiling Pillow from source.
#15 31.97
#15 31.97   Please see the install instructions at:
#15 31.97      https://pillow.readthedocs.io/en/latest/installation.html
#15 31.97
#15 31.97   Traceback (most recent call last):
#15 31.97     File "/tmp/pip-build-1x94y0dr/pillow/setup.py", line 1024, in <module>
#15 31.97       zip_safe=not (debug_build() or PLATFORM_MINGW),
#15 31.97     File "/usr/local/lib/python3.6/dist-packages/setuptools/__init__.py", line 153, in setup
#15 31.97       return distutils.core.setup(**attrs)
#15 31.97     File "/usr/lib/python3.6/distutils/core.py", line 148, in setup
#15 31.97       dist.run_commands()
#15 31.97     File "/usr/lib/python3.6/distutils/dist.py", line 955, in run_commands
#15 31.97       self.run_command(cmd)
#15 31.97     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#15 31.97       cmd_obj.run()
#15 31.97     File "/usr/local/lib/python3.6/dist-packages/wheel/bdist_wheel.py", line 299, in run
#15 31.97       self.run_command('build')
#15 31.97     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
#15 31.97       self.distribution.run_command(command)
#15 31.97     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#15 31.97       cmd_obj.run()
#15 31.97     File "/usr/lib/python3.6/distutils/command/build.py", line 135, in run
#15 31.97       self.run_command(cmd_name)
#15 31.97     File "/usr/lib/python3.6/distutils/cmd.py", line 313, in run_command
#15 31.97       self.distribution.run_command(command)
#15 31.97     File "/usr/lib/python3.6/distutils/dist.py", line 974, in run_command
#15 31.97       cmd_obj.run()
#15 31.97     File "/usr/local/lib/python3.6/dist-packages/setuptools/command/build_ext.py", line 79, in run
#15 31.97       _build_ext.run(self)
#15 31.97     File "/usr/lib/python3.6/distutils/command/build_ext.py", line 339, in run
#15 31.97       self.build_extensions()
#15 31.97     File "/tmp/pip-build-1x94y0dr/pillow/setup.py", line 790, in build_extensions
#15 31.97       raise RequiredDependencyException(f)
#15 31.97   __main__.RequiredDependencyException: zlib
#15 31.97
#15 31.97   During handling of the above exception, another exception occurred:
#15 31.97
#15 31.97   Traceback (most recent call last):
#15 31.97     File "<string>", line 1, in <module>
#15 31.97     File "/tmp/pip-build-1x94y0dr/pillow/setup.py", line 1037, in <module>
#15 31.97       raise RequiredDependencyException(msg)
#15 31.97   __main__.RequiredDependencyException:
#15 31.97
#15 31.97   The headers or library files could not be found for zlib,
#15 31.97   a required dependency when compiling Pillow from source.
#15 31.97
#15 31.97   Please see the install instructions at:
#15 31.97      https://pillow.readthedocs.io/en/latest/installation.html
#15 31.97
#15 31.97
#15 31.97
#15 31.97   ----------------------------------------
#15 31.97   Failed building wheel for pillow
#15 31.97   Running setup.py clean for pillow
