### ISSUE TITLE
Improve lifecycle documentation

### ISSUE THREAD

**Issue by jenstroeger** [python-pillow/Pillow#5772]
The [Image lifecycle](https://pillow.readthedocs.io/en/stable/reference/open_files.html#image-lifecycle) documentation states that

> The lifecycle of a single-frame image is relatively simple. The file must remain open until the `load()` or `close()` function is called or the context manager exits.

However, functions like [Image.convert()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert)

> Returns a converted copy of this image.

It’s unclear whether it’s necessary to call `close()` on such newly created objects or not, i.e. what’s the lifecycle here? Is the underlying file shared amongst these two objects?

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/reference/open_files.html#image-lifecycle
> When the pixel data from the image is required, `load()` is called.

Pixel data is required for `convert()`. So it calls `load()` before it does anything else, and the underlying file is closed (for a single-frame image) on the original image. Then `convert()` reads that data, transforms it appropriately, and places it in a new image instance.

As for improving the documentation, what do you think of #5773?

**Comment by radarhere** [comment]
That is safe to do with `new_img`, yes.

If you use `img` after the context manger, you can - it's just that the file association will be gone.

So the following code will work, because `load()` has already been called by `convert()`.

```python
from PIL import Image
with Image.open("some.jpg") as img:
    if img.fp is not None:
        print("img.fp is not None inside the context manager")
    new_img = img.convert("L")

if img.fp is None:
    print("img.fp is None outside the context manager")
img.save("out.png")
```

But this code will not work, because `load()` hasn't been called and the file has been lost.

```python
from PIL import Image
with Image.open("some.jpg") as img:
    pass

img.save("out.png")
```

**Comment by radarhere** [comment]
I've added a variation on the passing code I wrote to the PR. The failing code is already explained in https://pillow.readthedocs.io/en/stable/reference/open_files.html#complications

<img width="703" alt="Screen Shot 2021-10-16 at 11 32 30 pm" src="https://user-images.githubusercontent.com/3112309/137587558-017e5469-9e9c-4e20-87a6-fc90bc152725.png">
