### ISSUE TITLE
AnimGif

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#5781]
Some AnimGifs are not transparent:
````python
import PIL.Image
with PIL.Image.open('/tmp/AnimGif.gif', 'r') as image:
    for index, frame in enumerate(PIL.ImageSequence.Iterator(image)):
        #frame = frame.convert('RGBA')
        frame.save('/tmp/m/'+str(index)+'.png', 'PNG')
````

Image:
![AnimGif](https://user-images.githubusercontent.com/274624/137976345-fbad5689-ccea-4e7a-8337-2d8e1ffa9811.gif)

For example frame 6 and 19:
![6](https://user-images.githubusercontent.com/274624/137976388-5e638f66-9fab-4922-a316-8076ea33309f.png) 
![19](https://user-images.githubusercontent.com/274624/137976531-79fd85f4-4e6c-4447-a577-a1f111c10625.png)

**Comment by radarhere** [comment]
I've created PR #5857 to resolve this.

Frame 6 and 19
![6](https://user-images.githubusercontent.com/3112309/143822763-f441e642-207a-4c42-847f-dda6704ff0eb.png)
![19](https://user-images.githubusercontent.com/3112309/143822770-58d521d7-2c19-4d6e-bee1-a53a98364209.png)
