### ISSUE TITLE
How to compare images pixel by pixel and highlight an area that is different?

### ISSUE THREAD

**Issue by Aleksandr34nov** [python-pillow/Pillow#5786]
### What did you do?

I need to compare the images using PIL pixel by pixel, and then select those areas where the pixels differ, but I need to make a transparent selection or shading selection so that the image is visible. How can this be implemented?

### What are your OS, Python and Pillow versions?

* OS: Windows 10 64-bit
* Python: 3.7
* Pillow: 8.3.2

```python
code goes here
```

**Comment by radarhere** [comment]
@Aleksandr34nov was that helpful?

**Comment by edgevalue** [comment]
Excellent.  Worked straight cut & paste of the code.
