### ISSUE TITLE
Add GPU/CUDA Support?

### ISSUE THREAD

**Issue by DigitalGreyHat** [python-pillow/Pillow#5787]
Maybe add GPU/CUDA support we live in 2021!!!

**Comment by hugovk** [comment]
@thalesfsp Please keep it civil.

**Comment by aclark4life** [comment]
> @thalesfsp Please keep it civil.

Indeed, and also we'd need something like what is happening in #1888 to make any meaningful progress on this. 

In #1888 @wiredfool appeared to at least have some idea of what was required. 

In this case, I'm not sure anyone (core team, people filed issues) have any idea what is required but if you do, at the very least, add a comment here so we can start thinking about it. There are some things we'll probably never add (e.g. machine learning features) but I have no idea if this is one of them or not. Anyone?

Lastly, "PRs welcome" is quite common [here](https://github.com/search?q=repo%3Apython-pillow%2FPillow+prs+welcome&type=issues) and in all of open source from my experience. We have a core team of ~6 developers but over [400 committers which means PRs have been welcomed a lot here](https://github.com/python-pillow/Pillow/graphs/contributors). So anyone reading this should consider it and maybe we should [add a badge](https://makeapullrequest.com/) for it too.

And actually, let's discuss further on #1546 and not here 😄 Thanks all
