### ISSUE TITLE
Add SIMD support by turning on/off global option

### ISSUE THREAD

**Issue by jjangga0214** [python-pillow/Pillow#5791]
Hi!

I know `pillow` deliberately has not included SIMD, as `pillow` is used from various architectures, and selectively compiling is hard.

What if, even if the package size can become larger, `pillow` provides a (programmatic or env var) global option which can be turned on/off in runtime. Users should turn on/off by their own explicit decision by understanding their own system.

This way, the library does not have to care if the system is compatible or not. The decision would be up to the user.

How do you think?

Thanks.

**Comment by radarhere** [comment]
Just looping in @homm on this one, since he is the expert.

**Comment by radarhere** [comment]
Fyi, Pillow SIMD is no longer a version behind.

**Comment by radarhere** [comment]
I think this matter is better served by the issue in Pillow SIMD - https://github.com/uploadcare/pillow-simd/issues/8
