### ISSUE TITLE
Problem with using ImageTk on Cygwin

### ISSUE THREAD

**Issue by friedrichromstedt** [python-pillow/Pillow#5795]
While attempting to use `ImageTk` on Cygwin (64-bit, Windows 10, Python 3.8), I ran into an unhandled Exception. Just attempting to show some black square Pillow Image using a tkinter `Canvas` causes this failure. I've tried several versions of Pillow, from `8.4.0` down to `5.4.1`, all with the same result.

Further description of the dysfunction including a minimal example script can be found at https://github.com/friedrichromstedt/bughunting-02. This repo provides a summary along with detailed information on my work regarding the subject.

I've reported to Cygwin upstream https://sourceware.org/pipermail/cygwin/2021-October/249643.html, but up to now this did not lead to a solution. It might be that the problem is rooted somewhere outside of Pillow, but I would appreciate any pointer.

**Comment by friedrichromstedt** [comment]
Any further ideas how to track down this issue?

**Comment by DWesl** [comment]
https://github.com/python-pillow/Pillow/blob/a215f725ba98efeb48194460b8796be3acd6173f/src/_imagingtk.c#L54-L55
and
https://github.com/python-pillow/Pillow/blob/95cff6e959bb3c37848158ed2145d49d49806a31/src/Tk/tkImaging.c#L380-L397
look to be the only places that could fail on import.

```python
import tkinter
tk = tkinter.Tk()
canvas = tkinter.Canvas(tk)
canvas.pack()
photoimage = tkinter.PhotoImage(file="/path/to/image.png")
canvas.create_image((0, 0), image=photoimage, anchor='nw')
tk.mainloop()
```
works fine.

I'm not sure how to check further what's going on beyond this.

An interesting comment &mdash;
https://github.com/python-pillow/Pillow/blob/95cff6e959bb3c37848158ed2145d49d49806a31/src/Tk/tkImaging.c#L224-L230
&mdash; suggests that this is one of the times that "Cygwin uses Windows linking semantics" is relevant: I suspect Pillow is currently trying to import symbols defined in the Tcl/Tk shared libraries from Python's _tkinter shared library.  It would be interesting to have the Cygwin build of Pillow use the Windows code path and see if that fixes the issue.

**Comment by nulano** [comment]
> An interesting comment —

Note that this is in an `#if defined(_WIN32) || ...` block, so this is used on Cygwin (according to [this](http://jdebp.info/FGA/predefined-macros-platform.html#Cygwin), Cygwin defines `_WIN32`).

**Comment by DWesl** [comment]
> Note that this is in an `#if defined(_WIN32) || ...` block, so this is used on Cygwin (according to [this](http://jdebp.info/FGA/predefined-macros-platform.html#Cygwin), Cygwin defines `_WIN32`).

[Apparently Cygwin does sometimes define `_WIN32`](https://cygwin.com/faq/faq.html#faq.programming.preprocessor), but that has to be specifically requested:
```bash
$ echo | gcc -x c - -E -dM | grep -i WIN
#define __WINT_MAX__ 0xffffffffU
#define __WINT_MIN__ 0U
#define __SIZEOF_WINT_T__ 4
#define __CYGWIN__ 1
#define __WINT_TYPE__ unsigned int
#define __WINT_WIDTH__ 32
```
I don't think that flag got passed in any of the Pillow builds mentioned in the reproduction repository.

**Comment by DWesl** [comment]
@friedrichromstedt, do the changes suggested in #5807 fix the problem for you?

**Comment by friedrichromstedt** [comment]
The branch https://github.com/DWesl/Pillow/tree/tkimaging-on-cygwin (29b92391) referenced in #5807 solved the problem on my machine.

Detailed information about my proceeding is available on https://github.com/friedrichromstedt/bughunting-02/tree/v2021-11-05_2#proposal-of-a-fix-from-upstream.

Tanks a lot for all the work which has been spent solving this issue.

I noticed that the version of the branch I used (29b92391) is one commit behind the current https://github.com/DWesl/Pillow/tree/tkimaging-on-cygwin. Shall I test once more?

**Comment by DWesl** [comment]
The latest commit should just skip a test that won't work on Cygwin.  Is whatever code inspired your test case working now?

**Comment by friedrichromstedt** [comment]
> The latest commit should just skip a test that won't work on Cygwin.

I noticed that even with https://github.com/DWesl/Pillow/commit/29b92391bcf30b59fcc876d168b0b0b3677fc349 the selftests pass. You can find the logs in https://github.com/friedrichromstedt/bughunting-02/blob/v2021-11-05_2/Logs2/b01%20make%20install.txt, context in https://github.com/friedrichromstedt/bughunting-02/tree/v2021-11-05_2#proposal-of-a-fix-from-upstream.

> Is whatever code inspired your test case working now?

Yes! I tested carefully, so it needed some time. Thanks again!

**Comment by DWesl** [comment]
[I am told](https://github.com/python-pillow/Pillow/pull/5807#discussion_r742626179) that at some point the recommended way to run Pillow's tests changed from `python selftest.py` to `python -m pytest Tests`.  [`tox` does both](https://github.com/python-pillow/Pillow/blob/main/tox.ini); [the documentation](https://pillow.readthedocs.io/en/stable/installation.html#building-from-source) [doesn't seem to mention either](https://pillow.readthedocs.io/en/stable/search.html?q=test&check_keywords=yes&area=default).

**Comment by hugovk** [comment]
Yes, `selftest.py` has always* been a quick subset, the comment at the top is "minimal sanity check". Use pytest for the full test suite.

There's some more info in https://github.com/python-pillow/Pillow/blob/main/Tests/README.rst

---

\* `selftest.py` was added in PIL 1.1.2 in 2001, the main (custom framework) test suite was added in 2013, converted to unittest ran with nose in 2014, switched to pytest as a runner in 2017, and converted tests to pytest in 2020.

**Comment by DWesl** [comment]
Probably once through the Pillow test suite is enough.  I also use `startxwin` to start my X server.

> > Is whatever code inspired your test case working now?
> 
> Yes! I tested carefully, so it needed some time. Thanks again!

Thank you for testing.
