### ISSUE TITLE
PNG: Checksum mismatches are ignored

### ISSUE THREAD

**Issue by appgurueu** [python-pillow/Pillow#5800]
### What did you do?

I ran Willem van Schaik's PngSuite through Pillow in order to generate testing data for a PNG reader I'm writing.

### What did you expect to happen?

I expected all erroneous PNG files to trigger an error.

### What actually happened?

`xcsn0g01.png`, a file containing a wrong `IDAT` checksum, did not trigger an error.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04
* Python: 3.8.10
* Pillow: 8.3.2

```python
try:
    with Image.open("xcsn0g01.png") as im:
        print("this should not happen!")
except:
    print("this should happen")
```

**Comment by radarhere** [comment]
The file in question is http://www.schaik.com/pngsuite2011/xcsn0g01.png

**Comment by hugovk** [comment]
How do ImageMagick and other popular tools handle it? The file opens in Chrome with no error.

**Comment by appgurueu** [comment]
> How do ImageMagick and other popular tools handle it? The file opens in Chrome with no error.

Firefox shows the alt text instead. Pillow should somehow handle this; maybe a [warning](https://docs.python.org/3/library/warnings.html)?

**Comment by hugovk** [comment]
Safari, Opera and macOS Preview also show it fine.

**Comment by nulano** [comment]
I believe you are looking for the `im.verify()` function:

```python
>>> from PIL import Image
>>> im = Image.open(r"D:\Downloads\xcsn0g01.png")
>>> im.verify()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "c:\git\pillow\src\PIL\PngImagePlugin.py", line 765, in verify
    self.png.verify()
  File "c:\git\pillow\src\PIL\PngImagePlugin.py", line 231, in verify
    self.crc(cid, ImageFile._safe_read(self.fp, length))
  File "c:\git\pillow\src\PIL\PngImagePlugin.py", line 204, in crc
    f"broken PNG file (bad header checksum in {repr(cid)})"
SyntaxError: broken PNG file (bad header checksum in b'IDAT')
```

**Comment by appgurueu** [comment]
Indeed I am. Thanks.
