### ISSUE TITLE
Pillow Uninstallation or Upgrade Issue 

### ISSUE THREAD

**Issue by kashifzr** [python-pillow/Pillow#5802]
I am trying to install autolab-perception==1.0.0 which are using Pillow 8.3.2. Though it show Pillow 8.3.2 is installing on Shell, But when I try to build setup.py file autolab-perception then it took Pillow7 

* OS: Ubuntu 20.04
* Python: Python 3.8.10
* Pillow: 7 

Output of python3 setup.py develop

<pre>op
[sudo] password for abc: 
running develop
running egg_info
creating autolab_perception.egg-info
writing autolab_perception.egg-info/PKG-INFO
writing dependency_links to autolab_perception.egg-info/dependency_links.txt
writing requirements to autolab_perception.egg-info/requires.txt
writing top-level names to autolab_perception.egg-info/top_level.txt
writing manifest file &apos;autolab_perception.egg-info/SOURCES.txt&apos;
reading manifest file &apos;autolab_perception.egg-info/SOURCES.txt&apos;
writing manifest file &apos;autolab_perception.egg-info/SOURCES.txt&apos;
running build_ext
Creating /usr/local/lib/python3.8/dist-packages/autolab-perception.egg-link (link to .)
Removing autolab-perception 1.0.0 from easy-install.pth file
Adding autolab-perception 1.0.0 to easy-install.pth file

Installed /home/abc/deep_grasp/dexnet_deps/perception
Processing dependencies for autolab-perception==1.0.0
error: Pillow 7.0.0 is installed but pillow&gt;=8.3.2 is required by {&apos;imageio&apos;}
</pre>

Command to remove or Uninstalled Pillow7

<pre>pip uninstall pillow
Found existing installation: Pillow 7.0.0
Uninstalling Pillow-7.0.0:
  Would remove:
    /usr/lib/python3/dist-packages/PIL
    /usr/lib/python3/dist-packages/Pillow-7.0.0.egg-info
Proceed (Y/n)? y
<font color="#CC0000">ERROR: Exception:</font>
<font color="#CC0000">Traceback (most recent call last):</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.8/shutil.py&quot;, line 791, in move</font>
<font color="#CC0000">    os.rename(src, real_dst)</font>
<font color="#CC0000">PermissionError: [Errno 13] Permission denied: &apos;/usr/lib/python3/dist-packages/PIL&apos; -&gt; &apos;/tmp/pip-uninstall-342dgci3&apos;</font>

<font color="#CC0000">During handling of the above exception, another exception occurred:</font>

<font color="#CC0000">Traceback (most recent call last):</font>
<font color="#CC0000">  File &quot;/home/abc/.local/lib/python3.8/site-packages/pip/_internal/cli/base_command.py&quot;, line 164, in exc_logging_wrapper</font>
<font color="#CC0000">    status = run_func(*args)</font>
<font color="#CC0000">  File &quot;/home/abc/.local/lib/python3.8/site-packages/pip/_internal/commands/uninstall.py&quot;, line 97, in run</font>
<font color="#CC0000">    uninstall_pathset = req.uninstall(</font>
<font color="#CC0000">  File &quot;/home/abc/.local/lib/python3.8/site-packages/pip/_internal/req/req_install.py&quot;, line 671, in uninstall</font>
<font color="#CC0000">    uninstalled_pathset.remove(auto_confirm, verbose)</font>
<font color="#CC0000">  File &quot;/home/abc/.local/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py&quot;, line 384, in remove</font>
<font color="#CC0000">    moved.stash(path)</font>
<font color="#CC0000">  File &quot;/home/abc/.local/lib/python3.8/site-packages/pip/_internal/req/req_uninstall.py&quot;, line 282, in stash</font>
<font color="#CC0000">    renames(path, new_path)</font>
<font color="#CC0000">  File &quot;/home/abc/.local/lib/python3.8/site-packages/pip/_internal/utils/misc.py&quot;, line 307, in renames</font>
<font color="#CC0000">    shutil.move(old, new)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.8/shutil.py&quot;, line 809, in move</font>
<font color="#CC0000">    rmtree(src)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.8/shutil.py&quot;, line 718, in rmtree</font>
<font color="#CC0000">    _rmtree_safe_fd(fd, path, onerror)</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.8/shutil.py&quot;, line 675, in _rmtree_safe_fd</font>
<font color="#CC0000">    onerror(os.unlink, fullname, sys.exc_info())</font>
<font color="#CC0000">  File &quot;/usr/lib/python3.8/shutil.py&quot;, line 673, in _rmtree_safe_fd</font>
<font color="#CC0000">    os.unlink(entry.name, dir_fd=topfd)</font>
<font color="#CC0000">PermissionError: [Errno 13] Permission denied: &apos;ImageOps.py&apos;</font>
</pre>

Due to PermissionError I try something with Sudo pip uninstall Pillow 

<pre>sudo pip uninstall pillow
Found existing installation: Pillow 7.0.0
Not uninstalling pillow at /usr/lib/python3/dist-packages, outside environment /usr
Can&apos;t uninstall &apos;Pillow&apos;. No files were found to uninstall.</pre>

How to used update or upgrade Pillow

**Comment by radarhere** [comment]
My first theory is that Pillow is installed through apt.

I would try `sudo apt remove python3-pil`

**Comment by kashifzr** [comment]
Thanks its work,
