### ISSUE TITLE
Windows dependency builder can't include platform specific flags

### ISSUE THREAD

**Issue by gaborkertesz-linaro** [python-pillow/Pillow#5803]
### What did you do?
I'm working on enabling win-arm64 platform (pull requests will be created soon) and imagequant library enables Intel specific feature by default: https://github.com/ImageOptim/libimagequant/blob/master/CMakeLists.txt#L6
This can be easily disabled by "-DBUILD_WITH_SSE=OFF" cmake flag, but this should be added depending on the current platform, so for ARM64 on Windows only.

The current implementation of https://github.com/python-pillow/Pillow/blob/main/winbuild/build_prepare.py generates a static object of the build attributes so dynamic decision can't be made, based on the given platform.

### What did you expect to happen?
It would be great to have a way to add platform specific build flags.

**Comment by gaborkertesz-linaro** [comment]
I would like to emphasize that this is currently not a blocker, rather than proactive feature request as the current issue is attempted to fix at the origin: https://github.com/ImageOptim/libimagequant/pull/66

**Comment by nulano** [comment]
There are multiple ways to do this:
* Add a new variable in the `architectures` dict and then pass it as an argument to cmake.
* Add a Windows `IF ... THEN SET a=b` command to the build script and pass `%a%` as an argument to cmake.
* Add https://github.com/ImageOptim/libimagequant/pull/66 as a patch in the `patch` block of the build step.

The intended way to build for a different architecture is to set up a separate build in a different directory, so there is no need to detect platform variables at build time.

**Comment by gaborkertesz-linaro** [comment]
Thanks for the quick and thorough answer, really appreciated and understood!
