### ISSUE TITLE
Creating an image with "L" mode returns error when RBG color tuple is being used

### ISSUE THREAD

**Issue by ibrahim-ajarmeh** [python-pillow/Pillow#5804]
### What did you do?

I'm trying to create a new image from an existing one, with `L` mode, using RBG background color `(0, 0, 0)`

### What did you expect to happen?
Creating the image without any errors, when RBG color tuple is used.

### What actually happened?
It returns the following
`TypeError: color must be int or tuple`

### What are your OS, Python and Pillow versions?

* OS: Mac OS
* Python: 3.x
* Pillow: 8.4.0

```python
image = Image.open(image_bytes)

try:
    background = ImageColor.getcolor('#' + background, 'RGB')
except ValueError:
    background = ImageColor.getcolor('#000000', 'RGB')

Image.new(image.mode, (width, height), background)
```

**Comment by nulano** [comment]
From https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes:

> `L` (8-bit pixels, black and white)

It is impossible to use an RGB mode color with an L mode image.
Mode L only supports a single color channel, for example:

```python
>>> from PIL import Image
>>> Image.new("L", (10, 10), 0)
<PIL.Image.Image image mode=L size=10x10 at 0x2A60AC42388>
>>> Image.new("L", (10, 10), (0,))
<PIL.Image.Image image mode=L size=10x10 at 0x2A60C7DB308>
```

**Comment by radarhere** [comment]
L mode images are not in color. That is the definition. Asking for an L mode image with RGB color is like asking for a grayscale image where you can see that the sky is blue - it's not clear what you are hoping to accomplish with that request.

**Comment by ibrahim-ajarmeh** [comment]
> From https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes:
> 
> > `L` (8-bit pixels, black and white)
> > `RGB` (3x8-bit pixels, true color)
> 
> It is impossible to use an RGB mode color in an L mode image. Mode L only supports a single color channel, for example:
> 
> ```python
> >>> from PIL import Image
> >>> Image.new("L", (10, 10), 0)
> <PIL.Image.Image image mode=L size=10x10 at 0x2A60AC42388>
> >>> Image.new("L", (10, 10), (0,))
> <PIL.Image.Image image mode=L size=10x10 at 0x2A60C7DB308>
> ```

Thank you for the explanation.
I know `L` mode will not accept RGB mode color, I meant it is not handling it, so if I send a RGB tuple to `L` mode image it should handle the tuple on `Image.new` method, that is my point.
Is it something that can be a thing, or should I handle it from my side ? and if it is not, can you guid me on which doc contains all the modes and the color modes that they accept ?

**Comment by radarhere** [comment]
I don't think it should handle it automatically. I think that would be more misleading to users than helpful.

https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes is the documentation you are asking for. I doubt it is exhaustive, but if a mode isn't listed there, our support for it is likely not good.

It says

> RGB (3x8-bit pixels, true color)

So 3 channels of values from 0 to 255.

> L (8-bit pixels, black and white)

So 1 channel from 0 to 255.

**Comment by ibrahim-ajarmeh** [comment]
@radarhere @nulano 
Thank you for your help 😄
