### ISSUE TITLE
libpng not included in Windows Python 3.7 wheel

### ISSUE THREAD

**Issue by mszhanyi** [python-pillow/Pillow#5813]
### What did you do?
In one clean Python3.7 virtual environment on Windows
1. Run `pip install torch torchvision`
2. Run test command `python -c "import torch;import torchvision;print('Is torchvision useable?', all(x is not None for x in [torch.ops.image.decode_png, torch.ops.torchvision.roi_align]))"`
**It throws exception.**
3. Run `conda install libpng` 
4. step2 can pass.

On Linux with Python3.7 environment
step3 is not necessary.

### What did you expect to happen?
The behavior should be consistent between Windows and Linux.
No need to run step 3 on Windows.

### What are your OS, Python and Pillow versions?

* OS: 
Windows, Linux
* Python: 
3.7
* Pillow: 
8.4.0

Misc: 
For python 3.8 and 3.9, it works on both Windows and Linux 

In python 3.8 env , If we run 'conda install pillow'
```
The following NEW packages will be INSTALLED:

  freetype           pkgs/main/win-64::freetype-2.11.0-ha860e81_0
  jpeg               pkgs/main/win-64::jpeg-9d-h2bbff1b_0
  libtiff            pkgs/main/win-64::libtiff-4.2.0-hd0e1b90_0
  libwebp            pkgs/main/win-64::libwebp-1.2.0-h2bbff1b_0
  lz4-c              pkgs/main/win-64::lz4-c-1.9.3-h2bbff1b_1
  olefile            pkgs/main/noarch::olefile-0.46-pyhd3eb1b0_0
  pillow             pkgs/main/win-64::pillow-8.4.0-py38hd45dc43_0
  tk                 pkgs/main/win-64::tk-8.6.11-h2bbff1b_0
  xz                 pkgs/main/win-64::xz-5.2.5-h62dcd97_0
  zstd               pkgs/main/win-64::zstd-1.4.9-h19a0ad4_0
```

While in python 3.7 env, there are 2 additional dependent package **libpng** and **zlib**
```
The following NEW packages will be INSTALLED:

  freetype           pkgs/main/win-64::freetype-2.11.0-ha860e81_0
  jpeg               pkgs/main/win-64::jpeg-9d-h2bbff1b_0
  libpng             pkgs/main/win-64::libpng-1.6.37-h2a8f88b_0_
  libtiff            pkgs/main/win-64::libtiff-4.2.0-hd0e1b90_0
  libwebp            pkgs/main/win-64::libwebp-1.2.0-h2bbff1b_0
  lz4-c              pkgs/main/win-64::lz4-c-1.9.3-h2bbff1b_1
  olefile            pkgs/main/win-64::olefile-0.46-py37_0
  pillow             pkgs/main/win-64::pillow-8.4.0-py37hd45dc43_0
  tk                 pkgs/main/win-64::tk-8.6.11-h2bbff1b_0
  xz                 pkgs/main/win-64::xz-5.2.5-h62dcd97_0
  zlib               pkgs/main/win-64::zlib-1.2.11-h62dcd97_4
  zstd               pkgs/main/win-64::zstd-1.4.9-h19a0ad4_0
```

**Comment by wiredfool** [comment]
This is conda issue, as that's the packing that you're using for this. Our binary wheels include the required png libraries.

**Comment by radarhere** [comment]
This is not the place to report a problem with a conda package. We maintain Pillow itself. We don't control conda dependencies.

Looking at https://docs.conda.io/en/latest/contributing.html,
> If your issue is a bug report or feature request for:
> a specific conda package: please file it at https://github.com/ContinuumIO/anaconda-issues/issues

**Comment by mszhanyi** [comment]
> This is conda issue, as that's the packing that you're using for this, though it's unclear if you're getting a conflict because you're using `pip install` with torchvision and not using conda, like the rest of them. Our binary wheels include the required png libraries.

The issue is the included png libraries looks not working in python37 environment on Windows.

**Comment by radarhere** [comment]
Oh, ok. I see. While your subject is about Windows vs Linux, more interesting is that Python 3.8 works on Windows for you, but not Python 3.7.

Just looking at the wheel names, I see that we have Pillow-8.4.0-cp37-cp37m-win_amd64.whl vs Pillow-8.4.0-cp38-cp38-win_amd64.whl (one has m, one does not). Maybe that indicates that the wheels were put together in a different way.

**Comment by hugovk** [comment]
> Just looking at the wheel names, I see that we have Pillow-8.4.0-cp37-cp37m-win_amd64.whl vs Pillow-8.4.0-cp38-cp38-win_amd64.whl (one has m, one does not). Maybe that indicates that the wheels were put together in a different way.

The `m` flag became useless in Python 3.8 and was dropped:

* https://docs.python.org/dev/whatsnew/3.8.html#build-and-c-api-changes

The macOS and manylinux wheel filenames are the same.

**Comment by radarhere** [comment]
Let me just ask. You say "It throws exception." - could we get a traceback of that exception?

**Comment by mszhanyi** [comment]
@radarhere , thank your response. we found it shouldn't be an issue of pillow. Sorry for intrude
