### ISSUE TITLE
Enhancement: Change `Image.tobytes` return type to ByteArray or add a `Image.tobytearray` method

### ISSUE THREAD

**Issue by FirefoxMetzger** [python-pillow/Pillow#5815]
Currently the method `Image.tobytes` returns a byte string. There is nothing inherently bad about this, except that the returned bytes are _read only_ (ofc) since bytes are immutable.

The consequence of this is that `Image.__array__` does an extra copy when calling 

https://github.com/python-pillow/Pillow/blob/a3d1e2f85db890c6a1623e3902711863f55cc54e/src/PIL/Image.py#L678

that (I think) can be avoided. The data is copied from the immutable bytes string into a new mutable memory block around which the array is constructed.

This copy can be avoided in a few ways:

1. Chance the code in `Image.__array__` to (roughly) `np.frombuffer(self.tobytes(), dtype=dtype).reshape(shape)`. The downside is that the result is read-only (`result.flags['WRITEABLE'] == False`) which may be undesirable.
2. Change the code in `Image.tobytes` to return a `bytearray`. This may require work, depending on what `encoder` returns (didn't dive that far into the code), and it may be undesirable because type(Image.tobytes()) changes.
3. Introduce a new `Image.tobytearray` method that essentially mirrors `Image.tobytes`, except that it creates a mutable buffer. This resolves the problems that come with changing `Image.tobytes` return type, but may still need more work.

Would this be something interesting and/or useful to do?

**Comment by radarhere** [comment]
Just a note - one day, the deprecation in https://github.com/numpy/numpy/pull/19001 will be removed, probably in NumPy 1.23, paving the way for us to revert #5379 and move from `__array_interface__` back to `__array__`- making whatever changes we do here redundant. But that is in the future.

I agree that 2 is undesirable, because we value backwards compatibility.

So 3 is most likely the solution - but I don't think it necessarily needs to be a public method, if there's no obvious use case apart from this.

**Comment by FirefoxMetzger** [comment]
@radarhere Yes, other use-cases could go through numpy to get the writable buffer: `np.array(pil_image).data`. Then again numpy isn't a dependency of pillow, iirc, so it may not be available. I don't think this would be a common situation though, and if it does arise then `Image._tobytearray` can always be made public later.

**Comment by hugovk** [comment]
(NumPy minor releases (1.x.0) go out twice a year, so 1.23.0 is due out mid-2022.)

**Comment by radarhere** [comment]
NumPy 1.23 has been released, so I've created #6394 to revert #5379, resolving this.

**Comment by radarhere** [comment]
@FirefoxMetzger is this resolved?
