### ISSUE TITLE
ModuleNotFoundError: No module named 'pil'

### ISSUE THREAD

**Issue by cubecsaba** [python-pillow/Pillow#5817]
### What did you do?
Want to import images

### What did you expect to happen?
"from PIL import ImageTk,Image" does not give any error

### What actually happened?
"ModuleNotFoundError: No module named 'pil'" is reported

### What are your OS, Python and Pillow versions?

* OS: Win10
* Python: 3.10
* Pillow: 8.4.0

```python

from tkinter import *
from PIL import ImageTk,Image

root = Tk()
root.title("Images n shi")
root.iconbitmap('E:/BME/1. félév/Prog alap/Gyakorlás/recycle.ico')

def main():
    button_quit=Button(root, text="Exit program", command=root.quit)
    button_quit.pack()
    
    my_img = imageTk.PhotoImage(Image.open('firefox.png'))
    my_Label = Label(Image=my_img)
    my_Label.pack()
    
    root.mainloop()
main()
```
![pil](https://user-images.githubusercontent.com/46531900/140656811-89dc6395-f193-4f91-85ec-9f117f99badf.png)

**Comment by nulano** [comment]
Hi. I see you've attached a screenshot of pip, but not the actual error, so I can't tell if you are using the same interpreter to actually run your script. How are you running your script? Does `python -m PIL` output anything?

**Comment by cubecsaba** [comment]
Thanks! 
I am running my python script from Thonny V 3.3.13.
Actual error is attached here:
![PILError](https://user-images.githubusercontent.com/46531900/140739672-9ce2c7a6-14c1-4637-9f97-7b8683212a61.png)

Result of -m PIL: 
![PILError](https://user-images.githubusercontent.com/46531900/140739829-8f4d91b2-6120-42f1-8fed-9626a9f3c212.png)

What do these tell you? Thanks agan in advance.

**Comment by cubecsaba** [comment]
Sorry result of -m PIL is here
![result_mPIL](https://user-images.githubusercontent.com/46531900/140740139-be466a85-cbf5-4986-8cf8-c09a9711b1bc.png)
:

**Comment by nulano** [comment]
It looks like you have multiple versions of Python installed. Running `python` from the Windows command line gives you Python 3.10.0 as you can see in the first screenshot (`python -m pip --version`) and the last screenshot (`python -m PIL`), but befroe running your script (second screenshot) it says "Python 3.7.9 (bundled)".

I'm not familiar with "Thonny V 3.3.13", but it seems it includes a bundled version of Python, you need to install Pillow in that version instead.

Alternatively, you can run your script directly from the Windows command line with `python images.py`.

**Comment by cubecsaba** [comment]
Thank you guys, it has sorted out: I have imported Pillow into Thonny...
