### ISSUE TITLE
Incorrect GIF palette in frames after the first

### ISSUE THREAD

**Issue by sliva0** [python-pillow/Pillow#5819]
### Code and Image

Image (```ralsei.gif```): ![ralsei](https://user-images.githubusercontent.com/48382801/140715732-ae8a2bb1-16e7-4115-9542-323a0fde3b57.gif)

```python
from PIL import Image

image = Image.open("ralsei.gif")
image.seek(4)
image.save("ralsei.png")
```

### What did I expect to happen?
The script saves the fifth frame of the gif into a ```.png``` file.

### What actually happened?
```ralsei.png```: ![ralsei](https://user-images.githubusercontent.com/48382801/140716968-8fd9ea7e-f752-4c5e-8c08-d5b1dd835f53.png)
The script saves the fifth frame of the gif into a ```.png``` file, but without the yellow stars, in their place are completely transparent pixels. Possibly due to the fact that there is no yellow in the palette of the first frame.

### OS, Python and Pillow versions:

* OS: Windows 10 Pro 20H2
* Python: 3.10.0
* Pillow: 8.4.0

Also reproducible on:

* OS: Manjaro Linux (arm)
* Python: 3.9.7
* Pillow: 8.4.0

**Comment by SandaruKasa** [comment]
Can't reproduce it on Kubuntu 21.04 x86_64 with Python 3.9.5 and Pillow 8.1.2.
`ralsei.png`:![8.1.2](https://user-images.githubusercontent.com/50824690/140719184-3bb7e12a-905e-4a96-9561-bba97600f780.png)

But with Pillow 8.2.0 (and 8.3.2), the stars disappear and the background turns black.
`8.2.0`:![8.2.0](https://user-images.githubusercontent.com/50824690/140720614-c7a6c436-4b9c-4b91-ba2f-7380f9323fdf.png)
`8.3.2`:![8.3.2](https://user-images.githubusercontent.com/50824690/140720617-3062ac1e-5d82-4898-bf1e-3330b74d3e7e.png)

With Pillow 8.4.0, however, the background is back to normal, but the stars are still missing.
`8.4.0`:![8.4.0](https://user-images.githubusercontent.com/50824690/140720619-1683506f-8747-4169-9d0a-00d8a8cb0d03.png)

**Comment by radarhere** [comment]
I've created PR #5857 to resolve this.

![ralsei](https://user-images.githubusercontent.com/3112309/143822273-5ebeb7cf-a9c7-4f1e-ad6f-57cf2d6ade67.png)
