### ISSUE TITLE
Allow setting specific SDK on macOS

### ISSUE THREAD

**Issue by h-vetinari** [python-pillow/Pillow#5827]
Hey all

I help package things for conda-forge, and pillow 8.4 recently got stuck in limbo due to https://github.com/python-pillow/Pillow/pull/5624 breaking the build we (need to) use there. We rely on the fact that we can control the MacOS SDK being used (which is explicitly set up by conda-build), but after #5624, the sdk from the system gets preference and ends up breaking (mismatched compiler vs. lib).

I reverted it to get https://github.com/conda-forge/pillow-feedstock/pull/101 out the door, but carrying patches indefinitely is not great.

I haven't studied #5622, but I hope we can find a solution that suits everyone. This could (for example) work with an environment variable that gets precedence if non-empty (but many other solutions would likely be possible).

**Comment by radarhere** [comment]
Hi. Could you point me to exactly where conda-forge sets the SDK being used?

**Comment by h-vetinari** [comment]
Have a look at this [CI run](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=408603&view=logs&j=385a3385-ae8b-54d1-9abe-3c614f74cb73&t=a5f9d343-149e-5621-6ab9-f0278009be04&l=772), for example

**Comment by h-vetinari** [comment]
Sorry, azure-links to individual lines are pretty broken. Try looking for "echo 'Downloading 10.9 sdk'" and surrounding lines.

**Comment by h-vetinari** [comment]
The CONDA_BUILD_SYSROOT then obviously goes together with `CONDA_TOOLCHAIN_BUILD=x86_64-apple-darwin13.4.0` (conda-forge generally uses oldest-reasonable compilers to also support older OSes - due to ABI concerns). That toolchain is being set independently of the VM/image where the built-in SDK might be much newer.

AFAICT, the pillow-code post-#5624 then causes the code to refer to the standard library in the system-SDK, which however cannot be processed by the old toolchain. Here's a [failing](https://dev.azure.com/conda-forge/feedstock-builds/_build/results?buildId=394168&view=results) CI run with exactly that.

**Comment by radarhere** [comment]
Ok, what do you think of this idea - we only prefer the command line tools when `xcrun --show-sdk-path` returns the default setting - https://github.com/radarhere/Pillow/commit/58feec8cdaa858fb09ff23b7af608474f29f4416?
