### ISSUE TITLE
embedded_color issue

### ISSUE THREAD

**Issue by matezpaterson** [python-pillow/Pillow#5830]
Hello,

I tried to render a text with a font color like [this one](https://www.fontspace.com/blonde-font-f70195) using embedded_color=True on [draw.text](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text) method, but the output keep being either white or the color set to the "fill" parameter if I put one (black in my example).

```
font = ImageFont.truetype(fontfile, size)
draw.text(((W-left)//2,(H-bottom)//2), txt, font=font, embedded_color=True)
```

Expected : 
![blondepersonaluse-bolditalic](https://user-images.githubusercontent.com/35219765/141342252-b0ea8f19-f93e-4a65-8955-7f072fd69150.png)

Result:
![blonde_black](https://user-images.githubusercontent.com/35219765/141342491-90e82e0c-a123-4373-b2c5-129a1841b914.png)

Pillow-8.4.0

Dependencies:
```
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libXau-00ec42fe.so.6.0.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libfreetype-804dfcff.so.6.18.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libharfbuzz-a69be65e.so.0.30000.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libjpeg-183418da.so.9.4.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/liblcms2-035b9744.so.2.0.12
/usr/local/lib/python3.7/dist-packages/Pillow.libs/liblzma-d540a118.so.5.2.5
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libopenjp2-430a98fc.so.2.4.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libpng16-213e245f.so.16.37.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libtiff-9ffe9659.so.5.7.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libwebp-d8a3db66.so.7.1.2
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libwebpdemux-f117ddb4.so.2.0.8
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libwebpmux-fe44437b.so.3.0.7
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libxcb-1122e22b.so.1.1.0
/usr/local/lib/python3.7/dist-packages/Pillow.libs/libz-dd453c56.so.1.2.11
```

>>> from PIL import features
>>> features.check('raqm')
True

Any heros?

**Comment by nulano** [comment]
What font are you using? How did you install Pillow?

**Comment by matezpaterson** [comment]
As said, i'm using this font https://www.fontspace.com/blonde-font-f70195
I Installed Pillow with Pip
`
python3 -m pip install --upgrade Pillow
`

**Comment by nulano** [comment]
Running `ftdump -t` on your font:
```
D:\Downloads\freetype-demos-master\bin>ftdump.exe -t "..\..\BlondepersonaluseBolditalic-mLOva.otf"
There is 1 face in this file.

----- Face number: 0 -----

font name entries
   family:              Blonde Personal Use
   style:               Bold Italic
   postscript:          BlondePersonalUse-BoldItalic
   created:             2021-01-31
   modified:            2021-11-09
   revision:            1.00
   glyph count:         309

font type entries
   FreeType driver:     cff
   sfnt wrapped:        yes
   type:                scalable
   direction:           horizontal
   fixed width:         no
   glyph names:         yes
   EM size:             1000
   global BBox:         (-2447,-384):(1126,972)
   ascender:            628
   descender:           -284
   height:              962
   max_advance_width:   1249
   max_advance_height:  962
   underline_position:  -100
   underline_thickness: 50

font tables (14)
   0: CFF  01000403...
   1: DSIG 00000001...
   2: GDEF 00010000...
   3: GPOS 00010000...
   4: GSUB 00010000...
   5: OS/2 000401B4...
   6: SVG  00000000...
   7: cmap 00000005...
   8: head 00010000...
   9: hhea 00010000...
  10: hmtx 00900000...
  11: maxp 00005000...
  12: name 0000001F...
  13: post 00030000...

charmaps (6)
   0: unic, platform 0, encoding  3, format  4, language 0
   1: unic, platform 0, encoding  4, format 12, language 0
   2: armn, platform 1, encoding  0, format  6, language 0
   3: unic, platform 3, encoding  1, format  4, language 0
 * 4: unic, platform 3, encoding 10, format 12, language 0
   5: ADOB, platform 7, encoding  0
```
It seems to have SVG format color glyphs. These are not yet supported by FreeType, the dependency Pillow uses to render fonts. As stated [in the documentation](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.text), only COLR, CBDT, and SBIX format fonts are currently supported. Annoyingly, some font authors neglect to mention the glyph format used for their color glyphs.
> embedded_color –
> Whether to use font embedded color glyphs (COLR, CBDT, SBIX).

Here is a link for the issue requesting adding SVG to FreeType: https://gitlab.freedesktop.org/freetype/freetype/-/issues/592
You will likely find more requests in the FreeType mailing list archive.

**Comment by matezpaterson** [comment]
Oh i see, now it make sense.
Thank you for looking at this.
