### ISSUE TITLE
Increase the usage of augmented assignment statements

### ISSUE THREAD

**Issue by elfring** [python-pillow/Pillow#5832]
:eyes: Some source code analysis tools can help to find opportunities for improving software components.
:thought_balloon: I propose to [increase the usage of augmented assignment statements](https://docs.python.org/3/reference/simple_stmts.html#augmented-assignment-statements "Augmented assignment statements") accordingly.

Would you like to integrate anything from a transformation result which can be generated by a command like the following?
(:point_right: Please check also for questionable change suggestions because of an evolving search pattern.)
```
lokal$ perl -p -i.orig -0777 -e 's/^(?<indentation>\s+)(?<target>\S+)\s*=\s*\k<target>[ \t]*(?<operator>[+\-%&|^@]|\*\*?|\/\/?|<<|>>)/$+{indentation}$+{target} $+{operator}=/gm' $(find ~/Projekte/Pillow/lokal -name '*.py')
```

**Comment by hugovk** [comment]
👀 https://github.com/pypa/pip/issues/10624#issuecomment-955765371

**Comment by hugovk** [comment]
Let's just save some time and close this. 

https://github.com/sympy/sympy/issues/22440#issuecomment-962688656

https://github.com/PyCQA/pylint/issues/5174#issuecomment-961406006

https://lkml.org/lkml/2020/6/13/25

https://patchwork.ozlabs.org/project/linux-mtd/patch/e1d32aa4-7c82-64e0-b7c4-33c94d9a2769@web.de/

https://forums.somethingawful.com/showthread.php?threadid=2803713&userid=0&perpage=40&pagenumber=1400
