### ISSUE TITLE
Incorrect image data and type after TIFF compression

### ISSUE THREAD

**Issue by XrioBtw** [python-pillow/Pillow#5843]
When saving an image containing float data as a compressed TIFF the output image data and number type is incorrect (here the `float32` becomes `int32`). The output is correct if I specify `compression = None` or if the input image data is of e.g. type `uint8`. If I specify `compression = "something wrong"` I get no error message, the compression defaults to `"compression": "raw"`, but the output image data and type is still wrong.

```python
import numpy as np
from PIL import Image
from tempfile import TemporaryFile

with TemporaryFile() as fp:
    Z = np.array([[np.pi, np.pi], [np.pi, np.pi]], dtype = np.float32)
    img = Image.fromarray(Z)
    img.save(fp, format = "TIFF", compression = "packbits")
    img = Image.open(fp)
    print(img.info)   # {'compression': 'packbits', 'dpi': (1, 1), 'resolution': (1, 1)}
    Z = np.asarray(img)
    print(Z)   # [[1078530011, 1078530011], [1078530011, 1078530011]]
    print(Z.dtype)   # int32
```

**Comment by radarhere** [comment]
Just a note - it is libtiff that is converting an F mode image to I mode. When libtiff is not used, it stays in F mode.

Here is a demonstration without NumPy.
```python
from PIL import Image, TiffImagePlugin

for libtiff in (True, False):
    TiffImagePlugin.WRITE_LIBTIFF = libtiff
    img = Image.new("F", (1, 1), 0.5)
    path = ("libtiff" if libtiff else "without_libtiff")+".tif"
    img.save(path)
    with Image.open(path) as reloaded:
        print(libtiff, reloaded.mode)
```
gives
```
True I
False F
```

**Comment by radarhere** [comment]
I've created PR #5848 to resolve this.
