### ISSUE TITLE
webp decoder is leaking memory

### ISSUE THREAD

**Issue by totaam** [python-pillow/Pillow#586]
You must also free the pixel buffer when dealing with RGB data, just after calling PyBytes_FromStringAndSize.

I have written a simple standalone test case you can run to see the damage for yourself:
http://xpra.org/trac/browser/xpra/trunk/src/tests/xpra/codecs/test_Pillow.py

And you can see our fix here (for Cython code, but you get the idea):
http://xpra.org/trac/changeset/5945/xpra

**Comment by wiredfool** [comment]
#1114 fixes this OMM.

**Comment by gumblex** [comment]
@wiredfool Thanks for the fix. I have tested about a GB's pictures, and there is no longer obvious leaking.
