### ISSUE TITLE
Release Pillow 9.0.0 on January 2, 2022

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#5860]
## Main Release

Released quarterly on January 2nd, April 1st, July 1st and October 15th.

* [x] Open a release ticket e.g. https://github.com/python-pillow/Pillow/issues/3154
* [x] Develop and prepare release in `main` branch.
* [x] Check [GitHub Actions](https://github.com/python-pillow/Pillow/actions) and [AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm passing tests in `main` branch.
* [x] Check that all of the wheel builds [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels) pass the tests in Travis CI and GitHub Actions.
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Update `CHANGES.rst`.
* [x] Run pre-release check via `make release-test` in a freshly cloned repo.
* [x] Create branch and tag for release e.g.:
  ```bash
  git branch 9.0.x
  git tag 9.0.0
  git push --all
  git push --tags
  ```
* [x] Create and check source distribution:
  ```bash
  make sdist
  twine check dist/*
  ```
* [x] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/main/RELEASING.md#binary-distributions)
* [x] Check and upload all binaries and source distributions e.g.:
  ```bash
  twine check dist/*
  twine upload dist/Pillow-9.0.0*
  ```
* [x] Publish the [release on GitHub](https://github.com/python-pillow/Pillow/releases)
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), increment and append `.dev0` to version identifier in `src/PIL/_version.py`

### Windows
* [x] Contact `@cgohlke` for Windows binaries via release ticket e.g. https://github.com/python-pillow/Pillow/issues/1174.
* [x] Download and extract tarball from `@cgohlke` and copy into `dist/`

### Mac and Linux
* [x] Use the [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels):
  ```bash
  git clone https://github.com/python-pillow/pillow-wheels
  cd pillow-wheels
  ./update-pillow-tag.sh [[release tag]]
  ```
* [x] Download wheels from the [Pillow Wheel Builder release](https://github.com/python-pillow/pillow-wheels/releases)
  and copy into `dist/`

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the [default version for Read the Docs](https://pillow.readthedocs.io/en/stable/) is up-to-date with the release changes

## Docker Images

* [x] Update Pillow in the Docker Images repository
  ```bash
  git clone https://github.com/python-pillow/docker-images
  cd docker-images
  ./update-pillow-tag.sh [[release tag]]
  ```

**Comment by radarhere** [comment]
A note for when we request the Windows binaries - https://github.com/python-pillow/Pillow/issues/5697#issuecomment-911819922 should now be fixed with the release of freetype 2.11.1.

**Comment by radarhere** [comment]
Ok, @cgohlke, could we kindly have the Windows binaries for 9.0.0?

**Comment by cgohlke** [comment]
[Here](https://www.lfd.uci.edu/~gohlke/download/Pillow-9.0.0-win-dist.zip) you go.

**Comment by radarhere** [comment]
Thanks very much!

[Released](https://pypi.org/project/Pillow/9.0.0/), and [announced!](https://twitter.com/PythonPillow/status/1477774829281447938)

**Comment by h-vetinari** [comment]
Hey all, congratulations on the release! 🥳

I'm getting
```
    from PIL import Image
  File "D:\bld\pillow_1641174407982\_test_env\lib\site-packages\PIL\Image.py", line 93, in <module>
    "The _imaging extension was built for another version of Pillow or PIL:\n"
ImportError: The _imaging extension was built for another version of Pillow or PIL:
Core version: "9.0.0"
Pillow version: 9.0.0
```
in https://github.com/conda-forge/pillow-feedstock/pull/104 for windows with cpython 3.7 & 3.8 (not for 3.9, 3.10 or pypy though), seems like an issue with some extra quotes? Should I raise an issue for that?

**Comment by radarhere** [comment]
Hi. Yes, a new issue would be helpful, thanks.

This would be connected to https://github.com/python-pillow/Pillow/blob/05b63366df05ebe8dd182f4e1596b23582631b3d/setup.py#L843-L850

I'm not yet clear on why this would suddenly be a problem now.

**Comment by homm** [comment]
Pillow-SIMD `9.0.0.post0` released as well.
https://pypi.org/project/Pillow-SIMD/9.0.0.post0/
