### ISSUE TITLE
Wrong GPSInfo from `.getexif()`

### ISSUE THREAD

**Issue by Olegt0rr** [python-pillow/Pillow#5863]
Bug from #1477 still actual for public `getexif` method.

### What did you do?
Trying to get valid GPSInfo data from EXIF:

```python
from PIL import Image
from PIL.Image import Exif
from PIL.ExifTags import TAGS, GPSTAGS

def get_exif(file_name) -> Exif:
    image: Image.Image = Image.open(file_name)
    return image.getexif()


def get_labeled_exif(exif):
    return {
        TAGS.get(key, key): value
        for key, value in exif.items()
    }


def get_geo(labeled_exif):
    gps_info = labeled_exif.get("GPSInfo", {})
    return {
        GPSTAGS.get(key, key): value
        for key, value in gps_info.items()
    }

if __name__ == '__main__':
    exif = get_exif("Tests/images/exif_gps.jpg")
    labeled_exif = get_labeled_exif(exif)
    geo = get_geo(labeled_exif)
    print(geo)

```

### What did you expect to happen?
Result
```python
{'GPSVersionID': b'\x00\x00\x00\x01', 'GPSLatitude': 4294967295.0, 'GPSAltitudeRef': b'\x01', 'GPSDateStamp': '1999:99:99 99:99:99', 'GPSDifferential': 65535}
```

### What actually happened?
```
Traceback (most recent call last):
  line 33, in <module>
    geo = get_geo(labeled_exif)
  line 22, in get_geo
    for key, value in gps_info.items()
AttributeError: 'int' object has no attribute 'items'
```

### What are your OS, Python and Pillow versions?

* OS: macOS
* Python: 3.8
* Pillow: 8.4.0

### Workaround
Use `image._getexif()` instead of `image.getexif()`

### Tests
So why the Pillow tests pass successfully?
That's why:
https://github.com/python-pillow/Pillow/blob/bd00cd9214f986ceeef7d1707664f71231a5f643/Tests/test_file_jpeg.py#L254-L256

**Comment by radarhere** [comment]
Hi. My explanation is that GPSInfo is an IFD - https://www.awaresystems.be/imaging/tiff/tifftags/gpsifd.html.

The int that you're seeing is not the data itself, but the offset to the data, [in case anyone would like to access that.](https://github.com/python-pillow/Pillow/pull/4947#discussion_r502904408)

Instead,  you can use `get_ifd` to retrieve the GPS data.

See what you think of this.

```python
from PIL import Image
from PIL.Image import Exif
from PIL.ExifTags import TAGS, GPSTAGS

def get_exif(file_name) -> Exif:
    image: Image.Image = Image.open(file_name)
    return image.getexif()


def get_geo(exif):
    for key, value in TAGS.items():
        if value == "GPSInfo":
            break
    gps_info = exif.get_ifd(key)
    return {
        GPSTAGS.get(key, key): value
        for key, value in gps_info.items()
    }

if __name__ == '__main__':
    exif = get_exif("Tests/images/exif_gps.jpg")
    geo = get_geo(exif)
    print(geo)
```

**Comment by radarhere** [comment]
You gave my response a thumbs up. Does that mean you're happy with this and the issue can be closed?

**Comment by Olegt0rr** [comment]
@radarhere, I still can't understand behaviour of public exif method, e.g.:
`DateTimeOriginal` exists in `._get_exif()` and absent in `.get_exif()` result

**Comment by radarhere** [comment]
`DateTimeOriginal` is within the EXIF IFD - https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif.html

`_getexif()` merged the EXIF IFD into the rest of the top level items. This makes it harder to figure out afterwards what was in the EXIF IFD and what was at the top level to begin with. So since #4947, `getexif()` no longer does that. Instead, `DateTimeOriginal` can be found like so -

```python
from PIL import Image
from PIL.Image import Exif
from PIL.ExifTags import TAGS

def get_exif(file_name) -> Exif:
    image: Image.Image = Image.open(file_name)
    return image.getexif()


def get_exif_ifd(exif):
    for key, value in TAGS.items():
        if value == "ExifOffset":
            break
    info = exif.get_ifd(key)
    return {
        TAGS.get(key, key): value
        for key, value in info.items()
    }

if __name__ == '__main__':
    exif = get_exif("Tests/images/exif_gps.jpg")
    print(get_exif_ifd(exif))
```
gives
```
{'DateTimeOriginal': '2099:09:29 10:10:10', 'ExposureBiasValue': -0.9999999995343387, 'OECF': b'\xaa\xaa\xaa\xaa\xaa\xaa', 'Sharpness': 65535, 'LensSpecification': (1.0, 1.0, 1.0, 1.0), 'ISOSpeed': 4294967295, 'LensMake': 'LensMake', 'ExposureTime': 4294967295.0}
```

**Comment by Olegt0rr** [comment]
Thanks! Now that's clear for me :)

**Comment by jlw4049** [comment]
> `DateTimeOriginal` is within the EXIF IFD - https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif.html
> 
> `_getexif()` merged the EXIF IFD into the rest of the top level items. This makes it harder to figure out afterwards what was in the EXIF IFD and what was at the top level to begin with. So since #4947, `getexif()` no longer does that. Instead, `DateTimeOriginal` can be found like so -
> 
> ```python
> from PIL import Image
> from PIL.Image import Exif
> from PIL.ExifTags import TAGS
> 
> def get_exif(file_name) -> Exif:
>     image: Image.Image = Image.open(file_name)
>     return image.getexif()
> 
> 
> def get_exif_ifd(exif):
>     for key, value in TAGS.items():
>         if value == "ExifOffset":
>             break
>     info = exif.get_ifd(key)
>     return {
>         TAGS.get(key, key): value
>         for key, value in info.items()
>     }
> 
> if __name__ == '__main__':
>     exif = get_exif("Tests/images/exif_gps.jpg")
>     print(get_exif_ifd(exif))
> ```
> 
> gives
> 
> ```
> {'DateTimeOriginal': '2099:09:29 10:10:10', 'ExposureBiasValue': -0.9999999995343387, 'OECF': b'\xaa\xaa\xaa\xaa\xaa\xaa', 'Sharpness': 65535, 'LensSpecification': (1.0, 1.0, 1.0, 1.0), 'ISOSpeed': 4294967295, 'LensMake': 'LensMake', 'ExposureTime': 4294967295.0}
> ```

I couldn't find this anywhere in the documentation. This works really well, thanks for sharing here.

**Comment by andras-tim** [comment]
As I understand, the Exif contains different sets of data `0th`, `Exif`, `GPS`, ... which are stored in different ways.

``` python
from PIL import ExifTags, Image

# Load image
image: Image.open(path)
exif = image.getexif()
exif_ifd = exif.get_ifd(ExifTags.IFD.Exif)
gps_ifd = exif.get_ifd(ExifTags.IFD.GPSInfo)
```

You can get one particular value like this:

``` python
print(exif[ExifTags.Base.DateTime])
print(exif_ifd[ExifTags.Base.DateTimeOriginal])
print(gps_ifd[ExifTags.GPS.GPSLongitude])
```

Or transform the ID keyed dict to a human-readable dict:

``` python
exif_h = {ExifTags.TAGS[k]: v for k, v in exif.items()}
exif_ifd_h = {ExifTags.TAGS[k]: v for k, v in exif_ifd.items()}
gps_ifd_h = {ExifTags.GPSTAGS[k]: v for k, v in gps_ifd.items()}
```

**Comment by mixmastamyk** [comment]
Link above no longer working, but found it below.  There's not much interesting there however, page just states it can be an "IFD" or a long:

https://web.archive.org/web/20240329145327/https://www.awaresystems.be/imaging/tiff/tifftags/gpsifd.html
