### ISSUE TITLE
Incorrect behaviour of the ImageFile._safe_read function

### ISSUE THREAD

**Issue by leon9812** [python-pillow/Pillow#5871]
### What did you do?

Randomly came across the [ImageFile._safe_read](https://github.com/python-pillow/Pillow/blob/ab6efcb925f615d153538e84780f093f7f9f8df2/src/PIL/ImageFile.py#L527) fuction.

### What did you expect to happen?

An "OSError: Truncated File Read" if the length of the file-like object `fp` is less than the value of the `size` parameter.

### What actually happened?

Not always getting an OSError if the value for `size` is larger than `ImageFile.SAFEBLOCK` (and the length of fp is less than size).

### What are your OS, Python and Pillow versions?

* OS: Windows 10 (21H1)
* Python: 3.8.10
* Pillow: 8.4.0

```python
import io
from PIL import ImageFile

fp = io.BytesIO(b"0" * ImageFile.SAFEBLOCK)
size = ImageFile.SAFEBLOCK + 1

# no error, but expected OSError:
content = ImageFile._safe_read(fp=fp, size=size)

print(len(content))
# 1048576
print(size)
# 1048577
```

**Comment by hugovk** [comment]
Why are you calling `_safe_read`? It's a "private" function and not part of the public API, as denoted by the leading underscore.

Is there a concrete problem when calling this via the public API?

**Comment by leon9812** [comment]
I didn't find a problem via the public API. I just found this function because it raised an exception for a incompatible / truncated image and noticed, that it does not always do what its docstring describes. I just thought it is worth reporting so there are no problems in the future (regarding that function).

**Comment by radarhere** [comment]
I've figured out a test case for this using our public APIs, and created #5872 accordingly.

**Comment by hugovk** [comment]
Merged, thanks both!
