### ISSUE TITLE
8.4.0 automatically exits loop after first `Image.open()`

### ISSUE THREAD

**Issue by Sile96** [python-pillow/Pillow#5873]
Found a version issue when using `pillow`. Running the code below with `pillow` 8.4.0 will print the first `Image.open()`, but then will automatically exit the loop. No errors will be present. After downgraded to version 8.0.0, the function will work. 

```python
from PIL import Image
import os

path_in = 'D:/TIF_STORAGE/'
path_out = 'D:/Convert/'


def manip_img(in_pth, out_pth):
    i = 0
    for img in os.listdir(in_pth):
        img_open = Image.open(in_pth + img)
        print(img_open)
        conv = img_open.copy()
        print(conv)
        conv.save(out_pth + str(i) + '.tif') 
        i = i + 1
        
        
manip_img(path_in, path_out)
```

**Comment by radarhere** [comment]
Could you attach a copy of that first image?

**Comment by Sile96** [comment]
I apologize, but I am unable to reproduce the problem. I have been trying to compare my env package version from before and after, but I cannot find the problem. Just tried 8.4.0 and it worked. Might have been a defective install on my part. Again, sorry about that.
