### ISSUE TITLE
No module named PIL

### ISSUE THREAD

**Issue by BorScho** [python-pillow/Pillow#5880]
### What did you do?
Using VsCode.

1. In terminal I created a conda virtual environment:
`conda create --name conenv_multiMnist`

2. Installed pytorch from conda-forge:
`conda install pytorch torchvision -c pytorch -c conda-forge`

3. executed a progam "pillow01.py" containing:
```python
import PIL
from PIL import Image
```
Result:
`ModuleNotFoundError: No module named 'PIL'`

4. installed pillow:
`conda install -c anaconda pillow`
Result - now I have: 
C:\Users\BoSc\anaconda3\envs\conenv_multiMnist\Lib\site-packages\PIL and C:\Users\BoSc\anaconda3\envs\conenv_multiMnist\Lib\site-packages\Pillow-8.0.0.dist-info

5. Tried to execute my program again:
(conenv_multiMnist) C:\Users\BoSc\Documents\9999_Public_Repository_Github\BSC Public Github\multi_digit_MNIST>pillow01
```
Traceback (most recent call last):
  File "C:\Users\BoSc\Documents\9999_Public_Repository_Github\BSC Public Github\multi_digit_MNIST\pillow01.py", line 1, in <module>
    import PIL
ModuleNotFoundError: No module named 'PIL'
```
Same if I try to call it while environment is deactivated.

### Observation:
Earlier I tried the same with the same result: creating new conda environment, installing pytorch in it - from conda standard channel (comes with pillow included), executed my program got "No module named 'PIL'". I did not try to remove pillow and reininstall. But I had Python 3.9.7 and pillow 8.4.0 from the pytorch install.
When I did the pytorch install from conda-forge and installed an additional conda pillow, it gave me python 3.8.5 and pillow 8.0.0, though the pillow version on [conda ](https://anaconda.org/anaconda/pillow) is 8.4.0. Don't know if this means anything at all.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8.5; 3.9.7
* Pillow: 8.0.0; 8.4.0

**Comment by BorScho** [comment]
I did one more test:
1. created new conda environment.
2. conda installed python 3.9.7 and pillow 8.4.0
3. executed program containing the lines: "import PIL" and "from PIL import Image"
4. Result:
import PIL
ModuleNotFoundError: No module named 'PIL'

The installed files reside in:

C:\Users\BoSc\anaconda3\envs\conenv_testPillow\Lib\site-packages\PIL
C:\Users\BoSc\anaconda3\envs\conenv_testPillow\Lib\site-packages\Pillow-8.4.0-py3.9.egg-info

All commands where executed in VSCode terminal, the selected python interpreter for the python .py file is the one installed in the virtual environment.

**Comment by BorScho** [comment]
Found the error - though I don't understand it: if I start .py-file execution by using the "play"-button in the right upper corner of VSCode, everything works. If I choose "Run python file" from that button, everything works too, plus it prints the command to the terminal:
(conenv_testPillow) C:\Users\BoSc\Documents\9999_Public_Repository_Github\BSC Public Github\multi_digit_MNIST>C:/Users/BoSc/anaconda3/envs/conenv_testPillow/python.exe "c:/Users/BoSc/Documents/9999_Public_Repository_Github/BSC Public Github/multi_digit_MNIST/pillow01.py"

i.e. it uses the complete path to the python.exe and to the .py-file ...
If I just type "pillow01", the correct file is found but I get the >>ModuleNotFoundError: No module named 'PIL'<<

I am sure there is a reason for this behavior ...
I guess it is either a PATH issue or a VSCode issue, not pillow. 
Would be nice to know what happens and why.
Otherwize the issue can be closed.

**Comment by radarhere** [comment]
Are you sure that it's the same Python that's run by both?
```pycon
>>> import sys
>>> print(sys.executable)
```

**Comment by kero-ly** [comment]
A quick way to validate your python packages
>>> conda activate conenv_multiMnist
>>> pip show Pillow
If you can see any info of Pillow, that says your python env is correct, like this
Name: Pillow
Version: 8.4.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: /home/xxxx/install/lib/python3.7/site-packages

If your python env does not have Pillow, then you will get:
WARNING: Package(s) not found: Pillow

If you have confirmed there is no Pillow in your python env, just install it through
>>> pip install Pillow

**Comment by kmilos** [comment]
I've also found that VSCode doesn't always start the conda environment you think it would, I haven't always figured out why/how.

I always make sure the right environment is selected in the bottom left status bar, and also do `conda activate <my_env>` in any open terminals.

**Comment by BorScho** [comment]
import sys

> Are you sure that it's the same Python that's run by both?
> 
> ```
> >>> import sys
> >>> print(sys.executable)
> ```

When I do this I get:
C:/Users/BoSc/anaconda3/envs/conenv_testPillow/python.exe 
That is the python.exe in my virtual environment and as far as I understand should be the one executed by default, when the environment is activated and I told VSCode to use it for this folder.
