### ISSUE TITLE
Does swapping a PIL.Image in a variable release the old PIL.Image from memory?

### ISSUE THREAD

**Issue by ShaunKulesa** [python-pillow/Pillow#5889]
I have a for loop in my Texture-Atlas code, does replacing `image` with another PIL.Image release the old PIL.Image from the memory or should I close each image inside the for loop when I am finished with pasting them into the atlas?

```python
for texture in self.textures:
    image = Image.open(texture)
    self.atlas.paste(image)
```

**Comment by radarhere** [comment]
You're asking about something like this?
```python
for texture in self.textures:
    image = Image.open(texture)
    image2 = Image.open(texture)
    self.atlas.paste(image2)
```
You should still close both `image` and `image2`, to close the file pointer.

**Comment by ShaunKulesa** [comment]
Each time the for loop runs, `image` is going to be replaced with a new PIL.Image, is the PIL.Image in the previous loop turn going to be removed from the RAM is what I mean. If that makes any more sense?

**Comment by radarhere** [comment]
Python's garbage collector should take care of that, yes.

**Comment by ShaunKulesa** [comment]
Ok, thank you.
