### ISSUE TITLE
Make the size of a font accessible

### ISSUE THREAD

**Issue by jvanasco** [python-pillow/Pillow#589]
The arguments to `PIL.ImageFont.truetype()` are a black hole.  once created, the kwargs, including `size`, appear impossible to pull back.

It would be nice if these kwargs were at least readable.

* font file
* font size
* index
* encoding

This would better allow users to create a new font object at a different size or face.  This is necessary when trying to fit text onto a smaller canvas.  Text sizing with the current API is awkward, because the details of the font object must be tracked separately.  

Being able to do something like this would be a great timesaver for many:

    font_1 = PIL.ImageFont.truetype( font=font, size=20 )
    ....
    font_2 = PIL.ImageFont.truetype( font=font, size=font_1.size-2 )

It would be even nicer, if a new variant of a font object could be created from an existing font as well.

    font_1 = PIL.ImageFont.truetype( font=font, size=20 )
    font_2 = font_1.font_variant( size = (font_1.size - 2) )

**Comment by radarhere** [comment]
Given that #1123 has been merged, this issue can now be closed.
