### ISSUE TITLE
Changing Jupyter plain text output on every cell run

### ISSUE THREAD

**Issue by shamrin** [python-pillow/Pillow#5890]
### What did you do?

I'm using Pillow to generate simple images in Jupyter environment:

```python
from PIL import Image
Image.frombuffer('RGB', (16,16), bytes([100]*(16*16)))
```

It works nicely!

![image](https://user-images.githubusercontent.com/510678/146259055-bff41a14-b40d-452e-a354-11c05ce78b58.png)

### What did you expect to happen?

I expect every run of the cell produce the same output in the notebook file, to avoid needless changes in Git.

### What actually happened?

Every run produces different hash in text representation of the output. For example: `at 0x1075D8370`.

```diff
$ git diff test.ipynb 
diff --git a/test.ipynb b/test.ipynb
index f769d4b..a4dd8af 100644
--- a/test.ipynb
+++ b/test.ipynb
@@ -9,7 +9,7 @@
      "data": {
       "image/png": "iVBORw0KGgoAAAANSUhEUgAAABAAAAAQCAIAAACQkWg2AAAAGUlEQVR4nGPc62fCQApgIkn1qIZRDUNKAwADRwFfBBwAnwAAAABJRU5ErkJggg==",
       "text/plain": [
-       "<PIL.Image.Image image mode=RGB size=16x16 at 0x1075D8370>"
+       "<PIL.Image.Image image mode=RGB size=16x16 at 0x108C50160>"
       ]
      },
      "execution_count": 1,
```

Compare with Matplotlib output:

```json
     "data": {
      "image/png": "...",
      "text/plain": [
       "<Figure size 432x288 with 1 Axes>"
      ]
     }
```

### What are your OS, Python and Pillow versions?

* OS: Mac OS 10.15.6
* Python: 3.9.8
* Pillow: 8.4.0

**Comment by radarhere** [comment]
Hi. Good work on being proactive enough to create PR to fix your issue, but I don't personally think this is a compelling enough case for the change.

You should also be able to add your modification in dynamically when you run your code.

```python
from PIL import Image

def _repr_pretty_(self, p, cycle):
    p.text(
        "<%s.%s image mode=%s size=%dx%d>"
        % (
            self.__class__.__module__,
            self.__class__.__name__,
            self.mode,
            self.size[0],
            self.size[1],
        )
    )
Image.Image._repr_pretty_ = _repr_pretty_
```

**Comment by shamrin** [comment]
@radarhere Thanks for a quick reply! It didn't take much time to create a PR.

Your suggested monkeypatching is neat! But I think it doesn't make much sense in Jupyter context. Jupyter notebooks are usually focused experiments. Personally I spend all the efforts on the task at hand, and also on documenting it for myself and the reader. Adding hacks like this would make notebook harder to read. I would also have to copy it to every notebook.

**Comment by shamrin** [comment]
I've found a workaround - use matplotlib to show the image in the Jupyter notebook.

```python
from PIL import Image
import matplotlib.image as mpimg
import matplotlib.pyplot as plt

image = Image.frombuffer('RGB', (16,16), bytes([189,78,52]*(16*16)))
plt.imshow(mpimg.pil_to_array(image))
plt.show()
```

The rendering is different from plain PNG, but it works for my task:

![image](https://user-images.githubusercontent.com/510678/146540795-264b7286-be76-4830-ab34-536315b73d2f.png)

**Comment by radarhere** [comment]
This feels to me like it is specific to how you have chosen to work. Do you have any evidence that other users are performing diffs on their Jupyter notebook output?

**Comment by shamrin** [comment]
@radarhere I think it's common. Every time you commit Jupyter notebook to Git, it's output is committed as well, by default:

https://github.com/search?q=language%3A%22Jupyter+Notebook%22+pil&type=code

**Comment by shamrin** [comment]
Admittedly, some of the search results show stdout, which would always use `__repr__`.

Here is the more narrowed search to answer your question, with `image` output only. It's still sizable 108,000+ results:

https://github.com/search?q=language%3A%22Jupyter+Notebook%22+pil+text+plain+image+png+at&type=code

![image](https://user-images.githubusercontent.com/510678/146672479-174be206-32c6-4e4d-a1b6-7d49c94f503c.png)

**Comment by hugovk** [comment]
I rarely use Jupyter much but nice output is an important aspect of Jupyter, the notebook is like a combination IDE and terminal for running code, and it has a whole bunch of `_repr_*_()` methods that can be used.

https://ipython.readthedocs.io/en/stable/config/integrating.html

We already have `_repr_png_` (added in 2015: https://github.com/python-pillow/Pillow/pull/1091).

It might be useful to point out some other `_repr_pretty_()` (or `_repr_*_()`) examples in other libraries that produce constant output.

(Hmm, this might be a tricky request, it would likely require the `__repr__` producing variable output...)

**Comment by radarhere** [comment]
https://github.com/matplotlib/matplotlib/issues/9372 is a discussion about this functionality, but for matplotlib, started by a core developer of Jupyter - so, ok, I'm sold now on the idea that is not an obscure need.

**Comment by shamrin** [comment]
Thank you @radarhere!
