### ISSUE TITLE
TypeError: color must be int or single-element tuple

### ISSUE THREAD

**Issue by Windy2212** [python-pillow/Pillow#5892]
Here is the error encountered:

Here is the code I am running:

```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont, ImageOps
label1 = "VIKRAM"
font = ImageFont.truetype('D:/vikram/pythonProject/fonts/BalloonCraft-9YBK7.ttf', 800)
line_height = sum(font.getmetrics())
fontimage1 = Image.new('L', (font.getsize(label1)[0], line_height))
ImageDraw.Draw(fontimage1).text((0,0),str(label1),stroke_width=10, stroke_fill=(0, 0, 0), fill=255, font=font)
fontimage1 = fontimage1.rotate(90, resample=Image.NEAREST, expand=True)
orig = Image.open('F:/desktop/Kitty/PSI Hello Kitty Theme Personalized Door Poster-1.png')
orig.paste((135, 255, 135), box=(2200, 1500), mask=fontimage1)
orig.show()
```

Error in line no: 8 

How did I give Stroke Fill Color ??

If you have any idea how to fix this, please I would be very grateful. Thanks in advance.

**Comment by radarhere** [comment]
Your code states that `fontimage1` should be "L" mode. This means it is a grayscale image, not RGB.

But you specified `stroke_fill=(0, 0, 0)`. `(0, 0, 0)` is RGB. There is no red, green and blue in a grayscale image, so you get an error.

Instead, I suggest `stroke_fill=0`.

**Comment by Windy2212** [comment]
It is Not Working , Kindly Sugg me ..Or Rewrite the code 
My Requirement is Need To Rotate Text and also as I need To Give Stroke Fill Color In RBG Format

**Comment by radarhere** [comment]
Ok, here is your code but with an RGB stroke fill color - I have changed "fontimage1" to be in RGB mode.

```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont, ImageOps
label1 = "VIKRAM"
font = ImageFont.truetype('D:/vikram/pythonProject/fonts/BalloonCraft-9YBK7.ttf', 800)
line_height = sum(font.getmetrics())
fontimage1 = Image.new('RGB', (font.getsize(label1)[0], line_height))
ImageDraw.Draw(fontimage1).text((0,0),str(label1),stroke_width=10, stroke_fill=(0, 0, 0), fill=255, font=font)
fontimage1 = fontimage1.rotate(90, resample=Image.NEAREST, expand=True)
orig = Image.open('F:/desktop/Kitty/PSI Hello Kitty Theme Personalized Door Poster-1.png')
orig.paste((135, 255, 135), box=(2200, 1500), mask=fontimage1)
orig.show()
```

**Comment by Windy2212** [comment]
> Your code states that `fontimage1` should be "L" mode. This means it is a grayscale image, not RGB.
> 
> But you specified `stroke_fill=(0, 0, 0)`. `(0, 0, 0)` is RGB. There is no red, green and blue in a grayscale image, so you get an error.
> 
> Instead, I suggest `stroke_fill=0`.

It is Not Working , Kindly Sugg me ..Or Rewrite the code
My Requirement is Need To Rotate Text and also as I need To Give Stroke Fill Color In RBG Format

**Comment by Windy2212** [comment]
> 
ValueError: bad transparency mask

This Error Occur ..

**Comment by radarhere** [comment]
Ok, let's try RGBA instead.

```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont, ImageOps
label1 = "VIKRAM"
font = ImageFont.truetype('D:/vikram/pythonProject/fonts/BalloonCraft-9YBK7.ttf', 800)
line_height = sum(font.getmetrics())
fontimage1 = Image.new('RGBA', (font.getsize(label1)[0], line_height))
ImageDraw.Draw(fontimage1).text((0,0),str(label1),stroke_width=10, stroke_fill=(0, 0, 0), fill=255, font=font)
fontimage1 = fontimage1.rotate(90, resample=Image.NEAREST, expand=True)
orig = Image.open('F:/desktop/Kitty/PSI Hello Kitty Theme Personalized Door Poster-1.png')
orig.paste((135, 255, 135), box=(2200, 1500), mask=fontimage1)
orig.show()
```

**Comment by radarhere** [comment]
If that does not work, please provide a copy of your image and font, since at the moment, I can't run your code in the same way that you can.

**Comment by Windy2212** [comment]
> Ok, let's try RGBA instead.
> 
> ```python
> from PIL import Image
> from PIL import ImageDraw
> from PIL import ImageFont, ImageOps
> label1 = "VIKRAM"
> font = ImageFont.truetype('D:/vikram/pythonProject/fonts/BalloonCraft-9YBK7.ttf', 800)
> line_height = sum(font.getmetrics())
> fontimage1 = Image.new('RGBA', (font.getsize(label1)[0], line_height))
> ImageDraw.Draw(fontimage1).text((0,0),str(label1),stroke_width=10, stroke_fill=(0, 0, 0), fill=255, font=font)
> fontimage1 = fontimage1.rotate(90, resample=Image.NEAREST, expand=True)
> orig = Image.open('F:/desktop/Kitty/PSI Hello Kitty Theme Personalized Door Poster-1.png')
> orig.paste((135, 255, 135), box=(2200, 1500), mask=fontimage1)
> orig.show()
> ```

Already I tried .. RGB and RGBA , But Stroke Effort not coming

**Comment by radarhere** [comment]
Could you attach copies of "PSI Hello Kitty Theme Personalized Door Poster-1.png" and "BalloonCraft-9YBK7.ttf"?

**Comment by Windy2212** [comment]
YES

**Comment by radarhere** [comment]
I don't see any attachments.

**Comment by Windy2212** [comment]
> I don't see any attachments.

Try Ur Self And tell me , Plz Do this NeedFully..

**Comment by radarhere** [comment]
If I modify your code like this,
```python
from PIL import Image
from PIL import ImageDraw
from PIL import ImageFont, ImageOps
label1 = "VIKRAM"
font = ImageFont.truetype('Tests/fonts/FreeMono.ttf', 32)
line_height = sum(font.getmetrics())
fontimage1 = Image.new('RGBA', (font.getsize(label1)[0]+10, line_height))
ImageDraw.Draw(fontimage1).text((5,0), label1, stroke_width=2, stroke_fill=(255, 0, 0), fill=255, font=font)
fontimage1 = fontimage1.rotate(90, resample=Image.NEAREST, expand=True)
orig = Image.open('Tests/images/hopper.png')
orig.paste(fontimage1, (0, 0), fontimage1)
orig.show()
```
I get

![tmp](https://user-images.githubusercontent.com/3112309/146489537-940c3a31-7234-43b3-8367-6ab2171292e0.png)

I don't know what you hoped to do with `orig.paste((135, 255, 135), box=(2200, 1500), mask=fontimage1)`, so I have changed it to `orig.paste(fontimage1, (0, 0), fontimage1)`. I have also reduced the font size to fit in my smaller image, changed the text x position and `fontimage1` width.

If you would like more help than that, please upload your image and font to a post here.

**Comment by Windy2212** [comment]
> If I modify your code like this,
> 
> ```python
> from PIL import Image
> from PIL import ImageDraw
> from PIL import ImageFont, ImageOps
> label1 = "VIKRAM"
> font = ImageFont.truetype('Tests/fonts/FreeMono.ttf', 32)
> line_height = sum(font.getmetrics())
> fontimage1 = Image.new('RGBA', (font.getsize(label1)[0]+10, line_height))
> ImageDraw.Draw(fontimage1).text((5,0), label1, stroke_width=2, stroke_fill=(255, 0, 0), fill=255, font=font)
> fontimage1 = fontimage1.rotate(90, resample=Image.NEAREST, expand=True)
> orig = Image.open('Tests/images/hopper.png')
> orig.paste(fontimage1, (0, 0), fontimage1)
> orig.show()
> ```
> 
> I get
> 
> ![tmp](https://user-images.githubusercontent.com/3112309/146489537-940c3a31-7234-43b3-8367-6ab2171292e0.png)
> 
> I don't know what you hoped to do with `orig.paste((135, 255, 135), box=(2200, 1500), mask=fontimage1)`, so I have changed it to `orig.paste(fontimage1, (0, 0), fontimage1)`. I have also reduced the font size to fit in my smaller image, changed the text x position and `fontimage1` width.
> 
> If you would like more help than that, please upload your image and font to a post here.

That is good , My Requirement is Txt Color Should be blue and outline color need red color
Plz Do this Needfully..

**Comment by Windy2212** [comment]
Yes Thanks You For Ur help I Found This Solution .... Thanks lotzzzz..

**Comment by liujunzhuo** [comment]
hex color solved my problem. It may be helpful for someone
```python
def rgb_to_hex(rgb):
    return '#{:02x}{:02x}{:02x}'.format(*rgb)
rgb_tuple = (255, 0, 128)
hex_color = rgb_to_hex(rgb_tuple)
```
