### ISSUE TITLE
Convert PngImageFile to .png locally in Python script

### ISSUE THREAD

**Issue by RURQUIZA58** [python-pillow/Pillow#5893]
Hi 
 
How can I convert `image` below to image.png locally in a python script? I don't want to save it to disk
 
```python 
image = Image.open('opera_house.jpg')
image.paste(picture,pos)
```

Thanks

**Comment by aclark4life** [comment]
@RURQUIZA58 Probably like this, without the save part: https://www.kite.com/python/answers/how-to-save-an-image-as-png-with-pil-in-python

**Comment by RURQUIZA58** [comment]
After this commands:

image = Image.open('opera_house.jpg')
image.paste(picture,pos)

"image" becomes a PngImageFile

I can´t manupulate "image" ; Image.open(image), etc

I need to convert a PngImageFile to .png

Thanks in advance

**Comment by radarhere** [comment]
Hi.

First of all, after this code,
```python
image = Image.open('opera_house.jpg')
image.paste(picture,pos)
```
`image` should only be a "PngImageFile" if `image` is already a "PngImageFile" after this code
```python
image = Image.open('opera_house.jpg')
```
In which case, I expect your file is actually a PNG, and just has the wrong file extension.

But I wouldn't worry about what type of ImageFile `image` is. This doesn't reflect what will happen when you save the image. This reflects what type of image you opened.

After that, I'm not following what you'd like to do.

You say you would like to `Image.open(image)` - but `image` is already the opened image. Why would you need to open it again?

If you would like to turn `image` into a variable containing the contents of a PNG file, without a file on disk, then I suggest
```python
import io
fp = io.BytesIO()
image.save(fp, format="PNG")
data = fp.getvalue()
```
To demonstrate that this is correct, you can write `data` to file.
```python
with open("out.png", "wb") as fp:
    fp.write(data)
```

**Comment by radarhere** [comment]
@RURQUIZA58 was that helpful?

**Comment by radarhere** [comment]
Closing unless there is anything further.
