### ISSUE TITLE
When Pillow 8.4.0 is Installed on Py 3.10.1 via Pip, import name is "pil" instead of "PIL"

### ISSUE THREAD

**Issue by GaryBloom** [python-pillow/Pillow#5895]
Normally after installing Pillow on Python, a standard:
`from PIL import Image`
or:
`import PIL
`
succeeds. This works for me on 32-bit Py 3.8 and 3.9.
But this fails on Py 3.10.1. Rather I must type:
`from pil import Image
`
or:
`import pil as PIL
`
to try to keep my code compatible. Looks like a bug specific to Py 3.10.

**Comment by radarhere** [comment]
Installing through pip works fine for me on Python 3.10.1 my 64-bit Mac.

Could you give more information about your environment? What operating system are you using?

**Comment by GaryBloom** [comment]
Py3.10.1 x32 on Windows 10 Pro version 21H2.

Oddly enough, I just uninstalled and reinstalled it via pip, and now it seems fine. I have no idea how I ended up with the unknown/failing state before, but after reinstallation, it is working fine for me, as well.
________________________________

**Comment by GaryBloom** [comment]
I don't know if the issue I had is reproducible. Shall I close this for now?

**Comment by radarhere** [comment]
Given the prevalence of `pip`, I find it hard to imagine that this is failing for all attempts to use it to install Pillow on Python 3.10.

If you can't replicate it anymore, then it was something specific to your environment that is gone now - so closing seems reasonable. Thanks for solving the problem.
