### ISSUE TITLE
JPEG XL?

### ISSUE THREAD

**Issue by paolobenve** [python-pillow/Pillow#5898]
Hi! I'm using Pillow with great satisfaction on my projects.

Is there any plan to include jxl support?

**Comment by aclark4life** [comment]
@paolobenve Glad to hear! #4247 may be of interest.

**Comment by paolobenve** [comment]
I had seen that, but it doesn't answer my question...

**Comment by radarhere** [comment]
Hi. The information in that issue is all that we have to offer at the moment - so no, there aren't active plans. But for all I know, someone could create a PR tomorrow adding support for this format.

**Comment by radarhere** [comment]
@paolobenve is that answer sufficient?

**Comment by paolobenve** [comment]
yes :-(

**Comment by aclark4life** [comment]
Thanks @radarhere.

@paolobenve Turn that frown upside down! 😄 Or at least, tell us what "JPEG XL support" looks like to you for future reference for anyone interested adding it. E.g.

- The JPEG XL plugin for Pillow is great, but it would be better if Pillow did ``X, Y, Z``.

If enough people _both_ need ``X, Y, Z`` _and_ agree that ``X, Y, Z`` is the "right way" to support JPEG XL in Pillow, then it's much more likely someone will add it.

The @python-pillow/pillow-team can correct me if I'm wrong, but I suspect at least as many new feature additions come from outside the core team as come from within.

**Comment by paolobenve** [comment]
I'm interested in jxl support because I'm developing a gallery web app where (in the python part) Pillow generates reduced size copies of the images. Since I wanto to reduce the bandwidth used by the web app, I'm looking with interest to jxl, which promises to reduce the image size by a good amount.

Browsers are beginning to support jxl, and I'd want to have my app ready for when this support is complete
