### ISSUE TITLE
Not work with Khmer test for convert text to image

### ISSUE THREAD

**Issue by RathanakSreang** [python-pillow/Pillow#5903]
I try to follow code which is early issue but with different font.
```python
from PIL import Image,ImageDraw,ImageFont

# sample text and font
unicode_text = u"សួស្តីស្ត្រីខ្មែរដែលនៅទីនេះ"
font = ImageFont.truetype("Hanuman-Regular.ttf", 28, encoding="unic")

# get the line size
text_width, text_height = font.getsize(unicode_text)

# create a blank canvas with extra space between lines
canvas = Image.new('RGB', (text_width + 10, text_height + 50), "orange")

# draw the text onto the text canvas, and use black as the text color
draw = ImageDraw.Draw(canvas)
# draw.text((5,5), u'សួស្តីស្ត្រីខ្មែរដែលនៅទីនេះ', 'blue', font=font)
draw.text((10,10), u'សួស្តីស្ត្រីខ្មែរដែលនៅទីនេះ', font=font, fill=(255,255,255,128))

# save the blank canvas to a file
canvas.save("unicode-text.png", "PNG")
canvas.show()
```

### What did you expect to happen?
I expect it to show like this 'សួស្តីស្ត្រីខ្មែរដែលនៅទីនេះ', but  I got.
![unicode-text](https://user-images.githubusercontent.com/12246079/147251474-5a6a0671-6a78-4ce8-95ec-ae577c35f638.png)

**Comment by radarhere** [comment]
Hi. Testing, I find that the generated image improves if you use libraqm. Your code doesn't need to change, it's a dependency to install.
I don't know what version of Pillow or operating system you are using, but take a look at https://pillow.readthedocs.io/en/stable/installation.html.

**Comment by RathanakSreang** [comment]
@radarhere after install `sudo apt-get install libfreetype6-dev libharfbuzz-dev libfribidi-dev meson gtk-doc-tools` it's working fine.
Thanks
