### ISSUE TITLE
Pillow on Python 2.7 on an M1 Mac?

### ISSUE THREAD

**Issue by cclauss** [python-pillow/Pillow#5911]
As discussed at https://github.com/python-pillow/Pillow/issues/5093#issuecomment-795251758, is there any way to successfully install Pillow on legacy Python on an M1 Mac?

**Comment by radarhere** [comment]
Pillow 6.2.2 was the last version of Pillow to support Python 2.7.

You can try that, but this is not recommended - it does not include security fixes that we have released since then.

**Comment by radarhere** [comment]
I just downloaded https://files.pythonhosted.org/packages/b3/d0/a20d8440b71adfbf133452d4f6e0fe80de2df7c2578c9b498fb812083383/Pillow-6.2.2.tar.gz, expanded and navigated into the directory, ran `sudo python setup.py install`, and it worked.

**Comment by cclauss** [comment]
Sorry, I left out a key detail: I am running macOS --> Docker --> debian:10 (aka: Buster)

**Comment by radarhere** [comment]
Ok, you're running Debian on an M1 machine. My previous comments still stand.

If you want to use pip instead, I suggest `python -m pip install Pillow` or `python -m pip install Pillow --no-binary :all:`

**Comment by cclauss** [comment]
Thanks massively.  Needed to `apt-get install libjpeg-dev` then it worked!
