### ISSUE TITLE
Saving a GIF with multiple similar frames outputs GIF with single frame

### ISSUE THREAD

**Issue by idyllik-dev** [python-pillow/Pillow#5928]
In short, frames that look similar are being removed from an outputted GIF even if the optimize parameter is set to false.

In a bit more detail, upon making multiple single-pixel colour changes to iterations of an image, saving them as seperate images and then compiling them into one GIF the outputted GIF only has a single frame.

A small pixel edit is made to an image and each pixel edited frame is appended to the frames array, after this process it is compiled:
`frames[0].save('testimage.gif', save_all=True, append_images=frames[1:], optimize=False)`
But the result remains as a single frame GIF.

I assumed it was due to compression and optimisations but even upon turning the optimize parameter off, the issue has persisted.

What's most interesting about this is that if the pixel colour change is significant, e.g. turning it completely black, the issue doesn't come about - which is what made me believe it was down to optimisations and perhaps the parameter being set to false isn't working.

I have tried everything I could think of to get this to work but with no luck, hoping you all can help, feel free to ask for elaboration.

**Comment by radarhere** [comment]
Hi. As you may or may not know, each GIF frame may only introduce a limit of 256 colors.
So these similar colours being combined would be because Pillow is, in a blunt way, trying to limit the number of colors in the frames.

Here's an example of the situation you're talking about.

```python
from PIL import Image
im = Image.new("RGB", (100, 100), (255, 0, 0))

im2 = im.copy()
px = im2.load()
px[50, 50] = (235, 0, 0)

frames = [im, im2]

frames[0].save("out.gif", save_all=True, append_images=frames[1:])
```

Here's a version where I manually convert the frames to a limit of 256 colors first - and the output GIF becomes 2 frames instead of just 1.

```python
from PIL import Image
im = Image.new("RGB", (100, 100), (255, 0, 0))

im2 = im.copy()
px = im2.load()
px[50, 50] = (235, 0, 0)

frames = [im, im2]

# Without this line, the two frames are merged into one
# With it, they are not
frames = [frame.convert("P", palette=Image.ADAPTIVE) for frame in frames]

frames[0].save("out.gif", save_all=True, append_images=frames[1:])
```

If that doesn't help, would you be able to provide your specific images and code?

**Comment by idyllik-dev** [comment]
Hey, thank you for the help so far and though the issue isn't yet fixed, seeing your code did make me realise I had some severe inefficiencies within my own. But, as requested, I have spent some time commenting and neatening my code + gathering examples to provide you with.

As for the code:
```
#input text and calculate binary
intext = input("input text: ")
binary = ''.join(format(ord(i), '08b') for i in intext)

#open input image
img = Image.open("in.png")

#define frames array and input first default frame, acts as single frame to calculate RGB values when being read
frames = []
imgcopy = img.copy()
frames.append(imgcopy)

#iterate over binary string and append a new on/off frame for each character
for x in binary:
        imgcopy = img.copy()
        imgpix = imgcopy.load()
        if x == "0":
            imgpix[50,50] = (0,0,0)
            frames.append(imgcopy)
        elif x == "1":
            imgpix[50,50] = (255,255,255)
            frames.append(imgcopy)


#convert each frame in array to 8-bit colour palette and then save array as gif
frames = [frame.convert("P", palette=Image.ADAPTIVE) for frame in frames]
frames[0].save('out.gif', save_all=True, append_images=frames[1:])
```

The aim is here is to produce a GIF that can be split into its frames and a binary string can be read from it (I haven't included this section of the code) - this has actually worked, only I changed it to producing TIFFs in which the issue with frames being cut was not present.

Using my input png, a blank red square:
![in](https://user-images.githubusercontent.com/80986304/148133445-68bee404-efb2-4135-81d9-4fea81a666ba.png)

The following comes as a result:
![out](https://user-images.githubusercontent.com/80986304/148133500-816ccb20-6cdb-440d-afbd-2872e75f5fdf.gif)

When split into individual frames:
![frames](https://user-images.githubusercontent.com/80986304/148133781-92d0e0d6-bafc-4fc7-971e-0f2394cd62b6.png)

The result shows that regardless of the frames that were input, it is only including the frames that vary from one another - cutting the binary string from 32 down to 19 (not accounting for the base image at the beginning). This issue is only made worst when the difference between pixels is much smaller (1 RGB value apart) as this causes the issue of having only one frame, rather than a handful cut out, as it doesn't recognise any change at all between frames due to the minor significance of differences.

I understand that this is a fringe case use of Pillow and its GIF creation features and therefore this has probably not been picked up on before, I'm honestly not too sure what would cause this unless you cannot have similar frames within GIFs or there is some optimisation going on behind the scenes that is unaffected by the 'optimize' parameter mentioned in the docs.

Thank you for your quick response to the last message, I hope all this info doesn't complicate things too much and we can get to the bottom of this.

**Comment by radarhere** [comment]
When I look at your code, I see that you actually duplicate frames. Not just similar ones, but consecutive duplicate frames.

And yes, this is prevent by Pillow's code, in a way that can't be easily disabled by your code.

https://github.com/python-pillow/Pillow/blob/3f77466f11e04ddefdbbe79de6511ff8fb0b087b/src/PIL/GifImagePlugin.py#L560-L563

But what you might notice in the above is that Pillow combines the duration of the frames. So if you add in duration to your code, then when opening the image back up again, you can detect the duration and use that to determine the original binary string.

```python
from PIL import Image, ImageSequence

#input text and calculate binary
intext = input("input text: ")
binary = ''.join(format(ord(i), '08b') for i in intext)
print("Starting binary:", binary)

#open input image
img = Image.open("in.png")

#define frames array and input first default frame, acts as single frame to calculate RGB values when being read
frames = [img]

#iterate over binary string and append a new on/off frame for each character
for x in binary:
    imgcopy = img.copy()
    imgpix = imgcopy.load()
    imgpix[50,50] = (0,0,0) if x == "0" else (255,255,255)
    frames.append(imgcopy)

frames[0].save('out.gif', save_all=True, append_images=frames[1:], duration=1000)

reloaded = Image.open('out.gif')
binary = ""
for i, frame in enumerate(ImageSequence.Iterator(reloaded)):
    if i == 0:
        continue
    x = "0" if frame.load()[50, 50] == (0, 0, 0) else "1"
    howMany = frame.info["duration"] // 1000
    binary += x * howMany

print("Reloaded binary:", binary)
```

**Comment by radarhere** [comment]
@idyllik-dev did that solve your problem?
