### ISSUE TITLE
Reading GIF frame-by-frame changes mode during read in Pillow 9

### ISSUE THREAD

**Issue by FirefoxMetzger** [python-pillow/Pillow#5929]
I encountered some new behavior in pillow v9 that - to me - is a bit counter-intuitive (image attached):

```python
from PIL import Image
import numpy as np

img = Image.open("newtonscradle.gif")

img.seek(0)
foo = np.array(img.getdata())
assert foo.shape == (30000, )
assert img.mode == "P"

img.seek(1)
bar = np.array(img.getdata())

assert bar.shape == (30000, 3)
assert img.mode == "RGB"
```

Technically, this is not a bug, since it seems to be intended behavior according to [the v9 changelog](https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#convert-subsequent-gif-frames-to-rgb-or-rgba). At the same time, I find it a bit counter-intuitive that the first frame of a GIF now has mode `P` while each subsequent frame has mode `RGB`/`RGBA`. 

I was wondering if it would be possible to make this more consistent and also convert the first frame (`img.seek(0)`) of any GIF to RGB/RGBA, so that the mode of all frames is consistent.

Supplementary:

![newtonscradle.gif](https://user-images.githubusercontent.com/4402489/148028883-224cc59c-ba9e-4a48-a45a-cd3f440cbd6a.gif)

**Comment by radarhere** [comment]
I presume there is a contingent of Pillow users who just read the first frame of images, and don't bother seeking past that. #5857 had no effect on those users.

For Pillow users who do read animated GIFs, I expect them to be ok with this change, in the face of being able to read many GIF images correctly for the first time.

This is just a judgement call, but for my part, I'm a bit reluctant to change the experience of the first group of users for something that isn't an error. P mode more accurately reflects what is in that first image.

**Comment by FirefoxMetzger** [comment]
> For Pillow users who do read animated GIFs, I expect them to be ok with this change, in the face of being able to read many GIF images correctly for the first time.

I, too, like the idea behind this change, because it means better support for GIFs that use a different palette for each image and try to be smart on what areas they do/don't dispose of.

I'm not sure I agree on the part where P is the more accurate mode for the first image, though. RGB/RGBA seems to be more desirable for subsequent images (hence the change), and I don't see what makes the first page special to warrant an exception. Then again, you probably have a better view of the broader context, and it might indeed be the better choice. To me, this behavior was/is quite surprising and a bit unexpected, which is why I opened this issue to ask if it is worthwhile to change it.

Since you don't seem to think that it is worthwhile to change this behavior, I will go ahead and close this issue and look into changes downstream to adjust for the new pillow behavior.
