### ISSUE TITLE
Spacing in between one line characters

### ISSUE THREAD

**Issue by wazoooo** [python-pillow/Pillow#5932]
Is there a way to increase the spacing in between each character?

```python
color_var = (255, 255, 255)
tuple_var = (200, 400)
string_var = 'Today's date: 01/04/22'
font_var = ImageFont.truetype(font_file, 70)

text_var.text(tuple_var, string_var, color_var, font = font_var, align = 'center')
```

**Comment by hugovk** [comment]
Pillow uses FreeType and it's not possible to set the positioning (kerning) at the FreeType layer:

https://freetype.org/freetype2/docs/ft2faq.html

One option is to modify your `string_var` to add extra spaces in between each character.

# Original

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGB", (1600, 500), "black")
draw = ImageDraw.Draw(im)

color_var = (255, 255, 255)
tuple_var = (200, 400)
string_var = "Today's date: 01/04/22"
font_file = "arial.ttf"
font_var = ImageFont.truetype(font_file, 70)

draw.text(tuple_var, string_var, color_var, font=font_var, align="center")

im.show()
```

![image](https://user-images.githubusercontent.com/1324225/148222948-57596a9d-458a-47ef-959e-cb46effc6008.png)

# Adding a space

Create a new string with spaces in between: `string_var = " ".join(c for c in string_var)`

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGB", (1600, 500), "black")
draw = ImageDraw.Draw(im)

color_var = (255, 255, 255)
tuple_var = (200, 400)
string_var = "Today's date: 01/04/22"
font_file = "arial.ttf"
font_var = ImageFont.truetype(font_file, 70)

string_var = " ".join(c for c in string_var)

draw.text(tuple_var, string_var, color_var, font=font_var, align="center")

im.show()
```

![image](https://user-images.githubusercontent.com/1324225/148223063-08ed0f3f-804e-4ce3-a2dc-d789a4ae731a.png)

# Adding a thin space

If that's too spaced out, try another space character, for example U+2009 Thin Space

https://www.compart.com/en/unicode/U+2009

It's not obvious here, but I copied and pasted the thin space character from that webpage and put it in between the quotes: `string_var = " ".join(c for c in string_var)`

```python
from PIL import Image, ImageDraw, ImageFont

im = Image.new("RGB", (1600, 500), "black")
draw = ImageDraw.Draw(im)

color_var = (255, 255, 255)
tuple_var = (200, 400)
string_var = "Today's date: 01/04/22"
font_file = "arial.ttf"
font_var = ImageFont.truetype(font_file, 70)

string_var = " ".join(c for c in string_var)

draw.text(tuple_var, string_var, color_var, font=font_var, align="center")

im.show()
```

![image](https://user-images.githubusercontent.com/1324225/148223303-810ecfef-a7ef-4991-8049-ed6795898016.png)

# More

Here are some other space characters of different widths:

https://www.compart.com/en/unicode/category/Zs

**Comment by radarhere** [comment]
Another option would be to draw each character individually at varying positions. You can change the `gap` variable I've added for different results.

```python
from PIL import Image, ImageDraw, ImageFont
im = Image.new("RGB", (1600, 500), "black")
font_file = "Tests/fonts/FreeMono.ttf"
text_var = ImageDraw.Draw(im)

color_var = (255, 255, 255)
tuple_var = (200, 400)
string_var = "Today's date: 01/04/22"
font_var = ImageFont.truetype(font_file, 70)
gap = 5

for char in string_var:
	text_var.text(tuple_var, char, color_var, font = font_var, align = 'center')
	width = text_var.textsize(char, font = font_var)[0] + gap
	tuple_var = (tuple_var[0]+width, tuple_var[1])

im.save("out.png")
```
![out](https://user-images.githubusercontent.com/3112309/148857826-cfca8fbb-815e-4fa3-b0cb-b47ab5c31b3b.png)

@wazoooo are either of these answers helpful?

**Comment by nulano** [comment]
@radarhere  `textlength` is preferred for layout use, as it actually computes the amount by which text should be shifted, while `textsize` returns a (sometimes broken) bounding box.

The loop should therefore be:

```python
for char in string_var:
    text_var.text(tuple_var, char, color_var, font = font_var, align = 'center')
    width = text_var.textlength(char, font = font_var) + gap
    tuple_var = (tuple_var[0]+width, tuple_var[1])
```

![bbox3](https://user-images.githubusercontent.com/3819630/148876653-3d9d7ba4-495d-4cc1-8866-707871915f1f.png)

**Comment by wazoooo** [comment]
Thank you for your answers @hugovk @radarhere @nulano. I have it working now using @radarhere 's code:

```from PIL import Image, ImageDraw, ImageFont
im = Image.new("RGB", (1600, 500), "black")
font_file = "Tests/fonts/FreeMono.ttf"
text_var = ImageDraw.Draw(im)

color_var = (255, 255, 255)
tuple_var = (200, 400)
string_var = "Today's date: 01/04/22"
font_var = ImageFont.truetype(font_file, 70)
gap = 5

for char in string_var:
	text_var.text(tuple_var, char, color_var, font = font_var, align = 'center')
	width = text_var.textsize(char, font = font_var)[0] + gap
	tuple_var = (tuple_var[0]+width, tuple_var[1])

im.save("out.png")```
