### ISSUE TITLE
Weird character error

### ISSUE THREAD

**Issue by julianfn20215** [python-pillow/Pillow#5948]
Hello very good, how could I correct this error so that it can allow rare characters also that the emojis can be seen
thank you!

https://i.imgur.com/Ai6ajPq.png

Code:

```python
from PIL import Image, ImageDraw, ImageFont


font_size=36
width=500
height=100
back_ground_color=(255,255,255)
font_size=36
font_color=(0,0,0)


unicode_text = u"𝖏𝖚𝖆𝖑𝖎𝖆𝖓𝖋𝖓"

im  =  Image.new ( "RGB", (width,height), back_ground_color )
draw  =  ImageDraw.Draw ( im )
unicode_font = ImageFont.truetype("Montserrat-Thin.ttf", font_size,encoding='utf-8')
draw.text ( (10,10), unicode_text, font=unicode_font, fill=font_color )

im.save("text.jpg")

```

**Comment by radarhere** [comment]
Hi. You need to make sure that the characters you want to show are in your font.

For "𝖏𝖚𝖆𝖑𝖎𝖆𝖓𝖋𝖓",
```pycon
>>> [char.encode("unicode_escape") for char in "𝖏𝖚𝖆𝖑𝖎𝖆𝖓𝖋𝖓"]
[b'\\U0001d58f', b'\\U0001d59a', b'\\U0001d586', b'\\U0001d591', b'\\U0001d58e', b'\\U0001d586', b'\\U0001d593', b'\\U0001d58b', b'\\U0001d593']
```
the first character is https://www.fileformat.info/info/unicode/char/1d58f/index.htm.

That is an unusual character, and I'm having trouble finding a font containing it. If you instead wanted a character in Montserrat-Thin, then https://www.fileformat.info/info/unicode/char/135/index.htm will work instead.

```python
from PIL import Image, ImageDraw, ImageFont


font_size=36
width=500
height=100
back_ground_color=(255,255,255)
font_size=36
font_color=(0,0,0)


unicode_text = u"ĵ"

im  =  Image.new ( "RGB", (width,height), back_ground_color )
draw  =  ImageDraw.Draw ( im )
unicode_font = ImageFont.truetype("Montserrat-Thin.ttf", font_size,encoding='utf-8')
draw.text ( (10,10), unicode_text, font=unicode_font, fill=font_color )

im.save("text.jpg")
```
gives
![text](https://user-images.githubusercontent.com/3112309/148717805-785d14a5-80c5-4b1c-8d9d-47826237fa85.jpg)

You also asked about emojis, so here's an example with one of our tests fonts, also using `embedded_color`.

```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("Tests/fonts/NotoColorEmoji.ttf", 109)
im = Image.new("RGB", (150, 150), "white")
d = ImageDraw.Draw(im)
d.text((10, 10), "\U0001f469", font=font, embedded_color=True)

im.save("emoji.png")
```
![emoji](https://user-images.githubusercontent.com/3112309/148717935-e0b3f005-e06b-4675-a954-a73277bd3eb5.png)

**Comment by radarhere** [comment]
I found a font with your characters! Using latinmodern-math.otf, your original code works.

![text](https://user-images.githubusercontent.com/3112309/149086270-02d08399-3837-43c4-bc26-0c94555a15df.jpg)

**Comment by julianfn20215** [comment]
There are bots like koya that allow all kinds of characters, I don't know what font I could use


this is bot koya font

Do you have any idea what font I could be using?


https://i.imgur.com/n7uua3K.png



Thanks for helping me find the source

**Comment by radarhere** [comment]
Have you tried inspecting the font using Google Chrome? https://www.makeuseof.com/how-to-find-webpages-font-inspect-element-tool-browser-extensions/
I imagine it might be simpler for you to figure out the font name from the webpage using that, than for me to figure it out from a screenshot.

**Comment by radarhere** [comment]
I now suspect that your image is derived from the old Discord logo - https://fontmeme.com/discord-logo-font/. That article says that the font is a modified version of Uni Sans Heavy.

**Comment by radarhere** [comment]
@julianfn20215 would you like to know anything further about how to use Pillow, or have we answered your questions?
