### ISSUE TITLE
Rotating image unlinks ImageDraw Object

### ISSUE THREAD

**Issue by DeusAres** [python-pillow/Pillow#5951]
### What did you do?
Rotated an Image tried to write text on it

### What did you expect to happen?
Same as above

### What actually happened?
Same as above except text is not drawn, ImagingCore of Image object linking to another hex

### What are your OS, Python and Pillow versions?

* OS: Window
* Python: 3.9
* Pillow: 8.3.2

```python
from PIL import Image, ImageFont, ImageDraw

FONTPATH = 'C:\\Windows\\Fonts\\Arial.ttf'
font = ImageFont.truetype(FONTPATH, size=70)
cardB = Image.new("RGBA", (400, int(400*1.3)), 'white')
cardD = ImageDraw.Draw(cardB)
print(cardB.im, cardD.im)

cardD.text((x, y), str(number), fill=cardColor, anchor='lt', font=font)
print(cardB.im, cardD.im)
cardB = cardB.rotate(180)
print(cardB.im, cardD.im)
cardD.text((x, y), str(number), fill=cardColor, anchor='lt', font=font)
cardB.show()
```
I've included show and print to prove the bugs further
If creating again the ImageDraw object is necessary seems a bit strange since I've never had to
Maybe I did confusion since some objects need assignment while other don't need it? Idk about this statement I'm very confused from finding a solution

**Comment by radarhere** [comment]
Hi.

```pycon
>>> from PIL import Image, ImageDraw
>>> im = Image.new("RGB", (1, 1))
>>> d = ImageDraw.Draw(im)
>>> im.rotate(90)
<PIL.Image.Image image mode=RGB size=1x1 at 0x104CB5D20>
>>> im
<PIL.Image.Image image mode=RGB size=1x1 at 0x104F6F250>
```

So it's not just that the ImagingCore object is different - the image instance is different as well. Rotating an image creates a copy of the image instance.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.rotate
> Returns a rotated copy of this image.

So I wouldn't say that ImageDraw is unlinked from the image - it's still linked to the first image instance.

ImageDraw has no idea that you've assigned the copied image to the same variable name, so it just keeps on working with the first image instance.

I expect you understand how to create the ImageDraw instance again, but just in case -

```python
from PIL import Image, ImageFont, ImageDraw

FONTPATH = 'C:\\Windows\\Fonts\\Arial.ttf'
font = ImageFont.truetype(FONTPATH, size=70)
cardB = Image.new("RGBA", (400, int(400*1.3)), 'white')
cardD = ImageDraw.Draw(cardB)

# I inserted missing variables
x = y = 0
number = 0
cardColor = '#f00'

cardD.text((x, y), str(number), fill=cardColor, anchor='lt', font=font)
cardB = cardB.rotate(180)
cardD = ImageDraw.Draw(cardB)
cardD.text((x, y), str(number), fill=cardColor, anchor='lt', font=font)
cardB.show()
```

See also https://github.com/python-pillow/Pillow/issues/5738#issuecomment-932834769 for an example that you might find helpful.

**Comment by DeusAres** [comment]
Oh, a *copy*
I never noticed in 2 years and came to my attention only today.

Just in case, I'm writing (still in bad state for using old methods and unnecessary wheel reinvetions, I'll update a new version in few days) a collection of scripts using PIL and Numpy, posted on the community tab as well.
Should I expect more copies from Image methods or is it a one time case?

**Comment by radarhere** [comment]
`convert`, `crop`, `reduce`, `remap_palette`, `resize` and `transpose` also return copies.

**Comment by DeusAres** [comment]
Thank you very much for the help and the info
