### ISSUE TITLE
Result of `Image.resize` is not what expected based on described algorithms

### ISSUE THREAD

**Issue by sulyi** [python-pillow/Pillow#5952]
### What did you do?

I've resized an image using bilinear algorithm.

### What did you expect to happen?

The output to be the result of the described algorithm.

### What actually happened?

Got different output.

### What are your OS, Python and Pillow versions?

* Python: 3.9.9
* Pillow: both 8.4.0 and 9.0.0

I've checked by hand and using _octave_'s _image_ package also.  With later also checked `Image.BICUBIC`, but neither those were the same.

If this is an intended behaviour documentation might be more clear about what is this. All there is:

> calculate the output pixel value using linear interpolation on all pixels that may contribute to the output value.

Here's my example:

```python
from PIL import Image

original = bytes([181, 66, 39,
                  114, 179, 115,
                  55, 178, 227])

im = Image.frombytes('L', (3, 3), original)
linear_im = im.resize((5, 5), resample=Image.BILINEAR)

list(linear_im.tobytes())
```

output:
```python
[181, 135, 66, 50, 39,
 154, 137, 111, 86, 69,
 114, 140, 179, 141, 115,
 79, 118, 178, 181, 182,
 55, 104, 178, 207, 227]
```

expected:
```python
[181, 123, 66, 52, 39,
 147, 135, 122, 99, 77,
 114, 146, 179, 147, 115,
 84, 131, 178, 174, 171,
 55, 116, 178, 202, 227]
```
_Note_: I've used truncation (floor) to convert to integer.

**Comment by kmilos** [comment]
Octave's imresize might not be an ideal reference, not sure if all issues like this one were actually resolved:

https://savannah.gnu.org/bugs/?func=detailitem&item_id=51769

**Comment by sulyi** [comment]
This might help debugging [Resample.c](https://github.com/python-pillow/Pillow/blob/51a9dad82d483241e780d860abcee09e44362413/src/libImaging/Resample.c):

In case of bilinear interpolation the synthesis function is

![\varphi(x) = \begin{cases}1 -  |x| & |x| < 1 \\ 0 & |x|  \geq 1 \end{cases}](http://www.sciweavers.org/tex2img.php?eq=%5Cvarphi%28x%29%3D%5Cbegin%7Bcases%7D1-%7Cx%7C%26%7Cx%7C%3C1%5C%5C0%26%7Cx%7C%5Cgeq1%5Cend%7Bcases%7D&bc=White&fc=Black&im=png&fs=12&ff=ccfonts,eulervm&edit=0)

and therefore when resizing 3x3 to 5x5 coefficients should be something like:

![\bold{K}_x = \bold{K}_y^\top  =  \begin{bmatrix}   1 &    0  &   0 \\ 0.5 &  0.5 &   0 \\   0 &    1 &    0 \\   0 & 0.5 &  0.5 \\   0 &    0 &     1 \end{bmatrix}](http://www.sciweavers.org/tex2img.php?eq=%5Cbold%7BK%7D_x%3D%5Cbold%7BK%7D_y%5E%5Ctop%3D%5Cbegin%7Bbmatrix%7D1%260%260%5C%5C0.5%260.5%260%5C%5C0%261%260%5C%5C0%260.5%260.5%5C%5C0%260%261%5Cend%7Bbmatrix%7D&bc=White&fc=Black&im=png&fs=12&ff=ccfonts,eulervm&edit=0).

**Comment by radarhere** [comment]
Just breaking it down to a simpler example - you expect
```python
from PIL import Image

original = bytes([0, 50, 100])

im = Image.frombytes('L', (3, 1), original)
im = im.resize((5, 1), resample=Image.BILINEAR)

print(list(im.tobytes()))
```
to give `[0, 25, 50, 75, 100]`, yes? But instead, it gives `[0, 20, 50, 80, 100]`.

**Comment by sulyi** [comment]
Yes, that's correct.

It's a mapping problem, by the way.
As is left and right edge of the original image is mapped to the resized image's corresponding edge, instead of left and rightmost pixels.

I'm confident that I could make a PR fixing this, but first I'd like to make sure whether it is needed.
