### ISSUE TITLE
Brightness clipped on I;16 images loaded from png

### ISSUE THREAD

**Issue by flagadum** [python-pillow/Pillow#5967]
### What did you do?

* Open a 16bit greyscale image from a png file
* Paste that image into another 16bit greyscale image (I;16)

### What did you expect to happen?

The pasted image should be kept the same

### What actually happened?

The bright pixels got clipped to middle grey (32767 ?)

### Proposed workaround?

Immediately after loading png, convert the image to array, then back to image again.

### What are your OS, Python and Pillow versions?

* OS: MacOS 10.15
* Python: 3.9.10
* Pillow: 9.0.0

```python

from PIL import Image
import numpy

# Let's create a white 16bit square 
img1 = Image.new("I;16",(256,256),(65535))

# Let's save this square as png and open it again
if True :    # if False: The bug does not happen
	img1.save("test.png")
	img1 = Image.open("test.png")

if False :    # If True: Bug workaround: Convert image to array and back to image again
	(sizeu,sizev) = img1.size
	img1 = Image.fromarray(numpy.array(img1.getdata()).astype(numpy.uint16).reshape((sizev,sizeu)))

# We check that the loaded square is white
img1.show()

# But we might already see that something is wrong here
print(img1.histogram())

# Let's paste this square in another 16bit image
img2 = Image.new("I;16",(288,288),(0))
img2.paste(img1,(16,16,272,272))

# Is the pasted square white or grey???
img2.show()

```

**Comment by radarhere** [comment]
There are two things at work here.

1. Saving an I;16 image as a PNG and re-opening it turns it into I. See #3041 or #3796
```python
from PIL import Image

im = Image.new("I;16", (1, 1))
im.save("test.png")
reloaded = Image.open("test.png")
print(reloaded.mode)  # I
```

2. Converting an I mode image to I;16 clips the pixel values. See #3159 or https://github.com/python-pillow/Pillow/issues/5403#issuecomment-840846709

```python
from PIL import Image

im = Image.new("I", (1, 1), 60000)
im = im.convert("I;16")
px = im.load()
print(px[0, 0])  # 32767
```

**Comment by radarhere** [comment]
A workaround would be to create `img2` as "I" rather than "I;16".

**Comment by radarhere** [comment]
I've created PR #6112 to resolve this particular scenario, by fixing incorrect clipping when the "I" mode PNG was converted to match the "I;16" image you were pasting it on.

However, Pillow will still clip the values of the 32-bit "I" mode when converting to the 16-bit "I;16" mode. This scenario is only fixed by my PR because you are using white. If you try this with other images, I expect you will find a problem.

So resolving this situation more generally can be either part of #3796 or #3159.
