### ISSUE TITLE
Unicode rendering error in ImageDraw module

### ISSUE THREAD

**Issue by ensv** [python-pillow/Pillow#597]
I tried to convert unicode text into image, but the rendering in unicode is not correct. Here is an example, I want to convert this text "ស្នាក់​" ( real sequence of characters : ស + ្  ​+ ន​ +  ក​ +  ់​)​. I expected to get  "ស្នាក់​"  in the image, but I got the real sequence instead ("ស្​នាក់​").  Any ideas on this issue ? 

In case you want to test, you can use this font : http://sourceforge.net/projects/khmer/files/Fonts%20-%20KhmerOS/KhmerOS%20Fonts%205.0-%20LGPL%20Licence/All_KhmerOS_5.0.zip/download?use_mirror=skylink&download=

this is the image I get : 
![test](https://cloud.githubusercontent.com/assets/3463351/2593065/308aa22c-ba7c-11e3-9500-93b06958912d.jpg)

SV

**Comment by radarhere** [comment]
The combining of glyphs is handled by raqm in Pillow 4.2.0. However, there is a clipping issue after that, discussed in #3235.
