### ISSUE TITLE
Extracting additional channels

### ISSUE THREAD

**Issue by andrey-hider** [python-pillow/Pillow#5979]
### What did you do?

Tried to export two alpha channels:
<img width="416" alt="Screenshot 2022-01-20 at 14 17 04" src="https://user-images.githubusercontent.com/30869869/150346174-7dae1a87-86a1-49e5-a0cf-e91a48814081.png">

### What did you expect to happen?

To be able to get preview of both alpha channels as a png files.

### What actually happened?

<img width="450" alt="Screenshot 2022-01-20 at 12 25 11" src="https://user-images.githubusercontent.com/30869869/150346272-242955fe-366b-4bc0-a340-72db785c14db.png">
I've got preview of only one alpha channel:
<img width="471" alt="Screenshot 2022-01-20 at 14 20 18" src="https://user-images.githubusercontent.com/30869869/150346540-68aa0535-f77d-44c3-b077-5163e55eb376.png">

### What are your OS, Python and Pillow versions?

* OS: macOS Monterey 12.1
* Python: 3.9.10
* Pillow: 9.0.0

```python
from PIL import Image

folder = "<path_to_file>"
file = "Alpha Masks Sample with 2 Alphas.tif"
source_file = folder + "/" + file

f = open(source_file, 'rb')
loaded_tif=Image.open(f)
channel_counter = 0
for channel in loaded_tif.split():
    channel_counter += 1
    channel_image = Image.new("L", loaded_tif.size)
    channel_image.paste(channel)
    channel_image.save(folder + '/export_channel'+str(channel_counter)+'.png', optimize=True)
loaded_tif.close()
```

Archive with example and source code:
[pillow_alpha_channels.zip](https://github.com/python-pillow/Pillow/files/7905422/pillow_alpha_channels.zip)

**Comment by radarhere** [comment]
What application are the first two screenshots from?

**Comment by andrey-hider** [comment]
@radarhere
Adobe Photoshop 2022

**Comment by radarhere** [comment]
Just a note for future investigation - Pillow detects the image mode as RGBX. macOS Preview doesn't report that the image "Has Alpha" like it does for other TIFFs with transparency, so I don't think there is an alpha channel in our sense of the term.

I suspect the information sought after here lives within the 34377 TIFF Tag (TIFFTAG_PHOTOSHOP), as inspecting `tag_v2` shows the tag value contains the strings "Alpha 2" and "Numbers". Or possibly that tag in combination with the 37724 TIFF Tag, ImageSourceData.

**Comment by radarhere** [comment]
If we were to add this functionality, is your image one that we are able to include in our test suite, and distribute under the Pillow license?

**Comment by radarhere** [comment]
```python
from PIL import Image
with Image.open("Alpha Masks Sample with 2 Alphas.tif") as im:
	print("rawmode", im.tile[0][-1][0])
	print("mode", im.mode)
```
gives
```
rawmode RGBXX
mode RGBX
```

Pillow detects the raw mode as RGBXX and the mode as RGBX.

Pillow is trying to convert the image to a more common format by restricting the number of channels, in opposition to what you're requesting.

**Comment by radarhere** [comment]
If you've [already installed psdtags](https://github.com/python-pillow/Pillow/issues/5981), then I expect you've also installed the dependency tifffile. In that case, here is a way to solve your problem.

```python
import tifffile
from PIL import Image
img = tifffile.imread('Alpha Masks Sample with 2 Alphas.tif')
for channel_counter in range(img.shape[2]):
    im = Image.fromarray(img[:, :, channel_counter])
    im.save("export_channel"+str(channel_counter+1)+".png")
```

**Comment by andrey-hider** [comment]
@radarhere 
Thanks for detailed explanation!
Code is working like a charm.
Can I buy you a "virtual beer"? Do you have a Paypal?

**Comment by radarhere** [comment]
Thanks very much for asking! Ok, for the first time, I've setup a Sponsor button on my profile, so if you'd like to throw some spare change at me, your kindness can express itself there - https://github.com/sponsors/radarhere?frequency=one-time
