### ISSUE TITLE
TIFF layer mask

### ISSUE THREAD

**Issue by andrey-hider** [python-pillow/Pillow#5981]
Is there any way to extract a Layer mask thumbnail out of tiff image layer using Pillow?
It would be interesting for me to export black and white mask from the layer "Red Layer with Mask inside Folder".

Here how it looks like in Abode Photoshop:
![image](https://user-images.githubusercontent.com/30869869/150538688-b82ddda5-29d3-46b9-b4ed-f160369411fb.png)

Here is the example of [tiff file](https://github.com/python-pillow/Pillow/files/7914118/Alpha.Masks.Sample.with.3.Alphas.zip).

**Comment by cgohlke** [comment]
That mask is buried inside the TIFF tag #37724. Try the [psdtags](https://pypi.org/project/psdtags/) package (`python -m pip install psdtags[all]`) to extract it as a numpy array, e.g.:
```Python
import psdtags

mask = psdtags.TiffImageSourceData.fromtiff('Alpha Masks Sample with 3 Alphas.tif').layers[2].asarray(psdtags.PsdChannelId.USER_LAYER_MASK)
```

**Comment by radarhere** [comment]
If we were to add this functionality, is your image one that we are able to include in our test suite, and distribute under the Pillow license?

**Comment by radarhere** [comment]
To further demonstrate psdtags,
```python
import psdtags
from PIL import Image
mask = psdtags.TiffImageSourceData.fromtiff('Alpha Masks Sample with 3 Alphas.tif').layers[2].asarray(psdtags.PsdChannelId.USER_LAYER_MASK)
Image.fromarray(mask).save("out.png")
```
creates this image
![out](https://user-images.githubusercontent.com/3112309/150893000-f4bc3eb2-48ff-49cf-a431-58859858edc8.png)

**Comment by andrey-hider** [comment]
@cgohlke 
@radarhere 
Thanks for your examples how to extract TIFF layer mask!
You can use and distribute this test picture under the Pillow license.

**Comment by schwarzwals** [comment]
@cgohlke  fantastic job on psdtags !  I need to write a psd or tiff with layer mask. i have a mask and and original file...how i can do it ? Thank you !
