### ISSUE TITLE
Pillow doesn't recognize JFXX as an application marker

### ISSUE THREAD

**Issue by krisudom** [python-pillow/Pillow#5983]
### What did you do?
Called Image.open() on an image with a JFXX application marker. Despite having the JFXX marker, the rest of the app0 segment for this image is corrupted.
I've attached the image at the bottom.

### What did you expect to happen?
Expected Pillow to recognize the JFXX application marker and give an error. As far as I could tell by looking at the JPEG spec, JFXX is still a valid but uncommon application marker, so it JFXX should be recognized.

### What actually happened?
Pillow accepted it as a valid jpg image.

Looking at Pillow/src/PIL/JpegImagePlugin.py, the app0JFXX node isn't checked for in the chain of if statements in the APP function. My guess is since the application marker wasn't recognized, proper checks weren't made on it, so Pillow did not realize that the app0 segment had invalid information.

### What are your OS, Python and Pillow versions?

* OS: Pop!_OS 21.10
* Python: 3.9.7
* Pillow: 9.0.0

The running the code doesn't cause an error message or bug, but I think it should.
```python
from PIL import Image
image = "325385.jpg"
out = Image.open(image)
```
![325385](https://user-images.githubusercontent.com/41187237/150652812-8358d6e6-22c5-4ee1-b182-aea1c521f7a7.jpg)

**Comment by radarhere** [comment]
> Despite having the JFXX marker, the rest of the app0 segment for this image is corrupted.

> My guess is since the application marker wasn't recognized, proper checks weren't made on it, so Pillow did not realize that the app0 segment had invalid information.

Could you give some more detail? In what way is it invalid/corrupt?

If you're looking at JpegImagePlugin's `APP` function, then you'll also notice that for JFIF, we catch `Exception`, for Photoshop 3.0, we catch `struct.error`, and for Adobe, we catch `IndexError`. So preventing the user from viewing the image because of an invalid JFXX marker would seem out of line with that tradition.

**Comment by krisudom** [comment]
The JFXX APP0 segment is the wrong size, it's meant to be 21840 bytes long, but it's only 3853 bytes long. I'll print the first few bytes of the image I included earlier:

```
00000000   FF D8 FF E0  00 10 4A 46  49 46 00 01  02 00 00 01  ......JFIF......
00000010   00 01 00 00  FF E0 0F 1D  4A 46 58 58  00 10 FF D8  ........JFXX....
00000020   FF FE 00 0C  41 70 70 6C  65 4D 61 72  6B 0D FF DB  ....AppleMark...
```

I did notice that the `APP` function catches `Exception`'s, I think that when Pillow is parsing through and reaches `JFXX`, since there's no if condition that checks for that marker in JpegImagePlugin's `APP` function it doesn't even go into an if condition, so it doesn't catch an `Exception` either. Because the image is corrupt it should be raising an `Exception`.

Sorry that I wasn't more clear earlier!

**Comment by radarhere** [comment]
Following https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format#JFIF_extension_APP0_marker_segment,

`FF E0` is the APP0 marker.
`0F 1D` is the "length of segment excluding APP0 marker", so 15*256+29-2 = 3867.
`4A 46 58 58 00` is JFXX
`10` is the thumbnail format, JPEG.
`FF D8` is SOI.

So I don't see how the information you've presented leads to the conclusion that it should be 21840 bytes long?

**Comment by krisudom** [comment]
Ah! You're right, my bad! I missed that and put too much faith in another parser that expected 21840 bytes. The issue could probably get closed then. I wonder though, why doesn't the `APP` function check for a JFXX marker? If there was an invalid image with a JFXX marker, would it have been caught by one of the exceptions?

**Comment by radarhere** [comment]
It wouldn't be ignored just because we don't explicitly mention JFXX, no.

If I use a hex editor to change `OF 1D` to `OF 1E`, increasing the length by 1, it loads fine in Pillow.
If I go further to `OF FF`, then the image fails to load in Pillow with `OSError: broken data stream when reading image file`.
If I go further to `FF FF`, then I get `PIL.UnidentifiedImageError: cannot identify image file`

**Comment by krisudom** [comment]
Got it, thank you for the clarification, and sorry for my mistake!
