### ISSUE TITLE
libraqm not detected on macOS

### ISSUE THREAD

**Issue by naskio** [python-pillow/Pillow#5997]
### What did you do?

I installed Pillow using Poetry then I needed to set the direction, so I installed libraqm as follow:
- Installing libraqm dependencies
```
brew install freetype harfbuzz fribidi
```
- Installing libraqm using brew
```
brew install libraqm
```

### What did you expect to happen?

Being able to set the direction to RTL and to use the Arabic language

### What actually happened?

I got an exception saying that libraqm isn't found
```
KeyError: 'setting text direction, language or font features is not supported without libraqm'
```

### What are your OS, Python and Pillow versions?

* OS: macOS Monterey 12.1
* Python: 3.9.7
* Pillow: 9.0.0

```python
from PIL import Image, ImageDraw, ImageFont

background = Image.new('RGBA', (1200, 600), "white")  # white background
draw = ImageDraw.Draw(background)
font = ImageFont.truetype("Arial.ttf", 32)
text = "مرحبا بالعالم"
text_w, text_h = draw.textsize(text, font=font, direction="rtl", language="ar")
draw.text(
    (1200 - text_w, 0),  # right align
    text,
    font=font,
    fill="black",
    direction="rtl",
    language="ar",
    align="right"
)
background.show()
```

**Comment by radarhere** [comment]
Did you install (or re-install) Pillow after you installed libraqm?

**Comment by naskio** [comment]
After investigating the issue, I found out that I needed to:

-  set the env variable `DYLD_FALLBACK_LIBRARY_PATH` (or `DYLD_LIBRARY_PATH`, read the difference [here](https://stackoverflow.com/a/3172515/5986116)) to `/usr/local/lib`

To do so add this line to  the end of `~/.bashrc` (or `~/.bash_profile`) if you are using bash or `~/.zshrc` if you are using zsh:
```
export DYLD_FALLBACK_LIBRARY_PATH=/usr/local/lib:$DYLD_FALLBACK_LIBRARY_PATH
```
- Restart your Terminal/PyCharm before re-running the script.

This should fix the issue and would allow Pillow to detect libraqm.
