### ISSUE TITLE
Release 9.0.1 on February 3, 2022

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#6011]
* [x] Make necessary changes in main branch.
* [x] Update CHANGES.rst.
* [x] Check out release branch e.g.:
```
git checkout -t remotes/origin/9.0.x
```
* [x] Cherry pick individual commits from main branch to release branch e.g. 9.0.x, then git push.
* [x] Check GitHub Actions and AppVeyor to confirm passing tests in release branch e.g. 9.0.x.
* [x] In compliance with PEP 440, update version identifier in src/PIL/_version.py
* [x] Run pre-release check via make release-test.
* [x] Create tag for release e.g.:
```
git tag 9.0.1
git push
git push --tags
```
* [x] Create and check source distribution:
```
make sdist
twine check dist/*
```
* [x] Create binary distributions
* [x] Check and upload all binaries and source distributions e.g.:
```
twine check dist/*
twine upload dist/Pillow-9.0.1*
```
* [x] Publish the release on GitHub

**Comment by radarhere** [comment]
@cgohlke at your convenience, would you be able to put together wheels?

**Comment by cgohlke** [comment]
[Here](https://www.lfd.uci.edu/~gohlke/download/Pillow-9.0.1-win-dist.zip) you go.

**Comment by radarhere** [comment]
Thanks very much!

[Released](https://pypi.org/project/Pillow/9.0.1/), and [announced!](https://twitter.com/PythonPillow/status/1489088660880330753)

**Comment by radarhere** [comment]
I've uploaded additional macOS M1 wheels, with a build number of 1, to resolve https://github.com/python-pillow/Pillow/issues/6015
