### ISSUE TITLE
Pillow 9.0.1 crash: symbol not found in flat namespace '_xcb_connect' (Darwin M1)

### ISSUE THREAD

**Issue by ajslater** [python-pillow/Pillow#6015]
### What did you do?

Using Pillow 9.0.0 in python project. Works great as usual.
Installed Pillow 9.0.1
Ran a python program that imports PIL

### What did you expect to happen?

Perform much the same as Pillow 9.0.0

### What actually happened?

Crashes on import:
```
    from . import _imaging as core
ImportError: dlopen(/Users/aj/Code/codex/.venv/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so, 0x0002): symbol not found in flat namespace '_xcb_connect'
```

### What are your OS, Python and Pillow versions?

* OS: macOS 12.2 (M1)
* Python: 3.9.10
* Pillow: 9.0.1

#### Offending code
```python
from PIL import Image
```

Reverting to 9.0.0 fixes the issue. Easy workaround for now.

hombrew has libxcb installed:
libxcb: stable 1.14 (bottled)

Could be a problem with the binary wheel for M1

**Comment by radarhere** [comment]
> Works great as usual.

Quick aside: thanks for these kind words!

How did you actually install Pillow? pip?

**Comment by ajslater** [comment]
poetry, actually.

**Comment by victorbenichoux** [comment]
Hi!

I confirm that installing `pillow==0.0.1` through `pip` leads to the same issue on the same os/hardware! 

I can also confirm it works (great as usual) with `pillow==9.0.0`.

**Comment by hugovk** [comment]
> Could be a problem with the binary wheel for M1

Does 9.0.1 work when installed from sdist/GitHub source?

**Comment by hugovk** [comment]
Pillow source changes:

* https://github.com/python-pillow/Pillow/compare/9.0.0...9.0.1

Wheel builder changes:

* https://github.com/python-pillow/pillow-wheels/compare/9.0.0...9.0.1

**Comment by louisstuart96** [comment]
> > Could be a problem with the binary wheel for M1
> 
> Does 9.0.1 work when installed from sdist/GitHub source?

I have experienced the same crash as @ajslater : the environment is exactly the same, installed Pillow==9.0.1 via pip and crashed, revert to 9.0.0 and fixed.

In a newly created virtual environment I tried installing from source and it works fine as usual:
```
> pip install .
Looking in indexes: ****
Processing /Users/***/Desktop/Pillow-9.0.1
  Preparing metadata (setup.py) ... done
Using legacy 'setup.py install' for Pillow, since package 'wheel' is not installed.
Installing collected packages: Pillow
  Running setup.py install for Pillow ... done
Successfully installed Pillow-9.0.1
```
Did not crash on importing.

`sha256sum` hash of newly built library file:
```
1821b087ca27e013c080ce8c8b7f7db902fce29db6cbecd74d1fb9e41e39c997  /Users/***/testenv/lib/python3.9/site-packages/PIL/_imaging.cpython-39-darwin.so
```
and all the external libraries depended by `Pillow` are installed via Homebrew.

**Comment by nulano** [comment]
Actually, I think this is a change in the GHA image for MacOS, triggered by an update to some unrelated package on brew (IIRC that was the cause when this happened previously).

Comparing the wheels, 9.0.1 has an additional dylib, and the X related dylibs have different permissions, suggesting they were not built by pillow-wheels but come from a different source:

Pillow 9.0.0:
![image](https://user-images.githubusercontent.com/3819630/152369665-817b2c46-8cd9-426e-a6f0-04f6bda8aed8.png)

Pillow 9.0.1:
![image](https://user-images.githubusercontent.com/3819630/152369735-d8d4b25a-04f2-4b05-999b-edd9ae5fbe92.png)

I might have a proposed fix for this, but pillow-wheels takes a long time to run.

**Comment by pmh722** [comment]
+1 cannot install matplotlib on M1 Mac this morning

**Comment by nulano** [comment]
I have created https://github.com/python-pillow/pillow-wheels/pull/249 with a potential fix.

A build of Pillow with this change is available here if some would like to test it (download wheels or wheels-latest, then pip install the appropriate wheel for your platform): https://github.com/nulano/pillow-wheels/actions/runs/1790264094

**Comment by radarhere** [comment]
https://github.com/python-pillow/pillow-wheels/pull/249 has been merged, and I've uploaded the M1 wheels to PyPI with a build number.

This should be fixed now, but if someone else would like to confirm?

**Comment by abey79** [comment]
I've had the same issue but 9.0.1-1 works for me 👍🏻 (FWIW, I'm not using Homebrew but MacPorts)

**Comment by ajslater** [comment]
Still seems broken for me. Cleared my poetry cache of the wheels before trying again just now.
Darwin M1, homebrew.

**Comment by radarhere** [comment]
@ajslater could you try this and let us know if it works?
```
python3.9 -m pip install --force-reinstall https://files.pythonhosted.org/packages/34/4e/a491038f9bb13ea7f69874789d2cb69577eefb16724d678602f42222128f/Pillow-9.0.1-1-cp39-cp39-macosx_11_0_arm64.whl
```

**Comment by ajslater** [comment]
Hey that does work! Thanks for the suggestion, @radarhere. I used the poetry equivalent. 
Do you reckon this wheel just takes a little while to propagate past pypi caches?

Nice work @nulano

**Comment by radarhere** [comment]
Cool.

I'm not familiar with poetry, but PyPI itself shouldn't have this much of a delay. PyPI won't let us replace the original wheel, only add additional wheels with different build numbers. So we have followed PyPI's plan for what to do in this situation, and it should stop the influx of new users experiencing this problem.

**Comment by ajslater** [comment]
Nuked all my pip & poetry caches, destroyed my venv and installed from pypi and now it works. Thanks all.

**Comment by WittmannF** [comment]
`pip uninstall pillow` followed by `conda install pillow` worked for me.

**Comment by johncronan** [comment]
Installed before the fix, and I'm using poetry. Here's what I used:

```
poetry cache clear pypi --all
poetry update
pip uninstall pillow
poetry install
```
