### ISSUE TITLE
libimagequant included in conda-forge package

### ISSUE THREAD

**Issue by FelixS90** [python-pillow/Pillow#6019]
### What did you do?
`conda install -c conda-forge pillow
`
### What did you expect to happen?
Not pulling in libimagequant as a dependency as outlined in https://pillow.readthedocs.io/en/stable/installation.html#external-libraries ("Libimagequant is licensed GPLv3, which is more restrictive than the Pillow license, therefore we will not be distributing binaries with libimagequant support enabled.")

### What actually happened?
libimagequant was pulled in as a dependency.

### What are your OS, Python and Pillow versions?

* OS: Win10
* Python: 3.9
* Pillow: 9.0

Note: The behaviour seems to have changed from 8.* to 9.* (from looking at the meta.yaml downloaded through the wheels from https://anaconda.org/conda-forge/pillow/files?sort=basename&sort_order=desc).
![image](https://user-images.githubusercontent.com/9250590/152512498-a8f0c10c-c5db-48f7-8424-830bb0e99644.png)

Note: I have not confirmed with PyPI.

Feel free to delegate to the people from conda-forge if you think that this is a repackaging issue.

**Comment by radarhere** [comment]
meta.yaml would be controlled from https://github.com/conda-forge/pillow-feedstock, so this isn't directly a question for this repository, no. The line you're referring to was added in https://github.com/conda-forge/pillow-feedstock/pull/104

That said, in my limited understanding, I wouldn't have thought that meta.yml is putting libimagequant into a file with Pillow and sending it out. I think it's just listing it as something that is separately installed.

**Comment by h-vetinari** [comment]
Hey, one of the conda-forge maintainers here.

Which platform are you on? https://github.com/conda-forge/pillow-feedstock/issues/107 removed libimagequant on windows due to other issues.

Also, it seems you're in an environment that doesn't allow GPL dependencies, is that correct? We could solve this (in theory) by having different outputs for different bindings, but considering the number of them, that's would be a bit of a hassle...

**Comment by radarhere** [comment]
@FelixS90 did you have anything further to add? This matter seems to have now been picked up in https://github.com/conda-forge/pillow-feedstock/issues/111 and https://github.com/conda-forge/pillow-feedstock/issues/109
