### ISSUE TITLE
ImageTk.getimage() is broken (again)

### ISSUE THREAD

**Issue by muditl** [python-pillow/Pillow#6020]
### What did you do?
Tried to convert a PhotoImage to a Image using the ImageTk library function 

### What did you expect to happen?
Get an Image from the PhotoImage

### What actually happened?
got a TclError:
dir..\lib\site-packages\PIL\ImageTk.py", line 279, in getimage
    photo.tk.call("PyImagingPhotoGet", photo, block.id)
_tkinter.TclError: invalid command name "PyImagingPhotoGet"

### What are your OS, Python and Pillow versions?
* OS: Windows 10
* Python: 3.10.2
* Pillow: 8.0.1

```python
from tkinter import *
from PIL import Image, ImageTk
root = Tk()
p_img = PhotoImage(file='dir/img_name')
image = ImageTk.getimage(p_img)
```

**Comment by radarhere** [comment]
When you say "again", could you elaborate on this? Are you saying that it has been broken with some Pillow versions for you and not others?

Bear with me if you know this and think it is obvious, but
```python
p_img = PhotoImage(file='dir/img_name')
image = ImageTk.getimage(p_img)
```
could be simplified to 
```python
image = Image.open('dir/img_name')
```
You may have just used that specific code to demonstrate the general problem however.

Also, if you look at https://pillow.readthedocs.io/en/stable/installation.html#python-support, you will see that Pillow 8.0.1 is not intended to support Python 3.10. I doubt it would solve your problem, but I would recommend upgrading to a newer version of Pillow.

**Comment by muditl** [comment]
Greetings, 
I was referring to a [previous issue (from 2019)]((https://github.com/python-pillow/Pillow/issues/2372)) that has been long solved. In hindsight, maybe referencing such an old issue was not useful. 

Yes, I am aware that I can use the code provided, and yes, you are correct that I used the code to demonstrate the issue. 
The actual code is to resize a PhotoImage and I don't know any other way of doing so without converting to an Image. I can make it work without, but still thought useful to open the issue. Suggestions to resize without conversion would be very helpful! 

Thank you for the update suggestion. I am now running Pillow 9.0.0, however the issue still persists.

**Comment by radarhere** [comment]
Hi. Another question just to provide context - what version of Tkinter are you using?
```pycon
>>> from PIL import _tkinter_finder
>>> _tkinter_finder.tk_version
'8.6'
```

**Comment by muditl** [comment]
It is 8.6

**Comment by radarhere** [comment]
Ok, I've realised what the problem is - [`getimage()`](https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/src/PIL/ImageTk.py#L274-L281) does not call `_imagingtk.tkinit` [like `PhotoImage.paste` does](https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/src/PIL/ImageTk.py#L178-L199). This means that the Tcl commands are not necessarily [created.](https://github.com/python-pillow/Pillow/blob/ab8125fa6b8dff98b9de1a148308d40744583cca/src/Tk/tkImaging.c#L200-L214)

I've created PR #6032 to resolve this. If you would like an immediate solution, I find that the following code works.
```python
from tkinter import *
from PIL import Image, ImageTk
root = Tk()

# Clumsy way to activate Pillow's tkinter hooks
ImageTk.PhotoImage("RGB").paste(Image.new("RGB", (1, 1)))

p_img = PhotoImage("hopper.jpg")
image = ImageTk.getimage(p_img)
```

**Comment by muditl** [comment]
Thanks! I'll close this issue now.
