### ISSUE TITLE
ImageTk.PhotoImage very slow with PNG and Alphachannel

### ISSUE THREAD

**Issue by cardset** [python-pillow/Pillow#6022]
### What did you do?

Try to open an image with ImageTk.PhotoImage

### What did you expect to happen?

Opening the image in a fair amount of time

### What actually happened?

Waiting..., waiting far too long for such a small pic.

### What are your OS, Python and Pillow versions?

* OS: Windows 8.1
* Python: 3.8
* Pillow:  8.0.1

```python
from PIL import Image, ImageTk
from six.moves import tkinter

import time  # only to stop the time
start = time.process_time()


root = tkinter.Tk()

img = Image.open('shade.png')
img = img.convert("RGBA")  # make sure, it has alphachannel

print(time.process_time() - start, "after image.open")


img = ImageTk.PhotoImage(img)  # too slow

print(time.process_time() - start, "after PhotoImage")
```
![shade](https://user-images.githubusercontent.com/48878078/152642422-69ebd09b-18dc-49bd-bee3-92a769063bed.png)

**Comment by radarhere** [comment]
Hi. Testing, I find that the delay occurs at [the point](https://github.com/python-pillow/Pillow/blob/71839a76234edf09c2b5e062add2868ca04eb3a9/src/Tk/tkImaging.c#L143-L152) where Pillow calls [Tk_PhotoPutBlock](https://fiona.dmcs.pl/pd/tcl8.3/TkLib/FindPhoto.htm#M5). So I don't think the delay is within Pillow as such, but within Tk when it loads the data.

I don't think there's anything that Pillow can do about this. You might want to head over to https://core.tcl-lang.org/tk/ticket and file a ticket there.

**Comment by radarhere** [comment]
A ticket has been created - https://core.tcl-lang.org/tk/tktview?name=b9827ece14 - and another user is able to replicate it.

**Comment by toxicrecker** [comment]
Is this going to be fixed anytime soon

**Comment by toxicrecker** [comment]
alright, thanks

**Comment by chrstphrchvz** [comment]
This has been a known issue at least since 2004: https://core.tcl-lang.org/tk/info/919066. I am not a Tcl/Tk member and cannot say authoritatively when or whether it will be fixed, but I personally doubt it will be fixed anytime soon.
