### ISSUE TITLE
Updating GIF comment attribute without changing image data

### ISSUE THREAD

**Issue by EvilDude** [python-pillow/Pillow#6024]
Hello,

This is a question but maybe also a feature request.

I am working with editing/storing info in the metadata of image files. 

For GIF files I figured I could use the comment attribute to store information.
However, when simply saving the image with a new comment value I got the same noise/dithering result as in [this issue.](https://github.com/python-pillow/Pillow/issues/4263
)

```python
clickedimagePILImageobject = Image.open(clickedimagepath)
clickedimagePILImageobject.save(duplicatedimagepath, save_all=True,comment='Test',optimize=False)
```

Based on the comments in that issue and other information, I found that if I processed the image frames as follows that I was able to generate a copy of the original GIF that does not have the noise anymore. But while it appears to look the same as the original, in practice the image is still changed as at least the filesize is noticeably different. The test image, added below, goes from 3 MB to 6 MB.

```python
clickedimagePILImageobject = Image.open(clickedimagepath)
frames = []
        
for frame in ImageSequence.Iterator(clickedimagePILImageobject):
  frame = frame.quantize(method=Image.MEDIANCUT)
  frames.append(frame)
    
frames[0].save(duplicatedimagepath, save_all=True,comment='Test',optimize=False, append_images=frames[1:])
```

I've been trying various methods/settings to get rid of the difference as I assume it is just a matter of selecting the right ones but I don't seem to be able to work it out.

Alternatively, unless I've been overlooking it, it would be nice to have a way to simply save the GIF with an updated comment attribute without needing to dig into the image internals.

* OS: 
Windows 10
* Python: 
Python 3.7.9
   Looking at this now I realize that this version is quite old. I'll be looking into updating this.
* Pillow: 
Pillow-9.0.1

[Test image](https://user-images.githubusercontent.com/16456745/152652303-69e6066a-3435-42bc-819c-fbc19fe9c824.gif)

**Comment by radarhere** [comment]
How about this? Looking at GifImagePlugin, I was able to write a method that will update the GIF comment without changing anything else about the GIF file.

```python
from PIL import _binary

def set_comment(in_path, out_path, comment):
    with open(in_path, "rb") as fp:
        def data():
            s = fp.read(1)
            if s and s[0]:
                return fp.read(s[0])

        s = fp.read(13)
        if s[:6] not in [b"GIF87a", b"GIF89a"]:
            raise SyntaxError("not a GIF file")
        flags = s[10]
        if flags & 128:
            bits = (flags & 7) + 1
            fp.read(3 << bits)
        after = None
        while True:
            if after is None:
                before = fp.tell()
            s = fp.read(1)
            if s == b"!":
                s = fp.read(1)
                while data():
                    pass
                if s[0] == 254:
                    after = fp.tell()
            elif s == b",":
                s = fp.read(9)
                flags = s[8]
                if flags & 128:
                    bits = (flags & 7) + 1
                    fp.read(3 << bits)
                fp.read(1)
            elif not s or s == b";":
                break
        fp.seek(0)
        before_bytes = fp.read(before)
        fp.seek(after or before)
        after_bytes = fp.read()
        with open(out_path, "wb") as fp:
            fp.write(before_bytes)
            if comment:
                fp.write(b"!" + _binary.o8(254))
                if isinstance(comment, str):
                    comment = comment.encode()
                for i in range(0, len(comment), 255):
                    subblock = comment[i : i + 255]
                    fp.write(_binary.o8(len(subblock)) + subblock)
                fp.write(_binary.o8(0))
            fp.write(after_bytes)

from PIL import Image
for comment in (None, b"New comment"):
    set_comment("in.gif", "out.gif", comment)
    with Image.open("out.gif") as im:
        assert im.info.get("comment") == comment
```

**Comment by EvilDude** [comment]
Thanks for that!

On the test file from the opening post it does work great.
However, some of other files I'm running it on appear to get corrupted. The visible effect between files is not always the same, but I assume it's writing the comment in an unexpected location for those. Attempting to read back the comment always results in 'None'

I've attached one original and the copy after processing through the comment function. 
In that case it gets a corrupted band across the top in the final frame. Some other files appear to get color issues in all frames overall, or a combination of both.


[Original](https://user-images.githubusercontent.com/16456745/152862023-1cbc5c13-6563-4dc7-82f1-10bb5b5d412b.gif)

[Copy with corrupted band](https://user-images.githubusercontent.com/16456745/152862047-a489fa76-1753-477a-999e-629e75769e57.gif)

**Comment by radarhere** [comment]
Ah, yep, minor mistake. Try this instead.

```python
from PIL import _binary

def set_comment(in_path, out_path, comment):
    with open(in_path, "rb") as fp:
        def data():
            s = fp.read(1)
            if s and s[0]:
                return fp.read(s[0])

        s = fp.read(13)
        if s[:6] not in [b"GIF87a", b"GIF89a"]:
            raise SyntaxError("not a GIF file")
        flags = s[10]
        if flags & 128:
            bits = (flags & 7) + 1
            fp.read(3 << bits)
        after = None
        while True:
            if after is None:
                before = fp.tell()
            s = fp.read(1)
            if s == b"!":
                s = fp.read(1)
                while data():
                    pass
                if s[0] == 254:
                    after = fp.tell()
            elif s == b",":
                s = fp.read(9)
                flags = s[8]
                if flags & 128:
                    bits = (flags & 7) + 1
                    fp.read(3 << bits)
                fp.read(1)
                break
            elif not s or s == b";":
                break
        fp.seek(0)
        before_bytes = fp.read(before)
        fp.seek(after or before)
        after_bytes = fp.read()
        with open(out_path, "wb") as fp:
            fp.write(before_bytes)
            if comment:
                fp.write(b"!" + _binary.o8(254))
                if isinstance(comment, str):
                    comment = comment.encode()
                for i in range(0, len(comment), 255):
                    subblock = comment[i : i + 255]
                    fp.write(_binary.o8(len(subblock)) + subblock)
                fp.write(_binary.o8(0))
            fp.write(after_bytes)

from PIL import Image
for comment in (None, b"New comment"):
    set_comment("in.gif", "out.gif", comment)
    with Image.open("out.gif") as im:
        assert im.info.get("comment") == comment
```

**Comment by EvilDude** [comment]
Yes, that did it. I was able to process all GIFs I had on hand with no apparent issues.

Thank you very much for your time on this, hopefully this is usable as an addition to the GIF plugin as well then.
Unless there is anything else to do I guess the issue can be closed.


A side remark regarding image data integrity:

I have been running the output of Image.tobytes() through a hash to check that an image's data wasn't changed while performing metadata changes. (An idea from someplace)

In the case of opening that test GIF and immediately saving it, which introduced that noise/changed size, I had noticed that the hash computed this way was still identical between the original and the saved GIF. I'm guessing I'll need to adapt it so I'm taking all frames into account for GIFs.

So, while it's probably non-trivial considering the different image formats, it might be good to have a designated method with a reliable check for this, even for just for a few main formats. I feel it's quite important but often easy to get wrong without noticing.
This has probably come up before, so just wanted to add my vote.

Thanks again.

**Comment by radarhere** [comment]
It would seem to me that you could just iterate over all frames in an image, and combine that information to generate your hash.
```python
import hashlib
from PIL import Image, ImageSequence
data = b""
with Image.open("Tests/images/iss634.gif") as im:
    for im_frame in ImageSequence.Iterator(im):
        data += im_frame.tobytes()
    print(hashlib.sha256(data).hexdigest())
```
The closest request for a hash method would be #3120
