### ISSUE TITLE
ImageDraw.Draw.textsize issue with non ansi fonts

### ISSUE THREAD

**Issue by chiboreache** [python-pillow/Pillow#6028]
_Arch Linux, everything is bleeding edge._

[code from stackoverflow](https://stackoverflow.com/a/66091387/8912934)

`draw.textsize()` takes no account to `language=lang_id` parameter, literally zero difference

therefore scaling is very bad for non ansi fonts

![2022-02-06x21:44:51](https://user-images.githubusercontent.com/16459251/152696414-5852773d-df19-4f35-915a-57932929feb1.jpg)

**Comment by nulano** [comment]
Looking at the source, language is being passed correctly to the layout engine.

I believe what you are running into is a poor definition of what `textsize` means, due to historical reasons. For this reason, Pillow 8.0.0 introduced [textbbox()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textbbox).

This limitation is mentioned in the [textsize() docs](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textsize):
> For historical reasons this function measures text height from the ascender line instead of the top, see [Text anchors](https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html#text-anchors). If you wish to measure text height from the top, it is recommended to use [textbbox()](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.textbbox) with anchor='lt' instead.

**Comment by chiboreache** [comment]
but i'm using `anchor="mm"` 

i guess size should calculates equal for all, upper or lower, but equally

**Comment by nulano** [comment]
Actually, looking at the code you linked to, it does not even look at the text height, so you should not be surprised if short text is clipped on the top/bottom.

**Comment by nulano** [comment]
> but i'm using `anchor="mm"`
> 
> i guess size should calculates equal for all, upper or lower, but equally

I don't understand, `textsize()` does not accept an anchor.

**Comment by chiboreache** [comment]
oh i looked at `text()`

> returns the bottom of the bounding box assuming
ok got it

but why this things aren't on one bottom line?

![1](https://user-images.githubusercontent.com/16459251/152697991-6958ed68-756b-4774-afef-448f54e1f4b5.jpg)
![2](https://user-images.githubusercontent.com/16459251/152697992-28e2407b-2bc4-4646-8fcf-bac4e83e6ff3.jpg)

**Comment by nulano** [comment]
> but why this things aren't on one bottom line?

I don't understand your question. If you want text to have a shared baseline, you should use a vertical anchor of `s`. If you use the same font with the same size, vertical anchors `a`, `m`, `d` will also have a shared baseline. See https://pillow.readthedocs.io/en/stable/handbook/text-anchors.html#quick-reference

**Comment by chiboreache** [comment]
that was a logic error in `xy` parameter, now it's clear

![2022-02-07x19:44:30](https://user-images.githubusercontent.com/16459251/152832981-9b313f75-4645-47f1-8e1e-1ab7368c7679.jpg)


but still useless, because of one-axis nature of scaling

`fs = (default_fs / (observed_width / image.width) * m)`
