### ISSUE TITLE
Adding a background image makes widgets disappear

### ISSUE THREAD

**Issue by jazz-it** [python-pillow/Pillow#6043]
### What did you do?
I tried to dynamically add new frame elements and the last of them should contain an image background. Surprisingly, when I added an image as a background to dynamically created element, suddenly all other widgets disappeared from the container.

### What did you expect to happen?
I surely didn't expect such issue and I can't explain to myself why it happens. I already tried similar thing when I didn't create widgets dynamically and it worked as expected. Most probably the issue appears only whilst dynamically creating widgets.

### What actually happened?
The following two lines are critical:
```python
    img = ImageTk.PhotoImage(file="image.jpg")
    frame_v = Label(f, text=':)', font='calibri 36', compound='center', image=img)
```
Only when removing the first line entirely and `image=img` at the end of the second line, then the program works as expected, but of course - **without** the wanted image as a background. The following part of code works as expected:
```python
    frame_v = Label(f, text=':)', font='calibri 36', compound='center')
```

### What are your OS, Python and Pillow versions?

* OS: Manjaro KDE Plasma (Stable branch)
* Python: 3.10.2
* Pillow: 9.0.1

```python
from tkinter import *
from tkinter import ttk
from PIL import Image, ImageTk

def Quit():
    window.destroy()
    exit()

def ShowFrame(f):
    f.tkraise()

def CreateNewFrame():
    global FRAMES

    f = Frame(window)
    FRAMES.append(f)
    f.grid(row=0,column=0,sticky='nsew')

    img = ImageTk.PhotoImage(file="image.jpg")
    frame_v = Label(f, text=':)', font='calibri 36', compound='center', image=img)
    frame_v.pack(fill='both', expand=True)
    frame_btn = Button(f, text='START',command=lambda:ShowFrame(FRAMES[0]))
    frame_btn.pack(fill='x', expand=True, side=LEFT, anchor='s', ipady=15)
    quit_btn = Button(f, text="QUIT", command=lambda:Quit())
    quit_btn.pack(fill='x', expand=True, side=RIGHT, anchor='s', ipady=15)


window = Tk()
# window.state('zoomed')
window.attributes('-zoomed', True)

window.rowconfigure(0, weight=1)
window.columnconfigure(0, weight=1)

FRAMES = []
FRAMES.append(Frame(window))
frame = FRAMES[0]

frame.grid(row=0,column=0,sticky='nsew')

frame_title = Label(frame, text='WELCOME', font='times 35')
frame_title.pack(fill='both', expand=True)
frame_btn = Button(frame, text='START',command=lambda:CreateNewFrame())
frame_btn.pack(fill='x', expand=True, side=LEFT, ipady=15)
quit_btn = Button(frame, text="QUIT", command=lambda:Quit())
quit_btn.pack(fill='x', expand=True, side=RIGHT, ipady=15)

ShowFrame(frame)
window.mainloop()
```

**Comment by radarhere** [comment]
If you'll permit me to ask the type of simple question that one must sometimes ask in the course of debugging - when I run your code, I only saw all the widgets disappear when image.jpg was not present and a FileNotFoundError was raised. Is image.jpg present? And is it named image.jpg exactly, not perhaps image.jpeg? Are you sure that no errors are being raised?

A related note - even when image.jpg is present, in order to make the image appear correctly with tkinter, I find that you need to make sure that `img` stays around, and is not garbage collected. Inserting `global img` into `CreateNewFrame()` is the quickest way to do that in your code.

**Comment by jazz-it** [comment]
> Is image.jpg present? And is it named image.jpg exactly, not perhaps image.jpeg? Are you sure that no errors are being raised?

I understand your reasons to ask me that and the answer is yes, the image is present and displayed within the last frame. You could use any existing JPG image in your path and you will be able to reproduce this issue, I'm sure.

> Inserting `global img` into `CreateNewFrame()` is the quickest way to do that in your code.

I just added `global img` to the `CreateNewFrame()` function to avoid issue with the garbage collector and the issue persists.

**Comment by jazz-it** [comment]
> On the contrary, I can't replicate the issue.

I just tried with another random JPG and you're right: **sometimes** it works. The issue is obviously JPG dependant! You could try with this image, which is just one of many that creates the issue for me: https://i.pinimg.com/originals/42/90/2e/42902ee4fd0a2e11d56f56e6d0962f83.jpg

> On macoS, if I remove `window.attributes('-zoomed', True)` (I get a TclError when it is present), add in `global img`, and copy one of our test images to be image.jpg, it works for me.

The `zoomed` state is obviously OS's window manager dependent, therefore you should use `window.state('zoomed')` which works for Mac (but that would work for Windows as well).

**Comment by radarhere** [comment]
The image you have linked to is bigger than the original image I tested with.

If I rescale your image to be 1200x750, and run your code, here is what I see.
<img width="500" alt="1200" src="https://user-images.githubusercontent.com/3112309/153521523-0b427cd8-4f62-42d5-883f-71d44a61050b.png">

If I rescale your image to be 1300x812, I see that the buttons are getting smaller.
<img width="500" alt="1300" src="https://user-images.githubusercontent.com/3112309/153521637-b2fcb5cb-5b03-4d9b-9329-d7e3cc2cf6bb.png">

If I rescale your image to be 1400x874, then the buttons are no longer visible.
<img width="500" alt="1400" src="https://user-images.githubusercontent.com/3112309/153521691-12d9498d-d167-4135-8939-889e01e153d9.png">

Does this match your experience? If so, it is not that the buttons are being removed or forgotten, it is that they are being starved for space by the large image, making this a problem with tkinter layout, and not anything wrong with how Pillow is interacting with tkinter.

**Comment by jazz-it** [comment]
> Does this match your experience?

That matches my experience, yes. So, actually, when large images are added as a background, I would expect it would clip the remaining parts that are bigger than the parent Frame container, but it seems it stretches it as any other element in the foreground, which is really not a desired behavior. Thanks for your explanation and time.
