### ISSUE TITLE
Pillow's JPEG decode result different from OpenCV

### ISSUE THREAD

**Issue by lyksdu** [python-pillow/Pillow#6047]
### What did you do?

hey, for some reason, I have to do something about Image decoding. And the conclusion is, Pillow's JPEG decode result different from OpenCV in some cases.
Code:
```python
with open("img_data/test.jpeg", "rb") as fp:
    data= fp.read()
def PIL_load():
    a = np.asarray(Image.open(io.BytesIO(data), ), np.uint8)
    print(a.sum())

def cv2_load():
    b = cv2.imdecode(
                    np.frombuffer(
                        data, np.uint8),
                    cv2.IMREAD_COLOR) 
    print(b.sum())
```
I find a blog talking about this, but it seems nothing changed after half a year.
[link](https://towardsdatascience.com/image-read-and-resize-with-opencv-tensorflow-and-pil-3e0f29b992be)

### What did you expect to happen?

I think the output of the two functions is the same, but I got different.

### What actually happened?

```pycon
>>> for PIL_load:        226343825
>>> for opencv_load: 226343957
```

### What are your OS, Python and Pillow versions?

* OS: Debian 10
* Python: 3.9
* Pillow: 9.0

I think this can be reproduced in any jpeg image. I will upload the test image,  if necessary.

```python
with open("img_data/test.jpeg", "rb") as fp:
    data= fp.read()
def PIL_load():
    a = np.asarray(Image.open(io.BytesIO(data), ), np.uint8)
    print(a.sum())

def cv2_load():
    b = cv2.imdecode(
                    np.frombuffer(
                        data, np.uint8),
                    cv2.IMREAD_COLOR) 
    print(b.sum())
```

**Comment by radarhere** [comment]
Using [one of our test images](https://github.com/python-pillow/Pillow/blob/main/Tests/images/hopper.jpg),

```python
import numpy as np
from PIL import Image
print("Pillow", np.asarray(Image.open("hopper.jpg")).sum())

import cv2
print("OpenCV", cv2.imread("hopper.jpg").sum())
```
I actually get the same result for them, 4345064. If you run my code over our test images, do the results match for you as well? Perhaps you do need to upload your image?

**Comment by lyksdu** [comment]
@radarhere  eh, I upgrade my pillow version from 9.0.0.a to 9.0.1, and then this error has been fixed. maybe I have installed an alpha version of Pillow ...
```
new my version 
Pillow                            9.0.1  # I forget the version before
Pillow-SIMD                       9.0.0.post1 
```
And I reproduce the problem on version 8.0. On Pillow 8.0.0, `hooper.jpg` is different.

one version 
```
Pillow                            8.0.0
Pillow-SIMD                       9.0.0.post1
```
I get 
```
Pillow 4345114
OpenCV 4345064
```

**Comment by radarhere** [comment]
Thanks all.
