### ISSUE TITLE
Error measuring strings in some fontsizes

### ISSUE THREAD

**Issue by CarlosCRO** [python-pillow/Pillow#6074]
### What did you do?
Using `font.getbbox()` I measured a series of string obtained by web scrapping.

### What did you expect to happen?
To both the width of the string I scrapped and the result of Pillow to be the same
### What actually happened?
When using Arial, font 22, the result given by Pillow gives a shorter width than the one the string has in the web. Spacing between words is normal, don't think it has to do with any CSS attribute.
This problem replicates when using an even number as fontsize. I'll show examples with an even and an odd fontsize number for better understanding.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.6
* Pillow: 8.4.0

```python
def getwidth(element,  myFont):
    dir_to_font = r'C:\Windows\Fonts\''
    dir_to_font = dir_to_font[:-1]
    fontname = myFont[0] + '.ttf'
    font = ImageFont.truetype(dir_to_font+fontname,myFont[1])
    width_text = font.getbbox(element)[2]
    return width_text
text = 'different scientific texts through following a specific descriptive'
w1 = getwidth(text,('Arial', 22) #Output is 597, which crops the string in the web if a screenshot is done
w2= getwidth(text,('Arial',23) #Output is 635, the width in the web of this exact string matches.

```
First output:
![image](https://user-images.githubusercontent.com/60963224/154858063-7ab14ccc-5783-46bf-bd94-3bbc122bbe05.png)
Second output:
![image](https://user-images.githubusercontent.com/60963224/154858152-5878ab0f-fd4f-48d2-97f5-58f0daddaef7.png)

**Comment by nulano** [comment]
Different text rendering engines will render text differently, there is no reason to expect Pillow to match a web browser (I expect there will even be differences between different web browsers!).

However, you might get better results if you use Raqm layout instead of basic layout:
```python
from PIL import ImageFont

def getwidth(text, fontname, size, engine):
    return ImageFont.truetype(f"{fontname}.ttf", size, layout_engine=engine).getbbox(text)

text = 'different scientific texts through following a specific descriptive'
for engine in (ImageFont.LAYOUT_BASIC, ImageFont.LAYOUT_RAQM):
    print(getwidth(text, "arial", 22, engine))
    print(getwidth(text, "arial", 23, engine))
```

|Font size|Basic layout|Raqm layout|
|-----|-----|----------|
|22|(0, 4, 597, 24)|(0, 4, 604, 24)|
|23|(0, 4, 635, 26)|(0, 4, 631, 26)|

To install Raqm, see the installation instructions: https://pillow.readthedocs.io/en/stable/installation.html#external-libraries

> Pillow wheels since version 8.2.0 include a modified version of libraqm that loads libfribidi at runtime if it is installed. On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-Link Library Search Order (Microsoft Docs)](https://docs.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications) (fribidi-0.dll or libfribidi-0.dll are also detected).

**Comment by CarlosCRO** [comment]
Thanks a lot! Indeed the results seem better this way. I'll try to use this layout.

**Comment by radarhere** [comment]
@CarlosCRO are you happy for this issue to be close, or was there anything further?

**Comment by CarlosCRO** [comment]
Yes, thank you very much for the help! I already tested it and works fine
