### ISSUE TITLE
PIL.ImageFont.truetype takes size in points, but not convert to size in pixels, before FT_Set_Pixel_Sizes is called

### ISSUE THREAD

**Issue by underwatergrasshopper** [python-pillow/Pillow#6079]
In result, drawn text is smaller than should be.

Call hierarchy:
```
(FontImage.py)
truetype 
FreeTypeFont.__init__
core.getfont
(_imagingft.c)
getfont
FT_Set_Pixel_Sizes
```

**Comment by radarhere** [comment]
You're right. If I use Pillow to write '120' in a font,

![pillow](https://user-images.githubusercontent.com/3112309/155039378-90223a5c-15ec-4f4f-84a4-bcc64375d3de.png)

and use the same font in GIMP to write in points and in pixels and compare the two images (ignoring the fact that GitHub is scaling down the larger image on this page to fit) it is clear we are using pixels and not points.
![gimp](https://user-images.githubusercontent.com/3112309/155039297-c54edf5a-18dd-4b4b-8251-2f2a970a78d5.png)

I've created PR #6081 to resolve this by correcting the documentation.
