### ISSUE TITLE
Install Pillow on Python Portable version

### ISSUE THREAD

**Issue by deltaromeo974** [python-pillow/Pillow#6090]
Hi

* OS: Windows
* Python: 3.10
* Pillow: 3.2.2

I have Python 3.10 portable version and i need pillow, would anyone tell me a method to install it ?
Thanks

**Comment by radarhere** [comment]
The simplest way is through pip.

https://pillow.readthedocs.io/en/stable/installation.html#windows-installation

```
python3 -m pip install --upgrade pip
python3 -m pip install --upgrade Pillow
```

**Comment by deltaromeo974** [comment]
Thanks

I used this method but it didn't work

The problem was firewall filter access

Now it is reachable

Thanks

Le mer. 23 févr. 2022 à 08:22, Andrew Murray ***@***.***> a
écrit :
