### ISSUE TITLE
Can't draw on cropped image?

### ISSUE THREAD

**Issue by frdfsnlght** [python-pillow/Pillow#6114]
### What did you do?
Given an ImageDraw object (by a third party library), I want to crop a region and create a new ImageDraw object on the cropped region.

### What did you expect to happen?
I expected a valid ImageDraw object that I could use to draw on the cropped region.

### What actually happened?
I get a python exception:

```
Traceback (most recent call last):
  File "/scripts/crop.py", line 9, in <module>
    draw2 = ImageDraw.Draw(region)
  File "/scripts/python-lib/PIL/ImageDraw.py", line 790, in Draw
    return ImageDraw(im, mode)
  File "/scripts/python-lib/PIL/ImageDraw.py", line 58, in __init__
    im.load()
AttributeError: 'ImagingCore' object has no attribute 'load'
```

### What are your OS, Python and Pillow versions?

* OS: Running in the python:3 Docker container
* Python: 3.10.2
* Pillow: 9.0.1

Here's the sample code:

```python
from PIL import Image, ImageDraw

im = Image.new('RGB', (100, 100), 'white')
draw1 = ImageDraw.Draw(im)

box = (10, 10, 10, 10)
region = draw1.im.crop(box)
draw2 = ImageDraw.Draw(region)
```

I have to be able to start with the "draw1" object since that's what I'm given by the third party library I'm using (luma.core). Perhaps I'm doing something obviously wrong, but it's not obvious to me.

**Comment by radarhere** [comment]
```python
region = draw1.im.crop(box)
```
This is the problem. You are imagining that `draw1.im` is the image that you passed into it. [Not so.](https://github.com/python-pillow/Pillow/blob/397a9409959bccd0130d0b51820f2a94e3bf153d/src/PIL/ImageDraw.py#L74)

It's not really expected that you use `draw1.im`. You should just be able to keep working on `im` after performing whatever ImageDraw operations you need to. So `region = im.crop(box)`.

I'm guessing you think that doesn't work for some reason though, so feel free to provide a different example and ask another question.

**Comment by frdfsnlght** [comment]
The problem is I don't have direct access to the image ("im" in this example) used to create draw1. I just get draw1 from the third party library.

I see in the source that draw1._image references the original image, but I didn't want to refer to a "private" property of draw1. I thought there would be a more "official" way of accessing the original image an ImageDraw was created from, like a "getImage" method or something. Apparently no?

**Comment by radarhere** [comment]
Unfortunately for your situation, no. What is the third party library?

**Comment by frdfsnlght** [comment]
It's luma.core (for driving a small embedded OLED display). I've since discovered that the library does give some access to the base image, so maybe this isn't a big problem for me at the moment. But it is curious [to me] why there's no "official" way to access the base image of an ImageDraw. But I won't sweat it for now.

Thanks for insight. Feel free to close this out as a non-issue.
