### ISSUE TITLE
Broken background on transparent GIFs built from individual frames

### ISSUE THREAD

**Issue by balt-is-you-and-shift** [python-pillow/Pillow#6115]
The background of transparent GIFs constructed from Images seems to not quite see the transparent color correctly.

```py
from PIL import Image

with Image.open('test.gif') as im:
	images = []
	durations = []
	for i in range(im.n_frames):
		im.seek(i)
		im.convert('RGBA')
		im_temp = Image.new('RGBA',im.size,(0,0,0,0))
		im_temp.paste(im,(0,0))
		images.append(im_temp)
		durations.append(im.info['duration'])
	images[0].save(
		'test-out.gif', 
		interlace=True,
		save_all=True,
		append_images=images[1:],
		loop=0,
		duration=durations,
		disposal=2,
		transparency = 255,
		background = 255,
		optimize=False
	)
```
This should copy the image perfectly, but there are artifacts.
![Input](https://user-images.githubusercontent.com/59123926/157148158-e21b8ba6-bcfa-4c50-bcbc-3ddc41ed1b48.gif)
![Output](https://user-images.githubusercontent.com/59123926/157148265-a302bff2-5be0-40e0-9f4c-dbe8f97b12c4.gif)
[Here's the venv I used to test this, in a zip.](https://github.com/python-pillow/Pillow/files/8201983/pillowtest.zip)

**Comment by resnbl** [comment]
I suspect that setting transparency and background to 255 is the issue. These values are indexes into the color palette but your palette only has 13 entries, not 255.  I fed the test input and output .gifs provided by @balt-is-you-and-shift into a small script I wrote, and here is the output:
```
% python3 mk_ani.py -i test.gif
PIL 9.0.1
"test.gif" size=(32, 32) mode=P is_ani=True #frames=8 loop=0 palette_size=13
0: disposal=2 transparency=0 duration=1000 background='idx=0 color=(0, 0, 0) #000000'
1: disposal=2 transparency=None duration=50 background='idx=0 color=(0, 0, 0) #000000'
2: disposal=2 transparency=None duration=70 background='idx=0 color=(0, 0, 0) #000000'
3: disposal=2 transparency=None duration=200 background='idx=0 color=(0, 0, 0) #000000'
4: disposal=2 transparency=None duration=100 background='idx=0 color=(0, 0, 0) #000000'
5: disposal=2 transparency=None duration=100 background='idx=0 color=(0, 0, 0) #000000'
6: disposal=2 transparency=None duration=100 background='idx=0 color=(0, 0, 0) #000000'
7: disposal=2 transparency=None duration=50 background='idx=0 color=(0, 0, 0) #000000'
% python3 mk_ani.py -i test-out.gif
PIL 9.0.1
"test-out.gif" size=(32, 32) mode=P is_ani=True #frames=8 loop=0 palette_size=13
0: disposal=2 transparency=255 duration=1000 background='idx=255 color=None None'
1: disposal=2 transparency=None duration=50 background='idx=255 color=None None'
2: disposal=2 transparency=None duration=70 background='idx=255 color=None None'
3: disposal=2 transparency=None duration=200 background='idx=255 color=None None'
4: disposal=2 transparency=None duration=100 background='idx=255 color=None None'
5: disposal=2 transparency=None duration=100 background='idx=255 color=None None'
6: disposal=2 transparency=None duration=100 background='idx=255 color=None None'
7: disposal=2 transparency=None duration=50 background='idx=255 color=None None'
```
When I copied the background and transparency from the source to the save() call, I think I got the results you desire:
```
% python3 mk_ani.py -i test-out-t0-bg-none.gif
PIL 9.0.1
"test-out-t0-bg-none.gif" size=(32, 32) mode=P is_ani=True #frames=8 loop=0 palette_size=13
0: disposal=2 transparency=0 duration=1000 background='idx=0 color=(0, 0, 0) #000000'
1: disposal=2 transparency=None duration=50 background='idx=0 color=(0, 0, 0) #000000'
2: disposal=2 transparency=None duration=70 background='idx=0 color=(0, 0, 0) #000000'
3: disposal=2 transparency=None duration=200 background='idx=0 color=(0, 0, 0) #000000'
4: disposal=2 transparency=None duration=100 background='idx=0 color=(0, 0, 0) #000000'
5: disposal=2 transparency=None duration=100 background='idx=0 color=(0, 0, 0) #000000'
6: disposal=2 transparency=None duration=100 background='idx=0 color=(0, 0, 0) #000000'
7: disposal=2 transparency=None duration=50 background='idx=0 color=(0, 0, 0) #000000'
```
![test-out-t0-bg-none](https://user-images.githubusercontent.com/33208090/157178443-0713496d-d0fb-4f54-98ad-a39ee2c85a42.gif)

**Comment by radarhere** [comment]
Take a look at this. If I set the transparency using the key from the info dictionary, it works.

```python
from PIL import Image

with Image.open('test.gif') as im:
	images = []
	durations = []
	transparency = im.info["transparency"]
	for i in range(im.n_frames):
		im.seek(i)
		im.convert('RGBA')
		im_temp = Image.new('RGBA',im.size,(0,0,0,0))
		im_temp.paste(im,(0,0))
		images.append(im_temp)
		durations.append(im.info['duration'])
	images[0].save(
		'test-out.gif', 
		interlace=True,
		save_all=True,
		append_images=images[1:],
		loop=0,
		duration=durations,
		disposal=2,
		transparency = transparency,
		background = 255,
		optimize=False
	)
```
![test-out](https://user-images.githubusercontent.com/3112309/157183652-50170ee9-bf1b-4e83-a484-b646d38ca402.gif)

**Comment by balt-is-you-and-shift** [comment]
This wouldn't solve the issue well, bad example. I'll make a better example of the issue when I can.

**Comment by balt-is-you-and-shift** [comment]
[test.zip](https://github.com/python-pillow/Pillow/files/8207131/test.zip)
Not very copy-pastable, but it's a much better example of the problem at hand. _Make sure you're using 9.0.1 to test this._

```py
from PIL import Image
import json

with open('durations.json','rb') as f:
  durations = json.load(f)
images = []
for n in range(8):
  with Image.open(f'test{n}.png') as im:
    im = im.convert('RGBA').resize([n*8 for n in im.size],Image.NEAREST)
    images.append(im)
images[0].save(
  'test.gif', 
  interlace=True,
  save_all=True,
  append_images=images[1:],
  loop=0,
  duration=durations,
  disposal=2,
  transparency = 255,
  background = 255,
  optimize=False
)
```

**Comment by balt-is-you-and-shift** [comment]
Seems to be inconsistent. Now, the example doesn't show the issue at hand. I'll look at this more later, as I don't have time at the moment.

**Comment by resnbl** [comment]
Not sure why you are setting transparency=255 (or why PIL is not complaining about it!). According to the docs (https://pillow.readthedocs.io/en/latest/handbook/image-file-formats.html#saving), transparency is an "index", i.e. offset into the color palette indicating which "color" should denote transparent pixels. Your image palette does not contain 256 colors (only 13 are used), so you are not getting the proper results. For the test provided, using transparency=0 works.

The same applies to the background setting: it is an index into the color palette. Again, setting to 0 will get what you want for this. (@radarhere : your solution is missing this part as well.)

FYI: here is the color palette for your generated GIF:
```
Global palette:
  0 #000000 (0, 0, 0)
  1 #00E436 (0, 228, 54)
  2 #FFEC27 (255, 236, 39)
  3 #FF004D (255, 0, 77)
  4 #29ADFF (41, 173, 255)
  5 #00B543 (0, 181, 67)
  6 #FF6C24 (255, 108, 36)
  7 #BE1250 (190, 18, 80)
  8 #065AB5 (6, 90, 181)
  9 #A8E72E (168, 231, 46)
  10 #C2C3C7 (194, 195, 199)
  11 #F3EF7D (243, 239, 125)
  12 #FF6E59 (255, 110, 89)
```
If there is anything amiss with PIL, I think it is that the `.save()` method did not complain about the transparency and background arguments being outside the range of the generated palette table.

On a side note: I went through the same thing as you: generating an animated image from a list of images. In my solution, I chose a file naming convention over a .json durations file. I named my inputs "nn-dDDD-blah.png" where "nn" is the image order index (for easily sorting the output of a glob.glob('*.png') call), "DDD" is the duration in msecs., and "blah" is anything but was used for the default output filename "blah.{gif|png}". Just another way of doing things...

![test](https://user-images.githubusercontent.com/33208090/157293804-c9851207-87d4-4c3f-be20-6aa80fcbd021.gif)

**Comment by balt-is-you-and-shift** [comment]
See, the problem with that is that _using transparency and background set to 255 worked fine in previous versions, and now setting them both to 0 won't work if the majority of the image isn't transparent._

**Comment by radarhere** [comment]
I've created PR #6128 to resolve this. With it, your code works when you remove the `transparency` setting altogether. What do you think of that?

```python
from PIL import Image

with Image.open('test.gif') as im:
    images = []
    durations = []
    for i in range(im.n_frames):
        im.seek(i)
        im.convert('RGBA')
        im_temp = Image.new('RGBA',im.size,(0,0,0,0))
        im_temp.paste(im,(0,0))
        images.append(im_temp)
        durations.append(im.info['duration'])
    images[0].save(
        'test-out.gif', 
        interlace=True,
        save_all=True,
        append_images=images[1:],
        loop=0,
        duration=durations,
        disposal=2,
        background = 255,
        optimize=False
    )
```

**Comment by balt-is-you-and-shift** [comment]
Seems great, thanks!
