### ISSUE TITLE
Handle PNG cause exception: OSError: Truncated File Read

### ISSUE THREAD

**Issue by dxsooo** [python-pillow/Pillow#6118]
### What did you do?
Open an image and get its width

### What did you expect to happen?
width printed

### What actually happened?
come into exception: 
**OSError: Truncated File Read**
in `convert`

### What are your OS, Python and Pillow versions?

* OS: archlinux(5.16.12-arch1-1)
* Python: 3.10
* Pillow:  9.0.1

```python
from PIL import Image
fn = '142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193'
with Image.open(fn) as fo:
    img = fo.convert('RGB')
    print(img.width)
```

the image: 
[142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193.zip](https://github.com/python-pillow/Pillow/files/8207680/142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193.zip)

it can be viewed in Browser and image viewer but failed in pillow.

**Comment by radarhere** [comment]
If I run [pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) over your image, I get
```
$ pngcheck 142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193    
142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193  EOF while reading IDAT data
ERROR: 142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193
```
So i would conclude that your image is broken.

But if all you want is the width, the following code will do that without a problem.
```python
from PIL import Image
fn = '142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193'
with Image.open(fn) as fo:
    print(fo.width)
```

**Comment by dxsooo** [comment]
> If I run [pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) over your image, I get
> 
> ```
> $ pngcheck 142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193    
> 142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193  EOF while reading IDAT data
> ERROR: 142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193
> ```
> 
> So i would conclude that your image is broken.
> 
> But if all you want is the width, the following code will do that without a problem.
> 
> ```python
> from PIL import Image
> fn = '142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193'
> with Image.open(fn) as fo:
>     print(fo.width)
> ```

yes, but get width is just a simple usage, there are many other operations(e.g.: `fo.show()`、`fo.convert('RGB')`)

Is there some flag or processing that make pillow can handle this broken image in proper way? As the image is valid in browser and image viewers

**Comment by radarhere** [comment]
For this particular image, you could just `load()` it and ignore the error.

```python
from PIL import Image
fn = '142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193'
with Image.open(fn) as fo:
    try:
    	fo.load()
    except OSError:
    	pass
    img = fo.convert('RGB')
    print(img.width)
```

**Comment by dxsooo** [comment]
> For this particular image, you could just `load()` it and ignore the error.
> 
> ```python
> from PIL import Image
> fn = '142fc7b8018343d43101dae4900c99a4c0de558e33f6da2d029320633aa01193'
> with Image.open(fn) as fo:
>     try:
>     	fo.load()
>     except OSError:
>     	pass
>     img = fo.convert('RGB')
>     print(img.width)
> ```

It works, thank radarhere
