### ISSUE TITLE
ImageGrab.grab colors switched

### ISSUE THREAD

**Issue by BigDvsRL** [python-pillow/Pillow#6126]
### What did you do?
```python
screenshot2 = ImageGrab.grab(all_screens=True)
```
### What did you expect to happen?

That the ImageGrab saves the Image with the right colors^^ 

### What actually happened?

The colors are switched up. I think red and blue are having the wrong place in the tuple

I noticed that because I was comparing Pixels on Screenshots, to automate something

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.8.0
* Pillow: 8.4.0

![WrongColors](https://user-images.githubusercontent.com/36280398/157997941-ad728eed-51bd-4865-98a1-e8af172484c7.jpg)
You'll see it in THIS Screenshot (Background is the Original Browser)

```python
Background_Color = (24, 23, 28) #r24, g23, b28
if screenshot1[94, 1575][0] == Background_Color[0] and screenshot1[94, 1575][1] == Background_Color[1] and screenshot1[94, 1575][2] == Background_Color[2]:
```
#from another Project but i guided myself by this
```python
bgr = (b, g, r)
    # print("test")
    if health[0] == b and health[1] == g and health[2] == r:
```
That was the reason i noticed the change with the pixels

**Comment by radarhere** [comment]
This is a continuation of https://github.com/python-pillow/pillow-wheels/issues/263

In that issue, you mentioned that you are using OpenCV. Because of that, I suspect your problem has nothing to do with screen grab, but instead, I suspect that you are not correctly converting your Pillow image to OpenCV.

OpenCV uses BGR, while Pillow uses RGB - see https://towardsdatascience.com/what-library-can-load-image-in-python-and-what-are-their-difference-d1628c6623ad.

**Comment by radarhere** [comment]
So I expect if you use only Pillow
```python
from PIL import ImageGrab
im = ImageGrab.grab(all_screens=True)
im.save("out.png")
```
then you will create a correct PNG.

If you run this code, as I expect you have been doing approximately,
```python
import cv2
import numpy as np
from PIL import ImageGrab
im = ImageGrab.grab(all_screens=True)
a = np.array(im)
cv2.imwrite("incorrect.png", a)
```
then you will get an incorrect image.

And the problem will be fixed by
```python
import cv2
import numpy as np
from PIL import ImageGrab
im = ImageGrab.grab(all_screens=True)
a = np.array(im)
a = cv2.cvtColor(a, cv2.COLOR_BGR2RGB)
cv2.imwrite("correct.png", a)
```

**Comment by radarhere** [comment]
@BigDvsRL did that resolve your problem?

**Comment by BigDvsRL** [comment]
Yeah, i solved it with ```python
screenshot2 = screenshot2[:, :, ::-1].copy()```

And now its correct

Yes, i did it the incorrect way, without converting
But thank you for also posting the correct way to solve it :)
