### ISSUE TITLE
Gif output seems to restrict color pallet and lose transparency

### ISSUE THREAD

**Issue by elton-okawa** [python-pillow/Pillow#6133]
### What did you do?
I tried to create a `gif` file with some gradients with alpha channel and I noticed that saving as `gif` format seems to restrict color pallet and lose the transparency.

I've created a simple one frame gif to showcase the situation
### What did you expect to happen?
I expected that the `gif` output would preserve the original image (colors and transparency)

For example, this is the image saved as `png`:
![output](https://user-images.githubusercontent.com/24387035/158062681-4e0b837b-de8b-446a-a1b2-98d78e94d37d.png)

### What actually happened?
The `gif` output has a striped pattern and does not have transparency anymore.

This is the same image as before, but saved as `gif`:
![output](https://user-images.githubusercontent.com/24387035/158062741-6cddbac3-ee05-43d4-96d5-a480eb681767.gif)

### What are your OS, Python and Pillow versions?

- OS: `Ubuntu 18.04`
- Python: `3.9.10`
- Pillow: `9.0.1`

You can also access the code here:
https://github.com/elton-okawa/pillow-gif-gradient-issue

```python
from PIL import Image, ImageDraw
from pathlib import Path

def main():
  size = 256
  img = Image.new('RGBA', (size, size))

  # Draw gradient
  draw = ImageDraw.Draw(img)
  colors = _interpolate(
    start=(255, 255, 255, 255),
    end=(0, 0, 0, 0),
    interval=size,
  )
  for col, color in zip(range(256), colors):
    draw.line((0, col, size, col), color)

  # Save as png
  img.save(
    fp=Path("./output.png"),
    format='png',
  )

  # Save as gif
  img.save(
    fp=Path("./output.gif"),
    format='gif',
    save_all=True,
    duration=5,
    optimize=False,
    loop=0,
  )


def _interpolate(start, end, interval):
  delta = [0 if interval == 0 else (e - s) / interval for s, e in zip(start, end)]

  values = []
  for i in range(interval):
    values.append(tuple(round(s + det * i) for s, det in zip(start, delta)))

  return values

main()
```

**Comment by radarhere** [comment]
Hi. You're trying to save 255 different transparency values to a GIF. This is not possible. The GIF format only allows one color to be completely transparent. See https://stackoverflow.com/a/1952389/4093019 or https://community.adobe.com/t5/animate-discussions/export-an-animated-gif-to-be-transparent-specific-issue-below/m-p/10773454#M199364 for supporting answers.

If I change your code to
```python
img = Image.new('RGB', (size, size))

  # Draw gradient
  draw = ImageDraw.Draw(img)
  colors = _interpolate(
    start=(255, 255, 255),
    end=(0, 0, 0),
    interval=size,
  )
```
then the GIF and the PNG output match.

**Comment by fayzullox07** [comment]
bitch

**Comment by elton-okawa** [comment]
@radarhere yes, thanks for the detailed answer!
