### ISSUE TITLE
Black-and-white PDF export regression in Pillow 8.3.x

### ISSUE THREAD

**Issue by za3k** [python-pillow/Pillow#6149]
Black-and-white image export to PDF seems to blanket fail starting in PIL/Pillow 8.3.x. The version was reported to me by a user--I have not verified the switchover point.

Below is code which causes PDF generation to succeed (print a rectangle) in greyscale, but fails for black-and-white.

```python
#!/usr/bin/env python3
import PIL, PIL.Image, PIL.ImageDraw

# Works in 8.2.0, fails in 8.3.0
IMAGE_MODE="1"
WHITE=1
BLACK=0

# Works in 8.2.0 and 8.3.0
#IMAGE_MODE="L"
#WHITE=255
#BLACK=0

page = PIL.Image.new(mode=IMAGE_MODE, size=(200, 200), color=WHITE)
page_draw = PIL.ImageDraw.Draw(page)
page_draw.rectangle(((0,0), (99, 99)), outline=BLACK, fill=WHITE, width=1) # Rectangle for debugging print cutoff, and to look nice.

with open("test.pdf", "wb") as f:
    page.save(f, format="pdf")
```

Reproduced using two different Linux versions in Python 3.x, and multiple Pillow versions.
This bug report was verified with Python 3.10.2 and Pillow 9.0.1

Originally reported as: https://github.com/za3k/qr-backup/issues/24

**Comment by za3k** [comment]
[fail.pdf](https://github.com/python-pillow/Pillow/files/8319721/fail.pdf)
[success.pdf](https://github.com/python-pillow/Pillow/files/8319722/success.pdf)

**Comment by radarhere** [comment]
When I run your code, and when I open fail.pdf, in macOS Preview, I see a black rectangle on a white background no problem.

> almost every other PDF viewer

Could you provide a specific example?

**Comment by za3k** [comment]
From the original reporter: Moon Reader on Android; Firefox, Libreoffice Draw, and Evince

From me: xpdf on Linux

**Comment by radarhere** [comment]
I've created PR #6151 to resolve this.
