### ISSUE TITLE
PIL.Image.save ignores parameters

### ISSUE THREAD

**Issue by freshmre** [python-pillow/Pillow#6156]
### What did you do?
I want to read then write a png image while preserving its ```Image.info``` dictionary items like ```gamma``` using ```PIL.Image.save```.

### What did you expect to happen?
New image to have same ```Image.info``` value as original image.
As documented in [Image.save](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) and [PNG file format](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png)

### What actually happened?
New image has empty ```Image.info``` dictionary.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04
* Python: 3.8.10
* Pillow: 9.0.1

```python
from PIL import Image
img = Image.open("sample.png") # Sample image provided below code block
info = img.info
img.save("output.png", **info)

output_info = Image.open("output.png").info
print(info)                  # {'gamma': 2147.48365}
print(output_info)           # {}
print(output_info == info)   # False, should be True
```
[sample.zip](https://github.com/python-pillow/Pillow/files/8344263/sample.zip)

**Comment by radarhere** [comment]
Your expectation is not actually what is documented. `gamma` is documented under the properties present after `open()`, not the options that can be passed to `save()`.

<img width="812" alt="gamma" src="https://user-images.githubusercontent.com/3112309/160083634-8dcec66d-3da2-498e-9f6f-60afaa9badc7.png">

**Comment by radarhere** [comment]
Here's what I've put together.
```python
from PIL import Image, PngImagePlugin
from PIL import _binary
img = Image.open("sample.png")
info = img.info
pnginfo = PngImagePlugin.PngInfo()
pnginfo.add(b"gAMA", _binary.o32be(int(info["gamma"] * 100000)))
img.save("output.png", pnginfo=pnginfo)

output_info = Image.open("output.png").info
print(info)                  # {'gamma': 2147.48365}
print(output_info)           # {'gamma': 2147.48365}
print(output_info == info)   # True
```

**Comment by freshmre** [comment]
Funny, it's the same way I was using in my code which I felt was error prone
```python
from PIL import Image
from PIL.PngImagePlugin import PngInfo

img = Image.open("sample.png")
info = img.info

metadata = PngInfo()
cid = bytes("gAMA", "ascii")
data = round(info["gamma"] * 100_000).to_bytes(4, 'big')
metadata.add(cid, data)
img.save("output.png", pnginfo=metadata)
```
I was expecting something easier as PIL supports reading gamma I thought writing might be just as simple.
Thank you for your time.
