### ISSUE TITLE
'float' object cannot be interpreted as an integer exception when applying point transforms

### ISSUE THREAD

**Issue by alexvalentinm** [python-pillow/Pillow#6187]
### What did you do?
Following the docs to apply point transforms:
https://pillow.readthedocs.io/en/stable/handbook/tutorial.html?highlight=.point(#applying-point-transforms

### What actually happened?
The following exception was raised: `'float' object cannot be interpreted as an integer`.

### What are your OS, Python and Pillow versions?

* OS: Windows 11 Pro (22000.556)
* Python: 3.10.4 (packaged by conda-forge)
* Pillow: 9.1.0

Code to reproduce
```python
from PIL import Image

image = Image.open(image_path).convert('RGBA')
alpha_channel = image.getchannel('A')
image.putalpha(alpha_channel.point(lambda x: x * 0.5))
```

With Pillow 8.3.2 and Python 3.8, the above code worked well.

Edit: I've tested Pillow 9.1.0 with Python 3.9.12 and it works fine, so it seems to be an issue related to Python 3.10.x

**Comment by radarhere** [comment]
Thanks. This would be because of https://docs.python.org/3/c-api/long.html#c.PyLong_AsLong
> Changed in version 3.10: This function will no longer use `__int__()`.

I've created PR #6188 to resolve this.

**Comment by alexvalentinm** [comment]
Great, it should do the trick. Thanks!
