### ISSUE TITLE
`IFDRational` is not JSON serializable

### ISSUE THREAD

**Issue by SaulAryehKohn** [python-pillow/Pillow#6199]
It would be very useful to be able to save EXIF information from `Image._getexif()` as JSONs (my present reason is to be able to test extracted values against JSON snapshots of those values)

### What did you do?
```python
import json
from PIL import Image
import PIL.ExifTags

img = Image.open("test_image.jpeg")
dct = {
        PIL.ExifTags.TAGS[k]: v
        for k, v in img._getexif().items()
        if k in PIL.ExifTags.TAGS
    }
outs = json.dumps(dct)
```

### What did you expect to happen?
`outs` would be equal to the JSONified version of `dct`.

### What actually happened?
```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "[/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/__init__.py]()", line 231, in dumps
    return _default_encoder.encode(obj)
  File "[/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py]()", line 199, in encode
    chunks = self.iterencode(o, _one_shot=True)
  File "[/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py]()", line 257, in iterencode
    return _iterencode(o, 0)
  File "[/Library/Frameworks/Python.framework/Versions/3.8/lib/python3.8/json/encoder.py]()", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type IFDRational is not JSON serializable
```

### What are your OS, Python and Pillow versions?

* OS: Mac OS BigSur Version 11.6.4
* Python: 3.8.9
* Pillow: 8.3.1

[Test image attached](https://user-images.githubusercontent.com/7569274/162777848-6036f5e0-4c7e-42a4-b25b-f2e5c9f560de.jpeg)

**Comment by radarhere** [comment]
Hi. Investigating, I don't think this is possible without changing `IFDRational` to subclass from something other than just `Rational`.

https://docs.python.org/3.10/library/json.html#json.dumps
> Serialize obj to a JSON formatted str using this [conversion table](https://docs.python.org/3.10/library/json.html#py-to-json-table).

https://docs.python.org/3.10/library/json.html#py-to-json-table
<img width="423" alt="conversion" src="https://user-images.githubusercontent.com/3112309/162837668-1a0a7de3-36dd-41ab-a499-80aea526f3dd.png">
> To extend this to recognize other objects, subclass and implement a default() method with another method that returns a serializable object for o if possible, otherwise it should call the superclass implementation (to raise TypeError).

Nothing about adding a method to an object to allow it to be understood.

So instead, I modified your code to cast `IFDRational` to a `float`.

```python
import json
from PIL import Image, TiffImagePlugin
import PIL.ExifTags

img = Image.open("test_image.jpeg")
dct = {
        PIL.ExifTags.TAGS[k]: float(v) if isinstance(v, TiffImagePlugin.IFDRational) else v
        for k, v in img._getexif().items()
        if k in PIL.ExifTags.TAGS
    }
outs = json.dumps(dct)
```
gives
```
TypeError: Object of type bytes is not JSON serializable
```

So it seems your problem is broader than just `IFDRational`.

Here is code that I've put together that runs without errors.
```python
import json
from PIL import Image, TiffImagePlugin
import PIL.ExifTags

img = Image.open("test_image.jpeg")
dct = {}
for k, v in img._getexif().items():
	if k in PIL.ExifTags.TAGS:
		if isinstance(v, TiffImagePlugin.IFDRational):
			v = float(v)
		elif isinstance(v, tuple):
			v = tuple(float(t) if isinstance(t, TiffImagePlugin.IFDRational) else t for t in v)
		elif isinstance(v, bytes):
			v = v.decode(errors="replace")
		dct[PIL.ExifTags.TAGS[k]] = v
outs = json.dumps(dct)
```

**Comment by radarhere** [comment]
@SaulAryehKohn did that answer your question? I hope that by demonstrating that your problem also applies to bytes, I've shown that we can't just cleanly patch Pillow to solve this scenario.

**Comment by SaulAryehKohn** [comment]
Yes, thank you @radarhere! That makes sense to me.

**Comment by maxwoe** [comment]
The above code does not handle dict entries. Here is an improved version the uses recursion vor casting items.

``` python
import json
from PIL import Image, TiffImagePlugin
import PIL.ExifTags

img = Image.open("test_image.jpeg")
dct = {}

def cast(v):
    if isinstance(v, TiffImagePlugin.IFDRational):
        return float(v)
    elif isinstance(v, tuple):
        for item in v:
            cast(item)
    elif isinstance(v, bytes):
        return v.decode(errors="replace")
    elif isinstance(v, dict):
        for kk, vv in v.items():
            v[kk] = cast(vv)
        return v
    else: return v

for k, v in img._getexif().items():
    if k in PIL.ExifTags.TAGS:
        v = cast(v)
        dct[PIL.ExifTags.TAGS[k]] = v
outs = json.dumps(dct)
```
