### ISSUE TITLE
Backward seek on closed `GifImageFile` breaks expected behaviour

### ISSUE THREAD

**Issue by AnonymouX47** [python-pillow/Pillow#6205]
### What did you do?
- Opened a GIF image from a file
- Seeked forward
- Closed the image
- Tried to seek backward
- Tried to load the image

### What did you expect to happen?
After the image was closed, I expected all operations that involve loading or mutation to raise `ValueError: Operation on closed image`.
I tested `WebPImageFile` and it behaved as expected.

SInce `PIL.Image.Image` provides no public interface to determine if an image is closed or not, the next point of call would be trying an operation on the image to see if a specific exception is raised. The inconsistency shown above breaks that behaviour.

### What actually happened?
Operations on the closed image don't raise the expected exception after seeking backward.

### What are your OS, Python and Pillow versions?

* OS: Pop OS 21.10 (Linux)
* Python: 3.9.10
* Pillow: 9.1.0

```python
from PIL import Image

img = Image.open("tests/images/lion.gif")
img.seek(4)  # Ok
img.close()  # Ok
img.load()  # Ok; ValueError: Operation on closed image
img.seek(5)  # Ok; ValueError: Operation on closed image
img.seek(0)  # Not Ok; AttributeError: 'NoneType' object has no attribute 'seek'
img.tell()  # Not Ok; -1
img.seek(5)  # Not Ok; AttributeError: 'NoneType' object has no attribute 'seek'
img.load()  # Not Ok; AttributeError: 'NoneType' object has no attribute 'read'
```

**Comment by AnonymouX47** [comment]
I don't think this is an issue that could come up often but there's also the possibility of it coming up.

**Comment by radarhere** [comment]
I've created PR #6213 to resolve this.

**Comment by AnonymouX47** [comment]
Thanks 😃
