### ISSUE TITLE
How does Pillow handle jaggies after compositing images?

### ISSUE THREAD

**Issue by zhenzi0322** [python-pillow/Pillow#6226]
How does pillow handle jaggies after compositing images?

**Comment by radarhere** [comment]
An image's [`paste()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste) method has a `mask` parameter. If the overlaid image has translucent edge pixels, that could be used to apply partial transparency from them.

**Comment by radarhere** [comment]
@zhenzi0322 did that answer your question? If not, it would be helpful if you could provide a self-contained example showing the specific situation that you're talking about.
