### ISSUE TITLE
Build doesn't detect/support libopenjpeg v.2.1.3

### ISSUE THREAD

**Issue by ccazabon** [python-pillow/Pillow#623]
The docs for Pillow v.2.4.0 say "Pillow 2.4 requires openjpeg 2.0.0", but the build process says OPENJPEG/JPEG2000 support is not available when libopenjpeg v.2.1.3 is installed.  I'm not sure if it's _supposed_ to support newer 2.x versions or not, but it appears not to.

This happens on the new Ubuntu "Trusty Tahr" 2014.04, for which v.2.1.3 is the only version of libopenjpeg shipped.  I have the main package, the -dev package, and the openjpeg-tools package installed.

P.S.  Thanks for maintaining Pillow!

**Comment by calvinbutcher** [comment]
We're trying to build a Loris image server docker image running with Grok 1.0, an optimised version of OpenJPEG 2.1. 

I've come across the issues mentioned by @manisandro. 

Currently I'm having to template the Jpeg2KDecode.c and Jpeg2KEncode.c files with the correct 3 parameter call to OpenJPEG 2.1/Grok.

However, the docker image build then fails on the tests.
