### ISSUE TITLE
ZeroDivisionError is raised when the `maxval` of the PPM metadata is 0

### ISSUE THREAD

**Issue by ks888** [python-pillow/Pillow#6240]
Hi,

Thank you for developing and maintaining this project.

Recently I am fuzzing this library for fun, and I found the test case which raises ZeroDivisionError.

### What did you do?

```python3
from PIL import Image
import io

# Load hopper.ppm. Assumes the current directory is the root of this repository.
with open('Tests/images/hopper.ppm', 'rb') as f:
    data = bytearray(f.read())

# Sets the maximum value 0
data[49] = 0x30
data[50] = 0x30
data[51] = 0x30

# Raises ZeroDivisionError
with Image.open(io.BytesIO(data)) as img:
    img.load()
```

### What did you expect to happen?

The file is broken, so some error should be raised. But `ZeroDivisionError` may be a little confusing.

### What actually happened?

```
Traceback (most recent call last):
  File "issue1.py", line 15, in <module>
    img.load()
  File "/usr/local/lib/python3.8/site-packages/PIL/ImageFile.py", line 234, in load
    err_code = decoder.decode(b"")[1]
  File "/usr/local/lib/python3.8/site-packages/PIL/PpmImagePlugin.py", line 152, in decode
    value = min(out_max, round(value / maxval * out_max))
ZeroDivisionError: division by zero
```

### What are your OS, Python and Pillow versions?

* OS: Debian GNU/Linux 11 (bullseye)
* Python: 3.8.13
* Pillow: 9.1.0

I am happy to create the pull request to fix this issue, but I am not very sure which exception should be raised here.

**Comment by radarhere** [comment]
http://netpbm.sourceforge.net/doc/ppm.html states that maxval "Must be less than 65536 and more than zero", so yes, I agree it is broken.

I've created #6242 to raise a "Invalid maxval" ValueError.

**Comment by ks888** [comment]
Thank you. LGTM!
