### ISSUE TITLE
Read GIF into BytesIO

### ISSUE THREAD

**Issue by devfox-se** [python-pillow/Pillow#6245]
### What did you do?

I am trying to read a gif file into memory to transfer to a different component. For testing purposes I prepared a snippet that reads it to buffer and dumps content to a file

### What did you expect to happen?

GIF file has the same size and duration as the original image

### What actually happened?

Output file is enormously large (~83MB) where the original is only 2.7MB
It contains lots of frames where original only has 48 frames

### What are your OS, Python and Pillow versions?

* OS: MacOS
* Python: 3.9.12
* Pillow: 9.1.0

my test gif can be downloaded form here:
```
https://mir-s3-cdn-cf.behance.net/project_modules/max_1200/5eeea355389655.59822ff824b72.gif
```

```python
from io import BytesIO

from PIL import Image, ImageSequence

path_to_img = '/Users/mac_user/Downloads/5eeea355389655.59822ff824b72.gif'
gif_image = Image.open(path_to_img)

frames = []
for frame in ImageSequence.Iterator(gif_image):
    frames.append(frame)

img_container = BytesIO()
frames[0].save(
    img_container,
    format='GIF',
    save_all=True,
    append_images=frames[1:],
    duration=gif_image.info.get("duration"),
    loop=0,
    optimize=False
)

img_container.seek(0)
with open('test.gif', 'wb') as F:
    F.write(img_container.read())
```

Is there something wrong with my snippet? how can this be improved?

**Comment by radarhere** [comment]
Instead of
```python
frames = []
for frame in ImageSequence.Iterator(gif_image):
    frames.append(frame)
```
try
```python
frames = []
for frame in ImageSequence.Iterator(gif_image):
    frames.append(frame.copy())
```

`ImageSequence.Iterator` is just seeking forward to the next frame. It is still returning the original image object. So when you are appending this to a list, you're creating a list of 48 images, each with 48 frames, leading to your output image with 2304 frames.

Instead, if you call `.copy()` on `frame`, then you are only appending a single frame image.

**Comment by devfox-se** [comment]
Thank you for your quick reply! I confirm doing `.copy()` fixes the issue!
Closing this issue.

**Comment by radarhere** [comment]
Fyi, you may also be interested in `ImageSequence.all_frames` - https://pillow.readthedocs.io/en/latest/reference/ImageSequence.html#PIL.ImageSequence.all_frames

With that, I could change your code from
```python
frames = []
for frame in ImageSequence.Iterator(gif_image):
    frames.append(frame)
```
to
```python
frames = ImageSequence.all_frames(gif_image)
```
