### ISSUE TITLE
Drawing text with certain diacritic characters

### ISSUE THREAD

**Issue by kodymoodley** [python-pillow/Pillow#6258]
Hi, thanks for the nice imaging library!

I have problems drawing certain diacritic characters in transliterated Sanskrit. For example, the dots under the 'r', 's' and 'n' characters in the word `Kṛṣṇa` do not render when using the `.text()` method for the `ImageDraw.Draw` object.

Here is my minimal code to reproduce the problem:

```python
from PIL import Image, ImageFont, ImageDraw 
      
image = Image.open('circle_frame.png') 
draw = ImageDraw.Draw(image) 
font = ImageFont.truetype('arial.ttf', 20) 
text = 'Kṛṣṇa'
draw.text((5, 5), text, fill ="red", font = font, align ="right") 
image.show() 
```

Here is the `circle_frame.png` and `arial.ttf` test files I am using (you can obviously replace them with alternatives if needed):

[testdata.zip](https://github.com/python-pillow/Pillow/files/8604321/testdata.zip)

Here is output I am getting:

![output](https://user-images.githubusercontent.com/13569029/166279428-e35e7ebf-b904-445f-aa9b-8ecb9b4442c0.png)

**Comment by nulano** [comment]
Two things to check:

Does Arial support these characters?

Do you use basic or Raqm layout? The default is Raqm, but it might not be available for you. You can check by running `python -m PIL` (at the top of output).

**Comment by nulano** [comment]
> Does Arial support these characters?

Testing with your `arial.ttf` on my system with Raqm enabled the characters show up correctly for me, so I suspect you are missing Raqm. What is your operating system and how did you install Pillow?

**Comment by kodymoodley** [comment]
Hi, I am on MacOS Monterey v12.3.1 (Chip: Apple M1 Pro).

I ran `python -m PIL` as you indicated and I indeed get the message that `*** RAQM (Bidirectional Text) support not installed` and `*** LIBIMAGEQUANT (Quantization method) support not installed`. I do not remember installing PIL explicitly. I think it has been installed as a dependency of [word_cloud](https://github.com/amueller/word_cloud).

I would be surprised if `arial.ttf` did not support these characters but I will check.

**Comment by nulano** [comment]
> I would be surprised if arial.ttf did not support these characters but I will check.

The file you provided worked for me, so it does seem to support them. You just need to get Raqm to be detected.

**Comment by nulano** [comment]
Since you are on macOS, you might want to take a look at #6182 (you can test the fix by installing from main).

Alternativaly, you can try to replicate https://github.com/python-pillow/pillow-wheels/pull/281 by running these two commands: 
https://github.com/python-pillow/pillow-wheels/pull/281/files#diff-f664e29ba13a6135bb7bf8f7e4c51e380b0cd6266be561c046467e0accdcdaa5R155-R156

**Comment by kodymoodley** [comment]
Okay, thanks - do you have a link to another issue or resource about how to install Raqm? I found this [repo](https://github.com/HOST-Oman/libraqm). Can I install it from there?

**Comment by kodymoodley** [comment]
These two lines worked for me:

1. `brew install fribidi`
2. `ln -s /usr/local/lib/libfribidi.dylib libfribidi.dylib`

This is the output of `python -m PIL` after executing these two commands:

```
--- PIL CORE support ok, compiled for 9.1.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.12.0
--- LITTLECMS2 support ok, loaded 2.13.1
--- WEBP support ok, loaded 1.2.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 2.1.3
--- OPENJPEG (JPEG2000) support ok, loaded 2.4.0
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.11
--- LIBTIFF support ok, loaded 4.2.0
--- RAQM (Bidirectional Text) support ok, loaded 0.9.0, fribidi 1.0.12, harfbuzz 4.2.0
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
```

So Raqm is installed! Thank you very much for the tips!
