### ISSUE TITLE
GIF durations should be preserved from frame info

### ISSUE THREAD

**Issue by raygard** [python-pillow/Pillow#6259]
### What did you do?

Copied an animated GIF:

```python
with Image.open('Tazspin.gif') as im:
    im.save(f'new.gif', save_all=True, optimize=True, interlace=0)
```

### What did you expect to happen?

Hoped the copy would be something like the original Tazspin.gif:

![Tazspin](https://user-images.githubusercontent.com/24783736/166316458-3e8e3bfc-c5ac-4e88-86b2-7dd23c2e7371.gif)

### What actually happened?

Got this:

![new](https://user-images.githubusercontent.com/24783736/166316569-938b85af-8bd5-4bc4-b092-627a1d5b1bae.gif)

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.10.4
* Pillow: 9.1.0 (slightly modified but you'll get a very similar result with stock 9.1.0)

#### Discussion:

Duration has been a problem in the past. I think that in the absence of a `duration=` arg to `.save()`, the durations ("delay time" in the GIF spec) from the individual frames should be preserved in the output.

Maybe something like this: in `_write_multiple_frames()` (in `GifImagePlugin.py`), delete the line

```python
    duration = im.encoderinfo.get("duration", im.info.get("duration"))
```

Then modify the code that sets `im.encoderinfo` from `im_frame.info`:

```python
                for k, v in im_frame.info.items():
                    if k == "transparency" or k == "duration":
                        continue
                    im.encoderinfo.setdefault(k, v)
```

(Note I am including code changed in PR #6176. I am not making a PR out of this because I don't know how to deal with such conflicts and because I am not sure if this is a good fix. Need input from @radarhere.)

And then before the line `if isinstance(duration...`, insert:

```python
            if "duration" in im_frame.info:
                encoderinfo.setdefault("duration", im_frame.info["duration"])
            duration = encoderinfo.get("duration")
```

This seems to give me the desired result:

![new_910_fix_d1](https://user-images.githubusercontent.com/24783736/166322842-d604bcd2-0171-41a9-baa2-0d635298ad06.gif)

I hope it doesn't break anything.

**Comment by radarhere** [comment]
It's fine to create conflicting PRs - it just means that whichever one doesn't get merged in first needs to be updated later. And the test suite is what is there to prevent PRs from breaking things.

I've created PR #6265, similar to your suggestion.
