### ISSUE TITLE
Palette doesn't work converting RGB to P

### ISSUE THREAD

**Issue by Lsz-20** [python-pillow/Pillow#6263]
I'm convert a RGB image to P image with this code:
```python
paletts = target.getpalette()
img = img.convert("P", palette=paletts)
```
the paletts is the palette i want to use,but the wrong mapping result is obtained (Eg: in paletts [0,0,0] is 0,[128,0,0] is 1, but the result is 0 and 12)
Looking forward to your reply.

**Comment by radarhere** [comment]
Could you make your example self-contained? So could you show the values of `img` and `target`, attaching whatever images are necessary?

**Comment by Lsz-20** [comment]
> Could you make your example self-contained? So could you show the values of `img` and `target`, attaching whatever images are necessary?

Here are the messages：
target ("P")：
![image](https://user-images.githubusercontent.com/60343452/166418201-84050c34-0d22-45e6-9cef-12a279051cf5.png)
And the np.array(target):
![image](https://user-images.githubusercontent.com/60343452/166418412-37edf75b-3256-483c-a164-37f1d4e91a82.png)


img ("RGB"):
![image](https://user-images.githubusercontent.com/60343452/166417986-dacccace-96c2-4b10-a5b6-07b87d8de6d1.png)

And the np.array(img)
![image](https://user-images.githubusercontent.com/60343452/166417821-9577b2d2-d9f5-44dc-97af-546aa79b570a.png)

img with target palette:
![Uploading image.png…]()
which seems palette didn't work

**Comment by radarhere** [comment]
Could you actually upload 0033.png and 33.png?

**Comment by radarhere** [comment]
Ok, I've put together an example of what you are describing.

```python
from PIL import Image, ImagePalette

img = Image.new("RGB", (1, 2), (0, 0, 0))
img.putpixel((0, 1), (128, 0, 0))

paletts = ImagePalette.ImagePalette("RGB", (0, 0, 0, 128, 0, 0))
print("Colors:", paletts.colors)

img = img.convert("P", palette=paletts)
print(img.getpixel((0, 0)), img.getpixel((0, 1)))  # 0 13
```

**Comment by Lsz-20** [comment]
Here are the examples:
[example.zip](https://github.com/python-pillow/Pillow/files/8609491/example.zip)

**Comment by radarhere** [comment]
The `palette` argument for `convert()` is actually not what you think it is.

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert
> palette – Palette to use when converting from mode “RGB” to “P”. Available palettes are [Palette.WEB](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Palette.WEB) or [Palette.ADAPTIVE](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Palette.ADAPTIVE).

Instead, you can use `quantize()` - https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize

```python
from PIL import Image

paletts = Image.open("0033.png")
img = Image.open("33.png")

img = img.quantize(palette=paletts)
```

Here is a demonstration that it works.
```python
from PIL import Image

paletts = Image.open("0033.png")
assert paletts.palette.colors[(0, 0, 0)] == 0
assert paletts.palette.colors[(128, 0, 0)] == 1

img = Image.open("33.png")
assert img.getpixel((0, 0)) == (0, 0, 0)
assert img.getpixel((1, 218)) == (128, 0, 0)

img = img.quantize(palette=paletts)
assert img.getpixel((0, 0)) == 0
assert img.getpixel((1, 218)) == 1
```

**Comment by Lsz-20** [comment]
Thanks for your response, following your suggestions to get satisfactory results.
