### ISSUE TITLE
PIL.UnidentifiedImageError on TIFF file (regression from 9.0.1 to 9.1.0)

### ISSUE THREAD

**Issue by kevinmehall** [python-pillow/Pillow#6266]
### What did you do?

The attached TIFF file, which was generated by [Hugin](http://hugin.sourceforge.net/), fails to open in Pillow 9.1.0. It works fine in 9.0.1 and prior versions.

[example.zip](https://github.com/python-pillow/Pillow/files/8612938/example.zip)

### What did you expect to happen?

With 9.0.1:
```pycon
>>> import PIL
>>> PIL.__version__
'9.0.1'
>>> from PIL import Image
>>> Image.open('eqr.tiff')
<PIL.TiffImagePlugin.TiffImageFile image mode=RGBA size=512x256 at 0x1073FC4C0>
```

### What actually happened?

With 9.1.0:
```pycon
>>> import PIL
>>> PIL.__version__
'9.1.0'
>>> from PIL import Image
>>> Image.open('eqr.tiff')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/private/tmp/test/lib/python3.9/site-packages/PIL/Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'eqr.tiff'
```

### What are your OS, Python and Pillow versions?

* OS: Tested on macOS and Linux
* Python: Tested on 3.9.10 and 3.9.12
* Pillow: 9.1.0

**Comment by kevinmehall** [comment]
`git bisect` points to bb5a090f60ed08941e5bdd7077f9a53caec99b57

**Comment by radarhere** [comment]
If I run [`tiffinfo`](https://linux.die.net/man/1/tiffinfo) on your file, I receive a warning

> TIFFReadDirectory: Warning, Sum of Photometric type-related color channels and ExtraSamples doesn't match SamplesPerPixel. Defining non-color channels as ExtraSamples..

Just as an explanation, Pillow is failing to read the image for the same reason - the SampesPerPixel values doesn't match the rest of the data.

**Comment by radarhere** [comment]
Is the image that you've attached one that could be included in our test suite, and distributed under the Pillow license?

**Comment by kevinmehall** [comment]
> Is the image that you've attached one that could be included in our test suite, and distributed under the Pillow license?

Yes

**Comment by radarhere** [comment]
Thanks. I've added it to the PR.

**Comment by kevinmehall** [comment]
By the way, I got the `ExtraSamples` metadata that was causing this fixed on the generating side in libpano13 as well:
https://groups.google.com/g/hugin-ptx/c/WAfaYghJLW8

**Comment by radarhere** [comment]
Nice work
