### ISSUE TITLE
ImageDraw.rectangle() xy format issue

### ISSUE THREAD

**Issue by Foundsheep** [python-pillow/Pillow#6267]
### What did you do?

I tried to draw bboxes on an image and it worked well with a ndarray with several bboxes(shaping (N, 4)), but when it came to only a ndarray containing only one bbox(shaping (1, 4)) it gave me an error : typeerror: coordinate list must contain exactly 2 coordinates

### What did you expect to happen?
My original code is written below
```python
def visualize_bbox(sample):
    from PIL import Image, ImageDraw
    img = sample['image']
    bboxes = sample['bboxes']

    img_pil = Image.fromarray(img)
    draw = ImageDraw.Draw(img_pil)
    for bbox in bboxes:
        draw.rectangle(bbox, outline=(225,0,0), width=2)
    return img_pil
```
And I changed my code to below one and it is now working.
However, when I read the documentation I thought there shouldn't be any issue with the code above, since it is still giving a [x_0, y_0, x_1, y_1] format.

```python
def visualize_bbox(sample):
    from PIL import Image, ImageDraw
    img = sample['image']
    bboxes = sample['bboxes']

    img_pil = Image.fromarray(img)
    draw = ImageDraw.Draw(img_pil)
    if len(bboxes) == 1: 
        for bbox in bboxes:
            draw.rectangle(((bbox[0], bbox[1]), (bbox[2], bbox[3])), outline=(225,0,0), width=2)
    else:
        for bbox in bboxes:
            draw.rectangle(bbox, outline=(225,0,0), width=2)
    return img_pil
```

### What are your OS, Python and Pillow versions?

* OS: Colab
* Python: 
* Pillow: 7.1.2

**Comment by radarhere** [comment]
Could you provide code showing the exact value of `sample`?

**Comment by Foundsheep** [comment]
Hi Andrew,

Thanks for a quick reply.

Basically, sample values are in the format below

{'bboxes': array([[707, 179, 754, 202]]), 'image': array([[[117, 117, 117],
[117, 117, 117], [117, 117, 117], ..., [117, 117, 117], [117, 117, 117],
[117, 117, 117]], [[117, 117, 117], [117, 117, 117], [117, 117, 117], ...,
[116, 116, 116], [116, 116, 116], [117, 117, 117]], [[117, 117, 117], [117,
117, 117], [117, 117, 117], ..., [117, 117, 117], [117, 117, 117], [117,
117, 117]], ..., [[ 70, 70, 60], [ 70, 70, 60], [ 70, 70, 60], ..., [ 72,
72, 60], [ 73, 73, 61], [ 73, 73, 61]], [[ 71, 71, 61], [ 71, 71, 61], [
71, 71, 61], ..., [ 71, 71, 59], [ 73, 73, 61], [ 73, 73, 61]], [[ 70, 70,
60], [ 70, 70, 60], [ 70, 70, 60], ..., [ 72, 72, 60], [ 73, 73, 61], [ 73,
73, 61]]], dtype=uint8), 'labels': array(['Car'], dtype=object)}

So the thing making this issue, boxes is a 2-dimensional ndarray, and when
it has only one bbox, the array is still in the shape of 2-dimension.

**Comment by radarhere** [comment]
I'm unable to replicate your situation where there is an error that only occurs when "bboxes" has length 1, but not otherwise.

However, I suspect your problem is because "bboxes" is a numpy array. If you change it to a regular Python array or tuple, I expect it to work.

**Comment by Foundsheep** [comment]
Thanks for the reply.

I'm fine with the current situation since I've found a solution to make it
work as I wanted anyway.

Thanks :)
