### ISSUE TITLE
imagemagick downsamples pillow-created PDFs with resolution parameter

### ISSUE THREAD

**Issue by za3k** [python-pillow/Pillow#6277]
I created a sample image using Pillow, with

```python
pages[0].save(tmp_pdf, format="pdf", save_all=True, append_images=pages[1:], resolution=dpi, producer="qr-backup", title=f"qr-backup paper backup of {restore_file} with sha256 {sha256sum} and length {original_len}", creationDate=backup_date, modDate=backup_date)
```
Here dpi is 300.

Importing into ImageMagick via the C API, or running commands like `convert failure2.pdf output.png`, downsizes the image significantly, because ImageMagick [resamples the raster page](https://github.com/ImageMagick/ImageMagick/discussions/3983#discussioncomment-1047961) at 72dpi, the *page* resolution (here just a default).

This can be improved by setting the page resolution of the PDF. Given that the output of PIL is always an image-only file, and I believe even an image-per-page file with the same DPI for each image, I think it would make sense to output a "resolution 300" PDF in cases like this instead.

The reason to care and make things work out of the box in a uniform way, is that like PIL, ImageMagick is often used in projects to "just read in image". I'm running into a case (`zbar`, a QR reader) where I've fed the program a PDF as an image, but an author of zbar wasn't even aware zbar had PDF support. In other words, application layer programmers are unlikely to fix anything specific to PDFs.

---
How I checked out what's going on

poppler-utils's `pdfimages` confirms 301x300 ppi IMAGE resolution (okay, *something* seems off-by-one, but close enough):
```
page   num  type   width height color comp bpc  enc interp  object ID x-ppi y-ppi size ratio
--------------------------------------------------------------------------------------------
   1     0 image    2083  2500  gray    1   1  image  no         1  0   301   300 10.1M 1621%
```

ImageMagick reports the PAGE resolution (which it uses, it does not extract the images) is 72x72:
```
~/zbar $ magick failing2.pdf -verbose info: | grep Resolution
  Resolution: 72x72
```

Examining the PDF file, ImageMagick's value looks maybe correct, with my limited knowledge of postscript. I don't see a 72 or 300 anywhere, and 72pt is a common default. Not sure how the ppi/dpi is determined by poppler OTOH, so I'm not sure where that value comes from.

**Comment by radarhere** [comment]
Bear with me if you think this is a silly question - what leads you to the conclusion that PDFs have a "page resolution", and that ImageMagick is not just applying a default resolution of 72 DPI to all PDFs?

**Comment by za3k** [comment]
Not at all a silly question. In fact I think I'm likely [wrong](https://legacy.imagemagick.org/discourse-server/viewtopic.php?t=16598#:~:text=By%20default%2C%20ImageMagick%20reads%20a,image%2C%20which%20is%20very%20annoying.) and there is no way to embed a resolution in a PDF.

The reasons I thought this:
1. The output of the `magick -verbose info:` command above includes the `Resolution` number. Based on everything else in the command looking like a 'property' of the file, I thought it was one. This line is also why I decided the "page resolution" was in PPI and not total pixels, too.
2. I found some stackoverflow post telling me to "check the solution" using the above command, which I suspect was itself mistaken now. I can't find the post again.
3. The explanation in the linked ImageMagick post above, as well as several others I found, as to the page resolution. However these posts don't explicitly say you can change the page solution except with commands like `-density 300` or `-resample`.
4. A vague memory of how to set it in postscript. Google doesn't immediately support this one, but I haven't been able to find things on Google for 5-10 years, frankly, so that's a null result.

**Comment by radarhere** [comment]
On the general topic of PDF resolution, https://answers.acrobatusers.com/how-check-resolution-received-pdf-file-q211762.aspx

> There is no "resolution of a PDF file". Anything that is text or vector graphic will be rendered at the desired output resolution of your output device.

As for ImageMagick dealing with PDF resolution, https://stackoverflow.com/questions/50006770/how-to-get-dpi-of-a-pdf-file/50009180#comment87030801_50006770
> PDF files have no density. You have to assign it a density when reading it. It only has a physical print size in inches. It renders to some pixel dimensions using the default density of 72 dpi or whatever density you assign. Your command is likely giving you 72 dpi for both images, since that is the assumed default.

https://github.com/ImageMagick/ImageMagick/issues/2111#issuecomment-640058410
> PDF's are resolution independent. As such, the resolution is not stored in the PDF image files. Instead, you can render it at whatever resolution you want.

**Comment by za3k** [comment]
OK well. Sadly, I don't think I'll be able to get ImageMagick to fix this either, you're welcome to take up the baton if you think it's worthwhile. I'm giving up here and trying another multi-image format. Thanks for looking into it.
