### ISSUE TITLE
DPI doesn't roundtrip by default

### ISSUE THREAD

**Issue by user1584** [python-pillow/Pillow#6288]
### What did you do?
I opened an image with dpi info, saved it and noticed that the dpi info is missing in the saved image. 
Background: Apparently, the dpi information is used, e.g. by tesseract to get better OCR results. In an image that I am unfortunately not allowed to share, a huge difference in the OCR results could be traced back to existing/missing dpi info. This was discovered since the results from feeding an image directly into tesseract differed from the results that were achieved using pytesseract. The cause of this difference is that pytesseract saves the passed PIL images as temporary files without explicitly passing the dpi argument. 

### What did you expect to happen?
Basically, I expected that all attributes from the image are saved again. Ideally, all meta information should be passed during save operation.

### What actually happened?
dpi info is missing from saved image.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04.4
* Python: 3.9.7
* Pillow: 9.0.1

```python
from PIL import Image
import requests
from io import BytesIO

# Downloading a sample image and saving it with dpi parameter
response = requests.get("https://jeroen.github.io/images/testocr.png")
img = Image.open(BytesIO(response.content))
img.save("img_with_dpi.png", dpi=(300, 300)) # The sample image does not contain the dpi info - therefore it is added explicitly

# Opening the sample image, reading info and saving it again without explicit dpi parameter
img_with_dpi = PIL.Image.open("img_with_dpi.png")
print("img_with_dpi.info:", img_with_dpi.info)

# Opening the previously saved image and reading info
img_with_dpi.save("img_without_dpi.png")
img_without_dpi = PIL.Image.open("img_without_dpi.png")
print("img_without_dpi.info:", img_without_dpi.info)
>>> img_with_dpi.info: {'dpi': (299.9994, 299.9994)}
>>> img_without_dpi.info: {}
```

**Comment by radarhere** [comment]
Hi. If I'm following correctly, then your original image has a high DPI, yes? And when you're saving it back again, the absence of a high DPI is causing a problem for you?

If we made this change, couldn't that cause a problem for existing Pillow users? Say if I was used to opening a low DPI image, without ever being aware that it had a low DPI, writing text on it and then saving it. With your suggested change, I would suddenly start wondering why the DPI was so low.

**Comment by radarhere** [comment]
Pillow values backwards compatibility, so I'm going to close this rather than change the default behaviour.

If you have any further thoughts, let us know.
