### ISSUE TITLE
GIF: multiple comment blocks for a frame are run together

### ISSUE THREAD

**Issue by raygard** [python-pillow/Pillow#6293]
### What did you do?
Read a GIF file with two or more comments in a single frame

### What did you expect to happen?
They would somehow be kept separate in the `.info` dict

### What actually happened?
The comments are run together, e.g. separate comments `foo` and `bar` become `foobar`

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.10.4
* Pillow: 9.1.0

Example image:

![multiple_comments](https://user-images.githubusercontent.com/24783736/168400700-03d5a7a8-5329-4bde-80b9-b6d58a2a033b.gif)

```python
from PIL import Image
with Image.open("multiple_comments.gif") as im:
    print(f'{im.info["comment"]=}')
```
prints 
```
im.info["comment"]=b'Test comment 1Test comment 2'
```
I made PR #6294 to address this, that will separate the comments with `\r\n`.

I admit that such cases are rare, but I have a few found in the wild. Unfortunately most of them have the multiple comments after the last image block, and at present I see no way in Pillow to access comments beyond the last image block. I do have one with 10 comment blocks before the image, a logo from my former employer:

![b6483cc24863f387173dd6fb5a150ede_image003](https://user-images.githubusercontent.com/24783736/168401052-648a8862-82d0-4846-a348-4fc51e617834.gif)

**Comment by radarhere** [comment]
I tried to see what `exiftool` did, but it only returns the first comment.

```
$ exiftool relayhealth.gif | grep Comment
Comment                         : Author:
```

https://www.metadata2go.com/, https://exifdata.com/ and https://jimpl.com/ do the same.

If I try ImageMagick, `identify -verbose relayhealth.gif`, I get only "Title:"

So my quest to see if there was standard behaviour for this did not succeed.

And in all of the images you've found in the wild, the text is all such that it makes sense for them to be separated by newlines? No words split between comment blocks?

**Comment by raygard** [comment]
I combed through all the GIFs I have for those with more than one comment block. The result is in https://gist.github.com/raygard/3169ddef212679713d5e7dce81b21b67 . Most are over 20 years old, accumulated from old backups of my kids computers and such. I don't see any that would look right if run together. I realize it's probably a rare situation and maybe not worth the effort to mess with. Especially in Pillow, where (AFAIK) we can't currently even pick up comments after the last image, and that's where most of these came from.
