### ISSUE TITLE
How can I make the edges of a picture clear?

### ISSUE THREAD

**Issue by zhenzi0322** [python-pillow/Pillow#6302]
![bdb1b6763bb346c0875c6be6c05b5f58](https://user-images.githubusercontent.com/34839719/168511154-a902a8fa-bca1-41d9-9f8c-8b6f3683876f.png)

**Comment by radarhere** [comment]
When you say 'clear', are you able to provide a description of what you mean in terms of pixels?

**Comment by radarhere** [comment]
Here are some ideas.

```python
from PIL import Image, ImageFilter
im = Image.open("head.png")
im = im.filter(ImageFilter.SHARPEN)
im.save("filter.png")
```
<img src="https://user-images.githubusercontent.com/3112309/170807782-1e4b5991-b1f5-4ff4-b89f-a4a87bd8c724.png" width="200" />

```python
from PIL import Image, ImageEnhance
im = Image.open("head.png")
enhancer = ImageEnhance.Sharpness(im)
im = enhancer.enhance(2)
im.save('enhance.png');
```
<img src="https://user-images.githubusercontent.com/3112309/170807785-c3ba6e3a-58f1-45de-927d-1a85d3e44552.png" width="200" />

```python
# If a pixel has greater than 10% opacity, make it opaque
from PIL import Image
im = Image.open("head.png")
for x in range(im.width):
	for y in range(im.height):
		p = im.getpixel((x, y))
		alpha = p[3]
		if 25 < alpha < 255:
			p = (p[0], p[1], p[2], 255)
			im.putpixel((x, y), p)
im.save("custom.png")
```
<img src="https://user-images.githubusercontent.com/3112309/170807787-ac22328b-36a6-4a6e-b769-d20d0661524c.png" width="200" />

**Comment by radarhere** [comment]
I've found two more filters - `EDGE_ENHANCE` and `EDGE_ENHANCE_MORE`.
![pil123rgba](https://user-images.githubusercontent.com/3112309/170849712-8a4ee99c-74bb-45e8-901e-3a4062fd5aef.png)
```python
from PIL import Image, ImageFilter
im = Image.open("pil123rgba.png")
im = im.filter(ImageFilter.EDGE_ENHANCE)
im.save("edge_enhance.png")
```
![edge_enhance](https://user-images.githubusercontent.com/3112309/170849717-ffffbc01-c5df-4709-acf2-919e2368efde.png)
```python
from PIL import Image, ImageFilter
im = Image.open("pil123rgba.png")
im = im.filter(ImageFilter.EDGE_ENHANCE_MORE)
im.save("edge_enhance_more.png")
```
![edge_enhance_more](https://user-images.githubusercontent.com/3112309/170849719-57afab1b-0c77-485c-b82c-e7a3a1e76647.png)

**Comment by radarhere** [comment]
@zhenzi0322 was any of that helpful?
