### ISSUE TITLE
Release 9.1.1 on May 17, 2022

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#6304]
## Point Release

Released as needed for security, installation or critical bug fixes.

* [x] Make necessary changes in `main` branch.
* [x] Update `CHANGES.rst`.
* [x] Check out release branch e.g.:
  ```bash
  git checkout -t remotes/origin/5.2.x
  ```
* [x] Cherry pick individual commits from `main` branch to release branch e.g. `5.2.x`, then `git push`.
* [x] Check [GitHub Actions](https://github.com/python-pillow/Pillow/actions) and [AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm passing tests in release branch e.g. `5.2.x`.
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Run pre-release check via `make release-test`.
* [x] Create tag for release e.g.:
  ```bash
  git tag 5.2.1
  git push
  git push --tags
  ```
* [x] Create and check source distribution:
  ```bash
  make sdist
  python3 -m twine check --strict dist/*
  ```
* [x] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/main/RELEASING.md#binary-distributions)

### Windows
* [x] Contact `@cgohlke` for Windows binaries via release ticket e.g. https://github.com/python-pillow/Pillow/issues/1174.
* [x] Download and extract tarball from `@cgohlke` and copy into `dist/`

### Mac and Linux
* [x] Use the [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels):
  ```bash
  git clone https://github.com/python-pillow/pillow-wheels
  cd pillow-wheels
  ./update-pillow-tag.sh [[release tag]]
  ```
* [x] Download wheels from the [Pillow Wheel Builder release](https://github.com/python-pillow/pillow-wheels/releases)
  and copy into `dist/`

---

* [x] Check and upload all binaries and source distributions e.g.:
  ```bash
  python3 -m twine check --strict dist/*
  python3 -m twine upload dist/Pillow-5.2.1*
  ```
* [x] Publish the [release on GitHub](https://github.com/python-pillow/Pillow/releases)

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the [default version for Read the Docs](https://pillow.readthedocs.io/en/stable/) is up-to-date with the release changes

## Docker Images

* [x] Update Pillow in the Docker Images repository
  ```bash
  git clone https://github.com/python-pillow/docker-images
  cd docker-images
  ./update-pillow-tag.sh [[release tag]]
  ```

**Comment by hugovk** [comment]
Hi @cgohlke, please could we have Windows binaries for 9.1.1?

**Comment by cgohlke** [comment]
[Here](https://www.lfd.uci.edu/~gohlke/download/Pillow-9.1.1-win-dist.zip) you go. You may not want to upload the wheels for Python 3.11b1 to PyPI.

**Comment by hugovk** [comment]
@cgohlke Thank you! Yep, I skipped the 3.11 beta ones. Nice to see they're building though :) 

For 3.10 last year, we were going to do our October release as soon as 3.10 was released, but then decided to put out 3.10 wheels already during the RC period to help people test: https://github.com/python-pillow/Pillow/issues/5569#issuecomment-894275079. So I expect we'll do something similar this year.

[3.11 schedule](https://peps.python.org/pep-0664/):

- 3.11.0 beta 2: Monday, 2022-05-30
- 3.11.0 beta 3: Thursday, 2022-06-16
- 3.11.0 beta 4: Saturday, 2022-07-09
- 3.11.0 candidate 1: Monday, 2022-08-01
- 3.11.0 candidate 2: Monday, 2022-09-05
- 3.11.0 final: Monday, 2022-10-03

(Maybe even include a 3.11 in the July release? Anyway, we can discuss this stuff later.)

---

🚀 Pillow 9.1.1 is released!

* https://pillow.readthedocs.io/en/latest/releasenotes/9.1.1.html
* https://pypi.org/project/Pillow/9.1.1/#files
* https://github.com/python-pillow/Pillow/releases/tag/9.1.1

Tweet to follow.

**Comment by ulgens** [comment]
Installing 9.1.1 under `python:3.10.4-slim-bullseye` fails with the error below but 9.1.0 works fine. I'm not sure if this is something went wrong with release or a bug in the code.

```
#11 17.34         Traceback (most recent call last):
#11 17.34           File "/tmp/pip-req-build-e8_ay6ey/setup.py", line 989, in <module>
#11 17.34             setup(
#11 17.34           File "/usr/local/lib/python3.10/site-packages/setuptools/__init__.py", line 153, in setup
#11 17.34             return distutils.core.setup(**attrs)
#11 17.34           File "/usr/local/lib/python3.10/distutils/core.py", line 148, in setup
#11 17.34             dist.run_commands()
#11 17.34           File "/usr/local/lib/python3.10/distutils/dist.py", line 966, in run_commands
#11 17.34             self.run_command(cmd)
#11 17.34           File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
#11 17.34             cmd_obj.run()
#11 17.34           File "/usr/local/lib/python3.10/site-packages/setuptools/command/install.py", line 61, in run
#11 17.34             return orig.install.run(self)
#11 17.34           File "/usr/local/lib/python3.10/distutils/command/install.py", line 568, in run
#11 17.34             self.run_command('build')
#11 17.34           File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
#11 17.34             self.distribution.run_command(command)
#11 17.34           File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
#11 17.34             cmd_obj.run()
#11 17.34           File "/usr/local/lib/python3.10/distutils/command/build.py", line 135, in run
#11 17.34             self.run_command(cmd_name)
#11 17.34           File "/usr/local/lib/python3.10/distutils/cmd.py", line 313, in run_command
#11 17.34             self.distribution.run_command(command)
#11 17.34           File "/usr/local/lib/python3.10/distutils/dist.py", line 985, in run_command
#11 17.34             cmd_obj.run()
#11 17.34           File "/usr/local/lib/python3.10/site-packages/setuptools/command/build_ext.py", line 79, in run
#11 17.34             _build_ext.run(self)
#11 17.34           File "/usr/local/lib/python3.10/distutils/command/build_ext.py", line 340, in run
#11 17.34             self.build_extensions()
#11 17.34           File "/tmp/pip-req-build-e8_ay6ey/setup.py", line 804, in build_extensions
#11 17.34             raise RequiredDependencyException(f)
#11 17.34         __main__.RequiredDependencyException: zlib
```

**Comment by hugovk** [comment]
It's trying a source build there.

If you install 9.1.0 with no cache, does it install a wheel?

For example, what output do you get with this?

```sh
python3 -m pip install --no-cache-dir pillow==9.1.0
```

**Comment by ulgens** [comment]
@hugovk 

```
root@9a43f098af83:/code/src# python3 -m pip install --no-cache-dir pillow==9.1.0
Collecting pillow==9.1.0
  Downloading Pillow-9.1.0-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (4.3 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 4.3/4.3 MB 11.9 MB/s eta 0:00:00
Installing collected packages: pillow
Successfully installed pillow-9.1.0
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
root@9a43f098af83:/code/src# python3 -m pip install --no-cache-dir pillow==9.1.1
Collecting pillow==9.1.1
  Downloading Pillow-9.1.1.tar.gz (49.8 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 49.8/49.8 MB 23.5 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Building wheels for collected packages: pillow
  Building wheel for pillow (setup.py) ... error
```

**Comment by hugovk** [comment]
Thanks, we're missing the aarch64 wheels, the others are built on GitHub Actions but these are built by Travis CI and for some reason didn't upload to GitHub Releases (and from there to PyPI):

https://app.travis-ci.com/github/python-pillow/pillow-wheels/builds/250747395

We'll look into it.

**Comment by hugovk** [comment]
@ulgens Now uploaded to PyPI:

```
Pillow-9.1.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Pillow-9.1.1-cp37-cp37m-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Pillow-9.1.1-cp38-cp38-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
Pillow-9.1.1-cp39-cp39-manylinux_2_17_aarch64.manylinux2014_aarch64.whl
```

Please could you try again?

**Comment by ulgens** [comment]
@hugovk 

```
root@83a465c7191e:/code/src# python3 -m pip install --no-cache-dir pillow==9.1.1
Collecting pillow==9.1.1
  Downloading Pillow-9.1.1-cp310-cp310-manylinux_2_17_aarch64.manylinux2014_aarch64.whl (3.0 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.0/3.0 MB 10.7 MB/s eta 0:00:00
Installing collected packages: pillow
  Attempting uninstall: pillow
    Found existing installation: Pillow 9.1.0
    Uninstalling Pillow-9.1.0:
      Successfully uninstalled Pillow-9.1.0
Successfully installed pillow-9.1.1
```

Seems okay now. Thanks a lot.

**Comment by aclark4life** [comment]
Thanks all! Pinned Tweet is up.

![Screenshot 2022-05-18 104151](https://user-images.githubusercontent.com/72164/169069454-4a5ec6c3-8d52-4adc-b095-890eff6f855e.png)

**Comment by hugovk** [comment]
Issue https://github.com/python-pillow/pillow-wheels/issues/295 and PR https://github.com/python-pillow/pillow-wheels/pull/296 to help release aarch64 wheels for next time.
