### ISSUE TITLE
How to invert image color with percentage

### ISSUE THREAD

**Issue by julin69** [python-pillow/Pillow#6307]
Hello, 
I want to invert an image color with percentage, like css filter: invert(30%)，i want the same image color effect. I find ImageOps,  but ImageOps doesn't have percentage param, how to do? Thank you very much!

**Comment by julin69** [comment]
![image](https://user-images.githubusercontent.com/34527159/168945915-dd99c448-0e78-457b-a116-40a2dba91e28.png)


like this picture

**Comment by radarhere** [comment]
```python
from PIL import Image

def invert(im, percentage):
    lut = []
    for band in im.getbands():
        for i in range(256):
            if band == "A":
                # Don't invert transparency
                lut.append(i)
            else:
                lut.append(percentage * (255 - i) + (1 - percentage) * i)
    return im.point(lut)

im = Image.open("firefox.png")
invert(im, 0.3).save("30%.png")
```

**Comment by radarhere** [comment]
My above code makes use of [`point()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.point), which is what [`ImageOps.invert()` itself uses internally.](https://github.com/python-pillow/Pillow/blob/6bb408c9622617a6d37d1746716721004188f743/src/PIL/ImageOps.py#L518-L528)

**Comment by julin69** [comment]
Yes, this is what my want.Thanks very much!
