### ISSUE TITLE
ImageGrab.grab parameters not applied correctly on macOS

### ISSUE THREAD

**Issue by MarkSetchell** [python-pillow/Pillow#6311]
The code below from StackOverflow

https://stackoverflow.com/q/72204296/2836621

demonstrates the problem that, on macOS, the parameters to ImageGrab are not applied correctly:

```python
import time
from PIL import ImageGrab
bbox = (100, 100, 500, 500)
time.sleep(3)
screenshot = ImageGrab.grab(bbox)
screenshot.save("screenshot.png")
screenshot.close()
```

Hopefully my comment beneath the question provides a suitable correction.

**Comment by radarhere** [comment]
Hi. This has already been pointed out in #6308 and #6244.

It will be fixed in the next version of Pillow, due to be released on July 1.

**Comment by radarhere** [comment]
If you would like your code to work before then, you can either modify your Pillow installation, install Pillow from source using the main branch, or downgrade to Pillow 9.0.1.

**Comment by radarhere** [comment]
Although considering that you didn't ask the StackOverflow question, only answered it, I expect you have no practical need for this, and just wanted to let us know.
