### ISSUE TITLE
Not possible to take screenshot under Wayland

### ISSUE THREAD

**Issue by KhazAkar** [python-pillow/Pillow#6312]
### What did you do?
I've tried to make screenshot using Pillow on Wayland compositor, such as GNOME running in Wayland mode
### What did you expect to happen?
Screenshot of full display
### What actually happened?
```
Traceback (most recent call last):
  Python Shell, prompt 2, line 1
    # Used internally for debug sandbox under external interpreter
  File "/home/khazakar/Project/Test/test_venv/lib/python3.8/site-packages/PIL/ImageGrab.py", line 68, in grab
    size, data = Image.core.grabscreen_x11(xdisplay)
builtins.OSError: X get_image failed: error 8 (73, 0, 1315)
```
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04, GNOME Wayland
* Python: 3.8.10
* Pillow:  9.1.0

```python
from PIL import ImageGrab
ImageGrab.grab()
```

Is there wayland support on roadmap anytime soon?

**Comment by nulano** [comment]
> Is there wayland support on roadmap anytime soon?

AFAIK no one is working on this, contributions are welcome.

From https://stackoverflow.com/q/72216896/1648883, it sounds like `gnome-screenshot` is one of few utilities that can take a screenshot on Wayland. From a cursory look, https://gitlab.gnome.org/GNOME/gnome-screenshot/-/blob/master/src/screenshot-backend-shell.c appears to be the implementation.

**Comment by radarhere** [comment]
I don't suppose it would be sufficient to just check for [`gnome-screenshot`](https://linux.die.net/man/1/gnome-screenshot) and call that, in the same way that ImageGrab [calls `screencapture` on macOS](https://github.com/python-pillow/Pillow/blob/30a0e448c181a81b435b77655d2c86549fbb4fec/src/PIL/ImageGrab.py#L30-L37)?

**Comment by KhazAkar** [comment]
> I don't suppose it would be sufficient to just check for [`gnome-screenshot`](https://linux.die.net/man/1/gnome-screenshot) and call that, in the same way that ImageGrab [calls `screencapture` on macOS](https://github.com/python-pillow/Pillow/blob/30a0e448c181a81b435b77655d2c86549fbb4fec/src/PIL/ImageGrab.py#L30-L37)?

Not so much, since you can don't have GNOME stack running and all and you have more than 1 wayland-enabled DE :)

**Comment by nulano** [comment]
From https://news.ycombinator.com/item?id=26446802, it sounds like there is no standard way to take a screenshot on Wayland. `gnome-screenshot` uses a gnome-specific extension to Wayland, other implementations work differently.

**Comment by radarhere** [comment]
Googling, it seems Wayland considers it a security feature to prevent screenshots.

@KhazAkar there doesn't seem to be any way to achieve what you are after.

**Comment by KhazAkar** [comment]
> Googling, it seems Wayland considers it a security feature to prevent screenshots.
> 
> @KhazAkar there doesn't seem to be any way to achieve what you are after.

Depends. Somehow tools like gnome-screenshot works, right? I think they use some sort of portal or interface to contact the underlying compositor and grab needed data.

**Comment by radarhere** [comment]
https://www.reddit.com/r/linux/comments/7lb5l7/new_screenshot_alternative_for_wayland/
> It has been almost a decade, why does Wayland not have a protocol definition for screenshots?
> ...
> Because security

It could be done by using compositor-specific tools like gnome-screenshot, but I thought [you were looking for a generic solution](https://github.com/python-pillow/Pillow/issues/6312#issuecomment-1137816424).

**Comment by radarhere** [comment]
I've created PR #6361 to use `gnome-screenshot`.

**Comment by hugovk** [comment]
@KhazAkar Please can you test https://github.com/python-pillow/Pillow/pull/6361 and let us know if it works for you?

**Comment by radarhere** [comment]
PR #6361 has been merged, and there has been a lack of response here about that.

Any thoughts of further improvement can be continued in #6392
