### ISSUE TITLE
Artifacts and noise appearing on GIFs with colored backgrounds

### ISSUE THREAD

**Issue by justinodunn** [python-pillow/Pillow#6318]
### What did you do?
Made a script that would resize GIFs to 32px height, to be displayed on 64x32 LED matrix panels, using the Raspberry Pi.

### What did you expect to happen?
I expected the GIFs to be resized successfully, with colors appearing normally.

### What actually happened?
GIFs with black backgrounds appear fine. However, GIFs with colored backgrounds would have artifacts, static noise and distortion when displayed on the LED panels.

**Video examples for black background GIF:**
![](https://i.stack.imgur.com/gcJga.gif)

![](https://i.stack.imgur.com/S89Jr.gif)

![](https://i.imgur.com/IaLWDT8.gif)

**Video examples for colored background GIF:**
![](https://i.stack.imgur.com/a5DxU.gif)

![](https://i.stack.imgur.com/T27q8.gif)

![](https://i.imgur.com/lH4b6AJ.gif)

### What are your OS, Python and Pillow versions?

* OS: Debian Buster
* Python: Python 3.7.3
* Pillow: 9.0.0

```python
def getUserGIFs(self):

f = open('csv/GIF_settings.json', 'r')
all_settings = json.load(f)
f.close()


for ind,fle in enumerate(all_settings['images']):
            
            try:
                GIF = Image.open(os.path.join(os.path.join(os.path.dirname(os.path.abspath(__file__)), 'user_uploads'), fle))
                frames = []

                    for i, frame in enumerate(ImageSequence.Iterator(GIF)):
                        
                        frame = frame.convert('P')
                        frame.thumbnail((128, 32),Image.LANCZOS)

                        f = self.stitchImage([frame])
                        frames.append(f)


                frames[0].save('./display_images/working_gif{}.gif'.format(str(ind)), save_all=True, append_images=frames[1:], loop=0, optimize = False)
                GIF = Image.open('./display_images/working_gif{}.gif'.format(str(ind)))
                GIFs.append(GIF)


            except Exception as e:
                logf = open('log.txt', "a")
                exc_type, exc_obj, exc_tb = sys.exc_info()
                fname = os.path.split(exc_tb.tb_frame.f_code.co_filename)[1]
                logf.write(str(e))
                logf.write('. file: ' + fname)
                logf.write('. line: ' +  str(exc_tb.tb_lineno))
                logf.write('. type: ' +  str(exc_type))
                logf.write('\n ' + "".join(traceback.format_exception(sys.exc_info()[0], sys.exc_info()[1], sys.exc_info()[2])))
                logf.close()

        return GIFs

```

**Comment by justinodunn** [comment]
https://ezgif.com/resize

Using ezgif to resize the GIF is working fine. So is it the sampling methods of Pillow?

![cabin](https://user-images.githubusercontent.com/13812089/169755986-d1ea434c-4855-42b7-a495-78e8da7747ee.gif)

**Comment by justinodunn** [comment]
I also tried running this script on my Pi and the result was fine https://gist.github.com/Simon-Ince/910c440eb34bb722afa90853ecfb1d85

**Comment by radarhere** [comment]
Hi. Would you be able to provide a self-contained example? At the moment, I don't know what `stitchImage` is doing.

If you're happy with the out.gif generated from that gist though, have you considered just removing `frame = frame.convert('P')` from the code you posted above?

**Comment by justinodunn** [comment]
@radarhere Thanks so much for your reply. Let me do more testing and get back to you on this!

**Comment by justinodunn** [comment]
You're right, thank you! Sorry, turns out it was some other part of the bigger picture code that was causing this, I'm very embarrassed haha

Thanks agian!
