### ISSUE TITLE
BUG: n_frames is incorrect

### ISSUE THREAD

**Issue by WuZifan** [python-pillow/Pillow#6320]
### What did you do?
i try to load every frame of a gif by  the following code

```python
# PILLOW==9.1.0

img = Image.open('./test.gif')
for I in range(img.n_frames):
    tmp.seek(i)
```

below is the test img and I find that `img.n_frames` gives me 2 but the actual frame number is 1,so the seek function raise an EOF error. 

![13077030995698418847](https://user-images.githubusercontent.com/22706545/169772374-2a911010-4562-4fcd-8c5a-47b0642a111e.gif)

### What did you expect to happen?
load all the frame without any error

### What actually happened?

The following error is raised.
raise EOFError("no more images in GIF file") from e

### What are your OS, Python and Pillow versions?

* OS: macos m1
* Python: 3.7.0
* Pillow: 9.1.0

```python
from PIL import Image
img = Image.open('./test.gif')
for I in range(img.n_frames):
    tmp.seek(i)
```

**Comment by radarhere** [comment]
Testing, I find that #6219 will resolve this.
