### ISSUE TITLE
PIL import error

### ISSUE THREAD

**Issue by createvi** [python-pillow/Pillow#6327]
### What did you do?
i added 
`from PIL import Image` and used `Image.open` function
### What actually happened?
i got this error
```py
Traceback (most recent call last):
  File "/home/vishnu/Vortex/Projects/shop.py", line 2, in <module>
    from PIL import Image
  File "/usr/lib/python3/dist-packages/PIL/Image.py", line 69, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/usr/lib/python3/dist-packages/PIL/__init__.py)
```
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 20.04 LTS
* Python: 2.7.18
* Pillow: 9.1.1

**Comment by radarhere** [comment]
Hi. The traceback mentions "python3", so it would seem you are not using Python 2. If your intention is to use Python 2, be aware that [Pillow dropped support for it in 7.0.0.](https://pillow.readthedocs.io/en/stable/releasenotes/7.0.0.html#python-2-7)

How did you install Pillow?

**Comment by radarhere** [comment]
If you would like to use Python 2, then you should downgrade to Pillow 6.2.2.

If you would like to use Pillow 9.1.1, then you should upgrade to Python 3.

**Comment by createvi** [comment]
the code is python3.9 https://imgur.com/KawyYlW and i am using Pillow 9.1.1

**Comment by createvi** [comment]
https://imgur.com/aOAAjoG, and pillow is installed

**Comment by radarhere** [comment]
What is the command you are using to run your code? `python shop.py`? If so, please run
```
python -m pip uninstall Pillow
python -m pip install --upgrade pip
python -m pip install --upgrade Pillow
```
This will uninstall Pillow, upgrade your copy of pip and re-install Pillow.

Then try `python shop.py` again.

**Comment by radarhere** [comment]
Ok, so please try
```
/bin/python3.9 -m pip uninstall Pillow
/bin/python3.9 -m pip install --upgrade pip
/bin/python3.9 -m pip install --upgrade Pillow
```
and then run your code again.

**Comment by createvi** [comment]
![Screenshot from 2022-05-25 15-02-36](https://user-images.githubusercontent.com/93326280/170231019-b2533c4a-8e2a-48bd-8c65-0b17fe34f7d0.png)
thus happens when i run `/bin/python3.9 -m pip install --upgrade pip`
