### ISSUE TITLE
Error running build_prepare.py

### ISSUE THREAD

**Issue by dmay31** [python-pillow/Pillow#6328]
Trying to run build_prepare.py on windows and it can download  
https://iweb.dl.sourceforge.net/project/libjpeg-turbo/2.1.3/libjpeg-turbo-2.1.3.tar.gz

I also can not get this file from a normal web browser.

python3 build_prepare.py
Caching dependencies in: E:\grmn\prj\fit\Pillow\winbuild\depends
Target Python: C:\Python38\python3.exe
Target Architecture: x64
Found Visual Studio at: C:\Program Files (x86)\Microsoft Visual Studio\2019\Professional

Fetching https://iweb.dl.sourceforge.net/project/libjpeg-turbo/2.1.3/libjpeg-turbo-2.1.3.tar.gz (attempt 1)...
Fetching https://iweb.dl.sourceforge.net/project/libjpeg-turbo/2.1.3/libjpeg-turbo-2.1.3.tar.gz (attempt 2)...
Traceback (most recent call last):
  File "C:\Python38\lib\socket.py", line 796, in create_connection
    sock.connect(sa)
TimeoutError: [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond

During handling of the above exception, another exception occurred:

**Comment by radarhere** [comment]
This has been raised again as #6343
