### ISSUE TITLE
TIFF EXIF data is not updated when saving image

### ISSUE THREAD

**Issue by gverm** [python-pillow/Pillow#6334]
### What did you do?
Tried to add 'Artist' and 'Copyright' exif fields to artwork.tiff
### What did you expect to happen?
Exif to be saved and viewable for artwork.tiff.
### What actually happened?
Exif data was not updated and loading the image with Pillow again also didn't show the updated data.
### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.10.4
* Pillow: 9.1.1

```python
img = Image.open("artwork.tiff")
exif = img.getexif()
exif[0x8298] = "test"
exif[0x013B] = "test"
img.save("artwork.tiff", exif=exif)
```

[artwork.zip](https://github.com/python-pillow/Pillow/files/8775245/artwork.zip)
The tiff in the zip above was created by converting the svg I will attach below using ImageMagick.
[artwork-00.svg](https://user-images.githubusercontent.com/8126341/170388737-9f2c3100-f3b9-4342-b483-79eee8a6f226.svg)

Pillow saved the image successfully, no failure messages were shown.

**Comment by radarhere** [comment]
Hi. If you'd like an immediate workaround, adding in `img.load()` saves the data correctly.
```python
from PIL import Image
img = Image.open("artwork.tiff")
exif = img.getexif()
img.load()
exif[0x8298] = "test"
exif[0x013B] = "test"
img.save("artwork.tiff", exif=exif)
```

**Comment by radarhere** [comment]
I've created PR #6335 to resolve this.

**Comment by gverm** [comment]
@radarhere Thank you for the very fast response. I can confirm your workaround works.
