### ISSUE TITLE
`Image.verify` fails to detect corrupted file

### ISSUE THREAD

**Issue by LilithHafner** [python-pillow/Pillow#6342]
I have a .png file that passes `verify()` but fails on `load()` I expect the error has to do with compression within the IDAT chunk.

```python
>>> from PIL import Image
>>> img = Image.open("test image (800x600).png")
>>> img.verify()
>>> img = Image.open("test image (800x600).png")
>>> img.load()
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/ImageFile.py", line 274, in load
    raise_oserror(err_code)
  File "/Library/Frameworks/Python.framework/Versions/3.9/lib/python3.9/site-packages/PIL/ImageFile.py", line 67, in raise_oserror
    raise OSError(message + " when reading image file")
OSError: broken data stream when reading image file
```
Test image:
![test image (800x600)](https://user-images.githubusercontent.com/60898866/170707888-26373bed-bc92-4495-9c91-4e3889f33641.png)

Versions:
* OS: macOS 12.2.1
* Python: Python 3.9.5
* Pillow: 8.3.0

**Comment by radarhere** [comment]
It is perhaps worth nothing that if I tell Pillow to accept truncated images, the file loads without a problem.
```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
img = Image.open('test image (800x600).png')
img.load()
```

**Comment by radarhere** [comment]
The error isn't originating with any check in PngImagePlugin. It is coming from ImageFile.

If you run the code from my previous commit, you will see that the last 16 lines of the image are black. So I don't think that the image is "corrupted" as such. It is only "truncated", ending prematurely.

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.verify
> Verifies the contents of a file. For data read from a file, this method attempts to determine if the file is broken, without actually decoding the image data.

I would think that the image data is not broken. @LilithHafner does this answer your question?

**Comment by LilithHafner** [comment]
I made this .png file by hand with no intention of truncating it. I expect that the reason it is truncated is that I miscalculated one of the checksums. If this is the case, I would say the image data is broken. I'll get back to you if/when I determine the actual reason why this image is not working.
