### ISSUE TITLE
Windows build from source cannot find sourceforge dependencies

### ISSUE THREAD

**Issue by raygard** [python-pillow/Pillow#6343]
### What did you do?
Attempted to build Pillow from source on Windows
### What did you expect to happen?
Build should run OK
### What actually happened?
`winbuild\build_prepare.py` could not download dependencies because `SF_MIRROR` `https://iweb.dl.sourceforge.net` is not online.
### What are your OS, Python and Pillow versions?

* OS: Windows 10 Pro
* Python: 3.10.4
* Pillow: latest main source

```
Fetching https://iweb.dl.sourceforge.net/project/libjpeg-turbo/2.1.3/libjpeg-turbo-2.1.3.tar.gz (attempt 3)...
Traceback (most recent call last):
  File "E:\r\pil\PILdev\0530\Pillow-main\winbuild\build_prepare.py", line 588, in <module>
    build_dep_all()
  File "E:\r\pil\PILdev\0530\Pillow-main\winbuild\build_prepare.py", line 466, in build_dep_all
    script = build_dep(dep_name)
  File "E:\r\pil\PILdev\0530\Pillow-main\winbuild\build_prepare.py", line 431, in build_dep
    extract_dep(dep["url"], dep["filename"])
  File "E:\r\pil\PILdev\0530\Pillow-main\winbuild\build_prepare.py", line 391, in extract_dep
    raise RuntimeError(ex)
RuntimeError: <urlopen error [WinError 10060] A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond>
```

I find that the line `SF_MIRROR = "https://iweb.dl.sourceforge.net"` is the culprit.

Also, `ping https://iweb.dl.sourceforge.net` gets me:
`Ping request could not find host https://iweb.dl.sourceforge.net. Please check the name and try again.`

I changed to `SF_MIRROR = "https://cytranet.dl.sourceforge.net"` and it works.

I don't know if `iweb` is down for good or not. Maybe  `build_prepare.py` can be modified to have fallback mirrors, or somehow detect which of several SF mirrors are up?

**Comment by hugovk** [comment]
Can we use the link from https://sourceforge.net/projects/libjpeg-turbo/files/2.1.3/ ?

That is:

https://sourceforge.net/projects/libjpeg-turbo/files/2.1.3/libjpeg-turbo-2.1.3.tar.gz/download

That should do auto-mirror selection. For example, I did a wget of that from here in Finland and it selected a mirror from neighbouring Swden.

https://altushost-swe.dl.sourceforge.net/project/libjpeg-turbo/2.1.3/libjpeg-turbo-2.1.3.tar.gz

**Comment by raygard** [comment]
I tried `wget https://sourceforge.net/projects/libjpeg-turbo/files/2.1.3/libjpeg-turbo-2.1.3.tar.gz/download` just now (`--version` shows `GNU Wget 1.21.2 built on mingw32`) and just got the HTML download page. No actual package downloaded.
Also retried `ping https://iweb.dl.sourceforge.net` and now get:
```
Pinging sourceforge.mirror.iweb.ca [192.175.120.182] with 32 bytes of data:
Reply from 184.107.1.171: Destination host unreachable.
```
not quite the same as before but still no joy.

**Comment by raygard** [comment]
@nulano, thank you! that works. I have created PR #6345 to fix this. I don't know how to test it other than to say it works on my machine. Would appreciate any help testing from others who build Pillow on Windows.

**Comment by radarhere** [comment]
It will be tested in the PR by [AppVeyor](https://github.com/python-pillow/Pillow/blob/561d7ca9e05ed131a18dfd87491041ed73b08afe/.appveyor.yml#L32) and [GitHub Actions](https://github.com/python-pillow/Pillow/blob/561d7ca9e05ed131a18dfd87491041ed73b08afe/.github/workflows/test-windows.yml#L75).

**Comment by raygard** [comment]
@nulano this looks to be above my comfort level with GitHub etc. I hope someone else can help me with this. I think the PR is fine but would love some help before it goes out to the world.

**Comment by nulano** [comment]
> @nulano this looks to be above my comfort level with GitHub etc. I hope someone else can help me with this. I think the PR is fine but would love some help before it goes out to the world.

I've made the changes, see my response in the PR: https://github.com/python-pillow/Pillow/pull/6345#issuecomment-1144288545

**Comment by raygard** [comment]
@hugovk, thank you for the original auto-mirror-download suggestion; I don't know why it didn't work with my (maybe outdated?) Windows port of wget. @nulano, thank you for all the help. You guys are awesome!

Now, do I need to do anything more on this? Are these mods to the PR something that I need to, um, push or merge or whatever? (I'm so behind on learning git / GitHub). I'm guessing if I click "Create pull request" on @nulano's changes, then it will create a new PR or update my existing one? If it creates a new PR, what do I do with the old one? And do I want a PR that changes the Windows build or test workflow? Do you want it to download all the dependencies over and over? Obviously I need a clue...

**Comment by radarhere** [comment]
Oh, no, we don't want to download all the dependencies over and over. Precisely to avoid this problem, where one of the dependencies might become unavailable. Instead, we host dependencies for our CI scripts over at https://github.com/python-pillow/pillow-depends

This discussion was just about temporarily ignoring pillow-depends, to demonstrate that your new URL does work. The PR doesn't need to contain that change.

**Comment by raygard** [comment]
Thanks, that’s what I thought. So I think I do not need to do anything more
on this pull request.
