### ISSUE TITLE
DDS BC6 decoding has a broken blue channel

### ISSUE THREAD

**Issue by expenses** [python-pillow/Pillow#6344]
I attempted to use the code in https://github.com/python-pillow/Pillow/blob/main/src/libImaging/BcnDecode.c for a project in order to decode BC6 textures. The red and green channels decoded correctly but the blue channel ended up being mangled somehow.

Here's the red channel of the image as displayed in renderdoc:
![20220601_16h17m43s_grim](https://user-images.githubusercontent.com/13566135/171426393-5108509f-d4a9-48f1-b14e-4fe94d370749.png)

and here's the blue channel:

![20220601_16h17m52s_grim](https://user-images.githubusercontent.com/13566135/171426461-19642041-da11-4a56-bc62-4d59fb826cc6.png)

This results in an image that looks like this:

![20220601_15h56m13s_grim](https://user-images.githubusercontent.com/13566135/171426539-849b126b-28bf-4f49-ac9c-c92ab9509888.png)

### What are your OS, Python and Pillow versions?

* OS: N/A
* Python: N/A
* Pillow: https://github.com/python-pillow/Pillow/commit/b261e179078a36adb030e029c9834d8c00dec4e0

**Comment by radarhere** [comment]
Would we be able to get a copy of the image itself?

**Comment by expenses** [comment]
> Would we be able to get a copy of the image itself?

I've uploaded the source image (which is a cubemap with several mip levels) in 2 formats, .dds and .ktx2:

[broken.zip](https://github.com/python-pillow/Pillow/files/8823706/broken.zip)

As the broken output .dds file is quite large (128mb) it exceeds the 25mb upload limit unless I make a non-trivial modification. Let me know if you'd like me to send that to you by another means though!

**Comment by radarhere** [comment]
Thanks for the image.

I'm not happy with it enough yet for a PR, but see what you think of https://github.com/radarhere/Pillow/commit/3b51e1cc498273d6c25afa8d29e60f77a9861518. It generates this from your image.

<img width="350" src="https://user-images.githubusercontent.com/3112309/171997260-da7398b4-5433-4876-9cd7-fb55414e55e2.png" />
