### ISSUE TITLE
ImageDraw.text text falling outside of image

### ISSUE THREAD

**Issue by arditoibryan** [python-pillow/Pillow#6351]
I am using the following code to write text on an image:

```python
draw.text((100, 100), t ,fill=(255, 0, 0), font=font)
```

Is there a parameter that I can use to specify the margins of the text?

Thank you

**Comment by nulano** [comment]
Are you asking for automatic line-breaking? Pillow does not currently do that. There is already a request in #6201.

If you want to see the bounding box where text will be rendered you can use:

```python
left, top, right, bottom = draw.textbbox((100, 100), t, fill=(255, 0, 0), font=font)
```

For line-breaking purposes it is preferred to use `right = 100 + draw.textlength(t, font=font)` instead as it better reflects the font designer's intentions.

**Comment by radarhere** [comment]
Unless there are any further questions, closing as a duplicate.
