### ISSUE TITLE
Transformation functions should accept Image.ANTIALIAS as resampling filter

### ISSUE THREAD

**Issue by Bergfried** [python-pillow/Pillow#636]
It would be nice to see the Lanczos3 filter (`PIL.Image.ANTIALIAS`) available for other transformation functions besides `Image.resize`, e.g. `PIL.Image.rotate` and `PIL.Image.transform`.

**Comment by homm** [comment]
Currently, transformations use fast but very inaccurate filters based on fixed number of source samples (like resizing with `BICUBIC` and `BILINEAR` in Pillow prior `2.7.0`). `LANCZOS` (former `ANTIALIAS`) doesn't have any advantages over `BICUBIC` with such approach.
