### ISSUE TITLE
Create wheels for Python 3.11 beta

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#6367]
We'll release binary wheels for the next Pillow release (9.2.0, 1st July 2022, https://github.com/python-pillow/Pillow/issues/6366).

According to the [Python 3.11 release manager](https://discuss.python.org/t/python-3-11-0b2-is-now-available/16111?u=hugovk):

> We **strongly encourage** maintainers of third-party Python projects to test with 3.11 during the beta phase and report issues found to [the Python bug tracker](https://github.com/python/cpython/issues) as soon as possible. While the release is planned to be feature complete entering the beta phase, it is possible that features may be modified or, in rare cases, deleted up until the start of the release candidate phase (Monday, 2021-08-02). Our goal is have no ABI changes after beta ~4~ [5] and as few code changes as possible after 3.11.0rc1, the first release candidate. To achieve that, it will be **extremely important** to get as much exposure for 3.11 as possible during the beta phase.
> 
> Please keep in mind that this is a preview release and its use is not recommended for production environments.

Therefore it's possible the ABI may change before the official release, so these 3.11 wheels can also be considered preview releases, but will help people test and prepare their projects with 3.11.

**Comment by hugovk** [comment]
What do we need to build 3.11 wheels?

Does https://github.com/multi-build/multibuild support building wheels for 3.11?

(Re: https://github.com/python-pillow/Pillow/issues/5569 for adding support for Python 3.10, specifically https://github.com/python-pillow/pillow-wheels/pull/215 and https://github.com/python-pillow/pillow-wheels/pull/217).

**Comment by radarhere** [comment]
The last Python beta release before July 1 will be [Python 3.11 beta 4, due out today](https://peps.python.org/pep-0664/).

Once that is out, yes, a multibuild PR should be created to support building wheels for 3.11.

As for testing those wheels as part of our CI, I expect that will require a PR to https://github.com/multi-build/docker-images for 64-bit, and https://github.com/matthew-brett/trusty for 32-bit.

**Comment by hugovk** [comment]
> The last Python beta release before July 1 will be [Python 3.11 beta 4, due out today](https://peps.python.org/pep-0664/).

There are (currently five) release blockers:

* https://mail.python.org/archives/list/python-dev@python.org/thread/ORCYBRP432J36LXP32IDX6KLRE7Z646V/

* https://github.com/python/cpython/issues?q=is%3Aissue+is%3Aopen+label%3Arelease-blocker+label%3A3.11+

**Comment by radarhere** [comment]
Interestingly, replies on https://github.com/python/cpython/issues/89480 and https://github.com/python/cpython/issues/90235 say they were release blockers for beta 2... so maybe they aren't absolute "blockers".

**Comment by radarhere** [comment]
b4 might be released next week? https://mail.python.org/archives/list/python-dev@python.org/thread/7AT3YTUJOYMZI4VNMSJ42BE6ZNR7GANM/

For now though, I've created https://github.com/python-pillow/pillow-wheels/pull/302 to add b3 to pillow-wheels.

**Comment by radarhere** [comment]
https://github.com/python-pillow/pillow-wheels/pull/302 has been merged, so Pillow 9.2.0 can have Python 3.11.0 beta 3 wheels.

**Comment by radarhere** [comment]
Python 3.11.0 beta 3 is still the latest beta, and Pillow 9.2.0 has been released.

So this is resolved. Pillow 9.3.0 is scheduled to be released with the Python 3.11.0 final version.
