### ISSUE TITLE
Windows Wheels from Christoph Gohlke Going Away Forever

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#6369]
According to Christoph Gohlke, https://www.lfd.uci.edu/~gohlke/pythonlibs/  his lab has lost funding and the unofficial python wheels collection, and likely our official windows wheels, is going away before the end of next month.

**Comment by hugovk** [comment]
> **Funding for the Laboratory for Fluorescence Dynamics has ceased. This service will be discontinued before July 2022.**

I'm very sorry to hear this. Thank you @cgohlke, for providing an invaluable service to the Python community for 12+ years. And thank you for all your work helping with Pillow too.

Do you think you'll be able to make a last set of Windows wheels for our July 1 release?

**Comment by aclark4life** [comment]
End of an era, thanks @wiredfool for reporting and thank you @cgohlke for [being there for Pillow since the beginning](https://pypi.org/project/Pillow/1.7.5/#files)!! Not to mention dozens of other projects … 🙏 

@hugovk We probably better figure something out sooner rather than later … can you or @wiredfool or @radarhere remind me how far we got on wheels doing it ourselves last time? Seems like we got close …

**Comment by aclark4life** [comment]
@hugovk @cgohlke Maybe we can push the July release up a week or so if that would help… then we'd have 3 months or so to figure out something else assuming we don't need to do a bug fix release 🤞🤷

**Comment by hugovk** [comment]
We are actually building wheels on GitHub Actions for Windows (for example, see the "dist-main" link at https://github.com/python-pillow/Pillow/actions/runs/2495168122), but as I recall there's one or two things needed for them to be on par with the release ones.

@nulano, do you know what's needed?

@aclark4life We would also like to put out wheels for 3.11 beta, see https://github.com/python-pillow/Pillow/issues/6367, and need to check if multibuild is ready to do 3.11 for Linux/macOS.

(If we wanted to overhaul our wheel building, we could look at the newish https://github.com/pypa/cibuildwheel which can do wheels for all of Windows/Linux/macOS, but that's a bit longer term thing. That could also let us automate uploading releases to PyPI.)

**Comment by cgohlke** [comment]
> Do you think you'll be able to make a last set of Windows wheels for our July 1 release?

Sure.

**Comment by nulano** [comment]
> We are actually building wheels on GitHub Actions for Windows [...] but as I recall there's one or two things needed for them to be on par with the release ones.

IIRC the only thing missing was to check all dependencies are built with the same optimizations and optional dependencies enabled.

I'm pretty sure FreeType (and other font libs) was fine when I last checked, and zlib/libjpeg-turbo do not have dependencies themselves. The build explicitly disables OpenMP for ImageQuant, but that is not included in wheels anyway. The others build with their default configs (some patched to use /MD and the correct Windows SDK), so presumably should be fine as well.

**Comment by yasamoka** [comment]
Dear @cgohlke, I sent you an Email regarding this topic. Kindly check it out, if you have time. Thank you!

**Comment by radarhere** [comment]
So is this then just a matter of updating the RELEASING checklist, to ensure that we are now using GitHub Actions? I've created PR #6458

**Comment by radarhere** [comment]
Pillow 9.3.0 has now been released - the first release with Windows wheels generated from GitHub Actions.

**Comment by radarhere** [comment]
Thanks very much to all involved in helping us make this transition.
