### ISSUE TITLE
Suddenly PIL.ImageDraw.Draw.polygon(xy, fill=None, outline=None) took more time

### ISSUE THREAD

**Issue by hemanth-mudusu** [python-pillow/Pillow#6375]
I wrote a pipeline for my project , I efficiently used this PIL library but suddenly `PIL.ImageDraw.Draw.polygon(xy, fill=None, outline=None)` took more time(approximately 5 minutes ) . can you please tell me why it happens

Hope for response

**Comment by hugovk** [comment]
You'll have to give us much more detail than that.

Please read and fill out the issue template: https://raw.githubusercontent.com/python-pillow/Pillow/main/.github/ISSUE_TEMPLATE/ISSUE_REPORT.md

**Comment by radarhere** [comment]
This might be a duplicate of #5700, in which case upgrading to Pillow >= 9.0 should fix the problem.
