### ISSUE TITLE
Add release assets without test files

### ISSUE THREAD

**Issue by Arnaudv6** [python-pillow/Pillow#6395]
Disclaimer: gentoo user here. Thus compiling most stuff from source, yet ecology-conscious.

To date, uncompressed pillow source file is 69MB, with sub-folder "test" being 66MB.
I feel like there could be a release asset "with test files" and a default one without,
so users download and uncompress a 3Mb file instead of 69Mb.

### What did you do?
compile pillow from source for my gentoo system

### What did you expect to happen?
small 3MB download + unzip

### What actually happened?
60MB download + unzip

### What are your OS, Python and Pillow versions?
* OS: gentoo
* Python: 3.10
* Pillow: 9.1.1

**Comment by radarhere** [comment]
Just to be clear, when you're talking about release assets, you're thinking of PyPI, yes?

So this new reduced file would be named, say, Pillow-9.1.1-minimal.tar.gz?

**Comment by Arnaudv6** [comment]
Hello @radarhere, thanks for quick reply!
gentoo downloads the source code `*.tar.gz` from github directly:
https://github.com/python-pillow/Pillow/releases
so that's what I was referring to, sorry that I was not clear.
I think I'd go the other way around, so packagers transparently benefit of reduced footprint:
have `Pillow-9.1.1.tar.gz` without tests, and then also `Pillow-9.1.1-with-tests.tar.gz`

In the case of [Pypi](https://pypi.org/project/Pillow/#files), wheel files are fine of course (3.3MB, so pip is OK...)
I don't know what makes most sense for source-code archive on pypi: having tests or not..
Current state does not bother me.

**Comment by Arnaudv6** [comment]
My bad, I checked the gentoo ebuild: there is an option to run the tests...
so I don't know if my proposal is such a good idea... I'll try to get in touch with the maintainer.
closing for now

**Comment by Arnaudv6** [comment]
OK, I checked with a gentoo python maintainer:
we have an option to run the tests or not at compile time,
I chose not to, but we like it that enough users choose to run them.

So should you like to provide a source archive without tests,
your naming `Pillow-9.1.1-minimal.tar.gz` is a better fit than my proposal.

I can not warrant that the CO2 economy is worth the added maintenance burden though...
(on either pillow or gentoo side). Letting this closed for now.
Again, thanks

**Comment by hugovk** [comment]
I tried uploading a `-minimal.tar.gz` version to a project on TestPyPI but:

```
WARNING  Error during upload. Retry with the --verbose option for more details.
ERROR    HTTPError: 400 Bad Request from https://test.pypi.org/legacy/
         Only one sdist may be uploaded per release.
```
