### ISSUE TITLE
"Noisy" text on a GIF with transparent background

### ISSUE THREAD

**Issue by andrey-ushakov** [python-pillow/Pillow#6406]
### What did you do?
Generated a simple GIF, on a white background and on a transparent background with a text animation (counter).

### What did you expect to happen?
Same text quality on both GIFs.

### What actually happened?
Text on a white background looks perfect:
![test_white](https://user-images.githubusercontent.com/12819691/176800550-5b454a38-5548-46ec-9e99-1b53e738f80e.gif)

Text on  transparent background looks "noisy":
![test_transparent](https://user-images.githubusercontent.com/12819691/176800597-5e94423b-8e6b-4c9e-9d7c-70a657ea4a88.gif)

### What are your OS, Python and Pillow versions?

* OS: Mac
* Python: 3.8.9
* Pillow: 9.1.1

```python
frames = []
for i in range(0, 20):
    # This works (white background):
    # frame = Image.new('RGB', (200, 200), "#FFF")

    # This renders noisy text (transparent background):
    frame = Image.new('RGBA', (200, 200), (255,0,0,0))

    draw = ImageDraw.Draw(frame)
    draw.text((90, 90), str(i), font=self.font_title, fill="#000000")
    frames.append(frame)

frames[0].save('./test.gif',
    format='GIF',
    save_all=True,
    append_images=frames[1:],
    optimize=False,
    disposal=2,
    duration=100,
    loop=0)
```

How can I generate GIF with a transparent background and sharp text?

**Comment by radarhere** [comment]
Here's the problem. If you run
```python
from PIL import Image, ImageDraw, ImageFont
font = ImageFont.truetype('/System/Library/Fonts/Supplemental/Tahoma.ttf', 48)
frame = Image.new('RGBA', (200, 200), (255,0,0,0))

draw = ImageDraw.Draw(frame)
draw.text((90, 90), '0', font=font, fill="#000000")
frame.save("0.png")
```
and then zoom in on the PNG to see the text drawn on the transparent background, you will see that the edge pixels of the text are partially transparent.

GIF only supports 1 transparent color, and does not support partial transparency. This is a limitation of the format.

Here is a workaround that might suit your purposes. I've added code to convert all the partially transparent pixels into the range of opaque gray to opaque black.

```python
from PIL import Image, ImageDraw, ImageFont
frames = []
font = ImageFont.truetype('/System/Library/Fonts/Supplemental/Tahoma.ttf', 48)
for i in range(0, 20):
    # This renders noisy text (transparent background):
    frame = Image.new('RGBA', (200, 200), (255,0,0,0))

    draw = ImageDraw.Draw(frame)
    draw.text((90, 90), str(i), font=font, fill="#000000")
    
    # Set all partially transparent pixels to opaque
    for x in range(frame.width):
        for y in range(frame.height):
            rgba = frame.getpixel((x, y))
            if 0 < rgba[3] < 255:
                c = 127-rgba[3]//2
                frame.putpixel((x, y), (c, c, c, 255))
    
    frame.save(str(i)+'.png')
    frames.append(frame)

frames[0].save('./noisy2.gif',
    format='GIF',
    save_all=True,
    append_images=frames[1:],
    optimize=False,
    disposal=2,
    duration=100,
    loop=0)
```

**Comment by nulano** [comment]
An alternative option is to render text in 1 bit mode, by adding `draw.fontmode = "1"` between the two `draw` lines.
Although this still produces an aliased edge, it tells the font driver to optimize for an output not supporting partial transparency.

With `draw.fontmode = "1"`:
![fontmode_1](https://user-images.githubusercontent.com/3819630/176853365-bb43f8bd-4baa-48c6-b359-f0ffbfa157fe.gif)

With `draw.fontmode = "L"` (the default):
![fontmode_L](https://user-images.githubusercontent.com/3819630/176853382-74587734-36f8-474d-bb3d-1e45faa44ef2.gif)

**Comment by andrey-ushakov** [comment]
That's really, really helpful!! Thank you guys!!

**Comment by radarhere** [comment]
This should be faster than my previous version, as it only processes the pixels of the text.

```python
from PIL import Image, ImageDraw, ImageFont
frames = []
font = ImageFont.truetype('/System/Library/Fonts/Supplemental/Tahoma.ttf', 48)
for i in range(0, 20):
	# This renders noisy text (transparent background):
	frame = Image.new('RGBA', (200, 200), (255,0,0,0))

	draw = ImageDraw.Draw(frame)
	draw.text((90, 90), str(i), font=font, fill="#000000")

	# Set all partially transparent pixels to opaque
	x1, y1, x2, y2 = font.getbbox(str(i))
	for x in range(90+x1, 90+x2):
		for y in range(90+y1, 90+y2):
			rgba = frame.getpixel((x, y))
			if 0 < rgba[3] < 255:
				c = 127-rgba[3]//2
				frame.putpixel((x, y), (c, c, c, 255))

	frames.append(frame)

frames[0].save('./noisy2.gif',
	format='GIF',
	save_all=True,
	append_images=frames[1:],
	optimize=False,
	disposal=2,
	duration=100,
	loop=0)
```

**Comment by andrey-ushakov** [comment]
Very helpful, Thank you!!
