### ISSUE TITLE
ValueError: height and width must be > 0

### ISSUE THREAD

**Issue by javohirss** [python-pillow/Pillow#6419]
```python
--> 130             )
    131             resized_img = distorted_img.resize(
--> 132                 (new_width, size - vertical_margin), Image.ANTIALIAS
    133             )
    134             resized_mask = distorted_mask.resize((new_width, size - vertical_margin), Image.NEAREST)

[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in resize(self, size, resample, box, reducing_gap)
   1881         if self.mode in ["LA", "RGBA"]:
   1882             im = self.convert(self.mode[:-1] + "a")
-> 1883             im = im.resize(size, resample, box)
   1884             return im.convert(self.mode)
   1885 

[/usr/local/lib/python3.7/dist-packages/PIL/Image.py](https://localhost:8080/#) in resize(self, size, resample, box, reducing_gap)
   1903                 )
   1904 
-> 1905         return self._new(self.im.resize(size, resample, box))
   1906 
   1907     def reduce(self, factor, box=None):
ValueError: height and width must be > 0

```

**Comment by hugovk** [comment]
What size is your image? Make sure the width and height are greater than 0.

**Comment by javohirss** [comment]
I generate data images from trdg  [https://github.com/Belval/TextRecognitionDataGenerator/tree/master/trdg](url) 
Full error:
`ValueError                                Traceback (most recent call last)
<ipython-input-20-ceda3a2a62b1> in <module>()
      1 img_arr = []
----> 2 for img, lbl in generator:
      3   print(7)

4 frames
/usr/local/lib/python3.7/dist-packages/trdg/generators/from_strings.py in __next__(self)
     75 
     76     def __next__(self):
---> 77         return self.next()
     78 
     79     def next(self):

/usr/local/lib/python3.7/dist-packages/trdg/generators/from_strings.py in next(self)
    111                 self.stroke_width,
    112                 self.stroke_fill,
--> 113                 self.image_mode,
    114             ),
    115             self.strings[(self.generated_count - 1) % len(self.strings)],

/usr/local/lib/python3.7/dist-packages/trdg/data_generator.py in generate(cls, index, text, font, out_dir, size, extension, skewing_angle, random_skew, blur, random_blur, background_type, distorsion_type, distorsion_orientation, is_handwritten, name_format, width, alignment, text_color, orientation, space_width, character_spacing, margins, fit, output_mask, word_split, image_dir, stroke_width, stroke_fill, image_mode)
    130             )
    131             resized_img = distorted_img.resize(
--> 132                 (new_width, size - vertical_margin), Image.ANTIALIAS
    133             )
    134             resized_mask = distorted_mask.resize((new_width, size - vertical_margin), Image.NEAREST)

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in resize(self, size, resample, box, reducing_gap)
   1881         if self.mode in ["LA", "RGBA"]:
   1882             im = self.convert(self.mode[:-1] + "a")
-> 1883             im = im.resize(size, resample, box)
   1884             return im.convert(self.mode)
   1885 

/usr/local/lib/python3.7/dist-packages/PIL/Image.py in resize(self, size, resample, box, reducing_gap)
   1903                 )
   1904 
-> 1905         return self._new(self.im.resize(size, resample, box))
   1906 
   1907     def reduce(self, factor, box=None):

ValueError: height and width must be > 0`

**Comment by hugovk** [comment]
Check your values of `(new_width, size - vertical_margin)` in `/usr/local/lib/python3.7/dist-packages/trdg/data_generator.py`, one of them is zero.

This likely isn't a Pillow issue, your code or TextRecognitionDataGenerator is likely passing bad input to Pillow. You're probably better off opening an issue at https://github.com/Belval/TextRecognitionDataGenerator/issues

**Comment by gaurav-95** [comment]
I'm having a similar issue when using moviepy

**Comment by radarhere** [comment]
Would you be able to post a self-contained example?

**Comment by gaurav-95** [comment]
I've traced the issue to being a function that produces the 0 output. Not an issue with pillow. Sorry and Thanks for trying to help.

**Comment by dreadlocko** [comment]
As I see automatic1111 is clear trash
