### ISSUE TITLE
9.2.0 breaks compatibility to pass PIL.Image to tensorflow (tf.reshape)

### ISSUE THREAD

**Issue by sla-te** [python-pillow/Pillow#6422]
On passing it tf.reshape throws:
```
Attempt to convert a value (<PIL.Image.Image image mode=RGB size=100x100 at 0x153B2CF8EE0>) with an unsupported type (<class 'PIL.Image.Image'>) to a Tensor.
```

**Comment by sla-te** [comment]
> Could we get a self-contained example? A block of code that we can run, by itself, without any inputs (or with those inputs attached), to demonstrate the error?

Thats a little difficult, as you would need a model, that takes images as input

> And you're saying that the error doesn't occur with Pillow 9.1.1?
Correct, just tested again to make sure - 9.20 throws and 9.1.1 works

**Comment by radarhere** [comment]
Testing with
```python
from PIL import Image
import tensorflow as tf

im = Image.new("L", (1, 1))
tf.reshape(im, (1, 1))
```
I find that it #6394 is what caused the change.

If you would like an immediate workaround, you can convert the Pillow image to a NumPy array first.

```python
from PIL import Image
import tensorflow as tf
import numpy as np

im = Image.new("L", (1, 1))
arr = np.array(im)
tf.reshape(arr, (1, 1))
```

**Comment by radarhere** [comment]
I've created https://github.com/tensorflow/tensorflow/issues/56723 to try and see if TensorFlow is interested in supporting `__array_interface__`.

**Comment by radarhere** [comment]
@sla-te to explain a bit, we never intentionally supported the conversion to TensorFlow that you're performing.

We have a mechanism to allow conversion to NumPy. For a while there, we altered it to workaround a NumPy bug, and during that period of time, conversion to TensorFlow started working. The NumPy bug has been fixed, so we switched back, and now conversion to TensorFlow has stopped working.

So while we could add an `__array__` method specifically for the sake of TensorFlow, it could also be solved from their side by adding support for `__array_interface__`. Or, you could use `tf.reshape(np.array(im), (1, 1))` as a workaround.

**Comment by radarhere** [comment]
@sla-te are you happy for this to be closed? You could instead monitor the TensorFlow issue.

**Comment by radarhere** [comment]
The TensorFlow issue has been resolved, fixed in https://github.com/tensorflow/tensorflow/commit/8b3369b3cb4c3ecc3e0059a550c2d7cad136d371. This should be fixed in a future release of TensorFlow.
