### ISSUE TITLE
Set from white to transparent for many images

### ISSUE THREAD

**Issue by berik123** [python-pillow/Pillow#6424]
Thanks to the authors of the project, I'm sorry, I have no experience with python, I took the code to replace white with transparent, everything works. But I have more than 1000 images, how do I change the code to work with the folder.
I will be very grateful if you help, and I, in turn, will help the project financially.
Here is the code

```python
from PIL import Image

def convertImage():
	img = Image.open("./SS/image.png")
	img = img.convert("RGBA")

	datas = img.getdata()

	newData = []

	for item in datas:
		if item[0] == 255 and item[1] == 255 and item[2] == 255:
			newData.append((255, 255, 255, 0))
		else:
			newData.append(item)

	img.putdata(newData)
	img.save("./New/New.png", "PNG")
	print("Successful")

convertImage()
```

**Comment by radarhere** [comment]
Here is a modified version of your code, using [`glob.glob`](https://docs.python.org/3/library/glob.html#glob.glob). It will open all the files under the "SS" directory.

I've presumed that you would like to save a copy of the output images in the "New" directory with the same name as the original, so I've also modified the code to use [`os.path.join`](https://docs.python.org/3/library/os.path.html#os.path.join) and [`os.path.basename`](https://docs.python.org/3/library/os.path.html#os.path.basename).

```python
from PIL import Image

def convertImage(path):
	img = Image.open(path)
	img = img.convert("RGBA")

	datas = img.getdata()

	newData = []

	for item in datas:
		if item[0] == 255 and item[1] == 255 and item[2] == 255:
			newData.append((255, 255, 255, 0))
		else:
			newData.append(item)

	img.putdata(newData)
	img.save(os.path.join("New", os.path.basename(path)), "PNG")
	print("Successful")

import os, glob
for path in glob.glob("SS/*"):
	convertImage(path)
```

**Comment by radarhere** [comment]
While contributing financially would be a kind thing to do, if you're new to programming, it is worth understanding that it is not a requirement when answering questions - there are many communities like ours on the web where people freely try to help others in their spare time.

If you have questions about Python programming generally, you might find https://stackoverflow.com/ to be useful.

**Comment by berik123** [comment]
Thank you for your help! Everything works!
