### ISSUE TITLE
TypeError: a bytes-like object is required, not 'PhotoImage'

### ISSUE THREAD

**Issue by VERISBABY** [python-pillow/Pillow#6426]
### What did you do?
I use `ImageTk.PhotoImage(file=fff)`, even i change just to `PhotoImage` to open images. I tried using `Image.open()` but it only works with `ImageTk.PhotoImage`/ `PhotoImage`.
### What did you expect to happen?
I want to get those images to manipulate them (like, take from one place to paste to another...)
### What actually happened?
It got an error : TypeError: a bytes-like object is required, not 'PhotoImage'. It seems it cannot read bytes like normal images.
### What are your OS, Python and Pillow versions?
Win10, Python 3.10.5, PIL 9.2.0

My code is quite long and complex, but I'll show a snippet. 
```python
    for file in emoji_files:
        full_path = os.path.join(emoji_dir, file)
        image = ImageTk.PhotoImage(file=full_path)
        smilie_images.append(image)
```
and then i get those `PhotoImage` objs to send through mail and paste to another widget in `Tkinter` like normal images.

**Comment by radarhere** [comment]
Hi. If I run
```python
from PIL import Image, ImageTk
import tkinter
root = tkinter.Tk()
ImageTk.PhotoImage(file="test.jpg")
```
on my machine, it works without a problem.

Could you paste the full traceback? It would helpful to see the line the error is coming from.
