### ISSUE TITLE
Unsupported BMP bitfields layout error

### ISSUE THREAD

**Issue by usernamefreaks** [python-pillow/Pillow#6435]
I have a bitmap that can be opened by Ristretto Image Viewer (a Linux program), but it can't be opened by Pillow. I originally encountered this with Pillow version 5.1.0. I upgraded my package to v8.4.0 to see if the issue would resolve, but the same error is raised. In v8.4.0, this error is raised on line 203 of BmpImagePlugin.py.

Upon closer inspection, it seems that the bitmap file I was trying to open has `file_info['header_size'] == 124`, `file_info['compression'] == 3`, `file_info['bits'] == 32`, and `file_info['rgba_mask'] == (0xff000000, 0xff0000, 0xff00, 0xff)`.

Does my bmp file follow the BMP file format? If so, can it be supported in a future version? Thanks.

**Comment by radarhere** [comment]
Your BMP file seems perfectly valid to me. I've created PR #6436 to add support for it.

It would be ideal if you could take that branch, install Pillow from it, and load your image. That would just confirm that there aren't any other surprises. Alternatively, you could upload your image here.

**Comment by usernamefreaks** [comment]
Yep, everything works now after I applied your PR #6436. I will use this diff for now. Thank you!
