### ISSUE TITLE
SystemError: unknown raw mode after a lot of draws (both text and lines)

### ISSUE THREAD

**Issue by chas11man** [python-pillow/Pillow#646]
I am taking a large white gif and drawing a lot of lines and texts onto it of different sizes and fonts.  It works fine up to a certain point, but one too many draws causes the unknown raw mode error on save.

```
File "draw/card.py", line 13, in save
  self.image.save(os.path.join(os.path.dirname(os.path.abspath(__file__)), '%s.gif' % file_name), 'gif')
File ".../local/lib/python2.7/site-packages/PIL/Image.py", line 1564, in save
  save_handler(self, fp, filename)
File ".../local/lib/python2.7/site-packages/PIL/GifImagePlugin.py", line 317, in _save
  ImageFile._save(imOut, fp, [("gif", (0,0)+im.size, 0, rawmode)])
File ".../local/lib/python2.7/site-packages/PIL/ImageFile.py", line 473, in _save
  e = Image._getencoder(im.mode, e, a, im.encoderconfig)
File ".../local/lib/python2.7/site-packages/PIL/Image.py", line 413, in _getencoder
  return encoder(mode, *args + extra)
SystemError: unknown raw mode
```

**Comment by radarhere** [comment]
I don't suppose that anyone could provide a few lines of code to replicate the problem?

**Comment by amarynets** [comment]
I have this bug also. And solution
> before saving the image as a .gif, convert it to mode 'P'

can't help me, because .gif image now has 'P' mode. Here is my code

```
url = 'https://cdn.technologynetworks.com/tn/images/adverts/malvern-inline-rectangle-banner-31st-jan-2017.gif'
response = urlopen(url).read()
path = io.BytesIO(response)
image = Image.open(path)

output = io.BytesIO()
image = image.convert('P')
image.save(output, image.format, save_all=True)
```
After this, save image to file/db

**Comment by Savar** [comment]
the example image from @amarynets has a `rawmode` of `RGBA;L` but in https://github.com/python-pillow/Pillow/blob/03b9d718fcc39b9ff7af0da18cf3841ab78d1359/_imaging.c#L1413 the Unpacker to be searched has a hard-coded `mode` of `RGB` but the only mapping valid is `mode(RGBA) => rawmode(RGBA;L)` according to https://github.com/python-pillow/Pillow/blob/03b9d718fcc39b9ff7af0da18cf3841ab78d1359/libImaging/Unpack.c#L1235 so the method in https://github.com/python-pillow/Pillow/blob/03b9d718fcc39b9ff7af0da18cf3841ab78d1359/libImaging/Unpack.c#L1364 will always return `NULL` so if anybody can tell me why the unpacker is hardcoded to RGB?

**Comment by Savar** [comment]
so if you add after

https://github.com/python-pillow/Pillow/blob/03b9d718fcc39b9ff7af0da18cf3841ab78d1359/_imaging.c#L1413

a second round with `RGBA` as `mode`

```c
    if (!unpack) {
        unpack = ImagingFindUnpacker("RGBA", rawmode, &bits);
    }
    if (!unpack) {
        PyErr_SetString(PyExc_ValueError, wrong_raw_mode);
        return NULL;
    }
```

then the `image.save()` from @amarynets doesn't fail anymore

**Comment by wiredfool** [comment]
@amarynets issue is not related to the earlier issue, which is an unrecognized raw mode after doing many drawing operations to the image, essentially a memory corruption issue. 

At any rate, it's fixed with the changes in #2374

**Comment by wiredfool** [comment]
Hoisted discussion of @amarynets and @Savar's issue to #2433, as there's another bug lurking in there somewhere.

**Comment by radarhere** [comment]
#2433 is now resolved. So, just to be clear, the problems reported by @amarynets and @savar are now fixed, and this issue is back to just the original problem reported by @chas11man. However, my problem with addressing this is that there is no code example here, only a traceback.

**Comment by radarhere** [comment]
Closing due to lack of an example.

**Comment by wiredfool** [comment]
Apparently I had a repro at one point, and now I have enough tools to probably find the bug.  It's a matter of finding the repro that I had and confirming that it's still an issue. 

Not that we really need this opened again.
