### ISSUE TITLE
Pillow not importing in VSCode on macOS with Python 3.10.5

### ISSUE THREAD

**Issue by manipadam** [python-pillow/Pillow#6488]
I installed pillow correctly. But when I try to import Pillow in VScode it says module not found. But if I change the interpreter from 3.10.5 to 3.9.13 the error disappears.

The following is how I imported PIL

```from PIL import Image```

Is this a bug or am I doing something wrong?

**Comment by radarhere** [comment]
It sounds like Pillow is installed in Python 3.9, but not Python 3.10.

Could you provide some detail on how you installed Pillow?

**Comment by radarhere** [comment]
To answer your question, no, I don't expect this to be a bug. Simply that Pillow has not been installed in the specific version you're using.
