### ISSUE TITLE
ChecksumMismatchError for Pillow 9.2 in Conda

### ISSUE THREAD

**Issue by fh-katherinebargar** [python-pillow/Pillow#6495]
It seems like the md5 is incorrect in Conda for pillow 9.2. Specifically I'm interested in py3.7 and osx-64.

### What did you do?
Check the info in Conda for Pillow 9.2, this is for py3.7 and osx-64.

![Screen Shot 2022-08-12 at 10 15 38 AM](https://user-images.githubusercontent.com/106112765/184372280-22cd44e3-5e70-4ac7-847a-77ebf338bb44.png)

Run `md5 ~/Downloads/pillow-9.2.0-py37h1eb1bbc_0.tar.bz2`, this is the same file as in the screenshot.

### What did you expect to happen?
The md5s to match.

### What actually happened?
Conda thinks the md5 is a3173bdcbe36a8ca1d2b9e90e9caf093 but the actual file has an md5 of 79e8c2dac49e59b95a60c5dbab1ccdd8 .

### What are your OS, Python and Pillow versions?

* OS: Macos
* Python: 3.7
* Pillow: 9.2

**Comment by nulano** [comment]
I just downloaded the file from https://anaconda.org/conda-forge/pillow/files?sort=basename&sort_order=desc&version=9.2.0 and the hash matches for me:
```bash
$ md5sum.exe pillow-9.2.0-py37h1eb1bbc_0.tar.bz2
a3173bdcbe36a8ca1d2b9e90e9caf093 *pillow-9.2.0-py37h1eb1bbc_0.tar.bz2
```

The Conda Pillow package is not maintaned in this repository, you might get a better answer if you follow the help page for Anaconda: https://docs.anaconda.com/anacondaorg/help-support/

**Comment by radarhere** [comment]
@fh-katherinebargar does that answer your question? If this is a problem, it's not one that's in our power to fix.

**Comment by fh-katherinebargar** [comment]
Yes! Thanks for investigating, I'll follow up with the feedstock owners.
