### ISSUE TITLE
Possible missing "PA" check

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6502]
https://github.com/python-pillow/Pillow/blob/5a087ccbb9b48cba04276fd1b7d0cec93488b7c3/src/PIL/PyAccess.py#L59-L62

This code saves a reference to the image palette, but only for "P" mode images. I think it should probably check for "PA" here too. This saved palette is used later in this class, but again only for "P", not "PA".

https://github.com/python-pillow/Pillow/blob/5a087ccbb9b48cba04276fd1b7d0cec93488b7c3/src/PIL/PyAccess.py#L91-L97

I haven't checked if this palette reference is used outside of this class, though it is supposed to be private so hopefully not.

**Comment by radarhere** [comment]
The code you're discussing was added in #3519 - "Allow RGB and RGBA values for P image putpixel". In code, what that allowed was
```python
from PIL import Image
im = Image.new("P", (1, 1))
im.putpixel((0, 0), (255, 0, 0))
```

So you are requesting that this also work for PA.
```python
from PIL import Image
im = Image.new("PA", (1, 1))
im.putpixel((0, 0), (255, 0, 0))
```

I've created PR #6504 for this.
