### ISSUE TITLE
ZIP compression for TIFF files

### ISSUE THREAD

**Issue by ianengelbrecht** [python-pillow/Pillow#6512]
Adobe Lightroom has an option to compress TIFF files using ZIP compression, which [according to this source](https://havecamerawilltravel.com/tiff-image-compression/) is a better option than LZW compression. Could this be added as an option? I don't see it listed in the[ tiff compression options](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#saving-tiff-images) for Pillow.

**Comment by cgohlke** [comment]
`tiff_adobe_deflate` is the same as ZIP compression.

**Comment by radarhere** [comment]
https://openpreservation.org/blogs/compression-at-your-discretion/
> The TIFF format and lossless compression
> ...
> Since then support has been introduced for other compression methods, including the one which we were asked to investigate as to its effectiveness – namely [Deflate](https://en.wikipedia.org/wiki/DEFLATE), more commonly referred to as Zip compression.

https://en.wikipedia.org/wiki/ZIP_(file_format)
> The ZIP file format permits a number of compression [algorithms](https://en.wikipedia.org/wiki/Algorithms), though [DEFLATE](https://en.wikipedia.org/wiki/DEFLATE) is the most common.

**Comment by ianengelbrecht** [comment]
Thanks guys!
