### ISSUE TITLE
Parameterize tests

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6525]
Currently many of the pytest tests start with a loop over a list of some values, with all of the test code inside this loop.

https://github.com/python-pillow/Pillow/blob/4dd678a2e77a5111ca388187e599b986b7ad43bc/Tests/test_image_paste.py#L104-L112

Instead, we can use pytest's [`@pytest.mark.parametrize` annotation](https://docs.pytest.org/en/latest/how-to/parametrize.html) to handle this looping automatically.

https://github.com/python-pillow/Pillow/blob/b236c61c04c0f6a6cc1ac24f5a56e327e890ad9c/Tests/test_image_paste.py#L106-L114

The benefit of using pytest to do this is that if a test fails, it tells you which parameter it failed with. Also pytest will test with each of the parameters instead of stopping on the first failure.

I've already made this change for one file (#6519), but there are a lot more tests that could benefit from this annotation.

**Comment by radarhere** [comment]
I've done a pass over the tests, and created #6526. Do you think there is still more work to be done?

**Comment by Yay295** [comment]
I think there are more tests that can be parametrized. I left a comment with some of them on your pull request.

**Comment by radarhere** [comment]
I've applied your suggestions.

**Comment by radarhere** [comment]
#6531 is the next PR that adds parametrizations.

**Comment by radarhere** [comment]
All three PRs have now been merged. Is there still more work to be done?

**Comment by Yay295** [comment]
Possibly. I haven't looked through all of the test files, but there's probably a few more that could be parametrized.

**Comment by radarhere** [comment]
If there's nothing specific, this it's hard to know when this is done.

I've done another pass over the tests, and created PR #6634. I'm going to say that PR resolves this.

**Comment by Yay295** [comment]
I've noticed that some of the parameters use tuples, and some use lists. I don't think it makes a difference in most cases, but is there one format we should try to use everywhere?

**Comment by radarhere** [comment]
Since the parameters are an immutable series of items, [tuples.](https://stackoverflow.com/a/1708538)

**Comment by Yay295** [comment]
I've created #6653 to use tuples more often (plus some other things I noticed).

**Comment by homm** [comment]
@radarhere
> Since the parameters are an immutable series of items, [tuples.](https://stackoverflow.com/a/1708538)

The [accepted answer](https://stackoverflow.com/a/1708610/253146) is much better than the one you are referring. Immutability is a property of tuples, but not a purpose. Tuples are intended to store heterogeneous data. When you have (x, y, z) or (Name, Age, Vocation) in your program, it doesn't make sense to add another name in the end or change the order. It just different types of data. On the other hand, lists are used for homogeneous data. It worth nothing to add a person to the list of the persons or swap two persons in the list: it will remain the list of persons.

**Comment by radarhere** [comment]
My understanding is that tuples are more efficient than lists, but presumably that difference is minor, so if @homm has thoughts about what makes more sense stylistically, then I'm happy to go with that. If anything, I just hope to avoid going back and forth on this with [large PRs](https://github.com/python-pillow/Pillow/pull/6653#issuecomment-1367995025).
