### ISSUE TITLE
psd paths not correctly identified

### ISSUE THREAD

**Issue by dorphalsig** [python-pillow/Pillow#6530]
Hi,  when attempting to identify which  PSD paths are present in a TIF file Pillow fails to identify some cases.  The attached image has a path (7d0 according to exiftool), however pillow does not recognize it.

PILLOW code:
```python
from PIL import Image
img=Image.open("image.tif")
psd_paths = range(0x07d0, 0x0bb5)
exif_tags = list(img.getexif().keys())
print ("PSD Paths Found" if any(path in exif_tags for path in psd_paths) else "No PSD Paths Found")
```
returns _No PSD Paths found._

(exif_tags is [256, 2
57, 258, 259, 262, 273, 274, 277, 278, 279, 282, 283, 284, 296, 305, 306, 33723, 700, 317, 34377, 37724, 34665, 34675, 254] )

Whereas
`exiftool -config photoshop_paths.config -allpaths image.tif`

returns _Path 7d0                        : (Binary data 426 bytes, use -b option to extract)_

attached exif, its config file and the image file in question. 

I'm using Pillow 9.2

I renamed the .exe file to .ecse so it wont trigger any alarms. Since its also not a good idea to run executables from unknown sources exiftool can be downloaded from https://exiftool.org/ and the corresponding config file can be found at https://raw.githubusercontent.com/exiftool/exiftool/master/config_files/photoshop_paths.config

**Comment by hugovk** [comment]
No need to attach the exe, but please could you try attaching the config and image again? Zipping might help.

**Comment by dorphalsig** [comment]
[image and exif config.zip](https://github.com/python-pillow/Pillow/files/9415189/image.and.exif.config.zip)

Hi Hugovk, here you go. Thanks for your help!

**Comment by radarhere** [comment]
We've had actually had very similar question about PSD paths before - #6025.

`exiftool -v -v image.tif` shows that there is a "PhotoshopSettings (SubDirectory)", "Tag 0x8649".

`img.getexif()[0x8649]` is just a single string though. For that previous issue, I created `img.get_photoshop_blocks()`.

I suggest that you run
```python
from PIL import Image
img=Image.open("image.tif")
psd_paths = range(0x07d0, 0x0bb5)
blocks = list(img.get_photoshop_blocks().keys())
print ("PSD Paths Found" if any(path in blocks for path in psd_paths) else "No PSD Paths Found")
```

**Comment by dorphalsig** [comment]
Worked like a charm! many thanks
