### ISSUE TITLE
Values of some pixels are different while opening a picture using Pillow 9.2.0 and Pillow 8.2.0

### ISSUE THREAD

**Issue by nakairika** [python-pillow/Pillow#6536]
### What did you do?

I opened the first image in coco dataset val2017 in two different servers, installing Pillow==9.2.0 and Pillow==8.2.0, running the same code

```python
from PIL import Image
import numpy as np
image = Image.open("val2017/000000000139.jpg").convert("RGB")
np.array(image)
```

### What did you expect to happen?

They are expected to be the same array, so i use codes below to compare the results 

```python
a = (image920 == image820)
a.any()
```
Outputs should be "False" ,which means there's no difference between image920 and image820

### What actually happened?

The output is True, so I run the codes below to show where the difference is

```python
np.argwhere(a==False)
>>>array([[ 50, 290,   1],
       [ 88, 219,   1],
       [ 91, 236,   1],
       [ 95, 252,   1],
       [115, 400,   1],
       [126, 332,   1],
       [205, 407,   1],
       [207, 260,   1],
       [253, 490,   1],
       [271, 412,   1],
       [324, 568,   1],
       [324, 578,   1],
       [351, 557,   1],
       [356, 560,   1],
       [385, 580,   1]])
```
and md5 are different
![image](https://user-images.githubusercontent.com/35144242/186616984-81776954-b21a-44bc-9b8c-f863a547f7d1.png)

ps, it's a small part of a cv task, and it looks like result of Pillow==8.2.0 is correct

### What are your OS, Python and Pillow versions?

* OS:  linux 
* Python: 3.7.5
* Pillow: 9.2.0 and 8.2.0

**Comment by radarhere** [comment]
Hi. I think you're experiencing the same thing as #6262 and #6113.

https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#switched-to-libjpeg-turbo-in-macos-and-linux-wheels
> **Switched to libjpeg-turbo in macOS and Linux wheels**
> The Pillow wheels from PyPI for macOS and Linux have switched from libjpeg to libjpeg-turbo. It is a fork of libjpeg, popular for its speed.
>
> Because different JPEG decoders load images differently, JPEG pixels may be altered slightly with this change.

**Comment by nakairika** [comment]
thanks for quick reply, this can be closed
