### ISSUE TITLE
Save TGA with Compression / RLE

### ISSUE THREAD

**Issue by SmittyWerbenJJ** [python-pillow/Pillow#6545]
In the Documentation we have no information about how to apply compression for TGA files. It just states that it is possible,but not how to do it.

 https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html?highlight=tga#tga
> TGA
Pillow reads and writes TGA images containing L, LA, P, RGB, and RGBA data. Pillow can read and write both uncompressed and run-length encoded TGAs.

Now I find for other file formats we have the option to set `compression="someValue"` while calling Image.save(), to define file compression.

The only hint on how to use this, I found from this test case which calls for `rle=rle` and it actually works
https://github.com/python-pillow/Pillow/blob/cb6c94123e20c76a9e7c36601419ce1415bb69e3/Tests/test_file_tga.py#L26

Is this the only way to do TGA compression? Is this not written in the documentation (I could not find it)?

**Comment by radarhere** [comment]
You can use  the `compression` argument.
https://github.com/python-pillow/Pillow/blob/ad7be550aa539dc4c79da928dad071cf0150b731/Tests/test_file_tga.py#L217

I've created PR #6546 to add this to the documentation.
