### ISSUE TITLE
Green background in CMYK mode

### ISSUE THREAD

**Issue by bagcivan** [python-pillow/Pillow#6563]
### What did you do?
I'm trying to download image from url and save it.

### What did you expect to happen?
I was expecting for it to all download as it appears on the site.

### What actually happened?
I can download image that are in RGB or RGBA modes. But in CMYK mode download as green background.

### What are your OS, Python and Pillow versions?

* OS: Windows 11
* Python: 3.9.12
* Pillow:  9.2.0

```python
img_data = s.get(url, stream = True)
img_down = Image.open(img_data.raw)
img_down.convert('RGBA').save('img.png', "PNG")
```
### Mode : RGBA
![Y3738A6](https://user-images.githubusercontent.com/5860475/188841254-10956619-5af4-44ee-a9bc-274de87c8e9d.png)
### Mode : CMYK
![Y7454A6](https://user-images.githubusercontent.com/5860475/188841261-149e2619-4cf5-448e-a6a6-20ba70860bd8.png)

**Comment by radarhere** [comment]
Could we get the URL of the CMYK image?

**Comment by bagcivan** [comment]
> Could we get the URL of the CMYK image?

It downloading from a logged in site, but ı can upload the file i downloaded manually.
Can you download it from here https://easyupload.io/28ey15

The mode of the file looks like this in Spyder IDE
![2022-09-07 12_53_49-Clipboard](https://user-images.githubusercontent.com/5860475/188849358-8e46e12a-5729-4c93-8b75-2780885f5573.png)

**Comment by radarhere** [comment]
The image you provided is
![cmyk](https://user-images.githubusercontent.com/3112309/188852978-5907955a-582a-4f67-bbe3-8da8b861e942.jpg)

Running the following code,
```python
from PIL import Image
im = Image.open("cmyk.jpg")
im.convert("RGBA").save("rgba.png")
```
I get
![rgba](https://user-images.githubusercontent.com/3112309/188853101-a28822f5-c135-4be7-87ae-98556f46dd8a.png)

So I don't see the problem that you're experiencing. If you run my code on a local copy of the JPEG, does the problem occur?

**Comment by bagcivan** [comment]
> 
This is a bit confusing. When I run the your codes on the same file, the problem occur. I also tried it on a different computer. I have the same problem.

![rgba](https://user-images.githubusercontent.com/5860475/188855861-c675b8c7-bf97-42bd-a83b-baa7c076ee73.png)

**Comment by radarhere** [comment]
Hmm. It also works for me when I run the test in our CIs.

To try and narrow down which step the problem occurs at, could you run this code and report what it says?
```python
from PIL import Image
im = Image.open("cmyk.jpg")
print("Loaded:", im.getpixel((0, 0)))  # (0, 0, 0, 0)

converted = im.convert("RGBA")
print("Converted:", converted.getpixel((0, 0)))  # (255, 255, 255, 255)

converted.save("rgba.png")
reloaded = Image.open("rgba.png")
print("Reloaded:", reloaded.getpixel((0, 0)))  # (255, 255, 255, 255)
```

**Comment by bagcivan** [comment]
> Hmm. It also works for me when I run the test in our CIs.
> 
> To try and narrow down which step the problem occurs at, could you run this code and report what it says?
> 
> ```python
> from PIL import Image
> im = Image.open("cmyk.jpg")
> print("Loaded:", im.getpixel((0, 0)))  # (0, 0, 0, 0)
> 
> converted = im.convert("RGBA")
> print("Converted:", converted.getpixel((0, 0)))  # (255, 255, 255, 255)
> 
> converted.save("rgba.png")
> reloaded = Image.open("rgba.png")
> print("Reloaded:", reloaded.getpixel((0, 0)))  # (255, 255, 255, 255)
> ```

I added the results to the side of the code. 

```python
from PIL import Image
im = Image.open("cmyk.jpg")
print("Loaded:", im.getpixel((0, 0)))  # (0, 0, 0, 0) ## Loaded: (255, 121, 255, 0)

converted = im.convert("RGBA")
print("Converted:", converted.getpixel((0, 0)))  # (255, 255, 255, 255) ## Converted: (0, 134, 0, 255)

converted.save("rgba.png")
reloaded = Image.open("rgba.png")
print("Reloaded:", reloaded.getpixel((0, 0)))  # (255, 255, 255, 255) ##Reloaded: (0, 134, 0, 255)
```

**Comment by radarhere** [comment]
Ok, so the JPEG is opened with a green color. This isn't a problem to do with converting.

What version of libjpeg are you using?
```python
>>> from PIL import features
>>> features.pilinfo()
```

**Comment by bagcivan** [comment]
> Ok, so the JPEG is opened with a green color. This isn't a problem to do with converting.
> 
> What version of libjpeg are you using?
> 
> ```python
> >>> from PIL import features
> >>> features.pilinfo()
> ```

--------------------------------------------------------------------
Pillow 9.2.0
Python 3.9.12 (main, Apr  4 2022, 05:22:27) [MSC v.1916 64 bit (AMD64)]
--------------------------------------------------------------------
Python modules loaded from C:\Users\tevfi\anaconda3\lib\site-packages\PIL
Binary modules loaded from C:\Users\tevfi\anaconda3\lib\site-packages\PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 9.2.0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.10.4
*** LITTLECMS2 support not installed
--- WEBP support ok, loaded 1.2.0
--- WEBP Transparency support ok
*** WEBPMUX support not installed
*** WEBP Animation support not installed
--- JPEG support ok, compiled for 9.0
*** OPENJPEG (JPEG2000) support not installed
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.12
--- LIBTIFF support ok, loaded 4.4.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
*** XCB (X protocol) support not installed
--------------------------------------------------------------------
BLP
Extensions: .blp
Features: open, save, encode
--------------------------------------------------------------------
BMP image/bmp
Extensions: .bmp
Features: open, save
--------------------------------------------------------------------
BUFR
Extensions: .bufr
Features: open, save
--------------------------------------------------------------------
CUR
Extensions: .cur
Features: open
--------------------------------------------------------------------
DCX
Extensions: .dcx
Features: open
--------------------------------------------------------------------
DDS
Extensions: .dds
Features: open, save
--------------------------------------------------------------------
DIB image/bmp
Extensions: .dib
Features: open, save
--------------------------------------------------------------------
EPS application/postscript
Extensions: .eps, .ps
Features: open, save
--------------------------------------------------------------------
FITS
Extensions: .fit, .fits
Features: open, save
--------------------------------------------------------------------
FLI
Extensions: .flc, .fli
Features: open
--------------------------------------------------------------------
FPX
Extensions: .fpx
Features: open
--------------------------------------------------------------------
FTEX
Extensions: .ftc, .ftu
Features: open
--------------------------------------------------------------------
GBR
Extensions: .gbr
Features: open
--------------------------------------------------------------------
GIF image/gif
Extensions: .gif
Features: open, save, save_all
--------------------------------------------------------------------
GRIB
Extensions: .grib
Features: open, save
--------------------------------------------------------------------
HDF5
Extensions: .h5, .hdf
Features: open, save
--------------------------------------------------------------------
ICNS image/icns
Extensions: .icns
Features: open, save
--------------------------------------------------------------------
ICO image/x-icon
Extensions: .ico
Features: open, save
--------------------------------------------------------------------
IM
Extensions: .im
Features: open, save
--------------------------------------------------------------------
IMT
Features: open
--------------------------------------------------------------------
IPTC
Extensions: .iim
Features: open
--------------------------------------------------------------------
JPEG image/jpeg
Extensions: .jfif, .jpe, .jpeg, .jpg
Features: open, save
--------------------------------------------------------------------
JPEG2000 image/jp2
Extensions: .j2c, .j2k, .jp2, .jpc, .jpf, .jpx
Features: open, save
--------------------------------------------------------------------
MCIDAS
Features: open
--------------------------------------------------------------------
MIC
Extensions: .mic
Features: open
--------------------------------------------------------------------
MPEG video/mpeg
Extensions: .mpeg, .mpg
Features: open
--------------------------------------------------------------------
MSP
Extensions: .msp
Features: open, save, decode
--------------------------------------------------------------------
PCD
Extensions: .pcd
Features: open
--------------------------------------------------------------------
PCX image/x-pcx
Extensions: .pcx
Features: open, save
--------------------------------------------------------------------
PIXAR
Extensions: .pxr
Features: open
--------------------------------------------------------------------
PNG image/png
Extensions: .apng, .png
Features: open, save, save_all
--------------------------------------------------------------------
PPM image/x-portable-anymap
Extensions: .pbm, .pgm, .pnm, .ppm
Features: open, save
--------------------------------------------------------------------
PSD image/vnd.adobe.photoshop
Extensions: .psd
Features: open
--------------------------------------------------------------------
SGI image/sgi
Extensions: .bw, .rgb, .rgba, .sgi
Features: open, save
--------------------------------------------------------------------
SPIDER
Features: open, save
--------------------------------------------------------------------
SUN
Extensions: .ras
Features: open
--------------------------------------------------------------------
TGA image/x-tga
Extensions: .icb, .tga, .vda, .vst
Features: open, save
--------------------------------------------------------------------
TIFF image/tiff
Extensions: .tif, .tiff
Features: open, save, save_all
--------------------------------------------------------------------
WEBP image/webp
Extensions: .webp
Features: open, save
--------------------------------------------------------------------
WMF
Extensions: .emf, .wmf
Features: open, save
--------------------------------------------------------------------
XBM image/xbm
Extensions: .xbm
Features: open, save
--------------------------------------------------------------------
XPM image/xpm
Extensions: .xpm
Features: open
--------------------------------------------------------------------
XVTHUMB
Features: open
--------------------------------------------------------------------

**Comment by nulano** [comment]
How did you install Pillow? I think running `conda list` in a console might show this as well as the `libjpeg` build.

**Comment by bagcivan** [comment]
> How did you install Pillow? I think running `conda list` in a console might show this as well as the `libjpeg` build.

It installed with anaconda installation. I also didn't install it with pip.
libjpeg not showing in conda list. Should I install the libjpeg library?

![2022-09-08 12_56_38-Clipboard](https://user-images.githubusercontent.com/5860475/189093550-87f34531-efb8-444a-a527-a31da0916434.png)

**Comment by nulano** [comment]
> libjpeg not showing in conda list.

The [Anaconda page for `pillow`](https://anaconda.org/anaconda/pillow/files) suggests the `libjpeg` library can be found under the `jpeg` name in conda; from [the jpeg list](https://anaconda.org/anaconda/jpeg/files) the most recent version is 9e.

> It installed with anaconda installation. I also didn't install it with pip.

I just installed Anaconda3-2022.05 in a Windows Sandbox which lists `pillow` at version 9.0.1 build `py39hdc2b20a_0` and `jpeg` version 9e build `h2bbff1b_0`. Running the script from https://github.com/python-pillow/Pillow/issues/6563#issuecomment-1240114851 right away gives me the same results @radarhere got.

However, after running `conda update --all`, I got `pillow` version 9.2.0 build `py39hdc2b20a_1`, which shows the same (bad) results as https://github.com/python-pillow/Pillow/issues/6563#issuecomment-1240282070.

Finally, I tested the wheel from PyPI by installing a fresh Pthon 3.9.13 and installing Pillow with pip, and I again got correct results.

Therefore, I believe this is an issue with the Anaconda build of Pillow 9.2.0, which AFAICT should be reported here: https://github.com/ContinuumIO/anaconda-issues
In the mean time you might be interested in Pillow with pip or using conda-forge instead.

**Comment by radarhere** [comment]
Thanks @nulano for testing.

Rather than the general anaconda repository, I think https://github.com/conda-forge/pillow-feedstock is the place to report the matter.

**Comment by nulano** [comment]
No, that is for the [`conda-forge` channel](https://conda-forge.org/docs/user/introduction.html), not the main Anaconda channel. The [`conda-forge` page for `pillow`](https://anaconda.org/conda-forge/pillow/files) lists a completely different build number for Pillow 9.2.0, `py39hcef8f5f_2`.

**Comment by bagcivan** [comment]
> > libjpeg not showing in conda list.
> 
> The [Anaconda page for `pillow`](https://anaconda.org/anaconda/pillow/files) suggests the `libjpeg` library can be found under the `jpeg` name in conda; from [the jpeg list](https://anaconda.org/anaconda/jpeg/files) the most recent version is 9e.
> 
> > It installed with anaconda installation. I also didn't install it with pip.
> 
> I just installed Anaconda3-2022.05 in a Windows Sandbox which lists `pillow` at version 9.0.1 build `py39hdc2b20a_0` and `jpeg` version 9e build `h2bbff1b_0`. Running the script from [#6563 (comment)](https://github.com/python-pillow/Pillow/issues/6563#issuecomment-1240114851) right away gives me the same results @radarhere got.
> 
> However, after running `conda update --all`, I got `pillow` version 9.2.0 build `py39hdc2b20a_1`, which shows the same (bad) results as [#6563 (comment)](https://github.com/python-pillow/Pillow/issues/6563#issuecomment-1240282070).
> 
> Finally, I tested the wheel from PyPI by installing a fresh Python 3.9.13 and installing Pillow with pip, and I again got correct results.
> 
> Therefore, I believe this is an issue with the Anaconda build of Pillow 9.2.0, which AFAICT should be reported here: https://github.com/ContinuumIO/anaconda-issues In the mean time you might be interested in Pillow with pip or using conda-forge instead. 

I downgraded pillow version to 9.0.1 and installed jpeg <code>conda install -c anaconda jpeg</code>
problem fixed.

**Comment by radarhere** [comment]
Closing, as this is not a problem with Pillow itself.
