### ISSUE TITLE
Does Pillow have capability to organize bulk libraries?

### ISSUE THREAD

**Issue by datatalking** [python-pillow/Pillow#6565]
Pillow is something I've used now and then but I've wondered if there is a way to add or include support for organizing of photos and have not found most if not all of the features I'm looking for. I have 20,000+ photos in an archive I would like to organize them but most of these scripts all move them into folders and sub folders based on date or time.

I'm looking for context labeling, "27 faces found in 19 files" but not "found your aunt patty in 9 photos". Also deduplication on more than just a hash, text, or facial recognition, moving bulk files to different locations, bulk renaming or a sort of scan before saving to archive so the EXIF data is saved.

### What did you do?
I searched for "organize", "move", "facial", "management", "recognize", and both "cv" and "computer vision" but there doesn't seem to be support for these features. Now I probably used the wrong key words or placed them in comments search rather than title but how do people handle very large archives of photos that need to be organized.

Note I am not talking about recognizing your face in a photo, only that there is a face, or text and triage those to be handled by other existing tools. Also it would be great if I could have it work with HEIF or Mac based photos, or PDF files, I'm still learning more about Pillow and its best use case, so my apologies if this has already been discussed.

https://github.com/python-pillow/Pillow/issues?q=organize+in%3Acomments
I did find barcode recognition = https://github.com/python-pillow/Pillow/issues/1537
facial = https://github.com/python-pillow/Pillow/issues?q=facial+in%3Acomments+
HEIF files = https://github.com/python-pillow/Pillow/issues/2806#issuecomment-338200112
vision = https://github.com/python-pillow/Pillow/issues?q=vision+in%3Acomments+
computer vision = https://github.com/python-pillow/Pillow/issues/1777 @wiredfool closed saying they don't support computer vision.

### What did you expect to happen?
Either support is or is not built in or it was not built in for patent reason or never suggested

### What actually happened?
My search came up mostly empty but there are packages that I use now that kinda work, also there are github packages for images or file organization that are old that I use that need updating as they are 2 to 7 years old with no support.
### What are your OS, Python and Pillow versions?

* OS: Mac
* Python: 2.7, 3.7, 3.9, 3.10
* Pillow: Current

**Comment by aclark4life** [comment]
@datatalking Sounds deep-learning "ish" which would most likely make it out of scope for Pillow e.g. https://towardsdatascience.com/deep-learning-with-python-neural-networks-complete-tutorial-6b53c0b06af0

**Comment by hugovk** [comment]
No, Pillow doesn't do this and I agree it's out of scope.

I've used OpenCV in the past to do face recognition, something along the lines of: https://towardsdatascience.com/face-detection-in-2-minutes-using-opencv-python-90f89d7c0f81

**Comment by radarhere** [comment]
Closing, as it has been agreed that this is out of scope.
