### ISSUE TITLE
Exception using "seek" on GIF that contains frames with different modes

### ISSUE THREAD

**Issue by seidnerj** [python-pillow/Pillow#6571]
I have an animated GIF that has about 60 frames, some of the frames are encoded in 'L' mode and others are in 'RGB' mode. Many actions, including a simple "seek" command" fail with a "ValueError: images do not match" exception when `self.im.paste(frame_im, self.dispose_extent)` is issued in GifImagePlugin.py. This happens when "self.im" and "frame_im" have different modes.

This might be a protection technique for not being able to process such files with Pillow.

**Comment by seidnerj** [comment]
Here you go, use the code below and the attached GIF.

```
def main():
    image = Image.open('example.gif')
    image.seek(6)

if __name__ == '__main__':
    main()
```
![example](https://user-images.githubusercontent.com/4147381/189899683-85e19549-d37b-44f7-b420-e5ca82a96a12.gif)

**Comment by radarhere** [comment]
I've created PR #6576 to resolve this.

**Comment by seidnerj** [comment]
Great, thanks. I’ll patch my local version accordingly. What release do you expect this to be included in?

**Comment by nulano** [comment]
Pillow 8.3.0 was due for release on 2022-10-15, but will be delayed a few days due to the delay with the Python 3.11 release. The current estimate is 2022-10-25, you can watch #6460 for updates.

**Comment by seidnerj** [comment]
Great. Thanks!
