### ISSUE TITLE
How do I write a line of text and bold a word in the line using Pillow?

### ISSUE THREAD

**Issue by thenishantsapkota** [python-pillow/Pillow#6574]
Example:
My name is **Your Name**.

**Comment by radarhere** [comment]
Pillow doesn't have a single API that will allow you to do that. You will have to write 'My name is' and then 'Your Name' afterwards.

```python
from PIL import Image, ImageFont, ImageDraw

im = Image.new("RGB", (260, 50))
draw = ImageDraw.Draw(im)

font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Times New Roman.ttf", 24)
draw.text((10, 10), "My name is ", font=font)
length = draw.textlength("My name is ", font=font)

font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf", 24)
draw.text((10+length, 10), "Your Name", font=font)

im.save("out.png")
```
![out](https://user-images.githubusercontent.com/3112309/189896232-30ea0914-2538-45bf-9fe4-fb0670f46043.png)

**Comment by thenishantsapkota** [comment]
> Pillow doesn't have a single API that will allow you to do that. You will have to write 'My name is' and then 'Your Name' afterwards.
> 
> ```python
> from PIL import Image, ImageFont, ImageDraw
> 
> im = Image.new("RGB", (260, 50))
> draw = ImageDraw.Draw(im)
> 
> font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Times New Roman.ttf", 24)
> draw.text((10, 10), "My name is ", font=font)
> length = draw.textlength("My name is ", font=font)
> 
> font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Times New Roman Bold.ttf", 24)
> draw.text((10+length, 10), "Your Name", font=font)
> 
> im.save("out.png")
> ```
> 
> ![out](https://user-images.githubusercontent.com/3112309/189896232-30ea0914-2538-45bf-9fe4-fb0670f46043.png)

I have to bold these text
So how can I do it?
![image](https://user-images.githubusercontent.com/60746512/189959582-28cfdd9f-6139-41f9-b0a4-feba634cdb9f.png)

**Comment by nulano** [comment]
You have to draw each line piece-by-piece with the segments in regular font and segments in bold font drawn separately. One way you can do this is to first create an array with the relevant text segments, e.g. for the first two rows:

```python
from PIL import Image, ImageDraw, ImageFont

font_size = 24
norm_font = ImageFont.truetype("arial.ttf", font_size)
bold_font = ImageFont.truetype("arialbd.ttf", font_size)
line_height = norm_font.getbbox("A")[3] + 4  # same as in draw.multiline_textsize

rows = [
    [
        (norm_font, "This is to certify that "),
        (bold_font, "Mr. Nishant Sapkota"),
        (norm_font, ", son of "),
        (bold_font, "Mr. Bhawani Prasad Sapkota"),
        (norm_font, " is"),
    ],
    [
        (norm_font, "an inhabitant of "),
        (bold_font, "Damak-09"),
        (norm_font, " is a bonafide student of the academy. He passed the examination"),
    ],
    # ...
]
```

Then simply loop over the individual rows and their segments and draw each piece separately. To center each line, you can first calculate its total length and then halve that to use as the offset:

```python
width = 1000
height = 200
im = Image.new("RGB", (width, height), "white")
draw = ImageDraw.Draw(im)

y = 20
for row in rows:  # see rows defined above
    # calculate start position relative to center point
    row_length = sum(font.getlength(segment) for font, segment in row)
    x = (width - row_length) / 2

    # draw individual text segments
    for font, segment in row:
        draw.text((x, y), segment, fill="black", font=font)
        x += font.getlength(segment)

    # move cursor to next line
    y += line_height

im.show()
```

![6574](https://user-images.githubusercontent.com/3819630/189986273-3c6c4a39-17a0-4e27-aa0f-8dd1bc262ee7.png)

**Comment by radarhere** [comment]
@thenishantsapkota you liked the previous comment. Does that mean that your question has been answered?

**Comment by thenishantsapkota** [comment]
Yes sorry this is resolved.
Thank you for the help!
