### ISSUE TITLE
cannot identify image file <_io.BytesIO object at 0x7f8bbdc115f0>

### ISSUE THREAD

**Issue by Pravin770** [python-pillow/Pillow#6578]
Tried to convert the pdf to an image in colab. It was working fine till yesterday but not working today. Not sure what causes the issue.

```python
from pdf2image import convert_from_path
import glob
pdf_dir = glob.glob(r'/content/first_page.pdf')  
img_dir = "/content/" 
for pdf_ in pdf_dir:
    pages = convert_from_path(pdf_, 57)
    pages[0].save('output.'+"jpg", 'JPEG')
```

**Comment by radarhere** [comment]
What error are you receiving? What makes you think this is a Pillow issue, rather than an issue with pdf2image?

**Comment by radarhere** [comment]
Without a copy of the PDF, I don't expect there is enough information here to help.

We certainly haven't released a new version in the last day, and neither has pdf2image.

**Comment by Pravin770** [comment]
The issue got resolved after updating the `!sudo apt-get update`. The code works fine now
