### ISSUE TITLE
UnidentifiedImageError when opening picture from web?

### ISSUE THREAD

**Issue by Rapid1898-code** [python-pillow/Pillow#6583]
Hello - when i try to open this image:

```python
from PIL import Image
import imagehash
import requests
img = "https://cdn1.bitchesgirls.com/file/yael1c-yael-cohen-aug-31-2022/261656199427347453059782996929595436595.jpg"
# img = "https://i.imgur.com/5bGzZi7.jpg"
resp = requests.get(img, stream=True)
img = Image.open(resp.raw)
print(img)
```

I get the following error:

```
$ python test2.py
Traceback (most recent call last):
  File "C:\DEV\Fiverr\TRY\pilom1\test2.py", line 7, in <module>
    img = Image.open(resp.raw)
  File "C:\DEV\.venv\test\lib\site-packages\PIL\Image.py", line 3123, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000001C02F9EA5E0>
```

Why is this happening?
With other pictures i have no problem to open / print it in that way.

**Comment by Yay295** [comment]
```shell
>>> print(resp)
<Response [403]>
```

It's not Pillow; the request is failing. If you download the image manually and open it from the file it works fine. That site is probably blocking requests from `requests` to keep out bots.

**Comment by Rapid1898-code** [comment]
Thanks a lot for your reply - yes you are right, this was simply a permission problem - when i run the program with an user-agent input in the request, everything works fine.
