### ISSUE TITLE
Why can't other devices read the bit depth of a 24-bit depth tiff image after converting it to 1-bit depth with Pillow?

### ISSUE THREAD

**Issue by yuyuwo** [python-pillow/Pillow#6587]
Thank you for your further questions，I am using a 3D printer that can read tiff images; it requires the image to have a bit depth of 1.
This is my code to convert the bit deep:
```python
from PIL import Image
import numpy as np
import os
img = Image.open('input.tif')
img1 = img.convert("1")
img1.save('output.tif',dpi=(300,400))
```
When the image is read in, the following image is displayed.
![image](https://user-images.githubusercontent.com/79082185/190621818-c0bdc105-eb2d-4614-a752-fed96b0c9d2b.png)

**Comment by radarhere** [comment]
Could you provide some more detail?

What "other devices" are you referring to? Could you provide instructions or code showing that the bit depth can't be read?
Could you provide a copy of the TIFF image in question, and the code you're using to convert it with Pillow?

**Comment by radarhere** [comment]
Could you upload a copy of the original TIFF?

Are you saying that the 3D printer itself that is showing "0 bit", and not a computer application? What is the brand of the 3D printer?

**Comment by radarhere** [comment]
If you have a copy of a 1-bit TIFF that does work on the 3D printer, could you upload that as well? That would let us compare them to figure out what the difference is.

**Comment by yuyuwo** [comment]
> 
Thank you for your attention to this matter. I uploaded the tiff file 1.txt which cannot be recognized and the tiff file 2.txt which can be recognized (I changed the extension to .txt due to the file upload format limitation, you can change it to the original .tif after downloading)
[1.txt](https://github.com/python-pillow/Pillow/files/9583861/1.txt)
[2.txt](https://github.com/python-pillow/Pillow/files/9583862/2.txt)

**Comment by yuyuwo** [comment]
> If you have a copy of a 1-bit TIFF that does work on the 3D printer, could you upload that as well? That would let us compare them to figure out what the difference is.

It is worth noting that when I import the images that cannot be recognized into Photoshop before storing them. The images became recognizable by the device.

**Comment by yuyuwo** [comment]
> > 
> 
> Thank you for your attention to this matter. I uploaded the tiff file 1.txt which cannot be recognized and the tiff file 2.txt which can be recognized (I changed the extension to .txt due to the file upload format limitation, you can change it to the original .tif after downloading) [1.txt](https://github.com/python-pillow/Pillow/files/9583861/1.txt) [2.txt](https://github.com/python-pillow/Pillow/files/9583862/2.txt)

**Comment by yuyuwo** [comment]
> ```python
> tiffinfo={262: 0, 266: 1, 277: 1, 274: 1, 285: b"0.2"}
> ```

Thanks for your help, I need to try it out on the machine tomorrow.

**Comment by yuyuwo** [comment]
> Thanks. Here is code that sets the tags that 2 has that 1 does not.
> 
> ```python
> from PIL import Image
> im = Image.open("1.tif")
> im.save("1_changed.tif", tiffinfo={262: 0, 266: 1, 277: 1, 274: 1, 285: b"0.2"})
> ```
> 
> Does the resulting file work? [1_changed.txt](https://github.com/python-pillow/Pillow/files/9584078/1_changed.txt)

Thank you very much，it‘s working！！

**Comment by radarhere** [comment]
Excellent. I would suspect that not all of those tags need to be listed to make it work, but it's up to you whether or not you want to try removing them one by one to figure out what is necessary.
