### ISSUE TITLE
Save custom TIFF tags in LZW-compressed TIFFs

### ISSUE THREAD

**Issue by jondo** [python-pillow/Pillow#660]
If I understand correctly, the recent changes (#369) have not made it possible to write custom TIFF tags. I would like to do the following:

```python
info = TiffImagePlugin.ImageFileDirectory()
CustomTagId = 37000
info[CustomTagId] = 6
info.tagtype[CustomTagId] = 3 # 'short' according to TiffTags.TYPES

img.save(pathname, tiffinfo = info)
```

This corresponds to "Defining Application Tags" in http://www.remotesensing.org/libtiff/addingtags.html.

**Comment by radarhere** [comment]
The custom tag is skipped here - https://github.com/python-pillow/Pillow/blob/f115546b56a54b6458f189/src/PIL/TiffImagePlugin.py#L1512

So this looks like it is part of the 'UNDONE --  add code for the custom dictionary'

**Comment by radarhere** [comment]
I've created PR #660 for this
