### ISSUE TITLE
Unable to render Tibetan unicode sign

### ISSUE THREAD

**Issue by orinciog** [python-pillow/Pillow#6601]
### What did you do?
I'm trying to render an image that contains a Tibetan sign (\u0F1D).
I tried a lot of fonts, none are working. For this sign, all fonts output a rectangle.
I tried also the font that is used in LibreOffice Writer to output the sign (Lohit-Devanagari.ttf).
In LibreOffice is ok, in python is not ok.

### What did you expect to happen?
I expect to create an image with the sign \u0F1D (https://www.compart.com/en/unicode/U+0F1D)

### What are your OS, Python and Pillow versions?

* OS:      Ubuntu 20.04
* Python:  3.8.10
* Pillow: 9.2.0

```python
from PIL import Image, ImageDraw, ImageFont, ImageFilter

#configuration
font_size=36
width=500
height=100
back_ground_color=(255,255,255)
font_size=36
font_color=(0,0,0)
unicode_text = u"\u0F1D" + u"\u2606" + u"It works"

im  =  Image.new ( "RGB", (width,height), back_ground_color )
draw  =  ImageDraw.Draw ( im )
#insert whatever font - including Lohit-Devanagari.ttf
unicode_font = ImageFont.truetype("DejaVuSans.ttf", font_size)
draw.text ( (10,10), unicode_text, font=unicode_font, fill=font_color )

im.save("text.jpg")


```
The output from Python is
![text](https://user-images.githubusercontent.com/10981387/191069457-43cf87ab-5aba-40c9-9253-2ac71d591c0f.jpg)

The output from Libre Office Writer is  (CTRL+shift+U -> u0f1d and enter): 
![Screenshot from 2022-09-19 19-45-53](https://user-images.githubusercontent.com/10981387/191070091-a2d893ba-284b-4fb7-ad22-2207f6b5cb85.png)

Thank you

**Comment by orinciog** [comment]
I also tested with symbola.ttf, font shown in: https://apps.timwhitlock.info/unicode/inspect?s=%E0%BC%9D%E2%98%86It+works

Unicode viewer:
![Screenshot 2022-09-20 at 15-38-59 Unicode character inspector ༝☆It works](https://user-images.githubusercontent.com/10981387/191259870-4cc260b9-e846-43d6-b7f3-f181b13d3ab6.png)

Python:
![text](https://user-images.githubusercontent.com/10981387/191260593-589465b1-2bcc-4bc3-9bad-d5dd0ba31dbc.jpg)

**Comment by radarhere** [comment]
Trying TibetanMachineUni.ttf, I was able to generate
![text](https://user-images.githubusercontent.com/3112309/191409921-ae4f76d8-17f3-428a-918e-eeb44b5f8fbd.jpg)

**Comment by orinciog** [comment]
Thank for your comment, but that font does not render other symbols: for example the star, as your picture already shows. What I want to do is to create an image from some Twitter display name, that can contain arbitrary symbols and emoji.

The question was actually why Pillow does not render symbols that the font knows about it. (Symbola.ttf actually can render all unicode symbols, but with Pillow some special symbols are not rendered).

**Comment by radarhere** [comment]
I've tried inspecting symbola.ttf and Lohit-Devanagari.ttf with https://fontdrop.info/ and https://github.com/fonttools/fonttools - I don't think they have "Tibetan Sign Rdel Nag Gcig"

> From what I know, Symbola.ttf actually can render all unicode symbols

I don't think that is correct.
- https://www.fileformat.info/info/unicode/font/symbola/list.htm doesn't list every character, and not U+0F1D.
- U+0F1D is in the U+0F00-U+0FFF range. https://mpdf.github.io/reference/codepages-glyphs/unicode-coverage-of-free-fonts.html doesn't list symbola against every section, and it doesn't list it as covering the U+0F00-U+0FFF range.

It doesn't look like you can change the font for https://apps.timwhitlock.info/unicode/inspect, but for Libre Office Writer, here is a screenshot I put together, after copying and pasting in characters, and changing the font to 'Times New Roman'. I hope this demonstrates that your earlier screenshot doesn't show conclusively that Lohit Devanagari has those characters.

<img width="404" alt="Screen Shot 2022-09-21 at 11 14 06 pm" src="https://user-images.githubusercontent.com/3112309/191515251-a7e713d4-545e-401a-b75d-45c98dbe9a6f.png">

Furthermore, if I go into the Insert menu, and into 'Special Character...', I can't U+0F1D shows as a 'Missing Character'.

<img width="796" alt="Screen Shot 2022-09-21 at 11 21 14 pm" src="https://user-images.githubusercontent.com/3112309/191516010-b5599839-e2e3-4546-a0e2-185e330f7c4c.png">

**Comment by radarhere** [comment]
If you are interested in combining multiple fonts to cover more character ranges, see #4808 as an open request for a new feature to allow different fonts to be used based on whether or not characters are missing.

The beginning of that request states that this feature would be
> Similarly to how web browsers work when they are missing characters from fonts - the OS fills that void from a default font.

**Comment by orinciog** [comment]
Thank you very much for such a deep debugging. 
Indeed, I was incorrect in my assumptions and I'm sorry.

I will try to merge multiple fonts in order to render as many as possible chars. (For that particular sign, it is ok with  TibetanMachineUni.ttf)

Again, thank you.
