### ISSUE TITLE
App created on x86 won't run on arm64 device because of Pillow

### ISSUE THREAD

**Issue by MrBananaPants** [python-pillow/Pillow#6602]
So I'm developing an app that uses Pillow (the used import statements are `import PIL.Image` and `from PIL import Image, ImageTk`).
I compile the app as a .app file for macOS using py2app. The app works perfectly on x86 Macs but when run on an arm64 (M1 MBP) Mac, the app crashes at startup because of incompatibility with Pillow. When I compile the app on an arm64 Mac, the .app file works perfectly. 

All other packages / modules used in my app don't give me these problems and work fine on both x86 and arm64 when compiled on an x86 machine.

Here's the full error when trying to start the app on an arm64 machine:
```
Traceback (most recent call last):
  File "/Applications/PyFit.app/Contents/Resources/__boot__.py", line 89, in _recipes_pil_prescript
    import Image
ModuleNotFoundError: No module named 'Image'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Applications/PyFit.app/Contents/Resources/__boot__.py", line 135, in <module>
    _recipes_pil_prescript(['FitsStubImagePlugin', 'Hdf5StubImagePlugin', 'FtexImagePlugin', 'FliImagePlugin', 'XbmImagePlugin', 'MspImagePlugin', 'MicImagePlugin', 'Jpeg2KImagePlugin', 'PdfImagePlugin', 'PalmImagePlugin', 'DdsImagePlugin', 'MpoImagePlugin', 'EpsImagePlugin', 'SpiderImagePlugin', 'PixarImagePlugin', 'BufrStubImagePlugin', 'IcnsImagePlugin', 'XpmImagePlugin', 'JpegImagePlugin', 'FitsImagePlugin', 'SunImagePlugin', 'TgaImagePlugin', 'BmpImagePlugin', 'SgiImagePlugin', 'PsdImagePlugin', 'CurImagePlugin', 'DcxImagePlugin', 'XVThumbImagePlugin', 'IcoImagePlugin', 'PcxImagePlugin', 'McIdasImagePlugin', 'PngImagePlugin', 'GifImagePlugin', 'IptcImagePlugin', 'ImImagePlugin', 'ImtImagePlugin', 'PcdImagePlugin', 'PpmImagePlugin', 'WebPImagePlugin', 'TiffImagePlugin', 'GribStubImagePlugin', 'GbrImagePlugin', 'FpxImagePlugin', 'MpegImagePlugin', 'WmfImagePlugin', 'BlpImagePlugin'])
  File "/Applications/PyFit.app/Contents/Resources/__boot__.py", line 93, in _recipes_pil_prescript
    from PIL import Image
  File "PIL/Image.pyc", line 100, in <module>
  File "PIL/_imaging.pyc", line 14, in <module>
  File "PIL/_imaging.pyc", line 10, in __load
  File "imp.pyc", line 343, in load_dynamic
ImportError: dlopen(/Applications/PyFit.app/Contents/Resources/lib/python3.10/lib-dynload/PIL/_imaging.so, 0x0002): tried: '/Applications/PyFit.app/Contents/Resources/lib/python3.10/lib-dynload/PIL/_imaging.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')), '/System/Volumes/Preboot/Cryptexes/OS/Applications/PyFit.app/Contents/Resources/lib/python3.10/lib-dynload/PIL/_imaging.so' (no such file), '/Applications/PyFit.app/Contents/Resources/lib/python3.10/lib-dynload/PIL/_imaging.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64'))
2022-09-19 20:35:06.304 PyFit[5429:2938983] Launch error
2022-09-19 20:35:06.304 PyFit[5429:2938983] Launch error
See the py2app website for debugging launch issues
```

**Comment by MrBananaPants** [comment]
I just found out PIL is deprecated and Pillow should be used. I'll give it a try and update this issue once I got the results.

**Comment by radarhere** [comment]
Just to be clear, the part to focus on is
> '/Applications/PyFit.app/Contents/Resources/lib/python3.10/lib-dynload/PIL/_imaging.so' (mach-o file, but is an incompatible architecture (have 'x86_64', need 'arm64')

I imagine the difference between Pillow and your other libraries is that Pillow is not a purely Python library. There are C components to it.

You would like to create an app with universal2 architecture. https://py2app.readthedocs.io/en/stable/options.html#option-reference lists an `--arch` flag with a `universal2` setting.

**Comment by MrBananaPants** [comment]
@radarhere I just checked and my app was already a `universal` application (even without the `--arch universal2` flag). I also tried it with the `--arch universal2` flag but I get the same launch error (incompatible architecture).

When I build the app on my M1 Mac, it works fine on other arm64 Macs but then I get the launch error on x86 machines.

**Comment by radarhere** [comment]
I think you need to make sure that the `PIL/_imaging.so` on your machine has both architectures, before you start building with py2app.

Downloading the wheels from https://pypi.org/project/Pillow/, and running
```python
from delocate.fuse import fuse_wheels
fuse_wheels('Pillow-9.2.0-cp310-cp310-macosx_10_10_x86_64.whl', 'Pillow-9.2.0-cp310-cp310-macosx_11_0_arm64.whl', 'Pillow-9.2.0-cp310-cp310-macosx_11_0_universal2.whl')
```
I created [Pillow-9.2.0-cp310-cp310-macosx_11_0_universal2.whl.zip](https://github.com/python-pillow/Pillow/files/9612676/Pillow-9.2.0-cp310-cp310-macosx_11_0_universal2.whl.zip). If you install using that, then your `~/Library/Python/3.10/lib/python/site-packages/PIL/_imaging.cpython-310-darwin.so` should have both architectures. You can check with `lipo -info ~/Library/Python/3.10/lib/python/site-packages/PIL/_imaging.cpython-310-darwin.so`.

If that works, then I think your app should support both architectures.

**Comment by MrBananaPants** [comment]
@radarhere It worked! Thank you so much!
