### ISSUE TITLE
TiffImagePlugin doesn't honor the ROWSPERSTRIP tag value

### ISSUE THREAD

**Issue by agiudiceandrea** [python-pillow/Pillow#6607]
### What did you do?

I tried to save a PIL.Image.Image (mode=RGBA, size=335x333, 8 bits per sample) to a TIFF file with LZW compression and 9 rows per strip.

```python
img.save('output.tiff', compression='tiff_lzw', tiffinfo={278: 9})
```

### What did you expect to happen?

The file to be saved as a TIFF file with LZW compression and 9 rows per strip.

### What actually happened?

The file was saved as a TIFF file with LZW compression and 48 rows per strip.

### What are your OS, Python and Pillow versions?

* OS: Windows 10 64-bit
* Python: 3.9.5
* Pillow: 9.2.0

**Comment by radarhere** [comment]
As context, ROWSPERSTRIP has been set by TiffImagePlugin since PIL.

If I make a change to allow ROWSPERSTRIP to be set by the user, the following test code starts failing.
https://github.com/python-pillow/Pillow/blob/53b6e5f4bf9a6a68e29109c457b12d17761d0035/Tests/test_file_tiff_metadata.py#L124-L128

The error is
https://github.com/python-pillow/Pillow/blob/53b6e5f4bf9a6a68e29109c457b12d17761d0035/src/PIL/TiffImagePlugin.py#L906

**Comment by agiudiceandrea** [comment]
@radarhere, thanks.
Opening an image with a certain number of rows per strip and just saving it without any manipulation and with the same tags:
```Python
sourceimg = Image.open('input.tiff')
tiffinfo = sourceimg.tag_v2
sourceimg.save('output', tiffinfo=tiffinfo)
```
then the saved image will have a different number of rows per strip.

Anyway, changing the TiffImagePlugin.ROWSPERSTRIP tag number to another non conflicting tag number, e.g. 10, it is possible to trick the TiffImagePlugin, so it will write its calculated value of the rows per strip to such tag number 10 so the libtiff library will use the rows per strip provided by the tiffinfo:

```Python
sourceimg = Image.open('input.tiff')
tiffinfo = sourceimg.tag_v2
TiffImagePlugin.ROWSPERSTRIP = 10
sourceimg.save('output', tiffinfo=tiffinfo)
```
However, this is not a complete workaround, as the saved image will have a spurious tag number 10.

**Comment by radarhere** [comment]
Changing `TiffImagePlugin.ROWSPERSTRIP` is an inventive idea, but I think it might break reading TIFF files afterwards.

If you're looking for a workaround, see what you think of this.
```python
from PIL import Image, TiffImagePlugin

def setRowsPerStrip(im, rows_per_strip):
    TiffImagePlugin.WRITE_LIBTIFF = True
    
    bits = TiffImagePlugin.SAVE_INFO[im.mode][4]
    stride = len(bits) * ((im.size[0] * bits[0] + 7) // 8)
    TiffImagePlugin.STRIP_SIZE = rows_per_strip * stride

im = Image.open("Tests/images/hopper.tif")
setRowsPerStrip(im, 110)
im.save("out.tif")
```

**Comment by radarhere** [comment]
I've created #7654 to resolve this.
