### ISSUE TITLE
Why not ship with a default font able to change font size in ImageDraw.Draw.text?

### ISSUE THREAD

**Issue by wikiwen** [python-pillow/Pillow#6622]
### What did you do?
Hello, every author of `Pillow`! Thank you create this powerful tool in image processing. 
I want to draw a text in a image. But I found so inconvenient to change font size. **As the default font is unsupported to change font size, I need to download a truetype font file, and define a object `ImageFont` to change font size**. Why not shipped with a default font able to change font size in `ImageDraw.Draw.text` like `opencv`?

### What are your OS, Python and Pillow versions?

* OS: CentOS
* Python:  3.7
* Pillow: 9.2.0

```python
# Now: default font. can't change font size. Often so small in a image.
draw.text((10, 25), "world", font=None)

# Now: need download arial.ttf to change font size
font = ImageFont.truetype("arial.ttf", 15)
draw.text((10, 25), "world", font=font)

# Expected: default font, set font_size
draw.text((10, 25), "world", font_size=15)
```

**Comment by wikiwen** [comment]
similiar issue #2695

**Comment by nulano** [comment]
I think the main reason this has not yet been done are concerns over file size.

The current default font has about 6.5KB, but uses 8.7KB due to base64 encoding.

Using [this website](http://www.oxfordshireweb.com/smallest-file-size-google-web-fonts/), I found a monospace TrueType font [Share Tech Mono](https://fonts.google.com/specimen/Share+Tech+Mono) that has about 42KB (about 57KB with base64 encoding, ~2.5% of current Pillow wheels) and is licensed under the Open Font License, which might be acceptable for including in Pillow.

**Comment by Yay295** [comment]
Share Tech Mono is only 16.3KB when converted to WOFF2, if that works. 21.6KB for WOFF.

**Comment by dandv** [comment]
I was trying to get ChatGPT to add a grid over a map, and it couldn't figure out how to increase the axis labels font size. Is that possible but ChatGPT isn't aware of it yet?

![image](https://github.com/python-pillow/Pillow/assets/33569/f2c14097-8105-4574-bb2d-b9fcc19dec03)

**Comment by radarhere** [comment]
@dandv if ChatGPT is just using Pillow's builtin font, then no, it isn't possible to increase the font size. The current alternative is to use a font from outside of Pillow, such as `font = ImageFont.truetype(font_path, size=128)`

**Comment by aclark4life** [comment]
@dandv There are limits to what ChatGPT can generate as well as errors in the results. That said, I can recall having it give me both options: built-in-font and `path/to/my/font`. You'll know when you've reached its limit when you ask very specific questions and it returns very specific answers, the same specific answers over and over, either right or wrong. I've only used the free version so it's possible the paid version is better, but I would never base my understanding of something entirely on ChatGPT's answers. In short, yes, ChatGPT is unaware of lots of things, but it's still an amazing resource when used in combination with other resources. E.g. I got it to produce this logo in < 1 hour 😄 :

```
from PIL import Image, ImageDraw, ImageFont

# Define the logo size and background color
logo_width = 400
logo_height = 400
background_color = (45, 118, 187)  # Dark blue: #2D76BB

# Create a new image with the specified dimensions and background color
logo_image = Image.new("RGB", (logo_width, logo_height), background_color)

# Set up the drawing context
draw = ImageDraw.Draw(logo_image)

# Define the text and font for the logo
text = "ACLARK.NET, LLC"
font_size = 40  # Adjust as desired to shrink the text
font_color = (255, 255, 255)  # White

# Load the Arial font and calculate the text size
font = ImageFont.truetype("Arial.ttf", font_size)

text_width, text_height = draw.textsize(text, font=font)

# Calculate the position to center the text on the logo
text_x = (logo_width - text_width) // 2
text_y = (logo_height - text_height) // 2

# Calculate the dimensions for the rectangle
padding_x = 20
padding_y = 10
rectangle_width = text_width + (2 * padding_x)
rectangle_height = text_height + (2 * padding_y)

# Calculate the position to center the rectangle around the text
rectangle_x = text_x - padding_x
rectangle_y = text_y - padding_y

# Draw the rectangle
rectangle_coords = [
    (rectangle_x, rectangle_y),
    (rectangle_x + rectangle_width, rectangle_y + rectangle_height),
]
border_color = (255, 255, 255)  # White
border_width = 2  # Adjust as desired
draw.rectangle(rectangle_coords, outline=border_color, width=border_width)

# Draw the text on the logo
draw.text((text_x, text_y), text, font=font, fill=font_color)

# Save the logo as a PNG image
logo_image.save("aclarknet.png")
```

![aclarknet](https://github.com/python-pillow/Pillow/assets/72164/70583a43-3026-4b71-9483-e244c15a8a89)

**Comment by radarhere** [comment]
> Using [this website](http://www.oxfordshireweb.com/smallest-file-size-google-web-fonts/), I found a monospace TrueType font [Share Tech Mono](https://fonts.google.com/specimen/Share+Tech+Mono)

![sharetechmono](https://github.com/python-pillow/Pillow/assets/3112309/217c9b56-fd7a-4036-b149-5b9f2f3fecd8)

In my entirely subjective opinion, Share Tech Mono doesn't look quite "normal". I have instead found Aileron Regular, a CC0 font from https://dotcolon.net/font/aileron.

![aileron](https://github.com/python-pillow/Pillow/assets/3112309/aa888d19-96cc-4740-931d-d6c32cb37218)

I've created PR #7354 as a possible solution to this.
