### ISSUE TITLE
FliImagePlugin cannot get colours

### ISSUE THREAD

**Issue by Elefant-Freeciv** [python-pillow/Pillow#6624]
The fli/flc plugin is unable to get the colours from a civ iii flc animation. The result of opening any civ iii animation is a black and white image. I apologize in advance for any issues in my reporting style.
Code is approximate, as I am working from memory on my smartphone.
```python
from PIL import Image
img = Image.load("attack.flc")
img.save("attack.gif", Save_all=True)
```

**Comment by radarhere** [comment]
Could you upload a copy of attack.flc?

**Comment by Elefant-Freeciv** [comment]
[imgs.zip](https://github.com/python-pillow/Pillow/files/9669463/imgs.zip)
Here are a few.

**Comment by radarhere** [comment]
Thanks. I've created PR #6626 to resolve this.

**Comment by Elefant-Freeciv** [comment]
Thanks. This works great! Can I expect it in the upcoming 9.3 release?

**Comment by radarhere** [comment]
It still needs to be reviewed, but based on past experience, yes, I would expect so.

**Comment by radarhere** [comment]
The PR has now been merged, so it is now due to be part of the next release.
