### ISSUE TITLE
JPEG2000 bigger than JPEG

### ISSUE THREAD

**Issue by RobinFrcd** [python-pillow/Pillow#6648]
Hi,
If I understood JPEG2000 well, it should be more efficient that JPEGBaseline (in terms of storage). But when running the compression algorithm with Pillow, the JPEG2000 one is much bigger than the baseline.

### What did you do?
Compress an image with both JPEG2000 and JPEG formats.

### What did you expect to happen?
JPEG2000 image being smaller than the JPEG one.

### What actually happened?
The opposite, JPEG being 100x smaller than JPEG2000. And JPEG2000 compression is slower than JPEG, so I guess there's something wrong here.

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 22.04
* Python: 3.10.6
* Pillow: 9.2.0

```python
from PIL import Image
import numpy as np
from io import BytesIO

img = Image.open('/home/robz/Downloads/jpeg-home.jpg')
img_arr = np.array(img)

print(len(img.tobytes()) / 1e3)
# 960.0

with BytesIO() as bio:
    Image.fromarray(img_arr).save(bio, optimize=True, quality=0, format="JPEG")
    bio_bytes = bio.getvalue()
    print(len(bio_bytes) / 1e3)
# 2.598
  
with BytesIO() as bio:
    Image.fromarray(img_arr).save(bio, optimize=True, quality=0, format="JPEG2000")
    bio_bytes = bio.getvalue()
    print(len(bio_bytes) / 1e3)
# 270.683
```

![jpeg-home](https://user-images.githubusercontent.com/29704178/194703566-4d34dbcf-58b8-4394-8083-fac16aa8a5db.jpg)

**Comment by radarhere** [comment]
If I use [ImageMagick](https://imagemagick.org/) to convert your image,
```
convert -quality 0 jpeg-home.jpg magick.jpg
convert -quality 0 jpeg-home.jpg magick.jp2
```
I get 35.762 for JPEG and 159.214 for JPEG2000. Here are the files created - [magick.zip](https://github.com/python-pillow/Pillow/files/9739012/magick.zip)

So ImageMagick similarly creates JPEG2000 files that are larger than JPEG.

**Comment by RobinFrcd** [comment]
Oh, ok, thanks. But I don't get it, shouldn't JPEG2000 be more optimized than base JPEG ?

**Comment by radarhere** [comment]
Investigating further, I found that `quality` isn't actually an option when saving JPEG2000 files with Pillow - https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-2000

If I use `quality_layers` instead for JPEG2000, and choose a suitably high number,
```python
    Image.fromarray(img_arr).save(bio, optimize=True, quality_layers=[400], format="JPEG2000")
```
then I get a smaller result than JPEG - 2.397.
