### ISSUE TITLE
Document alpha values of PA image with RGBA palette

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6658]
I think the PA alpha is used regardless of any alpha values in the palette, but I'm not certain that's handled consistently, and I don't think it's documented anywhere.

**Comment by radarhere** [comment]
> I'm not certain that's handled consistently

Are there any specific operations that you're concerned about? If not, ok.

**Comment by Yay295** [comment]
Nothing specific. I don't think it's checked in very many places anyways.

**Comment by radarhere** [comment]
I've created PR #6662 to document that when converting PA with an RGBA palette, the image channel will be used as the source of the alpha. Does that resolve this then?

**Comment by Yay295** [comment]
Yeah, I think that should be good.
