### ISSUE TITLE
Attached PNG loads as solid-black square

### ISSUE THREAD

**Issue by ssokolow** [python-pillow/Pillow#666]
With this PNG file...

![logo](https://cloud.githubusercontent.com/assets/46915/3022678/b1178e42-dfce-11e3-94f3-fc1395ecb7a8.png)

...this code displays a black square:

``` python
from PIL import Image
im = Image.open('logo.png')
im.show()
```

...as a result, this code which depends on Pillow also produces a black square:

``` python
from escpos import printer
usblp = printer.Usb(0x0416, 0x5011)
usblp.image("logo.png")
usblp.cut()
```

I almost filed a bug with python-escpos because Pillow failed silently rather than either working or raising an exception.

**Comment by hugovk** [comment]
Closing this as there's been no updates in 5 years. PRs are welcome to improve library support.
