### ISSUE TITLE
ImageCms.profileToProfile error

### ISSUE THREAD

**Issue by julin69** [python-pillow/Pillow#6666]
Hello, i have an image,the mode is L ,and the icc profile is Dot Gain 20%.I want to transform the profile to sRGB,but i get an error like this:
PIL.ImageCms.PyCMSError: cannot build transform

The image is below:
![20221017091046tozprvqvsylty8drqim6](https://user-images.githubusercontent.com/34527159/196099247-fd4f213e-555a-4868-a446-132d120f4b00.jpeg)

and my code is below:
```python
from PIL import Image, ImageCms
import io

def main():
    srgb_icm_path = "C:/Windows/System32/spool/drivers/color/sRGB Color Space Profile.icm"
    srgb_profile = ImageCms.ImageCmsProfile(srgb_icm_path)
    image = Image.open("./wwww.jpeg")
    if image.mode != "RGB":
        image = image..convert("RGB")
    profile = image.info.get("icc_profile")
    new_image = ImageCms.profileToProfile(customerImage, io.BytesIO(profile), srgb_profile, 0, "RGB")  # error
```
I will waiting for your reply,Thanks!

**Comment by radarhere** [comment]
Pillow uses lcms2, which is failing with the error "Wrong input color space on transform".

Could you attach a copy of sRGB Color Space Profile.icm? And let us know what `customerImage` is? It would be better for us to be confident that we are replicating your situation exactly.

**Comment by julin69** [comment]
Where to get Icms2?

**Comment by radarhere** [comment]
If you didn't have lcms2 already installed, I expect Pillow to fail with a different error, so I don't think that is your problem. That said, you can download lcms2 from https://sourceforge.net/projects/lcms/files/

I've found that if you remove `image.convert("RGB")`, then your code works, and you still end up with an RGB image.
```python
from PIL import Image, ImageCms
import io

def main():
    srgb_icm_path = "C:/Windows/System32/spool/drivers/color/sRGB Color Space Profile.icm"
    srgb_profile = ImageCms.ImageCmsProfile(srgb_icm_path)
    image = Image.open("./wwww.jpeg")
    profile = image.info.get("icc_profile")
    new_image = ImageCms.profileToProfile(image, io.BytesIO(profile), srgb_profile, 0, "RGB")
```

**Comment by radarhere** [comment]
The error I found from lcms2 was "Wrong input color space on transform". You converted the image from L to RGB, and then tried to apply the original color profile to the transformed image - I haven't verified this in detail, but I think that LCMS2 figured out that the color profile was for an L mode image, not an RGB one, and didn't like that.

**Comment by julin69** [comment]
Now i understand the reason, thanks！Wish you a happy day at life.

**Comment by radarhere** [comment]
I can confirm that the LCMS2 error is happening because of a mismatch between the mode of the image, RGB, and the GRAY type of the profile.
