### ISSUE TITLE
APNG frames are cut off when saving

### ISSUE THREAD

**Issue by BootsManOut** [python-pillow/Pillow#6672]
When exporting animated PNG files as APNG, based of a PNG image sequence, it cuts 2 frames in half.

Here is the code I use:
```python
import PIL
from PIL import Image as Img
from os import walk

mypath="original character folder"

#import files:
files = []
for (dirpath, dirnames, filenames) in walk(mypath):
    files.extend(filenames)
    break
#import as PIL image:
images = []
for f in files:
    images.append(Img.open(mypath+"/"+f))

#Export as APNG:
images[0].save("exportfolder/exportimage.apng", disposal=2, save_all=True,
                                      append_images=images[1:], loop=0,
                                      duration=200, optimize=False, lossless=True)
```

The original images contain all frames. When exported as gif you can see all frames:
![characters animation](https://user-images.githubusercontent.com/63544082/197062023-55dfa6df-3e3b-4ec6-9523-8cb48271c247.gif)

And this is what it looks like exported as animated APNG:
![exportimage animation](https://user-images.githubusercontent.com/63544082/197062113-cc688d0b-4612-4abf-a07f-1d555a835fab.gif)

Here you can use this folders and place them in the project folder to test it out:
[original character folder and export folder containing apng export file.zip](https://github.com/python-pillow/Pillow/files/9834293/original.character.folder.and.export.folder.containing.apng.export.file.zip)

**Comment by radarhere** [comment]
I don't expect it to make a difference, but just for clarity - your 'original character folder' in the zip contains 'characters animation.00 animation.gif'. That was a mistake, yes?

**Comment by BootsManOut** [comment]
Yes, sorry, I still had the gif export in that folder. I updated the file, thanks for letting me know!

**Comment by radarhere** [comment]
I've found that if you remove `disposal=2` from your code, the image appears correctly.
![exportimage](https://user-images.githubusercontent.com/3112309/197149536-b80f4ca9-cff1-4163-b7c9-4fe2f7cef203.png)

**Comment by BootsManOut** [comment]
> I've found that if you remove `disposal=2` from your code, the image appears correctly. ![exportimage](https://user-images.githubusercontent.com/3112309/197149536-b80f4ca9-cff1-4163-b7c9-4fe2f7cef203.png)

Okay, awesome!
From what I read online, I understood the disposal should do the same as the disposal in gif files, but I assume that's not the case?
I found the 'blend' argument would do for APNG what 'disposal' does for gifs.

I'm not sure if disposal=2 is supposed to cut frames in half like that for APNGs, but from my side the issue is resolved anyways, by removing the argument as you said.

Thank you very much for your help, @radarhere !

**Comment by radarhere** [comment]
When running your original code, I noticed that the first frame was empty. I've created PR #6683 to fix that.
