### ISSUE TITLE
Typing difficulty because `Image` is a module and also a class

### ISSUE THREAD

**Issue by scarf005** [python-pillow/Pillow#6676]
### What did you do?
```py
from PIL import Image

def foo(img: Image) -> None:
	...
```
and got `Module "PIL.Image" is not valid as a typemypy(error)`.

### What did you expect to happen?
functions such as `Image.open` are classmethod of class `Image`.

### What actually happened?
`Image` was actually an module, so for typing you need to type `Image.Image`, such as
```py
from PIL import Image

def foo(img: Image.Image) -> None:
	...
```

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 22.04
* Python: Python 3.11.0rc2
* Pillow: Name: Pillow-SIMD 9.0.0.post1

**Comment by Yay295** [comment]
related #6614

**Comment by radarhere** [comment]
While this might have been an unfortunate choice from days long ago, is there really any way to improve this situation without breaking almost all code that currently uses Pillow?

**Comment by madeddy** [comment]
- Rename one of them
- Alias the old to the new name
- Deprecate it timely
- Output a obtrusive deprecation warning
I don't think anybody can do more with such a double bind.

**Comment by radarhere** [comment]
I've created PR #7639 as a possible solution to this, adding `ImageType` as an alias for `Image.Image`.

This is not intended to in any way mark `Image.Image` for future removal though. It is just an addition to allow for simpler type hinting.

**Comment by radarhere** [comment]
[Further thought](https://github.com/python-pillow/Pillow/pull/7639#issuecomment-1872303265) has decided against #7639.
> Image.Image vs ImageType is adding abstraction on top of something which isn't particularly complex in the first place, only save two chars, at the cost of another layer of indirection.

Internal discussion has agreed that we shouldn't make a breaking change, for the sake of backwards compatibility, so there is nothing to be done here.
