### ISSUE TITLE
Support float values for sizes in ImageFont.truetype 

### ISSUE THREAD

**Issue by DeusAres** [python-pillow/Pillow#6689]
When drawing on smaller images, float precision would be needed, because the text size between, let's say, 31 and 32 points is much

The workaround is to draw text on another canvas, crop to real size, resize to needed size and pasting, quite annoying but still working

**Comment by nulano** [comment]
My understanding is that the size is given in pixels, not points, so it is not clear to me what benefit fractional sizes would have?

I am probably wrong about this, but I would imagine that 31.5 pixels would be the same as 32, except the top and bottom are blurry.

However, this should be trivial to support just by inlining the FreeType [`FT_Set_Pixel_Sizes` function](https://gitlab.freedesktop.org/freetype/freetype/-/blob/master/src/base/ftobjs.c#L3526) used currently in: https://github.com/python-pillow/Pillow/blob/8ed46cd5687b29b41fed7a85e65fb53cb956c0ca/src/_imagingft.c#L188

**Comment by DeusAres** [comment]
Strange thing I've noticed is that before, on `8.4.0` the size was in points, I just upgraded to latest stable version to see if there was difference but nope

@nulano I can give you an example. I'm trying to fit a text in a image `1000px` wide. With a function purposely done for this, I calculated that the size to fit it is `31`, but the width of the text is `969`. Let's use `32` then, the width is `1026`

So in my opinion, if points or whatever system is used for fonts, floats should be used for granular precision and to avoid the workaround mentioned 
> The workaround is to draw text on another canvas, crop to real size, resize to needed size and pasting, quite annoying but still working

**Comment by nulano** [comment]
> Strange thing I've noticed is that before, on 8.4.0 the parameter description for size was in points, and now is in pixels, I just upgraded to latest stable version to see if there was difference but nope

There was an error in the documentation.

> @nulano I can give you an example. I'm trying to fit a text in a image 1000px wide. With a function purposely done for this, I calculated that the size to fit it is 31, but the width of the text is 969. Let's use 32 then, the width is 1026

Ah, I see. Your concern is the horizontal size, not the vertical. I suppose that might be useful, yes.

**Comment by DeusAres** [comment]
> Edit: Note however, that due to kerning and other details you might still not get the exact size even if you use a float, especially if you use basic layout instead of Raqm.

With some math you can get the exact size of your text, see more [here](https://github.com/DeusAres/funPIL/blob/master/funPIL.py#L373) (note the return int() because of parameter limitation)




> Ah, I see. Your concern is the horizontal size, not the vertical. I suppose that might be useful, yes.

It's not only about horizontal size, it's vertical too

**Comment by nulano** [comment]
> With some math you can get the exact size of your text, see more [here](https://github.com/DeusAres/funPIL/blob/master/funPIL.py#L373) (note the return int() because of parameter limitation)

You can try to calculate the exact size, but even if you select this size, and the font is rendered at this size, you might find it does not exactly fit your box. This is because a font might not scale linearly due to hinting and other effects. You might try to use [binary search](https://en.wikipedia.org/wiki/Bisection_method) or another method, but I'm not sure the scaling is even guaranteed to be monotone.

> It's not only about horizontal size, it's vertical too, but my example was peculiar

I'm assuming you are referring to multiline text here. I'd suggest nudging the `spacing` parameter might look better, but yes, that was an oversimplification on my part.

**Comment by radarhere** [comment]
I've created PR #7107 to resolve this.
