### ISSUE TITLE
Unnecessary use of ping

### ISSUE THREAD

**Issue by uyh39f** [python-pillow/Pillow#6694]
ImageShow.get_command includes the command 
```
f'start "Pillow" /WAIT "{file}" '
"&& ping -n 4 127.0.0.1 >NUL "
f'&& del /f "{file}"'
```

Based on my limited understanding of python, ping is being used to kill some time.  It seems like sleep() might be a better option here.
I don't know how to use git so I don't know how to propose a change unfortunately.

**Comment by nulano** [comment]
The Windows command line does not have a built-in sleep function. A common workaround us to use ping with the local address instead.

**Comment by uyh39f** [comment]
That makes sense, thanks!
