### ISSUE TITLE
Exception parsing all-black PGM images

### ISSUE THREAD

**Issue by sbliven** [python-pillow/Pillow#6732]
### What did you do?

Pillow 9.2.0 and newer throws an exception when parsing an all-black PGM image. The following snippet encodes a 1-pixel black image:

```python
from io import BytesIO
from PIL import Image
Image.open(BytesIO(b"P5 1 1 0 \0"))
```
The ascii '0' byte is the maximum value from the image, and is used to determine the bit depth. Maxval < 255 indicates an 8-bit data encoding.

### What did you expect to happen?

In version 9.1.1 this produces a one-pixel black image.

### What actually happened?

In 9.2.0 and 9.3.0 I get the following exception:

```
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/miniconda/envs/pgm/lib/python3.10/site-packages/PIL/Image.py", line 3172, in open
    im = _open_core(fp, filename, prefix, formats)
  File "/usr/local/miniconda/envs/pgm/lib/python3.10/site-packages/PIL/Image.py", line 3158, in _open_core
    im = factory(fp, filename)
  File "/usr/local/miniconda/envs/pgm/lib/python3.10/site-packages/PIL/ImageFile.py", line 116, in __init__
    self._open()
  File "/usr/local/miniconda/envs/pgm/lib/python3.10/site-packages/PIL/PpmImagePlugin.py", line 125, in _open
    raise ValueError(
ValueError: maxval must be greater than 0 and less than 65536
```

### What are your OS, Python and Pillow versions?

* OS: MacOS
* Python: 3.10
* Pillow: 9.2.0, 9.3.0

**Comment by Yay295** [comment]
This commit is probably what caused it. 81b473f9d2325540e858aba5cfd688ad1df25806

Looks like the range should be [0, 65536) not (0, 65536). Or [0, 65535] or (-1, 65536).

**Comment by radarhere** [comment]
https://netpbm.sourceforge.net/doc/pgm.html states that
> The maximum gray value (Maxval), again in ASCII decimal. Must be less than 65536, and more than zero.

So I would conclude that your image is invalid.

Did you come across an image in the wild with this maxval?

**Comment by Yay295** [comment]
Two lines later it states

> Each gray value is a number from 0 through Maxval, with 0 being black and Maxval being white.

So one of those lines is wrong.

**Comment by radarhere** [comment]
https://netpbm.sourceforge.net/doc/pgm.html also states
> Each gray value is a number from 0 through Maxval, with 0 being black and Maxval being white.

This actually explains why maxval should be greater than zero. When a value is 0, it is black. When a value is maxval, it is white. When a value is both 0 and maxval because they are the same... it is both white and black? Or rather, there's as much argument to say that it is black as there is to say that it is white.
