### ISSUE TITLE
Support ImageGrab from clipboard on Linux via xclip and wl-clipboard

### ISSUE THREAD

**Issue by AllanChain** [python-pillow/Pillow#6751]
Currently, `grabclipboard` raises `NotImplementedError` on Linux. But I think we can use xclip or wl-clipboard if they are installed. A subprocess call saving the image to a temporary file should be enough.

```sh
xclip -selection clipboard -t image/jpeg -o > test.jpg  # Edit 1
wl-paste --type image/jpg > test.jpg
```

I'm willing to help implement this feature.

### What did you do?

Try to grab an image from the clipboard on Linux

### What did you expect to happen?

The image is grabbed

### What actually happened?

```
NotImplementedError: ImageGrab.grabclipboard() is macOS and Windows only
```

### What are your OS, Python and Pillow versions?

* OS:  Linux (Manjaro KDE)
* Python: 3.10.8
* Pillow: 9.3.0

```python
from PIL.ImageGrab import grabclipboard
grabclipboard()
```

**Comment by radarhere** [comment]
Considering that we support [`gnome-screenshot` in `ImageGrab.grab`](https://github.com/python-pillow/Pillow/blob/0ec32a30120cb22b533fd8563749d44bd5d3f78f/src/PIL/ImageGrab.py#L64-L75), this seems reasonable.

**Comment by radarhere** [comment]
I experimented with this, but found when I copied an image, `xclip` didn't work.


https://user-images.githubusercontent.com/3112309/206149271-daab3ab1-854c-4a1a-b2c5-a93094fa329d.mov

**Comment by AllanChain** [comment]
Sorry for the wrong command. I've tested the command for xclip in X11 environment and updated the command.

I don't know whether you are using X windows on Ubuntu when testing the xclip commands though.

**Comment by AllanChain** [comment]
Sorry for the wrong command. I've tested the command for xclip in X11 environment and updated the command.

I don't know whether you are using X windows on Ubuntu when testing the xclip commands though.

**Comment by radarhere** [comment]
Thanks. I've added `xclip` to PR #6783 as well.

**Comment by benzen3** [comment]
I'm trying to use ImageGrab in Google Colab and getting the error:

`NotImplementedError: wl-paste or xclip is required for ImageGrab.grabclipboard() on Linux
`
which brought me here. 

wl-paste and xclip are not Python projects and so not supported in Google Colab. 

Any workarounds possible?

**Comment by AllanChain** [comment]
@benzen3 I think Python on Google Colab have no access to your system clipboard, because the Python process is running remotely. Therefore, it is impossible, and makes no sense, to support Google Colab.

As a workaround, you can try to run the notebook locally.
