### ISSUE TITLE
Resize the width and height to 90% of original, but the image file size(bytes) become larger

### ISSUE THREAD

**Issue by chucklu** [python-pillow/Pillow#6771]
### What did you do?
resize the width and height of a image to 90%

### What did you expect to happen?

I expect the file size(bytes) become smaller,

### What actually happened?

The file size(bytes) become larger, the original file size is 80KB,
and the resized image file size become ~~700KB~~ 89KB  
### What are your OS, Python and Pillow versions?

* OS: win10 21H2
* Python: Python 3.10.0
* Pillow: '9.3.0' (PIL.__version__)

```python
    im = Image.open(sourceFilePath)
    width, height = im.size
    width, height = int(width*0.9), int(height*0.9)
    im = im.resize((width, height))
    im.save(targetFilePath)
```

![cat](https://user-images.githubusercontent.com/3004057/205123438-4516bc67-d4a0-452b-afd5-65265851d93d.jpg)

**Comment by chucklu** [comment]
I also tried to open the jpg and save it as another jpg with 90% width and height, and the file size changed from 80KB to 89KB.  It's weird too.

**Comment by radarhere** [comment]
You may already know this, but regarding saving it as a PNG,

https://github.com/python-pillow/Pillow/issues/5069#issuecomment-735304799
> JPEGs are a lossy format, which means that perceptually, the image will be close to the original, but individual pixels and values may differ depending on implementations of the underlying jpeg library.  If you need pixel for pixel identical results, you need to use a lossless compression method, like PNGs.  Note that lossless compression usually results in images that are significantly larger than those using lossless compression.

Regarding saving it as a JPG,
if I use `im.save(targetFilePath, optimize=True)` instead, the result is slightly smaller (but still larger than the original).
If I use `im.save(targetFilePath, quality=72, optimize=True)`, then the result becomes a bit smaller than the original.

**Comment by radarhere** [comment]
I just manually decreased the quality value until I found one that gave a smaller file size.

**Comment by chucklu** [comment]
@radarhere  Thanks very much, I appreciate your effort.
