### ISSUE TITLE
PIL doesn't write JPEG comment

### ISSUE THREAD

**Issue by smason** [python-pillow/Pillow#6773]
Following up on an answer I gave to the following stackoverflow question: https://stackoverflow.com/a/74658310/1358308

OP asked how to write a JPEG comment into the file, i.e. not an EXIF comment, but as a COM segment.  The closest issue I could find, #4450, was about reading JPEG comments.

While looking for a solution I cloned the repo (hash 5bdf63e1d170e1db324c5f805c4e838e4d455e98) to see what was going on, but couldn't see anything relevant.

Would be happy to turn this into a pull-request if you think this is a reasonable idea.  I think I'd fix by modifying `_save()` to pull in the comment (from the `applist`) by appending to `extra` in a similar way as `icc_profile`:

https://github.com/python-pillow/Pillow/blob/948678633924fd62b4ab1cc632acd218ad6796ba/src/PIL/JpegImagePlugin.py#L714-L736

Comments appreciated!

**Comment by nicbou** [comment]
Thanks for this patch Sam. It's a significant improvement. Could you add a mention in the documentation?

**Comment by radarhere** [comment]
It should already be mentioned in the documentation, under https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-saving

> **Saving**
> The [save()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) method supports the following options:
> ...
> **comment**
> A comment about the image.
>
> New in version 9.4.0.
