### ISSUE TITLE
Getting IFD1 exif information

### ISSUE THREAD

**Issue by cobi-s** [python-pillow/Pillow#6777]
Follow-up to #6641 

A test image could be the following:
https://www.sun.ac.za/english/test-site/EXIF/sa.jpg

Please find below a code sample that uses the piexif library to extract all available exif information.

I wasn't able to retrieve the same information using only Pillow. In particular, not having the offsets to IFD1 and the embedded thumbnail makes it impossible (for me) to retrieve the tags from IFD1 as well as the raw data for the embedded thumbnail.

```python
from PIL import Image
from PIL.ExifTags import TAGS, GPSTAGS
import piexif

def lookup_tag(tag, ifd):
    lu = GPSTAGS if ifd == 'GPS' else TAGS
    try:
        return f'0x{tag:04x}: {lu[tag]}'
    except:
        return f'0x{tag:04x}: ???'

def print_dict(data):
    for ifd, val in data.items():
        print(f'{ifd}:')
        if ifd == 'thumbnail':
            print(f'    {len(val)} bytes')
        else:
            for tag in val:
                print(f'    {lookup_tag(tag, ifd)}: {val[tag]}')

path = 'sa.jpg'

with Image.open(path) as i:
    d = piexif.load(i.info['exif'])
    print_dict(d)
```

**Comment by radarhere** [comment]
I've added another commit to #6748. With that,
```python
from PIL import Image, ExifTags
im = Image.open("sa.jpg")
im.get_child_images()[0].save("thumbnail.jpg")
```
gives

![thumbnail](https://user-images.githubusercontent.com/3112309/205860827-44b36273-78e3-4d7b-93ef-60776001b9cf.jpg)

**Comment by mixmastamyk** [comment]
Hi, `get_child_images()` is convenient but a bit higher-level than I was looking for.  Digging into the source to see how it works I see it is using hardcoded constants.  Mildly surprising when so much trouble has gone into creating the Enums:

https://github.com/radarhere/Pillow/blob/main/src/PIL/Image.py#L1568

https://github.com/radarhere/Pillow/blob/main/src/PIL/Image.py#L1580

https://github.com/radarhere/Pillow/blob/main/src/PIL/Image.py#L1584

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/8611 to replace the constants.
