### ISSUE TITLE
8.4.0 when ImageFile.LOAD_TRUNCATED_IMAGES = True

### ISSUE THREAD

**Issue by Rahul-Matta** [python-pillow/Pillow#6781]
```python
# we are getting **builtins:OSError**
# convert image to 8-bit grayscale and resize to standard PDF 8 1/2 x 11 dimensions `based` on a res of 72 DPI.
img = img.convert("L").resize(settings.IMG_SIZE, Image.ANTIALIAS)
```

Research indicated this `ImageFile.LOAD_TRUNCATED_IMAGES = True` setting could fix that. However, after releasing this we discovered threat CPU usage on the server would spike, REAL high (specifically, it appears that we had a lot of FUTUEX locks just hanging around and all four processors would hit **100%** usage on the libc library. Given that we also bumped the pillow package (and the errors disappeared after setting this value, we'd like to keep this.)

so is this issue fixed in any version or any update or idea to fix it?

**Comment by radarhere** [comment]
Would you be able to attach a copy of the image?

**Comment by radarhere** [comment]
Also, regardless of whether or not upgrading resolves your problem, we do encourage users to upgrade to the latest version of Pillow.

https://pillow.readthedocs.io/en/stable/releasenotes/index.html
> Please use the latest version of Pillow. Functionality and security fixes should not be expected to be backported to earlier versions.
