### ISSUE TITLE
A frame is *ignored* when a GIF is saved with a completely transparent frame included

### ISSUE THREAD

**Issue by hsohliyt105** [python-pillow/Pillow#6785]
### What did you do?
I tried to save a gif file with a completely transparent frame.

### What did you expect to happen?
![expected](https://user-images.githubusercontent.com/62872159/206250174-2ac104fc-cd02-4da7-af72-213df161de3d.gif)

### What actually happened?
![example](https://user-images.githubusercontent.com/62872159/206251051-d40c78b8-2159-4a45-89c2-199683232134.gif)
You can see that the last empty frame does not appear. Instead, the duration of the previous frame is delayed.

### What are your OS, Python and Pillow versions?

* OS: I tried both Windows 10, MacOS, and Raspbian
* Python: 3.10.4
* Pillow: 9.3.0

Note that I came up with a simple code rather than my original code to keep this simple.
```python
from PIL import Image, ImageDraw

image1 = Image.new("RGBA", (100, 100), "#00000000")
image2 = Image.new("RGBA", (100, 100), "#00000000")
image3 = Image.new("RGBA", (100, 100), "#00000000")

draw = ImageDraw.Draw(image2)
draw.rectangle((25, 25, 75, 75), fill = "#FF0000FF")

image1.save("example.gif", format="GIF", save_all=True, disposal=2, loop=0, duration=1000, append_images=[image2, image3])
```

This also happens when a completely black (#000000) image is appended, regardless of the transparency. 
```python
from PIL import Image, ImageDraw

image1 = Image.new("RGBA", (100, 100), "#00000000")
image2 = Image.new("RGBA", (100, 100), "#00000000")
image3 = Image.new("RGBA", (100, 100), "#00000000")

draw = ImageDraw.Draw(image2)
draw.rectangle((25, 25, 75, 75), fill = "#FF0000FF")

draw = ImageDraw.Draw(image3)
draw.rectangle((25, 25, 75, 75), fill = "#000000FF")

image1.save("example.gif", format="GIF", save_all=True, disposal=2, loop=0, duration=1000, append_images=[image2, image3])
```

*edit
I checked that "white" (#FFFFFF00) transparent images are normally appended to the image. 

Example code:
```python
from PIL import Image, ImageDraw

image1 = Image.new("RGBA", (100, 100), "#FFFFFF00")
image2 = Image.new("RGBA", (100, 100), "#FFFFFF00")
image3 = Image.new("RGBA", (100, 100), "#FFFFFF00")

draw = ImageDraw.Draw(image2)
draw.rectangle((25, 25, 75, 75), fill = "#FF0000FF")

image1.save("example.gif", format="GIF", save_all=True, disposal=2, loop=0, duration=1000, append_images=[image2, image3])
```
This will produce the wanted result. But anyways, I think this still is an issue.

**Comment by radarhere** [comment]
I've created PR #6787 to resolve this.
