### ISSUE TITLE
Ghosting/repeated frames when converting an animated image from .webp to .gif

### ISSUE THREAD

**Issue by finahdinner** [python-pillow/Pillow#6794]
### What did you do?
Converted an animated .webp file to a .gif.

### What did you expect to happen?
I would have expected the resulting .gif file to produce the same frames as the .webp file from which it was derived.

### What actually happened?
When saving an animated .webp image as a .gif, there appears to be ghosting/repeated frames in the output .gif file.

### What are your OS, Python and Pillow versions?
OS: Windows 10 Home (Build 19045)
Python: 3.10.8
Pillow: 9.3.0

```python
img = Image.open(file_path)
img.info.pop('background', None) # remove background
img.save(converted_img_path, save_all=True)
```

Example URL of an original .webp file: https://cdn.7tv.app/emote/60abf171870d317bef23d399/4x.webp

Example of the output .gif:

![60abf171870d317bef23d399](https://user-images.githubusercontent.com/87808600/206719564-954a7a16-1934-444f-909c-c52dc788adbd.gif)

**Comment by radarhere** [comment]
I find that if you add `disposal=2` when saving,
```python
from PIL import Image
img = Image.open('4x.webp')
img.info.pop('background', None) # remove background
img.save('out.gif', save_all=True, disposal=2)
```
you get
![out](https://user-images.githubusercontent.com/3112309/206830387-a4a542fd-de5d-4a7b-9709-a5edfa407f7e.gif)

The disposal property is [part of the GIF specification](https://www.w3.org/Graphics/GIF/spec-gif89a.txt). Setting it to 2 means "Restore to background color" after this frame. This is also mentioned in [Pillow's documentation.](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif-saving)

**Comment by radarhere** [comment]
@finahdinner does that resolve your problem?

**Comment by finahdinner** [comment]
> 

It does, thank you! Apologies for the slow response.
