### ISSUE TITLE
AttributeError: 'int' object has no attribute 'encode'

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#6799]
This image:  ![rotateexif](https://user-images.githubusercontent.com/274624/207291409-c2d12ce9-14b6-4f2c-bfb4-57455c6ed290.jpg)

Testcase:
 ````python
import PIL.Image
with PIL.Image.open('/tmp/rotateexif.jpg') as img:
    PIL.ImageOps.exif_transpose( img )
````

**Comment by radarhere** [comment]
The image has a GPSLongitudeRef tag that [should be ASCII](https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/gps/gpslongituderef.html), but is instead SHORT.

I've created PR #6800 to handle this.

**Comment by doublex** [comment]
@radarhere 
They are always that fast!
