### ISSUE TITLE
Combining diacritics are not displayed in the proper position

### ISSUE THREAD

**Issue by Vuizur** [python-pillow/Pillow#6823]
First of all, I hope that you all have a great holiday! And thank you very much for all the effort in maintaining this (very likely super complex) project!

Creating text on images with pillow currently has problems with combining diacritics. The specific character that I am having this issue with is 'COMBINING ACUTE ACCENT' (U+0301). 
Some background info: In languages like Spanish all accents (like á) could in theory be represented with this combining diacritic, but in practice (almost) never is, because there exists LATIN SMALL LETTER A WITH ACUTE, so one single codepoint which contains both the a and the accent.

For some languages, like Russian, these single codepoint versions don't exist. If we have a dictionary entry which marks the stressed syllable - this is the primary use case -, we need to use combining accents. The word ужима́ть (copy-pasted from Wiktionary), for example, has the а́ represented as CYRILLIC SMALL LETTER A + COMBINING ACUTE ACCENT. 

I now want to print such a stressed word on a picture using Pillow, but am meeting some problems. I created the following example code:

```python
from PIL import Image, ImageDraw, ImageFont

text = "ужима́ть"
img = Image.new("1", (300, 80), 1)
font = ImageFont.truetype(
    #r"C:\Users\myname\AppData\Local\Microsoft\Windows\Fonts\Montserrat-SemiBold.ttf",
    #r"C:\Windows\Fonts\arial.ttf",
    r"C:\Windows\Fonts\calibri.ttf",
    50,
    encoding="unic",
)
draw = ImageDraw.Draw(img)
draw.text((40, 0), text, font=font, fill=0)
img.save("test_unicode.png", "PNG")
```

The results differ from font to font:

For Calibri, it works beautifully:
![test_unicode](https://user-images.githubusercontent.com/29223849/209461740-790100e3-9cd0-456f-aa5d-3890957afde5.png)
For Arial, it already works pretty badly, the combining accent is somehow put between the two characters:
![test_unicode](https://user-images.githubusercontent.com/29223849/209461775-5f0c0555-36eb-4721-8d41-96cae5be995a.png)
And for the font that I actually wanted to use, Montserrat semibold, it seems to be entirely wrong and exactly one character to the right:
![test_unicode](https://user-images.githubusercontent.com/29223849/209461798-532f7184-44fb-4101-a149-88e1a7e78ce6.png)

I don't know what is going on here. I also tested the acute accented versions of the word in Montserrat Semibold in the online Google Fonts previewer and also in Libreoffice, the accent was set perfectly in both cases. This makes it even more mysterious.

Thanks for the help! 

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.11
* Pillow: 9.3.0

**Comment by radarhere** [comment]
Hi. Testing, I find that I'm able to replicate your result if I use basic layout. Using raqm, I get the correct results.

So this should just be a problem of enabling raqm support.

https://pillow.readthedocs.io/en/stable/installation.html#windows-installation
> Raqm support requires FriBiDi to be installed separately

https://pillow.readthedocs.io/en/stable/installation.html#external-libraries
> Pillow wheels since version 8.2.0 include a modified version of libraqm that loads libfribidi at runtime if it is installed. On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-Link Library Search Order (Microsoft Docs)](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-desktop-applications) (fribidi-0.dll or libfribidi-0.dll are also detected).

The DLL can be downloaded from https://github.com/python-pillow/Pillow/suites/10039183318/artifacts/488327401

**Comment by Vuizur** [comment]
Thank you very much for the fast answer😀. I did as you told and downloaded the linked DLL and put it in the same folder as python.exe in my venv.

I first was very happy that it worked, but then I realized that it seems to work for all characters except for я, where the acute accent is shifted one position the the right. But knowing this, I went back to Libreoffice and Google Fonts and checked it there, and there it also seemed to be broken. So this time it apparently really is the fonts fault. I swear I am going crazy 😁

Update: After a bit of searching I found the official Montserrat repo and downloaded the latest version from there. And here it works perfectly! (This is the third time I download this font, and finally get a version that works after buggy experiences with FontsFree and Google Fonts, both broken in different ways.)

```
text = "Нарья́н-Ма́р"
text = "я́стреб"
#text = "говори́ть"
img = Image.new("1", (400, 80), 1)
font = ImageFont.truetype(
    r"C:\Users\hanne\AppData\Local\Microsoft\Windows\Fonts\Montserrat-SemiBold.ttf",
    #r"C:\Windows\Fonts\arial.ttf",
    #r"C:\Windows\Fonts\calibri.ttf",
    50,
    encoding="unic",
)
draw = ImageDraw.Draw(img)
draw.text((40, 0), text, font=font, fill=0)
img.save("test_unicode.png", "PNG")
```

![test_unicode](https://user-images.githubusercontent.com/29223849/209483103-f2c2a6be-a84e-4250-a341-c3c22ffc6021.png)
![test_unicode](https://user-images.githubusercontent.com/29223849/209483107-4f8c30ec-6e50-4a33-8f14-5369e217650a.png)
