### ISSUE TITLE
How image saturation picture will handle?

### ISSUE THREAD

**Issue by rsurendraidexcel** [python-pillow/Pillow#6824]
Image Pixel RGB is perfect detection.

what about  Image RGB along with Saturation pixel?

**Comment by radarhere** [comment]
Hi. I don't understand your question.

Are you talking about HSV (hue, saturation, value)? Yes, Pillow supports HSV. See https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes

Or are you trying to adjust the saturation of an RGB image?

Would you be able to rephrase your question with some more detail, and an example of what you are trying to do? Perhaps attaching an image?

**Comment by radarhere** [comment]
There is no RGBS mode, if that is what you meant. But if you have an image that you think is in RGBS mode, please attach.
