### ISSUE TITLE
trasparency and GIF

### ISSUE THREAD

**Issue by LingHu01** [python-pillow/Pillow#6837]
* OS:  windows 10 (should not matter)
* Python: 3.11
* Pillow: 9.3.0

i'm trying to resize a GIF, unpacking every single frame i had no issue, they all have the correct trasparent background, but when i try to create/save the GIF only the first frame will have the correct trasparency, the other ones will have black background.

```
from PIL import Image

def process_gif(in_path, out_path= 'out.gif', size= (32,32)):
    with Image.open(in_path) as im :
        images = []
        durations = []
        for i in range(im.n_frames - 1, -1, -1):
            im.seek(i)
            im.thumbnail(size, Image.Resampling.LANCZOS) # noqa
            im_temp = im.copy()
            print(im_temp.info)
            images.insert(0, im_temp)
            durations.append(im.info['duration'])
        images[0].save(
            out_path,
            format='gif',
            save_all=True,
            append_images=images[1 :],
            duration=durations,
            disposal=2,
            optimize=False
        )
        for i, image in enumerate(images):
            image.save(f'{i}.png')
```
i iterate backwards because thumbnail will raise an error if i iterate normaly after one cicle(i think is because im.size pick the first frame for reference)

imput image :
![in](https://user-images.githubusercontent.com/118489886/209860978-e92ae7a2-4960-4d82-89ac-0b2638e65db9.gif)

those are the single frame my code produced:
![0](https://user-images.githubusercontent.com/118489886/209861019-5032c16d-8d25-4190-a053-20b0813b4f89.png)![1](https://user-images.githubusercontent.com/118489886/209861009-366166c4-9da6-4b9d-92ce-00636f003a8b.png)![2](https://user-images.githubusercontent.com/118489886/209861012-7e11e8b4-f649-4430-9623-de9048febdc6.png)![3](https://user-images.githubusercontent.com/118489886/209861016-6e0e1d28-d030-4a59-bc38-904a30cbf046.png)

output:
![out](https://user-images.githubusercontent.com/118489886/209861351-61f9874e-9138-4426-953e-b4a20cee479c.gif)

I tried to include background= (0, 0, 0, 0) but getcolor in ImagePalette.py will raise an `ValueError: cannot add non-opaque RGBA color to RGB palette`

upon further inspection using `print(im_temp.info)` before inserting the fram i got this result in console
```
{'version': b'GIF89a', 'background': 0, 'loop': 0, 'duration': 70}  #last frame
{'version': b'GIF89a', 'background': 0, 'loop': 0, 'duration': 70}
{'version': b'GIF89a', 'background': 0, 'loop': 0, 'duration': 70}
{'version': b'GIF89a', 'background': 0, 'loop': 0, 'duration': 70, 'transparency': 48, 'extension': (b'NETSCAPE2.0', 219)} #first frame
```
it may be related to trasparency attribute?

**Comment by LingHu01** [comment]
using this after reading #6832 solved my problem
```
from PIL import GifImagePlugin
GifImagePlugin.LOADING_STRATEGY = GifImagePlugin.LoadingStrategy.RGB_AFTER_DIFFERENT_PALETTE_ONLY
```

**Comment by radarhere** [comment]
As an explanation, by default, GifImagePlugin does try to detect the transparency in your images, but after [it is converted to P](https://github.com/python-pillow/Pillow/blob/f0b494ede583d9080548cc6d589bb376053ca93b/src/PIL/GifImagePlugin.py#L485), the first pixel is `(0, 0, 0, 1)` - translucent, rather than transparent, which we can't express in a GIF.

If the default behaviour was to be improved here, it would be a conversion problem.
