### ISSUE TITLE
QOI support

### ISSUE THREAD

**Issue by Max1Truc** [python-pillow/Pillow#6844]
### What did you do?

Tried to open a QOI image ( https://qoiformat.org/ ) with Pillow (`Image.open("picture.qoi")`)

The picture is in this zip file (a 2-seconds stick-man) : [picture.zip](https://github.com/python-pillow/Pillow/files/10327604/picture.zip)

### What did you expect to happen?

I would love Pillow to recognize the file type and open the image.

### What actually happened?

Pillow can't recognize the QOI format.

```python
>>> from PIL import Image
>>> Image.open("picture.qoi")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/python3.10/site-packages/PIL/Image.py", line 3186, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'picture.qoi'
```

### What are your OS, Python and Pillow versions?

* OS: Manjaro Linux
* Python: 3.10.8
* Pillow: 9.3.0

### To replicate

```python
from PIL import Image
Image.open("picture.qoi")
```

**Comment by Max1Truc** [comment]
I would be happy to contribute to Pillow by adding QOI support btw

**Comment by radarhere** [comment]
Thanks for the test image, that was a helpful reference point.

I've created PR #6852 to add support for reading QOI images.

**Comment by Max1Truc** [comment]
Oh thanks, just had a look and this seems like a very clean implementation
