### ISSUE TITLE
Pillow not able to find libraqm in AWS lambda

### ISSUE THREAD

**Issue by GibreelAbdullah** [python-pillow/Pillow#6860]
I am writing some text to an image, this service is deployed in AWS lambda. Pillow was added as a layer. Since it has some RTL text it needs libraqm to work.

I used AWS cloudshell to download and install libraqm v 0.6 (the latest version 0.9 was not supported by the version of rpm on cloudshell) maybe this is the issue.

Pillow was still not able to find the libraqm and throws the below error message.

`setting text direction, language or font features is not supported without libraqm`

(I have tested the same code locally and it works)

OS : Linux on AWS lambda
Python version : 3.9
Pillow version : 9.3

**Comment by radarhere** [comment]
> Pillow was added as a layer

Could you provide some more detail on how you installed Pillow? Was this using https://github.com/keithrozario/Klayers? Or did you do something like https://victorl.in/aws-lambda-layer-cloudshell/?

> Pillow was still not able to find the libraqm and throws the below error message

It would be ideal if you could provide some code that triggers the error message. Or at least, could you let us know what the following code outputs?
```python
from PIL import features
features.pilinfo()
```

**Comment by GibreelAbdullah** [comment]
> Could you provide some more detail on how you installed Pillow?

I installed the packages in my local machine using `pip3 install -U pillow -t .` created a zip and uploaded it to the layer section of lambda. I just now tried https://github.com/keithrozario/Klayers method as well and getting the same result.

sample code

```python
    my_image = Image.open("HadithBackground.png")

    araHadith = '''شَهِدْتُ مِنْ رَسُولِ اللَّهِ صلى الله عليه وسلم مَجْلِسًا وَصَفَ فِيهِ الْجَنَّةَ حَتَّى انْتَهَى ثُمَّ قَالَ صلى الله عليه وسلم فِي آخِرِ حَدِيثِهِ ‏"‏ فِيهَا مَا لاَ عَيْنٌ رَأَتْ وَلاَ أُذُنٌ سَمِعَتْ وَلاَ خَطَرَ عَلَى قَلْبِ بَشَرٍ ‏"‏ ‏.‏ ثُمَّ اقْتَرَأَ هَذِهِ الآيَةَ ‏{‏ تَتَجَافَى جُنُوبُهُمْ عَنِ الْمَضَاجِعِ يَدْعُونَ رَبَّهُمْ خَوْفًا وَطَمَعًا وَمِمَّا رَزَقْنَاهُمْ يُنْفِقُونَ * فَلاَ تَعْلَمُ نَفْسٌ مَا أُخْفِيَ لَهُمْ مِنْ قُرَّةِ أَعْيُنٍ جَزَاءً بِمَا كَانُوا يَعْمَلُونَ‏}‏ ‏.‏'''

    engHadith = '''I was in the company of Allah's Messenger (ﷺ) that he gave a description of Paradise and then Allah's Apostle (ﷺ) concluded with these words: There would be bounties which the eye has not seen and the ear has not heard and no human heart has ever perceived them. He then recited this verse:" They forsake (their) beds, calling upon their Lord in fear and in hope, and spend out of what We have given them. So no soul knows what refreshment of the eyes is hidden for them: a reward for what they did'''

    para = textwrap.wrap(araHadith, width=90)
    current_h, pad = 250, 130

    for line in reverse(para):
        w, h = image_editable.textsize(line, font=font, direction='rtl') # This line is giving error.
        image_editable.text(((imageWidth - w) / 2, current_h), line, font=font)
        current_h += h - pad
.......
```

Output of `features.pilinfo()`

```markdown
Function Logs
Extensions: .jfif, .jpe, .jpeg, .jpg
Features: open, save
--------------------------------------------------------------------
JPEG2000 image/jp2
Extensions: .j2c, .j2k, .jp2, .jpc, .jpf, .jpx
Features: open, save
--------------------------------------------------------------------
MCIDAS
Features: open
--------------------------------------------------------------------
MPEG video/mpeg
Extensions: .mpeg, .mpg
Features: open
--------------------------------------------------------------------
MSP
Extensions: .msp
Features: open, save, decode
--------------------------------------------------------------------
PCD
Extensions: .pcd
Features: open
--------------------------------------------------------------------
PCX image/x-pcx
Extensions: .pcx
Features: open, save
--------------------------------------------------------------------
PIXAR
Extensions: .pxr
Features: open
--------------------------------------------------------------------
PNG image/png
Extensions: .apng, .png
Features: open, save, save_all
--------------------------------------------------------------------
PPM image/x-portable-anymap
Extensions: .pbm, .pgm, .pnm, .ppm
Features: open, save
--------------------------------------------------------------------
PSD image/vnd.adobe.photoshop
Extensions: .psd
Features: open
--------------------------------------------------------------------
SGI image/sgi
Extensions: .bw, .rgb, .rgba, .sgi
Features: open, save
--------------------------------------------------------------------
SPIDER
Features: open, save
--------------------------------------------------------------------
SUN
Extensions: .ras
Features: open
--------------------------------------------------------------------
TGA image/x-tga
Extensions: .icb, .tga, .vda, .vst
Features: open, save
--------------------------------------------------------------------
TIFF image/tiff
Extensions: .tif, .tiff
Features: open, save, save_all
--------------------------------------------------------------------
WEBP image/webp
Extensions: .webp
Features: open, save, save_all
--------------------------------------------------------------------
WMF
Extensions: .emf, .wmf
Features: open, save
--------------------------------------------------------------------
XBM image/xbm
Extensions: .xbm
Features: open, save
--------------------------------------------------------------------
XPM image/xpm
Extensions: .xpm
Features: open
--------------------------------------------------------------------
XVTHUMB
Features: open
```

**Comment by GibreelAbdullah** [comment]
Can you tell me where exactly is pillow looking for libraqm?

I have compiled the latest libraqm code from github and libraqm.so file is now available in the $PATH. Is this what pillow is looking for?

**Comment by nulano** [comment]
From https://pillow.readthedocs.io/en/latest/installation.html#external-libraries:

> libraqm depends on the following libraries: FreeType, HarfBuzz, FriBiDi, make sure that you install them before installing libraqm if not available as package in your system.

> Pillow wheels since version 8.2.0 include a modified version of libraqm that loads libfribidi at runtime if it is installed. 

If you are using an official wheel from PyPI to install Pillow, then you only need to install FriBiDi, since FreeType, HarfBuzz, and Raqm are included in the wheel. The following filenames are searched on Linux to load FriBiDi:
https://github.com/python-pillow/Pillow/blob/927780e55641c8eb6acb0647f91acff3a04e7e2c/src/thirdparty/fribidi-shim/fribidi.c#L46-L49

**Comment by nulano** [comment]
By the way, `textsize` is deprecated, you can instead use

```python
    for line in reverse(para):
        left, top, right, bottom = image_editable.textbbox(line, font=font, direction='rtl')
        image_editable.text((imageWidth / 2, current_h), line, font=font, anchor='ma')  # direction='rtl'?
        current_h += bottom - pad
```

although I would recommend

```python
    line_height = font.getbbox('A')[3]
    for line in reverse(para):
        image_editable.text((imageWidth / 2, current_h), line, font=font, anchor='ma')  # direction='rtl'?
        current_h += line_height - pad
```

or similar.

**Comment by GibreelAbdullah** [comment]
But the error says `setting text direction, language or font features is not supported without libraqm`
It specifically mentions libraqm. And I am using pillow 9.2 downloaded using `pip3 install pillow`, so I guess that is official wheel.

**Comment by nulano** [comment]
(assuming it is the wheel) It can't load the built-in libraqm without loading the system libfribidi.so.

The error message is telling you that you are using basic text layout, but requesting a raqm-only feature. Since you did not specify which layout engine you want to use, Pillow automatically selects basic layout because Raqm layout is not available without loading libfribidi.

**Comment by GibreelAbdullah** [comment]
understood. In the end i was unable to get it work using the normal way.

so, I created a docker container which worked.

Thanks for your help. I will close this since it is not an issue with pillow.
