### ISSUE TITLE
GIF file size

### ISSUE THREAD

**Issue by lxccc812** [python-pillow/Pillow#6863]
When I use the save method to save the picture list, the generated gif memory is too large.
I have used 14 images within 10kb, but the generated gif accounts for about 400k. When I use the same image to generate gif repeatedly, the size of the generated gif is different each time.
What is this situation? Can you answer it.

**Comment by radarhere** [comment]
Hi. You start out talking about memory, but then you switch to talking about file size. Memory is used temporarily during the execution of the script and then released afterwards. File size refers to the amount of space that the created GIF takes up when the script is done. I'm going to presume that you are just talking about file size.

Could you provide a self-contained example to demonstrate what is happening? That is, a copy of the script that you run, with any input images attached?

**Comment by lxccc812** [comment]
![image](https://user-images.githubusercontent.com/110974969/210946450-b9e5b004-49d7-4bf7-bf49-78cd4cfd7261.png)

``` python
from PIL import ImageSequence, Image


def t1():
    image_list = []
    im = Image.open(r'C:\Users\LXC\Desktop\t1\666.gif')
    for index, frame in enumerate(ImageSequence.Iterator(im)):
        rate = 1
        width = frame.size[0]
        height = frame.size[1]
        if width / height >= rate:
            target_height = height
            target_width = height * rate
            point_1x = width / 2 - target_width / 2
            point_1y = 0
            point_2x = width / 2 + target_width / 2
            point_2y = target_height
        else:
            target_width = width
            target_height = width / rate
            point_1x = 0
            point_1y = height / 2 - target_height / 2
            point_2x = target_width
            point_2y = height / 2 + target_height / 2
        cut_frame = frame.crop((point_1x, point_1y, point_2x, point_2y))
        resize_frame = cut_frame.resize((240, 240), Image.ANTIALIAS)
        image_list.append(resize_frame)

    duration = (im.info).get('duration', 30)
    transparency = (im.info).get('transparency', 255)
    loop = (im.info).get('loop', 0)
    comment = (im.info).get('comment', '')
    image_list[0].save(
        r'C:\Users\LXC\Desktop\t1\new666.gif',
        save_all=True,
        include_color_table=True,
        disposal=2,
        append_images=image_list[1:],

        duration=duration,
        transparency=transparency,
        loop=loop,
        comment=comment
    )
```
After I cut and resize each image in the gif, I synthesize a new gif image. Its size is larger than the original gif. On the left is the file size between modifications, and on the right is the file size after modifications.

**Comment by radarhere** [comment]
Could you attach a copy of the original GIF?

**Comment by lxccc812** [comment]
![666](https://user-images.githubusercontent.com/110974969/210952409-e08f875c-8cbd-4e18-af06-278de3b67276.gif)

**Comment by radarhere** [comment]
For this specific example, I find that if you change
```python
resize_frame = cut_frame.resize((240, 240), Image.ANTIALIAS)
```
to
```python
resize_frame = cut_frame.resize((240, 240))
```
then the created GIF is actually smaller than your original GIF.

**Comment by lxccc812** [comment]
According to the method you said, the file is really smaller after modification. But it is still not the effect I want. When I use 14 10 kb or so images to compose a gif, the file size becomes about 500 kb, which is unreasonable and incorrect. I'm not sure why this happened. The folder on the left is the picture I used, and the folder on the right is my composite gif. Its size is too large. I think this is wrong.

![image](https://user-images.githubusercontent.com/110974969/210960958-50a90d3f-eafb-457b-bad0-c6ad3a43bc0d.png)

**Comment by radarhere** [comment]
Could you attach the 14 images?

**Comment by lxccc812** [comment]
![666-0](https://user-images.githubusercontent.com/110974969/210965714-9a1bf246-5033-49c6-953c-7110387ba882.jpg)
![666-1](https://user-images.githubusercontent.com/110974969/210965719-64e7db40-4387-4018-8cf9-df96e096fd69.jpg)
![666-2](https://user-images.githubusercontent.com/110974969/210965723-6639f041-dbd8-490e-9ed1-f1c409f90a3c.jpg)
![666-3](https://user-images.githubusercontent.com/110974969/210965725-c07b5cca-2cf8-4999-977b-f8f0749eca10.jpg)
![666-4](https://user-images.githubusercontent.com/110974969/210965727-3a6f27ee-a429-4dc7-8885-ddbd62d92be4.jpg)
![666-5](https://user-images.githubusercontent.com/110974969/210965731-82abccab-428d-4055-9146-ba5a5d0ac957.jpg)
![666-6](https://user-images.githubusercontent.com/110974969/210965735-572ca499-c6ac-4e83-98f0-c4c6b0d257ea.jpg)
![666-7](https://user-images.githubusercontent.com/110974969/210965736-2a5bcbb3-19d4-4b87-8ede-3b02dac90437.jpg)
![666-8](https://user-images.githubusercontent.com/110974969/210965741-b3b056a0-4ec6-4d4e-a96e-9c0f82e57e3f.jpg)
![666-9](https://user-images.githubusercontent.com/110974969/210965747-59606f97-afa9-44d9-992a-0ca1c45e8447.jpg)
![666-10](https://user-images.githubusercontent.com/110974969/210965753-2ec85eed-e6e3-461f-b8ac-a4cab1dfb399.jpg)
![666-11](https://user-images.githubusercontent.com/110974969/210965758-dde373c9-70aa-4039-8204-b641c007877d.jpg)
![666-12](https://user-images.githubusercontent.com/110974969/210965765-3bb21768-6745-411c-bdbd-d1f24985e422.jpg)
![666-13](https://user-images.githubusercontent.com/110974969/210965770-74c1bdb2-d969-45fc-8000-471835fac0e0.jpg)

```
from PIL import Image, ImageSequence


def t2():
    image_list = []
    for i in range(14):
        im = Image.open(fr'C:\Users\LXC\Desktop\t2\666-{i}.jpg')
        print(im.mode)
        image_list.append(im)
    image_list[0].save(
        r'C:\Users\LXC\Desktop\t2\new666.gif',
        save_all=True,
        include_color_table=True,
        disposal=2,
        append_images=image_list[1:],

        duration=10,
        loop=0
    )

```

When I use this code to synthesize images, the gif is too large and not very reasonable
![image](https://user-images.githubusercontent.com/110974969/210969090-8799a773-2b73-47da-b9b4-e9f400e972c8.png)

**Comment by radarhere** [comment]
If I just open a single image and save it as a GIF,
```python
Image.open("0.jpg").save("zero.gif")
```
then the 10kb JPG becomes a 44kb GIF. I tested converting the image with ImageMagick instead of Pillow, and it was 42kb. So I don't think Pillow is doing anything wrong explicitly. JPEGs and GIFs are different, and sometimes a GIF image might be bigger. Over at http://users.wfu.edu/matthews/misc/jpg_vs_gif/JpgVsGif-compact.html, they mention a particular GIF being 2.4 times bigger than a JPEG.

44kb * 14 = 616kb, which is greater than your final file size, so I don't think the problem has anything to do with the animation.

Experimenting, I found that for this specific example, if I insert this new line above `image_list.append(im)`,

```python
im = im.quantize(36, method=Image.Quantize.FASTOCTREE)
```

then your output image is now 180kb.

**Comment by lxccc812** [comment]
I watched the comparison between jpg and gif. It roughly means that the more colors in the image, the bigger the gif. But I still don't understand. I split the original gif to get a lot of pictures, then cut and limit the size of these pictures, and then synthesize the gif. The result is even larger than the original gif, which I can't understand. I observed every step in the process and strictly followed the document. Still can not achieve the effect I want.If I can make this phenomenon clear, I think I can avoid it.

**Comment by radarhere** [comment]
Opening the image and resaving it
```python
from PIL import Image, ImageSequence
im = Image.open("in.gif")
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
	frames.append(frame.copy())
frames[0].save("out.gif", save_all=True, append_images=frames[1:])
```
gives a 493kb GIF.

If we crop it,
```python
from PIL import Image, ImageSequence
im = Image.open("in.gif")
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
    cropped_frame = frame.crop((0, 0, 247, 247))
	frames.append(cropped_frame)
frames[0].save("out.gif", save_all=True, append_images=frames[1:])
```
then it gives a 307kb GIF. Fair enough, it is smaller.

If we crop and resize it with ANTIALIAS,
```python
from PIL import Image, ImageSequence
im = Image.open("in.gif")
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
    cropped_frame = frame.crop((0, 0, 247, 247))
    resized_frame = cropped_frame.resize((240, 240), Image.ANTIALIAS)
    frames.append(resized_frame)
frames[0].save("out.gif", save_all=True, append_images=frames[1:])
```
then it gives a 513kb GIF. Why is this bigger? Here is some code to count the number of colours in the image before and after it is resized.

```python
from PIL import Image, ImageSequence

def get_number_of_colors(frame):
	colors = []
	for x in range(frame.width):
		for y in range(frame.height):
			color = frame.getpixel((x, y))
			if color not in colors:
				colors.append(color)
	return len(colors)

im = Image.open("in.gif")
frames = []
for i, frame in enumerate(ImageSequence.Iterator(im)):
    cropped_frame = frame.crop((0, 0, 247, 247))
    print("Before resizing, there are "+str(get_number_of_colors(cropped_frame))+" colors")
    resized_frame = cropped_frame.resize((240, 240), Image.ANTIALIAS)
    print("After resizing, there are "+str(get_number_of_colors(resized_frame))+" colors")
    frames.append(resized_frame)
frames[0].save("out.gif", save_all=True, append_images=frames[1:])
```
prints
```
Before resizing, there are 91 colors
After resizing, there are 91 colors
Before resizing, there are 93 colors
After resizing, there are 17891 colors
Before resizing, there are 93 colors
After resizing, there are 18622 colors
Before resizing, there are 90 colors
After resizing, there are 18082 colors
Before resizing, there are 93 colors
After resizing, there are 19052 colors
Before resizing, there are 89 colors
After resizing, there are 18140 colors
Before resizing, there are 92 colors
After resizing, there are 18444 colors
Before resizing, there are 90 colors
After resizing, there are 18013 colors
Before resizing, there are 90 colors
After resizing, there are 18097 colors
Before resizing, there are 91 colors
After resizing, there are 17609 colors
Before resizing, there are 91 colors
After resizing, there are 17429 colors
Before resizing, there are 93 colors
After resizing, there are 15807 colors
Before resizing, there are 93 colors
After resizing, there are 16406 colors
Before resizing, there are 93 colors
After resizing, there are 17394 colors
```

The resize operation has introduced more colours. The image has become less simple. It therefore seems reasonable that the GIF is larger.

**Comment by Yay295** [comment]
`Image.ANTIALIAS` is also the old way to refer to `Image.Resampling.LANCZOS`.
https://pillow.readthedocs.io/en/stable/reference/Image.html#resampling-filters
I think `Image.Resampling.NEAREST` may give the smallest size.

**Comment by radarhere** [comment]
@lxccc812 has that explained things?

**Comment by lxccc812** [comment]
The problem has been solved. Thank you for your answer.
