### ISSUE TITLE
Deprecated filters listed on "concepts" page

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6867]
https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-filters
https://pillow.readthedocs.io/en/stable/reference/Image.html#resampling-filters

The "concepts" page lists the `PIL.Image.X` names for the filters, but it should actually use `PIL.Image.Resampling.X`.

**Comment by radarhere** [comment]
As of Pillow 9.4.0, they are actually no longer deprecated - https://pillow.readthedocs.io/en/stable/releasenotes/9.4.0.html#constants

But we should be consistent in what we talk about in the documentation. I've created PR #6868 to resolve this
