### ISSUE TITLE
Fatal Python error for negative radius in ImageFilter.BoxBlur()

### ISSUE THREAD

**Issue by marcelgouka** [python-pillow/Pillow#6873]
Hi,

Python crashes without an exception when a negative radius is passed into ImageFilter.BoxBlur().
This is the error message using spyder.

```
Fatal Python error: Aborted

Main thread:
Current thread 0x00007fbab679b740 (most recent call first):
  File "/home/mgouka/miniconda3/envs/bx_gui/lib/python3.9/site-packages/PIL/ImageFilter.py", line 189 in filter
  File "/home/mgouka/miniconda3/envs/bx_gui/lib/python3.9/site-packages/PIL/Image.py", line 1305 in filter
  File "/tmp/ipykernel_28079/2108891280.py", line 1 in <module>


Restarting kernel...
```

And using python in the standard linux terminal it says:

```
Segmentation fault (core dumped)
```

The code below produces the problem.

```python
import numpy as np
from PIL import Image, ImageFilter

img = Image.fromarray(np.ones([100, 100, 3], dtype='uint8'))
img = img.filter(ImageFilter.BoxBlur(-2))
```

**Comment by Yay295** [comment]
For me it crashes when the filter is used, not when it's created. I haven't looked into it any further than that.

**Comment by hugovk** [comment]
Yep, it doesn't happen for:

```python
fil = ImageFilter.BoxBlur(-2))
```

But does for:

```python
fil = ImageFilter.BoxBlur(-2)
img = img.filter(fil)  # <--- here
```

Here's a suggestion: raise a _ValueError_ when _creating_ a filter with negative radius. We could do so when _using_ the filter, but why not handle it earlier?

Please see PR https://github.com/python-pillow/Pillow/pull/6874.
