### ISSUE TITLE
Technically invalid test images

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#6878]
"illu10_no_preview.eps", "illu10_preview.eps", "illuCS6_no_preview.eps", and "illuCS6_preview.eps" all contain one line that is longer than 255 characters, which is the maximum limit according to [the specification](https://web.archive.org/web/20220120164601/https://www.adobe.com/content/dam/acom/en/devnet/actionscript/articles/5002.EPSF_Spec.pdf).

Page 13:
> EPS files must not have lines of ASCII text that exceed 255 characters, excluding line-termination characters.

Page 25:
> The hexadecimal lines must never exceed 255 bytes in length. In cases where the preview is very wide, the lines must be broken. The line breaks can be made at any even number of hex digits, because the dimensions of the finished preview are established by the *width*, *height*, and *depth* values.

The four image files appear to be nearly the same, and have the same long line:

https://github.com/python-pillow/Pillow/blob/50f7888e3a8e583261f9a6c43d2b7fd0ea09cd10/Tests/images/illu10_no_preview.eps#L7995

It looks like `&#xA;`, an HTML encoded line feed, was added to this file instead of an actual line feed. Replacing `&#xA;` with `\n` allowed the files to load in my branch (I'm testing some changes to the EPS plugin).

The two "*_preview.eps" files also have a line that is longer than 255 characters at the end, but it looks like binary data so I think that's valid.

Currently the code only checks the line length for lines in the header, and lines after the header that start with a `%`. Since these test files came from [the wild](https://github.com/python-pillow/Pillow/issues/1104#issuecomment-73365470), we probably want to allow files like this, but I thought I'd at least document it.

**Comment by Yay295** [comment]
"timeout-d675703545fee17acab56e5fec644c19979175de.eps" is also invalid. It has a valid binary header, but it doesn't contain either of the required header comments: `%!PS-Adobe` and `%%BoundingBox`. This is fine, since the test it's used in isn't supposed to pass, but I think it should actually be raising an `OSError` instead of a `Image.UnidentifiedImageError`.

**Comment by radarhere** [comment]
It is [raising a SyntaxError](https://github.com/python-pillow/Pillow/blob/50f7888e3a8e583261f9a6c43d2b7fd0ea09cd10/src/PIL/EpsImagePlugin.py#L234) because the first line is longer than 255 characters. That error is [caught](https://github.com/python-pillow/Pillow/blob/50f7888e3a8e583261f9a6c43d2b7fd0ea09cd10/src/PIL/Image.py#L3257), leading to the UnidentifiedImageError.

https://www.loc.gov/preservation/digital/formats/fdd/fdd000246.shtml
> EPS files use lines of 255 or fewer ASCII characters.

**Comment by Yay295** [comment]
> It is [raising a SyntaxError](https://github.com/python-pillow/Pillow/blob/50f7888e3a8e583261f9a6c43d2b7fd0ea09cd10/src/PIL/EpsImagePlugin.py#L234) because the first line is longer than 255 characters.

I'm not sure it should be doing that, though. The file has a valid binary header with an offset of 32,820. That offset puts the start at column 594 of line 41 (using ANSI encoding), which appears to be binary data. So it could either raise an error because there isn't any header comments at that position, or it could assume there is no header and raise an error because the required comments are missing.

Perhaps it's different with a different encoding?

**Comment by radarhere** [comment]
Are you saying that an UnidentifiedImageError shouldn't be raised because we actually do know what the image format is? You may want to have a look at #1687

**Comment by Yay295** [comment]
I'm saying the error should be due to the missing header comments, not because the line is too long, because the line appears to be binary data, not ASCII, so it doesn't have a length limit.

**Comment by radarhere** [comment]
Looking at the actual specification, I see

https://web.archive.org/web/20170818010030/http://wwwimages.adobe.com/content/dam/Adobe/en/devnet/postscript/pdfs/5002.EPSF_Spec.pdf
> EPS files must not have lines of ASCII text that exceed 255 characters,
excluding line-termination characters.

> binary data is allowed

So perhaps leads to your conclusion that binary data can be longer than 255 characters.

In trying to find out what should come after the offset though, I'm having a hard time finding more information about this.
https://github.com/python-pillow/Pillow/blob/c2e2da4a2245dd42131fb47e19aa0ff06ee088cb/src/PIL/EpsImagePlugin.py#L326-L333
Do you happen to know where any documentation about that is?

**Comment by Yay295** [comment]
No, I didn't find anything other than that PDF.

**Comment by radarhere** [comment]
The comments regarding line length and required header comments in timeout-d675703545fee17acab56e5fec644c19979175de.eps and  have been resolved by #6879. The file now raises "SyntaxError: EPS header missing "%!PS-Adobe" comment".
