### ISSUE TITLE
Image.register_open called multiple times

### ISSUE THREAD

**Issue by bigcat88** [python-pillow/Pillow#6916]
### What did you do?

Calling `Image.register_open` multiply times should not lead to growth of `Image.ID` list.

### What did you expect to happen?

After second call to `Image.register_open` `Image.ID` should not contain similar values.

### What are your OS, Python and Pillow versions?

* OS: not OS dependent
* Python: not python version dependent
* Pillow: 9.4.0

Maybe it is invalid usage, I know that applications should not call `Image.register_open`, but this very small problem present.

```python3
def register_open(id, factory, accept=None):
    """
    Register an image file plugin.  This function should not be used
    in application code.

    :param id: An image format identifier.
    :param factory: An image file factory method.
    :param accept: An optional function that can be used to quickly
       reject images having another format.
    """
    id = id.upper()
    ID.append(id)  # growth of the list here.
    OPEN[id] = factory, accept
```

Image.ID used only in a few places:

1. PIL.Image.open
```python3
    if formats is None:
        formats = ID
```
2. PIL.FitsStubImagePlugin
```python3
    # Override FitsImagePlugin with this handler
    # for backwards compatibility
    try:
        Image.ID.remove(FITSStubImageFile.format)
    except ValueError:
        pass

    Image.register_open(
        FITSStubImageFile.format, FITSStubImageFile, FitsImagePlugin._accept
    )
```
3. PIL.features
```python3
        for i in sorted(Image.ID):
            line = f"{i}"
            if i in Image.MIME:
                line = f"{line} {Image.MIME[i]}"
            print(line, file=out)
```

Probably in 1 and 3 places this can be replaced with `OPEN.keys()` that contain the same values, if I understand code correct, and in place with number 2 just remove `Image.ID.remove` lines.
These changes should not affect performance.

**Comment by radarhere** [comment]
To be clear - you didn't actually have code that you'd written that you found calling `Image.register_open` multiple times, right? This is just a theoretical concern?

I'm reluctant to make `ID` redundant by replacing it with `OPEN.keys()`, since `ID` is part of the public API.

I've created PR #6917 to simply not append existing ids to `ID`.

**Comment by bigcat88** [comment]
> To be clear - you didn't actually have code that you'd written that you found calling `Image.register_open` multiple times, right? This is just a theoretical concern?

Yes, it is more theoretical, you are right.

> I've created PR #6917 to simply not append existing ids to `ID`.
Thanks.
