### ISSUE TITLE
Can support for the `memoryview` type be added as input to _decode (decode.c)?

### ISSUE THREAD

**Issue by bigcat88** [python-pillow/Pillow#6933]
Data created with help of `PyMemoryView_FromMemory` function.

Overhead for big images when converting `memoryview` to bytes is noticeable.

Code located here:
https://github.com/python-pillow/Pillow/blob/7e3bed6834e639cd0f5a410abfd8224d4e5725c5/src/decode.c#L124

Is this possible to easy add support for such feature or not?

**Comment by radarhere** [comment]
If I understand correctly, you're asking for a modification to the C API? This has nothing to do with the Python interface of Pillow?

https://github.com/python-pillow/Pillow/issues/4532#issuecomment-618255798
> Pillow makes a commitment to stable public interfaces, which are defined at the Python layer. The C interfaces are explicitly internal, and no effort is made to keep them stable even between minor releases, and no support or warning is given when they change. (IIRC, there are/were people using the internal interfaces, but they've always been explicitly on their own with that)

**Comment by bigcat88** [comment]
I'm asking for `Image.frombytes` method to accept `memoryview` type for `data` in addition to bytes, when `decoder_name="raw"`.

https://github.com/python-pillow/Pillow/blob/7e3bed6834e639cd0f5a410abfd8224d4e5725c5/src/PIL/Image.py#L806-L832

It should not be very hard, I can make a PR for this if you want.

**Comment by radarhere** [comment]
Feel free to do so.

**Comment by radarhere** [comment]
#6937 or #6974 have been created as possible resolutions to this.

**Comment by mara004** [comment]
Thanks for this improvement! Applies to `frombuffer()`, too.
It's shipped since v9.5, right?

**Comment by hugovk** [comment]
Yes, https://github.com/python-pillow/Pillow/pull/6974 was released in https://github.com/python-pillow/Pillow/releases/tag/9.5.0.
