### ISSUE TITLE
How to handle textsize deprecation warning

### ISSUE THREAD

**Issue by ArthurPains** [python-pillow/Pillow#6938]
I'm getting textsize is deprecated, however when I use textbbox or textlength instead, they don't do the same.

After a lot of research, I finally managed to figure out how to recalculate the font size of a text if it doesn't fit in a specific area. But the only way I could do that was using "textsize". I've already tried using textbbox or textlength and I couldn't use them in my function at all. With that, every time the text size needs to decrease, this message appears to me:

```
DeprecationWarning: textsize is deprecated and will be removed in Pillow 10 (2023-07-01). Use textbbox or textlength instead.
  textwidth, textheight = draw.textsize(text, font)
```

I would like to know how can I deal with this? Because every time a print appears with this message, it bothers me and also makes it difficult for me to find other errors.

This is my function:

```python
def draw_text_with_size_adjustment(text, region):
    font_size = 40
    font = ImageFont.truetype("Font/OpenSans-Bold.ttf", font_size)
    while True:
        textwidth, textheight = draw.textsize(text, font)
        if textwidth <= region[2] - region[0] and textheight <= region[3] - region[1]:
            break

        font_size -= 1
        font = ImageFont.truetype("Font/OpenSans-Bold.ttf", font_size)

    x = region[0] + (region[2] - region[0] - textwidth) / 2
    y = region[1] + (region[3] - region[1] - textheight) / 2

    draw.text((x, y), text, font=font, fill=(0, 0, 0))

    img.save("text_example.png")
```

**Comment by Yay295** [comment]
Does `draw.textbbox((0,0), text, font)` work?

**Comment by nulano** [comment]
> I'm getting textsize is deprecated, however when I use textbbox or textlength instead, they don't do the same.

Yes, the new functions do not return the same results - the old function was broken and returning incorrect values. But I'm curious, you haven't mentioned what exactly is your problem with the new functions?

> x = region[0] + (region[2] - region[0] - textwidth) / 2
> y = region[1] + (region[3] - region[1] - textheight) / 2

This is not a reliable way to center text (irrespective of how you obtain text width and height), it is preferred to use `anchor="mm"` instead.

---

Whether you use `textbbox` or `textlength` depends on your needs - use `textlength` if you wish to e.g. justify text in a paragraph, or `textbbox` if you wish to fit text in a box (considering both extra width beyond the advance values of the font, as well as vertical height). 

Does either of these examples help?

Using `font.getlength` (equivalent to `draw.textlength`):
```python
from PIL import Image, ImageDraw, ImageFont

w, h = 300, 100
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

im = Image.new("RGB", (w, h), "white")
draw = ImageDraw.Draw(im)

font_size = 40
font = ImageFont.truetype(r"C:\Users\Nulano\AppData\Local\Microsoft\Windows\Fonts\OpenSans-Bold.ttf", font_size)

while True:
  if font.getlength(text) < w:
    break
  font_size -= 1
  font = font.font_variant(size=font_size)

draw.text((w / 2, h / 2), text, font=font, fill="black", anchor="mm")
im.show()
```
![6938-textlength](https://user-images.githubusercontent.com/3819630/218188456-e30dfd9c-a449-4f5a-a749-e8cc4beeb3c8.png)

Using `font.textbbox`:
```python
from PIL import Image, ImageDraw, ImageFont

w, h = 300, 100
region = (50, 40, 200, 90)
text = "Lorem ipsum dolor sit amet, consectetur adipiscing elit."

im = Image.new("RGB", (w, h), "white")
draw = ImageDraw.Draw(im)
draw.rectangle(region, outline="black")

font_size = 40
font = ImageFont.truetype(r"C:\Users\Nulano\AppData\Local\Microsoft\Windows\Fonts\OpenSans-Bold.ttf", font_size)

x = int((region[2] - region[0]) / 2) + region[0]
y = int((region[3] - region[1]) / 2) + region[1]
while font_size > 1:
  bbox = draw.textbbox((x, y), text, font=font, anchor="mm")
  if bbox[0] > region[0] and bbox[1] > region[1] and bbox[2] < region[2] and bbox[3] < region[3]:
    break
  font_size -= 1
  font = font.font_variant(size=font_size)

draw.text((x, y), text, font=font, fill="black", anchor="mm")
im.save(r"E:\6938-textbbox.png")
im.show()
```
![6938-textbbox](https://user-images.githubusercontent.com/3819630/218188473-c4774a81-0fe0-428a-ac22-5092ee8f97ce.png)

![6938-textbbox2](https://user-images.githubusercontent.com/3819630/218188904-259df57e-6bd3-487f-adc8-bd84dfbb537c.png)

---

If you insist on using `font.getsize` / `draw.textsize`, that function is equivalent to

```python
def getsize(...):
  # this function has confusing behaviour and should not be used
  left, top, right, bottom = font.getbbox(...)
  width = right - left  # this value can be confusing
  height = bottom       # this value is clearly wrong
  return width, height
```

but as you can see from that code, that function most likely does not return the values you expect.

**Comment by radarhere** [comment]
@ArthurPains did that answer your question?

**Comment by ArthurPains** [comment]
@nulano Sorry for the delay, I was traveling. It worked, thank you very much!! The code has also become smaller and more organized. Thank you again.
