### ISSUE TITLE
Python 3.12: Fix building Pillow on Windows

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#6942]
For https://github.com/python-pillow/Pillow/issues/6941

Pillow doesn't build for Windows on 3.12:

```diff
diff --git a/.github/workflows/test-windows.yml b/.github/workflows/test-windows.yml
index e938e999d..306e34ca9 100644
--- a/.github/workflows/test-windows.yml
+++ b/.github/workflows/test-windows.yml
@@ -15,7 +15,7 @@ jobs:
     strategy:
       fail-fast: false
       matrix:
-        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11"]
+        python-version: ["3.7", "3.8", "3.9", "3.10", "3.11", "3.12-dev"]
         architecture: ["x86", "x64"]
         include:
           # PyPy 7.3.4+ only ships 64-bit binaries for Windows
```

[Python 3.12-dev x86](https://github.com/hugovk/Pillow/actions/runs/4141811740/jobs/7161777842#logs) fails:

```
   Creating library build\temp.win32-cpython-312\Release\src\_imaging.cp312-win32.lib and object build\temp.win32-cpython-312\Release\src\_imaging.cp312-win32.exp
display.obj : error LNK2001: unresolved external symbol _PyUnicode_AS_UNICODE
build\lib.win32-cpython-312\PIL\_imaging.cp312-win32.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x86\\link.exe' failed with exit code 1120
```

[Python 3.12-dev x64](https://github.com/hugovk/Pillow/actions/runs/4141811740/jobs/7161777920#logs) similarly fails:

```
   Creating library build\temp.win-amd64-cpython-312\Release\src\_imaging.cp312-win_amd64.lib and object build\temp.win-amd64-cpython-312\Release\src\_imaging.cp312-win_amd64.exp
display.obj : error LNK2001: unresolved external symbol PyUnicode_AS_UNICODE
build\lib.win-amd64-cpython-312\PIL\_imaging.cp312-win_amd64.pyd : fatal error LNK1120: 1 unresolved externals
error: command 'C:\\Program Files\\Microsoft Visual Studio\\2022\\Enterprise\\VC\\Tools\\MSVC\\14.34.31933\\bin\\HostX86\\x64\\link.exe' failed with exit code 1120
```

This is because `PyUnicode_AS_UNICODE()` was deprecated in Python 3.3 and removed in 3.12:

* https://docs.python.org/3.12/whatsnew/3.12.html?highlight=pyunicode_as_unicode#id5
* [PEP 623](https://peps.python.org/pep-0623/)
* https://docs.python.org/3/c-api/unicode.html?highlight=pyunicode_as_unicode#c.PyUnicode_AS_UNICODE

> _Changed in version 3.3:_ This function is now inefficient – because in many cases the [`Py_UNICODE`](https://docs.python.org/3/c-api/unicode.html?highlight=pyunicode_as_unicode#c.Py_UNICODE) representation does not exist and needs to be created – and can fail (return `NULL` with an exception set). Try to port the code to use the new `PyUnicode_nBYTE_DATA()` macros or use [`PyUnicode_WRITE()`](https://docs.python.org/3/c-api/unicode.html?highlight=pyunicode_as_unicode#c.PyUnicode_WRITE) or [`PyUnicode_READ()`](https://docs.python.org/3/c-api/unicode.html?highlight=pyunicode_as_unicode#c.PyUnicode_READ).
>
> _Deprecated since version 3.3, will be removed in version 3.12:_ Part of the old-style Unicode API, please migrate to using the _PyUnicode_nBYTE_DATA()_ family of macros.

**Comment by nulano** [comment]
The macro is used in `list_windows_callback`, which is referenced from `PyImaging_ListWindowsWin32`, i.e. `Image.core.listwindows`. That is an internal function that I can't see any references to, so I think it should be safe to just remove it.

https://github.com/python-pillow/Pillow/blob/bc1a96a85fc83bdde1173b5146bac136efeffb8f/src/display.c#L438
https://github.com/python-pillow/Pillow/blob/bc1a96a85fc83bdde1173b5146bac136efeffb8f/src/display.c#L487
https://github.com/python-pillow/Pillow/blob/bc1a96a85fc83bdde1173b5146bac136efeffb8f/src/_imaging.c#L4072

I think this was intended to be used with `ImageGrab.grab(bbox=Image.core.listwindows[...][...])` (i.e. what https://github.com/python-pillow/Pillow/issues/4415#issuecomment-584610994 asked for), but it would not help with that issue as applications aren't always visible on the desktop.

**Comment by hugovk** [comment]
Thanks, I've updated https://github.com/python-pillow/Pillow/pull/6943.
