### ISSUE TITLE
ModuleNotFoundError: No module named 'PIL' on M2 Mac using VSCode

### ISSUE THREAD

**Issue by joshuashumshere** [python-pillow/Pillow#6945]
### What did you do?

I am using Pillow with tkinter on VSCode.

### What did you expect to happen?

I expected the Pillow module to load and then be usable in the program.

### What actually happened?

I got an error saying ModuleNotFoundError: No module named 'PIL'

### What are your OS, Python and Pillow versions?

* OS:  Mac, M2 (2022) Ventura 13.0 (22A380)
* Python: 
```console
% python3 --version
Python 3.10.10
% python --version
Python 3.9.6
```
* Pillow: 
Name: Pillow
Version: 9.4.0
Summary: Python Imaging Library (Fork)
Home-page: https://python-pillow.org
Author: Alex Clark (PIL Fork Author)
Author-email: aclark@python-pillow.org
License: HPND
Location: /opt/homebrew/lib/python3.10/site-packages
Requires: 
Required-by: Pillow-PIL

```python
from tkinter import *
from PIL import ImageTk, Image

root = Tk()
root.title("Icons & Images")

button_quit = Button(root, text="Exit Program", command=root.quit) #quit the app
button_quit.pack()

root.mainloop()
```

**Comment by hugovk** [comment]
Please post the full traceback.

How did you install Pillow? How do you run your script?


> ```console
> % python3 --version
> Python 3.10.10
> % python --version
> Python 3.9.6
> ```

You have two different interpreters here, so please make sure you also install Pillow using the same interpreter you run your code with.

For example:

* if you run with `python myscript.py`, install with `python -m pip install pillow`.
* if you run with `python3 myscript.py`, install with `python3 -m pip install pillow`.

See https://snarky.ca/why-you-should-use-python-m-pip/

**Comment by joshuashumshere** [comment]
The `python3 -m pip install pillow` did not work. 

So I uninstalled python and all its dependencies. Reinstalled python using Brew. Then i installed `pillow` using Brew and it finally worked.
