### ISSUE TITLE
Add a corners parameter for `ImageDraw.rounded_rectangle`?

### ISSUE THREAD

**Issue by ChrisMGeo** [python-pillow/Pillow#6953]
### What's your feature request?
To add an optional bool tuple parameter (`corners=(True, True, True, True)`), or 4 optional bool parameters (`top_left=True, top_right=True,  ...`) describing which corners of a rectangle should be rounded for `ImageDraw.rounded_rectangle` and possibly similar functions.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.10.10
* Pillow: latest

## Example of feature request
```python
draw.rounded_rectangle((x0, y0, x1, y1), radius=4, fill = white, corners=(True, False, True, False)) # TL TR BL BR
draw.rounded_rectangle((x0, y0, x1, y1), radius=4, fill=white, top_right=False, bottom_right=False)
```

**Comment by radarhere** [comment]
I've created PR #6954 to resolve this, using the tuple method.
