### ISSUE TITLE
Any performant way to determine if an image is closed?

### ISSUE THREAD

**Issue by AnonymouX47** [python-pillow/Pillow#6982]
The only way I'm aware of to determine if an image instance has been closed/finalized is to try to [load](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.load) the image and check if an exception is raised or not.

This results in the image being loaded if it hasn't been closed nor loaded already, which isn't good in terms of performance. On the other hand, exceptions being raised and handled isn't so performant in python.

I'm developing a library which defines a class that accepts PIL images upon instantiation and would like to check if the image has been closed at initialization of instances. The only other alternative is to accept the image as given and allow an exception raised from within Pillow to be propagated later on when the PIL image is to be used but I do not like this.

I suggest that a property be added to `PIL.Image.Image` to determine if an image has been closed without the possible cost of loading the image or raising and handling an exception. A boolean attribute set at initialization and updated upon closing the image should be enough to get this done.

I know this might not be of much importance but it would be good to at least have a Look-Before-You-Leap alternative.

Thanks.

**Comment by radarhere** [comment]
When you mention an exception being raised, are you talking about this?
https://github.com/python-pillow/Pillow/blob/6ca7bcceee24400796ccbfa39182ecbe0924830a/src/PIL/ImageFile.py#L155-L160

In which case, you could just check if `im.tile is None` directly, without calling `load()`.

**Comment by AnonymouX47** [comment]
No, I'm taking about the exception raised when trying to load a closed image. See:

https://github.com/python-pillow/Pillow/blob/6ca7bcceee24400796ccbfa39182ecbe0924830a/src/PIL/Image.py#L587

https://github.com/python-pillow/Pillow/blob/6ca7bcceee24400796ccbfa39182ecbe0924830a/src/PIL/Image.py#L597-L600

https://github.com/python-pillow/Pillow/blob/6ca7bcceee24400796ccbfa39182ecbe0924830a/src/PIL/_util.py#L18-L19

**Comment by radarhere** [comment]
So your current code is
```python
from PIL import Image

def check(im):
	try:
		im.load()
	except ValueError:
		print("im was closed")

im = Image.open("Tests/images/hopper.png")
im.close()
check(im)
```

An immediate alternative could be to
```python
from PIL import Image
from PIL._util import DeferredError

def check(im):
	if isinstance(im.im, DeferredError):
		print("im was closed")

im = Image.open("Tests/images/hopper.png")
im.close()
check(im)
```

**Comment by AnonymouX47** [comment]
> So your current code is

Well... I don't even use that due to the possible cost of loading the image as I mentioned earlier. Currently, I do not check if the image is closed at all because I've found no alternative.

> An immediate alternative could be to
> ...

The problem with this is:

1. It uses private and undocumented API. There's simply no way anyone could know this without reading through the source code.
2. How do I know this will still be valid even in the next release of Pillow?

Like I mentioned earlier, it's for a [library](https://github.com/AnonymouX47/term-image) that a few (potentially more in the future) projects currently use as a dependency.

**Comment by radarhere** [comment]
The performance cost of checking via `load()` is negated if you were going to be loading the image anyway afterwards. But what you're saying is that you want to check if an image has been loaded or not, and if not, you... don't want to load it? You only want to perform operations on the image if it is already loaded, and if not, you don't want to do anything with it? Could you explain that a bit more?

**Comment by AnonymouX47** [comment]
> The performance cost of checking via `load()` is negated if you were going to be loading the image anyway afterwards.

The image **may** be loaded **afterwards** and even if it is, not at the point of **initializing** an object of the concerned class (that accepts a PIL image).

Multiple image instances could be created/initialized at a once at certain point but not rendered (this is when the image needs to be loaded) until [much] later (which is very common use case) and some may not even be rendered eventually.

> But what you're saying is that you want to check if an image has been loaded or not

No at all. There seems to be some misunderstanding here. I believe I've always clearly stated "if the image is **closed**" all the way from the title and I've checked, I don't think I mixed my words at any point.

All I'm asking for is a means to determine if an image instance has been **closed** (i.e `Image.close()` has been called) without calling `Image.load()`.

Thanks.

**Comment by radarhere** [comment]
You're right, I was confused in my last comment.

I've created PR #6984

**Comment by AnonymouX47** [comment]
I see. Thank you

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/pull/6984#pullrequestreview-1363018952

> No particular opposition to this, but wondering how much of a special case this addressing, and how common this sort of thing is in general.

**Comment by AnonymouX47** [comment]
Okay, thanks for the consideration and effort.

I guess I'll stick to not checking if the image is closed and just allow the exception raised when an image is closed to be propagated.

**Comment by isaac-bender** [comment]
This was a good change, you shouldn't have rejected it. Why do you hate performance?

**Comment by radarhere** [comment]
There was a suggestion that this was an uncommon scenario. If you think it is more common, feel free to explain why.

At present, you should be able to use `isinstance(im.im, DeferredError)` to check if an image is closed, it is just a less-optimal API.
