### ISSUE TITLE
Every font with variants throws an OSError on *variation* functions

### ISSUE THREAD

**Issue by vikingvynotking** [python-pillow/Pillow#6995]
### What did you do?

Tried to set a font variation, see code below.

### What did you expect to happen?

The correct variant would be set on the font.

### What actually happened?

OSError: invalid argument

### What are your OS, Python and Pillow versions?

* OS: MacOS 12.1 Monterey
* Python: 3.9.10
* Pillow: 9.1.0

```python
font = ImageFont.truetype('Futura', 20) # or Didot, or any other font with variants not in separate files
font.set_variation_by_name('Medium') # or Condensed, etc
```

Note that this happens for every single font with variations that exist in the same file. A font with different files (e.g. Arial-Bold.ttf and Arial.ttf) works as expected, but where I have Futura.ttc (all variants in the same file) the error occurs. Other applications are able to work with such fonts just fine so I am pretty certain the issue is within PIL/ _imagingft.

**Comment by vikingvynotking** [comment]
For reference, here's imagemagick correctly picking up Futura's variants:

```
$ magick -list font|ack Futura
Fontconfig warning: "/usr/local/etc/fonts/fonts.conf", line 86: unknown element "blank"
  Font: Futura-Bold
    family: Futura
    glyphs: /System/Library/Fonts/Supplemental/Futura.ttc
  Font: Futura-Condensed-ExtraBold
    family: Futura
    glyphs: /System/Library/Fonts/Supplemental/Futura.ttc
  Font: Futura-Condensed-Medium
    family: Futura
    glyphs: /System/Library/Fonts/Supplemental/Futura.ttc
  Font: Futura-Medium
    family: Futura
    glyphs: /System/Library/Fonts/Supplemental/Futura.ttc
  Font: Futura-Medium-Italic
    family: Futura
    glyphs: /System/Library/Fonts/Supplemental/Futura.ttc
```

**Comment by radarhere** [comment]
Hi. This error doesn't happen for the font with variations that we have included in our test suite.

```python
from PIL import ImageFont
font = ImageFont.truetype("Tests/fonts/AdobeVFPrototype.ttf")
font.set_variation_by_name("Bold")
```

The difference between this font and Futura.ttc is that Futura.ttc is a [collection](https://github.com/foliojs/fontkit/blob/master/README.md#font-collection-objects), and that is different from [variation fonts](https://github.com/foliojs/fontkit/blob/master/README.md#variation-fonts).

You can instead select different fonts in the collection using `index`.

```python
from PIL import ImageFont
font = ImageFont.truetype("Futura.ttc")
print(font.getname())  # ('Futura', 'Medium')
font = ImageFont.truetype("Futura.ttc", index=2)
print(font.getname())  # ('Futura', 'Bold')
```

**Comment by vikingvynotking** [comment]
Thanks for the response - this makes sense. I haven't had a chance to test it yet but will let you know the results when I do so.
