### ISSUE TITLE
Tiff image JPEG compression up to 3x original image disk size

### ISSUE THREAD

**Issue by GiovanniNova** [python-pillow/Pillow#7001]
I have been using this library for a while and although it works extremely well and is much faster than say, OpenCV, I noticed that it has some issues with compression.

When converting an image from JPEG to TIF they can end up with over 3x their original disk size, this woudn't be an issue for 1 or 2 images but we have over 4.000 images.

Sample code:

```python
from PIL import Image

with Image.open('original.jpg') as image:
	image.save('pillow - 50.jpg', optimize=True, compression='jpeg', quality=50)
	image.save('pillow - 50.tif', optimize=True, compression='jpeg', quality=50)
	
	image.save('pillow - 75.jpg', optimize=True, compression='jpeg', quality=75)	
	image.save('pillow - 75.tif', optimize=True, compression='jpeg', quality=75)
```

Original 89%: 3.352 kb
Photoshop 9/12 (75%): 3.417 kb
Pillow 50% .JPG: 1.175 kb
Pillow 50% .TIF: 3.828 kb
Pillow 75% .JPG: 2.320 kb
Pillow 75% .TIF: 7.206 kb

[original.zip](https://github.com/python-pillow/Pillow/files/10941882/original.zip)
[result.zip](https://github.com/python-pillow/Pillow/files/10941885/result.zip)

- Windows 10 x64
- Python 3.9.6 
- Pillow 9.4.0
- LibTiff 3.8.2-1 (features.check('libtiff') returns True)

**Comment by radarhere** [comment]
Setting aside `quality` and `optimize`, I tried comparing the results with ImageMagick's `convert` command.

`convert original.jpg -compress JPEG magick.tif` gave 7,203kb.

The Pillow code
```python
from PIL import Image
with Image.open('original.jpg') as image:
	image.save('pillow.tif', compression='jpeg')
```
gave 7,205kb.

So we're very similar to ImageMagick's output.

Also, just as an aside, `compression` is not a keyword argument used when saving JPEG images - https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#jpeg-saving

**Comment by GiovanniNova** [comment]
> Also, just as an aside, `compression` is not a keyword argument used when saving JPEG images - 

It was a small mistake since copy + pasted the TIF save lines and forgot to remove the compression argument

> So we're very similar to ImageMagick's output.

So, is this a won't fix kind of situation? Is Pillow a wrapper around ImageMagick? If so, should I bring this issue to ImageMagick's repo instead?

**Comment by cgohlke** [comment]
The size difference likely comes from Photoshop compressing JPEG in YCBCR colorspace inside TIFF, while Pillow and ImageMagick use RGB colorspace. Try `convert original.jpg -compress JPEG -colorspace YCbCr magick.tif`

**Comment by GiovanniNova** [comment]
Confirmed working by using Image.convert('YCbCr'), which produces a TIF file with a very small difference of 400KB from their JPEG counterparts, thank you!

**Comment by Yay295** [comment]
I think it would also technically be possible to embed a JPEG into a TIFF without recompressing, but I think that would be out of scope for Pillow.

**Comment by Yay295** [comment]
I found an open issue on the libtiff GitLab for this same situation: https://gitlab.com/libtiff/libtiff/-/issues/106

**Comment by radarhere** [comment]
> Is Pillow a wrapper around ImageMagick?

Not at all! I was just saying that two independent tools have similar results, so this is likely not as simple as "Pillow has a bug".

> Confirmed working by using Image.convert('YCbCr'), which produces a TIF file with a very small difference of 400KB from their JPEG counterparts, thank you!

Is this issue resolved then?

**Comment by Yay295** [comment]
I wrote a function that can directly embed a JPEG file into a TIFF file: #7006

Using your `original.jpg` I converted it to TIFF with only 204 bytes of overhead.

```python
from jpeg_to_tiff import jpeg_to_tiff
with open('embedded.tif', 'wb') as tiff_file:
    tiff_data = jpeg_to_tiff('original.jpg')
    tiff_file.write(tiff_data)
```

**Comment by cgohlke** [comment]
> I wrote a function that can directly embed a JPEG file into a TIFF file:

Nice. The YCbCrSubSampling tag needs to be specified for YCBCR images unless they are YUV420.

**Comment by GiovanniNova** [comment]
> Is this issue resolved then?

Thank you, it has been solved. 

The discussion about directly embedding the JPEG data feels important but perhaps opening another issue would to be more fitting.
