### ISSUE TITLE
getbbox incorrect when string contains new line character

### ISSUE THREAD

**Issue by vanviethieuanh** [python-pillow/Pillow#7013]
### What did you do?

So I use the `getbbox` to calculate the width and height of my string with a specific font. The string includes the `\n` character and it split the line into 2.

### What did you expect to happen?

 The string renders well and has a width of about 7xx pixels which is what I want. And I expect the `getbbox` function returns the same value.

### What actually happened?

However, the result I got from `getbbox` is 1555 pixels which might be the width of no break line text.

### What are your OS, Python, and Pillow versions?

* OS: Windows 10 Enterprise
* Python: Python 3.10.10
* Pillow: 9.4.0

```python
text = "Age is an issue of mind over matter.\nIf you don't mind, it doesn't matter."
_, _, text_width, text_height = FONT.getbbox(text)
# text_width = 1555
```

![image](https://user-images.githubusercontent.com/29355962/224971601-4429a5e4-78f3-4734-81c9-afcdd1ec483a.png)
The size of the image is 1080*1080 so there is no way that the text width is 1555.

Thank you!

**Comment by nulano** [comment]
Line breaking is handled only in `ImageDraw` and not in `ImageFont`; you should use `ImageDraw.multiline_textbbox()`. The thread around https://github.com/python-pillow/Pillow/issues/5816#issuecomment-962864866 might interest you.

**Comment by radarhere** [comment]
@vanviethieuanh did that answer your question?

**Comment by vanviethieuanh** [comment]
@radarhere yes, it does! Thanks (。・ω・。)

**Comment by mofear85** [comment]
Just faced this problem. Took a while to narrow it down. A hint in the documentation would be greatly appreciated (I assume). Either way thx for this great piece of software.

**Comment by radarhere** [comment]
I'd be happy to add a note at the very top of https://pillow.readthedocs.io/en/stable/reference/ImageFont.html, but I wouldn't want to add a note to [`getbbox()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.ImageFont.getbbox) specifically - there's a number of ImageFont methods, and it would be very repetitive to add it to each one.

Do you think it would be noticed at the top of the page?

**Comment by mofear85** [comment]
can't it be added to the docstring of getbbox() itself?

btw, isn't it possible to make the function properly determine the size even if the next includes newlines? The result is font dependent, but this should be easy/possible when the function is called as a method, ie from a specific font instance. Currently, even if done so, it ignores newlines.

**Comment by radarhere** [comment]
> can't it be added to the docstring of getbbox() itself?

If we add it to [`getbbox()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.ImageFont.getbbox), then why not also
- [`getlength()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.ImageFont.getlength)
- [`getmask()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.ImageFont.getmask)
- [`FreeTypeFont.getbbox()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.getbbox)
- [`FreeTypeFont.getlength()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.getlength)
- [`FreeTypeFont.getmask()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.getmask)
- [`FreeTypeFont.getmask2()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.getmask2)
- [`TransposedFont.getbbox()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.TransposedFont.getlength)
- [`TransposedFont.getlength()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.TransposedFont.getlength)
- [`TransposedFont.getmask()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.TransposedFont.getmask)

That would seem very repetitive to me.

> btw, isn't it possible to make the function properly determine the size even if the next includes newlines? The result is font dependent, but this should be easy/possible when the function is called as a method, ie from a specific font instance. Currently, even if done so, it ignores newlines.

We could, yes. The story of multiline text began in #582. My guess would be that measuring the size of multiline text was considered valuable in the context of drawing text, but there was a weaker need for it by itself.

If you'd like that feature, please open a new issue explaining why you think it would be useful.

**Comment by mofear85** [comment]
just an afterthought:

sometimes one wants to know the size/bounds of a character or font even without or before an image exists, for example to know how to size the image so that it fits the entire text.

> If we add it to [getbbox()](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.ImageFont.getbbox), then why not also ....

tbh, there isn't any need to copy/paste the text. the ImageDraw versions can inherit bzw use the methods from the font or the functions can be factored out.

**Comment by radarhere** [comment]
> the ImageDraw versions can inherit bzw use the methods from the font or the functions can be factored out.

I don't really know what is meant by this, but you are free to create a pull request to demonstrate if you would like.

**Comment by radarhere** [comment]
> sometimes one wants to know the size/bounds of a character or font even without or before an image exists, for example to know how to size the image so that it fits the entire text.

Investigating this, I think part of the problem is that the mode of an image actually does affect text dimensions.
```python
from PIL import Image, ImageDraw, ImageFont
for mode in ("1", "L", "RGB"):
  im = Image.new(mode, (1, 1))
  d = ImageDraw.Draw(im)
  print(mode, d.textlength("This is a test"))
```
gives
```
1 62.0
L 54.0
RGB 54.0
```

This would be because of
https://github.com/python-pillow/Pillow/blob/d56032047d11b17428e5ad01692b06fc8b1dfcdf/src/_imagingft.c#L544
https://github.com/python-pillow/Pillow/blob/d56032047d11b17428e5ad01692b06fc8b1dfcdf/src/_imagingft.c#L451-L453

I consider that to be a conceptual overlap, meaning that you can't purely consider text dimensions irrespective of the image it will go into.

**Comment by radarhere** [comment]
I've created #9098 in case you had any thoughts on that. It would allow for
```python
from PIL import ImageText
text = ImageText.ImageText(text, font, mode, spacing, direction, features, language)
text.embed_color()
text.stroke(stroke_width)

text.get_length()
text.get_bbox(xy, anchor)
```
