### ISSUE TITLE
AttributeError: module 'PIL._imaging' has no attribute 'libtiff_support_custom_tags'

### ISSUE THREAD

**Issue by Lucas-C** [python-pillow/Pillow#7019]
### What did you do?
```python
from io import BytesIO
from PIL import Image
img = Image.open("basi0g01.png")
img.save(BytesIO(), format="TIFF", compression="group4")
```
Image file `basi0g01.png`: ![basi0g01](https://user-images.githubusercontent.com/925560/225758528-ad3f53a9-cd49-434c-873a-93a7d32495ca.png)

### What did you expect to happen?
No error raised

### What actually happened?
```pytb
Traceback (most recent call last):
  File "./pil_bug.py", line 14, in <module>
    img.save(BytesIO(), format="TIFF", compression="group4")
  File "/home/lucas_cimon/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/Image.py", line 2435, in save
    save_handler(self, fp, filename)
  File "/home/lucas_cimon/.local/share/virtualenvs/fpdf2/lib/python3.8/site-packages/PIL/TiffImagePlugin.py", line 1810, in _save
    if not Image.core.libtiff_support_custom_tags:
AttributeError: module 'PIL._imaging' has no attribute 'libtiff_support_custom_tags'
```

### What are your OS, Python and Pillow versions?

* OS: WSL (Ubuntu 20.04)
* Python: 3.8.10
* Pillow: https://github.com/python-pillow/Pillow/commit/64f29247c2a36c8c0d255c806132007913b11cf8

Note: I think this issue can be tagged with `TIFF` & `Bug`

**Comment by radarhere** [comment]
I've created PR #7020 to fix the AttributeError, but even if that is merged, you will later encounter `OSError: encoder libtiff not available`.

You are trying to use a "compression" argument. This requires libtiff support. See https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#tiff-saving
> **compression**
> A string containing the desired compression method for the file. (valid only with libtiff installed)

**Comment by Lucas-C** [comment]
> I've created PR #7020 to fix the AttributeError, but even if that is merged, you will later encounter `OSError: encoder libtiff not available`.

OK, thank you.

FYI, after running those commands:
```
$ sudo apt install libtiff5-dev
$ pip uninstall Pillow
$ pip install git+https://github.com/radarhere/Pillow.git@no_libtiff
```
No more error, everything work fine 😊

Thanks @radarhere!
