### ISSUE TITLE
How can I create squircle (not rounded rectangle)?

### ISSUE THREAD

**Issue by nightadmin** [python-pillow/Pillow#7023]
I want to put squircle to my image. A squircle is a shape intermediate between a square and a circle.
![image](https://user-images.githubusercontent.com/78644136/225980918-aa03a4ca-9e14-46d2-8bd5-1efa48a1d119.png)
The task I am doing is to generate image from my Figma layout:
![temp](https://user-images.githubusercontent.com/78644136/225981376-0fa02bab-b18a-4e52-bcc5-ec086f15cd93.png)
In this case squircle is rounded rectangle with corner smoothing. It has following parameters: corner radius (in px) and corner smothing (from 0 to 1).
![image](https://user-images.githubusercontent.com/78644136/225981761-10d63e1d-0a75-4358-8217-2f780557e050.png)
The existing rounded_rectangle function cannot be used because it does not have a corner smoothing parameter.
```python
def rounded_rectangle(self, xy, radius=0, fill=None, outline=None, width=1):
```
How can I do it?

**Comment by radarhere** [comment]
Just to note - the diagram at the beginning of your post comes from https://en.wikipedia.org/wiki/Squircle. 

I initially wondered in this could be done using [`ImageDraw.chord()`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.chord), but I don't think so.

Instead, I found https://www.codespeedy.com/implement-a-superellipse-in-python/, which used matplotlib and NumPy.

I presume you're already using other parts of Pillow, so here is code that creates the plot, saves it in memory as an image, rereads that image with Pillow, and creates an animated GIF from the different values.
```python
import matplotlib.pyplot as plt
import numpy as np
import io
from PIL import Image
a = 5
b = 4
t = np.linspace(0, 2 * np.pi, 100)
ims = []
for n in range(2, 10):
	x = ((np.abs(np.cos(t))) ** (2 / n)) * a * np.sign(np.cos(t))
	y = ((np.abs(np.sin(t))) ** (2 / n)) * b * np.sign(np.sin(t))
	plt.axis("off")
	plt.plot(x, y)
	with io.BytesIO() as f:
		plt.savefig(f, bbox_inches="tight")
		im = Image.open(f)
		im.load()
		ims.append(im)
	plt.clf()
ims[0].save("squircle.gif", save_all=True, append_images=ims[1:], disposal=1, duration=350, loop=0)
```
![squircle](https://user-images.githubusercontent.com/3112309/226089966-105b8397-8ef2-45f3-b92d-753e30efd68f.gif)

**Comment by nightadmin** [comment]
Thank you for your answer. Could you explain how the parameters in your code correlate with those in the screenshot in Figma? The thing is that I need to achieve a pixel-perfect implementation as on the layout.

**Comment by Yay295** [comment]
I found a [blog post by Figma about their squircles](https://www.figma.com/blog/desperately-seeking-squircles/#keep-it-simple-squircle). It seems like they use Bézier curves, so I don't believe the code radarhere posted will be an exact match. They don't specify their exact formula, but I think it could be determined by following what they talk about in that blog post (you can start at the section titled "Keep it simple, squircle").

**Comment by radarhere** [comment]
I've found https://github.com/tienphaw/figma-squircle, which provides "Figma-flavored squircles for everyone" but "does not guarantee to produce the same results as you would get in Figma"

If a library dedicated to this purpose can't guarantee pixel perfect results, then I don't imagine that Figma has released enough information about their closed source software to make exact replication possible.

I thought about exporting the shape from Figma, but testing this with the CSS and SVG export methods, corner smoothing didn't change the output. You could export your squircle from Figma as a PNG, and then open and use that image in Pillow, either to paste or as a mask, but I suspect that wouldn't be satisfactory for your purposes.

**Comment by radarhere** [comment]
"Figma corner smoothing" (or Figma squircles, or Figma superellipses) seems like very specific functionality to be a part of Pillow to my mind.

If you do want to try and approximate the functionality in Python, you could follow the documentation linked. Bezier curves are possible in matplotlib - https://matplotlib.org/stable/gallery/shapes_and_collections/quad_bezier.html

@nightadmin was there anything else, or can this be closed?

**Comment by nightadmin** [comment]
Thanks, I'll try JS Figma squircles realization.
