### ISSUE TITLE
WebPImagePlugin: not supported, how to fix?

### ISSUE THREAD

**Issue by Sibiryakanton** [python-pillow/Pillow#7041]
### What did you do?
I'm trying to use a plugin from a package in a lambda function to store the content of an image in a BytesIO instance.

### What did you expect to happen?
Saving Image content in BytesIO instance.

### What actually happened?
I got the error, the traceback:

``` python
[ERROR] KeyError: 'WEBP'
Traceback (most recent call last):
  File "/function/runtime/runtime.py", line 191, in handle_event
    result = h(r.event, r.context)
  File "/function/code/handler.py", line 63, in handler
    result_file = handler_obj.generate_mutated_image(**params)
  File "/function/code/integration_modules/image_handler.py", line 140, in generate_mutated_image
    self._upload_mutated_file(image=image, filename=self.new_filename)
  File "/function/code/integration_modules/image_handler.py", line 211, in _upload_mutated_file
    image.save(result_file, **save_params)
  File "/function/code/PIL/Image.py", line 2229, in save
    save_handler = SAVE[format.upper()]
```
### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04 LTS
* Python: 3.11
* Pillow: 8.4.0

``` python
from PIL import Image, WebPImagePlugin

from .s3_manager import S3Manager

print(WebPImagePlugin, WebPImagePlugin.SUPPORTED)  # output -  <module 'PIL.WebPImagePlugin'> False

default_file = '{Raw content of image from bucket}'
image = Image.open(BytesIO(default_file), formats='bmp')
result_file = BytesIO()

image.save(result_file, format='webp')
```

Can I solve this problem without installing new system packages?

**Comment by nulano** [comment]
How did you install Pillow?

What does the following script output?
```python
from PIL import features
features.pilinfo(supported_formats=False)
```

---

> Python: 3.11
> Pillow: 8.4.0

Note that Pillow 9.3.0 is the first version to support Python 3.11: https://pillow.readthedocs.io/en/stable/installation.html#python-support

**Comment by radarhere** [comment]
I'm guessing that you don't have libwebp-dev installed? As pointed out in the previous comment, we didn't add support for Python 3.11 until Pillow 9.3.0. When you installed Pillow 8.4.0, it would have been built from source, and looked for libwebp-dev.

I would try installing Pillow >= 9.3.0. That should use the Python wheel instead of building from source.
