### ISSUE TITLE
ImageEnhance docs: please indicate all limits for Brightness and Contrast

### ISSUE THREAD

**Issue by FlorinAndrei** [python-pillow/Pillow#7043]
This page:

https://pillow.readthedocs.io/en/stable/reference/ImageEnhance.html

For Brightness and Contrast, it says a factor of 1.0 returns the original image, and a factor of 0.0 returns a black and grey image, respectively.

The documentation says nothing about factor values higher than 1.0. What are the upper limits for these factors?

**Comment by radarhere** [comment]
I would have thought this was already documented at https://pillow.readthedocs.io/en/stable/reference/ImageEnhance.html#PIL.ImageEnhance._Enhance.enhance
> There are no restrictions on this value.

![Screenshot 2023-04-01 at 1 53 17 pm](https://user-images.githubusercontent.com/3112309/229262399-d35abf27-0a4f-4f71-936e-d42a89e848ab.png)

**Comment by radarhere** [comment]
@FlorinAndrei did that answer your question, or do you still think the behaviour needs to be clarified?

**Comment by FlorinAndrei** [comment]
Technically the information is there. I feel it's not as clear as it could be. E.g. I, being a complete beginner at ImageEnhance, missed that reference. I also had questions such as - are there different limits for the different functions, etc.

The current docs are a bit too terse, that's all.

**Comment by radarhere** [comment]
Each class already re-iterates that the statement from `enhance()` that a factor of 1 gives the original image. Any more repetition feels distracting to me.

How about PR #7065? in that, I've create links from 'enhancement factor' back to `enhance()`, showing clearly where more information can be found. See https://pillow--7065.org.readthedocs.build/en/7065/reference/ImageEnhance.html#classes

**Comment by FlorinAndrei** [comment]
> An [enhancement factor](https://pillow--7065.org.readthedocs.build/en/7065/reference/ImageEnhance.html#enhancement-factor) of 0.0 gives a black and white image. A factor of 1.0 gives the original image.

This may sound counter-intuitive, but that language does suggest to some folks (and I'm one of them) that the limits of the interval are 0.0 and 1.0. I know it may be hard to believe.

**Comment by radarhere** [comment]
How about if I add text explaining that 'greater values increase the brightness/contrast of the image'?

![Screenshot 2023-04-04 at 3 03 04 pm](https://user-images.githubusercontent.com/3112309/229691621-240a998b-bdf6-47ac-9f54-98c2f6a19528.png)

**Comment by FlorinAndrei** [comment]
I think that would work. Thank you!
