### ISSUE TITLE
png and jpg conversion without saving locally

### ISSUE THREAD

**Issue by Hellcat1005** [python-pillow/Pillow#7048]
I am working on deep learning. There is a dataset with many png files. I downloaded them. Because those png files take up a lot of space, I converted png files to jpg files. Then I trained my model on jpg files. I know that the pixels are slightly different with png and jpg. So I need to read a png file. Then, convert png to jpg. After that, put the jpg data to the model.

I can use opencv to implement this function:
```python
# load a png file
img_png = cv2.imread(path_img_png)

# convert png to jpg
img_encode = cv2.imencode('.jpg', img_png)[1]
img_decode = cv2.imdecode(img_encode, cv2.IMREAD_COLOR)

# put the jpg data to the model
prediciton = model(img_decode)
```

I do not know how to do this using PIL.

**Comment by Yay295** [comment]
[`Image.save()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) takes a filename, pathlib.Path object, or file object. You can pass a [`io.BytesIO`](https://docs.python.org/3/library/io.html#io.BytesIO) as a file object and the image will be saved to that instead of to an actual file.

**Comment by nulano** [comment]
> I need to read a png file. Then, convert png to jpg.

You can save an image into any file object, e.g. `io.BytesIO`. Similarly, you can read any file object, e.g. `io.BytesIO`.
So, to convert an image to a JPEG buffer and then read it again, you can do:

```python
from PIL import Image
from io import BytesIO

buf = BytesIO()
with Image.open("E:/Git/Pillow/Tests/images/hopper.png") as im:
    print(im)  # <PIL.PngImagePlugin.PngImageFile image mode=RGB size=128x128 at 0x23D6E712250>
    im.save(buf, format="JPEG")

print(buf, buf.getbuffer().nbytes)  # <_io.BytesIO object at 0x0000023D6E71B790> 4677

reloaded = Image.open(buf)
print(reloaded)  # <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x23D6E712BD0>
```

> I know that the pixels are slightly different with png and jpg.

I'm not sure this will do what you expect. JPEG files use lossy compression, both saving and reading a JPEG file is allowed to introduce variance. You will likely get the same result if you always use the same tool, but even updating to a different version can give you different results.

**Comment by Yay295** [comment]
Since they're doing deep learning, the slight different between JPEG readers/versions probably doesn't matter.

**Comment by Hellcat1005** [comment]
> > I need to read a png file. Then, convert png to jpg.
> 
> You can save an image into any file object, e.g. `io.BytesIO`. Similarly, you can read any file object, e.g. `io.BytesIO`. So, to convert an image to a JPEG buffer and then read it again, you can do:
> 
> ```python
> from PIL import Image
> from io import BytesIO
> 
> buf = BytesIO()
> with Image.open("E:/Git/Pillow/Tests/images/hopper.png") as im:
>     print(im)  # <PIL.PngImagePlugin.PngImageFile image mode=RGB size=128x128 at 0x23D6E712250>
>     im.save(buf, format="JPEG")
> 
> print(buf, buf.getbuffer().nbytes)  # <_io.BytesIO object at 0x0000023D6E71B790> 4677
> 
> reloaded = Image.open(buf)
> print(reloaded)  # <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x23D6E712BD0>
> ```
> 
> > I know that the pixels are slightly different with png and jpg.
> 
> I'm not sure this will do what you expect. JPEG files use lossy compression, both saving and reading a JPEG file is allowed to introduce variance. You will likely get the same result if you always use the same tool, but even updating to a different version can give you different results.

Thank you. It works. But the pixels are different by using opencv conversion and pillow conversion. I think the best way for me is to use the same method to generate jpg data.

**Comment by Hellcat1005** [comment]
> > I need to read a png file. Then, convert png to jpg.
> 
> You can save an image into any file object, e.g. `io.BytesIO`. Similarly, you can read any file object, e.g. `io.BytesIO`. So, to convert an image to a JPEG buffer and then read it again, you can do:
> 
> ```python
> from PIL import Image
> from io import BytesIO
> 
> buf = BytesIO()
> with Image.open("E:/Git/Pillow/Tests/images/hopper.png") as im:
>     print(im)  # <PIL.PngImagePlugin.PngImageFile image mode=RGB size=128x128 at 0x23D6E712250>
>     im.save(buf, format="JPEG")
> 
> print(buf, buf.getbuffer().nbytes)  # <_io.BytesIO object at 0x0000023D6E71B790> 4677
> 
> reloaded = Image.open(buf)
> print(reloaded)  # <PIL.JpegImagePlugin.JpegImageFile image mode=RGB size=128x128 at 0x23D6E712BD0>
> ```
> 
> > I know that the pixels are slightly different with png and jpg.
> 
> I'm not sure this will do what you expect. JPEG files use lossy compression, both saving and reading a JPEG file is allowed to introduce variance. You will likely get the same result if you always use the same tool, but even updating to a different version can give you different results.

Thank you. It works. But the pixels are different by using opencv conversion and pillow conversion. I think the best way for me is to use the same method to generate jpg data.
