### ISSUE TITLE
Should I use Pillow or PIL?

### ISSUE THREAD

**Issue by aodag** [python-pillow/Pillow#705]
Hi.

When I operate Images, I use Pillow now.
But searching for "Python Imaging" on internet
gives me to use PIL.

AFAIK, PIL is released at 2009, past 5 years without maintainance.
I trust Pillow is successer for PIL.

I wish to Pillow becomes PIL
or PIL releases new distribution that has just dependency to Pillow.

I think that is similar to relationship between setuptools and distribute.
I hope to be solved confusions for Python Imaging Library.

Thanks

**Comment by radarhere** [comment]
See #1535 for more discussion about what should happen with PIL on PyPI.
