### ISSUE TITLE
Image not showing on macOS 

### ISSUE THREAD

**Issue by lrannn** [python-pillow/Pillow#7055]
### What are your OS, Python and Pillow versions?

* OS: macOS 13.2.1 m1 pro
* Python: Python 3.9.6
* Pillow: 9.4.0

The demo's only feature is show the local image with Tkinter+PIL, but it doesn't work, I don't know why

```python
import tkinter as tk
from PIL import Image, ImageTk

root = tk.Tk()
root.title('图片展示')
root.geometry('420x480')

path = './hello.jpg' 
#path = 'hello.jpg'
image = Image.open(path)
image = image.resize((400, 400)) 
photo = ImageTk.PhotoImage(image)

img_label = tk.Label(root, image=photo)
img_label.pack()

root.mainloop()

```

![img](https://i.postimg.cc/HsJCDcQ4/2023-04-01-17-25-27.png)

**Comment by radarhere** [comment]
Your code works for me.

Does "hello" display if you just show text instead?

```python
import tkinter as tk

root = tk.Tk()
root.title('图片展示')
root.geometry('420x480')

img_label = tk.Label(root, text="hello")
img_label.pack()

root.mainloop()
```
If not, then the problem is with tkinter rather than Pillow.

If it does still work, could you upload a copy of hello.jpg?

**Comment by lrannn** [comment]
> Your code works for me.
> 
> Does "hello" display if you just show text instead?
> 
> ```python
> import tkinter as tk
> 
> root = tk.Tk()
> root.title('图片展示')
> root.geometry('420x480')
> 
> img_label = tk.Label(root, text="hello")
> img_label.pack()
> 
> root.mainloop()
> ```
> 
> If not, then the problem is with tkinter rather than Pillow.
> 
> If it does still work, could you upload a copy of hello.jpg?

Thanks for your support, I  just tried it and the text is not displayed, so maybe it's tkinters problem, then I'll go find the cause of the problem again, thank you very much!! 👏👏👏
