### ISSUE TITLE
version `GLIBCXX_3.4.29' not found

### ISSUE THREAD

**Issue by Apisteftos** [python-pillow/Pillow#7071]
I just trying to work with images and I am getting an error. Is it somewhere libstdc++.so.6 in the site-packages locally missing?

OS: Ubuntu 22.04.02 LTS
VSCode
Pip 

```python
from PIL import Image

img = Image.open("my/image/path")

print(img.size)

img.show("original image")

resized_image = img.resize((500, 500))

resized_image.show("resized image")
```

Error
====
```
/snap/core20/current/lib/x86_64-linux-gnu/libstdc++.so.6: version `GLIBCXX_3.4.29' not found (required by /lib/x86_64-linux-gnu/libproxy.so.1)


symbol lookup error: /snap/core20/current/lib/x86_64-linux-gnu/libpthread.so.0: undefined symbol: __libc_pthread_init, version GLIBC_PRIVATE

```

```
strings /usr/lib/x86_64-linux-gnu/libstdc++.so.6 | grep GLIBCXX


GLIBCXX_3.4
GLIBCXX_3.4.1
GLIBCXX_3.4.2
GLIBCXX_3.4.3
GLIBCXX_3.4.4
GLIBCXX_3.4.5
GLIBCXX_3.4.6
GLIBCXX_3.4.7
GLIBCXX_3.4.8
GLIBCXX_3.4.9
GLIBCXX_3.4.10
GLIBCXX_3.4.11
GLIBCXX_3.4.12
GLIBCXX_3.4.13
GLIBCXX_3.4.14
GLIBCXX_3.4.15
GLIBCXX_3.4.16
GLIBCXX_3.4.17
GLIBCXX_3.4.18
GLIBCXX_3.4.19
GLIBCXX_3.4.20
GLIBCXX_3.4.21
GLIBCXX_3.4.22
GLIBCXX_3.4.23
GLIBCXX_3.4.24
GLIBCXX_3.4.25
GLIBCXX_3.4.26
GLIBCXX_3.4.27
GLIBCXX_3.4.28
GLIBCXX_3.4.29
GLIBCXX_3.4.30
GLIBCXX_DEBUG_MESSAGE_LENGTH

```

**Comment by radarhere** [comment]
Hi. If you'll permit an odd question - does the error happen if you just run Python, without Pillow? At first glance, I don't see anything related to Pillow in your error.

To try and be helpful though, https://stackoverflow.com/a/46613656/4093019 or https://stackoverflow.com/questions/72205522/glibcxx-3-4-29-not-found seem interesting.

**Comment by Apisteftos** [comment]
I came from stackoverflow here, because I didn't resolve my problem

**Comment by radarhere** [comment]
Does the error happen if you just run Python, without Pillow? At first glance, I don't see anything related to Pillow in your error.

**Comment by Apisteftos** [comment]
No I am not seeing somewhere else problem. 
It seems it's a bug in VScode [#179274](https://github.com/microsoft/vscode/issues/179274).

**Comment by Apisteftos** [comment]
Fixed: Installed the Version  [GTK4](https://www.gtk.org/docs/installations/linux/) with ` sudo apt-get install libgtk-4-dev ` and specified the GTK PATH with `GTK_PATH=/usr/lib/x86_64-linux-gnu/gtk-4.0` .

**Comment by radarhere** [comment]
Ok, thanks for the update on how you solved it. Let us know if there is anything else.

**Comment by muhammedsirajudeen** [comment]
i have actually come across the problem for me i think it was a bug in vscode although @Apisteftos has worked for me i think vscode messed with some environment variable just exporting it fixed my issue

**Comment by Apisteftos** [comment]
> i have actually come across the problem for me i think it was a bug in vscode although @Apisteftos has worked for me i think vscode messed with some environment variable just exporting it fixed my issue

This issue is nothing less of a snap version of VScode. You have to reinstall VScode in .* deb format, otherwise it doesn't work. Snap mess up with the local libraries. I will close the issue.
