### ISSUE TITLE
pillow-simd crashed kernel when using torchvision.transforms.resize

### ISSUE THREAD

**Issue by chauvinfish** [python-pillow/Pillow#7076]
**To reproduce : python 3.9
torchvision 0.15.1+cu117
pytoch 2.0.0+cu117
pillow-simd 9.0
I tried when using pytorch0.41, python 3.6.9 and normal pillow, no such bug happend.
I tried uninstalling pillow-simd and using pillow 9.2 instead, the bug fixed.**
bugged code:

```python
from PIL import Image  

import torch
import torch.utils.data as data
import torchvision
from torchvision import transforms
print(torchvision.__version__)
print(torch.__version__)
datapath = r'M:/datas/kitti_raw\2011_09_26/2011_09_26_drive_0014_sync\image_02/data\0000000016.png'
im = Image.open(datapath)
im = im.convert('RGB')
im = transforms.Resize((200,200))(im)
print (type(im))
Windows fatal exception: code 0xc000001d
```

Main thread:
Current thread 0x00005894 (most recent call first):
File “C:\Users\yan56\AppData\Roaming\Python\Python39\site-packages\PIL\Image.py”, line 1980 in resize
File “C:\Users\yan56\AppData\Roaming\Python\Python39\site-packages\torchvision\transforms_functional_pil.py”, line 250 in resize
File “C:\Users\yan56\AppData\Roaming\Python\Python39\site-packages\torchvision\transforms\functional.py”, line 490 in resize
File “C:\Users\yan56\AppData\Roaming\Python\Python39\site-packages\torchvision\transforms\transforms.py”, line 361 in forward
File “C:\Users\yan56\AppData\Roaming\Python\Python39\site-packages\torch\nn\modules\module.py”, line 1501 in _call_impl
File “C:\Users\yan56\Desktop\monocular-depth-prediction\monodepth2-master\datasets\untitled0.py”, line 22 in
File “C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py”, line 465 in exec_code
File “C:\ProgramData\Anaconda3\lib\site-packages\spyder_kernels\customize\spydercustomize.py”, line 585 in runfile
File “C:\Users\yan56\AppData\Local\Temp\ipykernel_13700\484932580.py”, line 1 in

**Comment by radarhere** [comment]
Hi. pillow-simd has a separate repository. Please create an issue at https://github.com/uploadcare/pillow-simd instead.
