### ISSUE TITLE
Un-premultiplication calculation is slightly wrong

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#7079]
The calculation to premultiply a value is `(value * alpha) / 255`. Pillow uses `(value * alpha + 127) / 255` so that the resulting values are rounded up, since this is all using integers. To un-premultiply then we should use `(255 * value - 127) / alpha`, but what we're actually using is `255 * value / alpha`.

https://github.com/python-pillow/Pillow/blob/b0c76535022b795f2c31d725131c54e8e10d1ff7/src/libImaging/Convert.c#L128-L146
https://github.com/python-pillow/Pillow/blob/b0c76535022b795f2c31d725131c54e8e10d1ff7/src/libImaging/Convert.c#L461-L499

Example image:
![image](https://user-images.githubusercontent.com/8922038/230810846-b17a5880-4c37-4405-9174-3a7b94e83f36.png)
```python
from PIL import Image
x = Image.open('image.png')
x.getpixel((0,32*3)) # (71, 10, 91, 2)
x.convert('RGBa').getpixel((0,32*3)) # (1, 0, 1, 2)
x.convert('RGBa').convert('RGB').getpixel((0,32*3)) # (127, 0, 127)
```

Premultiplication and un-premultiplication is inherently lossy, but with the correct calculation that last line should return `(64, 0, 64)`, which is a bit closer to the original value.

**Comment by radarhere** [comment]
To be clear, the example code you've posted uses
https://github.com/python-pillow/Pillow/blob/b0c76535022b795f2c31d725131c54e8e10d1ff7/src/libImaging/Convert.c#L448-L459
https://github.com/python-pillow/Pillow/blob/b0c76535022b795f2c31d725131c54e8e10d1ff7/src/libImaging/ImagingUtils.h#L19-L20
and
https://github.com/python-pillow/Pillow/blob/b0c76535022b795f2c31d725131c54e8e10d1ff7/src/libImaging/Convert.c#L482-L499

**Comment by radarhere** [comment]
So you're suggesting
```diff
diff --git a/src/libImaging/Convert.c b/src/libImaging/Convert.c
index 7fe24a639..1963b7309 100644
--- a/src/libImaging/Convert.c
+++ b/src/libImaging/Convert.c
@@ -490,9 +490,9 @@ rgba2rgb_(UINT8 *out, const UINT8 *in, int xsize) {
             *out++ = in[1];
             *out++ = in[2];
         } else {
-            *out++ = CLIP8((255 * in[0]) / alpha);
-            *out++ = CLIP8((255 * in[1]) / alpha);
-            *out++ = CLIP8((255 * in[2]) / alpha);
+            *out++ = CLIP8((255 * in[0] - 127) / alpha);
+            *out++ = CLIP8((255 * in[1] - 127) / alpha);
+            *out++ = CLIP8((255 * in[2] - 127) / alpha);
         }
         *out++ = 255;
     }
```
along with similar changes to other conversion functions.

I put together this code to calculate the difference between the possible values for an RGB channel and the value after RGBA -> RGBa -> RGB with an alpha value of 2 as in your example.
```python
totaldistance = 0
for i in range(0, 256):
    im = Image.new("RGBA", (1, 1), (i, i, i, 2))
    j = im.convert("RGBa").convert("RGB").getpixel((0, 0))[0]
    totaldistance += abs(i - j)
    print("RGBA value:", i, "RGBA -> RGBa -> RGB value:", j)
print()
print("Total distance:", totaldistance)
```

Comparing the current code with your version, I get "Total distance" before of 8128, and "Total distance" after of 24512. So this doesn't seem like an improvement to me?

| RGBA Value | Before | After |
| - | - | - |
|0|0|255|
|1|0|255|
|2|0|255|
|3|0|255|
|4|0|255|
|5|0|255|
|6|0|255|
|7|0|255|
|8|0|255|
|9|0|255|
|10|0|255|
|11|0|255|
|12|0|255|
|13|0|255|
|14|0|255|
|15|0|255|
|16|0|255|
|17|0|255|
|18|0|255|
|19|0|255|
|20|0|255|
|21|0|255|
|22|0|255|
|23|0|255|
|24|0|255|
|25|0|255|
|26|0|255|
|27|0|255|
|28|0|255|
|29|0|255|
|30|0|255|
|31|0|255|
|32|0|255|
|33|0|255|
|34|0|255|
|35|0|255|
|36|0|255|
|37|0|255|
|38|0|255|
|39|0|255|
|40|0|255|
|41|0|255|
|42|0|255|
|43|0|255|
|44|0|255|
|45|0|255|
|46|0|255|
|47|0|255|
|48|0|255|
|49|0|255|
|50|0|255|
|51|0|255|
|52|0|255|
|53|0|255|
|54|0|255|
|55|0|255|
|56|0|255|
|57|0|255|
|58|0|255|
|59|0|255|
|60|0|255|
|61|0|255|
|62|0|255|
|63|0|255|
|64|127|64|
|65|127|64|
|66|127|64|
|67|127|64|
|68|127|64|
|69|127|64|
|70|127|64|
|71|127|64|
|72|127|64|
|73|127|64|
|74|127|64|
|75|127|64|
|76|127|64|
|77|127|64|
|78|127|64|
|79|127|64|
|80|127|64|
|81|127|64|
|82|127|64|
|83|127|64|
|84|127|64|
|85|127|64|
|86|127|64|
|87|127|64|
|88|127|64|
|89|127|64|
|90|127|64|
|91|127|64|
|92|127|64|
|93|127|64|
|94|127|64|
|95|127|64|
|96|127|64|
|97|127|64|
|98|127|64|
|99|127|64|
|100|127|64|
|101|127|64|
|102|127|64|
|103|127|64|
|104|127|64|
|105|127|64|
|106|127|64|
|107|127|64|
|108|127|64|
|109|127|64|
|110|127|64|
|111|127|64|
|112|127|64|
|113|127|64|
|114|127|64|
|115|127|64|
|116|127|64|
|117|127|64|
|118|127|64|
|119|127|64|
|120|127|64|
|121|127|64|
|122|127|64|
|123|127|64|
|124|127|64|
|125|127|64|
|126|127|64|
|127|127|64|
|128|127|64|
|129|127|64|
|130|127|64|
|131|127|64|
|132|127|64|
|133|127|64|
|134|127|64|
|135|127|64|
|136|127|64|
|137|127|64|
|138|127|64|
|139|127|64|
|140|127|64|
|141|127|64|
|142|127|64|
|143|127|64|
|144|127|64|
|145|127|64|
|146|127|64|
|147|127|64|
|148|127|64|
|149|127|64|
|150|127|64|
|151|127|64|
|152|127|64|
|153|127|64|
|154|127|64|
|155|127|64|
|156|127|64|
|157|127|64|
|158|127|64|
|159|127|64|
|160|127|64|
|161|127|64|
|162|127|64|
|163|127|64|
|164|127|64|
|165|127|64|
|166|127|64|
|167|127|64|
|168|127|64|
|169|127|64|
|170|127|64|
|171|127|64|
|172|127|64|
|173|127|64|
|174|127|64|
|175|127|64|
|176|127|64|
|177|127|64|
|178|127|64|
|179|127|64|
|180|127|64|
|181|127|64|
|182|127|64|
|183|127|64|
|184|127|64|
|185|127|64|
|186|127|64|
|187|127|64|
|188|127|64|
|189|127|64|
|190|127|64|
|191|127|64|
|192|255|191|
|193|255|191|
|194|255|191|
|195|255|191|
|196|255|191|
|197|255|191|
|198|255|191|
|199|255|191|
|200|255|191|
|201|255|191|
|202|255|191|
|203|255|191|
|204|255|191|
|205|255|191|
|206|255|191|
|207|255|191|
|208|255|191|
|209|255|191|
|210|255|191|
|211|255|191|
|212|255|191|
|213|255|191|
|214|255|191|
|215|255|191|
|216|255|191|
|217|255|191|
|218|255|191|
|219|255|191|
|220|255|191|
|221|255|191|
|222|255|191|
|223|255|191|
|224|255|191|
|225|255|191|
|226|255|191|
|227|255|191|
|228|255|191|
|229|255|191|
|230|255|191|
|231|255|191|
|232|255|191|
|233|255|191|
|234|255|191|
|235|255|191|
|236|255|191|
|237|255|191|
|238|255|191|
|239|255|191|
|240|255|191|
|241|255|191|
|242|255|191|
|243|255|191|
|244|255|191|
|245|255|191|
|246|255|191|
|247|255|191|
|248|255|191|
|249|255|191|
|250|255|191|
|251|255|191|
|252|255|191|
|253|255|191|
|254|255|191|
|255|255|191|

**Comment by Yay295** [comment]
I'm not sure why you're getting 255 for values 0 though 63, but I wrote a simple test in C (without Pillow code) and I get the same conclusion. In the specific case I noticed originally, my change is better, but on average the current code is better.

```c
#include <stdint.h>
#include <stdio.h>

#define SHIFTFORDIV255(a) ((((a) >> 8) + a) >> 8)
#define MULDIV255(a, b, tmp) (tmp = (a) * (b) + 128, SHIFTFORDIV255(tmp))
#define CLIP8(v) ((v) <= 0 ? 0 : (v) < 256 ? (v) : 255)

uint8_t premultiply(const uint8_t value, const uint8_t alpha) {
    unsigned int temp;
    return MULDIV255(value, alpha, temp);
}

uint8_t unpremultiply_old(const uint8_t value, const uint8_t alpha) {
    if (alpha == 0 || alpha == 255) {
        return value;
    }
    return CLIP8((255 * value) / alpha);
}

uint8_t unpremultiply_new(const uint8_t value, const uint8_t alpha) {
    if (alpha == 0 || alpha == 255) {
        return value;
    }
    return CLIP8((255 * value - 127) / alpha);
}

int main() {
    printf("Value,Alpha,Premultiplied,Unpremultiplied Old,Unpremultiplied New\n");
    for (int value = 0; value < 256; ++value) {
        for (int alpha = 0; alpha < 256; ++alpha) {
            const uint8_t premultiplied = premultiply(value, alpha);
            const uint8_t unpremultiplied_old = unpremultiply_old(premultiplied, alpha);
            const uint8_t unpremultiplied_new = unpremultiply_new(premultiplied, alpha);
            printf("%i,%i,%i,%i,%i\n", value, alpha, premultiplied, unpremultiplied_old, unpremultiplied_new);
        }
    }
}
```

[values.xlsx](https://github.com/python-pillow/Pillow/files/11191058/values.xlsx)
