### ISSUE TITLE
`wl-paste` with image copied from browser results in `ImageGrab.grabclipboard` error 

### ISSUE THREAD

**Issue by rrcgat** [python-pillow/Pillow#7093]
### What did you do?

When source application offered multiple MIME type, `wl-paste` without `-t mime/type` maybe result in other MEME type instead of image. `ImageGrab.grabclipboard` use only `wl-paste` without arguments, which reports error whenever calling it with multiple MEME type. For example, open some website with images, copy the image, it will offer multiple MIME type.

### What did you expect to happen?

No error reports.

### What actually happened?

Error reports like this:

```
Traceback (most recent call last):
  File "/home/user/workspace/grab.py", line 9, in <module>
    main()
  File "/home/user/workspace/grab.py", line 5, in main
    ImageGrab.grabclipboard()
  File "/home/user/.local/lib/python3.10/site-packages/PIL/ImageGrab.py", line 146, in grabclipboard
    im = Image.open(filepath)
  File "/home/user/.local/lib/python3.10/site-packages/PIL/Image.py", line 3298, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmpvi9tcfs3'
```

### What are your OS, Python and Pillow versions?

* OS: Arch Linux
* Python: CPython 3.10.10
* Pillow: 9.5.0

```python
from PIL import ImageGrab


def main():
    ImageGrab.grabclipboard()


if __name__ == "__main__":
    main()
```

**Comment by radarhere** [comment]
I imagine you've tested this on your system without Pillow as well - what happens when you call `wl-paste` without arguments? In other words, what is the error hiding behind `UnidentifiedImageError` here?

**Comment by rrcgat** [comment]
@radarhere `wl-paste` print nothing in the terminal. I found that `ImageGrab.grabclipboard()` creates an empty file. 

Here's the output of `wl-paste` in my terminal:

```
$ wl-paste       

$ wl-paste --version
wl-clipboard 2.1.0
Copyright (C) 2019 Sergey Bugaev
License GPLv3+: GNU GPL version 3 or later <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
$ wl-paste -l       
audio/x-riff
image/webp
image/avif
image/tiff
image/jpeg
text/ico
image/icon
image/ico
application/ico
image/vnd.microsoft.icon
image/x-win-bitmap
image/x-ico
image/x-icon
image/x-MS-bmp
image/x-bmp
image/bmp
image/png
```
![image](https://user-images.githubusercontent.com/26518505/232266814-caa89f09-781f-4e85-bc25-fb08da4491c7.png)
