### ISSUE TITLE
Japanese text in EXIF woes

### ISSUE THREAD

**Issue by biggestsonicfan** [python-pillow/Pillow#7120]
### What did you do?
First attempt: Use the UserComment field to store the description as "Google 翻訳提供の翻訳テキスト". 

Second attempt: Use the ImageDescription field to store the description as "Google 翻訳提供の翻訳テキスト". 

Third attempt: Use the ImageDescription field encoded in utf8 to store the description as "Google 翻訳提供の翻訳テキスト".

### What did you expect to happen?

Both image viewers and Pillow should read the EXIF field as "Google 翻訳提供の翻訳テキスト"

### What actually happened?
First attempt: UserComment is not visible in my default image viewers, and GIMP sees `Exif.Image.0x9286` as `Google ????????????`

Second attempt: ImageDescription is a visible EXIF field in my default image viewer, but also shows `Google ????????????`

Third attempt: Both my default image viewer and GIMP correctly read the ImageDescription EXIF field as "Google 翻訳提供の翻訳テキスト", however PILLOW reads the EXIF field as `Google ç¿»è¨³æä¾ã®ç¿»è¨³ãã­ã¹ã`

### What are your OS, Python and Pillow versions?

* OS: OpenSUSE Tumbleweed
* Python: 3.10.10
* Pillow: 9.5.0

First attempt:
```python
import os, sys
from PIL import Image

img_path = r"/home/rob/Pictures/RMG/the_legend_of_zelda-001.png"

#Get the original access and modified times
stinfo = os.stat(img_path)
orig_acc = stinfo.st_atime
orig_mod = stinfo.st_mtime

#Open the image
image = Image.open(img_path)
exif = image.getexif()
user_comment = "Google 翻訳提供の翻訳テキスト"
exif[0x9286] = user_comment
#Get rid of alpha
rgb_image = image.convert('RGB')
#Resize
resized_im = rgb_image.resize((round(rgb_image.size[0]*0.6), round(rgb_image.size[1]*0.6)))
#Compress and save with new exif
resized_im.save(img_path, "JPEG", optimize = True, quality = 60, exif=exif)
#Restore original access and modified times
os.utime(img_path, (orig_acc, orig_mod))
```
Second attempt:
```python
import os, sys
from PIL import Image

img_path = r"/home/rob/Pictures/RMG/the_legend_of_zelda-001.png"

#Get the original access and modified times
stinfo = os.stat(img_path)
orig_acc = stinfo.st_atime
orig_mod = stinfo.st_mtime

#Open the image
image = Image.open(img_path)
exif = image.getexif()
user_comment = "Google 翻訳提供の翻訳テキスト"
exif[0x010e] = user_comment
#Get rid of alpha
rgb_image = image.convert('RGB')
#Resize
resized_im = rgb_image.resize((round(rgb_image.size[0]*0.6), round(rgb_image.size[1]*0.6)))
#Compress and save with new exif
resized_im.save(img_path, "JPEG", optimize = True, quality = 60, exif=exif)
#Restore original access and modified times
os.utime(img_path, (orig_acc, orig_mod))
```

Third attempt:
```python
import os, sys
from PIL import Image

img_path = r"/home/rob/Pictures/RMG/the_legend_of_zelda-001.png"

#Get the original access and modified times
stinfo = os.stat(img_path)
orig_acc = stinfo.st_atime
orig_mod = stinfo.st_mtime

#Open the image
image = Image.open(img_path)
exif = image.getexif()
user_comment = "Google 翻訳提供の翻訳テキスト"
exif[0x010e] = user_comment.encode('utf8')
#Get rid of alpha
rgb_image = image.convert('RGB')
#Resize
resized_im = rgb_image.resize((round(rgb_image.size[0]*0.6), round(rgb_image.size[1]*0.6)))
#Compress and save with new exif
resized_im.save(img_path, "JPEG", optimize = True, quality = 60, exif=exif)
#Restore original access and modified times
os.utime(img_path, (orig_acc, orig_mod))

print(Image.open(img_path).getexif()[0x010e])
```
EDIT:
Additional notes: If taking the UserComment code and using the line `user_comment = "Google 翻訳提供の翻訳テキスト".encode("utf8")`, Pillow seems to encode it as a byte array, which can be used with `print(Image.open(img_path).getexif()[0x9286].decode("utf8"))` to correctly print in python "Google 翻訳提供の翻訳テキスト", however you can not read this in GIMP, where it only shows the byte array. I am looking for a method to both display in image viewers properly and be able to be read by Pillow.

**Comment by radarhere** [comment]
ImageDescription is an ASCII tag - https://www.awaresystems.be/imaging/tiff/tifftags/imagedescription.html. ASCII doesn't include Japanese characters, so I wouldn't expect this to work.

As for UserComment on the other hand, https://www.awaresystems.be/imaging/tiff/tifftags/privateifd/exif/usercomment.html
> This tag is without the character code limitations of the ImageDescription tag.

I find that the following code prints out "Google 翻訳提供の翻訳テキスト".
```python
from PIL import Image
img_path = "out.jpg"
image = Image.open("Tests/images/hopper.png")
exif = image.getexif()
exif[0x9286] = "Google 翻訳提供の翻訳テキスト".encode('utf8')
image.save(img_path, exif=exif)

print(Image.open(img_path).getexif()[0x9286].decode())
```

However, you have said
> UserComment is not visible in my default image viewers

I don't know what those image viewers are, so I can't test this. So let's go back to ImageDescription.

You could try ignoring the specification, and changing the ImageDescription tag type to BYTE.
```python
from PIL import Image, TiffImagePlugin, TiffTags
img_path = "out.jpg"
image = Image.open("Tests/images/hopper.png")
exif = image.getexif()
exif[0x010e] = "Google 翻訳提供の翻訳テキスト".encode('utf8')
TiffTags.TAGS_V2[0x010e] = TiffTags.TagInfo(0x010e, "ImageDescription", TiffTags.BYTE, 1)
image.save(img_path, exif=exif)

reloaded = Image.open(img_path)
print(reloaded.getexif()[0x010e].decode())
```

**Comment by biggestsonicfan** [comment]
> I find that the following code prints out "Google 翻訳提供の翻訳テキスト".

I edited my original post at the bottom and included this code prior to your answer. This does not work for me because both my image viewer Gwenview and image manipulation program GIMP will read this as a byte array.

>You could try ignoring the specification, and changing the ImageDescription tag type to BYTE.

This seems to do the same thing and only produces a byte array in both programs.

>ImageDescription is an ASCII tag - https://www.awaresystems.be/imaging/tiff/tifftags/imagedescription.html. ASCII doesn't include Japanese characters, so I wouldn't expect this to work.

Would both GIMP and Gwenview break spec to display UTF8 in this field correctly? That seems odd and something it shouldn't do...

**Comment by radarhere** [comment]
Ok, how about this? You've said this code works with both GIMP and your default image viewer, and now I've figured out how to get Python to show the original characters.
```python
from PIL import Image, TiffImagePlugin, TiffTags
img_path = "out.jpg"
image = Image.open("Tests/images/hopper.png")
exif = image.getexif()
exif[0x010e] = "Google 翻訳提供の翻訳テキスト".encode('utf8')
image.save(img_path, exif=exif)

reloaded = Image.open(img_path)
print(reloaded.getexif()[0x010e].encode("latin-1").decode("utf-8"))
```

**Comment by biggestsonicfan** [comment]
Ha, I love it! Thanks! Works a treat!
