### ISSUE TITLE
Emoji sequences are not rendered correctly

### ISSUE THREAD

**Issue by missionfloyd** [python-pillow/Pillow#7121]
### What did you do?
```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("NotoColorEmoji.ttf", 109)
img = Image.new("RGB", (300, 150), "white")
draw = ImageDraw.Draw(img)
draw.text((10, 10), "🏴‍☠️", font=font, embedded_color=True)# zero-width joiner sequence
#draw.text((10, 10), "👩🏽", font=font, embedded_color=True)# modifier sequence
#draw.text((10, 10), "🇺🇸", font=font, embedded_color=True)# flag sequence
#draw.text((10, 10), "🏴󠁧󠁢󠁥󠁮󠁧󠁿", font=font, embedded_color=True)# tag sequence
#draw.text((10, 10), "1️⃣", font=font, embedded_color=True)# keycap sequence
img.save("out.png")
```
### What did you expect to happen?
![ZWJ](https://user-images.githubusercontent.com/4073789/235272014-48fca47e-2bc6-4d68-ba06-272982a11b9f.png)
![modifier](https://user-images.githubusercontent.com/4073789/235272512-dc34c6ab-3526-487a-ad7d-7c430fcb3be8.png)
![flag](https://user-images.githubusercontent.com/4073789/235272529-2c19b89f-768d-4678-bf12-fdbf2e4cd22d.png)
![tag](https://user-images.githubusercontent.com/4073789/235272555-ce219a17-1dca-4735-95c2-86432eb45a74.png)
![keycap](https://user-images.githubusercontent.com/4073789/235272568-81a90a11-86bc-4458-8aa0-609fc29a10b1.png)

### What actually happened?
![ZWJ](https://user-images.githubusercontent.com/4073789/235270789-5619bff3-fbc4-4f2e-ae2c-32123ade398f.png)
![modifier](https://user-images.githubusercontent.com/4073789/235271909-4225ef74-dd1e-466b-85bc-960b24944d3a.png)
![flag](https://user-images.githubusercontent.com/4073789/235271905-a94520fe-a172-4460-9959-642e4f64946d.png)
![tag](https://user-images.githubusercontent.com/4073789/235272297-a1545eab-b9eb-4826-9daf-f915c4d75738.png)
![keycap](https://user-images.githubusercontent.com/4073789/235272309-49791cee-4fda-4707-8430-e0ed1bb78b92.png)

### What are your OS, Python and Pillow versions?
* OS: Windows 10, Linux
* Python: 3.10.11
* Pillow: 9.5.0

**Comment by radarhere** [comment]
Hi. I think the first problem is that you don't have RAQM support.

I find that the following code
```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("Tests/fonts/NotoColorEmoji.ttf", 109, layout_engine=ImageFont.Layout.BASIC)
img = Image.new("RGB", (300, 750), "white")
draw = ImageDraw.Draw(img)
draw.text((10, 0), "🏴‍☠️", font=font, embedded_color=True)# zero-width joiner sequence
draw.text((10, 150), "👩🏽", font=font, embedded_color=True)# modifier sequence
draw.text((10, 300), "🇺🇸", font=font, embedded_color=True)# flag sequence
draw.text((10, 450), "🏴󠁧󠁢󠁥󠁮󠁧󠁿", font=font, embedded_color=True)# tag sequence
draw.text((10, 600), "1️⃣", font=font, embedded_color=True)# keycap sequence
img.save("out.png")
```
produces
<img src="https://user-images.githubusercontent.com/3112309/235276646-dfe1a95f-77d3-43ae-830e-29ff0a4384da.png" width="100" />

But when I stop specifying the `layout_engine` as BASIC,
```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype("Tests/fonts/NotoColorEmoji.ttf", 109)
img = Image.new("RGB", (300, 750), "white")
draw = ImageDraw.Draw(img)
draw.text((10, 0), "🏴‍☠️", font=font, embedded_color=True)# zero-width joiner sequence
draw.text((10, 150), "👩🏽", font=font, embedded_color=True)# modifier sequence
draw.text((10, 300), "🇺🇸", font=font, embedded_color=True)# flag sequence
draw.text((10, 450), "🏴󠁧󠁢󠁥󠁮󠁧󠁿", font=font, embedded_color=True)# tag sequence
draw.text((10, 600), "1️⃣", font=font, embedded_color=True)# keycap sequence
img.save("out.png")
```
produces
<img src="https://user-images.githubusercontent.com/3112309/235276665-f049afae-0f43-4275-a882-cb1ae3492103.png" width="100" />

See https://pillow.readthedocs.io/en/stable/installation.html for instructions on how to set it up.

**Comment by missionfloyd** [comment]
I'm not using `ImageFont.Layout.BASIC` and I already have libraqm, libfreetype, libharfbuzz, and libfribidi installed.
```console
pi@pizero:~/tests $ apt list libraqm0 libfreetype6 libharfbuzz0b libfribidi0
Listing... Done
libfreetype6/stable,now 2.10.4+dfsg-1+deb11u1 armhf [installed,automatic]
libfribidi0/stable,now 1.0.8-2+deb11u1 armhf [installed]
libharfbuzz0b/stable,now 2.7.4-1 armhf [installed,automatic]
libraqm0/stable,now 0.7.0-4 armhf [installed]
```

**Comment by radarhere** [comment]
How did you install Pillow? If you run the following code, what result do you get?
```pycon
>>> from PIL import features
>>> features.check_feature("raqm")
True
```

**Comment by missionfloyd** [comment]
`pip install pillow`. That returns False.

**Comment by radarhere** [comment]
Ok, RAQM support is indeed not working. I see you are running a Raspberry Pi Zero, so this sounds similar to #6023. The conclusion in that issue was there was a problem with the pre-build wheel being downloaded from piwheels. The solution was to install Pillow from source.

Could you try `pip install -U --force-reinstall Pillow==9.5.0 --no-binary :all:`? You will find more information at https://pillow.readthedocs.io/en/stable/installation.html#building-from-source

**Comment by missionfloyd** [comment]
That worked. The instructions are a little outdated, I had to use `libjpeg8-dev` instead of `libjpeg8-dev` and add `libraqm-dev`.

**Comment by radarhere** [comment]
> I had to use `libjpeg8-dev` instead of `libjpeg8-dev`

Would you like to clarify?

**Comment by missionfloyd** [comment]
Sorry, mistyped it. `libjpeg-dev`

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/issues/6023#issuecomment-1030776121 also mentioned `libjpeg-dev`.

Considering that we test installing on Linux regularly as part of our CIs (see [Ubuntu 22.04](https://github.com/python-pillow/docker-images/blob/main/ubuntu-22.04-jammy-amd64/Dockerfile) for example), I expect this isn't about being outdated, but simply about us not providing specific instructions for Raspberry Pi.

When you say that you had to install `libraqm-dev`, did `depends/install_raqm.sh` not work?

Is this issue resolved?

**Comment by missionfloyd** [comment]
I just used the ubuntu instructions, which should in theory be the same, since ubuntu and raspbian are both based on debian. When I installed the dependencies, apt complained about libjpeg8.

> did `depends/install_raqm.sh` not work?

I didn't even try that. Since `libraqm-dev` is available, it didn't seem necessary.

**Comment by octo-kumo** [comment]
```python
from PIL import Image, ImageDraw, ImageFont, features
print("raqm?", features.check_feature("raqm"))

text = "👨‍👩‍👧‍👦 👍🏽 👨‍💻 🇺🇸"

font = ImageFont.truetype("AppleColorEmoji-160px.ttf",
                          160, layout_engine=ImageFont.Layout.BASIC)
img = Image.new("RGB", (300, 750), "white")
draw = ImageDraw.Draw(img)
# zero-width joiner sequence
draw.text((10, 0), "🏴‍☠️", font=font, embedded_color=True)
draw.text((10, 150), "👩🏽", font=font, embedded_color=True)  # modifier sequence
draw.text((10, 300), "🇺🇸", font=font, embedded_color=True)  # flag sequence
draw.text((10, 450), "🏴󠁧󠁢󠁥󠁮󠁧󠁿", font=font, embedded_color=True)  # tag sequence
draw.text((10, 600), "1️⃣", font=font, embedded_color=True)  # keycap sequence
img.save("out.png")
```

```
❯ uv run sanity.py
raqm? True
```

<img width="300" height="750" alt="Image" src="https://github.com/user-attachments/assets/88f6d326-4aeb-441e-a404-361355b04761" />

Emoji rendering is broken even if raqm is enabled.

**Comment by radarhere** [comment]
Hi. You may have raqm installed, but you're telling Pillow not to use it by specifying `layout_engine=ImageFont.Layout.BASIC`.

If removing that doesn't fix your problem, would you mind sharing the output of `python3 -m PIL.report` (presuming you are using `python3` to run your code)? Also, where can I get a copy of AppleColorEmoji-160px.ttf? I have a macOS machine, but could only find AppleColorEmoji-160px.ttc.
