### ISSUE TITLE
Alpha channel is discarded when saving an animated PNG

### ISSUE THREAD

**Issue by gsingh93** [python-pillow/Pillow#7122]
### What did you do?

Created an animated PNG from RGBA images with transparent colors (non-zero alpha).

### What did you expect to happen?

The animated PNG should preserve the alpha channel of the individual images.

### What actually happened?

The alpha channel of all but the first image in the sequence is discarded. If the frames are of a static object fading in or out, then PIL then thinks that all of the frames are the same, and then discards them.

This bug also seems to occur with animated GIFs, but I'm not 100% sure the root cause is the same.

### What are your OS, Python and Pillow versions?

* OS: macOS 13.3.1
* Python: 3.11.3
* Pillow: 9.5.0

This script will create an APNG from 10 frames, with the alpha of the red square in the center increasing each frame: 
```python
#!/usr/bin/env python3

from PIL import Image, ImageDraw

images = []
for i in range(10):
    img = Image.new('RGBA', (300, 300), (255, 255, 255, 255))

    draw = ImageDraw.Draw(img)
    draw.rectangle((100, 100, 200, 200), fill=(255, 0, 0, i * 20))

    img.save(f'frame-{i}.png')
    images.append(img)

images[0].save(
    'test.png', save_all=True, append_images=images[1:], duration=100, loop=0
)
images[0].show()
```
Here is the PNG file with the transparency issue:
![test-incorrect](https://user-images.githubusercontent.com/1012677/235279655-a71bdda3-3d21-43d1-a736-bd71cdb9b561.png)

What happened here is that when the alpha channel was thrown away, all of the images in `append_images` are exactly the same and they get thrown away.

This is how I would expect the correct image to look:
![test-correct](https://user-images.githubusercontent.com/1012677/235279695-924e0b14-7125-4999-9b3a-9a116af12cf5.png)

**Comment by gsingh93** [comment]
I was able to fix this issue and generate the correct APNG file shown above by changing [this line](https://github.com/python-pillow/Pillow/blob/d1731b35fed4e69158d98bffbf5a415f3a4cec8d/src/PIL/PngImagePlugin.py#L1141) from:
```python
delta = ImageChops.subtract_modulo(
    im_frame.convert("RGB"), base_im.convert("RGB")
)
```
to:
```python
delta = ImageChops.subtract_modulo(
    im_frame.convert("RGBA"), base_im.convert("RGBA")
)
```

But I don't know if this is the correct fix, or whether it will break in some cases.

**Comment by radarhere** [comment]
Thanks for the head start. Your suggestion does break some of our existing tests, but I was able to add some further changes to fix them. I've created PR #7123 to resolve this.
