### ISSUE TITLE
Add the `unpackI16B_I16` unpacker to unpackers

### ISSUE THREAD

**Issue by FirefoxMetzger** [python-pillow/Pillow#7124]
I would like to propose to add a new unpacker to `Unpack.c` that can unpack big-endian 16-bit integer pixels (`I;16B`) into 16-bit integer pixels (`I;16`, I assume native or does it mean little-endian?).

At the moment, the following conversions are supported:

https://github.com/python-pillow/Pillow/blob/139acc45421ae56703b38fe6345860600d0c3060/src/libImaging/Unpack.c#L1761-L1773

and it would be really useful for me to also have `I;16B->I;16` as well. 

My use case is 16-bit PNGs, which I could then directly unpack into a 16-bit buffer. Currently, we can only unpack them into a 32-bit (`I`) buffer or a 16-bit big-endian buffer (`I;16B`), so I have to copy the data one more time from that buffer into `I;16`. With this small addition I could avoid/save this copy :)

**Comment by radarhere** [comment]
I've created PR #7125 to resolve this.

**Comment by FirefoxMetzger** [comment]
Awesome! Thanks for this @radarhere 🚀
