### ISSUE TITLE
Windows wheel doesn't have raqm support

### ISSUE THREAD

**Issue by missionfloyd** [python-pillow/Pillow#7126]
### What did you do?
```python
>>> from PIL import features
>>> features.check_feature("raqm")
```
Missing raqm support was thought to be an issue with piwheels (#6023, #7121) and maybe it's that as well, but this returns false on windows as well. Of the systems I've tried it on (Windows x64, Linux x64, Linux ARM), the only one that raqm works on when installed from a wheel is Linux x64.

Looking at the dependencies section of [build_prepare.py](https://github.com/python-pillow/Pillow/blob/main/winbuild/build_prepare.py), libraqm seems to be missing.

### What did you expect to happen?
```python
True
```
### What actually happened?
```python
False
```
### What are your OS, Python and Pillow versions?
* OS: Windows 10
* Python: 3.10.11
* Pillow: 9.5.0

**Comment by radarhere** [comment]
Under the 'Windows' section of https://pillow.readthedocs.io/en/stable/installation.html#basic-installation,
> Raqm support requires FriBiDi to be installed separately

Under https://pillow.readthedocs.io/en/stable/installation.html#external-libraries
> Pillow wheels since version 8.2.0 include a modified version of libraqm that loads libfribidi at runtime if it is installed. On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-link library search order (Microsoft Learn)](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-unpackaged-apps) (fribidi-0.dll or libfribidi-0.dll are also detected).

You can find the fribidi.dll under https://github.com/python-pillow/Pillow/actions/runs/4581728630 at https://github.com/python-pillow/Pillow/suites/11959728415/artifacts/627327930

**Comment by missionfloyd** [comment]
Tried that, still doesn't work.

**Comment by radarhere** [comment]
I'm guessing you once again used `pip install Pillow` to install Pillow?

Where did you place fribidi.dll?

**Comment by missionfloyd** [comment]
In the same folder I'm running python from.

**Comment by nulano** [comment]
> I put it in system32 and it worked.

I would not recommend that in case some other application has a conflict with it. Instead, I would recommend putting `fribidi.dll` next to the system Python executable.

> In the same folder I'm running python from.

Are you running Python from a virtual environment? The `python.exe` in the virtual environment is not the real Python executable, you have to put `fribidi.dll` next to the actual interpreter executable.

For example, my Python is installed here:

```
>>> import sys
>>> sys._base_executable
'C:\\Program Files\\Python311\\python.exe'
```

And I usually put `fribidi.dll` in `C:\\Program Files\\Python311\\fribidi.dll`.

The full list of supported directories is at https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#standard-search-order-for-unpackaged-apps, however, I think this may have been changed with Python 3.8 (I can't easily check right now) to just the directories at https://bugs.python.org/issue43173#msg386691.

> 4. Loaded-module list.

(I have never tested this, but you should be able to load `fribidi.dll` from any directory using `ctypes` before importing `PIL.ImageFont`)

> 7. The folder from which the application loaded.

(this is next to `sys._base_executable`, e.g. `C:\\Program Files\\Python311\\fribidi.dll`)

> 8. The system folder. Use the [GetSystemDirectory](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getsystemdirectorya) function to retrieve the path of this folder.

(`C:\Windows\System32`)

> 10. The Windows folder. Use the [GetWindowsDirectory](https://learn.microsoft.com/en-us/windows/win32/api/sysinfoapi/nf-sysinfoapi-getwindowsdirectorya) function to get the path of this folder.

(`C:\Windows`; possibly not supported with Python 3.8+)

> 11. The current folder.

(at the time `PIL.ImageFont` is first imported; possibly not supported with Python 3.8+)

> 12. The directories that are listed in the PATH environment variable. This doesn't include the per-application path specified by the App Paths registry key. The App Paths key isn't used when computing the DLL search path.

(possibly not supported with Python 3.8+)

> the user DLL search directories that get added by SetDllDirectory() and AddDllDirectory(), such as with os.add_dll_directory()

(possibly supported with Python 3.8+)

**Comment by Adventurerohan** [comment]
where is that fribidi.dll its deleted from everywhere pls help me to get that

**Comment by radarhere** [comment]
If you scroll to the bottom of https://github.com/python-pillow/Pillow/actions/runs/20888169833, one of the run of our CI for generating wheels, you will find that present as well.

**Comment by Adventurerohan** [comment]
Thanks you so much @radarhere for helping me 💕✌️
