### ISSUE TITLE
ImageGrab.grabclipboard() keeps unnecessary temporary files around

### ISSUE THREAD

**Issue by stephen-huan** [python-pillow/Pillow#7147]
### What did you do?

Call `PIL.ImageGrab.grabclipboard()` repeatedly. 

### What did you expect to happen?

A constant number of temp files to be created.

### What actually happened?

The number of files in `/tmp` keeps increasing.

If there not an actual image in the clipboard, e.g. only text, then
```shell
xclip -selection clipboard -target image/png -out
```
will error with the message
```text
Error: target image/png not available
```

while this error is caught on the latest Pillow (lines 146--148), the newly created tempfile is never removed.
https://github.com/python-pillow/Pillow/blob/ab3d0c071e60da904062d22f6b9a73e8fc6cdcb9/src/PIL/ImageGrab.py#L146-L151

This can cause tempfiles to accumulate with repeated calls of `grabclipboard()`.

I think `os.unlink(filepath)` should be called before `ChildProcessError` is raised to remove the now unnecessary file, i.e.
```python
        if err:
            os.unlink(filepath)
            msg = f"{args[0]} error: {err.strip().decode()}"
            raise ChildProcessError(msg)
        im = Image.open(filepath)
        im.load()
        os.unlink(filepath)
 ```

### What are your OS, Python and Pillow versions?

* OS: archlinux
* Python: 3.11.3
* Pillow: 9.5.0 (or commit [ab3d0c0](https://github.com/python-pillow/Pillow/commit/ab3d0c071e60da904062d22f6b9a73e8fc6cdcb9))

**Comment by stephen-huan** [comment]
with a bit of additional testing I think the suggested
```python
        if err:
            os.unlink(filepath)
            msg = f"{args[0]} error: {err.strip().decode()}"
            raise ChildProcessError(msg)
        im = Image.open(filepath)
        im.load()
        os.unlink(filepath)
```
should actually be something like
```python
        if err:
            os.unlink(filepath)
            msg = f"{args[0]} error: {err.strip().decode()}"
            raise ChildProcessError(msg)
        im = None
        try:
            im = Image.open(filepath)
            im.load()
        except UnidentifiedImageError:
            pass
        os.unlink(filepath)
```
as after the first paste `xclip` will no longer error with the message
```text
Error: target image/png not available
```
and simply write whatever text in the clipboard to `filepath`,
which causes an `UnidentifiedImageError`.

**Comment by radarhere** [comment]
> This also makes it more consistent with the behavior for Windows and macOS.

How so?

**Comment by stephen-huan** [comment]
In the sense that it should return `None` if there is not image data in the clipboard rather than erroring.

**Comment by radarhere** [comment]
I've created PR #7148 to remove the temporary file if an `ChildProcessError` occurs.

Regarding your second suggestion though, on macOS, it is returning `None` if the file is empty. On Windows, it is returning `None` if the image isn't PNG/DIB. What you're suggesting isn't either of those, and doesn't allow for any distinction between "this isn't image data" and "this is image data that Pillow can't successfully load". I don't think we should potentially silence Pillow failing to handle an image.

**Comment by stephen-huan** [comment]
A bit orthogonal to this discussion, the [latest stable documentation (9.5.0)](https://pillow.readthedocs.io/en/stable/reference/ImageGrab.html) for `grabclipboard()` is out of date.

It still says
> Only macOS and Windows are currently supported.

when Linux support was added in 9.4.0

Something like
https://github.com/python-pillow/Pillow/compare/main...stephen-huan:Pillow:patch-1
should be fine but of course the claim
> On Linux, an image, or None if the clipboard does not contain image data.

has not quite been substantiated yet.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/issues/7147#issue-1701870297
> If there not an actual image in the clipboard, e.g. only text, then
> 
> `xclip -selection clipboard -target image/png -out`
> will error with the message
> 
> `Error: target image/png not available`

https://github.com/python-pillow/Pillow/issues/7147#issuecomment-1540087205
> I just want to point out that even specifying -target image/png for xclip does not guarantee xclip does exactly one of
> (a) raises a ChildProcessError or
> (b) writes valid image data
> since it sometimes just writes the contents of the clipboard without erroring, e.g. plaintext.

In your first comment, you say that xclip doesn't print text data, and then the other comment you say that it does. Could you clarify? If you have found a way to get xclip to output text data from `xclip -selection clipboard -target image/png -out`, could you provide instructions? When I try, I get `Error: target image/png not available`.

**Comment by radarhere** [comment]
PR #7160 has been merged to update the `grabclipboard()` documentation to now state that Linux is supported. See https://pillow.readthedocs.io/en/latest/reference/ImageGrab.html#PIL.ImageGrab.grabclipboard

The stable documentation will be updated once the next version of Pillow is released.

**Comment by stephen-huan** [comment]
> In your first comment, you say that xclip doesn't print text data, and then the other comment you say that it does. Could you clarify? 

Sometimes it errors, sometimes it just prints text.

> If you have found a way to get xclip to output text data from `xclip -selection clipboard -target image/png -out`, could you provide instructions? When I try, I get `Error: target image/png not available`.

Sure,
1. Open a new shell
2. Run `xclip -selection clipboard -target image/png -out` with text copied
3. xclip errors with `Error: target image/png not available`
4. Copy text
5. Run the same command again
6. xclip prints the copied text out without error

This is completely deterministic for me. If step 4 is not performed, i.e., if 2 is ran over and over again, it always errors with the message. But once the clipboard is updated by copying something, then it won't error again until a new shell is started.

**Comment by radarhere** [comment]
> Looking at the code again, I'm not sure why a temporary file is even necessary in the first place.

I've created PR #7200 to no longer use a temporary file.

**Comment by stephen-huan** [comment]
> I've created PR https://github.com/python-pillow/Pillow/pull/7200 to no longer use a temporary file.

Thanks!

> I'm unable to replicate.

It may be a quirk on my setup then, perhaps I should have specified that I was using the [alacritty](https://github.com/alacritty/alacritty) terminal emulator.

One difference might be the terminal emulator, in the clip you selected the text `ubuntu@ubuntu`, right-clicked to copy, and then when you went to run the command, the highlighted text _stayed selected_. You then right-clicked to copy again and ran the same command. Could it be that the `PRIMARY` buffer didn't change? For example, you could try clicking on different text and then copying it. Or you could try seeing if you can replicate on alacritty. When I select something, there is no contextual menu, I have to copy with `<ctrl-c>`. Then when I run go to run the command, the selection will automatically clear, forcing a re-selection if something else should be copied  (see below).

https://github.com/python-pillow/Pillow/assets/20411956/575061f5-2655-439e-9308-7a18728082f8

**Comment by radarhere** [comment]
> And since the target is image/png, we can explicitly check whether the data is parsable as a PNG.

If you've found a situation where xclip will just print out whatever it has, isn't it possible that the user copied a JPEG file, and that the data xclip is outputting on the second run is JPEG data that Pillow would currently understand? In case, returning `None` just because it isn't PNG data would seem unhelpful.

I don't think there's any conceptual way to distinguish between "this isn't image data" and "this is image data that Pillow can't successfully load".
