### ISSUE TITLE
Help Pillow creator find job

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#7150]
Anyone mind if I advertise here for a new full time remote job? 

As you [may have noticed ](https://twitter.com/aclark4life/status/1512772315364438018)and has [since been confirmed](https://twitter.com/aclark4life/status/1654933561647017986), my ["science IT"](https://github.com/nimh-nif/nifscp2) job of 10 years at [NIMH](https://www.nimh.nih.gov/) is tentatively set to wrap ~Sep 15. As such, I need to find a new FT _remote_ job no later than then, else pay a terrible price! 

If no one minds, I will use this space to promote my availability around the globe, as well as maybe update the website with a link to this thread. If all goes well, we can close this issue no later than Sep 15! 😄 If anyone has any concerns, please let me know. Otherwise, here's one role I'm looking for.

**Full stack web developer**
- Django/React
- Jenkins CI
- AWS

**Here's my résumé**

- [alex-clark-resume.pdf](https://github.com/python-pillow/Pillow/files/11803225/alex-clark-resume.pdf)

Thank you for considering letting me do this here, and for any help you can provide in spreading the word. This applies to anyone reading this thread, in addition to the core team!

Thank you,

Alex

**Comment by hugovk** [comment]
Fine by me and good luck!

**Comment by aclark4life** [comment]
@hugovk Thanks! [Website updated](https://python-pillow.org). 🎉 

<img width="1024" alt="Screen Shot 2023-05-10 at 12 47 18 PM" src="https://github.com/python-pillow/Pillow/assets/72164/63054a39-96ea-4f7f-a778-af169a93bb71">

**Comment by aclark4life** [comment]
More attention to Pillow from me between now and mid-September, will keep an activity log here, starting with:

- Retro labeled all issues with either "Conda" or "Anaconda" in search results with "Anaconda" label.

<img width="865" alt="Screenshot 2023-05-19 at 7 14 26 AM" src="https://github.com/python-pillow/Pillow/assets/72164/9fdc6171-e9c7-4872-a5d6-b9d852f07d39">

Please remove label from false positives and… my general understanding is that we don't do much with these other than point to Anaconda… please correct me if I'm wrong.

**Comment by radarhere** [comment]
Sometimes they're Anaconda users who are reporting actual Pillow problems, like https://github.com/python-pillow/Pillow/issues/6015#issuecomment-1029205689 or https://github.com/python-pillow/Pillow/issues/6187

For https://github.com/python-pillow/Pillow/issues/5860#issuecomment-1003832804, I actually ended up helping to fix the problem in https://github.com/conda-forge/pillow-feedstock/pull/105#issuecomment-1004506649

But yes, sometimes, we do have to just redirect users as it isn't in our power to fix the problem - https://github.com/python-pillow/Pillow/issues/6495#issuecomment-1215744341

**Comment by goyalyashpal** [comment]
> And **here's my résumé**.
> 
> * [alex-clark-resume.pdf](https://github.com/python-pillow/Pillow/files/11436667/alex-clark-resume.pdf)

hey, will you mind if i share a criticism of the resume?

The table for "Skills" is split across pages of the pdf

This is likely as the pdf seems to be generated from webpage of some sort.

Possible fixes can be **transposing the table**, and **grouping some skills** - so that instead of one giant linear block, skills span multiple cells - which then can be arranged more freely. this will give you more freedom to utilise the space.

![image](https://github.com/python-pillow/Pillow/assets/19423063/1db6a6e1-52e1-4f31-bd9c-87a05d0f2598)

![image](https://github.com/python-pillow/Pillow/assets/19423063/21472c94-5d38-4b67-af12-ec6c8d3b43de)

**Comment by radarhere** [comment]
Perhaps relevant, perhaps not.

![Screenshot 2023-06-15 at 10 31 58 pm](https://github.com/python-pillow/Pillow/assets/3112309/a48828c2-b566-44bd-a8b5-28f5861de604)

**Comment by aclark4life** [comment]
@radarhere Thank you!

**Comment by aclark4life** [comment]
> > And **here's my résumé**.
> > 
> > * [alex-clark-resume.pdf](https://github.com/python-pillow/Pillow/files/11436667/alex-clark-resume.pdf)
> 
> hey, will you mind if i share a criticism of the resume?
> 
> The table for "Skills" is split across pages of the pdf
> 
> This is likely as the pdf seems to be generated from webpage of some sort.
> 
> Possible fixes can be **transposing the table**, and **grouping some skills** - so that instead of one giant linear block, skills span multiple cells - which then can be arranged more freely. this will give you more freedom to utilise the space.
> 
> ![image](https://user-images.githubusercontent.com/19423063/245061401-1db6a6e1-52e1-4f31-bd9c-87a05d0f2598.png)
> 
> ![image](https://user-images.githubusercontent.com/19423063/245063741-21472c94-5d38-4b67-af12-ec6c8d3b43de.png)

Thank you! Fixing …

**Comment by aclark4life** [comment]
And… coincidentally the website has just been updated, thank you @tfuxu! Works on mobile, much better "news" presentation, beautiful.

<img width="839" alt="Screenshot 2023-06-21 at 10 14 44 AM" src="https://github.com/python-pillow/Pillow/assets/72164/675718ea-ecba-400a-9e04-1f46fec3079b">

**Comment by aclark4life** [comment]
@hugovk @radarhere @wiredfool Do we have any experience with issues like this one in Pillow? I don't recall ever paying attention to dependency licensing … https://github.com/OpenImageIO/oiio/issues/3249#issuecomment-1580867603. Participating in https://github.com/OpenImageIO/oiio/wiki/Dev-Days-2023 and would love to pass on any "best practice" info we've acquired over the years, if anyone is able to summarize anything useful, without too much effort. Thanks

**Comment by wiredfool** [comment]
We've definitely done gymnastics to not ship GPL code, in the raqm/firbidi stack. It's ok to write the code to connect to it, we just can't actually ship the entire package without making our software GPL, which is more restrictive than our current license.  

Given that they're in Apache license land, I'd say that they've got similar constraints. Apache, MIT, BSD would be fine, LGPL is maybe and GPL is not. 

I don't know if there would be an issue shipping for us, but I know that I wouldn't be comfortable shipping a closed source application built with pillow and using the raqm/fribidi stack. 

(note, I don't remember which one is the GPL there, but I do remember the monkeying about with stub code so that if someone were to install the wheel and the library separately, it would work)

**Comment by aclark4life** [comment]
Thanks @wiredfool ! 

For anyone following along with my job search, here's an update. I decided that the overlapping of image processing and [content creation](https://www.aswf.io/) is _as cool_ if not more cool than the overlap of image processing and [medical imaging](https://github.com/nimh-nif/nifscp2).

As such, I [registered to participate in a sprint](https://wiki.aswf.io/display/PRWG/Dev+Days+2023) in which folks will be contributing to various projects used in the motion picture industry for visual and special effects.

Since I have an [accidental history with image processing in Python](https://www.youtube.com/watch?v=D0YwZhksDs8), I gravitated towards OpenImageIO and have already started working on a PR to provide wheels for this C++ image processing utility! E.g.

- https://github.com/aclark4life/oiio/pull/2

No idea if any of this will lead to any gainful employment, but it sure is fun! Cool to see [pyproject.toml](https://github.com/aclark4life/oiio/blob/python-wheels/pyproject.toml) creating a wheel with no setuptools in sight.

My [term date](https://twitter.com/aclark4life/status/1512772315364438018) is officially Oct 24 and rest assured, I'll be **closing this issue as soon as I find something even remotely close to "day job with benefits".**

Thanks all 🙏

**Comment by aclark4life** [comment]
Science IT job officially wrapped Oct 24, search continues!

**Comment by aclark4life** [comment]
Hah, new milestone: changed title of this issue 8 times within 80 seconds!

**Comment by aclark4life** [comment]
Thanks folks! Haven't found a job yet, but consulting work picked up so I'm going to focus on that for now. Thank you again to everyone who contributed to this thread and contacted me via email. 🙏
