### ISSUE TITLE
How to resize font object?

### ISSUE THREAD

**Issue by ahmed4end** [python-pillow/Pillow#7159]
after using ImageFont.truetype and assigning it to a variable in a project. It is essential to resize the font later, and I know I can make a new variable with a new font size, but it came to mind to first ask if there is a way to resize it.

**Comment by radarhere** [comment]
Not really.

The closest thing I can offer you is [`font_variant()`](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.FreeTypeFont.font_variant), which is just an easier way of creating a new font object with a different size.

```python
from PIL import ImageFont
font = ImageFont.truetype("Tests/fonts/DejaVuSans/DejaVuSans.ttf", 18)
print(font, font.size)

font2 = font.font_variant(size=24)
print(font2, font2.size)
```

**Comment by ahmed4end** [comment]
@radarhere  may i ask if this way better in after all performance than making a new object the normal way usingImageFont.truetype ?

**Comment by radarhere** [comment]
It would be a bit better, since it is not rereading the file from disk, but is instead retrieving the file contents from memory. That is the only difference though.
