### ISSUE TITLE
Why getbbox() returns None?

### ISSUE THREAD

**Issue by drunkwcodes** [python-pillow/Pillow#7162]
### What did you do?

I tried to use the following code to chop the image edges, but the `getbbox()` keeps returning `None`.

### What did you expect to happen?

I tried 9.5.0 and 8.4.0, it all returns None, but it worked and returned a tuple in older version which I can't tell.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.10.11
* Pillow: 9.5.0

```python
from PIL import Image, ImageChops


im1 = Image.open("001-0.png")
im = im1.convert(mode="RGBA")
im1.close()
bg = Image.new(im.mode, im.size, im.getpixel((0, 0)))
diff = ImageChops.difference(im, bg)
diff = ImageChops.add(diff, diff, 2.0, -100)


bbox = diff.getbbox()

assert bbox is not None
```
![001-0](https://github.com/python-pillow/Pillow/assets/36228443/1293650b-6c10-4ed6-ad51-7c603d8cfcb0)

**Comment by Yay295** [comment]
Because `diff` is fully transparent.

https://pillow.readthedocs.io/en/stable/releasenotes/7.1.0.html#if-present-only-use-alpha-channel-for-bounding-box

For images with an alpha channel, only the alpha channel is used when calculating the bounding box.

**Comment by nulano** [comment]
You may be interested in #4849 / #7123.

**Comment by drunkwcodes** [comment]
Thanks for your help. I will use RGB mode instead now and look forward to the PR being merged.
