### ISSUE TITLE
--global-option is deprecated

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#7167]
https://github.com/python-pillow/Pillow/actions/runs/4999985216/jobs/8956875899#step:7:23
> DEPRECATION: --build-option and --global-option are deprecated. pip 23.3 will enforce this behaviour change. A possible replacement is to use --config-settings. Discussion can be found at https://github.com/pypa/pip/issues/11859

While we could possibly just remove `make inplace`
https://github.com/python-pillow/Pillow/blob/599979caae111c22bd15f0103320bf74eb53d963/Makefile#L58-L59

and `--global-option="build_ext"`, we do still need something to replace our [build options](https://pillow.readthedocs.io/en/stable/installation.html#build-options).

The possible replacement of [`--config-settings`](https://peps.python.org/pep-0517/#config-settings) would involve switching from setuptools to build.

pip releases a new version [every 3 months](https://pip.pypa.io/en/stable/development/release-process/), so pip 23.3 is due out in October, [possibly before](https://github.com/pypa/pip/releases/tag/21.3) our scheduled October 15 release for Pillow 10.1. So it would be ideal to figure this out for Pillow 10.

**Comment by hugovk** [comment]
> would involve switching from setuptools to build.

Sounds like a good idea. I expect this would also unblock switching from setup.cfg/setup.py to pyproject.toml, even if that can be a follow up.



> pip releases a new version [every 3 months](https://pip.pypa.io/en/stable/development/release-process/), so pip 23.3 is due out in October, [possibly before](https://github.com/pypa/pip/releases/tag/21.3) our scheduled October 15 release for Pillow 10.1. So it would be ideal to figure this out for Pillow 10.

👍

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/7171 as a possible solution. See what you think
