### ISSUE TITLE
DLL import error when installing PIL in custom directory and then importing

### ISSUE THREAD

**Issue by mai1x9** [python-pillow/Pillow#7172]
PIL version:  9.4.0
OS: Windows 10.

I have installed PIL in custom directory named `contrib`, using
``` 
pip install PIL-t ./contrib
```
And from `test.py` which is outside `contrib` directory, I have imported as shown below by adding `contrib` to sys path.
```
import sys
import os
sys.path.append(os.path.join(os.path.dirname(__file__), "contrib" ))
from PIL import Image
# from contrib.PIL import Image
im = Image.open(r"image.jpg") 
  
# This method will show image in any image viewer 
im.show()
```
and it throws the error.
```
Traceback (most recent call last):
  File ".\test.py", line 15, in <module>
    from PIL import Image
  File ".\contrib\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The parameter is incorrect.
```
Even below import throws error.
```python
from contrib.PIL import Image
import contrib.PIL.Image
```
However, it is working when it is installed in default location `lib`. Am i missing something like adding dll part in windows or something like that??

**Comment by radarhere** [comment]
Quick note - I'm guessing that you didn't actually run `pip install PIL`, since that would attempt to install [PIL](https://pypi.org/project/PIL/). I'm guessing you instead ran `pip install Pillow`, which would install [Pillow](https://pypi.org/project/Pillow/), a fork of PIL. I think this is because you're writing these instructions from memory a bit, as you also later say that you created test.py, but the traceback shows libtest.py, and `from PIL. import Image` is incorrect syntax due to the aberrant period in the middle. That's fine, I understand. I primary want to dissuade people from running `pip install PIL`.

**Comment by mai1x9** [comment]
@radarhere thanks for quick reply, but I could see why the error has occured. In the PIL code, refer 
https://github.com/python-pillow/Pillow/blob/599979caae111c22bd15f0103320bf74eb53d963/src/PIL/ImageShow.py#L20

it is imported as `from PIL import Image` as a result it looks for `lib` folder and hence error. Changing to 
`from . import Image` has worked. Infact the files like `Imagegrab.py`, etc.. uses `from . import PIL`, hence they are working. Can you please confirm on this and assure I can modify the code from
`from PIL import Image` to `from . import Image`

**Comment by radarhere** [comment]
I wasn't able to replicate your problem on my macOS machine, so thanks for figuring out the solution.

If that solves your problem, sure, that's a perfectly valid change. I've created PR #7173 for this.

**Comment by mai1x9** [comment]
> I wasn't able to replicate your problem on my macOS machine, so thanks for figuring out the solution.
> 
> If that solves your problem, sure, that's a perfectly valid change. I've created PR #7173 for this.

thanks for the fix @radarhere. 



> Quick note - I'm guessing that you didn't actually run `pip install PIL`, since that would attempt to install [PIL](https://pypi.org/project/PIL/). I'm guessing you instead ran `pip install Pillow`, which would install [Pillow](https://pypi.org/project/Pillow/), a fork of PIL. I think this is because you're writing these instructions from memory a bit, as you also later say that you created test.py, but the traceback shows libtest.py, and `from PIL. import Image` is incorrect syntax due to the aberrant period in the middle. That's fine, I understand. I primary want to dissuade people from running `pip install PIL`.

My bad there were little typos in the code I posted. will edit properly.
