### ISSUE TITLE
Image.palette modified after calling show() or save()

### ISSUE THREAD

**Issue by zhyang-liu** [python-pillow/Pillow#718]
When an Image object is using palette, calling method Image.save() and Image.show() modifies Image.palette and  _Image.palette.save()_ throws an exception **ValueError: palette contains raw palette data**. The figure below shows the code and the exception. Please take a look at lines that commented out and the console output number **768**.

![1](https://cloud.githubusercontent.com/assets/2271442/3368571/1d979eaa-fb76-11e3-86e9-55129ad0299e.jpg)

After uncommenting the _show()_ method, the exception disappeared, and the length of palette.palette was still **768**.
![2](https://cloud.githubusercontent.com/assets/2271442/3368607/d6748992-fb76-11e3-8c82-79319fdea888.jpg)

But when I only use the _save()_ method and comment out the _show()_ method, the length will be 600, as I specified `colors=200` before.
![3](https://cloud.githubusercontent.com/assets/2271442/3368619/07b24b02-fb77-11e3-9d4f-e0e8a6ba7ba0.jpg)

I don't think a show() or save() method should modify the origin object, and I also think the palette of a converted palette picture should be able to save its palette directly, without saving or taking a glance at first.

**Comment by radarhere** [comment]
With regards to the saving of raw palette data, the same warning applies to the getcolor and tobytes method as well. Each time the code is as simple as -

    if self.rawmode:
        raise ValueError("palette contains raw palette data")

If the consensus is that any of these methods should be enabled for rawmode, and if there is confidence that the rawhide data isn't sufficiently different to cause problems, then it's just a matter of removing those lines.

**Comment by radarhere** [comment]
Since #1231 has been merged, the bug portion of this issue - the palette being modified - has been fixed. The remainder of this issue is about potentially changing the deliberate behaviour of the code - the ValueError raised when in rawmode.

**Comment by aclark4life** [comment]
Or alternatively can we close this and change the milestone to Never?
