### ISSUE TITLE
setup.py $LIB_ROOT dependency finding interface broken in 9.5.0

### ISSUE THREAD

**Issue by joshchngs** [python-pillow/Pillow#7182]
### What did you do?

I'm using Pillow as a transient dependency of matplotlib inside a Nix Flake which uses poetry2nix.
Pillow updated from 9.4.0 to 9.5.0 because of matplotlib's loose specification.

### What did you expect to happen?

Transparent update. Rebuild & move on.

### What actually happened?

Pillow 9.5.0 fails to find zlib when building.

### What are your OS, Python and Pillow versions?

* OS: macOS 13.3.1 (a) - but Nix is the more relevant point here
* Python: 3.11
* Pillow: 9.5.0

This is how Nix injects the correct paths to the native dependencies: https://github.com/NixOS/nixpkgs/blob/nixos-unstable/pkgs/development/python-modules/pillow/generic.nix#L59

So, Pillow's setup.py ends up looking like:
```
ZLIB_ROOT = "/nix/store/7n13ddp1m3340ls4x3zx9qkjhqidi08x-zlib-1.2.13/lib", "/nix/store/adgjjsasw9f8bvxwqfmv6fbssw1rdc08-zlib-1.2.13-dev/include"
```
 [setup.py L471](https://github.com/python-pillow/Pillow/blame/204590600c6a8c5246d0564d3312abd6e6b0ed70/setup.py#L471) effectively sets:

```
lib_root = "/nix/store/7n13ddp1m3340ls4x3zx9qkjhqidi08x-zlib-1.2.13/lib"
include_root = "/nix/store/adgjjsasw9f8bvxwqfmv6fbssw1rdc08-zlib-1.2.13-dev/include"
```

https://github.com/python-pillow/Pillow/commit/04cf5e2cfc5dc1676efd9f5c8d605ddfccb0f9ee broke this usage pattern, because in this case it will now iterate over each string's characters and add them as lib/include paths.

It looks to me that this bug is already resolved by https://github.com/python-pillow/Pillow/commit/fe4e52deacf1be96bb69758739d7fc88967a12e9 , which is not yet released. The commit message reads like a refactor, so @radarhere I'm not sure if you've spotted that there is actually a functional change?

So, if that commit goes out on the next release everything is fine, but right now 9.5.0 is broken with any system which assigns the (lib_root, include_root) tuple pattern to the ${LIB}_ROOT globals.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/commit/fe4e52deacf1be96bb69758739d7fc88967a12e9 was a part of #7069.

I think the functionality change you're requesting actually came in https://github.com/python-pillow/Pillow/pull/7069/commits/d94239ae3d21d8ae03f5120228dc8225faa99bac, an earlier part of that PR?

**Comment by radarhere** [comment]
I think that earlier commit, and the PR in general, make it clear that we are aware this was a functional change.

@joshchngs does that answer your question?

**Comment by joshchngs** [comment]
Yes, that makes sense. I didn't see the link to the PR. The blame for those lines just says "Rearranged code".

I don't have a question, I just wanted to flag that the current release is broken, at least for Nix users.

**Comment by radarhere** [comment]
Pillow 10.0.0 has been released with the fix.
