### ISSUE TITLE
Potential issue with bicubic resize

### ISSUE THREAD

**Issue by vfdev-5** [python-pillow/Pillow#7184]
### What did you do?

I resize a float32 image with range of (0, 255) with bicubic and bilinear modes. Then I cast float32 input into uint8 and resize it with the same configs. Next, I compare the results. I also do the same thing for images with reduced range (50, 200).
Here is a repro code to see result discrepancy between float vs uint8 dtypes:
```python
import numpy as np
import PIL
from PIL import Image


print("Pillow version: ", PIL.__version__)

def reduce_image_range(min, max):
    def wrapper(x):
        return (x % (max - min)) + min
    return wrapper


for interpolation in [Image.BICUBIC, Image.BILINEAR]:
    print("\n--- Interpolation mode: ", interpolation)
    for fn in (reduce_image_range(0, 255), reduce_image_range(50, 200)):

        input = np.arange(225 * 225, dtype="float32").reshape(225, 225)
        input = fn(input)
        input_ui8 = input.astype("uint8")

        pil_ui8 = Image.fromarray(input_ui8)
        pil_f32 = Image.fromarray(input)

        print(pil_ui8.size, pil_ui8.mode, input.min(), input.max())
        print(pil_f32.size, pil_f32.mode, input_ui8.min(), input_ui8.max())

        pil_out_ui8 = pil_ui8.resize([128, 128], interpolation)
        pil_out_f32 = pil_f32.resize([128, 128], interpolation)

        out_f32 = np.asarray(pil_out_f32)
        out_ui8 = np.asarray(pil_out_ui8).astype("float32")

        abs_diff = np.abs(out_f32 - out_ui8)
        print("Max Abs Error: ", abs_diff.max())
        print("Number of non-equal values: ", (abs_diff > 0).sum())
```
Output:
```
9.5.0

--- Interpolation mode:  3
(225, 225) L 0.0 254.0
(225, 225) F 0 254
Max Abs Error:  6.510681
Number of non-equal values:  16384
(225, 225) L 50.0 199.0
(225, 225) F 50 199
Max Abs Error:  0.9954376
Number of non-equal values:  16382

--- Interpolation mode:  2
(225, 225) L 0.0 254.0
(225, 225) F 0 254
Max Abs Error:  0.98968506
Number of non-equal values:  16359
(225, 225) L 50.0 199.0
(225, 225) F 50 199
Max Abs Error:  0.9948425
Number of non-equal values:  16384
```

### What did you expect to happen?

It is expected that rounding errors could lead to max abs errors around 1.

### What actually happened?

From bilinear mode test cases, we can see that for both types of ranges ((0, 255) and (50, 200)), the difference between resized images is around 1.

From bicubic mode test cases, we can see that for the images with reduced range (50, 200), max abs error is also around 1 but for full range images, max abs error is much larger, around 6.

The issue might be related to the dtype of intermediate buffer between horizontal and vertical passes. It may happen that in horizontal pass we could get a negative value that was saturated casted into uint8 and becomes 0. In the vertical pass, this incorrect value would propagate the error.

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.8.10
* Pillow: 9.5

Thanks and sorry if this was already reported.

**Comment by radarhere** [comment]
> The issue might be related to the dtype of intermediate buffer between horizontal and vertical passes. It may happen that in horizontal pass we could get a negative value that was saturated casted into uint8 and becomes 0.

My understanding of the problem is not what it could be, but am I right in thinking that https://github.com/python-pillow/Pillow/issues/4783#issuecomment-657401644 is related?
> IMHO, this is correct behaviour for float data. Lanzcos (and bicubic) have negative coeffs, and can therefore result in under- and over-shoot around high contrast edges (hence the 'sharper' property of the method). It should be up to the user to handle this in a way they see fit for their application (clipping or re-scaling). For uint data it's a different story: you have to clip during the computation in order to avoid wrap-around.

**Comment by NicolasHug** [comment]
> My understanding of the problem is not what it could be, but am I right in thinking that https://github.com/python-pillow/Pillow/issues/4783#issuecomment-657401644 is related?

You're correct @radarhere , both issues are the same: bicubic mode may lead to [final or intermediate] pixel values which can be outside of the [0, 255] (or [0, 1]) range. For float this is "mathematically correct" but might still be unexpected. For `uint8` types we have to clip anyway to avoid over/underflow. Clipping of intermediate values results in even bigger differences between the float and `uint8` implementations.

For context, @vfdev-5 and I are working on image resizing in PyTorch and @vfdev-5's experiments uncovered these differences.

**Comment by homm** [comment]
> It is expected that rounding errors could lead to max abs errors around 1.

It's not a rounding error.

> The issue might be related to the dtype of intermediate buffer between horizontal and vertical passes.

It not related only to intermediate, but also to dtype of the final pass. We obviously can't have values outside of 8 bit range.

> For float this is "mathematically correct" but might still be unexpected.

Not clear from the Issue, which behavior is expected? Do you need clipped values for float also?

**Comment by NicolasHug** [comment]
> It's not a rounding error.

I'm curious: apart from the clipping of `uint8` values happening during the first and second pass, what may be the reason for 1-off differences between the `float` and `uint8` implementations, if not rounding errors?

> Not clear from the Issue, which behavior is expected? Do you need clipped values for float also?

Personally I don't have an expert opinion on this. I can only report that the current behaviour resulting in <0 or >1 values may be surprising, as also reported in https://github.com/python-pillow/Pillow/issues/4783. I can also imagine some users prefer the current behaviour and start complaining if you were to move forward with https://github.com/python-pillow/Pillow/pull/7201 - this is not a trivial decision.

**Comment by homm** [comment]
The subject of this issue is not a rounding error. 1-off differences between the float and uint8 is.

**Comment by NicolasHug** [comment]
To clarify, the subject of this issue is indeed about differences between float and uint8 implementations, but these can lead to differences much larger than 1. https://github.com/python-pillow/Pillow/issues/7184#issue-1726093926 reports max abs errors of ~6.

**Comment by radarhere** [comment]
> values which can be outside of the [0, 255] (or [0, 1]) range

This might just be a different way of thinking about it, but to be clear, [F mode](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#modes) has values much larger than one. `pil_f32.getpixel((0, 1))` is 225.

**Comment by homm** [comment]
I still can't get  it.

> **What did you expect to happen?**
It is expected that rounding errors could lead to max abs errors around 1.

What are you showing **is not rounding error**. It is int8 range limit. So, what did you actually expect to happen?

**Comment by NicolasHug** [comment]
>  It is expected that rounding errors could lead to max abs errors around 1.

I think this sentence means: "We know that rounding error may cause differences of about 1. But here, we're observing bigger differences, which rounding errors cannot explain. These bigger differences are likely due to the clipping happening in `uint8` implementation (and not in `float` implementation). When that clipping happens after the first horizontal pass, this leads to reasonably large differences in the output values, even if both pixel values (for `uint8` and `float` path) are both in the [0, 255] range."

**Comment by homm** [comment]
Ok, but the question is what did you expect to happen?

**Comment by vfdev-5** [comment]
> Ok, but the question is what did you expect to happen?

Seems like I missed few details about what I was expecting: **rounding + clip on float output to match ui8 output within +/-1 margin**:

```python
out_f32 = np.clip(np.round(np.asarray(pil_out_f32)), 0, 255)
out_ui8 = np.asarray(pil_out_ui8).astype("float32")

abs_diff = np.abs(out_f32 - out_ui8)
assert abs_diff.max() <= 1
```
simiiar to OpenCV (which does not perform antialiasing but it should not matter here).

Here is a repro code:
```python
import numpy as np
import cv2
import PIL
from PIL import Image

print("Pillow version: ", PIL.__version__)

interpolation = Image.BICUBIC

input = np.arange(255 * 255, dtype="float32").reshape(255, 255)
input = input % 256;
input_ui8 = input.astype("uint8")

# ----- Pillow

pil_ui8 = Image.fromarray(input_ui8)
pil_f32 = Image.fromarray(input)

pil_out_ui8 = pil_ui8.resize([224, 224], interpolation)
pil_out_f32 = pil_f32.resize([224, 224], interpolation)

out_f32 = np.clip(np.round(np.asarray(pil_out_f32)), 0, 255)
out_ui8 = np.asarray(pil_out_ui8).astype("float32")

abs_diff = np.abs(out_f32 - out_ui8)
print("Pillow: Max Abs Error f32 vs ui8: ", abs_diff.max())
print("Number of non-equal values: ", (abs_diff > 0).sum())

# ----- OpenCV

out_f32 = np.clip(np.round(cv2.resize(input, (224, 224), interpolation=cv2.INTER_CUBIC)), 0, 255)
out_ui8 = cv2.resize(input_ui8, (224, 224), interpolation=cv2.INTER_CUBIC).astype("float32")

abs_diff = np.abs(out_f32 - out_ui8)
print("OpenCV: Max Abs Error f32 vs ui8: ", abs_diff.max())
print("Number of non-equal values: ", (abs_diff > 0).sum())
```
Output:
```
Pillow version:  9.5.0

Pillow: Max Abs Error f32 vs ui8:  13.0
Number of non-equal values:  12061

OpenCV: Max Abs Error f32 vs ui8:  0.0
Number of non-equal values:  0
```

Checking OpenCV code, they seem to use weight's dtype (int) for `dst` for horizontal pass unlike Pillow (if understand correctly the code): 
https://github.com/opencv/opencv/blob/b522148bd960eaf34e6c4b3a1b33038b663deb96/modules/imgproc/src/resize.cpp#L1948-L1950 


Anyway, I opened this issue for a discussion purpose to get your opinion as Pillow is a reference for image resizing in torchvision/pytorch.

**Comment by homm** [comment]
> rounding + clip on float output to match ui8 output within +/-1 margin

Thanks, now I see the point.

Indeed, even if we are limited with uint8 input and output, we still can use higher-range intermediate buffer for the first resizing pass. Mathematically it would provide more correct result. Despite this fact, necessity of this is doubtful for the following reasons:

* Higher-range intermediate buffer will use more memory during resize. It will also affect performance. 
* Much more complex implementation. For now there is no suitable internal formats for such buffers.
* Impact is hardly noticeable on real images, and even less after compression with image codecs.

There is an example of probably the worst case which you can get with this effect.

```python
from PIL import Image

Image.open('issues7184.png')\
    .convert('L').resize((128, 72), Image.BICUBIC)\
    .save('issues7184.L.png')
Image.open('issues7184.png')\
    .convert('F').resize((128, 72), Image.BICUBIC)\
    .convert('L').save('issues7184.F.png')
```

Source:
![issues7184](https://github.com/python-pillow/Pillow/assets/128982/84cdc13a-7860-4eb7-85be-d0d9c3f43cb2)

L, F:
![issues7184 L](https://github.com/python-pillow/Pillow/assets/128982/77ed49fa-3de9-4498-b06a-6ae9de53789b) ![issues7184 F](https://github.com/python-pillow/Pillow/assets/128982/1f85fb3d-50da-48e3-b125-b7ee5a5cb143)

**Comment by vfdev-5** [comment]
Thanks for feedback! Essentially, we have similar thoughts on this topic: more complex code to get more correct value + possible perfs degradation may not worth the changes. 
In addition, we also didn't see any metrics regression with pretrained neural networks on the inference using images resized with uint8 dtype or resized with f32 dtype. So, it may be safe to keep the current behaviour.

I let you handle the issue as you usually do in the project: close as resolved or open for visibilty, etc
