### ISSUE TITLE
Make a specific text as bold or Pillow should support to use HTML tags in text

### ISSUE THREAD

**Issue by Hunnyjain7** [python-pillow/Pillow#7198]
How can I achieve the below text using pillow.

"We are pleased to offer you an Internship position as a 'bold tag open' Junior Frontend Web Developer '/bold tag closed' with ..."
It should look like below text in image.
"We are pleased to offer you an Internship position as a <b>Junior Frontend Web Developer</b> with ..."

I hope you can understand it I have a text to write in image but also want to make a specific text BOLD. How can I achieve it also if possible add support for that.

Thank you.

**Comment by radarhere** [comment]
Hi. For making just part of a text segment bold, see #6574

**Comment by Hunnyjain7** [comment]
Thank you so much,  it got a long and complicated way.. but it solves it.

**Comment by Hunnyjain7** [comment]
Hi, the provided approach is good enough but still doesn't solves the problem completely as I'm not always aware of which text to make bold it can be anything from the dynamic text. Hence if something specific can be provided like html <b></b> then it would be perfect to work.

**Comment by radarhere** [comment]
How about the following? It uses regular expressions to split up the text into the appropriate parts.
```python
import re
from PIL import Image, ImageDraw, ImageFont

font_size = 24
normal_font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial.ttf", font_size)
bold_font = ImageFont.truetype("/System/Library/Fonts/Supplemental/Arial Bold.ttf", font_size)

text = "We are pleased to offer you an Internship position as a <b>Junior Frontend Web Developer</b> with ..."

im = Image.new("RGB", (1050, 50), "white")
draw = ImageDraw.Draw(im)

x = y = 10
for i, part in enumerate(re.split('<\/?b>', text)):
	font = normal_font if i % 2 == 0 else bold_font
	draw.text((x, y), part, fill="#000", font=font)
	x += font.getlength(part)

im.show()
```
![tmpgafbcqv9](https://github.com/python-pillow/Pillow/assets/3112309/4babbd46-6acc-4a84-9e53-d69635d9cbfa)

**Comment by radarhere** [comment]
@Hunnyjain7 you liked my comment. Does that mean this is resolved?
