### ISSUE TITLE
Image.save(append_images) cropping using bg color instead of alpha

### ISSUE THREAD

**Issue by viotalJiplk** [python-pillow/Pillow#7207]
### What did you do?
I used `Image.save(append_images=[])` to generate gif but it cropped part of the image (got boundary box of the image wrong). It throws away alpha when preparing to add image and then it relies only on bg color, which does not work when the image has the same color as background.
 
### What are your OS, Python and Pillow versions?

* OS: Linux (Debian GNU/Linux 12 (bookworm) x86_64)
* Python: 3.11.2
* Pillow: 9.5.0

code:
```python
from PIL import Image, ImageDraw

with Image.open('testin3.png') as avatar:
    frames = []
    deformWidth = [-1, -2]
    deformHeight = [4, 3]
    width, height = 80, 80
    x, y = 112, 122

    for i in range(2):
        frame = Image.new("RGBA", (x, y), (0, 0, 0, 0))
        width = width - deformWidth[i]
        height = height - deformHeight[i]
        avatar = avatar.resize((width, height))
        avatar = avatar.convert("P", palette=Image.ADAPTIVE, colors=200).convert("RGBA")

        frame.paste(avatar, (x - width, y - height), avatar)
        frames.append(frame)

    frames[0].save(
        "testout.gif",
        save_all=True,
        append_images=frames[1:],
        duration=400,
        loop=0,
        transparency=0,
        disposal=2,
        optimize=False
    )
```
testin3.png: ![testin3](https://github.com/python-pillow/Pillow/assets/61029138/218a1890-65aa-4604-8da0-5fa8fcb09573)

testout.gif: ![testout](https://github.com/python-pillow/Pillow/assets/61029138/54a15cfe-7264-425d-950e-95d65fea0aa9)

It could be solved by [this](https://github.com/python-pillow/Pillow/issues/7122#issuecomment-1528526139).

**Comment by radarhere** [comment]
I find that if I remove `transparency=0` from your code, I get the following as the final image.

![testout](https://github.com/python-pillow/Pillow/assets/3112309/b9f133c3-2018-49a9-84fd-a2db8c4b4090)

**Comment by viotalJiplk** [comment]
sorry I oversimplified it:
```python
from PIL import Image, ImageDraw

def square_to_circle(image: Image.Image) -> Image.Image:
        width, height = image.size
        mask = Image.new("L", (width, height), 0)
        draw = ImageDraw.Draw(mask)
        draw.ellipse((0, 0, width, height), fill=255)
        alpha = image.getchannel("A")
        circle_alpha = Image.new("L", (width, height), 0)
        circle_alpha.paste(alpha, mask=mask)
        result = Image.new("RGBA", (width, height), (0, 0, 0, 0))
        result.paste(image, (0, 0), mask=circle_alpha)
        return result

with Image.open('testin3.png') as avatar:
    avatar = square_to_circle(avatar)
    frames = []
    deformWidth = [-1, -2, 1, 2, 1]
    deformHeight = [4, 3, 1, 1, -4]
    width, height = 80, 80
    x, y = 112, 122

    for i in range(5):
        frame = Image.new("RGBA", (x, y), (0, 0, 0, 0))
        width = width - deformWidth[i]
        height = height - deformHeight[i]
        avatar = avatar.resize((width, height))
        avatar = avatar.convert("P", palette=Image.ADAPTIVE, colors=200).convert("RGBA")

        frame.paste(avatar, (x - width, y - height), avatar)
        frames.append(frame)

    frames[0].save(
        "testout.gif",
        save_all=True,
        append_images=frames[1:],
        duration=400,
        loop=0,
        disposal=2,
        optimize=False
    )
```

**Comment by radarhere** [comment]
Thanks.

I think you're correct about the change that needs to be made, although obviously applied to GifImagePlugin, rather than ApngImagePlugin. I will probably prepare a commit for that in the next day or so.

If you'd like an immediate solution, you could just change the background color to avoid black transparency, so that it is not confused with the black circle - `frame = Image.new("RGBA", (x, y), (100, 0, 0, 0))`

**Comment by radarhere** [comment]
Ok, I've added a commit to #7123 to resolve this.
