### ISSUE TITLE
Saved image's ICC Profile is not recognized by Photoshop

### ISSUE THREAD

**Issue by martimpassos** [python-pillow/Pillow#7215]
### What did you do?
Saved a JPEG image with `icc_profile=image.info.get("icc_profile")`
### What did you expect to happen?
Saved image should retain the original image's ICC profile, which should be recognizable by consuming applications such as Photoshop
### What actually happened?
ICC profile is kept in the `Profile Description` tag, but not in the `ICC Profile Name` XMP tag . This causes Photoshop to not recognize and thus ignore the embedded profile. I wonder if I can use `getxmp()` and combine it with `image.info["exif"]` somehow?

[original image exiftool output](https://github.com/python-pillow/Pillow/files/11772868/original-exiftool.txt)
[processed image exiftool output](https://github.com/python-pillow/Pillow/files/11772872/023IND22-01-exiftool.txt)

### What are your OS, Python and Pillow versions?

* OS: happened both on Windows and MacOS
* Python: 3.9
* Pillow: 9.5.0

```python
region_image.save(
            path,
            quality="keep",
            icc_profile=image.info.get("icc_profile"),
            exif=image.info["exif"],
        )
```

**Comment by martimpassos** [comment]
![image](https://github.com/python-pillow/Pillow/assets/49573683/e704af94-7d96-4368-ae48-c803c7ae209d)

**Comment by martimpassos** [comment]
I tried setting some XMP tags manually with exiftool and still get the error/warning in Photoshop, not sure what else needs to be changed:
```
[XMP]           XMP Toolkit                     : Adobe XMP Core 9.0-c001 79.c0204b2
[XMP]           Color Mode                      : Grayscale
[XMP]           ICC Profile Name                : Phase One Gray G2.2
```

**Comment by radarhere** [comment]
Here is a somewhat awkward method to resave the XMP data. Let us know if this works for you.
```python
from PIL import Image
import struct
with Image.open("rgb.jpg") as im:
    extra = b""
    for segment, content in im.applist:
        if segment == "APP1":
            extra += b"\xFF\xE1" + struct.pack(">H", 2 + len(content)) + content
    im.save("out.jpg", icc_profile=im.info["icc_profile"], extra=extra)
```
