### ISSUE TITLE
Test coverage >= 90%

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#722]
I'm not sure where the cutoff is, but it would be nice to get test coverage high enough to change the coveralls icon from red to not red. Currently we're at 72%.

**Comment by radarhere** [comment]
The coveralls icon is now yellow, and says 80%!

**Comment by hugovk** [comment]
Great!

https://coveralls.io/builds/9892857 says 79.977%, rounded up to 80% for the badge.

One last push and we can up the target to green 90% :)

**Comment by hugovk** [comment]
https://coveralls.io/builds/10203543 now says 80.631%, rounded up to 81%!

![image](https://cloud.githubusercontent.com/assets/1324225/23106017/0dda807c-f6f0-11e6-9048-959de6dec4e8.png)

Let's push onwards and upwards to 90% for a green!

**Comment by radarhere** [comment]
As of #3637, we are now using the Codecov badge. Note that it does not have the same boundaries for the badge color. According to https://docs.codecov.io/docs/coverage-configuration, it will gradually transition from red at 70% to green at 100%.

**Comment by radarhere** [comment]
90%!
