### ISSUE TITLE
Is CFFI still needed?

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#7223]
The CFFI is only used in PyAccess as a replacement for the C implementation in Access.c/PixelAccess. This was done in #476 to improve performance when using PyPy (see performance profiling in #816). However, that was nine years ago, and the PyPy cpyext has been [greatly improved](https://www.pypy.org/posts/2018/09/inside-cpyext-why-emulating-cpython-c-8083064623681286567.html) since then. Is PyAccess still necessary for performance on PyPy, or can we go back to just using the C implementation?

**Comment by hugovk** [comment]
How does performance profiling look now with PyPy, with and without CFFI?

**Comment by radarhere** [comment]
Running Tests/bench_cffi_access.py,

PyPy3.9 on Windows - https://github.com/radarhere/Pillow/actions/runs/5343847790/jobs/9687477077#step:27:46
> PyAccess - get: breaking at 30 iterations, 0.343930 per iteration
> PyAccess - set: breaking at 32 iterations, 0.317073 per iteration
> C-api - get: breaking at 245 iterations, 0.040906 per iteration
> C-api - set: breaking at 259 iterations, 0.038629 per iteration

PyPy3.10 on Windows - https://github.com/radarhere/Pillow/actions/runs/5343847790/jobs/9687477221#step:27:46
> PyAccess - get: breaking at 36 iterations, 0.278341 per iteration
> PyAccess - set: breaking at 42 iterations, 0.243066 per iteration
> C-api - get: breaking at 208 iterations, 0.048108 per iteration
> C-api - set: breaking at 198 iterations, 0.050532 per iteration

PyPy3.9 on Ubuntu - https://github.com/radarhere/Pillow/actions/runs/5343847795/jobs/9687476737#step:8:63
> PyAccess - get: breaking at 58 iterations, 0.173087 per iteration
> PyAccess - set: breaking at 76 iterations, 0.132276 per iteration
> C-api - get: breaking at 187 iterations, 0.053598 per iteration
> C-api - set: breaking at 193 iterations, 0.052231 per iteration

PyPy3.10 on Ubuntu - https://github.com/radarhere/Pillow/actions/runs/5343847795/jobs/9687476573
> PyAccess - get: breaking at 63 iterations, 0.160498 per iteration
> PyAccess - set: breaking at 83 iterations, 0.121258 per iteration
> C-api - get: breaking at 197 iterations, 0.050895 per iteration
> C-api - set: breaking at 204 iterations, 0.050110 per iteration

So PyAccess is running 2-8 times faster than the C API.

**Comment by Yay295** [comment]
> So PyAccess is running 2-8 times faster than the C API.

Isn't that backwards? In the last test PyAccess took 0.12-0.16 seconds per iteration, while the C API took 0.05 seconds per iteration. So it looks like the C API is actually faster than PyAccess.

**Comment by wiredfool** [comment]
I'm fine with taking it out -- There were some somewhat janky hacks to make that work (the unsafe members in the c struct) so it would be nice to clean that all up. Assuming that the benchmarks are pointing the right way.

**Comment by radarhere** [comment]
I've created PR #7236 to stop using PyAccess, and deprecate it.
