### ISSUE TITLE
10.0.0: New Mach-O header is too large to relocate on py2app

### ISSUE THREAD

**Issue by MAKOMO** [python-pillow/Pillow#7250]
### What did you do?

Bundling my app with py2app on macOS which fails under Pillow 10.0.0 with above message while it works with 9.5.0

### What did you expect to happen?

A working app bundle

### What actually happened?

On relocating py2app complaint

```
ValueError: New Mach-O header is too large to relocate in '/Users/appveyor/projects/artisan/src/dist/Artisan.app/Contents/Resources/lib/python3.11/PIL/.dylibs/libwebp.7.dylib' (new size=1768, max size=1760, delta=40)
```
### What are your OS, Python and Pillow versions?

* OS: macOS
* Python: 3.11
* Pillow: 10.0.0

The author of py2app stated on similar issues

> ..in general this can be fixed upstream by adding `-Wl, headerpad_max_install_names` to the linker flags. This will increase padding in the Mach-O headers.

see https://github.com/ronaldoussoren/py2app/issues/219#issuecomment-1305142378

**Comment by radarhere** [comment]
What version of macOS and py2app are you using?

**Comment by MAKOMO** [comment]
- pip installed current py2app==0.28.6  (I am aware that a new major version is under development, but not released yet)
- macOS macos-bigsur 11.7.1 on appveyor 

I just triggered a build locally on Intel macOS 13.4.1 resulting in

```
ValueError: New Mach-O header is too large to relocate in '/Users/luther/Documents/Projects/Artisan/Releases/2.8.4/artisan-2.8.4/src/dist/Artisan.app/Contents/Resources/lib/python3.11/PIL/.dylibs/libwebp.7.dylib' (new size=1768, max size=1760, delta=40)
```

Again, downgrading to Pillow 9.5 suceeds.

Pillow is not imported directly but via the current pypip matplotlib.

It is difficult for me to come up with a small script to demonstrate the issue as this is happening on building a relatively large project. But if I can assist you with any experiment or further data, let me know.

**Comment by radarhere** [comment]
When I was able to reproduce this, I found that downgrading libwebp from 1.3.1 to 1.3.0 (reverting https://github.com/python-pillow/pillow-wheels/pull/392) fixed it.

Could you confirm is this wheel works for you as well? [Pillow-10.0.0-cp311-cp311-macosx_10_10_x86_64.whl.zip](https://github.com/python-pillow/Pillow/files/11936272/Pillow-10.0.0-cp311-cp311-macosx_10_10_x86_64.whl.zip)

**Comment by MAKOMO** [comment]
Yep, this one works for me.

**Comment by radarhere** [comment]
Thanks.

The last time this happened in #4001 with lcms2, in the end things started working again with a later version of lcms2. Maybe a similar thing will eventually happen with libwebp as well? I would hope that never-upgrading-libwebp again is not the ultimate solution here.

Looking for differences between libwebp 1.3.0 and 1.3.1, nothing jumps out at me from https://github.com/webmproject/libwebp/blob/main/NEWS.

I've posted over in py2app to see if they have any thoughts - https://github.com/ronaldoussoren/py2app/issues/258#issuecomment-1620063217

**Comment by radarhere** [comment]
It turns out that just adding `-Wl, headerpad_max_install_names` to the flags when compiling libwebp does indeed fix the problem.

I've created https://github.com/python-pillow/pillow-wheels/pull/394 to resolve this.

**Comment by radarhere** [comment]
If anyone else encounters this and would like fixed Pillow 10 wheels, [here you go](https://github.com/python-pillow/Pillow/files/12050908/wheels.zip).

**Comment by MAKOMO** [comment]
Why not update the macOS wheels on pypip?

**Comment by radarhere** [comment]
We could. I'm just concerned about the slippery slope of uploading-a-new-version-every-time-a-problem-is-found.

For example, I expect some people would like new wheels released as soon as a Python beta is released (#6365).

If many more users report this problem, it can certainly be considered again.

**Comment by MAKOMO** [comment]
Without updated pypip projects requirements.txt cannot be updated to version 10.0.0 and will stay on 9.x. Awaiting the release of 10.0.1..

**Comment by radarhere** [comment]
If you like, you leave a comment on #7195 and see if anyone else thinks we should upload new wheels.

**Comment by MAKOMO** [comment]
Done

**Comment by radarhere** [comment]
Pillow 10.0.1 has now been released, and the wheels for that include https://github.com/python-pillow/pillow-wheels/pull/394
