### ISSUE TITLE
On windows ，File not found error while using Image.open function

### ISSUE THREAD

**Issue by xiaotongniu** [python-pillow/Pillow#7252]
### What did you do?
When in python file  call `PIL.Image.open(relative_image_path)` not found error while using Image.open function:

```
File "pytorch\lib\site-packages\PIL\Image.py", line 3241, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory:
```

### What did you expect to happen?
can open image directly

### What actually happened?
Not found image

### What are your OS, Python and Pillow versions?
* OS: Windows 
* Python: 3.10
* Pillow: 9.5.0

### Temporary Solution
```python
import os
from PIL import Image

image_path = 'images\dl.png'

script_dir = os.path.dirname(__file__)
absolute_image_path = os.path.join(script_dir, image_path)

print("absolute_file_path", absolute_image_path)

input_image = Image.open(absolute_image_path)
```

**Comment by homm** [comment]
`__file__` is an path to the current executed file (where you are using `__file__`) constant, while any other relative files are always related to current working dir. Use `import os; print(os.getcwd())` to find current working dir.

**Comment by xiaotongniu** [comment]
On Windows，as following，failed happend
`
from PIL import Image
# load a image
input_image = Image.open('images/dl.png')`

File "pytorch\lib\site-packages\PIL\Image.py", line 3241, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory:

Print log on PIL\Image.py
`  
# C:\Users\.conda\envs\pytorch\Lib\site-packages\PIL\Image.py
def open(fp, mode="r", formats=None):
    if mode != "r":
        msg = f"bad mode {repr(mode)}"
        raise ValueError(msg)
    elif isinstance(fp, io.StringIO):
        msg = (
            "StringIO cannot be used to open an image. "
            "Binary data must be used instead."
        )
        raise ValueError(msg)

    if formats is None:
        formats = ID
    elif not isinstance(formats, (list, tuple)):
        msg = "formats must be a list or tuple"
        raise TypeError(msg)

    exclusive_fp = False
    filename = ""
    if isinstance(fp, Path):
        filename = str(fp.resolve())
        print("Path: ",Path)
        print("filename1: ",filename)

    elif is_path(fp):
        filename = fp
        print("filename2: ",filename)

    if filename:
        fp = builtins.open(filename, "rb")
        exclusive_fp = True
        print("filename3: ",filename)`

log:
filename2:  images/dl.png
Traceback (most recent call last):
  File "d:\test.py", line 27, in <module>
    input_image = Image.open('images/dl.png')
  File "C:\Users\.conda\envs\pytorch\lib\site-packages\PIL\Image.py", line 3240, in open
    fp = builtins.open(filename, "rb")
FileNotFoundError: [Errno 2] No such file or directory: 'images/dl.png'
