### ISSUE TITLE
Saved PIL image is not the same as the original image?

### ISSUE THREAD

**Issue by krishnasrikard** [python-pillow/Pillow#7261]
Code:
```python
from PIL import Image
import numpy as np

Original_Image = Image.open("examples/Image.jpg")
Original_Image_Array = np.asarray(Original_Image, dtype=np.uint8)

Write_PIL_Image = Image.fromarray(Original_Image_Array.astype('uint8'))
Write_PIL_Image.save('examples/New_Image.jpg')

PIL_Image = Image.open("examples/New_Image.jpg")
PIL_Image_Array = np.asarray(PIL_Image, dtype=np.uint8)

print (np.array_equal(PIL_Image_Array, Original_Image_Array))
```
Output:
```
False
```

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/issues/4686#issuecomment-643421525
> JPEG is a lossy image format, so the exact encoded or decoded pixel values can vary, depending on compression settings, the exact version of the underlying jpeg library, and other settings. It is meant to gradually throw away data that is unlikely to be noticed in photographic type images.
>
> If you require exact pixel perfect images, you need an image format that doesn't use lossy compression, such as PNG or TIFF (with a lossless compression method).

If I run your code with a PNG file, it passes.

**Comment by krishnasrikard** [comment]
Thank You. It is working for PNG files.
