### ISSUE TITLE
Pillow 10 always links against libxcb.so, even with --disable-xcb

### ISSUE THREAD

**Issue by vdboor** [python-pillow/Pillow#7263]
I'm compiling Pillow against mozjpeg.
For this to work, I'm building Pillow in my docker base image using the following command:

```
pip install --no-binary=Pillow Pillow --global-option="build_ext" --global-option="--disable-xcb"  Pillow
```

As of Pillow 10, this will still link against `libxcb.so`:

```
cd /usr/local/lib/python3.8/site-packages/
ldd *.so | grep libx
	libxcb.so.1 => /usr/lib/x86_64-linux-gnu/libxcb.so.1 (0x00007fed27dac000)
```

When running the same command against `Pillow<10', this linkage does not happen.

### What are your OS, Python and Pillow versions?

* OS: Debian (`python:3.8-buster` docker base image)
* Python: 3.8 and 3.10
* Pillow: 10

When installing this package in a runtime image that doesn't have libxb.so, importing `PIL.Image` will fail:

```Traceback:
/usr/local/lib/python3.8/importlib/__init__.py:127: in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
tests/test_jpeg.py:5: in <module>
    from PIL import Image
/usr/local/lib/python3.8/site-packages/PIL/Image.py:82: in <module>
    from . import _imaging as core
E   ImportError: libxcb.so.1: cannot open shared object file: No such file or directory
```

**Comment by radarhere** [comment]
Hi. `--global-option` is [currently deprecated in pip](https://discuss.python.org/t/announcement-pip-23-1-release/25844), and soon to be removed, so with Pillow 10, we switched to config settings. You can read more about the new settings at https://pillow.readthedocs.io/en/stable/installation.html#build-options

For your case, I would suggest `pip install --no-binary=Pillow -C xcb=disable Pillow`

**Comment by vdboor** [comment]
Awesome, thanks!
