### ISSUE TITLE
Can Pillow handle CMYKA  5 channel TIFF format images?

### ISSUE THREAD

**Issue by sanbuphy** [python-pillow/Pillow#7267]
My idea is to convert a CMYKA image into an RGBA format image while simultaneously preserving the color profile information.

The format of this image is quite unusual. I tried using Image.open, but it couldn't read the image (it showed that the type was unrecognized). However, I was able to successfully read and convert the image into a NumPy array using the pytiff library. 

This allows me to perform limited processing on it, but it results in the loss of color profile information. 

If Image.open can successfully open the image, I can directly convert it to an RGBA image. What should I do or are there any other methods to achieve this? Thank you very much for your help.

### What are your OS, Python and Pillow versions?

* OS: ubuntu
* Python: 3.10
* Pillow:  10.0.0

None

**Comment by radarhere** [comment]
There isn't currently support for this, no. There is an open request for it in #3989
