### ISSUE TITLE
Cygwin CI not caching NumPy wheels

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#7281]
The Cygwin CI is rebuilding NumPy too often, taking 20-25 minutes and failing to cache it.

# CI config

The Cygwin CI has two jobs in the matrix:

https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/.github/workflows/test-cygwin.yml#L26-L27

We install a Cygwin-packaged NumPy:

https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/.github/workflows/test-cygwin.yml#L67

But then upgrade to the latest NumPy version:

https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/.github/workflows/test-cygwin.yml#L99-L102

NumPy doesn't offer Cygwin wheels, but that's not too bad, it's slow to build our own wheel the first time, but then we cache it for the next time.

We're caching, keyed on:

* `runner.os`
*  `matrix.python-minor-version`
* `hashFiles('.ci/install.sh')`

https://github.com/python-pillow/Pillow/blob/7a1e28404d692d4a7fed33dc67019a1d8c4bf9d9/.github/workflows/test-cygwin.yml#L79-L85

They keys mean we get a unique cache for this OS and Python version, and get a fresh cache when `.ci/install.sh` changes. So far, so good.

However, we should also either key on the NumPy version, or install without upgrading.

# 3.8

Looking at a recent build: https://github.com/python-pillow/Pillow/actions/runs/5500048265

The 3.8 build is fine. We first fetch the pip cache:

```
Run actions/cache@v3
Received 38542711 of 38542711 (100.0%), 100.2 MBs/sec
Cache Size: ~37 MB (38542711 B)
"C:\Program Files\Git\usr\bin\tar.exe" -xf D:/a/_temp/5617e746-c7fe-47bf-a[15](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043186#step:6:16)b-2188b6155326/cache.tzst -P -C D:/a/Pillow/Pillow --force-local --use-compress-program "zstd -d"
Cache restored successfully
Cache restored from key: Windows-cygwin-pip3.8-6925a01b5d239[16](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043186#step:6:17)c1d9340da4c3c4e1b4e9bae97f1e8dae779a25cbb0fd05f31
```

Then upgrade NumPy. 1.21.4 is already installed, then we upgrade to 1.24.4, but that's fine, there's a cached wheel (I guess it was built and cached from an earlier run):

```
Run python3 -m pip install -U numpy
Requirement already satisfied: numpy in /usr/lib/python3.8/site-packages (1.21.4)
Collecting numpy
  Using cached numpy-1.24.4-cp38-cp38-cygwin_3_4_[7](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043186#step:10:8)_x[8](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043186#step:10:9)6_64.whl
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.21.4
    Uninstalling numpy-1.21.4:
      Successfully uninstalled numpy-1.21.4
Successfully installed numpy-1.24.4
```

At the end of the run, it checks if we need to update the cache. No, nothing to upload, as no new wheel was built, all good:

```
Post job cleanup.
Cache hit occurred on the primary key Windows-cygwin-pip3.8-69[2](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043186#step:33:2)5a01b5d23916c1d9340da4c3c4e1b4e9bae97f1e8dae779a25cbb0fd05f31, not saving cache.
```

# 3.9

We have a similar flow for 3.9, but it's not working out the same: https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297

First fetch the cache, all good:

```
Run actions/cache@v3
Received 45937236 of 45937236 (100.0%), 63.0 MBs/sec
Cache Size: ~44 MB (45937236 B)
"C:\Program Files\Git\usr\bin\tar.exe" -xf D:/a/_temp/[15](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:6:16)a170a2-4530-43cd-89aa-1577436a6c5e/cache.tzst -P -C D:/a/Pillow/Pillow --force-local --use-compress-program "zstd -d"
Cache restored successfully
Cache restored from key: Windows-cygwin-pip3.9-6925a01b5d239[16](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:6:17)c1d9340da4c3c4e1b4e9bae97f1e8dae779a25cbb0fd05f31
```

Then install a different NumPy. Hmm, we already have 1.21.4, but upgrade to 1.25.1. We have no wheel in the cache so it's built from source, taking ~21 minutes:

```
Run python3 -m pip install -U numpy
Requirement already satisfied: numpy in /usr/lib/python3.9/site-packages (1.21.4)
Collecting numpy
  Downloading numpy-1.25.1.tar.gz (10.4 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 10.4/10.4 MB 53.9 MB/s eta 0:00:00
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: numpy
  Building wheel for numpy (pyproject.toml): started
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): still running...
  Building wheel for numpy (pyproject.toml): finished with status 'done'
  Created wheel for numpy: filename=numpy-1.25.1-cp39-cp39-cygwin_3_4_[7](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:10:8)_x[8](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:10:9)6_64.whl size=28376012 sha256=b[9](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:10:10)1a79302deea3a5330bef84cdc7c25266b91dc3d523d12edabae098de3f6707
  Stored in directory: /home/runneradmin/.cache/pip/wheels/0f/27/4d/422d845823770a343be7c7892d0c7fc213[10](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:10:11)03eef642ff72a5
Successfully built numpy
Installing collected packages: numpy
  Attempting uninstall: numpy
    Found existing installation: numpy 1.[21](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:10:22).4
    Uninstalling numpy-1.21.4:
      Successfully uninstalled numpy-1.21.4
Successfully installed numpy-1.[25](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:10:26).1
```

Well, that was slow, but we'll store it in the cache for next time? Nope:

```
Post job cleanup.
Cache hit occurred on the primary key Windows-cygwin-pip3.9-69[2](https://github.com/python-pillow/Pillow/actions/runs/5500048265/jobs/10027043297#step:33:2)5a01b5d23916c1d9340da4c3c4e1b4e9bae97f1e8dae779a25cbb0fd05f31, not saving cache.
```

No change to the cache keys, nothing to upload. We'll repeat the source build next time. And as Cygwin builds are also flakey at the moment, it might even fail after 20 minutes. 

# Options

A: We could pin the NumPy versions, make the version in the cache key, and manually update them at some point.
  * Or put the pinned version in a `requirements.txt`, put this file's hash in the cache key, and have Renovate update it from time to time.
    * Note that latest NumPy 1.25.1 only supports 3.9+, and NumPy 1.24.4 is the latest for 3.8. So we'd need separate files.
B: Don't upgrade the NumPy version, just use the `python3${{ matrix.python-minor-version }}-numpy` version

Any preferences? I'd prefer B if possible, it's simpler and much less config.

But is it important to test Cygwin against the latest available NumPy or is the pre-packaged one good enough?

**Comment by wiredfool** [comment]
I'm good with not upgrading numpy, I think using the standard for the particular environment will be fine, especially since the numpy integration is pretty minimal and limited to the array methods, and we're testing latest versions elsewhere.

**Comment by radarhere** [comment]
As a temporary solution, I deleted the Cygwin cache on main and reran the job. The latest NumPy is now in the cache, so running it again, 'Install a different NumPy' only takes 13s - https://github.com/python-pillow/Pillow/actions/runs/5543411513/jobs/10132968651

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/7286 to key on the NumPy version.
