### ISSUE TITLE
Is it possible to write text to simulate this effect?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7291]
Is it possible to write text to simulate this effect?
See upper row.
![image](https://github.com/python-pillow/Pillow/assets/41010669/aab07af1-7589-4e66-b5b5-db1bac630598)

**Comment by nissansz** [comment]
![image](https://github.com/python-pillow/Pillow/assets/41010669/c1ee06b8-8028-4a22-a5c3-e1c3a625baec)

I added some dots, it looks like similar now, except that the font seems different, any tool to recognize font?

**Comment by radarhere** [comment]
Pillow has nothing to identify fonts from an image.

If you Google, you will find sites that offer this feature, such as https://www.fontsquirrel.com/matcherator

**Comment by nissansz** [comment]
It seems not working for above website.

Do you know any tools on windows to convert png to ttf to create my own font?

**Comment by radarhere** [comment]
Googling, I find https://www.calligraphr.com/ suggested.

Closing, as it seems that found an answer to your initial question, and the subsequent questions are not about Pillow.

**Comment by nissansz** [comment]
An interesting phenomenon is below.
Large size has dots.
![image](https://github.com/python-pillow/Pillow/assets/41010669/d431b1ec-02a2-4815-8ce9-99e840e50442)

Zoom-out view has no dots, can I get such effect without dots?
![image](https://github.com/python-pillow/Pillow/assets/41010669/10857792-caa1-4b85-922a-845f4c9d9728)

**Comment by radarhere** [comment]
> Zoom-out view has no dots

There are still dots in your second image. It is unclear what you are trying to say.

> can I get such effect without dots?

I thought have thought the dots were the effect, so asking how to add dots without adding dots doesn't make sense to me.

**Comment by nissansz** [comment]
My target is to generate the zoom-out view as the effect at a size of 32px without zooming.

**Comment by radarhere** [comment]
It's not clear what you mean.

When asking whether Pillow is able to make a transformation, it would be helpful if you could provide 'before' and 'after' images.

**Comment by nissansz** [comment]
just a vague effect with white in characters

**Comment by nissansz** [comment]
How about below effect?

![image](https://github.com/python-pillow/Pillow/assets/41010669/63ced1c0-5646-42e8-a42f-398b0ecc99b7)

**Comment by radarhere** [comment]
Without a 'before' and 'after' version, it's too hard to figure out which possible changes you are interested in, and which you aren't. We don't know what is naturally a part of the font, and what isn't.

Looking at that image, it is possible that you want
- random black pixels on an image
- random white pixels on letters
- some letters to be filled with mostly white. Or maybe text stroking?
- something else entirely, if the font doesn't naturally look like that

**Comment by nissansz** [comment]
How to implmement below?

random black pixels on an image
random white pixels on letters
some letters to be filled with mostly white. Or maybe text stroking?

**Comment by radarhere** [comment]
Here is text, where some pixels are randomly flipped from black to white and vice versa.
```python
import random
from PIL import Image, ImageDraw, ImageFont
im = Image.new("L", (100, 60), 255)
draw = ImageDraw.Draw(im)
font = ImageFont.load_default(size=48)
draw.text((0, 0), "Test", font=font)

for y in range(im.height):
	for x in range(im.width):
		if random.randint(0, 10) == 0:
			im.putpixel((x, y), 255 - im.getpixel((x, y)))

im.save("out.png")
```
gives
![out](https://github.com/python-pillow/Pillow/assets/3112309/69a7f2b5-29dd-4019-8722-c7e76e03a2b7)

> some letters to be filled with mostly white

See an earlier question of yours, #7424

> Or maybe text stroking?

```python
from PIL import Image, ImageDraw, ImageFont
im = Image.new("L", (100, 60), 255)
draw = ImageDraw.Draw(im)
font = ImageFont.load_default(size=48)
draw.text((0, 0), "Test", font=font, fill=255, stroke_fill=0, stroke_width=2)
im.save("out.png")
```
gives
![out](https://github.com/python-pillow/Pillow/assets/3112309/2dc80326-da2d-4de4-b5b0-8ca97fceb7f1)

**Comment by nissansz** [comment]
Thank you.

**Comment by nissansz** [comment]
python pillow 读取灰度图
