### ISSUE TITLE
Is it possible to generate or simulate italic text for any font other than an original italic font?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7292]
Is it possible to generate or simulate italic text for any font other than an original italic font?

**Comment by radarhere** [comment]
What you're talking about is known as 'fake italics' - slanting text instead of using a properly designed italic font. Pillow doesn't offer that functionality, no, and I'm unable to find anything that says that FreeType supports it.

Unless you're talking about [variation fonts](https://learn.microsoft.com/en-us/typography/opentype/spec/otvaroverview), where multiple styles are contained within a single font file. That is supported by Pillow - https://pillow.readthedocs.io/en/stable/releasenotes/6.1.0.html#variation-fonts

**Comment by nissansz** [comment]
Check below effect, some words slanted to right, some to left. Some normal.
![image](https://github.com/python-pillow/Pillow/assets/41010669/0c6e67a9-ada9-4012-955e-0f06bd2424b0)

**Comment by radarhere** [comment]
I know what italics looks like, yes. I'm saying that no, Pillow can't generate italics if the font is not italic (unless you have a variable font), and I can't find any evidence to say that FreeType (a dependency that Pillow uses to render text) does either.

**Comment by nissansz** [comment]
Any method to transform, like wavy?

**Comment by nulano** [comment]
I found the following answer on StackOverflow: https://stackoverflow.com/a/51701378/1648883

The (now removed) `getsize` function there is used incorrectly, the following is a corrected version:

```python
def generate_text(text):
    fnt = ImageFont.truetype('arial.ttf', 72)
    mask = fnt.getmask(text, mode='1')
    img = Image.new('1', mask.size)
    img.putdata([x for x in mask])
    img = img.convert('RGB')
    return img

def add_border(img, width):
    new = Image.new('RGB', (img.width + 2 * width, img.height), (0, 0, 0))
    new.paste(img, (width, 0))
    return new

def shear(img, shear):
    shear = img.transform(img.size, Image.AFFINE, (1, shear, 0, 0, 1, 0))
    return shear

img = generate_text('test')
img = add_border(img, 200)
img = shear(img, 2)
```

**Comment by nissansz** [comment]
Thank you.
Which parameter to control direction and angle?

**Comment by radarhere** [comment]
The `shear` argument to `shear()`.

So `shear(img, 2)` with FreeMono.ttf gives
![2](https://github.com/python-pillow/Pillow/assets/3112309/c233febd-33b8-4513-bc15-ebfc0763d831)

`shear(img, 1)` gives
![1](https://github.com/python-pillow/Pillow/assets/3112309/fa784b79-e634-4d0e-b262-1a45b9da9edb)

`shear(img, -1)` gives
![minus1](https://github.com/python-pillow/Pillow/assets/3112309/f076e62b-1798-497c-a582-7fb257ddd0da)

**Comment by nissansz** [comment]
it looks good. Thank you.

**Comment by nissansz** [comment]
Is it possible to use ImageFont.FreeTypeFontFamily for above function?

**Comment by radarhere** [comment]
Oh, your problem is that `FreeTypeFontFamily` doesn't have `getmask`.

It should just be a matter of replacing
```python
fnt = ImageFont.truetype('arial.ttf', 72)
mask = fnt.getmask(text, mode='1')
```
with
```python
arial_fnt = ImageFont.truetype('arial.ttf', 72)
fnt = ImageFont.FreeTypeFontFamily(arial_fnt)
mask = fnt.getmask2(text, mode='1')[0]
```
in your code.

But again - you use #6926 at your own risk, as it has not been finished yet.

**Comment by nissansz** [comment]
I tried your code, there is below error.

   mask = fnt .getmask(text, mode='1')[0]
AttributeError: 'FreeTypeFontFamily' object has no attribute 'getmask'

**Comment by nulano** [comment]
> `getmask2`

**Comment by nissansz** [comment]
Ok. It works now. Thank you.

**Comment by nissansz** [comment]
I wonder what is the use for the mask?
can it be used to generate colorful text? Any use else?

**Comment by radarhere** [comment]
The mask was probably just used as a way of getting an image that was the exact size of the text.

You can use `getbbox()` instead to calculate a size for the image.

```python
def generate_text(text):
    arial_fnt = ImageFont.truetype('arial.ttf', 72)
    fnt = ImageFont.FreeTypeFontFamily(arial_fnt)
    right, bottom = fnt.getbbox(text)[2:]
    img = Image.new("RGB", (right, bottom))
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), text, fill="#f00", font=fnt)
    return img
```

**Comment by nissansz** [comment]
Thank you, is it possible to use white background instead of black too for this method?

**Comment by radarhere** [comment]
```python
from PIL import Image, ImageDraw, ImageFont

def generate_text(text):
    arial_fnt = ImageFont.truetype('arial.ttf', 72)
    fnt = ImageFont.FreeTypeFontFamily(arial_fnt)
    right, bottom = fnt.getbbox(text)[2:]
    img = Image.new("RGBA", (right, bottom))
    draw = ImageDraw.Draw(img)
    draw.text((0, 0), text, fill="#f00", font=fnt)
    return img

def add_border(img, width):
    new = Image.new('RGBA', (img.width + 2 * width, img.height))
    new.paste(img, (width, 0), img)
    return new

def shear(img, shear):
    shear = img.transform(img.size, Image.AFFINE, (1, shear, 0, 0, 1, 0))
    new = Image.new('RGB', (img.width, img.height), '#fff')
    new.paste(shear, (0, 0), shear)
    return new

img = generate_text('test')
img = add_border(img, 200)
img = shear(img, -1)
```

**Comment by nissansz** [comment]
Thank you.

**Comment by nissansz** [comment]
Can bold font be realized with similar method above? Any parameters to adjust?

**Comment by nissansz** [comment]
I also want to add background color for some random text, how to realize it with pillow?

![image](https://github.com/python-pillow/Pillow/assets/41010669/3879850a-f87f-4256-bd4e-af1f65d5b0da)

**Comment by radarhere** [comment]
> Can bold font be realized with similar method above? Any parameters to adjust?

Without a bold font or a variation font, no, Pillow can't do this, and I don't think Freetype can either.

**Comment by nissansz** [comment]
> > Can bold font be realized with similar method above? Any parameters to adjust?
> 
> Without a bold font or a variation font, no, Pillow can't do this, and I don't think Freetype can either.

Any fast method like opencv's erode, dilate to simulate bold?

**Comment by nissansz** [comment]
![image](https://github.com/python-pillow/Pillow/assets/41010669/41fa6b64-152b-4c5f-ab33-7b4a07638f28)

I used pixel color replace to simulate highlight, it may be slow? Any fast method?

**Comment by nissansz** [comment]
Below seems working, any improvements needed?

def shear(img, shear):
    shear = img.transform(img.size, Image.AFFINE, (1, shear, 0, 0, 1, 0))
    new = Image.new('RGB', (img.width, img.height), "#fff") # 白底

    new1 = Image.new('RGBA', (500, img.height), "#f00") # 白底
    new.paste(new1 , (0, 0), new1 )

    new.paste(shear, (0, 0), shear)
    return new

**Comment by nulano** [comment]
> Any fast method like opencv's erode, dilate to simulate bold?

Something like MaxFilter might work: 
https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.MaxFilter

**Comment by nulano** [comment]
> I also want to add background color for some random text, how to realize it with pillow?

You can add a background by using my answer on StackOverflow: https://stackoverflow.com/a/72302587/1648883

**Comment by nissansz** [comment]
thank you, will try
