### ISSUE TITLE
Enable writing I;16B images as PNG

### ISSUE THREAD

**Issue by FirefoxMetzger** [python-pillow/Pillow#7301]
While investigating an ImageIO issue concerning behavior on big-endian architectures I've noticed that pillow's PNG plugin currently doesn't allow writing 16-bit big-endian images to PNG. `I;16` is already supported, so I was wondering if it would be possible to add `I;16B` as well.

From what I can see, the only change needed to support this would be to add the line `"I;16B": ("I;16B", b"\x10\x00"),` to this dict:

https://github.com/python-pillow/Pillow/blob/3c5324b07c2ed98bc0ec94bd5c6a30f9c66e42fb/src/PIL/PngImagePlugin.py#L1035-L1051

With this change we would be able to do 16 bit round-trips on big-endian, i.e., we can decode the pixel data directly into a 16 bit big-endian buffer and then use that same buffer when encoding as PNG. This would improve performance and streamline working with native encoding on big-endian machines.

**Comment by radarhere** [comment]
I've created PR #7302 to resolve this.

**Comment by homm** [comment]
> This would improve performance and streamline working with native encoding on big-endian machines.

`I;16` is already native order for any machines, isn't it?

**Comment by FirefoxMetzger** [comment]
> I;16 is already native order for any machines, isn't it?

Yes, I always thought so as well. However, if you check the unpack function for `I;16` in `Unpack.c` it looks like `I;16` is treated as little-endian:

https://github.com/python-pillow/Pillow/blob/3c5324b07c2ed98bc0ec94bd5c6a30f9c66e42fb/src/libImaging/Unpack.c#L1152-L1160

I'm not sure if there is a platform-dependent macro missing or if this is intended though...
