### ISSUE TITLE
Filled up some of alpha area in animated gif

### ISSUE THREAD

**Issue by holawholaw** [python-pillow/Pillow#7308]
I've used the following code to create multiple animated gifs. They all turned out well except for one. There seems to be an issue where the transparent area gets filled automatically. I haven't been able to come up with a clear understanding of what's happening with this matter. Does anybody know how to fix it?

- Here are the original image sequences used to create the GIF.
![image](https://github.com/python-pillow/Pillow/assets/83199513/90c9e7e7-0f31-47a1-86da-a59f9514aae5)

- The GIF that was created by the code. the outcome is not what I wanted. The center area is filled with red instead of being transparent as I expected.
![aura_lv2](https://github.com/python-pillow/Pillow/assets/83199513/d7187d4b-ea49-45e1-ba99-10c63168dcf2)

- The code for generating gif
```
from PIL import Image
import os

main_folder = "myfolder"

for seq_folder in os.listdir(main_folder):
    images = []
    folder_path = os.path.join(main_folder, seq_folder)

    for file_name in sorted(os.listdir(folder_path)):
        if file_name.endswith('.png'):
            img_path = os.path.join(folder_path, file_name)
            img = Image.open(img_path)
            images.append(img)

    gif_name = seq_folder + '.gif'
    gif_path = os.path.join(main_folder, gif_name)
    
    images[0].save(gif_path, format='GIF', append_images=images[1:],
                   save_all=True, duration=100, loop=0, overwrite=True, disposal=2, transparency=0)
```

**Comment by Yay295** [comment]
Are the transparent areas of your images transparent red? They might be losing their alpha channel for some reason, so the transparent red is becoming just red.

**Comment by Yay295** [comment]
What happens if you don't set `transparency` to anything?

**Comment by holawholaw** [comment]
yes, those are transparent red.
You remind me to double-check the image itself; there really is very little transparent red.
Maybe 1-5% opacity in there so I can't be aware of it.
anyway, thx for your reply

**Comment by Yay295** [comment]
Did you mean to close this? Did you fix your issue?

**Comment by holawholaw** [comment]
> Did you mean to close this? Did you fix your issue?

Yup, fixed
