### ISSUE TITLE
Add capability to process CMYK palettes

### ISSUE THREAD

**Issue by pubpub-zz** [python-pillow/Pillow#7309]
### What did you do?
I'm using Pillow to add image extraction capability in pypdf. I'm facing some issues with images using some CMYK palettes.
However Pillow is currently not able to process them.

### What did you expect to happen?
Accept CMYK indexed images.

### What actually happened?
Exception `ValueError: unrecognized raw mode` is raised.

### What are your OS, Python and Pillow versions?

* OS: windows
* Python: 3.10.4
* Pillow: 10.0.0

test file: 
![test.png](https://github.com/python-pillow/Pillow/assets/4083478/ef23bff1-b184-4864-b139-3284cdf8bc18)

```python
from PIL using Image

img = Image.open("test.png")
img2.putpalette(b"\x00\x00\x00\xFB\x00\x00\x00\x00","CMYK")
```

**Comment by radarhere** [comment]
Hi. While I imagine you do know this, I still think it is good to minimise the spread of incorrect code - it should be `from PIL import Image`, not "using".

As noted in https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.putpalette
> rawmode – The raw mode of the palette. Either “RGB”, “RGBA”, or a mode that can be transformed to “RGB” (e.g. “R”, “BGR;15”, “RGBA;L”).

I've created PR #7310 to add this missing transformation (in Pillow development terms, an "unpacker") from CMYK to RGB.

With that, if I run your code, I get two RGB colors in the palette, (4, 4, 4) and (255, 255, 255), and the following image.
![out](https://github.com/python-pillow/Pillow/assets/3112309/ef263abc-0344-4b49-893a-4e1841453017)

**Comment by pubpub-zz** [comment]
@radarhere 
Very Impressed by your reactivity. 
Iooking forward to test it
