### ISSUE TITLE
RGBA image losing its transparency when saved as pdf

### ISSUE THREAD

**Issue by pubpub-zz** [python-pillow/Pillow#7312]
### What did you do?
convert an png to image to pdf or ~JPEG2000~
edit: 
   after checking with various  image viewer, I've observed that the issue could be linked with my original viewer(nomacs)
   In order to not bother any I will left on side JPEG2000 and carry on my investigations

### What did you expect to happen?

have the good alpha channel

### What actually happened?

alpha channel not correctly displayed in pdf  ~is not the good one~

### What are your OS, Python and Pillow versions?

* OS: windows 11
* Python:  3.10
* Pillow: 10.0
with this png
![tt](https://github.com/python-pillow/Pillow/assets/4083478/e054f4b7-dcbc-4173-ab28-e19e9b6d4fd9)

```python
from PIL import Image
img = Image.open("tt.png")
print("mode : ",img.mode)
img.save("tt.pdf")
img.save("tt.jp2")
img = Image.open("tt.jp2")
print("mode jp2 : ",img2.mode)
img.save("tt.jp2")
```
output
_mode : RGBA_
_mode jp2 : RGBA_

but the image in the PDF has lost its transparency
~same for the jpeg2000 image, although still reported as RGBA~

**Comment by homm** [comment]
I can't confirm JPEG2000. Your image is transparent after conversion.

**Comment by pubpub-zz** [comment]
@homm 
this is the pdf I'm getting: 
[tt.pdf](https://github.com/python-pillow/Pillow/files/12233871/tt.pdf)

**Comment by homm** [comment]
This is how your pdf is rendered to me. It's unclear to me if PDF really can be transparent. 

<img width="902" alt="Screenshot 2023-08-02 at 01 55 57" src="https://github.com/python-pillow/Pillow/assets/128982/3bedfe56-6446-4fac-9338-59ad1a0bd72d">

**Comment by radarhere** [comment]
I'm also unable to replicate the problem with either format. Are you sure that you are using Pillow 10.0.0, and not a version before 9.5.0?

**Comment by pubpub-zz** [comment]
I reinstalled it before to confirm the bug was on the latest version.
Actually it looks like the problem is also linked with the viewer:
https://github.com/mozilla/pdf.js/issues/5649#issuecomment-1597489448

Personally I checked all under windows with acrobat reader (black) sumatra (transparent) pdf.js( black and damaged) chrome (black)

**Comment by radarhere** [comment]
How did you install Pillow?

What version of OpenJPEG are you using?
```pycon
>>> from PIL import features
>>> features.version_codec("jpg_2000")
'2.5.0'
```

**Comment by homm** [comment]
> I am using Pillow 10.0.0 and getting the same incorrect results using the code above:

Why do you consider these results incorrect? I've tryed to convert second image to PDF using macOS Preview App, the results are identical:

<img width="1420" alt="Screenshot 2023-08-02 at 16 20 54" src="https://github.com/python-pillow/Pillow/assets/128982/ea2e6483-1fd3-4781-a9d3-8b66d28590c7">

**Comment by homm** [comment]
> but the PDFs generated using Pillow 10.0.0 

The file opened in the right window on my screenshot is your PDF [from the comment](https://github.com/python-pillow/Pillow/issues/7312#issuecomment-1661580046) which claimed was also generated using Pillow 10

**Comment by radarhere** [comment]
I've created PR #7316 to set SMaskInData to 1.

> I've removed ColorSpace to take into account

Could you explain this some more?

> remove ColorSpace and BitsPerComponents (to allow the extraction of data from the image)

What makes you think that the color inversion is a bug in pdf.js, but not the BitsPerComponent problem? Does "allow the extraction of data from the image" mean something special, or is that just another way of saying "appear correctly in a viewer"?

**Comment by pubpub-zz** [comment]
> I've created PR #7316 to set SMaskInData to 1.

👍 

> > I've removed ColorSpace to take into account
> Could you explain this some more?

This is an extract from Pdf 1.7 reference:
![image](https://github.com/python-pillow/Pillow/assets/4083478/b0bb9de1-7e00-4e2b-be58-154f8c90f09c)
(...)
![image](https://github.com/python-pillow/Pillow/assets/4083478/14aa7691-27e0-4e48-998b-a398eb4c0e63)

For the same reason we should ignore BitsPerComponents
![image](https://github.com/python-pillow/Pillow/assets/4083478/da3f7f7e-d197-4a50-9c6f-e36eaefd0dc0)


> > remove ColorSpace and BitsPerComponents (to allow the extraction of data from the image)
> 
> What makes you think that the color inversion is a bug in pdf.js, but not the BitsPerComponent problem? Does "allow the extraction of data from the image" mean something special, or is that just another way of saying "appear correctly in a viewer"?

I've tested a few set of PdfViewer( Acrobat / Sumatra / pdf.js / chrome) and the issue was observable in PDF.js.  previously this time of error was linked with Decode entry but setting the Decode entry was not improving that.

**Comment by radarhere** [comment]
Thanks. I've updated the PR to remove those properties.

I presume that is sufficient to fix the original problem here. 'Transparent_Image2' is also an RGBA image, so I think it should fix that as well.

**Comment by radarhere** [comment]
'Transparent_Image' is different, because it is not RGBA, but P.

I've created PR #7323. With it, running
```python
from PIL import Image
img = Image.open("transparent_image.png")
img.save("transparent_image.pdf")
```
gives
[transparent_image.pdf](https://github.com/python-pillow/Pillow/files/12269608/transparent_image.pdf)

This should clearly be an improvement, because the background is no longer green, but @mnmtz, let us know if you think that is fixed.

If that is all good, then everything in this issue should be resolved.
