### ISSUE TITLE
Gaussian/Box blur with different X and Y radius

### ISSUE THREAD

**Issue by Splendide-Imaginarius** [python-pillow/Pillow#7321]
### What did you do?

Call `ImageFilter.BoxBlur` or `ImageFilter.GaussianBlur` with the `radius` parameter set to a 2-tuple containing an X and Y radius.

### What did you expect to happen?

The blur operation should use different radii for the X and Y dimensions. If one of the dimensions is zero, then the blur should only be done in the other axis.

### What actually happened?

This is not supported, per documentation (the radius must be a single number).

### What are your OS, Python and Pillow versions?

* OS: Linux
* Python: 3.11
* Pillow: 9.5.0

### Example code

```python
# im is an image

# This works
im.filter(ImageFilter.GaussianBlur(32))

# This doesn't work
im.filter(ImageFilter.GaussianBlur((32, 16)))
```

### Other notes

It looks like there's already internal code for doing single-dimensional box blur; making the 2-dimensional blur functions (which are exposed to Python) use different radii per dimension should be pretty easy. See this code:

https://github.com/python-pillow/Pillow/blob/a5b025629023477ec62410ce77fd717c372d9fa2/src/libImaging/BoxBlur.c#L266-L281

I would probably be happy to send in a PR, if this is a feature that you would welcome -- let me know.

**Comment by homm** [comment]
Personally, I absolutely welcome for this feature.

**Comment by radarhere** [comment]
I've created PR #7336 to resolve this.

**Comment by Splendide-Imaginarius** [comment]
Nice, thank you for saving me the trouble @radarhere :)
