### ISSUE TITLE
No documented way to programmatically request single iteration of gif animation

### ISSUE THREAD

**Issue by jagerber48** [python-pillow/Pillow#7328]
### What did you do?

Generate a .gif file using `loop=1`. 

### What did you expect to happen?

I expected this to cause the .gif animation to play through once and then not repeat. 

### What actually happened?

On some gif viewers the gif played once, on others it played twice. 

### What are your OS, Python and Pillow versions?

* OS: Windows 11
* Python: 3.9
* Pillow: 9.1.1

### Discussion

See this issue which spells out the problem in more detail: https://github.com/python-pillow/Pillow/issues/4575

I was able to resolve my issue by omitting the `loop` argument from my gif `save` call altogether. In this case 1 iteration of the animation was reliably played on all gif players I tried. But how can I access the omitted argument behavior while still including the argument? Suppose I have code like:

```python
def save_images_to_gif(images, gif_path, tot_duration, loop):
    duration = tot_duration / len(images)
    images[0].save(gif_path, save_all=True, append_iamges=images[1:], duration=duration, loop=loop)
```

What argument can a user of this function pass in for `loop` to get the same behavior as if no `loop` argument was supplied to `save`? 0 doesn't work, 1 doesn't work, `None` doesn't work. I don't know of any argument that works and as far as I can tell there is no such argument in the documentation.

**Comment by Yay295** [comment]
There isn't one. The code just checks whether or not `loop` has been set at all.

https://github.com/python-pillow/Pillow/blob/c98a7994da83a416bfd0efc068bc7ebf5fc1d133/src/PIL/GifImagePlugin.py#L940-L950

**Comment by jagerber48** [comment]
Ok, thanks for the info and clarifying there is no way to do this. Would it be reasonable to request a way to be able to do this? For example using `None`, or some other sentinel, to realize this behavior?

**Comment by Yay295** [comment]
I think `None` currently raises an exception, right? If so, it could probably check that `loop` isn't `None` without breaking anyone's code.

**Comment by jagerber48** [comment]
Yes, if I pass `loop=None` I get `error: required argument is not an integer`.

**Comment by radarhere** [comment]
I've created PR #7329 to resolve this.
