### ISSUE TITLE
Using "hin_name_font1 = ImageFont.truetype("workspace\AyushmanCards\Bhaskar Normal.ttf", 20)", I'm getting error: cannot open resource

### ISSUE THREAD

**Issue by PrathamDubey06** [python-pillow/Pillow#7330]
I'm using jupyter notebook for faster execution of my code. When I was using VS Code everything was working fine but as soon as I run:
hin_name_font1 = ImageFont.truetype("workspace\AyushmanCards\Bhaskar Normal.ttf", 20) in jypyter notebook it shows error of cannot open resource.

**Comment by radarhere** [comment]
You closed this because you found the solution?
