### ISSUE TITLE
Docs about FLOAT32 confusing and/or misleading?

### ISSUE THREAD

**Issue by CGDogan** [python-pillow/Pillow#7333]
https://pillow.readthedocs.io/en/latest/handbook/concepts.html#concept-modes:

> 32-signed integer pixel has the range of INT32 and a 32-bit floating point pixel has the range of FLOAT32

The first part is correct but I'd expect that the second part says: 32-bit floating point pixel has the range of [0.0, 1.0]. Am I right? As you can see here, https://github.com/python-pillow/Pillow/issues/2856#issuecomment-976342701 0 gives black and 1 gives complete white

**Comment by CGDogan** [comment]
Opened pull request #7334

**Comment by wiredfool** [comment]
I don't think that's correct, float images can represent any float32 value per pixel. Geotiffs in particular will use the float value to represent a real-world value, which is then interpreted via some mapping to a visible image, or perhaps not if it's used for calculations.  

I think that the confusion is in the rendering for viewing (which is always going to be something like an 8 bit quantized RGB image)  and what process it goes through to get there. Your image process might convert a float on the range of [0,1] to black/white, or it may be a cyclical mapping, or whatever.

**Comment by radarhere** [comment]
For an example, you can see one of our test images - https://github.com/python-pillow/Pillow/blob/main/Tests/images/10ct_32bit_128.tiff
```python
from PIL import Image
im = Image.open("10ct_32bit_128.tiff")
print(im.getpixel((0, 2)))
```
gives
```
3.0820798873901367
```

If nothing else, you can see for yourself that you are able to store and retrieve values in F mode that are outside of 0-1
```pycon
>>> from PIL import Image
>>> im = Image.new("F", (1, 1))
>>> im.putpixel((0, 0), 10000)
>>> im.getpixel((0, 0))
10000.0
```

**Comment by CGDogan** [comment]
Hmm, when I run:

```py
from PIL import Image
import numpy as np
x = np.ones((100, 100), dtype='float32')
x[40:60, 40:60] = 0.0
x[90:100,90:100] = OURFLOAT
im = Image.fromarray(x, mode="F")
im.save("out.tiff")
```

I find that OURFLOAT is rounded to the nearest number in range [0,1]. Shouldn't this be documented? OURFLOAT = 1 and OURFLOAT = 10 produce the same image

**Comment by CGDogan** [comment]
Of course, it depends on the reader

**Comment by radarhere** [comment]
> I find that OURFLOAT is rounded to the nearest number in range [0,1]

I don't find this be the case.

```python
from PIL import Image
import numpy as np
x = np.ones((100, 100), dtype='float64')
x[40:60, 40:60] = 0.0
x[90:100,90:100] = 0.5
im = Image.fromarray(x)
im.save("out.tiff")
im = Image.open("out.tiff")
print(im.getpixel((95, 95)))
```
gives `0.5`

**Comment by CGDogan** [comment]
@radarhere All is well, I was surprised why Pillow allows floats outside the range 0 to 1 and the imageviewer I used would wrap them to 0 or 1, the closest boundary, hence I said "Pillow allows setting floats outside this range but it then saves them after wrapping!" But wrapping or refusing to show etc. is the characteristic of the reader. It does save those pixels.
