### ISSUE TITLE
libraqm-0.7.1 windows, where to download and how to install?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7337]
libraqm-0.7.1 windows, where to download and how to install?

https://www.lfd.uci.edu/~gohlke/pythonlibs/#pillow
this link expired already.

One computer can run pillow dev0.95 font family.
The other says, missing above libraqm.

**Comment by radarhere** [comment]
Hi. Would you be able to post the exact error message?

You can find libraqm-0.7.1 at https://github.com/HOST-Oman/libraqm/releases/tag/v0.7.1. The latest version is [0.10.1](https://github.com/HOST-Oman/libraqm/releases/tag/v0.10.1) though.

But libraqm may not be your problem exactly.

Under the 'Windows' section of https://pillow.readthedocs.io/en/stable/installation.html#basic-installation,
> Raqm support requires FriBiDi to be installed separately

Under https://pillow.readthedocs.io/en/stable/installation.html#external-libraries
> Pillow wheels since version 8.2.0 include a modified version of libraqm that loads libfribidi at runtime if it is installed. On Windows this requires compiling FriBiDi and installing fribidi.dll into a directory listed in the [Dynamic-link library search order (Microsoft Learn)](https://learn.microsoft.com/en-us/windows/win32/dlls/dynamic-link-library-search-order#search-order-for-unpackaged-apps) (fribidi-0.dll or libfribidi-0.dll are also detected).

If you do think you are missing fribidi, you can find the fribidi.dll at https://github.com/python-pillow/Pillow/actions/runs/5431167153, under the 'fribidi' link

**Comment by nissansz** [comment]
I downloaded it from csdn, and it works now.
