### ISSUE TITLE
Some alpha channel is discarded when saving an animated PNG

### ISSUE THREAD

**Issue by gucheng599** [python-pillow/Pillow#7346]
### What did you do?
composite each frame of the gif image with a watermark image

### What did you expect to happen?
The opacity will be displayed correctly for each frame of the image

### What actually happened?
The current phenomenon is ....
When each frame of the gif image is use `alpha_composite` with the watermark image, the opacity of the watermark image does not take effect. The opacity of the watermark image has always been 100%, even though I have previously modified the transparency of the watermark image.

### What are your OS, Python and Pillow versions?

* OS: windows10
* Python: 3.8.15
* Pillow: 10.0.0

```python
from PIL import Image


def set_image_opacity(im, opacity):
    """
    :param im: PIL.Image
    :param opacity: float; range: 0.0-1.0
    :return:
    """
    if opacity == 1.0:
        return im
    alpha_channel = im.split()[3]
    alpha_channel = alpha_channel.point(lambda i: i * opacity)
    im.putalpha(alpha_channel)
    return im


gif_image = Image.open(r"gif.gif")
wm_image = Image.open(r"test_wm.png")
# resize wm size
if wm_image.size != gif_image.size:
    wm_image = wm_image.resize(gif_image.size)
wm_image = wm_image.convert("RGBA")
wm_image = set_image_opacity(wm_image, 0.2)
# set gif attr
gif_loop = gif_image.info.get("loop", 0)
gif_duration = gif_image.info['duration']
frame_list = []
for i in range(0, gif_image.n_frames):
    gif_image.seek(i)
    frame_image = gif_image.convert("RGBA")
    new_image = Image.alpha_composite(frame_image, wm_image)
    new_image.save(f"frames/{i}.png")
    frame_list.append(new_image)

frame_list[0].save("output.gif", loop=gif_loop, duration=gif_duration, disposal=2, quality=100, optimize=False, lossless=True, save_all=True, append_images=frame_list[1:])

```
original image：
![gif](https://github.com/python-pillow/Pillow/assets/46436123/c3a160ba-18dc-4139-ac54-71ccaa00fd42)
watermark image:
![test_wm](https://github.com/python-pillow/Pillow/assets/46436123/2981a934-f590-4d6e-b736-28bd2791bb66)
result image:
![output](https://github.com/python-pillow/Pillow/assets/46436123/e28ddb8c-0a9c-47b5-9335-019acffea1fa)

frames:
![20230819180753](https://github.com/python-pillow/Pillow/assets/46436123/23a23a36-b11a-4c49-988f-a39a6de9f929)
The current phenomenon is that the opacity of the watermark image in the generated gif image is always 100%, but the opacity on each frame of the image is normal

My English is not very good. I hope you can understand what I mean. Thank you for taking the time to solve my problem. I have checked the relevant issues but cannot find the answer. I cannot confirm whether this is a PIL problem or my own problem.

[issue.zip](https://github.com/python-pillow/Pillow/files/12385547/issue.zip)

**Comment by radarhere** [comment]
If I understand you correctly, then you are happy with the GIF that is being created, but you do not like that 'test test test' is partly transparent in the PNGs that are being created?

Why not just remove the line `wm_image = set_image_opacity(wm_image, 0.2)`? Without it, this is what a 'frame' image looks like.
![4](https://github.com/python-pillow/Pillow/assets/3112309/5051ef13-50ab-41fb-93da-a4f9a95737d2)

**Comment by gucheng599** [comment]
> If I understand you correctly, then you are happy with the GIF that is being created, but you do not like that 'test test test' is partly transparent in the PNGs that are being created?
> 
> Why not just remove the line `wm_image = set_image_opacity(wm_image, 0.2)`? Without it, this is what a 'frame' image looks like. ![4](https://user-images.githubusercontent.com/3112309/261792668-5051ef13-50ab-41fb-93da-a4f9a95737d2.png)

Thank you for your answer.
My question is why `wm_image = set_image_opacity(wm_image, 0.2)` did not take effect
Even though I set a 20% opacity for the watermark image, the gif image generated after using `alpha_composite` still shows a 100% opacity
The "test test" on the left side of the generated gif image should be the 20% opacity I set,but it shows a 100% opacity

**Comment by gucheng599** [comment]
But, run `new_image.save(f"frames/{i}.png")` this code.
The image I saved, with the "test test" on its left side, is correctly displayed with a 20% opacity

**Comment by radarhere** [comment]
Oh. GIF images do not have partial opacity. This has nothing to do with Pillow, that is simply how GIFs are.

Part of the image might be fully transparent, but there is no such thing as partial transparency in GIFs.

**Comment by radarhere** [comment]
For a longer explanation, each frame in an animated GIF has, at most, 256 colors. The image is represented as a series of indexes from those 256 colors. So pixel 1 might be color 1, pixel 2 is color 2, pixel 3 is back to color 1 again, pixel 4 is color 3, and so on. Those colors are RGB.

One of those colors might be marked as being "transparent". So if we mark red as being transparent, the red in the image will disappear and instead become transparent.

That is just how GIFs are. https://www.w3.org/Graphics/GIF/spec-gif89a.txt is the last specification for GIF images. Here is how it describes setting which color is transparent
> viii) Transparency Index - The Transparency Index is such that when encountered, the corresponding pixel of the display device is not modified and processing goes on to the next pixel. The index is present if and only if the Transparency Flag is set to 1.

That's it. If this doesn't suit your purposes, you will have to pick another image format.

**Comment by gucheng599** [comment]
> Oh. GIF images do not have partial opacity. This has nothing to do with Pillow, that is simply how GIFs are.
> 
> Part of the image might be fully transparent, but there is no such thing as partial transparency in GIFs.

It turns out to be like this, Thank you for solving my doubts.
but, in Photoshop, it is possible to overlay layers and achieve partial layer transparency

**Comment by radarhere** [comment]
Whatever you can do in Photoshop, once you save an image as a GIF, there can only be full transparency or no transparency for a particular pixel. Not all image formats can do everything.

It might look like it is partially transparent if the colour is closer to white or grey, but it will still just be fully transparent or not transparent at all. Later frames might look partially transparent by slightly adjusting the solid colours of a previous frame, but it will still not be partially transparent compared to whatever is behind the image.

**Comment by gucheng599** [comment]
> Whatever you can do in Photoshop, once you save an image as a GIF, there can only be full transparency or no transparency for a particular pixel. Not all image formats can do everything.
> 
> It might look like it is partially transparent if the colour is closer to white or grey, but it will still just be fully transparent or not transparent at all. Later frames might look partially transparent by slightly adjusting the solid colours of a previous frame, but it will still not be partially transparent compared to whatever is behind the image.

Okay, I understand. Thank you again for your answer. You can close this question now
