### ISSUE TITLE
Unidentified Image File error 

### ISSUE THREAD

**Issue by Intenzi** [python-pillow/Pillow#7349]
### What did you do?
I tried opening a certain few image files via pillow from an assets list

### What did you expect to happen?
I expected the images to open normally as they've done for the rest of the sprites.

### What actually happened?
I received an error 

### What are your OS, Python and Pillow versions?

* OS: Windows 11 and on Ubuntu as well
* Python: 3.10
* Pillow: 10.0

```python
img = Image.open(r'C:\Users\tenzi\Downloads\eternatus-eternamax.png')
Traceback (most recent call last):
  File "<pyshell#7>", line 1, in <module>
    img = Image.open(r'C:\Users\tenzi\Downloads\eternatus-eternamax.png')
  File "C:\Users\tenzi\AppData\Local\Programs\Python\Python38-32\lib\site-packages\PIL\Image.py", line 2967, in open
    raise UnidentifiedImageError(
PIL.UnidentifiedImageError: cannot identify image file 'C:\\Users\\tenzi\\Downloads\\eternatus-eternamax.png'
```

Same error for zacian-crowned.png
The error occurs on only a certain few images from a sprites list that I am utilising.

### What have I tried?
1. I have checked that the sprites do exist in the said folders and the filepath is valid both manually and by using os library.
2. I had initially utilised w-get to obtain the sprites and thus next assumed that the issue might be a corrupted file.
3. I have manually downloaded the image, utilised requests library to download the said image, and also utilised aiohttp to stream the image to bytes via its url and then try to open the image. All of the aforementioned tries, resulted in the same error. The last one results in an error of UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x00000142E799CFE0>

I am unable to figure the reason for the same.
Sprite urls (if needed):- 
a. https://play.pokemonshowdown.com/sprites/gen5-shiny/eternatus-eternamax.png
b. https://play.pokemonshowdown.com/sprites/gen5-shiny/zacian-crowned.png

I have attached the files that I have manually downloaded from the above links.
![eternatus-eternamax](https://github.com/python-pillow/Pillow/assets/62426443/155bcce6-611d-4940-b863-96d7f15f1edd)
![zacian-crowned](https://github.com/python-pillow/Pillow/assets/62426443/d61a87d2-56e8-4b14-a1d1-089b2376f0fe)

**Comment by Yay295** [comment]
I tried converting the first one using ImageMagick and it also failed with an error: `convert: iCCP: CRC error`.

Also those URLs don't work for me. Maybe you have to be logged in to see them?

**Comment by radarhere** [comment]
For both images, I find that
```python
from PIL import Image, ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
im = Image.open('1.png')
```
works.

Testing, it because of this
https://github.com/python-pillow/Pillow/blob/3ea8b54c00fb4aec64873c3e817019c85fbd217f/src/PIL/PngImagePlugin.py#L194-L201

So yes, like imageMagick alternatively says in "iCCP: CRC error", there is a checksum error in the images. The code I posted will allow you to skip over this and load the images anyway.

**Comment by Intenzi** [comment]
Hi radarhere, thankyou for the response! It does indeed solve my issue.
To: Yay295; I apologise, the links were incomplete. I have edited the links so that they direct towards the appropriate sprites.
