### ISSUE TITLE
HPND application to LGPL code donated to PIL project

### ISSUE THREAD

**Issue by georgthegreat** [python-pillow/Pillow#7350]
Hi!

I am trying to clarify license status for a certain pieces of Pillow code.
In particular, some code is marked 

```
Originally released under LGPL.  Graciously donated to PIL in
March 2009, for distribution under the standard PIL license
```

As it was donated to PIL project, I wonder is this donation is still applicable to the fork.

Thanks in advance for clarification!

**Comment by aclark4life** [comment]
If it was donated to PIL and re-licensed as HPND in 2009, and the fork came along in 2010, then I would say "yes" it is applicable to the fork because the fork has maintained the HPND license. cc: @tieguy

**Comment by georgthegreat** [comment]
The problem is not about the license, but about the project.
The permission was granted to PIL, not to Pillow.

**Comment by homm** [comment]
It’s clearly articulated: “for distribution under the standard PIL license”. So any rules aplicable to another PIL code is aplicable to this code.

**Comment by tieguy** [comment]
Yeah, once it's under the public license that's generally for anyone, even
though the permission was granted by way of PIL.

Necessary disclaimer: I wasn't there, haven't looked at any paperwork, am
not PIL or pillow's attorney, etc.

**Comment by radarhere** [comment]
@georgthegreat has that sufficiently answered your question?

**Comment by georgthegreat** [comment]
Well, I am not a lawyer, but these answers look like a strong position to me.
