### ISSUE TITLE
getpixel() should work with list of length 2

### ISSUE THREAD

**Issue by cipri-tom** [python-pillow/Pillow#7352]
### What did you do?
`img.getpixel([473, 653])`

### What did you expect to happen?
the pixel at that position is returned

### What actually happened?
An unexpected error message: `TypeError: argument must be sequence of length 2`

But the argument is a **sequence** of length 2

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 18.04
* Python: 3.9
* Pillow: '9.4.0'

```python
img = Image.open('test.png')
img.getpixel([473, 653])
```

**Comment by hugovk** [comment]
It's expecting a tuple not a list:

https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getpixel

https://github.com/python-pillow/Pillow/blob/643a52a2eb7bda9e809e4806ad14806b4f9c6fe2/src/_imaging.c#L1149-L1151
https://github.com/python-pillow/Pillow/blob/643a52a2eb7bda9e809e4806ad14806b4f9c6fe2/src/_imaging.c#L1183-L1185

**Comment by homm** [comment]
> It's expecting a tuple not a list:

But the question is why it can't be a list? "argument must be sequence of length 2", list is also a sequence. So behavior or message should be changed.

**Comment by cipri-tom** [comment]
Exactly ! Thanks, @homm 

Of course, I would much prefer it it could take any sequence of 2 integers, so we could pass lists, numpy arrays, etc, as long as they have 2 integers. 

Would probably have been easier if it took 2 integer arguments, but I suppose there's no changing the interface now

**Comment by Yay295** [comment]
I think that could be done actually. Something like this:

```python
def getPixel(self, x, y=None):
    if y is None:
        xy = tuple(x)
    else:
        xy = (x, y)
```

**Comment by radarhere** [comment]
I've created PR #7355 to allow `img.getpixel([473, 653])`.

It does not allow `im.getpixel(473, 563)`. In a discussion about trying to clarify things after a confusing error message, it seems to me that "either an argument of sequence of length 2 or two arguments of single integer" is not a step towards clarity. But if someone else would like to create a PR for that change, they are free to do so and see it if receives approval from others.

**Comment by cipri-tom** [comment]
Thank you for such quick decision and acting !
