### ISSUE TITLE
Bug in QOI decoder leading to corrupted images

### ISSUE THREAD

**Issue by thatfuckingbird** [python-pillow/Pillow#7356]
### What did you do?

Loaded dice.qoi from the official test image set (https://qoiformat.org/qoi_test_images.zip).

### What did you expect to happen?

Image is not corrupted.

### What actually happened?

Image is corrupted.

### What are your OS, Python and Pillow versions?

* OS: doesn't matter
* Python: doesn't matter
* Pillow: all versions with QOI support

The problem is the faulty implementation of the QOI_OP_RGB operation here https://github.com/python-pillow/Pillow/blob/24606216e1e5931a8fe6f41acde9e7e67489905d/src/PIL/QoiImagePlugin.py#L58C10-L58C10
The implementation sets the alpha channel to 255, however, the QOI specification says it should use the previous alpha value.
Replacing that line with something like `value = self.fd.read(3) + o8(self._previous_pixel[3])` fixes the problem.

**Comment by radarhere** [comment]
I've created PR #7357 to resolve this.
