### ISSUE TITLE
Is it possible to imitate Advanced SubStation Alpha subtitle effect as below?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7365]
Is it possible to imitate Advanced SubStation Alpha (ASS) subtitle effect as below?

![image](https://github.com/python-pillow/Pillow/assets/41010669/a3bfdd16-09e3-423e-9eb1-710bdb8254b2)

**Comment by Yay295** [comment]
(note: "ass" stands for Advanced Substation Alpha. they are not saying the subtitle effect is bad.)

**Comment by hugovk** [comment]
Thanks, edited for clarity.

**Comment by nissansz** [comment]
Any code sample to imitate above ass subtitle?

**Comment by radarhere** [comment]
```python
from PIL import Image, ImageDraw, ImageFont

im = Image.open("Tests/images/hopper.png").resize((320, 320))
draw = ImageDraw.Draw(im)
font = ImageFont.truetype("Tests/fonts/FreeMono.ttf", 24)

draw.text((15, 250), "Text with blue stroke", "#fff", font, stroke_width=2, stroke_fill="#00008b")
draw.text((15, 280), "Text with grey stroke", "#fff", font, stroke_width=2, stroke_fill="#222")

im.save("out.png")
```
gives
![out](https://github.com/python-pillow/Pillow/assets/3112309/e3faa341-c424-4a4a-b732-4d451d1fb55e)

**Comment by nissansz** [comment]
Thank you.
