### ISSUE TITLE
How to imitate synthtiger effects for various deformations?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7367]
![image](https://github.com/python-pillow/Pillow/assets/41010669/909d16fc-a50a-4598-8d83-75b81f2f91dd)

**Comment by radarhere** [comment]
As with #7339, you're referring to https://github.com/clovaai/synthtiger

From what I can see, the images are
- skewed, rotated or maybe curved
- blurred
- letters are warped
- the words might have other characters added before and after
- there might be random rectangles of color behind latters
- the text might have a random color, although presumably you still want sufficient contrast to allow humans to be able to read the text

This is somewhat different than your previous questions. In #7360, you asked about underlines, and in #7365 you asked about stroke. Those were specific questions.

Here, you're asking how to replicate the functionality of an entire library?

**Comment by nissansz** [comment]
synthtiger is very slow, may be due to floodfill by cv.
I believe pure pillow is much faster if pillow is possible to achieve similar effects.

**Comment by radarhere** [comment]
See what you think of this simpler version.

```python
import random
from PIL import Image, ImageDraw, ImageFilter, ImageFont

# Start with a random word
text = random.choice([
  "random",
  "first",
  "second",
  "third",
  "fourth",
  "fifth",
  "sixth",
  "seventh",
  "eighth",
  "ninth",
  "tenth"
])

# Randomly choose between leaving the capitalisation alone,
# or making the first letter uppercase, or making the whole word uppercase
capitalization = random.randint(0, 2)
if capitalization == 1:
	text = text[0].upper() + text[1:]
elif capitalization == 2:
	text = text.upper()

# Add random characters before or after the text
characters = "{}@#$%^&*()+-/\:;,.'\"[]`~"
for number in range(random.randint(0, 2)):
	text = random.choice(characters) + text
for number in range(random.randint(0, 2)):
	text += random.choice(characters)

# Generate text from a random font
possible_font_paths = [
  "Tests/fonts/FreeMono.ttf",
  "Tests/fonts/OpenSansCondensed-LightItalic.ttf",
  "Tests/fonts/ArefRuqaa-Regular.ttf"
]
font_path = random.choice(possible_font_paths)
font = ImageFont.truetype(font_path, 36)
im = Image.new("RGBA", font.getbbox(text)[2:])
draw = ImageDraw.Draw(im)
draw.text((0, 0), text, "#fff", font)

# Rotate text by a random amount
im = im.rotate(random.randint(3, 10) * (1 if random.randint(0, 1) else -1), expand=True)

# Get a random background image
background_image_path = random.choice([
  "Tests/images/hopper.png",
  "Tests/images/test-card-lossless.jp2",
  "Tests/images/bc5_snorm.dds",
  "Tests/images/pil168.png"
])
final = Image.open(background_image_path).resize((im.size))
final.paste(im, (0, 0), im)

# Blur the final result by a random amount
filter = ImageFilter.GaussianBlur(0.5 + random.random() * 0.5)
final = final.filter(filter)

final.save("out.png")
```

Running this ten times, I get
![1](https://github.com/python-pillow/Pillow/assets/3112309/b1b6e46d-5c38-4906-8686-77241cfd98c0)
![2](https://github.com/python-pillow/Pillow/assets/3112309/a43c0580-1254-4877-a77d-9cfadccc72cd)
![3](https://github.com/python-pillow/Pillow/assets/3112309/e96f070d-d702-43a2-8c2e-a9c10f0eaa74)
![4](https://github.com/python-pillow/Pillow/assets/3112309/08d42431-aa2e-4305-8242-8d16905e038e)
![5](https://github.com/python-pillow/Pillow/assets/3112309/832bc36d-092a-4a77-9526-2527ddcf58fd)
![6](https://github.com/python-pillow/Pillow/assets/3112309/c311565d-a55c-4c26-ad7d-dbcd50c68bda)
![7](https://github.com/python-pillow/Pillow/assets/3112309/a5cad2dc-9116-4261-944b-6f8aea326424)
![8](https://github.com/python-pillow/Pillow/assets/3112309/8ae36599-4153-4f72-8c17-26bbc09620f6)
![9](https://github.com/python-pillow/Pillow/assets/3112309/9051cf03-6a5e-4441-af6a-f9e1b3432123)
![10](https://github.com/python-pillow/Pillow/assets/3112309/f3ff8271-ab65-4dd1-91a9-d07cf3d2ee65)

**Comment by nissansz** [comment]
Thank you for the sample code. It is fast.
Can add more blur effect? Like bleeding, small white pixels, burr edges, etc.

![image](https://github.com/python-pillow/Pillow/assets/41010669/f2b4c88e-ca19-4e6e-8de7-3bc77c579dea)

![image](https://github.com/python-pillow/Pillow/assets/41010669/ec1440e0-1e23-4272-9d0e-c6a5334003e8)

**Comment by radarhere** [comment]
You can see https://www.pythoninformer.com/python-libraries/pillow/imageops-deforming/ for an example of adding a wave to an image. You might be able to achieve the effect you want with that.

Here is a different variation on the second half of my earlier code. It cuts out small circles cut out, and moves individual pixels.

```python
# Generate text
font = ImageFont.truetype("Tests/fonts/AdobeVFPrototype.ttf", 72)
font.set_variation_by_name("Black")
im = Image.new("L", font.getbbox(text)[2:])
draw = ImageDraw.Draw(im)
draw.text((0, 0), text, 255, font)

# Draw circles that will be cut out of the text when pasting on the background
for i in range(random.randint(20, 50)):
	x = random.randint(0, im.width)
	y = random.randint(0, im.height)
	draw.ellipse((x-3, y-3, x+3, y+3), 0)

# Rotate text by a random amount
im = im.rotate(random.randint(3, 10) * (1 if random.randint(0, 1) else -1), resample=Image.Resampling.BICUBIC, expand=True)

# Get a random background image
background_image_path = random.choice([
  "Tests/images/hopper.png",
  "Tests/images/test-card-lossless.jp2",
  "Tests/images/bc5_snorm.dds",
  "Tests/images/pil168.png"
])
final = Image.open(background_image_path).resize((im.size))

# Shift pixels a random amount in a random direction
for x in range(final.width):
	for y in range(final.height):
		if not im.getpixel((x, y)):
			continue
		if x % 3 == 0 and y % 3 == 0:
			x += round(random.random() * 2 - 0.5)
			y += round(random.random() * 2 - 0.5)
			if x > final.width or y > final.height:
				continue
		final.putpixel((x, y), (255, 255, 255, 255))

# Blur the final result by a random amount
filter = ImageFilter.GaussianBlur(random.random())
final = final.filter(filter)
```

![1](https://github.com/python-pillow/Pillow/assets/3112309/6a90c1be-87c4-42be-8b9c-b319a273563e)
![2](https://github.com/python-pillow/Pillow/assets/3112309/b0547c07-3d75-4828-b694-7b269422847d)
![3](https://github.com/python-pillow/Pillow/assets/3112309/331a9f31-b77c-4273-9993-bb3d9dc56cd2)
![4](https://github.com/python-pillow/Pillow/assets/3112309/72cfabbc-474d-4bc8-bd74-53a9ca90c23e)
![5](https://github.com/python-pillow/Pillow/assets/3112309/bee5883d-d2f1-4755-ad41-53dc43b6ce35)

**Comment by nissansz** [comment]
Sometimes there is error for this line.            final.putpixel((x, y), (255, 255, 255, 255))
IndexError: image index out of range

Sometimes, effect as below.
![image](https://github.com/python-pillow/Pillow/assets/41010669/1c13cdc9-e8f7-4d97-abf2-434b58a4834e)

**Comment by radarhere** [comment]
> Sometimes there is error for this line. final.putpixel((x, y), (255, 255, 255, 255)) IndexError: image index out of range

Just replace `if x > final.width or y > final.height:` with `if x > final.width - 1 or y > final.height - 1:`

**Comment by nissansz** [comment]
Thank you. It is strange, my text becomes on top, and cannot be seen.
![image](https://github.com/python-pillow/Pillow/assets/41010669/fed232bd-f931-499f-b0a1-18530ffdd264)

**Comment by nissansz** [comment]
# im = Image.new("RGBA", font.getbbox(text)[2:])
    # draw = ImageDraw.Draw(im)
    # draw.text((0, 0), text, "#fff", font)
    #
    im = Image.new("L", font.getbbox(text)[2:])
    draw = ImageDraw.Draw(im)
    draw.text((0, 0), text, 255, font)

Replaced above code, and it looks fine.
![image](https://github.com/python-pillow/Pillow/assets/41010669/67836992-5fb9-44a0-a6fd-5c056e7edd03)

**Comment by radarhere** [comment]
Now that that works, is this issue resolved?

**Comment by nissansz** [comment]
Any more deformations?

**Comment by radarhere** [comment]
Here's a version using the code from https://www.pythoninformer.com/python-libraries/pillow/imageops-deforming/
```python
import math
import random
from PIL import Image, ImageDraw, ImageFilter, ImageFont, ImageOps

class WaveDeformer:

    def transform(self, x, y):
        y = y + 10*math.sin(x/self.d)
        return x, y

    def transform_rectangle(self, x0, y0, x1, y1):
        return (*self.transform(x0, y0),
                *self.transform(x0, y1),
                *self.transform(x1, y1),
                *self.transform(x1, y0),
                )

    def getmesh(self, img):
        self.d = random.randint(10, 40)
        self.w, self.h = img.size
        gridspace = 20

        target_grid = []
        for x in range(0, self.w, gridspace):
            for y in range(0, self.h, gridspace):
                target_grid.append((x, y, x + gridspace, y + gridspace))

        source_grid = [self.transform_rectangle(*rect) for rect in target_grid]

        return [t for t in zip(target_grid, source_grid)]

# Start with a random word
text = random.choice([
  "random",
  "first",
  "second",
  "third",
  "fourth",
  "fifth",
  "sixth",
  "seventh",
  "eighth",
  "ninth",
  "tenth"
])

# Randomly choose between leaving the capitalisation alone,
# or making the first letter uppercase, or making the whole word uppercase
capitalization = random.randint(0, 2)
if capitalization == 1:
	text = text[0].upper() + text[1:]
elif capitalization == 2:
	text = text.upper()

# Add random characters before or after the text
characters = "{}@#$%^&*()+-/\:;,.'\"[]`~"
for number in range(random.randint(0, 2)):
	text = random.choice(characters) + text
for number in range(random.randint(0, 2)):
	text += random.choice(characters)

# Generate text
font = ImageFont.truetype("Tests/fonts/AdobeVFPrototype.ttf", 72)
font.set_variation_by_name("Black")
im = Image.new("L", font.getbbox(text)[2:])
draw = ImageDraw.Draw(im)
draw.text((0, 0), text, "#fff", font)

# Rotate text by a random amount
im = im.rotate(random.randint(3, 10) * (1 if random.randint(0, 1) else -1), expand=True)

im = ImageOps.deform(im, WaveDeformer())

# Get a random background image
background_image_path = random.choice([
  "Tests/images/hopper.png",
  "Tests/images/test-card-lossless.jp2",
  "Tests/images/bc5_snorm.dds",
  "Tests/images/pil168.png"
])
final = Image.open(background_image_path).resize((im.size))
final.paste(im, (0, 0), im)

# Blur the final result by a random amount
filter = ImageFilter.GaussianBlur(0.5 + random.random() * 0.5)
final = final.filter(filter)

final.save("out.png")
```
![1](https://github.com/python-pillow/Pillow/assets/3112309/489e7be8-7aa3-482b-94f5-ec7ea7a25dfa)
![2](https://github.com/python-pillow/Pillow/assets/3112309/f75312db-106f-42f4-b5f4-d1f59c09bf73)
![3](https://github.com/python-pillow/Pillow/assets/3112309/634cbaa9-c3bd-4a4f-8b14-33cf4fddb144)
![4](https://github.com/python-pillow/Pillow/assets/3112309/2593bf7a-5f03-47c7-88f0-6b9485428dfa)
![5](https://github.com/python-pillow/Pillow/assets/3112309/ed2fdd3f-aa14-47ca-b480-ced1bdf69b83)
![6](https://github.com/python-pillow/Pillow/assets/3112309/15c17963-9544-45b0-8527-316c5f5e98d3)
![7](https://github.com/python-pillow/Pillow/assets/3112309/03755ee4-a64b-446d-b8d1-f2cd0ad5275c)

**Comment by nissansz** [comment]
Thank you. It looks good.
