### ISSUE TITLE
Is there any way to use Pillow to filter images? I want to extract characters with blue stroke, and remain characters only

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7369]
![image](https://github.com/python-pillow/Pillow/assets/41010669/c26e5319-cf04-43b6-9c91-0fefce7a21c7)

Finally, I want to get a clean image for ocr, which contains the character on black background only. Or white ground+black characters.
妈不让我告诉你 但我觉得你应该知道

**Comment by radarhere** [comment]
If I convert the image to grayscale, and then use [`point()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.point), the result seems ok.
```python
from PIL import Image
im = Image.open("input.png")
im.convert("L").point(lambda x: 255 if x > 230 else 0).save("out.png")
```
gives

![out](https://github.com/python-pillow/Pillow/assets/3112309/8c701839-f17f-4726-b00c-553083fad133)

**Comment by nissansz** [comment]
Above sample code works fine like cv2 for normal image.
But when there is similar small characters without blue stroke, the unneeded small character will be left. I want to remain only characters with blue stroke,

![image](https://github.com/python-pillow/Pillow/assets/41010669/93e132a0-368e-46c4-9f6a-a9f85f41bbdc)

**Comment by homm** [comment]
Try to apply this mask to result:


```python
from PIL import Image, ImageFilter, ImageDraw
im = Image.open('./subtitles.png').convert('RGB')
blue_mask = lambda r, g, b: (0, 0, 0) if 0.15 <= (b - (r + g) / 2) <= 0.25 else (1, 1, 1)
mask = im.filter(ImageFilter.Color3DLUT.generate(33, blue_mask))
ImageDraw.floodfill(mask, (0, 0), (0, 0, 0))
mask.save('mask.png')
```
![mask](https://github.com/python-pillow/Pillow/assets/128982/0f39857e-397b-436d-beeb-40c31843061c)

**Comment by nissansz** [comment]
Thank you. Some additional white areas are left. Any method to remove them?

![image](https://github.com/python-pillow/Pillow/assets/41010669/9ab4c059-b8a3-4bfb-8064-a2b50e324af4)

**Comment by homm** [comment]
I'm not suggesting you to use this as a result, I suggest to use this mask for clean [previous result](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1704742352) from lines outside of blue strokes

**Comment by nissansz** [comment]
Any other options?

**Comment by homm** [comment]
> Any other options?

I can do not suggest. But you didn't say why you need other options. Here is result from @radarhere method with my mask applied to filter extra white lines:

![result](https://github.com/python-pillow/Pillow/assets/128982/7679a721-8590-4b85-b7ab-f2bc126db6e7)

**Comment by nissansz** [comment]
How did you get the result? Please share full code?

I can only get below
![image](https://github.com/python-pillow/Pillow/assets/41010669/b504a526-1c4b-4c27-8b9d-042e22376af2)

**Comment by nissansz** [comment]
I can see your mask effect, but how to apply your mask to  @radarhere method

![image](https://github.com/python-pillow/Pillow/assets/41010669/f3228936-5973-4f38-a139-4b01b1c5dcb2)

**Comment by homm** [comment]
> Please share full code?

I shared all info how I get it

**Comment by nissansz** [comment]
I got your result with def darken_blend(bottom, top):
Thank you.

**Comment by nissansz** [comment]
Effect seems not good for other images.
![image](https://github.com/python-pillow/Pillow/assets/41010669/1aac8dea-300a-4552-b678-7e6d27d5cdbe)

![image](https://github.com/python-pillow/Pillow/assets/41010669/5bb11192-ef35-4957-a646-0c138a898860)

**Comment by homm** [comment]
Effect is very good if you try to spend some time to tune it for your data.

Source:
![subtitles](https://github.com/python-pillow/Pillow/assets/128982/06b2b916-49f8-43c4-b6fa-c46b7081b3ee)
Subresult:
![result](https://github.com/python-pillow/Pillow/assets/128982/1bb682bf-f21b-474f-bd4a-e08e1f7f4359)
Mask:
![mask](https://github.com/python-pillow/Pillow/assets/128982/4d85273c-2436-4eac-acd4-6d3e8988b66d)
Result:
![result](https://github.com/python-pillow/Pillow/assets/128982/0b83781a-8505-4c77-b14b-b21fa3b757ba)

**Comment by nissansz** [comment]
It looks good. Can you help share full code to test?

**Comment by nissansz** [comment]
I tried to adjust from 33 to 7-15, effect improved, but still not same as your result.
Which other parameter to adjust?

mask = im.filter(ImageFilter.Color3DLUT.generate(15, blue_mask))
# mask.show()
![image](https://github.com/python-pillow/Pillow/assets/41010669/9008ca12-0459-408a-b4c0-29dc9537d4fd)

**Comment by homm** [comment]
Why do you think different [size of the 3D color lookup table](https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.Color3DLUT.generate) can help you?

**Comment by nissansz** [comment]
other paragrameters did not work too.

**Comment by radarhere** [comment]
Here's an attempt to use `getpixel()` and logic
```python
from PIL import Image
im = Image.open("input.png").convert("RGB")
out = Image.new("RGB", im.size)

for x in range(im.width):
	letter = False
	whites = []
	for y in range(im.height):
		color = im.getpixel((x, y))
		if color[2] > max(color[0], color[1]) + 25:
			if not letter:
				letter = True
			for y1 in whites:
				out.putpixel((x, y1), (255, 255, 255))
			whites = []
		elif letter and min(color) > 150:
			whites.append(y)

out.save("out.png")
```
![out](https://github.com/python-pillow/Pillow/assets/3112309/a15d6bfb-ca93-4ba4-bee9-5fefb50f196f)

**Comment by nissansz** [comment]
Yes. Your sample code improved.
But it seems not as good as [homm]'s method (https://github.com/homm) commented [18 hours ago](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1705453525)****

Don't know how he applied below mask and "Darken" layer blending method in Pixelmator. 


blue mask code as below.

from PIL import Image, ImageFilter, ImageDraw
im = Image.open(path).convert('RGB')
# blue_mask = lambda r, g, b: (0, 0, 0) if 0.15 <= (b - (r + g) / 2) <= 0.25 else (1, 1, 1)
blue_mask = lambda r, g, b: (0, 0, 0) if 0.15 <= (b - (r + g) / 2) <= 0.25 else (1, 1, 1)
# mask = im.filter(ImageFilter.Color3DLUT.generate(33, blue_mask))
mask = im.filter(ImageFilter.Color3DLUT.generate(12, blue_mask))
# mask.show()
ImageDraw.floodfill(mask, (0, 0), (0, 0, 0))

**Comment by nissansz** [comment]
![image](https://github.com/python-pillow/Pillow/assets/41010669/f28efabf-de6f-413e-8188-846c456bfe4f)

If I want to filter lower line characters which has gray stroke? How to adjust parameters?

**Comment by nissansz** [comment]
> Effect is very good if you try to spend some time to tune it for your data.
> 
> Source: ![subtitles](https://user-images.githubusercontent.com/128982/265499598-06b2b916-49f8-43c4-b6fa-c46b7081b3ee.png) Subresult: ![result](https://user-images.githubusercontent.com/128982/265499834-1bb682bf-f21b-474f-bd4a-e08e1f7f4359.png) Mask: ![mask](https://user-images.githubusercontent.com/128982/265499623-4d85273c-2436-4eac-acd4-6d3e8988b66d.png) Result: ![result](https://user-images.githubusercontent.com/128982/265499647-0b83781a-8505-4c77-b14b-b21fa3b757ba.png)

blue_mask = lambda r, g, b: (0, 0, 0) if 0.15 <= (b - (r + g) / 2) <= 0.25 else (1, 1, 1)

How to get gray stroke mark? How did you calculate the value for 0.15 <= (b - (r + g) / 2) <= 0.25?

**Comment by radarhere** [comment]
> ![image](https://user-images.githubusercontent.com/41010669/265670931-f28efabf-de6f-413e-8188-846c456bfe4f.png)
> 
> If I want to filter lower line characters which has gray stroke? How to adjust parameters?

For any future reader, I'll note that this was later asked in #7378, about my [earlier code.](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1706332433)

**Comment by radarhere** [comment]
> Yes. Your sample code improved. But it seems not as good as [homm](https://github.com/homm)'s method - [#7369 (comment)](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1705453525)

> I can see your mask effect, but how to apply your mask to @radarhere method

> How did you get the result? Please share full code?

Ok, here's is homm's code, used as a mask for my original code.

```python
# My original code
from PIL import Image
original = Image.open("input.png")
radarhere = original.convert("L").point(lambda x: 255 if x > 230 else 0)

# homm's code
from PIL import Image, ImageFilter, ImageDraw
im = original.convert("RGB")
blue_mask = lambda r, g, b: (0, 0, 0) if 0.15 <= (b - (r + g) / 2) <= 0.25 else (1, 1, 1)
mask = im.filter(ImageFilter.Color3DLUT.generate(33, blue_mask))
ImageDraw.floodfill(mask, (0, 0), (0, 0, 0))

# Combining them
final = Image.new("L", original.size)
final.paste(radarhere, mask=mask.convert("L"))
final.save("final.png")
```
gives the same result as https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1705020179

![final](https://github.com/python-pillow/Pillow/assets/3112309/87f3fa94-89f8-4477-899c-49f3742a7ab4)

**Comment by radarhere** [comment]
> How did you calculate the value for 0.15 <= (b - (r + g) / 2) <= 0.25?

I doubt it was 'calculated' as such. `b - (r + g) / 2` is the checking how much more blue there is than red or green in the image. It is not sufficient just to know if there is blue, since there could also be a lot of red and green, then it could be white.

You can see at https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.Color3DLUT.generate that this
> Will be called size**3 times with values from 0.0 to 1.0

Testing, I don't think there's a need for an upper limit, so `<= 0.25` could be removed. `0.15` is just a number to adjust to determine what level of blue-and-not-other-colours is needed for a pixel to be considered part of the outline. I expect homm just used trial-and-error to find a number that worked for your image.

**Comment by radarhere** [comment]
@nissansz has that answered all of your questions?

**Comment by nissansz** [comment]
How about yellow? Any formula to calculate?
![0_01_10_710__0_01_12_420_0000000000000000000000001](https://github.com/python-pillow/Pillow/assets/41010669/2c3ab085-dd7d-412a-a523-9a048c853321)

**Comment by nissansz** [comment]
> ```python
> # My original code
> from PIL import Image
> original = Image.open("input.png")
> radarhere = original.convert("L").point(lambda x: 255 if x > 230 else 0)
> 
> # homm's code
> from PIL import Image, ImageFilter, ImageDraw
> im = original.convert("RGB")
> blue_mask = lambda r, g, b: (0, 0, 0) if 0.15 <= (b - (r + g) / 2) <= 0.25 else (1, 1, 1)
> mask = im.filter(ImageFilter.Color3DLUT.generate(33, blue_mask))
> ImageDraw.floodfill(mask, (0, 0), (0, 0, 0))
> 
> # Combining them
> final = Image.new("L", original.size)
> final.paste(radarhere, mask=mask.convert("L"))
> final.save("final.png")
> ```

I tried your code for below image, the effect is not as good as homm's version, don't know which parameter to adjust
![3](https://github.com/python-pillow/Pillow/assets/41010669/613bd178-5dd7-40e4-bc68-d79a8438dfc9)

**Comment by radarhere** [comment]
> How about yellow? Any formula to calculate?

We've previously discussed white text with blue stroke, and white text with grey stroke, but this image contains yellow text with black stroke, so that is different.

Because it is black stroke on a dark background, it is worth ignoring the stroke altogether.

To find out how much red, blue or green a pixel has in an image, you can use the Eyedropper or Color Picker tool in your image editor of choice. If you would like one but don't have one, I personally recommend [Gimp](https://www.gimp.org/). Alternatively, you could use Pillow's [`getpixel()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getpixel) once you have coordinates.

Adjusting [homm's code from earlier](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1704815318),

```python
from PIL import Image, ImageFilter, ImageDraw
im = Image.open('yellow.png')
out = lambda r, g, b: (0, 0, 0) if 0.5 < r and 0.3 < g < 0.8 and 0.2 < b < 0.5 else (1, 1, 1)
out = im.filter(ImageFilter.Color3DLUT.generate(33, out))
out.save('out.png')
```
gives

![out](https://github.com/python-pillow/Pillow/assets/3112309/8efd34d5-f0fd-4686-b63b-8c9ab4cac411)

Adjusting the numbers may produce a better result.

**Comment by nissansz** [comment]
> > How about yellow? Any formula to calculate?
> 
> We've previously discussed white text with blue stroke, and white text with grey stroke, but this image contains yellow text with black stroke, so that is different.
> 
> Because it is black stroke on a dark background, it is worth ignoring the stroke altogether.
> 
> To find out how much red, blue or green a pixel has in an image, you can use the Eyedropper or Color Picker tool in your image editor of choice. If you would like one but don't have one, I personally recommend [Gimp](https://www.gimp.org/). Alternatively, you could use Pillow's [`getpixel()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getpixel) once you have coordinates.
> 
> Adjusting [homm's code from earlier](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1704815318),
> 
> ```python
> from PIL import Image, ImageFilter, ImageDraw
> im = Image.open('yellow.png')
> out = lambda r, g, b: (0, 0, 0) if 0.5 < r and 0.3 < g < 0.8 and 0.2 < b < 0.5 else (1, 1, 1)
> out = im.filter(ImageFilter.Color3DLUT.generate(33, out))
> out.save('out.png')
> ```
> 
> gives
> 
> ![out](https://user-images.githubusercontent.com/3112309/266767414-8efd34d5-f0fd-4686-b63b-8c9ab4cac411.png)
> 
> Adjusting the numbers may produce a better result.

Is it better to use binary to filter than mask?

**Comment by radarhere** [comment]
I don't understand your question. What do you mean by binary? Are you talking about converting the image to black and white? What mask are you talking about? I wasn't using a mask in the comment that you're referring to.

**Comment by nissansz** [comment]
Yes. Black and white. opencv has binarization method.

For mask, I mean above homm's result.
https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1706495825

**Comment by radarhere** [comment]
> I tried to adjust from 33 to 7-15, effect improved, but still not same as your result

> Why do you think different size of the 3D color lookup table can help you?

The size of the lookup table controls how precise the generated filter is, which higher numbers being more precise. [`generate()`](https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.Color3DLUT.generate) runs the callback over the entire range of the channels. So a size of 3 calls it with the values of 0, 0.5 and 1 for each channel, and a size of 4 calls it with the values of 0, 0.33, 0.67 and 1.

**Comment by nissansz** [comment]
> > I tried to adjust from 33 to 7-15, effect improved, but still not same as your result
> 
> > Why do you think different size of the 3D color lookup table can help you?
> 
> The size of the lookup table controls how precise the generated filter is, which higher numbers being more precise. [`generate()`](https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.Color3DLUT.generate) runs the callback over the entire range of the channels. So a size of 3 calls it with the values of 0, 0.5 and 1 for each channel, and a size of 4 calls it with the values of 0, 0.33, 0.67 and 1.

Any sample code for this principle? I cannot understand it.

**Comment by radarhere** [comment]
> Is it better to use binary to filter than mask?

> I don't understand your question. What do you mean by binary? Are you talking about converting the image to black and white? What mask are you talking about?

> Yes. Black and white. opencv has binarization method.
> 
> For mask, I mean above homm's result. [#7369 (comment)](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1706495825)

[My initial comment](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1704729760) was converting the image to black-and-white. https://stackoverflow.com/questions/68957686/pillow-how-to-binarize-an-image-with-threshold asks the question of how to binarize an image, and shows code very similar to my first comment.

homm's approach was to combine that result with a different black-and-white conversion. The combination of those two black-and-white images is the masking process. It should be possible to achieve roughly the same result in one step, this is just what we collaboratively came up with.

So a general suggestion to try converting the image to black-and-white doesn't make sense to me, since you've already seen two different ways of doing that here.

**Comment by nissansz** [comment]
Ok. Thank you.

**Comment by nissansz** [comment]
When I used hsv, the effect is as below, but I don't know how to extract the clean large text portion.

![image](https://github.com/python-pillow/Pillow/assets/41010669/54c848c4-d385-4507-a514-58619776f766)

**Comment by radarhere** [comment]
What exactly do you mean by 'used hsv'? When I open the image you attached with Pillow, it is RGBA.

**Comment by nissansz** [comment]
I tested below code with cv2, hsv result seems good, but don't know how to use it to extract clean text only part.


import cv2
import numpy as np

# 加载图片
path = r'F:/3.png'
image = cv2.imread(path)

# 将图片转换为HSV颜色空间
hsv = cv2.cvtColor(image, cv2.COLOR_BGR2HSV)
cv2.imshow('hsv', hsv)

# 定义蓝色范围
lower_blue = np.array([70, 106, 143])
upper_blue = np.array([110, 130, 160])

# 创建蓝色掩膜
mask = cv2.inRange(hsv, lower_blue, upper_blue)
cv2.imshow('mask', mask)

# 使用形态学操作进行图像处理
kernel = np.ones((5, 5), np.uint8)
mask = cv2.morphologyEx(mask, cv2.MORPH_OPEN, kernel)
cv2.imshow('mask1', mask)

# 提取轮廓
contours, _ = cv2.findContours(mask, cv2.RETR_EXTERNAL, cv2.CHAIN_APPROX_SIMPLE)

# 创建黑底白字的图片
result = np.zeros_like(image)
result.fill(255)

# 绘制轮廓
cv2.drawContours(result, contours, -1, (0, 0, 0), thickness=cv2.FILLED)

# 显示原始图片和处理后的图片
cv2.imshow("Original Image", image)
cv2.imshow("Black and White Text", result)
cv2.waitKey(0)
cv2.destroyAllWindows()

**Comment by nissansz** [comment]
Adjusting below ranges, result may be improved for mask, but finally, I cannot get clean text result
lower_blue = np.array([100, 50, 50])
upper_blue = np.array([130, 255, 255])

![image](https://github.com/python-pillow/Pillow/assets/41010669/b346136d-d39c-4eaf-83b4-e5c306c0acb4)

**Comment by radarhere** [comment]
Regarding https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1722135577, the pixels you would like to extract from your image seem to be brighter than the others, so I imagine you filter them out. We have previously discussed how to [extract yellow pixels from an image](https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1712446414). I invite you to look at that answer and try to figure out how to adjust that for your particular shade of red.

Regarding https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1722137120 and https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1722137794, if you have a question about opencv-python, I think that https://github.com/opencv/opencv-python would be a better place for you.

**Comment by nissansz** [comment]
thank you
