### ISSUE TITLE
Is there any way to detect a table in a picture?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7370]
Is there any way to use pillow to detect Table area in a picture? 
For example, without table borders, or skrewed or inclined borders etc.

![image](https://github.com/python-pillow/Pillow/assets/41010669/f749b0a5-9ba2-40b5-b589-c037e57ae09c)

**Comment by radarhere** [comment]
You could use [`im.getpixel()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getpixel) to detect whether a pixel is black or not. From there, you should be able to figure out logic whether the pixels are arranged in a pattern that constitutes a "table".

**Comment by nissansz** [comment]
Any sample code about best practice? Sometimes, many deformations are involved too.

![image](https://github.com/python-pillow/Pillow/assets/41010669/48dfb0f2-6ede-432c-b210-543d4683f1a4)

**Comment by radarhere** [comment]
Another user raised the topic of 'edge detection' a while ago, and response was https://github.com/python-pillow/Pillow/issues/4572#issuecomment-618246247
> We don't currently ship any techniques for edge detection, so I'm not sure that this is the appropriate library for that. OpenCV or SciPy would probably be better choices.

You could certainly write logic to detect if a certain number of pixels are in a group, and decide that a certain amount in a certain direction is a 'line', and that a certain structure of 'line's make a table, but beyond pixel detection or transforming the image to make that detection simpler (like increasing the contrast), I don't know that Pillow has any particular tools for dealing with this scenario.

**Comment by radarhere** [comment]
Has that answered your question?

**Comment by nissansz** [comment]
It seems no solution for this topic under pillow.
