### ISSUE TITLE
UnidentifiedImageError for PNG which is valid according to pngcheck

### ISSUE THREAD

**Issue by violuke** [python-pillow/Pillow#7372]
### What did you do?
Trying to open an image (to resize it).

### What did you expect to happen?
It to open ok.

### What actually happened?
Got an exception
```
PIL.UnidentifiedImageError: cannot identify image file '/tmp/tmpi7hh6s63.png'
```

### What are your OS, Python and Pillow versions?

* OS: Docker container based upon python:3.11.5-slim-bullseye (issue happens running on MacOS on dev and k8s in prod)
* Python: 3.11.5
* Pillow: 10.0.0

```python
image = Image.open("/tmp/tmpi7hh6s63.png")
```

![logo](https://github.com/python-pillow/Pillow/assets/6420347/f0b10df4-bf43-44c8-b7ce-63539c58a903)

[pngcheck](http://www.libpng.org/pub/png/apps/pngcheck.html) is happy with it:
```
pngcheck logo.png
OK: logo.png (130x130, 8-bit palette, non-interlaced, 90.4%).
```

Your help would be much appreciated. Thank you :)

**Comment by radarhere** [comment]
The image works for me on my macOS machine.

The image also works if I try and replicate it using Docker - https://github.com/radarhere/docker-images/commit/b4b00c202f192652df10c87c363eb25f7cf7d788 / https://github.com/radarhere/docker-images/actions/runs/6077691412/job/16487783200#step:6:866

If you could share a Dockerfile that demonstrates the problem, that would be helpful.
