### ISSUE TITLE
How to remove white watermark on image with pillow?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7375]
How to remove white watermark on image with pillow?
![image](https://github.com/python-pillow/Pillow/assets/41010669/a7fbbf2c-5393-46af-9be6-bde5bf6c9f65)

**Comment by radarhere** [comment]
In the image you have attached, i would have though the watermark was the red box and the characters inside it, not white?

**Comment by nissansz** [comment]
Sorry, I mean red watermark.

**Comment by radarhere** [comment]
Are you expecting the watermark to be replaced by a solid color, or are you expecting Pillow to try and repair the resulting gaps in the image with other parts of the image? The second option is not functionality that Pillow provides.

**Comment by nissansz** [comment]
I would like inpaint replace

**Comment by radarhere** [comment]
Ok, so the second option, to try and replace the watermark with more of the background, automatically trying to fill in the watermark gap so that it looks like the watermark was never there.

This is not functionality that Pillow provides.

**Comment by nissansz** [comment]
Understood. It may need AI tech.
