### ISSUE TITLE
How to crop white or black edges?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7377]
![image](https://github.com/python-pillow/Pillow/assets/41010669/e538d575-10f7-49c5-a01f-cb2c477339be)

Get below. Bbox? How to crop well?
![image](https://github.com/python-pillow/Pillow/assets/41010669/6842a987-26a0-4e08-a6d7-7a8a41bed73c)

**Comment by radarhere** [comment]
```python
from PIL import Image
im = Image.open("input.png").convert("RGB")
im.crop(im.getbbox()).save("output.png")
```
gives

![output](https://github.com/python-pillow/Pillow/assets/3112309/fbaa8287-a4fc-4ed9-9721-0f629ba037a7)

**Comment by nissansz** [comment]
Thank you. If I want to crop a whole paragraph, how to adjust?

![image](https://github.com/python-pillow/Pillow/assets/41010669/f5d6dbdf-78a8-4577-9725-00d06507ba59)

**Comment by radarhere** [comment]
You originally asked how to crop white from the image. You can read more at https://github.com/python-pillow/Pillow/discussions/7327, but here is one way.
```python
from PIL import Image, ImageOps
im = Image.open("input.png")
bbox = ImageOps.invert(im.convert("RGB")).getbbox()
im.crop(bbox).save("output.png")
```
gives
![output](https://github.com/python-pillow/Pillow/assets/3112309/7c96f32d-2af8-4002-b7f4-3666cec79100)

If you're asking how to only remove the text in that image, simply determine the co-ordinates you would like to give to [`crop()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop)

**Comment by nissansz** [comment]
Thank you. So bbox works on black ground image.
If I want to split all paragraphs in one image with pillow, is it possible?
One paragraph from above image is as below.
![image](https://github.com/python-pillow/Pillow/assets/41010669/67a8559d-5f57-4978-8804-630029c82b8c)

**Comment by radarhere** [comment]
This is similar to #7371

```python
from PIL import Image
im = Image.open("input.png")
grayscale_im = im.convert("L")
threshold = 20
boxes = []
box = [0, None, im.width, None]
for y in range(im.height):
    for x in range(im.width):
        if grayscale_im.getpixel((x, y)) < 175:
            found_writing = True
            if box[1] is None or y < box[1]:
                box[1] = y
            if box[3] is None or y + 1 > box[3]:
                box[3] = y + 1
    if box != [0, None, im.width, None] and y > box[3] + threshold:
        boxes.append(box)
        box = [0, None, im.width, None]
if box != [0, None, im.width, None] and y > box[3] + threshold:
	boxes.append(box)
	box = [0, None, im.width, None]

for i, box in enumerate(boxes):
	im.crop(box).save("box"+str(i)+".png")
```

gives the following five images

![box0](https://github.com/python-pillow/Pillow/assets/3112309/9052744e-ee1b-4390-a1df-f00114db3a20)
----
![box1](https://github.com/python-pillow/Pillow/assets/3112309/54d74133-b050-4579-bfc2-ce9ccf0c8fda)
----
![box2](https://github.com/python-pillow/Pillow/assets/3112309/aeb6be6d-aa07-4b15-b095-b5c8f70181fb)
----
![box3](https://github.com/python-pillow/Pillow/assets/3112309/1608aa72-afd8-44a3-bab3-9182a3741ae3)
----
![box4](https://github.com/python-pillow/Pillow/assets/3112309/e652a1d5-2844-4166-83d4-78d08dd5638c)

**Comment by nissansz** [comment]
Can it split bottom area too? 
![image](https://github.com/python-pillow/Pillow/assets/41010669/3c489478-c4d4-48af-997d-965c744e212c)

**Comment by radarhere** [comment]
```python
from PIL import Image
im = Image.open("input.png")
grayscale_im = im.convert("L")
threshold = 20
boxes = []
box = [0, None, im.width, None]
for y in range(im.height):
    for x in range(im.width):
        if grayscale_im.getpixel((x, y)) < 175:
            found_writing = True
            if box[1] is None or y < box[1]:
                box[1] = y
            if box[3] is None or y + 1 > box[3]:
                box[3] = y + 1
    if box != [0, None, im.width, None] and y > box[3] + threshold:
        boxes.append(box)
        box = [0, None, im.width, None]
if boxes and boxes[-1][3] != im.height:
	boxes.append(box)

for i, box in enumerate(boxes):
	im.crop(box).save("box"+str(i)+".png")
```
gives

![box0](https://github.com/python-pillow/Pillow/assets/3112309/382aa7e6-9fad-47f0-b937-c9cf44c6ec50)
---
![box1](https://github.com/python-pillow/Pillow/assets/3112309/d54223d2-9c21-4a51-9b02-cf10e4bf43d4)
---
![box2](https://github.com/python-pillow/Pillow/assets/3112309/2fd0230b-fabc-4cbf-be0c-ef9e886e9519)
---
![box3](https://github.com/python-pillow/Pillow/assets/3112309/72479679-7f4b-4770-968e-c25da16fe263)
---
![box4](https://github.com/python-pillow/Pillow/assets/3112309/7e95609e-bff2-4ed2-8ff9-556a59164618)
---
![box5](https://github.com/python-pillow/Pillow/assets/3112309/97644953-28e2-4b98-a465-be570d63b4ae)

**Comment by nissansz** [comment]
It looks good.
