### ISSUE TITLE
How to calculate color value when filter white characters with grey stroke?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7378]
How to calculate color value when filter white characters with grey stroke?

![image](https://github.com/python-pillow/Pillow/assets/41010669/edaee843-76da-461d-9525-ebf72121b591)

Your below code seems working for blue stroke only.
```python
im = Image.open(path).convert("RGB")
out = Image.new("RGB", im.size)

for x in range(im.width):
	letter = False
	whites = []
	for y in range(im.height):
		color = im.getpixel((x, y))
		if color[2] > max(color[0], color[1]) + 25:
			if not letter:
				letter = True
			for y1 in whites:
				out.putpixel((x, y1), (255, 255, 255))
			whites = []
		elif letter and min(color) > 150:
			whites.append(y)
```

**Comment by radarhere** [comment]
This is referring to https://github.com/python-pillow/Pillow/issues/7369#issuecomment-1706332433

`color[2] > max(color[0], color[1]) + 25` is the part of the code that is detecting blue. As it is RGB, `color[0]` is red, `color[1]` is green and `color[2]` is blue. So it is checking that the blue in the pixel is 25 more than either the red or green.

You can adjust this to try and match other colors.

**Comment by nissansz** [comment]
Color sampler shows:
Hex color value for gray is #15160E
r= 21
g = 22
b = 14

How to adjust the code to detect grey stroke?

**Comment by radarhere** [comment]
`color[0] == 21 and color[1] == 22 and color[2] == 14` would detect that exact colour.

However, the outline is not constant. I'm guessing you would like to isolate the text below the blue-stroked text but not the text to the right of it - it may not be practical to effectively distinguish between those based on color, as they are both outlined by grey, just slightly different greys.

**Comment by nissansz** [comment]
Tested. Indeed, failed.

		# elif color[0] == 21 and color[1] == 22 and color[2] == 14 :
		elif color[0] in range (15, 50) and color[1]  in range (15, 50) and color[2]  in range (15, 50):
			whites.append(y)
