### ISSUE TITLE
Any handwritten fonts to download? Or any method to transform handwritten effects from existing fonts?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7379]
I can only found limited handwritten fonts.
Need to expand effects to imitate different persons.
![image](https://github.com/python-pillow/Pillow/assets/41010669/faa524cc-83e6-41b9-a9f5-1bcca117c897)

**Comment by radarhere** [comment]
Googling, I found https://www.dafont.com/theme.php?cat=603 - but looking for handwritten fonts is not a question about Pillow functionality.

As for altering a font to make it look handwritten... you could slant the text like in https://github.com/python-pillow/Pillow/issues/7292#issuecomment-1641931111, or add a blur and waves to the text like in https://github.com/python-pillow/Pillow/issues/7367#issuecomment-1706249174, but I doubt that will give you the results you are after. I'm not even sure if there is any software that will give you the results you are after. Googling, I found https://www.youtube.com/watch?v=klw0VDfkBSQ, but that doesn't look great. I expect people who are invested in making typography look good would generally be more interested in choosing a pre-existing handwritten font.

**Comment by nissansz** [comment]
Thank you.
