### ISSUE TITLE
Some .woff2 fonts return incorrect images

### ISSUE THREAD

**Issue by natuan62** [python-pillow/Pillow#7380]
### What did you do?

- Create thumbnail font for .woff2 

### What did you expect to happen?

- image thumbnail correct with text and font family

### What actually happened?

- image after generate incorrect

### What are your OS, Python and Pillow versions?

* OS: Mac Os 13.5.1
* Python: 3.11.4
* Pillow: 10.0.0

```python
from PIL import Image, ImageDraw, ImageFont

# FONT_NAME = "From Cartoon Blocks.woff2"
FONT_NAME = 'Karla.woff2'

font = ImageFont.truetype(
    FONT_NAME, 100, encoding="utf-8", layout_engine=ImageFont.Layout.RAQM
)
_, _, offset_w, offset_h = font.getbbox(FONT_NAME)

W = offset_w
H = offset_h
image = Image.new("RGBA", (W, H), (255, 0, 0, 0))
draw = ImageDraw.Draw(image)
pos = ((W - offset_w) / 2, (H - offset_h) / 2)
draw.text(pos, FONT_NAME, "white", font=font)
# image.save("test.png")
image.save("test2.png")
```

![image](https://github.com/python-pillow/Pillow/assets/10808157/e156f25b-8e86-4dc1-a1fd-0324ec310192)

[test-fonts.zip](https://github.com/python-pillow/Pillow/files/12531673/Archive.zip)

**Comment by radarhere** [comment]
I presume that 'From Cartoon Blocks.woff2' is fine, and you're just demonstrating what you expect.

If I upload your Karla.woff2 to https://fontdrop.info/, I see that some letters are missing? I expect that the font file is damaged in some way.

![karla](https://github.com/python-pillow/Pillow/assets/3112309/c6d250bc-d64a-4ed5-820b-4778aeca6eab)

If I download https://github.com/googlefonts/karla/blob/main/fonts/webfonts/Karla-Regular.woff2, that font file works fine. I'm able to use that file and your code (after changing the colour to black so you can see the image here on GitHub) to generate the following
![test2](https://github.com/python-pillow/Pillow/assets/3112309/a93883c8-8643-4d47-b115-32df26ce49d4)

**Comment by natuan62** [comment]
@radarhere Thanks for your quick reply. 

So what list glyphs need exists (can't missing) for pillow can generate correct thumbnail ?
Maybe all characters from A to Z and numbers 0 to 9 must exists ?
I want to know each glyphs to check if one of them missing, I'll not generate thumbnail for this damaged font.

**Comment by radarhere** [comment]
Sorry, I didn't mean "Because I can't see a period, letter 'f' or number 2, Pillow doesn't render the whole string"

I expect the data is corrupted somehow. In the case of https://fontdrop.info/, that corruption has lead to some letters appearing to be missing. In the case of Pillow, all of the letters your requested appear to be missing. If I try and preview your font in Chrome, I can see the letters, but they appear in a completely different style to https://fontdrop.info/

![karla](https://github.com/python-pillow/Pillow/assets/3112309/b73e51ac-6d3d-405b-ad40-58028c0f9536)

Sometimes we contact FreeType support to ask them if a font is broken, like in #7287, but given it appears to be broken when accessed in multiple ways, I'm not optimistic.

If you think that Pillow is going to fail to draw characters for multiple fonts, then one strategy to detect that could be to compare the dimensions of different characters - if 'W' and 'i' are the same width, then something is probably off, as I doubt that should be the case.

```python
from PIL import Image, ImageFont

for FONT_NAME in (
    "From Cartoon Blocks.woff2",
    "Karla.woff2",
    "Karla-Regular.woff2"
):
    font = ImageFont.truetype(FONT_NAME, 100)
    if font.getlength("W") == font.getlength("i"):
      print("'W' and 'i' are the same width for "+FONT_NAME+". Something is probably wrong")
    else:
        print(FONT_NAME+" is fine")
```
prints
```
From Cartoon Blocks.woff2 is fine
'W' and 'i' are the same width for Karla.woff2. Something is probably wrong
Karla-Regular.woff2 is fine
```

**Comment by radarhere** [comment]
You liked the previous comment. Does that mean this issue is resolved?

**Comment by natuan62** [comment]
@radarhere Thanks for useful and details description. I tried with many error fonts and them work fine

![Screenshot 2023-09-07 at 09 11 01](https://github.com/python-pillow/Pillow/assets/10808157/0e5eb893-44f0-4e4c-80cc-b2abd607a7d7)

Could you explain for me this thing: Why if a font is broken, all glyphs will be have same width ?
I saw this https://github.com/python-pillow/Pillow/issues/7287 link but I didn’t understand that

**Comment by radarhere** [comment]
Not all broken fonts are broken in the same way. The font in #7287 raises an error when stroking. I mentioned #7287 just in case you wanted an example of contacting FreeType to confirm that the broken is in the font.

The boxes with crosses in them that you are seeing is shown in [fontdrop.info screenshot earlier](https://github.com/python-pillow/Pillow/issues/7380#issuecomment-1707743894). It is called ".notdef", or the ["missing glyph"](https://freetype.org/freetype2/docs/tutorial/step2.html). My code suggestion was effectively checking if "W" and "i" were both missing, in which case they both show the missing glyph, in which case they both have the same width.

**Comment by radarhere** [comment]
Did you have any further questions?

**Comment by natuan62** [comment]
Oh big thanks for your supporting. i'll close this issue ? @radarhere

**Comment by radarhere** [comment]
Thanks

**Comment by natuan62** [comment]
Hi @radarhere :))

I see some fonts aren't broken but when check length of characters, it's return same width. Seem this way not working fines in some cases.

```
from PIL import ImageFont

def checkBrokenFont2(fontPath):
    font = ImageFont.truetype(fontPath)
    result = font.getlength("W") == font.getlength("i")
    return result
```

And I try to use `fontforge` to check whether unicode of characters will be equal -1, but it's not workings fines in some fonts
```
import fontforge

def checkBrokenFont(fontPath):
    try:
        font = fontforge.open(fontPath)

        for gly in font.glyphs():
            if gly.unicode == -1 and gly.glyphname == "A":
                return True
            if gly.unicode == -1 and gly.glyphname == "z":
                return True
            return False
    except Exception as error:
        print(f"Error check broken... {error}")
        return True
```
 
[script-check-broken-fonts.zip](https://github.com/python-pillow/Pillow/files/12596615/script-check-broken-fonts.zip)

![Screenshot 2023-09-13 at 17 51 41](https://github.com/python-pillow/Pillow/assets/10808157/9af717c0-58e8-4281-b3f1-3ea54f6503ff)

![image](https://github.com/python-pillow/Pillow/assets/10808157/0fd90d29-b9c3-4946-a208-546d1529437e)

**Comment by radarhere** [comment]
Oh, right, [monospaced fonts](https://en.wikipedia.org/wiki/Monospaced_font).

How about checking that the result of drawing one letter doesn't exactly match the result of drawing another letter?
```python
def checkBrokenFont2(fontPath):
    font = ImageFont.truetype(fontPath)

    w, h = font.getbbox("a")[2:]
    im = Image.new("L", (w, h), 255)
    draw = ImageDraw.Draw(im)
    draw.text((0, 0), "a", font=font)

    w, h = font.getbbox("b")[2:]
    if im.size != (w, h):
        return False
    im2 = Image.new("L", (w, h), 255)
    draw = ImageDraw.Draw(im2)
    draw.text((0, 0), "b", font=font)

    return im.tobytes() == im2.tobytes()
```

**Comment by natuan62** [comment]
@radarhere Many thanks !
I tested again and all fonts work fine...
