### ISSUE TITLE
ImageOps.exif_transpose not expected behaviour for TIFF images

### ISSUE THREAD

**Issue by bsekachev** [python-pillow/Pillow#7381]
### What did you do?
I have a simple tiff image 150x100px rotated 90 degrees according to exif tag: 

[sample-out.zip](https://github.com/python-pillow/Pillow/files/12549680/sample-out.zip)

```bash
exiftool -n sample-out.tif
...
Image Width                     : 150
Image Height                    : 100
Orientation                     : 6
...
```
I tried to rotate the image in Pillow according to EXIF Orientation tag.

### What did you expect to happen?
New resolution is 100x150, correct orientation

### What actually happened?
New resolution is 150x100, image transposed wrong way

### What are your OS, Python and Pillow versions?

* OS: Ubuntu
* Python: 3.10
* Pillow: 9.3.0

```python
from PIL import Image, ImageOps
im = Image.open('sample-out.tif') 
print(im.size) # (150, 100) - correct
im = ImageOps.exif_transpose(im)
print(im.size) # (150, 100) - not correct
im.save('output.tif') # you may save and see that now image rotated 540 degrees and does not contain
```

```bash
exiftool -n output.tif
...
Image Width                     : 150
Image Height                    : 100
# there is not Orientation tag anymore
...
```

### Reason

``Image.transpose`` calls ``Image.load()``.
``Image.load()``calls ``TiffImageFile.load()``
``TiffImageFile.load()`` calls ``ImageFile.load()``
``ImageFile.load()`` calls ``TiffImageFile.load_end()``
``load_end()`` transposes image. 

After ``Image.load()`` is done, image is transposed again.

**Comment by radarhere** [comment]
I've created PR #7383 to resolve this.

**Comment by bsekachev** [comment]
@radarhere 

Thanks for a quick response :)
