### ISSUE TITLE
DDS BC5_SNORM images are decoded incorrectly

### ISSUE THREAD

**Issue by RunDevelopment** [python-pillow/Pillow#7386]
### What did you do?

I loaded a BC5 SNORM images.

### What did you expect to happen?

For it to be decoded correctly.

![image](https://github.com/python-pillow/Pillow/assets/20878432/34c3f56d-a6ef-45e5-adc3-ef32c5e34c02)

### What actually happened?

Pillow incorrectly decoded the image. It added artifacts and washed out the "colors" of the stored normals.

This is speculation on my part (I haven't read PIL's source code), but it seems like PIL uses the same algorithm for BC5_UNORM (ATI2) and BC5_SNORM.

![image](https://github.com/python-pillow/Pillow/assets/20878432/d57d1c7a-e1a7-43e7-abba-aee801951d09)

### What are your OS, Python and Pillow versions?

* OS: Win 10 64 bit
* Python: 3.8.2
* Pillow: 9.2.0 and 10.0.0

```python
# it's pretty much as basic as it can get
im = Image.open(dds_path)
img = np.array(im)
```

The DDS file in question: [cables_normal.zip](https://github.com/python-pillow/Pillow/files/12568098/cables_normal.zip)

**Comment by radarhere** [comment]
> This is speculation on my part (I haven't read PIL's source code), but it seems like PIL uses the same algorithm for BC5_UNORM (ATI2) and BC5_SNORM.

It'll take some more investigation to figure out the problem, but I can at least say that this shouldn't be the case. Here is the ATI2 code in Python,

https://github.com/python-pillow/Pillow/blob/b8b78ed43478efda2192e415ec51f81c5cf0fd7f/src/PIL/DdsImagePlugin.py#L176-L179

and then where your image is handled.

https://github.com/python-pillow/Pillow/blob/b8b78ed43478efda2192e415ec51f81c5cf0fd7f/src/PIL/DdsImagePlugin.py#L193-L196

If you're interested, almost all of the decoding logic for this lives in our C code.

https://github.com/python-pillow/Pillow/blob/b8b78ed43478efda2192e415ec51f81c5cf0fd7f/src/libImaging/BcnDecode.c#L852-L864

**Comment by RunDevelopment** [comment]
> If you're interested, almost all of the decoding logic for this lives in our C code.

In that case, the issue is most likely in `decode_bc3_alpha`. Its `sign` parameter is basically just a bool whether the current block is BC5S. So the issue is most likely in there or around it.

https://github.com/python-pillow/Pillow/blob/b8b78ed43478efda2192e415ec51f81c5cf0fd7f/src/libImaging/BcnDecode.c#L114

For reference: [this is how DirectXTex does it](https://github.com/microsoft/DirectXTex/blob/419e31491496d7af58ab862b50558668704abebb/DirectXTex/BC4BC5.cpp#L531).

**Comment by radarhere** [comment]
What program did you use to convert the image to your "expected" PNG?

**Comment by radarhere** [comment]
I've created PR #7401. With it, this is the result. What do you think?

![out](https://github.com/python-pillow/Pillow/assets/3112309/3aedeecd-c280-4d85-80bc-c6dfc0d7dab3)

**Comment by radarhere** [comment]
> BC5 doesn't define a B channel (I think)

Correct. See https://learn.microsoft.com/en-us/windows/win32/direct3d10/d3d10-graphics-programming-guide-resources-block-compression#bc5

I find making changes not outlined by a specification to be awkward, but the fact that texconv is developed by Microsoft, who wrote the specification, is a pretty good argument for mimicking that behaviour.

**Comment by radarhere** [comment]
I've created #7413 to resolve this.

**Comment by RunDevelopment** [comment]
That looks perfect. Thank you @radarhere!
