### ISSUE TITLE
I found, png compression will lead to low loading speed in paddle training, jpg seems faster, any reason?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7387]
I found, png compression will lead to low loading speed in paddle training, jpg seems faster, any reason?

**Comment by radarhere** [comment]
What is paddle training? How does this relate to Pillow?

**Comment by nissansz** [comment]
![p0_l3_d1](https://github.com/python-pillow/Pillow/assets/41010669/95d47a99-09e4-405a-8a41-5086a1f9d4aa)
png is as above
jpg as below 
![p0_l3_d1](https://github.com/python-pillow/Pillow/assets/41010669/fc3030b4-dc64-413d-a94b-fa96b331dfbc)
I use pillow to save images for training, but found, png is slow.

**Comment by Yay295** [comment]
That PNG is a lot bigger than 32 pixels wide. Are you sure you're using the right PNG?

**Comment by nissansz** [comment]
Yes, above png is the former effect.
I tried to rezie to same height as 32 as jpg.
Still slow.

**Comment by radarhere** [comment]
As you can see at https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png-saving, a lower number for `compress_level` will increase speed. I also expect that turning off `optimize` will increase speed.

As for the general speed of PNG saving, there is already an issue open for that - #5986

**Comment by nissansz** [comment]
Not saving speed, it may be loading speed from disk after saved.

**Comment by radarhere** [comment]
So you're saving the images with Pillow, opening them with another library, and asking why that other library is slower to open PNG images rather than JPEG images?

This doesn't sound like a Pillow question, it sounds like a question for that other library.

**Comment by nissansz** [comment]
The loading code is pillow.
                img = Image.open(data['img_path'])

**Comment by nissansz** [comment]
Sometimes, png compression result is even larger than jpg.

**Comment by radarhere** [comment]
> Sometimes, png compression result is even larger than jpg.

PNG is a lossless format, JPEG is a lossy format. That gives JPEG a distinct advantage when it comes to small file sizes.

**Comment by nissansz** [comment]
But sometimes, png is much smaller than jpg.
For example, when I export image from Acrobat to jpg, then compress to png with pillow, it may become 1/2 of jpg size.

**Comment by radarhere** [comment]
https://www.quora.com/Why-is-my-PNG-file-smaller-than-my-JPEG
> The file size of an image depends on several factors, such as image resolution, color depth, and compression. In general, JPEG images tend to have larger file sizes than PNG images because JPEG uses lossy compression, which means some information is discarded during compression to reduce file size.
>
> On the other hand, PNG images use lossless compression, which means the image quality is not compromised during compression, resulting in larger file sizes. However, PNG images can have smaller file sizes than JPEG images in certain situations, such as when the image contains large areas of solid color or when there is transparency in the image.
>
> Additionally, the image resolution and color depth can also affect file size. A higher resolution and more colors will result in a larger file size, regardless of whether the image is a JPEG or PNG.
>
> Therefore, if your PNG file is smaller than your JPEG file, it may be because of the specific content of the images or the compression settings used. However, in general, JPEG files tend to have larger file sizes than PNG files.

**Comment by nissansz** [comment]
thank you

**Comment by homm** [comment]
> I tried to rezie to same height as 32 as jpg.

So why you are showing it to us?

> png slow: img.save(pngfile, optimize=True, compress_level=9)
> jpg fast: img.save(pngfile)

Why you are showing saving code if you are asking about loading speed?

> thank you

How this information about the size helps you to solve your problem with loading speed?

**Comment by homm** [comment]
Also you didn't answer what is paddle training? How does this relate to Pillow?

**Comment by nissansz** [comment]
Thank you, Will save as jpg and load with jpg.
