### ISSUE TITLE
Bug Report: Image conversion does not take effect after `PIL.Image.frombytes`

### ISSUE THREAD

**Issue by diyangzyft** [python-pillow/Pillow#7389]
In the following case, image conversion does not take effect after loading image with `PIL.Image.frombytes`:

```python
import PIL
import hashlib, base64, imagehash, urllib

image_file = "download.webp"
urllib.request.urlretrieve('https://cdn.shopify.com/s/files/1/1588/9573/products/PF017557.png?v=1626819941', 
                           image_file)

img_original = PIL.Image.open(image_file)
print(f"Original image mode is {img_original.mode}")

# convert immediately after open image 
img_converted = img_original.convert('RGB')
print(f"After conversion, image mode is {img_converted.mode}")

# create hash out of converted image
img_convert_hash = imagehash.phash(img_converted)

#################################################

# this time apply conversion after loading image from bytes
#use original image
input_image = img_original
input_image_mode = input_image.mode
input_image_size = input_image.size

# load image from bytes
img_str = base64.b64encode(input_image.tobytes())
img_str = img_str.decode()
img_encoded = img_str.encode()
img_b64 = base64.b64decode(img_encoded)
img_from_bytes = PIL.Image.frombytes(input_image_mode, input_image_size, img_b64)

# oppose conversion on image loaded from byte to RGB, which is NOT effect 
img_from_bytes = img_from_bytes.convert('RGB')

img_from_bytes_hash = imagehash.phash(img_from_bytes)

hash_diff = img_convert_hash - img_from_bytes_hash

print(f"Hash Difference: {hash_diff}, supposed to be 0 (i.e. same)")
```

If you run above code block, this result will present:
`Hash Difference: 28, supposed to be 0 (i.e. same)`

However, if I change `input_image = img_converted`, then we will get two exactly hashes, and the result will become
`Hash Difference: 0, supposed to be 0 (i.e. same)`

This indicates that `img_from_bytes = img_from_bytes.convert('RGB')` never works.

**Comment by radarhere** [comment]
Hi. This is actually the same as #6788. This is not related to the conversion from P to RGB, you are losing information when you are using `tobytes()`

https://github.com/python-pillow/Pillow/issues/6788#issuecomment-1342241233
> The idea of P mode is that there is a palette of up to 256 colors, and each pixel in the image is one of those colors. `tobytes()` is only writing out the indexes of the image pixels, and not the palette. So the image becomes black because when it converts those indexes back to an image, there is no palette to tell it what color each pixel is.
>
> For a simpler example, here is Pillow code that creates a 1x1 red P mode image.
>
> ```python
> from PIL import Image
> im = Image.new("P", (1, 1))
> im.putpalette((255, 0, 0))
> im.save("out.png")
> ```
> When you run tobytes() over this,
> ```python
> print(im.tobytes())
> ```
> you get b'\x00'. Zero. There is no way to know that this is supposed to be red. This isn't a bug. It's just not something you should attempt to do with a P mode image.
> 
> There are various alternatives.
> - You could save the palette separately, and then apply it to the new image at the end.
> - You could convert the image from P to RGB, or RGBA.
> - You could save the image in a particular image format (PNG for example), and then load the image back from that.

**Comment by radarhere** [comment]
Has that answer sufficiently explained what is happening?

**Comment by diyangzyft** [comment]
Thanks for this detailed explanation. So we have debugged our codes to make sure that we do conversion before encoding
