### ISSUE TITLE
Automate build and release to PyPI

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#7390]
Currently the [release process](https://github.com/python-pillow/Pillow/blob/main/RELEASING.md) has many steps, including preparing things in this repo, and then starting a build in https://github.com/python-pillow/pillow-wheels, before downloading the sdist + wheel artifacts to disk, and manually uploading them to PyPI using twine.

I'd like us to move towards more automated releases, including using the new Trusted Publishers to upload wheels directly from the CI to PyPI, which is more secure:

* https://blog.pypi.org/posts/2023-04-20-introducing-trusted-publishers/

We can do this in a phased manner, not all of these things would need to be done at once, to ensure we can still make releases with just some of them completed.

We could potentially deal with the Travis CI wheels later, and tackle GitHub Actions first as they're a bigger win and we don't know when Travis CI will go away.

Big picture:

* Prepare release
* Push a tag
* The CI builds release artifacts
* The CI uploads artifacts to PyPI

I'd suggest something along these lines:

1. Move Linux and macOS https://github.com/python-pillow/pillow-wheels to this repo https://github.com/python-pillow/Pillow. We already have Windows wheels build here.
   * We'll need to add [`paths:` / `paths-ignore`](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore) to workflows so we only trigger the main test workflows for "normal" code changes, and only trigger the wheel workflow for things like release and modifying its config
   * Upload wheels as GitHub artifacts in this repo instead

2. Add automation to download artifacts and upload them to PyPI via Trusted Publishing
   * This may need refactoring to move all the wheel building to the same workflow (but separate jobs), and then a final job that runs when the wheels have all been built, that builds sdist, checks and uploads them all.
   * See https://github.com/ultrajson/ultrajson/blob/main/.github/workflows/deploy.yml and https://github.com/ultrajson/ultrajson/actions/workflows/deploy.yml for examples.
   * We also have https://test.pypi.org/project/Pillow/ which we can use to verify the upload machinery is working smoothly before release. For example, we can upload for non-tagged wheel builds.

Thoughts?

**Comment by wiredfool** [comment]
This sounds like a great step.

**Comment by aclark4life** [comment]
Love it!!

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/7418 for 1.

**Comment by hugovk** [comment]
I've opened https://github.com/python-pillow/Pillow/pull/7544 to create the sdist during the release build.

---

Next, I'd like us to move the Windows wheel building from `test-windows.yml` into the same `wheels.yml` workflow.

So we get something like this:

<img width="592" alt="image" src="https://github.com/python-pillow/Pillow/assets/1324225/608ed974-239d-4503-a3ca-c37fe1d4d65e">

And the Windows wheels should be part of the same `dist.zip` artifact containing the Linux and macOS wheels, and the sdist.

I think we also probably want to use a reusable workflow, similar to `wheels-linux.yml` and `wheels-macos.yml`. 

We don't need to build the wheels anymore in `test-windows.yml`. If there's a lot of common steps needed for testing (in `test-windows.yml`) and building wheels, a reusable workflow could be useful here.

This doesn't all need to be done in one go, incremental steps are fine, as long as they're atomic changes and we're still able to make releases during any intermediate step.

Any thoughts on how to approach this? cc @nulano

---

After all this is done, we have all* the release files created in one place on the CI, and do the upload to PyPI! But one step at a time :)

(\* All the GHA files, not Travis CI, which will still need manual upload, but they should be ready before all the automation.)

**Comment by nulano** [comment]
I've managed to use `cibuildwheel` to build wheels locally, I should be able to make a PR on top of #7552 for Windows wheels once it is merged.

**Comment by hugovk** [comment]
Sounds good! When the time comes, we can ask around for someone to test the ARM64 wheels :)

**Comment by nulano** [comment]
I've since realized that I can borrow a relative's M2 MacBook to test the wheels.
The Python 3.12 wheel from my WIP branch tested OK.
I then used `cibuildwheel` manually in the terminal to build and test wheels for the 10.1.0 tag for https://github.com/python-pillow/Pillow/discussions/7547#discussioncomment-7592240

**Comment by radarhere** [comment]
#7616 has now been merged.

@aclark4life [could you](https://github.com/python-pillow/Pillow/pull/7616#issuecomment-1869629897) go to https://pypi.org/manage/project/pillow/settings/publishing/ and add a publisher?

Owner: python-pillow
Repository name: Pillow
Workflow name: wheels.yml
Environment name: release-pypi

**Comment by hugovk** [comment]
We also need to set up an environment named `release-pypi` in this repo, that all the release managers can access: at least @radarhere and me, probably also @aclark4life and @wiredfool for backup.

**Comment by aclark4life** [comment]
@radarhere @hugovk Thanks and done, I think! The env `release-pypi` already exists … need me to do anything to it?

![Screenshot 2023-12-27 at 9 52 12 AM](https://github.com/python-pillow/Pillow/assets/72164/9f92e559-9145-44f6-8aae-5cab327f2a11)

**Comment by hugovk** [comment]
Thanks, the publisher looks good!

> The env `release-pypi` already exists … need me to do anything to it?

@aclark4life What settings does it have?

@radarhere What settings should it have?

**Comment by aclark4life** [comment]
Most notably, no environment vars or secrets configured.

![Screenshot 2023-12-27 at 10 31 15 AM](https://github.com/python-pillow/Pillow/assets/72164/b3d118ff-1688-4a28-893d-876e5092de7b)

**Comment by radarhere** [comment]
The publisher looks good to me, thanks. The details I mentioned were the only ones I added.

**Comment by hugovk** [comment]
So when releasing, after pushing the tag, the CI will begin, build the sdist and all the wheels, and somehow put them in an environment? How does that look? What's the next step to upload to PyPI?

**Comment by aclark4life** [comment]
Probably need a testpypi release first.

**Comment by radarhere** [comment]
When I was using Test PyPI in #7616, once sdist and the wheels were built, the action uploaded them, and that was it.

https://github.com/radarhere/Pillow/actions/runs/7329629479/job/19960359962#step:4:1008
> View at:
> https://test.pypi.org/project/pillow/10.2.0.dev1/

I presume that Test PyPI works the same way as real PyPI.

**Comment by hugovk** [comment]
Okay, so the environment isn't doing anything. Anyway, I'm excited for the next release!

@radarhere Please will you update https://github.com/python-pillow/Pillow/blob/main/RELEASING.md? It can wait until after doing the release if you like.

**Comment by radarhere** [comment]
Sure. I've created #7652

**Comment by radarhere** [comment]
The tagged "Upload release to PyPI" [ran smoothly](https://github.com/python-pillow/Pillow/actions/runs/7383669755/job/20086288107#step:4:73) in the Pillow 10.2.0 release.

With that, is this completed?

**Comment by hugovk** [comment]
Great to hear it went smoothly!

Before closing this issue, we still have Travis to automate. Shall we try my suggestion at https://github.com/python-pillow/Pillow/issues/7485#issuecomment-1873821482 to upload to PyPI directly from Travis?

**Comment by radarhere** [comment]
Sure, sounds good if it works.

**Comment by hugovk** [comment]
Plan C: please see PR https://github.com/python-pillow/Pillow/pull/7690 to replace Travis native builds with GHA emulated builds.

**Comment by aclark4life** [comment]
Only loosely following, but I think I like Plan C!! Thanks all ❤️  (Losing travis in exchange for longer build times is my "hot take", sounds worth it to me.)
