### ISSUE TITLE
How to get background main color of an image and text color on the image? 

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7394]
How to get background main color of an image and text color on the image?

**Comment by radarhere** [comment]
As was said in #7376, Pillow doesn't have the ability to detect text in an image.

If you are still interested in getting the main color of an image, you can try and use [`getcolors()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.getcolors)

![in](https://github.com/python-pillow/Pillow/assets/3112309/5e4a9d76-caa2-4fec-8d4b-b6fcfd6210a8)
```python
from PIL import Image
im = Image.open("in.png")
maximum = 0
mostFrequentColor = None
for number, color in im.getcolors():
    if number > maximum:
        maximum = number
        mostFrequentColor = color
print(mostFrequentColor) # (255, 0, 0)
```

However, you may find this too specific, as it only counts the exact colour that occurs the most - I can imagine that many different browns would be rejected in favour of a smaller amount of an exact blue. #4634 is an open issue about trying to group the colours together.

**Comment by nissansz** [comment]
thank you
