### ISSUE TITLE
Release 10.0.1 on September 15, 2023

### ISSUE THREAD

**Issue by radarhere** [python-pillow/Pillow#7396]
## Point Release

Released as needed for security, installation or critical bug fixes.

* [x] Make necessary changes in `main` branch.
* [x] Update `CHANGES.rst`.
* [x] Check out release branch e.g.:
  ```bash
  git checkout -t remotes/origin/10.0.x
  ```
* [x] Cherry pick individual commits from `main` branch to release branch e.g. `10.0.x`, then `git push`.
* [x] Check [GitHub Actions](https://github.com/python-pillow/Pillow/actions) and [AppVeyor](https://ci.appveyor.com/project/python-pillow/Pillow) to confirm passing tests in release branch e.g. `10.0.x`.
* [x] In compliance with [PEP 440](https://www.python.org/dev/peps/pep-0440/), update version identifier in `src/PIL/_version.py`
* [x] Run pre-release check via `make release-test`.
* [x] Create tag for release e.g.:
  ```bash
  git tag 10.0.1
  git push
  git push --tags
  ```
* [x] Create and check source distribution:
  ```bash
  make sdist
  python3 -m twine check --strict dist/*
  ```
* [x] Create [binary distributions](https://github.com/python-pillow/Pillow/blob/main/RELEASING.md#binary-distributions)

### Windows
* [x] Download the artifacts from the [GitHub Actions "Test Windows" workflow](https://github.com/python-pillow/Pillow/actions/workflows/test-windows.yml) and copy into `dist/`

### Mac and Linux
* [x] Use the [Pillow Wheel Builder](https://github.com/python-pillow/pillow-wheels):
  ```bash
  git clone https://github.com/python-pillow/pillow-wheels
  cd pillow-wheels
  ./update-pillow-tag.sh [[release tag]]
  ```
* [x] Download wheels from the [Pillow Wheel Builder release](https://github.com/python-pillow/pillow-wheels/releases)
  and copy into `dist/`

---

* [x] Check and upload all binaries and source distributions e.g.:
  ```bash
  python3 -m twine check --strict dist/*
  python3 -m twine upload dist/Pillow-10.0.1*
  ```
* [x] Publish the [release on GitHub](https://github.com/python-pillow/Pillow/releases)

## Publicize Release

* [x] Announce release availability via [Twitter](https://twitter.com/pythonpillow) and [Mastodon](https://fosstodon.org/@pillow) e.g. https://twitter.com/PythonPillow/status/1013789184354603010

## Documentation

* [x] Make sure the [default version for Read the Docs](https://pillow.readthedocs.io/en/stable/) is up-to-date with the release changes

## Docker Images

* [x] Update Pillow in the Docker Images repository
  ```bash
  git clone https://github.com/python-pillow/docker-images
  cd docker-images
  ./update-pillow-tag.sh [[release tag]]
  ```

**Comment by radarhere** [comment]
Pillow 10.0.1 is released!

I've posted to Fosstodon - https://fosstodon.org/@pillow/111069554873271253 - but I think we can't use TweetDeck anymore - https://mashable.com/article/tweetdeck-paid-service-x-elon-musk

**Comment by hugovk** [comment]
Thank you for taking care of the release!

**Comment by aclark4life** [comment]
I'll do the X (formerly Twitter) notification

**Comment by radarhere** [comment]
Thanks. https://twitter.com/PythonPillow/status/1702689873239351611
