### ISSUE TITLE
How to draw png from svg file or data like below?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7405]
How to draw png from svg file or data like below?

Data from https://github.com/skishore/makemeahanzi
SVG examples from here.
[19975.zip](https://github.com/python-pillow/Pillow/files/12645834/19975.zip)
https://github.com/parsimonhi/animCJK/blob/master/svgsJa/19975.svg

{"character":"丈","strokes":["M 552 521 Q 618 534 689 547 Q 770 565 782 576 Q 792 585 787 594 Q 780 607 747 617 Q 713 624 678 612 Q 617 593 556 574 L 502 560 Q 493 559 486 557 Q 374 532 244 521 Q 202 515 232 496 Q 280 469 342 481 Q 418 496 500 511 L 552 521 Z","M 509 230 Q 536 300 542 396 Q 546 460 552 521 L 556 574 Q 557 688 590 759 Q 597 775 586 788 Q 561 810 517 823 Q 489 830 478 824 Q 468 817 476 802 Q 501 759 503 706 Q 504 633 502 560 L 500 511 Q 488 340 467 270 L 450 228 Q 425 174 376 137 Q 306 82 154 34 Q 139 30 138 24 Q 138 20 151 17 Q 176 11 235 25 Q 337 44 409 100 Q 457 137 487 185 L 509 230 Z","M 487 185 Q 488 184 490 181 Q 646 -2 704 -9 Q 834 -9 900 0 Q 945 4 941 17 Q 940 23 896 36 Q 719 85 661 116 Q 591 155 509 230 L 467 270 Q 421 316 374 367 Q 334 412 296 413 Q 277 414 273 409 Q 270 402 288 389 Q 339 356 450 228 L 487 185 Z"],"medians":[[[234,510],[259,503],[344,506],[515,538],[705,585],[775,588]],[[486,813],[516,792],[541,763],[513,370],[505,312],[487,246],[467,202],[439,161],[353,91],[271,54],[146,22]],[[279,406],[320,389],[342,372],[569,137],[677,57],[706,42],[768,31],[911,13],[935,15]]]}

graphics.txt keys:
character: The Unicode character for this glyph. Required.

strokes: List of SVG path data for each stroke of this character, ordered by proper stroke order. Each stroke is laid out on a 1024x1024 size coordinate system where:

The upper-left corner is at position (0, 900).
The lower-right corner is at position (1024, -124).
Note that the y-axes DECREASES as you move downwards, which is strage! To display these paths properly, you should hide render them as follows:

<svg viewBox="0 0 1024 1024">
  <g transform="scale(1, -1) translate(0, -900)">
    <path d="STROKE[0] DATA GOES HERE"></path>
    <path d="STROKE[1] DATA GOES HERE"></path>
    ...
  </g>
</svg>
medians: A list of stroke medians, in the same coordinate system as the SVG paths above. These medians can be used to produce a rough stroke-order animation, although it is a bit tricky. Each median is a list of pairs of integers. This list will be as long as the strokes list.

**Comment by nissansz** [comment]
SVG path abbreviations.
How to parse these values and then apply to pillow draw?

M = moveto
L = lineto
H = horizontal lineto
V = vertical lineto
C = curveto
S = smooth curveto
Q = quadratic Bézier curve
T = smooth quadratic Bézier curveto
A = elliptical Arc
Z = closepath

**Comment by nissansz** [comment]
3 parts for example, how to draw with pillow?

<path id="z19975d1" d="M515 233C577 226 694 221 864 222C878 222 887 218 891 212C895 203 891 193 879 184C835 151 793 145 752 155C622 183 426 207 166 236C150 237 147 244 160 257C181 279 207 287 237 280C307 262 393 246 468 238C499 235 499 235 515 233Z"/>

<path id="z19975d2" d="M480 416C510 428 563 435 640 434C656 433 667 434 673 444C680 456 674 474 668 500C642 597 623 667 605 708C589 740 575 759 564 770C546 785 528 786 502 776C480 767 455 758 427 748C415 743 410 746 411 751C412 757 419 764 431 775C462 804 485 831 500 856C509 871 518 879 530 880C540 880 556 876 576 864C601 846 622 817 640 780C660 737 687 658 721 544C729 515 740 493 756 480C767 470 774 462 774 452C773 441 750 420 704 389C689 379 675 381 660 385C606 398 550 395 494 385C483 383 469 412 480 416Z"/>

<path id="z19975d3" d="M494 385C516 336 531 309 537 304C545 295 551 286 548 276C543 260 530 247 515 233C503 223 465 223 468 238C472 258 466 288 450 329C448 334 445 339 443 346C397 458 350 544 301 605C253 663 193 722 120 779C115 782 111 785 108 790C103 796 106 799 114 801C126 803 147 791 183 771C292 708 398 595 480 416C489 395 489 395 494 385Z"/>

**Comment by hugovk** [comment]
Before someone does your work for you, what have you tried so far?

**Comment by nissansz** [comment]
I can only see the effect in web browser.

Below code does not work due to error.
line 13, in <module>
    bbox = svgpathtools.paths2svg(paths).get_bounding_box()
TypeError: 'module' object is not callable


from PIL import Image, ImageDraw
import svgpathtools
# pip install svgpathtools

# 输入SVG文件路径和输出PNG文件路径
svg_file = r'F:/19975.svg'
png_file = svg_file.replace('.svg','')+'.png'

# 使用svgpathtools库加载SVG文件中的路径
paths, attributes = svgpathtools.svg2paths(svg_file)

# 计算SVG路径的边界框大小
bbox = svgpathtools.paths2svg(paths).get_bounding_box()

# 计算图像的实际大小，并创建相应大小的图像
width = int(bbox[2] - bbox[0])
height = int(bbox[3] - bbox[1])
image = Image.new("RGBA", (width, height), (255, 255, 255, 0))

# 创建绘图工具对象
draw = ImageDraw.Draw(image)

# 绘制每条路径到图像上
for path in paths:
    for segment in path:
        start_point = complex(segment.start.real - bbox[0], segment.start.imag - bbox[1])
        end_point = complex(segment.end.real - bbox[0], segment.end.imag - bbox[1])
        control_point1 = complex(segment.control1.real - bbox[0], segment.control1.imag - bbox[1])
        control_point2 = complex(segment.control2.real - bbox[0], segment.control2.imag - bbox[1])
        draw.path([start_point, control_point1, control_point2, end_point], fill="black")

# 保存图像为PNG文件
# image.save(png_file, "PNG")
image.show()

**Comment by hugovk** [comment]
Tip: paste your code inside triple backticks, so it's formatted properly. 

``````
```
Code here
```
``````

Please can you edit your post?

**Comment by nissansz** [comment]
updated

**Comment by hugovk** [comment]
Thanks, this is a problem with how you're calling svgpathtools, which is not part of Pillow. 

https://github.com/mathandy/svgpathtools

The `paths2svg` module has no `get_bounding_box()` function, and you also can't call the module like a function: `paths2svg(paths)` 


https://github.com/mathandy/svgpathtools/blob/master/svgpathtools/svg_to_paths.py

Where did you get your code sample from? Who wrote it?

**Comment by nissansz** [comment]
I get the code from chatgpt.

Is it possible to directly parse paths with python and then write with pillow?

**Comment by nissansz** [comment]
Thank you.
I found a code working with import aggdraw.

https://stackoverflow.com/questions/246525/how-can-i-draw-a-bezier-curve-using-pythons-pil
