### ISSUE TITLE
Optimized PNG is larger

### ISSUE THREAD

**Issue by YueLengM** [python-pillow/Pillow#7408]
### What did you do?

Save png with optimize on

### What did you expect to happen?

Smaller file

### What actually happened?

Larger file

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.11.5
* Pillow: 10.0.1

```python
import sys
from pathlib import Path

import PIL
from PIL import Image

print(sys.version) # 3.11.5 | packaged by Anaconda, Inc. | (main, Sep 11 2023, 13:26:23) [MSC v.1916 64 bit (AMD64)]
print(PIL.__version__) # 10.0.1

i = Image.open("photo.png")

i.save("optimized.png", optimize=True)
print(f'optimized \t {Path("optimized.png").stat().st_size}')         # optimized        1347526

i.save("non-optimized.png", optimize=False)
print(f'non-optimized \t {Path("non-optimized.png").stat().st_size}') # non-optimized    1215070
```

Here is the photo.png
[photo.zip](https://github.com/python-pillow/Pillow/files/12650046/photo.zip)

**Comment by radarhere** [comment]
`optimize` has two effects in the code when saving PNG.
https://github.com/python-pillow/Pillow/blob/89340819cfe77b9680060983b49e91a73a5c94e9/src/libImaging/ZipEncode.c#L81-L82
https://github.com/python-pillow/Pillow/blob/89340819cfe77b9680060983b49e91a73a5c94e9/src/libImaging/ZipEncode.c#L218-L237

Something about this second block is causing the image to be larger than it could be.

If you're interested, an immediate way around this would be to use `compress_level` setting instead, to have the same effect as the first block without running the second.

`i.save("compress_level.png", compress_level=9)` is 1198609 bytes.

**Comment by homm** [comment]
Png size is unpredictable and most optimizers just brute-force different options trying to find the best, also using some heuristics. So this can't be considered as a bug. If you want be sure the size is minimum, it's better to save with minimum compression, then run independent optimizer, like [oxipng](https://github.com/shssoichiro/oxipng).
