### ISSUE TITLE
When saving a TIFF with old-style jpeg compressed file, the background is pink

### ISSUE THREAD

**Issue by xiaoyzhou** [python-pillow/Pillow#7417]
### What did you do?
I use this code to split the multiframe images to single frame image.
```python
from PIL import Image

#NG
image = Image.open('input.tiff')
#print(image.size, image.info, image.mode)

for i in range(image.n_frames):
    image.seek(i)
    print(image.size, image.info, image.mode)
    image.save(f'output_{i}.tiff', format='TIFF')
```

### What did you expect to happen?
The output tiff's background is white.

### What actually happened?
The output tiff's background is pink.

### What are your OS, Python and Pillow versions?
* OS: Windows 10 (22H2)
* Python: 3.9.13
* Pillow: 9.5.0

```python
code goes here
```
[input.zip](https://github.com/python-pillow/Pillow/files/12699061/input.zip)
[output.zip](https://github.com/python-pillow/Pillow/files/12699072/output.zip)

**Comment by radarhere** [comment]
I get a similar pink background if I try and read the image with ImageMagick or GIMP.

What makes you think the background should be white? How do you know the image isn't malformed? Is there a program that you have found that reads the image with a white background?

**Comment by xiaoyzhou** [comment]
![TiffView](https://github.com/python-pillow/Pillow/assets/88647067/e2c59187-247d-4dec-a360-2398df446023)

I use tiffview to open the tiff file.
Background is white.

**Comment by radarhere** [comment]
You're hitting
https://github.com/python-pillow/Pillow/blob/7a633e3500018031a36a5adbec3e6c3e5d1c60eb/src/PIL/TiffImagePlugin.py#L1326-L1328

This was added in #3489.

If I run `tiffinfo` over the image, I get
> TIFFReadDirectory: Warning, Photometric tag value assumed incorrect, assuming data is YCbCr instead of RGB.

So I think there is an accepted practice of how to read this old style JPEG compression that is leading to this background color.

**Comment by radarhere** [comment]
https://stackoverflow.com/a/23677466 states
> "old-style" JPEG compression is deprecated in TIFF, because it was never fully specified. And because of this under-specification, various vendors implemented it in different, incompatible ways.

I'm not sure there is a way to comfortably address your image without potentially breaking other "old-style" JPEG compression images.

For your specific image, my earlier suggestion combined with some `autocontrast()` produces a reasonable result. Is that sufficient to resolve this?

```python
from PIL import Image, ImageOps, TiffImagePlugin

im = Image.open("input.tiff")
if im._compression == "tiff_jpeg" and im.tag_v2.get(TiffImagePlugin.PHOTOMETRIC_INTERPRETATION) == 2:
    im2 = Image.new("RGB", im.size)
    im2.putdata(im.convert("YCbCr").getdata())
    im = ImageOps.autocontrast(im2, (0, 1))
im.save("out.png")
```
![out](https://github.com/python-pillow/Pillow/assets/3112309/ba925b91-ec40-43c8-b171-e7c33c6b2c71)

**Comment by xiaoyzhou** [comment]
Thank you very match!
It's helpful!
