### ISSUE TITLE
Cannot identify image

### ISSUE THREAD

**Issue by TheAnkurGoswami** [python-pillow/Pillow#7419]
### What did you do?

I was downloading an image using following python code:
```python
import requests
from PIL import Image
from io import BytesIO

link = "https://coloredmanga.com/wp-content/uploads/WP-manga/data/manga_6173003824249/85d69f8667f073e69cd03154b09f1412/149.jpg"

res = requests.get(link)
img = Image.open(BytesIO(res.content))
```

### What did you expect to happen?

This code should download the image successfully, as the image can easily be downloaded using browser.

### What actually happened?
I received following error:
```python
UnidentifiedImageError                    Traceback (most recent call last)
[<ipython-input-4-0ac70fca527d>](https://localhost:8080/#) in <cell line: 2>()
      1 res = requests.get(link)
----> 2 img = Image.open(BytesIO(res.content))

[/usr/local/lib/python3.10/dist-packages/PIL/Image.py](https://localhost:8080/#) in open(fp, mode, formats)
   3278         warnings.warn(message)
   3279     msg = "cannot identify image file %r" % (filename if filename else fp)
-> 3280     raise UnidentifiedImageError(msg)
   3281 
   3282 

UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x7a311b3fce00>
```

### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: 3.8
* Pillow: Tried with both 9.4.0 & 10.0.1

**Comment by radarhere** [comment]
If I download your file, it is a 1,050,628 byte file. When I try to open it,
```python
from PIL import Image
im = Image.open("149.jpg")
```
I see no problems. 

If I run your code with a different URL, I see no problems.

I would therefore conclude it is something specific to downloading this URL. If I run
```python
import requests
from PIL import Image
from io import BytesIO

link = "https://coloredmanga.com/wp-content/uploads/WP-manga/data/manga_6173003824249/85d69f8667f073e69cd03154b09f1412/149.jpg"

res = requests.get(link)
print(len(res.content))
```
I get `1008537`. This doesn't look like a problem reading an image with Pillow, but a problem downloading the file before it gets to Pillow.

**Comment by JamesParrott** [comment]
Hi Ankur.  Thanks for the code snippet - that's really helpful. There's something unusual about your linked image to the manga comic.  Your code works for 4 other links (to the BBC and wikipedia Jpeg article) mostly unaltered.  I was able to open the manga by saving it to a file first.  I'm not sure what is going on with requests or this particular file in BytesIO.

```
import requests
from PIL import Image
from io import BytesIO

links = ["https://upload.wikimedia.org/wikipedia/commons/thumb/6/61/JPEG_example_subimage.svg/256px-JPEG_example_subimage.svg.png",
         "https://upload.wikimedia.org/wikipedia/commons/thumb/2/23/Dctjpeg.png/220px-Dctjpeg.png",
         "https://upload.wikimedia.org/wikipedia/commons/e/e9/Felis_silvestris_silvestris_small_gradual_decrease_of_quality.png",
         "https://ichef.bbci.co.uk/onesport/cps/800/cpsprodpb/119CF/production/_131234127_gettyimages-1696023006.jpg",
         "https://coloredmanga.com/wp-content/uploads/WP-manga/data/manga_6173003824249/85d69f8667f073e69cd03154b09f1412/149.jpg",
         ]


N = len(links)
for i, link in enumerate(links):
    res = requests.get(link)
    img = Image.open(BytesIO(res.content))
    print(f'Successfully downloaded and opened link {i} / {N}')

```

```
Successfully downloaded and opened link 0 / 5
Successfully downloaded and opened link 1 / 5
Successfully downloaded and opened link 2 / 5
Successfully downloaded and opened link 3 / 5
Traceback (most recent call last):
  File "C:\ ... \pillow_issue_7419.py", line 18, in <module>
    img = Image.open(BytesIO(res.content))
          ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\ ... \Pillow\Lib\site-packages\PIL\Image.py", line 3280, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file <_io.BytesIO object at 0x000002848E215A80>
```

**Comment by TheAnkurGoswami** [comment]
> If I download your file, it is a 1,050,628 byte file. When I try to open it,
> 
> ```python
> from PIL import Image
> im = Image.open("149.jpg")
> ```
> 
> I see no problems.
> 
> If I run your code with a different URL, I see no problems.
> 
> I would therefore conclude it is something specific to downloading this URL. If I run
> 
> ```python
> import requests
> from PIL import Image
> from io import BytesIO
> 
> link = "https://coloredmanga.com/wp-content/uploads/WP-manga/data/manga_6173003824249/85d69f8667f073e69cd03154b09f1412/149.jpg"
> 
> res = requests.get(link)
> print(len(res.content))
> ```
> 
> I get `1008537`. This doesn't look like a problem reading an image with Pillow, but a problem downloading the file before it gets to Pillow.

I think you are right.

I tried running the same code again. This time it was successful. But when I again ran it, it failed. 
I printed first 100 bytes of the response in both cases.

**Case 1: Successful download**
```python
>>> res.content[:100]
b'\xff\xd8\xff\xe1)\xdcExif\x00\x00MM\x00*\x00\x00\x00\x08\x00\x0c\x01\x00\x00\x03\x00\x00\x00\x01\x05\xf0\x00\x00\x01\x01\x00\x03\x00\x00\x00\x01\t`\x00\x00\x01\x02\x00\x03\x00\x00\x00\x03\x00\x00\x00\x9e\x01\x06\x00\x03\x00\x00\x00\x01\x00\x02\x00\x00\x01\x12\x00\x03\x00\x00\x00\x01\x00\x01\x00\x00\x01\x15\x00\x03\x00\x00\x00\x01\x00\x03\x00\x00\x01\x1a\x00\x05\x00\x00'
```

**Case 2: Failure**
```python
>>> res.content[:100]
b'\xa5\xff\x7f1\n\xe9iq\xc6\x83\x88jR\x0f\x80:R\x17\xfe\xfc\xf9\xf7G\xc80\xb7\xff\xfc\xba\xff_\xfb\x0c\xef\xf5<@I`\x03\x9c\xe0\n\xb5\x0f\xb0JI\xf2\x0c\xe0\xdc\xa6\xa8\x18\x84T^\x04$"\xae"\xd1\x02\x12-\xd5Ry\x15\x89h\x91\xa8\xb8R)\xd5\xd2\x12\xf5S\x87\xff\x1b\x9e\xe6\xf6\x8f\x0c\x03\x8c\x9a\xb3\x89\x15,\x98\x0c'
```

**Comment by radarhere** [comment]
If I try `urllib` instead,
```python
from urllib.request import urlopen
link = "https://coloredmanga.com/wp-content/uploads/WP-manga/data/manga_6173003824249/85d69f8667f073e69cd03154b09f1412/149.jpg"
urlopen(link)
```
I get `urllib.error.HTTPError: HTTP Error 403: Forbidden`

So I imagine that the site doesn't actually want you to download images programmatically.

**Comment by radarhere** [comment]
https://github.com/psf/requests/issues/6535 was created to ask the question of the requests library, so I think it is agreed that the problem is not with Pillow's handling of the data it is given.
