### ISSUE TITLE
Merge character png to sentence png

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7422]
I want to have a code for below function.
[test.zip](https://github.com/python-pillow/Pillow/files/12721685/test.zip)

In the zip file, there will be png folders, each folder contains some options of a same character
I want to generate a random string with these random character pngs
for example,
sentence image height = 32
each character png is pasted at the center of each bbox in the final sentence image,
how to generate it fast and well?

**Comment by radarhere** [comment]
[You're aware](https://github.com/python-pillow/Pillow/issues/7371#issuecomment-1705745388) of the idea of creating a new image and [`paste()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste)ing other images into it. [You're also aware](https://github.com/python-pillow/Pillow/issues/7367#issuecomment-1704472071) of making random choices in Python.

Have you attempted to use these ideas to find a solution?

**Comment by nissansz** [comment]
My pc is stuck, converting gnt to png data.
Will try after finished png preparation.

**Comment by nissansz** [comment]
![image](https://github.com/python-pillow/Pillow/assets/41010669/8259e565-e01f-464e-bfbc-7a892fa2df7d)

It seems working fine.
