### ISSUE TITLE
How to fill the colors in a contour image of character?

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7424]
![ts_37](https://github.com/python-pillow/Pillow/assets/41010669/3634c9df-e8a8-4e25-98f8-8929e2e86dc5)
![ts_948](https://github.com/python-pillow/Pillow/assets/41010669/eec2d10c-1aa9-47d2-b21d-6df3a72c9f13)

**Comment by radarhere** [comment]
Given that Pillow does not have text detection, you're going to have to figure out a co-ordinate inside of the character, and then use [`ImageDraw.floodfill()`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.floodfill)

**Comment by nissansz** [comment]
Thank you.
