### ISSUE TITLE
Fontfamily cannot show some characters as browser effect

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7429]
[J007-日文毛笔.zip](https://github.com/python-pillow/Pillow/files/12773013/J007-.zip)
There are fonts, which cannot display some characters even with font family.
![image](https://github.com/python-pillow/Pillow/assets/41010669/d59863bd-cd51-4f05-be52-00591a14d50f)

Test string: をも資资儲储議议歷历權权
Upper is pillow draw
lower is edge browse render

Any method to replace font for unshown characters?

**Comment by radarhere** [comment]
For context, when you talk about 'font family', you are referring to the functionality of #6926, allowing missing characters in one font to be replaced by fonts in backup fonts.

It would seem that the darker characters in your first image are from the font you've attached, and the thinner characters are from a font you haven't provided.

When you say 'replace font for unshown characters', I don't know what you mean. If you would like the correct characters to appear, but they aren't, then the simplest explanation is the fonts you are using don't have the characters you're requesting, and you need to find another font. Given that you already believe that the attached font doesn't have all the characters you're after, do you have any reason to believe this isn't the case for these additional characters?

**Comment by nissansz** [comment]
Do you mean if a character is not in font char list, it will not be shown by itself or other backup font in same font family?
If so, any method to judge which character is missing when drawing text, so as to define backup font as the font for display the missing character?

**Comment by radarhere** [comment]
I think you're fundamentally asking about the functionality of #6926, and as I have [said](https://github.com/python-pillow/Pillow/issues/7290#issuecomment-1639277250) [before](https://github.com/python-pillow/Pillow/issues/7292#issuecomment-1642023721), you use it at your own risk. I don't think it is reasonable to expect it to always work, given that it hasn't been merged yet. If you have feedback on the PR, you're free to leave comments there.

**Comment by nissansz** [comment]
Yes. If I want to use below method to draw text for each char. is it slower than fontfamily?

Iterate all chacters in a string,
judge each character to see whether it is in the char list of a desire font,
if not in the list, specify the backup font to draw the character, then continue

**Comment by radarhere** [comment]
If you have questions about #6926, please ask them there. I don't think it is reasonable for us to support functionality that hasn't been finished yet.

**Comment by nissansz** [comment]
ok
