### ISSUE TITLE
tiff How to enhance UnsharpMask ？

### ISSUE THREAD

**Issue by monkeycc** [python-pillow/Pillow#7450]
![270649855-812a38af-12a9-43e3-a2d0-bacdc5f09e3b](https://github.com/python-pillow/Pillow/assets/6490927/d0a6501f-be95-4b5f-a552-001200fe53f5)
[1.zip](https://github.com/python-pillow/Pillow/files/12840095/1.zip)

1.
16 bit gray chart tiff
```python
Image.open
```
How to load ？

2.

```python
ImageEnhance.Sharpness
ImageEnhance.UnsharpMask
```

image enhancement
How to achieve the desired outcome ？

**Comment by homm** [comment]
To enhance something you first need to sa what wrong with existing thing.

**Comment by monkeycc** [comment]
> To enhance something you first need to say what wrong with existing thing.

Sorry

Realizing the need for improvement in one's own expression

Completed


1.
16 bit gray chart tiff
```python
Image.open
```
How to load ？

2.

```python
ImageEnhance.Sharpness
ImageEnhance.UnsharpMask
```

image enhancement
How to achieve the desired outcome ？

**Comment by radarhere** [comment]
1. Pillow does have a [`load()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.load) method, to pull the data from the file into memory,
```python
from PIL import Image
im = Image.open('1.tiff')
im.load()
```
but I expect there are many people who use Pillow without ever thinking about loading images, so I'd be surprised if that's what you meant. If you're interested in just opening the image,
```python
from PIL import Image
im = Image.open('1.tiff')
```
should suffice. If that doesn't work for you, please let us know what version of Pillow you're using.

2. Regarding ImageEnhance, you may have tried
```python
from PIL import Image, ImageEnhance
im = Image.open('1.tiff')
enh = ImageEnhance.Sharpness(im)
enh.enhance(1.9).save('out.tiff')
```
but received an error - `ValueError: image has wrong mode`

That is the same as #7397. In that issue, the following workaround is suggested.

```python
from PIL import Image, ImageEnhance
im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
enh = ImageEnhance.Sharpness(im)
enh.enhance(1.9).save("out.tiff")
```

Pillow doesn't have an `ImageEnhance.UnsharpMask`. You might be thinking of [`ImageFilter.UnsharpMask`](https://pillow.readthedocs.io/en/stable/reference/ImageFilter.html#PIL.ImageFilter.UnsharpMask)

```python
from PIL import Image, ImageFilter
im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
im.filter(ImageFilter.UnsharpMask).save("out.tiff")
```

**Comment by radarhere** [comment]
I suspect you primarily want a way to make 1.tiff look like the image on the right of your post though? Could you provide a description of how it was created?

**Comment by monkeycc** [comment]
Thank you.
Your answer is very detailed
It has taught me a lot
```python
Im. filter (ImageFilter. UnsharpMask (radius=3, percentage=400, threshold=0))
```

pillow:
![out2](https://github.com/python-pillow/Pillow/assets/6490927/a148f9e3-2494-40f9-a435-b337c2d45f2b)

But unfortunately
I can't adjust it
I don't know if there is a loading issue or an image enhancement issue
Missing a lot of details
And there are many patterns
Unfortunately




I implemented it through GIMP
https://www.gimp.org/

```python
Sharpen (Unsharp Mask)
Filters → Enhancement → Sharpen (Unsharp Mask)

Radius: 7.0
Amount: 11.0
Threshold: 0
```



```python
Exposure
Colors → Exposure

Black level: 0
Exposure: 3.0
```

GIMP:
![11111](https://github.com/python-pillow/Pillow/assets/6490927/f9f3ae9e-e85c-40ed-a301-68bee175663d)


@radarhere

**Comment by radarhere** [comment]
If you're asking how to provide arguments to `ImageFilter.UnsharpMask`, here is an example.
```python
from PIL import Image, ImageFilter
im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
im.filter(ImageFilter.UnsharpMask(3, 400, 0)).save("out.tiff")
```

**Comment by monkeycc** [comment]
> If you're asking how to provide arguments to , here is an example.`ImageFilter.UnsharpMask`
> 
> ```python
> from PIL import Image, ImageFilter
> im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
> im.filter(ImageFilter.UnsharpMask(3, 400, 0)).save("out.tiff")
> ```

Thank you for your help
Unfortunately
No matter how I adjust the parameters
The images are all unclear

![out2](https://github.com/python-pillow/Pillow/assets/6490927/a148f9e3-2494-40f9-a435-b337c2d45f2b)

**Comment by radarhere** [comment]
```python
from PIL import Image, ImageEnhance, ImageFilter
im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
im.filter(ImageFilter.UnsharpMask(7, 3600, 0)).save("out.jpg")
```
gives

<img src="https://github.com/python-pillow/Pillow/assets/3112309/11c9851e-f748-4af2-90d7-2cc56b84a4df" width="500" />

Is that closer?

I recognise you may not want the background though, so the following code will get rid of it.
```python
from PIL import Image, ImageEnhance, ImageFilter
im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
out = Image.new("L", im.size, 255)
mask = ImageEnhance.Contrast(im).enhance(5).point(lambda x: 255 if x < 50 else 0)
out.paste(im.filter(ImageFilter.UnsharpMask(7, 3600, 0)), mask=mask)
out.save("out.jpg")
```
<img src="https://github.com/python-pillow/Pillow/assets/3112309/d449aedd-e285-42d2-92d1-0b90b21c938b" width="500" />

**Comment by monkeycc** [comment]
Thank you for taking the time to debug

right
I tested it


Ripple pattern
![微信截图_20231009104739](https://github.com/python-pillow/Pillow/assets/6490927/05a0db9b-e7be-4c51-91cd-4fcf60a247bd)
![微信截图_20231009104844](https://github.com/python-pillow/Pillow/assets/6490927/07f06b32-0b89-4dc4-9d75-f717c8d7a12f)

Can't we handle this matter?

**Comment by radarhere** [comment]
I imagine you're really after a different approach than Unsharp, but see what you think of this slight modification.
```python
from PIL import Image, ImageEnhance, ImageFilter
im = Image.open("1.tiff").point(lambda x: x / 256).convert("L")
out = Image.new("L", im.size, 255)
out.paste(im, mask=ImageEnhance.Contrast(im).enhance(5).point(lambda x: 255 if x < 50 else 0))
out.paste(im.filter(ImageFilter.UnsharpMask(7, 3600, 0)), mask=im.point(lambda x: 255 if x < 59 else 0))
out.save("out.jpg")
```
gives

<img src="https://github.com/python-pillow/Pillow/assets/3112309/337d8af0-83cf-483f-ae30-1abeb38ec19b" width="500" />

**Comment by monkeycc** [comment]
Thank you very much for your help

This method is not suitable
Due to surface defects and missing details

I will try to adjust myself

Because I want to see surface defects
Need to see surface details
See if there are any defects

Thank you again for your selfless help
It moved me very much
@radarhere
