### ISSUE TITLE
WMF misses MIME handler

### ISSUE THREAD

**Issue by doublex** [python-pillow/Pillow#7471]
Just a "blemish":

````
from PIL import Image
Image.MIME['WMF']

Traceback (most recent call last):
KeyError: 'WMF'
````

**Comment by radarhere** [comment]
Hi. I have two comments here.
1. If you're following your example code directly, you won't find any mime types.
```pycon
>>> from PIL import Image
>>> Image.MIME
{}
```
As discussed in #7398, `Image.MIME` won't be populated until a plugin is loaded through `preinit()` or `init()`. These functions are usually just called internally when opening or saving images.

```pycon
>>> from PIL import Image
>>> Image.init()
1
>>> Image.MIME
{'BMP': 'image/bmp', 'DIB': 'image/bmp', 'PCX': 'image/x-pcx', 'EPS': 'application/postscript', 'GIF': 'image/gif', 'PNG': 'image/png', 'JPEG2000': 'image/jp2', 'ICNS': 'image/icns', 'ICO': 'image/x-icon', 'JPEG': 'image/jpeg', 'TIFF': 'image/tiff', 'MPEG': 'video/mpeg', 'MPO': 'image/mpo', 'PALM': 'image/palm', 'PDF': 'application/pdf', 'PPM': 'image/x-portable-anymap', 'PSD': 'image/vnd.adobe.photoshop', 'SGI': 'image/sgi', 'TGA': 'image/x-tga', 'WEBP': 'image/webp', 'XBM': 'image/xbm', 'XPM': 'image/xpm'}
```

2. 'WMF' in this context refers to Pillow's WMF format - https://github.com/python-pillow/Pillow/blob/main/src/PIL/WmfImagePlugin.py - which can open both WMF and EMF files, which have different mimetypes. So I don't think it's quite correct to say that "WMF" is image/wmf, when the Pillow WMF format also handles image/emf.

If you were asking for [`get_format_mimetype()`](https://pillow.readthedocs.io/en/stable/reference/ImageFile.html#PIL.ImageFile.ImageFile.get_format_mimetype) to return the specific mimetype for a WMF or EMF file that you had opened, then that would be another matter.

**Comment by doublex** [comment]
@radarhere 
You are right. Sorry for the disturbance.
