### ISSUE TITLE
Mix use of grayscale/greyscale in document and code

### ISSUE THREAD

**Issue by wx00** [python-pillow/Pillow#7479]
### What did you do?

I've been searching in the document and found it use "grayscale" in some places and "greyscale" in some other places, describing same type of images in Pillow. I also viewed those parts of code and found out they are mostly consistent with corresponding documents.

### What did you expect to happen?
It should be using the same word across the whole document and code.

### What actually happened?
Mix use of slightly different spelling words across multiple places.

### What are your OS, Python and Pillow versions?
Not related to the issue. The mix use of both words seems to have been the case for a very long time, at least since Pillow 3.x, which makes me a bit confused.

#### Examples of grayscale:
* `L` (8-bit pixels, grayscale) [[Modes](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes)]
* GIF files are initially read as grayscale (L) or palette mode (P) images. [[GIF](https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#gif)]
* [[`PIL.ImageOps.grayscale(image)`](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.grayscale)]

#### Examples of greyscale:

* When translating a color image to greyscale (mode “L”) [[`Image.convert(mode=None, matrix=None, dither=None, palette=Palette.WEB, colors=256)`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.convert)]
* A bilevel image (mode “1”) is treated as a greyscale (“L”) image by this method. [[`Image.histogram(mask=None, extrema=None)`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.histogram),[`Image.entropy(mask=None, extrema=None)`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.entropy)]
* Parameters: threshold – All pixels above this greyscale level are inverted. [[`PIL.ImageOps.solarize(image, threshold=128)`](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.solarize)]

**Comment by radarhere** [comment]
Using grep, I find that 'gray' is more popular in the codebase. I've created #7481 to use 'gray'.

However, I have left ImImagePlugin alone, as it actually writes "Greyscale" into image files.
https://github.com/python-pillow/Pillow/blob/0a6fcc2d9767ec06aa0d645ddd43305daa340e10/src/PIL/ImImagePlugin.py#L308-L313
