### ISSUE TITLE
Set up GitHub release token for Travis CI

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#7485]
For https://github.com/python-pillow/Pillow/issues/7390.
Re: https://github.com/python-pillow/Pillow/issues/7348#issuecomment-1763383329, https://github.com/python-pillow/pillow-wheels/pull/156#discussion_r450959499.

We need to set up a token for Travis CI to be able to upload wheels to this repo's release section.

1. Create a GitHub personal access token scoped to this repo. ⚠️ A repo admin needs to do this due to permissions.
2. Install Travis CLI:

```console
❯ sudo gem install travis --no-document
...
❯ travis --version
Shell completion not installed. Would you like to install it now? |y| y
1.11.1
```

3. The next bit is where I got stuck, but try something like this (https://stackoverflow.com/a/76234874/724176):

```
❯ travis login --github-token GITHUB_PERSONAL_ACCESS_TOKEN

❯ travis setup releases -r python-pillow/Pillow 
```

5. Save the new token as `GITHUB_RELEASE_TOKEN` at https://app.travis-ci.com/github/python-pillow/pillow/settings.

**Comment by hugovk** [comment]
@aclark4life Please could you look into this? It needs to be done by someone with admin permissions. Thanks!

**Comment by aclark4life** [comment]
@hugovk Sure, level of urgency?

**Comment by hugovk** [comment]
It would be nice (but not essential) to have it ready for the next quarterly release.

**Comment by hugovk** [comment]
Actually, we do need this before the next release, otherwise we'll need to do a similar hack to [last time](https://github.com/python-pillow/Pillow/issues/7348#issuecomment-1763371082) by uploading the files to a third-party site instead, and from a security perspective it would be better to avoid that.

**Comment by aclark4life** [comment]
@hugovk OK I'll work on it this week

**Comment by aclark4life** [comment]
@hugovk When you say stuck do you mean this or something else? It's possible I need to make a better token for this task with the appropriate permissions … I have not done that yet.

![Screenshot 2023-11-27 at 9 32 16 AM](https://github.com/python-pillow/Pillow/assets/72164/6a681a71-aec6-4720-890e-0e6127c346d6)

**Comment by hugovk** [comment]
Yes, I also got `resource not found ({}`: https://github.com/python-pillow/Pillow/issues/7348#issuecomment-1763351055

**Comment by aclark4life** [comment]
I cannot unsee what I've seen here today in working on this … but good news: progress!!

```
alexclark in ~/Developer/python-pillow/pillow on main λ travis accounts
aclark4life (Jeffrey A. Clark (Alex)): not subscribed, 4 repositories
plone (Plone Foundation): not subscribed, 392 repositories
python-pillow (Pillow): not subscribed, 5 repositories
To set up a subscription, please visit app.travis-ci.com.

```

**Comment by aclark4life** [comment]
@hugovk OK more progress, although I'm not entirely sure why or how, I got `repo` commands working e.g.

```

alexclark on alexclarks-Air.fios-router.home in ~/Developer/python-pillow/pillow((default)|4h34m|travis-setup-releases*)
$ travis branches
10.1.0:                          #9957 errored    10.1.0 version bump
travis:                          #9952 passed     Test file change
master:                          #9929 passed     Merge pull request #5074 from hugovk/docs-links
aclark4life-patch-1:             #9922 passed     Update CHANGES.rst
8.0.x:                           #9830 passed     8.0.1 version bump
8.0.1:                           #9831 passed     8.0.1 version bump
8.0.0:                           #9800 passed     8.0.0 version bump
docs-python-versions-header:     #9652 passed     Give supported Python versions its own header
update-macos:                    #9442 passed     Tested 7.2.0 with 3.5-3.8 on macOS Mojave
autobuild-pr-test:               #9155 errored    Merge pull request #4663 from radarhere/lcms2
7.1.x:                           #9029 passed     7.1.2 version bump
7.1.2:                           #9028 passed     7.1.2 version bump
7.1.1:                           #8928 passed     Add 7.1.1 release notes to index
7.1.0:                           #8916 errored    7.1.0 version bump
7.2.0:                           #8914 passed     7.1.0 version bump
7.2.x:                           #8913 passed     7.1.0 version bump
coverage2:                       #8562 passed     macOS only
LAuk1obh6Lwn0eO28oEJh:           #8561 passed     Merge pull request #4357 from radarhere/testing
coverage:                        #8560 passed     macOS only
macos:                           #8558 passed     before
6.2.2:                           #8501 passed     Release notes for 6.2.2
7.0.0:                           #8500 passed     Release notes for 6.2.2
7.0.x:                           #8499 passed     Release notes for 6.2.2
6.2.x:                           #8497 passed     Release notes for 6.2.2
stringio:                        #8434 passed     Lint fix
rm-2.7-docs:                     #8325 passed     Update macOS to reflect GitHub Actions
rm-2.7-ci-docs:                  #8273 passed     Docs: remove 2.7 from CI targets
test-coverage5beta:              #8235 passed     Test Coverage 5 beta on the CIs
6.2.1:                           #8115 passed     Pillow 6.2.1 is the last to support Python 2.7
update-tidelift-badge:           #7891 passed     Update Tidelift badge
add-license-to-setup:            #7707 canceled   Add license to setup.py for #3938
6.1.0:                           #7698 passed     Revert #3780 for PyPy3 as it hasn't been updated yet. (#3935)
6.1.x:                           #7697 passed     Revert #3780 for PyPy3 as it hasn't been updated yet. (#3935)
revert-3780-update_py_unicode:   #7690 passed     Revert "Update Py_UNICODE to Py_UCS4"
5.2.x:                           #7683 failed     5.2.0 version bump
revert-3752-update-classifiers:  #7488 canceled   Revert "Update Trove licence classifiers"
6.0.0:                           #7306 passed     Resolved segfaults
6.0.x:                           #7305 passed     Resolved segfaults
segfault:                        #7303 passed     Resolved segfaults
update-readme:                   #7213 failed     Wording/linking
update-docs:                     #6709 passed     Release history is visible at PyPI
5.4.1:                           #6670 passed     5.4.0 version bump
5.4.x:                           #6672 passed     5.4.1 version bump
5.4.0:                           #6615 passed     Fix for check-manifest
update-release-notes:            #6603 passed     Fix typo
readthedocs:                     #6426 passed     Install project using pip in ReadTheDocs build
fix-webp-loading-from-blob:      #6399 passed     skip old test
5.3.0:                           #6372 passed     5.3.0 version bump
5.3.x:                           #6371 passed     5.3.0 version bump
fix-docstring-typo:              #6304 errored    Fix docstring typo
```

Unfortunately, `travis setup releases` is still complaining about GitHub tokens and it's really hard to tell what's going on, and what is supposed to happen, and when it's supposed to happen.

That said, I did manage to update Pillow's .travis.yml with an encrypted token. If you think that would help, I can commit it on a branch.

![Screenshot 2023-11-28 at 12 03 32 PM](https://github.com/python-pillow/Pillow/assets/72164/3135226d-586e-4f0a-834c-2b30a15985ab)

I ask because `travis setup releases` seems to want to overwrite .travis.yml before it fails on:

```
$ travis setup releases        
deploy section already exists in .travis.yml, run with --force to override
alexclark on alexclarks-Air.fios-router.home in ~/Developer/python-pillow/pillow((default)|4h40m|travis-setup-releases*)
$ travis setup releases --force
all GitHub tokens given were invalid

````

So maybe all it does is edit `.travis.yml` and we can skip that and just worry about the tokens ?

**Comment by hugovk** [comment]
Okay, we _might_ be nearly there... Rather than committing the token, save it in the Travis UI like this:

> 5. Save the new token as GITHUB_RELEASE_TOKEN at [app.travis-ci.com/github/python-pillow/pillow/settings](https://app.travis-ci.com/github/python-pillow/pillow/settings).

**Comment by aclark4life** [comment]
Done, although I didn't escape any of the characters in the secure token string …

**Comment by hugovk** [comment]
Thanks! Now to figure out how to test it...

**Comment by radarhere** [comment]
Ok, I tried, and it "[failed to deploy](https://app.travis-ci.com/github/python-pillow/Pillow/jobs/614541649#L12753)" - more specifically with [an error that](https://app.travis-ci.com/github/python-pillow/Pillow/jobs/614541649#L12687)
> /home/travis/.rvm/gems/ruby-3.1.2/gems/faraday-0.15.4/lib/faraday/options.rb:166:in `new': tried to create Proc object without a block (ArgumentError)

I found [a suggestion to downgrade to focal](https://github.com/travis-ci/dpl/issues/1234#issuecomment-1698840515), and if I reverted https://github.com/python-pillow/Pillow/commit/dea5bbebbc71c9dac78a801b42766562154f8453, then I [made it to](https://app.travis-ci.com/github/python-pillow/Pillow/jobs/614546295#L12667)
> GET https://api.github.com/user: 401 - Bad credentials // See: https://docs.github.com/rest (Octokit::Unauthorized)

This is an error that [might be generated if the API key is wrong](https://github.com/travis-ci/travis-ci/issues/7574).

**Comment by aclark4life** [comment]
In reviewing the syntax for the various configuration files, I noticed when encrypted tokens were listed, they were listed within a `secure` block e.g. instead of:

```
token: some-token
```

It was:

```
token:
  secure: some-encrypted-token
```

Or something like that. I'm not sure if that's an issue here, but it may be worth looking into and trying just to rule it out.

**Comment by radarhere** [comment]
Instead of
https://github.com/python-pillow/Pillow/blob/0a66b98558054dea8059707f781937b754f4b406/.travis.yml#L43-L46
I tried
```
# Upload wheels to GitHub Releases
deploy:
  provider: releases
  api_key:
    secure: $GITHUB_RELEASE_TOKEN
```
but to no avail.

**Comment by hugovk** [comment]
Changing tack, we could cut out the middle steps:

1. build wheel on Travis CI
2. upload from Travis to GH release
3. download locally
4. upload to PyPI

And instead upload directly to PyPI from Travis:

1. build wheel on Travis CI
2. upload to PyPI

This would require creating an API token on PyPI and setting it as a `TWINE_PASSWORD` env var secret in the repo:


```
  -p PASSWORD, --password PASSWORD
                        The password to authenticate to the repository
                        (package index) with. (Can also be set via
                        TWINE_PASSWORD environment variable.)
```

https://twine.readthedocs.io

https://docs.travis-ci.com/user/environment-variables/#defining-variables-in-repository-settings

Then use `twine upload` on Travis CI.

We could try it with TestPyPI first.

Travis CI usually finishes before the GitHub Actions wheel build, so the Travis wheels will be uploaded before the sdist and other wheels. This should be fine.

What do you think?

**Comment by radarhere** [comment]
Sure, sounds good if it works.

**Comment by hugovk** [comment]
I've made an API token on TestPyPI, saved it in our 1Password vault ("Pillow TestPyPI API token"), and tried saving it as `TWINE_PASSWORD` at https://app.travis-ci.com/github/python-pillow/Pillow/settings but got an error:

![image](https://github.com/python-pillow/Pillow/assets/1324225/48c63e33-f75c-4439-9923-1bb04a139ac8)

Maybe it needs an admin to do it.

@aclark4life Please could you add it?

**Comment by aclark4life** [comment]
It doesn't sound that great to me … but I may be missing something. (E.g. things that sound good to me: "No more Travis!") But let me take another close look over the next few days and report back, thanks all.

**Comment by hugovk** [comment]
I was going to say:

> "No more Travis!" sounds good to me too, and we can drop it, either by:
> 
> * dropping the Linux aarch64 wheels
> * building them on GitHub Actions with emulation, but that would increase the build from ~40 mins to [~4 hours!](https://github.com/python-pillow/pillow-wheels/pull/367#issuecomment-1418263768)
>
> And now we have an automated release, maybe that's acceptable?

Then I decided to try it out, to see how long it takes now we have cibuildwheel.

First, Travis takes ~40 minutes for the longest job:

<img width="1093" alt="image" src="https://github.com/python-pillow/Pillow/assets/1324225/5f4f1c8f-b60b-4f71-9acc-840065f4f31a">

https://app.travis-ci.com/github/python-pillow/Pillow/builds/268090488

The first two creates manylinux wheels for 7 versions (3.8-3.12 + 2xPyPy) and the last musllinux for 5 versions (3.8-3.12).

The current GitHub Actions wheel build takes ~10 to ~40 minutes:

<img width="629" alt="image" src="https://github.com/python-pillow/Pillow/assets/1324225/47d14180-ae39-4e67-b64f-c5be4c45e7d4">

https://github.com/python-pillow/Pillow/actions/runs/7383669755

I added manylinux and musllinux to GitHub Actions using QEMU emulation. I forgot that Travis actually does two manylinux builds (manylinux_2_17 (aka manylinux2014) and manylinux_2_28), so we're actually missing some in this experiment, but let's come back to that.

I used a matrix, so each job ran for a single Python version and created 1 manylinux (by default manylinux_2_17) and 1 musllinx wheel (except PyPy which doesn't have musllinux so had a single manylinux).

The 7 QEMU jobs took 2-3 hours:

<img width="398" alt="image" src="https://github.com/python-pillow/Pillow/assets/1324225/addf0e33-577f-4ed1-addf-64144c6c8538">

https://github.com/hugovk/Pillow/actions/runs/7387963337

Next, also split so each job does a single Python version and manylinux OR musllinux (except only manylinux for PyPy).

The 12 QEMU jobs took 1.5-2 hours:

<img width="291" alt="image" src="https://github.com/python-pillow/Pillow/assets/1324225/cfcb2603-a7d3-432a-9e02-9872beb47bdd">

https://github.com/hugovk/Pillow/actions/runs/7390943205

Is this an acceptable cost? We ditch Travis CI (40 minutes) and use GitHub Actions (2 hours)? 

Note this the human waiting time, making use of parallel builds, the actually CPU time used is much greater.

---

As mentioned, I forgot manylinux_2_28 in this experiment. 

Do we actually need wheels for both manylinux_2_17 and manylinux_2_28?

If so, this would add another 7 jobs to GHA, I expect also taking 1.5-2 hours. 

We'd have 19 QEMU jobs taking 1.5-2 hours + 7 native jobs taking 10-40 mins. We get max 20 parallel jobs, so it would be fully saturated meaning some have to wait to be started, and so maybe take 2.5-3 hours for the whole thing.

**Comment by radarhere** [comment]
I'm willing to deal with the additional time, sure.

> Do we actually need wheels for both manylinux_2_17 and manylinux_2_28?

manylinux_2_28 was added in https://github.com/python-pillow/pillow-wheels/pull/301, to allow for zlib 1.2.12 on newer operating systems, whereas manylinux_2_17 only allowed for zlib 1.2.8. The reason for keeping manylinux_2_17 around was to support CentOS 7 (EOL June 30) and Amazon Linux 2 (EOL June 30, 2025).

**Comment by wiredfool** [comment]
AL2 is what we'd need for Lambda and Elastic Beanstalk.

**Comment by radarhere** [comment]
Off-topic aside: I'm in favour of waiting until Amazon Linux 2 (and CentOS 7) are EOL - but there is a more recent AWS alternative for users in the form of Amazon Linux 2023.

**Comment by wiredfool** [comment]
It looks like 3.8 and below are AL2, and 3.9+ are AL2023 for EB (https://docs.aws.amazon.com/elasticbeanstalk/latest/platforms/platform-history-python.html) , and 3.11 and below are AL2 for Lambda (https://docs.aws.amazon.com/lambda/latest/dg/lambda-runtimes.html)

**Comment by hugovk** [comment]
So, given CentOS 7 EOL is 2024-06-30, potentially we can forget about AL2 when Python 3.8 is EOL (2024-10-14), meaning we can drop manylinux_2_17 at the same time.

That would mean we have both manylinuxes for the next release in July, and just one for the following release in October.

**Comment by wiredfool** [comment]
No, because Lambda is using AL2 for 3.11.  And we certainly get enough questions about how to install on Lambda to know that it's something that people use.

**Comment by aclark4life** [comment]
RIP AL2. Long live AL2023. (AL2 stops at Python 3.8. AL2023 supports up to 3.11)

**Comment by hugovk** [comment]
Please see PR https://github.com/python-pillow/Pillow/pull/7690 to replace Travis native builds with GHA emulated builds.
