### ISSUE TITLE
DNG file from Samsung S23 is not supported

### ISSUE THREAD

**Issue by vishal-tandel** [python-pillow/Pillow#7487]
### What did you do?
I tried opening the image file from the Samsung S23 (Indian unit).

### What did you expect to happen?
I expected that the image could be successfully opened using this library.

### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: It failed to read the image. (UnidentifiedImageError: cannot identify image file 'dng_exeption/Asset_1_error.dng')

```python
from PIL import Image
filepath = 'Asset3_error.dng'
img = Image.open(filepath)
```
I have uploaded sample images here
[https://drive.google.com/drive/folders/1kxu-NSKaVHrvJyOaxlEKgJhIa9j7L18y?usp=sharing](url)

**Comment by radarhere** [comment]
We already have an open issue for the DNG format - #6482
