### ISSUE TITLE
`Image.frombytes` throws on empty image

### ISSUE THREAD

**Issue by dragazo** [python-pillow/Pillow#7492]
### What did you do?

I have some code I use to render text as images. When trying to render an empty string, it fails on `Image.frombytes`

### What did you expect to happen?

I expected `Image.frombytes` with size `(0, 0)` and bytes `[]` (as a numpy array of uint8) to successfully yield an empty image.

### What actually happened?

An exception is thrown:

```pytb
Traceback (most recent call last):
  File "/home/devin/Desktop/pyblox/netsblox/turtle.py", line 89, in wrapped
    fn(*args, **kwargs)
  File "/home/devin/Desktop/pyblox/netsblox/turtle.py", line 119, in wrapped
    return f(*args, **kwargs)
  File "<stdin>", line 34, in my_onstart
  File "/home/devin/Desktop/pyblox/netsblox/turtle.py", line 1250, in say
    imgs = [_render_text(x, size = 8, color = (0, 0, 0)) for x in lines]
  File "/home/devin/Desktop/pyblox/netsblox/turtle.py", line 1250, in <listcomp>
    imgs = [_render_text(x, size = 8, color = (0, 0, 0)) for x in lines]
  File "/home/devin/Desktop/pyblox/netsblox/turtle.py", line 80, in _render_text
    text_mask = Image.frombytes('L', text_mask.size, _np.array(text_mask).astype(_np.uint8)) # convert ImagingCore to Image
  File "/home/devin/.local/lib/python3.8/site-packages/PIL/Image.py", line 2976, in frombytes
    im.frombytes(data, decoder_name, args)
  File "/home/devin/.local/lib/python3.8/site-packages/PIL/Image.py", line 804, in frombytes
    d.setimage(self.im)
ValueError: tile cannot extend outside image
```

### What are your OS, Python and Pillow versions?

* OS: Linux Mint 20
* Python: 3.8.10
* Pillow: 10.1.0

```python
font = ImageFont.truetype('example-font.otf')
text = ''
color = (0, 0, 0)

text_mask = font.getmask(text, mode = 'L')
text_mask = Image.frombytes('L', text_mask.size, _np.array(text_mask).astype(_np.uint8)) # fails here with exception
```

**Comment by dragazo** [comment]
Looks like I constructed a minimal example incorrectly. The issue was actually from trying to render empty string, due to a pagination step in between getting the text and rendering it.

In that case, the issue would actually be that `Image.frombytes` throws an error when initializing it with size `(0, 0)` and bytes `[]`. It seems like this should just successfully return an empty image.

**Comment by radarhere** [comment]
Ok, I've created PR #7493 to resolve this. See what you think.

**Comment by hugovk** [comment]
> It seems like this should just successfully return an empty image.

Why should `Image.frombytes("L", (0, 0), b"")` return an empty image instead of an error?

What use is an empty image? 

Would it be better to raise because we're passing in "bad" input? 

Should the user be checking they're no passing in bad input?

**Comment by dragazo** [comment]
I haven't tried the new version personally, but if that test case passes, that should solve my issue.

**Comment by radarhere** [comment]
Using one of our test fonts, yes, it passes.

Could you help address a concern that has been raised? Why is it useful to you to have an empty image?

**Comment by dragazo** [comment]
Well like the example code showed, I'm not explicitly trying to produce an empty image, that's just what ends up happening during an intermediate step. Basically my code can sometimes try to render text consisting of only whitespace, for which `font.getmask` returns an empty image core. It's the conversion of the (empty) image core object into an (empty) image that was failing.

I suppose I could add pre-checks to ensure that doesn't happen, but from a type theory perspective does that mean I just have to always produce `str -> Optional[Image]` instead of the desired `str -> Image`? The only way to avoid that would be replacing the `None` fail case with a valid but empty(ish) image like a 1x1 transparent image. But that sounds less nice than just allowing empty images, esp. since `font.getmask` already happily produces them.

**Comment by hugovk** [comment]
Thanks. Let's say `str -> Image` succeeds. You now have an empty image, what do you do with it?

The thing I'm trying to balance is: do we give the user an exception they need to handle, or a (useless?) empty image they need to handle in another place/way.

**Comment by dragazo** [comment]
Among other things, I can paste it onto another image. For my use case this is part of a renderer - I have a string and a location, I render the text and paste it onto the base image (with some decoration steps in between). Empty image allows me to not need to check exceptions just for rendering text from a font object.

As for the useless part, I think an empty image is no less useless than an empty string.

If you want to do the exception route, you should make it so that `font.getmask` fails on empty or whitespace strings (currently returns an empty image core object), rather than the conversion to the `Image` wrapper type. That's what's confusing, I think.

**Comment by hugovk** [comment]
Thanks, that sounds reasonable.
