### ISSUE TITLE
DLL load failed while importing _imaging: The specified module could not be found.

### ISSUE THREAD

**Issue by mygithubaccount12** [python-pillow/Pillow#7494]
### What did you do?

```from matplotlib import rcParams```

### What did you expect to happen?
The program to execute beyond import statement.

### What actually happened?
```
Traceback (most recent call last):
  File "e:\Minitab_Killer\rcParams_print_out.py", line 2, in <module>
    from matplotlib import rcParams 
  File "C:\Users\D\miniconda3\lib\site-packages\matplotlib\__init__.py", line 107, in <module>
    from . import _api, cbook, docstring, rcsetup
  File "C:\Users\D\miniconda3\lib\site-packages\matplotlib\rcsetup.py", line 24, in <module>
    from matplotlib import _api, animation, cbook
  File "C:\Users\D\miniconda3\lib\site-packages\matplotlib\animation.py", line 34, in <module>
    from PIL import Image
  File "C:\Users\D\miniconda3\lib\site-packages\PIL\Image.py", line 103, in <module>
    from . import _imaging as core
ImportError: DLL load failed while importing _imaging: The specified module could not be found.
```

### What are your OS, Python and Pillow versions?

* OS:  Windows 10
* Python: 3.9.18
* Pillow: 10.0.1

I'm using anaconda (package list below).

I've created a new environment in ```conda``` and only ran the ```matplotlib``` install command , uninstalled Python outside of the anaconda environment, tried ```pip``` to uninstall/reinstall while trying every answer on SO I could find, but strictly using ```conda``` is highly desirable.

I've scoured the internet for days and have tried what I could find to no avail.

# Name                    Version                   Build  Channel
brotli                    1.1.0                hcfcfb64_1    conda-forge
brotli-bin                1.1.0                hcfcfb64_1    conda-forge
bzip2                     1.0.8                h8ffe710_4    conda-forge
ca-certificates           2023.7.22            h56e8100_0    conda-forge
certifi                   2023.7.22          pyhd8ed1ab_0    conda-forge
contourpy                 1.1.1            py39h1f6ef14_1    conda-forge
cycler                    0.12.1             pyhd8ed1ab_0    conda-forge
fonttools                 4.43.1           py39ha55989b_0    conda-forge
freetype                  2.12.1               hdaf720e_2    conda-forge
gettext                   0.21.1               h5728263_0    conda-forge
glib                      2.78.0               h12be248_0    conda-forge
glib-tools                2.78.0               h12be248_0    conda-forge
icu                       58.2                 ha925a31_3
importlib-resources       6.1.0              pyhd8ed1ab_0    conda-forge
importlib_resources       6.1.0              pyhd8ed1ab_0    conda-forge
intel-openmp              2023.2.0         h57928b3_50496    conda-forge
jpeg                      9e                   hcfcfb64_3    conda-forge
kiwisolver                1.4.5            py39h1f6ef14_1    conda-forge
krb5                      1.20.1               heb0366b_0    conda-forge
lerc                      3.0                  hd77b12b_0
libblas                   3.9.0                     8_mkl    conda-forge
libbrotlicommon           1.1.0                hcfcfb64_1    conda-forge
libbrotlidec              1.1.0                hcfcfb64_1    conda-forge
libbrotlienc              1.1.0                hcfcfb64_1    conda-forge
libcblas                  3.9.0                     8_mkl    conda-forge
libclang                  14.0.6          default_hb5a9fac_1
libclang13                14.0.6          default_h8e68704_1
libdeflate                1.17                 h2bbff1b_1
libffi                    3.4.2                h8ffe710_5    conda-forge
libglib                   2.78.0               he8f3873_0    conda-forge
libiconv                  1.17                 h8ffe710_0    conda-forge
liblapack                 3.9.0                     8_mkl    conda-forge
libpng                    1.6.39               h19919ed_0    conda-forge
libpq                     12.15                h906ac69_1
libtiff                   4.5.1                hd77b12b_0
libwebp                   1.3.2                hcfcfb64_1    conda-forge
libwebp-base              1.3.2                hcfcfb64_0    conda-forge
libxml2                   2.10.4               hc3477c8_0    conda-forge
libxslt                   1.1.37               h0192164_0    conda-forge
libzlib                   1.2.13               hcfcfb64_5    conda-forge
matplotlib                3.8.0            py39hcbf5309_2    conda-forge
matplotlib-base           3.8.0            py39hf19769e_2    conda-forge
mkl                       2020.4             hb70f87d_311    conda-forge
munkres                   1.1.4              pyh9f0ad1d_0    conda-forge
numpy                     1.26.0           py39hddb5d58_0    conda-forge
openjpeg                  2.5.0                ha2aaf27_2    conda-forge
openssl                   3.1.4                hcfcfb64_0    conda-forge
packaging                 23.2               pyhd8ed1ab_0    conda-forge
pcre2                     10.40                h17e33f8_0    conda-forge
pillow                    10.0.1           py39h045eedc_0
pip                       23.3             py39haa95532_0
ply                       3.11                       py_1    conda-forge
pyparsing                 3.1.1              pyhd8ed1ab_0    conda-forge
pyqt                      5.15.7           py39hd77b12b_0
pyqt5-sip                 12.11.0          py39hd77b12b_0
python                    3.9.18               h1aa4202_0
python-dateutil           2.8.2              pyhd8ed1ab_0    conda-forge
python_abi                3.9                      2_cp39    conda-forge
qt-main                   5.15.2               h879a1e9_9
qt-webengine              5.15.9               h5bd16bc_7
qtwebkit                  5.212                h2bbfb41_5
setuptools                68.0.0           py39haa95532_0
sip                       6.6.2            py39hd77b12b_0
six                       1.16.0             pyh6c4a22f_0    conda-forge
sqlite                    3.41.2               h2bbff1b_0
tk                        8.6.13               hcfcfb64_0    conda-forge
toml                      0.10.2             pyhd8ed1ab_0    conda-forge
tornado                   6.3.3            py39ha55989b_1    conda-forge
tzdata                    2023c                h04d1e81_0
ucrt                      10.0.22621.0         h57928b3_0    conda-forge
unicodedata2              15.1.0           py39ha55989b_0    conda-forge
vc                        14.2                 h21ff451_1
vc14_runtime              14.36.32532         hdcecf7f_17    conda-forge
vs2015_runtime            14.36.32532         h05e6639_17    conda-forge
wheel                     0.41.2           py39haa95532_0
xz                        5.4.2                h8cc25b3_0
zipp                      3.17.0             pyhd8ed1ab_0    conda-forge
zlib                      1.2.13               hcfcfb64_5    conda-forge
zstd                      1.5.5                h12be248_0    conda-forge

**Comment by radarhere** [comment]
Hi. This type of error has been encountered before - #2945, #3755 and https://github.com/conda-forge/pillow-feedstock/issues/45

Looking over those, here are some suggestions.

- 'conda install --channel conda-forge pillow=10.1.0'
- 'conda update conda'
- 'conda update --all'
- 'conda install -c anaconda pillow'
- Installing pywin32-ctypes

What specific version of Anaconda are you using? Are you running in 32-bit or 64-bit mode?

If you have the time, the most effective way to get help would be to reproduce your problem in Docker or on GitHub Actions and link to that from here, so that we can test solutions directly.

**Comment by mygithubaccount12** [comment]
@radarhere thank you for your quick response.

Based on your suggestion I started to work through the list of your suggestions and ran `conda update conda` first - it did the trick.  

I'm embarrassed and relieved at the same time.  I burned a lot of hours trying all kinds of stuff when it was something so fundamental to resolve.

Such is life.

Thank you for helping me.

**Comment by jlgutenson** [comment]
I was having a totally separate issue but it was related to the same error everyone else was experiencing. I was receiving the same error message with Pyarrow. Downgrading my conda environment to Python version 3.10 and installing Pillow version 9.0.1 worked for me as well.

**Comment by brunocalet** [comment]
I'm late to the party, but this may help someone as it solved my problem with import error after none of previous fix suggestions worked.

First, I opened cmd in admin mode. Then I did this:

`sfc /scannow`

Afterwards, I restarted my computer.

Then I went into installed apps, and repaired Microsoft Visual C++ installations (all of them).

One more restart after that and everything worked fine.
