### ISSUE TITLE
PIL.UnidentifiedImageError on png file

### ISSUE THREAD

**Issue by MayankFawkes** [python-pillow/Pillow#7504]
### What did you do?
Trying to open one png file
### What did you expect to happen?
open and skip all the file checks
### What actually happened?
returning error
### What are your OS, Python and Pillow versions?

* OS:  WIN 11
* Python:  3.10.11
* Pillow: 10.0.1/10.1.0

```python
from PIL import Image
import requests
from io import BytesIO

IMG_URL = "https://i.ibb.co/QN1JyLp/IMG-20231030-100421.png"

response = requests.get(IMG_URL)
image_object = BytesIO(response.content)

img = Image.open(image_object)
# do things here
img.show()
```

i tried some third party tools to check the PNG file. [https://processing.compress-or-die.com/repair-process](https://processing.compress-or-die.com/repair-process)

```
1	Combined all IDAT chunks.
2	Fixed CRC checksum for chunk "eXIf".
3	Fixed CRC checksum for chunk "IDAT".
```
is there a way i can skip those checks in pillow, and just open it in insecure way of something.

**Comment by radarhere** [comment]
You can set `LOAD_TRUNCATED_IMAGES`.

```python
from PIL import ImageFile
ImageFile.LOAD_TRUNCATED_IMAGES = True
```

**Comment by MayankFawkes** [comment]
alright that's working

**Comment by radarhere** [comment]
https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png
> By default Pillow doesn’t allow loading of truncated PNG files, set [ImageFile.LOAD_TRUNCATED_IMAGES](https://pillow.readthedocs.io/en/stable/reference/ImageFile.html#PIL.ImageFile.LOAD_TRUNCATED_IMAGES) to override this.

https://pillow.readthedocs.io/en/stable/reference/ImageFile.html#PIL.ImageFile.LOAD_TRUNCATED_IMAGES
> PIL.ImageFile.LOAD_TRUNCATED_IMAGES = False
> Whether or not to load truncated image files. User code may change this.

As of #1991, the setting allows PNGs to skip bad PNG checksums.

**Comment by MayankFawkes** [comment]
Alright thanks
