### ISSUE TITLE
Bundled license texts are incomplete for FreeType 2

### ISSUE THREAD

**Issue by stefan6419846** [python-pillow/Pillow#7506]
Thank you for providing the license texts of external packages within the wheel distributions! This is highly appreciated.

Skimming through the files, I nevertheless observed some incomplete texts/references which probably should be included into the `FREETYPE2.txt` file at https://github.com/python-pillow/Pillow/blob/main/wheels/dependency_licenses/FREETYPE2.txt: `FREETYPE2.txt` references the not available `docs/FTL.TXT`, `docs/GPLv2.TXT`, `src/bdf/README` and `src/pcf/README` files, which probably are relevant for further usage.

**Comment by aclark4life** [comment]
@stefan6419846 Thanks! Are you able to send a PR?
