### ISSUE TITLE
JPEG2000 image read incorrectly

### ISSUE THREAD

**Issue by sl2c** [python-pillow/Pillow#7511]
When doing
```python
from PIL import Image
Image.open('test.jp2').show()
```
on the file
[test.jp2.zip](https://github.com/python-pillow/Pillow/files/13223024/test.jp2.zip)
an apparently incorrect result is displayed.

I have checked this with both the latest Pillow-10.1.0 as well as my reference Pillow-9.4.0: both results are identical and both are incorrect.

**Comment by radarhere** [comment]
Am I correct in saying that you created this image

<img src="https://github.com/python-pillow/Pillow/assets/3112309/71af2f2b-79e6-4dcf-869e-421a1433e4af" width="400" />


but were expecting this?

<img src="https://github.com/python-pillow/Pillow/assets/3112309/963488af-1728-4f6a-b588-4e76ef846107" width="400" />

**Comment by sl2c** [comment]
I vaguely remember that I got this image from some student lecture notes that were freely distributed on the web. That is to say, I am not the author of this image.

**Comment by radarhere** [comment]
It seems to me that https://github.com/uclouvain/openjpeg/pull/1463 is relevant, and we might have an easier time addressing this once the next version of OpenJPEG is released.

**Comment by radarhere** [comment]
It turns out that https://github.com/uclouvain/openjpeg/pull/1463 didn't help.

I've created https://github.com/python-pillow/Pillow/pull/7867 to resolve this.
