### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file (DDS file)

### ISSUE THREAD

**Issue by finalcraftRu** [python-pillow/Pillow#7517]
Hello! i try to make .DDS to .PNG converter but when i call code it raises PIL.UnidentifiedImageError: cannot identify image file
```python
# Imports
from PIL import Image
import os

# Define names
file = 'C:\DDS\Portrait_Britain_Alan_Brooke.dds'
l = len(os.listdir("SOV"))+1
name = f'SOV/{l}.png'

# Load image
with Image.open(file) as im: # in this line error
    im.save(name)
```
screenshot of console:
![error](https://github.com/python-pillow/Pillow/assets/109862343/924e80c8-98f0-47f0-b334-2c5034f37d02)
this file:
[Portrait_Britain_Alan_Brooke.zip](https://github.com/python-pillow/Pillow/files/13239297/Portrait_Britain_Alan_Brooke.zip)

**Comment by radarhere** [comment]
Just as an explanation, the image contains uncompressed RGB data with a bitcount of 16 - it looks like it is compressing the three channels into the space normally allocated for two. Pillow doesn't yet support this configuration.

Is the image one that can be added to our test suite, and distributed under Pillow's license?

**Comment by finalcraftRu** [comment]
Yeah, I don't mind adding it, but this image was taken from the Hearts Of Iron 4 files

**Comment by radarhere** [comment]
I've created PR #7574 to resolve this. I created a test image derived from one of our existing images.
