### ISSUE TITLE
point() not supported for I;16B

### ISSUE THREAD

**Issue by monkeycc** [python-pillow/Pillow#7519]
tiff
300 dpi
16 bits
resolution unit 2

```python
from PIL import Image, ImageEnhance

im =Image.open("xx.tif").convert('RGB')
im.show("PIL")

# Image display in pure white
```

```python

from PIL import Image, ImageEnhance
im =Image.open("xx.tif").point(lambda x: x / 256).convert("L")
im.show("PIL")

#
Traceback (most recent call last):
  File "1.py", line 24, in <module>
    im =Image.open("xx.tif").point(lambda x: x / 256).convert("L")
  File "E:\anaconda3\envs\pil\lib\site-packages\PIL\Image.py", line 1834, in point
    return self._new(self.im.point(lut, mode))
ValueError: point operation not supported for this mode

```

**Comment by radarhere** [comment]
What is the mode of the image?

```python
from PIL import Image
im = Image.open("xx.tif")
print(im.mode)
```

**Comment by monkeycc** [comment]
> What is the mode of the image?
> 
> ```python
> from PIL import Image
> im = Image.open("xx.tif")
> print(im.mode)
> ```

I;16B

**Comment by radarhere** [comment]
If you're looking for an immediate solution, I think this should work.
```python
from PIL import Image, ImageEnhance
im = Image.open("xx.tif").convert("I;16").point(lambda x: x / 256).convert("L")
im.show("PIL")
```

**Comment by monkeycc** [comment]
> If you're looking for an immediate solution, I think this should work.
> 
> ```python
> from PIL import Image, ImageEnhance
> im = Image.open("xx.tif").convert("I;16").point(lambda x: x / 256).convert("L")
> im.show("PIL")
> ```

Can open images
But the image is black

**Comment by radarhere** [comment]
Could you attach a copy of the original image?

**Comment by monkeycc** [comment]
> Could you attach a copy of the original image?

[1.zip](https://github.com/python-pillow/Pillow/files/13248141/1.zip)

**Comment by monkeycc** [comment]
https://stackoverflow.com/questions/7247371/python-and-16-bit-tiff/43481563#43481563

```python
import numpy as np
from PIL import Image

im = np.array(Image.open("1.tif"))
image = Image.fromarray(im / np.amax(im) * 255)

print(image.mode)
# F

image.show("PIL")

```

This method has been found to open images
But image enhancement is not possible

```python
ImageEnhance.Sharpness
ImageEnhance.UnsharpMask
```

**Comment by radarhere** [comment]
See what you think of this.
```python
from PIL import Image
im = Image.open("1.tif").convert("I").point(lambda x: x / 256).convert("L")
im.show("PIL")
```

**Comment by monkeycc** [comment]
thanks
Problem solving
The code can be used
@radarhere
