### ISSUE TITLE
'ImageDraw' object has no attribute 'textsize'

### ISSUE THREAD

**Issue by hackerDashDash** [python-pillow/Pillow#7523]
I am trying to get the width and height of the text using a certain font. This is my code:

```python
image = Image.open(p) # path of image
d = ImageDraw.Draw(image)
font1 = ImageFont.truetype("font1.ttf", 80)
font2 = ImageFont.truetype("font2.ttf", 50)
text_size1 = d.textsize(wrapped_title, font1) # inputted text after textwrap.fill()
text_size2 = d.textsize(wrapped_artists, font2) # inputted text after textwrap.fill()
```

It keeps giving me this error:
```
Exception has occurred: AttributeError
'ImageDraw' object has no attribute 'textsize'
```

**Comment by radarhere** [comment]
Hi. ImageDraw.textsize was removed in Pillow 10. See https://pillow.readthedocs.io/en/stable/releasenotes/10.0.0.html#font-size-and-offset-methods for more information

**Comment by EDIflyer** [comment]
Thanks for the explanation, just spent a few hours trying to debug what was going wrong with my Luma OLED project - finally realised about this change! Will post a comment back on that project too to mention this deprecation.
