### ISSUE TITLE
AWS Lambda layer: get bbox font return width too big 

### ISSUE THREAD

**Issue by natuan62** [python-pillow/Pillow#7529]
### What did you do?
- FONT test: [HELVBLAK.ttf.zip](https://github.com/python-pillow/Pillow/files/13275824/HELVBLAK.ttf.zip). Another fonts tested still works fine.

- lambda layer pillow: https://drive.google.com/file/d/1BHQsFNpGIdC0iG-Y_QvtNcnzv5PI6ukR/view

- build pillow into layer aws lambda
- run code generate thumbnail for font

```python
inputFileTmp = /tmp/helvblak.ttf

s3Object = s3Client.get_object(
        Bucket,
        Key
 )

with open(inputFileTmp, "wb") as f:
        f.write(s3Object['Body'].read())

def generateThumbnail(inputFileTmp, outputThumbTmp, text):
    size = 90
    img = Image.new("RGBA", (2, 2), 'white')
    draw = ImageDraw.Draw(img)
    image_font = ImageFont.truetype(inputFileTmp, size)
    bounding_box = draw.textbbox((0, 0), text, font=image_font)

    print(f"thumbnail bbox {bounding_box}")

    if bounding_box[2] > 1200:
        current_size = size
        while bounding_box[2] > 1200:
            current_size -= 5
            image_font = ImageFont.truetype(inputFileTmp, current_size)
            bounding_box = draw.textbbox((0, 0), text, font=image_font)

    img_width = bounding_box[2] - bounding_box[0]
    img_height = bounding_box[3] - bounding_box[1]
    img_size = (img_width, img_height)
    img = img.resize(img_size)
    draw = ImageDraw.Draw(img)
    draw.text((-bounding_box[0], -bounding_box[1]), text, fill="black", font=image_font)
    img.save(outputThumbTmp)
    return True
```

### What did you expect to happen?

- return bbox correct width height like when testing on localhost

```
thumbnail bbox (0, 10, 493, 69)
```

![image](https://github.com/python-pillow/Pillow/assets/10808157/41b2e187-ef3e-4935-9c63-59bbc84f2450)

### What actually happened?

- return bbox with width too big

![image](https://github.com/python-pillow/Pillow/assets/10808157/43b9862e-0028-490a-9158-2f95d39b80c6)

### What are your OS, Python and Pillow versions?

* OS: (dockerfile FROM --platform=linux/arm64 public.ecr.aws/sam/build-python3.10:latest)
* Python: 3.10
* Pillow: 10.1.0 (built layer from wheel)

**Comment by natuan62** [comment]
When load font with https://opentype.js.org/. Seem it display incorrect

(https://freefontsdownload.net/free-helvetica-black-semibold-font-74265.htm)

![image](https://github.com/python-pillow/Pillow/assets/10808157/4bf38ac2-ca39-4697-97c6-7e3ba5f52cb9)

**Comment by nulano** [comment]
What output do you get with the following (both local and on aws)?

```python
from PIL import features
print(features.check("raqm"))
print(features.version("raqm"))
```

**Comment by natuan62** [comment]
- local output

```
Raqm available: True
Raqm version: 0.10.1
FreeType version: 2.13.1
```

- aws output
```
```

**Comment by natuan62** [comment]
@nulano thanks for your quick reply

Here is output

- local output

```
Raqm available: True
Raqm version: 0.10.1
FreeType version: 2.13.1
```

- aws output
```
Raqm available: True
Raqm version: 0.10.1
FreeType version: 2.13.2
```

**Comment by natuan62** [comment]
Hi @nulano seem this font has problem with kerning

[HELVBLAK.ttf.zip](https://github.com/python-pillow/Pillow/files/13315313/HELVBLAK.ttf.zip)

https://github.com/python-pillow/Pillow/assets/10808157/8cb723e2-4964-4e6b-91ab-08b0dc1521af

**Comment by nulano** [comment]
I'm sorry, but I'm not sure I understand.

> After I upgrade pillow (on local) from 10.0.0 => 10.1.0. now output local is same on aws

So everything works fine now?

**Comment by natuan62** [comment]
> I'm sorry, but I'm not sure I understand.
> 
> > After I upgrade pillow (on local) from 10.0.0 => 10.1.0. now output local is same on aws
> 
> So everything works fine now?

Oh sorry for confuse information

"output local is same on aws" => meaning after update layer to 10.1.0 on lambda. Now both lambda and local print variables has same values 

```
Raqm available: True
Raqm version: 0.10.1
FreeType version: 2.13.2
```

**Comment by nulano** [comment]
Ok, but does the code work as expected or not?

**Comment by natuan62** [comment]
It's still not working

- here image with too width =))
![111](https://github.com/python-pillow/Pillow/assets/10808157/2131b993-0050-4b57-9951-0748baeb9ccd)

But if I disable **-kern** features, it'll works fine

```
# bounding_box = draw.textbbox((0, 0), text, font=image_font)

 =>  bounding_box = draw.textbbox((0, 0), text, font=image_font, features=["-kern"])
    
# draw.text((-bounding_box[0], -bounding_box[1]), text, fill="black", font=image_font)

=> draw.text((-bounding_box[0], -bounding_box[1]), text, fill="black", font=image_font, features=["-kern"])
    ```

**Comment by radarhere** [comment]
Thanks for figuring out that there is a difference with 'kern'.

A simple script to demonstrate the problem on my machine is
```python
from PIL import ImageFont
font = ImageFont.truetype("HELVBLAK.ttf", 90)
print(font.getbbox("He"))
print(font.getbbox("He", features=["-kern"]))
```
which gives two wildly different widths.
```
(0, 11, 2850, 70)
(0, 11, 122, 70)
```

From past experience, I expect this is a problem with the font itself, rather than Pillow or Freetype. Would you like me to e-mail freetype@nongnu.org and see if they agree?

**Comment by natuan62** [comment]
@radarhere Thank you for reply and support email to freetype !!

**Comment by radarhere** [comment]
You've said that it no longer works fine on your local when you upgraded to Pillow 10.1.0. So that doesn't sound as simple as AWS vs your local.

Actually, upon further investigation, I found that switching to basic layout fixes the problem. So if you update your code to specify the `layout_engine` as `ImageFont.Layout.BASIC`, is that sufficient?
```python
image_font = ImageFont.truetype(inputFileTmp, size, layout_engine=ImageFont.Layout.BASIC)
image_font = ImageFont.truetype(inputFileTmp, current_size, layout_engine=ImageFont.Layout.BASIC)
```

If you're not concerned about non-English text, then this will actually be faster as well, as per https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype
> Raqm layout is recommended for all non-English text. If Raqm layout is not required, basic layout will have better performance.

**Comment by natuan62** [comment]
Oh, I updated my answer in https://github.com/python-pillow/Pillow/issues/7529#issuecomment-1806571118

With local and testing pillow 10.1.0 (same versions package with lambda). this font works fine
![Screenshot 2023-11-13 at 16 19 48](https://github.com/python-pillow/Pillow/assets/10808157/9f24df03-a278-4252-828f-12f96d045b9a)

**Comment by radarhere** [comment]
Have you tried changing the `layout_engine` as I suggested?

**Comment by natuan62** [comment]
On lambda I tried change **layout_engine=ImageFont.Layout.BASIC** before but it not working. Only set **features=["-kern"]** it work

**Comment by radarhere** [comment]
So the problem occurs only for this font and only on AWS. You've established from [another website that the problem is with the kerning and this font specifically](https://github.com/python-pillow/Pillow/issues/7529#issuecomment-1805051408), and when you disable kerning, the problem is fixed.

Allow me to ask this - why isn't that sufficient as a solution? You know the font is broken, or at least has an uncommon way of handling kerning, and you know how to work around it. Are you concerned that this may happen with other fonts? Are you concerned that your AWS environment might have other bugs as a result of whatever caused this?

**Comment by natuan62** [comment]
Oh simply I just want better understand If you know anything about why on lambda got problem. !!

**Comment by nulano** [comment]
> Actually, upon further investigation, I found that switching to basic layout fixes the problem. So if you update your code to specify the layout_engine as ImageFont.Layout.BASIC, is that sufficient?

FWIW, kerning does not work with basic layout (https://github.com/python-pillow/Pillow/issues/5191#issuecomment-756286205), so that is not surprising.
