### ISSUE TITLE
Feature request "BGRA" mode

### ISSUE THREAD

**Issue by JC3** [python-pillow/Pillow#7537]
A BGRA mode for `Image` constructors would be really useful when dealing with BGRA image data, so you don't have to incur the extra processing and coding overhead of swapping channels. (Especially processing overhead where Python loops are involved, it really slows things down.)

**Comment by radarhere** [comment]
Could you explain why you are using BGRA data in the first place? It could be helpful to understand where this need comes from.

You say that what you have to do at the moment is slow. Could you provide example code to demonstrate?

**Comment by homm** [comment]
You can import BGRA data when you are dealing with it using `PIL.Image.frombytes` or `PIL.Image.Image.frombytes`.

**Comment by homm** [comment]
> (Especially processing overhead where Python loops are involved, it really slows things down.)

I believe you don't understand how Pillow works There are no Python loops which swaps channels, of course.

**Comment by JC3** [comment]
> Could you explain why you are using BGRA data in the first place? It could be helpful to understand where this need comes from.

I have a stereo vision camera whose API provides image data in BGRA format.

> You say that what you have to do at the moment is slow. Could you provide example code to demonstrate?

```
def saveimage (data: bytes, width, height, filename):

    # swap R and B
    swapped = bytearray(data)
    for n in range(0, len(data), 4):
        swapped[n], swapped[n+2] = swapped[n+2], swapped[n]
        
    # use RGBA mode
    image = Image.frombytes("RGBA", (width, height), swapped)
    image.save(filename)
```

@homm 
> You can import BGRA data when you are dealing with it using `PIL.Image.frombytes` or `PIL.Image.Image.frombytes`.

That does not appear to be the case. According to https://pillow.readthedocs.io/en/stable/handbook/concepts.html#concept-modes, there is no BGRA mode.

> I believe you don't understand how Pillow works There are no Python loops which swaps channels, of course.

See code snippet above for a Python loop that swaps channels.

**Comment by JC3** [comment]
> You can use `PIL.Image.frombytes` to load data from other modes, not only listed as possible image modes.
> 
> ```python
> im = Image.frombytes('RGBA', (width, height), data, 'raw', 'BGRA')
> ```

This is great, thank you; is this documented anywhere? I'm having trouble finding the `raw` decoder docs.

**Comment by radarhere** [comment]
The [`frombytes()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.frombytes) documentation states
> You can also use any pixel decoder supported by PIL. For more information on available decoders, see the section [Writing Your Own File Codec](https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-image-plugin.html#file-codecs).

The "Writing Your Own File Codec" page contains a section called ["The raw decoder"](https://pillow.readthedocs.io/en/stable/handbook/writing-your-own-image-plugin.html#the-raw-decoder)
> The raw decoder is used to read uncompressed data from an image file. It can be used with most uncompressed file formats, such as PPM, BMP, uncompressed TIFF, and many others. To use the raw decoder with the [PIL.Image.frombytes()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.frombytes) function, use the following syntax

You can read more at the link. "BGRA" is the "raw mode", which "The raw decoder" also describes.

> The raw mode field is used to determine how the data should be unpacked to match PIL’s internal pixel layout. PIL supports a large set of raw modes; for a complete list, see the table in the Unpack.c module.

Unpack.c contains
https://github.com/python-pillow/Pillow/blob/556dd1e15c1c65e091d756eeedbc6c6ad6049e3b/src/libImaging/Unpack.c#L1624

**Comment by JC3** [comment]
@radarhere Awesome thank you!
