### ISSUE TITLE
Some MakerNotes altered after saving with getexif()

### ISSUE THREAD

**Issue by PescheHelfer** [python-pillow/Pillow#7545]
### What did you do?

- get the metadata of the original image using exiftools
- load a jpg image via Image.open()
- get the exif data via img.getexif()
- img.save(path, exif=exif_data)
- get the metadata of the resaved image using exiftools
- compare the maker block (Panasonic) of the outputs

### What did you expect to happen?
For the exif data to be identical, including the Manufacturer-specific information (MakerNotes)

### What actually happened?
Some MakerNote tags differ from the original.

#### Examples
	orig: Panasonic       AFPointPosition 0.5 0.5
	new:  Panasonic       AFPointPosition 0 0

	orig: Panasonic       PostFocusMerging        Post Focus Auto Merging or None
	new:  Panasonic       PostFocusMerging        Unknown (208666624 208797696)

	orig: Panasonic       FilterEffect    Expressive
	new:  Panasonic       FilterEffect    Unknown (260177920 260308992)

	orig: Panasonic       InternalNDFilter        0
	new:  Panasonic       InternalNDFilter        0.9996204453

	orig: Panasonic       TimeLapseShotNumber     0
	new:  Panasonic       TimeLapseShotNumber     267386880

### What are your OS, Python and Pillow versions?

* OS: Windows 10 Home 22H2
* Python: 3.11.0  
* Pillow: 10.0.1 

```python
from PIL import Image

with Image.open("Original.JPG") as img:
    exif = img.getexif()
    img.save("Resaved.JPG", quality=90, optimize=True, progressive=True, subsampling=2, exif=exif) 

# exiftool -s -G1 -t --composite Original.JPG
# exiftool -s -G1 -t --composite Resaved.JPG
# compare the Panasonic block of the outputs

```
![Original](https://github.com/python-pillow/Pillow/assets/8842081/fea9e3da-e02f-46c5-a0c5-abd504a89f19)

**Comment by radarhere** [comment]
Makernotes are specific to the manufacturer, and "[Most vendors do not publish their makernote specifications](https://exiv2.org/makernote.html)". So if your intention is to modify the data, I don't think we can provide a blanket solution to save all Makernote data correctly.

If your intention is not to modify the EXIF data, then you could
```python
from PIL import Image

with Image.open("in.jpg") as img:
    exif = img.info["exif"]
    img.save("out.jpg", quality=90, optimize=True, progressive=True, subsampling=2, exif=exif)
```

**Comment by PescheHelfer** [comment]
Thanks for your reply. My intention is not to modify the data, but to maintain it as it was in the original file. I will give your suggestion I try after work, thanks for that!
For me to understand: does img.info("exif") extract the exif data in a different way than getexif(), and possibly with different values?

**Comment by radarhere** [comment]
`getexif()` considers multiple sources for EXIF data - `img.info["exif"]` is one of them. Others are TIFF tags, XMP tags and early ImageMagick PNG EXIF data.

When `img.info["exif"]` is used, it is extracted from the image first, and then `getexif()` is called on it. Given that it has fewer transformations on it than `getexif()`, you shouldn't need to be concerned that it is less accurate than `getexif()`.

**Comment by PescheHelfer** [comment]
Thanks a lot, img.info["exif"] retrieves the data correctly, not, the makernotes are perfectly preserved.
