### ISSUE TITLE
[10.1.0 regression] Palette images save as blank PDFs

### ISSUE THREAD

**Issue by BertrandBordage** [python-pillow/Pillow#7554]
Minimal example (you can use [this tiny PNG](https://github.com/python-pillow/Pillow/assets/1119169/d8d45152-7734-4fe3-a2d3-fb49839a0893) for example):

```python
from PIL import Image

image = Image.open('test.png')
image = image.convert('P')
image.save('test.pdf')
```

Output PDF with Pillow 10.0.1:
![image](https://github.com/python-pillow/Pillow/assets/1119169/e3f02823-2aad-4490-acd8-695f90c6f15e)

Output PDF with Pillow 10.1.0:
![image](https://github.com/python-pillow/Pillow/assets/1119169/7ef6ccf8-a9e2-405c-99a6-6ae2ec4b253d)

Issue faced with Python 3.11.6 on Ubuntu 22.04 and Debian 12 (bookworm). I also had the same issue in Docker environments, so I could make a Docker image if needed.

**Comment by radarhere** [comment]
Testing, I find this was caused by #7289.

I've created PR #7555 to resolve this.

**Comment by BertrandBordage** [comment]
So quick, incredible job @radarhere!
