### ISSUE TITLE
Weird behavior in PIL 9.5 deprecated version of getsize()

### ISSUE THREAD

**Issue by xtlc** [python-pillow/Pillow#7556]
* OS: Windows, Linux
* Python: 3.9, 3.11, 3.12
* Pillow: 9.5, 10.1.0

I wanted to create a test for upgrading a project from PIL 9.5 to >10. I use Windows as test environment but usually deploy everything on Linux. We had some servers that got a new Debian -> new python versions.

**Windows, Python 3.12, PIL 9.5**
I built a fairly simple testscript, that started to fail silently very often and I could narrow it down to this part:

```python
from PIL import ImageFont

font = ImageFont.truetype(font = "arial.ttf", size = 32)
words = ["tesst", "test"]
for word in words:
    print(word, "::", font.getsize(word))
```
this results in:
```bash
tesst :: (120, 29)
(venv95) PS C:\Users\xtlc\Desktop\gentest>
```
so no exception, no nothing for the string `test`. It also does not work if I switch the positions of the string inside the list. When running this in some loops it sometimes works. I tested other things like:
```python
words = ["teet", "tsst", "tset", "estt", "test"]
```
resulting in:
```bash
teet :: (96, 29)
tsst :: (96, 29)
tset :: (96, 29)
estt :: (96, 29)
``` 
(`test` does fail silently again). 
So I dug a little bit further and tried the following:

```python
from PIL import ImageFont
print("test", "::", font.getbbox("test"))
```
no result -> fails silently, same with `getlength()` instead of `getbbox()`.

I tried to reproduce the testcase using a random word generator and testing for 250 words of any length but failed:

- Python 3.11 on a debian vBox with PIL 9.5 -> cannot reproduce
- Python 3.12 on windows with PIL 10.1.0 -> cannot reproduce
- Python 3.12 on a debian vBox with PIL 9.5 -> cannot reproduce

**Comment by nulano** [comment]
I can't reproduce on Windows 11 with Python 3.11 and Pillow 9.5.0.

How did you install Pillow?
What output do you get with the following code?

```python
from PIL import features
print("Raqm available:", features.check("raqm"))
print("Raqm version:", features.version("raqm"))
print("FreeType version:", features.version("freetype2"))
```

**Comment by xtlc** [comment]
I installed pillow using `python -m pip install pillow==9.5.0`. Regarding your question:
```
Python 3.12.0 (tags/v3.12.0:0fb18b0, Oct  2 2023, 13:03:39) [MSC v.1935 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import PIL
>>> from PIL import features
>>> print("Raqm available:", features.check("raqm"))
Raqm available: False
>>> print("Raqm version:", features.version("raqm"))
Raqm version: None
>>> print("FreeType version:", features.version("freetype2"))
FreeType version: 2.13.0
>>> print(PIL.__version__)
9.5.0
```

**Comment by nulano** [comment]
Ok, I can reproduce the crash with Python 3.12 and Pillow 9.5.0, but not Pillow 10.0.0.
Looking at https://pillow.readthedocs.io/en/stable/installation.html#python-support, Pillow 9.5.0 does not officially support Python 3.12.
Pillow 9.5.0 was most likely built using Python 3.12.0 alpha 6 (the logs have expired by now), I imagine the issue has been fixed since than.

If you really need to use Pillow 9.5.0, can you use Python 3.11 instead?

**Comment by xtlc** [comment]
I already have a workaround, but found the issue interesting enough to report it, as the "one string works but the other one does not" error odd.

**Comment by hugovk** [comment]
Thanks for the report, it's definitely a headscratcher!

Anyway, we won't be making any more updates to 9.x, only 10.x, and it's already working in 10.x so there's not too much to do here unless someone is curious enough to go on a hunt :)
