### ISSUE TITLE
Animated webps and gifs with low frame duration play very slowly

### ISSUE THREAD

**Issue by elirnm** [python-pillow/Pillow#7588]
Making an animated webp or gif with a low number for the frame duration argument (meaning high fps) results in an image that plays very slowly, more slowly than an image with a slightly higher frame duration. The cutoff seems to be at 19 for gif and 10 for webp - above this they get faster with lower frame duration as you'd expect and at or below the cutoff they play at a fixed slow speed (and don't change speed at all - frame duration 19 is the same as frame duration 1 for a gif).

### What did you do?
Made an animated webp with a low frame duration argument (high fps)

### What did you expect to happen?
The webp would play with high fps

### What actually happened?
The webp played very slowly

### What are your OS, Python and Pillow versions?

* OS: Windows 11
* Python: 3.12.0
* Pillow: 10.1.0

The first gif has duration=30, the second gif has duration=15. The second should play faster than the first.
![test30](https://github.com/python-pillow/Pillow/assets/19817004/bd7bb27c-212e-4719-9b21-694f34a326ef)
![test15](https://github.com/python-pillow/Pillow/assets/19817004/90b4481d-6f7f-4a9b-a41b-e7438002319e)

```python
from PIL import Image, ImageDraw

img = Image.new("RGBA", (150, 150), "black")
frames = []
for i in range(60):
    frame = img.copy()
    draw = ImageDraw.Draw(frame)
    draw.rectangle((i, i, i + 20, i + 20), "yellow")
    frames.append(frame)
time1 = 30
time2 = 15
time3 = 10
frames[0].save('test30.gif', save_all=True, append_images=frames[1:], duration=time1, loop=0)
frames[0].save('test30.webp', save_all=True, append_images=frames[1:], duration=time1, loop=0)
frames[0].save('test15.gif', save_all=True, append_images=frames[1:], duration=time2, loop=0)
frames[0].save('test15.webp', save_all=True, append_images=frames[1:], duration=time2, loop=0)
frames[0].save('test10.gif', save_all=True, append_images=frames[1:], duration=time3, loop=0)
frames[0].save('test10.webp', save_all=True, append_images=frames[1:], duration=time3, loop=0)
```

**Comment by Yay295** [comment]
This isn't a bug in Pillow, this is a limit imposed by web browsers. If you have `ffplay` available on your system you can use it to see your "slow" animations play at their specified speed.

**Comment by elirnm** [comment]
I was afraid it might be a limit of the format. But on my system I get the same results with ffplay that I get with browsers and with the default Windows photo viewer.

**Comment by radarhere** [comment]
Googling, I find similar results.

https://superuser.com/questions/1449366/do-60-fps-gifs-actually-exist-or-is-the-maximum-50-fps experiences a speed limit when creating GIFs with ffmpeg.

https://wunkolo.github.io/post/2020/02/buttery-smooth-10fps/
> The highest fps possible representable in the GIF file format specification is 100 fps (0.01s), which no browser supports and 60hz consumer screens cannot faithfully display this anyways. Browser-engine image decoders will automatically reset this framerate to 10fps and play it x10 times slower. If this gif is moving very slow to you, it is because your browser reset the speed to 10fps.

https://community.aseprite.org/t/animated-gif-export-rounding-frame-durations/1181/3
> In fact some browsers/players only play gifs with frame durations of 20 ms (0.02s per frame = 50 fps) or higher (slower than 50fps). Not sure if that’s true any more.

https://filmora.wondershare.com/video-editor/video-to-gif-60-fps.html
> The maximum fps for a GIF is 100 FPS, but browsers or consumer screens do not support it. The browser-engine image decoders will automatically reduce the framerate to 10 fps, playing it ten times slower. If a GIF appears slow, the browser has reset the speed to 10 fps. Some software and devices may support higher frame rates.

**Comment by elirnm** [comment]
I can confirm that this is just a limitation of browsers (and some offline viewers as well) for both gif and webp. I was able to find viewers that support faster animations (qView for webp, irfanView for gif) and Pillow seems to create them correctly down to `duration=1` for webp and `duration=10` for gif (=100 fps as the links quoted above say).
