### ISSUE TITLE
Enable updating PRs from `main`

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#7595]
@aclark4life Please could you enable this setting at https://github.com/python-pillow/Pillow/settings so we can update PRs from `main`?

![image](https://github.com/python-pillow/Pillow/assets/1324225/b2d947fd-f21a-4429-b13f-945e5e7fd879)

_Originally posted by @hugovk in https://github.com/python-pillow/Pillow/issues/7502#issuecomment-1818482831_

This would also help us in PRs like https://github.com/python-pillow/Pillow/pull/7593#issuecomment-1836950006: we can update it once an unrelated bug is fixed in `main`.

**Comment by radarhere** [comment]
I am usually able to update PRs, and have just merged main into #7593.

My guess is that when #7502 was created, the 'Allow edits and access to secrets by maintainers' checkbox was unchecked by that user.

**Comment by wiredfool** [comment]
I just set that option:

![image](https://github.com/python-pillow/Pillow/assets/19792/c824d1b1-c41f-474b-b140-b64f1e386327)

**Comment by radarhere** [comment]
Thanks! Having a button the UI now makes the process much easier.
