### ISSUE TITLE
Compiling with libimagequant dependency

### ISSUE THREAD

**Issue by poe7** [python-pillow/Pillow#7596]
After trying to compile pillow with libimagequant dependency enabled, i still get the same error.
![IMG_9923](https://github.com/python-pillow/Pillow/assets/128154193/e72ffd37-8029-4468-9cb1-b3932797abcb)
![IMG_9922](https://github.com/python-pillow/Pillow/assets/128154193/7a7eed9f-cb3c-40ea-9498-96568a55b7f8)

**Comment by radarhere** [comment]
What operating system are you using?
What library are you using that is emitting the "Uhandled error when trying to build the pallete"? Are you able to post a complete example of the code that you're running?

**Comment by poe7** [comment]
> The user also posted these images in Gitter, with the text
> 
> > im trying to compile pillow with libimagequant but everytime i try to quantize with Quantize.LIBIMAGEQUANT method i get an error.
> 
> What operating system are you using? What library are you using that is emitting the "Uhandled error when trying to build the pallete"? Are you able to post a complete example of the code that you're running?

Im using ubuntu Ubuntu 20.04.6 LTS x86_64

```py
from PIL import Image
buf=io!.BytesIO(await author.avatar.read())
with Image.open(buf) as img:
  img.quantize(10, method=Image.Quantize.LIBIMAGEQUANT, dither=0)
```

**Comment by radarhere** [comment]
Have you tried uninstalling Pillow, checking that it is not installed by seeing that it fails to import, and then tried installing again?

**Comment by radarhere** [comment]
When I try `python3 -m pip install --upgrade Pillow -C imagequant=enable --no-cache-dir` on my macOS machine, it still uses the precompiled wheel.

Try adding ` --no-binary :all:` as another argument to the command.

**Comment by poe7** [comment]
> python3 -m pip install --upgrade Pillow -C imagequant=enable --no-cache-dir

yes that worked, thank you :)
