### ISSUE TITLE
[Request] making `_getexif()` public

### ISSUE THREAD

**Issue by konbraphat51** [python-pillow/Pillow#7630]
Currently, the `getexif()` method only returns top-level ones, so not less users who want to have ALL exif properties are using `_getexif()` which is a private method. 

I guess that typically these private methods could be deprecated someday without warning, so I want this to be public and be safe to use.

My suggestion is to add a parameter in `getexif()` such as `getexif(top_level=True/False)`

**Comment by radarhere** [comment]
Hi. Are you aware of `getexif().get_ifd()`? You can use this to access information beyond the top level.

For documentation about this, you can see https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Exif

**Comment by konbraphat51** [comment]
Oh sorry, I didn’t know that
Thank you very much
