### ISSUE TITLE
ImageGrab.grab() region issue

### ISSUE THREAD

**Issue by JacobHagberg** [python-pillow/Pillow#7677]
### What did you do?

Used image grab on Mac OS, and the region input seems to not handle anything above a certain y1 value

### What did you expect to happen?

I expect the region of the ImageGrab.grab() to return an image of the screen of the region specified, but it throws an error

### What actually happened?

It threw an rect (836.0, 982.0, 500.0, 218.0) does not intersect any displays error

### What are your OS, Python and Pillow versions?

* OS: Mac OS 13.4, M1 Pro
* Python: 3.11.1
* Pillow: 10.1.0

This code takes an image of the region [836, i, 1336, 1200]. where i is incremented upward until i=982, where it throws an error. The result of `print(image1.size)` is (3024, 1964) BTW. Not sure what is going on here, please reach out if you have further questions. 
```python
from PIL import ImageGrab

image1 = ImageGrab.grab()
print(image1.size)

for i in range(950, 1050):
    image2 = ImageGrab.grab([836, i, 1336, 1200])
    print(i)
    print(image2.size)
```

output:
```pytb
973
(500, 227)
974
(500, 226)
975
(500, 225)
976
(500, 224)
977
(500, 223)
978
(500, 222)
979
(500, 221)
980
(500, 220)
981
(500, 219)
rect (836.0, 982.0, 500.0, 218.0) does not intersect any displays
Traceback (most recent call last):
  File "/Users/jacobhagberg/Documents/PythonCode/EveOnlineAutopilot/QuickTest.py", line 7, in <module>
    image2 = ImageGrab.grab([836, i, 1336, 1200])
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PIL/ImageGrab.py", line 38, in grab
    im = Image.open(filepath)
         ^^^^^^^^^^^^^^^^^^^^
  File "/Library/Frameworks/Python.framework/Versions/3.11/lib/python3.11/site-packages/PIL/Image.py", line 3305, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file '/var/folders/2t/fyymv8314fn56nytzjvtq93r0000gn/T/tmpxroi8hx0.png'
```

**Comment by radarhere** [comment]
Your script runs fine on my macOS machine without a problem.

Internally, Pillow is just calling `screencapture` on macOS. So if you run `screencapture -R 836,981,500,219 -x out.png` in your Terminal, does the same "rect (836.0, 982.0, 500.0, 218.0) does not intersect any displays" error appear?

**Comment by JacobHagberg** [comment]
Yes, the same error appears when I run the command as the error in the python script.

**Comment by JacobHagberg** [comment]
When I run "screencapture -R 836,982,1336,1200 -x out.png" same as I did with the problematic one in the python script, had the same error. 836,982,500,219 was not the region I was trying to capture, it was 836,982,1336,1200

**Comment by radarhere** [comment]
So, on the one hand, we have macOS's `screencapture` error. I'm able to replicate the error if I sufficiently increase the height. I don't think there's anything to fix there as such - it looks like you're trying to take a screenshot of an area outside of your monitor.

On the other hand, let's talk about `ImageGrab.grab()`'s box argument.

Pillow receives co-ordinate boxes as [`(x1, y1, x2, y2)`](https://pillow.readthedocs.io/en/stable/handbook/concepts.html#coordinate-system).
`man screencapture` will tell you that `screencapture`'s `-R` flag can "Capture rectangle using format x,y,width,height".  So that is why the error message is different, as it is coming from `screencapture`.
Pillow is aware of this, and [adjusts the co-ordinates to this format](https://github.com/python-pillow/Pillow/blob/31c8dacdc727673e9099f1ac86019714cdccec67/src/PIL/ImageGrab.py#L37).

**Comment by JacobHagberg** [comment]
I think I figured it out, when I go into the command shift 4 screenshot region thing on mac os, the screenshot has a y max of 981. The cords for the screen capture are half of what they are for the image resolution of a screenshot on my computer, I thought that the image gram region was x1, y1, x2, y2 of the image resolution, but it is of the mouse coordinates instead. I just misunderstood the coordinate system here, my mistake.

**Comment by radarhere** [comment]
I've created #7678 to update the documentation. You can see a preview of it at https://pillow--7678.org.readthedocs.build/en/7678/reference/ImageGrab.html#PIL.ImageGrab.grab

**Comment by JacobHagberg** [comment]
Looks good, that is much clearer.

**Comment by JacobHagberg** [comment]
Wait, I read the code here: https://github.com/python-pillow/Pillow/blob/ded2c8b1d145f84cf93d176cc1c82c95b2f8471a/src/PIL/ImageGrab.py#L43 for the image grab, and if it is mac os, it resizes the image to effectively half of the original resolution on mac os and Linux, but only if there is a bbox passed as an argument. If the whole image is grabbed, it is full resolution, but it is resized if the region is selected, that is also not mentioned in the docs, or maybe shouldn't be a feature at all. 

When I ran the code:

from PIL import ImageGrab

image = ImageGrab.grab()
print(image.size)
image2 = ImageGrab.grab([0,0,1512, 982])
print(image2.size)
image.show()
image2.show()

[0,0,1512, 982] being the full-screen box, image1 size was (3024, 1964), while image2 size was (1512, 982). Not sure if this is intended.

**Comment by radarhere** [comment]
> or maybe shouldn't be a feature at all

If you consider this from the perspective of the rest of Pillow, such as [`im.crop(box=...)`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.crop), I think it is more expected to have the rectangle co-ordinates produce an image that has dimensions ``(x2 - x1, y2 - y1)``.

> that is also not mentioned in the docs

I've created #7688 for this.

**Comment by JacobHagberg** [comment]
I guess this makes sense so, cropping after the grab would be the method used to get a portion of the screen without quality reduction.

**Comment by lifei** [comment]
when the process is running under super user permission, the system blocks pillow to grab image every time even after clicking allow one month.

**Comment by radarhere** [comment]
I'm not able to replicate your problem on macOS Sequoia. If you'd like to discuss your problem further, please open a new issue with more detail.
