### ISSUE TITLE
Image.transform data not well documented

### ISSUE THREAD

**Issue by AlexKubiesa** [python-pillow/Pillow#7683]
The [Image.transform](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.transform) documentation describes the `data` parameter as

> Extra data to the transformation method.

However, the documentation doesn't mention which data needs to be provided and in what format.

I am using perspective transform in a project and I was able to reverse engineer that a 1D numpy array of 8 floats works, but as I am lacking some of the theory behind it, it was unintuitive and I'm still not sure what the best way to generate those 8 numbers is.

**Comment by nulano** [comment]
With the exception of the perspective transform, I think the others are documented here: https://pillow.readthedocs.io/en/stable/PIL.html#module-PIL.ImageTransform
However, I agree that this is not well discoverable in the documentation.

**Comment by AlexKubiesa** [comment]
@nulano thank you for updating it!
