### ISSUE TITLE
Suggest adding camera support

### ISSUE THREAD

**Issue by monkeycc** [python-pillow/Pillow#7697]
Opencv is required every time the camera is used

Then convert PIL

Causing a large number of users to turn to OpenCV

If PIL can support cameras

So PIL users don't need to use opencv

Otherwise, using OpenCV would require using PIL conversion again

**Comment by homm** [comment]
> Causing a large number of users to turn to OpenCV

How large is this number?

**Comment by monkeycc** [comment]
All Python users
Read Camera
Only opencv can be used


Therefore, Python users can only use OpenCV
Not considering Pillow
Developing a habit for users to use


I think Pillow also needs to cultivate its own users
PIL can support cameras
Users will not consider OpenCV

Instead of OpenCV reading the camera
Use the pillow to switch again

of course
This is just my personal suggestion
May or may not be adopted

**Comment by radarhere** [comment]
I think what homm is asking is, how many users have you actually seen abandon Pillow for OpenCV because we don't support direct camera input? Are there discussions you can link to about this?

**Comment by monkeycc** [comment]
I am in the field of artificial intelligence image detection
In China, there are already over one million jobs in the field of artificial intelligence

According to the 2023 China Artificial Intelligence Talent Learning White Paper, there is still a job gap of 5 million people in the field of artificial intelligence
https://datawhaler.feishu.cn/file/QpIIbYm2EoJFQUxGpcmchQArnjb


Visited programmers in the field of artificial intelligence image detection in China's domestic industry
They said most of them use OpenCV
Because OpenCV can support cameras and video files


Artificial intelligence detection requires reading the camera, drawing rectangular boxes, and writing text
OpenCV can solve all problems
Why do we still need to use Pillow to process images
Pillow is only needed when there is a need for image enhancement

OpenCV can read cameras, draw rectangular boxes, and write text,
And there is no need for image enhancement.
Developers do not need to use Pillow 
Just treating Pillow as an image enhancement module
Indicates that the user is losing

I am not sure about the status of other countries and fields
At least in the field of artificial intelligence in China, there are hundreds of thousands or even over a million people
For this reason, Pillow is not used

If Pillow can support cameras and video files
Can the field of artificial intelligence attract more users
In actual deployment projects, OpenCV can be abandoned and Pillow can be used directly

I hope Pillow is not just a framework for image enhancement
It can be applied in the field of artificial intelligence to gain a large number of users' use

**Comment by aclark4life** [comment]
I don't see adding camera support to Pillow, or rather, I'm not sure what adding camera support would entail and we'd need to know that first before considering such a request. Even then, camera support in Pillow would likely come from an external source PR "Add camera support, you're welcome" rather than from the core team. That said, I appreciate the suggestion (not exactly sure where AI fits in, but … yeah.)

**Comment by Yay295** [comment]
I think they mean like how `ImageGrab` can take a screenshot, or get an image from the clipboard, they would like to get an image from an attached camera.

**Comment by wiredfool** [comment]
I think this is really the place for something standalone, like we have the SANE bindings.  While the users may overlap, I think the code is significantly compartmentalized from what we're doing in the main portion of Pillow that it's not necessarily good to be tying the two of them together.

**Comment by radarhere** [comment]
> I think this is really the place for something standalone, like we have the SANE bindings.

From the OP, it sounds to me like OpenCV is already a standalone tool for this - OpenCV supports cameras, and OpenCV images can be converted to Pillow. 

I don't see the purpose of re-inventing the wheel - I don't imagine that we're going to suddenly put together something better than what OpenCV has been working on for a long time.
