### ISSUE TITLE
Color quantization regression

### ISSUE THREAD

**Issue by H-A-M-G-E-R** [python-pillow/Pillow#7715]
same issue as https://github.com/Artheau/SpriteSomething/issues/84

**Comment by H-A-M-G-E-R** [comment]
regression above 7.0.0

**Comment by radarhere** [comment]
Is there a short self-contained code example you could post to demonstrate the problem?

**Comment by H-A-M-G-E-R** [comment]
i don't know
it's a different issue from #1852 because it only has the bug at 7.0.0 or later

**Comment by radarhere** [comment]
Running the CI job for that project with Pillow 7.0.0, I find that `test_exports` failed. Moving backwards through the changes in Pillow 7.0.0, I found that it started failing when https://github.com/python-pillow/Pillow/pull/4255 changed the default behaviour.

In other words, this is not a bug - the default behaviour of Pillow was deliberately changed. If you would like the behaviour that was previously the default, you just have to replace `im.resize((w, h))` with `im.resize((w, h), Image.NEAREST)` in your code.
