### ISSUE TITLE
Read/write support for 16-bit RGB PNG

### ISSUE THREAD

**Issue by fxthomas** [python-pillow/Pillow#7723]
Opening a 16-bit RGB PNG file with Pillow currently (as of 10.2.0) always results in an uint8 array.

* [Other people](https://stackoverflow.com/questions/59836574/how-to-load-a-16-bits-channel-rgba-image-with-pil) seem to have uses for this kind of format -- my use case being lossless storage of HDR/WCG and RAW imagery and textures, but typically working on very common video formats like `yuv420p10le` would require 16-bit storage support.
* https://github.com/python-pillow/Pillow/issues/880 is an old issue that discusses creating 16-bit RGB buffers, which is closed with a workaround.

I thought I'd open this to consolidate info about PNG support specifically. Does anybody have any plans for including this in Pillow; if not, would a PR be welcome if I started one?

If anybody has pointers they would be very welcome - after a quick look it sounds like the difficult part is to add proper support for the "RGB;16B" buffer mode ; just adding it to the `_MODES` and `_OUTMODES` dictionaries in the PNG plugin sounds simple enough but fails with "unrecognized image mode".

**Comment by wiredfool** [comment]
It's not a simple issue, essentially because there's no support for multichannel images with more than 8 bits/channel. This is the issue tracking the problem: https://github.com/python-pillow/Pillow/issues/1888.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/issues/880 was about three channels that in total made up 16 bits. This is what "RGB;16B" would refer to in Pillow modes. If you're interested in something relating to this, that is feasible.

The StackOverflow post you linked to is about three channels that each have 16 bits individually. You're welcome to work on this or create a PR, just know that isn't trivial and it won't be finished terribly quickly, as the hurdle there is #1888, support for multichannel high bit depth images in general. You've found `_MODES` - I don't think there's much more to say that is PNG-specific.

**Comment by fxthomas** [comment]
Got it, thank you for the pointers, I'll shift the discussion there then!
