### ISSUE TITLE
cannot identify image file <_io.BytesIO object

### ISSUE THREAD

**Issue by agrron** [python-pillow/Pillow#7729]
I am running the following code:
```python
def take_screenshot(device_id=''):
    # 构建截图命令
    screenshot_command = [ADB_COMMAND]
    if device_id:
        screenshot_command.extend(['-s', device_id])
    screenshot_command.extend(['shell', 'screencap', '-p'])

    # 执行截图命令
    screenshot_process = subprocess.Popen(screenshot_command, stdout=subprocess.PIPE)
    screenshot_data, error_message = screenshot_process.communicate()
    if screenshot_process.returncode == 0:
        print("截图命令成功执行")
    else:
        print(f"截图命令执行失败，错误信息: {error_message}")

    # 保存截图到文件
    screenshot_file_path = 'screenshot.png'
    # 使用Pillow库打开图片并保存
    try:
        image = Image.open(io.BytesIO(screenshot_data))
    except Exception as e:
        print(f"Error opening image data: {e}")
    else:
        image.save(screenshot_file_path, format='PNG')
```
And getting the following error:
截图命令成功执行
Error opening image data: cannot identify image file <_io.BytesIO object at 0x000001D91220BA60>
截图数据长度: 15582

Any ideas why is this happening?

Thanks in advance!

* OS:  windows10
* Python: 3.10.13
* Pillow: 10.2.0

**Comment by radarhere** [comment]
Have you tried `print(screenshot_data)` to check that `screenshot_data` isn't an obvious error?

If it isn't, could you provide us with a copy of `screenshot_data`? I suggest modifying your code like this to create a file you can attach here:
```python
screenshot_data, error_message = screenshot_process.communicate()
with open("upload_me.txt", "wb") as fp:
    fp.write(screenshot_data)
```

**Comment by agrron** [comment]
Okay, let me give it a try first. I'll prioritize Google and see how to determine if the output string is in the correct format

**Comment by agrron** [comment]
> Have you tried `print(screenshot_data)` to check that `screenshot_data` isn't an obvious error?
> 
> If it isn't, could you provide us with a copy of `screenshot_data`? I suggest modifying your code like this to create a file you can attach here:
> 
> ```python
> screenshot_data, error_message = screenshot_process.communicate()
> with open("upload_me.txt", "wb") as fp:
>     fp.write(screenshot_data)
> ```

Okay, let me give it a try first. I'll prioritize Google and see how to determine if the output string is in the correct format

**Comment by radarhere** [comment]
Looking at the file you uploaded, it should be a PNG.

If you run
```python
screenshot_data, error_message = screenshot_process.communicate()
with open("output.png", "wb") as fp:
    fp.write(screenshot_data)
```
does it create a PNG that you can actually open on your computer? Depending on what your goal is, I might have even just removed your need for Pillow in the first place.

Could you upload that PNG file here?

**Comment by agrron** [comment]
> Looking at the file you uploaded, it should be a PNG.查看您上传的文件，它应该是PNG。
> 
> If you run 如果你跑
> 
> ```python
> screenshot_data, error_message = screenshot_process.communicate()
> with open("output.png", "wb") as fp:
>     fp.write(screenshot_data)
> ```
> 
> does it create a PNG that you can actually open on your computer? Depending on what your goal is, I might have even just removed your need for Pillow in the first place.它会创建一个可以在计算机上实际打开的 PNG 吗？根据您的目标是什么，我什至可能一开始就消除了您对枕头的需求。
> 
> Could you upload that PNG file here?您可以在此处上传该 PNG 文件吗？

![screenshot](https://github.com/python-pillow/Pillow/assets/11327465/a134e6f2-3518-4cce-ada3-292fd086b3c0)
This file,thanks

**Comment by radarhere** [comment]
Thanks. For whatever reason, the data has "\r\n" where it should have "\n".
So if you replace
```python
image = Image.open(io.BytesIO(screenshot_data))
```
with
```python
image = Image.open(io.BytesIO(screenshot_data.replace(b"\r\n", b"\n")))
```
it should start working.

**Comment by agrron** [comment]
> Thanks. For whatever reason, the data has "\r\n" where it should have "\n". Making that adjustment on screenshot.png gives a black image, but upload_me.txt shows a mobile phone screen.
> 
> So if you replace
> 
> ```python
> image = Image.open(io.BytesIO(screenshot_data))
> ```
> 
> with
> 
> ```python
> image = Image.open(io.BytesIO(screenshot_data.replace(b"\r\n", b"\n")))
> ```
> 
> it should start working.

I sincerely appreciate your generous assistance in resolving a challenge that, as a beginner, went beyond the scope of Pillow itself. Your selfless help has been invaluable, and I'm truly grateful for your guidance. Thank you. I  made it.
