### ISSUE TITLE
cannot identify image file 'xxxx.eps'

### ISSUE THREAD

**Issue by WangZiXiao-ChenDu** [python-pillow/Pillow#7751]
### What are your OS, Python and Pillow versions?

* OS:  Windows 11
* Python:  3.10.9
* Pillow:  10.2.0

```python
from PIL import Image
try:
   im = Image.open("./input/G14.eps")
   im.load(scale=4)
   im.save("./output/G14.jpg")
except Exception as ex:
      print(ex)
else:
     print("success")
```
Firstly, I am certain that the code can run normally.  In the process of converting EPS to JPG, the majority of the conversions are successful, but there are some instances where it fails.  However, the EPS images that fail are not corrupted.  I can provide one of the failed images, and I would like to know the reasons for the failures and how to resolve them.
[eps_Pic.zip](https://github.com/python-pillow/Pillow/files/14034100/eps_Pic.zip)

**Comment by radarhere** [comment]
Looking at G14.eps, it contains data after the EOF marker that is causing it to fail.

Do you know what software was used to create the problem images?

**Comment by WangZiXiao-ChenDu** [comment]
Thank you for the reply. I can use Aspose to convert images to JPG, so my understanding is that the images are not damaged.
https://products.aspose.app/imaging/zh-hans/conversion/eps-to-jpg

**Comment by WangZiXiao-ChenDu** [comment]
The EPS image has data after the %%EOF marker, but it can still be successfully processed using Pillow.
[Uploading _2QW2L~Q.zip…]()

**Comment by radarhere** [comment]
Do you know what software was used to create the problem images?

**Comment by WangZiXiao-ChenDu** [comment]
I'm sorry, I didn't create this EPS file, and I'm not sure which software generated it.

**Comment by Yay295** [comment]
`II*␀` is the magic number for a (little endian) TIFF file. If you delete everything up to that magic number, you can view the (valid) TIFF images.
[tiff_pic.zip](https://github.com/python-pillow/Pillow/files/14039595/tiff_pic.zip)

**Comment by WangZiXiao-ChenDu** [comment]
> `II*␀` is the magic number for a (little endian) TIFF file. If you delete everything up to that magic number, you can view the (valid) TIFF images. [tiff_pic.zip](https://github.com/python-pillow/Pillow/files/14039595/tiff_pic.zip)



> II*␀

Can I understand that if I delete the content after %%EOF, it will be a correct EPS file?

**Comment by WangZiXiao-ChenDu** [comment]
> The EPS image has data after the %%EOF marker, but it can still be successfully processed using Pillow. ![image](https://private-user-images.githubusercontent.com/19464631/299265580-afe0a049-13d6-4e36-970d-af5ac123f182.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDYxNDczNzcsIm5iZiI6MTcwNjE0NzA3NywicGF0aCI6Ii8xOTQ2NDYzMS8yOTkyNjU1ODAtYWZlMGEwNDktMTNkNi00ZTM2LTk3MGQtYWY1YWMxMjNmMTgyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAxMjUlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMTI1VDAxNDQzN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTYxZDc1NDA2NDBkNDk0ZWM4YTFmNzNkMDMyMjFiYTUxODdhY2Y2YTFiNmI2OWU0ZDc4YTA4M2E5NDY5MDBiMmImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.WObt60Nd_oarjfi8KM9I8FEH-RWmQcU9EM9e-iiA0pk)
> 
> [_2QW2L~Q.zip](https://github.com/python-pillow/Pillow/files/14045707/_2QW2L.Q.zip)

I don't understand why this image can be successfully converted to JPG?

**Comment by radarhere** [comment]
> Can I understand that if I delete the content after %%EOF, it will be a correct EPS file?

Yes. If you would like an immediate solution, you can trim the content after %%EOF like this.
```python
import io
from PIL import Image, EpsImagePlugin
with open("./input/G14.eps", "rb") as fp:
  prefix = fp.read(4)
  if EpsImagePlugin._accept(prefix):
    data = prefix+fp.read()
    im = Image.open(io.BytesIO(data.split(b"%%EOF")[0]+b"%%EOF"))
  else:
    fp.seek(0)
    im = Image.open(fp)
  im.load(scale=4)
  im.save("./output/G14.jpg")
```

**Comment by WangZiXiao-ChenDu** [comment]
> > Can I understand that if I delete the content after %%EOF, it will be a correct EPS file?
> 
> Yes. If you would like an immediate solution, you can trim the content after %%EOF like this.
> 
> ```python
> import io
> from PIL import Image, EpsImagePlugin
> with open("./input/G14.eps", "rb") as fp:
>   prefix = fp.read(4)
>   if EpsImagePlugin._accept(prefix):
>     data = prefix+fp.read()
>     im = Image.open(io.BytesIO(data.split(b"%%EOF")[0]+b"%%EOF"))
>   else:
>     fp.seek(0)
>     im = Image.open(fp)
>   im.load(scale=4)
>   im.save("./output/G14.jpg")
> ```

This method works, thank you so much！

**Comment by WangZiXiao-ChenDu** [comment]
--
