### ISSUE TITLE
Replace camelCased APIs with snake_case

### ISSUE THREAD

**Issue by ThiefMaster** [python-pillow/Pillow#7799]
Not sure how controversial this is considering that it would be a massively backwards-incompatible change (it'd almost certainly require a grace period where the camelCase versions are just deprecated), but I think I'm not the only Python developer who find camelCase in Python code completely awful.

Besides being a matter of taste/style, having camelCase can also cause some practical issues e.g. during code reviews. For example, I recently reviewed a PR to my application that involved some client-side React code and server-side Python code using Pillow. The contributor was mentioning setting `preserveAspectRatio` and I got confused because I assumed this is something they were adding on the client side (since it's common in JavaScript), until I actually saw the commit adding it on the backend.

**Comment by aclark4life** [comment]
Probably pretty controversial 😄 

That said, you can always send a PR with the changes so we can see how many tests break and how invasive the change is.

Unlike adding Python 3 support, I'm not sure adding snake_case support is something that ever really needs to happen, or at least probably never crosses the threshold past "nice to have in theory, if it could be done without destructive effects".

**Comment by cosmochi** [comment]
Hi, can I work on this?

**Comment by ThiefMaster** [comment]
> That said, you can always send a PR with the changes so we can see how many tests break and how invasive the change is...

I'm not going to send a PR for something as big as this... especially without knowing for sure that it would get accepted.

**Comment by radarhere** [comment]
Understandable. Could you at least list the APIs that you've noticed that are camelCase?

**Comment by hugovk** [comment]
> Besides being a matter of taste/style, having camelCase can also cause some practical issues e.g. during code reviews. For example, I recently reviewed a PR to my application that involved some client-side React code and server-side Python code using Pillow. The contributor was mentioning setting `preserveAspectRatio` and I got confused because I assumed this is something they were adding on the client side (since it's common in JavaScript), until I actually saw the commit adding it on the backend.

Perhaps this is a general example and not meant to be a Pillow example, but there's no `preserveAspectRatio` in Pillow: https://github.com/search?q=repo%3Apython-pillow%2FPillow%20preserveAspectRatio&type=code

Was it this PR? https://github.com/indico/indico/pull/6160

Looks like that `preserveAspectRatio` is from ReportLab: https://docs.reportlab.com/tagref/tag_imagefigure/

**Comment by ThiefMaster** [comment]
oops. sorry for the noise!

**Comment by Yay295** [comment]
I did a search (https://github.com/search?type=code&q=repo%3Apython-pillow%2FPillow+%2F%28%3F-i%29%5Cb%5Ba-z%5D%2B%5BA-Z%5D%5Cw%2B%5C%28%2F) and it looks like the camel-cased functions are mostly in `ImageCms`.
