### ISSUE TITLE
When using img.save to store an icon, sizes are somehow ignored or overwritten

### ISSUE THREAD

**Issue by GeneriicName** [python-pillow/Pillow#7800]
windows 11 pro 
OS Version:  10.0.22631 N/A Build 22631
python 3.12.0
pillow 10.2.0

code:
```python
from PIL import Image
from io import BytesIO
from dataclasses import dataclass


@dataclass(frozen=True)
class Vars:
    sizes = [(16, 16), (192, 192), (96, 96), (32, 32), (64, 64), (128, 128), (48, 48), (256, 256), (24, 24)]
    formats = ["bmp", "dds", "dib", "eps", "icns", "im", "jpeg", "png", "ppm", "sgi", "tiff", "webp", "tga", "pcx",
               "msp", "gif", "ico"]


def convert_image(data: bytes, output_type: str) -> bytes | None:
    if output_type.lower() not in Vars.formats:
        return
    if output_type.lower() == "ico":
        with BytesIO() as output:
            with Image.open(data) as img:
                img.save(output, format='ICO', quality=100, sizes=Vars.sizes, subsampling=0, bitmap_format="bmp")
                with Image.open(output) as check:
                    print(check.info)
            return output.getvalue()
    with BytesIO() as output:
        with Image.open(data) as img:
            img = img.convert('RGB')
            img.save(output, format=output_type)
        return output.getvalue()
````
output:
`
{'sizes': {(96, 91), (48, 46), (24, 23), (32, 30), (192, 183), (128, 122), (64, 61), (256, 244), (16, 15)}}
`

issue:
the specified sizes are being ignored when saving the icon.
i made sure i have the newest pil version, also tested with third party tools that getting desired icon group sizes with my given image is possible.

the image is a random image from my pc i just picked for testing
![converted (1)](https://github.com/python-pillow/Pillow/assets/139624416/5c78ef72-3a1e-437d-8fa7-3fdbfffd534e)

any help will be greatly appricated! my current solution is to load a C# dll via clr but i would prefer to use purely python when possible.

the code is the entire file, at no point did i somehow modify Vars.sizes.

**Comment by radarhere** [comment]
Hi. The problem is that the aspect ratios don't match between the image and the sizes you're requesting - the sizes are square, but your image is not. Your image is 847px by 807px.

Pillow is scaling down the image to fit within the sizes you have specified, and so for (96, 96), 807/847*96=91, it becomes (96, 91).

You might be interested in calling either `ImageOps.fit()` (expand and cut parts off) or `ImageOps.pad()` (shrink and have a background colour added) with your image to make it square first. See https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#resize-relative-to-a-given-size

**Comment by GeneriicName** [comment]
> Hi. The problem is that the aspect ratios don't match between the image and the sizes you're requesting - the sizes are square, but your image is not. Your image is 847px by 807px.
> 
> Pillow is scaling down the image to fit within the sizes you have specified, and so for (96, 96), 807/847*96=91, it becomes (96, 91).
> 
> If you don't care about losing the original aspect ratio, you can call `resize()` on your image first to stretch it and make it square - https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.resize
> 
> If you do care, you could call `ImageOps.fit()` (expand and cut parts off) or `ImageOps.pad()` (shrink and have a background colour added) with your image. See https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#resize-relative-to-a-given-size

```ImageOps.fit()``` did the job amazingly, thank you so much!
