### ISSUE TITLE
PNG iCCP chunk profile compression type verification seems wrong

### ISSUE THREAD

**Issue by nathaniel-daniel** [python-pillow/Pillow#7817]
### What did you do?
Hello, I've been looking around at some PNG decoders and I think I've found a small bug in your iCCP chunk handling. 

### What did you expect to happen?
I would expect the library to read the iCCP chunk compression version byte correctly.

### What actually happened?
This library incorrectly assumes that the NUL terminator is the compression byte. This does not cause issues in practice, since the compression byte should currently always be 0, but I thought I'd report this anyways.

### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: Python 3.11.8-1 (MSYS2)
* Pillow: 10.2.0-1 (MSYS2)

```python
from PIL import Image, ImageFile
import logging

logging.basicConfig(level=logging.DEBUG)

path = 'ArcTriomphe-iCCP-red-green-swap-mod.png'

with Image.open(path) as img:
    icc = img.info.get('icc_profile')
    print(icc)
    print(img)
```

Here are my 2 test files:
![ArcTriomphe-iCCP-red-green-swap](https://github.com/python-pillow/Pillow/assets/80441888/792cedba-3ab1-4d46-bfb9-87389e8337f7)
![ArcTriomphe-iCCP-red-green-swap-mod](https://github.com/python-pillow/Pillow/assets/80441888/65141037-59cf-4381-94d7-0d18824b0096)

The first one is a normal image with an embedded icc profile. The second is the same image, modified in a hex editor to change the compression version field from 0 to 1.

Here is the output from the first image:
```
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'iCCP' 41 460
DEBUG:PIL.PngImagePlugin:iCCP profile name b'Swapped red & green channel'
DEBUG:PIL.PngImagePlugin:Compression method 0
DEBUG:PIL.PngImagePlugin:STREAM b'PLTE' 513 759
DEBUG:PIL.PngImagePlugin:STREAM b'IDAT' 1284 3618
b'\x00\x00\x02\x84lcms\x02@\x00\x00mntrRGB XYZ \x07\xd5\x00\x08\x00\r\x00\x16\x00!\x00,acspSUNW\x00\x00\x00\x00none\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\xf6\xd6\x00\x01\x00\x00\x00\x00\xd3-Greg^\xdf\x16\x9a"\xbb\xfd\xab\xb6@n\xf998\rz\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\ndesc\x00\x00\x00\xfc\x00\x00\x00\x84cprt\x00\x00\x01\x80\x00\x00\x00\x90wtpt\x00\x00\x02\x10\x00\x00\x00\x14bkpt\x00\x00\x02$\x00\x00\x00\x14rXYZ\x00\x00\x028\x00\x00\x00\x14gXYZ\x00\x00\x02L\x00\x00\x00\x14bXYZ\x00\x00\x02`\x00\x00\x00\x14rTRC\x00\x00\x02t\x00\x00\x00\x0egTRC\x00\x00\x02t\x00\x00\x00\x0ebTRC\x00\x00\x02t\x00\x00\x00\x0edesc\x00\x00\x00\x00\x00\x00\x00\'"sGRB": red and green channels swapped\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x0067 bytes of wasted space, courtesy of Apple Computer, dum de dum.\x00\x00text\x00\x00\x00\x00Copyright 2005 Greg Roelofs. Licensed under Creative Commons Attribution-NonCommercial, http://creativecommons.org/licenses/by-nc/2.5/ \x00XYZ \x00\x00\x00\x00\x00\x00\xf3Q\x00\x01\x00\x00\x00\x01\x16\xccXYZ \x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00XYZ \x00\x00\x00\x00\x00\x00b\x98\x00\x00\xb7\x86\x00\x00\x18\xdaXYZ \x00\x00\x00\x00\x00\x00o\xa1\x00\x008\xf5\x00\x00\x03\x90XYZ \x00\x00\x00\x00\x00\x00$\xa0\x00\x00\x0f\x84\x00\x00\xb6\xc9curv\x00\x00\x00\x00\x00\x00\x00\x01\x023\x00\x00'
<PIL.PngImagePlugin.PngImageFile image mode=P size=64x64 at 0x26C30640E10>
```

Here is the output from the second image:
```
DEBUG:PIL.PngImagePlugin:STREAM b'IHDR' 16 13
DEBUG:PIL.PngImagePlugin:STREAM b'iCCP' 41 460
DEBUG:PIL.PngImagePlugin:iCCP profile name b'Swapped red & green channel'
DEBUG:PIL.PngImagePlugin:Compression method 0
DEBUG:PIL.Image:Importing BlpImagePlugin
DEBUG:PIL.Image:Importing BmpImagePlugin
DEBUG:PIL.Image:Importing BufrStubImagePlugin
DEBUG:PIL.Image:Importing CurImagePlugin
DEBUG:PIL.Image:Importing DcxImagePlugin
DEBUG:PIL.Image:Importing DdsImagePlugin
DEBUG:PIL.Image:Importing EpsImagePlugin
DEBUG:PIL.Image:Importing FitsImagePlugin
DEBUG:PIL.Image:Importing FliImagePlugin
DEBUG:PIL.Image:Importing FpxImagePlugin
DEBUG:PIL.Image:Image: failed to import FpxImagePlugin: No module named 'olefile'
DEBUG:PIL.Image:Importing FtexImagePlugin
DEBUG:PIL.Image:Importing GbrImagePlugin
DEBUG:PIL.Image:Importing GifImagePlugin
DEBUG:PIL.Image:Importing GribStubImagePlugin
DEBUG:PIL.Image:Importing Hdf5StubImagePlugin
DEBUG:PIL.Image:Importing IcnsImagePlugin
DEBUG:PIL.Image:Importing IcoImagePlugin
DEBUG:PIL.Image:Importing ImImagePlugin
DEBUG:PIL.Image:Importing ImtImagePlugin
DEBUG:PIL.Image:Importing IptcImagePlugin
DEBUG:PIL.Image:Importing JpegImagePlugin
DEBUG:PIL.Image:Importing Jpeg2KImagePlugin
DEBUG:PIL.Image:Importing McIdasImagePlugin
DEBUG:PIL.Image:Importing MicImagePlugin
DEBUG:PIL.Image:Image: failed to import MicImagePlugin: No module named 'olefile'
DEBUG:PIL.Image:Importing MpegImagePlugin
DEBUG:PIL.Image:Importing MpoImagePlugin
DEBUG:PIL.Image:Importing MspImagePlugin
DEBUG:PIL.Image:Importing PalmImagePlugin
DEBUG:PIL.Image:Importing PcdImagePlugin
DEBUG:PIL.Image:Importing PcxImagePlugin
DEBUG:PIL.Image:Importing PdfImagePlugin
DEBUG:PIL.Image:Importing PixarImagePlugin
DEBUG:PIL.Image:Importing PngImagePlugin
DEBUG:PIL.Image:Importing PpmImagePlugin
DEBUG:PIL.Image:Importing PsdImagePlugin
DEBUG:PIL.Image:Importing QoiImagePlugin
DEBUG:PIL.Image:Importing SgiImagePlugin
DEBUG:PIL.Image:Importing SpiderImagePlugin
DEBUG:PIL.Image:Importing SunImagePlugin
DEBUG:PIL.Image:Importing TgaImagePlugin
DEBUG:PIL.Image:Importing TiffImagePlugin
DEBUG:PIL.Image:Importing WebPImagePlugin
DEBUG:PIL.Image:Importing WmfImagePlugin
DEBUG:PIL.Image:Importing XbmImagePlugin
DEBUG:PIL.Image:Importing XpmImagePlugin
DEBUG:PIL.Image:Importing XVThumbImagePlugin
<traceback omitted>
PIL.UnidentifiedImageError: cannot identify image file 'ArcTriomphe-iCCP-red-green-swap-mod.png'
```

As can be seen, PIL thinks the compression byte never changes. The issue is [here](https://github.com/python-pillow/Pillow/blob/380bc1766b7a3c23bde679be307ddfec1df252d0/src/PIL/PngImagePlugin.py#L395-L396), where there is an off-by-one error. `s[i]` should be `s[i + 1]` for the compression byte.

**Comment by radarhere** [comment]
I've created #7823 to resolve this.

**Comment by BloodyRain2k** [comment]
Is this supposed to be fixed in 11.3.0 (Python 3.11.2) on Linux (Debian)?
Wheel: `pillow-11.3.0-cp311-cp311-manylinux_2_27_x86_64.manylinux_2_28_x86_64.whl`

Because when I try to open the green png with `PIL.Image.open('png_green.png')` I get this:

> Exception has occurred: UnidentifiedImageError
cannot identify image file 'png_green.png'

When I traced the error back into the module it would say that `e` in
https://github.com/python-pillow/Pillow/blob/89f1f4626a2aaf5f3d5ca6437f41def2998fbe09/src/PIL/Image.py#L3550
is `'Unknown compression method 1 in iCCP chunk'`, if warnings weren't disabled by default.
Instead it says nothing other than "cannot identify image" in the end, which is technically wrong, because it correctly detected it as PNG, it just choked on a non-critical chunk.
I assume at least that it's non-critical because Firefox, Gimp and Debian's Imageviewer all don't even bother complaining in the first place.

I only found out about this issue because I encountered an image with a differently broken iCCP chunk, but it fails at the same point, just the message is a little different. I have yet to find a way to reproduce that one, but I decided to see if this old one was actually fixed, and it seems like it's not?

**Comment by radarhere** [comment]
I don't think the original report here ever thought it was a problem that the green image couldn't be read, merely that the compressed method was incorrect.

Regarding raising an error other than UnidentifiedImageError, have a read of #1687 (although keep in mind most of it was written before the error was changed to UnidentifiedImageError in #4182).

If you're asking for "Unknown compression method" to be ignored, perhaps we could do that if `ImageFile.LOAD_TRUNCATED_IMAGES = True` was set, but

> just the message is a little different

I'm not sure you are?

**Comment by BloodyRain2k** [comment]
Yeah maybe I did misunderstand what this issue was about.

But it seemed very similar to the problem I ran into.
In my case I have an image that should be throwing `"broken PNG file (bad header checksum in b'iCCP')"` at 3550.

I can get the image to load fine if I enable `LOAD_TRUNCATED_IMAGES`, but that then creates a new problem: the project I tried the image into doesn't expect "broken" images.
Having said flag off correctly alerted me that I would've added actually broken images before, where some damage caused the end of the image data to be unrecoverable and just show up as grey blocks in a viewer.
That's how it's intended to work.

But with this irrelevant part of the image causing the same rejection, need to find a way to figure out if any loading error that reports itself as `UnidentifiedImageError` might be just a damaged header checksum.

What I'm annoyed by isn't even that the error exists or that I have to work around it, but that it says externally "I don't know what this is" while it internally figured out "this is a PNG, but something's damaged".
If it could at least say `PIL.UnidentifiedImageError: cannot identify image file 'broken.png' | "broken PNG file (bad header checksum in b'iCCP')"` I'd already be happy, because I could just match the error text and let the code repair the image.

**Comment by radarhere** [comment]
> If it could at least say PIL.UnidentifiedImageError: cannot identify image file 'broken.png' | "broken PNG file (bad header checksum in b'iCCP')" I'd already be happy, because I could just match the error text and let the code repair the image.

If you set [`Image.WARN_POSSIBLE_FORMATS`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.WARN_POSSIBLE_FORMATS) to true,
```python
from PIL import Image
Image.WARN_POSSIBLE_FORMATS = True
with Image.open('green.png') as img:
  print(img)
```
then you should see warnings that mention errors raised by different formats, including 'bad header checksum'.
```
PIL/Image.py:3560: UserWarning: PNG opening failed. broken PNG file (bad header checksum in b'IHDR')
  warnings.warn(message)
PIL/Image.py:3560: UserWarning: IM opening failed. Syntax error in IM header: �PNG
  warnings.warn(message)
PIL/Image.py:3560: UserWarning: IMT opening failed. not identified by this driver
  warnings.warn(message)
PIL/Image.py:3560: UserWarning: IPTC opening failed. invalid IPTC/NAA file
  warnings.warn(message)
PIL/Image.py:3560: UserWarning: PCD opening failed. not a PCD file
  warnings.warn(message)
PIL/Image.py:3560: UserWarning: SPIDER opening failed. not a valid Spider file
  warnings.warn(message)
PIL/Image.py:3560: UserWarning: TGA opening failed. not a TGA file
  warnings.warn(message)
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    with Image.open('green.png') as img:
  File "PIL/Image.py", line 3562, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'green.png'
```

**Comment by BloodyRain2k** [comment]
> If you set [`Image.WARN_POSSIBLE_FORMATS`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.WARN_POSSIBLE_FORMATS) to true,

I figured out as much already, but I have not found a way for that being useful to me. The exception still doesn't say anything else, so I wouldn't know how to make the code see "oh, this PNG just has a bad chunk" vs "this image is completely broken".

**Comment by radarhere** [comment]
Is this interesting to you at all?
```python
from PIL import Image, PngImagePlugin, UnidentifiedImageError

try:
    img = Image.open('green.png')
except UnidentifiedImageError:
    with open('green.png', 'rb') as fp:
        if PngImagePlugin._accept(fp.read(8)):
            fp.seek(0)
            PngImagePlugin.PngImageFile(fp)
        else:
            raise
```
gives
```pytb
Traceback (most recent call last):
  File "demo.py", line 4, in <module>
    img = Image.open('green.png')
  File "PIL/Image.py", line 3562, in open
    raise UnidentifiedImageError(msg)
PIL.UnidentifiedImageError: cannot identify image file 'green.png'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "demo.py", line 9, in <module>
    PngImagePlugin.PngImageFile(fp)
  File "PIL/ImageFile.py", line 148, in __init__
    self._open()
  File "PIL/PngImagePlugin.py", line 779, in _open
    s = self.png.call(cid, pos, length)
  File "PIL/PngImagePlugin.py", line 204, in call
    return getattr(self, f"chunk_{cid.decode('ascii')}")(pos, length)
  File "PIL/PngImagePlugin.py", line 438, in chunk_iCCP
    raise SyntaxError(msg)
SyntaxError: Unknown compression method 1 in iCCP chunk
```

**Comment by BloodyRain2k** [comment]
Thanks a lot, that works for me 👍
