### ISSUE TITLE
Deprecate X (formerly Twitter) account, focus on Fosstodon only

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#7828]
Anyone mind if I archive and delete https://twitter.com/PythonPillow ? I'm kind of done with X (formerly Twitter) and while I may keep my personal account, I'd love to archive https://twitter.com/PythonPillow and focus on https://fosstodon.org/@pillow.

And speaking of https://fosstodon.org/@pillow, can someone please send me an invite to https://fosstodon.org/? I have a Mastodon account but that doesn't work on Fosstodon… for reasons I don't fully understand… but are probably explained here: https://hub.fosstodon.org/were-invite-only. 🤷 

Thanks all 🙏

**Comment by hugovk** [comment]
> Anyone mind if I archive and delete https://twitter.com/PythonPillow ? I'm kind of done with X (formerly Twitter) and while I may keep my personal account, I'd love to archive https://twitter.com/PythonPillow and focus on https://fosstodon.org/@pillow.

Good idea! 

What exactly do you mean by delete and archive? 

Our options go from:

* stop using it, remove links from here
* set to private 
* delete the account and all tweets completely

It may come in handy to be able to refer to things there, but I'm not too bothered. 

I've not deleted mine yet, but I've made it private and don't check it any more. 

> And speaking of https://fosstodon.org/@pillow, can someone please send me an invite to https://fosstodon.org/? I have a Mastodon account but that doesn't work on Fosstodon… for reasons I don't fully understand… but are probably explained here: https://hub.fosstodon.org/were-invite-only. 🤷

Yep, I can send an invite later. 

Fosstodon is a server on Mastodon, you should be able to follow and reply to anyone on Mastodon or Fosstodon from existing accounts anywhere (assuming there's no blocks). Mine is on mastodon.social and I can see Fosstodon accounts. 

We can try and figure out what's up with your existing account if you like? But if you want to start fresh on Fosstodon, that's fine too!

**Comment by aclark4life** [comment]
> What exactly do you mean by delete and archive?

Probably going to archive then delete and make the archive public, possibly by checking it in to GitHub and publishing on pages. As I recall, the archive from X can be web-hosted as-is.

> Yep, I can send an invite later.

Please do! If you can give administrative access for https://fosstodon.org/@pillow to https://mastodon.social/@aclark then maybe that would suffice … but in that case I'd still have to log in to Fosstodon? My Mastodon account works fine, but if I try to login to Fosstodon with that email address and the password from Mastodon, it fails. Thanks for the help!

**Comment by hugovk** [comment]
> Probably going to archive then delete and make the archive public, possibly by checking it in to GitHub and publishing on pages. As I recall, the archive from X can be web-hosted as-is.

I'd be a bit cautious about hosting the original archive, in case there's some private data in there. Not just DMs, but it looks like there's a list of login IPs.

But I've heard good things about this tool, which makes a hostable, searchable archive:

https://tinysubversions.com/twitter-archive/make-your-own/ 

Here's an example:

https://tweets.jvns.ca/


> Please do! 

Invite sent via Discord! Or I can email or Slack it.

> If you can give administrative access for [fosstodon.org/@pillow](https://fosstodon.org/@pillow) to [mastodon.social/@aclark](https://mastodon.social/@aclark) then maybe that would suffice … but in that case I'd still have to log in to Fosstodon? My Mastodon account works fine, but if I try to login to Fosstodon with that email address and the password from Mastodon, it fails. 


You can't give access to an account via another. (The login for `fosstodon.org/@pillow` is in the team 1Password that you should have access to, ping me via Discord/Slack/email about that.) So you need to log in to them separately.

**Comment by hugovk** [comment]
@aclark4life Before deleting the https://twitter.com/PythonPillow account, please could you tweet (and pin) to tell people we're using `https://fosstodon.org/@pillow` instead?

Also put `https://fosstodon.org/@pillow` as the profile link, and maybe even put `@pillow@fosstodon.org` as the display name.

**Comment by aclark4life** [comment]
Done! Can I edit https://fosstodon.org/@pillow ?

**Comment by hugovk** [comment]
Thanks!

Yes, credentials are in the team's 1Password.

**Comment by radarhere** [comment]
> could you tweet (and pin) to tell people we're using https://fosstodon.org/@pillow instead?

This became https://twitter.com/PythonPillow/status/1762152674277937574
> We're using [https://fosstodon.org/@pillow](https://t.co/nsMXqCIBLB) now instead of X (formerly Twitter), see you there! This account will be archived and deleted on or shortly after the release of 10.3.0 in April 2024.

**Comment by radarhere** [comment]
10.3.0 has been released, making this the scheduled time to archive/delete the Twitter account.

**Comment by aclark4life** [comment]
Deactivated, and working on public archive… I couldn't get https://tinysubversions.com/twitter-archive/make-your-own/ to work but if anyone else wants to try please let me know and I'll send you the zip. Pretty sure I've published the contents of the zip on the web in the past without worrying about privacy issues, but I didn't look that closely.

**Comment by hugovk** [comment]
I can try!

**Comment by aclark4life** [comment]
OK I slacked it to you, thanks!
