### ISSUE TITLE
[FR] Fill the out of range parts with colors when cropping images

### ISSUE THREAD

**Issue by diolam** [python-pillow/Pillow#7833]
### What did you do?

```python
from PIL import Image
img = Image.new("RGB", (1000, 1000), color="white")
img.crop((-500, -500, 500, 500)).show()
```

I got this.

![result](https://github.com/python-pillow/Pillow/assets/78291982/8680ab91-2e72-41c6-a64a-68a5eb78eabe)

### What did you expect to happen?

I want to add a keyword argument `fill`, so that I can specify what color to fill when exceeding the boundary.

### What are your OS, Python and Pillow versions?

* OS: Windows
* Python: Python 3.10.5 (tags/v3.10.5:f377153, Jun  6 2022, 16:14:13) [MSC v.1929 64 bit (AMD64)]
* Pillow: Pillow 9.2.0

**Comment by radarhere** [comment]
Hi. Did you know that you can achieve that effect with [`ImageOps.expand()`](https://pillow.readthedocs.io/en/stable/reference/ImageOps.html#PIL.ImageOps.expand)?
```python
from PIL import Image, ImageOps
img = Image.new("RGB", (1000, 1000), color="white")
ImageOps.expand(img, (1000, 1000, 0, 0), fill="#f00").show()
```
gives
![out](https://github.com/python-pillow/Pillow/assets/3112309/fbbeda2c-d5bf-40ee-8cf3-70f988bf1c46)

**Comment by diolam** [comment]
Thanks. I didn't know that. I will close this issue.
