### ISSUE TITLE
Errors while processing TIFF images

### ISSUE THREAD

**Issue by zhoumeng250** [python-pillow/Pillow#7845]
### What did you do?

The code below occasionally encounters an issue where, after resizing the TIF image data and saving it to a new location, the four bytes in the file header of the new TIF file that describe the OFFSET position of the IFD (Image File Directory) are set to zero. This prevents the new resized TIF image from being opened.

### What did you expect to happen?

The four bytes describing the OFFSET position of the IFD (Image File Directory) should not be zero.

### What actually happened?

The four bytes in the file header of the new TIF file that describe the OFFSET position of the IFD (Image File Directory) are set to zero.

~! Most of the time, there are no this issues. I would like to know the possible reasons that could cause this problem in order to reduce such similar errors.

### What are your OS, Python and Pillow versions?

* OS:   Dockerfile - FROM python:3.6

PRETTY_NAME="Debian GNU/Linux 11 (bullseye)"
NAME="Debian GNU/Linux"
VERSION_ID="11"
VERSION="11 (bullseye)"
VERSION_CODENAME=bullseye
ID=debian
HOME_URL="https://www.debian.org/"
SUPPORT_URL="https://www.debian.org/support"
BUG_REPORT_URL="https://bugs.debian.org/"

* Python:  python:3.6
* Pillow:  Pillow==8.4.0

```python
float_resize_multiple_width = float(os.environ.get('WIDTH_SCALE', 0.3))
float_resize_multiple_height = float(os.environ.get('HEIGHT_SCALE', 0.3))

def process_image(image_path, target_path):
    try:
        with Image.open(image_path) as img:
            width, height = img.size
            new_width = round(width * float_resize_multiple_width)
            new_height = round(height * float_resize_multiple_height)
            resized_img = img.resize((new_width, new_height), Image.LANCZOS)
            resized_img.save(os.path.join(target_path, os.path.basename(image_path)))
            os.remove(image_path)
    except Exception as e:
        print(f"handle {image_path}：{e}")

```

**Comment by radarhere** [comment]
I gather you're not able to upload one of the images that causes the problem?

Or even one of the saved images?

**Comment by zhoumeng250** [comment]
Yes, I went through the contents of _save(im, fp, filename) in Pillow 8.4.0's TiffImagePlugin.py, but I didn't find anything significant. Also, in my code, the original image is deleted after resizing, so I can't reproduce it. Therefore, I can only speculate that it might be an issue with EMC during program execution or disk bad blocks causing changes in the content of IFH.

**Comment by radarhere** [comment]
I'm not seeing anything so far.

If there's no compression, then the offset should be 8.
https://github.com/python-pillow/Pillow/blob/40e7ff622669550733b26f14dc817fb72e096250/src/PIL/TiffImagePlugin.py#L902

If there's compression, then libtiff would be used. What version of libtiff are you using?
```pycon
>>> from PIL import features
>>> features.version_codec("libtiff")
'4.6.0'
```

**Comment by radarhere** [comment]
If the problem is in libtiff, then you could avoid it by saving without compression - `resized_img.save(..., compression=None)`
