### ISSUE TITLE
Add webp export option alpha_quality

### ISSUE THREAD

**Issue by mzealey** [python-pillow/Pillow#7868]
`cwebp` has a commandline flag of `-alpha_q <x>%` which uses lossy-compression for the alpha channel and can significantly reduce image size, and also seems to speed up image conversion in some cases. It would be great to have this ability in Pillow also.

Additionally an option similar to `-noalpha` where we know the image does not contain any alpha layer saves ~27 bytes per image - not particularly significant but again a nice-to-have for cwebp compatibility.

Thanks!

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/7872 to resolve this by adding `alpha_quality`.

**Comment by mzealey** [comment]
Oh brilliant thank you this looks great :-)
