### ISSUE TITLE
Font rendering issue with ttc font

### ISSUE THREAD

**Issue by camprevail** [python-pillow/Pillow#7871]
### What did you do?
It seems that font rendering changed for the worse between 7.2.0 and 8.x, not sure which version exactly. (edit, it changed between 7.2 and 8.0). I had this issue a few years ago when I tried to upgrade to 8.x so I had to revert, but now I really have a need to upgrade.
Below is a comparison image, with the caption text rendered with draw.text() in Pillow 7.2.0 on the left and 10.2 on the right. On the right, you can see that the text appears to have lost it's softer anti-aliased look and kerning in some spots - some letters are touching each other. 
I searched up and down and couldn't find any other reports of anything like this, I did try a few suggestions like setting draw.textmode = 'L' and enabling the kern feature, but nothing worked.

All I'm looking for is a solution or suggestions to get the old look back. The font used is msgothic.ttc, index 1.

![diffs](https://github.com/python-pillow/Pillow/assets/34872547/16cb5a09-2d23-4337-bbea-6146e510c1d2)

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.10.11
* Pillow: 10.2

```python
base = Image.open('assets/misc/bg_new.png').convert('RGB')
draw = ImageDraw.Draw(base)
draw.fontmode = 'L'
caption_font = ImageFont.truetype("assets/font/msgothic.ttc", size=12, index=1)
text = "Warrior with a fan. She fights with the force of\nthe wind. She has a very strong personality,..."
draw.text((171, 780), text, (164, 144, 64), font=caption_font)
base.show()
```

**Comment by camprevail** [comment]
Small update, tried changing the layout engine for this font object to layout_engine=ImageFont.Layout.BASIC. That seems to kind of fixed the kerning issue, but the antialias setting with draw.fontmode = 'L' still does nothing, no difference from setting it to '1'. 
I don't think antialias will fix the overall look of it being completely different... it almost doesn't look like the same font?

**Comment by camprevail** [comment]
Tried switching to arial and it looks much better. Perhaps this is a problem with the msgothic TTC, or TTC font rendering specifically?
![test3](https://github.com/python-pillow/Pillow/assets/34872547/f683a024-c110-4433-8681-7a20f4fe2822)

**Comment by camprevail** [comment]
Alright I nailed down the specific version it broke, first image here is 10.0.1, second image is 10.1.0. 
![pillowtest-10 0 1](https://github.com/python-pillow/Pillow/assets/34872547/1c66550b-62bb-4cf4-b473-e30674c4926a)
![pillowtest-10 1 0](https://github.com/python-pillow/Pillow/assets/34872547/fa7e9563-3460-4195-aaea-9a49c9f99390)

**Comment by camprevail** [comment]
Sorry, forgot to add the `font` arg to draw.text. Looks like it changed between 7.2 and 8.0. Here's the comparison images
![pillowtest-7 2 0](https://github.com/python-pillow/Pillow/assets/34872547/605e07f1-f61a-49a9-80eb-299c0562fe84)
![pillowtest-8 0](https://github.com/python-pillow/Pillow/assets/34872547/e684a537-af9b-4b30-b4a0-6bb2ccb8fb2e)
My code is:
```python
from PIL import Image, ImageDraw, ImageFont

font = ImageFont.truetype('msgothic.ttc', size=12, index=1)
base = Image.new('RGB', (250, 50), color=(255, 255, 255))
draw = ImageDraw.Draw(base)
mytext = 'The quick brown fox jumps over...'

draw.text((5, 10), mytext, (0,0,0), font=font)
base.show()
```

**Comment by camprevail** [comment]
Here's a much better test revealing that it seems that something is happening between 22 and 23pt sizes.
![pillowtest-7 2 0](https://github.com/python-pillow/Pillow/assets/34872547/ca2a4900-88a1-4ece-ae25-a362cb523a96)
![pillowtest-8 0 0](https://github.com/python-pillow/Pillow/assets/34872547/807b72b8-6239-47f1-b540-9f8bb4c15e9b)

**Comment by nulano** [comment]
Based on the images, this is almost certainly caused by #4955 fixing #891. The previous behaviour was caused by a bug where Pillow was ignoring embedded bitmaps in a font.

OpenType fonts can contain embedded bitmaps in the [EBDT table](https://learn.microsoft.com/en-us/typography/opentype/spec/ebdt). This is supposed to provide better quality when rendering at small font sizes. Unfortunately, it seems that the font you are using did not implement this very well. You may be able to remove the embedded bitmap table with a tool such as FontForge.

**Comment by camprevail** [comment]
Alright thanks for the suggestion, that worked and was very easy.
![pillowtest-10 2 0](https://github.com/python-pillow/Pillow/assets/34872547/a2670498-62d7-414d-bc85-f40f863fda9e)

**Comment by radarhere** [comment]
Thanks very much nulano.

Is this resolved then?

**Comment by camprevail** [comment]
Yeah I suppose so. I'll close it
