### ISSUE TITLE
Failing to load Image from PIL in macOS with 9.5.0

### ISSUE THREAD

**Issue by ViviLuD** [python-pillow/Pillow#7889]
### What did you do?

I try to install pillow 9.5.0

### What actually happened?
Note: This error originates from the build backend, and is likely not a problem with poetry but with pillow (9.5.0) not supporting PEP 517 builds. You can verify this by running 'pip wheel --no-cache-dir --use-pep517 "pillow (==9.5.0)"'.

### What are your OS, Python and Pillow versions?

* OS:  MacOS 14.4
* Python: 3.12
* Pillow: 9.5.0

```python
poetry add pillow==9.5.0
```

**Comment by radarhere** [comment]
Hi. Have you tried to install the latest version of Pillow (10.2.0)?

**Comment by ViviLuD** [comment]
Yes, I the problem is I need the version 9.5.0 because I'm using the package tkhtmlview and I have this issue:

Because no versions of tkhtmlview match >0.2.0,<0.3.0
 and tkhtmlview (0.2.0) depends on Pillow (>=9.4.0,<10.0.0), tkhtmlview (>=0.2.0,<0.3.0) requires Pillow (>=9.4.0,<10.0.0).
So, because hank depends on both pillow (^10.2.0) and tkhtmlview (^0.2.0), version solving failed.

**Comment by radarhere** [comment]
Then I would suggest that you go to https://github.com/bauripalash/tkhtmlview and ask them to upgrade their version of Pillow.

**Comment by radarhere** [comment]
https://github.com/bauripalash/tkhtmlview/issues/49 has been created.
