### ISSUE TITLE
What does the integer in Kmeans in Image.quantize mean?

### ISSUE THREAD

**Issue by AeroDEmi** [python-pillow/Pillow#7890]
I'm having trouble understanding the Integer argument of Kmeans in [Image.quantize](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.quantize)

**Comment by Yay295** [comment]
So the C quantize function passes the `kmeans` value to the `ImagingQuantize` function,

https://github.com/python-pillow/Pillow/blob/ca973709a079b5152b9670e5cd684003aa71f913/src/_imaging.c#L1685-L1700

which passes it to the `quantize` or `quantize2` functions,

https://github.com/python-pillow/Pillow/blob/ca973709a079b5152b9670e5cd684003aa71f913/src/libImaging/Quant.c#L1761-L1782

which each do the same thing - check if it's 0, and if not, subtract 1 as they pass it to the `k_means` function.

https://github.com/python-pillow/Pillow/blob/ca973709a079b5152b9670e5cd684003aa71f913/src/libImaging/Quant.c#L1474-L1476

In the `k_means` function the value is now called `threshold`,

https://github.com/python-pillow/Pillow/blob/ca973709a079b5152b9670e5cd684003aa71f913/src/libImaging/Quant.c#L1158-L1165

and it determines the number of pixel changes that are allowed during each loop of the k-means quantization algorithm, ending when the number of changes is less than or equal to the threshold.

**Comment by Yay295** [comment]
It should probably be mentioned that `dither` is only used when `palette` is given, and if `palette` is given then `colors`, `method`, and `kmeans` are ignored.

**Comment by radarhere** [comment]
> It should probably be mentioned that `dither` is only used when `palette` is given

#5836 is actually an open issue that expects this not to be the case.

**Comment by Yay295** [comment]
It looks like `kmeans` needs to be non-negative, but I don't see a check for that. I think it would get stuck in an infinite loop. It also seems like it might be possible to get stuck in a loop if `kmeans` is small and the number of changes in each loop never gets below that value.

**Comment by Yay295** [comment]
To answer your original question @AeroDEmi, the `kmeans` parameter determines how the quantization uses [k-means clustering](https://en.wikipedia.org/wiki/K-means_clustering). If it's 0, then it doesn't use k-means clustering at all. Otherwise, `kmeans` should be an integer from 1 though the number of pixels in your image, with smaller values meaning that it will try harder to find the best color palette to use.

**Comment by AeroDEmi** [comment]
Awesome, Thank you!
Yeah it seems that `kmeans=0` the n_colors is given by the count and if `kmeans>0` it will find the different clusters.
FYI If you put something <0 it gets stuck in an infinite loop.

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/7891 to fix the infinite loop.

Otherwise, your question has been answered?
