### ISSUE TITLE
ImageGrab.grab() unable to capture screenshot with bounding box coordinates on main screen when external monitor is attached

### ISSUE THREAD

**Issue by rockyko** [python-pillow/Pillow#7898]
### What did you do?
 I used PIL.ImageGrab.grab() to capture screenshot by specifying the bounding box coordinates based on two mouse clicks. These clicks corresponded to the top left and bottom right corners while an external monitor was connected

### What did you expect to happen?
I expected PIL.ImageGrab.grab() to accurately capture the precise screenshot of the specified region on main screen.

### What actually happened?
Unfortunately, PIL.ImageGrab.grab() did not capture the precise screenshot as expected. The issue occurred when using the specified corner coordinates on the main screen while an external monitor was connected.

However, the code works fine when trying to grab the screenshot in a standalone monitor setup or just capturing external monitor screen.

### What are your OS, Python and Pillow versions?

* OS: windows 11
* Python: 3.12
* Pillow: 10.2.0

```python
from PIL import ImageGrab
from io import BytesIO
import win32clipboard
import win32api
import win32con
import time

def send_to_clipboard(clip_type, data):
    win32clipboard.OpenClipboard()
    win32clipboard.EmptyClipboard()
    win32clipboard.SetClipboardData(clip_type, data)
    win32clipboard.CloseClipboard()

# Screenshot to clipboard
def screenshot_to_clipboard(top_left_corner_x, top_left_corner_y, bottom_right_corner_x, bottom_right_corner_y):
    img = ImageGrab.grab(bbox=(top_left_corner_x, top_left_corner_y, bottom_right_corner_x, bottom_right_corner_y), all_screens=True)
    output = BytesIO()
    img.convert("RGB").save(output, "BMP")
    data = output.getvalue()[14:]
    output.close()
    send_to_clipboard(win32clipboard.CF_DIB, data)

# Get position
def get_pos():
    positions = []
    click_count = 0

    print("Click TOP left and bottom-right corner and parse position...")
    print("Re-click to rectify if you make a mistake.")

    while click_count < 2:
        if win32api.GetAsyncKeyState(win32con.VK_LBUTTON) < 0:
            while win32api.GetAsyncKeyState(win32con.VK_LBUTTON) < 0:
                pass
            x, y = win32api.GetCursorPos()
            positions.append((x, y))
            click_count += 1
            time.sleep(0.1) # Debounce delay

    screenshot_to_clipboard(*positions[0], *positions[1])

get_pos()

```

**Comment by nulano** [comment]
> Unfortunately, PIL.ImageGrab.grab() did not capture the precise screenshot as expected. The issue occurred when using the specified corner coordinates on the main screen while an external monitor was connected.

Can you clarify what exactly this means? Are the coordinates slightly different perhaps? A full desktop screenshot with some marking showing the area you intended to capture and the area actually captured might be helpful.

**Comment by rockyko** [comment]
> > Unfortunately, PIL.ImageGrab.grab() did not capture the precise screenshot as expected. The issue occurred when using the specified corner coordinates on the main screen while an external monitor was connected.
> 
> Can you clarify what exactly this means? Are the coordinates slightly different perhaps? A full desktop screenshot with some marking showing the area you intended to capture and the area actually captured might be helpful.

When I try to get full screenshot, I try to locate the bottom right corner coordinates by using win32api.GetCursorPos(), it failed as shown below.  The actual needed coordinates for ImageGrab.grab() is very different.
![bbox](https://github.com/python-pillow/Pillow/assets/79775825/589be1cb-720f-43cc-a252-cfddb997f0e4)

**Comment by nulano** [comment]
Ok, I'm assuming your left monitor resolution is 2560x1600 with 150% scaling?

It looks like the coordinates returned by `win32api.GetCursorPos()` are wrong due to display scaling. You should be able to get the correct coordinates if you first call:
```python
from ctypes import windll, wintypes
DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE = wintypes.HANDLE(-3)
windll.user32.SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE)
```

For example, I have a 3840x2160 monitor with 150% scaling and placing the cursor near the bottom right corner I get the following values with the second one being correct:
```
C:\Users\Nulano>"\Program Files\Python311\python.exe"
Python 3.11.4 (tags/v3.11.4:d2340ef, Jun  7 2023, 05:45:37) [MSC v.1934 64 bit (AMD64)] on win32
Type "help", "copyright", "credits" or "license" for more information.
>>> import win32api
>>> win32api.GetCursorPos()
(2542, 1435)
>>> from ctypes import windll, wintypes
>>> DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE = wintypes.HANDLE(-3)
>>> windll.user32.SetThreadDpiAwarenessContext(DPI_AWARENESS_CONTEXT_PER_MONITOR_AWARE)
-2147459056
>>> win32api.GetCursorPos()
(3820, 2156)
>>>
```

**Comment by rockyko** [comment]
The solution works, thank you for solving my problem
