### ISSUE TITLE
Code-friendly way to get supported file types

### ISSUE THREAD

**Issue by stevecj** [python-pillow/Pillow#7939]
In the project that I work on, we currently have a hard-coded list of file extensions that we can use Pillow to make thumbnails from, but it would make more sense to ask Pillow for that.

The text output from `PIL.features.pilinfo()` contains that information, but there is no obvious way to get that information in a code-friendly rather than human-friendly format. I looked at the definition of the `pilinfo` function, and it iterates over a hard-coded sequence, so any attempt to use lower-level code in Pillow to get that info would required duplicating code and risking it drifting out of date.

**Comment by Yay295** [comment]
it's here:
```python
from PIL import Image
Image.registered_extensions()
```

**Comment by Yay295** [comment]
Though I suppose that doesn't specify if it's read-only, write-only, or read-write.

**Comment by Yay295** [comment]
These variables aren't documented, but you could do the same thing as `pilinfo()` to get the data.

https://github.com/python-pillow/Pillow/blob/aeeb596c98fe4c9cd79cc1408eb7a3353c43eef1/src/PIL/features.py#L311-L336

**Comment by Yay295** [comment]
If anyone else thinks this is something Pillow should have a proper method for, I have an idea for an implementation I can work on. Otherwise I'll leave it as it is.

**Comment by radarhere** [comment]
This should give you a list of file extensions that Pillow can save to.
```python
from PIL import Image
for extension, id in Image.registered_extensions().items():
    if id in Image.SAVE:
        print(extension)
```

**Comment by stevecj** [comment]
Thanks for the replies, everyone. 😄  `Image.registered_extensions()` is close enough to what I want to be usable for my purposes.

**Comment by stevecj** [comment]
I didn't think that code was a list of image types, BTW, but I did think it was necessary to repeat that list/logic to get the list of image types.
