### ISSUE TITLE
Image.filename is not an exposed property

### ISSUE THREAD

**Issue by bburtin** [python-pillow/Pillow#7941]
The Pillow reference says that [Image.filename](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.filename) is an attribute, but VSCode doesn't auto-complete it.  This code works:

![Pillow filename screenshot](https://github.com/python-pillow/Pillow/assets/5264133/a7fd6998-08df-4da5-84fc-edace7369344)

but VSCode shows `image.filename` as white whereas the other attributes are blue.  Is it possible to make `Image.filename` a declared Python attribute so that developers have confidence that their code will work?

I'm using Pillow 10.3.0.

**Comment by nulano** [comment]
From https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.filename:
> Only images created with the factory function open have a filename attribute.

We currently do not have a way to distinguish how an Image was created, so there is no simple way to add the attribute AFAIK.

**Comment by bburtin** [comment]
Thanks for the fast response!  It's not possible to declare the Python property as `str | None` and only set it when `Image.open()` is called?

**Comment by nulano** [comment]
Declaring `filename: str | None` implies that `image.filename` will not raise an `AttributeError` as it currently does:

```
>>> from PIL import Image
>>> Image.new("RGB", (10, 10)).filename
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
AttributeError: 'Image' object has no attribute 'filename'
```

**Comment by radarhere** [comment]
> perhaps we should consider changing that to PIL.ImageFile.ImageFile since (based on a quick search) all of the existing image plugins seem to use that as their base class.

The `factory` that `Image.open` uses is already hinted to return `ImageFile.ImageFile`, so yes, this makes sense.

https://github.com/python-pillow/Pillow/blob/e8ab5640774716c5486d3cb05167f74f742ad6ef/src/PIL/Image.py#L3298
https://github.com/python-pillow/Pillow/blob/e8ab5640774716c5486d3cb05167f74f742ad6ef/src/PIL/Image.py#L222-L228

I've created https://github.com/python-pillow/Pillow/pull/7943

**Comment by nulano** [comment]
And I've just created #7944 to the the same thing, as well as add type hints for the `Image.open` parameters. 😄
