### ISSUE TITLE
fontfamily (font1 (include some chars)+font2(include most chars)) cannot show some characters

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#7946]
fontfamily (font1 (include some chars)+font2(include most chars)) cannot show some characters

font1: see attachment.

font2: Arial Unicode MS.ttf or any other fonts
str = 'をも資资儲储議议歷历權权個个TextInAaBbCcDdEeFfGgHhIi  family PILLOW'

![image](https://github.com/python-pillow/Pillow/assets/41010669/40208eae-c3ef-42c2-a47a-4a2ba64e34da)

[ballpen.zip](https://github.com/python-pillow/Pillow/files/14883724/ballpen.zip)

**Comment by nulano** [comment]
https://github.com/python-pillow/Pillow/pull/6926 has not been merged yet, please keep discussions about it in [the PR](https://github.com/python-pillow/Pillow/pull/6926) and avoid creating new issues.

Please provide code demonstrating the error (by commenting in https://github.com/python-pillow/Pillow/pull/6926).
