### ISSUE TITLE
pillow gets wrong size of a jpg image

### ISSUE THREAD

**Issue by yinkaisheng** [python-pillow/Pillow#7953]
I have a jpg file, its size is w 3840 * h 5760, Window Explorer and opencv show it as w 3840 * h 5760, 
but pillow shows that its size is w 5760 * h 3840.
I also get w 5760 * h 3840 by Windows GDI+ API and MediaInfo.exe
![image](https://github.com/python-pillow/Pillow/assets/5846696/39143592-9b5c-40de-b311-2b1ccda49e42)
What happens?

### What are your OS, Python and Pillow versions?

* OS: Windows 11
* Python: 3.11.8 x64
* Pillow: 10.3.0

```python
from PIL import Image
import cv2

path=r'f:\media\pictures\447A5354.JPG'
im=Image.open(path)
im.size

img=cv2.imread(path)
img.shape # height, width, channel

import matplotlib.pyplot as plt
plt.imshow(cv2.cvtColor(img, cv2.COLOR_BGR2RGB));    plt.show()
```
![image](https://github.com/python-pillow/Pillow/assets/5846696/aae0ef6f-74c0-4132-bad2-43d56f47c24c)
----
The jpg file is [447A5354.zip](https://github.com/python-pillow/Pillow/files/14895456/447A5354.zip)

**Comment by Yay295** [comment]
That image has rotation applied via Exif data. The raw image data is landscape, but image viewers will automatically rotate it due to the Exif attribute.

try this
```python
from PIL import Image, ImageOps

path = r'f:\media\pictures\447A5354.JPG'
im = Image.open(path)
im = ImageOps.exif_transpose(im)
print(im.size)
```

**Comment by yinkaisheng** [comment]
> That image has rotation applied via Exif data. The raw image data is landscape, but image viewers will automatically rotate it due to the Exif attribute.
> 
> try this
> 
> ```python
> from PIL import Image, ImageOps
> 
> path = r'f:\media\pictures\447A5354.JPG'
> im = Image.open(path)
> im = ImageOps.exif_transpose(im)
> print(im.size)
> ```

Thanks, it works.
