### ISSUE TITLE
ImageSequence encounters an exception when JPEG pixels exceed 4096*4096

### ISSUE THREAD

**Issue by YYH2913** [python-pillow/Pillow#7954]
When using the Pillow library to handle images larger than 4096x4096 pixels, I encountered a specific issue. Specifically, when I use ImageSequence.Iterator on a single-frame JPEG image exceeding this size, it unexpectedly iterates twice, producing two frames of different dimensions: one of the original size and one of a reduced size.
Here is a simplified version of the code I used:

```python
from PIL import Image, ImageOps, ImageSequence
import numpy as np
import torch

def load_image(image_path):
    img = Image.open(image_path)
    print("Original image size:", img.size)
    for i in ImageSequence.Iterator(img):
        i = ImageOps.exif_transpose(i)
        print("Processed frame size:", i.size)
```
And the output I received for an image of size 8192x5464 is:
Original image size: (8192, 5464)
Processed frame size: (8192, 5464)
Processed frame size: (1620, 1080)
And 4096x2731 is:
Original image size: (4096, 2731)
Processed frame size: (4096, 2731)

This behavior only occurs with images larger than 4096*4096 pixels, and as far as I understand, JPEG images should not be treated as multi-frame, which makes this behavior unexpected.

I'm using Pillow version 10.3.0. Has anyone else experienced this or found a workaround? Any insights or suggestions on this matter would be greatly appreciated.

Thank you!

**Comment by radarhere** [comment]
> JPEG images should not be treated as multi-frame

They are not, but be aware of the existence of [MPO](http://justsolve.archiveteam.org/wiki/Multi-Picture_Format) images that may use the .jpg extension.

If you `print(img)`, you can see what type of image Pillow has identified it as.

**Comment by YYH2913** [comment]
> > JPEG images should not be treated as multi-frame
> 
> They are not, but be aware of the existence of [MPO](http://justsolve.archiveteam.org/wiki/Multi-Picture_Format) images that may use the .jpg extension.
> 
> If you `print(img)`, you can see what type of image Pillow has identified it as.

The image type is indeed MPO. Thank you very much for your help.
