### ISSUE TITLE
`ImageMath.eval` deprecation warning running `selftest.py`

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#7958]
During the release, `make release-test` runs `python3 selftest.py`:

```console
❯ python3 selftest.py
...
Running selftest:
<doctest __main__.testimage[57]>:1: DeprecationWarning: ImageMath.eval is deprecated and will be removed in Pillow 12 (2025-10-15). Use ImageMath.lambda_eval or ImageMath.unsafe_eval instead.
  im = ImageMath.eval("float(im + 20)", im=im.convert("L"))
--- 59 tests passed.
```

Here's the `eval`:
https://github.com/python-pillow/Pillow/blob/33a73b5266c6589e21cc32a381fe907e23161877/selftest.py#L142

Shall we rewrite it as `lambda_eval`, catch the deprecation warning, or just remove it?

**Comment by radarhere** [comment]
Rewriting it with `lambda_eval` would be my suggestion. #7960
