### ISSUE TITLE
Add small number of carefully curated screenshots to handbook tutorial

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#7962]
Anyone interested in seeing a few ideally helpful screenshots added to the handbook tutorial? E.g. 

<img width="896" alt="Screenshot 2024-04-10 at 8 33 10 AM" src="https://github.com/python-pillow/Pillow/assets/72164/8c6edec8-fa78-4097-87b2-fbcbb5564dce">

I may like to see this done, but am also concerned we shouldn't be adding images to the main repository for a variety of reasons perhaps, but mostly size concerns.

I'm working on a Pillow demo where I follow the handbook tutorial and if nothing else they can go there. But I also wanted to rule-out-or-in the possibility of including some of these screenshots in the handbook proper. Thanks for any thoughts.

**Comment by wiredfool** [comment]
I think images/screenshots in the tutorial are a net benefit.

**Comment by Yay295** [comment]
Could images in the documentation be external links, instead of keeping them all in this repository? It might make updating the images a bit more difficult, but I don't think that would need to happen often.

**Comment by aclark4life** [comment]
> Could images in the documentation be external links, instead of keeping them all in this repository? It might make updating the images a bit more difficult, but I don't think that would need to happen often.

Maybe, but may not be worth doing in that case. Also just checked the distribution and we don't include any of the docs anyway so as long as these screenshots are not LFS-size should be OK, stay tuned for PR.

**Comment by radarhere** [comment]
@aclark4life is this still something on your to-do list, or should someone else take a crack at it?
