### ISSUE TITLE
KeyError: 'setting text direction, language or font features is not supported without libraqm'

### ISSUE THREAD

**Issue by luohao123** [python-pillow/Pillow#7968]
I have libraqm installed?

```
ls /opt/homebrew/lib | grep libraqm
libraqm.0.dylib
libraqm.dylib
```

and this path is in my PATH varaible.

Why can not find?

**Comment by radarhere** [comment]
Have you checked if libfribidi.dylib is also present?

https://pillow.readthedocs.io/en/stable/installation/basic-installation.html#basic-installation
> Raqm support requires FriBiDi to be installed separately

For some general background, what version of Pillow are you using? Could you paste the output of `python3 -m PIL --report`? It might also be helpful if you provide some simple code to demonstrate the problem, just so we know you're not manually setting the layout engine to BASIC.

**Comment by luohao123** [comment]
I have using 

pip install --upgrade Pillow  --global-option="build_ext" --global-option="--enable-raqm --enable-jpeg --enable-freetype" 

solved it.


But now..

Wrong JPEG library version: library is 90, caller expects 80

Why nowadays Pillow so many issues....

**Comment by radarhere** [comment]
Discussion about the JPEG matter can continue in https://github.com/python-pillow/Pillow/issues/7969
