### ISSUE TITLE
Wrong JPEG library version: library is 90, caller expects 80

### ISSUE THREAD

**Issue by luohao123** [python-pillow/Pillow#7969]
Using build againt system lib:

pip install --upgrade Pillow  --global-option="build_ext" --global-option="--enable-raqm --enable-jpeg --enable-freetype"

Didn't work???

**Comment by radarhere** [comment]
From [your other issue](https://github.com/python-pillow/Pillow/issues/7968), I see that you are a homebrew user. Could you tell us what JPEG packages you have installed through homebrew?
