### ISSUE TITLE
Unknown test comment

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#7991]
What is "bug-200802-systemerror"?

https://github.com/python-pillow/Pillow/blob/f8160b858aebf8b7bffdefba48735feac300a060/Tests/test_image_putdata.py#L32-L46

@cgohlke This comes all the way from your original tests. I don't suppose you remember what this was?

**Comment by cgohlke** [comment]
Not from me. Those tests come from Fredrik Lundh's pil-1.1.7.  Maybe "bug-200802-systemerror" is a reference to a bug reported in 2008?

**Comment by nulano** [comment]
Checking the metadata archive from https://bitbucket-archive.softwareheritage.org/projects/ef/effbot/pil-2009-raclette.html, I get no hits with grep for "systemerror", "putpixel", nor "putdata".

I've also tried checking the [Image-SIG mailing list archive](https://mail.python.org/pipermail/image-sig/), but I can't see anything relevant.

**Comment by nulano** [comment]
> The commit is "Handle long integers in putpixel/putdata." by Fredrik aka effbot on Apr 25, 2010:
> https://github.com/hugovk/pil-2009-raclette/commit/52970c61e62ddfc9b8fdc2370a785c69628cbbcf


The Pillow version of that commit is https://github.com/python-pillow/Pillow/commit/c8ce29c23903b5145ed0e1a23804e7e99faa5eb8 from #35:

> FIX: Handle long values in _imaging getink
>
> This gets the putdata test case to run correctly under 2.6/2.7. It fixes an
> issue where the value 0xFFFFFFFF (which is long in old Python) isn't
> recognized and putdata tries to parse it as a tuple.
>
> The original fix comes from Christoph Gohlke. It was adapted to work in
> both 2.* and 3.*.

**Comment by Yay295** [comment]
That seems like the answer to me. I don't know what the exact error report was, but it looks like it was something to do with big numbers and Python 2/3 compatibility.

**Comment by radarhere** [comment]
https://github.com/python-pillow/Pillow/pull/8017 now suggests removing this comment.
