### ISSUE TITLE
Unable to install Pillow on M1 Mac (Clang error)

### ISSUE THREAD

**Issue by NiekPas** [python-pillow/Pillow#8035]
### What did you do?

I ran `pip install Pillow`.

### What did you expect to happen?

I expected pip to install Pillow.

### What actually happened?

I got a compilation error:

```pytb
Collecting pillow
  Using cached pillow-10.3.0.tar.gz (46.6 MB)
  Installing build dependencies: started
  Installing build dependencies: finished with status 'done'
  Getting requirements to build wheel: started
  Getting requirements to build wheel: finished with status 'done'
  Installing backend dependencies: started
  Installing backend dependencies: finished with status 'done'
  Preparing metadata (pyproject.toml): started
  Preparing metadata (pyproject.toml): finished with status 'done'
Building wheels for collected packages: pillow
  Building wheel for pillow (pyproject.toml): started
  Building wheel for pillow (pyproject.toml): finished with status 'error'
  error: subprocess-exited-with-error

  × Building wheel for pillow (pyproject.toml) did not run successfully.
  │ exit code: 1
  ╰─> [18953 lines of output]

[snip]

      error: command '/opt/homebrew/opt/llvm@12/bin/clang' failed with exit code 1
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for pillow
Failed to build pillow
ERROR: Could not build wheels for pillow, which is required to install pyproject.toml-based projects
```

Digging through the clang output, I mostly see a bunch of warnings (not errors) of the form `warning: unknown platform 'visionos' in availability macro [-Wavailability]`. I tried to grep for `err` or `fatal` but couldn't find anything in the output, [which I've uploaded as a Gist here](https://gist.github.com/NiekPas/fd85a9139d06565af5df46177e97741f).

Command-line tools for macOS are installed properly, and I'm able to build other Pip packages.

### What are your OS, Python and Pillow versions?

* OS: `macOS Sonoma 14.3.1`
* Python: `Python 3.9.19` (I've tried using `3.10` as well)
* Pillow: -

**Comment by aclark4life** [comment]
Can you try `pip install -U pip` then try again? Seems like pip should be choosing one of the `arm64` wheels here: https://pypi.org/project/pillow/10.3.0/#files but instead it's falling back to compilation, which then fails.

**Comment by NiekPas** [comment]
Thanks for checking in.

```
> pip install -U pip
Requirement already satisfied: pip in /Users/niekvdpas/.pyenv/versions/3.10.14/lib/python3.10/site-packages (24.0)

> pip install pillow
[same result]
```

No luck unfortunately.

**Comment by hugovk** [comment]
Please could you try reinstalling with `-vv` for extra debug output? It will tell us which wheels it attempted and why it skipped them.

And also run `pip debug --verbose` to show your compatible tags.

**Comment by hugovk** [comment]
And what does `python --version --version` say?

**Comment by radarhere** [comment]
Thanks for those logs. The log of `pip install pillow -vv` keeps saying
> run pip debug --verbose to show compatible tags

What does `pip debug --verbose` show?

**Comment by radarhere** [comment]
For a slightly odd idea, since `pip debug --verbose` lists "cp310-cp310-macosx_10_16_arm64", and 10.16 and 11.0 are the same thing, you could download [pillow-10.3.0-cp310-cp310-macosx_11_0_arm64.whl](https://files.pythonhosted.org/packages/d4/0e/e344d6532f30b3b8de3d7a36fd05d5a43e4164afd1b41882529e766ef959/pillow-10.3.0-cp310-cp310-macosx_11_0_arm64.whl), rename it to pillow-10.3.0-cp310-cp310-macosx_10_16_arm64.whl, and try installing that.

**Comment by radarhere** [comment]
https://github.com/pypa/pip/issues/11789 talks about a faliure to find macOS 11 wheels with Python 3.8, and the problem seems to be outdated packaging.

Could you `pip install --upgrade packaging` and then try installing Pillow again?

**Comment by NiekPas** [comment]
Thanks for the help! The renaming trick worked :)

Upgrading packaging did not seem to do anything, unfortunately.

**Comment by NiekPas** [comment]
Hang on, I'm now getting an error when trying to import:

```
import pytesseract
from PIL import Image
```

```
Traceback (most recent call last):
  File "/Users/niekvdpas/code/ocr.py", line 1, in <module>
    import pytesseract
  File "/Users/niekvdpas/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pytesseract/__init__.py", line 2, in <module>
    from .pytesseract import ALTONotSupported
  File "/Users/niekvdpas/.pyenv/versions/3.10.14/lib/python3.10/site-packages/pytesseract/pytesseract.py", line 27, in <module>
    from PIL import Image
  File "/Users/niekvdpas/.pyenv/versions/3.10.14/lib/python3.10/site-packages/PIL/Image.py", line 94, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL' (/Users/niekvdpas/.pyenv/versions/3.10.14/lib/python3.10/site-packages/PIL/__init__.py)
```

Seems like the installation may not have been as succesful as it seemed

**Comment by radarhere** [comment]
Given your multiple attempts at installation, could you `pip uninstall Pillow`, make sure you can't import Pillow at all (if not, uninstall again), and then try installing from the renamed wheel again?

**Comment by NiekPas** [comment]
Ah, that fixed it! Thanks so much!
