### ISSUE TITLE
Saving a CMYK image as .jp2/.j2k fails

### ISSUE THREAD

**Issue by sl2c** [python-pillow/Pillow#8062]
When running

`Image.open('cmyk.tif').save('out.jp2')`

I get:

`OSError: encoder error -2 when writing image file`

Same with writing to '.j2k'. Same with other CMYK images I tried. I am using Pillow v. 10.1.0.

[cmyk.tif.zip](https://github.com/python-pillow/Pillow/files/15321057/cmyk.tif.zip)

**Comment by radarhere** [comment]
I've created https://github.com/uclouvain/openjpeg/pull/1529 as the first step in saving JP2 CMYK images.

Without the colour specification box of JP2, it doesn't seem possible to have a CMYK J2K image.

https://community.intel.com/t5/Intel-Integrated-Performance/JPEG2000-and-CMYK-Data-Not-RGB/td-p/862891
> JPEG 2000 encoding doesn't support CMYK coding, mostly because it's an extension of JP2 file container (part 2 of the standard)

https://newsgroup.xnview.com/viewtopic.php?t=29274
> the JPEG-2000 standard does not specify any means for encoding color space information in a JPEG-2000 code stream, the decoder must make certain assupmtions about the color space of an image. If accurate color representation is important, the JPEG-2000 code stream format should not be employed. The JPEG-2000 JP2 format should be used instead.

**Comment by radarhere** [comment]
OpenJPEG 2.5.3 has now been released, so I've created #8592 to add CMYK JP2 saving.

If you build Pillow from source, then you should note this will need OpenJPEG 2.5.3 to be installed.
If you install Pillow from wheels, then this will also need #8591.
