### ISSUE TITLE
Why do Pillow's wheels put shared objects in the non-standard `.dylibs` directory on macOS (and thereby break code-signing without tons of additional support code)?

### ISSUE THREAD

**Issue by glyph** [python-pillow/Pillow#8073]
I am opening this issue with a relatively low level of information because investigating what exactly is going on with all the build scripts is a fair amount of work, and someone more familiar with that system might be able to fill in the blanks far more quickly than I could. However, if the report is not clear, I can put in the effort to do a more substantive investigation and produced detailed error logs; I assume I'll have to do *some* of that but given how time-consuming and expensive it is to build a minimal code-signable app that can produce the relevant errors, I'd rather react to specific questions than try to have everything ready before filing a report.

### What did you do?

I tried to code-sign a macOS application that used pillow and found that dylibs were being squirreled away inside a zip file instead of in more standard locations

### What did you expect to happen?

for the code-signing to work

### What actually happened?

notarization failed, and I need to do this: https://github.com/glyph/Encrust/issues/5

### What are your OS, Python and Pillow versions?

* OS: 
```
ProductName:		macOS
ProductVersion:		14.5
BuildVersion:		23F79
```
* Python: 3.11.9
* Pillow: 10.3.0

```text
--------------------------------------------------------------------
Pillow 10.3.0
Python 3.11.9 (v3.11.9:de54cf5be3, Apr  2 2024, 07:12:50) [Clang 13.0.0 (clang-1300.0.29.30)]
--------------------------------------------------------------------
Python executable is /Users/glyph/.virtualenvs/tmp-47bc9cbebd0563a/bin/python3
Environment Python files loaded from /Users/glyph/.virtualenvs/tmp-47bc9cbebd0563a
System Python files loaded from /Library/Frameworks/Python.framework/Versions/3.11
--------------------------------------------------------------------
Python Pillow modules loaded from /Users/glyph/.virtualenvs/tmp-47bc9cbebd0563a/lib/python3.11/site-packages/PIL
Binary Pillow modules loaded from /Users/glyph/.virtualenvs/tmp-47bc9cbebd0563a/lib/python3.11/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.2
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------
```

```python
code goes here
```

**Comment by glyph** [comment]
(It's also possible that Pillow is entirely the wrong project here and I should be reporting this on `cibuildwheel`, since I can't even find the string `".dylibs"` in this project; I don't really know exactly what is going on here)

**Comment by nulano** [comment]
I think you may be looking for https://github.com/matthew-brett/delocate

(Or perhaps you are asking why we use it?)

**Comment by radarhere** [comment]
> (Or perhaps you are asking why we use it?)

We don't, explicitly. It is cibuildwheel that [uses it.](https://github.com/pypa/cibuildwheel#legal-note)

**Comment by radarhere** [comment]
I agree that this is a question for delocate rather than Pillow

https://github.com/matthew-brett/delocate/blob/f6af44562dd90d0f9279ab77abeab607ee9c2ee0/delocate/delocating.py#L531-L534
```python
def _decide_dylib_bundle_directory(
    wheel_dir: str, package_name: str, lib_sdir: str = ".dylibs"
) -> str:
    """Return a relative directory which should be used to store dylib files.
```

From a glance at [your project](https://github.com/glyph/Encrust), I imagine you would be concerned about this situation for other libraries as well, so I think it is best to take this discussion [over there.](https://github.com/matthew-brett/delocate)

**Comment by glyph** [comment]
OK, will do!
