### ISSUE TITLE
Saving all frames of a paletted PNG with few colors can fail

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#8081]
```python
>>> image.save('copy.png',save_all=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\...\.venv\Lib\site-packages\PIL\Image.py", line 2459, in save
    save_handler(self, fp, filename)
  File "C:\...\.venv\Lib\site-packages\PIL\PngImagePlugin.py", line 1230, in _save_all
    _save(im, fp, filename, save_all=True)
  File "C:\...\.venv\Lib\site-packages\PIL\PngImagePlugin.py", line 1408, in _save
    im = _write_multiple_frames(
         ^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\.venv\Lib\site-packages\PIL\PngImagePlugin.py", line 1117, in _write_multiple_frames
    im_frame = im_frame.convert(rawmode)
               ^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\...\.venv\Lib\site-packages\PIL\Image.py", line 1087, in convert
    im = self.im.convert(mode, dither)
         ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ValueError: conversion not supported
```

The image isn't mine to share, but it's a `P` mode image with only 9 colors. This causes it to hit this bit of code:

https://github.com/python-pillow/Pillow/blob/8b14ed741a1c757734c65535ca1db4ab4162c843/src/PIL/PngImagePlugin.py#L1265-L1285

Which changes `mode` to `P;4`. Then when getting the output rawmode:

https://github.com/python-pillow/Pillow/blob/8b14ed741a1c757734c65535ca1db4ab4162c843/src/PIL/PngImagePlugin.py#L1297
https://github.com/python-pillow/Pillow/blob/8b14ed741a1c757734c65535ca1db4ab4162c843/src/PIL/PngImagePlugin.py#L1052-L1069

It gets a rawmode of `P;4`. This would all be fine, except I passed `True` for the `save_all` parameter, which causes a branch here:

https://github.com/python-pillow/Pillow/blob/8b14ed741a1c757734c65535ca1db4ab4162c843/src/PIL/PngImagePlugin.py#L1415-L1420

Inside `_write_multiple_frames` is this bit of code:

https://github.com/python-pillow/Pillow/blob/8b14ed741a1c757734c65535ca1db4ab4162c843/src/PIL/PngImagePlugin.py#L1122-L1125

Now since the actual image mode is `P`, but the requested rawmode is `P;4`, it tries to convert from `P` to `P;4`, which fails, because `Image.convert()` takes modes, not rawmodes, and `P;4` is not a valid mode.

This method also attempts to convert to a rawmode a bit further on as well:

https://github.com/python-pillow/Pillow/blob/8b14ed741a1c757734c65535ca1db4ab4162c843/src/PIL/PngImagePlugin.py#L1186-L1188

A basic search of the rest of Pillow's code only shows one other instance of ".convert(rawmode)" (in `WebPImagePlugin`), but it's okay in that case because the rawmode is set on the prior line to be either "RGB" or "RGBA".

**Comment by radarhere** [comment]
I've created #8087
