### ISSUE TITLE
Missing ImageDraw.Draw.circle function

### ISSUE THREAD

**Issue by void4** [python-pillow/Pillow#8083]
### What did you do?

I find it frustrating that Pillow's ImageDraw does still not have a function to draw a circle. Every time I come around to do it, I find that I must use ImageDraw.Draw.ellipse instead, which costs time. It must be even more frustrating for beginners who don't know more complex shapes like ellipses.

### What did you expect to happen?

An ImageDraw.Draw.circle to be available

### What actually happened?

It does not exist

### What are your OS, Python and Pillow versions?

* OS: Every
* Python: Every
* Pillow: Every

**Comment by hugovk** [comment]
Sounds like a useful shortcut, would you like to propose a PR?

**Comment by void4** [comment]
Aye, https://github.com/python-pillow/Pillow/pull/8085
