### ISSUE TITLE
New (since 10.1.0) font display is worse than "better than nothing font" for small sizes

### ISSUE THREAD

**Issue by dhylands** [python-pillow/Pillow#8084]
I'm using a small (128x32) [OLED display](https://www.adafruit.com/product/3527), which is setup as 4 lines of text on a Raspberry Pi 5 running Ubuntu Server 24.04 LTS.

### What did you do?

Upgraded my version of pillow (to any version from 10.1.0 or later)

### What did you expect to happen?

My display to be readable.

### What actually happened?

Some text is unreadable.  In particular, the 6's look almost the same as 8's

### What are your OS, Python and Pillow versions?

* OS: Ubuntu 22.04 and 24.04
* Python: 3.9.19, 3.10.12, 3.12.3
* Pillow: 10.3.0

```text
Pillow 10.3.0
Python 3.12.3 (main, Apr 10 2024, 05:33:47) [GCC 13.2.0]
--------------------------------------------------------------------
Python executable is /home/dhylands/adafruit-oled-ssd1306/.direnv/python-3.12.3/bin/python3
Environment Python files loaded from /home/dhylands/adafruit-oled-ssd1306/.direnv/python-3.12.3
System Python files loaded from /usr
--------------------------------------------------------------------
Python Pillow modules loaded from /home/dhylands/adafruit-oled-ssd1306/.direnv/python-3.12.3/lib/python3.12/site-packages/PIL
Binary Pillow modules loaded from /home/dhylands/adafruit-oled-ssd1306/.direnv/python-3.12.3/lib/python3.12/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.2
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1, fribidi 1.0.13, harfbuzz 8.4.0
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------
```

```python
from PIL import Image, ImageFont, ImageDraw

font = ImageFont.load_default(size=10)

line1 = "IP: 192.168.1.4"
line2 = "CPU load: 0.15"
line3 = "Mem: 341/7942 MB  4.29%"
line4 = "Disk: 2/58 GB  5%"

top = -2

image = Image.new("1", (128, 32))
draw = ImageDraw.Draw(image)
draw.rectangle((0, 0, 128, 32), outline=0, fill=0)
draw.text((0, top + 0), line1, font=font, fill=255)
draw.text((0, top + 8), line2, font=font, fill=255)
draw.text((0, top + 16), line3, font=font, fill=255)
draw.text((0, top + 25), line4, font=font, fill=255)

image.save("display.png")
```

Image from version 10.0.1 using `ImageFont.load_default()`
![display-better-than-nothing](https://github.com/python-pillow/Pillow/assets/127500/deea0c91-73bd-420a-a5da-80b4c3aa613a)

Image from version 10.3.0 using `ImageFont.load_default()`  (same results seen using 10.1.0 or later)
![display-default](https://github.com/python-pillow/Pillow/assets/127500/6a91be96-81eb-42df-aebe-5d6450eda773)

Image from 10.3.0 using `ImageFont.load_default(size=8)`
![display-8](https://github.com/python-pillow/Pillow/assets/127500/d6163c14-f588-4eee-bf40-8fa47883daf5)

Image from 10.3.0 using `ImageFont.load_default(size=9)`
![display-9](https://github.com/python-pillow/Pillow/assets/127500/4efa9375-4b92-4885-8df8-7ae63f0fed90)

Image from 10.3.0 using `ImageFont.load_default(size=10)`
![display-10](https://github.com/python-pillow/Pillow/assets/127500/0e6b0232-845f-48ec-9148-ade419ec4b55)

**Comment by radarhere** [comment]
If our default font isn't suitable for your purposes, would the easiest solution not be to simply find another font to use? Or are you requesting that provide a way to access to the previous default font?

**Comment by dhylands** [comment]
I guess I'm asking for a way to access the previous default font.
I'm dubious that raterizing a vector font is going to give decent results for characters that are only 8 pixels high, but I'm not a font expert.

**Comment by radarhere** [comment]
I've created #8086, to add `ImageFont.load_default_imagefont()`.
