### ISSUE TITLE
image.save('my.png", quality=85) does not work

### ISSUE THREAD

**Issue by xalteropsx** [python-pillow/Pillow#8088]
image.save('my.png", quality=85)  quality is not even working

**Comment by wiredfool** [comment]
PNG images are lossless, so they don’t take a quality argument.

**Comment by radarhere** [comment]
For a list of arguments that do work when saving PNGs, see https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html#png-saving

**Comment by radarhere** [comment]
Let us know if you have any further questions.
