### ISSUE TITLE
Blocky alpha-artifacts, webp save, Pillow: 10.3.0

### ISSUE THREAD

**Issue by MvGulik** [python-pillow/Pillow#8101]
When saving a RGBA image as webp it gives blocky alpha-artifacts around the target-none-transparent image part.
Using Pillow:10.3.0 "**im.save(filespec, 'webp')**"
Tried adding the default "**alpha_quality=100**". No change.
Tried lossless, Alpha now ok. (_but ofc target file-size is now not ok_)

### What did you do?
"im.save(filespec, 'webp')"
Using RGBA image.
Using alpha channel with only two values (0, 255) ... (_or at least that should be the case_.)

### What did you expect to happen?
Webp image with nice transparent (same as when saved as png)

### What actually happened?
Saved image shows blocky alpha-artifacts around the target-none-transparent-image part

### What are your OS, Python and Pillow versions?
* OS: Linux Mint 21.3 Cinnamon
* Python: 3.10.12
* Pillow: 10.3.0

???

**Comment by radarhere** [comment]
Could you upload a copy of the original image?

**Comment by MvGulik** [comment]
Odd ...

Did some additional testing on some test image. (_gimp created_)
Odd thing here is that if I open the output webp image with pillow and show() it. It looks ok. (_shown as png ofc_)
Same thing when I open the output webp image in gimp. It also looks ok.
But when viewed two other apps. It shows alpha-artifacts. (Merged_screenshots image)(Nip2 & gThump(bottom-left)

Related used code:
```
im = Image.open('.../test_circle(in).png', mode='r', formats=None)
im.save('.../test_circle(out).webp', 'webp')
```

Images:
![test_circle(in)](https://github.com/python-pillow/Pillow/assets/666868/89f56070-9605-4dde-95ef-905e60e9293b)
![Merged_screenshots](https://github.com/python-pillow/Pillow/assets/666868/3ec79e4e-fe2b-4390-88cd-ce36ef8a727b)

**Comment by MvGulik** [comment]
... are those other apps potentially using some outdated webp support code ?
