### ISSUE TITLE
Saving to apng has wrong durations

### ISSUE THREAD

**Issue by Yay295** [python-pillow/Pillow#8102]
Using https://github.com/python-pillow/Pillow/blob/main/Tests/images/apng/different_durations.png

```python
from PIL import Image, ImageSequence

ddp = Image.open('different_durations.png')
print([frame.info.get('duration') for frame in ImageSequence.Iterator(ddp)]) # [4000.0, 1000.0]
ddp.save('different_durations.gif',save_all=True)

ddg = Image.open('different_durations.gif')
print([frame.info.get('duration') for frame in ImageSequence.Iterator(ddg)]) # [4000, 1000]
ddg.save('same_durations.png',save_all=True)

sdp = Image.open('same_durations.png')
print([frame.info.get('duration') for frame in ImageSequence.Iterator(sdp)]) # [1000.0, 1000.0]
```

Also, ImageMagick (version 7.1.1-33) says the duration of the second frame is actually 990, not 1000.
```sh
> magick identify -format %T\n apng:different_durations.png
400
99
```
I'm not sure what's going on there though, because the duration parsing isn't complicated.
https://github.com/python-pillow/Pillow/blob/219add02393d6e63276286908ecd9014271c941c/src/PIL/PngImagePlugin.py#L669-L672

**Comment by radarhere** [comment]
Regarding saving to APNG, I've created #8104

I'm having trouble convincing ImageMagick to tell me the durations on my local machine or on GitHub Actions. I opened different_durations.png with https://davidmz.github.io/apng-js/ and it reported 4000 and 1000. If you think that ImageMagick isn't reading the duration [according to the specification](https://wiki.mozilla.org/APNG_Specification#.60fcTL.60:_The_Frame_Control_Chunk), then maybe that's something for you to raise with ImageMagick?

**Comment by Yay295** [comment]
I don't know why I didn't check this before, but saving from APNG to APNG has the same issue; it not only when the source is a GIF.
```python
from PIL import Image, ImageSequence
ddp = Image.open('different_durations.png')
ddp.save('ddc.png',save_all=True)
ddc = Image.open('ddc.png')
print([frame.info.get('duration') for frame in ImageSequence.Iterator(ddc)]) # [1000.0, 1000.0]
```

I think it probably is an issue in ImageMagick, or rather in libpng. I've filed an issue with ImageMagick though.

**Comment by radarhere** [comment]
The ImageMagick issue is https://github.com/ImageMagick/ImageMagick/issues/7371

**Comment by radarhere** [comment]
ImageMagick has made a change to fix their problem.
