### ISSUE TITLE
Fails to open OME-TIFF example data files

### ISSUE THREAD

**Issue by anntzer** [python-pillow/Pillow#811]
[OME-TIFF](https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/index.html) is a TIFF format that embeds some microscopy-specific metadata as an XML comment embedded in the TIFF header.  Sample data is available at https://www.openmicroscopy.org/site/support/ome-model/ome-tiff/data.html, but PIL fails to open `single-channel.ome.tiff` (throwing `OSError: cannot identify image file 'single-channel.ome.tiff'`).

**Comment by radarhere** [comment]
Just a direct link to the sample image - https://downloads.openmicroscopy.org/images/OME-TIFF/2016-06/bioformats-artificial/single-channel.ome.tiff

**Comment by radarhere** [comment]
I've created PR #7111 to resolve this.
