### ISSUE TITLE
Disable JFIF header when writing EXIF into JPEG

### ISSUE THREAD

**Issue by regen100** [python-pillow/Pillow#812]
When writing EXIF `img.save('img.jpg', exif=data)`, Pillow writes both APP0 (JFIF header) and APP1 (EXIF).
Some applications require APP1 next to SOI, so Pillow should disable JFIF header when writing EXIF.

**Comment by aclark4life** [comment]
Wow this is old. Is this really a thing? I suppose if the EXIF spec specifies the JFIF header should be disabled when writing EXIF then this is a valid issue.

**Comment by radarhere** [comment]
http://dev.exiv2.org/projects/exiv2/wiki/The_Metadata_in_JPEG_files

> In theory, Exif APP1 is recorded immediately after the SOI marker (the marker indicating the beginning of the file). However, this leads to the incompatibility between the Exif and JFIF standards because both of them specify that their particular application segment (APP0 for JFIF, APP1 for Exif) must be the first in the image file. In practice, most JPEG files contain a JFIF marker segment (APP0) that precedes the Exif APP1. This allows older readers to correctly handle the format JFIF segment, while newer readers also decode the following Exif segment, being less strict about requiring it to appear first. This way will not affect the image decoding for most decoders, but poorly designed JFIF or Exif parsers may not recognize the file properly.

**Comment by radarhere** [comment]
For another source, with the same wording strangely enough, https://en.wikipedia.org/wiki/JPEG_File_Interchange_Format

> The newer Exchangeable image file format (Exif) is comparable to JFIF, but the two standards are mutually incompatible. This is because both standards specify that their particular application segment (APP0 for JFIF, APP1 for Exif) must immediately follow the SOI marker. In practice, many programs and digital cameras produce files with both application segments included. This will not affect the image decoding for most decoders, but poorly designed JFIF or Exif parsers may not recognise the file properly.

Closing, as unless someone has an argument otherwise, the current behaviour would seem to be the standard.
