### ISSUE TITLE
PIL.UnidentifiedImageError: cannot identify image file

### ISSUE THREAD

**Issue by ZOMGVTEK** [python-pillow/Pillow#8122]
Hey There.

I've been struggling with this one for a bit now. I have code that works fine to pull all the images from Coingecko, and store them in a uniform format. It works on all the ~14,600 images except for 3.
```python
tokenimageurl = "https://api.coingecko.com/api/v3/coins/"+coin+"?tickers=false&market_data=false&community_data=false&developer_data=false&sparkline=false?raw=true"
rawimage2 = requests.get(tokenimageurl, headers=headers)
rawimage = rawimage2.json()
tokenimageRAW = io.BytesIO(requests.get(rawimage['image']['large'], headers=headers, stream=True).content)
tokenimageF1 = Image.open(tokenimageRAW)

coins = ['cellframe', 'for-loot-and-glory', 'universal-liquidity-union']
```
The code does further image processing from here. **The error always occurs at Image.open**. Coingecko uses several formats for the raw images, always 250x250, some have alpha layers and some do not. They display fine in a web browser.

https://coin-images.coingecko.com/coins/images/14465/large/cellframe-coingecko.png?1696514152
https://coin-images.coingecko.com/coins/images/20726/large/token_logo.ico?1696520124
https://coin-images.coingecko.com/coins/images/12376/large/ulu_finance_logo.ico?1696512200

[test_images.zip](https://github.com/user-attachments/files/15753863/test_images.zip)

OS: Debian 11.9
Python: 3.9.2
Pillow: 10.3.0

**Comment by Yay295** [comment]
I was able to open and load all three images from the attached ZIP archive.

**Comment by ZOMGVTEK** [comment]
That's curious, I wonder if its a server issue, or code issue pulling the image. I get this same error on 2 other coins, but those appear to be server issues since the coin image can't be pulled over the API in a browser without an error.

I'll try manually loading them on my end.

**Comment by radarhere** [comment]
I'm also able to open the images you've provided without a problem.

**Comment by ZOMGVTEK** [comment]
It was a server issue, and appears to now be fixed.

Thanks.
