### ISSUE TITLE
Formats build options?

### ISSUE THREAD

**Issue by blap-o** [python-pillow/Pillow#8123]
I have read the Build documentation and I know a couple of image formats can easily be disabled during build by using the different build options like `-C jpeg2000=disable`.

But Pillow supports 30+ image formats, and only a small part seem to be available as build option toggles.

Is it only possible to enable/disable the formats described in the Build options documentation?

**Comment by nulano** [comment]
These options are for enabling/disabling third-party dependencies, not image formats.
Some third-party dependencies are only required for a single image format, others are used for multiple image formats.
However, many image formats supported by Pillow have no third-party dependencies and so there is no such flag to disable them at build time.
If you'd like to disable them at run time, have a look at the [`formats`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.open) parameter to `Image.open`.
