### ISSUE TITLE
Incomplete discovery of libraries

### ISSUE THREAD

**Issue by laggron42** [python-pillow/Pillow#8130]
Hello!

I attempted to build Pillow with libraqm support, and had a lot of difficulties to get it to work. Specifically, the `raqm` and `webp` libraries would never be found without some edition.

With the following context returned by `pkg-config`:
```
$ pkg-config --list-all
libturbojpeg    libturbojpeg - A SIMD-accelerated JPEG codec that provides the TurboJPEG API
libwebp         libwebp - Library for the WebP graphics format
liblzma         liblzma - General purpose data compression library
libbrotlienc    libbrotlienc - Brotli encoder library
libopenjp2      openjp2 - JPEG2000 library (Part 1 and 2)
libwebpmux      libwebpmux - Library for manipulating the WebP graphics format container
libdeflate      libdeflate - Fast implementation of DEFLATE, zlib, and gzip
libpng16        libpng - Loads and saves PNG files
libsharpyuv     libsharpyuv - Library for sharp RGB to YUV conversion
freetype2       FreeType 2 - A free, high-quality, and portable font engine.
libbrotlidec    libbrotlidec - Brotli decoder library
zlib            zlib - zlib compression library
libpng          libpng - Loads and saves PNG files
lcms2           lcms2 - LCMS Color Management Library
libwebpdemux    libwebpdemux - Library for parsing the WebP graphics format container
libtiff-4       libtiff - Tag Image File Format (TIFF) library.
bzip2           bzip2 - Lossless, block-sorting data compression
libbrotlicommon libbrotlicommon - Brotli common dictionary library
raqm            raqm - A library for complex text layout
libjpeg         libjpeg - A SIMD-accelerated JPEG codec that provides the libjpeg API
libwebpdecoder  libwebpdecoder - Library for the WebP graphics format (decode only)
```
I'm supposed to have all the required dependencies, but both errors would occur when installing:

Log 1: https://gist.github.com/laggron42/5be2a2c66c25a913f711ac3893d7181a#file-log1-txt

Log 2 (after patching for libraqm): https://gist.github.com/laggron42/5be2a2c66c25a913f711ac3893d7181a#file-log2-txt

The solution I found was to patch `setup.py` like this:
```diff
--- a/setup.py
+++ b/setup.py
@@ -39,6 +39,8 @@ JPEG_ROOT = None
 LCMS_ROOT = None
 TIFF_ROOT = None
 ZLIB_ROOT = None
+RAQM_ROOT = None
+WEBP_ROOT = None
 FUZZING_BUILD = "LIB_FUZZING_ENGINE" in os.environ

 class DependencyException(Exception):
@@ -460,6 +462,8 @@ class pil_build_ext(build_ext):
             "HARFBUZZ_ROOT": "harfbuzz",
             "FRIBIDI_ROOT": "fribidi",
             "LCMS_ROOT": "lcms2",
+            "RAQM_ROOT": "raqm",
+            "WEBP_ROOT": "libwebp",
             "IMAGEQUANT_ROOT": "libimagequant",
         }.items():
             root = globals()[root_name]
```

Am I missing something here? It doesn't look right that I need to edit the source files for proper library discover, maybe my dependencies weren't installed the correct way.

For context, I'm using macOS 14.5 and nixpkgs as package manager. The dependencies were installed in a nix shell with the following command: `nix-shell -p libraqm libjpeg libtiff openjpeg libwebp zlib freetype lcms pkg-config`

**Comment by radarhere** [comment]
Hi. From your logs, Pillow is searching for raqm.h, but doesn't find it.

>       Checking for include file raqm.h in /nix/store/fbq6rwbqpwpvgs6jm5bzgqi5zf5h92wj-freetype-2.13.2-dev/include
>       Checking for include file raqm.h in /nix/store/0sksvw4kvr3j63md09z11b6q9xj776kj-libjpeg-turbo-2.1.5.1-dev/include
>       Checking for include file raqm.h in /nix/store/0phdb1r6chn6ifindy9d1436sy7b8wn4-openjpeg-2.5.0-dev/include/openjpeg-2.5
>       Checking for include file raqm.h in /nix/store/c8z6bw47x52fja2q85iqgi3gqnnp4854-libtiff-4.6.0-dev/include
>       Checking for include file raqm.h in /nix/store/68289cwrk5pjj6nmlb7r76qqpw99s011-zlib-1.3-dev/include
>       Checking for include file raqm.h in /nix/store/xg5p8vpqglfg9mlcvnchr8hhhf04m9ii-lcms2-2.15-dev/include
>       Checking for include file raqm.h in /private/tmp/Pillow/venv/include
>       Checking for include file raqm.h in /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include
>       Checking for include file raqm.h in /usr/local/include
>       Checking for include file raqm.h in /private/tmp/Pillow/venv/include
>       Checking for include file raqm.h in /Users/laggron/.pyenv/versions/3.11.4/include/python3.11

So where is your raqm.h located?

Similarly, it goes looking for webp/encode.h and doesn't find it.

>       Checking for include file webp/encode.h in /nix/store/fbq6rwbqpwpvgs6jm5bzgqi5zf5h92wj-freetype-2.13.2-dev/include
>       Checking for include file webp/encode.h in /nix/store/0sksvw4kvr3j63md09z11b6q9xj776kj-libjpeg-turbo-2.1.5.1-dev/include
>       Checking for include file webp/encode.h in /nix/store/0phdb1r6chn6ifindy9d1436sy7b8wn4-openjpeg-2.5.0-dev/include/openjpeg-2.5
>       Checking for include file webp/encode.h in /nix/store/c8z6bw47x52fja2q85iqgi3gqnnp4854-libtiff-4.6.0-dev/include
>       Checking for include file webp/encode.h in /nix/store/68289cwrk5pjj6nmlb7r76qqpw99s011-zlib-1.3-dev/include
>       Checking for include file webp/encode.h in /nix/store/xg5p8vpqglfg9mlcvnchr8hhhf04m9ii-lcms2-2.15-dev/include
>       Checking for include file webp/encode.h in /private/tmp/Pillow/venv/include
>       Checking for include file webp/encode.h in /Library/Developer/CommandLineTools/SDKs/MacOSX14.4.sdk/usr/include
>       Checking for include file webp/encode.h in /usr/local/include
>       Checking for include file webp/encode.h in /private/tmp/Pillow/venv/include
>       Checking for include file webp/encode.h in /Users/laggron/.pyenv/versions/3.11.4/include/python3.11

So where is your webp/encode.h located?

**Comment by Yay295** [comment]
There are two log files at the gist they linked. The second one has:

      Looking for Raqm
      Checking for include file raqm.h in /nix/store/fbq6rwbqpwpvgs6jm5bzgqi5zf5h92wj-freetype-2.13.2-dev/include
      Checking for include file raqm.h in /nix/store/0sksvw4kvr3j63md09z11b6q9xj776kj-libjpeg-turbo-2.1.5.1-dev/include
      Checking for include file raqm.h in /nix/store/0phdb1r6chn6ifindy9d1436sy7b8wn4-openjpeg-2.5.0-dev/include/openjpeg-2.5
      Checking for include file raqm.h in /nix/store/c8z6bw47x52fja2q85iqgi3gqnnp4854-libtiff-4.6.0-dev/include
      Checking for include file raqm.h in /nix/store/68289cwrk5pjj6nmlb7r76qqpw99s011-zlib-1.3-dev/include
      Checking for include file raqm.h in /nix/store/xg5p8vpqglfg9mlcvnchr8hhhf04m9ii-lcms2-2.15-dev/include
      Checking for include file raqm.h in /nix/store/5vg2xz1wmq9f6kjnrg465y6sikqwxsmf-libraqm-0.10.1/include
      Found raqm.h
      Found library raqm at /nix/store/5vg2xz1wmq9f6kjnrg465y6sikqwxsmf-libraqm-0.10.1/lib/libraqm.dylib

The WEBP files were not found in either log though.

**Comment by radarhere** [comment]
I've created #8142 with your change to resolve this.

**Comment by laggron42** [comment]
Hi, sorry if that was unclear, but basically what is happening with most installations is that `pkg-config` would return a directory for one of the requested libs, and the include directory for `raqm` and `webp` would usually be in the same folder, so it worked for most users. The PR you opened fixes that problem, thanks!
