### ISSUE TITLE
Python can't find pillow 

### ISSUE THREAD

**Issue by q1225** [python-pillow/Pillow#8145]
my command prompt has found pillow but python can't how do i fix it because when i type python3 it says its not in the system

**Comment by aclark4life** [comment]
`from PIL import Image` ?

**Comment by q1225** [comment]
from PIL import Image
Traceback (most recent call last):
  File "<pyshell#0>", line 1, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

**Comment by aclark4life** [comment]
``python -m pip install pillow`` ?

**Comment by q1225** [comment]
same

**Comment by aclark4life** [comment]
Run `python -m pip install pillow` from the command line, not Python.

**Comment by q1225** [comment]
![Coding](https://github.com/python-pillow/Pillow/assets/46804537/e58fe9cc-8275-4bbe-844b-db878579d9b9)

**Comment by aclark4life** [comment]
Cool now make sure that when you run Python, it is the Python 3.10 that is located in `c:\users\administrator\appdata\local\programs\python310`. If so, then `from PIL import Image` should work. Otherwise, you may be running the wrong Python, the one that does not have pillow installed.

**Comment by q1225** [comment]
How would I move it to other versions though?

**Comment by aclark4life** [comment]
``pythonOtherVersion -m pip install pillow``

**Comment by q1225** [comment]
btw it does work on 3.10 i need to get back to coding more

**Comment by radarhere** [comment]
> i need to get back to coding more

Are you saying this is resolved, or do you need further assistance?

**Comment by q1225** [comment]
I'm have issues out side of pillow but this one is fixed
