### ISSUE TITLE
ValueError PIL/ImageDraw.py line 316, in rectangle 

### ISSUE THREAD

**Issue by ianovert** [python-pillow/Pillow#8149]
Hi I’m using python 3.11 to compile my application into an apk on google colab but i keep getting and error on PIL.The Pillow version im using is 10.3.0 On google colab when compiling..The error im facing is described below.

armeabi_v7a/PIL/ImageDraw.py, line 316, in rectangle  ValueError: x1 must be greater than or equal to x0

How do i solve the issue??Thanks in advance.

**Comment by radarhere** [comment]
You are calling the [`rectangle`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.ImageDraw.rectangle) method with either a single list of points - `draw.rectangle([x0, y0, x1, y1])` - or with the top-left point and the bottom-right point - `draw.rectangle([(x0, y0), (x1, y1)])`

The error is trying to tell you that what you are specifying as the 'right' of the rectangle is less than the 'left', meaning that the rectangle doesn't quite make sense. There is something wrong with the numbers you are passing through.

**Comment by ianovert** [comment]
Okay Thanks.
