### ISSUE TITLE
Image.mode give different result in Windows than in Linux

### ISSUE THREAD

**Issue by DhSufi** [python-pillow/Pillow#8172]
### What did you do?
Checked each frame mode (Image.mode) in a GIF. Run the same code in Windows and Linux (Raspbian).

### What did you expect to happen?
Each frame returns the same mode in Windows and in Linux.

### What actually happened?

The outputs are different in Windows and Linux

The code:

```python
from PIL import Image

my_gif = Image.open('pika.gif')

for idx in range(my_gif.n_frames):
    my_gif.seek(idx)
    frame = my_gif.copy()
    print(idx, frame.mode)
```

Windows output:
_0 P
1 RGBA
2 RGBA
3 RGBA_

Linux output:
_0 P
1 P
2 P
3 P_

### What are your OS, Python and Pillow versions?

* OS Windows: Windows 10 Enterprise LTSC 21H2 19044.4529
* Python Windows: 3.11.9
* Pillow Windows: 10.3.0

* OS Linux: Raspbian GNU/Linux 11 (bullseye) Linux 6.1.21+ 
* Python Linux: 3.9.2
* Pillow Linux: 8.1.2

**Comment by nulano** [comment]
This will be because of the following change in Pillow 9.0.0: https://pillow.readthedocs.io/en/stable/releasenotes/9.0.0.html#convert-subsequent-gif-frames-to-rgb-or-rgba

> ### Convert subsequent GIF frames to RGB or RGBA
> Since each frame of a GIF can have up to 256 colors, after the first frame it is possible for there to be too many colors to fit in a P mode image. To allow for this, seeking to any subsequent GIF frame will now convert the image to RGB or RGBA, depending on whether or not the first frame had transparency.

**Comment by radarhere** [comment]
So to be clear, this is not a difference between operating systems, but rather a difference in behaviour between Pillow versions. The old version may render some GIFs incorrectly.

The best solution would be to upgrade Pillow in your Linux environment.

**Comment by DhSufi** [comment]
Thanks you so much for your guidance. I should have realized it before open an issue. Thanks for your time and sorry for the inconvenience. @radarhere @nulano
