### ISSUE TITLE
An issue with font characters

### ISSUE THREAD

**Issue by monkeycc** [python-pillow/Pillow#8179]
There is an issue with the font characters
![微信截图_20240630014922](https://github.com/Belval/TextRecognitionDataGenerator/assets/6490927/da181d2e-984b-47b3-a8ea-4e24951e75b7)

`4-48`

How to filter this type of error
I need to filter out this problematic font, how should I determine

`draw = ImageDraw.Draw(img_pil)  `

**Comment by radarhere** [comment]
Hi. What font are you using? Could you provide some code to generate the image? Could you describe what exactly is wrong with the output image?

I also don't know what you mean when you say you would like to 'filter out' the font?

**Comment by monkeycc** [comment]
[font.zip](https://github.com/user-attachments/files/16043813/font.zip)

This is a font file

I need the string "-"

But there is a problem with this Font Rendering

The output image is not "-"

I need to read the font folder
There are hundreds of font files inside
Used for font OCR image enhancement

We need to filter out these problematic fonts

@radarhere

**Comment by radarhere** [comment]
Looking at your font in https://fontdrop.info/, I see that your unexpected character is the 'undefined' one in the font - in other words, '-' is not in the font you're using.

Here's a previous strategy I've suggestd to determine if a font has a character - https://github.com/python-pillow/Pillow/issues/5993#issuecomment-1023699805
```python
from itertools import chain
from fontTools.ttLib import TTFont
ttf = TTFont("7-digit-regular_1.ttf", 0, allowVID=0, ignoreDecompileErrors=True, fontNumber=-1)
chars = []
for x in ttf["cmap"].tables:
    chars += [y[0] for y in x.cmap.items()]
ttf.close()

letter = "-"
if ord(letter) in chars:
    print(letter, "is in font")
else:
    print(letter, "is missing from font")
```

**Comment by radarhere** [comment]
@monkeycc you liked the previous comment. Does that mean this is resolved?

**Comment by monkeycc** [comment]
Thank you for resolving the issue
