### ISSUE TITLE
Combined frames extracted from a GIF 45 larger than the gif itself

### ISSUE THREAD

**Issue by maj113** [python-pillow/Pillow#8190]
### What did you do?

See code below
Source image from:
`https://upload.wikimedia.org/wikipedia/commons/9/96/.Animation_of_Hayabusa2_orbit.gif`

![Animation_of_Hayabusa2_orbit](https://github.com/python-pillow/Pillow/assets/36992813/eef0aa5d-7913-44ad-9544-c257cc5cac72)

### What did you expect to happen?

processed frames from the gif being smaller or equal in terms of "file size"

### What actually happened?

Combined processed frames being 327169440B vs the file size of GIF being 7262063B **45 times bigger**

### What are your OS, Python and Pillow versions?

* OS:  W11 24H2 26120
* Python: 3.12.3
* Pillow: 10.4.0

```text
py -3.12 -m PIL.report                                                                                                                                            
--------------------------------------------------------------------                            
Pillow 10.4.0
Python 3.12.3 (tags/v3.12.3:f6650f9, Apr  9 2024, 14:05:25) [MSC v.1938 64 bit (AMD64)]
--------------------------------------------------------------------
Python executable is C:\Program Files\Python312\python.exe
System Python files loaded from C:\Program Files\Python312
--------------------------------------------------------------------
Python Pillow modules loaded from C:\Users\Maj\AppData\Roaming\Python\Python312\site-packages\PIL
Binary Pillow modules loaded from C:\Users\Maj\AppData\Roaming\Python\Python312\site-packages\PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.4.0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.4.0
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.3
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
*** XCB (X protocol) support not installed
-------------------------------------------------------------------
```

```python

# Image is obtained with aiohttp  
# aiohttp.ClientSession.get(image_url)
# data = await response.content.read()
gif = Image.open(io.BytesIO(data))
frames_size = 0
def process_frame(self, frame, bg):
    image = bg.copy()
    image.paste(frame, (0, 0), 0)
    image.thumbnail((512, 512))
    frames_size += sys.getsizeof(image.tobytes())
    return ImageTk.PhotoImage(image)

def load_gif_frames(self):
    bg = Image.new('RGBA', gif.size, (0, 0, 0, 0))
    frames = [process_frame(frame, bg) for frame in ImageSequence.Iterator(gif)]
    print(frames_size) # 327169440
    ...
```

**Comment by Yay295** [comment]
That GIF has 416 frames. Each frame is 512x512 pixels. Each pixel has three bands/channels (RGB). 416*512*512*3 = 327,155,712 bytes, which is a bit less than the 327,169,440 bytes you counted, but that's probably due to the overhead of each Python object.

**Comment by radarhere** [comment]
> processed frames from the gif being smaller or equal in terms of "file size"

In general, this does not have to be true for GIF images.

I think you are imagining that a GIF file has the first complete image stored, and then the second complete image stored, and so on. This is not always the case.

For many GIF images, the second frame is not the complete image. It is recorded as the difference between the second frame and the first frame, as this saves space. However, when Pillow loads the image, it computes the result, the image that the user is intended to see. If you had loaded the second image, and it was not the complete image, you would have been surprised, yes? This resulting image however, contains more data that the original 'difference' image.

Also, GIF images might use LZW compression, whereas the images in Pillow's memory are uncompressed.

> The frames are used in tkinter and are being played/animated so they can't be discarded

Rather than loading all of the images, and then providing them to tkinter, why not seek each individual frame, and provide them to tkinter one at a time?

```python
from PIL import Image, ImageTk
import tkinter

class Demo:
    def __init__(self):
        self.root = tkinter.Tk()
        
        self.gif = Image.open("in.gif")
        self.label = tkinter.Label(self.root)
        self.label.pack()
        
        self.root.after(0, self.update, 0)
        self.root.mainloop()

    def update(self, index):
        if index == self.gif.n_frames:
            index = 0
        self.gif.seek(index)
        image = self.gif.copy()
        image.thumbnail((512, 512))
        self.image = ImageTk.PhotoImage(image)
        self.label.configure(image=self.image)
        self.root.after(50, self.update, index + 1)

Demo()
```

**Comment by maj113** [comment]
> why not seek each individual frame, and provide them to tkinter one at a time?

I haven't tried this however I'm pretty sure it would really badly affect performance especially with more than one gif playing on screen

I don't think doing .thumbnail() would be able to keep up with the gif frame duration

and since tkinter doesn't have a proper way to actually natively animate a gif (afaik) I'm stuck with this workaround I presume


Also thanks for reminding me that gifs != images, I shouldn't have expected 1:1 or less size but it still surprised me how huge it became, in theory it could have playing +100 gifs but the ram usage is too much with these bigger gifs

**Comment by radarhere** [comment]
It sounds like you just need to experiment now to see how performance fares with your particular scenario.

Is there anything further we can do for you?

**Comment by maj113** [comment]
No, thanks for helping me with this
