### ISSUE TITLE
Cannot import ImageCms with no LITTLECMS2 feature installed

### ISSUE THREAD

**Issue by mrbean-bremen** [python-pillow/Pillow#8193]
If building pillow without the LITTLECMS2 feature (e.g. with the lcms library not present), it was still possible to import `ImageCms` until pillow 10.2. This is done by using `DeferredError`:
```py
try:
    from . import _imagingcms as core
except ImportError as ex:
    # Allow error import for doc purposes, but error out when accessing
    # anything in core.
    from ._util import DeferredError

    core = DeferredError.new(ex)
```

With the type hints added in 10.3, there is now a top level access to `_imagingcms` alias `core`:
```py
 _CmsProfileCompatible = Union[
    str, SupportsRead[bytes], core.CmsProfile, ImageCmsProfile
]
```
Using 
```py
from PIL import ImageCms
```
causes now (in 10.3/10.4):
```
Traceback (most recent call last):
ImageCms.py(370) , in <module>
ImageCms.py(370)    str, SupportsRead[bytes], core.CmsProfile, ImageCmsProfile
ImageCms.py(370)                              ^^^^^^^^^^^^^^^
_util.py(23) , in __getattr__
_util.py(23)    raise self.ex
ImageCms.py(33) , in <module>
ImageCms.py(33)    from . import _imagingcms as core
ImportError: cannot import name '_imagingcms' from 'PIL' (C:\git\...\site-packages\PIL\__init__.py)
```
Happens both under Windows (as shown) and Linux.

This is probably a fringe problem, but can easily be fixed by using the string version of the problematic type hint:
```py
 _CmsProfileCompatible = Union[
    str, SupportsRead[bytes], "core.CmsProfile", ImageCmsProfile
]
```
_Environment:_
* OS: Windows 10, Ubuntu 22.04
* Python: 3.11
* Pillow: 103, 10.4

_Features:_
```text
--------------------------------------------------------------------
Pillow 10.3.0
Python 3.11.9 (main, Jun 28 2024, 12:22:23) [MSC v.1939 64 bit (AMD64)]
--------------------------------------------------------------------
Python executable is C:\git\...bin\Python.exe
Environment Python files loaded from C:\git\...\bin
System Python files loaded from 
--------------------------------------------------------------------
Python Pillow modules loaded from C:\git\...\Lib\site-packages\PIL
Binary Pillow modules loaded from C:\git\...\Lib\site-packages\PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
*** TKINTER support not installed
*** FREETYPE2 support not installed
*** LITTLECMS2 support not installed
*** WEBP support not installed
*** WEBP Transparency support not installed
*** WEBPMUX support not installed
*** WEBP Animation support not installed
--- JPEG support ok, compiled for libjpeg-turbo 3.0.3
*** OPENJPEG (JPEG2000) support not installed
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
*** XCB (X protocol) support not installed
--------------------------------------------------------------------
```

**Comment by nulano** [comment]
Yes, you are right this was unintentional. I've created #8196 to fix it.

**Comment by cleebp** [comment]
Ran into this today it still appears to be an issue when building on windows without lcms2 present.

**Comment by aclark4life** [comment]
Looks like we're waiting on resolution to a [Docs build](https://github.com/python-pillow/Pillow/pull/8196#issuecomment-2204211887) [issue](https://github.com/python-pillow/Pillow/pull/8197#pullrequestreview-2158010309) in order to merge the [fix](https://github.com/python-pillow/Pillow/pull/8196)([s](https://github.com/python-pillow/Pillow/pull/8197)).

**Comment by radarhere** [comment]
> **edit:** made a patch for my build to pass without adding the `lcms2` depenency, [here's the gist](https://gist.github.com/cleebp/ad3b6fe9cbe92b9cbe1aa2fbb103d5fa)

This is the same as proposed fix #8196

**Comment by mrbean-bremen** [comment]
Both #8196 and #8197 fix the problem, it's just a matter of somebody (I guess @radarhere or @hugovk) to decide which one to use.

**Comment by radarhere** [comment]
> Looks like we're waiting on resolution to a [Docs build](https://github.com/python-pillow/Pillow/pull/8196#issuecomment-2204211887) [issue](https://github.com/python-pillow/Pillow/pull/8197#pullrequestreview-2158010309) in order to merge the [fix](https://github.com/python-pillow/Pillow/pull/8196)([s](https://github.com/python-pillow/Pillow/pull/8197)).

I'm not entirely sure about the priority level of building docs without dependencies (Pillow is a library first and foremost, has public online documentation, and has distributed documentation as a bonus feature), but I've found that just using `nitpick_ignore` can workaround the matter - https://github.com/python-pillow/Pillow/pull/8197/commits/e938283eb9ff28fbd18432eae3aa5b0ec79967d3

**Comment by mrbean-bremen** [comment]
@radarhere - thanks for the fix! From my perspective (which admittedly may not be that relevant here) your fix is the cleaner approach, and I see no reason not to merge it.

**Comment by radarhere** [comment]
The opinion of Pillow users should always be relevant. Thanks for your review - just waiting for approval from another member of the core team.
