### ISSUE TITLE
Python 3.13 free-threading compatibility

### ISSUE THREAD

**Issue by lysnikolaou** [python-pillow/Pillow#8199]
Hey all! 👋 

This aims to be a tracking issue for all work necessary to support the free-threaded build of Python 3.13. A very high-level list of steps is (more details to follow as I investigate more issues):

- [x] Set up CI for free-threading
  - [x] https://github.com/python-pillow/Pillow/pull/8200
- [x] Move away from APIs that use borrowed references under the free-threaded build
  - [x] https://github.com/python-pillow/Pillow/pull/8216
- [x] Audit C extension module for thread-safety issues
  - [x] #8238
- [x] Mark C extension modules as thread-safe with the `Py_mod_gil` slot (or `PyUnstable_Module_SetGIL`)
  - [x] https://github.com/python-pillow/Pillow/pull/8216 
- [x] Upload wheels for the free-threaded build. Other projects have started uploading nightlies for the free-threaded on the [scientific-python-nightly-wheels index](https://anaconda.org/scientific-python-nightly-wheels) so that we can enable faster iteration, we can discuss whether we wanna do this for `Pillow` as well.
  - [X] https://github.com/python-pillow/Pillow/pull/8219
  - [x] https://github.com/scientific-python/upload-nightly-action/issues/84 
  - [x] #8236  
  - [x] https://github.com/python-pillow/Pillow/pull/8243
  - [x] https://github.com/python-pillow/Pillow/pull/8244

**Comment by hugovk** [comment]
Please see PR https://github.com/python-pillow/Pillow/pull/8200 to set up CI for free-threading.

**Comment by hugovk** [comment]
I'm working on this today with @lysnikolaou at the EuroPython sprints. 

It would help the ecosystem if we also upload nightly wheels so others can test the current code without needing to wait for quarterly releases.

@lysnikolaou has requested access at https://github.com/scientific-python/upload-nightly-action/issues/84 for the Scientific Python Nightly Wheels index, where other projects like SciPy are uploading.

See also https://labs.quansight.org/blog/free-threaded-python-rollout and https://py-free-threading.github.io/.

**Comment by radarhere** [comment]
If anyone would like wheels generated after #8216, here you go - [Linux.zip](https://github.com/user-attachments/files/16216912/Linux.zip), [macOS.zip](https://github.com/user-attachments/files/16216941/macOS.zip), [Windows.zip](https://github.com/user-attachments/files/16216960/Windows.zip)

**Comment by rgommers** [comment]
https://anaconda.org/scientific-python-nightly-wheels/pillow rather than `pandas`. And, yay thank you both! 🎉

**Comment by radarhere** [comment]
Every task in this issue has been completed - is this just open now as a tracking issue until Python 3.13 is finalized?

**Comment by lysnikolaou** [comment]
> is this just open now as a tracking issue until Python 3.13 is finalized?

Yes, I'd leave it open until at least the final release of 3.13 and see how it goes from there.

**Comment by radarhere** [comment]
Python 3.13 has now been released - https://www.python.org/downloads/release/python-3130/

**Comment by radarhere** [comment]
Pillow 11.0.0 has now been released, with 3.13t wheels.
