### ISSUE TITLE
Save 16-bit PGM Image?

### ISSUE THREAD

**Issue by SvarunSoda** [python-pillow/Pillow#8226]
I am attempting to convert an image in PNG format to a 16-bit PGM format and save it using Python's [PIL](https://python-pillow.org/) library. I'm using Python 3.12.4 in all examples shown.

---

Using the following `test.png` image:

![test](https://github.com/python-pillow/Pillow/assets/95188575/96526c49-5b98-4c49-a7c3-f32135da8405)

Attempting a simple script like this with the [Image.save()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.save) function:

```python
from PIL import Image

image = Image.open("test.png")
image.save("test.pgm")
```

Can save resave the image as PGM, however it's always saved as an 8-bit image, as shown by GIMP:

![gimp](https://github.com/python-pillow/Pillow/assets/95188575/6b09a48b-3dfc-4598-8a52-5f876081d892)

---

Attempting to specify the amount of pixel bits via the optional `bits` argument as such:

```python
from PIL import Image

image = Image.open("test.png")
image.save("test.pgm", bits = 16)
```

Also results in an 8-bit PGM image being saved.

---

Attempting to manually create a numpy array of the `np.uint16` type & then creating an image from it using the [Image.fromarray()](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.fromarray) function as such:

```python
from PIL import Image
import numpy as np

image = Image.open("test.png")
imageData = np.array(image.getdata(), dtype = np.uint16)
newImage = Image.fromarray(imageData)
newImage.save("test.pgm", bits = 16)

```

Results in:

```
OSError: cannot write mode I;16 as PPM
```

I also noticed that this appears to break the image, as saving with `np.uint32` saves a blank image with a very narrow horizontal size and a very large vertical size.

---

What is the proper way to save 16-bit PGM images using the Python `PIL` library?

Thanks for reading my post, any guidance is appreciated.

**Comment by radarhere** [comment]
Hi. The image that you have provided is an RGBA image. It has 8-bits per channel, so I think it makes perfect sense for it to be saved in 8-bit mode by default.

Converting it to I mode
```python
from PIL import Image

image = Image.open("test.png")
image.convert("I").save("test.pgm")
```
will save a 16-bit image.

> via the optional `bits` argument as such:

Looking at the source code, that isn't a Pillow feature. What led you to believe that it was?

As for your NumPy code, I would suggest
```python
from PIL import Image
import numpy as np

image = Image.open("test.png")
imageData = np.array(image.getdata(), dtype = np.uint16)
newImage = Image.fromarray(imageData)
newImage.convert("I").save("test.pgm")
```

> OSError: cannot write mode I;16 as PPM

Let us know if you would like I;16 saving to be supported.

**Comment by radarhere** [comment]
@SvarunSoda was that answer helpful?
