### ISSUE TITLE
`ImageFont` claims to load font sizes in pixels but seems to use points?

### ISSUE THREAD

**Issue by xmo-odoo** [python-pillow/Pillow#8258]
Per [the documentation](https://pillow.readthedocs.io/en/stable/reference/ImageFont.html#PIL.ImageFont.truetype)

> size – The requested size, in pixels.

`load_default` does not clarify but I assume it's similar.

Now I will readily confess I'm not well versed in fonts, but my understanding was that the font-size, or em-size, is the size from the *ascent* to the *descent*. That is, the sum of the values `FreeTypeFont.getmetrics` returns. However when I test this:
```pycon
>>> ImageFont.load_default(16).getmetrics()
(16, 4)
>>> f = ImageFont.truetype("Ubuntu-R.ttf", size=16)
>>> f.getmetrics()
(15, 4)
```
This does however align with the font-size being in points, and a point being 4/3 pixels (aka fixed resolutions of 72 dpi and 96 ppi which are correct for just about nothing but are common fixed values notably matching CSS's): 16(4/3) is 21.333..., which doesn't quite match the font sizes of 20 and 19 pixels we get from the metrics but seems reasonably close and could be chalked up to the font itself: just by sampling a bit I get metrics down to (13, 4) (Lato) and up to (18, 5) (Noto, Open).

Not really anything which truly reconciles with `size` being a pixel size though, Lato is the closest and it's a pixel above still.

**Comment by nulano** [comment]
This seems to be the opposite of #6079.

Has something changed since, or is one of these questions incorrect?

**Comment by radarhere** [comment]
[Comparing with Gimp](https://github.com/python-pillow/Pillow/issues/6079#issuecomment-1047303514), I would still conclude that we're using pixels and not points.
