### ISSUE TITLE
Cannot install Tkdesigner

### ISSUE THREAD

**Issue by yoboy1102** [python-pillow/Pillow#8276]
### What are your OS, Python and Pillow versions?

* OS: 
* Python: 
* Pillow: 

```text
Please paste here the output of running:

python3 -m PIL.report
or
python3 -m PIL --report

Or the output of the following Python code:

from PIL import report
# or
from PIL import features
features.pilinfo(supported_formats=False)
```

```python
code goes here
```

**Comment by radarhere** [comment]
So you're talking about https://pypi.org/project/tkdesigner/, which [requires Pillow](https://github.com/ParthJadhav/Tkinter-Designer/blob/master/requirements.txt).

Could you provide more information? What is the error you are seeing? Could you fill out the OS, Python and Pillow versions in our issue template?

**Comment by hugovk** [comment]
Duplicate of https://github.com/python-pillow/Pillow/issues/8277
