### ISSUE TITLE
Add SVG Support Using PlutoSVG

### ISSUE THREAD

**Issue by sammycage** [python-pillow/Pillow#8292]
### What did you do?

I am suggesting adding SVG support to Pillow using plutosvg.

### What did you expect to happen?

Enhance Pillow's capabilities to support SVG rendering.

### What actually happened?

Pillow currently lacks built-in support for rendering SVG images.

**Comment by sammycage** [comment]
PlutoSVG is an SVG rendering library in C. It can also be integrated with FreeType to render SVG emojis, enhancing Pillow's support for modern font formats.

I am ready to send a pull request if you are interested in integrating PlutoSVG with Pillow. This integration would add valuable functionality for users who need SVG support in their image processing workflows.

Looking forward to your response.

https://github.com/sammycage/plutosvg

**Comment by sammycage** [comment]
#1146 #3509 #6170

**Comment by radarhere** [comment]
Would it not make more sense to just make this suggestion in #3509?
