### ISSUE TITLE
ImportError: cannot import name 'PILLOW_VERSION' from 'PIL' (python3.7, PILLOW vers < 9.0)

### ISSUE THREAD

**Issue by nhsamng** [python-pillow/Pillow#8311]
Try this in the script that tries to `import PILLOW_VERSION`

`from PIL import __version__ as PILLOW_VERSION`

not guaranteed to work with all cases though, you need to dig up a bit

This is so much headache

_Originally posted by @nguyenvulong in https://github.com/python-pillow/Pillow/issues/4130#issuecomment-1201516416_

**Comment by nhsamng** [comment]
I tried to display the ` torchvision.__version__()`, but met `NameError: name 'torchvision' is not defined` with Traceback: `ImportError: cannot import name 'PILLOW_VERSION' from 'PIL'`

I fixed and happy run, by:

- changing `from PIL import Image, ImageOps, ImageEnhance, PILLOW_VERSION` to `from PIL import Image, ImageOps, ImageEnhance, __version__` as 
`
# VERSION was removed in Pillow 6.0.0.
# PILLOW_VERSION was removed in Pillow 9.0.0.
# Use __version__ instead. 
`
And remember to change anywhere has `PILLOW_VERSION` to `__version__` in your traceback files

**Comment by radarhere** [comment]
If you're using torchvision 0.5 or later, this shouldn't be a problem that needs fixing.

If you are using a more recent version than that and still having a problem, please let us know.

**Comment by radarhere** [comment]
@nhsamng are you interested in trying to fix the problem on your machine, or did you simply wish to post that information for others who may be interested?

**Comment by nhsamng** [comment]
> If you're using torchvision 0.5 or later, this shouldn't be a problem that needs fixing.
> 
> If you are using a recent version and still having a problem, please let us know.

Hi **[radarhere](https://github.com/radarhere)**, thanks for your information.
I have checked, my torch vision is under 0.5, it's 0.4.2 specifically. no problem with the issue right now, but i think because i made change as i described above

**Comment by nhsamng** [comment]
> @nhsamng are you interested in trying to fix the problem on your machine, or did you simply wish to post that information for others who may be interested?

want to share my way of resolve the error, and want to discuss more about the reason of errors as it might depend on personal machine and personal set up env. Have u met the error?

**Comment by radarhere** [comment]
I'm not a torchvision user myself, so I've not experienced this error (outside of investigating #4130).

I think the simplest solution for someone on torchvision 0.4.2 is just to upgrade their torchvision - which seems like a good idea anyway, as torchvision 0.4.2 is rather old compared to the latest torchvision 0.19.

**Comment by radarhere** [comment]
As a general note, Python 3.7 is [EOL](https://devguide.python.org/versions/), and [no longer supported by the latest version of Pillow.](https://pillow.readthedocs.io/en/stable/installation/python-support.html)

**Comment by nhsamng** [comment]
🤞gonna use later version of python. Tks
