### ISSUE TITLE
Scale factor for resizing

### ISSUE THREAD

**Issue by enomis-dev** [python-pillow/Pillow#8312]
Hi!
Often working with images it is common to specify the scale factor to downsample/upsample the images preserving the aspect ratio.
I was wondering if it could be possible to include a scale factor as input param of the _resize_ method.

Today I achieve this by doing the following:

```python
from PIL import Image

image = Image.open('example.jpg')
scale_factor = 0.5  # For example, reduce the size by half
# Calculate the new size
new_size = (
    int(image.width * scale_factor),
    int(image.height * scale_factor)
)
resampled_image = image.resize(new_size)
```

Perhaps, it could be interesting to have this directly  inside the resize method.
I leave a simple PR in case you like the addition.
Wdyt?

**Comment by Yay295** [comment]
Does [`Image.reduce`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.reduce) work?

**Comment by radarhere** [comment]
So the `Image.reduce` code to scale an image down by half would be
```python
from PIL import Image
with Image.open("/Tests/images/hopper.png") as im:
    reduced_image = im.reduce(2)
```

**Comment by enomis-dev** [comment]
Nice, thank you for answer, reduce does exactly that!
I'll close the isssue.
