### ISSUE TITLE
Impossible to detect multi-images tiff pages

### ISSUE THREAD

**Issue by eroux** [python-pillow/Pillow#8323]
### What did you do?

I have this tiff that has one page, but two images in the page (which is weird but apparently common in Photoshop exports):

[11b.zip](https://github.com/user-attachments/files/16695433/11b.zip)

You can see that it has two images with Imagemagick:

```
$ identify 11b.tif 
11b.tif[0] TIFF 3926x852 3926x852+0+0 8-bit sRGB 18.6303MiB 0.030u 0:00.029
11b.tif[1] TIFF 3890x851 3890x851+36+1 8-bit sRGB 18.6303MiB 0.000u 0:00.000
identify-im6.q16: Incompatible type for "RichTIFFIPTC"; tag ignored. `TIFFFetchNormalTag' @ warning/tiff.c/TIFFWarnings/949.
```

I want to:
- know how many images are in the tiff
- export each image to a different file

I'm using this code to detect the number of images:

```python
from PIL import Image, ImageSequence

with Image.open("/tmp/11b.tif") as img:
	nbf = img.n_frames
	print(f"{nbf} frame(s) found")
	i=0
	for tif_image in ImageSequence.Iterator(img):
		tif_image.save(f"/tmp/11b-{i}.jpg")
		i += 1
	print(f"{i} image(s) found through ImageSequence.iterator")
```

but it can't detect that there are more than one image:

```sh
$ python3 testpillow.py 
1 frame(s) found
1 image(s) found through ImageSequence.iterator
```

### What did you expect to happen?

I expected at least one of the reported values to be 2

### What actually happened?

the reported values are 1

### What are your OS, Python and Pillow versions?

* OS: Debian 12
* Python: 3.11
* Pillow: 10.3.0

```text
--------------------------------------------------------------------
Pillow 10.3.0
Python 3.11.2 (main, May  2 2024, 11:59:08) [GCC 12.2.0]
--------------------------------------------------------------------
Python executable is /home/admin/pvenv/bin/python3
Environment Python files loaded from /home/admin/pvenv
System Python files loaded from /usr
--------------------------------------------------------------------
Python Pillow modules loaded from /home/admin/pvenv/lib/python3.11/site-packages/PIL
Binary Pillow modules loaded from /home/admin/pvenv/lib/python3.11/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 10.3.0
*** TKINTER support not installed
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.3.2
--- WEBP Transparency support ok
--- WEBPMUX support ok
--- WEBP Animation support ok
--- JPEG support ok, compiled for libjpeg-turbo 3.0.2
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.2.13
--- LIBTIFF support ok, loaded 4.6.0
--- RAQM (Bidirectional Text) support ok, loaded 0.10.1, fribidi 1.0.8, harfbuzz 8.4.0
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------
```

**Comment by radarhere** [comment]
Using [psdtags](https://pypi.org/project/psdtags/),
```python
import psdtags
from PIL import Image
Image.open('11b.tif').save("one.png")
layers = psdtags.TiffImageSourceData.fromtiff('11b.tif').layers
layer = layers[0].asarray()
Image.fromarray(layer).save("two.png")
```
I was able to generate these two images.
![one](https://github.com/user-attachments/assets/fdc115c8-df92-42ca-8159-448eb7021b47)
![second](https://github.com/user-attachments/assets/d017091d-f8d5-42e1-8d29-ca001ab7d6e3)

Is that the output you are aiming for?

**Comment by eroux** [comment]
well, not really... I'm not sure what psdtags is supposed to do but it only finds only layer while this tiff file has two. For instance:

```python
import psdtags
print(len(psdtags.TiffImageSourceData.fromtiff('11b.tif').layers))
```

prints `1`, not `2`. My use case is really to detect how many layers a tiff has, and then access the layers, image by image, in PIL directly.

**Comment by radarhere** [comment]
Is ImageMagick your source of truth for determining how many layers the TIFF has? Or are you seeing multiple images in other software as well?

I ask because I've tried opening your image in GIMP, and it just shows the one. I'm not convinced that both images are equal, and that it's not the case that one is the combined image and the other is a mask. Are you saying that even if there was a Pillow-only way to generate those two images, you're explicitly requesting an API that says that there are two images within this file?

**Comment by eroux** [comment]
ImageMagick is my source of truth yes. Other softwares I have only show one page. See https://www.bitsgalore.org/2024/03/11/multi-image-tiffs-subfiles-and-image-file-directories . My interpretation is that this is encoded using a "SubIFD chain", which the [libtiff doc](https://libtiff.gitlab.io/libtiff/multi_page.html)) claims is "rarely supported". Is your interpretation that this is in fact just one image + some PhotoShop tags that confuses ImageMagick into thinking there are multiple images?

**Comment by radarhere** [comment]
The output of `identify -verbose 11b.tif` shows for both images an identical filesize.
```
Filesize: 18.6303MiB
```
Within a 19.5mb file, that would lead you to believe that they're not two images stored separately.

`identify -verbose 11b.tif` also shows for the second image
```
Background color: white
    label: Layer 0
    ...
    psd:layer.x: 36
    psd:layer.y: 1
```
It doesn't show any 'label: ' for the first image.

I think this is one layer, with transparency and a positive offset. The layer itself is the 'second' image. The 'first' image is that layer with the offset applied to make it 'bigger', and with the white background colour applied.

**Comment by eroux** [comment]
Thanks for your analysis! I can't really fathom why anyone would produce tiffs in that format but that's not really relevant to the topic at hand. I'l consider it an oddity in ImageMagick then
