### ISSUE TITLE
ResourceWarning: unclosed file when calling save / thumbnail on an ImageFile instance (for Python 3)

### ISSUE THREAD

**Issue by kanoc** [python-pillow/Pillow#835]
This is a similar issue to #477, but the context is a bit different. Executing this code with `python -Wall` will generate a `ResourceWarning` (can be reproduced with an arbitrary image):

``` python
from PIL import Image

with Image.open('test_img.png') as img:
    img.save('test_img.jpg', format='JPEG', quality=80)
```

This code will not produce a warning:

``` python
from PIL import Image

with open('test_img.png', 'rb') as image_file:
    with Image.open(image_file) as img:
        img.save('test_img.jpg', format='JPEG', quality=80)
```

I've spent a few hours debugging this, and I think I've nailed it down. Apologies if I've misunderstood something.

The warning is caused by the line `PIL/Image.py:762`, when the file object was opened by `Image.open`:

``` python
return self.im.pixel_access(self.readonly)
```

Looking at he C bindings in `_imaging.c:2799` I can see that because the return value of the call above is discarded, the line `_imaging.c:2824` gets executed

``` c
PyObject_Del(self);
```

which will destroy the file object without closing it, thus generating a `ResourceWarning: unclosed file...` error.

To verify this, I've added a line to close the file before returning from the `load` method:

``` python
self.fp.close()
return self.im.pixel_access(self.readonly)
```

With this, no `ResourceWarning` was generated.

Tested with Pillow v2.5.1 and Python 3.3.2.

**Comment by hugovk** [comment]
I've added failing tests for these in this branch:

https://github.com/hugovk/Pillow/tree/ResourceWarning
https://travis-ci.org/hugovk/Pillow/builds/45600222

The [image save](https://github.com/python-pillow/Pillow/issues/835#issue-39288006) fails for Python 3.4 and the [NumPy array](https://github.com/python-pillow/Pillow/issues/835#issuecomment-53990504) fails for 3.2, 3.3 and 3.4.

**Comment by aclark4life** [comment]
@kanoc Is it similar enough that we can close either this one or #477 to combine issues?

**Comment by hugovk** [comment]
(I merged latest master into my branch with tests, as expected they still fail in the same way: 
https://github.com/hugovk/Pillow/tree/ResourceWarning
https://travis-ci.org/hugovk/Pillow/builds/55929699 )

**Comment by kanoc** [comment]
@aclark4life The issue reported in #477 was fixed and #477 was closed. I think the reference to #477 from https://github.com/pklaus/PhotoBrowser/commit/8248b78af72bf7e1a529649ba8c3ef520324c416 is wrong, the ResourceWarning there is caused by this issue.

As the cause of the ResourceWarning reported here is different than the one reported in #477 and #477 is closed, I don't see why these issues should be combined.

**Comment by aclark4life** [comment]
@kanoc Got it, thanks

**Comment by hugovk** [comment]
> I've added failing tests for these in this branch:
> 
> https://github.com/hugovk/Pillow/tree/ResourceWarning
> https://travis-ci.org/hugovk/Pillow/builds/45600222
>
> The image save fails for Python 3.4 and the NumPy array fails for 3.2, 3.3 and 3.4.

These tests, rebased onto latest master, now pass. See PR https://github.com/python-pillow/Pillow/pull/2756.
