### ISSUE TITLE
Render emojis with zwj

### ISSUE THREAD

**Issue by wlt233** [python-pillow/Pillow#8380]
### What did you do?

```python
from PIL import Image, ImageDraw, ImageFont

text = "👩‍🚒"

font = ImageFont.truetype("seguiemj.ttf", 100)
base = Image.new("RGB", (500, 300), "#FFF")
draw = ImageDraw.Draw(base)
draw.text((50, 50), text, font=font, embedded_color=True, fill="#000")
base.show()
```

> E.g. 👩‍🚒 is encoded as:
> 
> - 👩 U+1F469
> - U+200D (the ZWJ)
> - 🚒 U+1F692

### What did you expect to happen?

show a single emoji like in browser
![image](https://github.com/user-attachments/assets/8b8baeab-f39a-4252-a91c-5a2bd2af6d79)
 
### What actually happened?

the emoji was split into three parts and rendered respectively
![image](https://github.com/user-attachments/assets/6c0c71cc-4f2f-4e42-b251-878c77129075)

### What are your OS, Python and Pillow versions?

* OS: Windows 10 Pro 22H2 19045
* Python: Python 3.9.6
* Pillow: 11.0.0.dev0 from #6926

**Comment by nulano** [comment]
Works for me:
![image](https://github.com/user-attachments/assets/6bd51937-189e-457f-977e-42acc5bcd2c5)

I suspect you are missing RAQM support. Please provide the output of the `python3 -m PIL.report` command or the `import PIL.report` Python statement to confirm.

**Comment by wlt233** [comment]
you are right, thanks a lot
