### ISSUE TITLE
TypeError: argument 1 must be int, not HWND

### ISSUE THREAD

**Issue by Kawasaki5963** [python-pillow/Pillow#8383]
### What did you do?

```python
from PIL import ImageWin
dib = ImageWin.Dib("RGB", (1, 1))
hwnd = ImageWin.HWND(0)
dib.expose(hwnd)
```

### What did you expect to happen?

It works without errors.

### What actually happened?

TypeError: argument 1 must be int, not HWND

### What are your OS, Python and Pillow versions?

* OS: Windows10
* Python: 3.11.4 
* Pillow: 10.4.0

Thank you.

**Comment by radarhere** [comment]
I've created #8385 to resolve this.
