### ISSUE TITLE
Animated gif skips frames

### ISSUE THREAD

**Issue by muitdebos** [python-pillow/Pillow#8397]
Hi, there have been several threads related to saving an animated gif where frames get skipped under certain circumstances. From what I can tell, the most recent thread was the following: https://github.com/python-pillow/Pillow/issues/7613

As that thread is closed and my use-case is different, I open this new one.

### What did you do?
I have a bunch of .pngs as render output from Blender. I want to merge these into an animated .gif using a specific palette. This all works fine, except that there are sometimes multiple transparent frames after one-another. I need these to be actual separate frames, so the total frame count remains equal to the amount of input images. This is important as the .gif is used as input for another quite old program which requires separate and an equal amount of frames.

### What did you expect to happen?
In this case, 240 png's in, convert to animated .gif, end result has only exactly 240 frames. By setting `optimize=False` I would expect no optimisation to happen, including no skipping of frames.

### What actually happened?
240 png's in, conversion is successful, but only contains 200 frames. Consecutive same frames get skipped / merged, despite `optimize=False`

### What are your OS, Python and Pillow versions?

* OS:  Mac Sonoma 14.5, M1
* Python: 3.9.6
* Pillow: 10.4.0

To clarify, the below code works and most settings are more or less required to get the output I want, minus the fact that it's using less frames than required.

```python
processed_images[0].save('output.gif',
    append_images = processed_images[1:],
    background = 0,
    transparency = 255,
    disposal = 2,
    save_all = True, 
    optimize = False,
    palette = some_palette,
    loop = 0,
    duration = 0)
```

**Comment by radarhere** [comment]
Hi. Combining duplicate frames is intended as a feature - there is no visual difference, and the final file size is smaller.

#7613 was resolved once I explained the situation. If you know of more issues that find this functionality inconvenient, please let us know.

The scenario where you explicitly need duplicate frames is unusual. Would you mind sharing what the old program is that requires this?

**Comment by muitdebos** [comment]
Thanks for the quick reply. Indeed, it is a fairly specific scenario. I make animations in Blender for a mod for the game Diablo 2, the old version, which uses pre-rendered sprites. It's an isometric game with rotating characters, so the animations need to have the exact same framecount in all directions for each animation. In addition, this game uses a 256-color palette. This also applies to missiles or other special effects which might have varying levels of transparency that get quantised to the same 256-color palette, using blackness as transparency with a screen blendmode. Some of those frames end up becoming completely black because of this quantisation, thus causing the discrepancy in frame count when they get deduplicated.

To be complete; there is an in-between step, where there is a program called Cv5 that is able to convert a .gif (as long as it meets the requirements) to the proprietary format the game uses, but since that was made specifically for this purpose (not by me I might add), it also expects the same amount of frames.

I completely understand in 99% of usecases it's highly desirable to combine duplicate frames. If it's not feasible to do something on this at a library level maybe I'll have to look into making a fork. Anyway, that's my situation.

**Comment by radarhere** [comment]
Oh, I don't think you need to go as far as making a fork.

Try inserting this before your Pillow code to patch GifImagePlugin.
```python
from PIL import GifImagePlugin

def _getbbox(base_im, im_frame):
    return None, (0, 0) + im_frame.size
GifImagePlugin._getbbox = _getbbox
```

**Comment by muitdebos** [comment]
Oh. Well. That seems to work! 😅 That's a lot easier for sure. Wasn't aware it was this easy to patch some functionality from a library. Thanks a lot for your quick replies!
