### ISSUE TITLE
Possible integer overflow in ImagingSgiRleDecode (SgiRleDecode.c)

### ISSUE THREAD

**Issue by karasovsky** [python-pillow/Pillow#8401]
Hello!

There is size check in code, that c->tablen = im->bands * im->ysize > INT_MAX. 
But 8 * c->tablen can lead to integer overflow. I suggest to adjust the size check.

![image](https://github.com/user-attachments/assets/ff3df0ec-139e-4d36-8002-598fac3b653b)

Found by Linux Verification Center (linuxtesting.org) with SVACE.
Reporter: Dmitriy Karasovsky (d.karasovsky@fobos-nt.ru).

**Comment by radarhere** [comment]
I've created #8402 to resolve this.
