### ISSUE TITLE
Unused code in FliDecode.c and _imaging.c has SAST security issue

### ISSUE THREAD

**Issue by karasovsky** [python-pillow/Pillow#8405]
Hello!

According to the comments in _imaging.c thers is number of codecs, that must be replaced in PIL 1.2. But PIL development was discontinued 15 years ago.

![image](https://github.com/user-attachments/assets/2408b9f2-1603-4cc5-beb7-494b9b0119f2)

One of this codecs has SAST security issue.

![image](https://github.com/user-attachments/assets/ec52aefc-6ecd-4268-8524-b47aeaa5b22f)

`state->xsize` potentially be equal to zero, which will lead to division by zero exception in `ImagingFliDecode`. If this code is not used, I suggest remove it.

Found by Linux Verification Center (linuxtesting.org) with SVACE.
Reporter: Dmitriy Karasovsky ([d.karasovsky@fobos-nt.ru](mailto:d.karasovsky@fobos-nt.ru)).

**Comment by radarhere** [comment]
While this can be thought of as a problem by looking at the C code in isolation,
in the context of our library as a whole, images that say one of their dimensions is zero will be stopped at https://github.com/python-pillow/Pillow/blob/731bcda904544d9d26bce268eca3a5cb4fcc1c46/src/PIL/ImageFile.py#L154-L156

Not saying we shouldn't fix it, merely pointing out that it should not occur in our normal operations.

**Comment by radarhere** [comment]
#8406 and #8408 have been created as possible ways to alleviate this concern.

**Comment by hugovk** [comment]
> ... has SAST security issue

For future reference, please see our security policy on how to report potential security issues:

https://github.com/python-pillow/Pillow?tab=security-ov-file#readme
