### ISSUE TITLE
Possible memory leak

### ISSUE THREAD

**Issue by VoroninArtemii** [python-pillow/Pillow#8412]
There is a possible memory leak:
https://github.com/python-pillow/Pillow/blob/8d0a6d0bbf2de5aeaf172470c568d7596b48acbd/src/libImaging/SgiRleDecode.c#L191-L200
We allocated memory for `ptr` but didn't free it before `return -1;` on line 199.

Found by Linux Verification Center ([portal.linuxtesting.ru](http://portal.linuxtesting.ru/)) with SVACE.
Author A. Voronin.

**Comment by radarhere** [comment]
I've created #8413 to resolve this.
