### ISSUE TITLE
cannot import name '_imagingft' from 'PIL'

### ISSUE THREAD

**Issue by Gamerns10s** [python-pillow/Pillow#8433]
### What did you do?
Running a bit to post images to twitter
### What did you expect to happen?
It should have made images by receiving data from api 
### What actually happened?
It's receiving data but can't make images
### What are your OS, Python and Pillow versions?
Termux with every module at its latest version 
* OS: 
* Python: 
* Pillow: 

```text
Please paste here the output of running:
![IMG_20241001_125812](https://github.com/user-attachments/assets/f1961610-11c4-43b7-90ea-ba68b682c0e4)

python3 -m PIL.report
or
python3 -m PIL --report

Or the output of the following Python code:

from PIL import report
# or
from PIL import features
features.pilinfo(supported_formats=False)
```

```python
code goes here
```
Error 👇👇
![IMG_20240930_125511](https://github.com/user-attachments/assets/8d176b19-4ef9-40a7-b974-9698fce5f869)
Orignal code👇👇
![Screenshot_2024-10-01-12-54-46-922_com termux](https://github.com/user-attachments/assets/14fc8d6e-cd38-4ba9-88b4-470fa55232d4)
![Screenshot_2024-10-01-12-54-56-569_com termux](https://github.com/user-attachments/assets/78fe042b-fe8a-4c64-88fd-fc92e1f35835)
![Screenshot_2024-10-01-12-55-10-225_com termux](https://github.com/user-attachments/assets/f2f9c1e0-6b3e-47dc-b39a-e4a0e9f72f31)
![Screenshot_2024-10-01-12-55-19-797_com termux](https://github.com/user-attachments/assets/63b18164-db80-4476-8c0f-ba9d2429c777)
![Screenshot_2024-10-01-12-55-27-590_com termux](https://github.com/user-attachments/assets/82a0dbeb-cb63-4ed7-90fc-217d8bba639b)

**Comment by radarhere** [comment]
Hi. You do not have FreeType2 support setup for Pillow, on what I believe is your Android device.

I suggest running `apt-get install libfreetype6-dev` and then installing Pillow again.

**Comment by Gamerns10s** [comment]
Pillow was installed automatically because it was mentioned in the requirement file .
Now before running the mentioned command I uninstalled pillow and then run the command you told but it gives me this error
![IMG_20241001_142616](https://github.com/user-attachments/assets/8138c454-da16-4bb3-8e45-d86ebf16cd64)

**Comment by radarhere** [comment]
Ah. Ok, try `apt-get install freetype-dev` instead.

**Comment by Gamerns10s** [comment]
![IMG_20241001_150927](https://github.com/user-attachments/assets/ba1d71c2-fc98-46f4-8e36-71ffedef271a)

**Comment by radarhere** [comment]
Next attempt.
```
apt-get update
apt-get install freetype-dev
python -m pip install Pillow
```

**Comment by Gamerns10s** [comment]
I just uninstalled termux and then reinstalled and cloned the bot once again but still it's the same 
![IMG_20241001_184530](https://github.com/user-attachments/assets/eafd072b-0be5-4003-a79e-d5186a15ac9b)
Mere

**Comment by radarhere** [comment]
Hmm, I think the error message is [actually right.](https://github.com/termux/termux-packages/commit/6e70277fb3fe8e57114ecad786d92a4a2c7726f6#diff-f5b3cb66c0a122542640d16492ee77ee040ddf7c4e7291a87add2943715b1735) Try this?
```
apt-get install freetype
python -m pip install Pillow
```

**Comment by Gamerns10s** [comment]
Freetype was installed but pillow gave another error 
![Screenshot_2024-10-01-19-12-21-150_com termux](https://github.com/user-attachments/assets/a5e902d4-b43b-4d35-992e-3c0f2df5fe90)
![Screenshot_2024-10-01-19-12-32-010_com termux](https://github.com/user-attachments/assets/73780220-b016-46e4-8ed5-92f378f9c15c)
![Screenshot_2024-10-01-19-12-39-982_com termux](https://github.com/user-attachments/assets/1ef96b7f-96ae-4b87-9eaf-149164ca433e)
![Screenshot_2024-10-01-19-12-47-613_com termux](https://github.com/user-attachments/assets/14233bf9-52d4-478e-b8c0-2b9387ab6d0a)

**Comment by radarhere** [comment]
`apt-get install libjpeg-turbo zlib`

**Comment by Gamerns10s** [comment]
It was installed successfully what should I do next

**Comment by Gamerns10s** [comment]
Maybe everything related to pillow is fixed now but got another one which I think is of the main code 
![IMG_20241001_231039](https://github.com/user-attachments/assets/04eb9566-32c1-4625-8610-ca61f6679b32)

**Comment by Yay295** [comment]
That looks like an error in your own code, not Pillow.

**Comment by radarhere** [comment]
It [looks](https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L72-L94) like fortnite-api.com isn't returning the data that the script expects.

If you would like to try and just make this work, you could change line 94 of bot.py to
```python
if i.get('newDisplayAsset') != None:
```

However, there might be a bigger underlying problem that causes other issues as well. I suggest you update your question at https://github.com/FortniteFevers/Fortnite-Shop-Bot/issues/6

**Comment by Gamerns10s** [comment]
This above command didn't worked instead in the line 94 their was an extra space before the last bracket I removed it and that error got fixed but another one came stating about image development 😔

**Comment by Gamerns10s** [comment]
![IMG_20241002_113502](https://github.com/user-attachments/assets/f14c2e31-370d-4a27-b65d-e064ca4c00fe)

**Comment by radarhere** [comment]
The key part of your error is
> image file could not be identified because WEBP support not installed

Install webp, and then install Pillow again.
```
python -m pip uninstall Pillow
apt-get install webp
python -m pip install Pillow
```

**Comment by Gamerns10s** [comment]
![IMG_20241002_164721](https://github.com/user-attachments/assets/6caf3278-a2be-4481-8d7d-9db198c83a4c)

**Comment by radarhere** [comment]
Oh, sorry, libwebp

python -m pip uninstall Pillow
apt-get install libwebp
python -m pip install Pillow

**Comment by Gamerns10s** [comment]
It's already installed

**Comment by Gamerns10s** [comment]
When I tried doing pip install webp 
![Screenshot_2024-10-02-16-55-39-242_com termux](https://github.com/user-attachments/assets/d4f515fa-c1af-4421-9721-44c8225ed721)
![Screenshot_2024-10-02-16-55-46-983_com termux](https://github.com/user-attachments/assets/cb8e9244-0967-4679-84c7-ea9071b1e429)
![Screenshot_2024-10-02-16-55-50-561_com termux](https://github.com/user-attachments/assets/0260d096-53f9-44cc-b9e6-eb52e3988d26)

**Comment by radarhere** [comment]
Ok, if libwebp is installed, then webp/encode.h and libwebp.so or webp.so should exist on your device, it's just that Pillow can't find them. Can you find them?

If you can find webp/encode.h at /opt/local/include for example,
and libwebp.so at /opt/local/lib for example,

then you can run
```
CFLAGS="-L/opt/local/lib -I/opt/local/include" python -m pip install Pillow
```

**Comment by Gamerns10s** [comment]
Thank you so much bro I did the first and the third step you stated and everything is working now Thank you so much brother 😊🙏
