### ISSUE TITLE
Xdg open not available 

### ISSUE THREAD

**Issue by Botgamerns10s** [python-pillow/Pillow#8444]
### What did you do?
Trying to run a bot on render
### What did you expect to happen?
It should open an image and then merge them into one and the final one to be posted on twitter 
### What actually happened?
Getting xdg error and the code stops 
### What are your OS, Python and Pillow versions?
Everything to latest version on Render
* OS: 
* Python: 
* Pillow: 

```text
Please paste here the output of running:

python3 -m PIL.report
or
python3 -m PIL --report

Or the output of the following Python code:

from PIL import report
# or
from PIL import features
features.pilinfo(supported_formats=False)
```

```python
code goes here
```
Orignal code https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/main/bot.py
Error on render
![IMG_20241006_114237](https://github.com/user-attachments/assets/fe4fe50b-89e8-468f-b75e-5534283d1c41)

**Comment by radarhere** [comment]
The code would be trying to open up an image, so that you can see it on your screen. It is running 'xdg-open something.png' on the command line. xdg-open is installed, but it isn't connected to any application.

What application are you expecting to open up with the image?

**Comment by Botgamerns10s** [comment]
Ahh I am not sure but I know this that the main code (which I attached) receives data from an api and saves it into images they it opens another python file which merges them into one in the whole process the image is not displayed to me instead after all the images are merged it is uploaded as a tweet on twitter

**Comment by hugovk** [comment]
It sounds like this is code for a bot running on a server, so there's no point in showing the image to the user. 

I suggest removing the `img.show()`

**Comment by Botgamerns10s** [comment]
Let me try that but I won't be able to check if it's working or not because the bot auto updates at 8 pm et when the shop resets so will update you after that . Also is their anything I can do about this -- UserWarning: Palette images with Transparency expressed in bytes should be converted to RGBA images

**Comment by aclark4life** [comment]
> Palette images with Transparency expressed in bytes should be converted to RGBA images

Convert palette images with transparency expressed in bytes to RGBA images or disable warnings (not sure if we support that?) or redirect `stderr` to `stdout` and `stdout` to `/dev/null`.

**Comment by radarhere** [comment]
> Let me try that

I don't understand where `show()` is being called on a PNG image - the only time https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/main/bot.py calls `show()` [it is on a JPG](https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L259). I thought that you might be saying that tweepy calls it, but I don't see any evidence of Pillow use in their codebase.

Are you just running bot.py, or is there other code?

I think if you would like further assistance with this, and with the UserWarning, it would be help if you could provide tracebacks, so that we can see how your code has reached that point.

> or disable warnings (not sure if we support that?)

No, there's no functionality in Image.py for that. The warning is [straightforward.](https://github.com/python-pillow/Pillow/blob/01bb78a8e7ae7656b5abddd2d9d37f67124f8a3e/src/PIL/Image.py#L1059-L1062)

**Comment by Botgamerns10s** [comment]
The show command is on line 259 in main code
And here is the second python file which is automatically imported to merge the images 
https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/main/merger.py

**Comment by Botgamerns10s** [comment]
![IMG_20241006_233551](https://github.com/user-attachments/assets/eed71cc0-707b-49ec-8840-432fb6aa3555)
If this provides more information

**Comment by hugovk** [comment]
> If this provides more information

Thanks, it does. This is unrelated to Pillow.

You're running with `-W error` which turns warnings into error. Python 3.11 has deprecation warnings about imghdr. You're using Tweepy which uses imghdr. See https://github.com/tweepy/tweepy/issues/2177. You should take this up with Tweepy, don't run with `-W error`, or add an exception for this warning.

**Comment by radarhere** [comment]
> When calling `img.show()` on an image, Pillow converts it to PNG for displaying:

Ah, of course! Thanks.

**Comment by Botgamerns10s** [comment]
Btw guys you can see in the image that some of the items/merged images have a black background but Instead they should have a specific coloured according to their type can you tell me from the mai code where is the colour defined which is making few images with black background. I am new to python and all this stuff and couldn't find a solution on Google etc so thought to ask you guys 😅😅
![IMG_20241008_000509](https://github.com/user-attachments/assets/336c8e4a-cad6-40a8-858c-d3c023024a81)

**Comment by radarhere** [comment]
https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L187-L188 pastes overlay.png, which is the lower translucent section, onto `img`. So the background colour would happen before that.

But before that is just loading images from URLs and pasting them - https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L141-L183

I suggest printing some of those URLs and loading them individually in your browser.

It is possible that the 'black background' images don't actually have a black background, and are just transparent images being pasted onto the already black `img`. In that case, you can set the initial colour of `img` at https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L145 by changing it to `img=Image.new("RGB",(512,512), "#f00")` or whatever you like.

If the images do actually have a black background in the URLs though, then that is more interesting. I could suggest using Pillow to filter out all black pixels, but the foreground of the images also have black in some cases. You could try using [`floodfill()`](https://pillow.readthedocs.io/en/stable/reference/ImageDraw.html#PIL.ImageDraw.floodfill) at the edge of the images, and seeing if that doesn't interfere with the foreground.

**Comment by Botgamerns10s** [comment]
I actually checked the URLs generated by the api which the code is receiving manually but api is sending 2 links for each item, 1 with no background and another with background and the code is picking the one with no background to generate images for (but only for a few items) idk how to make it correct 😭

**Comment by radarhere** [comment]
Are you sure this shouldn't be a question for https://github.com/FortniteFevers/Fortnite-Shop-Bot?

I found that changing https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L145-L146 to
```python
img=Image.new("RGB",(512,512),'#0f0')
img.paste(background, (0, 0), background.convert('RGBA'))
```
making use of the [`paste()`](https://pillow.readthedocs.io/en/stable/reference/Image.html#PIL.Image.Image.paste) `mask` argument, worked to give a green background to some images.

For one of the images that it didn't give a green background to, I found that changing https://github.com/FortniteFevers/Fortnite-Shop-Bot/blob/951d1d7f104aa03c25ffa0961f55dbdf9c9084d1/bot.py#L96-L99 to always use 'OfferImage' fixed it.
```python
url = i['newDisplayAsset']['materialInstances'][0]['images']['OfferImage']
```
That makes sense, that avoiding the 'Background' image stops the image from having a background.

**Comment by Botgamerns10s** [comment]
Okay so sorry for the late reply but the things marked by me are some values which the api gives to make images 
![IMG_20241010_220856](https://github.com/user-attachments/assets/39b01fa0-7a53-49d3-a7e3-68369accbf05)
Here the lines with [renderimage] variables are the ones which are getting images with no/black background and also the api sends another variable 'rarities' which actually decides the color of the background but when I edit the code and add it to the lines with [renderimages] the code gives a string value error . The lines with [materialinstance] and [offerimage] are making images with correct background. I tried adding [materialinstance] and [offerimage] variables to the other lines also but it messes up and the generated images are repeated.
Though I found another code which is totally different but I found this which is preventing it from making images with no background here is a pic of the other code 
![IMG_20241010_220909](https://github.com/user-attachments/assets/19cdbf91-5f11-44a1-8cca-0ae79ff17cd3)

**Comment by radarhere** [comment]
Again, you're not asking questions about how to use Pillow. You're asking questions about how to modify the code at https://github.com/FortniteFevers/Fortnite-Shop-Bot. Users at that repository would be better able to help you than we are - before this conversation, I didn't even know Fortnite had an API.

> when I edit the code and add it to the lines with [renderimages] the code gives a string value error

> I tried adding [materialinstance] and [offerimage] variables to the other lines also but it messes up and the generated images are repeated.

This is hard to debug without knowing exactly what code you wrote. It would also be easier to have the complete script that you are trying to run each time as a text file, rather than portions of it as screenshots.

If you're still just trying to set the background colour for each square, then I don't see what the problem is with the code from my last comment. With the script I'm attaching here, I'm able to get a green background for all of the squares.

[bot.py.zip](https://github.com/user-attachments/files/17335359/bot.py.zip)
<img src="https://github.com/user-attachments/assets/520196a5-dc51-49a8-a570-2bb5b4929031" width="250" />

**Comment by Botgamerns10s** [comment]
Yeah I went out of topic sorry won't ask again actually the person who wrote script wasn't interested in helping and I am new to python all  this so thought to ask you guys sorry for the trouble
