### ISSUE TITLE
Segfault under free-threaded build

### ISSUE THREAD

**Issue by ngoldbaum** [python-pillow/Pillow#8454]
See https://github.com/tonybaloney/pytest-freethreaded/issues/9 where this was discovered and for steps to reproduce.

Ultimately this comes down to the thread safety warnings in the freetype docs for `FT_Face`: https://freetype.org/freetype2/docs/reference/ft2-face_creation.html#ft_face. Somehow an `FT_Face` is being shared across threads in the test scenario linked above.

Ping @lysnikolaou

**Comment by radarhere** [comment]
It's strange that our Ubuntu GitHub Actions free-threaded job doesn't detect this error, isn't it? The error report is on macOS, maybe the error only occurs on that platform.
