### ISSUE TITLE
Is there a way to list file types that support saving with animation?

### ISSUE THREAD

**Issue by BPplays** [python-pillow/Pillow#8503]
is there a way to get a list of file types that support saving with image animation?

**Comment by radarhere** [comment]
If you mean in terms of our documentation, you could go to https://pillow.readthedocs.io/en/stable/handbook/image-file-formats.html and search for 'save_all'.

If you mean programmatically,
```pycon
>>> from PIL import Image
>>> Image.init()
True
>>> Image.SAVE_ALL.keys()
dict_keys(['GIF', 'PNG', 'TIFF', 'MPO', 'PDF', 'WEBP'])
```

**Comment by radarhere** [comment]
Although yes, I am taking 'animation' to simply mean 'multiple images'.

In normal speech, one would not describe PDFs as being animated.

**Comment by BPplays** [comment]
```python
>>> from PIL import Image
>>> Image.init()
True
>>> Image.SAVE_ALL.keys()
dict_keys(['GIF', 'PNG', 'TIFF', 'MPO', 'PDF', 'WEBP'])
```
that worked
⁤
⁤
> Although yes, I am taking 'animation' to simply mean 'multiple images'.
>
> In normal speech, one would not describe PDFs as being animated.

that's fine for my use case
