### ISSUE TITLE
How to detect character shown as box for a font? 

### ISSUE THREAD

**Issue by nissansz** [python-pillow/Pillow#8528]
text = "をも資资儲储議议歷历權权個个堅坚㊽㊾㊿TextInAaBbCcDdEeFfGgHhIi"
![image](https://github.com/user-attachments/assets/966a7abc-9a7c-4402-bfdf-110b74cae997)

**Comment by radarhere** [comment]
See https://github.com/python-pillow/Pillow/issues/5993#issuecomment-1023699805

**Comment by nissansz** [comment]
I tried to add some more backup fonts as family, it works now.
What is the latest version to support font family?

**Comment by radarhere** [comment]
I believe you are talking about `FreeTypeFontFamily` from #6926. That PR hasn't been merged, meaning that you use it at your own risk. If you have questions about it, please ask them in that PR.

**Comment by nissansz** [comment]
https://github.com/nulano/Pillow/actions/runs/10547427520/job/29220095047

I saw python 3.9 supported.
How about 3.8?

**Comment by radarhere** [comment]
Python 3.8 is now EOL - https://devguide.python.org/versions/

So Pillow no longer supports it - see https://pillow.readthedocs.io/en/stable/installation/python-support.html. Pillow 10.4.0 was the last version to support Python 3.8.

**Comment by nissansz** [comment]
ok. Thank you.
