### ISSUE TITLE
How could I let warning be error?

### ISSUE THREAD

**Issue by CoinCheung** [python-pillow/Pillow#8539]
I have plenty of images, so I process them with multi-processing. However, when I run the script, I got the errors like 
```
/opt/miniconda3/envs/py310/lib/python3.10/site-packages/PIL/TiffImagePlugin.py:900: UserWarning: Truncated File Read
  warnings.warn(str(msg))
```

I cannot know which image brings this warning, since it is merely warning. Would you tell me how to make this warning an error so that I can catch it?

By the way, I have already checked the start bytes and end bytes of the image files, there should not be truncated images...

**Comment by radarhere** [comment]
You can add
```python
import warnings
warnings.filterwarnings("error")
```
before you run your code to treat warnings as errors.

**Comment by CoinCheung** [comment]
Thanks, it works for me.
