### ISSUE TITLE
How could I eliminate this error message?

### ISSUE THREAD

**Issue by CoinCheung** [python-pillow/Pillow#8540]
My code is like this:

```python
from PIL import Image
import warnings
warnings.filterwarnings("error")

pth = 'image_013493346.png'
img = Image.open(pth)
img = img.convert('RGB')
img.save('tmp.jpg')
img.close()
```

my PIL version is: 10.4.0, and the image is: 
![image_013493346](https://github.com/user-attachments/assets/80a91d79-edee-4881-b5fe-0bf55b8947a7)

I did not observe same problem with other images, only this one. Is there any problem with this image? How could I avoid this error?

**Comment by radarhere** [comment]
What is the error/warning that you are seeing?

**Comment by CoinCheung** [comment]
@radarhere 
```
Exception ignored in: <_io.FileIO name='image_013493346.png' mode='rb' closefd=True>
Traceback (most recent call last):
  File "/zj_a100/zzy/l5/tmp.py", line 8, in <module>
    img = img.convert('RGB')
ResourceWarning: unclosed file <_io.BufferedReader name='image_013493346.png'>
```

**Comment by radarhere** [comment]
You can change
```python
img = Image.open(pth)
img = img.convert('RGB')
```
to
```python
with Image.open(pth) as img:
    img = img.convert('RGB')
```

You can read more about this at https://pillow.readthedocs.io/en/stable/deprecations.html#image-del

**Comment by CoinCheung** [comment]
Actually, I need to read image, and check it and return the image object to other function. Can the img object live out of the `with` statement?

**Comment by radarhere** [comment]
The context manager of the `with` applies to the initial image. After `img = img.convert('RGB')`, `img` no longer refers to the initial image.

**Comment by CoinCheung** [comment]
Thanks!!
