### ISSUE TITLE
ImportError: Unable to Import 'PIL' in Pillow 11.0.0 on macOS 15.1

### ISSUE THREAD

**Issue by braher** [python-pillow/Pillow#8558]
### What did you do?

I installed Pillow 11.0.0 in a Python virtual environment on macOS 15.1 (24B83) using Visual Studio Code (VSCode). When trying to import `PIL` in a Python script or run `python3 -m PIL --report`, I encountered an ImportError.

### What did you expect to happen?

I expected the `PIL` module to work correctly without any errors and for the `python3 -m PIL --report` command to output detailed information about the Pillow installation.

### What actually happened?

Running `python3 -m PIL --report` resulted in the following traceback:

```pytb
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "/path/to/virtualenv/lib/python3.12/site-packages/PIL/__main__.py", line 5, in <module>
    from .features import pilinfo
  File "/path/to/virtualenv/lib/python3.12/site-packages/PIL/features.py", line 11, in <module>
    from . import Image
  File "/path/to/virtualenv/lib/python3.12/site-packages/PIL/Image.py", line 97, in <module>
    from . import _imaging as core
ImportError: dlopen(/path/to/virtualenv/lib/python3.12/site-packages/PIL/_imaging.cpython-312-darwin.so, 0x0002): symbol not found in flat namespace '_jpeg_resync_to_restart'
```

The `PIL` module also failed to import in Python scripts, displaying a similar ImportError.

### What are your OS, Python, and Pillow versions?

* OS: macOS 15.1 (24B83)
* Python: 3.12
* Pillow: 11.0.0

### Additional Information

The error appears to be related to a missing or incompatible shared library (`_jpeg_resync_to_restart`). Below is the code snippet used for testing:

```python
from PIL import Image

# Sample code to open and display an image
image = Image.open("example.jpg")
image.show()
```

I verified that Pillow was installed correctly using `pip list`. The issue persists despite:

- Reinstalling Pillow with `pip install --force-reinstall Pillow`
- Restarting the IDE and virtual environment
- Ensuring the Python environment is correctly configured

Let me know if further information or logs are needed to debug this issue.

**Comment by radarhere** [comment]
Hi. Could you show the output of `python3 -m pip install --force-reinstall Pillow`? Sometimes people have more than one Python installation, and `pip` by itself can refer to the wrong one - https://snarky.ca/why-you-should-use-python-m-pip/

I wonder if you're installing Pillow from source somehow. I would suggest uninstalling Pillow, making sure that you're getting a `ModuleNotFoundError` to confirm that it is really gone, and then running `python3 -m pip install Pillow --no-binary :all:`.

**Comment by braher** [comment]
> Running

Thank you for your comment! I realized the issue was caused by having the Rosetta option enabled in my terminal, which led to the packages not being found. After disabling Rosetta in the terminal and reinstalling Homebrew, everything started working as expected. Thanks again for your help!
