### ISSUE TITLE
Show breaking changes more prominently in the changelog

### ISSUE THREAD

**Issue by bfontaine** [python-pillow/Pillow#8569]
Hello,
Would it be possible to show breaking changes more prominently in the changelog? For example, there are 50+ items in the changelog of the 11.0.0 release and it’s hard to understand which ones are breaking changes and which are not. It would help to decide if one can upgrade or not.
Thanks.

**Comment by nulano** [comment]
Have you looked at the [release notes](https://pillow.readthedocs.io/en/stable/releasenotes/index.html)? There is a heading for [Backwards Incompatible Changes](https://pillow.readthedocs.io/en/stable/releasenotes/11.0.0.html#backwards-incompatible-changes) under the 11.0.0 release (as well as under other major releases).

**Comment by hugovk** [comment]
We can also adjust the order of categories shown in releases pages like https://github.com/python-pillow/Pillow/releases/tag/11.0.0.

Please see PR https://github.com/python-pillow/Pillow/pull/8570 to adjust how they're shown for _future_ releases.

After merge, we can also manually edit a few older release pages to bring more important things up. No need to do them all.

**Comment by radarhere** [comment]
If you're wondering how you could have found the documentation on your own, both https://pypi.org/project/pillow/ and https://github.com/python-pillow/Pillow have a 'docs' badge and links under 'More Information' to the 'Documentation' in general, and 'Release notes' specifically.

**Comment by bfontaine** [comment]
Thank you. Does it make sense to keep `CHANGES.rst` then? When I see a `CHANGELOG` file or similar, I don’t expect to have to go to the website to find a _better_ changelog; I assume both are the same.

**Comment by hugovk** [comment]
I don't think there's much value in updating `CHANGES.rst` any more, it's tedious to update and is essentially a reverse chronological list of merged PRs.

**Comment by hugovk** [comment]
> After merge, we can also manually edit a few older release pages to bring more important things up. No need to do them all.

I've edited them back to 9.0.0 to put removals and deprecations at the top.

**Comment by radarhere** [comment]
I think CHANGES.rst acts as something halfway between the [GitHub release](https://github.com/python-pillow/Pillow/releases/tag/11.0.0) and the [release notes](https://pillow.readthedocs.io/en/stable/releasenotes/11.0.0.html).

It's a list of pull requests, like the [GitHub release](https://github.com/python-pillow/Pillow/releases/tag/11.0.0),
but it is shorter, a curated list (I think of it as being limited to functional changes), like the [release notes](https://pillow.readthedocs.io/en/stable/releasenotes/11.0.0.html).

If others think that the [GitHub release](https://github.com/python-pillow/Pillow/releases/tag/11.0.0) list makes CHANGES.rst redundant though, I'm willing to go with that. However, I'm not sure that @bfontaine doesn't think that the [GitHub release](https://github.com/python-pillow/Pillow/releases/tag/11.0.0) list should be removed as well?

**Comment by bfontaine** [comment]
> However, I'm not sure that @bfontaine doesn't think that the [GitHub release](https://github.com/python-pillow/Pillow/releases/tag/11.0.0) list should be removed as well?

No, I think it’s fine. If you think it makes sense to keep `CHANGES.rst`, please consider adding a sentence at the top with a link to the detailed release notes.

**Comment by aclark4life** [comment]
Any precedent in other projects for removing CHANGES and/or moving CHANGES to release notes?

**Comment by hugovk** [comment]
In my other projects I generally only use GitHub Releases via Release Drafter. If there was an existing CHANGES (or equivalent) I refer to the GH Releases. I've not had anyone complain about this.

For example:

* https://github.com/termcolor/termcolor/blob/main/CHANGES.md -> https://github.com/termcolor/termcolor/releases
* https://github.com/pylast/pylast/blob/main/CHANGELOG.md -> https://github.com/pylast/pylast/releases
* https://github.com/prettytable/prettytable/blob/main/CHANGELOG.md -> https://github.com/prettytable/prettytable/releases
* https://github.com/python-humanize/humanize/releases

**Comment by mschoettle** [comment]
FWIW, this is how the changes now shows up when receiving a PR from Renovate (screenshot is from a merge request on GitLab):

<img width="461" alt="Image" src="https://github.com/user-attachments/assets/680fd3c2-0fe7-4d1f-ac25-3d45b65b7318" />

I am not sure what it will show for future releases. It's possible that it will fallback to the releases when there is no changelog in the repo (it generally does support releases: https://docs.renovatebot.com/key-concepts/changelogs/).
