### ISSUE TITLE
ImageDraw.Draw.text will cause "OSError: raster overflow" when U+842d using Noto Sans Traditional Chinese

### ISSUE THREAD

**Issue by tyohei** [python-pillow/Pillow#8573]
### What did you do?

Run following code to draw a Chinese character "U+842b" using Noto Sans Traditional Chinese (https://fonts.google.com/noto/specimen/Noto+Sans+TC).

(full code is at the bottom).

```python
draw = ImageDraw.Draw(im)
draw.text(
    xy=char_position,
    text=char,
    font=font,
    fill=char_color,
    anchor='mm')
```

### What did you expect to happen?

Code outputs temporary file name (e.g., `/var/folders/xm/X/T/foo.png`) at stdout and that file displays the character "U+842b" (https://unicode-explorer.com/c/842B).

### What actually happened?

Following error throws:

```
Traceback (most recent call last):
  File "/tmp/src/main.py", line 48, in <module>
    handler(None, None)
  File "/tmp/src/main.py", line 8, in handler
    handler_core()
  File "/tmp/src/main.py", line 36, in handler_core
    draw.text(
  File "/tmp/.venv/lib/python3.12/site-packages/PIL/ImageDraw.py", line 698, in text
    draw_text(ink)
  File "/tmp/.venv/lib/python3.12/site-packages/PIL/ImageDraw.py", line 639, in draw_text
    mask, offset = font.getmask2(  # type: ignore[union-attr,misc]
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/tmp/.venv/lib/python3.12/site-packages/PIL/ImageFont.py", line 639, in getmask2
    return self.font.render(
           ^^^^^^^^^^^^^^^^^
OSError: raster overflow
```

Above error only throws only when I input U+842b.
Other characters, including LGC, and other CJK characters did not (as far as I tried).

I have confirmed that U+842b is drawable with Noto Sans at the Noto Sans type tester: https://fonts.google.com/noto/specimen/Noto+Sans+TC/tester.

### What are your OS, Python and Pillow versions?

* OS: macOS 14.6.1
* Python: 3.12.3 (`Python 3.12.3 (main, Apr 15 2024, 17:43:11) [Clang 17.0.6 ]`)
* Pillow: 11.0.0 (also reproduced at 10.3.0)

```text
--------------------------------------------------------------------
Pillow 11.0.0
Python 3.12.3 (main, Apr 15 2024, 17:43:11) [Clang 17.0.6 ]
--------------------------------------------------------------------
Python executable is /tmp/.venv/bin/python
Environment Python files loaded from /tmp/.venv
System Python files loaded from /Users/tyohei/.rye/py/cpython@3.12.3
--------------------------------------------------------------------
Python Pillow modules loaded from /tmp/.venv/lib/python3.12/site-packages/PIL
Binary Pillow modules loaded from /tmp/.venv/lib/python3.12/site-packages/PIL
--------------------------------------------------------------------
--- PIL CORE support ok, compiled for 11.0.0
--- TKINTER support ok, loaded 8.6
--- FREETYPE2 support ok, loaded 2.13.2
--- LITTLECMS2 support ok, loaded 2.16
--- WEBP support ok, loaded 1.4.0
--- JPEG support ok, compiled for libjpeg-turbo 3.0.4
--- OPENJPEG (JPEG2000) support ok, loaded 2.5.2
--- ZLIB (PNG/ZIP) support ok, loaded 1.3.1
--- LIBTIFF support ok, loaded 4.6.0
*** RAQM (Bidirectional Text) support not installed
*** LIBIMAGEQUANT (Quantization method) support not installed
--- XCB (X protocol) support ok
--------------------------------------------------------------------
```

```python
import pathlib
import tempfile

from PIL import Image, ImageColor, ImageDraw, ImageFont


def handler(event, context):
    handler_core()
    return


def handler_core():
    char = chr(0x842b)

    with tempfile.NamedTemporaryFile(suffix='.png', delete=False) as fp:
        background_size = (512, 512)
        background_color = ImageColor.getrgb('#CD55EC')
        char_size = 255
        char_color = ImageColor.getrgb('#FFFFFF')
        char_position_x = background_size[0]/2
        char_position_y = background_size[1]/2
        char_position = (char_position_x, char_position_y)
        font_path = pathlib.Path.cwd() / 'Noto Sans TC.ttf' 
        font = ImageFont.truetype(font_path, char_size)
        im = Image.new('RGBA', background_size, background_color)
        draw = ImageDraw.Draw(im)

        draw.text(
            xy=char_position,
            text=char,
            font=font,
            fill=char_color,
            anchor='mm')

        im.save(fp, 'PNG')
        print(fp.name)


if __name__ == '__main__':
    handler(None, None)
```

The font file ("Noto Sans TC.ttf") is downloaded by following code:

```bash
curl https://fonts.gstatic.com/s/notosanstc/v35/-nFuOG829Oofr2wohFbTp9ifNAn722rq0MXz70e1_CpOtma3uNQ.ttf -o 'fonts/Noto Sans TC.ttf'
```

**Comment by radarhere** [comment]
Hi. I'm unable to reproduce your problem on my macOS machine.

I can see that you don't have RAQM support. I would suggest installing it to see if that fixes your problem.

Do you use a package manager? If you use MacPorts, you could try `port install libraqm`. If you use Homebrew, you could try `brew install libraqm`.

https://pillow.readthedocs.io/en/stable/installation/building-from-source.html

> To install libraqm on macOS use Homebrew to install its dependencies:
> 
> `brew install freetype harfbuzz fribidi`
> Then see `depends/install_raqm_cmake.sh` to install libraqm.

**Comment by tyohei** [comment]
Thank you.
I will retry it with RAQM support.

**Comment by tyohei** [comment]
After enabling RAQM support, I was able to run the code without error.
Thank you 👍 

Just for you information, even if I enabled RAQM support, the error occured in Amazon Linux 2023.
Below are the envs I tried
* Without RAQM support
    * error in Python 3.10, 3.11, and 3.12
* With RAQM support
    * local macOS (M3) -> ok in 3.10, 3.11, and 3.12
    * Amazon Linux 2 (docker) -> ok in 3.10 and 3.11
    * Amazon Linux 2023 (docker) -> error in 3.11 and 3.

**Comment by radarhere** [comment]
"raster overflow" is actually an error that [comes from FreeType](https://freetype.org/freetype2/docs/reference/ft2-error_code_values.html), one of Pillow's dependencies.

There are a lot of fonts in the world, and some are flawed. It's unfeasible for us to investigate all fonts - so if this works for you in your current environment, then that sounds fine, and I don't think we need to look into this further.

However, if it would be helpful for you to get this working in Amazon Linux 2023, then that is a concrete need, and let us know.

**Comment by tyohei** [comment]
> here are a lot of fonts in the world, and some are flawed.
I see.

Amazon Linux 2023 is not required for my project, so current status is OK for me.

I will close this issue.
