### ISSUE TITLE
Slightly different gray-scaling result

### ISSUE THREAD

**Issue by AlttiRi** [python-pillow/Pillow#8583]
### What did you do?

I do JavaScript library for image hashing, and I compare my results with https://github.com/JohannesBuchner/imagehash.

One of reasons of slightly different results is a different image gray-scaling result while I use the same BT.601 algorithm.
```js
function calculateBT601(i: number) {
    const uint = dw.getUint32(i);
    return ((uint >> 24) & 0xFF) * 0.299
        +  ((uint >> 16) & 0xFF) * 0.587
        +  ((uint >>  8) & 0xFF) * 0.114;
}
```

https://github.com/python-pillow/Pillow/blob/76356c5fe4e02fdf1cb99a00ba731c3ed2d87e52/src/PIL/Image.py#L946-L949

However, my manual python gray-scaling code produces the same result as I get with JS:
```py
array = numpy.asarray(image.convert("RGB"))
gray_array = 0.299 * array[:, :, 0] + 0.587 * array[:, :, 1] + 0.114 * array[:, :, 2]
gray_array = gray_array.astype(numpy.uint8)
image_gray_correct = Image.fromarray(gray_array, mode="L")
image_gray_correct.save("img-out-py/image-py-gray-correct.png", "PNG")
# BTW, it works 15 times slower: 30 ms vs 2 ms (PIL).
```

Here is the full example:
```py
from PIL import Image
import numpy


# https://raw.githubusercontent.com/kryptan/luminance/master/images/magenta-dress.png
imagePath = "magenta-dress.png"

image = Image.open(imagePath)
image.save("img-out-py/image-py-orig.png", "PNG")

image_gray = image.convert("L")
image_gray.save("img-out-py/image-py-gray-pil.png", "PNG")

array = numpy.asarray(image.convert("RGB"))
gray_array = 0.299 * array[:, :, 0] + 0.587 * array[:, :, 1] + 0.114 * array[:, :, 2]
gray_array = gray_array.astype(numpy.uint8)
image_gray_correct = Image.fromarray(gray_array, mode="L")
image_gray_correct.save("img-out-py/image-py-gray-correct.png", "PNG")

a = numpy.sum(numpy.asarray(image_gray.convert("RGBA")))
b = numpy.sum(numpy.asarray(image_gray_correct.convert("RGBA")))
print(a)  # 1528790073
print(b)  # 1527351837

# compare only 1 channel
a = (a - 255 * image.width * image.height) / 3
b = (b - 255 * image.width * image.height) / 3
# or
# a = numpy.sum(numpy.asarray(image_gray.convert("L")))
# b = numpy.sum(numpy.asarray(image_gray_correct.convert("L")))

print(abs((100 - a / (b / 100))), "%") # 0.13447775922709582 %

```

### What did you expect to happen?

The results are no different.

### What actually happened?

The PIL result differs by 0.134 %.

### What are your OS, Python and Pillow versions?

* OS: Windows 10
* Python: 3.12.4
* Pillow: 11.0.0

**Comment by wiredfool** [comment]
I suspect that you're not explicitly dealing with rounding in your calculations.

**Comment by AlttiRi** [comment]
I just followed the formula from the docs [ `L = R * 299/1000 + G * 587/1000 + B * 114/1000`](https://github.com/python-pillow/Pillow/blob/76356c5fe4e02fdf1cb99a00ba731c3ed2d87e52/src/PIL/Image.py#L949).

Yeah, with `Math.round` the result is almost as PIL's one. However, not the same.

1528791063 vs 1528790073 (diff 990) with `Math.round`.
1527351837 vs 1528790073 (diff 1438236) without `Math.round`.

**Comment by AlttiRi** [comment]
Checked it once more.

Using `round` decreases the diff from `1438236` to `990`.

Now I see that PIL for number ends with `.5` uses `floor`:
- `37  * 0.299 +  25 * 0.587  + 33 * 0.114` (`29.5`) PIL' result is `29`
- `159 * 0.299 + 103 * 0.587  + 57 * 0.114` (`114.5`) PIL' result is `114`
- `187 * 0.299 + 141 * 0.587 + 130 * 0.114` (`153.5`) PIL' result is `153`

I added extra `if`:
```js
if (result % 1 === 0.5) {
    return Math.floor(result);
}
```

However, it only decreased the diff to `111`.

For:
- `242 * 0.299 + 254 * 0.587 + 246 * 0.114` (`249.5`) PIL' result is `250`
- `240 * 0.299 + 252 * 0.587 + 244 * 0.114` (`247.49999999999997`) PIL' result is `248`
- `121 * 0.299 +   3 * 0.587 +  40 * 0.114` (`42.50000000000001`) PIL' result is `42`

---

Even with this:
```js
const result = (
       ((uint >> 24) & 0xFF) * 299
    +  ((uint >> 16) & 0xFF) * 587
    +  ((uint >>  8) & 0xFF) * 114) / 1000;

if (result % 1 === 0.5) {
    return Math.floor(result);
}
return Math.round(result);
```
The diff is `126` and some results are strange:
- `(242 * 299 + 254 * 587 + 246 * 114) / 1000)` (`249.5`) -> `250`
- `( 11 * 299 +  23 * 587 +  15 * 114) / 1000)` (`18.5`) -> `19`
- `( 46 * 299 +  58 * 587 +  50 * 114) / 1000)` (`53.5`)   ->  `54`

PIL _sometimes_ uses `ceil` for `.5`.

---

It's strange that I can't reproduce the result of
https://github.com/python-pillow/Pillow/blob/76356c5fe4e02fdf1cb99a00ba731c3ed2d87e52/src/libImaging/Convert.c#L43

**Comment by wiredfool** [comment]
Sorry, memory of rounding wasn't right, the conversion from RGB is using the next line:

`#define L24(rgb) ((rgb)[0] * 19595 + (rgb)[1] * 38470 + (rgb)[2] * 7471 + 0x8000)`

and 
`        *out++ = L24(in) >> 16;`

So it's a bit shift over, with an effective bias of .5, and there's no divide by 1000 in it, all integer multiplication. 

https://github.com/python-pillow/Pillow/blob/76356c5fe4e02fdf1cb99a00ba731c3ed2d87e52/src/libImaging/Convert.c#L230

I think what's going on here is that the L conversion returns an integer value that's  65000 * the L value + 32k, which is then bitshifted 16, or divide by 65536.

So there'a potential of ~ 500 in 65k error, or about 2 levels for all white. (255*1000*65 + 0x8000) >> 16 = 0xFD

**Comment by AlttiRi** [comment]
I have reproduced it. 
No rounding need, just only the correct formula.

```js
const uint = dw.getUint32(i);
return (((uint >> 24) & 0xFF) * 19595
    +   ((uint >> 16) & 0xFF) * 38470
    +   ((uint >>  8) & 0xFF) *  7471
    + 0x8000) >> 16; // "0x8000" === "1 << 15" === 32768
```

Yeah, it works faster than `R * 0.299 +  G * 0.587 +  B * 0.114` and `(R * 299 +  G * 587 +  B * 114) / 1000`.
As I wrote in the first message, the result differs by only 0.13 %.

**Comment by wiredfool** [comment]
Sorry, was wrong with the factor, it's 65 and a bit, so it does go full range. My calculator must have been in integer mode.

**Comment by AlttiRi** [comment]
If anyone is interested, then the more correct difference between the "optimized version"
- and "sum version" (`R*0.299+G*0.587+B*0.114`) is 0.057 %,
- and "divide version" (`(R*299+G*587+B*114)/1000`) is 0.053 %.
```js
let a_pos = 0, a_neg = 0, b_neg = 0, b_pos = 0;
const max_value = 0xFFFFFF; // 3 "RGB" channels without "A"
const to = max_value + 1;
for (let uint = 0; uint < to; uint++) {
    const sum = ((uint >> 16) & 0xFF) * 0.299
             +  ((uint >>  8) & 0xFF) * 0.587
             +  ( uint        & 0xFF) * 0.114
             + 0.5 << 0; // round
    const div = (
                ((uint >> 16) & 0xFF) * 299
             +  ((uint >>  8) & 0xFF) * 587
             +  ( uint        & 0xFF) * 114) / 1000
             + 0.5 << 0; // round
    const optimized = (
                ((uint >> 16) & 0xFF) * 19595
            +   ((uint >>  8) & 0xFF) * 38470
            +   ( uint        & 0xFF) *  7471
            + 0x8000) >> 16;
    if (optimized > sum) {
        a_pos++;
    } else if (optimized < sum) {
        a_neg++;
    }
    if (optimized > div) {
        b_pos++;
    } else if (optimized < div) {
        b_neg++;
    }
    if (Math.abs(optimized - sum) > 1 || Math.abs(optimized - div) > 1) {
        console.log(optimized, sum, div); // never
    }
}
console.log(max_value);
console.log(a_pos, a_neg);
console.log(b_pos, b_neg);
console.log((a_pos + a_neg) / (max_value / 100), "%");
console.log((b_pos + b_neg) / (max_value / 100), "%");
// 16777215
// 2463 7253
// 393 8647
// 0.05791187631558635 %
// 0.053882602088606485 %
```
