### ISSUE TITLE
Do not renew python-pillow.org domain

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#8585]
Anyone mind if a don't renew the python-pillow.org and we move that website to python-pillow.github.io? I used to like having the domain available for email, but I think we can safely rely on `security@tidelift.com` for the foreseeable future. Expiration date is 2 months from now.

**Comment by hugovk** [comment]
Sure, fine with me.

Let's get https://python-pillow.github.io working already now and start updating links.

**Comment by hugovk** [comment]
@aclark4life Please could you update the URL at the top right of https://github.com/python-pillow/Pillow?

I've updated the link in Mastodon profile: https://fosstodon.org/@pillow

**Comment by aclark4life** [comment]
Done, thanks!

**Comment by dacort** [comment]
Did something happen to the domain already? This is what it currently looks like ...

![image](https://github.com/user-attachments/assets/5e0bfa29-e218-4815-b591-e4ffbf97ba2f)

Seems rather confusing.

**Comment by aclark4life** [comment]
Thanks for the info! Fixing …

**Comment by aclark4life** [comment]
Fixed

<img width="589" alt="Screenshot 2024-12-09 at 8 01 49 PM" src="https://github.com/user-attachments/assets/b01e669a-9cf7-4d55-b9f9-b7843a3b3629">

**Comment by dacort** [comment]
🙏

**Comment by aclark4life** [comment]
I thought about that, but not sure there's a compelling attack vector there. Maybe @sethmlarson knows more.

**Comment by ljharb** [comment]
There’s a reputational risk, even if nothing else

**Comment by sethmlarson** [comment]
My default recommendation around domains is to keep them forever, once they are let go they are basically gone and can be used for any sorts of nefarious things.

For example, Notepad++ has had fake websites hosted to try to persuade users to download and install incorrect things and send money to who-knows-where. Now imagine that happening for the previously official domain.

If you previously relied on the domain for email that's important too. Whoever buys the domain might be receiving security reports from outdated sources. Unlikely, but not impossible.
