### ISSUE TITLE
ImportError: cannot import name '_imaging' from 'PIL'  running Python 3.13t

### ISSUE THREAD

**Issue by tagelabs** [python-pillow/Pillow#8589]
### What did you do?
tried running the following single line of code:
`from PIL import Image`

### What happened?
Threw the following error:
`ImportError: cannot import name '_imaging' from 'PIL'`

### What are your OS, Python and Pillow versions?

* OS: Windows 11 Pro
* Python:  3.13.1 (free-threaded version)
* Pillow: 11.0.0

```text
Please paste here the output of running:

python3 -m PIL.report
or
python3 -m PIL --report

Or the output of the following Python code:

from PIL import report
# or
from PIL import features
features.pilinfo(supported_formats=False)
```
```pytb
Traceback (most recent call last):
  File "c:\Users\jrtag\Documents\GitHub\sensomatic\Desktop App\testing.py", line 1, in <module>
    from PIL import report
  File "C:\Users\jrtag\AppData\Local\Programs\Python\Python313\Lib\site-packages\PIL\report.py", line 3, in <module>
    from .features import pilinfo
  File "C:\Users\jrtag\AppData\Local\Programs\Python\Python313\Lib\site-packages\PIL\features.py", line 11, in <module>
    from . import Image
  File "C:\Users\jrtag\AppData\Local\Programs\Python\Python313\Lib\site-packages\PIL\Image.py", line 97, in <module>
    from . import _imaging as core
ImportError: cannot import name '_imaging' from 'PIL'
```

```python
from PIL import report
```
this is the only version of python I have installed on my system, and it is a clean install, pip is up to date as well.
Selecting the non free-threaded version of python 3.13 allows me to import without issue.

Installing the pillow 11.1.0.dev0 nightly build produces all the same results

I have also tried completely wiping the Python 3.13.1 install, and doing a clean install with 3.13.0 and installing Pillow version 11.0.0, all to the same result....

![Screenshot 2024-12-07 230007](https://github.com/user-attachments/assets/f41e1994-6285-4e5a-b8f3-784df2e1ed39)

**Comment by radarhere** [comment]
Hi. How did you install Pillow?

My recommendation would be to
1. uninstall Pillow - `C:/Users/jrtag/AppData/Local/Programs/Python/Python313/python3.13t.exe -m pip uninstall Pillow`
2. check that Pillow is no longer installed by trying to `import PIL` and making sure you see a `ModuleNotFoundError`.
3. re-install Pillow with `C:/Users/jrtag/AppData/Local/Programs/Python/Python313/python3.13t.exe -m pip install Pillow`

**Comment by tagelabs** [comment]
I had originally installed it by running `pip install Pillow`
It seems to have been an install issue though, as the instructions you provided have resolve my issues.
I greatly appreciate the help!
