### ISSUE TITLE
ZeroDivisionError occurs when calling Image.open

### ISSUE THREAD

**Issue by gabe-sherman** [python-pillow/Pillow#8597]
A ZeroDivisionError occurs at line 105 in WmfImagePlugin.py when the below code is run. A check to `self._inch` is missed, resulting in a ZeroDivisionError rather than an `"Unsupported file format"` message.
```python
import PIL.Image as Im
import io

data = io.BytesIO(b'\xd7\xcd\xc6\x9a\x00\x00\xff\xff\xff\xff\x00\x00\x00<\x00\x00')
Im.open(data)
```

Version:
```
pip show pillow
Name: pillow
Version: 11.1.0.dev0
```

Trace:
```pytb
Traceback (most recent call last):
  File "rep.py", line 5, in <module>
    Im.open(data)
  File "python3.9/site-packages/PIL/Image.py", line 3511, in open
    im = _open_core(
  File "python3.9/site-packages/PIL/Image.py", line 3494, in _open_core
    im = factory(fp, filename)
  File "python3.9/site-packages/PIL/ImageFile.py", line 144, in __init__
    self._open()
  File "python3.9/site-packages/PIL/WmfImagePlugin.py", line 105, in _open
    (x1 - x0) * self.info["dpi"] // self._inch,
ZeroDivisionError: integer division or modulo by zero
```

**Comment by radarhere** [comment]
Looking at [the code](https://github.com/python-pillow/Pillow/blob/bce51744f63f6bfd77c618fab7501178652a04a2/src/PIL/WmfImagePlugin.py#L90-L143), "Unsupported file format" is intended to occur when an image cannot be identified as either a WMF or EMF.

That isn't the case with the situation you're describing. The file is identified as a WMF, it's just that the number of logical units per inch is zero.

If I suggest raising an "Invalid inch" ValueError instead, how does that sound?

**Comment by gabe-sherman** [comment]
I think that suggestion makes sense, thanks!

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/8600
