### ISSUE TITLE
'IOError: cannot identify image file' when opening .pbm, .pgm and .ppm in an ascii file encoding

### ISSUE THREAD

**Issue by aclel** [python-pillow/Pillow#860]
Netpbm file formats can be encoded in either binary or ASCII. When opening a .pbm, .pgm or .ppm in the ASCII format, the following error is thrown:

```
IOError: cannot identify image file
```

All Netpbm formats in binary encoding open perfectly.

**Comment by Adityashaw** [comment]
> Looks like Pillow only supports the binary versions of the PPM formats, P4-6, not the ascii versions: P1-3.
> 
> See https://github.com/python-pillow/Pillow/blob/master/src/PIL/PpmImagePlugin.py#L27

Will `ascii` format be ever supported?
