### ISSUE TITLE
Exif: MakerNote enums spelled differently

### ISSUE THREAD

**Issue by mixmastamyk** [python-pillow/Pillow#8614]
https://github.com/radarhere/Pillow/blob/main/src/PIL/ExifTags.py#L156

    MakerNote = 0x927C

https://github.com/radarhere/Pillow/blob/main/src/PIL/ExifTags.py#L355

    Makernote = 37500

These names should be consistent.  Also, some values specified in hex and others in decimal is also a bit messy, though merely cosmetic.

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/8615 to resolve this.

Also, just as an aside - you've linked to my fork, rather than to this repository.

**Comment by mixmastamyk** [comment]
Thanks.  However, it would probably be good to carry the old spelling for a while, marked deprecated as a courtesy.  Otherwise will break some users.  Unless there is a big breaking release coming up.

**Comment by radarhere** [comment]
I've created https://github.com/python-pillow/Pillow/pull/8629
