### ISSUE TITLE
Can template matching be achieved?

### ISSUE THREAD

**Issue by monkeycc** [python-pillow/Pillow#8621]
![微信截图_20241224154158](https://github.com/user-attachments/assets/5617ce42-db3d-4873-aa82-b9b2c1be68fc)
Two pictures

Crop the rectangular frame of image A to produce the product
B picture needs to identify similar products and frame them

**Comment by radarhere** [comment]
You're saying that you have the image on the right without the pink rectangle, and you'd like to add the pink rectangle into the image, based on the image on the left?

Yes, that should be possible. Could you attach the original two images though? Without them, there is a chance that any code we might provide for you won't work the first time.

**Comment by monkeycc** [comment]
Need to find the corresponding product:
![image](https://github.com/user-attachments/assets/84475d6e-c468-4cad-982f-2f78e7753aff)
![94c303c3d21eb9955e77785f4e9936dd](https://github.com/user-attachments/assets/d96c868f-6442-45d6-8cb8-52776c7ed324)


Need to find all identical products:
![image](https://github.com/user-attachments/assets/7d512fc4-ceeb-46ab-9ae7-53e07fda914d)
![349293-20210403230217832-1802403393](https://github.com/user-attachments/assets/5a750e1d-33d4-4832-a372-a140d5b9dd3a)

![image](https://github.com/user-attachments/assets/2c11d948-d95d-4306-b7b5-7494640f25dc)
![349293-20210403230029064-927228912](https://github.com/user-attachments/assets/a2bbd938-8bda-4645-a5f2-c5671043d6fd)

Thank you for your help
I just need to achieve a similar effect

The OpenCV algorithm is too old
Not supporting complex application scenarios

**Comment by radarhere** [comment]
For the images you've supplied, you're interested in finding a match for the first image inside the second image,
potentially at different rotations,
and when the match is at a different size?

Pillow doesn't offer a high-level API for this, no.

Pillow can rotate, resize and crop images, and compare images for similarity, but were you to try this with Pillow, I imagine it would require
a) writing logic to split up the second image into individual shapes
b) rotating the shapes until they fit the ratio of the first image
c) resizing the shape to fit the size of the first image
d) comparing the shape to the first image

Perhaps take a look at https://docs.opencv.org/4.x/d4/dc6/tutorial_py_template_matching.html for OpenCV?

**Comment by monkeycc** [comment]
Thanks for your help
Thank you for providing the idea

OpenCV does not support rotation angles
And it's not easy to find the object

If encountering code that can be solved
I will put it here
