### ISSUE TITLE
Likely incorrect tk include detection

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#876]
https://github.com/python-pillow/Pillow/blob/master/setup.py#L343

Doesn't catch /usr/local/include, also doesn't look in */tk[version] for the header.

**Comment by aclark4life** [comment]
I don't think either of these assertions are true. I'd guess it was fixed after this ticket was opened, but that does not appear to be the case. In https://github.com/python-pillow/Pillow/blob/master/setup.py#L344 TCL_VERSION is appended and in https://github.com/python-pillow/Pillow/blob/master/setup.py#L350 /usr/local/include is included (oh!) regardless of the condition of ``_tkinter`` i.e. it's always included.
