### ISSUE TITLE
OSError: cannot identify image file 'xxxxx.jpg'

### ISSUE THREAD

**Issue by guardrex** [python-pillow/Pillow#878]
I'm getting an intermittent issue while processing JPEG files.

System: Raspberry Pi
OS: Arch Linux
Python: 3.4.1
Pillow: 2.5.3

Exception:

```
File "/usr/lib/python3.4/site-package/PIL/Image.py", line 2256, in open
% (filename if filename else fp))
OSError: cannot identify image file 'xxxxx.jpg'
```

My image files are saved out of PiCamera; however, the same issue also crops up with images that Pillow saves. I'm processing images in a loop. There is a two-second delay between processing each image. It's not related to memory: I monitored available memory, and that was stable before and after the exception.

After processing a few images, the exception is thrown, then my Pillow code simply re-processes (re-opens) the same image and Pillow opens it and processes it normally ... same file ... no changes ... just two seconds later after the exception is thrown. Therefore, it seems something is amiss in the library.

**Comment by jcavejr** [comment]
Sorry that I'm commenting on this so late. I'm wondering if you could share your solution to this issue? I'm on a raspberry pi getting the same error. I've tried every solution I've read so far, but I'm leaning towards my issue being the same as yours. Only problem is I'm not sure how to go about fixing it. Thanks in advance for any replies!
