### ISSUE TITLE
No way to shift the image

### ISSUE THREAD

**Issue by kernc** [python-pillow/Pillow#888]
Say I'd want to move the image 200px to the left, with the left 200px wide stack of pixels moved all the way across to the right (e.g. a shift, a cirular move operation). How would I do it efficiently and where would be the best place to contrib this, `ImageOps.shift()`? Something like `Image.crop()` but allowing `right < left` on the bounding box, etc.

**Comment by vstadnytskyi** [comment]
Is there a way to shift by a float offset?

**Comment by kernc** [comment]
@vstadnytskyi Sure, to shift the image to the left by 30%:
```py
PIL.ImageChops.offset(im, xoffset=int(-im.width * .3), yoffset=0)
```

**Comment by vstadnytskyi** [comment]
> @vstadnytskyi Sure, to shift the image to the left by 30%:
> 
> ```python
> PIL.ImageChops.offset(im, xoffset=int(-im.width * .3), yoffset=0)
> ```

I meant by fraction of a pixel.
