### ISSUE TITLE
Add functions to Image: static fromqimage and fromqpixmap; methods toqimage and toqpixmap

### ISSUE THREAD

**Issue by rominf** [python-pillow/Pillow#897]
I'm writing Qt application that needs diff feature of Pillow `Image`. So, I need to convert `QPixmap` to `Image` and and vice versa.

I've found existing class `ImageQt`. But I don't like it. It contains just one `__init__` function. In this case using class is not required. I would say it's misleading.

I'm gonna prepare functions for Image class: static `fromqimage` and `fromqpixmap`; methods `toqimage` and `toqpixmap`.

Those functions would be defined only if PyQt is installed.

What do you think?

PS: I would like to change `from*` functions to `from_*` due readability. But I want to be consistent. If you like `from*` more, I would write `fromqpixmap`, etc.

**Comment by aclark4life** [comment]
Looks like this was shipped in 2.7.0

**Comment by hugovk** [comment]
It wasn't shipped in 2.7.0: its PR is still open but not ready for merge.
https://github.com/python-pillow/Pillow/pull/905

**Comment by aclark4life** [comment]
Thanks

**Comment by radarhere** [comment]
This change has been merged with PR #1217 and so this issue can be closed.
