### ISSUE TITLE
Consider changing standard test image size

### ISSUE THREAD

**Issue by wiredfool** [python-pillow/Pillow#947]
I know we've just gone through a huge test update, but I think we should change the test image a bit more. (or at least, test with odd image sizes)

We're currently testing with a 128x128 image. There are at least 2 classes of (potential) bug that aren't hit by this:
- Always getting the x,y order right, and checking the right bounds. If they're the same, we're never going to notice. If we're doing it backwards and the sizes are different, something should error.
- There are some line size and padding code bits that are tickled with non aligned bits*samples*pixels. 

I think it might be worth cropping the output of hopper to something like (121,127) and see what fails.

It's likely that a lot of the comparisons to the various hopper.* images would fail. It's probably not worth a changes that invalidates all of them.

Thoughts?

**Comment by aclark4life** [comment]
Status? Looks like maybe this was merged. Please reopen if still an issue.

**Comment by hugovk** [comment]
Re-opening. This was some testing that identified a few things that still need addressing.

**Comment by aclark4life** [comment]
Roger that, thanks

**Comment by hugovk** [comment]
I've created PR https://github.com/python-pillow/Pillow/pull/1469 with the [suggestions above](https://github.com/python-pillow/Pillow/issues/947#issuecomment-61641247), but let's close this whether that PR makes it or not.
