### ISSUE TITLE
Release 2.7.0 on January 1, 2015

### ISSUE THREAD

**Issue by aclark4life** [python-pillow/Pillow#949]
OK I'm dropping off again, please use @aclark4life if you need anything or email aclark@aclark.net. Thank you :beers:

**Comment by wiredfool** [comment]
I've got to say, the existing one doesn't exactly look right. But it's not like it's getting tested on travis, since  Ubuntu 12.04 ships with scipy 0.9, which doesn't even have the imresize method. Not that we're installing it to find that out.

**Comment by wiredfool** [comment]
OK, I found these -- they're from the scipy tests, and were added after the last release.

**Comment by wiredfool** [comment]
The scipy change appears to be because of a change in the way that image resizing works. The new version looks more reasonable to me, which fits with the conclusions that we've had from the changes in the resizing code this iteration.

**Comment by wiredfool** [comment]
@cgohlke Check master now. 

Also as a heads up, I'm planning on a 2.6.2 release tomorrow with the PNG dos fix. When the tests pass on my branch, I'll push the last changes in. (it's 2.6.1 + png dos fix + pypy2.4 regression fix + reverting the test changes on for pypy2.4)

**Comment by wiredfool** [comment]
Ok, versions bumped. 12 hours or so till I tag & push.

**Comment by cgohlke** [comment]
Looks good. All test pass.

**Comment by wiredfool** [comment]
Ok, 2.7.0 and 2.6.2 are tagged and released.

**Comment by aclark4life** [comment]
Great, thanks @wiredfool @hugovk @cgohlke et al. Happy new year!

**Comment by cgohlke** [comment]
Windows binaries are at
<http://www.lfd.uci.edu/~gohlke/download/Pillow-2.7.0.win-dist.zip>
<http://www.lfd.uci.edu/~gohlke/download/Pillow-2.6.2.win-dist.zip>

**Comment by aclark4life** [comment]
Uploading…

**Comment by aclark4life** [comment]
Done, thanks (Twine now supports exe!!!)

**Comment by wiredfool** [comment]
You beat me to it.

also yay about exes.

**Comment by wiredfool** [comment]
OSX binaries are up now.

**Comment by stonebig** [comment]
hi,

Excuse-me, if I'm not wrong, with latest @cgohlke binaries for pillow2.7.0 and scipy0.14.1, I have still the issue on windows 64bit python3.4.2.... What detail can I have missed ?

````
raise AssertionError(msg)
AssertionError: 
Arrays are not equal

(mismatch 75.0%)
 x: array([[ 1.  ,  1.25,  1.75,  2.  ],
       [ 1.5 ,  1.75,  2.25,  2.5 ],
       [ 2.5 ,  2.75,  3.25,  3.5 ],
       [ 3.  ,  3.25,  3.75,  4.  ]], dtype=float32)
 y: array([[ 1. ,  1. ,  1.5,  2. ],
       [ 1. ,  1. ,  1.5,  2. ],
       [ 2. ,  2. ,  2.5,  3. ],
       [ 3. ,  3. ,  3.5,  4. ]], dtype=float32)
````

**Comment by hugovk** [comment]
@stonebig Which issue are you referring to? Was there a bug reported here about it?

**Comment by stonebig** [comment]
the effect is apparently the same FAIL  @cgohlke complained about https://github.com/python-pillow/Pillow/issues/949#issuecomment-68474924
when doing:
````
import scipy;scipy.test()
````

**Comment by aclark4life** [comment]
@stonebig Can you please open a new issue to report this problem? Thanks

**Comment by homm** [comment]
@stonebig This is obviously very bad scipy developers idea to test third-party functionality in own unit tests. This is [wrong result](https://github.com/scipy/scipy/blob/master/scipy/misc/tests/test_pilutil.py#L48) of bilinear interpolation produced by previous Pillow and PIL version. This is definitely scipy issue, not Pillow.

**Comment by stonebig** [comment]
@aclark4life done ! https://github.com/python-pillow/Pillow/issues/1074
