### ISSUE TITLE
Cannot save .TIF file with tag 347 (JPEGTables)

### ISSUE THREAD

**Issue by hugovk** [python-pillow/Pillow#975]
There's a problem saving a TIFF with a JPEGTables tag.

To reproduce:

```python
    def test_save_tiff_with_jpegtables(self):
        # Arrange
        outfile = self.tempfile("temp.tif")

        # Created with ImageMagick: convert hopper.jpg hopper_jpg.tif
        # Contains JPEGTables (347) tag
        infile = "Tests/images/hopper_jpg.tif"
        im = Image.open(infile)

        # Act / Assert
        # Should not raise UnicodeDecodeError or anything else
        im.save(outfile)
```

Branch with failing test:
https://github.com/hugovk/Pillow/compare/tiff_jpegtables

Fails for Py 2.6, 2.7, 3.4, PyPy and PyPy3 (passes for 3.2 and 3.3):
https://travis-ci.org/hugovk/Pillow/builds/39065110

**Comment by hugovk** [comment]
Merging with master gives similar results, except 3.4 now passes:
https://travis-ci.org/hugovk/Pillow/builds/65927635

**Comment by hugovk** [comment]
Leave it for long enough and it'll fix itself! 

After merging with master it now all passes.
https://travis-ci.org/hugovk/Pillow/builds/120480498

**Comment by wiredfool** [comment]
I'm going to guess that the tag is stripped, especially from a libtiff save

**Comment by hugovk** [comment]
Do we still want the test, in this form or another?

**Comment by wiredfool** [comment]
Yeah, I think so, It's certainly related to the tiff metadata mess.

**Comment by hugovk** [comment]
See PR https://github.com/python-pillow/Pillow/pull/1804.
