### ISSUE TITLE
Add icns save support if "iconutil" exist in OS X

### ISSUE THREAD

**Issue by exherb** [python-pillow/Pillow#998]
Is this a good idea?

**Comment by aclark4life** [comment]
Maybe? Please send a PR and we'll review.

**Comment by radarhere** [comment]
As far as I can see, iconutil always exists in OS X, so checking for OS X is sufficient. If I'm wrong, feel free to correct me.

**Comment by exherb** [comment]
ok, I will send a PR today

**Comment by radarhere** [comment]
I've already created a PR - #1185.

If you feel like you want to do something different though, that's fine, just letting you know.

**Comment by exherb** [comment]
@radarhere cool, I think yours is better, so I will close mine.
